Repository openshift/openshift-docs, pull requests merged in 2018-09, with the labels that each got.

#11801 add fatal error log file
  using_images/other_images/jenkins.adoc
Labels: branch/enterprise-3.11, size/XS

#11670 Added azure content from ref arch
  install_config/configuring_azure.adoc
  install_config/topics/configuring_azure_authorization.adoc
  install_config/topics/configuring_azure_load_balancer.adoc
  install_config/topics/configuring_azure_objects.adoc
  install_config/topics/configuring_azure_using_ansible.adoc
  install_config/topics/configuring_for_azure_registry.adoc
  install_config/topics/configuring_for_azure_storage.adoc
  install_config/topics/example_azure_inventory_file.adoc
  install_config/topics/manually_configuring_for_azure.adoc
Labels: Peer Review Needed, branch/enterprise-3.10, branch/enterprise-3.11, size/XXL

#11892 adding user story for using cookies to keep route state
  _topic_map.yml
  modules/annotating-a-route-with-a-cookie-name.adoc
  networking/using-cookies-to-keep-route-statefulness.adoc
Labels: size/M

#11895 Create sym links for all modules + added a script for future
  applications_and_projects/modules
  authentication/modules
  backup_and_restore/modules
  builds_and_deployments/modules
  cloud_providers/modules
  contributing_to_docs/modules
  create_sum_link.sh
  images/modules
  installation/modules
  logging/modules
  masters/modules
  metrics/modules
  mod_docs_guide/modules
  modules/modules
  networking/modules
  nodes/modules
  operators/modules
  planning/modules
  registry/modules
  router/modules
  scalability_and_performance/modules
  storage/modules
  upgrading/modules
  users_and_roles/modules
Labels: size/M

#11730 bug 1616435 custom CA can contain only one cert
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#11900 [enterprise-3.10] bug 1616435 custom CA can contain only one cert
  install_config/redeploying_certificates.adoc
Labels: size/M

#11901 [enterprise-3.9] bug 1616435 custom CA can contain only one cert
  install_config/redeploying_certificates.adoc
Labels: size/M

#11576 [enterprise-3.5] Bug 1458025 Enable Ansible Logging
  scaling_performance/install_practices.adoc
Labels: size/S

#11577 [enterprise-3.6] Bug 1458025 Enable Ansible Logging
  scaling_performance/install_practices.adoc
Labels: size/S

#11917 Update f5_big_ip.adoc-- fix typos and standardize naming convention
  architecture/topics/f5_big_ip.adoc
Labels: needs-ok-to-test, size/M

#10536 [3.11] Pod Retention for Jenkins Pipeline Builds
  using_images/other_images/jenkins.adoc
  using_images/other_images/jenkins_slaves.adoc
Labels: branch/enterprise-3.11, size/M

#11394 Bug 1554244 Addition example for throttling logs
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, lgtm, size/S

#11816 Eviction settings cause false positive diskpressure and evict the pods
  admin_guide/out_of_resource_handling.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11936 Fix some typos
  admin_guide/high_availability.adoc
  admin_guide/managing_pods.adoc
  admin_guide/scheduling/descheduler.adoc
  architecture/additional_concepts/storage.adoc
  architecture/topics/router_sharding.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/verifying_mtu.adoc
  dev_guide/projected_volumes.adoc
Labels: size/S

#11937 [enterprise-3.10] Fix some typos
  admin_guide/high_availability.adoc
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/topics/router_sharding.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/verifying_mtu.adoc
Labels: size/S

#11938 [enterprise-3.11] Fix some typos
  admin_guide/high_availability.adoc
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/topics/router_sharding.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/verifying_mtu.adoc
Labels: size/S

#11929 Added ifexists parameter to Cluster Loader content
  scaling_performance/optimizing_compute_resources.adoc
  scaling_performance/using_cluster_loader.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11942 [enterprise-3.7]Added ifexists parameter to Cluster Loader content
  scaling_performance/optimizing_compute_resources.adoc
  scaling_performance/using_cluster_loader.adoc
Labels: size/S

#11922 Document admin console inventory variables
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.11, size/M

#11525 Fixed env var name. Added namespace selector
  day_two_guide/topics/verifying_mtu.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11851 Adding GHE as an auth provider
  install_config/configuring_authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm, size/M

#11907 BZ#1590663 - added BROKER_NAMESPACE to running ASB template command
  apb_devel/cli_tooling.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11916 Liveliness probe does not log a failure
  dev_guide/application_health.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11765 Improve documentation on Container storage driver to add overlay2
  scaling_performance/optimizing_storage.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#11960 [enterprise-3.7] Improve documentation on Container storage driver to add overlay2
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#11961 [enterprise-3.10] Improve documentation on Container storage driver to add overlay2
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#11962 [enterprise-3.9] Improve documentation on Container storage driver to add overlay2
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#11963 [enterprise-3.11] Improve documentation on Container storage driver to add overlay2
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#11651 Initial add Service Mesh files to repo.
  _topic_map.yml
  servicemesh-install/images/grafana-dashboard-no-traffic.png
  servicemesh-install/images/grafana-home-screen.png
  servicemesh-install/images/grafana-mesh-no-traffic.png
  servicemesh-install/images/grafana-mesh-with-traffic.png
  servicemesh-install/images/grafana-services.png
  servicemesh-install/images/grafana-workloads.png
  servicemesh-install/images/jaeger-main-screen.png
  servicemesh-install/images/jaeger-spans.png
  servicemesh-install/images/prometheus-home-screen.png
  servicemesh-install/images/prometheus-metrics.png
  servicemesh-install/servicemesh-install.adoc
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-overview.adoc
  servicemesh-install/topics/install-post.adoc
  servicemesh-install/topics/install-prerequisites.adoc
  servicemesh-install/topics/install-remove.adoc
  servicemesh-install/topics/install-supported-config.adoc
  servicemesh-install/topics/install-upgrade.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-install/topics/servicemesh-architecture.adoc
  servicemesh-install/topics/servicemesh-overview.adoc
  servicemesh-install/topics/tutorial-bookinfo.adoc
  servicemesh-install/topics/tutorial-grafana.adoc
  servicemesh-install/topics/tutorial-jaeger-tracing.adoc
  servicemesh-install/topics/tutorial-prometheus.adoc
  servicemesh-install/topics/tutorial-rhoar-missions.adoc
  servicemesh-install/topics/tutorials.adoc
  servicemesh-release-notes/servicemesh-release-notes.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-deprecated-features.adoc
  servicemesh-release-notes/topics/rn-fixed-issues.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
  servicemesh-release-notes/topics/rn-technology-preview.adoc
  servicemesh-release-notes/topics/servicemesh-overview.adoc
  servicemesh-release-notes/topics/support.adoc
Labels: Peer Review Needed, branch/enterprise-3.10, branch/enterprise-3.11, size/XXL

#11967 [enterprise-3.7]added BROKER_NAMESPACE to running ASB template command
  apb_devel/cli_tooling.adoc
Labels: size/S

#10772 Added section for priority and preemption
  admin_guide/scheduling/priority_preemption.adoc
Labels: branch/enterprise-3.11, size/L

#11971 removed .js from anchor id
  dev_guide/migrating_applications/web_framework_applications.adoc
Labels: size/XS

#11951 fixing GitHub nesting
  install_config/configuring_authentication.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#11852 SSPI support for Windows through request header
  install_config/configuring_authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#11886 GitLab can use OIDC
  install_config/configuring_authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm, size/M

#11987 [enterprise-3.2] Adding a warning section in our documentation
  install_config/install/advanced_install.adoc
Labels: size/S

#11988 [enterprise-3.3] Adding a warning section in our documentation
  install_config/install/advanced_install.adoc
Labels: size/S

#11989 [enterprise-3.5] Adding a warning section in our documentation
  install_config/install/advanced_install.adoc
Labels: size/S

#11990 [enterprise-3.6] Adding a warning section in our documentation
  install_config/install/advanced_install.adoc
Labels: size/S

#11992 [enterprise-3.10] Adding a warning section in our documentation
  install/running_install.adoc
Labels: size/S

#11993 [enterprise-3.11] Adding a warning section in our documentation
  install/running_install.adoc
Labels: size/S

#11996 Update URL to reflect OKD rebranding
  contributing_to_docs/term_glossary.adoc
Labels: size/XS

#11984 fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: size/S

#11997 fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#12000 [enterprise-3.11] fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: size/S

#12001 [enterprise-3.9] fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: size/S

#12002 [enterprise-3.10] fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: size/S

#12003 [enterprise-3.7] fixes openshift/openshift-docs#11983
  upgrading/os_upgrades.adoc
Labels: size/S

#12004 [enterprise-3.6] fixes openshift/openshift-docs#11983
  install_config/upgrading/os_upgrades.adoc
Labels: size/S

#11920 Update f5_router.adoc--fix typos and standardize naming convention
  install_config/router/f5_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, lgtm, size/M

#11805 bug 1529522 backup /etc/etcd/ca/ folder
  admin_guide/backup_restore.adoc
Labels: branch/enterprise-3.5, branch/enterprise-3.6, size/S

#11881 Installing from a container is ok
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/XS

#12016 fix typo per renato
  scaling_performance/optimizing_storage.adoc
Labels: size/XS

#12017 [enterprise-3.10] Adding a warning section in our documentation
  install/running_install.adoc
Labels: size/XS

#12018 fix typo per renato
  scaling_performance/optimizing_storage.adoc
Labels: size/XS

#12019 fix typo per renato
  scaling_performance/optimizing_storage.adoc
Labels: size/XS

#12033 Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/proc_backing-up-project.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  release_notes/ocp_3_9_release_notes.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#12037 [enterprise-3.11]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/proc_backing-up-project.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  release_notes/ocp_3_9_release_notes.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12038 [enterprise-3.10]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/proc_backing-up-project.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  release_notes/ocp_3_9_release_notes.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12039 [enterprise-3.9]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/proc_backing-up-project.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  release_notes/ocp_3_9_release_notes.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12040 [enterprise-3.7]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/proc_backing-up-project.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12041 [enterprise-3.6]Align with github repos move
  creating_images/guidelines.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/dev_tutorials/quickstarts.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12042 [enterprise-3.5]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  dev_guide/app_tutorials/quickstarts.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  security/build_process.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12044 [enterprise-3.4]Align with github repos move
  cli_reference/basic_cli_operations.adoc
  creating_images/guidelines.adoc
  dev_guide/app_tutorials/quickstarts.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12045 Fix for PR#12042
  dev_guide/templates.adoc
Labels: size/S

#12051 Add necessary API versions
  install_config/configuring_local.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12055 Fixed link rendering
  scaling_performance/optimizing_ephemeral_storage.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11

#12036 Clean CLI docs
  cli_reference/admin_cli_operations.adoc
  cli_reference/basic_cli_operations.adoc
  cli_reference/get_started_cli.adoc
Labels: branch/enterprise-3.11, size/L

#12007 Add Ansible Galaxy registry adapter to OAB docs
  install_config/oab_broker_configuration.adoc
Labels: branch/enterprise-3.11, size/S

#12060 [enterprise-3.11]Clean CLI docs
  cli_reference/admin_cli_operations.adoc
  cli_reference/basic_cli_operations.adoc
  cli_reference/get_started_cli.adoc
Labels: size/L

#12056 [enterprise-3.9] Add necessary API versions
  install_config/configuring_local.adoc
Labels: size/XS

#12057 [enterprise-3.7] Add necessary API versions
  install_config/configuring_local.adoc
Labels: size/XS

#12062 style edits
  install_config/oab_broker_configuration.adoc
Labels: branch/enterprise-3.11, size/XS

#12065 switch signature url for TBR
  admin_guide/image_signatures.adoc
Labels: branch/enterprise-3.11, size/XS

#11905 Added OCP 3.11 release notes
  _topic_map.yml
  install/configuring_inventory_file.adoc
  install_config/cluster_metrics.adoc
  release_notes/index.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/index.adoc
Labels: branch/enterprise-3.11, size/XL

#12069 [enterprise-3.11]Added OCP 3.11 release notes
  _topic_map.yml
  install/configuring_inventory_file.adoc
  install_config/cluster_metrics.adoc
  release_notes/index.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/index.adoc
Labels: size/XL

#12068 Changes for haproxy dynamic configuration manager support.
  architecture/topics/router_environment_variables.adoc
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.11, size/L

#12075 document slave pod image configuration env vars
  using_images/other_images/jenkins.adoc
Labels: branch/enterprise-3.11, branch/online, size/S

#12077 Added details to 3.11 Release Notes
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/L

#12091 Fixed typo from PR-5000
  architecture/topics/f5_big_ip.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#12092 [enterprise-3.7] Fixed typo from PR-5000
  architecture/topics/f5_big_ip.adoc
Labels: size/XS

#12093 [enterprise-3.6] Fixed typo from PR-5000
  architecture/topics/f5_big_ip.adoc
Labels: size/XS

#12032 Adding in required section for scaling down and up ES dcs
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#12102 Create robots.txt to disallow .htaccess protected directories
  .s2i/bin/assemble
Labels: size/XS

#12010 edits to the disconnected install topic
  install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XL

#12107 [enterprise-3.4] Adding a warning section in our documentation
  install_config/install/advanced_install.adoc
Labels: size/S

#12108 [enterprise-3.11] edits to the disconnected install topic
  install/disconnected_install.adoc
Labels: size/XL

#12109 [enterprise-3.10] edits to the disconnected install topic
  install/disconnected_install.adoc
Labels: size/XL

#11658 Upgrading Clusters: Create a note about CNS earlier in the document
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11632 Added Dedicated reader role
  admin_guide/index.adoc
  admin_guide/service_accounts.adoc
  architecture/additional_concepts/authorization.adoc
  getting_started/dedicated_administrators.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#12113 [enterprise-3.11]Added Dedicated reader role
  admin_guide/index.adoc
  admin_guide/service_accounts.adoc
  architecture/additional_concepts/authorization.adoc
  getting_started/dedicated_administrators.adoc
Labels: size/M

#12114 [enterprise-3.10]Added Dedicated reader role
  admin_guide/index.adoc
  admin_guide/service_accounts.adoc
  architecture/additional_concepts/authorization.adoc
  getting_started/dedicated_administrators.adoc
Labels: size/M

#12115 [enterprise-3.9]Added Dedicated reader role
  admin_guide/index.adoc
  admin_guide/service_accounts.adoc
  architecture/additional_concepts/authorization.adoc
  getting_started/dedicated_administrators.adoc
Labels: size/M

#12117 [enterprise-3.9] Upgrading Clusters: Create a note about CNS earlier in the document
  upgrading/automated_upgrades.adoc
Labels: size/XS

#12116 [enterprise-3.7] Upgrading Clusters: Create a note about CNS earlier in the document
  upgrading/automated_upgrades.adoc
Labels: size/XS

#11250 Added Accessing Your Services content for Dedicated
  _topic_map.yml
  getting_started/access_your_services.adoc
  getting_started/topics/configuring_AWS_VPC.adoc
Labels: branch/dedicated, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/L

#12098 Clarify openshift_master_cluster_public_hostname
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#12122 Revert "Clarify openshift_master_cluster_public_hostname"
  install/configuring_inventory_file.adoc
Labels: size/S

#12123 Clarify openshift_master_cluster_public_hostname
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12129 [enterprise-3.10]Added Accessing Your Services content for Dedicated
  _topic_map.yml
  getting_started/access_your_services.adoc
  getting_started/topics/configuring_AWS_VPC.adoc
Labels: size/L

#12130 [enterprise-3.9]Added Accessing Your Services content for Dedicated
  _topic_map.yml
  getting_started/access_your_services.adoc
  getting_started/topics/configuring_AWS_VPC.adoc
Labels: size/L

#12131 [enterprise-3.9] Clarify openshift_master_cluster_public_hostname
  install_config/install/advanced_install.adoc
Labels: size/XS

#11912 Update ES to 5.x
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/M

#12128 Fix unexpanded product-title in "Configuring IP failover"
  admin_guide/high_availability.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#10925 Router mutual tls auth documentation.
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.11, size/M

#11947 BZ 1624014: Edits after NFS note feedback
  install/configuring_inventory_file.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#12110 Fixing advanced install topic from bad merges
  install_config/install/advanced_install.adoc
Labels: size/L

#12144 [enterprise-3.7] BZ 1624014: Edits after NFS note feedback
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/L

#12146 [enterprise-3.9] BZ 1624014: Edits after NFS note feedback
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/M

#12147 [enterprise-3.10] BZ 1624014: Edits after NFS note feedback
  install/configuring_inventory_file.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/L

#12150 conditional statement adjustments for dedicated networking content
  architecture/networking/routes.adoc
Labels: size/M

#12151 Dedicated networking ifdef fixes
  architecture/networking/routes.adoc
Labels: size/M

#12152 Fixed conditionals for Dedicated networking content
  architecture/networking/routes.adoc
Labels: size/M

#12024 [wip] Bz1609697
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#12153 removing reference to 3.9
  install/running_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12158 GlusterFS: Update README link for 3.10
  _snippets/glusterfs.adoc
Labels: branch/enterprise-3.10, size/XS

#12156 GlusterFS: Update README link for 3.11
  _snippets/glusterfs.adoc
Labels: branch/enterprise-3.11, size/XS

#12157 GlusterFS: Update README link for 3.9
  _snippets/glusterfs.adoc
Labels: branch/enterprise-3.9, size/XS

#12031 Add RHBA-2018-2660 release note details
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#12027 [enterprise-3.7]Bumped 3.7 tags to 3.7.64
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.7, size/S

#12029 [enterprise-3.9]latest-tag bump for 3.9.43
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/S

#12030 [enterprise-3.10]Bumped latest-tags to 3.10.45
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, size/S

#12159 Continued updates to NFS documentation
  install/configuring_inventory_file.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#12169 [enterprise-3.7] Continued updates to NFS documentation
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/S

#12170 [enterprise-3.9] Continued updates to NFS documentation
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/S

#11446 Followup edits to PR 10312
  install_config/configuring_sdn.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#12155 Added bug to list
  release_notes/ocp_3_11_release_notes.adoc
Labels: size/L

#12172 follow up to PR11446
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.11, size/XS

#12161 Add apiserver qps and burst values recommendation for large clusters
  scaling_performance/host_practices.adoc
Labels: branch/enterprise-3.11, lgtm, size/S

#12183 Fixed a typo in the release notes
  release_notes/ocp_3_11_release_notes.adoc
Labels: size/XS

#12014 Add details for RHSA-2018-2654
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/S

#12034 [enterprise-3.6] Bump latest-tag to 3.6.173.0.130
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  install_config/upgrading/automated_upgrades.adoc
  install_config/upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.6, size/XS

#12178 bug 1479700 changed version to 3.3
  install_config/aggregate_logging.adoc
  install_config/upgrading/manual_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.3, size/XS

#12194 [enterprise-3.9] Bug 1602878 Prometheus State Variable update
  install_config/cluster_metrics.adoc
Labels: size/M

#12195 Edit date for advisory
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/XS

#12174 Adding new storage driver to the release notes
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#12201 BZ#1582554 - updated procedure to add and update project annotation
  admin_guide/managing_pods.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#12084 Liveliness probe does not log a failure - Follow Up
  dev_guide/application_health.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11451 admin guide - note: not all net.* syscts are namespaced
  admin_guide/sysctls.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#12097 Cloud config section not required on worker nodes
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#12202 [enterprise-3.6] BZ#1582554 - updated procedure to add and update project annotation
  admin_guide/managing_pods.adoc
Labels: size/M

#12203 [enterprise-3.7] BZ#1582554 - updated procedure to add and update project annotation
  admin_guide/managing_pods.adoc
Labels: size/M

#12204 [enterprise-3.9] BZ#1582554 - updated procedure to add and update project annotation
  admin_guide/managing_pods.adoc
Labels: size/M

#12205 [enterprise-3.10] BZ#1582554 - updated procedure to add and update project annotation
  admin_guide/managing_pods.adoc
Labels: size/M

#12217 [enterprise-3.11] Liveliness probe does not log a failure - Follow Up
  dev_guide/application_health.adoc
Labels: size/S

#12185 Improve NetworkPolicy documentation
  release_notes/ocp_3_7_release_notes.adoc
Labels: Peer Review Done, size/S

#12182 Added information to the 3.11 release notes
  release_notes/images/311-cluster-console.png
  release_notes/images/311-cluster-wide-event-stream.png
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/L

#12179 updating registry namespace
  install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12181 Add cluster auto-scaler documentation
  _topic_map.yml
  admin_guide/cluster-autoscaler.adoc
  admin_guide/topics/about-cluster-auto-scaler.adoc
  admin_guide/topics/creating-LC-and-ASG-cluster-auto-scaler.adoc
  admin_guide/topics/creating-primed-images-cluster-auto-scaler.adoc
  admin_guide/topics/deploying-cluster-auto-scaler.adoc
  admin_guide/topics/testing-auto-scaler.adoc
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#12166 [enterprise-3.10] bug 1609697 update disconnected install
  _topic_map.yml
  install/disconnected_install.adoc
Labels: size/L
