Repository openshift/openshift-docs, pull requests merged in 2018-07, with the labels that each got.

#10531 rm io.openshift.expose-services label
  architecture/core_concepts/builds_and_image_streams.adoc
  creating_images/metadata.adoc
  dev_guide/managing_images.adoc
Labels: size/S

#10557 fixed para in roles topic
  architecture/additional_concepts/authorization.adoc
Labels: size/XS

#10516 bug 1590486 volume security for Cinder
  architecture/core_concepts/deployments.adoc
  install_config/persistent_storage/persistent_storage_cinder.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#10559 [enterprise-3.10] bug 1590486 volume security for Cinder
  architecture/core_concepts/deployments.adoc
  install_config/persistent_storage/persistent_storage_cinder.adoc
Labels: size/L

#10560 [enterprise-3.9] bug 1590486 volume security for Cinder
  architecture/core_concepts/deployments.adoc
  install_config/persistent_storage/persistent_storage_cinder.adoc
Labels: size/L

#10561 [enterprise-3.7] bug 1590486 volume security for Cinder
  architecture/core_concepts/deployments.adoc
  install_config/persistent_storage/persistent_storage_cinder.adoc
Labels: size/L

#10418 Link to cluster limits page to clarify max-pods-per-nodes from core concepts
  architecture/core_concepts/pods_and_services.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10540 Typo in prerequisites regarding the firewall
  install/prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10567 [enterprise-3.10] Typo in prerequisites regarding the firewall
  install/prerequisites.adoc
Labels: size/XS

#10272 [enterprise-3.5] Logging and metrics version example uses v3.6 in 3.7 doc REDO
  install_config/cluster_metrics.adoc
Labels: size/XS

#10572 [enterprise-3.6] Logging and metrics version example uses v3.6 in 3.7 doc
  install_config/cluster_metrics.adoc
Labels: size/XS

#10435 Bug 1558794, specify image prefix during upgrade
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/S

#10576 Clarified details around Cockpit registry console
  install/stand_alone_registry.adoc
Labels: branch/enterprise-3.10, size/XS

#10442 BZ 1591637 - Add info about mode permissions
  install_config/persistent_storage/persistent_storage_azure_file.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/M

#10578 [enterprise-3.9]Clarified details around Cockpit registry console
  install_config/install/stand_alone_registry.adoc
Labels: size/XS

#10579 [enterprise-3.7]Clarified details around Cockpit registry console
  install_config/install/stand_alone_registry.adoc
Labels: size/XS

#10535 BZ 1593658 - Update for PVC protection GA
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/configuring_pvc_protection.adoc
Labels: branch/enterprise-3.10, size/L

#5236 Node Problem Detector
  _topic_map.yml
  admin_guide/diagnostics_tool.adoc
  admin_guide/node_problem_detector.adoc
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#10584 changed emptyDir to emptydir for variable values
  install_config/cluster_metrics.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10594 removed extra endif
  architecture/additional_concepts/storage.adoc
Labels: size/XS

#10603 Bug 1549690 Add note to update imagePullPolicy for EFK Automated Upgrade
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: size/L

#10519 clarify that reencrypt is supported for registry routes
  install_config/registry/securing_and_exposing_registry.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10610 [enterprise-3.1] Update links to Kubernetes documentation
  architecture/core_concepts/pods_and_services.adoc
Labels: size/M

#10606 Added Re-encrypt Route per PR-10519
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/XS

#10611 [enterprise-3.2] Update links to Kubernetes documentation
  architecture/core_concepts/pods_and_services.adoc
Labels: size/M

#10612 [enterprise-3.3] Update links to Kubernetes documentation
  architecture/core_concepts/pods_and_services.adoc
Labels: size/M

#10605 Change link to OpenShift repo
  using_images/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10613 Bug 1549690 Add note to update imagePullPolicy for EFK Automated Upgrade
  upgrading/automated_upgrades.adoc
Labels: size/S

#10617 Bug 1549690 Add note to update imagePullPolicy for EFK Automated Upgrade
  install_config/upgrading/automated_upgrades.adoc
Labels: size/S

#10580 [enterprise-3.10] Update for PVC protection GA
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/configuring_pvc_protection.adoc
Labels: size/L

#10590 Added info and default for event-ttl
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10200 BZ#1590731 - updated image tags for cloudforms, etcd, gluster
  install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#10626 [enterprise-3.9] updated image tags for cloudforms, etcd, gluster
  install_config/install/disconnected_install.adoc
Labels: size/S

#10449 updated mongodb image version and replication section
  using_images/db_images/mongodb.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#10565 adding conditionals
  architecture/core_concepts/pods_and_services.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10510 heading case, note clarifications
  _topic_map.yml
  admin_guide/pruning_resources.adoc
  install_config/syncing_groups_with_ldap.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#10630 [enterprise-3.9] adding conditionals
  architecture/core_concepts/pods_and_services.adoc
Labels: size/S

#10633 Bug 1443235 Add more information on dynamic provisioning with corrected links
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10080 Edit suggested in file admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/pod_placement.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10635 [enterprise-3.9] Bug 1443235 Add more information on dynamic provisioning
  install_config/install/advanced_install.adoc
Labels: size/M

#10636 [enterprise-3.7] Bug 1443235 Add more information on dynamic provisioning
  install_config/install/advanced_install.adoc
Labels: size/M

#10631 [enterprise-3.7] adding conditionals
  architecture/core_concepts/pods_and_services.adoc
Labels: size/S

#10602 [enterprise-3.2] Edit suggested in file admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduler.adoc
Labels: size/M

#10601 [enterprise-3.3] Edit suggested in file admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduler.adoc
Labels: size/M

#10599 [enterprise-3.4] Edit suggested in file admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduler.adoc
Labels: size/M

#10598 [enterprise-3.5] Edit suggested in file admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduler.adoc
Labels: size/M

#10432 BZ 1573476 - Add missing boolean data type
  install_config/persistent_storage/topics/glusterfs_security_selinux.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10641 [enterprise-3.9] Add missing boolean data type
  install_config/persistent_storage/topics/glusterfs_security_selinux.adoc
Labels: size/XS

#10642 [enterprise-3.10] Add missing boolean data type
  install_config/persistent_storage/topics/glusterfs_security_selinux.adoc
Labels: size/XS

#10643 fixing typo
  architecture/core_concepts/pods_and_services.adoc
  day_two_guide/topics/proc_scaling-etcd-ansible.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10647 Removed efs-provisioner
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.7, size/XS

#10648 Removed efs-provisioner
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.6, size/XS

#10600 Fix typo in vSphere link
  _topic_map.yml
  install_config/persistent_storage/persistent_storage_vsphere.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10103 Add information on raw block devices
  install_config/configuring_local.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L, tech_review

#10111 Added new calls to Device Plug-in docs for 3.10
  dev_guide/topics/about_device_plugins.adoc
Labels: branch/enterprise-3.10, lgtm, size/S

#10653 [enterprise-3.10] Add information on raw block devices
  install_config/configuring_local.adoc
Labels: size/L

#10649 [enterprise-3.6] Fix typo in vSphere link
  _topic_map.yml
  install_config/configuring_vsphere.adoc
  install_config/persistent_storage/persistent_storage_vsphere.adoc
Labels: size/L

#10656 Change info for options field
  install_config/persistent_storage/persistent_storage_flex_volume.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/L

#10657 Revert "Change info for options field"
  install_config/persistent_storage/persistent_storage_flex_volume.adoc
Labels: size/L

#10459 BZ 1588151 - Update Ceph RBD dynamic example
  _topic_map.yml
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#10660 [enterprise-3.9] Update Ceph RBD dynamic example
  _topic_map.yml
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: size/L

#10661 [enterprise-3.10] Update Ceph RBD dynamic example
  _topic_map.yml
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: size/L

#10462 BZ 1555929 - Update Ceph RBD example
  _topic_map.yml
  install_config/storage_examples/ceph_example.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#10655 clarify binary input used for local content
  dev_guide/builds/build_inputs.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10293 Update restart commands for 3.10
  admin_guide/backup_restore.adoc
  admin_guide/disabling_features.adoc
  admin_guide/encrypting_data.adoc
  admin_guide/managing_networking.adoc
  admin_guide/managing_projects.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/quota.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  admin_guide/scheduling/taints_tolerations.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  admin_guide/topics/proc_etcd-quorum-single-node-v2-v3.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/proc_removing-etcd-host.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
  day_two_guide/topics/proc_restoring-master.adoc
  dev_guide/expanding_persistent_volumes.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/pod_preset.adoc
  getting_started/configure_openshift.adoc
  getting_started/install_openshift.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/build_defaults_overrides.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_gce.adoc
  install_config/configuring_sdn.adoc
  install_config/http_proxies.adoc
  install_config/master_node_configuration.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/topics/applying_configuration_changes.adoc
  scaling_performance/managing_hugepages.adoc
  security/securing_container_platform.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#10672 [enterprise-3.7] updated mongodb image version and replication section
  using_images/db_images/mongodb.adoc
Labels: size/L

#10673 [enterprise-3.9] updated mongodb image version and replication section
  using_images/db_images/mongodb.adoc
Labels: size/L

#10674 [enterprise-3.10] updated mongodb image version and replication section
  using_images/db_images/mongodb.adoc
Labels: size/L

#10675 Fixed link in diagnostics tool section
  admin_guide/diagnostics_tool.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9

#10680 Fixes enterprise-3.6 in _topic_map.yml
  _topic_map.yml
Labels: size/L

#10682 fixed link in diagnostics tool section
  admin_guide/diagnostics_tool.adoc
Labels: size/XS

#10683 [enterprise-3.6] clarify binary input used for local content
  dev_guide/builds/build_inputs.adoc
Labels: size/XS

#10427 removing notes about master being unschedulable
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_deprecating-master.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10342 Bug 1590734 CNS required for rhgs3 images
  install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#10581 Correct the supported PostgreSQL versions and fix the broken links
  using_images/db_images/postgresql.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#10686 [enterprise-3.9] Bug 1590734 CNS required for rhgs3 images
  install_config/install/disconnected_install.adoc
Labels: size/S

#10687 Bug 1590734 CNS required for rhgs3 images
  install/disconnected_install.adoc
Labels: size/S

#10347 Bug 1588290 OpenShift_Logging is default logging project
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, size/XS

#10191 log aggregation created pvcs start with name logging-es-0 and not logging-es-1
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10688 [enterprise-3.10] Correct supported PostgreSQL versions, fix the broken links
  using_images/db_images/postgresql.adoc
Labels: size/S

#10690 [enterprise-3.9] Correct supported PostgreSQL versions, fix the broken links
  using_images/db_images/postgresql.adoc
Labels: size/S

#10691 [enterprise-3.7] Correct supported PostgreSQL versions, fix the broken links
  using_images/db_images/postgresql.adoc
Labels: size/S

#10692 [enterprise-3.6] Correct supported PostgreSQL versions, fix the broken links
  using_images/db_images/postgresql.adoc
Labels: size/S

#10694 [enterprise-3.5] Correct supported PostgreSQL versions, fix the broken links
  using_images/db_images/postgresql.adoc
Labels: size/S

#10116 Bug 1582041 Add ose-recycler and deprecation notice
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10698 [enterprise-3.9] Bug 1582041 Add ose-recycler and deprecation notice
  install_config/install/disconnected_install.adoc
Labels: size/XS

#10701 Bug 1582041 Add ose-recycler and deprecation notice
  install/disconnected_install.adoc
Labels: size/XS

#10433 Bug 1583632, added a known issue
  install_config/registry/registry_known_issues.adoc
Labels: branch/enterprise-3.10, lgtm, size/S

#10364 Bug 1460587 Add note - openshift_master_default_subdomain is required
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/XS

#10704 [enterprise-3.9] Bug 1460587 Add note - openshift_master_default_subdomain is required
  install_config/install/advanced_install.adoc
Labels: size/XS

#10705 [enterprise-3.7] Bug 1460587 Add note - openshift_master_default_subdomain is required
  install_config/install/advanced_install.adoc
Labels: size/XS

#10706 [enterprise-3.6] Bug 1460587 Add note - openshift_master_default_subdomain is required
  install_config/install/advanced_install.adoc
Labels: size/S

#10707 [enterprise-3.5] Bug 1460587 Add note - openshift_master_default_subdomain is required
  install_config/install/advanced_install.adoc
Labels: size/S

#9972 [enterprise-3.3] removed service account creation steps
  admin_guide/high_availability.adoc
Labels: branch/enterprise-3.3, size/S

#10313 New command to launch service logs
  day_two_guide/topics/proc_adding-etcd-after-restoring.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
  install_config/master_node_configuration.adoc
  security/monitoring.adoc
Labels: branch/enterprise-3.10, size/S

#10700 Added a Known Issue per BZ1485375
  admin_guide/quota.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/S

#10712 [enterprise-3.7]Added a Known Issue per BZ1485375
  admin_guide/quota.adoc
Labels: size/S

#10714 [enterprise-3.5]Added a Known Issue per BZ1485375
  admin_guide/quota.adoc
Labels: size/XS

#10715 [enterprise-3.4]Added a Known Issue per BZ1485375
  admin_guide/quota.adoc
Labels: size/XS

#10718 Updated apb push command
  apb_devel/cli_tooling.adoc
  apb_devel/writing/getting_started.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/M

#10708 Bug 1592855 added step for labeling default project to managing networking
  admin_guide/managing_networking.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#10726 added step for labeling default project to managing networking
  admin_guide/managing_networking.adoc
Labels: size/M

#10727 added a note to recreate routes on wildcard policy change
  install_config/router/default_haproxy_router.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10566 GlusterFS: Uninstall playbook
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/topics/glusterfs_uninstall.adoc
Labels: Peer Review Done, size/S

#8906 Sync up with upstream Kuryr development
  architecture/topics/kuryr.adoc
Labels: branch/enterprise-3.10, size/M

#10738 [enterprise-3.10]Add Kuryr SDN documentation
  _topic_map.yml
  admin_guide/kuryr.adoc
  architecture/networking/network_plugins.adoc
  architecture/topics/kuryr.adoc
  install_config/configuring_kuryrsdn.adoc
Labels: size/L

#10746 Minor fixes
  admin_guide/service_accounts.adoc
  cli_reference/get_started_cli.adoc
  install/host_preparation.adoc
  install_config/router/f5_router.adoc
Labels: size/S

#10130 Fix incorrect example for downward API
  dev_guide/downward_api.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#10744 Follow-up to PR 10566
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/topics/glusterfs_uninstall.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/S

#10597 Change title to encrypting traffic
  _topic_map.yml
  admin_guide/ipsec.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/M

#10088 Added Dedicated Limits Docs
  admin_guide/limits.adoc
  admin_guide/managing_projects.adoc
  admin_guide/quota.adoc
Labels: Peer Review Done, branch/dedicated, size/M

#10759 [enterprise-3.9]Added Dedicated Limits Docs
  admin_guide/limits.adoc
  admin_guide/managing_projects.adoc
  admin_guide/quota.adoc
Labels: size/L

#10763 [enterprise-3.10] Updates for OCP 3.10 upgrade
  install/index.adoc
  upgrading/automated_upgrades.adoc
  upgrading/index.adoc
Labels: size/L

#10760 [enterprise-3.10]Added Dedicated Limits Docs
  admin_guide/limits.adoc
  admin_guide/managing_projects.adoc
  admin_guide/quota.adoc
Labels: size/M

#10591 Bug 1591941 Added footnotes about cidr range for egress_source value
  admin_guide/managing_networking.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/M

#10765 added footnotes about cidr range for egress_source value
  admin_guide/managing_networking.adoc
Labels: size/M

#10767 Deleted multiple diagnostics objects
  admin_guide/diagnostics_tool.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10766 fixing typo "cassanda"
  install/configuring_inventory_file.adoc
  install_config/persistent_storage/topics/glusterfs_example_full.adoc
  install_config/persistent_storage/topics/glusterfs_example_full_external.adoc
  install_config/persistent_storage/topics/glusterfs_example_infra.adoc
Labels: branch/enterprise-3.10, size/S

#10697 Updated GSG section on installation process
  getting_started/install_openshift.adoc
Labels: branch/enterprise-3.10, lgtm, size/M

#9562 Adds ServerAliveInterval to ansible.cfg ssh options.
  scaling_performance/install_practices.adoc
Labels: lgtm, size/XS

#9634 Fixed api versions
  dev_guide/pod_autoscaling.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#10315 Remove references to single and multiple master clusters, per sdodson
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_deprecating-master.adoc
  install/configuring_inventory_file.adoc
  install/prerequisites.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_nuagesdn.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10782 BZ 1595017 - Add info to PV object definition example
  install_config/persistent_storage/persistent_storage_vsphere.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10784 [enterprise-3.7] Remove references to single and multiple master clusters
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_deprecating-master.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_nuagesdn.adoc
  install_config/install/prerequisites.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: size/M

#10788 bug 1595935 fixing link
  architecture/additional_concepts/authorization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#10719 Moved json-file note from 3.7 to 3.9 per BZ
  release_notes/ocp_3_7_release_notes.adoc
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10792 [enterprise-3.7] Moved json-file note from 3.7 to 3.9 per BZ
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/S

#10793 Fix endif in kube_infra.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
Labels: size/XS

#10745 Bug 1579762 Updated docker insecure registry value for IP
  day_two_guide/topics/managing_docker_registries.adoc
  install/configuring_inventory_file.adoc
  install/disconnected_install.adoc
  install/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#10797 Enterprise 3.9
  day_two_guide/topics/managing_docker_registries.adoc
  install_config/install/disconnected_install.adoc
Labels: size/S

#10201 added explanation around BUFFER_QUEUE_LIMIT variable
  admin_guide/overcommit.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10801 Update Ceph RBD dynamic example
  _topic_map.yml
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: size/L

#10802 [enterprise-3.7] Update Ceph RBD dynamic example
  _topic_map.yml
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: size/L

#10803 updated docker insecure registry value for IP
  install_config/install/disconnected_install.adoc
Labels: size/XS

#10795 fix typo
  install/configuring_inventory_file.adoc
Labels: size/XS

#10805 Change info for options field
  install_config/persistent_storage/persistent_storage_flex_volume.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/L

#10787 [enterprise-3.9] Remove references to single and multiple master cluster
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_deprecating-master.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_nuagesdn.adoc
  install_config/install/prerequisites.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: size/M

#10734 BZ#1595208 - updated version numbers to 3.9
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/M

#10811 [enterprise-3.7]Updated pod presets support statements for OCP 3.7
  admin_guide/managing_pods.adoc
  architecture/core_concepts/pods_and_services.adoc
  dev_guide/pod_preset.adoc
Labels: size/M

#10812 Updated pod presets support statements
  admin_guide/managing_pods.adoc
  architecture/core_concepts/pods_and_services.adoc
  dev_guide/pod_preset.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/M

#10791 [enterprise-3.10] Update restart commands for 3.10
  admin_guide/backup_restore.adoc
  admin_guide/disabling_features.adoc
  admin_guide/encrypting_data.adoc
  admin_guide/managing_networking.adoc
  admin_guide/managing_projects.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/quota.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  admin_guide/scheduling/taints_tolerations.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  admin_guide/topics/proc_etcd-quorum-single-node-v2-v3.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/proc_removing-etcd-host.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
  day_two_guide/topics/proc_restoring-master.adoc
  dev_guide/expanding_persistent_volumes.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/pod_preset.adoc
  getting_started/configure_openshift.adoc
  getting_started/install_openshift.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/build_defaults_overrides.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_gce.adoc
  install_config/configuring_sdn.adoc
  install_config/http_proxies.adoc
  install_config/master_node_configuration.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/topics/applying_configuration_changes.adoc
  scaling_performance/managing_hugepages.adoc
  security/securing_container_platform.adoc
Labels: size/L

#9998 3.10 Release Notes
  dev_guide/topics/about_device_manager.adoc
  dev_guide/topics/about_device_plugins.adoc
  install_config/persistent_storage/persistent_storage_csi.adoc
  install_config/persistent_storage/persistent_storage_manila.adoc
  release_notes/index.adoc
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/XXL

#10816 [enterprise-3.10] Remove references to single and multiple master clusters, per sdodson
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_deprecating-master.adoc
  install/configuring_inventory_file.adoc
  install/prerequisites.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_nuagesdn.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: size/M

#10819 [enterprise-3.9] Moved json-file note from 3.7 to 3.9 per BZ
  release_notes/ocp_3_7_release_notes.adoc
  release_notes/ocp_3_9_release_notes.adoc
Labels: size/M

#9467 Ephemeral storage
  _topic_map.yml
  admin_guide/allocating_node_resources.adoc
  admin_guide/limits.adoc
  admin_guide/overcommit.adoc
  admin_guide/quota.adoc
  architecture/additional_concepts/ephemeral-storage.adoc
  dev_guide/application_ephemeral_storage_sizing.adoc
  dev_guide/compute_resources.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/configuring_ephemeral.adoc
  scaling_performance/optimizing_ephemeral_storage.adoc
  scaling_performance/optimizing_storage.adoc
Labels: lgtm, size/XL

#10828 Ephemeral Storage Fixes
  _topic_map.yml
  admin_guide/allocating_node_resources.adoc
  admin_guide/limits.adoc
  admin_guide/overcommit.adoc
  admin_guide/quota.adoc
  architecture/additional_concepts/ephemeral-storage.adoc
  dev_guide/application_ephemeral_storage_sizing.adoc
  dev_guide/compute_resources.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/configuring_ephemeral.adoc
  scaling_performance/optimizing_ephemeral_storage.adoc
  scaling_performance/optimizing_storage.adoc
Labels: size/XL

#10829 Fixes for PR 10825
  admin_guide/limits.adoc
  admin_guide/quota.adoc
  architecture/additional_concepts/ephemeral-storage.adoc
Labels: size/S

#10830 # 10794 Fix headings in router assembly
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/haproxy_template_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9

#10831 fix headings in router assembly
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/haproxy_template_router.adoc
Labels: size/M

#10832 fix headings in router assembly
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/haproxy_template_router.adoc
Labels: size/M
