Repository openshift/openshift-docs, pull requests merged in 2018-08, with the labels that each got.

#11268 updated guidelines with special character issues
  contributing_to_docs/doc_guidelines.adoc
Labels: size/S

#9072 Clarify GitHub Content type JSON in triggering_builds.adoc
  dev_guide/builds/triggering_builds.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11270 Follow up PR 4404: remove content from enterprise-3.3 routes
  architecture/core_concepts/routes.adoc
Labels: size/L

#11271 Follow up 4405
  architecture/core_concepts/routes.adoc
Labels: size/S

#9251 Add Membership whitelist customization docs to console customization page
  install_config/web_console_customization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#11256 Update registry/router step in blue-green
  upgrading/blue_green_deployments.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#11070 Edit suggested in file admin_guide/manage_nodes.adoc
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#10549 Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#10102 Registry catalog API call
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.11, size/M

#11286 [enterprise-3.11] Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: size/L

#11287 [enterprise-3.10] Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: size/L

#11288 [enterprise-3.9] Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: size/L

#11290 [enterprise-3.6] Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: size/L

#11289 [enterprise-3.7] Clearly Specify Router Metrics file format returned
  install_config/router/default_haproxy_router.adoc
Labels: size/L

#11291 PR10102-Follow-up Minor Edits
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.11, size/M

#11297 Redirects for 3.10 install
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/S

#11305 [enterprise-3.10] clarify GitHub Content type JSON in triggering_builds.adoc
  dev_guide/builds/triggering_builds.adoc
Labels: size/XS

#11306 [enterprise-3.9] clarify GitHub Content type JSON in triggering_builds.adoc
  dev_guide/builds/triggering_builds.adoc
Labels: size/XS

#11298 fixes version selector dropdown for 3.3
  _javascripts/page-loader.js
Labels: branch/enterprise-3.0, branch/enterprise-3.1, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/XS

#11063 Adds errors as comments onTravis build failures
  .travis.yml
  autocomment.sh
Labels: size/M

#11319 removed old links
  install_config/cluster_metrics.adoc
  scaling_performance/scaling_cluster_metrics.adoc
Labels: size/XS

#11153 removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11326 [enterprise-3.9] removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#11327 [enterprise-3.7] removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#11328 [enterprise-3.6] removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#11329 [enterprise-3.5] removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#11330 [enterprise-3.4]removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#11331 [enterprise-3.3] removing a note about tokens and GitLab
  install_config/configuring_authentication.adoc
Labels: size/XS

#9381 Add documentation about "oc image mirror" commmand
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.11, size/M, to_followup

#11332 Minor: "exiting" should be "existing" on line 533
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11338 Remove Gluster content for Logging and Metrics
  install_config/aggregate_logging.adoc
  install_config/cluster_metrics.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#11341 [enterprise-3.9] Remove Gluster content for Logging and Metrics
  install_config/aggregate_logging.adoc
  install_config/cluster_metrics.adoc
Labels: size/S

#11334 PR9381-Follow-up minor edits
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.11, size/M

#10082 Add Dynatrace Monitoring for OpenShift docs
  _topic_map.yml
  day_two_guide/dynatrace_oneagent_installation.adoc
  day_two_guide/topics_dynatrace/installation.adoc
  day_two_guide/topics_dynatrace/locate_installer_url.adoc
  day_two_guide/topics_dynatrace/troubleshooting.adoc
  day_two_guide/topics_dynatrace/uninstallation.adoc
  day_two_guide/topics_dynatrace/updating.adoc
Labels: origin-only, size/L

#11347 Rebrand openshift.org and OpenShift Origin as okd.io and OKD
  404-commercial.html
  404-community.html
  README.adoc
  _distro_map.yml
  _images/okd_logo.svg
  _stylesheets/docs.css
  _stylesheets/foundation.css
  _templates/_topnav_other.html
  architecture/networking/routes.adoc
  contributing_to_docs/contributing.adoc
  contributing_to_docs/doc_guidelines.adoc
  contributing_to_docs/term_glossary.adoc
  contributing_to_docs/tools_and_setup.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  index-commercial.html
  index-community.html
  install_config/cfme/container_provider.adoc
  install_config/configuring_authentication.adoc
  install_config/master_node_configuration.adoc
  install_config/persistent_storage/dynamically_provisioning_pvs.adoc
  install_config/web_console_customization.adoc
  release_notes/ocp_3_10_release_notes.adoc
  release_notes/ocp_3_4_release_notes.adoc
  search-commercial.html
  upgrading/automated_upgrades.adoc
  upgrading/index.adoc
Labels: size/L

#11355 [enterprise-3.11] added updated stylesheets and image for okd
  _images/okd_logo.svg
  _stylesheets/docs.css
  _stylesheets/foundation.css
Labels: size/M

#11356 added updated stylesheets and image for okd
  _images/okd_logo.svg
  _stylesheets/docs.css
  _stylesheets/foundation.css
Labels: size/M

#11354 fix typo
  install/configuring_inventory_file.adoc
Labels: size/XS

#11307 version selector on top
  _templates/_nav_openshift.html.erb
  _templates/_page_openshift.html.erb
Labels: size/M

#11371 Fixes #11370 - Wrong variable for defining Storage Class for Metrics Cassandra
  install_config/cluster_metrics.adoc
Labels: size/XS

#10930 BZ#1601757 - added considerations for using MySQL and PostgreSQL with azure file
  install_config/persistent_storage/persistent_storage_azure_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#11378 [enterprise-3.7] fixes #4892
  dev_guide/migrating_applications/support_guide.adoc
Labels: size/XS

#11380 [enterprise-3.9] fixes #4892
  dev_guide/migrating_applications/support_guide.adoc
Labels: size/XS

#11381 [enterprise-3.10] fixes #4892
  dev_guide/migrating_applications/support_guide.adoc
Labels: size/XS

#11382 [enterprise-3.11] fixes #4892
  dev_guide/migrating_applications/support_guide.adoc
Labels: size/XS

#10361 updating sysctls for 3.11
  admin_guide/sysctls.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#10758 [enterprise-3.6]Fix incorrect example for downward API
  dev_guide/downward_api.adoc
Labels: size/M

#11232 updating list of supported sysctls
  admin_guide/sysctls.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#10618 Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/persistent_storage/topics/glusterfs_using_storage.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
  release_notes/ocp_3_6_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.1, branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#11349 Issue 10876 Fix ramp node config file setting
  install_config/routing_from_edge_lb.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#11413 [enterprise-3.3] Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
Labels: size/L

#11407 [enterprise-3.7] Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/L

#11414 [enterprise-3.2] Don't use nginx image for the Pod example
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/compute_resources.adoc
  dev_guide/new_app.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
Labels: size/L

#11415 [enterprise-3.4] Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
Labels: size/L

#11408 [enterprise-3.6] Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/L

#11409 [enterprise-3.5] Don't use nginx image for the Pod example
  admin_guide/managing_pods.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/compute_resources.adoc
  dev_guide/persistent_volumes.adoc
  install_config/storage_examples/privileged_pod_storage.adoc
  install_config/storage_examples/shared_storage.adoc
Labels: size/L

#11418 Added technical note related to Ansible version
  release_notes/ocp_3_7_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.7, size/S

#11420 Added Storage section on Overlay FS to Dedicated Product Updates
  release_notes/osd_latest_product_updates.adoc
Labels: branch/dedicated, size/S

#11423 Edited technical note for clarity
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10

#11426 [dedicated] Update to 3.9
  .travis.yml
  _distro_map.yml
  _templates/_page_openshift.html.erb
Labels: size/XS

#11431 Fix optimizing_on_glusterfs_storage in topic_map
  _topic_map.yml
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11369 add eol notification for openshift pipeline plugin
  using_images/other_images/jenkins.adoc
Labels: branch/enterprise-3.11, size/XS

#11434 fix typo
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#10312 Adding vxlanPort changes to the docs
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.11, size/M

#11184 Bring the retry topic back and switch to oc rollout
  dev_guide/deployments/basic_deployment_operations.adoc
Labels: branch/enterprise-3.11, size/XS

#11448 Fix space and unicode quotes in oc annotate command
  dev_guide/routes.adoc
Labels: size/XS

#11444 revised Ansible note
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/S

#11422 Added OCP 3.6 technical note related to Ansible version
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/S

#11335 Update Scheduler Docs Follow-up
  admin_guide/scheduling/scheduler.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11461 [enterprise-3.7] Mention that docker gc should only be installed on overlay2
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/S

#11432 bug 1610348 moving openshift-ansible update command
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#11161 MaxLimitRequestsRatio should be positive integral value
  admin_guide/limits.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11469 Re-add 3.10 APB known issue
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10

#11481 Backport async release notes content to master
  release_notes/ocp_3_6_release_notes.adoc
  release_notes/ocp_3_7_release_notes.adoc
  release_notes/ocp_3_9_release_notes.adoc
Labels: size/L

#11485 [enterprise-3.11]Added Network Policy content to Dedicated
  admin_guide/managing_networking.adoc
Labels: branch/enterprise-3.11, size/XS

#11489 [master]Fixes #11299 - Replace selectors based on old openshift_node_labels
  admin_guide/manage_nodes.adoc
  admin_guide/managing_projects.adoc
  admin_guide/topics/proc_adding-hosts.adoc
  install/configuring_inventory_file.adoc
  install_config/cluster_metrics.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/M

#11343 [enterprise-3.9]Added RHBA-2018:2013 to async release notes + latest-tag bump
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  release_notes/ocp_3_9_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/L

#11346 [enterprise-3.6]Added async advisory RHBA-2018:2340 + latest-tag bump
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  install_config/upgrading/automated_upgrades.adoc
  install_config/upgrading/manual_upgrades.adoc
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/M

#11345 [enterprise-3.7]Added async release notes for RHBA-2018:2337 + latest-tag bump
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.7, size/L

#6461 Add examples of using Secrets for Environment Variables in Build Configs
  dev_guide/builds/build_environment.adoc
  dev_guide/secrets.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#11498 Formatting fix
  release_notes/ocp_3_6_release_notes.adoc
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/XS

#10515 Edit API version in file dev_guide/pod_autoscaling.adoc
  dev_guide/pod_autoscaling.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#11499 [enterprise-3.6]formatting fix
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/XS

#11503 [enterprise-3.7]formatting fix
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/XS

#11511 updated label for tagging resources
  install_config/configuring_aws.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11514 [enterprise-3.7] updated label for tagging resources
  install_config/configuring_aws.adoc
Labels: size/S

#11519 fix egressip and ingressip caps issue
  architecture/core_concepts/pods_and_services.adoc
  install_config/master_node_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: size/S

#11520 fix egressip and ingressip caps issue
  architecture/core_concepts/pods_and_services.adoc
  install_config/master_node_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: size/S

#11521 fix egressip and ingressip caps issue
  architecture/core_concepts/pods_and_services.adoc
  install_config/master_node_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: size/S

#11524 fix egressip and ingressip caps issue
  architecture/core_concepts/pods_and_services.adoc
  install_config/master_node_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: size/S

#11522 fix egressip and ingressip caps issue
  architecture/core_concepts/pods_and_services.adoc
  install_config/master_node_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: size/S

#11515 [enterprise-3.9] updated label for tagging resources
  install_config/configuring_aws.adoc
Labels: size/S

#11145 Rm version-specific mediawiki-apb
  apb_devel/writing/getting_started.adoc
  apb_devel/writing/reference.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#11529 Updated image tag for OpenShift enterprise
  architecture/additional_concepts/authentication.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11467 Clarify s2i Secrets/ConfigMap Behavior
  dev_guide/builds/build_inputs.adoc
Labels: branch/enterprise-3.11, size/XS

#11411 BZ1600199:Corrected role clusteradmin to cluster-admin
  admin_guide/manage_rbac.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11449 Switch to oc set env/volume, since oc env/volume is now removed
  admin_guide/high_availability.adoc
  admin_guide/managing_networking.adoc
  admin_guide/pruning_resources.adoc
  architecture/networking/routes.adoc
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  day_two_guide/topics/proc_restoring-data-new-pvc.adoc
  day_two_guide/topics/pvc_backup_and_restore.adoc
  dev_guide/dev_tutorials/maven_tutorial.adoc
  dev_guide/volumes.adoc
  getting_started/configure_openshift.adoc
  install_config/redeploying_certificates.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/registry/securing_and_exposing_registry.adoc
  install_config/router/customized_haproxy_router.adoc
  install_config/router/default_haproxy_router.adoc
  install_config/router/proxy_protocol.adoc
  install_config/storage_examples/azure_blob_docker_registry_example.adoc
  install_config/storage_examples/gluster_backed_registry.adoc
Labels: branch/enterprise-3.11

#11535 [enterprise-3.11] Switch to oc set env/volume, since oc env/volume is now removed
  admin_guide/high_availability.adoc
  admin_guide/pruning_resources.adoc
  architecture/networking/routes.adoc
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  day_two_guide/topics/proc_restoring-data-new-pvc.adoc
  day_two_guide/topics/pvc_backup_and_restore.adoc
  dev_guide/dev_tutorials/maven_tutorial.adoc
  dev_guide/volumes.adoc
  getting_started/configure_openshift.adoc
  install_config/redeploying_certificates.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/registry/securing_and_exposing_registry.adoc
  install_config/router/customized_haproxy_router.adoc
  install_config/router/default_haproxy_router.adoc
  install_config/router/proxy_protocol.adoc
  install_config/storage_examples/azure_blob_docker_registry_example.adoc
  install_config/storage_examples/gluster_backed_registry.adoc
Labels: size/L

#11484 Bug 1566438, added suggestion to validate storage before upgrading
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: lgtm, size/S

#11509 Added suggestion to validate storage before upgrading for 3.9
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: lgtm, size/S

#11505 Adding suggestion to validate storage before upgrading 3.10+
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, lgtm, size/XS

#11450 doc: openshift_node_groups examples
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#11538 Update openshift_pipeline.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11548 Fix a typo in Device Manager topic
  dev_guide/device_manager.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11554 Fixed unclear sentences in Custom Build Strategy topic
  creating_images/custom.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11563 Bump ansible repo to 2.6
  getting_started/install_openshift.adoc
  install/disconnected_install.adoc
  install/host_preparation.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/S

#11566 BZ: 1588095 - fixed link to etcd migration
  upgrading/automated_upgrades.adoc
Labels: size/XS

#11567 Bug 1589133 Added namespace value to master connectivity health checks
  day_two_guide/topics/network_connectivity.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11553 Bug 1610417 Quick Installer known issue
  release_notes/ocp_3_7_release_notes.adoc
Labels: Peer Review Done, size/XS

#11429 bug 1613077 updating files to back up
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11417 adding parameters that disable OAB and TSB
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#11580 [enterprise-3.9] adding parameters that disable OAB and TSB
  install_config/install/advanced_install.adoc
Labels: size/M

#11581 [enterprise-3.7] adding parameters that disable OAB and TSB
  install_config/install/advanced_install.adoc
Labels: size/M

#11586 Typo fix
  upgrading/index.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11589 [enterprise-3-9]Typo fix
  upgrading/index.adoc
Labels: size/XS

#11590 [enterprise-3.7]Typo fix
  upgrading/index.adoc
Labels: size/XS

#11490 BZ#1613747 - updated disabling a build strategy
  admin_guide/securing_builds.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#11597 [enterprise-3.10] Updated image tag for OpenShift enterprise
  architecture/additional_concepts/authentication.adoc
Labels: size/S

#11596 [enterprise-3.11] Updated image tag for OpenShift enterprise
  architecture/additional_concepts/authentication.adoc
Labels: size/S

#11598 [enterprise-3.9] Updated image tag for OpenShift enterprise
  architecture/additional_concepts/authentication.adoc
Labels: size/S

#11599 [enterprise-3.7] Updated image tag for OpenShift enterprise
  architecture/additional_concepts/authentication.adoc
Labels: size/S

#7720 Add allow command "osd blacklist" to client.kube in ceph
  install_config/storage_examples/ceph_rbd_dynamic_example.adoc
Labels: size/XS

#11079 Fixed syntax error and add required fields.
  dev_guide/deployments/kubernetes_deployments.adoc
Labels: size/XS

#11611 [enterprise-3.7] bug BZ1616293 updating playbook path
  install_config/certificate_customization.adoc
Labels: size/XS

#6418 Update builddefaults documentation.
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/M

#11612 Fixed link to RHBA-2018:2335
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/XS

#11157 removing content from the backup_restore topic
  admin_guide/backup_restore.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XL

#11539 Added information on a known issue with cluster loader
  scaling_performance/using_cluster_loader.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#11618 [enterprise-3.11] Document a way to override build defaults proxy.
  install/configuring_inventory_file.adoc
Labels: size/L

#11619 [enterprise-3.10] Document a way to override build defaults proxy.
  install/configuring_inventory_file.adoc
Labels: size/L

#11620 [enterprise-3.9] Document a way to override build defaults proxy.
  install_config/install/advanced_install.adoc
Labels: size/L

#11621 [enterprise-3.7] Document a way to override build defaults proxy.
  install_config/install/advanced_install.adoc
Labels: size/L

#11622 [enterprise-3.6] Document a way to override build defaults proxy.
  install_config/install/advanced_install.adoc
Labels: size/M

#11623 [enterprise-3.5] Document a way to override build defaults proxy.
  install_config/install/advanced_install.adoc
Labels: size/M

#11624 [enterprise-3.11] removing content from the backup_restore topic
  admin_guide/backup_restore.adoc
Labels: size/XL

#11625 [enterprise-3.10] removing content from the backup_restore topic
  admin_guide/backup_restore.adoc
Labels: size/XL

#11626 [enterprise-3.9] removing content from the backup_restore topic
  admin_guide/backup_restore.adoc
Labels: size/XL

#11627 [enterprise-3.7] removing content from the backup_restore topic
  admin_guide/backup_restore.adoc
Labels: size/XL

#11634 Fix a minor spelling in build and imagestreams doc
  architecture/core_concepts/builds_and_image_streams.adoc
Labels: size/XS

#10681 GCE content from refarch
  _topic_map.yml
  install_config/configuring_gce.adoc
  install_config/topics/configuring_for_gce.adoc
  install_config/topics/configuring_for_gce_registry.adoc
  install_config/topics/configuring_for_gce_storage.adoc
  install_config/topics/configuring_gce_objects.adoc
  install_config/topics/gce_scopes_permissions.adoc
  install_config/topics/manually_configuring_for_gce.adoc
  install_config/topics/using_gcp_load_balancer.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XXL

#11540 Bug 1511257: Clarify v2/v3 etcd backup steps
  admin_guide/backup_restore.adoc
Labels: branch/enterprise-3.6, lgtm, size/S

#11585 Added location where ansible_service_broker_install is set
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11647 Issue-11633 Update Image Policy Link
  admin_guide/image_policy.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#11584 [enterprise-3.9]Added location where ansible_service_broker_install is set
  install_config/install/advanced_install.adoc
Labels: branch/enterprise-3.9, size/XS

#11583 [enterprise-3.7]Added location where ansible_service_broker_install is set
  install_config/install/advanced_install.adoc
Labels: branch/enterprise-3.7, size/XS

#11653 Edits after translation
  upgrading/automated_upgrades.adoc
Labels: size/XS

#11662 added note box on unavailable features for networkpolicy
  admin_guide/managing_networking.adoc
Labels: size/S

#11663 Provide httpd pod naming convention in day two operations guide
  day_two_guide/topics/network_connectivity.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#11673 Changed openshift-ansible-utils package name
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#11483 Remove `alpha` from node.alpha.kubernetes.io AND removed duplicate node.alpha.kubernetes.io/notReady:NoExecute
  admin_guide/scheduling/taints_tolerations.adoc
Labels: branch/enterprise-3.11, size/S
