Repository openshift/openshift-docs, pull requests merged in 2018-05, with the labels that each got.

#8781 Bug 1563929 - add a 3.9 upgrade known issues section
  _topic_map.yml
  upgrading/upgrading_known_issues.adoc
  {
Labels: branch/enterprise-3.9, size/L

#8800 [enterprise-3.6] Fixes vsphere file path and a list rendering issue
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.6, size/S

#8801 fixed formatting issue
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#8619 Bug#1532704 - Added a note for enabling dynamic provisioning by using ansible variable
  install_config/persistent_storage/dynamically_provisioning_pvs.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#8959 Bug 1537882, added information about enabling block volume feature gates
  architecture/additional_concepts/storage.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#8925 Bug 1568809 remove deprecated images
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#8867 Bug 1570382 Add images for Prometheus, Cloudforms, and Gluster
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/M

#9010 [enterprise-3.7] Add relnotes for OCP 3.7.44
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  release_notes/ocp_3_7_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.7, size/M

#7050 Add note for path-based routes.
  architecture/networking/routes.adoc
Labels: branch/dedicated, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/S

#8908 Sanitize openshift_master_cluster_hostname
  install_config/install/advanced_install.adoc
  install_config/install/stand_alone_registry.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#8559 Promote CPU manager pinning to supported
  scaling_performance/using_cpu_manager.adoc
Labels: branch/enterprise-3.10, size/S

#8984 [enterprise-3.6] Adding documentation around tsb node selector
  install_config/install/advanced_install.adoc
Labels: size/XS

#8982 [enterprise-3.9] Adding documentation around tsb node selector
  install_config/install/advanced_install.adoc
Labels: size/S

#8981 [enterprise-3.7] Adding documentation around tsb node selector
  install_config/install/advanced_install.adoc
Labels: size/S

#9031 [enterprise-3.10] New Sections for Custom Certificates
  install_config/certificate_customization.adoc
Labels: size/L

#9017 remove meaningless "{" empty file
  {
Labels: Peer Review Done, branch/enterprise-3.9, size/XS

#7666 Added Granting Service Accounts Access to Dedicated-Admin Roles section
  admin_guide/service_accounts.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#8891 Bug 1562091 Fixed footnote
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#8620 Edits to day 2 guide as suggested
  day_two_guide/topics/default_storage_class.adoc
  day_two_guide/topics/deprecating_master.adoc
  day_two_guide/topics/entropy.adoc
  day_two_guide/topics/etcd_backup.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_certs.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/master_backup.adoc
  day_two_guide/topics/node_backup.adoc
  day_two_guide/topics/node_maintenance.adoc
  day_two_guide/topics/project_backup.adoc
  day_two_guide/topics/pruning_images_and_containers.adoc
  day_two_guide/topics/pvc_backup_and_restore.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#8889 Bug 1566992 added note on peerdns setting set to yes
  install_config/install/prerequisites.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#8803 router-depricate --expose-metrics --metrics-image
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.11, size/XS

#9053 Added known issues file and deleted current outdated issues
  _topic_map.yml
  upgrading/upgrading_known_issues.adoc
Labels: size/L

#9027 [master] Release: Link Fixes from 3.7
  admin_guide/garbage_collection.adoc
  admin_guide/limits.adoc
  admin_guide/monitoring_images.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/pruning_resources.adoc
  admin_guide/scheduling/pod_affinity.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  creating_images/custom.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/managing_images.adoc
  dev_guide/volumes.adoc
  rest_api/oapi/v1.Build.adoc
  scaling_performance/cluster_limits.adoc
  security/container_content.adoc
Labels: size/M

#9059 Adjust CSS for site redesign
  _stylesheets/docs.css
Labels: size/XS

#9060 Adjust CSS for site redesign
  _stylesheets/docs.css
Labels: size/XS

#9064 Adjust CSS for site redesign
  _stylesheets/docs.css
Labels: size/XS

#9058 Adjust CSS for site redesign
  _stylesheets/docs.css
Labels: size/XS

#9032 Update site nav with openshift.com redesign
  404-commercial.html
  _stylesheets/docs.css
  _templates/_footer_other.html.erb
  _templates/_page_openshift.html.erb
  _templates/_topnav_other.html
  contributing_to_docs/tools_and_setup.adoc
  index-commercial.html
  search-commercial.html
Labels: size/XXL

#9055 Revert "Undo changes to daemonset RBAC docs"
  admin_guide/manage_rbac.adoc
  dev_guide/daemonsets.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, lgtm, size/S

#8536 Added opaque secrets, per BZ
  dev_guide/secrets.adoc
Labels: branch/dedicated, branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/M

#8989 BZ 1559895 Change link for CNS on OCP document
  install_config/persistent_storage/dynamically_provisioning_pvs.adoc
Labels: Peer Review Done, branch/enterprise-3.7, size/XS

#9080 [enterprise-3.6] Added opaque secrets, per BZ
  dev_guide/secrets.adoc
Labels: size/M

#9081 [enterprise-3.5] Added opaque secrets, per BZ
  dev_guide/secrets.adoc
Labels: size/M

#9082 [enterprise-3.4] Added opaque secrets, per BZ
  dev_guide/secrets.adoc
Labels: size/M

#9083 Fixed missing [NOTE]
  install_config/redeploying_certificates.adoc
Labels: size/XS

#9085 fixed missing [NOTE]
  install_config/redeploying_certificates.adoc
Labels: size/XS

#9086 fixed missing [NOTE]
  install_config/redeploying_certificates.adoc
Labels: size/XS

#9087 fixed missing [NOTE]
  install_config/redeploying_certificates.adoc
Labels: size/XS

#9084 fixed missing [NOTE]
  install_config/redeploying_certificates.adoc
Labels: size/XS

#8730 Add documentation for Azure configuration
  install_config/configuring_azure.adoc
Labels: branch/enterprise-3.10, size/M

#9091 Edits to 9090 to docs standards
  install_config/configuring_azure.adoc
Labels: Peer Review Done, size/S

#9056 link to cluster limits page from admin guide to clarify max-pods
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/XS, to_followup

#9101 Follow-up edits to PR#9056
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#8924 Fix a link
  install_config/configuring_authentication.adoc
  release_notes/ocp_3_9_release_notes.adoc
Labels: size/XS

#9089 added openshift_gcp_multizone variable in Configuring GCE section
  install_config/configuring_gce.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#9112 Followup edits to dns proxy mode for egress
  admin_guide/managing_networking.adoc
Labels: branch/enterprise-3.10, size/M

#8955 Document how to expand the service CIDR range
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.10, size/M

#8668 Bug 15069999 Add variables for replicas and shards
  install_config/aggregate_logging.adoc
Labels: size/XS

#9119 Removed errant endif
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#8671 Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9130 [enterprise-3.2] Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#9131 [enterprise-3.3] Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#9132 [enterprise-3.5] Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#9129 [enterprise-3.4] Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#9133 [enterprise-3.6] Need Doc for Adding Certs to Registry
  install_config/registry/extended_registry_configuration.adoc
Labels: size/XS

#9054 Added new know issue for 3.7
  upgrading/upgrading_known_issues.adoc
Labels: size/S

#9141 BZ: 1493310, typo fix
  install_config/configuring_routing.adoc
Labels: branch/enterprise-3.3, size/XS

#8659 Added vrrp to high avail. variables
  admin_guide/high_availability.adoc
Labels: branch/enterprise-3.10, size/M

#9143 BUG#1573849 - fixes - Updated hyperlink to the most recent draft specification
  architecture/additional_concepts/authentication.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9121 adding yum-utils to host prep
  install_config/install/host_preparation.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#8949 add multinamespace instructions to pipeline tutorial
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  using_images/other_images/jenkins.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M, to_followup

#9137 add resources to default imagepolicy list
  admin_guide/image_policy.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9156 add multinamespace instructions to pipeline tutorial
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  using_images/other_images/jenkins.adoc
Labels: size/M

#7896 Fix non working example
  dev_guide/deployments/kubernetes_deployments.adoc
Labels: branch/dedicated, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/S

#9163 PR8949-Follow-up Minor Edits
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9175 Follow-up edits to PR#7896, fixed into to example
  dev_guide/deployments/kubernetes_deployments.adoc
Labels: branch/dedicated, branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9185 [enterprise-3.5]Follow-up to PR#9030, removed PaaS references
  install_config/install/stand_alone_registry.adoc
  release_notes/ocp_3_5_release_notes.adoc
Labels: branch/enterprise-3.5, size/S

#9183 [enterprise-3.7]Follow-up to PR#9030, removed PaaS references
  getting_started/index.adoc
  install_config/install/stand_alone_registry.adoc
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/S

#9184 [enterprise-3.6]Follow-up to PR#9030, removed PaaS references
  getting_started/index.adoc
  install_config/install/stand_alone_registry.adoc
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/S

#9186 [enterprise-3.4]Follow-up to PR#9030, removed PaaS references
  install_config/install/stand_alone_registry.adoc
  release_notes/ocp_3_4_release_notes.adoc
Labels: branch/enterprise-3.4, size/S

#9187 [enterprise-3.3]Follow-up to PR#9030, removed PaaS references
  install_config/install/stand_alone_registry.adoc
  release_notes/ocp_3_3_release_notes.adoc
Labels: branch/enterprise-3.3, size/S

#9190 Edits to fix/clarify-maxconn branch
  install_config/router/default_haproxy_router.adoc
  scaling_performance/routing_optimization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#8504 Clarified how haproxy counts the connections
  install_config/router/default_haproxy_router.adoc
  scaling_performance/routing_optimization.adoc
Labels: size/S

#9191 Fix/clarify egress policy plugins
  admin_guide/managing_networking.adoc
Labels: size/XS

#8905 Add ovs-networkpolicy to the list of EgressNetworkPolicy plugins
  admin_guide/managing_networking.adoc
Labels: size/XS

#9197 [enterprise-3.0] Fix status codes for success
  dev_guide/application_health.adoc
Labels: branch/enterprise-3.0, size/XS

#8900 Brief note about timeouts in the haproxy router
  architecture/topics/router_environment_variables.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, lgtm, size/XS

#9134 bug 1442828 adding identity provider planning
  install_config/configuring_authentication.adoc
  install_config/install/advanced_install.adoc
  install_config/install/planning.adoc
Labels: Peer Review Needed, branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9139 Bug 1575916, updated playbook
  install_config/install/prerequisites.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#9140 Bug 1563744, added disclaimers about images running as root in Online
  dev_guide/application_lifecycle/new_app.adoc
  using_images/docker_images/index.adoc
Labels: Peer Review Done, branch/online, size/S

#9138 Bug 157608, Removed filename key and value
  install_config/configuring_authentication.adoc
  install_config/install/advanced_install.adoc
  install_config/install/stand_alone_registry.adoc
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.10, size/S

#8694 Added information about logging login failures
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9217 [enterprise-3.7]Added information about logging login failures
  install_config/master_node_configuration.adoc
Labels: size/XS

#9201 delete redundant 'also'
  architecture/core_concepts/builds_and_image_streams.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9225 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9226 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9228 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9227 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9229 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9230 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9224 Removed passthroughs
  admin_guide/pruning_resources.adoc
Labels: size/S

#9231 Added redirect for dedicated 3.7 to rbac
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#9218 Hawkular hostname
  install_config/install/advanced_install.adoc
Labels: size/XS

#8368 Bug 1542724 Add additional router metrics env var to docs
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/router_environment_variables.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9236 Bug 1542724 Add additional router metrics env var to docs
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/router_environment_variables.adoc
Labels: size/M

#9238 Bug 1542724 Add additional router metrics env var to docs
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/router_environment_variables.adoc
Labels: size/M

#9234 remove atomic-registry docs
  Jenkinsfile
  README.adoc
  _distro_map.yml
  _templates/_page_atomic.html.erb
  _topic_map.yml
  admin_guide/manage_rbac.adoc
  admin_guide/service_accounts.adoc
  architecture/additional_concepts/authorization.adoc
  architecture/index.adoc
  architecture/infrastructure_components/image_registry.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  architecture/infrastructure_components/web_console.adoc
  cli_reference/admin_cli_operations.adoc
  cli_reference/get_started_cli.adoc
  cli_reference/index.adoc
  contributing_to_docs/contributing.adoc
  dev_guide/authentication.adoc
  dev_guide/expose_service/expose_internal_ip_router.adoc
  dev_guide/getting_traffic_into_cluster.adoc
  dev_guide/index.adoc
  dev_guide/managing_images.adoc
  index-atomic-registry.html
  install_config/install/index.adoc
  install_config/install/prerequisites.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/securing_and_exposing_registry.adoc
  registry_quickstart/administrators/index.adoc
  registry_quickstart/administrators/system_configuration.adoc
  registry_quickstart/administrators/uninstall.adoc
  registry_quickstart/developers.adoc
  registry_quickstart/index.adoc
Labels: size/XXL

#9071 Updated Documentation on Custom Certificates and External Load Balancers
  install_config/certificate_customization.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9242 [enterprise-3.6] Updated Documentation on Custom Certificates and External Load Balancers
  install_config/certificate_customization.adoc
Labels: size/M

#9243 [enterprise-3.5] Updated Documentation on Custom Certificates and External Load Balancers
  install_config/certificate_customization.adoc
Labels: size/M

#9244 [enterprise-3.4] Updated Documentation on Custom Certificates and External Load Balancers
  install_config/certificate_customization.adoc
Labels: size/M

#9246 Issue 9165, remove confusing reference to "free" account
  dev_guide/projects.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#8551 added warning for F5 router docs
  install_config/router/f5_router.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/XS

#9254 BZ: 1560590 - Added JDV link and text
  install_config/imagestreams_templates.adoc
Labels: size/XS

#9255 BZ: 1560590 - Added JDV link and text
  install_config/imagestreams_templates.adoc
Labels: size/XS

#9256 BZ: 1560590 - Added JDV link and text
  install_config/imagestreams_templates.adoc
Labels: size/XS

#9250 Removed some HA references from Online
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#9245 removing please
  admin_guide/index.adoc
  admin_guide/manage_scc.adoc
  admin_guide/osd_request.adoc
  admin_guide/sdn_troubleshooting.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  contributing_to_docs/create_or_edit_content.adoc
  contributing_to_docs/templates/overview_topic_template.adoc
  contributing_to_docs/term_glossary.adoc
  getting_started/dedicated_administrators.adoc
  getting_started/devpreview_faq.adoc
  install_config/aggregate_logging.adoc
  install_config/cluster_metrics.adoc
  install_config/configuring_pipeline_execution.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/topics/glusterfs_overview_containerized.adoc
  install_config/persistent_storage/topics/glusterfs_security_selinux.adoc
  install_config/registry/extended_registry_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
  release_notes/ocp_3_4_release_notes.adoc
  release_notes/ocp_3_5_release_notes.adoc
  release_notes/ocp_3_6_release_notes.adoc
  release_notes/ocp_3_7_release_notes.adoc
  release_notes/ose_3_2_release_notes.adoc
  rest_api/api/v1.Binding.adoc
  scaling_performance/host_practices.adoc
  using_images/xpaas_images/a_mq.adoc
  whats_new/ose_3_0_release_notes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9266 removing please
  README.adoc
  admin_guide/index.adoc
  admin_guide/manage_scc.adoc
  admin_guide/osd_request.adoc
  admin_guide/sdn_troubleshooting.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  getting_started/dedicated_administrators.adoc
  getting_started/devpreview_faq.adoc
  install_config/aggregate_logging.adoc
  install_config/cluster_metrics.adoc
  install_config/configuring_pipeline_execution.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/registry/extended_registry_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
  release_notes/ocp_3_4_release_notes.adoc
  release_notes/ocp_3_5_release_notes.adoc
  release_notes/ocp_3_6_release_notes.adoc
  release_notes/ocp_3_7_release_notes.adoc
  release_notes/ose_3_1_release_notes.adoc
  release_notes/ose_3_2_release_notes.adoc
  rest_api/api/v1.Binding.adoc
  scaling_performance/host_practices.adoc
  whats_new/ose_3_0_release_notes.adoc
Labels: size/M

#9247 Rename 'Other Container Images' topic, add security warning
  _topic_map.yml
  creating_images/guidelines.adoc
  install_config/install/prerequisites.adoc
  using_images/docker_images/index.adoc
  using_images/other_images/other_container_images.adoc
  welcome/index.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#9270 removing please
  README.adoc
  admin_guide/index.adoc
  admin_guide/manage_scc.adoc
  admin_guide/osd_request.adoc
  admin_guide/sdn_troubleshooting.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  getting_started/dedicated_administrators.adoc
  getting_started/devpreview_faq.adoc
  install_config/aggregate_logging.adoc
  install_config/cluster_metrics.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/registry/extended_registry_configuration.adoc
  release_notes/ocp_3_3_release_notes.adoc
  release_notes/ocp_3_4_release_notes.adoc
  release_notes/ocp_3_5_release_notes.adoc
  release_notes/ocp_3_6_release_notes.adoc
  release_notes/ose_3_1_release_notes.adoc
  release_notes/ose_3_2_release_notes.adoc
  scaling_performance/host_practices.adoc
  whats_new/ose_3_0_release_notes.adoc
Labels: size/M

#9271 fixing typo
  release_notes/ocp_3_3_release_notes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9277 [enterprise-3.10] Rename 'Other Container Images' topic, add security warning
  _topic_map.yml
  creating_images/guidelines.adoc
  install_config/install/prerequisites.adoc
  using_images/docker_images/index.adoc
  using_images/other_images/other_container_images.adoc
  welcome/index.adoc
Labels: size/L

#9278 [enterprise-3.9] Rename 'Other Container Images' topic, add security warning
  _topic_map.yml
  creating_images/guidelines.adoc
  install_config/install/prerequisites.adoc
  using_images/docker_images/index.adoc
  using_images/other_images/other_container_images.adoc
  welcome/index.adoc
Labels: size/L

#9279 [enterprise-3.7] Rename 'Other Container Images' topic, add security warning
  _topic_map.yml
  creating_images/guidelines.adoc
  install_config/install/prerequisites.adoc
  using_images/docker_images/index.adoc
  using_images/other_images/other_container_images.adoc
  welcome/index.adoc
Labels: size/L

#9223 Add admissionconfig step to upgrade prereq
  install_config/upgrading/automated_upgrades.adoc
Labels: lgtm, size/S

#9282 Add admissionconfig step to upgrade prereq
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9283 [enterprise-3.7] Add admissionconfig step to upgrade prereq
  upgrading/automated_upgrades.adoc
Labels: size/S

#9253 Bug 1577830 Added important box about changing default SCC
  admin_guide/manage_scc.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, lgtm, size/XS

#9298 Moved important box to be ocp and origin specific
  admin_guide/manage_scc.adoc
Labels: size/S

#9115 Followup edits to cidr range pr 8955
  day_two_guide/topics/increasing_docker_storage.adoc
  install_config/configuring_sdn.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/M

#9308 Fixed incorrect anchor tags
  admin_guide/custom_resource_definitions.adoc
Labels: size/S

#9309 Fixed incorrect anchor tags
  admin_guide/custom_resource_definitions.adoc
Labels: size/S

#9310 Fixed incorrect anchor tags
  admin_guide/custom_resource_definitions.adoc
Labels: size/S

#9306 Fixed incorrect anchor tags
  admin_guide/custom_resource_definitions.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9249 fixing gitlab link
  install_config/configuring_authentication.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9320 bug 1538391 fixing router version image number
  release_notes/ocp_3_5_release_notes.adoc
Labels: branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9337 Fixing an endif in the backup/restore topic
  admin_guide/backup_restore.adoc
Labels: origin-only

#9341 Bug 1578754, fixed product title
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/XS

#9338 bug 1549362 clarifying active peers
  admin_guide/backup_restore.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9348 [enterprise 3.4] bug 1549362 clarifying active peers
  admin_guide/backup_restore.adoc
Labels: size/S

#9349 [enterprise 3.3] bug 1549362 clarifying active peers
  admin_guide/backup_restore.adoc
Labels: size/S

#9200 Arranged timeout router variables into one place
  architecture/topics/router_environment_variables.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/M

#9354 Added router_override_domains variable
  architecture/topics/router_environment_variables.adoc
Labels: size/XS

#9358 Fix issue with online release notes
  release_notes/online_release_notes.adoc
Labels: branch/online, size/XS

#9360 Bug 1573744 Added azure file to table in arch guide
  architecture/additional_concepts/storage.adoc
Labels: size/XS

#9340 Bug 1477340, Added corsAllowedOrigin to the Master and Node Configuration topic
  architecture/infrastructure_components/web_console.adoc
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9325 Update Release Notes for RHBA-2018:1566 - OCP 3.9.27 Bug Fix and Enhancements
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  release_notes/ocp_3_9_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/L

#9319 bug 1503109 correcting node resource kubelet argument
  admin_guide/out_of_resource_handling.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9379 [enterprise 3.3] bug 1503109 correcting node resource kubelet argument
  admin_guide/out_of_resource_handling.adoc
Labels: size/XS

#9380 [enterprise 3.4] bug 1503109 correcting node resource kubelet argument
  admin_guide/out_of_resource_handling.adoc
Labels: size/XS

#9350 [enterprise 3.2] bug 1549362 clarifying active peers
  admin_guide/backup_restore.adoc
Labels: size/S

#9043 adding and editing docs for cluster role aggregation
  _topic_map.yml
  admin_guide/custom_resource_definitions.adoc
  admin_guide/topics/crd_overview.adoc
  admin_guide/topics/create_aggregated_cluster_role_crd.adoc
  admin_guide/topics/create_crd.adoc
  admin_guide/topics/create_crd_obj.adoc
  admin_guide/topics/manage_crd_obj.adoc
  architecture/additional_concepts/authorization.adoc
  dev_guide/creating_crd_objects.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/XL

#9382 Fix spec.ports format
  architecture/core_concepts/pods_and_services.adoc
  upgrading/upgrading_known_issues.adoc
Labels: size/XS

#9391 removed link to install docs for a variable
  architecture/topics/router_environment_variables.adoc
Labels: size/XS

#9295 Bug 1574836 Edited AWS info to be more specific about labeling
  install_config/configuring_aws.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9395 removed link to install docs for a variable
  architecture/topics/router_environment_variables.adoc
Labels: size/XS

#9396 removed link to install docs for a variable
  architecture/topics/router_environment_variables.adoc
Labels: size/XS

#9397 removed link to install docs for a variable
  architecture/topics/router_environment_variables.adoc
Labels: size/XS

#8919 added registry-editor and registry-viewer roles info
  install_config/registry/accessing_registry.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S
