Repository openshift/openshift-docs, pull requests merged in 2018-02, with the labels that each got.

#7687 [enterprise-3.4]Bug 1537196, clarified wildcard usage
  install_config/certificate_customization.adoc
Labels: size/M

#7688 [enterprise-3.3]Bug 1537196, clarified wildcard usage
  install_config/certificate_customization.adoc
Labels: size/M

#7635 adjust declarative sample to match recommendation
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/L

#7633 Update local storage documentation
  install_config/configuring_local.adoc
Labels: branch/enterprise-3.9, size/M

#7690 [enterprise-3.7] adjust declarative sample to match recommendation
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: size/L

#7694 [enterprise-3.9] Update local storage documentation
  install_config/configuring_local.adoc
Labels: size/M

#7693 [online-3.7] adjust declarative sample to match recommendation
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: size/L

#7691 [enterprise-3.9] adjust declarative sample to match recommendation
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: size/L

#7692 [online-3.9] adjust declarative sample to match recommendation
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: size/L

#7375 Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: Peer Review Done, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7695 [enterprise-3.5] Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7696 [enterprise-3.7] Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7697 [enterprise-3.9] Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7698 [enterprise-3.6] Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7699 [enterprise-3.4]Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7700 [enterprise-3.3]Bug 1512781, updated the Scenario math
  admin_guide/out_of_resource_handling.adoc
Labels: size/S

#7305 Trello 590 and 711 use file buffer
  admin_guide/overcommit.adoc
Labels: Peer Review Done, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#7703 [enterprise-3.9] Trello 590 and 711 use file buffer
  admin_guide/overcommit.adoc
Labels: size/M

#7702 [enterprise-3.7] Trello 590 and 711 use file buffer
  admin_guide/overcommit.adoc
Labels: size/M

#7701 [enterprise-3.9] advanced_install: installer as system container
  install_config/install/advanced_install.adoc
Labels: size/L

#7704 [enterprise-3.9] Update 'byo' references based on playbook refactoring
  admin_solutions/master_node_config.adoc
  install_config/cluster_metrics.adoc
  install_config/install/advanced_install.adoc
  install_config/install/stand_alone_registry.adoc
  install_config/redeploying_certificates.adoc
  install_config/storage_examples/containerized_heketi_with_dedicated_gluster.adoc
  install_config/upgrading/automated_upgrades.adoc
Labels: size/L

#7564 Bug#1288488 - fixes - added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  using_images/s2i_images/wildfly.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/M

#7706 [dedicated-3.6] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7707 [dedicated-3.7] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7708 [dedicated-3.9] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7709 [enterprise-3.5] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7710 [enterprise-3.6] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7711 [enterprise-3.7] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7712 [enterprise-3.9] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7713 [online-3.7] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7714 [online-3.9] added build process section for all s2i images
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
Labels: size/M

#7596 Bug#1539570 - added info for openshift_logging_es_pvc_prefix variable
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#7620 Added footnote on macvlan to specify network when using multiples
  admin_guide/managing_networking.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-3.9, size/S

#7718 [enterprise-3.9] added footnote on macvlan to specify network when us…
  admin_guide/managing_networking.adoc
Labels: size/S

#7705 fix broken link
  using_images/other_images/jenkins.adoc
Labels: branch/dedicated, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/XS

#6596 Bug 1457945, Clarified default behavior in Garbage Collection docs
  admin_guide/garbage_collection.adoc
Labels: branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#7721 [enterprise-3.9] fix broken link
  using_images/other_images/jenkins.adoc
Labels: size/XS

#7722 [dedicated-3.9] fix broken link
  using_images/other_images/jenkins.adoc
Labels: size/XS

#7723 [online-3.9] fix broken link
  using_images/other_images/jenkins.adoc
Labels: size/XS

#7724 [enterprise-3.5] Bug 1457945, Clarified default behavior in Garbage C…
  admin_guide/garbage_collection.adoc
Labels: size/M

#7725 [enterprise-3.6] Bug 1457945, Clarified default behavior in Garbage C…
  admin_guide/garbage_collection.adoc
Labels: size/M

#7726 [enterprise-3.7] Bug 1457945, Clarified default behavior in Garbage C…
  admin_guide/garbage_collection.adoc
Labels: size/M

#7727 [enterprise-3.9] Bug 1457945, Clarified default behavior in Garbage C…
  admin_guide/garbage_collection.adoc
Labels: size/M

#7728 [enterprise-3.4]Bug 1457945, Clarified default behavior in Garbage Collection docs
  admin_guide/garbage_collection.adoc
Labels: size/M

#7729 [enterprise-3.3]Bug 1457945, Clarified default behavior in Garbage Collection docs
  admin_guide/garbage_collection.adoc
Labels: size/M

#5359 Hide space after line continuation \ due to callout
  getting_started/administrators.adoc
Labels: Peer Review Done, origin-only

#7730 Remove incorrect cronjob -> scheduledjob redirect
  .s2i/httpd-cfg/01-commercial.conf
Labels: lgtm, size/XS

#7608 Fixed line spacing in command example
  dev_guide/pod_autoscaling.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/XS

#7441 Bugzilla 1271482: Added note stating that OCP user names should not contain "/"
  architecture/additional_concepts/other_api_objects.adoc
  install_config/configuring_authentication.adoc
Labels: Peer Review Needed, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7574 correct image tag v3.7 to v3.6 in OCP 3.6 doc
  install_config/install/advanced_install.adoc
Labels: branch/enterprise-3.6, size/S

#7179 Bugzilla 1316593: Adding information to Reclaiming Resources section
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: Peer Review Done, branch/enterprise-3.1, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#7754 [enterprise-3.1] Adding information to Reclaiming Resources section
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/M

#7755 [enterprise-3.2] Adding information to Reclaiming Resources section
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/M

#7760 [enterprise-3.3] Adding information to Reclaiming Resources section
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/M

#7761 [enterprise-3.4] Adding information to Reclaiming Resources section
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/M

#7762 Adjust broken 'latest' redirect
  .s2i/bin/assemble
  .s2i/httpd-cfg/01-commercial.conf
Labels: lgtm, size/XS

#7617 Bugzilla 1539984: Removed section for 3.3 and 3.4 guides
  architecture/networking/routes.adoc
Labels: Peer Review Needed, branch/enterprise-3.3, branch/enterprise-3.4, size/M

#7764 [enterprise-3.3] Removed section for 3.3 and 3.4 guides
  architecture/core_concepts/routes.adoc
Labels: size/M

#7765 [enterprise-3.4] Removed section for 3.3 and 3.4 guides
  architecture/core_concepts/routes.adoc
Labels: size/M

#7577 Trello: Pospispa 566 postpone pvc deletion if used in a pod
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/configuring_pvc_protection.adoc
Labels: Peer Review Needed, branch/dedicated, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/L

#7579 Trello card: Added Kubernetes Storage Metrics via Prometheus section
  install_config/cluster_metrics.adoc
Labels: Peer Review Needed, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#7442 Issue 6022: Fixed broken links to CNS for OCP content
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
Labels: branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7281 Bug 1314564 Add Note to Scale EFK Pods When Changes are Made
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, size/M

#7769 Add NE to all redirects that have the potential to contain anchor tags
  .s2i/httpd-cfg/01-commercial.conf
  .s2i/httpd-cfg/01-community.conf
Labels: size/M

#7779 Bugzilla 1540832: Add local pv changes
  install_config/configuring_local.adoc
Labels: branch/enterprise-3.9, size/L

#7780 Revert "Bugzilla 1540832: Add local pv changes"
  install_config/configuring_local.adoc
Labels: size/L

#7719 Bug#1512813 - added notes for NO_PROXY variable for scaleup playbook
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/http_proxies.adoc
Labels: Peer Review Done, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7078 Added information about --selector to 3.1 docs
  install_config/install/deploy_router.adoc
  install_config/install/docker_registry.adoc
Labels: branch/enterprise-3.1, size/M

#7079 Added information about --selector to 3.2 docs
  install_config/install/deploy_router.adoc
  install_config/install/docker_registry.adoc
Labels: branch/enterprise-3.2, size/M

#7752 async operations/eventual consistency
  architecture/service_catalog/index.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, size/S, to_followup

#7792 Follow-up edits to PR#7752
  architecture/service_catalog/index.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7803 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7802 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7801 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7800 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7799 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7798 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7807 BZ:1544932: Removed content not applicable to dedicated and online
  admin_guide/managing_networking.adoc
Labels: size/S

#7782 enables travis cache feature
  .travis.yml
Labels: size/XS

#7811 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7810 [dedicated-3.6] BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7614 Rm refs to auth_type:config and BZ#1526949 from 3.9+
  install_config/oab_broker_configuration.adoc
Labels: branch/enterprise-3.9, size/M

#7364 New topic for Kubernetes descheduler
  _topic_map.yml
  admin_guide/managing_pods.adoc
  admin_guide/scheduling/descheduler.adoc
Labels: branch/enterprise-3.9, size/L

#7634 Added the Persistent Volume Snapshots topic
  _topic_map.yml
  install_config/persistent_storage/persistent_volume_snapshots.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/L

#7817 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7815 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7816 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7818 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7819 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/M

#7822 [enterprise-3.6] BZ:1544932 Combined fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/M

#7820 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7821 BZ:1544932 - More egress incorrect inclusion fixes
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/tcp_ingress_external_ports.adoc
Labels: size/S

#7823 [enterprise-3.7] Weekly Release: 02/16/18
  admin_guide/revhistory_admin_guide.adoc
  apb_devel/revhistory_apb_devel.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/revhistory_architecture.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/install/advanced_install.adoc
  install_config/revhistory_install_config.adoc
  scaling_performance/revhistory_scaling_performance.adoc
  using_images/revhistory_using_images.adoc
  welcome/revhistory_full.adoc
Labels: size/L

#7824 [enterprise-3.7] Weekly Release: 02/16/18
  admin_guide/garbage_collection.adoc
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/overcommit.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  apb_devel/revhistory_apb_devel.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/images/docker-diagram.png
  architecture/core_concepts/index.adoc
  architecture/revhistory_architecture.adoc
  architecture/service_catalog/index.adoc
  dev_guide/builds/advanced_build_operations.adoc
  dev_guide/builds/images/chained-build.png
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/aggregate_logging.adoc
  install_config/certificate_customization.adoc
  install_config/configuring_authentication.adoc
  install_config/http_proxies.adoc
  install_config/install/advanced_install.adoc
  install_config/oab_broker_configuration.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/persistent_storage_nfs.adoc
  install_config/provisioners.adoc
  install_config/revhistory_install_config.adoc
  scaling_performance/revhistory_scaling_performance.adoc
  using_images/revhistory_using_images.adoc
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  welcome/revhistory_full.adoc
Labels: size/XL

#7825 [enterprise-3.6] Weekly Release: 02/16/18
  admin_guide/garbage_collection.adoc
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/images/docker-diagram.png
  architecture/revhistory_architecture.adoc
  dev_guide/builds/advanced_build_operations.adoc
  dev_guide/builds/images/chained-build.png
  dev_guide/pod_autoscaling.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/aggregate_logging.adoc
  install_config/certificate_customization.adoc
  install_config/configuring_authentication.adoc
  install_config/http_proxies.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/persistent_storage_nfs.adoc
  install_config/provisioners.adoc
  install_config/revhistory_install_config.adoc
  install_config/web_console_customization.adoc
  scaling_performance/revhistory_scaling_performance.adoc
  security/revhistory_security.adoc
  using_images/revhistory_using_images.adoc
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  welcome/revhistory_full.adoc
Labels: size/XL

#7826 [enterprise-3.6] Weekly Release: 02/16/18
  admin_guide/revhistory_admin_guide.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/revhistory_architecture.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/install/advanced_install.adoc
  install_config/revhistory_install_config.adoc
  scaling_performance/revhistory_scaling_performance.adoc
  security/revhistory_security.adoc
  using_images/revhistory_using_images.adoc
  welcome/revhistory_full.adoc
Labels: size/L

#7828 [enterprise-3.5] Weekly Release: 02/16/18
  admin_guide/garbage_collection.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/images/docker-diagram.png
  architecture/revhistory_architecture.adoc
  dev_guide/builds/advanced_build_operations.adoc
  dev_guide/builds/images/chained-build.png
  dev_guide/revhistory_dev_guide.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/certificate_customization.adoc
  install_config/configuring_authentication.adoc
  install_config/http_proxies.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/persistent_storage_nfs.adoc
  install_config/revhistory_install_config.adoc
  install_config/router/f5_router.adoc
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  welcome/revhistory_full.adoc
Labels: size/XXL

#7827 [enterprise-3.5] Weekly Release: 02/16/18
  admin_guide/revhistory_admin_guide.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/revhistory_architecture.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/install/advanced_install.adoc
  install_config/persistent_storage/persistent_storage_nfs.adoc
  install_config/revhistory_install_config.adoc
  welcome/revhistory_full.adoc
Labels: size/L

#7829 [online] Weekly Release: 02/16/18
  admin_guide/iptables.adoc
  admin_guide/managing_networking.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/revhistory_architecture.adoc
  dev_guide/revhistory_dev_guide.adoc
  getting_started/revhistory_getting_started.adoc
  install_config/revhistory_install_config.adoc
  using_images/revhistory_using_images.adoc
  welcome/revhistory_full.adoc
Labels: size/L

#7830 [online] Weekly Release: 02/16/18
  admin_guide/manage_authorization_policy.adoc
  admin_guide/managing_networking.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  architecture/additional_concepts/sdn.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/images/docker-diagram.png
  architecture/revhistory_architecture.adoc
  dev_guide/builds/advanced_build_operations.adoc
  dev_guide/builds/images/chained-build.png
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/pod_autoscaling.adoc
  getting_started/choose_a_plan.adoc
  getting_started/images/active_subscriptions.png
  getting_started/images/online_pro_manage_plan.png
  install_config/configuring_sdn.adoc
  using_images/db_images/mysql.adoc
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  welcome/revhistory_full.adoc
Labels: size/XXL

#7831 [online] Weekly Release: Link Fixes 3: 02/16/18
  architecture/additional_concepts/authorization.adoc
  using_images/db_images/mysql.adoc
Labels: size/M

#7832 Online
  admin_guide/managing_networking.adoc
  admin_guide/sdn_troubleshooting.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/core_concepts/deployments.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/service_catalog/template_service_broker.adoc
  cli_reference/basic_cli_operations.adoc
  dev_guide/dev_tutorials/binary_builds.adoc
  dev_guide/dev_tutorials/maven_tutorial.adoc
  dev_guide/integrating_external_services.adoc
  dev_guide/managing_images.adoc
  dev_guide/openshift_pipeline.adoc
  dev_guide/projects.adoc
  dev_guide/routes.adoc
  using_images/db_images/mariadb.adoc
Labels: size/XL

#7834 [dedicated] Weekly Release: 02/16/18
  _topic_map.yml
  admin_guide/backup_restore.adoc
  admin_guide/manage_nodes.adoc
  admin_guide/managing_networking.adoc
  admin_guide/monitoring_images.adoc
  admin_guide/overcommit.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/images/docker-diagram.png
  architecture/revhistory_architecture.adoc
  architecture/topics/router_environment_variables.adoc
  dev_guide/builds/advanced_build_operations.adoc
  dev_guide/builds/images/chained-build.png
  dev_guide/cron_jobs.adoc
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  dev_guide/managing_images.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/revhistory_dev_guide.adoc
  dev_guide/routes.adoc
  install_config/configuring_pipeline_execution.adoc
  install_config/install/advanced_install.adoc
  install_config/revhistory_install_config.adoc
  release_notes/revhistory_release_notes.adoc
  using_images/db_images/mariadb.adoc
  using_images/other_images/jenkins.adoc
  using_images/revhistory_using_images.adoc
  using_images/s2i_images/dot_net_core.adoc
  using_images/s2i_images/java.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
  using_images/s2i_images/topics/build_process.adoc
  welcome/revhistory_full.adoc
Labels: size/XXL

#7833 Minor fix
  admin_guide/managing_networking.adoc
Labels: size/XS

#7835 [enterprise-3.5] Final Changes
  admin_guide/revhistory_admin_guide.adoc
  architecture/core_concepts/routes.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/install/quick_install.adoc
  install_config/router/customized_haproxy_router.adoc
Labels: size/M

#7837 [enterprise-3.7] Final Changes
  .gitignore
  _topic_map.yml
  _update_rest_api.py
  admin_guide/managing_networking.adoc
  install_config/master_node_configuration.adoc
  rest_api/api/v1.Pod.adoc
  rest_api/api/v1.ReplicationController.adoc
  rest_api/api/v1.SecurityContextConstraints.adoc
  rest_api/apis-apps.openshift.io/v1.DeploymentConfig.adoc
  rest_api/apis-apps/v1beta1.Deployment.adoc
  rest_api/apis-build.openshift.io/v1.Build.adoc
  rest_api/apis-build.openshift.io/v1.BuildConfig.adoc
  rest_api/apis-extensions/v1beta1.Deployment.adoc
  rest_api/apis-extensions/v1beta1.ReplicaSet.adoc
  rest_api/apis-image.openshift.io/v1.ImageStream.adoc
  rest_api/apis-image.openshift.io/v1.ImageStreamImport.adoc
  rest_api/apis-image.openshift.io/v1.ImageStreamTag.adoc
  rest_api/apis-network.openshift.io/v1.ClusterNetwork.adoc
  rest_api/apis-network.openshift.io/v1.HostSubnet.adoc
  rest_api/apis-network.openshift.io/v1.NetNamespace.adoc
  rest_api/apis-oauth.openshift.io/v1.OAuthClient.adoc
  rest_api/apis-security.openshift.io/v1.SecurityContextConstraints.adoc
  rest_api/oapi/v1.Build.adoc
  rest_api/oapi/v1.BuildConfig.adoc
  rest_api/oapi/v1.ClusterNetwork.adoc
  rest_api/oapi/v1.DeploymentConfig.adoc
  rest_api/oapi/v1.HostSubnet.adoc
  rest_api/oapi/v1.ImageStream.adoc
  rest_api/oapi/v1.ImageStreamImport.adoc
  rest_api/oapi/v1.ImageStreamTag.adoc
  rest_api/oapi/v1.NetNamespace.adoc
  rest_api/oapi/v1.OAuthClient.adoc
Labels: size/L

#7838 [dedicated] added missing image
  dev_guide/images/run_on_openshift_buttons.png
Labels: size/XS

#7843 Migration: Dedicated --> OCP 3.6
  _topic_map.yml
  admin_guide/index.adoc
  admin_guide/managing_networking.adoc
  admin_guide/managing_projects.adoc
  admin_guide/quota.adoc
  architecture/additional_concepts/admission_controllers.adoc
  architecture/additional_concepts/authentication.adoc
  architecture/additional_concepts/authorization.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/additional_concepts/sdn.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/deployments.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/infrastructure_components/image_registry.adoc
  architecture/networking/routes.adoc
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/router_environment_variables.adoc
  architecture/topics/routers.adoc
  architecture/topics/sticky_sessions.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/authorization.adoc
  dev_guide/builds/build_environment.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  dev_guide/integrating_external_services.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/S2I_tool.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/projects.adoc
  dev_guide/routes.adoc
  getting_started/dedicated_administrators.adoc
  getting_started/index.adoc
  release_notes/osd_latest_product_updates.adoc
  using_images/db_images/mongodb.adoc
  using_images/other_images/jenkins.adoc
  using_images/s2i_images/perl.adoc
  welcome/index.adoc
Labels: size/XXL

#7845 Migration: Dedicated + Online --> OCP 3.7
  _topic_map.yml
  admin_guide/backup_restore.adoc
  admin_guide/index.adoc
  admin_guide/manage_rbac.adoc
  admin_guide/managing_networking.adoc
  admin_guide/managing_projects.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/quota.adoc
  architecture/additional_concepts/admission_controllers.adoc
  architecture/additional_concepts/authentication.adoc
  architecture/additional_concepts/authorization.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/additional_concepts/sdn.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  architecture/core_concepts/containers_and_images.adoc
  architecture/core_concepts/deployments.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/infrastructure_components/image_registry.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  architecture/networking/routes.adoc
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/openshift_sdn_plugins.adoc
  architecture/topics/router_environment_variables.adoc
  architecture/topics/routers.adoc
  architecture/topics/sticky_sessions.adoc
  cli_reference/manage_cli_profiles.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/authentication.adoc
  dev_guide/authorization.adoc
  dev_guide/builds/build_environment.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  dev_guide/dev_tutorials/maven_tutorial.adoc
  dev_guide/dev_tutorials/openshift_pipeline.adoc
  dev_guide/events.adoc
  dev_guide/images/monitoring_menu.png
  dev_guide/images/notifications_UI.png
  dev_guide/images/success_message.png
  dev_guide/integrating_external_services.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/S2I_tool.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/projects.adoc
  dev_guide/routes.adoc
  dev_guide/selector_label_volume_binding.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/choose_a_plan.adoc
  getting_started/dedicated_administrators.adoc
  getting_started/images/active_subscriptions.png
  getting_started/images/online_pro_manage_plan.png
  getting_started/images/web_console_about.png
  getting_started/index.adoc
  release_notes/online_known_issues.adoc
  release_notes/online_release_notes.adoc
  release_notes/osd_latest_product_updates.adoc
  using_images/db_images/mongodb.adoc
  using_images/s2i_images/java.adoc
  welcome/index.adoc
Labels: size/XXL

#7847 Migration: Minor Link Fix
  dev_guide/managing_images.adoc
Labels: size/XS

#7846 Migration: Build online and dedicated from enterprise branches
  _distro_map.yml
Labels: size/XS

#7848 Migration: Fixes
  welcome/index.adoc
Labels: size/XS

#7053 Bug 1500614 Document External Access to Elasticsearch
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#7787 Bug#1543291 - Added a note for Azure disk delays
  install_config/persistent_storage/persistent_storage_azure.adoc
Labels: Peer Review Done, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7863 Removed custom SCC note
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/S

#7864 Removed custom SCC notes
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: size/S

#7868 BZ1500614 Revision History
  install_config/revhistory_install_config.adoc
Labels: size/S

#7857 BZ1500614 Revision History
  install_config/revhistory_install_config.adoc
Labels: size/S

#7856 BZ1500614 Revision History
  install_config/revhistory_install_config.adoc
Labels: size/S

#7592 Bug - 1537851 Added value for provider: local for cluster loader topic
  scaling_performance/using_cluster_loader.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7872 arranged ipsec info
  admin_guide/ipsec.adoc
Labels: branch/enterprise-3.9, size/M

#5709 Updated commands to `oc adm drain node`
  admin_guide/manage_nodes.adoc
Labels: Peer Review Done, branch/enterprise-3.5, branch/enterprise-3.6, size/M, to_followup

#7849 Include the controller verification for 3.7
  day_two_guide/environment_health_checks.adoc
  day_two_guide/topics/controller_role_verification.adoc
Labels: branch/enterprise-3.7, branch/enterprise-3.9, size/M

#7876 [enterprise-3.5] PR#5709 CP and Revision History
  admin_guide/manage_nodes.adoc
  admin_guide/revhistory_admin_guide.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#6864 Add dnsmasq configuration per BZ
  install_config/upgrading/manual_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.6, size/L

#7885 Revision History
  install_config/revhistory_install_config.adoc
Labels: size/S

#7886 BZ-1518022 Full Revision History
  welcome/revhistory_full.adoc
Labels: size/XS

#7887 Fixed weird formatting in Rev History
  admin_guide/revhistory_admin_guide.adoc
Labels: size/XS

#7880 Added --dry-run option for `oc adm drain` for 3.7
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.7, size/XS

#7889 [enterprise-3.7] Added --dry-run option for oc adm drain for 3.7
  admin_guide/manage_nodes.adoc
  admin_guide/revhistory_admin_guide.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#4177 Followup edits to the scaling and performance networking info
  scaling_performance/network_optimization.adoc
Labels: Peer Review Done, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7895 Link Fixes
  day_two_guide/host_level_tasks.adoc
  day_two_guide/project_level_tasks.adoc
  day_two_guide/topics/deprecating_master.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
Labels: size/S

#7865 Changed the actual path and filename format style
  install_config/downgrade.adoc
Labels: Peer Review Done, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#7899 BZ1500614 Revision History Update
  install_config/revhistory_install_config.adoc
  welcome/revhistory_full.adoc
Labels: size/S

#7898 BZ1500614 Revision History Update
  welcome/revhistory_full.adoc
Labels: size/XS

#7897 BZ1500614 Revision History Update
  install_config/revhistory_install_config.adoc
  welcome/revhistory_full.adoc
Labels: size/XS

#7867 Added new topic
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/configuring_pvc_protection.adoc
Labels: Peer Review Done, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7904 Conditionalized architecture guide
  architecture/additional_concepts/storage.adoc
Labels: size/XS

#7905 Add new topic on configuring PVC protection
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/configuring_pvc_protection.adoc
Labels: size/L

#7313 Update scheduling docs per BZ
  _topic_map.yml
  admin_guide/scheduling/index.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  architecture/additional_concepts/admission_controllers.adoc
Labels: Peer Review Needed, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XXL

#7841 Update the docs to highlight that -z can prevent typos that can cause unintentional access
  admin_guide/manage_scc.adoc
  admin_guide/service_accounts.adoc
Labels: branch/dedicated, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, branch/online, size/S

#7908 Reorganizedd scheduler doc and new pod placement topic & rev history
  _topic_map.yml
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/scheduling/index.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  architecture/additional_concepts/admission_controllers.adoc
  welcome/revhistory_full.adoc
Labels: size/XXL

#7909 [Enterprise 3.9] Cherry-pick of PR#7841 + Revision History
  admin_guide/manage_scc.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/service_accounts.adoc
  dev_guide/revhistory_dev_guide.adoc
  install_config/revhistory_install_config.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#7911 [Enterprise 3.7] Cherry-pick of PR#7841 + Revision History
  admin_guide/manage_scc.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/service_accounts.adoc
  dev_guide/revhistory_dev_guide.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#7913 Rev history fix
  dev_guide/revhistory_dev_guide.adoc
Labels: size/XS

#7914 Reorganized scheduler doc and new pod placement topic & rev history
  _topic_map.yml
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/scheduling/index.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  architecture/additional_concepts/admission_controllers.adoc
Labels: size/XXL

#7915 [Enterprise 3.6]Cherry-pick of PR#7841 + Revision History
  admin_guide/manage_scc.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/service_accounts.adoc
  dev_guide/revhistory_dev_guide.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#7917 [Enterprise 3.5]Cherry-pick of PR#7841 + Revision History
  admin_guide/manage_scc.adoc
  admin_guide/revhistory_admin_guide.adoc
  admin_guide/service_accounts.adoc
  dev_guide/revhistory_dev_guide.adoc
  welcome/revhistory_full.adoc
Labels: size/M

#7881 Added oc adm drain options for 3.9
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.9, size/S

#7916 fixed rev history link
  admin_guide/revhistory_admin_guide.adoc
Labels: size/XS
