Repository openshift/openshift-docs, pull requests merged in 2018-11, with the labels that each got.

#12729 bug 1640881 etcd note
  day_two_guide/topics/proc_scaling-etcd-manual.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12735 Disconnected Installation - Add missing images to docker save command
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.9, size/XS

#12740 [enterprise-3.10] bug 1641134 removing registry instructions
  getting_started/configure_openshift.adoc
Labels: size/L

#12736 Fix issues#12730: Correct the hostPath indentation
  install_config/configuring_local.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12741 [enterprise-3.7] bug 1641134 removing registry instructions
  getting_started/configure_openshift.adoc
Labels: size/L

#12742 [enterprise-3.6] bug 1641134 removing registry instructions
  getting_started/configure_openshift.adoc
Labels: size/L

#12743 [enterprise-3.9] bug 1641134 removing registry instructions
  getting_started/configure_openshift.adoc
Labels: size/L

#12726 Added oc commands to 3.7
  cli_reference/basic_cli_operations.adoc
Labels: branch/enterprise-3.7, size/L

#12714 Added oc commands to 3.9
  cli_reference/basic_cli_operations.adoc
Labels: branch/enterprise-3.9, size/L

#12751 Fixed an typo in ordered list
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.11, size/XS

#12749 Add missing backslash after registry-console
  install_config/install/disconnected_install.adoc
Labels: branch/enterprise-3.9, needs-ok-to-test, size/XS

#12754 install: fix typo mistake [for for] -> [for]
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12757 install: fix typo mistake [for for] -> [for]
  install/configuring_inventory_file.adoc
Labels: size/XS

#12763 fixed all.yml header/anchor
  install_config/topics/ocp_osp_provisioning.adoc
Labels: size/XS

#12753 Fix typo in image change trigger
  dev_guide/builds/triggering_builds.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12538 Bug 1437137, Added storage management guidance
  install/prerequisites.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, lgtm, size/M

#12780 Applied PR#12538 to 3.7
  install_config/install/prerequisites.adoc
Labels: branch/enterprise-3.7, size/M

#12782 disconnected_install: fix typo (orge_url->oreg_url)
  install/disconnected_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12785 [enterprise-3.10] bug 1640687 adding command to restart the controllers
  admin_guide/encrypting_data.adoc
  day_two_guide/topics/proc_scaling-etcd-manual.adoc
  install_config/configuring_sdn.adoc
  install_config/master_node_configuration.adoc
  servicemesh-install/topics/install-prerequisites.adoc
Labels: size/S

#12691 Add OSDK 0.1.0 migration doc
  _topic_map.yml
  modules/about-operator-sdk.adoc
  modules/building-memcached-operator-using-osdk.adoc
  modules/creating-new-osdk-v0-1-0-project.adoc
  modules/installing-operator-sdk-cli.adoc
  modules/managing-memcached-operator-using-olm.adoc
  modules/migrating-custom-types-pkg-apis.adoc
  modules/migrating-reconcile-code.adoc
  modules/operator-project-staffolding-layout.adoc
  operators/migrating-to-osdk-v0-1-0.adoc
  operators/osdk-getting-started.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#12755 Clarify descriptions of master certificate files
  install_config/certificate_customization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12717 Fix BZ#1644604: Add Ansible usage for vSphere provider in v3.9
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.9, size/S

#12795 Add migration guide & update "Getting started" for OSDK v0.1.0
  _topic_map.yml
  modules/about-operator-sdk.adoc
  modules/building-memcached-operator-using-osdk.adoc
  modules/creating-new-osdk-v0-1-0-project.adoc
  modules/installing-operator-sdk-cli.adoc
  modules/managing-memcached-operator-using-olm.adoc
  modules/migrating-custom-types-pkg-apis.adoc
  modules/migrating-reconcile-code.adoc
  modules/operator-project-staffolding-layout.adoc
  operators/migrating-to-osdk-v0-1-0.adoc
  operators/modules
  operators/osdk-getting-started.adoc
Labels: origin-only, size/XL

#12492 highlight in the documentation how users can increase replica counts
  install_config/aggregate_logging.adoc
  install_config/aggregate_logging_sizing.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#12802 [enterprise-3.9] highlight in the documentation how users can increase replica counts
  install_config/aggregate_logging.adoc
  install_config/aggregate_logging_sizing.adoc
Labels: size/L

#12800 [enterprise-3.7] highlight in the documentation how users can increase replica counts
  install_config/aggregate_logging.adoc
  install_config/aggregate_logging_sizing.adoc
Labels: size/L

#12796 Remove PV Resize Tech Preview Notes
  dev_guide/expanding_persistent_volumes.adoc
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/M

#12792 Bug 1645657, added note about IBM Power issue
  release_notes/ocp_3_10_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/S

#12806 Updated image name
  release_notes/ocp_3_10_release_notes.adoc
Labels: size/XS

#12099 Missing Binary data in Configmap feature in documentation
  dev_guide/configmaps.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#12805 remove scheduler.alpha.kubernetes.io/affinity
  admin_guide/manage_nodes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#12810 [enterprise-3.9] remove scheduler.alpha.kubernetes.io/affinity
  admin_guide/manage_nodes.adoc
Labels: size/S

#12811 [enterprise-3.10] remove scheduler.alpha.kubernetes.io/affinity
  admin_guide/manage_nodes.adoc
Labels: size/S

#12813 [enterprise-3.11] remove scheduler.alpha.kubernetes.io/affinity
  admin_guide/manage_nodes.adoc
Labels: size/S

#12794 Adding cri-o runtime docs
  _topic_map.yml
  crio/crio_runtime.adoc
  crio/modules
  modules/crio_arch.adoc
  modules/crio_get.adoc
  modules/crio_setconfig.adoc
  modules/crio_trouble.adoc
  modules/modules
Labels: Peer Review Needed, branch/enterprise-3.11, size/XL

#12818 Changes from tech editing pass
  crio/crio_runtime.adoc
  modules/crio_add.adoc
  modules/crio_arch.adoc
  modules/crio_get.adoc
  modules/crio_setconfig.adoc
  modules/crio_trouble.adoc
Labels: branch/enterprise-3.11, size/L

#12821 re-adding modules
  cloud_providers/modules
Labels: size/XS

#12822 fixing modules issue
  crio/modules
  modules/modules
Labels: size/XS

#12692 The osm_cluster_network_cidr, openshift_portal_net, and osm_host_subnet_length no longer set by default.
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12826 Fix typo in Service Catalog docs
  architecture/service_catalog/index.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12835 Added release notes for RHSA-2018-2709
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#12704 Fix etcd backup and restore for API v2 and v3
  day_two_guide/topics/proc_backing-up-etcd.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#12841 Updated cluster loader command
  scaling_performance/using_cluster_loader.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#12801 install updates draft
  installation/installing-customizations-cloud.adoc
  installation/installing-existing-hosts.adoc
  installation/installing-quickly-cloud.adoc
  modules/cloud_installations.adoc
  modules/installation-overview.adoc
Labels: branch/enterprise-4.0, size/L

#12463 Bug 1634172 fix edit router service command
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#12849 install_config: fix typo [by modifying by modifying] -> [by modifying]
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, needs-ok-to-test, size/M

#12860 Applied PR#12849 to 3.6
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.6, size/M

#12861 removing a note
  install/prerequisites.adoc
Labels: branch/enterprise-3.10, size/XS

#12848 TP4 documentation and release notes updates
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-fixed-issues.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: branch/enterprise-3.11, size/S

#12870 Fix typo: and -> an
  modules/installing-operator-sdk-cli.adoc
Labels: origin-only, size/XS

#12878 [enterprise-3.10] updates to Apache config
  install_config/configuring_authentication.adoc
Labels: size/L

#12879 [enterprise-3.9] updates to Apache config
  install_config/configuring_authentication.adoc
Labels: size/L

#12882 ~ Added examples of node labels and xref link, per BZ1647168
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#12823 Updated versions for maistra-0.4.0 release: MAISTRA-107
  servicemesh-install/topics/install.adoc
Labels: branch/enterprise-3.11, size/S

#12750 Remove references to docker.
  admin_guide/diagnostics_tool.adoc
  admin_guide/manage_scc.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  contributing_to_docs/term_glossary.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics_dynatrace/installation.adoc
  day_two_guide/topics_dynatrace/troubleshooting.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  install/configuring_inventory_file.adoc
  install/running_install.adoc
  install_config/aggregate_logging.adoc
  install_config/configuring_local.adoc
  install_config/configuring_nuagesdn.adoc
  install_config/master_node_configuration.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/router/customized_haproxy_router.adoc
  scaling_performance/using_cluster_loader.adoc
  using_images/xpaas_images/fuse.adoc
Labels: branch/enterprise-3.11, size/M

#12885 [enterprise-3.11] Remove references to docker.
  admin_guide/diagnostics_tool.adoc
  admin_guide/manage_scc.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  creating_images/guidelines.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/network_connectivity.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  install/configuring_inventory_file.adoc
  install/running_install.adoc
  install_config/aggregate_logging.adoc
  install_config/configuring_local.adoc
  install_config/configuring_nuagesdn.adoc
  install_config/master_node_configuration.adoc
  install_config/registry/extended_registry_configuration.adoc
  install_config/router/customized_haproxy_router.adoc
  scaling_performance/using_cluster_loader.adoc
Labels: size/M

#12887 Revert "~ Added examples of node labels and xref link, per BZ1647168"
  install_config/aggregate_logging.adoc
Labels: size/S

#12892 Fixed 3.10 heading to show 3.10.66
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/XS

#12871 Add --from-file to create secret
  install_config/registry/deploy_registry_existing_clusters.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, lgtm, size/XS

#12899 Add build inputs modules
  builds/creating-build-inputs.adoc
  modules/builds-adding-input-secrets-configmaps.adoc
  modules/builds-adding-source-clone-secrets.adoc
  modules/builds-automatically-add-source-clone-secrets.adoc
  modules/builds-binary-source.adoc
  modules/builds-custom-strategy.adoc
  modules/builds-define-build-inputs.adoc
  modules/builds-docker-credentials-private-registries.adoc
  modules/builds-docker-strategy.adoc
  modules/builds-dockerfile-source.adoc
  modules/builds-gitconfig-file-secured-git.adoc
  modules/builds-gitconfig-file.adoc
  modules/builds-image-source.adoc
  modules/builds-input-secrets-configmaps.adoc
  modules/builds-manually-add-source-clone-secrets.adoc
  modules/builds-source-code.adoc
  modules/builds-source-secret-basic-auth.adoc
  modules/builds-source-secret-combinations-basic-auth-ca.adoc
  modules/builds-source-secret-combinations-basic-auth-gitconfig-ca.adoc
  modules/builds-source-secret-combinations-basic-auth-gitconfig.adoc
  modules/builds-source-secret-combinations-gitconfig-ca.adoc
  modules/builds-source-secret-combinations-ssh-gitconfig.adoc
  modules/builds-source-secret-combinations.adoc
  modules/builds-source-secret-ssh-key-auth.adoc
  modules/builds-source-secret-trusted-ca.adoc
  modules/builds-source-to-image.adoc
  modules/builds-using-external-artifacts.adoc
  modules/builds-using-proxy-git-cloning.adoc
  modules/define-build-inputs.adoc
Labels: size/XXL, to_followup

#12889 Hand edited some more Docker commands.
  contributing_to_docs/term_glossary.adoc
  creating_images/custom.adoc
  creating_images/guidelines.adoc
  creating_images/s2i_testing.adoc
  day_two_guide/docker_tasks.adoc
  getting_started/access_your_services.adoc
  getting_started/administrators.adoc
  getting_started/install_openshift.adoc
  scaling_performance/host_practices.adoc
  scaling_performance/install_practices.adoc
  scaling_performance/optimizing_compute_resources.adoc
  scaling_performance/optimizing_storage.adoc
  servicemesh-install/topics/install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/os_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#12903 [enterprise-3.11] Hand edited some more Docker commands.
  creating_images/custom.adoc
  creating_images/guidelines.adoc
  creating_images/s2i_testing.adoc
  day_two_guide/docker_tasks.adoc
  getting_started/access_your_services.adoc
  getting_started/administrators.adoc
  getting_started/install_openshift.adoc
  scaling_performance/host_practices.adoc
  scaling_performance/install_practices.adoc
  scaling_performance/optimizing_compute_resources.adoc
  scaling_performance/optimizing_storage.adoc
  servicemesh-install/topics/install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/os_upgrades.adoc
Labels: size/L

#12083 reference deployment additions
  install_config/configuring_aws.adoc
  install_config/topics/aws_service_account.adoc
  install_config/topics/configuring_for_aws_registry-proc.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/L

#12912 images, parent-context etc
  applications_and_projects/images
  authentication/images
  backup_and_restore/images
  builds/creating-build-inputs.adoc
  builds/images
  cloud_providers/images
  contributing_to_docs/images
  images/PLACEHOLDER
  installation/images
  logging/efk-logging-curator.adoc
  logging/efk-logging-deploy.adoc
  logging/efk-logging-driver.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-exported-fields.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-manual-rollout.adoc
  logging/efk-logging-systemd.adoc
  logging/efk-logging-troubleshooting.adoc
  logging/efk-logging-uninstall.adoc
  logging/efk-logging.adoc
  logging/images
  masters/images
  metrics/images
  mod_docs_guide/images
  modules/common-attributes.adoc
  networking/images
  nodes/images
  openshift_images/PLACEHOLDER
  openshift_images/images
  openshift_images/modules
  operators/images
  planning/images
  registry/images
  router/images
  scalability_and_performance/images
  storage/images
  upgrading/images
  users_and_roles/images
Labels: branch/enterprise-4.0, size/L

#12918 adding common_attributes module to install assemblies
  installation/installing-customizations-cloud.adoc
  installation/installing-existing-hosts.adoc
  installation/installing-quickly-cloud.adoc
Labels: branch/enterprise-4.0, size/S

#12838 Added release notes for RHBA-2018:3537
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/L

#12862 Added Release Notes for 3.10.72
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#12922 BZ1643492 - edit in Adding Hosts section OCP 3.11
  admin_guide/topics/proc_adding-hosts.adoc
Labels: branch/enterprise-3.11, size/XS

#12924 Revert "BZ1643492 - edit in Adding Hosts section OCP 3.11"
  admin_guide/topics/proc_adding-hosts.adoc
Labels: size/XS

#12863 Added Release Notes for 3.9.51
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#12926 Added release notes for OCP 3.7.72
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/S

#12764 Fix the broken Atomic Registry link
  install_config/install/stand_alone_registry.adoc
Labels: branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, size/XS

#12089 Drop oc types command
  cli_reference/basic_cli_operations.adoc
Labels: branch/enterprise-4.0, size/XS

#12941 removed TP for openstack
  install/running_install.adoc
Labels: size/S

#12940 Fix persistent volume reclaim policy, bug 1652782
  architecture/additional_concepts/storage.adoc
Labels: size/XS

#12786 set kibana session timeout to 168 hours
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/XS

#12948 changing anchor text per translation feedback
  install/prerequisites.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12867 Added Scaling the cluster monitoring Operator content to 4.0
  _topic_map.yml
  modules/prometheus-database-storage-requirements.adoc
  modules/scaling-prometheus-components.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
Labels: branch/enterprise-4.0, size/L

#12517 Update repos orgazation to sclorg
  dev_guide/dev_tutorials/ruby_on_rails.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  using_images/db_images/mongodb.adoc
  using_images/db_images/mysql.adoc
Labels: branch/enterprise-3.1, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#12907 adding cluster-reader aggregation
  architecture/additional_concepts/authorization.adoc
  modules/proc_creating-aggregated-cluster-role.adoc
Labels: Add to 4.0 Docs, Peer Review Done, branch/enterprise-3.11, size/S

#12963 [enterprise-3.1] Update some urls
  creating_images/guidelines.adoc
  creating_images/s2i_testing.adoc
  dev_guide/app_tutorials/quickstarts.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/builds.adoc
  dev_guide/new_app.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/developers/developers_cli.adoc
  getting_started/developers/developers_console.adoc
  using_images/db_images/mongodb.adoc
  using_images/db_images/mysql.adoc
  using_images/db_images/postgresql.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12962 [enterprise-3.2] Update some urls
  creating_images/guidelines.adoc
  creating_images/s2i_testing.adoc
  dev_guide/app_tutorials/quickstarts.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/builds.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/new_app.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  install_config/build_defaults_overrides.adoc
  install_config/install/docker_registry.adoc
  using_images/db_images/mongodb.adoc
  using_images/db_images/mysql.adoc
  using_images/db_images/postgresql.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12961 [enterprise-3.3] Update some urls
  admin_solutions/master_node_config.adoc
  creating_images/guidelines.adoc
  creating_images/s2i_testing.adoc
  dev_guide/app_tutorials/quickstarts.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/application_lifecycle/new_app.adoc
  dev_guide/builds.adoc
  dev_guide/managing_images.adoc
  dev_guide/migrating_applications/quickstart_examples.adoc
  dev_guide/migrating_applications/web_framework_applications.adoc
  dev_guide/templates.adoc
  getting_started/administrators.adoc
  getting_started/basic_walkthrough.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  getting_started/developers_console.adoc
  install_config/build_defaults_overrides.adoc
  install_config/install/docker_registry.adoc
  using_images/db_images/mongodb.adoc
  using_images/db_images/mysql.adoc
  using_images/db_images/postgresql.adoc
  using_images/s2i_images/nodejs.adoc
  using_images/s2i_images/perl.adoc
  using_images/s2i_images/php.adoc
  using_images/s2i_images/python.adoc
  using_images/s2i_images/ruby.adoc
Labels: size/L

#12960 [enterprise-3.4] Update some urls
  admin_solutions/master_node_config.adoc
  creating_images/s2i_testing.adoc
  dev_guide/app_tutorials/ruby_on_rails.adoc
  dev_guide/builds/build_inputs.adoc
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  install_config/build_defaults_overrides.adoc
  install_config/install/docker_registry.adoc
  release_notes/ocp_3_4_release_notes.adoc
  using_images/db_images/mongodb.adoc
  using_images/db_images/mysql.adoc
  using_images/db_images/postgresql.adoc
Labels: size/M

#12928 BZ1643492 edited Adding Hosts section
  admin_guide/topics/proc_adding-hosts.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#12973 fixed id statement
  modules/efk-logging-about-curator.adoc
  modules/efk-logging-about-elasticsearch.adoc
  modules/efk-logging-about-eventrouter.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-about-kibana.adoc
  modules/efk-logging-about-ops-cluster.adoc
  modules/efk-logging-about.adoc
  modules/efk-logging-curator-actions.adoc
  modules/efk-logging-curator-configuration.adoc
  modules/efk-logging-curator-configure.adoc
  modules/efk-logging-deploy-certificates.adoc
  modules/efk-logging-deploy-eventrouter.adoc
  modules/efk-logging-deploy-label.adoc
  modules/efk-logging-deploy-memory.adoc
  modules/efk-logging-deploy-ops-cluster.adoc
  modules/efk-logging-deploy-playbook.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-driver-changing.adoc
  modules/efk-logging-driver-viewing.adoc
  modules/efk-logging-elasticsearch-admin.adoc
  modules/efk-logging-elasticsearch-exposing.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-persistent-storage.adoc
  modules/efk-logging-elasticsearch-scaling.adoc
  modules/efk-logging-exported-fields-aushape.adoc
  modules/efk-logging-exported-fields-collectd.adoc
  modules/efk-logging-exported-fields-default.adoc
  modules/efk-logging-exported-fields-docker.adoc
  modules/efk-logging-exported-fields-kubernetes.adoc
  modules/efk-logging-exported-fields-ovirt.adoc
  modules/efk-logging-exported-fields-rsyslog.adoc
  modules/efk-logging-exported-fields-systemd.adoc
  modules/efk-logging-exported-fields-tlog.adoc
  modules/efk-logging-external-elasticsearch.adoc
  modules/efk-logging-external-fluentd.adoc
  modules/efk-logging-external-syslog.adoc
  modules/efk-logging-fluentd-connections.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-kibana-console.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-kibana-visualize.adoc
  modules/efk-logging-manual-rollout-full.adoc
  modules/efk-logging-manual-rollout-rolling.adoc
  modules/efk-logging-storage-considerations.adoc
  modules/efk-logging-systemd-rate-limiting.adoc
  modules/efk-logging-systemd-scaling.adoc
  modules/efk-logging-troubleshooting-cryptic.adoc
  modules/efk-logging-troubleshooting-loop.adoc
  modules/efk-logging-troubleshooting-proxy.adoc
  modules/efk-logging-troubleshooting-unknown.adoc
  modules/efk-logging-uninstall-efk-eventrouter.adoc
  modules/efk-logging-uninstall-efk-ops.adoc
  modules/efk-logging-uninstall-efk.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
Labels: branch/enterprise-4.0, size/L

#12974 Added 3.10.72 IBM POWER LE Packages and Images Update to the release notes
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#12979 Correct command for stopping node service. Fixes #12947
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12984 Remove a uncorrect reference link of CustomPodDNS
  admin_guide/disabling_features.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12631 bug 1639080 clarifying insecure connection override
  install_config/syncing_groups_with_ldap.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S
