Repository openshift/openshift-docs, pull requests merged in 2018-06, with the labels that each got.

#9686 Bug 1554389 Added links to allocating node resources section
  day_two_guide/host_level_tasks.adoc
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9616 Bug 1547913 Added more info on firewalld installs
  install_config/install/advanced_install.adoc
  install_config/install/prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9717 Revert "Removed section for 3.3 and 3.4 guides"
  architecture/networking/routes.adoc
Labels: size/M

#9720 Made fewer conditionals
  architecture/networking/routes.adoc
Labels: size/S

#9722 Made fewer conditionals
  architecture/networking/routes.adoc
Labels: size/L

#9721 Made fewer conditionals
  architecture/networking/routes.adoc
Labels: size/S

#9701 bug 1572654 - adding patch permission to clusterrole
  admin_guide/manage_rbac.adoc
Labels: branch/enterprise-3.7, size/XS

#9724 Wrong yaml snippet of the master-config.yaml file (named certificates nesting)
  install_config/certificate_customization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9

#9727 [enterprise-3.7]Update certificate_customization.adoc
  install_config/certificate_customization.adoc
Labels: size/L

#9728 [enterprise-3.6]Update certificate_customization.adoc
  install_config/certificate_customization.adoc
Labels: size/M

#9729 [enterprise-3.5]Update certificate_customization.adoc
  install_config/certificate_customization.adoc
Labels: size/M

#9730 [enterprise-3.4]Update certificate_customization.adoc
  install_config/certificate_customization.adoc
Labels: size/M

#9708 Bug 1423067, added Supported Security Version statement to Notable Technical Changes
  release_notes/ocp_3_4_release_notes.adoc
Labels: branch/enterprise-3.4, size/XS

#9731 Added TLS security statement
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9

#9732 [enterprise-3.5]Added TLS security statement
  release_notes/ocp_3_5_release_notes.adoc
Labels: size/XS

#9733 [enterprise-3.6]Added TLS security statement
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/XS

#9736 wrong slash in oc command examples
  admin_guide/manage_users.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9648 Bug 1526147: Add 'Working with Remote Clusters' APB doc
  apb_devel/writing/getting_started.adoc
  apb_devel/writing/reference.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#8654 Allow to diasble OpenShift features
  _topic_map.yml
  admin_guide/disabling_features.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#9742 document explicit openstack block version configuration
  install_config/configuring_openstack.adoc
Labels: branch/enterprise-3.6, branch/enterprise-3.7, size/XS

#9297 Bug#1576125 - fixes - added note for handling changes in the azure storageclass
  install_config/persistent_storage/dynamically_provisioning_pvs.adoc
Labels: Peer Review Done, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9752 Link Fixes
  admin_guide/managing_networking.adoc
  architecture/additional_concepts/dynamic_admission_controllers.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/routes.adoc
  architecture/topics/alternate_backends_weights.adoc
  architecture/topics/haproxy_template_router.adoc
  dev_guide/executing_remote_commands.adoc
  dev_guide/port_forwarding.adoc
Labels: size/M

#9754 Link Fixes
  admin_guide/managing_networking.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/routes.adoc
  architecture/topics/alternate_backends_weights.adoc
  architecture/topics/haproxy_template_router.adoc
  dev_guide/executing_remote_commands.adoc
  dev_guide/port_forwarding.adoc
Labels: size/M

#9755 Link Fixes
  admin_guide/managing_networking.adoc
  architecture/additional_concepts/dynamic_admission_controllers.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/routes.adoc
  architecture/topics/alternate_backends_weights.adoc
  architecture/topics/haproxy_template_router.adoc
  dev_guide/executing_remote_commands.adoc
  dev_guide/port_forwarding.adoc
Labels: size/M

#9753 Link Fixes
  admin_guide/managing_networking.adoc
  architecture/additional_concepts/dynamic_admission_controllers.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/routes.adoc
  architecture/topics/alternate_backends_weights.adoc
  architecture/topics/haproxy_template_router.adoc
  dev_guide/executing_remote_commands.adoc
  dev_guide/port_forwarding.adoc
Labels: size/M

#9756 Removed contributing to docs from branches other than master
  contributing_to_docs/contributing.adoc
  contributing_to_docs/create_or_edit_content.adoc
  contributing_to_docs/doc_guidelines.adoc
  contributing_to_docs/templates/overview_topic_template.adoc
  contributing_to_docs/templates/rev_history.adoc
  contributing_to_docs/templates/topic_template.adoc
  contributing_to_docs/term_glossary.adoc
  contributing_to_docs/tools_and_setup.adoc
Labels: size/XXL

#9757 Fixed #8985 for 3.1 Docs
  install_config/install/prerequisites.adoc
Labels: size/XS

#9388 Redirects docker_images/index -> other_images/other_container_images
  .s2i/httpd-cfg/01-commercial.conf
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9632 Arranged third party networking vendors info
  _topic_map.yml
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/network_plugins.adoc
  architecture/networking/routes.adoc
  architecture/topics/contiv.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/flannel.adoc
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/kuryr.adoc
  architecture/topics/nuage.adoc
  architecture/topics/routers.adoc
  install_config/router/default_haproxy_router.adoc
  install_config/router/f5_router.adoc
  install_config/router/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.9, size/L

#9760 [enterprise-3.10] Arranged third party content in arch guide
  _topic_map.yml
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/network_plugins.adoc
  architecture/networking/routes.adoc
  architecture/topics/contiv.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/flannel.adoc
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/kuryr.adoc
  architecture/topics/nuage.adoc
  architecture/topics/routers.adoc
  install_config/router/default_haproxy_router.adoc
  install_config/router/f5_router.adoc
  install_config/router/index.adoc
Labels: size/L

#9761 Arranged third party content in arch guide
  _topic_map.yml
  architecture/networking/assembly_available_router_plugins.adoc
  architecture/networking/haproxy-router.adoc
  architecture/networking/network_plugins.adoc
  architecture/networking/routes.adoc
  architecture/topics/contiv.adoc
  architecture/topics/f5_big_ip.adoc
  architecture/topics/flannel.adoc
  architecture/topics/haproxy_template_router.adoc
  architecture/topics/kuryr.adoc
  architecture/topics/nuage.adoc
  architecture/topics/routers.adoc
  install_config/router/default_haproxy_router.adoc
  install_config/router/f5_router.adoc
  install_config/router/index.adoc
Labels: size/L

#9762 Redirect for HAProxy Router
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#9038 document custom initiator iqn
  install_config/persistent_storage/persistent_storage_iscsi.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/M

#9681 add note about using cli in other distros
  cli_reference/get_started_cli.adoc
Labels: lgtm, size/S

#9107 Rework of Online docs for Fuse
  _topic_map.yml
  getting_started/choose_a_plan.adoc
  getting_started/manage_your_plan/images/active_subscriptions.png
  getting_started/manage_your_plan/images/online_pro_manage_plan.png
  getting_started/manage_your_plan/online.adoc
Labels: branch/online, size/L

#9776 [enterprise-3.9]Rework of Online docs for Fuse
  _topic_map.yml
  getting_started/choose_a_plan.adoc
  getting_started/manage_your_plan/images/active_subscriptions.png
  getting_started/manage_your_plan/images/online_pro_manage_plan.png
  getting_started/manage_your_plan/online.adoc
Labels: size/L

#9777 [enterprise-3.10]Rework of Online docs for Fuse
  _topic_map.yml
  getting_started/choose_a_plan.adoc
  getting_started/manage_your_plan/images/active_subscriptions.png
  getting_started/manage_your_plan/images/online_pro_manage_plan.png
  getting_started/manage_your_plan/online.adoc
Labels: size/L

#9600 bug 1464401 etcd restore clarifications
  admin_guide/backup_restore.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#8802 Provisioning persistent volumes using OpenStack Manila
  _topic_map.yml
  install_config/persistent_storage/persistent_storage_manila.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#9035 Edit suggested in file
  admin_guide/out_of_resource_handling.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9675 BZ 1583143 - Add info on configuring zone labels
  install_config/configuring_openstack.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/M

#9645 Add edits to PR 8990
  dev_guide/expanding_persistent_volumes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9

#9796 [enterprise-3.10] Add edits to PR 8990
  dev_guide/expanding_persistent_volumes.adoc
Labels: size/S

#8836 Removed references to Quick Installer for 3.10
  _topic_map.yml
  admin_guide/backup_restore.adoc
  admin_guide/manage_nodes.adoc
  day_two_guide/topics/adding_master_host.adoc
  getting_started/install_openshift.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_sdn.adoc
  install_config/install/host_preparation.adoc
  install_config/install/index.adoc
  install_config/install/planning.adoc
  install_config/install/rpm_vs_containerized.adoc
  install_config/install/stand_alone_registry.adoc
  install_config/master_node_configuration.adoc
  upgrading/automated_upgrades.adoc
  upgrading/blue_green_deployments.adoc
  upgrading/index.adoc
  using_images/xpaas_images/eap.adoc
  using_images/xpaas_images/sso.adoc
Labels: branch/enterprise-3.10, size/L

#9798 [enterprise-3.10]Removed references to Quick Installer for 3.10
  _topic_map.yml
  admin_guide/backup_restore.adoc
  admin_guide/manage_nodes.adoc
  day_two_guide/topics/adding_master_host.adoc
  getting_started/install_openshift.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
  install_config/configuring_authentication.adoc
  install_config/configuring_sdn.adoc
  install_config/install/host_preparation.adoc
  install_config/install/index.adoc
  install_config/install/planning.adoc
  install_config/install/rpm_vs_containerized.adoc
  install_config/install/stand_alone_registry.adoc
  install_config/master_node_configuration.adoc
  upgrading/automated_upgrades.adoc
  upgrading/blue_green_deployments.adoc
  upgrading/index.adoc
Labels: size/L

#9799 make libc note availabe across all enterprise/dedicated/origin/etc.
  cli_reference/get_started_cli.adoc
Labels: branch/enterprise-3.1, branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9599 Bug 1543460, add Securing Builds info to Advanced Installation topic
  install_config/install/advanced_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#7733 Various fixes to router sharding documentation
  cli_reference/basic_cli_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#9836 Followup style edits to #7733
  install_config/router/default_haproxy_router.adoc
Labels: size/M

#9638 Fix the OpenShift SDN migration steps
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/S

#9844 Minor fixes
  install_config/persistent_storage/persistent_volume_snapshots.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/XS

#9845 Minor fix
  install_config/router/default_haproxy_router.adoc
Labels: size/XS

#9846 Minor fix
  install_config/router/default_haproxy_router.adoc
Labels: size/XS

#9847 Link Fix in online.adoc
  getting_started/manage_your_plan/online.adoc
Labels: size/XS

#9656 #9655 Added missing docker images
  install_config/install/disconnected_install.adoc
Labels: size/XS

#9851 added missing image file
  cli_reference/images/about_page.png
Labels: size/XS

#9850 Bug 1526147 - Update oc run instructions to include cluster name
  apb_devel/writing/reference.adoc
Labels: size/XS

#9576 Add 'Blocking Local Volume Usage'
  install_config/install/host_preparation.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9816 [enterprise-3.1]Added missing repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9814 [enterprise-3.2]Added missing repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9813 [enterprise-3.3]Added missing repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9812 [enterprise-3.4]3 4 add repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9811 [enterprise-3.5]Added missing repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9810 [enterprise-3.6]Added missing repo
  install_config/upgrading/automated_upgrades.adoc
Labels: size/XS

#9800 [enterprise-3.7]Added missing repo
  upgrading/automated_upgrades.adoc
Labels: size/XS

#9856 Removed Dedicated from Topic Map for Disabling Features
  _topic_map.yml
Labels: branch/enterprise-3.10, size/XS

#9864 Disabling features using feature gates
  _topic_map.yml
  admin_guide/disabling_features.adoc
Labels: size/L

#9865 Fix duplicate ids in disabling features
  admin_guide/disabling_features.adoc
Labels: size/XS

#9553 bug BZ1465049 generate router certificates
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9213 Bug 1426158 Update documentation on creating a local role
  admin_guide/manage_authorization_policy.adoc
Labels: Peer Review Done, size/M

#9876 clarify need for :80 port suffix
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9775 Bug 1549238 Update 3.6.0 tags to 3.6
  install_config/upgrading/automated_upgrades.adoc
Labels: Peer Review Done, size/S

#9884 [enterprise-3.3] clarify need for :80 port suffix
  dev_guide/managing_images.adoc
Labels: size/XS

#9885 [enterprise-3.2] clarify need for :80 port suffix
  dev_guide/managing_images.adoc
Labels: size/XS

#9886 [enterprise-3.6] clarify need for :80 port suffix
  dev_guide/managing_images.adoc
Labels: size/XS

#9883 [enterprise-3.4] clarify need for :80 port suffix
  dev_guide/managing_images.adoc
Labels: size/XS

#9888 [enterprise-3.6] Bug 1426158 Update documentation on creating a local role
  admin_guide/manage_authorization_policy.adoc
Labels: size/M

#9887 [enterprise-3.5] Bug 1426158 Update documentation on creating a local role
  admin_guide/manage_authorization_policy.adoc
Labels: size/M

#9758 Bug#1583526 - added a note about double-escaping special chars
  install_config/configuring_openstack.adoc
  install_config/install/advanced_install.adoc
  install_config/topics/escaping_special_characters.adoc
Labels: Peer Review Done, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9890 [enterprise-3.6] Added note to double-escape special chars in inventory file
  install_config/configuring_openstack.adoc
  install_config/install/advanced_install.adoc
  install_config/topics/escaping_special_characters.adoc
Labels: size/S

#9891 [enterprise-3.7] Added note to double-escape special chars in invento…
  install_config/configuring_openstack.adoc
  install_config/install/advanced_install.adoc
  install_config/topics/escaping_special_characters.adoc
Labels: size/S

#9892 [enterprise-3.9] Added note to double-escape special chars in inventory file
  install_config/configuring_openstack.adoc
  install_config/install/advanced_install.adoc
  install_config/topics/escaping_special_characters.adoc
Labels: size/S

#9878 Bug 1586108: Add 3.10 APB known issue
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#9815 Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.2, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9906 [enterprise-3.3] Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: size/XS

#9261 XFS quota for emptyDir volumes
  day_two_guide/topics/node_maintenance.adoc
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/M

#9908 Sync 3.7 relnotes to master
  release_notes/ocp_3_7_release_notes.adoc
Labels: size/XL

#9909 Sync 3.6 relnotes to master
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/L

#9905 [enterprise-3.2] Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: size/XS

#9904 [enterprise-3.1] Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: size/XS

#9903 [enterprise-3.3] Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: size/XS

#9866 Day two guide headings and offset fixes, and some typos
  day_two_guide/docker_tasks.adoc
  day_two_guide/environment_backup.adoc
  day_two_guide/environment_health_checks.adoc
  day_two_guide/host_level_tasks.adoc
  day_two_guide/index.adoc
  day_two_guide/project_level_tasks.adoc
  day_two_guide/run_once_tasks.adoc
  day_two_guide/topics/default_storage_class.adoc
  day_two_guide/topics/deprecating_master.adoc
  day_two_guide/topics/deprecating_node.adoc
  day_two_guide/topics/entropy.adoc
  day_two_guide/topics/host_health.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_certs.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  day_two_guide/topics/master_backup.adoc
  day_two_guide/topics/network_connectivity.adoc
  day_two_guide/topics/node_backup.adoc
  day_two_guide/topics/ntp_synchronization.adoc
  day_two_guide/topics/proc_add-etcd-after-restoring.adoc
  day_two_guide/topics/proc_etcd_backup.adoc
  day_two_guide/topics/proc_restore_etcd.adoc
  day_two_guide/topics/proc_router_and_registry_status.adoc
  day_two_guide/topics/project_backup.adoc
  day_two_guide/topics/pvc_backup_and_restore.adoc
  day_two_guide/topics/removing_etcd_host.adoc
  day_two_guide/topics/restore_master.adoc
  day_two_guide/topics/restore_node.adoc
  day_two_guide/topics/scaling_etcd.adoc
  day_two_guide/topics/verifying_mtu.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#9894 Added RHEL 7.5 as supported
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/XS

#9893 [enterprise-3.7]Bug 1572896, added RHEL 7.5 as supported
  install_config/install/prerequisites.adoc
Labels: size/XS

#9910 Added release notes for RHBA-2018:1796 and bumped latest-tag
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  release_notes/ocp_3_9_release_notes.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/L

#9911 Added Release Notes for 3.7.52
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/L

#9912 Update 3.7 latest tags to 3.7.52
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: size/S

#9913 Updated latest-tag for v3.6.173.0.123
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  install_config/upgrading/automated_upgrades.adoc
  install_config/upgrading/manual_upgrades.adoc
Labels: size/S

#9832 Added Control Pod Placement to Projects
  admin_guide/scheduler.adoc
Labels: size/L

#9923 clean up imagestream example
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9926 Adding Edits from 9832 to Other Versions
  admin_guide/scheduling/pod_placement.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#9877 clarify that completion deadline is not supported with pipeline strategy
  dev_guide/builds/advanced_build_operations.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9936 [enterprise-3.6] clarify that completion deadline is not supported with pipeline strategy
  dev_guide/builds/advanced_build_operations.adoc
Labels: size/XS

#9938 [enterprise-3.7] clarify that completion deadline is not supported with pipeline strategy
  dev_guide/builds/advanced_build_operations.adoc
Labels: size/XS

#9940 [enterprise-3.3] Fix merge error in 9923
  dev_guide/managing_images.adoc
Labels: size/S

#9941 [enterprise-3.4] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9942 [enterprise-3.5] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9943 [enterprise-3.6] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9944 [enterprise-3.7] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9946 [enterprise-3.9] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9945 Added Release Notes for RHBA-2018:1801, v3.6.173.0.123
  release_notes/ocp_3_6_release_notes.adoc
Labels: size/S

#9947 [enterprise-3.10] clean up imagestream example
  dev_guide/managing_images.adoc
Labels: size/S

#9935 Follow-up Edits to PR-9923
  dev_guide/managing_images.adoc
Labels: size/M

#9948 ID fix
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/XS

#9953 Minor edits based on discussion from translators
  install_config/install/host_preparation.adoc
  install_config/router/customized_haproxy_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9954 [enterprise-3.9]Minor edits based on discussion from translators
  install_config/install/host_preparation.adoc
  install_config/router/customized_haproxy_router.adoc
Labels: size/XS

#9959 [enterprise-3.3 Follow-up Edits to PR-9923
  dev_guide/managing_images.adoc
Labels: size/M

#9960 [enterprise-3.4] Follow-up Edits to PR-9923
  dev_guide/managing_images.adoc
Labels: size/M

#9961 [enterprise-3.5] Follow-up Edits to PR-9923
  dev_guide/managing_images.adoc
Labels: size/M

#9962 [enterprise-3.6] Follow-up Edits to PR-9923
  dev_guide/managing_images.adoc
Labels: size/M

#9963 [enterprise-3.5 Ansible-based installation reuses incorrect/unintended configuration value
  install_config/install/advanced_install.adoc
Labels: size/XS

#9965 Removed link to newer REST API
  dev_guide/managing_images.adoc
Labels: size/XS

#9968 [enterprise-3.3] Removed link to newer REST API
  dev_guide/managing_images.adoc
Labels: size/XS

#9647 Bug 1503845, added more information about collecting token
  cli_reference/get_started_cli.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9964 Modify cluster limits for ocp v3.10
  scaling_performance/cluster_limits.adoc
Labels: branch/enterprise-3.10, lgtm, size/XS

#9723 Updating HAProxy performance numbers for 3.10.
  scaling_performance/routing_optimization.adoc
Labels: branch/enterprise-3.10, size/M

#6492 Fix indentation in example pod spec for ConfigMaps
  dev_guide/configmaps.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9969 Typo fix
  architecture/topics/haproxy_template_router.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9985 [enterprise-3.10] Typo fix
  architecture/topics/haproxy_template_router.adoc
Labels: size/XS

#9986 [enterprise-3.9] Typo fix
  architecture/topics/haproxy_template_router.adoc
Labels: size/XS

#9987 [enterprise-3.7] Typo fix
  architecture/topics/haproxy_template_router.adoc
Labels: size/XS

#9988 [enterprise-3.6] Typo fix
  architecture/topics/haproxy_template_router.adoc
Labels: size/XS

#9666 Add oc debug cmd information
  cli_reference/basic_cli_operations.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#9937 BZ 1445774 - Update Metrics and Logging section
  release_notes/ocp_3_5_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.5, size/XS

#9996 [enterprise-3.5] Remove update to Metrics and Logging section
  release_notes/ocp_3_5_release_notes.adoc
Labels: size/XS

#9070 Update and edit advanced LDAP docs to use BasicAuthPasswordIdentityProvider
  _topic_map.yml
  admin_guide/manage_users.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/advanced_ldap_configuration/sssd_for_ldap_failover.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XXL

#9999 [enterprise 3.10] Update advanced LDAP docs to use BasicAuthPasswordI…
  _topic_map.yml
  admin_guide/manage_users.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10000 [enterprise-3.9]Update advanced LDAP docs to use BasicAuthPasswordIde…
  _topic_map.yml
  admin_guide/manage_users.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10001 [enterprise-3.7] Update advanced LDAP docs to use BasicAuthPasswordId…
  _topic_map.yml
  admin_guide/manage_users.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10002 [enterprise-3.6] Update advanced LDAP docs to use BasicAuthPasswordId…
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10003 [enterprise-3.5] Update advanced LDAP docs to use BasicAuthPasswordId…
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10004 [enterprise-3.4] Update advanced LDAP docs to use BasicAuthPasswordId…
  dev_guide/expose_service/expose_internal_ip_service.adoc
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
  security/securing_container_platform.adoc
Labels: size/XXL

#10006 Extra file
  security/securing_container_platform.adoc
Labels: needs-rebase, size/L

#10005 [enterprise-3.3] Update advanced LDAP docs to use BasicAuthPasswordId…
  install_config/advanced_ldap_configuration/configuring_extended_ldap_attributes.adoc
  install_config/advanced_ldap_configuration/configuring_form_based_authentication.adoc
  install_config/advanced_ldap_configuration/index.adoc
  install_config/configuring_authentication.adoc
  install_config/sssd_for_ldap_failover.adoc
  install_config/topics/sssd_for_ldap_failover_configure_apache.adoc
  install_config/topics/sssd_for_ldap_failover_configure_openshift.adoc
  install_config/topics/sssd_for_ldap_failover_configure_sssd.adoc
  install_config/topics/sssd_for_ldap_failover_generate_certs.adoc
  install_config/topics/sssd_for_ldap_failover_overview.adoc
  install_config/topics/sssd_for_ldap_failover_prereqs.adoc
Labels: size/XXL

#9970 added ec2:DeleteSecurityGroup to aws permissions
  install_config/configuring_aws.adoc
Labels: branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#9440 Bug 1446164 Deleted instances of oc deploy --cancel
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#10010 deleted instances of oc deploy --cancel
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/M

#10011 deleted instances of oc deploy --cancel
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/M

#10012 deleted instances of oc deploy --cancel
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/M

#10013 deleted instances of oc deploy --cancel
  cli_reference/basic_cli_operations.adoc
  cli_reference/cli_by_example_content.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/deployments/basic_deployment_operations.adoc
  install_config/router/default_haproxy_router.adoc
Labels: size/M
