Repository openshift/openshift-docs, pull requests merged in 2019-04, with the labels that each got.

#14235 Add note about USER and PROJECT_DOMAIN_NAME support
  install_config/topics/ocp_osp_admin_tasks.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#14296 BZ1693034: Fix wrong object name in backup steps
  day_two_guide/topics/proc_backing-up-project.adoc
Labels: size/XS

#14300 Bug 1692013, fix typo in kubelet spelling
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: branch/enterprise-4.0, size/XS

#14265 Added ose-ansible tag
  install/disconnected_install.adoc
Labels: branch/enterprise-3.11, size/XS

#14252 BZ-1693405: Removed openshift-web-console.
  modules/oauth-token-requests.adoc
Labels: branch/enterprise-4.0, size/XS

#14251 BZ-1693410: Included the bcrypt option when creating htpasswd files.
  modules/identity-provider-creating-htpasswd-file.adoc
Labels: branch/enterprise-4.0, size/XS

#14254 BZ-1693416: Removed references to passwords in login commands.
  modules/cli-developer-basic.adoc
  modules/identity-provider-add.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/S

#14129 improvement in logging-elasticsearch-exposing
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-elasticsearch-exposing.adoc
  modules/nodes-pods-plugins-install.adoc
Labels: branch/enterprise-4.0, retest-not-required, size/L

#14301 [enterprise-3.11]Added ose-ansible tag
  install/disconnected_install.adoc
Labels: size/S

#14268 BZ-1693408: Consolidated references to the kubeadmin user.
  _topic_map.yml
  authentication/remove-kubeadmin.adoc
  authentication/understanding-authentication.adoc
  modules/authentication-kubeadmin.adoc
  modules/authentication-remove-kubeadmin.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-overview.adoc
  modules/rbac-users.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/M

#14303 Typo {prouct-title} on Deploying cluster logging documentation
  logging/efk-logging-deploy.adoc
Labels: branch/enterprise-4.0, retest-not-required, size/XS

#14078 Edits to Logging 4.0 topics per team review 2
  _topic_map.yml
  logging/efk-logging-configuring.adoc
  logging/efk-logging-curator.adoc
  logging/efk-logging-deploy.adoc
  logging/efk-logging-elasticsearch-storage.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-management.adoc
  logging/efk-logging-manual-rollout.adoc
  modules/efk-logging-about.adoc
  modules/efk-logging-configuring-node-selector.adoc
  modules/efk-logging-curator-actions.adoc
  modules/efk-logging-curator-schedule.adoc
  modules/efk-logging-deploy-storage-considerations.adoc
  modules/efk-logging-deploy-subscription.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-limits.adoc
  modules/efk-logging-elasticsearch-persistent-storage-empty.adoc
  modules/efk-logging-elasticsearch-storage.adoc
  modules/efk-logging-eventrouter-deploy.adoc
  modules/efk-logging-external-elasticsearch.adoc
  modules/efk-logging-fluentd-collector.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-fluentd-pod-location.adoc
  modules/efk-logging-kibana-limits.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-kibana-visualize.adoc
  modules/efk-logging-management-state-changing-es.adoc
  modules/efk-logging-management-state-changing.adoc
  modules/efk-logging-manual-rollout-rolling.adoc
  modules/efk-logging-systemd-scaling.adoc
  modules/efk-logging-troubleshooting-cryptic.adoc
  modules/efk-logging-troubleshooting-loop.adoc
  modules/efk-logging-troubleshooting-proxy.adoc
  modules/efk-logging-uninstall-efk.adoc
  modules/nodes-nodes-resources-configuring-setting.adoc
Labels: branch/enterprise-4.0, size/XL

#14306 Fluentd example to set LOGGING_FILE_AGE and LOGGING_FILE_SIZE has a typo
  modules/efk-logging-fluentd-log-rotation.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only

#14307 Typo using systemmd word instead systemd
  modules/efk-logging-exported-fields-systemd.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only

#14294 BZ-1693049: Updated default registries array
  modules/sb-configuring-ansible-service-broker-options.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/S

#14308 Table has interchanged the half of the parameters with the Description
  modules/efk-logging-exported-fields-kubernetes.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only

#14311 Incorrect explanation in point 5 at POD Object Definition (YAML)
  modules/nodes-pods-using-example.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only

#14310 Format problem: the collectd.virt.disk_ops.read parameter doesn't follow the same style rest of paraemeters
  modules/efk-logging-exported-fields-default.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only

#14313 Not link to the Changing the Aggregated Logging Driver instructions
  modules/efk-logging-about-fluentd.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only, size/XS

#14312 BZ-1694825: Adjusted the configuration details of the OAuth server.
  authentication/configuring-internal-oauth.adoc
  modules/oauth-configuring-internal-oauth.adoc
  modules/oauth-internal-options.adoc
  modules/oauth-register-additional-client.adoc
  modules/oauth-server-metadata.adoc
Labels: branch/enterprise-4.0, lgtm, size/L

#14319 bug 1622044 amended advanced audit directories
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11

#14322 [enterprise-3.9] bug 1622044 amended advanced audit directories
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.9, size/S

#14323 BZ-1682962: Updated htpasswd instructions.
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  modules/identity-provider-creating-htpasswd-file-linux.adoc
  modules/identity-provider-creating-htpasswd-file-windows.adoc
  modules/identity-provider-htpasswd-secret.adoc
Labels: Peer Review Done, branch/enterprise-4.0, lgtm, size/M

#14329 Fix resouce kind (bug 1695528)
  modules/nodes-pods-disabling-features-cluster.adoc
Labels: branch/enterprise-4.0, retest-not-required-docs-only, size/XS

#14259 Added Recommended node host practices information
  modules/recommended-node-host-practices.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: branch/enterprise-4.0, lgtm, size/M

#14221 Added how to uninstall service brokers
  _topic_map.yml
  applications/service_brokers/configuring-ansible-service-broker.adoc
  applications/service_brokers/installing-ansible-service-broker.adoc
  applications/service_brokers/installing-service-catalog.adoc
  applications/service_brokers/installing-template-service-broker.adoc
  applications/service_brokers/uninstalling-ansible-service-broker.adoc
  applications/service_brokers/uninstalling-template-service-broker.adoc
  modules/common-attributes.adoc
  modules/sb-about-template-service-broker.adoc
  modules/sb-configuring-ansible-service-broker.adoc
  modules/sb-install-asb-operator.adoc
  modules/sb-install-service-catalog.adoc
  modules/sb-install-tsb-operator.adoc
  modules/sb-provision-service-bundle.adoc
  modules/sb-provision-template-application.adoc
  modules/sb-start-asb.adoc
  modules/sb-start-tsb.adoc
  modules/sb-uninstall-asb.adoc
  modules/sb-uninstall-tsb.adoc
  modules/templates-exposing-object-fields.adoc
  modules/templates-marking-as-bindable.adoc
  modules/templates-waiting-for-readiness.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#14327 Two small changes: mktplc-178, 174, 175
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  modules/olm-operatorhub.adoc
Labels: branch/enterprise-4.0, size/XS

#13646 Include volumenameprefix in GlusterFS example
  install_config/persistent_storage/topics/glusterfs_storageclass.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#14339 Revert accidental add
  ocp311-managing_networking.adoc
Labels: size/XXL

#14340 [enterprise-3.11] Fix typo
  admin_guide/managing_networking.adoc
Labels: size/XS

#14304 Bump the pods per namespace limit to 25k
  scaling_performance/cluster_limits.adoc
Labels: branch/enterprise-3.11, size/S

#14345 Follow-up edits to PR#14304
  scaling_performance/cluster_limits.adoc
Labels: branch/enterprise-3.11, size/S

#14324 Added information about configuring faster storage for etcd
  modules/installation-aws-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/S

#14248 Edits to Configuring network subnets
  modules/configuring-network-subnets.adoc
  scalability_and_performance/using-cluster-loader.adoc
Labels: branch/enterprise-4.0, size/S

#14234 Removed Prometheus Alert Buffer references
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#14348 [enterprise-3.11] Removed docker pull cmd for Prometheus Alert Buffer
  install/disconnected_install.adoc
Labels: size/XS

#14255 Edits of Cluster Monitoring Operator docs
  modules/configuring-cluster-monitoring.adoc
  modules/prometheus-database-storage-requirements.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
Labels: branch/enterprise-4.0, lgtm, size/L

#14132 bug 1672345 amended articles for grammar and context
  install_config/topics/ocp_osp_cinder_vol.adoc
  install_config/topics/ocp_osp_node_registration.adoc
  install_config/topics/ocp_osp_provisioning.adoc
Labels: branch/enterprise-3.11, size/S

#14356 Add dhoyle to preview builds
  autocomment.sh
  autopreview.sh
Labels: size/XS

#14270 Cnv1016 RDP console over L2 network
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-vm-rdp-console-web.adoc
Labels: Peer Review Done, branch/enterprise-3.11, ok-to-test, size/L

#14354 OSDOCS-294: Included CSI details.
  _topic_map.yml
  images/csi-arch.png
  modules/persistent-storage-csi-architecture.adoc
  modules/persistent-storage-csi-driver-daemonset.adoc
  modules/persistent-storage-csi-dynamic-provisioning.adoc
  modules/persistent-storage-csi-example-deployment.adoc
  modules/persistent-storage-csi-external-controllers.adoc
  modules/persistent-storage-csi-mysql-example.adoc
  storage/persistent-storage/persistent-storage-csi.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#14358 [enterprise-3.11] Create topic for AWS Service Broker
  _topic_map.yml
  architecture/service_catalog/aws_broker.adoc
  architecture/service_catalog/images/aws-service-broker.png
Labels: size/M

#14366 trying to fix portal format
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#14272 [enterprise-3.6] bumped latest-tags
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  install_config/upgrading/automated_upgrades.adoc
  install_config/upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.6, size/XS

#14305 Fluentd examples are using etcd pod names
  modules/efk-logging-fluentd-log-viewing.adoc
Labels: branch/enterprise-4.0, size/S

#14365 Pr14364
  _topic_map.yml
  logging/efk-logging-curator.adoc
  logging/efk-logging-elasticsearch-storage.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-management.adoc
  modules/deployments-comparing-deploymentconfigs.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-management-state-changing-es.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/monitoring-accessing-prometheus-alertmanager-grafana.adoc
  modules/monitoring-alerting-rules.adoc
  modules/monitoring-configurable-monitoring-components.adoc
  modules/monitoring-configuring-a-persistent-volume-claim.adoc
  modules/monitoring-configuring-cluster-for-application-monitoring.adoc
  modules/monitoring-configuring-monitoring-for-an-application.adoc
  modules/monitoring-configuring-the-cluster-monitoring-stack.adoc
  modules/monitoring-contents-of-alertmanager-ui.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  modules/monitoring-editing-silences.adoc
  modules/monitoring-expiring-silences.adoc
  modules/monitoring-exposing-custom-application-metrics-for-horizontal-pod-autoscaling.adoc
  modules/monitoring-getting-information-about-alerts-and-alerting-rules.adoc
  modules/monitoring-getting-information-about-silences.adoc
  modules/monitoring-maintenance-and-support.adoc
  modules/monitoring-modifying-retention-time-for-prometheus-metrics-data.adoc
  modules/monitoring-monitoring-overview.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-silencing-alerts.adoc
  modules/monitoring-stack-components-and-monitored-targets.adoc
  modules/monitoring-update-and-compatibility-guarantees.adoc
  modules/olm-deleting-operators-from-a-cluster-using-cli.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/upgrade-upgrading-web.adoc
  monitoring/accessing-prometheus-alertmanager-grafana.adoc
  monitoring/application-monitoring.adoc
  monitoring/cluster-monitoring/about-cluster-monitoring.adoc
  monitoring/cluster-monitoring/configuring-the-monitoring-stack.adoc
  monitoring/cluster-monitoring/managing-alerts-using-alertmanager-ui.adoc
  monitoring/cluster-monitoring/prometheus-alertmanager-and-grafana.adoc
  monitoring/monitoring.adoc
  storage/dynamic-provisioning.adoc
  updating/updating-cluster.adoc
Labels: branch/enterprise-4.0, size/L

#14379 Adding "restart" to virtctl commands
  modules/cnv_controlling_vms.adoc
  modules/cnv_virtctl_commands.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#14378 OSDOCS-387: Included iSCSI on AWS note.
  storage/persistent-storage/persistent-storage-iscsi.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XS

#14242 Bug 1657326, Added Setting the Registry Host Name section to Deploying a Registry topic
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/extended_registry_configuration.adoc
Labels: branch/enterprise-3.11, size/M

#14377 Bug BZ1442565 -- Do not use NFS storage in advanced install
  install_config/install/advanced_install.adoc
Labels: Peer Review Done, approved, size/S

#14355 bug 1695625 -hostPath for Elasticsearch
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/L

#14266 Logging json parsing
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-fluentd-json.adoc
Labels: branch/enterprise-4.0, size/M

#14215 [enterprise-3.11] auditFilePath value is set to wrong path
  install_config/master_node_configuration.adoc
  security/monitoring.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/S

#14386 [enterprise-3.11] auditFilePath value is set to wrong path
  install_config/master_node_configuration.adoc
  security/monitoring.adoc
Labels: size/S

#14387 Logging json parsing follow up
  modules/efk-logging-fluentd-json.adoc
Labels: branch/enterprise-4.0, lgtm, retest-not-required-docs-only

#14389 fixing articles for {product-title}
  installing/installing_aws/installing-aws-account.adoc
  logging/efk-logging.adoc
  machine_management/applying-autoscaling.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/configuration-resource-overview.adoc
  modules/identity-provider-basic-authentication-CR.adoc
  modules/identity-provider-github-CR.adoc
  modules/identity-provider-gitlab-CR.adoc
  modules/identity-provider-keystone-CR.adoc
  modules/identity-provider-ldap-CR.adoc
  modules/identity-provider-ldap-secret.adoc
  modules/identity-provider-oidc-CR.adoc
  modules/identity-provider-provisioning-user-lookup-mapping.adoc
  modules/identity-provider-request-header-CR.adoc
  modules/installation-configuration-parameters.adoc
  modules/machine-autoscaler-about.adoc
  modules/olm-creating-etcd-cluster-from-operator.adoc
  nodes/clusters/nodes-containers-events.adoc
  nodes/containers/nodes-containers-remote-commands.adoc
Labels: branch/enterprise-4.0, size/M

#14273 [enterprise-3.7] bumped latest-tags
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.7, size/S

#14274 [enterprise-3.9] bumped latest-tags
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/S

#14275 [enterprise-3.10] bumped latest-tag
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, size/S

#14279 Added release notes for 3.7.108
  release_notes/ocp_3_7_release_notes.adoc
Labels: branch/enterprise-3.7, size/S

#14280 Added release notes for 3.9.74
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#14281 Added release notes for 3.10.127
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#14376 OSDOCS-395: Include the Manila PV.
  _topic_map.yml
  modules/persistent-storage-manila-install.adoc
  modules/persistent-storage-manila-usage.adoc
  storage/persistent-storage/persistent-storage-manila.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#14391 Added RHSA-2019:0739 to the release notes
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/S

#14368 Logging updated workflow to create CL instance
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.0, size/M

#14325 Logging new topic for Kibana interface
  _topic_map.yml
  logging/efk-logging-kibana-interface.adoc
  modules/efk-logging-kibana-interface-launch.adoc
Labels: branch/enterprise-4.0, size/M

#14405 Nodes docs feedback
  _topic_map.yml
  modules/nodes-cluster-overcommit-configure-nodes.adoc
  modules/nodes-cluster-overcommit-master-disabling-swap.adoc
  modules/nodes-cluster-resource-levels-command.adoc
  modules/nodes-cluster-resource-levels-job.adoc
  modules/nodes-containers-downward-api-container-configmaps.adoc
  modules/nodes-containers-events-viewing.adoc
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-problem-detector-installing.adoc
  modules/nodes-nodes-rebooting-infrastructure.adoc
  modules/nodes-nodes-viewing-memory.adoc
  modules/nodes-pods-priority-about.adoc
  modules/nodes-pods-priority-configuring.adoc
  modules/nodes-pods-priority-preempt-about.adoc
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-viewing-usage.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  nodes/containers/nodes-containers-init.adoc
  nodes/containers/nodes-containers-volumes.adoc
  nodes/pods/nodes-pods-viewing.adoc
Labels: size/L

#14362 [enterprise-3.11] Correct a annotation for overriding existing cookie name
  dev_guide/routes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, ok-to-test, size/S

#14384 Fix incorrect deployment syntax
  dev_guide/dev_tutorials/openshift_pipeline.adoc
Labels: ok-to-test, size/XS

#14409 [enterprise-3.7] Correct annotation for overriding cookie name, and wrong explanation
  dev_guide/routes.adoc
Labels: size/S

#14410 [enterprise-3.9] Correct annotation for overriding cookie name, and wrong explanation
  dev_guide/routes.adoc
Labels: size/S

#14414 Monitoring fixes
  modules/monitoring-contents-of-alertmanager-ui.adoc
  modules/monitoring-getting-information-about-alerts-and-alerting-rules.adoc
  monitoring/cluster-monitoring/images
  monitoring/cluster-monitoring/modules
Labels: size/S

#14415 minor fix
  modules/builds-about.adoc
Labels: size/XS

#14347 rotate-server-certificates gets set to false when set separately
  admin_guide/disabling_features.adoc
Labels: branch/enterprise-3.11, lgtm, size/M

#14398 Updating the namespaces to use for the brokers
  modules/sb-install-asb-operator.adoc
  modules/sb-install-tsb-operator.adoc
  modules/sb-start-asb.adoc
  modules/sb-start-tsb.adoc
  modules/sb-uninstall-asb.adoc
  modules/sb-uninstall-tsb.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/M

#14417 Updating service account subject name
  modules/sb-install-asb-operator.adoc
Labels: branch/enterprise-4.0, size/XS

#14352 bug 1656374 added notes for NetworkPolicy feature support
  admin_guide/managing_networking.adoc
  install_config/configuring_sdn.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#13941 Correct the steps for redeploying router certificates
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, ok-to-test, size/M

#13926 Add missing registry examples to Ansible Broker Configuration
  install_config/oab_broker_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.11, ok-to-test, size/L

#14282 3.11.98 Release notes and tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/L

#14059 Node edits
  _topic_map.yml
  admission-config.yaml
  modules/nodes-cluster-overcommit-configure-nodes.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-containers-copying-files-procedure.adoc
  modules/nodes-containers-events-viewing.adoc
  modules/nodes-containers-init-creating.adoc
  modules/nodes-containers-port-forwarding-using.adoc
  modules/nodes-containers-projected-volumes-creating.adoc
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-managing-about.adoc
  modules/nodes-nodes-problem-detector-installing.adoc
  modules/nodes-nodes-problem-detector-uninstalling.adoc
  modules/nodes-nodes-problem-detector-verifying.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-nodes-working-updating.adoc
  modules/nodes-pods-daemonsets-creating.adoc
  modules/nodes-pods-plugins-install.adoc
  modules/nodes-pods-priority-disabling.adoc
  modules/nodes-pods-viewing-project.adoc
  modules/nodes-scheduler-node-affinity-configuring-preferred.adoc
  nodes/nodes/nodes-nodes-resources-configuring.adoc
  nodes/scheduling/nodes-scheduler-node-affinity.adoc
  nodes/scheduling/nodes-scheduler-node-names.adoc
  nodes/scheduling/nodes-scheduler-overcommit.adoc
Labels: branch/enterprise-4.0, ok-to-test, size/L

#14428 bug 1656374 added notes for NetworkPolicy feature support
  admin_guide/managing_networking.adoc
  install_config/configuring_sdn.adoc
Labels: size/S

#14416 making guidance for variables in paths explicit
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#14429 Bug BZ1695625 -- fixing for cherrypick
  install_config/aggregate_logging.adoc
Labels: size/L

#14430 Correct the steps for redeploying router certificates
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, size/M

#14433 Bug BZ1695625 -- cherrypick to enterprise-3.10
  install_config/aggregate_logging.adoc
Labels: size/L

#14370 [WIP] EO - ClusterLogging Status messages when cluster logging is not functional
  logging/config/efk-logging-elasticsearch.adoc
  modules/efk-logging-elasticsearch-status-comp.adoc
  modules/efk-logging-elasticsearch-status.adoc
Labels: branch/enterprise-4.0, do-not-merge/work-in-progress, size/L

#14058 the description of scheduler policy-configmap's project is conflicting
  modules/nodes-scheduler-default-about.adoc
  modules/nodes-scheduler-default-creating.adoc
  modules/nodes-scheduler-default-modifying.adoc
  modules/nodes-scheduler-default-sample.adoc
  modules/nodes-scheduler-node-projects-about.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
Labels: branch/enterprise-4.0, ok-to-test, size/L

#14388 OSDOCS-396 machine health checks are tech preview
  machine_management/deploying-machine-health-checks.adoc
Labels: branch/enterprise-4.0, size/XS

#14440 bug 1695625 - fixing formatting error
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, size/S

#14449 Bug 1664744, added information about fluentd known issue
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS

#14461 adding Ignition config to the glossary
  contributing_to_docs/term_glossary.adoc
Labels: branch/enterprise-4.0, size/XS

#14468 fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14463 Bug BZ169382 -- corrected reference link.
  scaling_performance/scaling_cluster_monitoring.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#14482 [enterprise-3.6] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14483 [enterprise-3.5] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14484 [enterprise-3.4] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14485 [enterprise-3.3] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14486 [enterprise-3.2] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14487 [enterprise-3.1] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14488 [enterprise-3.0] fix travis version to 2.7
  .travis.yml
Labels: size/XS

#14489 4.0 build to 4.1
  _distro_map.yml
Labels: size/XS

#14490 Adding redirects for 4.0 to 4.1
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#14216 openshift_logging_master_public_url is no longer used
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#14493 Including symlink for subdirectory.
  storage/persistent-storage/images
Labels: branch/enterprise-4.1

#14454 improvement in efk-logging-configuring.html
  modules/efk-logging-about-crd.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-limits.adoc
  modules/efk-logging-elasticsearch-storage.adoc
  modules/efk-logging-fluentd-collector.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-kibana-limits.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-management-state-changing.adoc
Labels: branch/enterprise-4.1, ready, size/S

#14445 improvement in efk-logging-eventrouter.html
  logging/config/efk-logging-elasticsearch.adoc
  logging/efk-logging-eventrouter.adoc
  modules/efk-logging-eventrouter-deploy.adoc
Labels: branch/enterprise-4.1, size/S

#14444 improvement in efk-logging.html
  modules/efk-logging-about-crd.adoc
  modules/efk-logging-about-curator.adoc
  modules/efk-logging-about-fluentd.adoc
Labels: branch/enterprise-4.1, size/S

#14442 No documentation about how to get and modify elasticsearch alerting rules
  modules/efk-logging-elasticsearch-rules.adoc
Labels: branch/enterprise-4.1, size/XS

#14491 Add important section when redeploying ca and certificates
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#14443 Delete the managementState explanation in efk-logging-configuring-about
  logging/config/efk-logging-management.adoc
  logging/efk-logging-deploying-about.adoc
  modules/efk-logging-curator-actions.adoc
  modules/efk-logging-curator-schedule.adoc
  modules/efk-logging-deploying-about.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
  modules/efk-logging-elasticsearch-exposing.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-limits.adoc
  modules/efk-logging-elasticsearch-persistent-storage-empty.adoc
  modules/efk-logging-elasticsearch-storage.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-manual-rollout-rolling.adoc
  modules/efk-logging-systemd-scaling.adoc
Labels: branch/enterprise-4.1, size/M

#14452 BZ-1699700: Fixing default OpenShift Ansible Broker options
  modules/sb-configuring-ansible-service-broker-options.adoc
Labels: branch/enterprise-4.1, size/XS

#14451 OSDOCS-400: Stating the supported OSDK version
  applications/operator_sdk/osdk-getting-started.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#14448 BZ-1698470: Clarified the state of service catalog's custom resources
  modules/sb-install-service-catalog.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#14309 OSDOCS-34: Updating with the latest examples
  modules/osdk-monitoring-prometheus-metrics-helper-modifying-port.adoc
  modules/osdk-monitoring-prometheus-metrics-helper.adoc
  modules/osdk-monitoring-prometheus-servicemonitor-creating.adoc
  modules/osdk-monitoring-prometheus-servicemonitor.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/M

#13907 OSDOCS-316: Updated OperatorGroup docs
  modules/olm-operator-lifecycle-manager.adoc
  modules/olm-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/L

#14357 Removing Descheduler and Node Problem Detector from 4.1
  _topic_map.yml
  modules/nodes-nodes-problem-detector-about.adoc
  modules/nodes-nodes-problem-detector-customizing.adoc
  modules/nodes-nodes-problem-detector-installing.adoc
  modules/nodes-nodes-problem-detector-uninstalling.adoc
  modules/nodes-nodes-problem-detector-verifying.adoc
  modules/nodes-scheduler-descheduler-about.adoc
  modules/nodes-scheduler-descheduler-create-role.adoc
  modules/nodes-scheduler-descheduler-installing.adoc
  modules/nodes-scheduler-descheduler-modifying.adoc
  modules/nodes-scheduler-descheduler-policy.adoc
  modules/nodes-scheduler-descheduler-running.adoc
  nodes/nodes/nodes-nodes-problem-detector.adoc
  nodes/scheduling/nodes-scheduler-descheduler.adoc
Labels: branch/enterprise-4.1, size/XXL

#14374 TP10 Documentation and Release Notes updates.
  servicemesh-install/servicemesh-install.adoc
  servicemesh-install/topics/appendix-crd-old.adoc
  servicemesh-install/topics/appendix-threescale-adapter.adoc
  servicemesh-install/topics/application-requirements.adoc
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-post.adoc
  servicemesh-install/topics/install-prerequisites.adoc
  servicemesh-install/topics/install-remove.adoc
  servicemesh-install/topics/install-supported-config.adoc
  servicemesh-install/topics/install-upgrade.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-install/topics/servicemesh-istio-comparison.adoc
  servicemesh-install/topics/tutorial-bookinfo.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-fixed-issues.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: branch/enterprise-3.11, size/XXL

#14475 BZ-1699802: Fixed typo.
  storage/persistent-storage/persistent-storage-iscsi.adoc
Labels: branch/enterprise-4.1, size/XS

#14499 Fix broken link
  dev_guide/application_health.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#14497 Updated .NET Core variables
  using_images/s2i_images/dot_net_core.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#14467 Improve efk-logging-curator-schedule-efk-logging-curator
  logging/config/efk-logging-curator.adoc
  modules/efk-logging-curator-actions.adoc
  modules/efk-logging-curator-cron.adoc
  modules/efk-logging-curator-schedule.adoc
Labels: branch/enterprise-4.1, size/M

#14383 Adds ingress controller scaling
  _topic_map.yml
  modules/nw-scaling-ingress-controller.adoc
  networking/ingress-controller-configuration.adoc
Labels: branch/enterprise-4.1, lgtm, size/M

#14464 Bug 1699207, removed duplicated Azure File
  modules/available-persistent-storage-options.adoc
Labels: branch/enterprise-4.1, size/XS

#14513 [enterprise-3.6]Updated .NET Core variables
  using_images/s2i_images/dot_net_core.adoc
Labels: branch/enterprise-3.6, size/S

#14517 fixing MachineSet permissions
  modules/machineset-creating.adoc
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.1, size/S

#14520 4.0 to product-version
  applications/operators/olm-creating-apps-from-installed-operators.adoc
  architecture/customizations.adoc
  builds/custom-builds-buildah.adoc
  contributing_to_docs/doc_guidelines.adoc
  modules/available-persistent-storage-options.adoc
  modules/building-memcached-operator-using-osdk.adoc
  modules/installation-planning.adoc
  modules/managing-memcached-operator-using-olm.adoc
  modules/olm-creating-etcd-cluster-from-operator.adoc
  modules/olm-operator-lifecycle-manager.adoc
  modules/openshift-cluster-limits.adoc
  modules/osdk-building-ansible-operator.adoc
  modules/osdk-building-helm-operator.adoc
  modules/prometheus-database-storage-requirements.adoc
  welcome/index.adoc
Labels: size/M

#14521 Version fixes
  modules/node-tuning-operator.adoc
  modules/openshift-cluster-limits.adoc
Labels: branch/enterprise-4.1, size/XS

#14318 Remove deprecated "system:openshift-registry" system user
  architecture/core_concepts/projects_and_users.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#14514 improvement in logging-management-state
  logging/config/efk-logging-management.adoc
  modules/efk-logging-deploying-about.adoc
  modules/efk-logging-management-state-changing-es.adoc
  modules/efk-logging-management-state-changing.adoc
Labels: branch/enterprise-4.1, size/M

#14524 BUG BZ1695719 -- removed outdated note
  install/prerequisites.adoc
Labels: branch/enterprise-3.11, size/XS

#14531 fixed [source-yaml] formatting
  modules/nodes-containers-init-creating.adoc
Labels: branch/enterprise-4.1, size/XS

#14533 [Istio] Incorrect namespace in docs and name no longer has to be istio-installation
  servicemesh-install/topics/install.adoc
Labels: branch/enterprise-3.11, size/XS

#14537 Update the SAN to HOSTNAME of the etcd member
  day_two_guide/topics/proc_scaling-etcd-manual.adoc
Labels: branch/enterprise-3.11, lgtm, size/XS

#14477 BZ-1699270: Updating tech preview feature notice for Block Volumes
  modules/nodes-cluster-disabling-features-cluster.adoc
  modules/storage-persistent-storage-block-volume.adoc
Labels: branch/enterprise-4.1, size/S

#14447 BZ1694774: Included module to define a cluster admin.
  authentication/using-rbac.adoc
  modules/rbac-creating-cluster-admin.adoc
Labels: Peer Review Done, branch/enterprise-4.1, lgtm, size/S

#14530 bug 1691936 clarifying autoscaling parameters
  modules/machine-autoscaler-cr.adoc
Labels: branch/enterprise-4.1, size/S

#14528 bug 1692008 fixing machineset command
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.1, size/XS

#14516 Bug 1692330, Added * for any custom name
  install_config/certificate_customization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#14546 [enterprise-3.9]Bug 1692330, Added * for any custom name
  install_config/certificate_customization.adoc
Labels: size/XS

#14547 [enterprise-3.7]Bug 1692330, Added * for any custom name
  install_config/certificate_customization.adoc
Labels: size/XS

#14548 [enterprise-3.6]Bug 1692330, Added * for any custom name
  install_config/certificate_customization.adoc
Labels: size/S

#14561 Replace Red Hat Enterprise Linux 7 Atomic Host with Red Hat Enterprise Linux CoreOS
  modules/debugging-issues-with-rhel-tools.adoc
Labels: branch/enterprise-4.1, size/XS

#14566 Moving CLI reference section to the end
  _topic_map.yml
Labels: Peer Review Done, branch/enterprise-4.1, size/M

#14552 bug 1699773 removing sigs.k8s.io
  modules/machine-health-checks-resource.adoc
  modules/machineset-cr.adoc
  modules/machineset-creating.adoc
  modules/osdk-monitoring-prometheus-metrics-helper.adoc
  modules/osdk-monitoring-prometheus-servicemonitor-creating.adoc
Labels: branch/enterprise-4.1, size/M

#14527 bug 1692011 updating cluster config commands
  modules/infrastructure-moving-registry.adoc
Labels: branch/enterprise-4.1, size/XS

#13987 modules/machineset-*: Drop openshiftClusterID
  modules/machineset-cr.adoc
  modules/machineset-creating.adoc
Labels: branch/enterprise-4.1, size/XS

#14550 bug 1699778 updating sg value
  modules/machineset-cr.adoc
  modules/machineset-creating.adoc
Labels: branch/enterprise-4.1, size/XS

#14553 bug 1699781 updating subnet value
  modules/machineset-cr.adoc
  modules/machineset-creating.adoc
Labels: branch/enterprise-4.1, size/XS

#14556 BZ-1700266: Clarifications for etcd Operator
  modules/olm-creating-etcd-cluster-from-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS
