Repository openshift/openshift-docs, pull requests merged in 2019-09, with the labels that each got.

#16461 Updated link to Asciibinder
  _templates/_footer_origin.html.erb
  asciibinder-template.yml
  contributing_to_docs/tools_and_setup.adoc
Labels: size/XS

#16426 Update CNV doc attributes
  cnv/cnv_install/cnv-about-cnv.adoc
  cnv/cnv_install/cnv-installing-virtctl.adoc
  cnv/cnv_install/installing-container-native-virtualization.adoc
  cnv/cnv_install/preparing-cluster-for-cnv.adoc
  cnv/cnv_install/uninstalling-container-native-virtualization.adoc
  cnv/cnv_release_notes/cnv-release-notes.adoc
  cnv/cnv_users_guide/cnv-accessing-vm-consoles.adoc
  cnv/cnv_users_guide/cnv-attaching-vm-multiple-networks.adoc
  cnv/cnv_users_guide/cnv-configuring-pxe-booting.adoc
  cnv/cnv_users_guide/cnv-controlling-vm-states.adoc
  cnv/cnv_users_guide/cnv-expanding-virtual-storage-with-blank-disk-images.adoc
  cnv/cnv_users_guide/cnv-importing-virtual-machine-images-datavolumes.adoc
  cnv/cnv_users_guide/cnv-managing-guest-memory.adoc
  cnv/cnv_users_guide/cnv-using-the-cli-tools.adoc
  cnv/cnv_users_guide/cnv-using-the-default-pod-network-with-cnv.adoc
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-adding-virtio-drivers-vm-yaml.adoc
  modules/cnv-ansible-modules.adoc
  modules/cnv-cancelling-vm-migration-web.adoc
  modules/cnv-connecting-resource-bridge-network.adoc
  modules/cnv-connecting-vnc-console.adoc
  modules/cnv-creating-template-wizard-web.adoc
  modules/cnv-creating-vm.adoc
  modules/cnv-delete-vm-web.adoc
  modules/cnv-deleting-custom-resource.adoc
  modules/cnv-deleting-hco-subscription.adoc
  modules/cnv-deleting-template-web.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-document-attributes.adoc
  modules/cnv-editing-template-web.adoc
  modules/cnv-enabling-cnv-repos.adoc
  modules/cnv-importing-vm-datavolume.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-initiating-vm-migration-web.adoc
  modules/cnv-monitoring-vm-migration-web.adoc
  modules/cnv-networking-glossary.adoc
  modules/cnv-openshift-client-commands.adoc
  modules/cnv-preparing-to-install.adoc
  modules/cnv-restarting-vm-web.adoc
  modules/cnv-resuming-node-maintenance-web.adoc
  modules/cnv-setting-node-maintenance-web.adoc
  modules/cnv-starting-vm-web.adoc
  modules/cnv-stopping-vm-web.adoc
  modules/cnv-subscribing-to-hco-catalog.adoc
  modules/cnv-supported-virtio-drivers.adoc
  modules/cnv-understanding-events.adoc
  modules/cnv-understanding-live-migration.adoc
  modules/cnv-understanding-logs.adoc
  modules/cnv-understanding-node-maintenance.adoc
  modules/cnv-understanding-virtio-drivers.adoc
  modules/cnv-updating-imported-vm-network-name.adoc
  modules/cnv-viewing-virtual-machine-logs-web.adoc
  modules/cnv-viewing-vmi-ip-web.adoc
  modules/cnv-virtctl-commands.adoc
  modules/cnv-vm-create-nic-web.adoc
  modules/cnv-vm-rdp-console-web.adoc
  modules/cnv-vm-serial-console-web.adoc
  modules/cnv-what-you-can-do-with-cnv.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16463 [enterprise-4.1] Update CNV doc attributes
  cnv/cnv_install/cnv-about-cnv.adoc
  cnv/cnv_install/cnv-installing-virtctl.adoc
  cnv/cnv_install/installing-container-native-virtualization.adoc
  cnv/cnv_install/preparing-cluster-for-cnv.adoc
  cnv/cnv_install/uninstalling-container-native-virtualization.adoc
  cnv/cnv_release_notes/cnv-release-notes.adoc
  cnv/cnv_users_guide/cnv-accessing-vm-consoles.adoc
  cnv/cnv_users_guide/cnv-attaching-vm-multiple-networks.adoc
  cnv/cnv_users_guide/cnv-configuring-pxe-booting.adoc
  cnv/cnv_users_guide/cnv-controlling-vm-states.adoc
  cnv/cnv_users_guide/cnv-expanding-virtual-storage-with-blank-disk-images.adoc
  cnv/cnv_users_guide/cnv-importing-virtual-machine-images-datavolumes.adoc
  cnv/cnv_users_guide/cnv-managing-guest-memory.adoc
  cnv/cnv_users_guide/cnv-using-the-cli-tools.adoc
  cnv/cnv_users_guide/cnv-using-the-default-pod-network-with-cnv.adoc
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-adding-virtio-drivers-vm-yaml.adoc
  modules/cnv-ansible-modules.adoc
  modules/cnv-cancelling-vm-migration-web.adoc
  modules/cnv-connecting-resource-bridge-network.adoc
  modules/cnv-connecting-vnc-console.adoc
  modules/cnv-creating-template-wizard-web.adoc
  modules/cnv-creating-vm.adoc
  modules/cnv-delete-vm-web.adoc
  modules/cnv-deleting-custom-resource.adoc
  modules/cnv-deleting-hco-subscription.adoc
  modules/cnv-deleting-template-web.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-document-attributes.adoc
  modules/cnv-editing-template-web.adoc
  modules/cnv-enabling-cnv-repos.adoc
  modules/cnv-importing-vm-datavolume.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-initiating-vm-migration-web.adoc
  modules/cnv-monitoring-vm-migration-web.adoc
  modules/cnv-networking-glossary.adoc
  modules/cnv-openshift-client-commands.adoc
  modules/cnv-preparing-to-install.adoc
  modules/cnv-restarting-vm-web.adoc
  modules/cnv-resuming-node-maintenance-web.adoc
  modules/cnv-setting-node-maintenance-web.adoc
  modules/cnv-starting-vm-web.adoc
  modules/cnv-stopping-vm-web.adoc
  modules/cnv-subscribing-to-hco-catalog.adoc
  modules/cnv-supported-virtio-drivers.adoc
  modules/cnv-understanding-events.adoc
  modules/cnv-understanding-live-migration.adoc
  modules/cnv-understanding-logs.adoc
  modules/cnv-understanding-node-maintenance.adoc
  modules/cnv-understanding-virtio-drivers.adoc
  modules/cnv-updating-imported-vm-network-name.adoc
  modules/cnv-viewing-virtual-machine-logs-web.adoc
  modules/cnv-viewing-vmi-ip-web.adoc
  modules/cnv-virtctl-commands.adoc
  modules/cnv-vm-create-nic-web.adoc
  modules/cnv-vm-rdp-console-web.adoc
  modules/cnv-vm-serial-console-web.adoc
  modules/cnv-what-you-can-do-with-cnv.adoc
Labels: size/L

#16464 [enterprise-4.2] Update CNV doc attributes
  cnv/cnv_install/cnv-about-cnv.adoc
  cnv/cnv_install/cnv-installing-virtctl.adoc
  cnv/cnv_install/installing-container-native-virtualization.adoc
  cnv/cnv_install/preparing-cluster-for-cnv.adoc
  cnv/cnv_install/uninstalling-container-native-virtualization.adoc
  cnv/cnv_release_notes/cnv-release-notes.adoc
  cnv/cnv_users_guide/cnv-accessing-vm-consoles.adoc
  cnv/cnv_users_guide/cnv-attaching-vm-multiple-networks.adoc
  cnv/cnv_users_guide/cnv-configuring-pxe-booting.adoc
  cnv/cnv_users_guide/cnv-controlling-vm-states.adoc
  cnv/cnv_users_guide/cnv-expanding-virtual-storage-with-blank-disk-images.adoc
  cnv/cnv_users_guide/cnv-importing-virtual-machine-images-datavolumes.adoc
  cnv/cnv_users_guide/cnv-managing-guest-memory.adoc
  cnv/cnv_users_guide/cnv-using-the-cli-tools.adoc
  cnv/cnv_users_guide/cnv-using-the-default-pod-network-with-cnv.adoc
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-adding-virtio-drivers-vm-yaml.adoc
  modules/cnv-ansible-modules.adoc
  modules/cnv-cancelling-vm-migration-web.adoc
  modules/cnv-connecting-resource-bridge-network.adoc
  modules/cnv-connecting-vnc-console.adoc
  modules/cnv-creating-template-wizard-web.adoc
  modules/cnv-creating-vm.adoc
  modules/cnv-delete-vm-web.adoc
  modules/cnv-deleting-custom-resource.adoc
  modules/cnv-deleting-hco-subscription.adoc
  modules/cnv-deleting-template-web.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-document-attributes.adoc
  modules/cnv-editing-template-web.adoc
  modules/cnv-enabling-cnv-repos.adoc
  modules/cnv-importing-vm-datavolume.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-initiating-vm-migration-web.adoc
  modules/cnv-monitoring-vm-migration-web.adoc
  modules/cnv-networking-glossary.adoc
  modules/cnv-openshift-client-commands.adoc
  modules/cnv-preparing-to-install.adoc
  modules/cnv-restarting-vm-web.adoc
  modules/cnv-resuming-node-maintenance-web.adoc
  modules/cnv-setting-node-maintenance-web.adoc
  modules/cnv-starting-vm-web.adoc
  modules/cnv-stopping-vm-web.adoc
  modules/cnv-subscribing-to-hco-catalog.adoc
  modules/cnv-supported-virtio-drivers.adoc
  modules/cnv-understanding-events.adoc
  modules/cnv-understanding-live-migration.adoc
  modules/cnv-understanding-logs.adoc
  modules/cnv-understanding-node-maintenance.adoc
  modules/cnv-understanding-virtio-drivers.adoc
  modules/cnv-updating-imported-vm-network-name.adoc
  modules/cnv-viewing-virtual-machine-logs-web.adoc
  modules/cnv-viewing-vmi-ip-web.adoc
  modules/cnv-virtctl-commands.adoc
  modules/cnv-vm-create-nic-web.adoc
  modules/cnv-vm-rdp-console-web.adoc
  modules/cnv-vm-serial-console-web.adoc
  modules/cnv-what-you-can-do-with-cnv.adoc
Labels: size/L

#16189 State that modifying ConfigMaps triggers automatic application of new configs
  modules/monitoring-configuring-a-persistent-volume-claim.adoc
  modules/monitoring-configuring-the-cluster-monitoring-stack.adoc
  modules/monitoring-modifying-retention-time-for-prometheus-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16465 updating CF templates per installer #2296
  modules/installation-cloudformation-vpc.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16314 Kiali docs for GA.
  _topic_map.yml
  modules/ossm-kiali-architecture.adoc
  modules/ossm-kiali-features.adoc
  modules/ossm-kiali-overview.adoc
  modules/ossm-kiali-service-mesh.adoc
  service_mesh/service_mesh_install/ossm-kiali.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16476 Bug 1748378 warning added for default CA
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16479 [enterprise-4.1] Kiali overview topics for GA.
  _topic_map.yml
  modules/ossm-kiali-architecture.adoc
  modules/ossm-kiali-features.adoc
  modules/ossm-kiali-overview.adoc
  modules/ossm-kiali-service-mesh.adoc
  service_mesh/service_mesh_install/ossm-kiali.adoc
Labels: branch/enterprise-4.1, size/M

#16317 Jaeger docs for GA.
  _topic_map.yml
  modules/ossm-jaeger-architecture.adoc
  modules/ossm-jaeger-config-elasticsearch.adoc
  modules/ossm-jaeger-features.adoc
  modules/ossm-jaeger-overview.adoc
  modules/ossm-jaeger-service-mesh.adoc
  service_mesh/service_mesh_day_two/configuring-jaeger.adoc
  service_mesh/service_mesh_day_two/images
  service_mesh/service_mesh_day_two/modules
  service_mesh/service_mesh_install/ossm-jaeger.adoc
Labels: Peer Review Done, size/L

#16153 CNV - scratchspace
  _topic_map.yml
  cnv/cnv_users_guide/cnv-preparing-cdi-scratch-space.adoc
  modules/cnv-cdi-supported-operations-matrix.adoc
  modules/cnv-defining-storageclass-in-cdi-configuration.adoc
  modules/cnv-operations-requiring-scratch-space.adoc
  modules/cnv-understanding-scratch-space.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16287 group sync needs to indicate that userNameAttributes needs to match LDAP configuration
  install_config/syncing_groups_with_ldap.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#16488 [enterprise-3.9] group sync needs to indicate that userNameAttributesneeds to match LDAP configuration
  install_config/syncing_groups_with_ldap.adoc
Labels: size/S

#16489 [enterprise-3.7] group sync needs to indicate that userNameAttributesneeds to match LDAP configuration
  install_config/syncing_groups_with_ldap.adoc
Labels: size/S

#16494 3.11.141 release notes and latest tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/M

#16449 Update to operators.coreos.com/v1
  modules/olm-operatorgroups.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16505 OSSM fixes
  modules/ossm-vs-istio.adoc
  service_mesh/service_mesh_arch/understanding-ossm.adoc
Labels: size/XS

#15089 Add CRD/APIService sections to CSV topic
  applications/operator_sdk/osdk-generating-csvs.adoc
  modules/osdk-apiservices.adoc
  modules/osdk-crds.adoc
  modules/osdk-manually-defined-csv-fields.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16515 Edits to About Cluster Logging
  modules/efk-logging-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16517 [enterprise-4.1] Edits to About Cluster Logging
  modules/efk-logging-about.adoc
Labels: size/XS

#16518 [enterprise-4.2] Edits to About Cluster Logging
  modules/efk-logging-about.adoc
Labels: size/S

#16520 jboss 807
  modules/ossm-rn-known-issues.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15980 BZ-1728315: Clarified usage of CA inside ConfigMap.
  modules/identity-provider-config-map.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/XS

#16228 BZ-1738703: Updated supported storage types.
  modules/available-persistent-storage-options.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/S

#16493 SRVCOM-545 Document using defaultPodDisruptionBudget in installation docs
  modules/serverless-installing-service-mesh-control-plane.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16350 SRVCLI-42: Serverless CLI
  _topic_map.yml
  modules/serverless-creating-kubeconfig-file.adoc
  modules/serverless-installing-cli-linux-rpm.adoc
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-installing-cli-macos.adoc
  modules/serverless-installing-cli-windows.adoc
  modules/serverless-workflow-autoscaling.adoc
  modules/serverless-workflow-basic.adoc
  modules/serverless-workflow-tag-revisions-assign.adoc
  modules/serverless-workflow-tag-revisions-unassign.adoc
  modules/serverless-workflow-traffic-flag-operation-precedence.adoc
  modules/serverless-workflow-traffic-splitting-flags.adoc
  modules/serverless-workflow-traffic-splitting.adoc
  modules/srvls-using-cluster-logging-find-logs-knative-serving-components.adoc
  modules/srvls-using-cluster-logging-find-logs-services-deployed.adoc
  serverless/knative-client.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16541 SRVCLI-42 : Adding Knative Client
  _topic_map.yml
  modules/serverless-creating-kubeconfig-file.adoc
  modules/serverless-installing-cli-linux-rpm.adoc
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-installing-cli-macos.adoc
  modules/serverless-installing-cli-windows.adoc
  modules/serverless-workflow-autoscaling.adoc
  modules/serverless-workflow-basic.adoc
  modules/serverless-workflow-tag-revisions-assign.adoc
  modules/serverless-workflow-tag-revisions-unassign.adoc
  modules/serverless-workflow-traffic-flag-operation-precedence.adoc
  modules/serverless-workflow-traffic-splitting-flags.adoc
  modules/serverless-workflow-traffic-splitting.adoc
  modules/srvls-using-cluster-logging-find-logs-knative-serving-components.adoc
  modules/srvls-using-cluster-logging-find-logs-services-deployed.adoc
  serverless/knative-client.adoc
Labels: size/L

#16533 Fix typo
  admin_guide/cluster-autoscaler.adoc
Labels: branch/enterprise-3.11, size/XS

#16542 Typo fix per PR#16533
  admin_guide/cluster-autoscaler.adoc
Labels: size/XS

#16456 metering: Add about-metering and about-installing-metering assemblies
  _topic_map.yml
  metering/metering-about-installing-metering.adoc
  metering/metering-about-metering.adoc
  metering/metering-installing-metering.adoc
  modules/metering-about-install.adoc
  modules/metering-install-operator.adoc
  modules/metering-install-prerequisites.adoc
  modules/metering-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.2, lgtm, size/M

#16523 metering configuration
  _topic_map.yml
  metering/configuring-metering/metering-common-config-options.adoc
  metering/configuring-metering/metering-configure-aws-billing-correlation.adoc
  metering/configuring-metering/metering-configure-hive-metastore.adoc
  metering/configuring-metering/metering-configure-persistent-storage.adoc
  metering/configuring-metering/metering-configure-reporting-operator.adoc
  metering/configuring-metering/modules
  metering/metering-configuring-metering.adoc
  modules/metering-configure-persistentvolumes.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/metering-prometheus-connection.adoc
  modules/metering-store-data-in-azure.adoc
  modules/metering-store-data-in-gcp.adoc
  modules/metering-store-data-in-s3-compatible.adoc
  modules/metering-store-data-in-s3.adoc
  modules/metering-store-data-in-shared-volumes.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XL

#16553 Revert "[enterprise-4.2] metering configuration"
  _topic_map.yml
  metering/configuring-metering/metering-common-config-options.adoc
  metering/configuring-metering/metering-configure-aws-billing-correlation.adoc
  metering/configuring-metering/metering-configure-hive-metastore.adoc
  metering/configuring-metering/metering-configure-persistent-storage.adoc
  metering/configuring-metering/metering-configure-reporting-operator.adoc
  metering/configuring-metering/modules
  metering/metering-configuring-metering.adoc
  modules/metering-configure-persistentvolumes.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/metering-prometheus-connection.adoc
  modules/metering-store-data-in-azure.adoc
  modules/metering-store-data-in-gcp.adoc
  modules/metering-store-data-in-s3-compatible.adoc
  modules/metering-store-data-in-s3.adoc
  modules/metering-store-data-in-shared-volumes.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
Labels: size/XL

#16165 jenkins doc fixes post 4.x rewrite
  modules/builds-strategy-pipeline-mapping-buildconfig-jenkins.adoc
  modules/images-other-jenkins-agent-memory.adoc
  modules/images-other-jenkins-memory.adoc
  modules/images-other-jenkins-oauth-auth.adoc
  openshift_images/using_images/images-other-jenkins.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16545 SRVCOM-546: Edits to install docs
  modules/ossm-operatorhub-install.adoc
  modules/serverless-installing-service-mesh-control-plane.adoc
  modules/serverless-installing-service-mesh-member-roll.adoc
  modules/serverless-installing-service-mesh-no-kiali-jaeger.adoc
  modules/serverless-using-cluster-logging-find-logs-knative-serving-components.adoc
  modules/serverless-using-cluster-logging-find-logs-services-deployed.adoc
  serverless/installing-openshift-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16088 OSDOCS-469: Add OVNKubernetes CNI plug-in tech preview content
  installing/installing_aws/installing-aws-network-customizations.adoc
  modules/nw-install-config-parameters.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/nw-operator-cr.adoc
  modules/nw-ovn-technology-preview.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16490 Add Operator install/upgrade policy
  _topic_map.yml
  applications/operators/olm-creating-policy.adoc
  modules/olm-policy-fine-grained-permissions.adoc
  modules/olm-policy-scenarios.adoc
  modules/olm-policy-scoping-operator-install.adoc
  modules/olm-policy-troubleshooting.adoc
  modules/olm-policy-understanding.adoc
  modules/olm-policy-workflow.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16551 SRVCOM-516: Serverless Release Notes
  _topic_map.yml
  modules/serverless-rn-fixed-issues.adoc
  modules/serverless-rn-known-issues.adoc
  modules/serverless-rn-new-features.adoc
  modules/serverless-support.adoc
  serverless/release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16568 Update ldap-syncing-rfc2307-user-defined.adoc
  modules/ldap-syncing-rfc2307-user-defined.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16454 BZ_174160 change to CSI 1.0.0
  modules/persistent-storage-csi-example-deployment.adoc
  storage/persistent-storage/persistent-storage-csi.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#16439 bug 1746962 add note in recycle
  modules/storage-persistent-storage-lifecycle.adoc
Labels: size/S

#16526 Update the 4.2 EO and CLO installs
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.2, size/M

#16578 corrected deployment and logging statements
  modules/architecture-platform-benefits.adoc
  modules/efk-logging-about.adoc
Labels: branch/dedicated, size/M

#16581 [enterprise-4.1] SRVCOM-516: Serverless Release Notes
  _topic_map.yml
  modules/serverless-rn-fixed-issues.adoc
  modules/serverless-rn-known-issues.adoc
  modules/serverless-rn-new-features.adoc
  modules/serverless-support.adoc
  serverless/release-notes.adoc
Labels: branch/enterprise-4.1, size/L

#16480 Document Clusterlogging does not support scaling down Elasticsearch cluster
  logging/config/efk-logging-elasticsearch.adoc
  logging/efk-logging-deploying-about.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16409 Changing instanceType in machineset on AWS takes effect only after scaling to 0 and back up
  _topic_map.yml
  machine_management/manually-scaling-machineset.adoc
  machine_management/modifying-machineset.adoc
  modules/machineset-manually-scaling.adoc
  modules/machineset-modifying.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16587 Published Serverless Docs
  _topic_map.yml
  serverless/installing-openshift-serverless.adoc
  serverless/serverless-release-notes.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16591 amended phrasing for dedicated cluster-admin purposes
  modules/architecture-platform-benefits.adoc
  modules/efk-logging-about.adoc
Labels: branch/dedicated, size/XS

#16546 OSDOCS-619: Adding content for schedulable master nodes
  modules/nodes-nodes-working-marking.adoc
  modules/nodes-nodes-working-master-schedulable.adoc
  nodes/nodes/nodes-nodes-working.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#16600 [enterprise-4.1] Publish Serverless
  _topic_map.yml
  serverless/installing-openshift-serverless.adoc
  serverless/serverless-release-notes.adoc
Labels: size/M

#16601 Adding back Support
  _topic_map.yml
Labels: branch/enterprise-4.2, size/S

#16549 4.1.14 release notes added
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#16628 Added 4.1.15 release notes stub
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#16630 Added release notes stub for 3.10.170
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#16631 Removing KubeFed for 4.2
  _topic_map.yml
  kubefed/images
  kubefed/installing-kubefed.adoc
  kubefed/modules
  kubefed/understanding-kubefed.adoc
  modules/creating-kubefed-CRs.adoc
  modules/kubefed-document-attributes.adoc
Labels: Peer Review Done, size/L

#16636 SRVCOM-548: Update Install notes regarding Service Mesh
  modules/serverless-using-cluster-logging-find-logs-services-deployed.adoc
  serverless/installing-openshift-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16565 Reorganize service mesh docs for better flow.
  _topic_map.yml
  modules/ossm-jaeger-service-mesh.adoc
  modules/ossm-kiali-service-mesh.adoc
  modules/ossm-mixer-policy.adoc
  modules/ossm-threescale-integrate.adoc
  modules/ossm-vs-istio.adoc
  service_mesh/service_mesh_arch/ossm-jaeger.adoc
  service_mesh/service_mesh_arch/ossm-kiali.adoc
  service_mesh/service_mesh_arch/ossm-vs-community.adoc
  service_mesh/service_mesh_day_two/ossm-example-bookinfo.adoc
  service_mesh/service_mesh_day_two/prepare-to-deploy-applications-ossm.adoc
  service_mesh/service_mesh_install/customizing-installation-ossm.adoc
  service_mesh/service_mesh_install/installing-ossm.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16613 minor clean up for metering docs
  _topic_map.yml
  metering/configuring-metering/metering-configure-persistent-storage.adoc
  metering/metering-about-installing-metering.adoc
  metering/metering-installing-metering.adoc
  modules/metering-about-install.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/S

#16124 Bug 1731177 adding procedural documentation for router sharding
  modules/nw-ingress-sharding-namespace-labels.adoc
  modules/nw-ingress-sharding-route-labels.adoc
  modules/nw-using-ingress-and-routes.adoc
  networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc
  networking/ingress-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16522 CNV-1547 Support matrix added to relevant CDI procedures
  cnv/cnv_users_guide/cnv-cloning-vm-disk-into-new-datavolume.adoc
  cnv/cnv_users_guide/cnv-cloning-vm-using-datavolumetemplate.adoc
  cnv/cnv_users_guide/cnv-importing-virtual-machine-images-datavolumes.adoc
  cnv/cnv_users_guide/cnv-uploading-local-disk-images-virtctl.adoc
  modules/cnv-cdi-supported-operations-matrix.adoc
Labels: Peer Review Done, size/M

#16597 Remove rsyslog from cluster logging documentation
  _topic_map.yml
  logging/config/efk-logging-configuring-about.adoc
  logging/config/efk-logging-configuring.adoc
  logging/config/efk-logging-fluentd.adoc
  logging/config/efk-logging-systemd.adoc
  logging/efk-logging-eventrouter.adoc
  logging/efk-logging-exported-fields.adoc
  modules/efk-logging-about-components.adoc
  modules/efk-logging-about-crd.adoc
  modules/efk-logging-about-eventrouter.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-clo-status.adoc
  modules/efk-logging-configuring-image-about.adoc
  modules/efk-logging-deploying-about.adoc
  modules/efk-logging-eventrouter-deploy.adoc
  modules/efk-logging-exported-fields-default.adoc
  modules/efk-logging-external-elasticsearch.adoc
  modules/efk-logging-external-syslog.adoc
  modules/efk-logging-fluentd-alerts.adoc
  modules/efk-logging-fluentd-collector.adoc
  modules/efk-logging-fluentd-envvar.adoc
  modules/efk-logging-fluentd-external.adoc
  modules/efk-logging-fluentd-json.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-fluentd-log-rotation.adoc
  modules/efk-logging-fluentd-pod-location.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-fluentd-undefined.adoc
  modules/efk-logging-systemd-scaling.adoc
  modules/efk-logging-viewing-logs-console.adoc
  modules/efk-logging-viewing-logs.adoc
  modules/infrastructure-moving-logging.adoc
Labels: branch/enterprise-4.2, size/L

#16508 CNV-OCP monitoring/telemetry modularization for associated products
  _topic_map.yml
  cnv/cnv_users_guide/cnv-openshift-cluster-monitoring.adoc
  modules/monitoring-about-cluster-monitoring.adoc
  modules/telemetry-about-telemetry.adoc
  monitoring/cluster-monitoring/about-cluster-monitoring.adoc
  telemetry/about-telemetry.adoc
Labels: Peer Review Done, size/L

#16667 Moving node selector logging topic
  _topic_map.yml
  logging/config/efk-logging-configuring.adoc
  logging/efk-logging-moving-nodes.adoc
  modules/infrastructure-moving-logging.adoc
Labels: branch/enterprise-4.2, size/S

#16672 Re-lock asciibinder version
  .s2i/bin/assemble
Labels: size/XS

#16669 Add MachineSet Note
  serverless/installing-openshift-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16676 Removing logging systemd topic
  _topic_map.yml
Labels: branch/enterprise-4.1

#16680 Removed configuring knative services section
  _topic_map.yml
  modules/configuring-knative-services-domains.adoc
  modules/domain-templates-knative-services.adoc
  serverless/configuring-knative-services.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16642 bz 1699836 added note for custom CA deployment
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#16647 cisco_1749892: add Cisco ACI to SDN plug-ins
  architecture/networking/network_plugins.adoc
  architecture/topics/cisco.adoc
  architecture/topics/nsxt.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#16567 CNV-2386: must-gather tool
  _topic_map.yml
  cnv/cnv_users_guide/cnv-collecting-cnv-data.adoc
  modules/about-must-gather.adoc
  modules/cnv-about-collecting-cnv-data.adoc
  modules/gathering-data-specific-features.adoc
  modules/support-gather-data.adoc
  support/gathering-cluster-data.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16049 osdocs-631 installing default cluster on Azure
  _topic_map.yml
  installing/installing_azure/installing-azure-default.adoc
  modules/installation-launching-installer.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#16624 Redirects for PR: 16514
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#16697 [enterprise-3.0] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16698 [enterprise-3.1] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16699 [enterprise-3.2] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16700 [enterprise-3.3] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16701 [enterprise-3.4] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16702 [enterprise-3.5] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16703 [enterprise-3.6] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16704 [enterprise-3.7] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16705 [enterprise-3.9] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16706 [enterprise-3.11] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16707 [master-3] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/S

#16708 [enterprise-4.1] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/XS

#16709 [enterprise-4.2] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/XS

#16710 exclude search from 4.2
  _templates/_page_openshift.html.erb
Labels: size/XS

#16711 Fix breadcrumb to go to root
  _templates/_page_openshift.html.erb
Labels: size/XS

#16715 [enterprise-3.10] Sync page template
  _templates/_page_openshift.html.erb
Labels: size/L

#16453 Remove the outdated compatibility section
  install_config/monitoring/update-and-compatibility-guarantees.adoc
  install_config/prometheus_cluster_monitoring.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#16474 Updates to the Alerting UI section
  images/yaml-screen.png
  modules/monitoring-contents-of-the-alerting-ui.adoc
Labels: size/S

#16548 Improve a command invocation
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
Labels: size/XS

#16616 added 4.2 content for snapshot assembly and modules
  _topic_map.yml
  modules/persistent-storage-snapshots-about.adoc
  modules/persistent-storage-snapshots-controller-provisioner-aws-gce.adoc
  modules/persistent-storage-snapshots-controller-provisioner.adoc
  modules/persistent-storage-snapshots-create.adoc
  modules/persistent-storage-snapshots-creating-deleting.adoc
  modules/persistent-storage-snapshots-delete.adoc
  modules/persistent-storage-snapshots-managing-users.adoc
  modules/persistent-storage-snapshots-restore.adoc
  modules/persistent-storage-snapshots-starting-controller-provisioner.adoc
  storage/persistent-storage/persistent-storage-snapshots.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16734 Update apache redirects for the dedicated docs
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#16742 Added snapshots deprecated note 4.2
  storage/persistent-storage/persistent-storage-snapshots.adoc
Labels: Peer Review Done, size/XS

#16586 Change the instructions in favor of local storage for Prometheus and AM
  modules/monitoring-configuring-a-local-persistent-volume-claim.adoc
  monitoring/cluster-monitoring/configuring-the-monitoring-stack.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#16575 Add the tolerations for monitoring components section
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  monitoring/cluster-monitoring/configuring-the-monitoring-stack.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#16739 formatting change for ossm-26
  modules/ossm-control-plane-deploy.adoc
Labels: Peer Review Done, size/XS

#16746 Update apache redirects for the dedicated docs for welcome pages
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#16584 Change the recommended storage statement
  monitoring/cluster-monitoring/configuring-the-monitoring-stack.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16760 Add procedure: listing acting alerting rules
  modules/monitoring-listing-acting-alerting-rules.adoc
  monitoring/cluster-monitoring/configuring-the-monitoring-stack.adoc
Labels: size/M

#16688 BZ-1743397: Included block detailing not to use vSphere storage for registry storage.
  modules/registry-configuring-storage-vsphere.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16738 Resolves bz#1734100 by adding ignition configs via vApp
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16740 4.1.16 release notes added
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#14676 Edit suggested in file nodes/scheduling/nodes-scheduler-default.adoc
  modules/nodes-scheduler-default-about.adoc
  modules/nodes-scheduler-default-creating.adoc
  modules/nodes-scheduler-default-modifying.adoc
  modules/nodes-scheduler-default-predicates.adoc
  modules/nodes-scheduler-default-priorities.adoc
  modules/nodes-scheduler-default-sample.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, ok-to-test, size/XL

#16772 fixing typo
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-creating-aws-bootstrap.adoc
  modules/installation-overview.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16758 New, add kernel args to nodes per OSDOCS-479 Jira
  modules/nodes-nodes-kernel-arguments.adoc
  nodes/nodes/nodes-nodes-working.adoc
Labels: branch/enterprise-4.2, size/L

#16775 Adding kernel args proc to master
  modules/nodes-nodes-kernel-arguments.adoc
  nodes/nodes/nodes-nodes-working.adoc
Labels: size/L

#16776 Removed Scaling the Prometheus Components section
  scaling_performance/scaling_cluster_monitoring.adoc
Labels: branch/enterprise-3.11, size/S

#16752 Add the "Examining cluster metrics" section
  _topic_map.yml
  images/monitoring-alert-overview.png
  images/monitoring-alerting-rule-overview.png
  images/monitoring-alerts-screen.png
  images/monitoring-metrics-screen.png
  images/monitoring-silences-screen.png
  images/monitoring-yaml-screen.png
  modules/monitoring-accessing-prometheus-alerting-ui-grafana-using-the-web-console.adoc
  modules/monitoring-accessing-prometheus-alertmanager-grafana-directly.adoc
  modules/monitoring-configuring-cluster-for-application-monitoring.adoc
  modules/monitoring-contents-of-the-alerting-ui.adoc
  modules/monitoring-contents-of-the-metrics-ui.adoc
  modules/monitoring-editing-silences.adoc
  modules/monitoring-expiring-silences.adoc
  modules/monitoring-exploring-the-visualized-metrics.adoc
  modules/monitoring-getting-information-about-alerts-and-alerting-rules.adoc
  modules/monitoring-getting-information-about-silences.adoc
  modules/monitoring-running-metrics-queries.adoc
  modules/monitoring-silencing-alerts.adoc
  monitoring/cluster-monitoring/examining-cluster-metrics.adoc
  monitoring/cluster-monitoring/managing-cluster-alerts.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16689 adding storage locations
  _topic_map.yml
  metering/reports/metering-about-reports.adoc
  metering/reports/metering-storage-locations.adoc
  metering/reports/modules
Labels: Peer Review Done, branch/enterprise-4.2, lgtm, size/M

#16757 OSDOCS-468-DEVEXP-401 Add Builds - Mount trusted CA for cluster proxies warning
  modules/builds-source-code.adoc
Labels: Peer Review Done, branch/enterprise-4.2, lgtm, size/S

#15872 Bug 1724805 Add managing images
  _topic_map.yml
  modules/images-add-tags-to-imagestreams.adoc
  modules/images-allow-pods-to-reference-images-across-projects.adoc
  modules/images-allow-pods-to-reference-images-from-secure-registries.adoc
  modules/images-image-pull-policy-overview.adoc
  modules/images-managing-overview.adoc
  modules/images-pulling-from-private-registries.adoc
  modules/images-referencing-images-imagestreams.adoc
  modules/images-remove-tag-imagestream.adoc
  modules/images-tag.adoc
  modules/images-tagging-conventions.adoc
  openshift_images/managing-images/image-pull-policy.adoc
  openshift_images/managing-images/managing-images-overview.adoc
  openshift_images/managing-images/tagging-images.adoc
  openshift_images/managing-images/using-image-pull-secrets.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16786 adjusting a module to better reflect the installation status
  modules/installation-installing-bare-metal.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16443 CNV2525 - extended Telemetry metrics to include VMs and VMIs
  cnv/cnv_users_guide/cnv-openshift-cluster-monitoring.adoc
  modules/telemetry-what-information-is-collected.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#16498 updating kube api version
  modules/dr-recover-lost-control-plane-hosts.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-installing-bare-metal.adoc
  modules/looking-inside-nodes.adoc
  modules/nodes-nodes-audit-log-basic-viewing.adoc
  modules/nodes-nodes-audit-log-basic.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/understanding-workers-masters.adoc
Labels: branch/enterprise-4.2, size/M

#16644 bug 1658559 included openshift_storage_glusterfs_block_host_vol_size variable description
  install_config/persistent_storage/topics/glusterfs_example_full.adoc
  install_config/persistent_storage/topics/glusterfs_example_full_external.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#16554 Make iSCSI options more obvious
  modules/storage-persistent-storage-iscsi-provisioning.adoc
  modules/storage-persistent-storage-iscsi-volume-security.adoc
  storage/persistent-storage/persistent-storage-iscsi.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16782 Support multiline docker json-file log driver
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, lgtm, size/M

#16513 improve node selector docs
  modules/nodes-scheduler-node-selectors-pod.adoc
Labels: QE Required, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15956 CNV-1589: Using Ansible modules with CNV (kubevirt_vm module used as example)
  _topic_map.yml
  cnv/cnv_users_guide/cnv-automating-management-tasks.adoc
  modules/cnv-about-red-hat-ansible-automation.adoc
  modules/cnv-ansible-modules.adoc
  modules/cnv-automating-virtual-machine-creation-with-ansible.adoc
  modules/cnv-example-ansible-playbook-creating-vms.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16563 osdocs-634 and osdocs-639 deleting gcp and azure clusters
  _topic_map.yml
  installing/installing_aws/uninstalling-cluster-aws.adoc
  installing/installing_azure/uninstalling-cluster-azure.adoc
  installing/installing_gcp/uninstalling-cluster-gcp.adoc
  modules/installation-uninstall-clouds.adoc
Labels: Peer Review Done, QE Required, branch/enterprise-4.2, size/M

#16556 removing the --log-level debug option
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-launching-installer.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16067 osdocs-630 Azure account creation draft
  _topic_map.yml
  installing/installing_azure/installing-azure-account.adoc
  modules/installation-aws-route53.adoc
  modules/installation-azure-increasing-limits.adoc
  modules/installation-azure-limits.adoc
  modules/installation-azure-network-config.adoc
  modules/installation-azure-permissions.adoc
  modules/installation-azure-regions.adoc
  modules/installation-azure-service-principal.adoc
  modules/installing-aws-customizations.adoc
Labels: Peer Review Done, QE Required, branch/enterprise-4.2, size/L

#16232 osdocs-635 draft of GCP account config
  _topic_map.yml
  installing/installing_gcp/installing-gcp-account.adoc
  modules/installation-gcp-dns.adoc
  modules/installation-gcp-enabling-api-services.adoc
  modules/installation-gcp-limits.adoc
  modules/installation-gcp-permissions.adoc
  modules/installation-gcp-regions.adoc
  modules/installation-gcp-service-account.adoc
Labels: Peer Review Done, QE Required, branch/enterprise-4.2, size/L

#16696 osdocs-627 disconnected install
  _topic_map.yml
  installing/install_config/configuring-custom-ca.adoc
  installing/installing_disconnected/installing-disconnected.adoc
  installing/installing_restricted_networks/installing-disconnected-preparations.adoc
  installing/installing_restricted_networks/installing-restricted-networks-aws.adoc
  installing/installing_restricted_networks/installing-restricted-networks-bare-metal.adoc
  installing/installing_restricted_networks/installing-restricted-networks-vsphere.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-generate-aws-user-infra.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/ssh-agent-using.adoc
  modules/telemetry-consequences-of-disabling-telemetry.adoc
  updating/updating-disconnected-cluster.adoc
Labels: Peer Review Done, size/XL

#16678 osdocs-626 preparing for disconnected installation
  _topic_map.yml
  installing/installing_restricted_networks/installing-disconnected.adoc
  installing/installing_restricted_networks/installing-restricted-networks-preparations.adoc
  modules/installation-about-mirror-registry.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-local-registry-pull-secret.adoc
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XL

#16687 BZ-1752553: Indicated that the default SC is Operator-owned.
  modules/dynamic-provisioning-defining-storage-class.adoc
  modules/storage-persistent-storage-pvc.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16596 OSDOCS-687: Included FibreChannel details.
  _topic_map.yml
  modules/persistent-storage-fibre-disk-quotas.adoc
  modules/persistent-storage-fibre-provisioning.adoc
  modules/persistent-storage-fibre-volume-security.adoc
  storage/persistent-storage/persistent-storage-fibre.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16214 OSDOCS-483: Included GCE Persistent Disk details.
  _topic_map.yml
  modules/dynamic-provisioning-available-plugins.adoc
  modules/storage-create-storage-class.adoc
  modules/storage-persistent-storage-aws-volume-format.adoc
  modules/storage-persistent-storage-volume-format.adoc
  storage/persistent-storage/persistent-storage-aws.adoc
  storage/persistent-storage/persistent-storage-gce.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16205 OSDOCS-610: Updated details regarding raw block volumes.
  modules/storage-persistent-storage-block-volume-examples.adoc
  modules/storage-persistent-storage-block-volume.adoc
  storage/understanding-persistent-storage.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#15820 OSDOCS-484: Include Azure persistent storage.
  _topic_map.yml
  modules/storage-azure-create-storage-class.adoc
  modules/storage-persistent-storage-azure-volume-format.adoc
  modules/storage-persistent-storage-pv.adoc
  storage/persistent-storage/persistent-storage-azure.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#16796 Fixed command for finding OAuth namespace route.
  modules/oauth-token-requests.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16821 correcting a suggestion from a different PR
  modules/installation-gcp-config-yaml.adoc
Labels: branch/enterprise-4.2, size/XS

#16834 fixes
  logging/cluster-logging-deploying.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
Labels: size/XS

#16835 [enterprise-4.2] fixes
  logging/cluster-logging-deploying.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
Labels: size/XS

#16837 [enterprise-4.1] fixing some doubles
  logging/config/efk-logging-curator.adoc
  logging/config/efk-logging-elasticsearch.adoc
  modules/efk-logging-configuring-node-selector.adoc
  modules/efk-logging-deploy-subscription.adoc
  modules/efk-logging-elasticsearch-persistent-storage-empty.adoc
  modules/efk-logging-elasticsearch-storage.adoc
  modules/efk-logging-management-state-changing-es.adoc
  modules/installation-creating-aws-dns.adoc
  modules/installation-vsphere-machines.adoc
  modules/nodes-nodes-audit-log-basic-config.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/rhel-compute-using-hooks.adoc
  modules/rhel-removing-rhcos.adoc
  modules/storage-persistent-storage-block-volume-examples.adoc
  modules/storage-persistent-storage-nfs-group-ids.adoc
  modules/storage-persistent-storage-overview.adoc
  modules/storage-persistent-storage-pvc.adoc
Labels: size/M

#16818 fixing 'log into'
  logging/config/cluster-logging-configuring.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-logging-kibana-console-launch.adoc
  modules/cluster-logging-kibana-interface-launch.adoc
  modules/cluster-logging-kibana-visualize.adoc
  modules/cnv-accessing-vmi-ssh.adoc
  modules/completing-installation.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/ignition-config-viewing.adoc
  modules/images-other-jenkins-config-kubernetes.adoc
  modules/images-other-jenkins-env-var.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/looking-inside-nodes.adoc
  modules/machineset-manually-scaling.adoc
  modules/machineset-modifying.adoc
  modules/nw-create-load-balancer-service.adoc
  modules/nw-creating-project-and-service.adoc
  modules/nw-exposing-service.adoc
  modules/ossm-tutorial-kiali-accessing-console.adoc
  modules/rhcos-about.adoc
  nodes/nodes/nodes-nodes-managing.adoc
  welcome/index.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16841 [enterprise-4.1] fixing 'log into'
  logging/config/efk-logging-configuring.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cnv-accessing-vmi-ssh.adoc
  modules/completing-installation.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/efk-logging-kibana-console-launch.adoc
  modules/efk-logging-kibana-interface-launch.adoc
  modules/efk-logging-kibana-visualize.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/ignition-config-viewing.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/looking-inside-nodes.adoc
  modules/machineset-manually-scaling.adoc
  modules/rhcos-about.adoc
  nodes/nodes/nodes-nodes-managing.adoc
  welcome/index.adoc
Labels: size/M

#16780 adding usage examples
  _topic_map.yml
  metering/metering-usage-examples.adoc
  modules/metering-cluster-capacity-examples.adoc
  modules/metering-cluster-usage-examples.adoc
  modules/metering-cluster-utilization-examples.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16764 3.11.146 release notes stub and latest tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/M

#16813 cleaning up anchor ids, backticks, and xrefs for metering
  metering/configuring-metering/metering-about-configuring.adoc
  metering/configuring-metering/metering-common-config-options.adoc
  metering/configuring-metering/metering-configure-aws-billing-correlation.adoc
  metering/configuring-metering/metering-configure-hive-metastore.adoc
  metering/configuring-metering/metering-configure-persistent-storage.adoc
  metering/configuring-metering/metering-configure-reporting-operator.adoc
  metering/metering-about-installing-metering.adoc
  metering/metering-installing-metering.adoc
  metering/metering-troubleshooting-debugging.adoc
  metering/metering-using-metering.adoc
  metering/reports/metering-storage-locations.adoc
  modules/metering-configure-persistentvolumes.adoc
  modules/metering-debugging.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/metering-install-metering-stack.adoc
  modules/metering-install-operator.adoc
  modules/metering-install-verify.adoc
  modules/metering-overview.adoc
  modules/metering-prometheus-connection.adoc
  modules/metering-reports.adoc
  modules/metering-resources.adoc
  modules/metering-store-data-in-shared-volumes.adoc
  modules/metering-troubleshooting.adoc
  modules/metering-verify-installation.adoc
  modules/metering-viewing-report-results.adoc
  modules/metering-writing-reports.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16450 Add Operator update workflow to OLM docs
  applications/operators/olm-understanding-olm.adoc
  images/olm-catalogsource.png
  images/olm-channels.png
  images/olm-replaces.png
  images/olm-skipping-updates.png
  images/olm-z-stream.png
  modules/olm-architecture.adoc
  modules/olm-csv.adoc
  modules/olm-dependency-resolution.adoc
  modules/olm-upgrades.adoc
Labels: Peer Review Done, QE Required, branch/enterprise-4.2, size/L

#16570 Vddk container for CNV VMware VM import
  cnv/cnv_users_guide/cnv-importing-vmware-vm.adoc
  modules/cnv-creating-vddk-image.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-uploading-vddk.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16847 Add Operator update workflow to OLM docs
  applications/operators/olm-understanding-olm.adoc
  images/olm-catalogsource.png
  images/olm-channels.png
  images/olm-replaces.png
  images/olm-skipping-updates.png
  images/olm-z-stream.png
  modules/olm-architecture.adoc
  modules/olm-csv.adoc
  modules/olm-dependency-resolution.adoc
  modules/olm-upgrades.adoc
Labels: size/L

#16670 Confirm the default number of primary shards for application and operations indices equals data node count
  modules/cluster-logging-about-elasticsearch.adoc
  modules/cluster-logging-deploy-subscription.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/S

#16562 PROD-615-proxy-enablement
  _topic_map.yml
  modules/nw-proxy-configure-object.adoc
  modules/nw-proxy-remove.adoc
  networking/enable-cluster-wide-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16851 Adding Version to Release Notes
  modules/serverless-rn-new-features.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16807 Logging tolerations
  _topic_map.yml
  logging/config/cluster-logging-kibana.adoc
  logging/config/cluster-logging-tolerations.adoc
  modules/cluster-logging-curator-tolerations.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-fluentd-tolerations.adoc
  modules/cluster-logging-kibana-tolerations.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16850 First draft of ShiftStack IPI content
  _topic_map.yml
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer.adoc
  installing/installing_openstack/installing-openstack-load-balancing.adoc
  installing/installing_openstack/installing-openstack-troubleshooting.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-osp-about-kuryr.adoc
  modules/installation-osp-accessing-api-floating.adoc
  modules/installation-osp-accessing-api-no-floating.adoc
  modules/installation-osp-accessing-api.adoc
  modules/installation-osp-balancing-external-loads.adoc
  modules/installation-osp-configuring-floating-ip.adoc
  modules/installation-osp-creating-image.adoc
  modules/installation-osp-default-deployment.adoc
  modules/installation-osp-describing-cloud-parameters.adoc
  modules/installation-osp-destroying-cluster.adoc
  modules/installation-osp-enabling-kuryr.adoc
  modules/installation-osp-enabling-swift.adoc
  modules/installation-osp-installation-parameters.adoc
  modules/installation-osp-troubleshooting.adoc
  modules/installation-osp-verifying-cluster-status.adoc
  modules/installation-osp-verifying-external-network.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.2, size/XL

#16655 BZ-1729195: Indicated pods must be privileged for block volumes.
  modules/storage-persistent-storage-block-volume.adoc
Labels: QE Required, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16594 OSDOCS-485: Updated CSI instructions for OCP 4.2
  modules/persistent-storage-csi-dynamic-provisioning.adoc
  modules/persistent-storage-csi-example-deployment.adoc
  storage/persistent-storage/persistent-storage-csi.adoc
Labels: QE Required, branch/enterprise-4.2, size/L
