Repository openshift/openshift-docs, pull requests merged in 2019-07, with the labels that each got.

#15629 Fixed API version for autoscaling ReplicationController examples
  dev_guide/pod_autoscaling.adoc
Labels: size/XS

#15544 Add note about log length in the web console
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#15672 [enterprise-3.9] Add note about log length in the web console
  install_config/master_node_configuration.adoc
Labels: size/XS

#15663 Bug 1684134 add multi-stage builds TP line to Release Notes for 3.11
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS

#15674 [enterprise-3.7] Add note about log length in the web console
  install_config/master_node_configuration.adoc
Labels: size/S

#14842 CNV 2.0 release notes
  cnv/cnv_release_notes/cnv-release-notes.adoc
  modules/cnv-document-attributes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15600 Editing CLO section of Infra MachineSet topc
  logging/config/efk-logging-configuring-about.adoc
  modules/infrastructure-moving-logging.adoc
  modules/nodes-scheduler-default-creating.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15683 Fix bullet list in exported field
  modules/efk-logging-exported-fields-default.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15607 Cnv 1604
  cnv/cnv_users_guide/cnv-delete-vms.adoc
  modules/cnv-delete-vm-web.adoc
  modules/cnv-deleting-vms.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15529 Cnv 1602
  cnv/cnv_users_guide/cnv-create-vms.adoc
  modules/cnv-cloud-init-fields-web.adoc
  modules/cnv-create-vms-ref-table-wizard-fields-web.adoc
  modules/cnv-creating-vm-wizard-web.adoc
  modules/cnv-creating-vm-yaml-web.adoc
  modules/cnv-creating-vm.adoc
  modules/cnv-networking-wizard-fields-web.adoc
  modules/cnv-storage-wizard-fields-web.adoc
  modules/cnv-vm-storage-volume-types.adoc
  modules/cnv-vm-wizard-fields-web.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15271 Included initial draft of a script to search for unused modules.
  _unused_topics/README
  scripts/find_unused.py
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15692 CNV-module-cleanup
  cnv/cnv_users_guide/cnv-accessing-vm-consoles.adoc
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-create-vms-ref-table-wizard-fields-web.adoc
  modules/cnv-vm-rdp-console-web.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15697 Updated script to exclude cnv and ossm files.
  scripts/find_unused.py
Labels: size/XS

#15625 New assembly and modules for CNV-1616 Editing VMs
  cnv/cnv_users_guide/cnv-edit-vms.adoc
  modules/cnv-editing-vm-cli.adoc
  modules/cnv-editing-vm-web.adoc
  modules/cnv-editing-vm-yaml-web.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15669 search: avoid iframe
  _javascripts/hc-search.js
  _stylesheets/search.css
  _templates/_page_openshift.html.erb
  _templates/_search_dedicated.html.erb
  _templates/_search_enterprise.html.erb
  _templates/_search_online.html
  _templates/_search_origin.html.erb
  _templates/_search_other.html
  search-commercial.html
Labels: size/L

#15707 CNV: fix link to attributes file
  cnv/cnv_users_guide/cnv-create-vms.adoc
  cnv/cnv_users_guide/cnv-delete-vms.adoc
  cnv/cnv_users_guide/cnv-edit-vms.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15710 CNV link fixes
  cnv/cnv_install/cnv-installing-virtctl.adoc
  cnv/cnv_users_guide/cnv-attaching-vm-multiple-networks.adoc
  cnv/cnv_users_guide/cnv-configuring-pxe-booting.adoc
  cnv/cnv_users_guide/cnv-installing-qemu-guest-agent.adoc
  cnv/cnv_users_guide/cnv-installing-virtio-drivers-on-new-windows-vm.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15713 [master-3] search: avoid iframe
  _javascripts/hc-search.js
  _stylesheets/search.css
  _templates/_page_openshift.html.erb
  _templates/_search_dedicated.html.erb
  _templates/_search_enterprise.html.erb
  _templates/_search_online.html
  _templates/_search_origin.html.erb
  _templates/_search_other.html
  search-commercial.html
Labels: size/L

#15644 Add master node sizing recommendations
  modules/master-node-sizing.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/M

#15716 Updated release notes for RHSA-2019:1636
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#15702 removing hpa refs
  install_config/cluster_metrics.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#15717 4.1.4 release notes added
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/L

#15721 Added OCE for 4.1 docs
  _topic_map.yml
  index-commercial.html
  welcome/oce_about.adoc
Labels: size/L

#15500 redeploy efk certificates on 3.10
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, size/M

#15499 redeploy efk certificates on 3.9
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.9, size/M

#15682 Removing prereq to get name of Cluster Logging CR
  modules/efk-logging-configuring-node-selector.adoc
  modules/efk-logging-curator-schedule.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-limits.adoc
  modules/efk-logging-elasticsearch-persistent-storage-empty.adoc
  modules/efk-logging-elasticsearch-storage.adoc
  modules/efk-logging-fluentd-collector.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-kibana-limits.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-management-state-changing.adoc
  modules/efk-logging-uninstall-efk.adoc
  modules/infrastructure-moving-logging.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15720 Use registry.access.redhat.com
  using_images/s2i_images/dot_net_core.adoc
Labels: Peer Review Needed, branch/enterprise-3.10, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#15675 [enterprise-3.9] Add note about log length in the web console
  install_config/master_node_configuration.adoc
Labels: size/S

#15698 bumped latest tags to 3.9.85
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/S

#15699 added release notes stub for 3.9.85
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#15737 Fix bz1727760: use consistent storage class name
  install_config/persistent_storage/topics/glusterfs_dynamic_provisioning.adoc
Labels: size/XS

#15657 Fix a gramatic error
  architecture/additional_concepts/dynamic_admission_controllers.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, lgtm, size/XS

#15718 Fixing typo in chown command
  day_two_guide/topics/proc_scaling-etcd-manual.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#15741 Fix bz1727861: use consistent indentation level for example yaml
  install_config/persistent_storage/topics/glusterfs_dynamic_provisioning.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#15753 removed istio from the TP table
  release_notes/ocp-4-1-release-notes.adoc
Labels: size/XS

#15174 BZ1676399 - Upgrade documentation if oreg_url changes
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/S

#15756 BZ1725229 quick typo fix
  install_config/topics/managing_registry_credentials_install.adoc
Labels: branch/enterprise-3.11, size/XS

#15760 BZ1652065-missing forward slash
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#15263 Update tag version for glusterfs
  install/configuring_inventory_file.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/topics/glusterfs_images.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/M

#15733 Fix broken link to example on master-3 branch
  admin_guide/high_availability.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#15606 Clarify which NTP package is used and when
  day_two_guide/topics/ntp_synchronization.adoc
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#15774 [enterprise-3.10] Update tag version for glusterfs
  install/configuring_inventory_file.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
  install_config/persistent_storage/topics/glusterfs_images.adoc
Labels: branch/enterprise-3.10, size/M

#15048 bug 1712579 no pull secret for RHEL playbook
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-ansible-parameters.adoc
  modules/rhel-compute-updating.adoc
Labels: branch/enterprise-4.2, size/M

#15779 QE Review of CNV-1604 Deleting VMs
  modules/cnv-deleting-vms.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15685 Adding release note for BZ1717930
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15777 CNV-1602 Edits from QE Round 1
  cnv/cnv_users_guide/cnv-create-vms.adoc
  modules/cnv-creating-vm-wizard-web.adoc
  modules/cnv-creating-vm-yaml-web.adoc
  modules/cnv-vm-wizard-fields-web.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15780 QE Feedback for CNV-1616 Editing VMs
  modules/cnv-editing-vm-web.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15764 CNV - QE feedback for User Guide stories
  modules/cnv-accessing-vmi-web.adoc
  modules/cnv-importing-vm-datavolume.adoc
  modules/cnv-openshift-client-commands.adoc
  modules/cnv-virtctl-commands.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15763 CNV - QE feedback for Installation guide
  cnv/cnv_install/preparing-cluster-for-cnv.adoc
  modules/cnv-deleting-custom-resource.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-subscribing-to-hco-catalog.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15778 CNV - QE feedback for migration/maintenance content
  cnv/cnv_users_guide/cnv-configuring-vmi-eviction-strategy.adoc
  cnv/cnv_users_guide/cnv-live-migration.adoc
  cnv/cnv_users_guide/cnv-migrate-vmi.adoc
  modules/cnv-configuring-live-migration-limits.adoc
  modules/cnv-configuring-vm-live-migration-cli.adoc
  modules/cnv-configuring-vmi-live-migration-cli.adoc
  modules/cnv-enabling-vm-live-migration-cli.adoc
Labels: size/M

#15700 BZ-1724889: Updated note to tell users to keep cluster running for 24…
  modules/installation-generate-aws-user-infra.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-overview.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/S

#15801 Fix typo
  welcome/oce_about.adoc
Labels: branch/enterprise-3.11, size/XS

#15802 Fix typo
  welcome/oce_about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15759 CNV - QE update for Networking user stories
  cnv/cnv_users_guide/cnv-using-the-default-pod-network-with-cnv.adoc
  modules/cnv-configuring-masquerade-mode-cli.adoc
  modules/cnv-connecting-resource-bridge-network.adoc
  modules/cnv-template-vm-config.adoc
  modules/cnv-template-windows-vmi.adoc
  modules/cnv-viewing-vmi-ip-cli.adoc
  modules/cnv-viewing-vmi-ip-web.adoc
  modules/cnv-vm-create-nic-web.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15807 CNV - QE feedback for storage stories
  modules/cnv-creating-blank-disk-datavolumes.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-storage-wizard-fields-web.adoc
Labels: size/M

#15813 Fix busted include
  cnv/cnv_users_guide/cnv-using-the-default-pod-network-with-cnv.adoc
Labels: size/XS

#15423 BZ-1676372 Added section on creating certificate chain.
  install_config/certificate_customization.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#15819 Elasticsearch 3.11 Logging Performance Edits
  install_config/aggregate_logging.adoc
  install_config/aggregate_logging_sizing.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9

#15822 BZ-1724563: Removed RBD examples.
  modules/storage-persistent-storage-nfs-group-ids.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15821 samples operator resource is v1, not v1alpha1
  modules/samples-operator-crd.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15772 EgressNetworkPolicy only supports cidrSelector and dnsName
  admin_guide/managing_networking.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#15838 [enterprise-3.9] EgressNetworkPolicy only supports cidrSelector and dnsName
  admin_guide/managing_networking.adoc
Labels: branch/enterprise-3.9, size/M

#15642 Update apiserver.doc
  authentication/certificates/api-server.adoc
  modules/customize-certificates-api-add-named.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15817 Bug 1661562: Rm <node2> from oc adm drain cmds
  admin_guide/manage_nodes.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, bugzilla/invalid-bug, size/M

#15843 [enterprise-3.11] Rm <node2> from oc adm drain cmds
  admin_guide/manage_nodes.adoc
Labels: size/M

#15844 [enterprise-3.10] Rm <node2> from oc adm drain cmds
  admin_guide/manage_nodes.adoc
Labels: size/M

#15845 [enterprise-3.9] Rm <node2> from oc adm drain cmds
  admin_guide/manage_nodes.adoc
Labels: size/M

#15719 Clarify behavior of sticky sessions and service weights
  architecture/topics/sticky_sessions.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#15805 BZ1725848 Release Notes
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15851 Fix bz1729334: remove GCE storage reference
  modules/dynamic-provisioning-change-default-class.adoc
Labels: size/XS

#15856 Rm servicemesh dirs from 3.10 branch
  servicemesh-install/images/grafana-dashboard-no-traffic.png
  servicemesh-install/images/grafana-home-screen.png
  servicemesh-install/images/grafana-mesh-no-traffic.png
  servicemesh-install/images/grafana-mesh-with-traffic.png
  servicemesh-install/images/grafana-services.png
  servicemesh-install/images/grafana-workloads.png
  servicemesh-install/images/jaeger-main-screen.png
  servicemesh-install/images/jaeger-spans.png
  servicemesh-install/images/kiali-graph.png
  servicemesh-install/images/kiali-istio-config.png
  servicemesh-install/images/kiali-istio-config2.png
  servicemesh-install/images/kiali-login.png
  servicemesh-install/images/kiali-services-details.png
  servicemesh-install/images/kiali-services-list.png
  servicemesh-install/images/prometheus-home-screen.png
  servicemesh-install/images/prometheus-metrics.png
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-overview.adoc
  servicemesh-install/topics/install-post.adoc
  servicemesh-install/topics/install-prerequisites.adoc
  servicemesh-install/topics/install-remove.adoc
  servicemesh-install/topics/install-supported-config.adoc
  servicemesh-install/topics/install-upgrade.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-install/topics/servicemesh-architecture.adoc
  servicemesh-install/topics/servicemesh-overview.adoc
  servicemesh-install/topics/tutorial-bookinfo.adoc
  servicemesh-install/topics/tutorial-grafana.adoc
  servicemesh-install/topics/tutorial-jaeger-tracing.adoc
  servicemesh-install/topics/tutorial-kiali.adoc
  servicemesh-install/topics/tutorial-prometheus.adoc
  servicemesh-install/topics/tutorial-rhoar-missions.adoc
  servicemesh-install/topics/tutorials.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-deprecated-features.adoc
  servicemesh-release-notes/topics/rn-fixed-issues.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
  servicemesh-release-notes/topics/rn-technology-preview.adoc
  servicemesh-release-notes/topics/servicemesh-overview.adoc
  servicemesh-release-notes/topics/support.adoc
Labels: size/XXL

#15435 Bug 1721225: fix kubelet reservation example
  modules/nodes-nodes-resources-configuring-setting.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, bugzilla/valid-bug, size/S

#15855 Fix bz1729350: PV is listed as Physical Volume instead of Persistent …
  architecture/understanding-development.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15866 fixup for original BZ1723278 pr
  install_config/cluster_metrics.adoc
Labels: size/XS

#15370 Bug 1718163 Update Exposing Registry Content
  modules/registry-exposing-non-secure-registry-manually.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  registry/securing-exposing-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15830 Change default project added in error
  install_config/aggregate_logging.adoc
  install_config/aggregate_logging_sizing.adoc
Labels: branch/enterprise-3.9, size/S

#15686 Upgrade docs for OCP 3.11 - Example Given in Logging Ansible Variables Section is misleading
  install_config/aggregate_logging.adoc
Labels: size/XS

#15877 Fixing release note regarding Read-Write-Many
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15840 Moved VMware import into Create VMs assembly, added QA updates.
  cnv/cnv_users_guide/cnv-create-vms.adoc
  cnv/cnv_users_guide/cnv-importing-vmware-vm-to-ocp.adoc
  modules/cnv-importing-vmware-vm.adoc
  modules/cnv-updating-imported-vm-network-name.adoc
  modules/cnv-uploading-vddk.adoc
  modules/cnv-vm-wizard-fields-web.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15665 bug 1725079 adding bare metal install context
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-dns-user-infra.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/rhel-ansible-parameters.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15882 [enterprise-4.1] bug 1725079 adding bare metal install context
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-dns-user-infra.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/rhel-ansible-parameters.adoc
Labels: size/M

#15816 Removing references to resources that cannot be configured and are no…
  installing/install_config/customizations.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15483 osdocs-398 draft of cluster/machineautoscaling updates
  machine_management/applying-autoscaling.adoc
  modules/cluster-autoscaler-cr.adoc
  modules/machine-autoscaler-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/M

#15890 Adding comment that AMQ links to these docs
  cli_reference/get_started_cli.adoc
Labels: branch/enterprise-3.11, size/XS

#15891 Adding comment that AMQ links to these docs
  modules/cli-installing-cli.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15896 BZ1728849: Typo fix
  modules/installation-user-infra-machines-iso.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15900 Fix typo in secrets section
  modules/nodes-pods-secrets-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15906 amended release notes summary
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/XS

#15865 Resolving BZ1705663 for master-3 content
  modules/cnv_cloning_pvc_datavolume.adoc
  modules/cnv_cloning_pvc_virtualmachine.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#15864 Resolving BZ1686775 for master-3 content
  dev_guide/pod_autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#15470 Bug BZ1661446 - Added variables information
  install/configuring_inventory_file.adoc
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
Labels: branch/enterprise-3.11, size/L

#15908 Bug 1726705
  admin_guide/manage_users.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#15904 Bug 1729534
  modules/nodes-containers-health-about.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15687 BZ-1717554: Added a step to remove the etcd directory
  admin_guide/topics/proc_removing-failed-etcd-member.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#15636 Update OSDK CLI to v0.8.0 usage
  modules/building-memcached-operator-using-osdk.adoc
  modules/osdk-ansible-k8s-module-inside-operator.adoc
  modules/osdk-building-ansible-operator.adoc
  modules/osdk-building-helm-operator.adoc
  modules/osdk-cli-reference-add.adoc
  modules/osdk-cli-reference-new.adoc
  modules/osdk-cli-reference-test.adoc
  modules/osdk-installing-cli.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15929 bug 1725235 fix typos
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/XS

#15932 bug 1724028 remove startingCSV line in section 2f
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15937 add clarification for OLM operator version syntax
  applications/operator_sdk/osdk-generating-csvs.adoc
  modules/olm-csv.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15940 typo fix: s/manger/manager/
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15229 Update the storage recommendations for metrics
  modules/recommended-configurable-storage-technology.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15920 added 4.1.6 release notes stub
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#15947 fix mdap typo
  admin_guide/manage_users.adoc
Labels: branch/enterprise-3.7, size/XS

#15948 bug 1725235 fix typos in section 3b on master-3 branch
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/XS

#15885 Fix the Elasticsearch Operator install based on slack -typo
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.1, size/XS

#15952 bug 172535 removed startingCSV and callout 3 in example subscription 2f
  modules/efk-logging-deploy-subscription.adoc
Labels: size/S

#15953 fixing typo
  welcome/index.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15913 Added serverless placeholder dir and entry in topic map
  _topic_map.yml
  serverless/PLACEHOLDER
  serverless/images
  serverless/modules
Labels: Peer Review Done, branch/enterprise-4.2, size/S

#15959 bz1724028 remove callout ref
  modules/efk-logging-deploy-subscription.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#15958 Bz#1730598
  cnv/cnv_users_guide/cnv-create-vms.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15963 CNV - Importing VMs structural change
  cnv/cnv_users_guide/cnv-create-vms.adoc
  cnv/cnv_users_guide/cnv-importing-vmware-vm.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15970 BZ-1720096 updating a telemetry query
  modules/telemetry-showing-data-collected-from-the-cluster.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15262 Clarify storage recommendations for monitoring stack
  architecture/additional_concepts/storage.adoc
  install_config/monitoring/configuring-openshift-cluster-monitoring.adoc
  release_notes/ocp_3_11_release_notes.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_monitoring.adoc
Labels: branch/enterprise-3.11, size/M

#15421 BZ-1692856: Removing references to set-credentials.
  cli_reference/cli_by_example_content.adoc
  cli_reference/manage_cli_profiles.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/L

#15981 Fix malformed URL in link to Anacona kickstart docs
  modules/rhcos-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15988 Fixing typo in bare metal installation
  modules/installation-initializing-manual.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15975 Replace Elasticsearch Operator install
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.2, size/L

#15993 Revert "Replace Elasticsearch Operator install"
  modules/efk-logging-deploy-subscription.adoc
Labels: size/L

#15973 Example list of system-cluster-critical priority class is wrong
  modules/nodes-pods-priority-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15488 bug 1720178 updating post-install CSR approval
  modules/installation-approve-csrs.adoc
  modules/installation-infrastructure-user-infra.adoc
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15681 TP12 Modularization Work
  _topic_map.yml
  modules/ossm-architecture.adoc
  modules/ossm-automatic-sidecar-injection.adoc
  modules/ossm-configure-security-constraints.adoc
  modules/ossm-control-plane-deploy.adoc
  modules/ossm-control-plane-verify.adoc
  modules/ossm-cr-cni.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-gateway.adoc
  modules/ossm-cr-istio-global.adoc
  modules/ossm-cr-kiali.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-cr-parameters.adoc
  modules/ossm-cr-pilot.adoc
  modules/ossm-cr-threescale.adoc
  modules/ossm-cr-tracing-jaeger.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-installation-activities.adoc
  modules/ossm-manual-sidecar-injection.adoc
  modules/ossm-master-configuration.adoc
  modules/ossm-mixer-policy.adoc
  modules/ossm-mt-installation.adoc
  modules/ossm-mt-known-issues.adoc
  modules/ossm-mt-namespaces.adoc
  modules/ossm-mt-vs-clusterwide.adoc
  modules/ossm-operator-install.adoc
  modules/ossm-operator-verify.adoc
  modules/ossm-remove-control-plane.adoc
  modules/ossm-remove-operator.adoc
  modules/ossm-remove-projects.adoc
  modules/ossm-security-constraints.adoc
  modules/ossm-supported-configurations.adoc
  modules/ossm-tech-preview.adoc
  modules/ossm-threescale-authentication.adoc
  modules/ossm-threescale-caching.adoc
  modules/ossm-threescale-cr.adoc
  modules/ossm-threescale-integrate.adoc
  modules/ossm-threescale-integration-settings.adoc
  modules/ossm-threescale-manifests.adoc
  modules/ossm-threescale-metrics.adoc
  modules/ossm-threescale-routing.adoc
  modules/ossm-threescale-templates.adoc
  modules/ossm-understanding-service-mesh.adoc
  modules/ossm-updating-master-configuration.adoc
  modules/ossm-updating-node-configuration.adoc
  modules/ossm-vs-istio.adoc
  service_mesh/service_mesh_install/installing-mt-ossm.adoc
  service_mesh/service_mesh_install/installing-ossm.adoc
  service_mesh/service_mesh_install/prepare-to-deploy-applications-ossm.adoc
  service_mesh/service_mesh_install/preparing-ossm-installation.adoc
  service_mesh/service_mesh_install/removing-ossm.adoc
  service_mesh/service_mesh_install/understanding-ossm.adoc
  service_mesh/threescale_adapter/threescale-adapter.adoc
Labels: branch/enterprise-4.1, size/XXL

#15862 Update Welcome page for OSD v4
  modules/dedicated-admin-granting-permissions.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/dedicated-managing-dedicated-administrators.adoc
  modules/dedicated-managing-quotas-and-limit-ranges.adoc
  modules/dedicated-managing-service-accounts.adoc
  modules/managing-dedicated-readers-group.adoc
  welcome/index.adoc
Labels: branch/dedicated, branch/enterprise-4.1, size/M

#15884 BZ-1724488: Added description of openshift_docker_ent_reg variable
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#16001 testing migrating metering install docs
  metering/images
  metering/metering-configuring-metering.adoc
  metering/metering-installing-metering.adoc
  metering/metering-using-metering.adoc
  metering/modules
Labels: branch/enterprise-4.2, size/S

#15624 [ModDocs] Modularized the tutorial file.
  _topic_map.yml
  images/ossm-grafana-dashboard-no-traffic.png
  images/ossm-grafana-home-screen.png
  images/ossm-grafana-mesh-no-traffic.png
  images/ossm-grafana-mesh-with-traffic.png
  images/ossm-grafana-services.png
  images/ossm-grafana-workloads.png
  images/ossm-jaeger-main-screen.png
  images/ossm-jaeger-spans.png
  images/ossm-kiali-applications-details.png
  images/ossm-kiali-graph.png
  images/ossm-kiali-istio-config.png
  images/ossm-kiali-istio-config2.png
  images/ossm-kiali-legend.png
  images/ossm-kiali-login.png
  images/ossm-kiali-overview.png
  images/ossm-kiali-services-details.png
  images/ossm-kiali-services-list.png
  images/ossm-kiali-workloads-details.png
  images/ossm-prometheus-home-screen.png
  images/ossm-prometheus-metrics.png
  modules/ossm-document-attributes.adoc
  modules/ossm-tutorial-bookinfo-adding-destination-rules.adoc
  modules/ossm-tutorial-bookinfo-install.adoc
  modules/ossm-tutorial-bookinfo-overview.adoc
  modules/ossm-tutorial-bookinfo-removing.adoc
  modules/ossm-tutorial-bookinfo-verify-install.adoc
  modules/ossm-tutorial-grafana-accessing.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  modules/ossm-tutorial-kiali-accessing-console.adoc
  modules/ossm-tutorial-kiali-applications-page.adoc
  modules/ossm-tutorial-kiali-graph.adoc
  modules/ossm-tutorial-kiali-istio-config.adoc
  modules/ossm-tutorial-kiali-services-page.adoc
  modules/ossm-tutorial-kiali-workloads-page.adoc
  modules/ossm-tutorial-prometheus-querying-metrics.adoc
  service_mesh/service_mesh_install/ossm-example-bookinfo.adoc
  service_mesh/service_mesh_install/ossm-tutorial-grafana.adoc
  service_mesh/service_mesh_install/ossm-tutorial-jaeger-tracing.adoc
  service_mesh/service_mesh_install/ossm-tutorial-kiali.adoc
  service_mesh/service_mesh_install/ossm-tutorial-prometheus.adoc
  service_mesh/service_mesh_release_notes/images
  service_mesh/service_mesh_release_notes/modules
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XL

#15560 [ModDocs] Service Mesh Release Notes.
  _topic_map.yml
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
  modules/ossm-servicemesh-overview.adoc
  modules/ossm-support.adoc
  service_mesh/service_mesh_install/images
  service_mesh/service_mesh_install/modules
  service_mesh/servicemesh-release-notes.adoc
Labels: branch/enterprise-4.1, size/L

#15832 Elasticsearch Logging Performance Edits
  modules/efk-logging-deploy-storage-considerations.adoc
  modules/efk-logging-deploying-storage-considerations.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16006 Fix link issues in Service Mesh docs install
  modules/ossm-threescale-integrate.adoc
Labels: size/XS

#16008 Adding correct links to images and modules for SM
  service_mesh/service_mesh_install/images
  service_mesh/service_mesh_install/modules
  service_mesh/threescale_adapter/images
  service_mesh/threescale_adapter/modules
Labels: size/XS

#16010 removed images attribute from SM
  modules/ossm-document-attributes.adoc
Labels: size/XS

#16005 Revert "Revert "Replace Elasticsearch Operator install""
  modules/efk-logging-deploy-subscription.adoc
Labels: size/L

#15992 [enterprise-4.2] Replace Elasticsearch Operator install
  modules/efk-logging-deploy-subscription.adoc
Labels: size/L

#15930 bumped latest tags 3.9.89
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/S

#16012 Some title name fixes for SM and CNV
  cnv/cnv_install/cnv-about-cnv.adoc
  service_mesh/service_mesh_install/understanding-ossm.adoc
Labels: size/XS

#15931 added 3.9.89 RN stub
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#15946 added 3.11.129 release notes stub and latest-tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#16014 added 4.1.7 release notes
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#15933 bumped latest tags 3.10.153
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, size/S

#15934 added release notes stub 3.10.153
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#16016 Bug 1720351 Remove broken link
  install_config/cluster_metrics.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.9, size/XS

#15808 CNV 2.0 GA
  _topic_map.yml
  images/ellipsis-v.svg
Labels: size/L

#16019 CNV 2.0 GA
  _topic_map.yml
Labels: size/L

#16017 4.2 installation stubs
  _topic_map.yml
  installing/install_config/configuring-custom-ca.adoc
  installing/installing_azure/installing-azure-account.adoc
  installing/installing_azure/installing-azure-customizations.adoc
  installing/installing_azure/installing-azure-default.adoc
  installing/installing_azure/uninstalling-cluster-azure.adoc
  installing/installing_disconnected/installing-disconnected-preparations.adoc
  installing/installing_disconnected/installing-disconnected.adoc
  installing/installing_gcp/installing-gcp-account.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-default.adoc
  installing/installing_gcp/uninstalling-cluster-gcp.adoc
  updating/updating-disconnected-cluster.adoc
Labels: branch/enterprise-4.2, size/L

#14618 osdocs-354 getting traffic into cluster
  _topic_map.yml
  modules/customize-certificates-replace-default-router.adoc
  modules/nw-configuring-route-timeouts.adoc
  modules/nw-create-load-balancer-service.adoc
  modules/nw-creating-project-and-service.adoc
  modules/nw-exposing-service.adoc
  modules/nw-ingress-controller-status.adoc
  modules/nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate.adoc
  modules/nw-ingress-creating-an-edge-route-with-a-custom-certificate.adoc
  modules/nw-ingress-operator-logs.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  modules/nw-ingress-view.adoc
  modules/nw-installation-ingress-config-asset.adoc
  modules/nw-scaling-ingress-controller.adoc
  modules/nw-using-cookies-keep-route-statefulness.adoc
  modules/nw-using-ingress-and-routes.adoc
  modules/nw-using-load-balancer-getting-traffic.adoc
  modules/nw-using-nodeport.adoc
  modules/nw-using-service-external-ip.adoc
  networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc
  networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-load-balancer.adoc
  networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-nodeport.adoc
  networking/configuring-ingress-cluster-traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc
  networking/configuring-ingress-cluster-traffic/overview-traffic.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XL

#15982 Audit components for arch/OS label usage
  modules/nodes-nodes-viewing-listing-pods.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nw-multinetwork-sriov.adoc
Labels: branch/enterprise-4.2, lgtm, size/S

#16015 TP12 Release Notes Update (Add MAISTRA-684)
  modules/ossm-cr-tracing-jaeger.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
  modules/ossm-support.adoc
  service_mesh/servicemesh-release-notes.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15471 Improve and fixing managing nodes section
  modules/nodes-nodes-managing-about.adoc
Labels: size/M

#16031 BZ: 1724372: removed easter egg
  _javascripts/page-loader.js
Labels: size/S

#16035 Updated TP note to align with published standard.
  modules/technology-preview.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16038 BZ1726493 - fixed 2 typos in release notes/images
  release_notes/ocp-4-1-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#15869 Bug 1722922 - Add running entitled builds to topic map
  _topic_map.yml
  builds/running-entitled-builds.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/XS
