Repository openshift/openshift-docs, pull requests merged in 2019-08, with the labels that each got.

#16089 Edit suggested in file nodes/nodes/nodes-nodes-working.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-nodes-working-marking.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16085 bug 1724684 clarifying AWS key/token type
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-default.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_aws_user_infra/installing-aws-user-infra.adoc
  modules/installation-aws-iam-user.adoc
  modules/installation-extracting-infraid.adoc
  modules/installation-generate-aws-user-infra.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-initializing.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15848 Add metrics-server item to playbook component run order table - BZ 1724545
  install/running_install.adoc
Labels: branch/enterprise-3.11, size/XS

#15997 BZ-1730609: Clarify changes for 4.1
  modules/identity-provider-about-request-header.adoc
  modules/identity-provider-request-header-CR.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16098 Fix release notes table for TP features
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/XS

#15907 Bug 1723848 Add required registry oreg_auth variables
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#16060 Clarify which CSR gets automatically approved.
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16052 Shrink deployment yaml to allow for deploying community/commercial docs into separate projects
  asciibinder-template.yml
  contributing_to_docs/tools_and_setup.adoc
Labels: size/L

#16107 CNV fixes
  _topic_map.yml
  cnv_install/cnv_install.adoc
  cnv_release_notes/cnv_release_notes.adoc
  cnv_users_guide/cnv_users_guide.adoc
Labels: size/XS

#16110 Changing kebab to use png
  modules/cnv-document-attributes.adoc
  modules/common-attributes.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2

#16080 TP12 Documentation Backport to 3.11 Branch
  servicemesh-install/images/kiali-applications-details.png
  servicemesh-install/images/kiali-graph.png
  servicemesh-install/images/kiali-istio-config.png
  servicemesh-install/images/kiali-istio-config2.png
  servicemesh-install/images/kiali-legend.png
  servicemesh-install/images/kiali-login.png
  servicemesh-install/images/kiali-overview.png
  servicemesh-install/images/kiali-services-details.png
  servicemesh-install/images/kiali-services-list.png
  servicemesh-install/images/kiali-workloads-details.png
  servicemesh-install/topics/appendix-threescale-adapter.adoc
  servicemesh-install/topics/application-requirements.adoc
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-multi-tenant.adoc
  servicemesh-install/topics/install-overview.adoc
  servicemesh-install/topics/install-post.adoc
  servicemesh-install/topics/install-prerequisites.adoc
  servicemesh-install/topics/install-remove.adoc
  servicemesh-install/topics/install-supported-config.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-install/topics/servicemesh-architecture.adoc
  servicemesh-install/topics/servicemesh-istio-comparison.adoc
  servicemesh-install/topics/servicemesh-overview.adoc
  servicemesh-install/topics/tutorial-kiali.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-fixed-issues.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: branch/enterprise-3.11, size/XXL

#16025 correction in doc for logging installation in OCP v4.1 correct branch
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.1, size/XS

#16056 When deploying logging, storage config is stripped out of the imported ClusterLogging instance
  modules/efk-logging-deploying-about.adoc
  modules/efk-logging-elasticsearch-storage.adoc
Labels: size/S

#16048 BZ-1728686: Changed steps to use script that is now provided
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/M

#16117 CNV - l10n minor fix
  modules/cnv_openshift_commands.adoc
Labels: size/XS

#16104 bz-1734610 Remove command
  day_two_guide/topics/proc_restoring-etcd.adoc
  day_two_guide/topics/proc_scaling-etcd-manual.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#15905 add base documentation for all operator+config resources
  installing/install_config/customizations.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#14292 Update host_health.adoc
  day_two_guide/topics/host_health.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#15173 Fix typos and copy and paste errors
  install_config/certificate_customization.adoc
Labels: size/S

#16140 [enterprise-3.6] Fix typos and copy and paste errors
  install_config/certificate_customization.adoc
Labels: size/XS

#16143 Follow-up add base documentation for all operator+config resources
  installing/install_config/customizations.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/S

#16063 SRVCOM-490 documentation for Knative services
  _topic_map.yml
  modules/configuring-knative-services-domains.adoc
  modules/creating-knative-services.adoc
  modules/deploying-serverless-apps.adoc
  modules/domain-templates-knative-services.adoc
  modules/interacting-serverless-apps.adoc
  modules/knative-serving.adoc
  serverless/configuring-knative-services.adoc
  serverless/getting-started-knative-services.adoc
  serverless/understanding-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15126 OSDOCS-347 Bring forward Creating new applications content
  _topic_map.yml
  applications/application-life-cycle-management/creating-new-applications.adoc
  modules/applications-create-using-cli-image.adoc
  modules/applications-create-using-cli-modify.adoc
  modules/applications-create-using-cli-source-code.adoc
  modules/applications-create-using-cli-template.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XL

#16087 Improve visibility of association of Ingress Operator with routing
  modules/nw-scaling-ingress-controller.adoc
  networking/ingress-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#15967 Kubernetes Feature Flag doc is confusing and incorrect
  modules/feature-gate-features.adoc
  modules/nodes-cluster-enabling-features-cluster.adoc
  modules/nodes-cluster-features-about.adoc
  nodes/clusters/nodes-cluster-enabling-features.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16135 Changes in Node Tuning Operator 4.2 functionality.
  modules/accessing-an-example-cluster-node-tuning-operator-specification.adoc
  modules/custom-tuning-example.adoc
  modules/node-tuning-operator.adoc
  scalability_and_performance/using-node-tuning-operator.adoc
Labels: branch/enterprise-4.2, lgtm, size/M

#15258 Adds documentation for JENKINS_UC_INSECURE variable
  using_images/other_images/jenkins.adoc
Labels: branch/enterprise-3.11, size/S

#16162 Update clusterrole names and rm dedicated-readers for OSD v4
  administering_a_cluster/dedicated-admin-role.adoc
  modules/dedicated-admin-role-overview.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/rbac-viewing-local-roles.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16050 OSDOCS-613: Mention the OpenShift server version in oc version output
  modules/cli-developer-other.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#16096 BZ 1713508 Apply feedback to Cluster Monitoring
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  modules/monitoring-maintenance-and-support.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16174 fixes formatting
  modules/images-imagestream-external-image-tags.adoc
Labels: branch/enterprise-4.1

#16173 [enterprise-4.1] fixes formatting
  modules/images-imagestream-external-image-tags.adoc
Labels: branch/enterprise-4.1, size/XS

#16109 Fix typos for variables where OpenShift is used (fix case to be consi…
  install_config/configuring_nsxtsdn.adoc
Labels: branch/enterprise-3.11, size/S

#16142 added 4.1.9 release notes
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#16180 Edits to logging install based on slack chat
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.2, size/L

#16095 bug 1725079 updates based on more feedback
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-vsphere-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16172 Add Operator installation to OSD v4
  _topic_map.yml
  administering_a_cluster/dedicated-admin-role.adoc
  applications/operators/olm-adding-operators-to-cluster.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/olm-deleting-operators-from-a-cluster-using-cli.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  modules/olm-installing-operators-from-operatorhub.adoc
  modules/rbac-viewing-cluster-roles.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#15868 added logging docs for dedicated
  _topic_map.yml
  logging/dedicated-efk-deploying.adoc
  logging/dedicated-efk-logging.adoc
  modules/efk-logging-about-crd.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16195 Clarify confusing sentence
  admin_guide/allocating_node_resources.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#16186 bug 1739495 adjusting ingress certificate extension name
  modules/customize-certificates-replace-default-router.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16188 bug 1728932 no infra components on masters
  machine_management/creating-infrastructure-machinesets.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15727 updating information related to customer-admin-cluster role in ARO
  _topic_map.yml
  admin_guide/index.adoc
  admin_guide/manage_rbac.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#16210 [3.11] updating information related to customer-admin-cluster role in ARO
  _topic_map.yml
  admin_guide/index.adoc
  admin_guide/manage_rbac.adoc
Labels: size/M

#16211 bug1737501 - modify step 6c-6d
  modules/installation-vsphere-machines.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16154 SRVCOM-483: Monitoring docs for Serverless inc. example for autoscaler pods
  _topic_map.yml
  modules/monitoring-configuring-the-cluster-monitoring-stack.adoc
  modules/monitoring-knative-serving.adoc
  modules/verify-knative-serving-monitoring.adoc
  serverless/monitoring-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15626 Discuss behavior different for multicast in multitenant mode
  modules/nw-about-multicast.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16141 added 3.11.135 release notes stub and updated latest-tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/M

#16175 DEVEXP-388: Adding note on S3 bucket security configuration during UPI.
  modules/registry-configuring-storage-aws-user-infra.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16196 amended dedicated docs per review
  _topic_map.yml
  applications/quotas/quotas-setting-per-project.adoc
  authentication/dedicated-understanding-authentication.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/understanding-authentication.adoc
  authentication/using-rbac.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-managing-quotas-and-limit-ranges.adoc
  modules/storage-persistent-storage-lifecycle.adoc
  modules/storage-persistent-storage-pv.adoc
  registry/architecture-component-imageregistry.adoc
Labels: Peer Review Done, branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16237 [enterprise-4.1] amended dedicated docs per review
  _topic_map.yml
  applications/quotas/quotas-setting-per-project.adoc
  authentication/dedicated-understanding-authentication.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/understanding-authentication.adoc
  authentication/using-rbac.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-managing-quotas-and-limit-ranges.adoc
  modules/storage-persistent-storage-lifecycle.adoc
  modules/storage-persistent-storage-pv.adoc
  registry/architecture-component-imageregistry.adoc
Labels: size/L

#16238 Various fixes for ARO
  admin_guide/managing_networking.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/core_concepts/templates.adoc
  architecture/index.adoc
  architecture/infrastructure_components/image_registry.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  architecture/networking/routes.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/daemonsets.adoc
  dev_guide/managing_images.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/secrets.adoc
  getting_started/dedicated_administrators.adoc
Labels: size/M

#16239 [enterprise-3.11] Various fixes for ARO
  admin_guide/managing_networking.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/core_concepts/templates.adoc
  architecture/index.adoc
  architecture/infrastructure_components/image_registry.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  architecture/networking/routes.adoc
  dev_guide/application_lifecycle/promoting_applications.adoc
  dev_guide/daemonsets.adoc
  dev_guide/managing_images.adoc
  dev_guide/pod_autoscaling.adoc
  dev_guide/secrets.adoc
  getting_started/dedicated_administrators.adoc
Labels: size/M

#16157 Enhance KuryrSDN configuration details
  install_config/configuring_kuryrsdn.adoc
  install_config/configuring_openstack.adoc
  install_config/topics/ocp_osp_admin_tasks.adoc
  install_config/topics/ocp_osp_provisioning.adoc
  install_config/topics/ocp_osp_sdn.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#16220 SRVCOM-519: Initial commit for autoscaling Knative Serving docs
  _topic_map.yml
  modules/configuring-scale-bounds-knative.adoc
  modules/knative-serving-concurrent-autoscaling-requests.adoc
  modules/knative-serving.adoc
  modules/monitoring-knative-serving.adoc
  serverless/configuring-knative-serving-autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16243 Fixing build failure
  applications/quotas/quotas-setting-per-project.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#16234 fixing two build warnings
  cnv/cnv_users_guide/cnv-create-vms.adoc
  images/kebab.png
  modules/ldap-syncing-rfc2307-user-defined-error.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16229 BZ-1740869: Corrected file name
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: branch/enterprise-4.2, lgtm, size/XS

#16250 SRVKS-163: OpenShift ClusterLogging Serverless
  _topic_map.yml
  modules/serverless-using-cluster-logging-find-logs-knative-serving-components.adoc
  modules/serverless-using-cluster-logging-find-logs-services-deployed.adoc
  serverless/cluster-logging-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16245 MULTI-122: Initial commit for kubefed docs (multicluster)
  _topic_map.yml
  kubefed/images
  kubefed/modules
  kubefed/understanding-kubefed.adoc
  modules/kubefed-document-attributes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16257 Fix OSD v4 role names
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/olm-deleting-operators-from-a-cluster-using-cli.adoc
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  modules/rbac-viewing-cluster-roles.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16086 bz1656397 amended backup and recovery steps for clarity
  day_two_guide/topics/proc_backing-up-etcd.adoc
  day_two_guide/topics/proc_backing-up-master.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
Labels: branch/enterprise-3.11, size/M

#16262 Fix more OSD v4 role names
  modules/dedicated-admin-role-overview.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/rbac-viewing-local-roles.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16265 Dedicated changes
  architecture/understanding-development.adoc
  authentication/dedicated-understanding-authentication.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-gitlab-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  modules/cluster-entitlements.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  welcome/accessing-your-services.adoc
  welcome/index.adoc
Labels: size/S

#16269 typo fix
  _topic_map.yml
Labels: size/XS

#16272 Dedicated to 4
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
  index-commercial.html
Labels: size/S

#16273 Dedicated to 4.1 fixes
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
Labels: size/S

#16158 bug 1531449 add note on master about restart with cloud outage
  modules/nodes-pods-configuring-restart.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16068 BZ1531449 - Added cloud integration note in Architecture
  architecture/core_concepts/pods_and_services.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#16227 added 4.1.11 release notes stub
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#16282 Fixing Deploying Logging in topic_map
  _topic_map.yml
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#15703 Bug 1686743: Formatting edits for Prometheus Cluster Monitoring assembly/modules
  getting_started/dedicated_administrators.adoc
  install_config/monitoring/accessing-prometheus-alertmanager-grafana.adoc
  install_config/monitoring/alerting-rules.adoc
  install_config/monitoring/configuring-alertmanager.adoc
  install_config/monitoring/configuring-etcd-monitoring.adoc
  install_config/monitoring/configuring-openshift-cluster-monitoring.adoc
  install_config/monitoring/overview.adoc
  install_config/monitoring/update-and-compatibility-guarantees.adoc
  install_config/prometheus_cluster_monitoring.adoc
Labels: Peer Review Done, branch/enterprise-3.11, bugzilla/valid-bug, size/L

#16051 Bug 1729505: Fix hugepages node config
  modules/configuring-huge-pages.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, bugzilla/valid-bug, size/M

#16194 Allow Whitelisting of Sysctls Configuration
  _topic_map.yml
  modules/nodes-containers-sysctls-about.adoc
  modules/nodes-containers-sysctls-setting.adoc
  modules/nodes-containers-sysctls-unsafe.adoc
  nodes/containers/nodes-containers-sysctls.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#16285 fixes/updates for CNV 2.0, inspired by recent feedback
  cnv/cnv_install/installing-container-native-virtualization.adoc
  modules/cnv-editing-template-web.adoc
  modules/cnv-editing-vm-web.adoc
  modules/cnv-initiating-vm-migration-web.adoc
  modules/cnv-preparing-to-install.adoc
  modules/cnv-subscribing-to-hco-catalog.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16294 fixed dedicated comments
  modules/dedicated-configuring-your-application-routes.adoc
  welcome/accessing-your-services.adoc
Labels: size/XS

#16274 SRVKS-188: added http2/gRPC caveat
  _topic_map.yml
  modules/interacting-serverless-apps-http2-gRPC.adoc
  modules/verifying-serverless-app-deployment.adoc
  serverless/interacting-serverless-apps.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16302 Corrected example for in_forward for external logger
  modules/efk-logging-fluentd-external.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/XS

#16305 fixing typo
  modules/installation-aws-route53.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16077 Moved the Viewing cluster logging to its own topic
  _topic_map.yml
  logging/config/efk-logging-fluentd.adoc
  logging/efk-logging-viewing.adoc
  modules/efk-logging-fluentd-log-viewing.adoc
  modules/efk-logging-viewing-logs-console.adoc
  modules/efk-logging-viewing-logs.adoc
Labels: branch/enterprise-4.2, size/L

#15425 Pod/Container can steal cpu/memory resources if cluster admin did not set minimum (not maximum) limitrange
  admin_guide/limits.adoc
  architecture/additional_concepts/other_api_objects.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#16311 Revert "Pod/Container can steal cpu/memory resources if cluster admin did not set minimum (not maximum) limitrange"
  admin_guide/limits.adoc
  architecture/additional_concepts/other_api_objects.adoc
Labels: size/M

#16312 Pod/Container can steal cpu/memory resources if cluster admin did not set minimum (not maximum) limitrange
  admin_guide/limits.adoc
  architecture/additional_concepts/other_api_objects.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/M

#16197 Bug 1714844 Clarify storage type and replica number
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-configuring-storage-vsphere.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16318 [enterprise-3.10] Pod/Container can steal cpu/memory resources if cluster admin did not set minimum (not maximum) limitrange
  admin_guide/limits.adoc
  architecture/additional_concepts/other_api_objects.adoc
Labels: size/M

#16301 OCP 4.1 cluster limits changes
  modules/openshift-cluster-limits.adoc
Labels: branch/enterprise-4.1, lgtm, size/XS

#16320 OCP 4.1 cluster limits changes
  modules/openshift-cluster-limits.adoc
Labels: branch/enterprise-4.2, size/XS

#16309 removing reference to a singlet in the install-config
  modules/installation-aws-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-vsphere-config-yaml.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16159 4.2 Kubernetes Feature Flag doc is confusing and incorrect
  modules/feature-gate-features.adoc
  modules/nodes-cluster-enabling-features-cluster.adoc
Labels: branch/enterprise-4.2, size/S

#16329 [enterprise-4.2] 4.2 Kubernetes Feature Flag doc is confusing and incorrect
  modules/feature-gate-features.adoc
  modules/nodes-cluster-enabling-features-cluster.adoc
Labels: size/M

#16331 templates: pass OSD version when searching
  _templates/_page_openshift.html.erb
  _templates/_search_dedicated.html.erb
Labels: size/XS

#15154 Bz1658687 ocp on rhv
  _topic_map.yml
  install_config/configuring_for_rhv.adoc
  install_config/configuring_rhv.adoc
  install_config/topics/configuring_rhv_objects.adoc
  install_config/topics/creating_the_bastion_virtual_machine.adoc
  install_config/topics/full_rhv_inventory.adoc
  install_config/topics/installing_with_bastion_vm.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#15874 Scrape more of _cluster/health
  modules/efk-logging-elasticsearch-status-viewing.adoc
Labels: branch/enterprise-4.2, size/M

#16330 SRVCOM-535 and SRVCOM-534: Minor changes to content and added attributes file
  _topic_map.yml
  modules/serverless-document-attributes.adoc
  serverless/cluster-logging-serverless.adoc
  serverless/configuring-knative-services.adoc
  serverless/configuring-knative-serving-autoscaling.adoc
  serverless/getting-started-knative-services.adoc
  serverless/interacting-serverless-apps.adoc
  serverless/monitoring-serverless.adoc
  serverless/serverless-architecture.adoc
  serverless/understanding-serverless.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16340 bumped latest tags for 3.10.163
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, size/S

#16341 added 3.10.163 release notes stub
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#15903 Update CRD topics for OSD v4
  _topic_map.yml
  applications/operators/olm-managing-resources-from-crds.adoc
  modules/crd-creating-aggregated-cluster-roles.adoc
  modules/crd-creating-custom-resources-from-file.adoc
  modules/crd-custom-resource-definitions.adoc
  modules/crd-inspecting-custom-resources.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16345 typo
  images/targets-and-dependencies.png
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16339 Added Unmanged prereq for Fluentd config map changes
  modules/efk-logging-fluentd-external.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16353 Rm quota subdir from OSD topic_map
  _topic_map.yml
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16261 BZ-1741289: Updating commands to use sudo
  modules/dr-recover-lost-control-plane-hosts.adoc
Labels: branch/enterprise-4.1, size/XS

#16216 modules/dr-recover-lost-control-plane-hosts: update setup-etcd-environment
  modules/dr-recover-lost-control-plane-hosts.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#16360 Add app create from Operator to OSD v4
  _topic_map.yml
  modules/olm-creating-etcd-cluster-from-operator.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16363 Fixing bad links
  nodes/scheduling/nodes-scheduler-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16367 CNV - Combining the VM and VM Template wizard fields modules
  cnv/cnv_users_guide/cnv-create-vms.adoc
  cnv/cnv_users_guide/cnv-creating-vm-template.adoc
  cnv/cnv_users_guide/cnv-importing-vmware-vm.adoc
  modules/cnv-networking-wizard-fields-web.adoc
  modules/cnv-storage-wizard-fields-web.adoc
  modules/cnv-template-wizard-fields-web.adoc
  modules/cnv-vm-wizard-fields-web.adoc
Labels: size/M

#16328 New topic for insecure registries
  modules/images-configuration-file.adoc
  modules/images-configuration-insecure.adoc
  openshift_images/image-configuration.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#15599 Update new machineset docs
  modules/machineset-creating.adoc
  modules/machineset-yaml.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/M

#16368 clarifying a note and removing a GitHub link
  install_config/oab_broker_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#16413 Creating 4.2 docs
  _distro_map.yml
Labels: branch/enterprise-4.2, size/XS

#16399 BZ-1745765: Add step to force MCD to accept cert update
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: Peer Review Done, branch/enterprise-4.2, lgtm, size/XS

#16348 BZ-1722739: Adding the new mandatory second parameter
  modules/dr-recover-lost-control-plane-hosts.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/XS

#16123 BZ-1737533: Added warning to hostnetwork SCC
  modules/security-context-constraints-about.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/XS

#16215 OSDOCS-128: Adding docs for must-gather
  _topic_map.yml
  modules/support-gather-data.adoc
  modules/support.adoc
  support/gathering-cluster-data.adoc
  support/getting-support.adoc
  support/images
  support/modules
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16401 adding jq package prereq
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16433 Swap steps in deleting Operators procedure
  modules/olm-deleting-operators-from-a-cluster-using-cli.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/S

#16127 Prometheus Alerts for Fluentd and Rsyslog Log Collection
  logging/config/efk-logging-fluentd.adoc
  modules/efk-logging-fluentd-alerts.adoc
Labels: branch/enterprise-4.2, size/L

#16432 OSDOCS-128: Adding docs for must-gather
  _topic_map.yml
  modules/support-gather-data.adoc
  modules/support.adoc
  support/gathering-cluster-data.adoc
  support/getting-support.adoc
  support/images
  support/modules
Labels: size/L

#16440 removing prereq for unmanaged state per slack
  modules/efk-logging-fluentd-external.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16444 Fixed incorrect endif statement
  modules/efk-logging-fluentd-external.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#16445 [enterprise-4.1] Fixed incorrect endif statement
  modules/efk-logging-fluentd-external.adoc
Labels: size/XS

#16446 [enterprise-4.2] Fixed incorrect endif statement
  modules/efk-logging-fluentd-external.adoc
Labels: size/XS

#16407 SREP-1733 dedicated logging updates
  logging/dedicated-efk-deploying.adoc
  logging/efk-logging.adoc
  modules/dedicated-efk-install-deploy.adoc
  modules/efk-logging-about.adoc
  modules/efk-logging-deploy-subscription.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/L

#16185 SREP1775 updated dedicated-admins group management
  modules/dedicated-managing-dedicated-administrators.adoc
Labels: branch/dedicated, branch/enterprise-4.1, branch/enterprise-4.2, lgtm, size/M

#16028 support improved undefined field handling
  logging/config/efk-logging-fluentd.adoc
  modules/efk-logging-fluentd-undefined.adoc
Labels: branch/enterprise-4.2, size/L

#16457 Corrected typo in release notes
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/XS

#16459 Fixed format errors
  logging/efk-logging-eventrouter.adoc
  modules/efk-logging-about-eventrouter.adoc
  modules/efk-logging-eventrouter-deploy.adoc
  modules/efk-logging-fluentd-limits.adoc
  modules/efk-logging-fluentd-undefined.adoc
Labels: size/S
