Repository openshift/openshift-docs, pull requests merged in 2019-02, with the labels that each got.

#13514 fixing word order in heading
  install_config/topics/configuring_for_aws_registry-proc.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13492 [enterprise-3.11] bug 1622044 corrected auditFilePath examples
  install_config/master_node_configuration.adoc
Labels: size/M

#13483 BZ-1528464: Added missing command option
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, size/M

#13529 BZ-1528464: Added missing command option
  install_config/aggregate_logging.adoc
Labels: size/XS

#13530 BZ-1528464: Added missing command option
  install_config/aggregate_logging.adoc
Labels: size/M

#13518 osdocs-87 add templates modules
  _topic_map.yml
  builds/using-templates.adoc
  modules/templates-cli-generating-list-of-objects.adoc
  modules/templates-cli-labels.adoc
  modules/templates-cli-parameters.adoc
  modules/templates-create-from-existing-object.adoc
  modules/templates-creating-from-console.adoc
  modules/templates-exposing-object-fields.adoc
  modules/templates-marking-as-bindable.adoc
  modules/templates-modifying-uploaded-template.adoc
  modules/templates-overview.adoc
  modules/templates-uploading.adoc
  modules/templates-using-instant-app-quickstart.adoc
  modules/templates-using-the-cli.adoc
  modules/templates-waiting-for-readiness.adoc
  modules/templates-writing-description.adoc
  modules/templates-writing-labels.adoc
  modules/templates-writing-object-list.adoc
  modules/templates-writing-parameters.adoc
  modules/templates-writing.adoc
Labels: branch/enterprise-4.0, size/XL

#13528 [enterprise-3.11] Add missing space in Azure Storage
  install_config/persistent_storage/persistent_storage_azure.adoc
Labels: branch/enterprise-3.11

#13486 osdocs-82 adding pipeline modules
  builds/build-strategies.adoc
  modules/builds-strategy-pipeline-build.adoc
  modules/builds-strategy-pipeline-providing-jenkinsfile.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/builds-understanding-openshift-pipeline.adoc
Labels: branch/enterprise-4.0, size/L

#13524 For BZ1643169 -- configuring storage Option A dynamic provisioning -- non-NFS
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13292 Add new Operator / OLM topics
  _topic_map.yml
  images/etcd-operator-overview.png
  images/etcd-operator-resources.png
  images/olm-catalog-sources.png
  images/olm-workflow.png
  images/osdk-workflow.png
  modules/building-memcached-operator-using-osdk.adoc
  modules/building-operator-with-helm-using-osdk.adoc
  modules/olm-creating-etcd-cluster-from-operator.adoc
  modules/olm-installing-operator-using-operatorhub.adoc
  modules/olm-operator-framework.adoc
  modules/olm-operator-lifecycle-manager.adoc
  modules/olm-operator-project-staffolding-layout.adoc
  modules/olm-operatorhub.adoc
  modules/olm-why-use-operators.adoc
  modules/osdk-cli-reference-test.adoc
  modules/osdk-helm-chart-support.adoc
  modules/osdk-operator-sdk.adoc
  operators/olm-adding-operators-to-cluster.adoc
  operators/olm-creating-apps-from-installed-operators.adoc
  operators/olm-what-are-operators.adoc
  operators/operators-appendices.adoc
  operators/osdk-getting-started.adoc
Labels: branch/enterprise-4.0, size/L

#12929 New assemblies and modules for containers
  _topic_map.yml
  modules/nodes-containers-copying-files-about.adoc
  modules/nodes-containers-copying-files-procedure.adoc
  modules/nodes-containers-copying-files-rsync.adoc
  modules/nodes-containers-downward-api-about.adoc
  modules/nodes-containers-downward-api-container-configmaps.adoc
  modules/nodes-containers-downward-api-container-envars.adoc
  modules/nodes-containers-downward-api-container-escaping.adoc
  modules/nodes-containers-downward-api-container-resources-envars.adoc
  modules/nodes-containers-downward-api-container-resources-plugin.adoc
  modules/nodes-containers-downward-api-container-resources.adoc
  modules/nodes-containers-downward-api-container-secrets.adoc
  modules/nodes-containers-downward-api-container-values-envars.adoc
  modules/nodes-containers-downward-api-container-values-plugin.adoc
  modules/nodes-containers-downward-api-container-values.adoc
  modules/nodes-containers-events-about.adoc
  modules/nodes-containers-events-list.adoc
  modules/nodes-containers-events-viewing.adoc
  modules/nodes-containers-init-about.adoc
  modules/nodes-containers-init-creating.adoc
  modules/nodes-containers-port-forwarding-about.adoc
  modules/nodes-containers-port-forwarding-protocol.adoc
  modules/nodes-containers-port-forwarding-using.adoc
  modules/nodes-containers-projected-volumes-about.adoc
  modules/nodes-containers-projected-volumes-creating.adoc
  modules/nodes-containers-remote-commands-about.adoc
  modules/nodes-containers-remote-commands-protocol.adoc
  modules/nodes-containers-using-about.adoc
  modules/nodes-containers-using-ssh.adoc
  modules/nodes-containers-volumes-about.adoc
  modules/nodes-containers-volumes-adding.adoc
  modules/nodes-containers-volumes-cli.adoc
  modules/nodes-containers-volumes-listing.adoc
  modules/nodes-containers-volumes-removing.adoc
  modules/nodes-containers-volumes-subpath.adoc
  modules/nodes-containers-volumes-updating.adoc
  nodes/nodes-containers-copying-files.adoc
  nodes/nodes-containers-downward-api.adoc
  nodes/nodes-containers-events.adoc
  nodes/nodes-containers-init.adoc
  nodes/nodes-containers-port-forwarding.adoc
  nodes/nodes-containers-projected-volumes.adoc
  nodes/nodes-containers-remote-commands.adoc
  nodes/nodes-containers-using.adoc
  nodes/nodes-containers-volumes.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XXL

#13439 HTPasswd options
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13543 Fix Operator topic typos
  _topic_map.yml
  modules/olm-installing-operator-using-operatorhub.adoc
  modules/olm-operator-framework.adoc
Labels: branch/enterprise-4.0, size/S

#13535 osdocs-86 add quickstart modules
  builds/using-templates.adoc
  modules/templates-overview.adoc
  modules/templates-quickstart.adoc
Labels: branch/enterprise-4.0, size/M

#13544 Edits to understanding builds
  _topic_map.yml
  builds/understanding-builds.adoc
  modules/builds-about.adoc
  modules/builds-buildconfig.adoc
Labels: branch/enterprise-4.0, size/S

#13521 Adding example options for variable
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13520 changes based on edits and base on master vs 3.10
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.10, branch/enterprise-3.11, size/M

#12964 new assemblies and modules for nodes
  _topic_map.yml
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-garbage-collection-containers.adoc
  modules/nodes-nodes-garbage-collection-images.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-nodes-jobs-creating-cron.adoc
  modules/nodes-nodes-jobs-creating.adoc
  modules/nodes-nodes-modifying-maximum.adoc
  modules/nodes-nodes-opaque-resources-about.adoc
  modules/nodes-nodes-opaque-resources-consuming.adoc
  modules/nodes-nodes-opaque-resources-creating.adoc
  modules/nodes-nodes-problem-detector-about.adoc
  modules/nodes-nodes-problem-detector-customizing.adoc
  modules/nodes-nodes-problem-detector-installing.adoc
  modules/nodes-nodes-problem-detector-uninstalling.adoc
  modules/nodes-nodes-problem-detector-verifying.adoc
  modules/nodes-nodes-rebooting-affinity.adoc
  modules/nodes-nodes-rebooting-infrastructure.adoc
  modules/nodes-nodes-rebooting-router.adoc
  modules/nodes-nodes-resources-configuring-about.adoc
  modules/nodes-nodes-resources-configuring-setting.adoc
  modules/nodes-nodes-resources-configuring-viewing.adoc
  modules/nodes-nodes-viewing-listing-pods.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-viewing-memory.adoc
  modules/nodes-nodes-working-deleting.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-nodes-working-marking.adoc
  modules/nodes-nodes-working-updating.adoc
  nodes/nodes-nodes-garbage-collection.adoc
  nodes/nodes-nodes-jobs.adoc
  nodes/nodes-nodes-modifying.adoc
  nodes/nodes-nodes-opaque-resources.adoc
  nodes/nodes-nodes-problem-detector.adoc
  nodes/nodes-nodes-rebooting.adoc
  nodes/nodes-nodes-resources-configuring.adoc
  nodes/nodes-nodes-viewing.adoc
  nodes/nodes-nodes-working.adoc
Labels: Peer Review Needed, branch/enterprise-4.0, size/XXL

#13519 BZ1637616 -so it builds correctly in master,3-10,and 3.11.
  install_config/persistent_storage/persistent_storage_manila.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13398 BZ 1666367: correcting API usage
  modules/cnv_cloning_pvc_virtualmachine.adoc
  modules/cnv_creating_vm.adoc
  modules/cnv_creating_vm_web_console.adoc
  modules/cnv_importing_vm_disk_DVs.adoc
  modules/cnv_pxebooting.adoc
  modules/cnv_template_dv_config.adoc
  modules/cnv_template_vm_config.adoc
  modules/cnv_template_vmi_pxe_config.adoc
  modules/cnv_vm_storage_volume_types.adoc
Labels: branch/enterprise-3.11, size/M

#13550 osdocs-88 Add ruby on rails tutorial and move templates
  _topic_map.yml
  modules/registry-accessing-directly.adoc
  modules/templates-cli-generating-list-of-objects.adoc
  modules/templates-cli-labels.adoc
  modules/templates-cli-parameters.adoc
  modules/templates-create-from-existing-object.adoc
  modules/templates-creating-from-console.adoc
  modules/templates-exposing-object-fields.adoc
  modules/templates-marking-as-bindable.adoc
  modules/templates-modifying-uploaded-template.adoc
  modules/templates-overview.adoc
  modules/templates-quickstart.adoc
  modules/templates-rails-configuring-application.adoc
  modules/templates-rails-creating-database-service.adoc
  modules/templates-rails-creating-frontend-service.adoc
  modules/templates-rails-creating-route-for-application.adoc
  modules/templates-rails-creating-welcome-page.adoc
  modules/templates-rails-deploying-application.adoc
  modules/templates-rails-setting-up-database.adoc
  modules/templates-rails-storing-application-in-git.adoc
  modules/templates-rails-writing-application.adoc
  modules/templates-uploading.adoc
  modules/templates-using-instant-app-quickstart.adoc
  modules/templates-using-the-cli.adoc
  modules/templates-waiting-for-readiness.adoc
  modules/templates-writing-description.adoc
  modules/templates-writing-labels.adoc
  modules/templates-writing-object-list.adoc
  modules/templates-writing-parameters.adoc
  modules/templates-writing.adoc
  openshift_images/PLACEHOLDER
  openshift_images/templates-using-ruby-on-rails.adoc
  openshift_images/using-templates.adoc
Labels: branch/enterprise-4.0, size/XL

#13515 Bug 1647168 - base master for node labels
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.10, branch/enterprise-3.11

#12980 new assemblies and modules for scheduler
  _topic_map.yml
  applications_and_projects/PLACEHOLDER
  modules/nodes-scheduler-default-about.adoc
  modules/nodes-scheduler-default-modifying.adoc
  modules/nodes-scheduler-default-predicates.adoc
  modules/nodes-scheduler-default-priorities.adoc
  modules/nodes-scheduler-default-sample.adoc
  modules/nodes-scheduler-descheduler-about.adoc
  modules/nodes-scheduler-descheduler-config-map.adoc
  modules/nodes-scheduler-descheduler-create-policy.adoc
  modules/nodes-scheduler-descheduler-create-role.adoc
  modules/nodes-scheduler-descheduler-job-spec.adoc
  modules/nodes-scheduler-descheduler-running.adoc
  modules/nodes-scheduler-node-affinity-about.adoc
  modules/nodes-scheduler-node-affinity-configuring-preferred.adoc
  modules/nodes-scheduler-node-affinity-configuring-required.adoc
  modules/nodes-scheduler-node-affinity-example.adoc
  modules/nodes-scheduler-node-antiaffinity-configuring.adoc
  modules/nodes-scheduler-node-names-configuring.adoc
  modules/nodes-scheduler-node-projects-about.adoc
  modules/nodes-scheduler-node-projects-configuring.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-node-selectors-configuring.adoc
  modules/nodes-scheduler-pod-affinity-about.adoc
  modules/nodes-scheduler-pod-affinity-configuring.adoc
  modules/nodes-scheduler-pod-affinity-example.adoc
  modules/nodes-scheduler-pod-anti-affinity-configuring.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  modules/nodes-scheduler-taints-tolerations-adding.adoc
  modules/nodes-scheduler-taints-tolerations-binding.adoc
  modules/nodes-scheduler-taints-tolerations-dedicating.adoc
  modules/nodes-scheduler-taints-tolerations-evictions.adoc
  modules/nodes-scheduler-taints-tolerations-examples.adoc
  modules/nodes-scheduler-taints-tolerations-seconds.adoc
  modules/nodes-scheduler-taints-tolerations-special.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
  nodes/scheduling/nodes-scheduler-descheduler.adoc
  nodes/scheduling/nodes-scheduler-node-affinity.adoc
  nodes/scheduling/nodes-scheduler-node-names.adoc
  nodes/scheduling/nodes-scheduler-node-projects.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  nodes/scheduling/nodes-scheduler-overcommit.adoc
  nodes/scheduling/nodes-scheduler-pod-affinity.adoc
  nodes/scheduling/nodes-scheduler-taints-tolerations.adoc
Labels: branch/enterprise-4.0, size/XXL

#13470 Add quota docs to v4
  _topic_map.yml
  administering_clusters/quotas-setting-across-multiple-projects.adoc
  administering_clusters/quotas-setting-per-project.adoc
  masters/PLACEHOLDER
  masters/images
  masters/modules
  modules/quotas-configuring-quota-sync-period.adoc
  modules/quotas-creating-a-quota.adoc
  modules/quotas-creating-object-count-quotas.adoc
  modules/quotas-enforcement.adoc
  modules/quotas-requests-vs-limits.adoc
  modules/quotas-requiring-explicit-quota.adoc
  modules/quotas-resources-managed.adoc
  modules/quotas-sample-resource-quotas-def.adoc
  modules/quotas-scopes.adoc
  modules/quotas-selecting-projects.adoc
  modules/quotas-selection-granularity.adoc
  modules/quotas-viewing-clusterresourcequotas.adoc
  modules/quotas-viewing-quotas.adoc
  modules/setting-resource-quota-for-extended-resources.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13555 for BZ634097 - docker options
  install_config/install/host_preparation.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.9, size/S

#13556 adding stub for v3 versus v4 content
  _topic_map.yml
  release_notes/comparing_v3_v4.adoc
  release_notes/images
  release_notes/modules
Labels: branch/enterprise-4.0

#13435 Add LoadBalancer details to OSD docs
  getting_started/access_your_services.adoc
Labels: branch/enterprise-3.11, size/M

#12970 new assemblies and modules for cluster
  _topic_map.yml
  modules/nodes-cluster-overcommit-about.adoc
  modules/nodes-cluster-overcommit-configure-masters.adoc
  modules/nodes-cluster-overcommit-configure-nodes.adoc
  modules/nodes-cluster-overcommit-master-disable.adoc
  modules/nodes-cluster-overcommit-master-disabling-swap.adoc
  modules/nodes-cluster-overcommit-node-enforcing.adoc
  modules/nodes-cluster-overcommit-node-memory.adoc
  modules/nodes-cluster-overcommit-node-resources.adoc
  modules/nodes-cluster-overcommit-qos-about.adoc
  modules/nodes-cluster-overcommit-resource-requests.adoc
  modules/nodes-cluster-overcommit-resources-containers.adoc
  modules/nodes-cluster-resource-configure-about.adoc
  modules/nodes-cluster-resource-configure-evicted.adoc
  modules/nodes-cluster-resource-configure-jdk.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/nodes-cluster-resource-levels-about.adoc
  modules/nodes-cluster-resource-levels-command.adoc
  modules/nodes-cluster-resource-levels-job.adoc
  modules/nodes-nodes-working-adding.adoc
  nodes/nodes-cluster-overcommit.adoc
  nodes/nodes-cluster-resource-configure.adoc
  nodes/nodes-cluster-resource-levels.adoc
Labels: branch/enterprise-4.0, size/XXL

#13558 Fixed image placement
  getting_started/dedicated_administrators.adoc
  getting_started/images/311-cluster-console.png
Labels: branch/enterprise-3.11, size/XS

#13485 TP7 Documentation Updates including 3Scale Istio Adapter Docs
  servicemesh-install/servicemesh-install.adoc
  servicemesh-install/topics/appendix-threescale-adapter.adoc
  servicemesh-install/topics/application-requirements.adoc
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-overview.adoc
  servicemesh-install/topics/install-post.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/L

#13561 Fix typo and add missing topics to topic-map
  nodes/nodes-nodes-garbage-collection.adoc
  nodes/nodes-nodes-opaque-resources.adoc
  nodes/nodes-nodes-problem-detector.adoc
  nodes/nodes-nodes-resources-configuring.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
Labels: size/S

#13562 Rename resource quotas and admin dir
  _topic_map.yml
  administration/quotas-setting-across-multiple-projects.adoc
  administration/quotas-setting-per-project.adoc
  modules/quotas-configuring-quota-sync-period.adoc
  modules/quotas-creating-a-quota.adoc
  modules/quotas-creating-object-count-quotas.adoc
  modules/quotas-enforcement.adoc
  modules/quotas-requests-vs-limits.adoc
  modules/quotas-requiring-explicit-quota.adoc
  modules/quotas-resources-managed.adoc
  modules/quotas-sample-resource-quotas-def.adoc
  modules/quotas-scopes.adoc
  modules/quotas-selecting-projects.adoc
  modules/quotas-selection-granularity.adoc
  modules/quotas-viewing-clusterresourcequotas.adoc
  modules/quotas-viewing-quotas.adoc
  modules/setting-resource-quota-for-extended-resources.adoc
Labels: branch/enterprise-4.0, size/M

#13566 fixing RHCOS full name
  modules/installation-clouds.adoc
  modules/installation-options.adoc
  modules/node-management.adoc
  modules/update-service-overview.adoc
Labels: branch/enterprise-4.0, size/S

#13548 add kubeletconfig management for 4.0
  modules/node-management.adoc
Labels: branch/enterprise-4.0, size/L

#13571 Removing Manage Nodes from Architecture doc
  modules/node-management.adoc
Labels: branch/enterprise-4.0, size/M

#13563 Add CR/CRD topics to 4.0
  _topic_map.yml
  applications_and_projects/crd-managing-resources-from-crds.adoc
  masters/crd-extending-api-with-crds.adoc
  masters/images
  masters/modules
  masters/quotas-setting-across-multiple-projects.adoc
  masters/quotas-setting-per-project.adoc
  modules/crd-creating-aggregated-cluster-roles.adoc
  modules/crd-creating-crds.adoc
  modules/crd-creating-custom-resources-from-file.adoc
  modules/crd-custom-resource-definitions.adoc
  modules/crd-inspecting-custom-resources.adoc
  modules/installing-docker.adoc
  modules/quotas-configuring-quota-sync-period.adoc
  modules/quotas-creating-a-quota.adoc
  modules/quotas-creating-object-count-quotas.adoc
  modules/quotas-enforcement.adoc
  modules/quotas-requests-vs-limits.adoc
  modules/quotas-requiring-explicit-quota.adoc
  modules/quotas-resources-managed.adoc
  modules/quotas-sample-resource-quotas-def.adoc
  modules/quotas-scopes.adoc
  modules/quotas-selecting-projects.adoc
  modules/quotas-selection-granularity.adoc
  modules/quotas-viewing-clusterresourcequotas.adoc
  modules/quotas-viewing-quotas.adoc
  modules/setting-resource-quota-for-extended-resources.adoc
Labels: branch/enterprise-4.0, size/L

#13573 configuration resource stubs
  modules/configuration-resource-configure.adoc
  modules/configuration-resource-overview.adoc
Labels: branch/enterprise-4.0, size/M

#13574 Add idling topics to 4.0
  _topic_map.yml
  masters/idling-applications.adoc
  modules/idle-idling-applications.adoc
  modules/idle-unidling-applications.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/M

#13578 Removing Ansible from Nodes topics
  modules/nodes-containers-projected-volumes-about.adoc
  modules/nodes-nodes-problem-detector-about.adoc
  modules/nodes-nodes-problem-detector-installing.adoc
  modules/nodes-nodes-problem-detector-uninstalling.adoc
  modules/nodes-nodes-viewing-listing.adoc
Labels: size/M

#13580 Removing Ansible from Logging topics
  logging/efk-logging-deploy.adoc
  logging/efk-logging-uninstall.adoc
  modules/efk-logging-about-elasticsearch.adoc
  modules/efk-logging-curator-configuration.adoc
  modules/efk-logging-deploy-certificates.adoc
  modules/efk-logging-deploy-memory.adoc
  modules/efk-logging-deploy-playbook.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-elasticsearch-exposing.adoc
  modules/efk-logging-elasticsearch-ha.adoc
  modules/efk-logging-elasticsearch-persistent-storage-about.adoc
  modules/efk-logging-elasticsearch-persistent-storage-local.adoc
  modules/efk-logging-elasticsearch-persistent-storage-persistent.adoc
  modules/efk-logging-elasticsearch-scaling.adoc
  modules/efk-logging-external-syslog.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-kibana-scaling.adoc
  modules/efk-logging-troubleshooting-cryptic.adoc
  modules/efk-logging-troubleshooting-loop.adoc
  modules/efk-logging-uninstall-efk-ops.adoc
  modules/efk-logging-uninstall-efk.adoc
Labels: size/XL

#13581 Removing autoscaling topics
  _topic_map.yml
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-creating.adoc
  modules/nodes-pods-autoscaling-status-about.adoc
  modules/nodes-pods-autoscaling-status-viewing.adoc
  nodes/nodes-pods-autoscaling.adoc
Labels: size/L

#13570 adding common-attributes to the conventions
  modules/mod-docs-ocp-conventions.adoc
Labels: branch/enterprise-4.0, size/XS

#13484 Change button type so the form submits on click
  index-commercial.html
Labels: Peer Review Done, size/XS, tech_review

#13513 Fix misspelled instance of PostgreSQL
  install_config/persistent_storage/persistent_storage_azure_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13579 Add pruning topics to 4.0
  _topic_map.yml
  masters/idling-applications.adoc
  masters/pruning-objects.adoc
  modules/pruning-basic-operations.adoc
  modules/pruning-builds.adoc
  modules/pruning-cronjobs.adoc
  modules/pruning-deployments.adoc
  modules/pruning-groups.adoc
  modules/pruning-hard-pruning-registry.adoc
  modules/pruning-images.adoc
  registry/accessing-the-registry.adoc
  registry/securing-exposing-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13600 Minor clarifications to the Mod docs conventions and whitespace clari…
  contributing_to_docs/doc_guidelines.adoc
  contributing_to_docs/tools_and_setup.adoc
  modules/mod-docs-ocp-conventions.adoc
Labels: size/S

#13601 Minor clarifications to the Mod docs conventions and whitespace clari…
  contributing_to_docs/doc_guidelines.adoc
  contributing_to_docs/tools_and_setup.adoc
Labels: size/XS

#13582 bug 1673645 removed Tech Preview message for autoscaling
  dev_guide/pod_autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#13327 Added Network optimization content to 4.0 docs
  _topic_map.yml
  modules/configuring-network-subnets.adoc
  modules/optimizing-the-MTU-for-your-network.adoc
  networking/PLACEHOLDER
  networking/network-optimization.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13604 fixing typo
  modules/architecture-overview.adoc
Labels: branch/enterprise-4.0, size/XS

#13609 adding a stub for new architecture content
  architecture/architecture.adoc
  modules/architecture-new-content.adoc
Labels: branch/enterprise-4.0, size/S

#13568 Update the monitoring diagram
  install_config/images/monitoring-diagram.png
Labels: size/XS

#13612 Correct the cluster autoscaler image tag on enterprise version
  admin_guide/topics/deploying-cluster-auto-scaler.adoc
Labels: ok-to-test, size/XS

#13614 Adding [4.0] as the drop down option
  _templates/_page_openshift.html.erb
Labels: size/S

#13575 bug 1673314 amended federation section
  welcome/oce_about.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#13511 Updates to Cluster Loader 4.0 content
  modules/installing-cluster-loader.adoc
  modules/running-cluster-loader.adoc
Labels: branch/enterprise-4.0, lgtm, size/M

#13617 Remove replication controller topic from nodes per sjenning
  modules/nodes-pods-configuring-replication.adoc
  nodes/nodes-pods-configuring.adoc
Labels: size/M

#13615 Adding the TP note back in for CLI plugins
  cli_reference/extend_cli.adoc
Labels: Peer Review Needed, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13620 oc adm cordon vs oc adm manage-node node1 --schedulable=false
  modules/nodes-nodes-viewing-listing-pods.adoc
  modules/nodes-nodes-working-marking.adoc
Labels: branch/enterprise-4.0, size/S

#13628 Setting encoding for script
  makeBuild.py
Labels: size/XS

#13618 for BZ1634097 - edits based on QE review
  install_config/install/advanced_install.adoc
  install_config/install/host_preparation.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/S

#13610 draft of autoscaler assembly
  _topic_map.yml
  control-plane-management/applying-autoscaling.adoc
  control-plane-management/images
  control-plane-management/modules
  modules/cluster-autoscaler-about.adoc
  modules/cluster-autoscaler-crd.adoc
  modules/cluster-autoscaler-deploying.adoc
  modules/deploying-resource.adoc
  modules/machine-api-overview.adoc
  modules/machine-autoscaler-about.adoc
  modules/machine-autoscaler-crd.adoc
Labels: branch/enterprise-4.0, size/L

#13640 MYLASTBZ1634097 - fixed git issue and redid
  install_config/install/advanced_install.adoc
  install_config/install/host_preparation.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.9, size/XS

#13457 Adding Recommended Host Practices to 4.0
  _topic_map.yml
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  scalability_and_performance/PLACEHOLDER
  scalability_and_performance/recommended-host-practices.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/M

#13641 Added {nbsp} + after TOCs to fix spacing
  scalability_and_performance/optimizing-compute-resources.adoc
  scalability_and_performance/planning-your-environment-according-to-object-limits.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
  scalability_and_performance/using-cluster-loader.adoc
  scalability_and_performance/using-node-tuning-operator.adoc
Labels: size/S

#13598 Removing references to Docker from Nodes topics
  modules/nodes-cluster-overcommit-node-resources.adoc
  modules/nodes-containers-using-about.adoc
  modules/nodes-nodes-garbage-collection-containers.adoc
  modules/nodes-nodes-modifying-maximum.adoc
  modules/nodes-nodes-problem-detector-about.adoc
  modules/nodes-nodes-problem-detector-customizing.adoc
  modules/nodes-nodes-problem-detector-verifying.adoc
  modules/nodes-nodes-rebooting-affinity.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-pods-disabling-features-list.adoc
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-certificates-about.adoc
  modules/nodes-pods-secrets-creating-docker.adoc
  modules/nodes-pods-using-example.adoc
  nodes/nodes-containers-using.adoc
  nodes/nodes-nodes-resources-configuring.adoc
  nodes/nodes-pods-secrets.adoc
Labels: branch/enterprise-4.0, size/L

#13642 adding {nbsp} + to assemblies
  architecture/architecture.adoc
  authentication/configuring-internal-oauth.adoc
  authentication/configuring-ldap-failover.adoc
  authentication/configuring-user-agent.adoc
  authentication/identity_providers/configuring-allow-all-identity-provider.adoc
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/identity_providers/configuring-deny-all-identity-provider.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-gitlab-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  authentication/identity_providers/configuring-keystone-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/identity_providers/configuring-request-header-identity-provider.adoc
  authentication/managing-security-context-constraints.adoc
  authentication/tokens-scoping.adoc
  authentication/understanding-and-creating-service-accounts.adoc
  authentication/understanding-authentication.adoc
  authentication/understanding-identity-provider.adoc
  authentication/using-rbac.adoc
  authentication/using-service-accounts-as-oauth-client.adoc
  authentication/using-service-accounts-in-applications.adoc
  control-plane-management/applying-autoscaling.adoc
  installing-aws/installing-aws-account.adoc
  installing-aws/installing-customizations-cloud.adoc
  installing-aws/installing-quickly-cloud.adoc
  installing-aws/uninstalling-cluster-aws.adoc
  installing-byoh/installing-existing-hosts.adoc
  installing-byoh/uninstalling-existing-hosts.adoc
  release_notes/comparing_3_4.adoc
  users_and_roles/creating-project-other-user.adoc
  users_and_roles/impersonating-system-admin.adoc
Labels: branch/enterprise-4.0, size/M

#13367 Remove references to the Mux service from docs
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-external-syslog.adoc
  modules/efk-logging-fluentd-connections.adoc
  modules/efk-logging-systemd-scaling.adoc
Labels: branch/enterprise-4.0, size/L

#13445 Operator can add and remove ES nodes
  logging/efk-logging-elasticsearch.adoc
  modules/efk-logging-elasticsearch-add-remove.adoc
Labels: branch/enterprise-4.0, size/L

#13650 fixing nesting
  control-plane-management/applying-autoscaling.adoc
Labels: branch/enterprise-4.0, size/XS

#13653 Adjusted headings in the Recommended configurable storage technology module
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.0, size/S

#13656 breaking out a pod module
  modules/nodes-pods-about.adoc
  nodes/nodes-pods-viewing.adoc
Labels: branch/enterprise-4.0, size/S

#13616 bug 1670732 need to update master-config.yaml for a cert change
  install_config/certificate_customization.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/M

#13660 [enteprise-3.10] bug 1670732 need to update master-config.yaml for a cert change
  install_config/certificate_customization.adoc
Labels: size/M

#13654 Add major version # usage to contrib
  contributing_to_docs/doc_guidelines.adoc
Labels: size/S

#13664 Exposing elasticsearch service with a route
  modules/efk-logging-elasticsearch-exposing.adoc
Labels: branch/enterprise-4.0, lgtm, size/M

#12900 Added node tuning operator content
  _topic_map.yml
  modules/accessing-an-example-cluster-node-tuning-operator-specification.adoc
  modules/cluster-node-tuning-operator-default-profiles-set.adoc
  modules/custom-tuning-specification.adoc
  modules/deploying-node-tuning-operator.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
  modules/node-tuning-operator.adoc
  scalability_and_performance/using-node-tuning-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13644 osdocs-238 add console overview
  _topic_map.yml
  architecture/web-console.adoc
  modules/web-console-overview.adoc
  modules/web-console-statefulsets.adoc
Labels: branch/enterprise-4.0, size/M

#13576 Added information on managing nodes from rphillips
  _topic_map.yml
  modules/nodes-nodes-managing-about.adoc
  modules/nodes-nodes-managing-max-pods-proc.adoc
  nodes/managing/nodes-nodes-garbage-collection.adoc
  nodes/managing/nodes-nodes-managing-max-pods.adoc
  nodes/managing/nodes-nodes-managing.adoc
  nodes/managing/nodes-nodes-resources-configuring.adoc
Labels: size/L

#13605 machine health check draft
  _topic_map.yml
  control-plane-management/deploying-machine-health-checks.adoc
  modules/machine-health-checks-about.adoc
  modules/machine-health-checks-creating.adoc
  modules/machine-health-checks-resource.adoc
Labels: branch/enterprise-4.0, size/L

#13586 Reveal openshift_master_manage_htpasswd variable in upgrade preparations
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13677 [enterprise-4.0] updated list of allowed folks for previews
  autocomment.sh
  autopreview.sh
Labels: size/XS

#13678 Updated list of allowed people for previews
  autocomment.sh
Labels: size/XS

#13680 Fixes for the Node Tuning Operator in 4.0.
  modules/accessing-an-example-cluster-node-tuning-operator-specification.adoc
  modules/custom-tuning-specification.adoc
  modules/node-tuning-operator.adoc
Labels: branch/enterprise-4.0, size/S

#13623 3.9.68 async release notes
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#13649 Add information about the metrics-server requirement for HPA
  admin_guide/manage_nodes.adoc
  admin_guide/managing_pods.adoc
  dev_guide/pod_autoscaling.adoc
Labels: size/M

#13681 Added Chris's image topics to the map
  _topic_map.yml
  applications/operator_sdk/osdk-ansible.adoc
  applications/operator_sdk/osdk-getting-started.adoc
  applications/operator_sdk/osdk-helm.adoc
  modules/image-stream-configure.adoc
  modules/image-stream-use.adoc
  modules/images-create-guide-general.adoc
  modules/images-create-guide-openshift.adoc
  modules/images-create-s2i-scripts.adoc
  modules/images-create-s2i.adoc
  modules/images-custom.adoc
  modules/images-test-s2i.adoc
  modules/quotas-creating-a-quota.adoc
  openshift_images/images-create.adoc
Labels: size/L

#13624 3.9 bumped latest-tags
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: branch/enterprise-3.9, size/S

#13657 bumped latest-tags to 3.10.111
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_10_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.10, size/M

#13661 3.10.111 release notes stub added
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.11, size/S

#13679 Fixing typo
  modules/installation-planning.adoc
Labels: branch/enterprise-4.0, size/XS

#13599 Removing references to Docker from Logging topics
  logging/efk-logging-exported-fields.adoc
  modules/efk-logging-deploy-label.adoc
  modules/efk-logging-exported-fields-docker.adoc
Labels: branch/enterprise-4.0, size/S

#13663 3.11.82 release notes and latest-tags
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/M

#13572 bug 1664579 corrected command syntax
  admin_guide/pruning_resources.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13690 Improve advanced audit configuration
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13567 issue 13527 removed xPaaS image links
  _topic_map.yml
  getting_started/developers_cli.adoc
  install/configuring_inventory_file.adoc
  using_images/xpaas_images/a_mq.adoc
  using_images/xpaas_images/data_grid.adoc
  using_images/xpaas_images/decision_server.adoc
  using_images/xpaas_images/eap.adoc
  using_images/xpaas_images/eap_old.adoc
  using_images/xpaas_images/fuse.adoc
  using_images/xpaas_images/index.adoc
  using_images/xpaas_images/jws.adoc
  using_images/xpaas_images/sso.adoc
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/XXL

#13665 OSDOCS-286: Updated output of RBAC commands.
  modules/rbac-adding-roles.adoc
  modules/rbac-creating-cluster-role.adoc
  modules/rbac-creating-local-role.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/rbac-viewing-local-roles.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13700 [enterprise-3.11] issue 13527 removed xPaaS image links
  _topic_map.yml
  getting_started/developers_cli.adoc
  install/configuring_inventory_file.adoc
  using_images/xpaas_images/index.adoc
  welcome/index.adoc
Labels: size/S

#13698 OSDOCS-248: Including EBS Persistent Storage.
  _topic_map.yml
  modules/storage-create-storage-class.adoc
  modules/storage-persistent-storage-aws-maximum-volumes.adoc
  modules/storage-persistent-storage-aws-volume-format.adoc
  modules/storage-persistent-storage-creating-volume-claim.adoc
  storage/persistent-storage-aws.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13706 added padding after toc
  _stylesheets/docs.css
Labels: size/XS

#13076 Remove duplicate content
  install/host_preparation.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, ok-to-test, size/XS

#13709 [enterprise-3.10] Remove duplicate content
  install/host_preparation.adoc
Labels: size/XS

#13710 [enterprise-3.9] Remove duplicate content
  install_config/install/host_preparation.adoc
Labels: size/XS

#13702 Fix typo in descheduler introduction
  admin_guide/scheduling/descheduler.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13380 Improve page load performance
  404-commercial.html
  404-community.html
  _images/commercial-masthead.jpg
  _images/commercial-masthead.png
  _javascripts/page-loader.js
  _stylesheets/commercial-home.css
  _templates/_page_openshift.html.erb
  _templates/_search.html.erb
  _templates/_search_dedicated.html.erb
  _templates/_search_enterprise.html.erb
  _templates/_search_online.html
  _templates/_search_origin.html.erb
  _templates/_search_other.html
  index-commercial.html
  index-community.html
  search-commercial.html
Labels: Peer Review Needed, enhancement, size/L, tech_review

#13674 OSDOCS-241: Initial CLI reference docs for dev commands
  _topic_map.yml
  cli_reference/developer-cli-commands.adoc
  cli_reference/images
  cli_reference/modules
  modules/cli-developer-advanced.adoc
  modules/cli-developer-application-management.adoc
  modules/cli-developer-basic.adoc
  modules/cli-developer-build-deploy.adoc
  modules/cli-developer-other.adoc
  modules/cli-developer-settings.adoc
  modules/cli-developer-troubleshooting.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13720 [enterprise-3.7] Include branch specific changes for page speed improvements
  _images/commercial-masthead.jpg
  _images/commercial-masthead.png
  _javascripts/page-loader.js
  _stylesheets/commercial-home.css
Labels: size/XS

#13719 [enterprise-3.9] Include branch specific changes for page speed improvements
  _images/commercial-masthead.jpg
  _images/commercial-masthead.png
  _javascripts/page-loader.js
  _stylesheets/commercial-home.css
Labels: size/XS

#13718 [enterprise-3.10] Include branch specific changes for page speed improvements
  _images/commercial-masthead.jpg
  _images/commercial-masthead.png
  _javascripts/page-loader.js
  _stylesheets/commercial-home.css
Labels: size/XS

#13717 [enterprise-3.11] Include branch specific changes for page speed improvements
  _images/commercial-masthead.jpg
  _images/commercial-masthead.png
  _javascripts/page-loader.js
  _stylesheets/commercial-home.css
Labels: size/XS

#13715 issue 13527 removed xPaaS image links
  _topic_map.yml
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  install/configuring_inventory_file.adoc
  using_images/xpaas_images/index.adoc
  welcome/index.adoc
Labels: branch/enterprise-3.10, size/S

#13721 issue 13527 removed xPaaS image links
  _topic_map.yml
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  install/configuring_inventory_file.adoc
  using_images/xpaas_images/index.adoc
  welcome/index.adoc
Labels: branch/enterprise-3.9, size/XXL

#13450 Creating a blank disk image (DV/PVC)
  cnv_users_guide/cnv_users_guide.adoc
  modules/cnv_blankdisk_dv.adoc
  modules/cnv_blankdisk_pvc.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#13714 BZ1670721: fix typo in config custom certs
  install_config/certificate_customization.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13328 CNV 1.4 installation guide updates
  cnv_install/cnv_install.adoc
  cnv_users_guide/cnv_users_guide.adoc
  modules/cnv_enabling_repo.adoc
  modules/cnv_import_vm_gui.adoc
  modules/cnv_install_1_4.adoc
  modules/cnv_install_vmtemplates.adoc
  modules/cnv_requirements.adoc
  modules/cnv_uninstall_1_4.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#13722 issue 13527 removed xPaaS image links
  _topic_map.yml
  getting_started/beyond_the_basics.adoc
  getting_started/developers_cli.adoc
  using_images/xpaas_images/index.adoc
  welcome/index.adoc
Labels: branch/enterprise-3.7, size/S

#13673 [enterprise-3.11] bug 1673314 amended federation section
  welcome/oce_about.adoc
Labels: branch/enterprise-3.11, size/S

#13725 draft table of AWS permissions
  installing-aws/installing-aws-account.adoc
  modules/installation-aws-permissions.adoc
Labels: size/L

#13687 updates from the training repo docs
  _topic_map.yml
  installing-aws/installing-aws-account.adoc
  installing-aws/installing-customizations-cloud.adoc
  installing-aws/installing-quickly-cloud.adoc
  machine_management/applying-autoscaling.adoc
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating-machineset.adoc
  machine_management/deploying-machine-health-checks.adoc
  machine_management/images
  machine_management/manually-scaling-machineset.adoc
  machine_management/modules
  modules/cli-install.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-autoscaler-about.adoc
  modules/cluster-autoscaler-cr.adoc
  modules/cluster-autoscaler-deploying.adoc
  modules/deploying-resource.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-aws-regions.adoc
  modules/installation-aws-route53.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-overview.adoc
  modules/installation-provide-credentials.adoc
  modules/installation-uninstall-aws.adoc
  modules/machine-autoscaler-about.adoc
  modules/machine-autoscaler-cr.adoc
  modules/machineset-cr.adoc
  modules/machineset-creating.adoc
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.0, size/XL

#13724 cluster customizations
  _topic_map.yml
  architecture/customizations.adoc
Labels: branch/enterprise-4.0, size/L

#13728 Moved topics into Scalability and performance guide for QA review
  _topic_map.yml
  scalability_and_performance/network-optimization.adoc
  scalability_and_performance/optimizing-storage.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
Labels: branch/enterprise-4.0, size/S

#13627 AUTH-177: Updating Identity Provider instructions.
  _topic_map.yml
  authentication/identity_providers/configuring-allow-all-identity-provider.adoc
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/identity_providers/configuring-deny-all-identity-provider.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-gitlab-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  authentication/identity_providers/configuring-keystone-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/identity_providers/configuring-request-header-identity-provider.adoc
  authentication/understanding-identity-provider.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-allow-all-CRD.adoc
  modules/identity-provider-basic-authentication-CRD.adoc
  modules/identity-provider-create-CRD.adoc
  modules/identity-provider-default-CRD.adoc
  modules/identity-provider-deny-all-CRD.adoc
  modules/identity-provider-github-CRD.adoc
  modules/identity-provider-gitlab-CRD.adoc
  modules/identity-provider-google-CRD.adoc
  modules/identity-provider-htpasswd-CRD.adoc
  modules/identity-provider-htpasswd-secret.adoc
  modules/identity-provider-keystone-CRD.adoc
  modules/identity-provider-ldap-CRD.adoc
  modules/identity-provider-ldap-secret.adoc
  modules/identity-provider-oidc-CRD.adoc
  modules/identity-provider-parameters.adoc
  modules/identity-provider-request-header-CRD.adoc
  modules/identity-provider-secret.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13489 CNV 1.4 Web UI update for VM and Templates
  cnv_release_notes/cnv_release_notes.adoc
  cnv_users_guide/cnv_users_guide.adoc
  modules/cnv_cloud_init_fields_web.adoc
  modules/cnv_creating_template_wizard_web.adoc
  modules/cnv_creating_vm_wizard_web.adoc
  modules/cnv_creating_vm_yaml_web.adoc
  modules/cnv_delete_template_web.adoc
  modules/cnv_delete_vm_web.adoc
  modules/cnv_editing_template_yaml_web.adoc
  modules/cnv_editing_vm_web.adoc
  modules/cnv_editing_vm_yaml_web.adoc
  modules/cnv_networking_wizard_fields_web.adoc
  modules/cnv_restart_vm_web.adoc
  modules/cnv_start_vm_web.adoc
  modules/cnv_stop_vm_web.adoc
  modules/cnv_storage_wizard_fields_web.adoc
  modules/cnv_template_wizard_fields_web.adoc
  modules/cnv_vm_actions_web.adoc
  modules/cnv_vm_console_web.adoc
  modules/cnv_vm_create_disk_web.adoc
  modules/cnv_vm_create_nic_web.adoc
  modules/cnv_vm_delete_disk_web.adoc
  modules/cnv_vm_delete_nic_web.adoc
  modules/cnv_vm_events_web.adoc
  modules/cnv_vm_serial_console_web.adoc
  modules/cnv_vm_vnc_console_web.adoc
  modules/cnv_vm_wizard_fields_web.adoc
Labels: Peer Review Done, branch/enterprise-3.11, ok-to-test, size/XL

#13731 Commented out sections not for stage 1 review
  _topic_map.yml
Labels: branch/enterprise-4.0, size/M

#13584 CNV virtio drivers
  cnv_users_guide/cnv_users_guide.adoc
  modules/cnv_adding_virtio_drivers_vm_yaml.adoc
  modules/cnv_installing_virtio_drivers_existing_windows.adoc
  modules/cnv_installing_virtio_drivers_installing_windows.adoc
  modules/cnv_removing_virtio_disk_from_vm.adoc
  modules/cnv_supported_virtio_drivers.adoc
  modules/cnv_virtio_drivers.adoc
Labels: Peer Review Done, branch/enterprise-3.11, ok-to-test, size/L

#13254 Added routing optimization content to 4.0
  _topic_map.yml
  backup_and_restore/PLACEHOLDER
  modules/baseline-router-performance.adoc
  modules/router-performance-optimizations.adoc
  scalability_and_performance/routing-optimization.adoc
Labels: branch/enterprise-4.0, size/L

#13727 bug 1664579 command revisions
  admin_guide/pruning_resources.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13739 Installing an Operator using the command line and expanded OperatorHub (Marketplace) descriptions
  applications/operators/olm-adding-operators-to-cluster.adoc
  modules/olm-installing-operator-using-commands.adoc
  modules/olm-installing-operator-using-operatorhub.adoc
  modules/olm-operatorhub.adoc
Labels: branch/enterprise-4.0, size/L

#13647 Added Working with projects content
  _topic_map.yml
  applications_and_projects/working-with-projects.adoc
  modules/adding-to-a-project.adoc
  modules/checking-project-status-using-the-CLI.adoc
  modules/checking-project-status-using-the-web-console.adoc
  modules/creating-a-project-using-the-CLI.adoc
  modules/creating-a-project-using-the-web-console.adoc
  modules/deleting-a-project-using-the-CLI.adoc
  modules/deleting-a-project-using-the-web-console.adoc
  modules/viewing-a-project-using-the-CLI.adoc
  modules/viewing-a-project-using-the-web-console.adoc
  web-console/working-with-projects.adoc
Labels: branch/enterprise-4.0, size/L

#13744 BZ1670721: fix typo in config custom certs
  install_config/certificate_customization.adoc
Labels: size/XS

#13747 BZ1670721: fix typo in config custom certs
  install_config/certificate_customization.adoc
Labels: size/M

#13669 Adding node tuning operator topic from ahardin-rh to Nodes bucket
  _topic_map.yml
  nodes/nodes-node-tuning-operator.adoc
Labels: branch/enterprise-4.0, size/S

#13750 Removed typo in 3.5 release notes
  release_notes/ocp_3_5_release_notes.adoc
Labels: branch/enterprise-3.5, size/XS

#13723 Add more terms to glossary
  contributing_to_docs/term_glossary.adoc
Labels: branch/enterprise-4.0, size/L

#13658 Reorg Nodes bucket into subtopics
  _topic_map.yml
  applications/pruning-objects.adoc
  machine_management/applying-autoscaling.adoc
  modules/nodes-pods-configuring-bandwidth.adoc
  modules/nodes-pods-configuring-pod-critical.adoc
  modules/nodes-pods-configuring-restart.adoc
  modules/nodes-pods-configuring-run-once.adoc
  modules/nodes-pods-pod-disruption-about.adoc
  modules/nodes-pods-pod-disruption-configuring.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  nodes/clusters/nodes-cluster-pods-configuring.adoc
  nodes/clusters/nodes-cluster-resource-configure.adoc
  nodes/clusters/nodes-cluster-resource-levels.adoc
  nodes/clusters/nodes-containers-events.adoc
  nodes/clusters/nodes-pods-disabling-features.adoc
  nodes/containers/nodes-containers-copying-files.adoc
  nodes/containers/nodes-containers-downward-api.adoc
  nodes/containers/nodes-containers-init.adoc
  nodes/containers/nodes-containers-port-forwarding.adoc
  nodes/containers/nodes-containers-projected-volumes.adoc
  nodes/containers/nodes-containers-remote-commands.adoc
  nodes/containers/nodes-containers-using.adoc
  nodes/containers/nodes-containers-volumes.adoc
  nodes/jobs/nodes-nodes-jobs.adoc
  nodes/jobs/nodes-pods-daemonsets.adoc
  nodes/nodes/nodes-node-tuning-operator.adoc
  nodes/nodes/nodes-nodes-garbage-collection.adoc
  nodes/nodes/nodes-nodes-managing-max-pods.adoc
  nodes/nodes/nodes-nodes-managing.adoc
  nodes/nodes/nodes-nodes-modifying.adoc
  nodes/nodes/nodes-nodes-opaque-resources.adoc
  nodes/nodes/nodes-nodes-problem-detector.adoc
  nodes/nodes/nodes-nodes-rebooting.adoc
  nodes/nodes/nodes-nodes-resources-configuring.adoc
  nodes/nodes/nodes-nodes-viewing.adoc
  nodes/nodes/nodes-nodes-working.adoc
  nodes/pods/nodes-pods-configuring.adoc
  nodes/pods/nodes-pods-plugins.adoc
  nodes/pods/nodes-pods-priority.adoc
  nodes/pods/nodes-pods-secrets.adoc
  nodes/pods/nodes-pods-using.adoc
  nodes/pods/nodes-pods-viewing.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
Labels: branch/enterprise-4.0, size/L

#13666 Add monitoring to OSDK
  _topic_map.yml
  applications/operator_sdk/osdk-getting-started.adoc
  applications/operator_sdk/osdk-migrating-to-v0-1-0.adoc
  applications/operator_sdk/osdk-monitoring-prometheus.adoc
  modules/osdk-architecture.adoc
  modules/osdk-monitoring-prometheus-metrics-helper-modifying-port.adoc
  modules/osdk-monitoring-prometheus-metrics-helper.adoc
  modules/osdk-monitoring-prometheus-operator-support.adoc
  modules/osdk-monitoring-prometheus-servicemonitor-creating.adoc
  modules/osdk-monitoring-prometheus-servicemonitor.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13625 osdocs-157 add samples operator modules
  _topic_map.yml
  modules/configuration-resource-overview.adoc
  modules/samples-operator-configuration.adoc
  modules/samples-operator-overview.adoc
  openshift_images/configuring-samples-operator.adoc
Labels: branch/enterprise-4.0, size/L

#13752 osdocs-157 minor edit
  modules/samples-operator-configuration.adoc
Labels: branch/enterprise-4.0, size/XS

#13716 Web console: refining overview content
  modules/web-console-overview.adoc
Labels: branch/enterprise-4.0, size/M

#13699 Update Event Router for 4.0
  _topic_map.yml
  logging/efk-logging-eventrouter.adoc
  logging/efk-logging.adoc
  modules/efk-logging-about-eventrouter.adoc
  modules/efk-logging-eventrouter-deploy.adoc
Labels: branch/enterprise-4.0, size/L

#13749 Follow-up: OperatorHub docs
  applications/operator_sdk/osdk-ansible.adoc
  applications/operator_sdk/osdk-appendices.adoc
  applications/operator_sdk/osdk-cli-reference.adoc
  applications/operator_sdk/osdk-getting-started.adoc
  applications/operator_sdk/osdk-helm.adoc
  applications/operator_sdk/osdk-migrating-to-v0-1-0.adoc
  applications/operators/olm-adding-operators-to-cluster.adoc
  applications/operators/olm-creating-apps-from-installed-operators.adoc
  applications/operators/olm-what-operators-are.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  modules/olm-installing-operator-using-commands.adoc
  modules/olm-installing-operator-using-operatorhub.adoc
  modules/olm-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13754 fixed warnings
  applications/operators/olm-adding-operators-to-cluster.adoc
  authentication/configuring-internal-oauth.adoc
  modules/identity-provider-oidc-CRD.adoc
  modules/nodes-nodes-problem-detector-customizing.adoc
  modules/nodes-scheduler-node-affinity-example.adoc
  modules/quotas-creating-object-count-quotas.adoc
  modules/service-accounts-as-oauth-clients.adoc
Labels: branch/enterprise-4.0, size/S

#13596 Remove overcommit topics
  modules/nodes-cluster-overcommit-configure-masters.adoc
  modules/nodes-cluster-overcommit-node-enforcing.adoc
  modules/nodes-cluster-overcommit-project-disable.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
Labels: branch/enterprise-4.0, size/L

#13753 Remove master-config.yaml
  modules/nodes-pods-configuring-run-once.adoc
  modules/nodes-scheduler-node-names-configuring.adoc
  modules/nodes-scheduler-node-projects-about.adoc
  modules/nodes-scheduler-node-projects-configuring.adoc
  modules/nodes-scheduler-node-selectors-configuring.adoc
  modules/nodes-scheduler-taints-tolerations-seconds.adoc
  nodes/scheduling/nodes-scheduler-node-projects.adoc
Labels: branch/enterprise-4.0, size/L

#13675 Removing node-config.yaml references
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-garbage-collection-containers.adoc
  modules/nodes-nodes-garbage-collection-images.adoc
  modules/nodes-nodes-modifying-maximum.adoc
  modules/nodes-nodes-resources-configuring-setting.adoc
  modules/nodes-pods-plugins-install.adoc
  modules/nodes-scheduler-node-affinity-configuring-preferred.adoc
  modules/nodes-scheduler-node-affinity-configuring-required.adoc
  modules/nodes-scheduler-node-antiaffinity-configuring.adoc
Labels: branch/enterprise-4.0, size/L

#13607 Update the docs for new feature gates
  modules/nodes-pods-disabling-features-about.adoc
  modules/nodes-pods-disabling-features-cluster.adoc
  modules/nodes-pods-disabling-features-list.adoc
  nodes/clusters/nodes-pods-disabling-features.adoc
Labels: branch/enterprise-4.0, size/L

#13756 Removing node-config.yaml references II
  modules/nodes-cluster-overcommit-node-enforcing.adoc
  modules/nodes-cluster-overcommit-node-memory.adoc
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-managing-about.adoc
  modules/nodes-nodes-managing-max-pods-proc.adoc
  modules/nodes-nodes-resources-configuring-setting.adoc
  modules/nodes-pods-disabling-features-cluster.adoc
  modules/nodes-pods-disabling-features-nodes.adoc
  modules/nodes-pods-plugins-install.adoc
  nodes/clusters/nodes-pods-disabling-features.adoc
Labels: size/L

#13757 Remove master-config.yaml from Nodes bucket II
  modules/nodes-pods-priority-disabling.adoc
  modules/nodes-scheduler-default-modifying.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  modules/nodes-scheduler-taints-tolerations-evictions.adoc
  nodes/scheduling/nodes-scheduler-taints-tolerations.adoc
Labels: size/L

#13759 small change to kick off build
  admin_guide/manage_nodes.adoc
Labels: size/XS

#13594 3.11 docs conversion monitoring
  _topic_map.yml
  modules/monitoring-accessing-prometheus-alertmanager-grafana.adoc
  modules/monitoring-alerting-rules.adoc
  modules/monitoring-alertmanager-default-configuration.adoc
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
  modules/monitoring-configuring-etcd-monitoring.adoc
  modules/monitoring-dead-mans-switch-pagerduty.adoc
  modules/monitoring-dead-mans-switch.adoc
  modules/monitoring-enabling-dynamically-provisioned-storage.adoc
  modules/monitoring-enabling-persistent-storage.adoc
  modules/monitoring-full-list-of-configuration-variables.adoc
  modules/monitoring-grouping-alerts.adoc
  modules/monitoring-monitoring-overview.adoc
  modules/monitoring-setting-persistent-storage-size.adoc
  modules/monitoring-supported-configuration.adoc
  modules/monitoring-update-and-compatibility-guarantees.adoc
  monitoring/installing-monitoring-stack.adoc
  monitoring/prometheus-cluster-monitoring.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL
