Repository openshift/openshift-docs, pull requests merged in 2019-01, with the labels that each got.

#13201 Fix bug 1650105
  install_config/topics/manually_configuring_for_vsphere.adoc
  install_config/topics/vsphere_prerequisites.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13196 correct typo 3110 bug1662075
  install/host_preparation.adoc
Labels: branch/enterprise-3.11, size/XS

#13200 Allowing unsafe sysctls is no longer experimental
  admin_guide/sysctls.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#13205 update from translation
  install_config/topics/configuring_azure_using_ansible.adoc
  install_config/topics/manually_configuring_for_azure.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#12639 bug 1613765 hostname changes for 3.10-3.11 upgrade
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/S

#12436 disable ansible 2.4
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/XS

#13210 [enterprise-3.11] disable ansible 2.4
  upgrading/automated_upgrades.adoc
Labels: size/XS

#13112 FIX:BZ1659352:Provide the available parameter sets for config of non-default storageclass
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, ok-to-test, size/S

#13215 Edit to PR13112
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13128 Update Getting Started installation docs
  getting_started/install_openshift.adoc
  install/configuring_inventory_file.adoc
  install/example_inventories.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, lgtm, size/M

#13144 Add ExpandPersistentVolumes to the controllerArgument section
  dev_guide/expanding_persistent_volumes.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, ok-to-test, size/XS

#13224 [enterprise-3.10] Update Getting Started installation docs
  getting_started/install_openshift.adoc
  install/configuring_inventory_file.adoc
  install/example_inventories.adoc
Labels: size/M

#13223 [enterprise-3.11] Update Getting Started installation docs
  getting_started/install_openshift.adoc
  install/configuring_inventory_file.adoc
  install/example_inventories.adoc
Labels: size/M

#13219 OCP 3.10 should reference RHOCS 3.10, rather than 3.11 (bz 1663065)
  install_config/topics/red_hat_openshift_container_storage.adoc
Labels: size/XS

#13105 porting info about scoping tokens
  _topic_map.yml
  authentication/tokens-scoping.adoc
  modules/tokens-scoping-about.adoc
Labels: branch/enterprise-4.0, size/M

#12916 added common-attributes tag to files
  logging/efk-logging-curator.adoc
  logging/efk-logging-deploy.adoc
  logging/efk-logging-driver.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-exported-fields.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-manual-rollout.adoc
  logging/efk-logging-systemd.adoc
  logging/efk-logging-troubleshooting.adoc
  logging/efk-logging-uninstall.adoc
  logging/efk-logging.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13226 Removing commented section that was in the assembly template
  logging/PLACEHOLDER
  logging/efk-logging-curator.adoc
  logging/efk-logging-deploy.adoc
  logging/efk-logging-driver.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-exported-fields.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-manual-rollout.adoc
  logging/efk-logging-systemd.adoc
  logging/efk-logging-troubleshooting.adoc
  logging/efk-logging-uninstall.adoc
  logging/efk-logging.adoc
Labels: size/L

#13106 OSDOS-85 Basic builds
  _topic_map.yml
  builds/basic-build-operations.adoc
  modules/builds-basic-access-build-logs.adoc
  modules/builds-basic-access-build-verbosity.adoc
  modules/builds-basic-access-buildconfig-logs.adoc
  modules/builds-basic-access-buildconfig-version-logs.adoc
  modules/builds-basic-cancel-all-state.adoc
  modules/builds-basic-cancel-all.adoc
  modules/builds-basic-cancel-build.adoc
  modules/builds-basic-cancel-multiple.adoc
  modules/builds-basic-delete-buildconfig.adoc
  modules/builds-basic-start-build.adoc
  modules/builds-basic-start-environment-variable.adoc
  modules/builds-basic-start-logs.adoc
  modules/builds-basic-start-re-run.adoc
  modules/builds-basic-start-source.adoc
  modules/builds-basic-view-build-details.adoc
Labels: branch/enterprise-4.0, size/L

#13232 Fix:BZ1656032:Change the path of openstack cloud provider conf file for static pods
  install_config/configuring_openstack.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, ok-to-test, size/XS

#13233 Add cloud-config for vsphere nodes (bz 1663385)
  install_config/configuring_vsphere.adoc
Labels: branch/enterprise-3.9, size/XS

#13165 Update individual playbooks from Retry Installation
  install/running_install.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#13064 Added Optimizing compute resources content to 4.0
  _topic_map.yml
  modules/debugging-issues-with-rhel-tools.adoc
  modules/using-a-pre-deployed-image-to-improve-efficiency.adoc
  scalability_and_performance/optimizing-compute-resources.adoc
Labels: branch/enterprise-4.0, size/M

#13227 BZ:1655135 Add trailing slash
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13229 bz:1644046 Remove 'or later' from Ansible version recommendation
  install_config/install/advanced_install.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/XS

#13239 Remove extra '*' from master/node config
  install_config/topics/manually_configuring_for_azure.adoc
  install_config/topics/manually_configuring_for_gce.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13171 Add a note to include timezone for cron jobs
  dev_guide/cron_jobs.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13248 Change docker registery image name
  install/disconnected_install.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#13253 [enterprise-3.5] removed .js from anchor id
  dev_guide/migrating_applications/web_framework_applications.adoc
Labels: size/XS

#13000 osdocs-82 Add build strategy modules
  _topic_map.yml
  builds/build-strategies.adoc
  modules/builds-custom-strategy.adoc
  modules/builds-strategy-custom-build.adoc
  modules/builds-strategy-custom-environment-variables.adoc
  modules/builds-strategy-custom-expose-docker-socket.adoc
  modules/builds-strategy-custom-from-image.adoc
  modules/builds-strategy-custom-secrets.adoc
  modules/builds-strategy-docker-build-arguments.adoc
  modules/builds-strategy-docker-build.adoc
  modules/builds-strategy-docker-environment-variables.adoc
  modules/builds-strategy-docker-force-pull-example.adoc
  modules/builds-strategy-docker-from-image.adoc
  modules/builds-strategy-docker-no-cache.adoc
  modules/builds-strategy-dockerfile-path.adoc
  modules/builds-strategy-enable-pulling-pushing.adoc
  modules/builds-strategy-force-pull-procedure.adoc
  modules/builds-strategy-pipeline-build.adoc
  modules/builds-strategy-pipeline-environment-variables.adoc
  modules/builds-strategy-pipeline-mapping-buildconfig-jenkins.adoc
  modules/builds-strategy-pipeline-providing-jenkinsfile.adoc
  modules/builds-strategy-s2i-build.adoc
  modules/builds-strategy-s2i-buildconfig-environment.adoc
  modules/builds-strategy-s2i-environment-files.adoc
  modules/builds-strategy-s2i-environment-variables.adoc
  modules/builds-strategy-s2i-force-pull-example.adoc
  modules/builds-strategy-s2i-ignore-source-files.adoc
  modules/builds-strategy-s2i-incremental-builds.adoc
  modules/builds-strategy-s2i-override-builder-image-scripts.adoc
  modules/builds-strategy-secrets-web-console.adoc
Labels: branch/enterprise-4.0, size/XL

#13263 Fluent Pod Pre-emption and Priority
  modules/efk-logging-deploy-playbook.adoc
Labels: branch/enterprise-4.0, size/S

#13259 Follow-up: Changes to Agg Logging per jcantrill slack comments
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/M

#13266 [enterprise-3.11] Follow-up: Changes to Agg Logging per jcantrill slack comments
  install_config/aggregate_logging.adoc
Labels: size/M

#12834 Follow-up: Anping comments in Logging Installer forgets to create PV when using NFS
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/L

#13269 [enterprise-3.10] Follow-up: Anping comments in Logging Installer forgets to create PV when using NFS
  install_config/aggregate_logging.adoc
Labels: size/L

#13275 [enterprise-3.10] Update NFS recommendation / call out
  install/configuring_inventory_file.adoc
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#13276 [enterprise-3.9] Update NFS recommendation / call out
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
Labels: size/S

#13277 [enterprise-3.7] Update NFS recommendation / call out
  install_config/registry/deploy_registry_existing_clusters.adoc
  install_config/registry/registry_known_issues.adoc
  scaling_performance/optimizing_storage.adoc
Labels: size/M

#13267 Added release notes for OCP 3.11.59
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/L

#13265 Added release notes for OCP 3.10.89
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/L

#13262 Added release notes for RHBA-2019:0028, OCP 3.9.60
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#13288 Added missing [
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/XS

#13289 [Enterprise 3.10] Cherry-pick of PR13288 and PR13265
  release_notes/ocp_3_10_release_notes.adoc
Labels: size/L

#12994 Added optimizing storage content
  _topic_map.yml
  modules/available-persistent-storage-options.adoc
  modules/recommended-configurable-storage-technology.adoc
  storage/optimizing-storage.adoc
Labels: branch/enterprise-4.0, lgtm, size/L

#13256 OSDOCS-71-75 add build environment modules
  builds/creating-build-inputs.adoc
  modules/builds-build-environment.adoc
  modules/builds-using-build-fields-as-environment-variables.adoc
  modules/builds-using-secrets-as-environment-variables.adoc
Labels: branch/enterprise-4.0, size/M

#13237 Bug BZ1637658 - required parameters in some situations
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.10, size/L

#13231 Add OSDK Helm docs
  _topic_map.yml
  modules/about-operator-sdk.adoc
  modules/building-memcached-operator-using-osdk.adoc
  modules/building-operator-with-helm-using-osdk.adoc
  modules/installing-operator-sdk-cli.adoc
  modules/managing-memcached-operator-using-olm.adoc
  modules/operator-project-staffolding-layout.adoc
  modules/osdk-helm-chart-support.adoc
  operators/operators-appendices.adoc
  operators/osdk-cli-reference.adoc
  operators/osdk-getting-started.adoc
  operators/osdk-helm.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XL

#13278 Fix minor typos
  getting_started/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13293 Fix missing backslash from commands in logging restart
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.7, branch/enterprise-3.9, size/S

#13294 Fix registry url and a typo
  install/disconnected_install.adoc
Labels: branch/enterprise-3.11, size/XS

#13279 Minor changes for clarity
  getting_started/install_openshift.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#13230 Adding changes to 3.11 docs to 4.0
  _topic_map.yml
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-elasticsearch-persistent-storage-about.adoc
  modules/efk-logging-elasticsearch-persistent-storage-local.adoc
  modules/efk-logging-elasticsearch-persistent-storage-persistent.adoc
  modules/efk-logging-elasticsearch-persistent-storage.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-fluentd-log-rotation.adoc
  modules/efk-logging-fluentd-log-viewing.adoc
  modules/efk-logging-fluentd-pod-location.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-manual-rollout-full.adoc
Labels: branch/enterprise-4.0, size/XL

#13313 [enterprise-3.9] Minor changes for clarity
  getting_started/install_openshift.adoc
Labels: size/XS

#13314 Revert "Adding changes to 3.11 docs to 4.0"
  _topic_map.yml
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-elasticsearch-persistent-storage-about.adoc
  modules/efk-logging-elasticsearch-persistent-storage-local.adoc
  modules/efk-logging-elasticsearch-persistent-storage-persistent.adoc
  modules/efk-logging-elasticsearch-persistent-storage.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-fluentd-log-rotation.adoc
  modules/efk-logging-fluentd-log-viewing.adoc
  modules/efk-logging-fluentd-pod-location.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-manual-rollout-full.adoc
Labels: size/XL

#13315 Adding changes to 3.11 docs to 4.0
  _topic_map.yml
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-fluentd.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-elasticsearch-persistent-storage-about.adoc
  modules/efk-logging-elasticsearch-persistent-storage-local.adoc
  modules/efk-logging-elasticsearch-persistent-storage-persistent.adoc
  modules/efk-logging-elasticsearch-persistent-storage.adoc
  modules/efk-logging-fluentd-log-location.adoc
  modules/efk-logging-fluentd-log-rotation.adoc
  modules/efk-logging-fluentd-log-viewing.adoc
  modules/efk-logging-fluentd-pod-location.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-manual-rollout-full.adoc
Labels: size/XL

#13261 OSDOCS-83 triggering and modifying builds
  _topic_map.yml
  builds/triggering-builds-build-hooks.adoc
  modules/builds-build-hooks.adoc
  modules/builds-configuration-change-triggers.adoc
  modules/builds-configuring-post-commit-build-hooks.adoc
  modules/builds-displaying-webhook-urls.adoc
  modules/builds-setting-triggers-manually.adoc
  modules/builds-triggers.adoc
  modules/builds-using-bitbucket-webhooks.adoc
  modules/builds-using-cli-post-commit-build-hooks.adoc
  modules/builds-using-generic-webhooks.adoc
  modules/builds-using-github-webhooks.adoc
  modules/builds-using-gitlab-webhooks.adoc
  modules/builds-using-image-change-triggers.adoc
  modules/builds-webhook-triggers.adoc
Labels: branch/enterprise-4.0, size/XL

#13280 Minor content fixes
  security/container_content.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/S

#13264 Update Kiali screen shots for TP6.
  servicemesh-install/images/kiali-graph.png
  servicemesh-install/images/kiali-istio-config.png
  servicemesh-install/images/kiali-istio-config2.png
  servicemesh-install/images/kiali-legend.png
  servicemesh-install/images/kiali-login.png
  servicemesh-install/images/kiali-overview.png
  servicemesh-install/images/kiali-services-details.png
  servicemesh-install/images/kiali-services-list.png
  servicemesh-install/topics/tutorial-kiali.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#13323 [enterprise-3.11] Updates and changes for Tech Preview 6
  servicemesh-install/servicemesh-install.adoc
  servicemesh-install/topics/application-requirements.adoc
  servicemesh-install/topics/document-attributes.adoc
  servicemesh-install/topics/install-overview.adoc
  servicemesh-install/topics/install-prerequisites.adoc
  servicemesh-install/topics/install-supported-config.adoc
  servicemesh-install/topics/install.adoc
  servicemesh-release-notes/topics/document-attributes.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: size/L

#13281 OSDOCS-73 add build output modules
  _topic_map.yml
  builds/managing-build-output.adoc
  modules/builds-docker-source-build-output.adoc
  modules/builds-output-image-digest.adoc
  modules/builds-output-image-environment-variables.adoc
  modules/builds-output-image-labels.adoc
Labels: branch/enterprise-4.0, size/L

#13324 Update contrib doc to use a better example for root command
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XS

#13258 FIX:1614176:Add openshift_sdn_vxlan_port to networking variable list table.
  install/configuring_inventory_file.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#13331 Took NOTE box out of a table because it skewed Portal doc formatting
  using_images/db_images/mongodb.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13336 [enterprise-3.6]Took NOTE box out of a table because it skewed Portal doc formatting
  using_images/db_images/mongodb.adoc
Labels: size/XS

#13337 [enterprise-3.5] Took NOTE box out of a table because it skewed Portal doc formatting
  using_images/db_images/mongodb.adoc
Labels: size/XS

#13338 [enterprise-3.4] Took NOTE box out of a table because it skewed Portal doc formatting
  using_images/db_images/mongodb.adoc
Labels: size/XS

#13339 [enterprise-3.3]Took NOTE box out of a table because it skewed Portal doc formatting
  using_images/db_images/mongodb.adoc
Labels: size/XS

#13325 Update referencePolicy.type default
  dev_guide/managing_images.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13340 [enterprise-3.11] Update referencePolicy.type default
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.11, size/S

#13341 [enterprise-3.10] Update referencePolicy.type default
  dev_guide/managing_images.adoc
Labels: branch/enterprise-3.10, size/S

#13342 Add Operator name capitalization guidance
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/S

#13349 removing BYO references
  _topic_map.yml
Labels: branch/enterprise-4.0, size/XS

#13291 Add build troubleshooting module
  _topic_map.yml
  builds/troubleshooting-builds.adoc
  modules/builds-troubleshooting-access-resources.adoc
Labels: branch/enterprise-4.0, size/M

#13352 Updated language around supported RHEL versions
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/XS

#13354 Updated language around supported RHEL versions
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS

#13120 porting scc content
  _topic_map.yml
  authentication/managing-security-context-constraints.adoc
  authentication/understanding-authentication.adoc
  authentication/using-rbac.adoc
  modules/authentication-overview.adoc
  modules/rbac-api-authentication.adoc
  modules/rbac-default-projects.adoc
  modules/rbac-groups.adoc
  modules/rbac-projects-namespaces.adoc
  modules/rbac-updating-policy-definitions.adoc
  modules/rbac-users.adoc
  modules/security-context-constraints-about.adoc
  modules/security-context-constraints-command-reference.adoc
  modules/security-context-constraints-creating.adoc
  modules/security-context-constraints-example.adoc
  modules/security-context-constraints-pre-allocated-values.adoc
  modules/security-context-constraints-restore-defaults.adoc
  modules/service-accounts-default.adoc
Labels: branch/enterprise-4.0, size/XXL

#13251 configuring IDP conversion draft
  _topic_map.yml
  authentication/identity_providers/configuring-allow-all-identity-provider.adoc
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/identity_providers/configuring-deny-all-identity-provider.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-gitlab-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  authentication/identity_providers/configuring-keystone-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/identity_providers/configuring-request-header-identity-provider.adoc
  authentication/understanding-identity-provider.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/identity-provider-about-ldap.adoc
  modules/identity-provider-about-request-header.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-allow-all-CRD.adoc
  modules/identity-provider-basic-authentication-CRD.adoc
  modules/identity-provider-basic-authentication-troubleshooting.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/identity-provider-configuring-basic-authentication.adoc
  modules/identity-provider-configuring-github.adoc
  modules/identity-provider-configuring-keystone.adoc
  modules/identity-provider-create-CRD.adoc
  modules/identity-provider-creating-htpasswd-file.adoc
  modules/identity-provider-default-CRD.adoc
  modules/identity-provider-deny-all-CRD.adoc
  modules/identity-provider-github-CRD.adoc
  modules/identity-provider-gitlab-CRD.adoc
  modules/identity-provider-google-CRD.adoc
  modules/identity-provider-htpasswd-CRD.adoc
  modules/identity-provider-keystone-CRD.adoc
  modules/identity-provider-ldap-CRD.adoc
  modules/identity-provider-oidc-CRD.adoc
  modules/identity-provider-overview.adoc
  modules/identity-provider-parameters.adoc
  modules/identity-provider-provisioning-user-lookup-mapping.adoc
  modules/identity-provider-registering-github.adoc
  modules/identity-provider-request-header-CRD.adoc
Labels: branch/enterprise-4.0, size/XXL

#13218 Edits to merged EFK topics
  _topic_map.yml
  logging/efk-logging-curator.adoc
  logging/efk-logging-deploy.adoc
  logging/efk-logging-driver.adoc
  logging/efk-logging-elasticsearch.adoc
  logging/efk-logging-exported-fields.adoc
  logging/efk-logging-external.adoc
  logging/efk-logging-fluentd.adoc
  logging/efk-logging-kibana.adoc
  logging/efk-logging-manual-rollout.adoc
  logging/efk-logging-systemd.adoc
  logging/efk-logging-troubleshooting.adoc
  logging/efk-logging-uninstall.adoc
  logging/efk-logging.adoc
  modules/efk-logging-about-curator.adoc
  modules/efk-logging-about-elasticsearch.adoc
  modules/efk-logging-about-eventrouter.adoc
  modules/efk-logging-about-fluentd.adoc
  modules/efk-logging-about-kibana.adoc
  modules/efk-logging-about-ops-cluster.adoc
  modules/efk-logging-about.adoc
  modules/efk-logging-deploy-eventrouter.adoc
  modules/efk-logging-deploy-ops-cluster.adoc
  modules/efk-logging-deploy-playbook.adoc
  modules/efk-logging-deploy-pre.adoc
  modules/efk-logging-deploy-variables.adoc
  modules/efk-logging-driver-changing.adoc
  modules/efk-logging-driver-viewing.adoc
  modules/efk-logging-exported-fields-aushape.adoc
  modules/efk-logging-exported-fields-docker.adoc
  modules/efk-logging-exported-fields-kubernetes.adoc
  modules/efk-logging-exported-fields-ovirt.adoc
  modules/efk-logging-exported-fields-systemd.adoc
  modules/efk-logging-exported-fields-tlog.adoc
  modules/efk-logging-fluentd-throttling.adoc
  modules/efk-logging-manual-rollout-full.adoc
  modules/efk-logging-manual-rollout-rolling.adoc
  modules/efk-logging-storage-considerations.adoc
  modules/efk-logging-uninstall-efk-eventrouter.adoc
  modules/efk-logging-uninstall-efk-ops.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/L

#13358 Fix a command typo
  release_notes/ose_3_2_release_notes.adoc
Labels: branch/enterprise-3.2, size/XS

#13361 Use `oc set env`, to replace removed `oc env`
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.11, size/XS

#13348 Added details about known issue per docs issue#13345
  release_notes/ocp_3_9_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.9, size/M

#12880 4.0 arch draft
  _topic_map.yml
  architecture/architecture.adoc
  architecture/images/architecture_overview.png
  modules/abstraction-layers.adoc
  modules/architecture-overview.adoc
  modules/cloud_installations.adoc
  modules/installation-options.adoc
  modules/machine-api-overview.adoc
  modules/node-management.adoc
  modules/node-types.adoc
  modules/operators-overview.adoc
  modules/security-overview.adoc
  modules/telemetry-service-overview.adoc
  modules/update-service-overview.adoc
Labels: branch/enterprise-4.0, size/XL

#13295 Add cluster console to OSD docs
  getting_started/dedicated_administrators.adoc
Labels: branch/enterprise-3.11, size/S

#13299 BUGBZ1637616 - removed port number 8888
  install_config/persistent_storage/persistent_storage_manila.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13311 no github links
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#13375 no github links
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#13378 fixing for another cherrypick
  install_config/persistent_storage/persistent_storage_manila.adoc
Labels: size/XS

#13379 cherrypicking to master
  install_config/persistent_storage/persistent_storage_manila.adoc
Labels: branch/enterprise-3.11, size/XS

#13357 Update glusterfs_prereqs_hardware.adoc
  install_config/persistent_storage/topics/glusterfs_prereqs_hardware.adoc
Labels: branch/enterprise-3.11, ok-to-test, size/XS

#13389 Fix typo in REST API introduction
  rest_api/index.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/XS

#13368 BZ-1662698: Corrected first note in configuring identity providers
  install_config/configuring_authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13183 Bug 1660834 - virtctl image-upload command change
  modules/cnv_upload_virtctl.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#13376 adding a mod docs crash course
  contributing_to_docs/contributing_user_stories.adoc
Labels: size/M

#13377 updates to the mod docs guide
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
  mod_docs_guide/mod-docs-conventions-ocp.adoc
  modules/creating-your-first-content.adoc
  modules/mod-docs-ocp-conventions.adoc
Labels: size/M

#13359 Fixes from 1.3 OCP docs feedback, mostly language, markup, formatting
  modules/cnv_accessing_serial_console.adoc
  modules/cnv_accessing_vmi_ssh.adoc
  modules/cnv_accessing_vnc_console.adoc
  modules/cnv_clone_vm_template_gui.adoc
  modules/cnv_cloning_pvc_datavolume.adoc
  modules/cnv_cloning_pvc_virtualmachine.adoc
  modules/cnv_configuring_guest_memory_overcommit.adoc
  modules/cnv_configuring_rbac_permissions.adoc
  modules/cnv_controlling_vms.adoc
  modules/cnv_creating_cluster_admin_user.adoc
  modules/cnv_creating_vm.adoc
  modules/cnv_creating_vm_web_console.adoc
  modules/cnv_deleting_pvcs_webconsole.adoc
  modules/cnv_deleting_vms_webconsole.adoc
  modules/cnv_disabling_guest_memory_overhead_accounting.adoc
  modules/cnv_enabling_repo.adoc
  modules/cnv_events.adoc
  modules/cnv_import_vm_gui.adoc
  modules/cnv_importing_vm_disk_DVs.adoc
  modules/cnv_importing_vm_disk_to_pvc.adoc
  modules/cnv_install_cnv_apb.adoc
  modules/cnv_install_ovscni.adoc
  modules/cnv_install_vmtemplates.adoc
  modules/cnv_installing_cdi_manifest.adoc
  modules/cnv_installing_kubevirt_manifests.adoc
  modules/cnv_installing_virtct_client.adoc
  modules/cnv_installing_web_console.adoc
  modules/cnv_introduction_to_cnv.adoc
  modules/cnv_logs.adoc
  modules/cnv_metrics.adoc
  modules/cnv_metrics_events_logs_webconsole.adoc
  modules/cnv_openshift_commands.adoc
  modules/cnv_pxebooting.adoc
  modules/cnv_requirements.adoc
  modules/cnv_template_openshift_inventory.adoc
  modules/cnv_upload_virtctl.adoc
  modules/cnv_using_openvswitch_bridge.adoc
  modules/cnv_virtctl_commands.adoc
  modules/cnv_vm_storage_volume_types.adoc
Labels: Peer Review Done, branch/enterprise-3.11, ok-to-test, size/XL

#13410 [dedicated to 3.11] Took out latest product page
  _topic_map.yml
Labels: size/XS

#13402 osdocs-227 registry options modules
  _topic_map.yml
  modules/registry-authentication-enabled-registry-overview.adoc
  modules/registry-integrated-openshift-registry.adoc
  modules/registry-quay-overview.adoc
  modules/registry-third-party-registries.adoc
  registry/registry-options.adoc
Labels: branch/enterprise-4.0, size/L

#11893 added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.3, branch/enterprise-3.4, branch/enterprise-3.5, branch/enterprise-3.6, branch/enterprise-3.7, branch/enterprise-3.9, size/M

#13415 [enterprise-3.11] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13416 [enterprise-3.10] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13417 [enterprise-3.9] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13418 [enterprise-3.7] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13419 [enterprise-3.6] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13420 [enterprise-3.5] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13422 [enterprise-3.3] added example to get token for openshift-challenging-client
  architecture/additional_concepts/authentication.adoc
Labels: size/M

#13423 bug 1644908 Correcting CloudForms deprecation/support
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS

#13427 don't overcommit your hypervisor
  scaling_performance/optimizing_compute_resources.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.6, branch/enterprise-3.7, size/XS

#13425 osdocs-227 accessing registry modules
  _topic_map.yml
  modules/registry-accessing-directly.adoc
  modules/registry-accessing-metrics.adoc
  modules/registry-viewing-contents.adoc
  modules/registry-viewing-logs.adoc
  registry/PLACEHOLDER
  registry/accessing-the-registry.adoc
Labels: branch/enterprise-4.0, size/L

#13436 Fixes for dedicated to 3.11
  getting_started/dedicated_administrators.adoc
  welcome/index.adoc
Labels: size/XS

#13366 OSDOCS-52 Understanding Networking
  _topic_map.yml
  modules/networking-ne-openshift-dns.adoc
  networking/understanding-networking.adoc
Labels: branch/enterprise-4.0, size/L

#13437 fixing image issue
  getting_started/dedicated_administrators.adoc
Labels: size/XS

#13438 FINALBZ1647168 -fixed xref to adoc from html
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, approved, branch/enterprise-3.10, size/XS

#13441 Fixed Route-specific Annotations heading in 3.11
  architecture/networking/routes.adoc
Labels: size/XS

#13442 Fixed Route-specific Annotations heading in 3.10
  architecture/networking/routes.adoc
Labels: size/XS

#13443 Fixed Route-specific Annotations heading in 3.9
  architecture/networking/routes.adoc
Labels: size/XS

#13446 updating install drafts
  _topic_map.yml
  installation/installing-aws-account.adoc
  installation/installing-customizations-cloud.adoc
  installation/installing-quickly-cloud.adoc
  installation/uninstalling-cluster-aws.adoc
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
  modules/about-custom-installation.adoc
  modules/installation-about-custom.adoc
  modules/installation-aws-iam-user.adoc
  modules/installation-aws-limits.adoc
  modules/installation-aws-route53.adoc
  modules/installation-clouds.adoc
  modules/installation-customizing.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-overview.adoc
  modules/installation-preparing-assets.adoc
  modules/installation-preparing-custom.adoc
  modules/installation-preparing-hosts.adoc
  modules/installation-provide-credentials.adoc
  modules/installation-rendering.adoc
  modules/installation-uninstall-aws.adoc
  modules/installing-customizations-cloud.adoc
  modules/launching-installer.adoc
  modules/machine-api-overview.adoc
  modules/obtaining_cloud_installer.adoc
Labels: branch/enterprise-4.0, size/XL

#13453 changing bucket name
  _topic_map.yml
  installation-AWS/images
  installation-AWS/installing-aws-account.adoc
  installation-AWS/installing-customizations-cloud.adoc
  installation-AWS/installing-quickly-cloud.adoc
  installation-AWS/modules
  installation-AWS/uninstalling-cluster-aws.adoc
  installation-BYOH/installing-existing-hosts.adoc
  installation-BYOH/uninstalling-existing-hosts.adoc
Labels: branch/enterprise-4.0, size/XS

#13448 For bug BZ1469406 - added note about ansible_ssh_user variable
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13455 BZ-1662448: Fixing typo in anchor
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13461 updating folder names
  installation-AWS/installing-aws-account.adoc
  installation-AWS/installing-customizations-cloud.adoc
  installation-AWS/installing-quickly-cloud.adoc
  modules/glusterfs-hardware-requirements.adoc
  modules/installation-about-custom.adoc
  modules/installation-aws-iam-user.adoc
  modules/installation-aws-limits.adoc
  modules/installation-aws-route53.adoc
  modules/installation-base-packages.adoc
  modules/installation-byo-cloud-requirements.adoc
  modules/installation-byo-system-requirements.adoc
  modules/installation-clouds.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-configuring-dns.adoc
  modules/installation-configuring-node-host-names.adoc
  modules/installation-customizing.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-networking-requirements.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-overview.adoc
  modules/installation-planning.adoc
  modules/installation-preparing-assets.adoc
  modules/installation-preparing-custom.adoc
  modules/installation-preparing-hosts.adoc
  modules/installation-provide-credentials.adoc
  modules/installation-registering-hosts.adoc
  modules/installation-render-options.adoc
  modules/installation-rendering.adoc
  modules/installation-required-ports.adoc
  modules/installation-security-warning.adoc
  modules/installation-storage-requirements.adoc
  modules/installation-uninstall-aws.adoc
  modules/installing-customizations-cloud.adoc
  modules/installing-docker.adoc
  modules/prometheus-database-storage-requirements.adoc
  modules/wildcard-dns-configuring.adoc
Labels: branch/enterprise-4.0, size/M

#13454 bug 1668381 Modified GlusterFS upgrade instructions
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13456 bug 1648122 Typo fixed in overview section
  admin_guide/tcp_ingress_external_ports.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13474 online to 3.11 and travis update
  .travis.yml
  _distro_map.yml
Labels: size/XS

#13475 [enterprise-3.11] took out whole release notes book from dedicated and online
  _topic_map.yml
Labels: size/S

#13467 Added section on Setting Resource Quota for Extended Resources
  admin_guide/quota.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#13478 bug 1669934 Corrected example link
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, branch/enterprise-3.9, size/XS

#13434 osdocs-227 securing and exposing the registry
  _topic_map.yml
  modules/registry-accessing-directly.adoc
  modules/registry-authentication-enabled-registry-overview.adoc
  modules/registry-exposing-non-secure-registry-manually.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/registry-securing-manually.adoc
  modules/registry-viewing-contents.adoc
  modules/registry-viewing-logs.adoc
  registry/securing-exposing-registry.adoc
Labels: branch/enterprise-4.0, size/XL

#13477 bug 1622044 corrected auditFilePath examples
  install_config/master_node_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13494 fixing link
  install_config/topics/aws_service_account.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13384 Added release notes for OCP 3.10.101
  release_notes/ocp_3_10_release_notes.adoc
Labels: branch/enterprise-3.10, size/S

#13498 Bumped 3.10 latest-tag
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: size/S

#13385 Added release notes for OCP 3.9.65
  release_notes/ocp_3_9_release_notes.adoc
Labels: branch/enterprise-3.9, size/S

#13440 Fix "include file not found" error
  install_config/configuring_vsphere.adoc
  install_config/topics/manually_configuring_for_vsphere.adoc
Labels: Peer Review Done, branch/enterprise-3.10, branch/enterprise-3.11, size/XS

#13433 don't overcommit your hypervisor
  scalability_and_performance/optimizing-compute-resources.adoc
Labels: Peer Review Done, branch/enterprise-4.0, size/XS

#13504 Bumped latest-tag to 3.9.65
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  upgrading/automated_upgrades.adoc
  upgrading/manual_upgrades.adoc
Labels: size/M

#13388 Remove unused atomic pages
  _templates/_footer_atomic.html
  _templates/_nav_atomic.html.erb
  _templates/_topnav_atomic.html
  _templates/page.html.erb
Labels: Peer Review Done, size/M, tech_review

#13386 Added release notes for OCP 3.6.173.0.146
  release_notes/ocp_3_6_release_notes.adoc
Labels: branch/enterprise-3.6, size/S

#13507 Bumped latest-tag to 3.6.173.0.146
  install_config/aggregate_logging.adoc
  install_config/install/disconnected_install.adoc
  install_config/upgrading/automated_upgrades.adoc
  install_config/upgrading/manual_upgrades.adoc
Labels: size/XS

#13491 updating description of values in a code block
  install_config/topics/ocp_osp_flavor.adoc
  install_config/topics/ocp_osp_provisioning.adoc
Labels: branch/enterprise-3.10, branch/enterprise-3.11, size/S

#13510 [enterprise-3.10] updating description of values in a code block
  install_config/topics/ocp_osp_flavor.adoc
  install_config/topics/ocp_osp_provisioning.adoc
Labels: size/S

#13468 updates to the custom install draft
  _topic_map.yml
  installing-aws/images
  installing-aws/installing-aws-account.adoc
  installing-aws/installing-customizations-cloud.adoc
  installing-aws/installing-quickly-cloud.adoc
  installing-aws/modules
  installing-aws/uninstalling-cluster-aws.adoc
  installing-byoh/installing-existing-hosts.adoc
  installing-byoh/uninstalling-existing-hosts.adoc
  modules/glusterfs-hardware-requirements.adoc
  modules/installation-about-custom.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-aws-iam-user.adoc
  modules/installation-aws-limits.adoc
  modules/installation-aws-route53.adoc
  modules/installation-base-packages.adoc
  modules/installation-byo-cloud-requirements.adoc
  modules/installation-byo-system-requirements.adoc
  modules/installation-clouds.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-configuring-dns.adoc
  modules/installation-configuring-node-host-names.adoc
  modules/installation-customizing.adoc
  modules/installation-default-aws-config-yaml.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-networking-requirements.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-overview.adoc
  modules/installation-planning.adoc
  modules/installation-preparing-assets.adoc
  modules/installation-preparing-custom.adoc
  modules/installation-preparing-hosts.adoc
  modules/installation-provide-credentials.adoc
  modules/installation-registering-hosts.adoc
  modules/installation-render-options.adoc
  modules/installation-rendering.adoc
  modules/installation-required-ports.adoc
  modules/installation-security-warning.adoc
  modules/installation-storage-requirements.adoc
  modules/installation-uninstall-aws.adoc
  modules/installing-customizations-cloud.adoc
  modules/installing-docker.adoc
  modules/prometheus-database-storage-requirements.adoc
  modules/wildcard-dns-configuring.adoc
Labels: branch/enterprise-4.0, size/XL

#13512 revert docker.io changes
  modules/registry-accessing-directly.adoc
  modules/registry-securing-manually.adoc
Labels: branch/enterprise-4.0, size/XS
