Repository openshift/openshift-docs, pull requests merged in 2020-02, with the labels that each got.

#19281 search: add ARO search support
  _javascripts/hc-search.js
  _templates/_page_openshift.html.erb
Labels: size/XS

#19203 OSDOCS-332 - Add command to show PVC binding status
  modules/storage-persistent-storage-pv.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19272 BZ#1789120 Have additonalNetworks name match 'oc get' output
  modules/nw-multus-create-network.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19289 BZ#1794683 Remove warning for required public CA signing of certs
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#18784 Bug 1779924 Add configuration settings
  modules/builds-source-input-satellite-config.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19466 Fixing build issue
  modules/builds-source-input-satellite-config.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19468 Enterprise 4.4 CP Bug 1779924 Add configuration settings
  modules/builds-source-input-satellite-config.adoc
Labels: size/S

#19469 Enterprise 4.3 CP Bug 1779924 Add configuration settings
  modules/builds-source-input-satellite-config.adoc
Labels: size/S

#19470 Enterprise 4.2 CP Bug 1779924 Add configuration settings
  modules/builds-source-input-satellite-config.adoc
Labels: size/S

#19360 Allow hostNetwork ingress for network policy
  modules/nw-networkpolicy-about.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19465 typo
  modules/rhcos-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19480 Renaming files to support stand alone Jaeger.
  modules/installation-special-config-kmod.adoc
  modules/jaeger-architecture.adoc
  modules/jaeger-features.adoc
  modules/jaeger-product-overview.adoc
  service_mesh/service_mesh_arch/ossm-jaeger.adoc
Labels: size/S

#19452 Adding additional info on upgrade note
  cnv/cnv-release-notes/cnv-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19447 comments about folder names
  contributing_to_docs/doc_guidelines.adoc
Labels: size/S

#19355 Updates for BZ1702001
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#19467 BZ#1769300 Add kube-proxy metrics to Control Plane Ingress table
  modules/installation-aws-user-infra-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19495 release notes bug fix correction
  release_notes/ocp-4-3-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#19454 BZ1790673 - Add prereq to disconnected cluster update
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#19145 bug 1791994 - FCP restriction on z in 4.2
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/S

#19403 dedicated note correction for backups
  day_two_guide/topics/proc_backing-up-project.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#19501 [enterprise-4.1] typo
  getting_started/accessing-your-services.adoc
  installing/installing-gather-logs.adoc
  modules/installation-dns-user-infra.adoc
  modules/installation-infrastructure-user-infra.adoc
  modules/installation-overview.adoc
  modules/rhcos-about.adoc
Labels: size/S

#19483 [enterprise-4.2] Remove new docs on configuring custom PKI using Proxy API
  _topic_map.yml
  builds/setting-up-trusted-ca.adoc
  modules/certificate-injection-using-operators.adoc
  modules/installation-configure-proxy.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  modules/nw-proxy-configure-object.adoc
  networking/configuring-a-custom-pki.adoc
  networking/ingress-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/M

#17838 4.2 private
  _topic_map.yml
  installing/install_config/configuring-private-cluster.adoc
  modules/private-clusters-about.adoc
  modules/private-clusters-setting-api-private.adoc
  modules/private-clusters-setting-dns-private.adoc
  modules/private-clusters-setting-ingress-private.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, needs-rebase, size/L

#19310 Adding rel note for CNV 2.1 - BZ1754920
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/S

#19511 Add OperatorSources deprecation notice back to 4.3 relnotes
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/S

#19513 Typos
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-creating-aws-bootstrap.adoc
  modules/installation-creating-aws-control-plane.adoc
  modules/installation-creating-aws-worker.adoc
  modules/installation-creating-gcp-bootstrap.adoc
  modules/installation-creating-gcp-control-plane.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-gcp-user-infra-adding-ingress.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19510 Removing OBJ object rendering
  release_notes/ocp-4-1-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.1, size/S

#19517 [enterprise-4.1] Typos
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-creating-aws-bootstrap.adoc
  modules/installation-creating-aws-control-plane.adoc
  modules/installation-creating-aws-worker.adoc
Labels: size/XS

#19498 updates for BZ1728350
  modules/metering-store-data-in-s3.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19502 Update Kubernetes to 1.17 version in outputs
  modules/dr-recover-lost-control-plane-hosts.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/looking-inside-nodes.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/rhel-compute-updating.adoc
  modules/understanding-workers-masters.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#19328 BZ-1795264: Updating login command for several IDPs
  modules/identity-provider-add.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/M

#19503 Bug 1784532: Clarify FROM behavior in builds.
  modules/builds-strategy-docker-from-image.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, bugzilla/valid-bug, size/XS

#19538 quick spelling updates for metering
  modules/metering-cluster-usage-examples.adoc
  modules/metering-cluster-utilization-examples.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19537 Update the Report documentation for Metering.
  metering/reports/metering-storage-locations.adoc
  modules/metering-reports.adoc
  modules/metering-writing-reports.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19531 adding content of uninstalling metering
  _topic_map.yml
  metering/metering-uninstall.adoc
  modules/metering-store-data-in-s3.adoc
  modules/metering-uninstall.adoc
Labels: Peer Review Needed, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19142 [WIP] Updates to Knative Client docs (Serverless)
  _topic_map.yml
  images/question-circle.png
  modules/kubefed-document-attributes.adoc
  modules/serverless-installing-cli-web-console.adoc
  serverless/knative-client.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, do-not-merge/work-in-progress, size/M

#19422 SRVKS-409 Serverless metering updates for k8s 1.16 (>=OCP4.3) metrics
  modules/serverless-metering-datasources.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19280 Change KnativeServing's API group to the new value.
  modules/serverless-deleting-knative-serving-crds.adoc
  modules/serverless-installing-knative-serving.adoc
  modules/serverless-uninstalling-knative-serving.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19232 Added release notes for Serverless tech preview 1.4.0
  _topic_map.yml
  modules/serverless-rn-1-4-0.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, size/M

#19556 quick update
  metering/reports/metering-storage-locations.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19560 Updates to Knative Client docs (Serverless)
  _topic_map.yml
  images/question-circle.png
  modules/serverless-installing-cli-web-console.adoc
  serverless/knative-client.adoc
Labels: size/M

#19563 Added release notes for Serverless 1.4.0
  _topic_map.yml
  modules/serverless-rn-1-4-0.adoc
  serverless/serverless-release-notes.adoc
Labels: size/M

#19497 Update link for fluentd
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/XS

#19512 Add CatalogSource step to disconnected OLM
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-testing-operator-catalog-image.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19548 Clarify OperatorSource/CSC deprecation note
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2, size/S

#19471 BZ-1795670: Use full path to scripts
  modules/restore-add-master.adoc
  modules/restore-remove-failed-master.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#19363 BZ-1731015: Clarify the parameters
  modules/restore-add-master.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19432 Updating CNV uninstall assembly with new namespace module
  cnv/cnv_install/uninstalling-container-native-virtualization.adoc
  modules/deleting-a-namespace-using-the-web-console.adoc
  modules/deleting-a-project-using-the-web-console.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19580 Fix 'manger' typo
  modules/pod-interactions-with-topology-manager.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#17680 Add director and dnsmasq param in network prereqs
  modules/installation-osp-verifying-external-network.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, size/S

#19573 Fix a YAML line
  modules/monitoring-configuring-the-cluster-monitoring-stack.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19453 BZ-1667744: Fix repo name for power-9 reposync
  install/disconnected_install.adoc
Labels: branch/enterprise-3.11, size/XS

#18556 amending cluster-cidr at node level after modifying cluster network C…
  install_config/configuring_sdn.adoc
Labels: branch/enterprise-3.11, lgtm, size/M

#19590 BZ1799487 - Move OCS to Configuring persistent storage
  _topic_map.yml
  storage/persistent-storage/persistent-storage-ocs.adoc
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/S

#18944 Move KB article "OpenShift 4.2 Upgrades phased roll out" contents int…
  modules/understanding-upgrade-channels.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19606 [enterprise-4.3] Move KB article "OpenShift 4.2 Upgrades phased roll out" contents int…
  modules/understanding-upgrade-channels.adoc
Labels: size/L

#19608 [enterprise-4.2] Move KB article "OpenShift 4.2 Upgrades phased roll out" contents int…
  modules/understanding-upgrade-channels.adoc
Labels: size/L

#19609 BZ1799487 - Move OCS to Configuring persistent storage
  _topic_map.yml
  storage/persistent-storage/persistent-storage-ocs.adoc
  welcome/index.adoc
Labels: branch/enterprise-4.2, size/S

#19610 BZ1799487 - Move OCS to Configuring persistent storage
  _topic_map.yml
  storage/persistent-storage/persistent-storage-ocs.adoc
  welcome/index.adoc
Labels: branch/enterprise-4.3, size/S

#19611 Move OCS to end of Install section
  welcome/index.adoc
Labels: branch/enterprise-4.4, size/XS

#19626 redirects for OCS and metering
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#19392 Small formatting fixes and fixes from the minimalism sessions.
  _topic_map.yml
  cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/installing-odo.adoc
  cli_reference/openshift_developer_cli/managing-environment-variables-in-odo.adoc
  cli_reference/openshift_developer_cli/odo-architecture.adoc
  cli_reference/openshift_developer_cli/odo-release-notes.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
  cli_reference/openshift_developer_cli/using-sample-applications.adoc
  modules/openshift-developer-cli-adding-a-custom-builder-to-specify-a-build-image.adoc
  modules/openshift-developer-cli-adding-storage-to-the-application-components.adoc
  modules/openshift-developer-cli-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/openshift-developer-cli-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/openshift-developer-cli-sample-applications.adoc
  modules/openshift-developer-cli-using-command-completion.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19628 Updated versions mentioned in dedicated release notes
  release_notes/dedicated-4-2-release-notes.adoc
Labels: branch/enterprise-4.2, size/XS

#19629 Small formatting fixes and fixes from the minimalism sessions.
  _topic_map.yml
  cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/installing-odo.adoc
  cli_reference/openshift_developer_cli/managing-environment-variables-in-odo.adoc
  cli_reference/openshift_developer_cli/odo-architecture.adoc
  cli_reference/openshift_developer_cli/odo-release-notes.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
  cli_reference/openshift_developer_cli/using-sample-applications.adoc
  modules/openshift-developer-cli-adding-a-custom-builder-to-specify-a-build-image.adoc
  modules/openshift-developer-cli-adding-storage-to-the-application-components.adoc
  modules/openshift-developer-cli-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/openshift-developer-cli-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/openshift-developer-cli-sample-applications.adoc
  modules/openshift-developer-cli-using-command-completion.adoc
Labels: size/L

#19630 Small formatting fixes and fixes from the minimalism sessions.
  _topic_map.yml
  cli_reference/openshift_developer_cli/creating-a-multicomponent-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-a-single-component-application-with-odo.adoc
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/installing-odo.adoc
  cli_reference/openshift_developer_cli/managing-environment-variables-in-odo.adoc
  cli_reference/openshift_developer_cli/odo-architecture.adoc
  cli_reference/openshift_developer_cli/odo-release-notes.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
  cli_reference/openshift_developer_cli/using-sample-applications.adoc
  modules/openshift-developer-cli-adding-a-custom-builder-to-specify-a-build-image.adoc
  modules/openshift-developer-cli-adding-storage-to-the-application-components.adoc
  modules/openshift-developer-cli-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/openshift-developer-cli-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/openshift-developer-cli-sample-applications.adoc
  modules/openshift-developer-cli-using-command-completion.adoc
Labels: size/L

#19604 Bugfix for Helm.
  modules/helm-creating-a-custom-helm-chart-on-openshift.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19434 Initial commit for Knative Eventing TP content @ Serverless GA
  _topic_map.yml
  modules/knative-cli.adoc
  modules/serverless-eventing-components.adoc
  modules/serverless-serving-components.adoc
  serverless/creating-serverless-applications.adoc
  serverless/knative_serving/cluster-logging-serverless.adoc
  serverless/knative_serving/configuring-knative-serving-autoscaling.adoc
  serverless/knative_serving/creating-serverless-applications.adoc
  serverless/knative_serving/getting-started-knative-services.adoc
  serverless/knative_serving/images
  serverless/knative_serving/interacting-serverless-apps.adoc
  serverless/knative_serving/modules
  serverless/knative_serving/serverless-knative-serving.adoc
  serverless/knative_serving/splitting-traffic-between-revisions.adoc
  serverless/serverless-architecture.adoc
  serverless/serverless-getting-started.adoc
  serverless/serverless-knative-eventing.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19636 [enterprise-4.3] Initial commit for Knative Eventing TP content @ Serverless GA
  _topic_map.yml
  modules/knative-cli.adoc
  modules/serverless-eventing-components.adoc
  modules/serverless-serving-components.adoc
  serverless/creating-serverless-applications.adoc
  serverless/knative_serving/cluster-logging-serverless.adoc
  serverless/knative_serving/configuring-knative-serving-autoscaling.adoc
  serverless/knative_serving/creating-serverless-applications.adoc
  serverless/knative_serving/getting-started-knative-services.adoc
  serverless/knative_serving/images
  serverless/knative_serving/interacting-serverless-apps.adoc
  serverless/knative_serving/modules
  serverless/knative_serving/serverless-knative-serving.adoc
  serverless/knative_serving/splitting-traffic-between-revisions.adoc
  serverless/serverless-architecture.adoc
  serverless/serverless-getting-started.adoc
  serverless/serverless-knative-eventing.adoc
Labels: size/L

#19637 [enterprise-4.4] Initial commit for Knative Eventing TP content @ Serverless GA
  _topic_map.yml
  modules/knative-cli.adoc
  modules/serverless-eventing-components.adoc
  modules/serverless-serving-components.adoc
  serverless/creating-serverless-applications.adoc
  serverless/knative_serving/cluster-logging-serverless.adoc
  serverless/knative_serving/configuring-knative-serving-autoscaling.adoc
  serverless/knative_serving/creating-serverless-applications.adoc
  serverless/knative_serving/getting-started-knative-services.adoc
  serverless/knative_serving/images
  serverless/knative_serving/interacting-serverless-apps.adoc
  serverless/knative_serving/modules
  serverless/knative_serving/serverless-knative-serving.adoc
  serverless/knative_serving/splitting-traffic-between-revisions.adoc
  serverless/serverless-architecture.adoc
  serverless/serverless-getting-started.adoc
  serverless/serverless-knative-eventing.adoc
Labels: size/L

#19596 Adding minor style changes found during peer reviews
  modules/cnv-about-liveness-readiness-probes.adoc
  modules/cnv-add-disk-to-vm.adoc
  modules/cnv-add-nic-to-vm.adoc
  modules/cnv-editing-vm-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19342 Continuation of PR#19340
  _topic_map.yml
  modules/machineset-modifying.adoc
  modules/recommended-scale-practices.adoc
  scalability_and_performance/recommended-cluster-scaling-practices.adoc
Labels: Peer Review Done, branch/enterprise-3.3, branch/enterprise-3.4, size/M

#19642 updated report immediately
  modules/metering-reports.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19620 New Features for RN 2.2
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19151 IBM z hardware clarification
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#19656 [enterprise-4.2] IBM z hardware clarification
  modules/installation-requirements-user-infra.adoc
Labels: size/XS

#18307 BZ#1770694 Apache authentication example using request header
  authentication/identity_providers/configuring-request-header-identity-provider.adoc
  modules/identity-provider-apache-custom-proxy-configuration.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19536 Add recommendation for installing large clusters
  _topic_map.yml
  modules/recommended-install-practices.adoc
  scalability_and_performance/recommended-install-practices.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19663 [enterprise-4.2] - Updating documentation to make disconnected install more clear
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: size/XS

#19666 Add more details re: disconnected + relatedImages
  modules/olm-enabling-operator-restricted-network.adoc
  operators/olm-restricted-networks.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19670 Fix cluster/shard order in OSD URL
  modules/dedicated-configuring-your-application-routes.adoc
Labels: size/XS

#19652 Update podman command for CAM 1.1 (OSP 3.x)
  modules/migration-installing-cam-operator-ocp-3.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19584 Release Notes 4.3.1 errata update
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/M

#19477 bug 1782039 adding vCenter to noProxy
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19641 Release Notes 4.2.18 errata update
  release_notes/ocp-4-2-release-notes.adoc
Labels: size/M

#19677 Removed xref, added steps for editing VM yaml
  modules/cnv-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19687 [enterprise-4.2] Removed xref, added steps for editing VM yaml
  modules/cnv-importing-vmware-vm.adoc
Labels: size/XS

#19319 Added manual rollback procedure and updated known issues.
  migration/migrating-3-4/troubleshooting.adoc
  migration/migrating-4_1-4/troubleshooting.adoc
  migration/migrating-4_2-4/troubleshooting.adoc
  modules/migration-known-issues.adoc
  modules/migration-manually-rolling-back-migration.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19691 [enterprise-4.2] Added manual rollback procedure and updated known issues.
  migration/migrating-3-4/troubleshooting.adoc
  migration/migrating-4_1-4/troubleshooting.adoc
  migration/migrating-4_2-4/troubleshooting.adoc
  modules/migration-known-issues.adoc
  modules/migration-manually-rolling-back-migration.adoc
Labels: size/L

#19692 Add guidance on code snip continuation
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/S

#17978 Update examples for Using sample imagestreams in a restricted network installation
  _topic_map.yml
  modules/cli-installing-cli.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-local-registry-pull-secret.adoc
  modules/installation-mirror-repository.adoc
  modules/installation-restricted-network-samples.adoc
  openshift_images/samples-operator-alt-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19664 bug 1798921 BYO VPC proxy
  installing/installing_aws/installing-aws-private.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  installing/installing_azure/installing-azure-private.adoc
  installing/installing_azure/installing-azure-vnet.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  networking/enable-cluster-wide-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19704 Bug 1801472, added known issue for OCP 4.2.18
  release_notes/ocp-4-2-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#19707 Typo
  modules/infrastructure-moving-registry.adoc
Labels: size/XS

#19654 CNV Updating virtio namespace/repo and url
  modules/cnv-adding-virtio-drivers-vm-yaml.adoc
  modules/cnv-removing-virtio-disk-from-vm.adoc
  modules/cnv-understanding-virtio-drivers.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19635 Added note about Serverless 1.4.1
  modules/serverless-rn-1-4-0.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19618 Add info about machine delete policies
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19572 OSP 16 now available as GA
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19739 Fixed title for Serverless 4.3 docs
  serverless/serverless-release-notes.adoc
Labels: size/XS

#19736 Create dummy Release Notes for 4.4 on master
  _topic_map.yml
  installing/install_config/customizations.adoc
  migration/migrating-3-4/planning-migration-3-to-4.adoc
  release_notes/ocp-4-4-release-notes.adoc
  welcome/index.adoc
Labels: branch/enterprise-4.4, size/S

#19742 Stub for 4.4 release notes
  _topic_map.yml
  migration/migrating-3-4/planning-migration-3-to-4.adoc
  release_notes/ocp-4-1-release-notes.adoc
  release_notes/ocp-4-3-release-notes.adoc
  release_notes/ocp-4-4-release-notes.adoc
  welcome/index.adoc
Labels: branch/enterprise-4.4, size/XXL

#19722 bug 1801528 correction machine deletion command
  modules/machine-delete.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19633 4.1.34 release notes stub added
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#19380 fixing release version syntax
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19733 IBM Z restricted network notes
  installing/install_config/installation-types.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  modules/cluster-entitlements.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19698 107 cleanup items
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-control-plane-deploy.adoc
  modules/ossm-control-plane-remove.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-member-roll-create.adoc
  modules/ossm-member-roll-modify.adoc
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/M

#19760 107 updates for 44 branch
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-control-plane-deploy.adoc
  modules/ossm-control-plane-remove.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-member-roll-create.adoc
  modules/ossm-member-roll-modify.adoc
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/M

#19724 Bug 1801385, pipeline strategy is dropped in 4.3
  modules/openshift-cluster-maximums.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19732 Bug 1802420, clarify whether PKI injection is only available to operators
  modules/certificate-injection-using-operators.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19755 bug 1726729 added statement about mismatched packages
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS

#19706 Hard Eviction and Soft Eviction samples show numerical value for inodes instead of percentage values.
  admin_guide/out_of_resource_handling.adoc
Labels: branch/enterprise-3.11, size/S

#19367 Assigning static IPs works only for some SDN plug-ins
  admin_guide/managing_networking.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#19461 Ensure product name is capitalized
  _distro_map.yml
Labels: Peer Review Done, size/XS

#19775 BZ-1802183: Updating 4.3 tag example and linking to tags page
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#19774 BZ-1802183: Updating tag example and linking to tags page
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#19754 4.2.19 release notes stub added
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2, size/S

#19723 BZ#1789125 Add namespace param to Multus plug-in YAML config
  modules/nw-multus-bridge-object.adoc
  modules/nw-multus-create-network.adoc
  modules/nw-multus-host-device-object.adoc
  modules/nw-multus-ipvlan-object.adoc
  modules/nw-multus-macvlan-object.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19731 Bring back Azure UPI registry storage
  _topic_map.yml
  modules/registry-configuring-storage-azure-user-infra.adoc
  registry/configuring-registry-operator.adoc
  registry/configuring_registry_storage/configuring-registry-storage-azure-user-infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#19796 Clarify SAML support
  modules/identity-provider-about-request-header.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19306 [enterprise-4.2] Replace NFS suggestion with OCS
  modules/registry-configuring-storage-baremetal.adoc
Labels: Peer Review Done, branch/enterprise-4.2, lgtm, size/XS

#19665 Add suggestion for OCS for provision persistent storage
  modules/registry-configuring-storage-baremetal.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#19795 Fixed typo in perl
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19803 [enterprise-4.2] Fixed typo in perl
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: size/XS

#19804 [enterprise-4.4] Fixed typo in perl
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: size/XS

#19805 [enterprise-4.3] Fixed typo in perl
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: size/XS

#19693 updating Z versions per support
  modules/installation-requirements-user-infra.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19810 [enterprise-4.4] updating Z versions per support
  modules/installation-requirements-user-infra.adoc
Labels: size/XS

#19735 Release Notes 4.3.2 errata update
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/M

#19790 Bug 1803186, updated defaults based on 4.3 scale tests
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#19634 3.11.170 release notes and RHSA stub
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/M

#19830 Add missing word
  modules/architecture-container-application-benefits.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#16662 Documentation "Configuring systemd-journald" lists incorrect steps
  _topic_map.yml
  modules/cluster-logging-systemd-scaling.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#18103 Add OVN Kubernetes network provider
  _topic_map.yml
  modules/nw-about-multicast.adoc
  modules/nw-disabling-multicast.adoc
  modules/nw-enabling-multicast.adoc
  networking/openshift_sdn/about-openshift-sdn.adoc
  networking/ovn-kubernetes-network-provider/about-ovn-kubernetes.adoc
  networking/ovn-kubernetes-network-provider/disabling-multicast.adoc
  networking/ovn-kubernetes-network-provider/enabling-multicast.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/L

#19841 updated to unset variables
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_3_4/deploying_cam.adoc
  migration/migrating_3_4/migrating-application-workloads-3-to-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/troubleshooting.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/deploying_cam.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4_1-to-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam.adoc
  migration/migrating_4_1_4/troubleshooting.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/deploying_cam.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4_2-to-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam.adoc
  migration/migrating_4_2_4/troubleshooting.adoc
Labels: size/S

#19783 Updating Kubernetes version to 1.17 in release notes
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#19852 [enterprise-4.1] Documentation 'Configuring systemd-journald' lists incorrect step
  _topic_map.yml
  modules/efk-logging-systemd-scaling.adoc
Labels: size/L

#19854 Adding link to Kubernetes 1.15 and 1.16 release notes
  release_notes/ocp-4-3-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.3, size/XS

#19853 Adding link to Kubernetes 1.17 release notes
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.4, size/XS

#19855 Updating cert rotation note
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/S

#19857 Fixing a few typos
  metering/metering-installing-metering.adoc
  modules/cluster-logging-upgrading-logging.adoc
  modules/cnv-define-http-liveness-probe.adoc
  modules/installation-special-config-kmod.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/private-clusters-setting-api-private.adoc
Labels: branch/enterprise-4.4, size/S

#19829 Remove extra step for removing an additional network
  modules/nw-multus-delete-network.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#19862 Use underscores in directory name
  _topic_map.yml
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/disabling-multicast.adoc
  networking/ovn_kubernetes_network_provider/enabling-multicast.adoc
Labels: branch/enterprise-4.4, size/XS

#19761 Need to update HorizontalPodAutoscaler yaml file under section Autoscaling for Memory Utilization
  dev_guide/pod_autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#19624 Add recommendation to enable machine health checks
  modules/recommended-scale-practices.adoc
  scalability_and_performance/recommended-cluster-scaling-practices.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19870 Heading fix
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19874 Removed xref from module per docs guidelines
  web_console/odc-about-developer-perspective.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19873 Add Idea to gitignore
  .gitignore
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19851 Fix navigation path in defining-template-for-external-log-link
  modules/defining-template-for-external-log-link.adoc
Labels: branch/enterprise-4.4, size/XS

#19845 Fix yaml indention in adding-a-custom-logo
  modules/adding-a-custom-logo.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19844 Fix navigation path and CRD format in creating-custom-notification-banners
  modules/adding-custom-notification-banners.adoc
Labels: branch/enterprise-4.4, size/S

#19848 Fix navigation path in creating-custom-links
  modules/creating-custom-links.adoc
Labels: branch/enterprise-4.4, size/XS
