Repository openshift/openshift-docs, pull requests merged in 2020-04, with the labels that each got.

#20798 BZ1703335 Updating the step: Update the spec.strategy.type field from…
  admin_guide/high_availability.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20792 BZ1662043 typos - fix for enterprise-3.11
  admin_guide/service_accounts.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#20762 Add optional annotation step to block default node selector in LSO
  modules/persistent-storage-local-install.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20666 Added release notes for Serverless 1.6.0
  modules/serverless-rn-1-6-0.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#20825 Bump 4.2 ose-operator-registry tag (workaround)
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: branch/enterprise-4.2

#20820 Updated CRD removal section for Serverless
  serverless/installing_serverless/removing-openshift-serverless.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20266 CNV-3167: vm/vmi pause/unpause
  _topic_map.yml
  cnv/cnv_virtual_machines/cnv-controlling-vm-states.adoc
  modules/cnv-cli-reference-controlling-vms.adoc
  modules/cnv-openshift-client-commands.adoc
  modules/cnv-restarting-vm-web.adoc
  modules/cnv-starting-vm-web.adoc
  modules/cnv-stopping-vm-web.adoc
  modules/cnv-unpausing-vm-web.adoc
  modules/cnv-virtctl-commands.adoc
Labels: branch/enterprise-4.4, size/L

#20831 Disabling feature article misinforms of possibility in 3.11
  admin_guide/disabling_features.adoc
Labels: branch/enterprise-3.11

#20810 Enhance PVC resize documentation for OSD
  _topic_map.yml
  modules/dedicated-storage-expanding-filesystem-pvc.adoc
  storage/PLACEHOLDER
  storage/expanding-persistent-volumes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#20837 Update the outputs for oc get svc -n <myproject>
  modules/nw-create-load-balancer-service.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20709 Errata update for 4.3.9 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#20805 Issues: Wrong PV name in install_config/persistent_storage/persistent_storage_iscsi.html
  install_config/persistent_storage/persistent_storage_iscsi.adoc
Labels: branch/enterprise-3.11

#20802 Clarified the service serving cert expiration time frame as per BZ161…
  dev_guide/secrets.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#20758 Errata update for 4.2.26 release
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2

#16414 Add a note to clarify master certs redeployment.
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#20858 Fixed link in Serverless install docs
  serverless/installing_serverless/installing-openshift-serverless.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20836 BZ#1692701 Run openshift_node_group playbook before scaleup
  admin_guide/topics/proc_adding-hosts.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20357 Update procedure for configuring IPsec
  admin_guide/ipsec.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#20821 Updated upgrading section to add API group update
  _topic_map.yml
  modules/serverless-rn-1-4-0.adoc
  modules/serverless-rn-1-5-0.adoc
  modules/serverless-update-api-group.adoc
  modules/serverless-upgrade-sub-channel.adoc
  serverless/installing_serverless/upgrading-serverless.adoc
Labels: branch/enterprise-4.3, do-not-merge/work-in-progress

#20804 BZ1816083 updating template locations
  install_config/imagestreams_templates.adoc
Labels: branch/enterprise-3.11

#20816 BZ1762753 correct 'tuningset' field name to 'tuningsets'
  scaling_performance/using_cluster_loader.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20822 BZ1679419 change Ansible version from 2.5 to 2.6
  install_config/topics/ocp_osp_deploy_instance.adoc
  install_config/topics/ocp_osp_node_registration.adoc
  install_config/topics/ocp_osp_prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20722 Bug 1789657: Enhancement to Kuryr quota documentation
  modules/installation-osp-default-kuryr-deployment.adoc
  modules/installation-osp-kuryr-known-limitations.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, bugzilla/valid-bug

#20648 Document kuryr_openstack_ca option
  install_config/topics/ocp_osp_provisioning.adoc
Labels: branch/enterprise-3.11, lgtm

#20693 Remove incorrect information on ignition files
  modules/installation-ibm-z-user-infra-machines-iso.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20876 BZ#1700770 Edit service creation command
  dev_guide/expose_service/expose_internal_ip_nodeport.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20901 Replace 'execute' with 'run' as recommended in ISG
  dev_guide/expose_service/expose_internal_ip_nodeport.adoc
Labels: branch/enterprise-3.11

#20884 Updated sub channel to 4.3 for GA
  modules/serverless-upgrade-sub-channel.adoc
Labels: Peer Review Done, branch/enterprise-4.3, lgtm

#20823 CNV - bz1819700 HCO_CHANNEL should be CNV_CHANNEL
  cnv/cnv_release_notes/cnv-release-notes.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20796 Bug 1654320, added more details about openshift_console_auth_ca_file
  install/configuring_inventory_file.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20871 PodEvictionTimeout is a variable which needs to be passed to for master nodes
  admin_guide/scheduling/taints_tolerations.adoc
  install_config/master_node_configuration.adoc
Labels: branch/enterprise-3.11

#20875 Updating number of replica for existing indices while deploying openshift-logging
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20897 replaced NFS warning to logging docs per jcantrill
  modules/cluster-logging-elasticsearch-storage.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20869 BZ1703529 corrected command to capture the hawkular certificate
  day_two_guide/certificate_management.adoc
Labels: branch/enterprise-3.11

#20208 Added information on Operator-defined Installation Namespace
  modules/cluster-logging-deploy-clo.adoc
  modules/cnv-subscribing-to-the-catalog.adoc
  modules/metering-install-operator.adoc
  modules/migration-configuring-mcg.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#20937 Added RN: Insights Operator now collects anonymized CSRs
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4

#20817 Changing secret name to a more normal example
  dev_guide/volumes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#20815 Changing secret name to a more normal example
  modules/nodes-containers-volumes-adding.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm

#20788 BZ1817548 - Add Pod teardown note and other minor updates
  modules/persistent-storage-csi-snapshots-create.adoc
  modules/persistent-storage-csi-snapshots-operator.adoc
  modules/persistent-storage-csi-snapshots-provision.adoc
  modules/persistent-storage-csi-snapshots-restore.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#20763 Update to include Certificate Chain info
  modules/customize-certificates-api-add-named.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm

#20899 BZ1725985 Clarify label rules and fix example to be compliant
  creating_images/metadata.adoc
Labels: branch/enterprise-3.11, lgtm

#20951 BZ#1691756 Clarify how CA cert is processed for LDAP IdP
  install_config/configuring_authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20896 Adding upgrade docs for Serverless on OCP 4.4
  _topic_map.yml
  modules/serverless-upgrade-sub-channel.adoc
  serverless/installing_serverless/upgrading-serverless.adoc
Labels: branch/enterprise-4.4

#20354 bug 1782900 MITM proxy settings
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20900 The default values for OpenShift metrics(hawkular) on installation should be documented
  install_config/cluster_metrics.adoc
Labels: branch/enterprise-3.11

#20942 BZ-1747616: Added local PV definition with node affinity
  install_config/persistent_storage/persistent_storage_local.adoc
Labels: branch/enterprise-3.11

#20874 Aggregate Logging Sizing Guidelines doc have wrong references which needs to correct
  install_config/aggregate_logging_sizing.adoc
Labels: branch/enterprise-3.11

#20846 Edit suggested in file machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-creating.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20492 Add information to moving monitoring components instructions
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20978 BZ-1697799: Removed ipfailover command example and added link to admi…
  dev_guide/expose_service/expose_internal_ip_service.adoc
Labels: branch/enterprise-3.11

#20910 Added an example of the allowVolumeExpansion attribute in a StorageClass
  dev_guide/expanding_persistent_volumes.adoc
Labels: branch/enterprise-3.11

#20738 edits to channel topic
  modules/understanding-upgrade-channels.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20932 Added cloud integration note in Configuring for OpenStack - BZ1714240
  install_config/topics/applying_configuration_changes.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20906 Errata update for 4.3.10 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#20781 fluentd secure forward section does not stop elasticsearch logging
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11

#20904 Behavior in storage setup for metrics and logging not properly documented and inconsistent
  install_config/cluster_metrics.adoc
Labels: branch/enterprise-3.11

#20996 Remove dash for CSI features in TP Tracker
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21003 Bug 1771465, removed incorrect statement
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.11

#20988 Fix spelling of section title and typos
  logging/config/cluster-logging-external.adoc
  nodes/nodes/nodes-nodes-audit-log.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20812 Documentation incorrectly advises to edit node-config.yaml instead of ConfigMaps
  admin_guide/sysctls.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20296 ApiServerSource docs
  _topic_map.yml
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml.adoc
  serverless/knative_eventing/serverless-apiserversource.adoc
  serverless/knative_eventing/serverless-event-source-types.adoc
  serverless/knative_eventing/serverless-kn-source.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20913 Clarify phrasing for choosing a region
  modules/installation-aws-limits.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20999 Bug 1710693, added list of service serving certificate secrets
  dev_guide/secrets.adoc
Labels: branch/enterprise-3.11

#20911 Bug 1741675, added support note about upgrade
  install_config/router/customized_haproxy_router.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21013 Add catalog build dep notice + use DP name
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4

#21025 Add --from to catalog build cmds
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#21026 Revert dash additions added in 4.3 RNs
  release_notes/ocp-4-3-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.3

#21031 [enterprise-4.4] Add --from to catalog build cmds
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
Labels: branch/enterprise-4.4

#20124 Bug 1786246 clarify Samples Operator documentation for Jenkins
  modules/installation-restricted-network-samples.adoc
  modules/samples-operator-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#21032 Use downstream base image for catalog build
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#21037 [enterprise-4.4] Use downstream base image for catalog build
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
Labels: branch/enterprise-4.4

#20887 Bug 1812735 correct file in description
  install_config/registry/extended_registry_configuration.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21001 Fixed typo related to API port referenced in oc login
  modules/ossm-control-plane-deploy.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20924 3.11.200 latest tags and release notes stub added
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11

#20923 4.2.27 release notes stub added
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2

#21008 Issue fixes for #19438 and #19437
  modules/interacting-serverless-apps-http2-gRPC.adoc
  modules/verifying-serverless-app-deployment.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20681 Added HA and leader election docs for Serverless
  modules/serverless-serving-resources.adoc
  serverless/installing_serverless/installing-openshift-serverless.adoc
  serverless/knative_cli/knative-cli.adoc
  serverless/knative_serving/serverless-knative-serving.adoc
  serverless/serverless-getting-started.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20783 Added details of SinkBinding for Serverless
  _topic_map.yml
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  serverless/knative_eventing/serverless-sinkbinding.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20992 Moved the commands to appropriate modules.
  modules/openshift-developer-cli-creating-a-project-in-odo.adoc
  modules/openshift-developer-cli-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/openshift-developer-cli-deploying-the-back-end-component.adoc
  modules/openshift-developer-cli-deploying-the-front-end-component.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#21063 fixing typo
  modules/installation-azure-permissions.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#21010 Add dataSource field to CSI cloning example
  modules/persistent-storage-csi-cloning-provisioning.adoc
Labels: Peer Review Done, branch/enterprise-4.4, lgtm

#21069 Release Notes 4.4 updates
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4

#20941 Reorganized Overlay and Thinpool sections
  scaling_performance/optimizing_storage.adoc
Labels: branch/enterprise-3.11

#20591 Add overriding proxy for OLM
  modules/olm-overriding-proxy-settings.adoc
  operators/olm-adding-operators-to-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#21081 [enterprise-4.2] Add overriding proxy for OLM
  modules/olm-overriding-proxy-settings.adoc
  operators/olm-adding-operators-to-cluster.adoc
Labels: branch/enterprise-4.2

#21082 [enterprise-4.3] Add overriding proxy for OLM
  modules/olm-overriding-proxy-settings.adoc
  operators/olm-adding-operators-to-cluster.adoc
Labels: branch/enterprise-4.3

#19170 Hide daemon set section for OpenShift 3.11 ARO
  admin_guide/index.adoc
Labels: branch/enterprise-3.11, size/XS

#16280 Add notes to example inventory files about NFS DNS-1123 requirements
  install/configuring_inventory_file.adoc
Labels: size/S

#20508 BZ-1778362: Adding how to update HTPasswd IDP with new user list
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  modules/identity-provider-creating-htpasswd-file-linux.adoc
  modules/identity-provider-htpasswd-update-users.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm

#20053 OSDOCS-893: Updating DR procedures for the etcd cluster operator
  backup_and_restore/backing-up-etcd.adoc
  backup_and_restore/disaster_recovery/about-disaster-recovery.adoc
  backup_and_restore/disaster_recovery/scenario-1-infra-recovery.adoc
  modules/backup-etcd.adoc
  modules/dr-recover-lost-control-plane-hosts.adoc
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XL

#19173 Indicate that labels updates must include a value
  admin_guide/manage_users.adoc
Labels: branch/enterprise-3.11, size/XS

#20728 Update Kuryr known limitations
  modules/installation-osp-kuryr-known-limitations.adoc
  modules/installation-osp-kuryr-octavia-configuration.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#19504 bug 1797076, CRI-O and FIPS in 3.11
  admin_guide/ipsec.adoc
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#20980 BZ-1680083 Replaced openshift_cockpit_deployer_prefix variable with o…
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
Labels: branch/enterprise-3.11

#21024 Fixing a bunch of 3.11 build warnings
  admin_guide/manage_nodes.adoc
  apb_devel/cli_tooling.adoc
  architecture/infrastructure_components/web_console.adoc
  cnv_install/cnv_install.adoc
  cnv_release_notes/cnv_release_notes.adoc
  cnv_users_guide/cnv_users_guide.adoc
  day_two_guide/docker_tasks.adoc
  day_two_guide/topics/increasing_docker_storage.adoc
  day_two_guide/topics/managing_docker_certs.adoc
  day_two_guide/topics/managing_docker_registries.adoc
  dev_guide/authentication.adoc
  dev_guide/builds/build_strategies.adoc
  dev_guide/templates.adoc
  install/running_install.adoc
  install/uninstalling_cluster.adoc
  install_config/configuring_aws.adoc
  install_config/configuring_openstack.adoc
  install_config/topics/aws_service_account.adoc
  install_config/topics/configuring_for_aws_registry-proc.adoc
  product_security/recommendations_for_customers/restrict_access.adoc
  rest_api/examples.adoc
  using_images/s2i_images/php.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20940 CNV-3580 expose cd-rom
  cnv/cnv_virtual_machines/cnv-create-vms.adoc
  modules/cnv-cdrom-wizard-fields-web.adoc
  modules/cnv-edit-cdrom-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21075 BZ#1677404 Specify roles in single YAML file
  modules/proc_creating-aggregated-cluster-role.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#21112 CephFS and Manila provisioners were removed for 4.x
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21111 [enterprise-4.3] CephFS and Manila provisioners were removed for 4.x
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#21110 [enterprise-4.2] CephFS and Manila provisioners were removed for 4.x
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2

#20907 Clarify podman auth.json for OLM disconnected
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#20938 GarbageCollector section is not clear
  admin_guide/garbage_collection.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21124 Fix typo
  nodes/pods/nodes-pods-plugins.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#21107 OpenShift Pipelines document attributes
  _unused_topics/openshift-pipelines-attributes.adoc
  modules/pipelines-document-attributes.adoc
Labels: branch/enterprise-4.4

#21077 BZ1688089 - Standalone Heketi not supported in 3.11
  install_config/persistent_storage/topics/glusterfs_overview_external.adoc
Labels: branch/enterprise-3.11

#21115 BZ1822552 updating installer command output
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#21087 Change sysconfig.conf to syslog.conf
  modules/cluster-logging-collector-syslog.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#20420 Swiftless ShiftStack installation - OSDOCS923
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  modules/installation-osp-default-deployment.adoc
  modules/installation-osp-enabling-swift.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#21080 Errata update for 4.3.12 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#21108 maximum number of pods per node when pods require PVCs
  modules/openshift-cluster-maximums.adoc
Labels: branch/enterprise-4.4, lgtm

#21062 4.2.28 release notes stub added
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2

#19713 Correct login command for accessing internal registry
  modules/registry-accessing-directly.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#21150 OSDOCS-893: Adding release notes for etcd cluster operator
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#20416 Add CLI instructions for LSO
  modules/persistent-storage-local-install.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/M

#21164 Final 4.3 changes.
  installing/installing_bare_metal_ipi/deploying-ipi-bare-metal.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-configuring-the-metal3-config-file.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/ipi-install-creating-an-rhcos-images-cache.adoc
  modules/ipi-install-creating-the-openshift-manifests.adoc
  modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  modules/ipi-install-extracting-the-openshift-installer.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ipi-install-retrieving-the-openshift-installer.adoc
  modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: branch/enterprise-4.3

#21073 Add fixes for SR-IOV VF partitions
  modules/nw-sriov-nic-partitioning.adoc
  networking/hardware_networks/configuring-sriov-device.adoc
Labels: branch/enterprise-4.4

#21133 Updated steps on running cluster-capacity inside a job to include reg…
  admin_guide/cluster_capacity.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21083 Remove discretionary language from CA redeployment install_config section - BZ 1764890
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#21165 RN 4.4 updates
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4

#21170 BZ1823977 - Better approval command for CSR
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#21180 Remove 'discretionary' language for cert redeploy
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.11

#20885 BZ1731358 Added valid time units, fixed typo.
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11

#20971 BZ1735755/BZ1735759 correcting and adding more detail about user agents
  install_config/configuring_authentication.adoc
Labels: branch/enterprise-3.11, lgtm

#20943 Document the --extended-logging variable
  install_config/router/default_haproxy_router.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20021 Issues: Edit suggested in file install_config/aggregate_logging.adoc
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/M

#21191 updated online documentation
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21166 OSDOCS-960 - Create h2 section for Storage -> CSI
  _topic_map.yml
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  modules/persistent-storage-csi-architecture.adoc
  modules/persistent-storage-csi-cloning-overview.adoc
  modules/persistent-storage-csi-cloning-provisioning.adoc
  modules/persistent-storage-csi-cloning-using.adoc
  modules/persistent-storage-csi-driver-daemonset.adoc
  modules/persistent-storage-csi-dynamic-provisioning.adoc
  modules/persistent-storage-csi-external-controllers.adoc
  modules/persistent-storage-csi-mysql-example.adoc
  modules/persistent-storage-csi-snapshots-controller-sidecar.adoc
  modules/persistent-storage-csi-snapshots-create.adoc
  modules/persistent-storage-csi-snapshots-delete.adoc
  modules/persistent-storage-csi-snapshots-operator.adoc
  modules/persistent-storage-csi-snapshots-overview.adoc
  modules/persistent-storage-csi-snapshots-provision.adoc
  modules/persistent-storage-csi-snapshots-restore.adoc
  storage/container_storage_interface/images
  storage/container_storage_interface/persistent-storage-csi-cloning.adoc
  storage/container_storage_interface/persistent-storage-csi-snapshots.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21030 Added script for checking cert expiration
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.11

#20905 Fix audit logs
  modules/nodes-nodes-audit-log-basic-config.adoc
  modules/nodes-nodes-audit-log-basic-viewing.adoc
  modules/nodes-nodes-audit-log-basic.adoc
  nodes/nodes/nodes-nodes-audit-log.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20355 Add self-signed certificate steps to ShiftStack params module - OSASINFRA1122
  modules/installation-osp-bootstrap-machine.adoc
  modules/installation-osp-describing-cloud-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#21208 Fix invalid admonition type in ShiftStack Kuryr limitations
  modules/installation-osp-kuryr-known-limitations.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#21211 cnv: link to kbase article
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-vmware-vm.adoc
  modules/cnv-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#21118 OSDOCS-876: Adding docs for bound service account tokens
  _topic_map.yml
  authentication/bound-service-account-tokens.adoc
  modules/bound-sa-tokens-about.adoc
  modules/bound-sa-tokens-configuring.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21160 [WIP] OSDOCS-876: Adding release notes for bound service account tokens
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, do-not-merge/work-in-progress

#20998 BZ1739420 - Clarify selector-label volume binding
  install_config/persistent_storage/selector_label_binding.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21176 BZ-1823977: Updating command to approval all pending CSRs
  modules/installation-approve-csrs.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm

#20968 CNV2928 - OVN support
  cnv/cnv-about-cnv.adoc
  cnv/cnv_release_notes/cnv-release-notes.adoc
  modules/cnv-what-you-can-do-with-cnv.adoc
Labels: branch/enterprise-4.4

#21171 Add missing _{context}
  modules/nw-ptp-installing-operator.adoc
  modules/nw-sriov-installing-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#20036 Add content for SCTP
  _topic_map.yml
  modules/nw-sctp-about.adoc
  modules/nw-sctp-enabling.adoc
  modules/nw-sctp-verifying.adoc
  networking/using-sctp.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/L

#21225 More 4.4 release notes updates
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#21122 Need description about how to move the cluster logging resources for cluster on the vSphere environment
  modules/infrastructure-moving-logging.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20936 Update command to run ovs-* in OVS pods
  admin_guide/sdn_troubleshooting.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#21240 Removing note on @type:copy added to 4.3 and 4.4 in error
  modules/cluster-logging-collector-fluentd.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4

#21202 BZ-1651440 Updated Applying Custom Roles and Permissions
  architecture/additional_concepts/authorization.adoc
Labels: branch/enterprise-3.11, lgtm

#21255 BZ1767690 minor typo fix
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#20669 CNV-4324: must delete objects before uninstall
  _topic_map.yml
  cnv/cnv_install/uninstalling-container-native-virtualization.adoc
  cnv/cnv_virtual_machines/cnv-delete-vms.adoc
  cnv/cnv_virtual_machines/cnv-deleting-vmis.adoc
  cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-deleting-datavolumes.adoc
  modules/cnv-about-datavolumes.adoc
  modules/cnv-delete-vm-web.adoc
  modules/cnv-deleting-dvs.adoc
  modules/cnv-deleting-vmi.adoc
  modules/cnv-deleting-vms.adoc
  modules/cnv-listing-dvs.adoc
  modules/cnv-listing-vmis.adoc
Labels: branch/enterprise-4.4

#21210 Add information on Watchdog
  modules/monitoring-alertmanager-default-configuration.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#21254 BZ1649168 - Updated monitoring/metrics references in 'Optimizing pers…
  scaling_performance/optimizing_storage.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#21232 updating 3.11 FIPS note
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, lgtm

#21137 BZ1704090 - Add registry encryption variables for configuring S3
  install_config/topics/configuring_for_aws_registry-proc.adoc
Labels: Peer Review Needed, branch/enterprise-3.11
