Repository openshift/openshift-docs, pull requests merged in 2020-03, with the labels that each got.

#20125 Change pfName to pfNames
  modules/nw-sriov-configuring-device.adoc
Labels: branch/enterprise-4.2, size/XS

#20005 BZ-1722807: Adding note to wait a few minutes after recovering
  modules/dr-recover-lost-control-plane-hosts.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20024 Add instruction on making projects global after move to ovs-multitenant
  install_config/configuring_sdn.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#20098 CheckNodeMemoryPressure & CheckNodeDiskPressure should be removed from docs
  modules/nodes-scheduler-default-predicates.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20145 BZ-1722807: Adding note to wait a few minutes after recovering
  modules/dr-recover-lost-control-plane-hosts.adoc
Labels: size/XS

#20137 Fix typos for SR-IOV content
  modules/nw-sriov-configuring-operator.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#19509 Edits for SR-IOV high performance multicast
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20038 Always installer-provisioned
  modules/accessing-hosts-on-aws.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20061 Subscribe PTP Operator from right channel
  modules/nw-ptp-installing-operator.adoc
Labels: branch/enterprise-4.4, lgtm, size/XS

#19786 [4.3] Subscribe PTP Operator from right channel
  modules/nw-ptp-installing-operator.adoc
Labels: branch/enterprise-4.3, size/XS

#20157 BZ-1806342 Updated typo compute to worker
  modules/nodes-nodes-viewing-listing.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20119 Fix indentation
  modules/adding-a-custom-logo.adoc
Labels: branch/enterprise-4.2, size/XS

#19828 Bug 1783088, update Hard pruning the registry procedure
  modules/pruning-hard-pruning-registry.adoc
  modules/pruning-images.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#20135 Stringify array for internal CRDs
  modules/osdk-hiding-internal-objects.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20170 [enterprise-4.2]Bug 1783088, update Hard pruning the registry procedure
  modules/pruning-hard-pruning-registry.adoc
  modules/pruning-images.adoc
Labels: size/M

#19908 BZ#1798848 Add step for setting mastersSchedulable param 4.3
  modules/nw-modifying-operator-install-config.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/S

#20037 Follow up commit for network policy host network warning
  modules/nw-networkpolicy-about.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20165 BZ#1798848 Add step for setting mastersSchedulable param 4.2
  modules/nw-modifying-operator-install-config.adoc
Labels: branch/enterprise-4.2, size/S

#19954 Added 4.4 metric of 500 pods per node
  modules/how-to-plan-your-environment-according-to-cluster-maximums.adoc
  modules/openshift-cluster-maximums.adoc
Labels: branch/enterprise-4.4, lgtm, size/S

#20182 Added disallow
  .s2i/bin/assemble
Labels: size/S

#20184 fix typo in assembly script
  .s2i/bin/assemble
Labels: size/XS

#19734 BZ-1754052: Added info on managing CSRs and additional node cert info
  day_two_guide/certificate_management.adoc
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#19886 VMware vSphere installation and Time configuration
  modules/installation-vsphere-infrastructure.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20192 Updating note for release with 4.3.5
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/XS

#20193 Increment copyright year 2020
  404-commercial.html
  _templates/_footer_other.html.erb
  index-commercial.html
  search-commercial.html
Labels: Peer Review Done, size/XS

#19911 BZ1797036 Add optional step for configuring NFS PV in reg storage
  modules/registry-configuring-storage-vsphere.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#19968 BZ1661949 - Fix command for disabling ID mapping on NFSv4
  install_config/persistent_storage/persistent_storage_nfs.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#20186 Bug 1809431: "illegal base64 data at input byte 76 ..." error message is shown due to incorrect base64 command
  modules/cluster-logging-collector-external.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, size/XS

#19838 Bug 1788691: Clarify DNS resource record requirements in UPI
  modules/installation-dns-user-infra.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, bugzilla/valid-bug, lgtm, size/S

#20200 removing fips warning for metering
  metering/metering-installing-metering.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20213 YAML formatting correction
  modules/machineset-yaml-azure.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20214 Increment copyright year 2020 on master-3
  404-commercial.html
  _templates/_footer_other.html.erb
  index-commercial.html
  search-commercial.html
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#20220 changed webscale to container-platform-ocp
  _distro_map.yml
Labels: size/XS

#20221 test separate password
  .s2i/bin/assemble
Labels: size/S

#20222 fix assemble script
  .s2i/bin/assemble
Labels: size/S

#20225 assemble script diff
  .s2i/bin/assemble
Labels: size/S

#20229 Use token for version
  installing/install_config/configuring-private-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20233 Remove incorrect prefix from ShiftStack params
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4

#20180 Added Known Issue to OCP 4.2.21 release notes
  release_notes/ocp-4-2-release-notes.adoc
Labels: size/M

#20237 Increment copyright year 2020 in legal notice
  welcome/legal-notice.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20243 Increment copyright year 2020 on master-3
  welcome/legal_notice.adoc
Labels: branch/enterprise-3.11, size/XS

#20248 BZ-1792907 Fixed broken link to Red Hat Single Sign-On
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20223 Added item that Insights Operator collects CSRs and information about cert validity (CCXDEV-227)
  modules/insights-operator-what-information-is-collected.adoc
Labels: Peer Review Done, branch/enterprise-4.4, lgtm, size/XS

#18140 Bug 1759969 Added variable for Importing insecure registries and blocking registries
  modules/images-configuration-insecure.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20245 Proper regexp for variables that *begin* with RAILS_
  dev_guide/environment_variables.adoc
Labels: branch/enterprise-3.11, lgtm, size/XS

#20255 Migration cleanup
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-using-cpma.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20264 Migration cleanup for 4.2
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-using-cpma.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/L

#19811 Boot order items
  _topic_map.yml
  cnv/cnv_virtual_machines/cnv-edit-boot-order.adoc
  modules/cnv-add-boot-order-web.adoc
  modules/cnv-edit-boot-order-web.adoc
  modules/cnv-edit-boot-order-yaml-web.adoc
  modules/cnv-remove-boot-order-item-web.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/L

#20260 Fixed a few typos and updated version details.
  contributing_to_docs/contributing.adoc
Labels: Peer Review Done, size/S

#20253 release notes catchup
  modules/ossm-document-attributes.adoc
  modules/ossm-rn-new-features.adoc
Labels: size/S

#20281 [enterprise-4.4] Added item that Insights Operator collects CSRs and information about…
  modules/insights-operator-what-information-is-collected.adoc
Labels: size/XS

#20106 Changes for RHDEVDOCS-1612-1602
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20285 Changes for RHDEVDOCS-1612-1602
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: size/XS

#20284 Changes for RHDEVDOCS-1612-1602
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: size/XS

#20176 Updated OSD docs to enterprise-4.3
  _distro_map.yml
  _topic_map.yml
  modules/cluster-logging-upgrading-logging.adoc
  openshift_images/images-understand.adoc
Labels: size/S

#20286 Removed OSC tech preview note
  modules/prometheus-database-storage-requirements.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20289 [enterprise-4.2]Removed OSC tech preview note
  modules/prometheus-database-storage-requirements.adoc
Labels: size/S

#20290 [enterprise-4.1]Removed OSC tech preview note
  modules/prometheus-database-storage-requirements.adoc
Labels: size/S

#20272 Edit suggested in file logging/cluster-logging.adoc
  cnv/cnv_logging_events_monitoring/cnv-openshift-cluster-monitoring.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-about-components.adoc
  modules/cluster-logging-about.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#20292 Issue 12512, Link update
  dev_guide/topics/about_device_plugins.adoc
Labels: branch/enterprise-3.11, size/XS

#19505 OSDOCS 723 document automated image pruning
  applications/pruning-objects.adoc
  modules/pruning-images-manual.adoc
  modules/pruning-images.adoc
  registry/configuring-registry-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XL

#20298 OSDOCS 723 document automated image pruning
  applications/pruning-objects.adoc
  modules/pruning-images-manual.adoc
  modules/pruning-images.adoc
  registry/configuring-registry-operator.adoc
Labels: size/XL

#20297 BZ1810772 - one-word typo
  modules/installation-user-infra-machines-pxe.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20304 [enterprise-4.1] Edit suggested in file logging/cluster-logging.adoc
  logging/efk-logging.adoc
  modules/cluster-logging-about.adoc
  modules/efk-logging-about-components.adoc
  modules/efk-logging-about.adoc
Labels: size/M

#20306 [enterprise-4.2] Edit suggested in file logging/cluster-logging.adoc
  cnv/cnv_users_guide/cnv-openshift-cluster-monitoring.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-about-components.adoc
  modules/cluster-logging-about.adoc
Labels: size/M

#20307 [enterprise-4.4] Edit suggested in file logging/cluster-logging.adoc
  cnv/cnv_logging_events_monitoring/cnv-openshift-cluster-monitoring.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-about-components.adoc
  modules/cluster-logging-about.adoc
Labels: size/M

#20308 [enterprise-4.3] Edit suggested in file logging/cluster-logging.adoc
  cnv/cnv_logging_events_monitoring/cnv-openshift-cluster-monitoring.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-about-components.adoc
  modules/cluster-logging-about.adoc
Labels: size/M

#20164 OSD-3014 Federated networking access for dedicated
  _topic_map.yml
  getting_started/cloud_infrastructure_access/dedicated-aws-access.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#20313 Added information about the dedicated-admin role
  modules/dedicated-managing-service-accounts.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20321 minor updates for osd to 4
  _topic_map.yml
  cli_reference/openshift_developer_cli/creating-an-application-with-a-database.adoc
Labels: size/XS

#20007 BZ#1807121 - NAD requires a 'name' for the configuration
  modules/cnv-creating-bridge-nad-cli.adoc
Labels: size/S

#20077 BZ-1771578: Docs for 4.3 for installing CLI using RPM
  cli_reference/openshift_cli/getting-started-cli.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/M

#20074 BZ-1771578: Docs for installing CLI using RPM
  cli_reference/openshift_cli/getting-started-cli.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#20271 BZ#1797841 Note for recommended master node usage
  modules/architecture-machine-roles.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20333 [enterprise-4.2] Fix typo in 4.2 only
  modules/installation-user-infra-machines-pxe.adoc
Labels: size/XS

#20335 [enterprise-4.1] Fix typo in 4.1 only
  modules/installation-user-infra-machines-pxe.adoc
Labels: size/XS

#20336 Formatting fix
  modules/openshift-cluster-maximums.adoc
Labels: size/XS

#20032 Issues: Edit suggested in file admin_guide/overcommit.adoc 4x
  logging/config/cluster-logging-collector.adoc
  modules/nodes-cluster-overcommit-buffer-chunk.adoc
  modules/nodes-cluster-overcommit-resource-requests.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20341 [enterprise-4.1] Edit suggested in file admin_guide/overcommit.adoc 4x
  logging/config/efk-logging-fluentd.adoc
  modules/nodes-cluster-overcommit-buffer-chunk.adoc
  modules/nodes-cluster-overcommit-resource-requests.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
Labels: size/L

#20030 Issues: Edit suggested in file admin_guide/overcommit.adoc
  admin_guide/overcommit.adoc
  install_config/aggregate_logging.adoc
Labels: branch/enterprise-3.11, size/XS

#19592 Removing Opaque Integer Resources
  _topic_map.yml
  modules/nodes-nodes-opaque-resources-about.adoc
  modules/nodes-nodes-opaque-resources-consuming.adoc
  modules/nodes-nodes-opaque-resources-creating.adoc
  nodes/nodes/nodes-nodes-opaque-resources.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/L

#19593 Removing Opaque Integer Resources from 3x
  _topic_map.yml
  admin_guide/opaque_integer_resources.adoc
  dev_guide/compute_resources.adoc
Labels: branch/enterprise-3.11, size/L

#20350 Removing typo in 4.1 branch only
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: branch/enterprise-4.1, size/XS

#20356 Removing typo in 4.2 branch only
  logging/cluster-logging-upgrading.adoc
  metering/metering-installing-metering.adoc
  modules/cluster-logging-upgrading-logging.adoc
  modules/nodes-cluster-disabling-features-cluster.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
  modules/private-clusters-setting-api-private.adoc
Labels: branch/enterprise-4.2, size/S

#19963 BZ1799065
  cnv/cnv_virtual_machines/cnv-create-vms.adoc
Labels: size/XS

#20370 Fix a command
  modules/metering-store-data-in-azure.adoc
Labels: size/XS

#20246 BZ 1791599: Fix typos and formatting issues in expose_service docs
  dev_guide/expose_service/expose_internal_ip_load_balancer.adoc
  dev_guide/expose_service/expose_internal_ip_nodeport.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#20373 [enterprise-3.11] Fix typos and formatting issues in expose_service docs
  dev_guide/expose_service/expose_internal_ip_load_balancer.adoc
  dev_guide/expose_service/expose_internal_ip_nodeport.adoc
  dev_guide/expose_service/expose_internal_ip_service.adoc
Labels: size/M

#20319 Quick update of odo supported table
  cli_reference/openshift_developer_cli/understanding-odo.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#20158 Removing must-gather from dedicated distro
  _topic_map.yml
  modules/support.adoc
Labels: Peer Review Done, branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20379 Removing must-gather from dedicated distro
  _topic_map.yml
  modules/support.adoc
Labels: size/XS

#20380 Removing must-gather from dedicated distro
  _topic_map.yml
  modules/support.adoc
Labels: size/XS

#20089 bz1744543 amended etcd restoration steps
  day_two_guide/topics/con_scaling-etcd.adoc
  day_two_guide/topics/proc_adding-etcd-after-restoring.adoc
  day_two_guide/topics/proc_backing-up-etcd.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
Labels: branch/enterprise-3.11, size/L

#20265 Errata update for 4.2.22 release
  release_notes/ocp-4-2-release-notes.adoc
Labels: branch/enterprise-4.2, size/M

#20324 Make the OS support accurate in 4.2 release note
  release_notes/ocp-4-2-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.2, size/XS

#20382 Fixing space issue
  dev_guide/projects.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#20386 Update version for errata link | 4.2
  modules/update-upgrading-cli.adoc
Labels: Peer Review Done, size/XS

#20387 Update version for errata link | 4.3
  modules/update-upgrading-cli.adoc
Labels: Peer Review Done, size/XS

#20385 Fixing oc adm command
  cli_reference/admin_cli_operations.adoc
Labels: branch/enterprise-3.11, size/XS

#20389 Added missing brace
  install_config/certificate_customization.adoc
Labels: branch/enterprise-3.11, size/XS

#20364 Continuation of Deploying ipi bare metal, PR#20316
  _topic_map.yml
  installing/installing_bare_metal_ipi/deploying-ipi-bare-metal.adoc
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-configuring-the-metal3-config-file.adoc
  modules/ipi-install-creating-the-openshift-manifests.adoc
  modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  modules/ipi-install-extracting-the-openshift-installer.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-retrieving-the-openshift-installer.adoc
  modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-the-control-plane.adoc
  modules/ipi-install-validation-checklist-for-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: size/XL

#20391 [enterprise-4.3 for webscale] Cherry-pick of PR#20364
  _topic_map.yml
  installing/installing_bare_metal_ipi/deploying-ipi-bare-metal.adoc
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_2.png
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-configuring-the-metal3-config-file.adoc
  modules/ipi-install-creating-the-openshift-manifests.adoc
  modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  modules/ipi-install-extracting-the-openshift-installer.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-retrieving-the-openshift-installer.adoc
  modules/ipi-install-troubleshooting-the-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-the-control-plane.adoc
  modules/ipi-install-validation-checklist-for-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: size/XL

#20393 added webscale redirect for welcome page
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#20305 Errata update for 4.3.5 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/M

#20006 OKD to 40
  _distro_map.yml
  _topic_map.yml
  modules/ose_3_0_release_notes.adoc
  modules/whats-new-deprecated.adoc
  modules/whats-new-features.adoc
  whats_new/index.adoc
  whats_new/modules
Labels: size/XXL

#19246 OSDOCS-878: Adding docs for auto rotation of service CA
  modules/customize-certificates-manually-rotate-service-ca.adoc
  modules/customize-certificates-understanding-service-serving.adoc
  modules/update-upgrading-cli.adoc
  modules/update-upgrading-web.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20397 OSDOCS-909: Temporarily commenting out migration planning until updat…
  _topic_map.yml
  migration/migrating_3_4/migrating-application-workloads-3-to-4.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#20155 Update SR-IOV marketplace channel jsonpath
  modules/nw-sriov-installing-operator.adoc
Labels: branch/enterprise-4.2, size/XS

#20400 Fixing a few typos
  modules/cluster-logging-upgrading-logging.adoc
  modules/cnv-define-http-liveness-probe.adoc
  modules/installation-special-config-kmod.adoc
Labels: size/XS

#20402 Fixing a few typos
  modules/cluster-logging-upgrading-logging.adoc
  modules/cnv-define-http-liveness-probe.adoc
  modules/installation-special-config-kmod.adoc
  modules/private-clusters-setting-api-private.adoc
Labels: size/S

#19837 OSDOCS-894: Adding docs for the descheduler
  _topic_map.yml
  modules/nodes-descheduler-about.adoc
  modules/nodes-descheduler-configuring-other-settings.adoc
  modules/nodes-descheduler-configuring-strategies.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-descheduler-strategies.adoc
  nodes/scheduling/nodes-descheduler.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/L

#20320 consolelink: fix Laucher->Launcher typo
  modules/creating-custom-links.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20398 OSDOCS-957: Updating restart requirements due to auto rotation for 4.4
  modules/update-upgrading-cli.adoc
  modules/update-upgrading-web.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.4, lgtm, size/M

#20408 OSDOCS-909: Updating migration planning content for 4.4
  _topic_map.yml
  migration/migrating_3_4/migrating-application-workloads-3-to-4.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#20394 Prefer short flag for whoami -t
  rest_api/index.adoc
Labels: branch/enterprise-3.11, size/XS

#20406 Reintroduce GA'd features in TP table
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4, size/L

#20317 Remove Temp-URL step from Swift procedure - BZ 1805176
  modules/installation-osp-enabling-swift.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20090 replace vnic with nic
  _topic_map.yml
  cnv/cnv_virtual_machines/cnv_vm_networking/cnv-attaching-vm-multiple-networks.adoc
  cnv/cnv_virtual_machines/cnv_vm_networking/cnv-viewing-ip-of-vm-nic.adoc
  modules/cnv-accessing-rdp-console.adoc
  modules/cnv-viewing-vmi-ip-web.adoc
  modules/cnv-vm-rdp-console-web.adoc
Labels: size/M

#20392 Note that OCE does not support SR-IOV hardware
  welcome/oce_about.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#19213 Change instances of machineCIDR to machineNetwork.cidr
  machine_management/manually-scaling-machineset.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-kuryr-config-yaml.adoc
  modules/installation-osp-verifying-external-network.adoc
  modules/nw-install-config-parameters.adoc
  modules/nw-proxy-configure-object.adoc
  networking/enable-cluster-wide-proxy.adoc
Labels: branch/enterprise-4.4, size/M

#20363 Include namespace+pod selector network policy
  modules/nw-networkpolicy-about.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/S

#20430 Bug 1812804: [4.1] Fix the versions
  release_notes/ocp-4-1-release-notes.adoc
Labels: bugzilla/invalid-bug, size/XS

#20227 Docs for odo in airgap
  _topic_map.yml
  cli_reference/openshift_developer_cli/using_odo_in_a_restricted_environment/about-odo-in-a-restricted-environment.adoc
  cli_reference/openshift_developer_cli/using_odo_in_a_restricted_environment/creating-and-deploying-a-component-to-the-disconnected-cluster.adoc
  cli_reference/openshift_developer_cli/using_odo_in_a_restricted_environment/modules
  cli_reference/openshift_developer_cli/using_odo_in_a_restricted_environment/pushing-the-odo-init-image-to-the-restricted-cluster-registry.adoc
  modules/openshift-developer-cli-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/openshift-developer-cli-mirroring-a-supported-builder-image.adoc
  modules/openshift-developer-cli-overwriting-a-mirror-registry.adoc
  modules/openshift-developer-cli-pushing-the-odo-init-image-to-a-mirror-registry.adoc
  modules/openshift-developer-cli-pushing-the-odo-init-image-to-an-internal-registry-directly.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20422 BZ#1783489 Clarify image registry storage config
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-registry-storage-config.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/M

#20428 Fix build warnings in OKD doc
  modules/whats-new-features.adoc
Labels: Peer Review Done, okd-only, size/M

#20275 removing openshift.io/cluster-logging: 'true'
  modules/cluster-logging-deploy-clo-cli.adoc
  modules/cluster-logging-deploy-clo.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#20309 Bug 1795495 update node sample policy configurations
  modules/nodes-scheduler-default-sample.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20163 Add catalog image update procedure
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-testing-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
  operators/olm-restricted-networks.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#19688 Added Serverless 1.5.0 relnotes and updates to docs for 4.3
  modules/deploying-serverless-apps.adoc
  modules/serverless-rn-1-5-0.adoc
  serverless/installing-openshift-serverless.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, size/M

#20366 Add genevePort for OVN-Kubernetes
  modules/nw-operator-cr.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, lgtm, size/XS

#20448 [enterprise-4.3] Added Serverless 1.5.0 relnotes and updates to docs for 4.3
  modules/deploying-serverless-apps.adoc
  modules/serverless-rn-1-5-0.adoc
  serverless/installing-openshift-serverless.adoc
  serverless/serverless-release-notes.adoc
Labels: size/M

#20441 Slight changes to LoadBalancer OSD docs
  modules/dedicated-exposing-TCP-services.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20451 [enterprise-4.4] Added Serverless 1.5.0 relnotes and updates to docs for 4.3
  modules/deploying-serverless-apps.adoc
  modules/serverless-rn-1-5-0.adoc
  serverless/installing-openshift-serverless.adoc
  serverless/serverless-release-notes.adoc
Labels: size/M

#20427 Fixing build warnings
  modules/osdk-crd-templates.adoc
  modules/osdk-owned-crds.adoc
  modules/osdk-required-crds.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS

#20457 add redirect for landing page for migration
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#20459 fix bad redirect
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#20463 added minishift redirect
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#20464 [WIP] undo minishift to 3.11
  .s2i/bin/assemble
  .s2i/httpd-cfg/01-commercial.conf
Labels: do-not-merge/work-in-progress, size/XS

#20261 Add info on packaging to Understanding the OperatorHub
  modules/olm-operatorhub-overview.adoc
  operators/olm-understanding-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20268 Add info/link re OperatorGroups
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-operatorgroups-about.adoc
  operators/olm-adding-operators-to-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20467 BZ1813087 fix indent in one line
  modules/cluster-logging-deploy-eo-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#20439 4.1.38 release notes stub
  release_notes/ocp-4-1-release-notes.adoc
Labels: branch/enterprise-4.1, size/S

#20368 Revert arbitrary uid guidance
  creating_images/guidelines.adoc
Labels: size/M

#20458 Fix broken link to OpenStack Ansible playbook
  _snippets/glusterfs.adoc
  install/running_install.adoc
  install_config/imagestreams_templates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#20454 The default network provider for OKD is OVNKubernetes
  modules/nw-install-config-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#19991 Configuring MCG as replication repo for migration
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-understanding-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, size/L

#20491 Adding MCG storage to CAM for migration
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-understanding-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.2

#20118 bz 1799055: cnv namespace is automatically created
  cnv/cnv_install/installing-container-native-virtualization.adoc
  modules/cnv-deleting-custom-resource.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-preparing-to-install.adoc
  modules/cnv-subscribing-to-the-catalog.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#20365 attach disk edits
  modules/cnv-creating-vm.adoc
  modules/cnv-storage-wizard-fields-web.adoc
  modules/cnv-vm-wizard-fields-web.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#20175 Sending a copy of the logs to an external log aggregator while keeping the logs local
  modules/cluster-logging-collector-external.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/XS
