Repository openshift/openshift-docs, pull requests merged in 2020-09, with the labels that each got.

#25125 Add Secret/ConfigMap as optional bundle objects
  modules/olm-bundle-format.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25160 Update code block style in web console/getting started content
  getting_started/configure_openshift.adoc
  getting_started/developers_cli.adoc
  getting_started/install_openshift.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#25123 Rel Notes doc text for 4.4.19 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, size/M

#25072 Add note about assembly headers
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/M

#25073 OSDOCS-1351 Separate images command and output blocks
  modules/images-add-tags-to-imagestreams.adoc
  modules/images-allow-pods-to-reference-images-across-projects.adoc
  modules/images-allow-pods-to-reference-images-from-secure-registries.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-insecure.adoc
  modules/images-create-guide-general.adoc
  modules/images-create-metadata-define.adoc
  modules/images-create-metadata.adoc
  modules/images-getting-info-about-imagestreams.adoc
  modules/images-imagestream-adding-tags.adoc
  modules/images-imagestream-external-image-tags.adoc
  modules/images-imagestream-import.adoc
  modules/images-imagestream-remove-tag.adoc
  modules/images-imagestream-update-tag.adoc
  modules/images-other-jenkins-agent-images.adoc
  modules/images-other-jenkins-auth.adoc
  modules/images-other-jenkins-create-service.adoc
  modules/images-other-jenkins-cross-project.adoc
  modules/images-pulling-from-private-registries.adoc
  modules/images-remove-tag-imagestream.adoc
  modules/images-test-s2i.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/samples-operator-crd.adoc
  modules/templates-cli-generating-list-of-objects.adoc
  modules/templates-cli-labels.adoc
  modules/templates-cli-parameters.adoc
  modules/templates-create-from-existing-object.adoc
  modules/templates-creating-from-console.adoc
  modules/templates-modifying-uploaded-template.adoc
  modules/templates-rails-configuring-application.adoc
  modules/templates-rails-creating-database-service.adoc
  modules/templates-rails-creating-frontend-service.adoc
  modules/templates-rails-creating-route-for-application.adoc
  modules/templates-rails-creating-welcome-page.adoc
  modules/templates-rails-deploying-application.adoc
  modules/templates-rails-setting-up-database.adoc
  modules/templates-rails-storing-application-in-git.adoc
  modules/templates-rails-writing-application.adoc
  modules/templates-uploading.adoc
  modules/templates-using-instant-app-quickstart.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25023 Separating command and output for 3.11 CLI book
  cli_reference/admin_cli_operations.adoc
  cli_reference/basic_cli_operations.adoc
  cli_reference/extend_cli.adoc
  cli_reference/get_started_cli.adoc
  cli_reference/index.adoc
  cli_reference/manage_cli_profiles.adoc
  dev_guide/authentication.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#25169 Updated code block style in 3.11 Scaling and Performance guide
  admin_guide/manage_nodes.adoc
  architecture/additional_concepts/storage.adoc
  scaling_performance/host_practices.adoc
  scaling_performance/install_practices.adoc
  scaling_performance/managing_hugepages.adoc
  scaling_performance/optimizing_compute_resources.adoc
  scaling_performance/optimizing_storage.adoc
  scaling_performance/scaling_cluster_metrics.adoc
  scaling_performance/using_cluster_loader.adoc
  scaling_performance/using_cpu_manager.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#25154 [WIP] update to provide parity with portal for inclusion of raw files
  build.py
  build_for_portal.py
Labels: branch/enterprise-3.11, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, do-not-merge/work-in-progress, size/M

#25168 Moa update product name in content
  _topic_map.yml
  getting_started_moa/creating-first-moa-cluster.adoc
  getting_started_moa/legal-notice.adoc
  getting_started_moa/overview-moa.adoc
  modules/moa-accessing-your-cluster.adoc
  modules/moa-deleting-cluster.adoc
  modules/moa-installing-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/M

#25163 [WIP] Update UPI templates to auto-update by including raw files
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-control-plane.adoc
  modules/installation-arm-dns.adoc
  modules/installation-arm-image-storage.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-arm-worker.adoc
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-dns.adoc
  modules/installation-cloudformation-security.adoc
  modules/installation-cloudformation-vpc.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-deployment-manager-bootstrap.adoc
  modules/installation-deployment-manager-control-plane.adoc
  modules/installation-deployment-manager-ext-lb.adoc
  modules/installation-deployment-manager-firewall-rules.adoc
  modules/installation-deployment-manager-iam-shared-vpc.adoc
  modules/installation-deployment-manager-int-lb.adoc
  modules/installation-deployment-manager-private-dns.adoc
  modules/installation-deployment-manager-vpc.adoc
  modules/installation-deployment-manager-worker.adoc
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/installation-uninstall-infra.adoc
Labels: branch/enterprise-4.6, do-not-merge/work-in-progress, size/XXL

#25175 [WIP] Update guidelines for embedding an external file
  contributing_to_docs/doc_guidelines.adoc
Labels: do-not-merge/work-in-progress, size/S

#25186 update to use specifically https to openshift repo
  build.py
  build_for_portal.py
Labels: size/XS

#25185 Use https when embedding raw files
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#25192 Serverless redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/S

#25035 VM import requires admin user
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  modules/virt-troubleshooting-vm-import.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/S

#25178 Fixed a mistake in code block style
  getting_started/install_openshift.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#25151 Clarify Configure your firewall section
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25152 Deprecated CLI command deletion and rpm update
  modules/op-installing-tkn-on-linux-using-rpm.adoc
  modules/op-installing-tkn-on-linux.adoc
  modules/op-installing-tkn-on-macos.adoc
  modules/op-installing-tkn-on-windows.adoc
  modules/op-tkn-pipeline-management.adoc
  modules/op-tkn-pipeline-resource-management.adoc
  modules/op-tkn-task-management.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#24759 GitHub-23511: Adding installing CLI by RPM for RHEL 8 for 4.3
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, branch/enterprise-4.3, lgtm, size/S

#24758 GitHub-23511: Adding installing CLI by RPM for RHEL 8 for 4.4
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, branch/enterprise-4.4, lgtm, size/S

#24757 GitHub-23511: Adding installing CLI by RPM for RHEL 8 for 4.5
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, branch/enterprise-4.5, lgtm, size/S

#24756 GitHub-23511: Adding installing CLI by RPM for RHEL 8
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/S

#25204 updates to moa quickstart
  modules/moa-accessing-your-cluster.adoc
  modules/moa-creating-cluster.adoc
  modules/moa-installing-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/L

#25172 Updating code blocks to guideline format for OPC 4.3
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-inmemorychannel.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-6-0.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-workflow-basic.adoc
Labels: Peer Review Done, size/L

#25212 CP of #25172: Updating code blocks to guideline format for OPC 4.4
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-inmemorychannel.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-6-0.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-workflow-basic.adoc
Labels: size/L

#25215 CP of #25172: Updating code blocks to guideline format for OPC 4.5
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-inmemorychannel.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-workflow-basic.adoc
Labels: size/L

#25217 CP of #25172: Updating code blocks to guideline format for master
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-inmemorychannel.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-workflow-basic.adoc
Labels: size/L

#25218 Updating code blocks to guideline format for OPC 4.6
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-inmemorychannel.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-workflow-basic.adoc
Labels: size/L

#25223 Fix code block typo
  modules/installation-uninstall-infra.adoc
Labels: branch/enterprise-4.6, size/XS

#25133 CNV: Storage matrix for VM import
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
  virt/virtual_machines/virtual_disks/virt-features-for-storage.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/L

#25222 [enterprise-4.4] Update UPI templates to auto-update by including raw files
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-control-plane.adoc
  modules/installation-arm-dns.adoc
  modules/installation-arm-image-storage.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-arm-worker.adoc
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-dns.adoc
  modules/installation-cloudformation-security.adoc
  modules/installation-cloudformation-vpc.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-deployment-manager-bootstrap.adoc
  modules/installation-deployment-manager-control-plane.adoc
  modules/installation-deployment-manager-dns.adoc
  modules/installation-deployment-manager-security.adoc
  modules/installation-deployment-manager-vpc.adoc
  modules/installation-deployment-manager-worker.adoc
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/installation-uninstall-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XXL

#25220 [enterprise-4.5] Update UPI templates to auto-update by including raw files
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-control-plane.adoc
  modules/installation-arm-dns.adoc
  modules/installation-arm-image-storage.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-arm-worker.adoc
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-dns.adoc
  modules/installation-cloudformation-security.adoc
  modules/installation-cloudformation-vpc.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-deployment-manager-bootstrap.adoc
  modules/installation-deployment-manager-control-plane.adoc
  modules/installation-deployment-manager-ext-lb.adoc
  modules/installation-deployment-manager-firewall-rules.adoc
  modules/installation-deployment-manager-iam-shared-vpc.adoc
  modules/installation-deployment-manager-int-lb.adoc
  modules/installation-deployment-manager-private-dns.adoc
  modules/installation-deployment-manager-vpc.adoc
  modules/installation-deployment-manager-worker.adoc
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/installation-uninstall-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.5, lgtm, size/XXL

#25210 BZ-1850350: Adding checks for stopped pods
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25165 Remove tech preview for odo debugging
  cli_reference/developer_cli_odo/debugging-applications-in-odo.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25237 Typo
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25254 BZ 1871886: Fixed typo
  modules/installation-special-config-kargs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25253 Remove PodSecurityPolicy from API reference
  _topic_map.yml
  api-map.yaml
  rest_api/index.adoc
  rest_api/objects/index.adoc
  rest_api/policy_apis/podsecuritypolicy-policy-v1beta1.adoc
  rest_api/policy_apis/policy-apis-index.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XXL

#25261 BZ1835172 storageClassName typo fixed
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#25064 Task migration from using Resources to using workspaces
  modules/op-about-pipelinerun.adoc
  modules/op-about-pipelines.adoc
  modules/op-about-taskrun.adoc
  modules/op-about-tasks.adoc
  modules/op-about-triggers.adoc
  modules/op-about-workspace.adoc
  modules/op-adding-triggers.adoc
  modules/op-assembling-a-pipeline.adoc
  modules/op-creating-pipeline-tasks.adoc
  modules/op-pipelines-concepts.adoc
  modules/op-release-notes-1-1.adoc
  modules/op-running-a-pipeline.adoc
  modules/op-specifying-pvc-as-volumesource-in-workspaces.adoc
  modules/op-triggering-a-pipelinerun.adoc
  pipelines/creating-applications-with-cicd-pipelines.adoc
  pipelines/understanding-openshift-pipelines.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25002 TRACING-895 Documenting autoscaling the Collector and Ingester.
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
Labels: size/L

#24173 BZ 1851760: cloning between volume modes
  virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-datavolume-block.adoc
  virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-datavolume.adoc
  virt/virtual_machines/cloning_vms/virt-cloning-vm-using-datavolumetemplate.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25156 Update cluster-logging-visualizer.adoc
  logging/viewing/cluster-logging-visualizer.adoc
Labels: branch/enterprise-4.5, size/XS

#25260 [enterprise-4.4] Remove PodSecurityPolicy from API reference
  _topic_map.yml
  api-map.yaml
  rest_api/index.adoc
  rest_api/objects/index.adoc
  rest_api/policy_apis/podsecuritypolicy-policy-v1beta1.adoc
  rest_api/policy_apis/policy-apis-index.adoc
Labels: branch/enterprise-4.4, size/XXL

#25102 CNV - BZ#1861297 removing timeout note/rel_not
  virt/virt-2-4-release-notes.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: CNV, size/M

#25045 CNV - updating 'HCOVersion' attribute
  modules/gathering-data-specific-features.adoc
  modules/virt-about-collecting-virt-data.adoc
  modules/virt-deleting-virt-cli.adoc
  modules/virt-document-attributes.adoc
  support/gathering-cluster-data.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25281 [enterprise-4.5] migration to workspace
  modules/op-about-pipelinerun.adoc
  modules/op-about-pipelines.adoc
  modules/op-about-taskrun.adoc
  modules/op-about-tasks.adoc
  modules/op-about-triggers.adoc
  modules/op-about-workspace.adoc
  modules/op-adding-triggers.adoc
  modules/op-assembling-a-pipeline.adoc
  modules/op-creating-pipeline-tasks.adoc
  modules/op-pipelines-concepts.adoc
  modules/op-release-notes-1-1.adoc
  modules/op-running-a-pipeline.adoc
  modules/op-specifying-pvc-as-volumesource-in-workspaces.adoc
  modules/op-triggering-a-pipelinerun.adoc
  pipelines/creating-applications-with-cicd-pipelines.adoc
  pipelines/understanding-openshift-pipelines.adoc
Labels: size/L

#25282 update preview files
  autocomment.sh
  autopreview.sh
Labels: size/XS

#25099 Converting S2I to devfiles procedure.
  _topic_map.yml
  cli_reference/developer_cli_odo/odo-release-notes.adoc
  cli_reference/developer_cli_odo/using-devfiles-in-odo.adoc
  modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#24845 Added Service Mesh + Serverless docs for 1.9.0
  _topic_map.yml
  serverless/networking/images
  serverless/networking/modules
  serverless/networking/serverless-ossm.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25107 Add group impersonation info
  authentication/impersonating-system-admin.adoc
  modules/impersonation-system-admin-group.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25113 Errata update for 4.5.8 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#25270 Removing source,terminal for now
  modules/backup-etcd.adoc
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#23615 [enterprise-4.3] Disconnected round two, with file system
  installing/install_config/installing-restricted-networks-preparations.adoc
  modules/installation-about-mirror-registry.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-mirror-repository.adoc
  modules/installation-performing-disconnected-mirror-without-registry.adoc
  modules/installation-performing-disconnected-mirror.adoc
  modules/installation-vsphere-config-yaml.adoc
Labels: size/L

#25144 addressing known issue BZ1829101 and adding information on workaround…
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#25044 [enterprise-4.6] Fix nodecount and ES memory per slack
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-configuring-node-selector.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: size/S

#24992 Known issue fixed in 4.5.8
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/XS

#25292 Rel Notes doc text for 4.4.20 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#25293 New deprecated warnings included with Kube 1.19
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#25047 BZ1872278 - Clarify vSphere Reg Storage RWO Docs
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/registry-configuring-storage-vsphere.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25312 Removing SRIOV ipam release note
  virt/virt-2-4-release-notes.adoc
Labels: CNV, size/XS

#25055 Updated link to kubeletconfig options
  modules/nodes-nodes-managing-about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#24995 OSDOCS-1224: Adding OAuth token format to migration planning doc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/XS

#25305 Small fix to clarify vm import prerequisite
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#24987 Fixed default limit/requests for fluentd
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-cpu-memory.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25290 Update odo commands output and remove outdated info.
  cli_reference/developer_cli_odo/understanding-odo.adoc
  modules/developer-cli-odo-creating-a-service-from-an-operator.adoc
  modules/developer-cli-odo-creating-services-from-yaml-files.adoc
  modules/developer-cli-odo-deploying-a-java-application-using-a-devfile.adoc
  modules/developer-cli-odo-deploying-the-back-end-component.adoc
  modules/developer-cli-odo-deploying-the-front-end-component.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-listing-available-devfile-components.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25227 Updating the guidance to remove the wordy version of installing CLI p…
  contributing_to_docs/term_glossary.adoc
Labels: Peer Review Done, size/XS

#16512 BZ-1748368: Adding details on optional vs required fields
  modules/identity-provider-github-CR.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/S

#25050 Remove tech preview statement for no worker deployments
  modules/nodes-nodes-working-master-schedulable.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25345 Fixing long oc install wording
  modules/nodes-cluster-disabling-features-cluster.adoc
  modules/update-upgrading-cli.adoc
Labels: size/XS

#25346 One more oc preq wording fix
  modules/update-upgrading-cli.adoc
Labels: size/XS

#25347 Fixing long oc install wording
  modules/nodes-cluster-disabling-features-cluster.adoc
  modules/update-upgrading-cli.adoc
Labels: size/XS

#25326 [enterprise-4.3] Fixed default limit/requests for fluentd
  modules/cluster-logging-collector-limits.adoc
Labels: size/XS

#25329 [enterprise-4.4] Fixed default limit/requests for fluentd
  modules/cluster-logging-collector-limits.adoc
Labels: size/XS

#25351 added dockerfile for prow
  Dockerfile
Labels: size/XS

#25209 Errata update for 4.3.35 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/M

#25353 Fix command typo
  modules/nodes-nodes-working-deleting-bare-metal.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25053 Changed install option to right namespace
  modules/cluster-logging-deploy-console.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/XS

#25124 Added 4.6 web console release notes for several items
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#24970 OSDOCS-1299 - Add Storage section to Troubleshooting guide
  _topic_map.yml
  modules/storage-multi-attach-error.adoc
  support/troubleshooting/troubleshooting-storage-issues.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#24942 Added web console column management to 4.6 release notes
  images/manage-columns.png
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#25224 Add sqlite search for subset image mirroring
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/M

#25367 Remove RHSA that never shipped
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#25147 CNV-5092 Guest agent information in the web console
  _topic_map.yml
  modules/virt-about-qemu-guest-agent-web.adoc
  modules/virt-viewing-qemu-guest-agent-information-web.adoc
  virt/virtual_machines/vm_networking/virt-viewing-qemu-guest-agent-web.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#24897 rhdevdocs 2092 event sources
  _topic_map.yml
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml.adoc
  modules/serverless-list-source-types-kn.adoc
  modules/serverless-list-source-types-odc.adoc
  modules/serverless-list-source.adoc
  modules/serverless-service-ac-event-sources.adoc
  serverless/event_sources/serverless-listing-event-sources.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#25375 BZ1873359 Changed example to foo: bar.
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#20461 cnv: maintenance: fix capitalization of LiveMigration
  modules/virt-setting-node-maintenance-cli.adoc
  modules/virt-setting-node-maintenance-web.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25364 [enterprise-4.4] Changed install option to right namespace
  modules/cluster-logging-deploy-console.adoc
Labels: size/XS

#21705 ES High Availability example in OpenShift documentation is wrong
  install_config/aggregate_logging.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#25311 CNV BZ#1859231 remove ipam from cnv sriov
  modules/nw-sriov-network-attachment.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25314 Added Scale section + Real-time profile for NTO notes to 4.6 release notes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#25046 Adding compute machines to vSphere/bare metal UPI environments
  _topic_map.yml
  installing/installing-fips.adoc
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
  machine_management/user_infra/adding-rhel-compute.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  machine_management/user_infra/more-rhel-compute.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
  modules/machine-vsphere-machines.adoc
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-ansible-parameters.adoc
  modules/rhel-compute-overview.adoc
  modules/rhel-compute-requirements.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
  modules/rhel-removing-rhcos.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#25361 [enterprise-4.5] Adding compute machines to vSphere/bare metal UPI environments
  _topic_map.yml
  installing/installing-fips.adoc
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
  machine_management/user_infra/adding-rhel-compute.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  machine_management/user_infra/more-rhel-compute.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
  modules/machine-vsphere-machines.adoc
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-ansible-parameters.adoc
  modules/rhel-compute-overview.adoc
  modules/rhel-compute-requirements.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
  modules/rhel-removing-rhcos.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#25390 [enterprise-4.4] Adding compute machines to vSphere/bare metal UPI environments
  _topic_map.yml
  installing/installing-fips.adoc
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
  machine_management/user_infra/adding-rhel-compute.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  machine_management/user_infra/more-rhel-compute.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
  modules/machine-vsphere-machines.adoc
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-ansible-parameters.adoc
  modules/rhel-compute-overview.adoc
  modules/rhel-compute-requirements.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
  modules/rhel-removing-rhcos.adoc
Labels: branch/enterprise-4.4, size/L

#25391 [enterprise-4.3] Adding compute machines to vSphere/bare metal UPI environments
  _topic_map.yml
  installing/installing-fips.adoc
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
  machine_management/user_infra/adding-rhel-compute.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  machine_management/user_infra/more-rhel-compute.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
  modules/machine-vsphere-machines.adoc
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-ansible-parameters.adoc
  modules/rhel-compute-overview.adoc
  modules/rhel-compute-requirements.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
  modules/rhel-removing-rhcos.adoc
Labels: branch/enterprise-4.3, size/L

#25396 Fix typo
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-default.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_aws/installing-aws-private.adoc
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-customizations.adoc
  installing/installing_azure/installing-azure-default.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure/installing-azure-private.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure/installing-azure-vnet.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-default.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25348 BZ1876886 - Add EBS max vol note
  modules/storage-persistent-storage-aws-maximum-volumes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25407 [enterprise-4.3] Fix typo
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-default.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_aws/installing-aws-private.adoc
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-customizations.adoc
  installing/installing_azure/installing-azure-default.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure/installing-azure-private.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure/installing-azure-vnet.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-default.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
Labels: branch/enterprise-4.3, size/M

#25406 [enterprise-4.4] Fix typo
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-default.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_aws/installing-aws-private.adoc
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-customizations.adoc
  installing/installing_azure/installing-azure-default.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure/installing-azure-private.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure/installing-azure-vnet.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-default.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
Labels: branch/enterprise-4.4, size/M

#25176 Adding missing information on AWS Spot Instances
  machine_management/creating-infrastructure-machinesets.adoc
  modules/machineset-non-guaranteed-instance.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#24850 Add ingress config next step to OSP install docs
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-user-kuryr.adoc
  installing/installing_openstack/installing-openstack-user.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25411 Remove KUBE_MAX_PD_VOLS variable in 4.4
  modules/storage-persistent-storage-aws-maximum-volumes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#25413 Remove KUBE_MAX_PD_VOLS variable in 4.3
  modules/storage-persistent-storage-aws-maximum-volumes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/S

#25418 [enterprise-4.3] Add ingress config next step to OSP install docs
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#25323 RHV version support update for OCP 4.6+
  modules/installing-rhv-requirements.adoc
Labels: branch/enterprise-4.6, size/XS

#24969 Updates to the Uninstalling metering documentation
  metering/metering-uninstall.adoc
  metering/reports/metering-storage-locations.adoc
  modules/metering-reports.adoc
  modules/metering-uninstall-crds.adoc
  modules/metering-uninstall.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25296 Updated formatting and minor edits for Serverless ApiServerSource docs
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  serverless/event_sources/serverless-apiserversource.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25432 Updated formatting and minor edits for ApiServerSource docs
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  serverless/event_sources/serverless-apiserversource.adoc
Labels: size/L

#25431 Updated formatting and minor edits for ApiServerSource docs
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  serverless/event_sources/serverless-apiserversource.adoc
Labels: size/L

#24778 BZ1856186 - Add manual reclaim procedure to 3.11 docs
  architecture/additional_concepts/storage.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#24776 BZ1856186 - Add manual reclaim procedure to 4.x docs
  modules/storage-persistent-storage-reclaim-manual.adoc
  storage/understanding-persistent-storage.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25048 Bug 1821771: Adding known issue and workaround with unauthenticated a…
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, bugzilla/invalid-bug, bugzilla/severity-high, lgtm, size/M

#25134 Same MTC version on 3 and 4 clusters
  modules/common-attributes.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-known-issues.adoc
  modules/migration-upgrading-migration-tool.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25386 Update Configuring your firewall section
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25414 Errata update for 4.5.9 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#25449 BZ1878627 Removed duplicate warning.
  modules/installation-adding-registry-pull-secret.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#24579 After installation infra and audit index pattern not available in Kibana
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-external.adoc
  logging/cluster-logging-upgrading.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/viewing/cluster-logging-visualizer.adoc
  modules/cluster-logging-collector-log-forward.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-visualizer-indices.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#25430 Updated image to latest
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  serverless/event_sources/serverless-listing-event-sources.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/S

#25453 [enterprise-4.5] After installation infra and audit index pattern not available in Kibana
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-external.adoc
  logging/cluster-logging-upgrading.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/viewing/cluster-logging-visualizer.adoc
  modules/cluster-logging-collector-log-forward.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-visualizer-indices.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: size/L

#24804 Add release note for Kibana link moved
  release_notes/ocp-4-5-release-notes.adoc
Labels: size/XS

#25394 Minor updates to Optimizing storage section
  modules/recommended-configurable-storage-technology.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25457 Azure UPI VHD URL version typo
  modules/installation-azure-user-infra-uploading-rhcos.adoc
Labels: branch/enterprise-4.5, size/XS

#25464 Fix typo
  modules/images-imagestream-import.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25469 Remove unnecessary shell continuation
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/XS

#23948 Wrong documentation on Audit Log procedures
  install_config/master_node_configuration.adoc
Labels: size/M

#25350 Fix spec.template.metadata.annotations for min and max scale example
  modules/configuring-scale-bounds-knative.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25232 logging-fluentd ConfigMap is overwritten during logging stack upgrades
  install_config/aggregate_logging.adoc
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#25448 [OSP] Remove duplicative statement from resource requirements
  modules/installation-osp-default-kuryr-deployment.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25101 issue #25065 - clarify SNI requirement
  modules/installation-network-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25474 Update migration 'must-gather' tool module
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/common-attributes.adoc
  modules/gathering-data-for-a-customer-support-case.adoc
  modules/migration-using-must-gather.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25398 Add command line block for command line
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/XS

#25385 CNV - JIRA story CNV-4333 Adding fslist, guestosinfo, and userlist commands to ands to Virtctl commands table in Virtual client commands subsection of Using the CLI tools section
  modules/virt-virtctl-commands.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#25219 Updated OCS section of 'Persistent storage using Red Hat OpenShift Co…
  storage/persistent_storage/persistent-storage-ocs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#25092 Improve documentation on recommendations to manage settings when using cgroup-driver systemd
  admin_guide/allocating_node_resources.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#22718 OCPRHV-57-customization [enterprise-4.5][enterprise-4.6]
  contributing_to_docs/term_glossary.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installing-rhv-config-yaml.adoc
  modules/installing-rhv-requirements.adoc
  modules/proxy-certificates.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XL

#25497 Pr to cherry pick ##25398 into 4.3 branch.
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/XS

#25498 Pr to cherry pick ##25398 into 4.4 branch.
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/XS

#25374 Updates to Architecture book code blocks
  architecture/additional_concepts/authentication.adoc
  architecture/additional_concepts/authorization.adoc
  architecture/additional_concepts/dynamic_admission_controllers.adoc
  architecture/additional_concepts/ephemeral-storage.adoc
  architecture/additional_concepts/other_api_objects.adoc
  architecture/additional_concepts/storage.adoc
  architecture/core_concepts/builds_and_image_streams.adoc
  architecture/core_concepts/deployments.adoc
  architecture/core_concepts/pods_and_services.adoc
  architecture/core_concepts/projects_and_users.adoc
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  architecture/infrastructure_components/web_console.adoc
  architecture/networking/routes.adoc
  architecture/service_catalog/aws_broker.adoc
  architecture/service_catalog/index.adoc
  architecture/service_catalog/service_catalog_cli.adoc
  architecture/topics/flannel.adoc
  architecture/topics/openshift_dns.adoc
  architecture/topics/packet_flow.adoc
  architecture/topics/router_environment_variables.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#25499 Second half of updates for #25398
  service_mesh/service_mesh_install/updating-ossm.adoc
Labels: size/XS

#25433 Rel Notes doc text for 4.4.21 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#25451 Add Helm chart workaround to 4.6 known issues
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#25501 OCPRHV-374 add a note pointing people to kcs letting people know abou… [enterprise-4.5]
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#25420 Rel Notes doc text for 3.11.285 release
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#25506 Fixed bug in OCP 4.5 install docs
  modules/serverless-install-web-console.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#25341 Replacing the Event Router docs
  _topic_map.yml
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-about-eventrouter.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25511 Removing CAUTION notices as they are not supported on the portal
  modules/identity-provider-about-basic-authentication.adoc
  modules/installation-osp-creating-image.adoc
  modules/installation-osp-verifying-external-network.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-externalip-about.adoc
  modules/pruning-images-manual.adoc
  modules/virt-deploying-virt.adoc
  modules/virt-uploading-local-disk-image-pvc.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes-block.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25510 update --cluster-name flag
  getting_started_moa/creating-first-moa-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#25518 Removing CAUTION notices as they are not supported on the portal
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes-block.adoc
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes.adoc
  modules/cnv-deploying-cnv.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/installation-osp-creating-image.adoc
  modules/installation-osp-verifying-external-network.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-externalip-about.adoc
  modules/pruning-images-manual.adoc
Labels: size/S

#25520 Removing CAUTION notices as they are not supported on the portal
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes-block.adoc
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-virtual-machine-images-datavolumes.adoc
  modules/cnv-deploying-cnv.adoc
  modules/cnv-uploading-local-disk-image-dv.adoc
  modules/cnv-uploading-local-disk-image-pvc.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/installation-osp-verifying-external-network.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-externalip-about.adoc
  modules/pruning-images.adoc
Labels: size/S

#25519 moa remove machine config section
  _topic_map.yml
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#25523 Update moa quickstart quota, logs, and moactl login
  getting_started_moa/creating-first-moa-cluster.adoc
  modules/moa-creating-cluster.adoc
  modules/moa-installing-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/S
