Repository openshift/openshift-docs, pull requests merged in 2020-06, with the labels that each got.

#22434 Removing 1.4.0 specific upgrade section from Serverless docs
  modules/serverless-update-api-group.adoc
  serverless/installing_serverless/upgrading-serverless.adoc
Labels: branch/enterprise-4.3

#22316 Add kuryr information about global namespaces
  install_config/topics/ocp_osp_provisioning.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#22507 Two new CSI drivers in TP
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22343 Installing CAM in restricted environment
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/configuring-replication-repository-3-4.adoc
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/deploying_cam.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/deploying_cam.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/deploying_cam.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-restic-errors.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-using-cpma.adoc
  modules/migration-viewing-migration-crs.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22393 Health checks flow
  applications/application-health.adoc
  images/odc_import_from_git.png
  modules/application-health-configuring.adoc
  modules/odc-adding-health-checks.adoc
  modules/odc-editing-health-checks.adoc
  modules/odc-importing-codebase-from-git-to-create-application.adoc
  modules/odc-monitoring-application-health-using-developer-perspective.adoc
  modules/odc-monitoring-health-checks.adoc
Labels: Peer Review Done, branch/enterprise-4.5, lgtm

#22535 Use unique context for SR-IOV assemblies
  networking/hardware_networks/configuring-sriov-net-attach.adoc
  networking/hardware_networks/configuring-sriov-operator.adoc
  networking/hardware_networks/installing-sriov-operator.adoc
  networking/hardware_networks/using-dpdk-and-rdma.adoc
  networking/hardware_networks/using-sriov-multicast.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22508 Update PTP Operator installation
  modules/nw-ptp-installing-operator.adoc
  networking/multiple_networks/configuring-ptp.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#20705 OSASINFRA-1352: OpenStack: remove pin on Ansible 2.5
  install_config/topics/ocp_osp_prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#22545 [enterprise-4.2] restricted installation 4.2
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/configuring-replication-repository-3-4.adoc
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/deploying_cam.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/deploying_cam.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/deploying_cam.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4_2-to-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-restic-errors.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-using-cpma.adoc
  modules/migration-viewing-migration-crs.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: branch/enterprise-4.2

#22542 [enterprise-4.3] Restricted install 4.3
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/configuring-replication-repository-3-4.adoc
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/deploying_cam.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/deploying_cam.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/deploying_cam.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-restic-errors.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-using-cpma.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: branch/enterprise-4.3

#22537 [enterprise-4.4] Restricted install 4.4
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/configuring-replication-repository-3-4.adoc
  migration/migrating_3_4/configuring-replication-repository.adoc
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/deploying_cam.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/deploying_cam.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/deploying_cam.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-restic-errors.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-using-cpma.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: branch/enterprise-4.4

#22525 Bugzilla doc text for 4.4.6 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#22443 Added an admonition in persistent storage glusterfs using the install…
  install_config/persistent_storage/persistent_storage_glusterfs.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#22568 BZ1789293- Fix pronoun typo
  modules/ossm-control-plane-templates.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22556 Updated log retention time for Dedicated
  logging/cluster-logging.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, lgtm

#22341 Changed storageClassName gp2 to storage-class-name
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/dedicated-cluster-install-deploy.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22445 Errata update for 4.3.23 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#22579 Clarifying the behavior of the etcd operator
  backup_and_restore/replacing-unhealthy-etcd-member.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22517 Fix typo and cleanup
  modules/images-create-metadata.adoc
  openshift_images/create-images.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22600 Cancel a migration in progress
  modules/migration-running-migration-plan-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22588 Bugzilla doc text for 4.2.34 release
  release_notes/ocp-4-2-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.2

#22483 changed the recommendation to check the Kbase article
  install_config/persistent_storage/topics/glusterfs_overview_block_volumes.adoc
Labels: Peer Review Done, branch/enterprise-3.11

#22139 BZ1782386 - Clarify vSphere infra reqs in OCP 4.2
  modules/installation-vsphere-infrastructure.adoc
Labels: Peer Review Needed, branch/enterprise-4.2

#22598 CAM 1.2 not installing on OCP 3.x
  modules/migration-known-issues.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22565 OSDOCS-743: Release notes for auto control plane cert recovery
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22564 Replace manual cert recovery with automated one
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22452 [release-4.5] Remove unsupportedConfigOverrides from documentation
  applications/quotas/quotas-setting-per-project.adoc
  modules/quotas-configuring-quota-sync-period.adoc
Labels: branch/enterprise-4.5

#22453 [release-4.4] Remove unsupportedConfigOverrides from documentation
  applications/quotas/quotas-setting-per-project.adoc
  modules/quotas-configuring-quota-sync-period.adoc
Labels: branch/enterprise-4.4

#22454 [release-4.3] Remove unsupportedConfigOverrides from documentation
  applications/quotas/quotas-setting-per-project.adoc
  modules/quotas-configuring-quota-sync-period.adoc
Labels: branch/enterprise-4.3

#22455 [release-4.2] Remove unsupportedConfigOverrides from documentation
  applications/quotas/quotas-setting-per-project.adoc
  modules/quotas-configuring-quota-sync-period.adoc
Labels: branch/enterprise-4.2

#22555 remove cors from 4.2
  modules/migration-configuring-cors-3.adoc
  modules/migration-configuring-cors-4.adoc
Labels: Peer Review Done, branch/enterprise-4.2

#22582 Fix example how to disable registry cache
  install_config/registry/extended_registry_configuration.adoc
Labels: branch/enterprise-3.11

#19866 bug 1803979 updating vSphere requirements
  modules/installation-vsphere-infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, size/S

#22619 OSDOCS-1043: Updating migration planning docs to version 4.5
  migration/migrating_3_4/planning-migration-3-to-4.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22554 Add additional resource to IBM Z install section
  installing/installing_ibm_z/installing-ibm-z.adoc
Labels: Peer Review Done, branch/enterprise-4.2

#22592 Do not use emphasis in conjunction with code font
  _unused_topics/nodes-containers-using-ssh.adoc
  modules/images-test-s2i.adoc
  modules/nodes-containers-downward-api-container-resources-envars.adoc
  modules/nodes-containers-downward-api-container-values-envars.adoc
  modules/nodes-containers-events-list.adoc
  modules/nodes-nodes-garbage-collection-images.adoc
  modules/nodes-nodes-rebooting-affinity.adoc
  modules/nodes-nodes-rebooting-router.adoc
  modules/nodes-nodes-resources-configuring-setting.adoc
  modules/nodes-pods-daemonsets-creating.adoc
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/nodes-pods-secrets-updating.adoc
  modules/nodes-pods-using-example.adoc
  modules/nodes-scheduler-default-priorities.adoc
  modules/persistent-storage-cinder-creating-pv.adoc
  modules/persistent-storage-cinder-pv-format.adoc
  modules/persistent-storage-cinder-volume-security.adoc
  modules/security-context-constraints-creating.adoc
  modules/service-accounts-enabling-authentication.adoc
  modules/storage-persistent-storage-nfs-provisioning.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22596 [enterprise-4.2] Fix typo and cleanup
  modules/images-create-metadata.adoc
  openshift_images/create-images.adoc
Labels: branch/enterprise-4.2

#22526 Add TP for PTP
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22637 Manually adding links from PR22554
  installing/installing_ibm_z/installing-ibm-z.adoc
Labels: branch/enterprise-4.2

#21908 Virt: VMware import troubleshooting section
  modules/virt-importing-vmware-vm.adoc
  modules/virt-troubleshooting-vmware-vm-import.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22289 Update oc installation to include instructions by OS
  modules/cli-installing-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, lgtm

#22523 OSDOCS-1082: Updating Kubernetes version in example output
  _unused_topics/looking-inside-nodes.adoc
  _unused_topics/understanding-workers-masters.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/rhel-compute-updating.adoc
Labels: Peer Review Done, branch/enterprise-4.5, lgtm

#22650 CNV: troubleshooting for VMware VM import
  cnv/cnv_virtual_machines/cnv_importing_vms/cnv-importing-vmware-vm.adoc
  modules/cnv-troubleshooting-vmware-vm-import.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4

#22647 Updated master node sizing for 4.4
  modules/master-node-sizing.adoc
Labels: branch/enterprise-4.4, lgtm

#22433 OSDOCS-945: Updating references to oc flags that were removed
  modules/applications-create-using-cli-image.adoc
  modules/deployments-lifecycle-hooks.adoc
  modules/nodes-containers-volumes-cli.adoc
  modules/nodes-containers-volumes-listing.adoc
Labels: Peer Review Done, branch/enterprise-4.5, lgtm

#22658 Updated master node sizing
  modules/master-node-sizing.adoc
Labels: branch/enterprise-4.5

#22664 Updates for OCS 4.4 docs
  modules/dynamic-provisioning-ocs-object-definition.adoc
  modules/storage-persistent-storage-pv.adoc
  storage/dynamic-provisioning.adoc
  storage/persistent_storage/persistent-storage-ocs.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#20997 Doc changes for OCS 4.3
  modules/dynamic-provisioning-ocs-object-definition.adoc
  modules/storage-persistent-storage-pv.adoc
  storage/dynamic-provisioning.adoc
Labels: Peer Review Done, branch/enterprise-4.3

#22665 Azure UPI - using one NSG instead of two
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-azure-user-infra-wait-for-bootstrap.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22476 Pipelines in odc
  _topic_map.yml
  images/op-pipeline-builder-task-details.png
  images/op-pipeline-builder.png
  images/op_pipeline_run.png
  images/op_pipeline_topology.png
  modules/odc-importing-codebase-from-git-to-create-application.adoc
  modules/op-about-tasks.adoc
  modules/op-about-triggers.adoc
  modules/op-adding-triggers.adoc
  modules/op-assembling-a-pipeline.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-creating-pipeline-tasks.adoc
  modules/op-creating-project-and-checking-pipeline-service-account.adoc
  modules/op-creating-webhooks.adoc
  modules/op-defining-and-creating-pipelineresources.adoc
  modules/op-deleting-pipelines.adoc
  modules/op-editing-pipelines.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-pipelines-concepts.adoc
  modules/op-running-a-pipeline.adoc
  modules/op-starting-pipelines.adoc
  modules/op-triggering-a-pipelinerun.adoc
  pipelines/creating-applications-with-cicd-pipelines.adoc
  pipelines/working-with-pipelines-using-the-developer-perspective.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22667 Terminology changes from Gowrishankar Rajaiyan and Sebastian Scheinkman.
  modules/cnf-installing-the-performance-addon-operator.adoc
  openshift_images/cnf-building-and-deploying-a-dpdk-payload.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5

#22670 Re-add deleted topicmap entry
  _topic_map.yml
Labels: branch/enterprise-4.4, branch/enterprise-4.5

#22543 Odo operators services
  _topic_map.yml
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  modules/developer-cli-odo-creating-a-service-from-an-operator.adoc
  modules/developer-cli-odo-creating-services-from-yaml-files.adoc
  modules/developer-cli-odo-listing-available-services-from-the-operators-installed-on-the-cluster.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5

#22518 OCPRHV-81-4.5 Add chmod/perm information for CA cert [enterprise-4.4][enterprise-4.5]
  modules/installing-rhv-setting-up-ca-certificate.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22674 Small bug fix for Serverless install docs
  modules/serverless-install-web-console.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#21744 Odo correction for no additional server in understanding docs
  cli_reference/developer_cli_odo/understanding-odo.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22608 Change v1alpha1 to v1 in Serverless docs code samples
  modules/knative-serving-concurrent-autoscaling-requests.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22678 Remove long standing GA features in RNs
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#22625 Add --filter-by-os for catalog build + mirror
  modules/olm-arch-os-support.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-enabling-operator-for-multi-arch.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
  operators/olm-restricted-networks.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, lgtm

#22516 [enterprise-4.2] Nodejs version change
  modules/images-other-jenkins-agent-images.adoc
  openshift_images/using_images/images-other-jenkins-agent.adoc
Labels: branch/enterprise-4.2

#22597 Add known issues about intermittent connectivity
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22723 Connectivity known issue fixup
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#21746 Remove RHV installing-rhv-creating-custom-vm.adoc [branch/enterprise-4.4] [branch/enterprise-4.5]
  _topic_map.yml
  installing/installing_rhv/installing-rhv-creating-custom-vm.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-launching-installer.adoc
  modules/installing-rhv-attaching-virt-disk-to-vm.adoc
  modules/installing-rhv-configuring-and-creating-the-vm.adoc
  modules/installing-rhv-creating-vm-template.adoc
  modules/installing-rhv-downloading-rhcos-image.adoc
  modules/installing-rhv-export-some-environment-variables.adoc
  modules/installing-rhv-using-ansible-playbook.adoc
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22475 Added 4.5 cluster maximums
  modules/openshift-cluster-maximums.adoc
Labels: branch/enterprise-4.5

#22154 Placing 4.5 ingress certificate workflow diagrams
  authentication/certificate-types-descriptions.adoc
  images/custom_4.5.png
  images/darkcircle-11.png
  images/darkcircle-12.png
  images/default_4.5.png
Labels: branch/enterprise-4.5, lgtm

#22744 Remove "Using" from CSI titles
  _topic_map.yml
  storage/container_storage_interface/ephemeral-storage-csi-inline.adoc
  storage/container_storage_interface/persistent-storage-csi-cloning.adoc
  storage/container_storage_interface/persistent-storage-csi-snapshots.adoc
Labels: Peer Review Needed, branch/enterprise-4.5

#22520 KI and Manual Workaround for Buildah ClusterTask in Pipelines 1.0
  modules/op-release-notes-1-0.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22757 Remove 4.6 content from 4.5 RN
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#22760 Remove long standing dropped features from RNs
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22201 Removing separate log forward topic not needed since PR-22196
  _topic_map.yml
  logging/config/cluster-logging-log-forwarding.adoc
  modules/cluster-logging-log-forwarding-about.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
Labels: area/dependency, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22766 Related image block is defined to use image as the key
  modules/olm-enabling-operator-restricted-network.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#21987 LogForwarding endpoint must be an node name or FQDN, not an IP Address
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-log-forwarding-about.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22511 Apply feedback to SR-IOV related documentation 1/3
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
  modules/nw-multus-add-pod.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-sriov-add-pod-runtimeconfig.adoc
  modules/nw-sriov-configuring-device.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22721 [enterprise-4.4] Add known issues about intermittent connectivity
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#22722 [enterprise-4.3] Add known issues about intermittent connectivity
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3

#22778 Fixing a few build errors
  authentication/certificate-types-descriptions.adoc
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  modules/cluster-logging-deploy-cli.adoc
  scalability_and_performance/using-topology-manager.adoc
  serverless/serverless-tracing.adoc
  service_mesh/service_mesh_user_guide/images
  service_mesh/service_mesh_user_guide/modules
Labels: Peer Review Done, branch/enterprise-4.5

#22734 Added another item to the list of information Insights Operator collects
  modules/insights-operator-what-information-is-collected.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#21488 Add information about octavia upgrades impact on Kuryr SDN
  modules/installation-osp-kuryr-known-limitations.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22785 BZ1842514 - Default volumesnapshotclass is not supported in 4.5+
  modules/persistent-storage-csi-snapshots-create.adoc
Labels: Peer Review Needed, branch/enterprise-4.5

#22720 BZ1842514 - Default volumesnapshotclass is not supported in 4.4
  modules/persistent-storage-csi-snapshots-create.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#22510 RN 4.5 additions for nodeAffinity and known issue
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22794 Fix callout numbering
  modules/persistent-storage-csi-snapshots-create.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22417 sriov: update notes for mellanox dpdk
  modules/nw-sriov-configuring-device.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22362 OSDOCS-847 document custom build strategy change for node pull secrets
  builds/creating-build-inputs.adoc
  modules/builds-custom-strategy.adoc
  modules/nodes-pods-secrets-creating.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22844 Fix invalid attribute
  modules/jaeger-config-storage.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5

#22709 Update ancient SCL reference
  modules/templates-creating-from-console.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#21753 Do not use deprecated asciidoctor footnote syntax
  modules/available-persistent-storage-options.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22861 [enterprise-4.2] Do not use deprecated asciidoctor footnote syntax
  modules/available-persistent-storage-options.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.2

#22862 [enterprise-4.4] Do not use deprecated asciidoctor footnote syntax
  modules/available-persistent-storage-options.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.4

#22863 [enterprise-4.5] Do not use deprecated asciidoctor footnote syntax
  modules/available-persistent-storage-options.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.5

#22864 [enterprise-4.4] Do not use deprecated asciidoctor footnote syntax
  release_notes/versioning-policy.adoc
Labels: branch/enterprise-4.4

#22865 [enterprise-3.11] Do not use deprecated asciidoctor footnote syntax
  architecture/index.adoc
  release_notes/index.adoc
  release_notes/ocp_3_10_release_notes.adoc
  release_notes/ocp_3_11_release_notes.adoc
  release_notes/ocp_3_9_release_notes.adoc
  scaling_performance/cluster_maximums.adoc
  scaling_performance/optimizing_storage.adoc
Labels: branch/enterprise-3.11

#22877 Virt registry update
  modules/virt-creating-vddk-image.adoc
  modules/virt-downloading-vddk.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22788 BZ-1691019: Adding additional notes about concatenating files for cer…
  install_config/certificate_customization.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm

#22786 Fix note to match source code
  admin_guide/garbage_collection.adoc
Labels: branch/enterprise-3.11

#22577 CRIO Termination Grace Period Support
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#22756 Follow up to Topology Manager PR
  modules/setting-up-cpu-manager.adoc
  modules/setting-up-topology-manager.adoc
  modules/topology-manager-policies.adoc
  scalability_and_performance/using-cpu-manager.adoc
  scalability_and_performance/using-topology-manager.adoc
Labels: branch/enterprise-4.5

#22747 OSDOCS-1017 Release Notes 4.5 - Storage
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22019 BZ1701038 - Adding OpenShift 4 admission controller document.
  _topic_map.yml
  architecture/admission-plug-ins.adoc
  images/api-admission-chain.png
  modules/admission-plug-ins-about.adoc
  modules/admission-plug-ins-default.adoc
  modules/admission-webhook-types.adoc
  modules/admission-webhooks-about.adoc
  modules/configuring-dynamic-admission.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22905 [enterprise-4.5] Replace deprecated footnote syntax
  release_notes/versioning-policy.adoc
Labels: branch/enterprise-4.5

#22906 [enterprise-4.3] Replace deprecated footnote syntax
  release_notes/versioning-policy.adoc
Labels: branch/enterprise-4.3

#22907 [enterprise-4.2] Replace deprecated footnote syntax
  modules/openshift-cluster-maximums-environment.adoc
  release_notes/ocp-4-1-release-notes.adoc
  release_notes/ocp-4-2-release-notes.adoc
  release_notes/versioning-policy.adoc
Labels: branch/enterprise-4.2

#22909 [enterprise-4.5] Remove unnecessary extra line
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#22915 Migration between same cluster versions
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
Labels: Peer Review Needed, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22326 Document enhancement for using targetAverageUtilization in autoscaling
  modules/nodes-pods-autoscaling-creating-memory.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22894 bz1846644 updated k8s_status procedures
  modules/osdk-ansible-custom-resource-files.adoc
  modules/osdk-ansible-managing-cr-status.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22928 Migration later versions
  _topic_map.yml
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22367 CNV-3703 Virtual Machine Instances 4.5 Release
  _topic_map.yml
  modules/virt-about-vmis.adoc
  modules/virt-deleting-vmi.adoc
  modules/virt-deleting-vmis-cli.adoc
  modules/virt-deleting-vmis-web.adoc
  modules/virt-editing-vmis-web.adoc
  modules/virt-listing-vmis-cli.adoc
  modules/virt-listing-vmis-web.adoc
  modules/virt-listing-vmis.adoc
  virt/install/uninstalling-virt.adoc
  virt/virtual_machines/virt-deleting-vmis.adoc
  virt/virtual_machines/virt-manage-vmis.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22783 SDK updates to release notes
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5

#22941 s/footnoteref/footnote/g
  _unused_topics/security-overview.adoc
  modules/available-persistent-storage-options.adoc
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22945 s/footnoteref/footnote/g
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/openshift-cluster-maximums-environment.adoc
  modules/openshift-cluster-maximums-major-releases.adoc
  modules/openshift-cluster-maximums.adoc
  modules/recommended-configurable-storage-technology.adoc
  modules/security-overview.adoc
  release_notes/ocp-4-1-release-notes.adoc
  release_notes/ocp-4-2-release-notes.adoc
  release_notes/versioning-policy.adoc
Labels: branch/enterprise-4.2

#22940 BZ#1846817 Recommend uninstallation procedure to remove clusters
  modules/installation-obtaining-installer.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22939 BZ1846651 removing duplicated steps
  modules/persistent-storage-local-install.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22958 minor fix of step numbers
  modules/ssh-agent-using.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22903 Remove typo in code block
  modules/images-configuration-registry-mirror.adoc
Labels: branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22780 Removed 4.4 imagestreamtags list
  modules/migration-prerequisites.adoc
Labels: Peer Review Needed, branch/enterprise-4.2, branch/enterprise-4.3

#22735 Update CAM installation for 4.4
  modules/migration-installing-cam-operator-ocp-4.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22967 Small fix to 'oc convert' for deprecated GVKs
  modules/migration-updating-deprecated-gvks.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22551 BZ-1691204: Adding note that it is unsupported to use unsupportedConf…
  updating/updating-cluster-between-minor.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, lgtm

#22938 Bug 1846523, stated that guidance is not for bare metal installations
  scalability_and_performance/recommended-cluster-scaling-practices.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, lgtm

#22853 Hugepages allocation at boot time, rather than run time.
  modules/configuring-huge-pages.adoc
  modules/how-huge-pages-are-consumed-by-apps.adoc
Labels: branch/enterprise-4.5

#22885 BZ#1843056 RHEL supported versions for OCP 4.4
  modules/rhel-compute-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.4

#22930 BZ#1843056 RHEL supported versions for OCP 4.5
  modules/rhel-compute-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22652 Errata update for 4.4.8 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4

#22996 Fixing typos to kick off a build
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/op-installing-pipelines-operator-in-web-console.adoc
  modules/topology-manager-policies.adoc
  service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: branch/enterprise-4.5

#22997 Fixing typos
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/op-installing-pipelines-operator-in-web-console.adoc
  release_notes/ocp-4-4-release-notes.adoc
  service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc
Labels: branch/enterprise-4.4

#22998 Fixing typos to kick off a build
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/op-installing-pipelines-operator-in-web-console.adoc
  modules/topology-manager-policies.adoc
  service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: branch/enterprise-4.5

#22999 Fixing typos for 4.3
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc
Labels: branch/enterprise-4.3

#23000 Fixing typos for 4.2
  modules/installation-creating-aws-bootstrap.adoc
  service_mesh/service_mesh_user_guide/ossm-traffic-manage.adoc
Labels: branch/enterprise-4.2

#22765 BZ-1845226: Updating the output for the etcd cluster operator's status
  modules/restore-identify-unhealthy-etcd-member.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22929 Migration upgrade source clusters
  modules/migration-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22924 Bugzilla doc text for 4.3.25 release
  release_notes/ocp-4-3-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.3

#22821 Errata update for 3.11.232 release
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11

#22807 Bug 1842431: backup_and_restore: clarify backup process
  backup_and_restore/backing-up-etcd.adoc
  modules/backup-etcd.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, bugzilla/severity-high, bugzilla/valid-bug

#22428 Logging 4.5 Documentation Issues
  _topic_map.yml
  _unused_topics/cluster-logging-collector-log-rotation.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging-troubleshooting.adoc
  logging/cluster-logging-viewing.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring-about.adoc
  logging/config/cluster-logging-configuring.adoc
  modules/cluster-logging-about-collector.adoc
  modules/cluster-logging-about-elasticsearch.adoc
  modules/cluster-logging-about-kibana.adoc
  modules/cluster-logging-collector-envvar.adoc
  modules/cluster-logging-collector-log-location.adoc
  modules/cluster-logging-collector-pod-location.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-status-comp.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-kibana-interface-launch.adoc
  modules/cluster-logging-troubleshooting-loop.adoc
  modules/cluster-logging-viewing-logs.adoc
  modules/common-attributes.adoc
Labels: branch/enterprise-4.5

#23008 CAM 1.2 (OCP 4.4+) uses "migration-controller" SA
  modules/migration-adding-cluster-to-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#22912 virt: update vddk registry procedures
  modules/configmap-adding-ca.adoc
  modules/images-allow-pods-to-reference-images-from-secure-registries.adoc
  modules/registry-accessing-directly.adoc
  modules/registry-change-management-state.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/virt-creating-vddk-image.adoc
  modules/virt-downloading-vddk.adoc
  modules/virt-importing-vmware-vm.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#22828 Updated Operator uninstallation procedure for 4.2
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
Labels: branch/enterprise-4.2

#22803 Bug 1845968, removed mention of check box
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22297 Correct spec.maturity definition and add spec.capabilities
  modules/osdk-manually-defined-csv-fields.adoc
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#22697 Updated images in Serverless examples
  modules/creating-serverless-apps-kn.adoc
  modules/creating-serverless-apps-yaml.adoc
  modules/interacting-serverless-apps-http2-gRPC.adoc
  modules/serverless-apps-intro.adoc
  modules/serverless-workflow-basic.adoc
  modules/verifying-serverless-app-deployment.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#20755 Add migration procedure for OpenShift SDN [4.5]
  _topic_map.yml
  modules/nw-ovn-kubernetes-migration.adoc
  modules/nw-ovn-kubernetes-rollback.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
  networking/ovn_kubernetes_network_provider/rollback-to-openshift-sdn.adoc
Labels: Peer Review Done, branch/enterprise-4.5

#23033 Re-add deleted topicmap entry
  _topic_map.yml
Labels: Peer Review Done, branch/enterprise-4.4

#22669 Add feature list and table for OVN-Kubernetes
  modules/nw-ovn-kubernetes-features.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  modules/nw-ovn-kubernetes-metrics.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5

#19047 [DDF] Addresses BZ1789244, BZ1789250, and BZ1789251.
  modules/ossm-control-plane-deploy.adoc
  modules/ossm-cr-example.adoc
Labels: size/L

#23044 Fixup commit for OVN-Kubernetes
  modules/nw-ovn-kubernetes-features.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  modules/nw-ovn-kubernetes-metrics.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
  virt/about-virt.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5

#23052 Fixup commit for OVN-Kubernetes
  modules/nw-ovn-kubernetes-features.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  modules/nw-ovn-kubernetes-metrics.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: branch/enterprise-4.4

#23007 Quay URL for configuring firewall
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5

#20560 4.5 Refactor CLO to generate Kibana resource instead of managing Kibana deployment
  logging/config/cluster-logging-kibana.adoc
  modules/cluster-logging-management-state-changing-es.adoc
  modules/cluster-logging-management-state-changing.adoc
Labels: branch/enterprise-4.5

#23045 Fix indentation per bug
  modules/osdk-ansible-managing-cr-status.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5
