Repository openshift/openshift-docs, pull requests merged in 2020-10, with the labels that each got.

#25864 Removed dnsVIP from the 4.5 docs.
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.5_Baremetal_IPI_Depoyment_0920_1.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.5_Baremetal_IPI_Depoyment_0920_2.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  installing/installing_bare_metal_ipi/images/OpenShift_Baremetal_IPI_Deployment_2.png
  installing/installing_bare_metal_ipi/ipi-install-overview.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#25800 adding moa faq
  _topic_map.yml
  getting_started_moa/creating-first-moa-cluster.adoc
  getting_started_moa/moa-faq.adoc
  modules/moa-creating-cluster.adoc
  modules/moa-faq-installing.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/L

#25805 Errata update for 4.4.26 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4, size/M

#26020 [enterprise-4.2] Added links to Red Hat Marketplace
  modules/olm-why-use-operators.adoc
  operators/olm-understanding-operatorhub.adoc
Labels: size/S

#26021 Serverless redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#26014 Always include padding in regular literal blocks
  _stylesheets/docs.css
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26012 Fix vertical scroll bar on .main container
  _stylesheets/docs.css
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26011 Lowercase field names
  modules/registry-operator-configuration-resource-overview.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26006 4-6 release notes for metering report expiration
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#26059 [enterprise-4.6] 4.6 After installation infra and audit index pattern not available in Kibana
  logging/config/cluster-logging-log-store.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: size/L

#25953 removing ref to ISO file for PXE/iPXE boot
  modules/installation-user-infra-machines-pxe.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25952 GIT21792: Changed values for subscription manager repo. Seems to appl…
  modules/rhel-compute-updating.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/XS

#25875 RHCOS release note additions
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#26065 [enterprise-4.4] removing ref to ISO file for PXE/iPXE boot
  modules/installation-user-infra-machines-pxe.adoc
Labels: size/XS

#25812 Initial commit for IPI bare metal installation for OCP 4.6
  _topic_map.yml
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.6_Baremetal_IPI_Deployment_1020_1.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.6_Baremetal_IPI_Deployment_1020_2.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  installing/installing_bare_metal_ipi/images/OpenShift_Baremetal_IPI_Deployment_2.png
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
  installing/installing_bare_metal_ipi/ipi-install-overview.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/ipi-install-creating-an-rhcos-images-cache.adoc
  modules/ipi-install-creating-the-openshift-manifests.adoc
  modules/ipi-install-deploying-routers-on-worker-nodes.adoc
  modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  modules/ipi-install-extracting-the-openshift-installer.adoc
  modules/ipi-install-following-the-installation.adoc
  modules/ipi-install-installing-rhel-on-the-provision-node.adoc
  modules/ipi-install-modifying-install-config-for-no-provisioning-network.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-retrieving-the-openshift-installer.adoc
  modules/ipi-install-root-device-hints.adoc
  modules/ipi-install-troubleshooting-api-not-accessible.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-misc-issues.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XL

#26066 [enterprise-4.6] Initial commit for IPI bare metal installation for OCP 4.6
  _topic_map.yml
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.6_Baremetal_IPI_Deployment_1020_1.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_4.6_Baremetal_IPI_Deployment_1020_2.svg
  installing/installing_bare_metal_ipi/images/71_OpenShift_Baremetal_IPI_Depoyment_0320_1.png
  installing/installing_bare_metal_ipi/images/OpenShift_Baremetal_IPI_Deployment_2.png
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
  installing/installing_bare_metal_ipi/ipi-install-overview.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/ipi-install-creating-an-rhcos-images-cache.adoc
  modules/ipi-install-creating-the-openshift-manifests.adoc
  modules/ipi-install-deploying-routers-on-worker-nodes.adoc
  modules/ipi-install-deploying-the-cluster-via-the-openshift-installer.adoc
  modules/ipi-install-extracting-the-openshift-installer.adoc
  modules/ipi-install-following-the-installation.adoc
  modules/ipi-install-installing-rhel-on-the-provision-node.adoc
  modules/ipi-install-modifying-install-config-for-no-provisioning-network.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-preparing-the-provision-node-for-openshift-install.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-retrieving-the-openshift-installer.adoc
  modules/ipi-install-root-device-hints.adoc
  modules/ipi-install-troubleshooting-api-not-accessible.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-misc-issues.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: branch/enterprise-4.6, size/XL

#25867 Bug 1879902, added metrics for 3.11 route maximums + Fixed footnotes
  scaling_performance/cluster_maximums.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm, size/M

#26073 Fix typos in docs
  modules/builds-basic-start-source.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/installation-gcp-service-account.adoc
  modules/installation-gcp-user-infra-config-host-project-vpc.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/update-oc-configmap-signature-verification.adoc
  storage/container_storage_interface/persistent-storage-csi-manila.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26078 No qcow2 images for ISO installs
  modules/installation-azure-user-infra-uploading-rhcos.adoc
  modules/installation-gcp-user-infra-rhcos.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.3, size/S

#26081 [enterprise-4.4]Fix typos in docs
  modules/builds-basic-start-source.adoc
  modules/installation-gcp-service-account.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/update-oc-configmap-signature-verification.adoc
Labels: size/S

#26080 [enterprise-4.5] Fix typos in docs
  modules/builds-basic-start-source.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/installation-gcp-service-account.adoc
  modules/installation-gcp-user-infra-config-host-project-vpc.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/update-oc-configmap-signature-verification.adoc
Labels: size/S

#26082 [enterprise-4.3]Fix typos in docs
  modules/builds-basic-start-source.adoc
  modules/installation-gcp-service-account.adoc
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/update-oc-configmap-signature-verification.adoc
Labels: size/S

#25990 GH issue 25155 OCP Online and Dedicated are not supported for Service…
  modules/ossm-supported-configurations.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25823 New MCO post-install tasks section
  _topic_map.yml
  modules/checking-mco-status.adoc
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  modules/installation-special-config-crony.adoc
  modules/machine-config-operator.adoc
  modules/machine-config-overview.adoc
  modules/machineconfig-modify-journald.adoc
  modules/machineconfig-modify-registry.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/rhcos-add-extensions.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XL

#25709 Updated bare metal install for coreos-installer
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  modules/digging-into-machine-config.adoc
  modules/installation-user-infra-machines-advanced.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XL

#26091 Fix 4.6 CP merge conflict in PR25709
  modules/installation-user-infra-machines-pxe.adoc
Labels: branch/enterprise-4.6, size/M

#26070 Fix merge conflict and apply SME feedback
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-static-network.adoc
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
Labels: branch/enterprise-4.6, size/L

#26093 Fix merge conflict in 4.6CP PR 26070
  modules/installation-user-infra-machines-iso.adoc
Labels: branch/enterprise-4.6, size/M

#26085 Support IPv6 single and dual stack only on Multus
  welcome/oke_about.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26017 Updating distro map to 4.5 for moa
  _distro_map.yml
Labels: Peer Review Done, size/XS

#26016 Updating moa topics to pull from the 4.5 branch
  _distro_map.yml
  _topic_map.yml
  cli_reference/moactl/moactl.adoc
  cli_reference/moactl/modules
  getting_started_moa/creating-first-moa-cluster.adoc
  getting_started_moa/images
  getting_started_moa/moa-faq.adoc
  getting_started_moa/modules
  getting_started_moa/required-aws-service-quotas.adoc
  modules/moa-accessing-your-cluster.adoc
  modules/moa-create-dedicated-cluster-admins.adoc
  modules/moa-creating-cluster.adoc
  modules/moa-deleting-cluster.adoc
  modules/moa-faq-installing.adoc
  modules/moa-installing-prerequisites.adoc
  modules/moa-quickstart-instructions.adoc
  modules/moa-required-aws-service-quotas.adoc
  modules/registry-integrated-openshift-registry.adoc
  web_console/web-console.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XL

#25730 cnv 2.5: Remove HPP storage workaround and v2v disk
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25763 cnv 2.5: VMware import supports Ceph block-format storage
  modules/virt-features-for-storage-matrix.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25821 OCPRHV-391 Add not tested/not supported notice to OCP 4.6 and RHV 4.3 docs [enterprise-4.6][enterprise-4.5][enterprise-4.4]
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-initializing.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26110 Verified Pipelines still TP for 4.6
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/XS

#25507 BZ#1879380 Compute machine creation not required in all cases
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26057 Adding `namespace: openshift-logging` to log forward CR
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26115 [enterprise-4.5] BZ#1879380 Compute machine creation not required in all cases
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.5, size/S

#26105 remove moa cli placeholder
  _topic_map.yml
  cli_reference/moactl/moactl.adoc
  cli_reference/moactl/modules
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#26023 cnv 2.5: VMware imported VM name must not contain forward slash
  modules/virt-importing-vm-wizard.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25715 cam 1.3: Create supplemental group for Restic on NFS
  modules/migration-known-issues.adoc
  modules/migration-restic-errors.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#25616 Add release notes entry for SR-IOV InfiniBand support
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#25980 CNV-4356: stable channel
  modules/virt-document-attributes.adoc
  modules/virt-monitoring-upgrade-status.adoc
  modules/virt-subscribing-cli.adoc
  modules/virt-subscribing-to-the-catalog.adoc
  modules/virt-upgrading-virt.adoc
Labels: CNV, branch/enterprise-4.6, size/M

#16884 Add Using Imagestreams with Kubernetes Resources assembly
  _topic_map.yml
  modules/images-managing-images-enabling-imagestreams-kube.adoc
  openshift_images/using-imagestreams-with-kube-resources.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#26132 Fix 4.6 CP merge conflict in PR25709, PR26091
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  modules/digging-into-machine-config.adoc
  modules/installation-user-infra-machines-advanced.adoc
Labels: branch/enterprise-4.6, size/L

#26125 Fix sidebar word overflow
  _stylesheets/docs.css
Labels: size/XS

#26024 Upgrade to mtc 1.3
  _topic_map.yml
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/upgrading-migration-tool-3-4.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/upgrading-migration-tool-4-1-4.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/upgrading-migration-tool-4-2-4.adoc
  modules/common-attributes.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-restic-errors.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-upgrading-migration-tool-3.adoc
  modules/migration-upgrading-migration-tool-4.adoc
  modules/migration-upgrading-migration-tool.adoc
  modules/migration-using-must-gather.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#26131 [virt] Replacing link to ConfigMap docs with OCP xref
  virt/virtual_machines/virt-managing-configmaps-secrets-service-accounts.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25808 BZ-1880750 Updated clipboard.js to remove sh-4.x# from copied code blocks
  _javascripts/clipboard.js
  _templates/_page_openshift.html.erb
Labels: branch/enterprise-3.11, branch/enterprise-4.1, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26100 fixed Typos in 3.11 #25828
  architecture/infrastructure_components/kubernetes_infrastructure.adoc
  dev_guide/managing_images.adoc
  dev_guide/topics/about_device_manager.adoc
  install_config/aggregate_logging.adoc
  install_config/master_node_configuration.adoc
  install_config/router/customized_haproxy_router.adoc
  install_config/topics/ocp_osp_provisioning.adoc
  release_notes/ocp_3_10_release_notes.adoc
  release_notes/ocp_3_5_release_notes.adoc
  release_notes/ocp_3_6_release_notes.adoc
  servicemesh-install/topics/tutorial-rhoar-missions.adoc
  servicemesh-release-notes/topics/rn-known-issues.adoc
  servicemesh-release-notes/topics/rn-new-features.adoc
Labels: Peer Review Done, branch/enterprise-3.11, hacktoberfest-accepted, size/M

#26090 BZ-1879167 Fixes copy button code block misalignment
  _javascripts/clipboard.js
Labels: size/XS

#26168 [enterprise-3.11] BZ-1880750 Updated clipboard.js to remove sh-4.x# from copied code bl…
  _javascripts/clipboard.js
Labels: size/M

#26163 replace term whitelist in doc.
  service_mesh/service_mesh_day_two/prepare-to-deploy-applications-ossm.adoc
Labels: size/XS

#24568 [enterprise-4.3] Add Metering and Cost Management to TP Matrix
  release_notes/ocp-4-3-release-notes.adoc
Labels: branch/enterprise-4.3, size/S

#24569 [enterprise-4.4] Add Cost Management to TP Matrix
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4, size/XS

#26187 Reverting distro_map for openshift-enterprise and changing version to 4.5
  _distro_map.yml
Labels: size/S

#26095 Various edits from Support review
  logging/config/cluster-logging-visualizer.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: branch/enterprise-4.6, size/M

#26190 [enterprise-4.5] Various edits from Support review
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/S

#26189 [enterprise-4.6] Various edits from Support review
  logging/config/cluster-logging-visualizer.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/M

#26191 [enterprise-4.4] Various edits from Support review
  modules/cluster-logging-collector-chunk.adoc
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-limits.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/S

#25685 CNV - BZ#1875383 rel_note for terminationGracePeriod
  virt/virt-2-4-release-notes.adoc
Labels: CNV, size/S

#26072 Add more explanations for custom domain example for serverless
  modules/serverless-service-mesh-resources.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25509 [enterprise-4.6] Add restricted OSP IPI assembly
  _topic_map.yml
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing.adoc
  modules/installation-osp-creating-image-restricted.adoc
  modules/installation-osp-restricted-config-yaml.adoc
Labels: branch/enterprise-4.6, size/L

#26130 [virt] BZ 1869194: OpenShift Virtualization Operator Deployment tab
  modules/virt-deleting-deployment-custom-resource.adoc
  modules/virt-deploying-virt.adoc
  virt/install/uninstalling-virt-web.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26068 Fixing typos Openshift to OpenShift
  applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc
  modules/developer-cli-odo-developer-setup.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-openshift-source-to-image.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
  modules/nw-networkpolicy-about.adoc
  modules/op-release-notes-1-0.adoc
  modules/rhel-preparing-playbook-machine.adoc
Labels: size/S

#26206 [enterprise-4.6] Fixing typos Openshift to OpenShift
  _topic_map.yml
  applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc
  modules/developer-cli-odo-developer-setup.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-openshift-source-to-image.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
  modules/nw-networkpolicy-about.adoc
  modules/op-release-notes-1-0.adoc
  modules/rhel-preparing-playbook-machine.adoc
  rest_api/config_apis/network-config-openshift-io-v1.adoc
Labels: size/M

#26208 [enterprise-4.5] Fixing typos Openshift to OpenShift
  _topic_map.yml
  applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  modules/developer-cli-odo-developer-setup.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-openshift-source-to-image.adoc
  modules/installation-initializing.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/nodes-cluster-remote-workers-objects.adoc
  modules/nw-networkpolicy-about.adoc
  modules/op-release-notes-1-0.adoc
  modules/rhel-preparing-playbook-machine.adoc
  release_notes/ocp-4-5-release-notes.adoc
  rest_api/config_apis/network-config-openshift-io-v1.adoc
  virt/virt-2-4-release-notes.adoc
Labels: size/M

#26209 [enterprise-4.4] Fixing typos Openshift to OpenShift
  _topic_map.yml
  applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc
  modules/developer-cli-odo-developer-setup.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-openshift-source-to-image.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/op-release-notes-1-0.adoc
  modules/rhel-preparing-playbook-machine.adoc
  release_notes/ocp-4-4-release-notes.adoc
  rest_api/config_apis/network-config-openshift-io-v1.adoc
Labels: size/S

#26108 Added sinkbinding notes
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  serverless/event_workflows/serverless-sinkbinding.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#26211 [enterprise-4.3] Fixing typos Openshift to OpenShift
  _topic_map.yml
  applications/application_life_cycle_management/odc-creating-applications-using-developer-perspective.adoc
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/openshift-developer-cli-developer-setup.adoc
  modules/openshift-developer-cli-linking-both-components.adoc
  modules/openshift-developer-cli-openshift-cluster-objects.adoc
  modules/openshift-developer-cli-openshift-source-to-image.adoc
  modules/rhel-preparing-playbook-machine.adoc
Labels: size/S

#26216 Removing unneeded + character
  modules/cluster-logging-elasticsearch-exposing.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26137 SM books redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/S

#26221 Fix-attributes
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/configuring-replication-repository-3-4.adoc
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/upgrading-migration-tool-3-4.adoc
  migration/migrating_4_1_4/configuring-replication-repository-4-1-4.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/upgrading-migration-tool-4-1-4.adoc
  migration/migrating_4_2_4/configuring-replication-repository-4-2-4.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/upgrading-migration-tool-4-2-4.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#26162 ES nodes requirements not so much understandable
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26229 [enterprise-4.3] ES nodes requirements not so much understandable
  modules/cluster-logging-deploy-eo-cli.adoc
Labels: size/XS

#26231 [enterprise-4.4] ES nodes requirements not so much understandable
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
Labels: size/S

#26071 Updates PR 26013 - add tang: Note that rd.neednet=1 is needed
  modules/installation-special-config-encrypt-disk-tang.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/M

#25786 Known issue for loading VMIs with Redfish Virtual Media
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26203 Remove all instances of Starter EOL from the docs.
  _distro_map.yml
  index-commercial.html
  modules/nodes-cluster-limit-ranges-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/starter-support.adoc
  support/getting-support.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#26060 Configuring multiple helm chart repositories
  _topic_map.yml
  cli_reference/helm_cli/configuring-custom-helm-chart-repositories.adoc
  modules/helm-adding-helm-chart-repositories.adoc
  modules/helm-creating-credentials-and-certificates-to-add-helm-repositories.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26236 [enterprise-4.6] Remove all instances of Starter EOL from the docs.
  modules/nodes-cluster-limit-ranges-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/starter-support.adoc
  support/getting-support.adoc
Labels: branch/enterprise-4.6, size/M

#26237 [enterprise-4.5] Remove all instances of Starter EOL from the docs.
  modules/nodes-cluster-limit-ranges-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/starter-support.adoc
  support/getting-support.adoc
Labels: branch/enterprise-4.5, size/M

#26239 [enterprise-4.3] Remove all instances of Starter EOL from the docs.
  modules/nodes-cluster-limit-ranges-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/starter-support.adoc
  support/getting-support.adoc
Labels: branch/enterprise-4.3, size/M

#26251 modules/pruning-groups: '//Future' prefixes for xrefs
  modules/pruning-groups.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#25985 Adding channels docs for ODC
  images/create-sub-ODC.png
  images/serverless-verify-source-channel.png
  images/sink-pingsource-channel.png
  images/verify-channel-odc.png
  images/verify-pingsource-ODC.png
  images/verify-subscription-odc.png
  modules/kn-trigger-list.adoc
  modules/serverless-connect-channel-source-odc.adoc
  modules/serverless-create-channel-odc.adoc
  modules/serverless-create-inmemorychannel-yaml.adoc
  modules/serverless-create-inmemorychannel.adoc
  modules/serverless-creating-subscriptions-odc.adoc
  modules/serverless-creating-subscriptions-yaml.adoc
  modules/serverless-pingsource-odc.adoc
  modules/serverless-supported-channel-types.adoc
  serverless/event_sources/serverless-pingsource.adoc
  serverless/event_workflows/serverless-channels.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26167 New Installer features for 4.6 RNs
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26267 CP 4-4 from PR26071
  modules/installation-special-config-encrypt-disk-tang.adoc
Labels: branch/enterprise-4.4, size/S

#26269 CP 4-3 from PR26071
  modules/installation-special-config-encrypt-disk-tang.adoc
Labels: branch/enterprise-4.3, size/S

#26255 modules/dynamic-provisioning-available-plugins: Drop xref
  modules/dynamic-provisioning-available-plugins.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26232 RN-OpenShift Virtualization 2.5 Release Notes
  modules/virt-supported-cluster-version.adoc
  virt/virt-2-5-release-notes.adoc
Labels: CNV, lgtm, size/L

#26245 RN - Added dummy 2-5 release notes file
  virt/virt-2-5-release-notes.adoc
Labels: CNV, lgtm, size/S

#26250 modules/ose_3_0_release_notes: Remove unused file
  modules/ose_3_0_release_notes.adoc
Labels: lgtm, size/XL

#25605 [OSP] Update Ignition files script - BZ1868439
  modules/installation-osp-creating-control-plane-ignition.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26166 Known issue for egress IP node shutdown
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26247 OSDOCS-1293 Update AWS AMIs for 4.6 release
  modules/installation-aws-user-infra-rhcos-ami.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#26268 CNV - Moved xref out of module and into assembly file
  modules/virt-about-upgrading-virt.adoc
  virt/upgrading-virt.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26286 Formatting fixes flagged by L10n
  modules/installation-about-custom-gcp-vpc.adoc
  modules/installation-gcp-user-infra-config-host-project-vpc.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26164 Adding note about AMQ Streams license requirement.
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  modules/jaeger-deploy-streaming.adoc
Labels: Peer Review Needed, size/S

#26293 GIT26169: Removed paragraph about changing settings in files.
  modules/digging-into-machine-config.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#24834 Param changes for OSP AZ support
  modules/installation-configuration-parameters.adoc
  modules/machineset-yaml-osp.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#26301 Sync egress firewall filename IDs
  _topic_map.yml
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-egressnetworkpolicy-delete.adoc
  modules/nw-egressnetworkpolicy-edit.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-egressnetworkpolicy-view.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/editing-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/removing-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/viewing-egress-firewall-ovn.adoc
Labels: branch/enterprise-4.6, size/M

#26302 [enterprise-4.6] Sync egress firewall filename IDs
  _topic_map.yml
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-egressnetworkpolicy-delete.adoc
  modules/nw-egressnetworkpolicy-edit.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-egressnetworkpolicy-view.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/editing-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/removing-egress-firewall-ovn.adoc
  networking/ovn_kubernetes_network_provider/viewing-egress-firewall-ovn.adoc
Labels: branch/enterprise-4.6, size/L

#25882 Logging cluster labels
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#26243 Improve MachineConfig and journald.conf examples
  modules/cluster-logging-systemd-scaling.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/M

#26310 [enterprise-4.3] Improve MachineConfig and journald.conf examples
  modules/cluster-logging-systemd-scaling.adoc
Labels: size/M

#26312 [enterprise-4.4] Improve MachineConfig and journald.conf examples
  modules/cluster-logging-systemd-scaling.adoc
Labels: size/M

#26313 [enterprise-4.5] Improve MachineConfig and journald.conf examples
  modules/cluster-logging-systemd-scaling.adoc
Labels: size/M

#26317 Bump OSDK to v0.19.4
  modules/osdk-building-bundle-image.adoc
  modules/osdk-installing-cli.adoc
Labels: branch/enterprise-4.6, size/XS

#26181 Add conversion webhooks for OLM
  _topic_map.yml
  modules/olm-defining-csv-webhooks.adoc
  modules/olm-webhook-considerations.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
  operators/understanding/olm/olm-webhooks.adoc
  operators/user/olm-webhooks.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/L

#25824 OSDOCS-1173: Adding release notes for audit log config
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/S

#25873 OSDOCS-1206: Updating 1.18 to 1.19 in example output
  _unused_topics/looking-inside-nodes.adoc
  _unused_topics/understanding-workers-masters.adoc
  metering/configuring_metering/metering-common-config-options.adoc
  modules/graceful-restart.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/rhel-compute-updating.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/L

#25666 BZ-1880925: Adding step to navigate to /home/core
  modules/backup-etcd.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#26320 cnv 2.5: Added CNV-7102 to virt 2.5 RN
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26326 Fix typo in eventrouter docs
  modules/cluster-logging-eventrouter-deploy.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26307 Remove empty module from OSP UPI assemblies
  installing/installing_openstack/installing-openstack-user-kuryr.adoc
  installing/installing_openstack/installing-openstack-user.adoc
  modules/installation-user-infra-generate.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#24731 BZ1769845 - Add storage management table and ephemeral storage docs
  _topic_map.yml
  modules/data-storage-management.adoc
  modules/feature-gate-features.adoc
  modules/storage-ephemeral-storage-manage.adoc
  modules/storage-ephemeral-storage-monitoring.adoc
  modules/storage-ephemeral-storage-overview.adoc
  modules/storage-ephemeral-storage-types.adoc
  scalability_and_performance/optimizing-storage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#26300 Add known issue release note for bug 1881262
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26123 GIT22310: Added a note in step 3 about quay.io persisting in the regstry after mirroring.
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26340 BZ1769845 - Add storage mgmnt table and ephemeral storage docs
  _topic_map.yml
  modules/data-storage-management.adoc
  modules/feature-gate-features.adoc
  modules/storage-ephemeral-storage-manage.adoc
  modules/storage-ephemeral-storage-monitoring.adoc
  modules/storage-ephemeral-storage-overview.adoc
  modules/storage-ephemeral-storage-types.adoc
  scalability_and_performance/optimizing-storage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: branch/enterprise-4.6, size/L

#26341 BZ1769845 - Add storage mgmnt table and ephemeral storage docs
  _topic_map.yml
  modules/data-storage-management.adoc
  modules/feature-gate-features.adoc
  modules/storage-ephemeral-storage-manage.adoc
  modules/storage-ephemeral-storage-monitoring.adoc
  modules/storage-ephemeral-storage-overview.adoc
  modules/storage-ephemeral-storage-types.adoc
  scalability_and_performance/optimizing-storage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: branch/enterprise-4.5, size/L

#21177 installation: provide rd.neednet=1 when using Tang disk encryption
  modules/installation-special-config-encrypt-disk-tang.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, size/XS

#26344 BZ1769845 - Add storage mgmnt table and ephemeral storage docs
  _topic_map.yml
  modules/data-storage-management.adoc
  modules/feature-gate-features.adoc
  modules/storage-ephemeral-storage-manage.adoc
  modules/storage-ephemeral-storage-monitoring.adoc
  modules/storage-ephemeral-storage-overview.adoc
  modules/storage-ephemeral-storage-types.adoc
  scalability_and_performance/optimizing-storage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: branch/enterprise-4.4, size/L

#26347 BZ1769845 - Add storage mgmnt table and ephemeral storage docs
  _topic_map.yml
  modules/data-storage-management.adoc
  modules/feature-gate-features.adoc
  modules/storage-ephemeral-storage-manage.adoc
  modules/storage-ephemeral-storage-monitoring.adoc
  modules/storage-ephemeral-storage-overview.adoc
  modules/storage-ephemeral-storage-types.adoc
  scalability_and_performance/optimizing-storage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: branch/enterprise-4.3, size/L

#25919 Update release links for OKD/OCP
  modules/understanding-upgrade-channels.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#25844 Known issue for GCP destroy
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#26316 Rel Notes doc text for 4.5.14 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#25740 osdocs-1466 Compliance Operator docs
  _topic_map.yml
  modules/compliance-anatomy.adoc
  modules/compliance-applying.adoc
  modules/compliance-custom-storage.adoc
  modules/compliance-imagestreams.adoc
  modules/compliance-inconsistent.adoc
  modules/compliance-manual.adoc
  modules/compliance-objects.adoc
  modules/compliance-profilebundle.adoc
  modules/compliance-profiles.adoc
  modules/compliance-raw-tailored.adoc
  modules/compliance-rescan.adoc
  modules/compliance-results.adoc
  modules/compliance-review.adoc
  modules/compliance-tailored-profiles.adoc
  modules/compliance-unapplying.adoc
  modules/compliance-update.adoc
  modules/compliance-updating.adoc
  security/compliance_operator/compliance-operator-advanced.adoc
  security/compliance_operator/compliance-operator-manage.adoc
  security/compliance_operator/compliance-operator-raw-results.adoc
  security/compliance_operator/compliance-operator-remediation.adoc
  security/compliance_operator/compliance-operator-tailor.adoc
  security/compliance_operator/compliance-operator-troubleshooting.adoc
  security/compliance_operator/compliance-operator-understanding.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XXL

#22202 Update content for OVN-Kubernetes GA [4.6]
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  modules/nw-install-config-parameters.adoc
  modules/nw-operator-cr.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  modules/nw-ovn-technology-preview.adoc
  networking/cluster-network-operator.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/disabling-multicast.adoc
  networking/ovn_kubernetes_network_provider/enabling-multicast.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26225 OSDOCS-1050 Power and Z Samples release note
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26215 machine_management: add note about using original boot media
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
Labels: branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26272 Add "Upgrading installed Operators"
  _topic_map.yml
  modules/olm-approving-pending-upgrade.adoc
  modules/olm-changing-update-channel.adoc
  operators/admin/olm-upgrading-operators.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#26353 Release notes logging
  release_notes/ocp-4-6-release-notes.adoc
Labels: size/M

#26366 GIT22380: Added clarification for number 7 standard node pod selector.
  modules/pruning-images.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26369 [enterprise-4.5] GIT22380: Added clarification for number 7 standard node pod selector.
  modules/pruning-images.adoc
Labels: size/XS

#26365 [enterprise-4.5] Add "Upgrading installed Operators"
  _topic_map.yml
  modules/olm-approving-pending-upgrade.adoc
  modules/olm-changing-update-channel.adoc
  operators/admin/olm-upgrading-operators.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
Labels: size/L

#25537 Remote worker node at the Edge
  _topic_map.yml
  modules/nodes-cluster-remote-workers-objects.adoc
  modules/nodes-edge-remote-workers-network.adoc
  modules/nodes-edge-remote-workers-power.adoc
  modules/nodes-edge-remote-workers-strategies.adoc
  nodes/edge/nodes-edge-remote-workers.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#25903 Added note on ephemeral storge if no StorageClass defined in logging CR
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/XS

#26372 [enterprise-4.4] Added note on ephemeral storge if no StorageClass defined in logging CR
  modules/cluster-logging-deploy-cli.adoc
Labels: size/XS

#26373 [enterprise-4.5] Added note on ephemeral storge if no StorageClass defined in logging CR
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
Labels: size/XS

#26214 Add OLM dependency best practices
  modules/olm-adding-new-crd-version.adoc
  modules/olm-bundle-format-dependencies-file.adoc
  modules/olm-bundle-format.adoc
  modules/olm-dependencies-best-practices.adoc
  modules/olm-dependencies-caveats.adoc
  modules/olm-dependency-resolution-about.adoc
  modules/olm-dependency-resolution-crd-upgrades.adoc
  modules/olm-dependency-resolution-preferences.adoc
  modules/olm-removing-crd-version.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
  operators/understanding/olm-packaging-format.adoc
  operators/understanding/olm/olm-understanding-dependency-resolution.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#25729 CCO: Explicit mode support
  modules/admin-credentials-root-secret-formats.adoc
  modules/cloud-credential-operator.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#26377 Bump OSDK to v0.19.4 in scorecard
  operators/operator_sdk/osdk-scorecard.adoc
Labels: branch/enterprise-4.6, lgtm, size/XS

#26248 Add OperatorSources to 4.6 RN rem feat
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#26314 Add macOS/Windows install for opm
  modules/olm-installing-opm.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/M

#26277 Rm remaining instances of OperatorSources
  installing/install_config/customizations.adoc
  modules/olm-catalogsource.adoc
  modules/olm-operatorhub-architecture.adoc
  modules/olm-operatorhub-overview.adoc
  operators/understanding/olm-understanding-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/L

#26348 Rel Notes doc text for 4.4.27 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#26385 Descheduler is still TP
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/XS

#25782 BZ1879959 - updating vCenter datastore permissions
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/XS

#26319 External links to migration CRs updated, few small fixes.
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/S

#26015 OSDOCS-1297 vSphere 7 support updates
  modules/installation-vsphere-infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S
