Repository openshift/openshift-docs, pull requests merged in 2020-11, with the labels that each got.

#26964 Update installation-common-issues.adoc
  modules/installation-common-issues.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26967 create WIP 47 site
  .travis.yml
  _distro_map.yml
Labels: size/XS

#26971 updated travis
  .travis.yml
Labels: size/XS

#26872 Warning note about ipam definition in NAD for VMs
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#26965 BZ#1893520: Remove CPMA from MTC documentation
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-using-cpma.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#26970 KI fixes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26979 Update tools sentence (removing CPMA)
  migration/migrating_3_4/about-migration.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#25932 GIT24440: In step 5, for the example I changed the minimum to 1. Also…
  admin_guide/topics/creating-LC-and-ASG-cluster-auto-scaler.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm, size/XS

#26706 Fix a typo in Serverless Broker injection annotation
  modules/serverless-creating-broker-admin.adoc
  modules/serverless-rn-1-10-0.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26987 [enterprise-4.4] Add examples for route allow list
  modules/nw-route-specific-annotations.adoc
Labels: branch/enterprise-4.4, size/M

#26988 [enterprise-4.5] Add examples for route allow list
  modules/nw-route-specific-annotations.adoc
Labels: branch/enterprise-4.5, size/M

#26975 Ocprhv 415 relnotes rhv addlinks
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26613 Bug 1889945: [DOCS] provide the prerequisite to enable ImageStream through mirror registry for must-gather IS
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  modules/support-gather-data.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, bugzilla/invalid-bug, bugzilla/severity-medium, size/XS

#26648 CNV (no tracker): Reorganizing vm import prerequisites
  modules/virt-creating-configmap.adoc
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#26911 OSSMDOC-141 update upstream/downstream differences topic.
  modules/ossm-vs-istio.adoc
Labels: size/M

#26856 Update installation-bare-metal-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26919 OSSMDOC-102
  _topic_map.yml
  modules/threescale-backend-cache.adoc
  service_mesh/v2x/_topic_map_DRAFT_2x.yml
  service_mesh/v2x/installing-ossm.adoc
  service_mesh/v2x/ossm-extensions.adoc
  service_mesh/v2x/ossm-vs-community.adoc
Labels: size/L

#25946 issue 24814 - clarifying an absolute path for image mirroring
  modules/installation-configuration-parameters.adoc
  modules/installation-mirror-repository.adoc
  modules/update-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#25904 Clarify ose variables in oc adm registry (Fix Issue 19346)
  install_config/registry/deploy_registry_existing_clusters.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#26558 CNV 2.5 Release Notes - Bob
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/XS

#25359 Cnv bz1875725 containerdisks
  _topic_map.yml
  modules/virt-about-container-disks.adoc
  modules/virt-preparing-container-disk-for-vms.adoc
  modules/virt-vm-storage-volume-types.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/virtual_disks/virt-using-container-disks-with-vms.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27014 [enterprise-4.4] issue 24814 - clarifying an absolute path for image mirroring
  modules/installation-configuration-parameters.adoc
  modules/installation-mirror-repository.adoc
  modules/update-mirror-repository.adoc
Labels: size/S

#27018 [enterprise-4.5] Cnv bz1875725 containerdisks
  _topic_map.yml
  modules/virt-about-container-disks.adoc
  modules/virt-preparing-container-disk-for-vms.adoc
  modules/virt-vm-storage-volume-types.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/virtual_disks/virt-using-container-disks-with-vms.adoc
Labels: size/L

#26963 CNV-7443: document how to manually resolve unknown nodes
  _topic_map.yml
  modules/nodes-nodes-working-deleting-bare-metal.adoc
  modules/virt-listing-vmis-cli.adoc
  virt/virtual_machines/virt-triggering-vm-failover-resolving-failed-node.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26899 adding log forwarding and links to Understanding cluster logging
  logging/cluster-logging.adoc
  modules/cluster-logging-forwarding-about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#26890 JIRA1593: Changed MOA naming to official new name Red Hat Openshift S…
  _distro_map.yml
Labels: Peer Review Needed, branch/enterprise-4.5, size/XS

#27029 search: unify the search button style
  _stylesheets/search.css
Labels: size/XS

#26746 MIG 358: CA certificate errors in MTC console
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-error-messages.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26870 OSSMDOC-125 and 131, configure external Elasticsearch.
  modules/jaeger-config-storage.adoc
Labels: Service Mesh, size/L

#26921 Incorrect description of how to view haproxy statistics in OCP3.11
  admin_guide/router.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#27024 BZZ1882647 - clarifying DHCP configuration for vsphere IPI
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26135 BZ#1882203 - adding docs about openshift-master/redeploying-named-cer…
  install_config/redeploying_certificates.adoc
Labels: branch/enterprise-3.11, size/S

#27037 Rm plus sign in virtctl module
  modules/virt-virtctl-commands.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26261 OSSMDOC-72 OSSM 2.0 installation changes
  modules/jaeger-install.adoc
  modules/ossm-control-plane-deploy-1x.adoc
  modules/ossm-control-plane-deploy.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-install-kiali.adoc
  modules/ossm-install-ossm-operator.adoc
  service_mesh/v2x/installing-ossm.adoc
  service_mesh/v2x/ossm-architecture.adoc
  service_mesh/v2x/prepare-to-deploy-applications-ossm.adoc
Labels: Service Mesh, size/L

#25976 Bug: 1883036 - Option to not redeploy the service signer
  install/configuring_inventory_file.adoc
  install_config/redeploying_certificates.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#25205 BZ#1828814 Update production env support to include fast channels
  modules/update-upgrading-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26624 Disconnected envt support for Pipelines
  pipelines/installing-pipelines.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27050 Bug-1882726 minor updates to ssh access doc
  modules/virt-accessing-vmi-ssh.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#26687 OSDOCS-1563: Re-use OLM arch modules in Op ref guide
  modules/olm-arch-catalog-operator.adoc
  modules/olm-arch-catalog-registry.adoc
  modules/olm-arch-olm-operator.adoc
  modules/olm-architecture.adoc
  modules/olm-overview.adoc
  operators/operator-reference.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/M

#26998 CNV-BZ-1874403 release note for 2.5
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26597 RN-CNV-7168 Prevent incorrect use of DataVolume in VM spec
  virt/virt-2-5-release-notes.adoc
Labels: CNV, lgtm, size/XS

#26265 OSSMDOC-40 and OSSMDOC-113 New SMCP and configuration topics
  _topic_map.yml
  modules/ossm-auto-route.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-istio-global-1x.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-member-roll-create.adoc
  modules/ossm-security-mtls.adoc
  modules/ossm-updating-smcp.adoc
  service_mesh/v1x/customizing-installation-ossm.adoc
  service_mesh/v1x/ossm-custom-resources.adoc
  service_mesh/v2x/customizing-installation-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
Labels: Service Mesh, size/XL

#27063 BZ#1894281 Azure VHD URL version update
  modules/installation-azure-user-infra-uploading-rhcos.adoc
Labels: branch/enterprise-4.6, size/XS

#27017 RN for Pipelines TP 1-2
  modules/op-release-notes-1-0.adoc
  modules/op-release-notes-1-1.adoc
  modules/op-release-notes-1-2.adoc
  pipelines/op-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#26991 CNV-7317 RN-guest agent details view in the web console
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26585 Add etcd disk recommendations
  modules/recommended-etcd-practices.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27066 bz1892294 - fixed images name issue
  release_notes/ocp-4-6-release-notes.adoc
Labels: Telco, branch/enterprise-4.6, size/XS

#26620 Changing second level one heading and subsequent headings
  networking/ingress-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#26736 OSSMDOC-122 - Release Notes for OSSM 2.0.0
  _topic_map.yml
  jaeger/rhbjaeger-release-notes.adoc
  modules/jaeger-document-attributes.adoc
  modules/jaeger-rn-known-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/jaeger-rn-technology-preview.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-rn-deprecated-features.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/ossm-supported-configurations-v1x.adoc
  modules/ossm-supported-configurations.adoc
  service_mesh/v2x/customizing-installation-ossm.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: Service Mesh, size/L

#27076 Late Telco-related RN for BM IPI
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/XS

#27027 Improve info on Operator channel naming & approval strategy
  modules/olm-changing-update-channel.adoc
  modules/olm-installing-operators-from-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26854 Moving audit log content to security section
  _topic_map.yml
  modules/nodes-nodes-audit-log-basic-viewing.adoc
  modules/nodes-nodes-audit-log-basic.adoc
  security/audit-log-view.adoc
  security/container_security/security-monitoring.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, size/S

#27085 Audit Log and Config Redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#26185 Restructure odo docs.
  _topic_map.yml
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-single-component-application-with-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-an-application-with-a-database.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/debugging-applications-in-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/deleting-applications.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/using-devfiles-in-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/working-with-projects.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/working-with-storage.adoc
  cli_reference/developer_cli_odo/odo-release-notes.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/creating-and-deploying-a-component-to-the-disconnected-cluster.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/pushing-the-odo-init-image-to-the-restricted-cluster-registry.adoc
  modules/developer-cli-odo-adding-storage-to-the-application-components.adoc
  modules/developer-cli-odo-configuring-debugging-parameters.adoc
  modules/developer-cli-odo-connecting-the-database.adoc
  modules/developer-cli-odo-creating-a-project.adoc
  modules/developer-cli-odo-debugging-an-application.adoc
  modules/developer-cli-odo-deleting-an-application.adoc
  modules/developer-cli-odo-deploying-a-database-in-interactive-mode.adoc
  modules/developer-cli-odo-deploying-a-database-manually.adoc
  modules/developer-cli-odo-deploying-the-front-end-component.adoc
  modules/developer-cli-odo-installing-odo-on-linux.adoc
  modules/developer-cli-odo-installing-odo-on-macos.adoc
  modules/developer-cli-odo-installing-odo-on-windows.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27089 added odo redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#26980 Cnv vmware ports
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/S

#27100 [enterprise-4.5] BZ1879440: cnv ports for VMware
  modules/virt-importing-vm-prerequisites.adoc
Labels: size/XS

#27092 Add allowlist item for firewall config.
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26989 Errata update for 4.5.17 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#26811 Added Insights plug-in release note for 4.7
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#26961 Bug 1883837, updated Managing Weights procedure
  modules/deployments-ab-testing-lb.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#25941 Fix Issue 25610 - expand block reg storage proc
  modules/installation-registry-storage-block-recreate-rollout.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26062 BZ1860894: Added URL for AWS in step 4.
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27019 CNV-BZ-1885964 release note for 2.5
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#27113 Clarify OVN-Kubernetes GA release notes entry
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#26608 Log Forwarding add topic on forwarding from project
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#25387 CNV-2705 Creating and exposing a VM-backed service
  modules/virt-creating-a-service-from-a-virtual-machine.adoc
  virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, size/L

#25255 CNV BZ#1874084 removing unsupported NICs
  modules/virt-networking-wizard-fields-web.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26946 Rosa add aws profile support
  modules/rosa-installing-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#26524 CNV-7522 - nmstate more config example
  modules/virt-about-nmstate.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-bond-nncp.adoc
  modules/virt-example-bridge-nncp.adoc
  modules/virt-example-ethernet-nncp.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-example-nmstate-multiple-interfaces.adoc
  modules/virt-example-vlan-nncp.adoc
  modules/virt-removing-interface-from-nodes.adoc
  virt/node_network/virt-updating-node-network-config.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27147 Improve disconnected OLM intro
  operators/admin/olm-restricted-networks.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27158 Lowercase CRD
  modules/olm-operator-framework.adoc
  modules/olm-why-use-operators.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26450 SRVKE-562: Added Kafka install docs
  _topic_map.yml
  images/knative-kafka-overview.png
  modules/serverless-install-kafka-odc.adoc
  modules/serverless-install-kafka-yaml.adoc
  serverless/serverless-kafka.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#26828 BZ-1844449 Updating hostname in syslog protocol example 4.6 4.7
  modules/cluster-logging-collector-legacy-syslog.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#26835 BZ-1844449 Updating hostname in syslog protocol examples 4.4
  modules/cluster-logging-collector-syslog.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#26836 BZ-1844449 Updating hostname in syslog protocol examples 4.5
  modules/cluster-logging-collector-syslog.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#27172 Revert "BZ#1893520: Remove CPMA from MTC documentation"
  _topic_map.yml
  migration/migrating_3_4/about-migration.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-using-cpma.adoc
Labels: size/L

#27125 Rel Notes doc text for 4.6.2 release
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#27150 Add OSP IPI restricted to installation types table
  installing/install_config/installation-types.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27119 BZ#1879620 Creating vSphere MachineSets
  _topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  modules/machine-api-overview.adoc
  modules/machineset-creating.adoc
  modules/machineset-yaml-vsphere.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27186 [enterprise-4.5] BZ#1879620 Creating vSphere MachineSets
  _topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  modules/machine-api-overview.adoc
  modules/machineset-creating.adoc
  modules/machineset-yaml-vsphere.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: branch/enterprise-4.5, size/L

#27126 CNV-7169 RN for Golden Images
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26877 Clarifying overutilization requirement
  modules/nodes-descheduler-strategies.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#26996 Re-created the PR to address rebase, Ashley's changes and my changes.
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-ipv6-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27183 Update XREFs for service mesh v2x
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  jaeger/jaeger_install/rhbjaeger-installation.adoc
  post_installation_configuration/network-configuration.adoc
  serverless/networking/serverless-ossm-custom-domains.adoc
  serverless/networking/serverless-ossm-jwt.adoc
  serverless/networking/serverless-ossm.adoc
Labels: size/S

#27187 NFD Operator known issue is resolved in latest z-stream
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#26986 CNV - JIRA Story CNV7160 Adding guest agent virtctl command info to 2.5 Release Notes
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#26676 CNV-1396_2 Fixing Vikram's comments from merged PR
  modules/virt-cloning-a-datavolume.adoc
  modules/virt-understanding-smart-cloning.adoc
  virt/virtual_machines/virtual_disks/virt-cloning-a-datavolume-using-smart-cloning.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/M

#25162 CNV-4657 virtctl web console download
  modules/virt-enabling-virt-repos.adoc
  modules/virt-installing-virtctl-client-web.adoc
  modules/virt-installing-virtctl-client.adoc
  virt/install/virt-installing-virtctl.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27072 RN-BZ-1893160 2.5 release notes known issue
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#27135 Bug 1895270 : [DOCS] RHEL7 worker node needs additional package repository as of OCPv4.6 for scaling up
  modules/rhel-compute-updating.adoc
  modules/rhel-preparing-node.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27122 Errata update for 4.5.18 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/L

#27142 CNV-7295 Rel_Note download virtctl from web console
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/XS

#27202 CNV-7314: release note for image upload via web console
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/XS

#27203 CNV-7318: release note for opening console in new window
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/XS

#27201 BZ 1886795: nonexistent virt-tuning plugin
  modules/virt-pxe-booting-with-mac-address.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27218 Fix ROSA AWS table
  modules/rosa-required-aws-service-quotas.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#27088 CNV-7193 Default OS Images
  _topic_map.yml
  modules/virt-creating-a-vm-from-a-default-os-image.adoc
  modules/virt-creating-pvcs-to-store-default-os-images.adoc
  virt/virtual_machines/virtual_disks/virt-creating-and-using-default-os-images.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27093 BZ1894007: CNV remove import provider secrets
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27233 Issue #27213, updated version numbers in examples
  modules/update-upgrading-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#26205 SRVKE-486 + RHDEVDOCS-2087: Add kn broker docs
  images/add-trigger-odc.png
  images/delete-trigger-odc.png
  images/odc-view-broker.png
  images/verify-trigger-odc.png
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml.adoc
  modules/delete-kn-trigger.adoc
  modules/kn-trigger-describe.adoc
  modules/kn-trigger-filtering.adoc
  modules/kn-trigger-list.adoc
  modules/kn-trigger-update.adoc
  modules/serverless-create-broker-kn.adoc
  modules/serverless-create-kn-trigger.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-broker-admin.adoc
  modules/serverless-creating-broker-annotation.adoc
  modules/serverless-creating-broker.adoc
  modules/serverless-delete-trigger-odc.adoc
  modules/serverless-deleting-broker-admin.adoc
  modules/serverless-describe-broker-kn.adoc
  modules/serverless-list-broker-kn.adoc
  modules/serverless-rn-1-10-0.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/event_workflows/serverless-using-brokers.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.6, branch/enterprise-4.7, size/XL

#27232 OSSMDOC-126 Roll back updates to serverless XREFs
  serverless/networking/serverless-ossm-custom-domains.adoc
  serverless/networking/serverless-ossm-jwt.adoc
  serverless/networking/serverless-ossm.adoc
Labels: Serverless, Service Mesh, size/S

#27249 OKD to latest
  .s2i/httpd-cfg/01-community.conf
  _distro_map.yml
Labels: size/XS

#27207 Update registry logs example
  modules/registry-viewing-logs.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#25804 bz1785021 - using ssh to reach bootstrap node
  modules/ssh-agent-using.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#26997 CNV-7293: RN for stable channel
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/S

#27251 BZ1894007: CNV - delete provider secret
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, size/S

#27260 [enterprise-4.4] bz1785021 - using ssh to reach bootstrap node
  modules/ssh-agent-using.adoc
Labels: size/XS

#27261 [enterprise-4.5] bz1785021 - using ssh to reach bootstrap node
  modules/ssh-agent-using.adoc
Labels: size/XS

#27225 Formatting fixes to CNV relnotes
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#27239 BZ 1884538: config map warning
  virt/virt-2-5-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, size/XS

#27127 Rel Notes doc text for 4.4.30 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, size/L

#27141 CNV-7296 RelNot - HCO and HPP version bump
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, size/XS

#27265 [SRVKE-568] [srvls] Broker doc changes for 4.5
  images/add-trigger-odc.png
  images/delete-trigger-odc.png
  images/odc-view-broker.png
  images/verify-trigger-odc.png
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml.adoc
  modules/delete-kn-trigger.adoc
  modules/kn-trigger-describe.adoc
  modules/kn-trigger-filtering.adoc
  modules/kn-trigger-list.adoc
  modules/kn-trigger-update.adoc
  modules/serverless-create-broker-kn.adoc
  modules/serverless-create-kn-trigger.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-broker-admin.adoc
  modules/serverless-creating-broker-annotation.adoc
  modules/serverless-delete-trigger-odc.adoc
  modules/serverless-deleting-broker-admin.adoc
  modules/serverless-describe-broker-kn.adoc
  modules/serverless-list-broker-kn.adoc
  modules/serverless-rn-1-10-0.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/event_workflows/serverless-using-brokers.adoc
  serverless/knative_eventing/serverless-kn-trigger.adoc
Labels: Serverless, branch/enterprise-4.5, size/XL

#27188 OSSMDOC-158 and OSSMDOC-156
  modules/ossm-control-plane-profiles.adoc
  modules/ossm-control-plane-templates-1x.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-new-features.adoc
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
  service_mesh/v2x/prepare-to-deploy-applications-ossm.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: Service Mesh, size/L

#27216 removing -o yaml from oc edit
  modules/infrastructure-moving-router.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27166 Update max rules for egress firewall
  modules/nw-egressnetworkpolicy-about.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27132 The `openshift` namespace is a namespace
  builds/running-entitled-builds.adoc
  modules/configuration-resource-overview.adoc
  modules/installation-restricted-network-samples.adoc
  modules/registry-authentication-enabled-registry-overview.adoc
  modules/samples-operator-configuration.adoc
  modules/samples-operator-overview.adoc
  openshift_images/configuring-samples-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27167 PTP hardware supported only on bare metal hardware
  networking/multiple_networks/configuring-ptp.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#27276 [enterprise-4.7] Update max rules for egress firewall
  modules/nw-egressnetworkpolicy-about.adoc
Labels: branch/enterprise-4.7, size/XS

#27248 Adding new terms to the glossary
  contributing_to_docs/term_glossary.adoc
Labels: Peer Review Done, size/S

#27236 OSSMDOC-157
  modules/ossm-rn-fixed-issues.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: Service Mesh, size/M

#27197 Updated commands, added new commands and procedures.
  getting_started_rosa/creating-first-rosa-cluster.adoc
  modules/rosa-create-dedicated-cluster-admins.adoc
  modules/rosa-delete-cluster-admins.adoc
  modules/rosa-delete-dedicated-admins.adoc
  modules/rosa-deleting-cluster.adoc
  modules/rosa-quickstart-instructions.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#27155 Fix broken block tags
  modules/images-create-s2i-scripts.adoc
  modules/nw-configure-ingress-access-logging.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27266 Add CSV to term glossary
  contributing_to_docs/term_glossary.adoc
Labels: Peer Review Done, size/XS

#27290 [enterprise-4.4] PTP hardware supported only on bare metal hardware
  networking/multiple_networks/configuring-ptp.adoc
Labels: branch/enterprise-4.4, size/S

#27262 OSSMDOC-133 Add note that autoscaling supported 1.20 or later.
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
Labels: Service Mesh, size/S

#27286 Update memory requirement
  modules/dedicated-cluster-install-deploy.adoc
Labels: Peer Review Done, branch/enterprise-4.3, size/S

#27297 Improve disconnected OLM intro
  modules/olm-understanding-operator-catalog-images.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: branch/enterprise-4.5, size/M

#27300 BZ1897071: Remove filesystem storage from VM import modules
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27096 BZ1894537: CNV RHV VM disk too large for Ceph RBD block
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27303 [enterprise-4.5] BZ1897071: remove filesystem support from VM import
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-wizard.adoc
Labels: size/S

#27217 Errata update for 3.11.317 release
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/L

#27299 Aligning VM import modules
  modules/virt-checking-storage-class.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#27246 ElasticSearch operator upgrade created new PVCs
  modules/cluster-logging-updating-logging.adoc
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#27253 Release Notes updates for Power
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/S

#27311 Update ignition version for vSphere bootstrap
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, size/XS

#26688 BZ1890663 Storage matrix needs updating for CNV 2.5
  modules/virt-features-for-storage-matrix.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27309 Terminology style updates for arch
  architecture/cicd_gitops.adoc
  architecture/understanding-development.adoc
  modules/admission-webhook-types.adoc
  modules/architecture-machine-roles.adoc
  modules/architecture-platform-benefits.adoc
  modules/configuring-dynamic-admission.adoc
  modules/digging-into-machine-config.adoc
  modules/ignition-config-viewing.adoc
  modules/rhcos-about.adoc
  modules/understanding-machine-config-operator.adoc
  modules/unmanaged-operators.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27318 Terminology style updates for arch
  architecture/cicd_gitops.adoc
  architecture/understanding-development.adoc
  modules/admission-webhook-types.adoc
  modules/architecture-machine-roles.adoc
  modules/architecture-platform-benefits.adoc
  modules/configuring-dynamic-admission.adoc
  modules/digging-into-machine-config.adoc
  modules/ignition-config-viewing.adoc
  modules/rhcos-about.adoc
  modules/understanding-machine-config-operator.adoc
  modules/unmanaged-operators.adoc
Labels: size/L

#27306 Terminology style updates for welcome content
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27322 Terminology style updates for welcome content
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: size/S

#27319 Terminology style updates for arch
  architecture/cicd_gitops.adoc
  architecture/understanding-development.adoc
  modules/admission-webhook-types.adoc
  modules/architecture-machine-roles.adoc
  modules/architecture-platform-benefits.adoc
  modules/configuring-dynamic-admission.adoc
  modules/digging-into-machine-config.adoc
  modules/rhcos-about.adoc
  modules/understanding-machine-config-operator.adoc
  modules/unmanaged-operators.adoc
Labels: size/L

#27323 Terminology style updates for welcome content
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: size/S

#27154 BZ#1804764 - Clarify when instance metadata endpoint is in `status.noProxy`
  modules/installation-configure-proxy.adoc
  networking/enable-cluster-wide-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27134 BZ#1871145 - An IPAM static address must be specified with CIDR
  modules/nw-multus-create-network.adoc
  modules/nw-multus-ipam-object.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#17565 OSDOCS-715 pull secret doc improvements
  installing/install_config/customizations.adoc
  modules/builds-creating-secrets.adoc
  modules/images-allow-pods-to-reference-images-from-secure-registries.adoc
  modules/images-imagestream-import-images-private-registry.adoc
  modules/images-update-global-pull-secret.adoc
  modules/samples-operator-overview.adoc
  openshift_images/configuring-samples-operator.adoc
  openshift_images/image-streams-manage.adoc
  openshift_images/managing_images/using-image-pull-secrets.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27250 odo fixes.
  cli_reference/developer_cli_odo/understanding-odo.adoc
  modules/developer-cli-odo-deploying-the-back-end-component.adoc
  modules/developer-cli-odo-deploying-the-front-end-component.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27267 RN-BZ-1894525 release notes known issue
  virt/virt-2-5-release-notes.adoc
Labels: CNV, lgtm, size/XS

#27347 Last minute pull of 3.11 RHSA; scheduled for next release
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, size/XS
