Repository openshift/openshift-docs, pull requests merged in 2020-12, with the labels that each got.

#27737 [enterprise-4.6] Adding topic for logs in Kibana
  _topic_map.yml
  logging/cluster-logging-viewing.adoc
  logging/cluster-logging-visualizer.adoc
  logging/cluster-logging.adoc
  logging/viewing/images
  modules/cluster-logging-visualizer-indices.adoc
  modules/cluster-logging-visualizer-kibana.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: size/L

#27738 [enterprise-4.5] Adding topic for logs in Kibana
  _topic_map.yml
  logging/cluster-logging-viewing.adoc
  logging/cluster-logging-visualizer.adoc
  logging/cluster-logging.adoc
  logging/viewing/images
  modules/cluster-logging-visualizer-indices.adoc
  modules/cluster-logging-visualizer-kibana.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: size/L

#22300 BZ-1726771: Clarifying project restore procedure
  day_two_guide/topics/proc_backing-up-project.adoc
  day_two_guide/topics/proc_restoring-project.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#27181 Add glibc version 2.28+ limitation for using opm
  modules/olm-installing-opm.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#27739 [enterprise-4.7] Adding topic for logs in Kibana
  _topic_map.yml
  logging/cluster-logging-viewing.adoc
  logging/cluster-logging-visualizer.adoc
  logging/cluster-logging.adoc
  logging/viewing/images
  modules/cluster-logging-visualizer-indices.adoc
  modules/cluster-logging-visualizer-kibana.adoc
  modules/cluster-logging-visualizer-launch.adoc
Labels: size/L

#27736 Module header typo fix
  modules/installation-special-config-crony.adoc
  security/container_security/security-hosts-vms.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27710 Errata update for 4.5.21 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#27754 missed edits in previous PR
  release_notes/ocp-4-4-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/S

#27404 Changes on spec.logStore.elasticsearch.nodeCount not reflected when decreasing the number of nodes
  logging/config/cluster-logging-log-store.adoc
  modules/cluster-logging-elasticsearch-scaledown.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27169 OSDOCS-1146, added router sharding content for Dedicated
  modules/dedicated-configuring-your-application-routes.adoc
Labels: size/M

#27756 mtc style changes for 4.6
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_3_4/upgrading-migration-tool-3-4.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_1_4/upgrading-migration-tool-4-1-4.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  migration/migrating_4_2_4/upgrading-migration-tool-4-2-4.adoc
  modules/common-attributes.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-error-messages.adoc
  modules/migration-excluding-resources.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-upgrading-migration-tool-3.adoc
  modules/migration-upgrading-migration-tool-4.adoc
  modules/migration-using-cpma.adoc
  modules/migration-using-must-gather.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/XL

#27764 Follow-up edit to PR#27169
  modules/dedicated-configuring-your-application-routes.adoc
Labels: size/XS

#27759 MTC style updates for 4.5
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-with-cpma.adoc
  migration/migrating_3_4/planning-migration-3-to-4.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_3_4/upgrading-migration-tool-3-4.adoc
  migration/migrating_4_1_4/deploying-cam-4-1-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_1_4/upgrading-migration-tool-4-1-4.adoc
  migration/migrating_4_2_4/deploying-cam-4-2-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  migration/migrating_4_2_4/upgrading-migration-tool-4-2-4.adoc
  modules/common-attributes.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-changing-migration-plan-limits.adoc
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-excluding-resources.adoc
  modules/migration-installing-cam-operator-ocp-3.adoc
  modules/migration-installing-cam-operator-ocp-4.adoc
  modules/migration-installing-cpma.adoc
  modules/migration-known-issues.adoc
  modules/migration-launching-cam.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-prerequisites.adoc
  modules/migration-restic-errors.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-understanding-cam.adoc
  modules/migration-understanding-cpma.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-deprecated-gvks.adoc
  modules/migration-upgrading-migration-tool-3.adoc
  modules/migration-upgrading-migration-tool-4.adoc
  modules/migration-using-cpma.adoc
  modules/migration-using-must-gather.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XL

#27600 Separate MachineSet sections into two modules
  machine_management/manually-scaling-machineset.adoc
  modules/machineset-delete-policy.adoc
  modules/machineset-manually-scaling.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27771 [enterprise-4.4] Separate MachineSet sections into two modules
  machine_management/manually-scaling-machineset.adoc
  modules/machineset-delete-policy.adoc
  modules/machineset-manually-scaling.adoc
Labels: branch/enterprise-4.4, size/M

#27542 Reviewed troubleshooting for 4.6 revisions.
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-cannot-boot.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm-inspecting-logs.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-cluster-nodes-will-not-pxe.adoc
  modules/ipi-install-troubleshooting-install-config.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26916 Clarify MachineHealthChecks for Masters
  modules/machine-health-checks-about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27774 Typo fix
  modules/dedicated-configuring-your-application-routes.adoc
Labels: size/XS

#24846 Required key name for NoSchedule taints on master nodes
  modules/nodes-scheduler-taints-tolerations-about.adoc
  modules/nodes-scheduler-taints-tolerations-adding.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lifecycle/stale, size/M

#27740 [3.11] .NET Core: remove information about EOL versions
  using_images/s2i_images/dot_net_core.adoc
Labels: branch/enterprise-3.11, size/L

#27649 topic_map: use oVirt instead of RHV for OKD
  _topic_map.yml
Labels: size/S

#27772 API terminology and formatting updates for the 4.5 Release Notes
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#27422 nproc * 1/2 MiB of each container memory may be taken by RHEL8 kernel slabs
  nodes/containers/nodes-containers-using.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27704 cluster capacity: add missing rbac rules
  modules/nodes-cluster-resource-levels-job.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27136 RPM repo version name is not matched with release version(OCPv4.6)
  modules/rhel-preparing-playbook-machine.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27749 Errata update for 4.4.31 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4, size/S

#27624 Bug 1891614: Update mlx dpdk base on cve-2020-14386
  modules/nw-sriov-dpdk-example-mellanox.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, bugzilla/severity-urgent, bugzilla/valid-bug, size/XS

#27799 welcome: mention oVirt on OKD
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#26514 OSDOCS-1462 loglevel for Registry Config
  modules/registry-operator-configuration-resource-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/S

#27763 BZ#1722638 Clarity for vSphere compute machine creation
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-vsphere-machines.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27813 BZ1903547: Update podman req to v2.0+
  modules/olm-building-operator-catalog-image.adoc
  modules/olm-creating-index-image.adoc
  modules/olm-installing-opm.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-mirroring-package-manifest-catalog.adoc
  modules/olm-pruning-index-image.adoc
  modules/olm-testing-operator-catalog-image.adoc
  modules/olm-updating-index-image.adoc
  modules/olm-updating-operator-catalog-image.adoc
  modules/osdk-building-bundle-image.adoc
  modules/osdk-installing-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27826 Removing OKE abbreviation as it is not allowed
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#25276 Logging add must gather
  _topic_map.yml
  logging/troubleshooting/cluster-logging-must-gather.adoc
  modules/cluster-logging-must-gather-about.adoc
  modules/cluster-logging-must-gather-collecting.adoc
  modules/gathering-data-specific-features.adoc
  support/gathering-cluster-data.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27728 OSSMDOC-179
  modules/ossm-sidecar-injection.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27486 Terminology style updates for the rest of the security book
  modules/about-etcd-encryption.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/builds-adding-input-secrets-configmaps.adoc
  modules/builds-input-secrets-configmaps.adoc
  modules/customize-certificates-add-service-serving-apiservice.adoc
  modules/customize-certificates-add-service-serving-configmap.adoc
  modules/customize-certificates-add-service-serving-crd.adoc
  modules/customize-certificates-add-service-serving-mutating-webhook.adoc
  modules/customize-certificates-add-service-serving-validating-webhook.adoc
  modules/customize-certificates-add-service-serving.adoc
  modules/customize-certificates-replace-default-router.adoc
  modules/customize-certificates-rotate-service-serving.adoc
  modules/disabling-etcd-encryption.adoc
  modules/enabling-etcd-encryption.adoc
  modules/security-build-inputs.adoc
  modules/security-deploy-secrets.adoc
  modules/security-hardening-how.adoc
  modules/security-monitoring-cluster-logging.adoc
  modules/security-monitoring-events.adoc
  modules/security-network-namespaces.adoc
  modules/security-registries-quay.adoc
  modules/security-storage-persistent.adoc
  security/certificate_types_descriptions/ingress-certificates.adoc
  security/certificate_types_descriptions/proxy-certificates.adoc
  security/certificate_types_descriptions/service-ca-certificates.adoc
  security/certificate_types_descriptions/user-provided-certificates-for-default-ingress.adoc
  security/container_security/security-build.adoc
  security/container_security/security-deploy.adoc
  security/container_security/security-hosts-vms.adoc
  security/container_security/security-platform.adoc
  security/container_security/security-registries.adoc
  security/pod-vulnerability-scan.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27845 Terminology style updates for the rest of the security book
  modules/about-etcd-encryption.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/builds-adding-input-secrets-configmaps.adoc
  modules/builds-input-secrets-configmaps.adoc
  modules/customize-certificates-add-service-serving-apiservice.adoc
  modules/customize-certificates-add-service-serving-configmap.adoc
  modules/customize-certificates-add-service-serving-crd.adoc
  modules/customize-certificates-add-service-serving-mutating-webhook.adoc
  modules/customize-certificates-add-service-serving-validating-webhook.adoc
  modules/customize-certificates-add-service-serving.adoc
  modules/customize-certificates-replace-default-router.adoc
  modules/customize-certificates-rotate-service-serving.adoc
  modules/disabling-etcd-encryption.adoc
  modules/enabling-etcd-encryption.adoc
  modules/proxy-certificates.adoc
  modules/security-build-inputs.adoc
  modules/security-deploy-secrets.adoc
  modules/security-hardening-how.adoc
  modules/security-monitoring-cluster-logging.adoc
  modules/security-monitoring-events.adoc
  modules/security-network-namespaces.adoc
  modules/security-registries-quay.adoc
  modules/security-storage-persistent.adoc
  modules/service-ca-certificates.adoc
  security/certificate-types-descriptions.adoc
  security/container_security/security-build.adoc
  security/container_security/security-deploy.adoc
  security/container_security/security-hosts-vms.adoc
  security/container_security/security-platform.adoc
  security/container_security/security-registries.adoc
  security/pod-vulnerability-scan.adoc
Labels: size/L

#27846 [enterprise-4.4] Logging add must gather
  logging/troubleshooting/cluster-logging-must-gather.adoc
  modules/cluster-logging-must-gather-about.adoc
  modules/cluster-logging-must-gather-collecting.adoc
  modules/gathering-data-specific-features.adoc
  support/gathering-cluster-data.adoc
Labels: size/L

#27398 Terminology style updates for auth book
  _topic_map.yml
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/managing-security-context-constraints.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/identity-provider-about-request-header.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-apache-custom-proxy-configuration.adoc
  modules/identity-provider-basic-authentication-CR.adoc
  modules/identity-provider-config-map.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/identity-provider-default-CR.adoc
  modules/identity-provider-github-CR.adoc
  modules/identity-provider-gitlab-CR.adoc
  modules/identity-provider-google-CR.adoc
  modules/identity-provider-htpasswd-CR.adoc
  modules/identity-provider-htpasswd-secret.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/identity-provider-keystone-CR.adoc
  modules/identity-provider-ldap-CR.adoc
  modules/identity-provider-ldap-secret.adoc
  modules/identity-provider-oidc-CR.adoc
  modules/identity-provider-overview.adoc
  modules/identity-provider-registering-github.adoc
  modules/identity-provider-request-header-CR.adoc
  modules/identity-provider-secret.adoc
  modules/ldap-failover-configure-apache.adoc
  modules/ldap-failover-configure-openshift.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/ldap-syncing-activedir.adoc
  modules/ldap-syncing-augmented-activedir.adoc
  modules/ldap-syncing-config-activedir.adoc
  modules/ldap-syncing-config-augmented-activedir.adoc
  modules/ldap-syncing-config-rfc2307.adoc
  modules/ldap-syncing-nesting.adoc
  modules/ldap-syncing-rfc2307-user-defined-error.adoc
  modules/ldap-syncing-rfc2307-user-defined.adoc
  modules/ldap-syncing-rfc2307.adoc
  modules/ldap-syncing-running-all-ldap.adoc
  modules/ldap-syncing-running-openshift.adoc
  modules/ldap-syncing-running-subset.adoc
  modules/oauth-configuring-token-inactivity-timeout-clients.adoc
  modules/oauth-configuring-token-inactivity-timeout.adoc
  modules/oauth-internal-tokens.adoc
  modules/oauth-troubleshooting-api-events.adoc
  modules/rbac-api-authentication.adoc
  modules/rbac-creating-cluster-role.adoc
  modules/rbac-overview.adoc
  modules/rbac-users.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/security-context-constraints-creating.adoc
  modules/security-context-constraints-example.adoc
  modules/security-context-constraints-pre-allocated-values.adoc
  modules/security-context-constraints-rbac.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/service-accounts-granting-roles.adoc
  modules/service-accounts-using-credentials-externally.adoc
  modules/user-agent-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27852 Terminology style updates for auth book
  _topic_map.yml
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/managing-security-context-constraints.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/identity-provider-about-request-header.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-apache-custom-proxy-configuration.adoc
  modules/identity-provider-basic-authentication-CR.adoc
  modules/identity-provider-config-map.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/identity-provider-default-CR.adoc
  modules/identity-provider-github-CR.adoc
  modules/identity-provider-gitlab-CR.adoc
  modules/identity-provider-google-CR.adoc
  modules/identity-provider-htpasswd-CR.adoc
  modules/identity-provider-htpasswd-secret.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/identity-provider-keystone-CR.adoc
  modules/identity-provider-ldap-CR.adoc
  modules/identity-provider-ldap-secret.adoc
  modules/identity-provider-oidc-CR.adoc
  modules/identity-provider-overview.adoc
  modules/identity-provider-registering-github.adoc
  modules/identity-provider-request-header-CR.adoc
  modules/identity-provider-secret.adoc
  modules/ldap-failover-configure-apache.adoc
  modules/ldap-failover-configure-openshift.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/ldap-syncing-activedir.adoc
  modules/ldap-syncing-augmented-activedir.adoc
  modules/ldap-syncing-config-activedir.adoc
  modules/ldap-syncing-config-augmented-activedir.adoc
  modules/ldap-syncing-config-rfc2307.adoc
  modules/ldap-syncing-nesting.adoc
  modules/ldap-syncing-rfc2307-user-defined-error.adoc
  modules/ldap-syncing-rfc2307-user-defined.adoc
  modules/ldap-syncing-rfc2307.adoc
  modules/ldap-syncing-running-all-ldap.adoc
  modules/ldap-syncing-running-openshift.adoc
  modules/ldap-syncing-running-subset.adoc
  modules/oauth-internal-tokens.adoc
  modules/oauth-troubleshooting-api-events.adoc
  modules/rbac-api-authentication.adoc
  modules/rbac-creating-cluster-role.adoc
  modules/rbac-overview.adoc
  modules/rbac-users.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/security-context-constraints-creating.adoc
  modules/security-context-constraints-example.adoc
  modules/security-context-constraints-pre-allocated-values.adoc
  modules/security-context-constraints-rbac.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/service-accounts-granting-roles.adoc
  modules/service-accounts-using-credentials-externally.adoc
  modules/user-agent-overview.adoc
Labels: size/L

#27853 Terminology style updates for auth book
  _topic_map.yml
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/managing-security-context-constraints.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/identity-provider-about-basic-authentication.adoc
  modules/identity-provider-about-request-header.adoc
  modules/identity-provider-add.adoc
  modules/identity-provider-apache-custom-proxy-configuration.adoc
  modules/identity-provider-basic-authentication-CR.adoc
  modules/identity-provider-config-map.adoc
  modules/identity-provider-configuring-apache-request-header.adoc
  modules/identity-provider-default-CR.adoc
  modules/identity-provider-github-CR.adoc
  modules/identity-provider-gitlab-CR.adoc
  modules/identity-provider-google-CR.adoc
  modules/identity-provider-htpasswd-CR.adoc
  modules/identity-provider-htpasswd-secret.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/identity-provider-keystone-CR.adoc
  modules/identity-provider-ldap-CR.adoc
  modules/identity-provider-ldap-secret.adoc
  modules/identity-provider-oidc-CR.adoc
  modules/identity-provider-overview.adoc
  modules/identity-provider-registering-github.adoc
  modules/identity-provider-request-header-CR.adoc
  modules/identity-provider-secret.adoc
  modules/ldap-failover-configure-apache.adoc
  modules/ldap-failover-configure-openshift.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/ldap-syncing-activedir.adoc
  modules/ldap-syncing-augmented-activedir.adoc
  modules/ldap-syncing-config-activedir.adoc
  modules/ldap-syncing-config-augmented-activedir.adoc
  modules/ldap-syncing-config-rfc2307.adoc
  modules/ldap-syncing-nesting.adoc
  modules/ldap-syncing-rfc2307-user-defined-error.adoc
  modules/ldap-syncing-rfc2307-user-defined.adoc
  modules/ldap-syncing-rfc2307.adoc
  modules/ldap-syncing-running-all-ldap.adoc
  modules/ldap-syncing-running-openshift.adoc
  modules/ldap-syncing-running-subset.adoc
  modules/oauth-internal-tokens.adoc
  modules/oauth-troubleshooting-api-events.adoc
  modules/rbac-api-authentication.adoc
  modules/rbac-creating-cluster-role.adoc
  modules/rbac-overview.adoc
  modules/rbac-users.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/security-context-constraints-creating.adoc
  modules/security-context-constraints-example.adoc
  modules/security-context-constraints-pre-allocated-values.adoc
  modules/security-context-constraints-rbac.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/service-accounts-granting-roles.adoc
  modules/service-accounts-using-credentials-externally.adoc
  modules/user-agent-overview.adoc
Labels: size/L

#27814 Modify initialDelaySeconds definition
  modules/application-health-about.adoc
  modules/application-health-configuring.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27524 BZ-1886892: Adding note to set 'GODEBUG=x509ignoreCN=0'
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#27428 Terminology style updates for odo and helm
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  cli_reference/developer_cli_odo/odo-release-notes.adoc
  cli_reference/tkn_cli/op-tkn-reference.adoc
  modules/developer-cli-odo-adding-storage-to-the-application-components.adoc
  modules/developer-cli-odo-connecting-the-database.adoc
  modules/developer-cli-odo-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
  modules/developer-cli-odo-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/developer-cli-odo-creating-services-from-yaml-files.adoc
  modules/developer-cli-odo-deploying-the-back-end-component.adoc
  modules/developer-cli-odo-exposing-the-components-to-the-public.adoc
  modules/developer-cli-odo-installing-odo-on-windows.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-push-workflow.adoc
  modules/developer-cli-odo-using-command-completion.adoc
  modules/helm-adding-helm-chart-repositories.adoc
  modules/helm-creating-credentials-and-certificates-to-add-helm-repositories.adoc
  modules/helm-installing-helm.adoc
Labels: Peer Review Needed, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27870 Terminology style updates for odo and helm
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  cli_reference/tkn_cli/op-tkn-reference.adoc
  modules/developer-cli-odo-adding-storage-to-the-application-components.adoc
  modules/developer-cli-odo-connecting-the-database.adoc
  modules/developer-cli-odo-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/developer-cli-odo-converting-an-s2i-component-into-a-devfile-component.adoc
  modules/developer-cli-odo-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/developer-cli-odo-creating-services-from-yaml-files.adoc
  modules/developer-cli-odo-deploying-the-back-end-component.adoc
  modules/developer-cli-odo-exposing-the-components-to-the-public.adoc
  modules/developer-cli-odo-installing-odo-on-windows.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-push-workflow.adoc
  modules/developer-cli-odo-using-command-completion.adoc
  modules/helm-installing-helm.adoc
Labels: size/L

#27871 Terminology style updates for odo and helm
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  cli_reference/developer_cli_odo/odo-release-notes.adoc
  cli_reference/tkn_cli/op-tkn-reference.adoc
  modules/developer-cli-odo-connecting-the-database.adoc
  modules/developer-cli-odo-connecting-your-application-to-multiple-services-using-openshift-service-catalog.adoc
  modules/developer-cli-odo-creating-and-deploying-a-nodejs-application-with-odo.adoc
  modules/developer-cli-odo-creating-services-from-yaml-files.adoc
  modules/developer-cli-odo-deploying-the-back-end-component.adoc
  modules/developer-cli-odo-exposing-the-components-to-the-public.adoc
  modules/developer-cli-odo-installing-odo-on-windows.adoc
  modules/developer-cli-odo-linking-both-components.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-push-workflow.adoc
  modules/developer-cli-odo-using-command-completion.adoc
  modules/helm-installing-helm.adoc
Labels: size/L

#27727 Non-preempting PriorityClass
  modules/nodes-pods-priority-configuring.adoc
  modules/nodes-pods-priority-preempt-about.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/S

#27726 [WIP] OSDOCS-1654: Release notes for non-preempting priority class option
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, do-not-merge/work-in-progress, size/XS

#27492 Terminology formatting updates
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/pruning-images.adoc
  modules/registry-configuring-storage-aws-user-infra.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/registry-operator-config-resources-secret-aws.adoc
  modules/registry-operator-config-resources-secret-azure.adoc
  modules/registry-operator-config-resources-secret-gcp.adoc
  registry/configuring-registry-operator.adoc
  rest_api/config_apis/image-config-openshift-io-v1.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27876 [Enterprise-4.7] Terminology formatting updates
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/pruning-images.adoc
  modules/registry-configuring-storage-aws-user-infra.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/registry-operator-config-resources-secret-aws.adoc
  modules/registry-operator-config-resources-secret-azure.adoc
  modules/registry-operator-config-resources-secret-gcp.adoc
  registry/configuring-registry-operator.adoc
  rest_api/config_apis/image-config-openshift-io-v1.adoc
Labels: size/L

#27879 [enterprise-4.5] Terminology formatting updates
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/pruning-images.adoc
  modules/registry-configuring-storage-aws-user-infra.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/registry-operator-config-resources-secret-aws.adoc
  modules/registry-operator-config-resources-secret-azure.adoc
  modules/registry-operator-config-resources-secret-gcp.adoc
  registry/configuring-registry-operator.adoc
  rest_api/config_apis/image-config-openshift-io-v1.adoc
Labels: size/L

#27880 [enterprise-4.4] Terminology formatting updates
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/pruning-images.adoc
  modules/registry-configuring-storage-aws-user-infra.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/registry-exposing-secure-registry-manually.adoc
  modules/registry-operator-config-resources-secret-aws.adoc
  modules/registry-operator-config-resources-secret-azure.adoc
  modules/registry-operator-config-resources-secret-gcp.adoc
  registry/configuring-registry-operator.adoc
  rest_api/config_apis/image-config-openshift-io-v1.adoc
Labels: size/L

#27878 Rosaupdate
  modules/rosa-installing-prerequisites.adoc
Labels: branch/enterprise-4.5, size/XS

#27805 OSSMDOC-184
  modules/ossm-cr-example.adoc
  modules/ossm-cr-gateway.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27812 OSSMDOC-162 Resolve headings generating errors.
  _topic_map.yml
  modules/ossm-security-cert-manage-1x.adoc
  modules/ossm-security-cert-manage.adoc
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v1x/ossm-architecture.adoc
  service_mesh/v1x/removing-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
  service_mesh/v2x/ossm-architecture.adoc
  service_mesh/v2x/removing-ossm.adoc
Labels: Service Mesh, size/L

#27433 Changes for upcoming IBM Z P pipelines support
  modules/op-installing-tkn-on-linux.adoc
  modules/op-release-notes-1-2.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#26738 Uninstall cluster-logging from OCP leaves behind cluster-logging operator and elastic-search operator
  modules/cluster-logging-uninstall.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27891 [enterprise-4.4] Uninstall cluster-logging from OCP leaves behind cluster-logging operator and elastic-search operator
  modules/cluster-logging-uninstall.adoc
Labels: size/M

#27895 Uninstall cluster-logging from OCP leaves behind cluster-logging operator and elastic-search operator 4.5
  modules/cluster-logging-uninstall.adoc
Labels: size/S

#27872 Update documentation to current interface on cloud.rh.c
  modules/dedicated-managing-dedicated-administrators.adoc
Labels: size/XS

#27874 CNV - version bump and upgrade note
  modules/virt-document-attributes.adoc
  modules/virt-monitoring-upgrade-status.adoc
  modules/virt-upgrade-pathways.adoc
  virt/upgrading-virt.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27778 BZ1875663 - remove flag
  upgrading/automated_upgrades.adoc
Labels: Peer Review Done, branch/enterprise-3.11, lgtm, size/XS

#27800 An egress firewall in ovs-multitenant ignores global projects
  admin_guide/managing_networking.adoc
Labels: branch/enterprise-3.11, size/XS

#27606 SRVCOM-1115: Updating docs to new OCP guidelines
  _topic_map.yml
  modules/creating-serverless-apps-kn.adoc
  modules/creating-serverless-apps-yaml.adoc
  modules/knative-serving-advanced-config.adoc
  modules/odc-splitting-traffic-between-revisions-using-developer-perspective.adoc
  modules/serverless-config-replicas.adoc
  modules/serverless-install-eventing-web-console.adoc
  modules/serverless-install-eventing-yaml.adoc
  modules/serverless-install-serving-web-console.adoc
  modules/serverless-install-serving-yaml.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-using-cluster-logging-find-logs-knative-serving-components.adoc
  modules/serverless-using-cluster-logging-find-logs-services-deployed.adoc
  modules/serverless-workflow-autoscaling-kn.adoc
  modules/serverless-workflow-autoscaling.adoc
  modules/serverless-workflow-basic.adoc
  modules/serverless-workflow-traffic-splitting-flags.adoc
  modules/serverless-workflow-traffic-splitting.adoc
  modules/traffic-splitting-kn.adoc
  modules/verifying-serverless-app-deployment.adoc
  serverless/architecture/serverless-serving-architecture.adoc
  serverless/installing_serverless/installing-knative-eventing.adoc
  serverless/installing_serverless/installing-knative-serving.adoc
  serverless/installing_serverless/removing-openshift-serverless.adoc
  serverless/installing_serverless/serverless-install-config-options.adoc
  serverless/knative_serving/cluster-logging-serverless.adoc
  serverless/knative_serving/configuring-knative-serving-autoscaling.adoc
  serverless/knative_serving/serving-kn-commands.adoc
  serverless/knative_serving/splitting-traffic-between-revisions-knative.adoc
  serverless/knative_serving/splitting-traffic-between-revisions.adoc
  serverless/serverless-getting-started.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XL

#27854 BZ 1898042: disclaimers about VMs getting OOM killed
  modules/virt-configuring-guest-memory-overcommitment.adoc
  modules/virt-disabling-guest-memory-overhead-accounting.adoc
  virt/virtual_machines/advanced_vm_management/virt-managing-guest-memory.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27810 BZ1893600 - clarify disk and partitions in "separate /var partitioning"
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-disk-partitioning.adoc
  modules/installation-user-infra-machines-advanced.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27733 OSDOCS-1455: Updating backup and restore procedures
  day_two_guide/topics/con_etcd_backup.adoc
  day_two_guide/topics/proc_backing-up-application-data.adoc
  day_two_guide/topics/proc_backing-up-etcd.adoc
  day_two_guide/topics/proc_restoring-data-new-pvc.adoc
  day_two_guide/topics/proc_restoring-etcd.adoc
  day_two_guide/topics/proc_restoring-master.adoc
  day_two_guide/topics/proc_restoring-node.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#27644 Update docs to align with MTC UI
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-replication-repository-to-cam.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-downloading-logs.adoc
  modules/migration-running-migration-plan-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27918 multiarch issue 652
  modules/installation-requirements-user-infra.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, lgtm, size/XS

#27904 bug 1901592 - correcting oc adm release command flags
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27656 Fix #27579: Add escape for each double-quotes
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27481 BZ-1892614 Update the optional pull-secret procedure
  modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27654 Fix #27583: Add cp for openshift-baremetal-install
  modules/ipi-install-extracting-the-openshift-installer.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#25611 Added creating infra node content
  modules/creating-an-infra-node.adoc
  modules/creating-infra-machines.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/L

#27875 Rel Notes doc text for 4.5.22 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XXL

#27940 BZ1809630: mention DNS PTR records
  modules/installation-dns-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27765 Ported the proxy setting from upstream to downstream
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
  modules/ipi-install-setting-proxy-settings-within-install-config.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27776 [DRAFT] BZ:1856361 crojob spec and variables
  dev_guide/cron_jobs.adoc
Labels: Peer Review Done, size/L

#24450 BZ#1760675 Preventing user workloads from being scheduled to infra nodes
  machine_management/creating-infrastructure-machinesets.adoc
  modules/binding-infra-node-workloads-using-taints-tolerations.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#27916 GH#27697 Update min_tx_rate
  modules/nw-sriov-network-attachment.adoc
  modules/nw-sriov-network-object.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27156 OSDOCS-1549, updated Operator installation docs for Dedicated
  administering_a_cluster/dedicated-admin-role.adoc
  modules/olm-installing-operators-from-operatorhub.adoc
Labels: branch/enterprise-4.3, size/S

#27942 Update extract path for opm install
  modules/olm-installing-opm.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#27976 [enterprise-4.5] Update extract path for opm install
  modules/olm-installing-opm.adoc
Labels: branch/enterprise-4.5, size/XS

#27896 Updating terminology for cluster logging
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-external.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring-cr.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/config/cluster-logging-curator.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-storage-considerations.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-logging.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-cpu-memory.adoc
  modules/cluster-logging-curator-schedule.adoc
  modules/cluster-logging-curator-troubleshoot.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-empty.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-forwarding-about.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-kibana-scaling.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-log-forward-update.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
  modules/cluster-logging-log-store-status-comp.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-systemd-scaling.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-viewing-logs-console.adoc
  modules/cluster-logging-visualizer-kibana.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27978 [enterprise-4.7] Updating terminology for cluster logging
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-external.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring-cr.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/config/cluster-logging-curator.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-storage-considerations.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-logging.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-cpu-memory.adoc
  modules/cluster-logging-curator-schedule.adoc
  modules/cluster-logging-curator-troubleshoot.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-empty.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-forwarding-about.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-kibana-scaling.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-log-forward-update.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
  modules/cluster-logging-log-store-status-comp.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-systemd-scaling.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-viewing-logs-console.adoc
  modules/cluster-logging-visualizer-kibana.adoc
Labels: size/L

#27977 [enterprise-4.6] Updating terminology for cluster logging
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-external.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring-cr.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/config/cluster-logging-curator.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-storage-considerations.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-logging.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-cpu-memory.adoc
  modules/cluster-logging-curator-schedule.adoc
  modules/cluster-logging-curator-troubleshoot.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-empty.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-forwarding-about.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-kibana-scaling.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-log-forward-update.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
  modules/cluster-logging-log-store-status-comp.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-systemd-scaling.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-viewing-logs-console.adoc
  modules/cluster-logging-visualizer-kibana.adoc
Labels: size/L

#27932 Update cluster maximums for OpenShift 4.6
  modules/openshift-cluster-maximums.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27979 [enterprise-4.5] Updating terminology for cluster logging
  logging/cluster-logging-eventrouter.adoc
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-external.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring-cr.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/config/cluster-logging-curator.adoc
  logging/config/cluster-logging-log-store.adoc
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-storage-considerations.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-logging.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-collector-log-forward-enable.adoc
  modules/cluster-logging-collector-log-forwarding-disable.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-configuring-node-selector.adoc
  modules/cluster-logging-cpu-memory.adoc
  modules/cluster-logging-curator-schedule.adoc
  modules/cluster-logging-curator-troubleshoot.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-about.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-empty.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-forwarding-about.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-kibana-scaling.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
  modules/cluster-logging-log-store-status-comp.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-systemd-scaling.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cluster-logging-viewing-logs-console.adoc
  modules/cluster-logging-visualizer-kibana.adoc
  modules/cluster-openshift-controller-manager-operators.adoc
Labels: size/L

#27983 [enterprise-4.4] Updating terminology for cluster logging
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-collector.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/config/cluster-logging-curator.adoc
  logging/config/cluster-logging-elasticsearch.adoc
  logging/config/cluster-logging-eventrouter.adoc
  logging/config/cluster-logging-external.adoc
  logging/config/cluster-logging-management.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-logging.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-about-elasticsearch.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-collector-chunk.adoc
  modules/cluster-logging-collector-limits.adoc
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-collector-log-forward-enable.adoc
  modules/cluster-logging-collector-log-forwarding-disable.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-configuring-node-selector.adoc
  modules/cluster-logging-curator-configuration.adoc
  modules/cluster-logging-curator-schedule.adoc
  modules/cluster-logging-curator-tolerations.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-limits.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-about.adoc
  modules/cluster-logging-elasticsearch-persistent-storage-empty.adoc
  modules/cluster-logging-elasticsearch-status-viewing.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-kibana-scaling.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-log-forwarding-about.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
  modules/cluster-logging-management-state-changing-es.adoc
  modules/cluster-logging-management-state-changing.adoc
  modules/cluster-logging-uninstall.adoc
Labels: size/L

#27782 adding guidance for how to markup error text
  contributing_to_docs/doc_guidelines.adoc
Labels: size/M

#27986 virt-installing-qemu-guest-agent: drop non-prerequisite
  virt/virtual_machines/virt-installing-qemu-guest-agent.adoc
Labels: CNV, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27985 virt-installing-qemu-guest-agent: shorten procedure
  modules/virt-installing-qemu-guest-agent-on-linux-vm.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27984 Fix log forwarding CR name
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-log-forward-update.adoc
  modules/cluster-logging-log-forwarding-disable.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27998 Fix typo in Tolerating all taints
  modules/nodes-scheduler-taints-tolerations-about.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27900 GH27762: RHV IPI doesn't need static IP for internal DNS
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/XS

#27394 OSDOCS-1605 - add vSphere static IP config procedure from 4-6 RNs
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/installation-vsphere-machines.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#28003 Bug BZ1888527 removed operator hub note
  modules/olm-operatorhub-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27773 BZ1846458 - Remove note that ES scaling is not supported
  logging/config/cluster-logging-log-store.adoc
  modules/cluster-logging-elasticsearch-scaledown.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28016 API terminology and formatting updates for the 4.6 Release Notes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.6

#27811 Bug 1832483, clarify master limit
  modules/architecture-machine-roles.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#28029 [enterprise-4.5]Bug 1832483, clarify master limit
  modules/architecture-machine-roles.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/M

#28030 [enterprise-4.4]Bug 1832483, clarify master limit
  modules/architecture-machine-roles.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/M

#27922 BZ#1721567: overlay2 driver reqs XFS
  install/host_preparation.adoc
  scaling_performance/optimizing_storage.adoc
Labels: branch/enterprise-3.11, size/S

#28033 Follow-up to PR#27917
  modules/openshift-cluster-maximums-environment.adoc
Labels: size/XS

#27589 Add quick access for cluster admins topic.
  getting_started_rosa/accessing-rosa-cluster.adoc
  modules/rosa-accessing-your-cluster-quick.adoc
  modules/rosa-accessing-your-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#26607 OSDOCS-1519 document SameSite route annotation
  modules/nw-route-specific-annotations.adoc
Labels: Peer Review Needed, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28039 Follow-up to PR#27917
  modules/openshift-cluster-maximums-environment.adoc
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: branch/enterprise-4.7, size/XS

#28035 Update "Red Hat Operators reference" modules for API object & unwrap changes
  modules/cloud-credential-operator.adoc
  modules/cluster-authentication-operator.adoc
  modules/cluster-autoscaler-operator.adoc
  modules/cluster-dns-operator.adoc
  modules/cluster-image-registry-operator.adoc
  modules/cluster-kube-scheduler-operator.adoc
  modules/cluster-monitoring-operator.adoc
  modules/cluster-network-operator.adoc
  modules/cluster-openshift-controller-manager-operators.adoc
  modules/cluster-samples-operator.adoc
  modules/cluster-storage-operator.adoc
  modules/etcd-operator.adoc
  modules/ingress-operator.adoc
  modules/kube-apiserver-operator.adoc
  modules/kube-controller-manager-operator.adoc
  modules/machine-api-operator.adoc
  modules/machine-config-operator.adoc
  modules/node-tuning-operator.adoc
  modules/openshift-apiserver-operator.adoc
  modules/operator-marketplace.adoc
  modules/prometheus-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#26917 Bug 1787281, Added Optimizing networking section
  _topic_map.yml
  modules/ipsec-impact-networking.adoc
  modules/optimizing-mtu-networking.adoc
  scalability_and_performance/optimizing-networking.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/M

#28036 Bug 1902584: note workaround for advanced networking issues
  modules/installation-user-infra-machines-static-network.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, bugzilla/invalid-bug, bugzilla/severity-low, size/XS

#28052 remove ocp topic from osd docs
  _topic_map.yml
Labels: Peer Review Done, branch/enterprise-4.3, size/XS

#28047 API terminology and formatting updates for the 4.7 Release Notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/L

#27662 Monitoring term style updates for 4.6 and 4.7
  modules/monitoring-accessing-alerting-rules-for-your-project.adoc
  modules/monitoring-accessing-the-alerting-ui.adoc
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-configurable-monitoring-components.adoc
  modules/monitoring-configuring-a-local-persistent-volume-claim.adoc
  modules/monitoring-configuring-alert-receivers.adoc
  modules/monitoring-configuring-the-monitoring-stack.adoc
  modules/monitoring-creating-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  modules/monitoring-creating-scrape-sample-alerts.adoc
  modules/monitoring-creating-user-defined-workload-monitoring-configmap.adoc
  modules/monitoring-disabling-monitoring-for-user-defined-projects.adoc
  modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
  modules/monitoring-exploring-the-visualized-metrics.adoc
  modules/monitoring-exposing-custom-application-metrics-for-horizontal-pod-autoscaling.adoc
  modules/monitoring-getting-information-about-alerts-silences-and-alerting-rules.adoc
  modules/monitoring-granting-users-permission-to-configure-monitoring-for-user-defined-projects.adoc
  modules/monitoring-granting-users-permission-to-monitor-user-defined-projects.adoc
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
  modules/monitoring-managing-silences.adoc
  modules/monitoring-modifying-retention-time-for-prometheus-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-optimizing-alerting-for-user-defined-projects.adoc
  modules/monitoring-querying-metrics-for-user-defined-projects-as-a-developer.adoc
  modules/monitoring-reducing-latency-for-alerting-rules-that-do-not-query-platform-metrics.adoc
  modules/monitoring-removing-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-searching-alerts-silences-and-alerting-rules.adoc
  modules/monitoring-sending-notifications-to-external-systems.adoc
  modules/monitoring-setting-a-scrape-sample-limit-for-user-defined-projects.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-up-metrics-collection-for-user-defined-projects.adoc
  modules/monitoring-specifying-how-a-service-is-monitored.adoc
  modules/monitoring-support-considerations.adoc
  monitoring/configuring-the-monitoring-stack.adoc
  monitoring/enabling-monitoring-for-user-defined-projects.adoc
  monitoring/managing-alerts.adoc
  monitoring/reviewing-monitoring-dashboards.adoc
  monitoring/troubleshooting-monitoring-issues.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#27939 Updating infrastructure components list to include components for monitoring user-defined projects
  modules/infrastructure-components.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27118 Document causes of automated reboots and MCO pause behavior
  architecture/control-plane.adoc
  modules/understanding-machine-config-operator.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28069 [enterprise-4.5] Update "Red Hat Operators reference" modules for API object & unwrap changes
  modules/cloud-credential-operator.adoc
  modules/cluster-authentication-operator.adoc
  modules/cluster-autoscaler-operator.adoc
  modules/cluster-dns-operator.adoc
  modules/cluster-image-registry-operator.adoc
  modules/cluster-kube-scheduler-operator.adoc
  modules/cluster-monitoring-operator.adoc
  modules/cluster-network-operator.adoc
  modules/cluster-openshift-controller-manager-operators.adoc
  modules/cluster-samples-operator.adoc
  modules/cluster-storage-operator.adoc
  modules/etcd-operator.adoc
  modules/ingress-operator.adoc
  modules/kube-apiserver-operator.adoc
  modules/kube-controller-manager-operator.adoc
  modules/machine-api-operator.adoc
  modules/machine-config-operator.adoc
  modules/node-tuning-operator.adoc
  modules/openshift-apiserver-operator.adoc
  modules/operator-marketplace.adoc
  modules/prometheus-operator.adoc
Labels: branch/enterprise-4.5, size/L

#24905 Windows containers GA
  _topic_map.yml
  images/mixed-windows-linux-workloads.png
  images/wmco-design.png
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  modules/accessing-windows-node-using-rdp.adoc
  modules/accessing-windows-node-using-ssh.adoc
  modules/collecting-docker-logs-windows.adoc
  modules/collecting-kube-node-logs-windows.adoc
  modules/collecting-windows-application-event-logs.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/configuring-secret-for-wmco.adoc
  modules/creating-runtimeclass.adoc
  modules/deleting-wmco-namespace.adoc
  modules/installing-wmco-using-cli.adoc
  modules/installing-wmco-using-web-console.adoc
  modules/investigating-why-windows-machine-compute-node.adoc
  modules/machine-api-overview.adoc
  modules/machine-delete.adoc
  modules/machineset-creating.adoc
  modules/machineset-manually-scaling.adoc
  modules/sample-windows-workload-deployment.adoc
  modules/uninstalling-wmco.adoc
  modules/windows-machine-config-operator.adoc
  modules/windows-machineset-aws.adoc
  modules/windows-machineset-azure.adoc
  modules/windows-node-services.adoc
  modules/windows-pod-placement.adoc
  modules/windows-workload-management.adoc
  modules/wmco-does-not-install.adoc
  modules/wmco-upgrades.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  operators/operator-reference.adoc
  support/troubleshooting/troubleshooting-windows-container-workload-issues.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-aws.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-azure.adoc
  windows_containers/disabling-windows-container-workloads.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/images
  windows_containers/modules
  windows_containers/removing-windows-nodes.adoc
  windows_containers/scheduling-windows-workloads.adoc
  windows_containers/understanding-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes.adoc
  windows_containers/windows-node-upgrades.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/XXL

#28072 [enterprise-4.7] Windows containers GA
  _topic_map.yml
  images/mixed-windows-linux-workloads.png
  images/wmco-design.png
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  modules/accessing-windows-node-using-rdp.adoc
  modules/accessing-windows-node-using-ssh.adoc
  modules/collecting-docker-logs-windows.adoc
  modules/collecting-kube-node-logs-windows.adoc
  modules/collecting-windows-application-event-logs.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/configuring-secret-for-wmco.adoc
  modules/creating-runtimeclass.adoc
  modules/deleting-wmco-namespace.adoc
  modules/installing-wmco-using-cli.adoc
  modules/installing-wmco-using-web-console.adoc
  modules/investigating-why-windows-machine-compute-node.adoc
  modules/machine-api-overview.adoc
  modules/machine-delete.adoc
  modules/machineset-creating.adoc
  modules/machineset-manually-scaling.adoc
  modules/sample-windows-workload-deployment.adoc
  modules/uninstalling-wmco.adoc
  modules/windows-machine-config-operator.adoc
  modules/windows-machineset-aws.adoc
  modules/windows-machineset-azure.adoc
  modules/windows-node-services.adoc
  modules/windows-pod-placement.adoc
  modules/windows-workload-management.adoc
  modules/wmco-does-not-install.adoc
  modules/wmco-upgrades.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  operators/operator-reference.adoc
  support/troubleshooting/troubleshooting-windows-container-workload-issues.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-aws.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-azure.adoc
  windows_containers/disabling-windows-container-workloads.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/images
  windows_containers/modules
  windows_containers/removing-windows-nodes.adoc
  windows_containers/scheduling-windows-workloads.adoc
  windows_containers/understanding-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes.adoc
  windows_containers/windows-node-upgrades.adoc
Labels: branch/enterprise-4.7, size/XXL

#28073 [enterprise-4.6] Windows containers GA
  _topic_map.yml
  images/mixed-windows-linux-workloads.png
  images/wmco-design.png
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  modules/accessing-windows-node-using-rdp.adoc
  modules/accessing-windows-node-using-ssh.adoc
  modules/collecting-docker-logs-windows.adoc
  modules/collecting-kube-node-logs-windows.adoc
  modules/collecting-windows-application-event-logs.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/configuring-secret-for-wmco.adoc
  modules/creating-runtimeclass.adoc
  modules/deleting-wmco-namespace.adoc
  modules/installing-wmco-using-cli.adoc
  modules/installing-wmco-using-web-console.adoc
  modules/investigating-why-windows-machine-compute-node.adoc
  modules/machine-api-overview.adoc
  modules/machine-delete.adoc
  modules/machineset-creating.adoc
  modules/machineset-manually-scaling.adoc
  modules/sample-windows-workload-deployment.adoc
  modules/uninstalling-wmco.adoc
  modules/windows-machine-config-operator.adoc
  modules/windows-machineset-aws.adoc
  modules/windows-machineset-azure.adoc
  modules/windows-node-services.adoc
  modules/windows-pod-placement.adoc
  modules/windows-workload-management.adoc
  modules/wmco-does-not-install.adoc
  modules/wmco-upgrades.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  operators/operator-reference.adoc
  support/troubleshooting/troubleshooting-windows-container-workload-issues.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-aws.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-azure.adoc
  windows_containers/disabling-windows-container-workloads.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/images
  windows_containers/modules
  windows_containers/removing-windows-nodes.adoc
  windows_containers/scheduling-windows-workloads.adoc
  windows_containers/understanding-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes.adoc
  windows_containers/windows-node-upgrades.adoc
Labels: branch/enterprise-4.6, size/XXL

#28074 WINC Xref typo
  windows_containers/disabling-windows-container-workloads.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27941 MIG-421 Using unified logger in MTC
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-using-mig-log-reader.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28083 Revert WINC
  _topic_map.yml
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  operators/operator-reference.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#27832 Errata update for 4.6.8 release
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#28086 Updating link to point to Kubernetes 1.19 release notes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#28088 [enterprise-4.6] Update podman req to v2.0+
  modules/olm-creating-index-image.adoc
  modules/olm-installing-opm.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-pruning-index-image.adoc
  modules/olm-testing-operator-catalog-image.adoc
  modules/olm-updating-index-image.adoc
  modules/osdk-building-bundle-image.adoc
  modules/osdk-installing-cli.adoc
Labels: size/S

#28089 [enterprise-4.7] Update podman req to v1.9.3+
  modules/olm-creating-index-image.adoc
  modules/olm-installing-opm.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-pruning-index-image.adoc
  modules/olm-testing-operator-catalog-image.adoc
  modules/olm-updating-index-image.adoc
  modules/osdk-building-bundle-image.adoc
  modules/osdk-installing-cli.adoc
Labels: size/S

#28024 BZ#1874098: image reg, cdn, and firewalls
  modules/configuring-firewall.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28096 [enterprise-4.4] BZ#1874098: image reg, cdn, and firewalls
  modules/configuring-firewall.adoc
Labels: size/XS

#28097 [enterprise-4.5] BZ#1874098: image reg, cdn, and firewalls
  modules/configuring-firewall.adoc
Labels: size/XS

#27227 GH#27212 - Use only the node name in the command
  modules/graceful-shutdown.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28092 CO-1159 new feature blurb
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/XS

#27594 Add eus channel info
  modules/understanding-upgrade-channels.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#25018 Fixup source terminal for admin_guide
  admin_guide/allocating_node_resources.adoc
  admin_guide/assembly_restore-etcd-quorum.adoc
  admin_guide/building_dependency_trees.adoc
  admin_guide/cluster_capacity.adoc
  admin_guide/diagnostics_tool.adoc
  admin_guide/disabling_features.adoc
  admin_guide/encrypting_data.adoc
  admin_guide/high_availability.adoc
  admin_guide/idling_applications.adoc
  admin_guide/image_policy.adoc
  admin_guide/image_signatures.adoc
  admin_guide/index.adoc
  admin_guide/ipsec.adoc
  admin_guide/iptables.adoc
  admin_guide/limits.adoc
  admin_guide/manage_nodes.adoc
  admin_guide/manage_rbac.adoc
  admin_guide/manage_scc.adoc
  admin_guide/manage_users.adoc
  admin_guide/managing_networking.adoc
  admin_guide/managing_pods.adoc
  admin_guide/managing_projects.adoc
  admin_guide/monitoring_images.adoc
  admin_guide/multiproject_quota.adoc
  admin_guide/node_problem_detector.adoc
  admin_guide/out_of_resource_handling.adoc
  admin_guide/overcommit.adoc
  admin_guide/pruning_resources.adoc
  admin_guide/quota.adoc
  admin_guide/router.adoc
  admin_guide/scheduling/custom_scheduler.adoc
  admin_guide/scheduling/descheduler.adoc
  admin_guide/scheduling/node_affinity.adoc
  admin_guide/scheduling/pod_affinity.adoc
  admin_guide/scheduling/pod_placement.adoc
  admin_guide/scheduling/scheduler.adoc
  admin_guide/scheduling/taints_tolerations.adoc
  admin_guide/sdn_troubleshooting.adoc
  admin_guide/seccomp.adoc
  admin_guide/securing_builds.adoc
  admin_guide/service_accounts.adoc
  admin_guide/sysctls.adoc
  admin_guide/tcp_ingress_external_ports.adoc
  admin_guide/topics/creating-LC-and-ASG-cluster-auto-scaler.adoc
  admin_guide/topics/creating-primed-images-cluster-auto-scaler.adoc
  admin_guide/topics/deploying-cluster-auto-scaler.adoc
  admin_guide/topics/pod-priority-disable.adoc
  admin_guide/topics/proc_adding-hosts.adoc
  admin_guide/topics/proc_etcd-quorum-single-node-v2-v3.adoc
  admin_guide/topics/proc_etcd-quorum-static-pod.adoc
  admin_guide/topics/proc_removing-failed-etcd-member.adoc
  admin_guide/topics/testing-auto-scaler.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#22465 Fix Elasticsearch rolling restart
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/M

#27996 Add recommendation around service name impacting the pods
  modules/how-to-plan-your-environment-according-to-application-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27843 bz1900036
  modules/cnf-installing-the-performance-addon-operator.adoc
Labels: Telco, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28114 [enterprise-4.5] Fix Elasticsearch rolling restart
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/M

#28117 Enterprise 4.6
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/M

#28087 WINC support notice and feature name update
  _topic_map.yml
  windows_containers/understanding-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#27468 MIG-415, MIG 416: Direct image and PV migration
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-creating-migration-plan-cam.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#28122 [enterprise-4.6] WINC support notice
  _topic_map.yml
  windows_containers/understanding-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes.adoc
Labels: branch/enterprise-4.6, size/S

#28119 [enterprise-4.7] Fix Elasticsearch rolling restart
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/M

#28127 Fix typos from CP error
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/XS

#28128 [enterprise-4.5] Fix typos from CP error
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/XS

#28130 [enterprise-4.6] Fix typos from CP error
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/XS

#28132 Use only the node name in the command
  modules/graceful-shutdown.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28107 [enterprise-4.4] GH#27697 Update min_tx_rate
  modules/nw-sriov-network-object.adoc
Labels: branch/enterprise-4.4, size/XS

#28131 [enterprise-4.7] Fix typos from CP error
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: size/XS

#26604 Log Forwarding add info when endpoint goes down
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28055 Rel Notes doc text for 4.5.23 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#28138 [enterprise-4.5] Log Forwarding add info when endpoint goes down
  modules/cluster-logging-collector-log-forward-about.adoc
Labels: size/XS
