Repository openshift/openshift-docs, pull requests merged in 2021-02, with the labels that each got.

#28319 MTC 1.4 UI updates (1.4.0)
  modules/migration-creating-migration-plan-cam.adoc
Labels: size/M

#28973 Errata update for 4.6.15 release
  release_notes/ocp-4-6-release-notes.adoc
Labels: branch/enterprise-4.6, size/S

#28917 Fixed error for BZ 1921544
  modules/gathering-data-specific-features.adoc
Labels: Peer Review Done, branch/enterprise-4.6, lgtm, size/XS

#28949 [SRVCOM-967] Updating terms and clean up serverless docs sections
  modules/serverless-cluster-sizing-req.adoc
  serverless/installing_serverless/installing-openshift-serverless.adoc
Labels: size/M

#28950 [SRVCOM-967] Updating terms and clean up serverless docs sections
  modules/serverless-cluster-sizing-req.adoc
  serverless/installing_serverless/installing-openshift-serverless.adoc
Labels: size/M

#28946 BZ-1921831: Excluding etcd quorum guard pods from output
  modules/dr-restoring-cluster-state.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/restore-replace-crashlooping-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28544 Add Helm module.
  _topic_map.yml
  cli_reference/helm_cli/disabling-helm-chart-repositories.adoc
  modules/helm-disabling-helm-chart-repository-in-the-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#28921 Bug 1919393 - Updates Python script
  modules/compliance-review.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, lgtm, size/XS

#28993 Update migration-controller SCC on OCP3.10/earlier (1.4.0)
  modules/migration-upgrading-migration-tool-3.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28943 Bug 1921281: remove --export flag from oc
  modules/templates-create-from-existing-object.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/S

#28519 CNV-5258: FS overhead space
  _topic_map.yml
  modules/virt-how-fs-overhead-affects-space-vm-disks.adoc
  modules/virt-overriding-default-fs-overhead-value.adoc
  virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, size/M

#28961 Bug 1916082 bring forward updates to Automatically pruning images
  modules/pruning-images.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/M

#28667 Pipelines 1.13.0 cli download link version bump
  modules/op-installing-tkn-on-linux-using-rpm.adoc
  modules/op-installing-tkn-on-linux.adoc
  modules/op-installing-tkn-on-macos.adoc
  modules/op-installing-tkn-on-windows.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#28980 [SRVCOM-1115] Updating OCP 4.5 serverless docs to new OCP guidelines
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  modules/creating-serverless-apps-kn.adoc
  modules/serverless-about-collecting-data.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-list-source-types.adoc
  modules/serverless-list-source.adoc
  modules/serverless-metering-datasources.adoc
  modules/serverless-metering-queries.adoc
  modules/serverless-metering-reports.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-rn-1-7-0.adoc
  modules/verifying-serverless-app-deployment.adoc
  serverless/architecture/serverless-event-architecture.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/event_sources/serverless-apiserversource.adoc
  serverless/event_sources/serverless-kn-source.adoc
  serverless/event_sources/serverless-pingsource.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/L

#28942 Added a section about inclusive language to the 4.7 release notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/XS

#28968 Update FC link to RHEL8 doc
  storage/persistent_storage/persistent-storage-fibre.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29021 Follow-up edits to web console localization in the 4.7 release notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/XS

#28807 Change target platforms assembly language to indicate support rather than possibility
  _topic_map.yml
  installing/install_config/installation-types.adoc
Labels: Peer Review Done, size/XS

#28779 OperatorHub inconsistent to Documentation
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/migration-configuring-mcg.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-pods-vertical-autoscaler-install.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
  pipelines/installing-pipelines.adoc
  post_installation_configuration/preparing-for-users.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, okd-only, size/L

#29032 remove old preview bot
  .travis.yml
Labels: size/XS

#29030 [enterprise-4.4] OperatorHub inconsistent to Documentation
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/migration-configuring-mcg.adoc
  modules/nodes-descheduler-installing.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  operators/olm-adding-operators-to-cluster.adoc
  pipelines/installing-pipelines.adoc
Labels: size/L

#29039 add banner for aro 4 docs
  _templates/_page_openshift.html.erb
Labels: size/XS

#28401 OpenShift Virtualization 2.6 release notes template
  _topic_map.yml
  modules/virt-supported-cluster-version.adoc
  virt/virt-2-5-release-notes.adoc
  virt/virt-2-6-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, size/L

#28662 Add release notes for SR-IOV DPDK library functions
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#29046 remove old preview
  .travis.yml
Labels: size/XS

#29047 remove old preview
  .travis.yml
Labels: size/XS

#29048 remove old preview
  .travis.yml
Labels: size/XS

#29049 remove old preview
  .travis.yml
Labels: size/XS

#28313 P/Z Service Mesh
  modules/jaeger-deploy-default.adoc
  modules/jaeger-deploy-streaming.adoc
  modules/jaeger-rn-known-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-supported-configurations.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
Labels: Peer Review Done, Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28853 BYO RHEL docs need to be updated to include RHEL 7.9 support 4.5
  modules/installation-requirements-user-infra.adoc
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/XS

#28173 OSDOCS-1648: Adding API performance dashboard to the list
  monitoring/reviewing-monitoring-dashboards.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#29011 Errata update for 4.5.30 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#29025 OSDOCS-1648: Adding API dashboard to release notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#28859 Known issue for BZ#1887007
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#29062 adding dummy file for 2.6 release notes
  _topic_map.yml
  virt/virt-2-6-release-notes.adoc
Labels: CNV, lgtm, size/S

#29038 Add CSI snapshot support note for OCS, OpenShift Virtualization in 4-6
  storage/container_storage_interface/persistent-storage-csi-snapshots.adoc
Labels: Peer Review Done, Peer Review Needed, branch/enterprise-4.6, lgtm, size/XS

#28203 CNF-802 Infrastructure-provided enablement/disablement of interrupt processing for guaranteed pod CPUs
  modules/cnf-configure_for_irq_dynamic_load_balancing.adoc
  modules/cnf-creating-the-performance-profile-object.adoc
  modules/cnf-installing-the-performance-addon-operator.adoc
  modules/cnf-managing-device-interrupt-processing-for-guaranteed-pod-isolated-cpus.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  modules/cnf-upgrading-performance-addon-operator.adoc
  modules/cnf-use-device-interrupt-processing-for-isolated-cpus.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, lgtm, size/L

#28436 TELCODOCS-146 - document hyperthreading config in OCP
  modules/cnf-about_hyperthreading_for_low_latency_and_real_time_applications.adoc
  modules/configuring_hyperthreading_for_a_cluster.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, size/L

#29060 Fixed syntax error for link with spaces
  modules/understanding-upgrade-channels.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28676 OSSMDOC-215
  service_mesh/v2x/ossm-security.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#28893 OSDOCS-1653: Adding TP docs for scheduler profiles
  _topic_map.yml
  modules/nodes-scheduler-profiles-about.adoc
  modules/nodes-scheduler-profiles-configuring.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
  nodes/scheduling/nodes-scheduler-profiles.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#28892 OSDOCS-1653: Adding RN for scheduler profiles and deprecating schedul…
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#28745 BZ-1907905: Adding a note about waiting if login fails
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#29077 BZ-1907905: Adding a note about waiting if login fails
  modules/dr-restoring-cluster-state.adoc
Labels: size/XS

#28982 Rename left-nav Welcome to About
  _topic_map.yml
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28761 CNV 778 - Booting VMs in EFI Mode
  _topic_map.yml
  modules/virt-about-efi-mode-for-vms.adoc
  modules/virt-booting-efi-mode.adoc
  virt/virtual_machines/advanced_vm_management/virt-efi-mode-for-vms.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, size/M

#29089 Fix topic title section to use title case
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#29090 [enterprise-4.7] changes for TELCODOCS-146
  modules/cnf-about_hyperthreading_for_low_latency_and_real_time_applications.adoc
  modules/configuring_hyperthreading_for_a_cluster.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: size/L

#29040 Fix IPI supported methods table
  installing/install_config/installation-types.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, size/XS

#29022 Errata update for 4.4.33 release
  release_notes/ocp-4-4-release-notes.adoc
Labels: branch/enterprise-4.4, size/S

#29070 BZ#1916393 Verification step for CSR approval
  modules/installation-approve-csrs.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#29104 [enterprise-4.5] BZ#1916393 Verification step for CSR approval
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.5, size/S

#29105 [enterprise-4.4] BZ#1916393 Verification step for CSR approval
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.4, size/S

#27343 Proxy container in elasticsearch pods restarting due to oom-kill during test of scale cluster
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#29106 [enterprise-4.5] Proxy container in elasticsearch pods restarting due to oom-kill during test of scale cluster
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: size/M

#29107 [enterprise-4.7] Proxy container in elasticsearch pods restarting due to oom-kill during test of scale cluster
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: size/M

#29108 [enterprise-4.6] Proxy container in elasticsearch pods restarting due to oom-kill during test of scale cluster
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: size/M

#28850 Errata update for 3.11.380 release
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/L

#29098 search: OKD4 version and URL workaround
  _javascripts/hc-search.js
Labels: size/XS

#29097 Removing incorrect source specification on a table
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28956 EgressIPs automatically reassign
  modules/nw-egress-ips-about.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/S

#29116 Fix merge conflict with PR#26070 and PR#26521 typo in 4-7
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Needed, branch/enterprise-4.7, size/XS

#29115 Fix merge conflict with PR#26070 and PR#26521 typo in 4-6
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#29094 The field is not fully indented
  modules/virt-example-nmstate-multiple-interfaces.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29126 Removing incorrect source specification on a table
  modules/installation-user-infra-machines-static-network.adoc
Labels: size/XS

#29127 Removing incorrect source specification on a table
  modules/installation-user-infra-machines-static-network.adoc
Labels: size/XS

#28059 BZ 1906890 - Documentation refers to append-bootstrap.ign but the example of that file has been removed from the documentation
  modules/installation-vsphere-machines.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28382 BZ-1907402: Removing startup probe references as they aren't supporte…
  modules/application-health-about.adoc
  modules/application-health-configuring.adoc
Labels: Peer Review Done, branch/enterprise-4.4, size/M

#29125 [enterprise-4.7] Updated image tag
  modules/gathering-data-specific-features.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#29051 [enterprise-4.7] Update to the Insights Operator RN
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#29130 luks: use AES-CBC for FIPS 140-2
  modules/installation-special-config-encrypt-disk-tang.adoc
  modules/installation-special-config-encrypt-disk-tpm2.adoc
Labels: size/XS

#28831 CNV-6480 Add note on WFFC limitations to virt documentation
  modules/virt-creating-storage-class.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29061 describe pull secret differences from OCP
  modules/installation-obtaining-installer.adoc
Labels: okd-only, size/XS

#29139 Use 'OpenShift CLI' name unambiguously
  _topic_map.yml
  cli_reference/openshift_cli/administrator-cli-commands.adoc
  cli_reference/openshift_cli/configuring-cli.adoc
  cli_reference/openshift_cli/developer-cli-commands.adoc
  cli_reference/openshift_cli/extending-cli-plugins.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/cli-about-cli.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in.adoc
  modules/cli-logging-out.adoc
  modules/cli-using-cli.adoc
  serverless/installing_serverless/installing-kn.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  virt/install/uninstalling-virt-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#29148 Pt 2: Use 'OpenShift CLI' name unambiguously
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  cli_reference/opm-cli.adoc
  modules/cli-about-cli.adoc
  modules/olm-about-opm.adoc
  modules/olm-installing-opm.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/S

#29146 [enterprise-4.7] Use 'OpenShift CLI' name unambiguously
  _topic_map.yml
  cli_reference/openshift_cli/administrator-cli-commands.adoc
  cli_reference/openshift_cli/configuring-cli.adoc
  cli_reference/openshift_cli/developer-cli-commands.adoc
  cli_reference/openshift_cli/extending-cli-plugins.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/cli-about-cli.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in.adoc
  modules/cli-logging-out.adoc
  modules/cli-using-cli.adoc
  serverless/installing_serverless/installing-kn.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  virt/install/uninstalling-virt-cli.adoc
Labels: size/L

#29150 [enterprise-4.6] Use 'OpenShift CLI' name unambiguously
  _topic_map.yml
  cli_reference/openshift_cli/administrator-cli-commands.adoc
  cli_reference/openshift_cli/configuring-cli.adoc
  cli_reference/openshift_cli/developer-cli-commands.adoc
  cli_reference/openshift_cli/extending-cli-plugins.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/installing_rhv/installing-rhv-customizations.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/cli-about-cli.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in.adoc
  modules/cli-logging-out.adoc
  modules/cli-using-cli.adoc
  serverless/installing_serverless/installing-kn.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  virt/install/uninstalling-virt-cli.adoc
Labels: size/L

#28594 OSSMDOC-200
  modules/ossm-security-auth-policy.adoc
  service_mesh/v2x/ossm-security.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#28291 Machine API - Support for Google Cloud Customer Managed Encryption Keys
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-enabling-customer-managed-encryption.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#29160 Fix `section title out of sequence` warning
  networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28978 BZ#1916453 - SR-IOV Operator device config - master node selection
  modules/nw-sriov-configuring-device.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/S

#29044 Update SSH private key generation in the latest OKD installation documentation
  modules/builds-source-secret-ssh-key-auth.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29170 fixed [source,yaml] typo
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/configuring_hyperthreading_for_a_cluster.adoc
Labels: Telco, size/XS

#29169 CNF-802 - typo in performance profile snippet
  modules/cnf-managing-device-interrupt-processing-for-guaranteed-pod-isolated-cpus.adoc
Labels: Telco, branch/enterprise-4.7, lgtm, size/XS

#29143 BZ#1916374 Approving CSRs is two step process
  modules/installation-approve-csrs.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#29183 [enterprise-4.6] BZ#1916374 Approving CSRs are is step process
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.6, size/M

#29185 [enterprise-4.5] BZ#1916374 Approving CSRs are is step process
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.5, size/M

#29186 [enterprise-4.4] BZ#1916374 Approving CSRs are is step process
  modules/installation-approve-csrs.adoc
Labels: branch/enterprise-4.4, size/M

#29136 OSDOCS-1715 AlertmanagerConfig CRD not supported
  modules/monitoring-support-considerations.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#29056 Rename RHV to include/switch to oVirt
  installing/install_config/installation-types.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installing-rhv-verifying-rhv-environment.adoc
Labels: okd-only, size/M

#29158 Documentation indicates OpenShiftSDN is a (preferred) supported default network CNI Provider
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/nw-operator-cr.adoc
  networking/openshift_sdn/about-openshift-sdn.adoc
Labels: okd-only, size/M

#28373 Install and restricted install on power
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#28972 add multipathing to installation procedure
  modules/installation-complete-user-infra.adoc
  modules/installation-ibm-z-kvm-user-infra-machines-iso.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/installation-infrastructure-user-infra.adoc
  modules/installation-network-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/L

#28151 BZ#1853249 allocating node resources
  _topic_map.yml
  admin_guide/allocating_node_resources.adoc
  admin_guide/limits.adoc
  admin_guide/out_of_resource_handling.adoc
  scaling_performance/using_cpu_manager.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XL

#28960 BZ 1916218 Inserted missing project name in in deleting metrics secre…
  modules/restore-replace-crashlooping-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27912 Packaging UPI playbooks for download - OSDOCS1665
  installing/installing_openstack/installing-openstack-user-kuryr.adoc
  installing/installing_openstack/installing-openstack-user.adoc
  installing/installing_openstack/uninstalling-openstack-user.adoc
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/installation-osp-downloading-modules.adoc
  modules/installation-osp-downloading-playbooks.adoc
  modules/installation-osp-emptying-worker-pools.adoc
  modules/installation-uninstall-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#28609 Add egress-router-cni to the docs (OSDOCS-979)
  _topic_map.yml
  modules/nw-egress-router-about.adoc
  modules/nw-egress-router-network-attachment.adoc
  modules/nw-egress-router-pod-ovn.adoc
  modules/nw-egress-router-redirect-mode-ovn.adoc
  networking/ovn_kubernetes_network_provider/deploying-egress-router-ovn-redirection.adoc
  networking/ovn_kubernetes_network_provider/using-an-egress-router-ovn.adoc
Labels: branch/enterprise-4.7, size/L

#28932 BZ1918270 - update Azure storage class kind annotations in docs
  modules/dynamic-provisioning-azure-disk-definition.adoc
  modules/storage-azure-create-storage-class.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#28637 GRPA-3235: Document disk mirroring during installation
  installing/install_config/installing-customizing.adoc
  modules/installation-special-config-encrypt-disk-tang.adoc
  modules/installation-special-config-encrypt-disk-tpm2.adoc
  modules/installation-special-config-mirrored-disk.adoc
Labels: branch/enterprise-4.7, size/L

#28538 Add OLM OperatorConditions docs
  _topic_map.yml
  modules/olm-crds.adoc
  modules/olm-operatorconditions-about.adoc
  modules/olm-overriding-operatorconditions.adoc
  modules/olm-supported-operatorconditions.adoc
  modules/olm-updating-use-operatorconditions.adoc
  operators/admin/olm-managing-operatorconditions.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
  operators/understanding/olm/olm-operatorconditions.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/L

#28372 Rework OSDK intros + Golang examples
  _topic_map.yml
  modules/building-memcached-operator-using-osdk.adoc
  modules/managing-memcached-operator-using-olm.adoc
  modules/osdk-about-openapi-validation.adoc
  modules/osdk-ansible-support.adoc
  modules/osdk-architecture.adoc
  modules/osdk-bundling-deploying-using-olm.adoc
  modules/osdk-golang-build-run.adoc
  modules/osdk-golang-controller-configs.adoc
  modules/osdk-golang-controller-rbac-markers.adoc
  modules/osdk-golang-controller-reconcile-loop.adoc
  modules/osdk-golang-controller-resources.adoc
  modules/osdk-golang-create-api-controller.adoc
  modules/osdk-golang-create-cr.adoc
  modules/osdk-golang-create-deploy.adoc
  modules/osdk-golang-create-project.adoc
  modules/osdk-golang-define-api.adoc
  modules/osdk-golang-generate-crd.adoc
  modules/osdk-golang-implement-controller.adoc
  modules/osdk-golang-manager.adoc
  modules/osdk-golang-multi-group-apis.adoc
  modules/osdk-golang-run-in-cluster.adoc
  modules/osdk-golang-run-locally.adoc
  modules/osdk-helm-chart-support.adoc
  modules/osdk-how-csv-gen-works.adoc
  modules/osdk-installing-cli-linux-macos.adoc
  modules/osdk-manager-file.adoc
  modules/osdk-monitoring-prometheus-operator-support.adoc
  modules/osdk-project-scaffolding-layout.adoc
  modules/osdk-project-staffolding-layout.adoc
  modules/osdk-workflow.adoc
  operators/operator_sdk/golang/images
  operators/operator_sdk/golang/modules
  operators/operator_sdk/golang/osdk-golang-quickstart.adoc
  operators/operator_sdk/golang/osdk-golang-tutorial.adoc
  operators/operator_sdk/osdk-about.adoc
  operators/operator_sdk/osdk-ansible.adoc
  operators/operator_sdk/osdk-appendices.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
  operators/operator_sdk/osdk-getting-started.adoc
  operators/operator_sdk/osdk-helm.adoc
  operators/operator_sdk/osdk-installing-cli.adoc
  operators/operator_sdk/osdk-migrating-to-v0-1-0.adoc
  operators/operator_sdk/osdk-scorecard.adoc
  operators/understanding/crds/crd-extending-api-with-crds.adoc
  operators/understanding/olm-understanding-operatorhub.adoc
  welcome/index.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XXL

#28728 Add docs for pullsecrets in CatalogSources
  modules/images-update-global-pull-secret.adoc
  modules/olm-accessing-images-private-registries.adoc
  modules/olm-creating-catalog-from-index.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/L

#29213 Test AutoMerge
  .travis.yml
  automerge.sh
Labels: size/S

#29201 [enterprise-4.6] Packaging UPI playbooks for download - OSDOCS1665
  installing/installing_openstack/installing-openstack-user-kuryr.adoc
  installing/installing_openstack/installing-openstack-user.adoc
  installing/installing_openstack/uninstalling-openstack-user.adoc
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-deleting-bootstrap-resources.adoc
  modules/installation-osp-downloading-modules.adoc
  modules/installation-osp-downloading-playbooks.adoc
  modules/installation-osp-emptying-worker-pools.adoc
  modules/installation-uninstall-infra.adoc
Labels: size/L

#29223 Use v2 config for APIs
  api-config.yaml
Labels: branch/enterprise-4.7, size/M

#29217 [skip netlify] updates to automerge
  .travis.yml
  automerge.sh
Labels: size/S

#29226 Fix typo
  nodes/scheduling/nodes-scheduler-node-affinity.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29232 updates to automerge
  automerge.sh
Labels: size/XS

#29233 updates to automerge
  automerge.sh
Labels: size/XS

#29236 [skip netlify] removed file in root
  ossm-threescale-authentication.adoc
Labels: size/L

#29239 updated automerge
  .travis.yml
  automerge.sh
Labels: size/M

#29240 updated automerge
  .travis.yml
  automerge.sh
Labels: size/M

#29241 updated automerge
  .travis.yml
  automerge.sh
Labels: size/M

#29242 [skip netlify] testing minor change
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
Labels: size/XS

#28746 CNF-802 Infrastructure-provided enablement/disablement of interrupt processing for guaranteed pod CPUs Telco - release note
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/XS

#28022 Add Kuryr docs about limitation of service without selector
  modules/installation-osp-kuryr-known-limitations.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#28778 Egress Router CNI (OSDOCS-979)
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#29199 Rel Notes doc text for 4.6.16 release
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#28739 BZ1913826
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, size/S

#29174 47bugs known
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, size/S

#29249 Add TP note to kdump doc
  modules/investigating-kernel-crashes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#28403 [OSP] Document PV limit workaround
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#29197 [enterprise-4.4] Updated payload_Key description
  modules/cluster-logging-collector-syslog.adoc
Labels: Peer Review Done, size/XS

#29195 Updated payloadKey parameter description
  modules/cluster-logging-collector-log-forward-syslog.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#29196 [enterprise-4.5] Updated payload_Key description
  modules/cluster-logging-collector-syslog.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#28797 [OSP] Deprecate computeFlavor in install-config.yaml
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#29261 Fixes two typos in the 4.5 Release Notes
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#29266 Update examples to Ignition config spec v3-2-0
  modules/installation-special-config-crony.adoc
  modules/installation-special-config-kmod.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#27911 OSDOCS#1491 - Add IPsec support
  _topic_map.yml
  modules/nw-operator-cr.adoc
  modules/nw-ovn-ipsec-certificates.adoc
  modules/nw-ovn-ipsec-encryption.adoc
  modules/nw-ovn-ipsec-traffic.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  networking/ovn_kubernetes_network_provider/about-ipsec-ovn.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#27907 OVN-Kubernetes supports IPsec
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#28981 Add OLM/OSDK release notes for 4.7
  release_notes/ocp-4-7-release-notes.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#27919 MIG-466: MTC version and image names for 1.4.0
  modules/common-attributes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#27373 MIG-412: MTC migration rollback (1.4.0)
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-rolling-back-migration-cli.adoc
  modules/migration-rolling-back-migration-web-console.adoc
  modules/migration-running-migration-plan-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#28908 Direct volume/image migration requirements (1.4.0)
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#29285 Revert "mtc rollback"
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-rolling-back-migration-cli.adoc
  modules/migration-rolling-back-migration-web-console.adoc
  modules/migration-running-migration-plan-cam.adoc
Labels: size/L

#29287 mtc rollback and module correction
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-error-messages.adoc
  modules/migration-manually-rolling-back-migration.adoc
  modules/migration-rolling-back-migration-cli.adoc
  modules/migration-rolling-back-migration-web-console.adoc
  modules/migration-running-migration-plan-cam.adoc
Labels: size/L

#28994 Backup: original reclaim policy annotation, BSL/VSL: migcontroller label (1.4.0)
  _topic_map.yml
  migration/migrating_3_4/deploying-cam-3-4.adoc
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-mtc-custom-resources.adoc
  modules/migration-mtc-workflow.adoc
  modules/migration-prerequisites.adoc
  modules/migration-running-migration-plan-cam.adoc
  modules/migration-viewing-migration-crs.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#28918 Updating OCP3 internal images for OCP4 cluster (1.4.1)
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  modules/migration-prerequisites.adoc
  modules/migration-updating-internal-images.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/L

#29219 MIG528: DVM and missing node selectors to Troubleshooting (1.4.1)
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-dvm-error-node-selectors.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#29198 Errata update for 4.5.31 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#28748 CNF-846 - Deploy a VRF CNI plugin that makes it possible to assign different secondary networks to different VRF - release note
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, size/XS

#28600 CNV-7494 Documented interface for offline VM snapshots
  modules/virt-creating-offline-vm-snapshot-web.adoc
  modules/virt-deleting-vm-snapshot-web.adoc
  modules/virt-restoring-vm-from-snapshot-web.adoc
  virt/virtual_machines/virtual_disks/virt-managing-offline-vm-snapshots.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, lgtm, size/M

#28818 Update GCP disk encryption docs based on KMS SA support issues
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#29264 Updated term based on customer feedback
  modules/architecture-container-application-benefits.adoc
Labels: branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, size/XS

#28456 OSDOCS-1616 using Cluster Samples Operator disconnected mirroring assistance
  installing/install_config/installing-restricted-networks-preparations.adoc
  modules/images-samples-operator-deprecated-image-stream.adoc
  modules/installation-images-samples-disconnected-mirroring-assist.adoc
  openshift_images/configuring-samples-operator.adoc
  openshift_images/image-streams-manage.adoc
  openshift_images/samples-operator-alt-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#29247 BZ1926248: Manual changes for upgrading MTC 1.3 to 1.4 (1.4.0)
  migration/migrating_3_4/upgrading-migration-tool-3-4.adoc
  migration/migrating_4_1_4/upgrading-migration-tool-4-1-4.adoc
  migration/migrating_4_2_4/upgrading-migration-tool-4-2-4.adoc
  modules/migration-upgrading-from-mtc-1-3.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, priority/critical-urgent, size/M

#29309 HCO bump for 2.4.6
  modules/virt-document-attributes.adoc
  modules/virt-monitoring-upgrade-status.adoc
Labels: CNV, branch/enterprise-4.5, lgtm, size/XS

#29311 [enterprise-4.6] OSDOCS-1477 Monitoring capabilities for WINC
  modules/windows-workload-management.adoc
Labels: branch/enterprise-4.6, size/S

#29135 Update event source procedures and correct assembly path for ping source modules in Serverless
  modules/odc-creating-apiserversource.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-odc.adoc
  modules/serverless-pingsource-yaml.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.7, size/M

#28800 Remove 'clusterID' from ShiftStack install-config.yaml mods
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-kuryr-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS
