Repository openshift/openshift-docs, pull requests merged in 2021-04, with the labels that each got.

#31183 Fix emphasis and tokens in table
  modules/ipi-install-network-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31213 BZ#1852105 No longer a short char limit for GCP cluster name
  modules/installation-initializing.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31191 GitHub issue#31057 add haproxy.router.openshift.io/set-forwarded-headers to annotation table
  modules/nw-route-specific-annotations.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31141 RHDEVDOCS-2829 Explain how to "only deploy collector section"
  _topic_map.yml
  _unused_topics/cluster-logging-collector-envvar.adoc
  _unused_topics/cluster-logging-log-forwarding-disable.adoc
  logging/config/cluster-logging-collector.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-removing-unused-components-if-no-elasticsearch.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#31212 BZ#1852120 Update RHCOS image upload steps for GCP
  modules/installation-gcp-user-infra-rhcos.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31210 Removes MTU network link
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30776 GitHub issue-28150/issue-29904 update PVC command for registry
  modules/installation-registry-storage-block-recreate-rollout.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, issue-burndown, lgtm, size/XS

#30790 BZ185249 - Added the `\A` parameter to the templates documentation.
  modules/templates-writing-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#31220 Adds 4.7.5 RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/M

#31254 updated OKD distros
  _distro_map.yml
Labels: size/S

#29596 OSDOCS-1168 vSphere IPI in restricted networks
  _topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-image-restricted.adoc
  modules/installation-initializing.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/registry-configuring-storage-vsphere.adoc
  modules/registry-removed.adoc
  modules/ssh-agent-using.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31206 Bug 1871802: customer feedback to make yaml filename consistent
  modules/installation-special-config-crony.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31256 [enterprise-4.8] OSDOCS-1168 vSphere IPI in restricted networks
  _topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-image-restricted.adoc
  modules/installation-initializing.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/registry-configuring-storage-vsphere.adoc
  modules/registry-removed.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.8, size/L

#31257 [enterprise-4.7] OSDOCS-1168 vSphere IPI in restricted networks
  _topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-image-restricted.adoc
  modules/installation-initializing.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/registry-configuring-storage-vsphere.adoc
  modules/registry-removed.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.7, size/L

#31262 [enterprise-4.6] OSDOCS-1168 vSphere IPI in restricted networks
  _topic_map.yml
  installing/install_config/installation-types.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-image-restricted.adoc
  modules/installation-initializing.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/registry-configuring-storage-vsphere.adoc
  modules/registry-removed.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.6, size/L

#31264 [enterprise-4.5] OSDOCS-1168 vSphere IPI in restricted networks
  _topic_map.yml
  installing/install_config/installation-types.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-image-restricted.adoc
  modules/installation-initializing.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/registry-configuring-storage-vsphere.adoc
  modules/registry-removed.adoc
  modules/ssh-agent-using.adoc
Labels: branch/enterprise-4.5, size/L

#31267 Manual CP of #31141 to 4.5 RHDEVDOCS-2829 Explain how to "only deploy collector section"
  logging/config/cluster-logging-collector.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-removing-unused-components-if-no-elasticsearch.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.5, size/M

#31252 Manual CP of #31141 to 4.6 RHDEVDOCS-2829 Explain how to "only deploy collector section"
  _topic_map.yml
  logging/config/cluster-logging-collector.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-removing-unused-components-if-no-elasticsearch.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.6, lgtm, size/M

#31117 Commenting out content that was merged before GA
  cicd/pipelines/op-release-notes.adoc
Labels: Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#31266 BZ1807463: Added restriction for FIPS on Azure File storage
  installing/installing-fips.adoc
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31214 Bug 1789554: added a note to emphasize important info from code callouts
  modules/nw-proxy-configure-object.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#31229 BZ1946177: RHV VM import fails for NFS target storage class (CNV 2.6.1)
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  modules/virt-troubleshooting-vm-import.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31276 Fixed formatting in a VPA module
  modules/nodes-pods-vertical-autoscaler-using-about.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31152 BZ-1783799: Added path based route doc
  modules/nw-path-based-routes.adoc
  networking/routes/route-configuration.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#31296 manual cherry-pick for 4.5
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-importing-vm-cli.adoc
  modules/virt-importing-vm-prerequisites.adoc
  modules/virt-importing-vm-wizard.adoc
  modules/virt-troubleshooting-vm-import.adoc
Labels: size/L

#30905 NTO: More precise description of MCP matching.
  modules/custom-tuning-specification.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#31243 Remove link Ansible inv doc link
  install_config/topics/configuring_azure_using_ansible.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#29903 [enterprise-4.6] Add known issue to 4.6 relnotes for BZ#1909152
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#30901 Clarify channel name usage in Operator install via CLI
  modules/olm-changing-update-channel.adoc
  modules/olm-dependency-resolution-preferences.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-subscription.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, issue-burndown, size/S

#31307 [enterprise-4.5] Clarify channel name usage in Operator install via CLI
  modules/olm-changing-update-channel.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-subscription.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
Labels: size/S

#31202 OSDOCS#1491 - Include diagram for IPsec traffic flows
  images/nw-ipsec-encryption.png
  modules/nw-ovn-ipsec-traffic.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31082 Initial additions of sandboxed containers
  _topic_map.yml
  modules/common-attributes.adoc
  modules/sandboxed-containers-about-sandboxing.adoc
  modules/sandboxed-containers-building-blocks.adoc
  modules/sandboxed-containers-installing-operator-cli.adoc
  modules/sandboxed-containers-installing-operator-web-console.adoc
  modules/sandboxed-containers-installing-operator.adoc
  modules/sandboxed-containers-limitations.adoc
  modules/sandboxed-containers-os-extensions.adoc
  modules/sandboxed-containers-preparing-openshift-cluster.adoc
  modules/sandboxed-containers-scheduling-workloads.adoc
  modules/sandboxed-containers-selecting-nodes.adoc
  modules/sandboxed-containers-triggering-installation-kata-runtime.adoc
  modules/sandboxed-containers-uninstalling-kata-runtime.adoc
  modules/sandboxed-containers-viewing-workloads-from-cli.adoc
  modules/sandboxed-containers-viewing-workloads-from-web-console.adoc
  sandboxed_containers/deploying-sandboxed-container-workloads.adoc
  sandboxed_containers/disabling-sandboxed-container-workloads.adoc
  sandboxed_containers/modules
  sandboxed_containers/understanding-sandboxed-containers.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/L

#31302 RHDEVDOCS-2900 Tracker for #30976 Issue in file logging/cluster-loggi…
  jaeger/jaeger_install/rhbjaeger-removing.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-upgrading.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-deploying.adoc
  logging/dedicated-cluster-logging.adoc
  logging/troubleshooting/cluster-logging-log-store-status.adoc
  modules/cluster-logging-about-collector.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-multitenant.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-log-store-status-viewing.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-about.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-release-notes-5.0.0.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/dedicated-cluster-install-deploy.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deploy-production-es.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-install-overview.adoc
  modules/jaeger-install.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/metering-install-verify.adoc
  modules/ossm-install-ossm-operator.adoc
  modules/ossm-installation-activities.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-rn-fixed-issues-1x.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/security-monitoring-cluster-logging.adoc
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30696 CNV-10910 Updating cluster install info related to IPI, UPI, MHC, and HA
  virt/install/preparing-cluster-for-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/S

#31186 The fields in this module are duplicated elsewhere
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/installation-configuration-parameters.adoc
  modules/nw-install-config-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31325 [enterprise-4.8] The fields in this module are duplicated elsewhere
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/installation-configuration-parameters.adoc
  modules/nw-install-config-parameters.adoc
Labels: branch/enterprise-4.8, size/L

#31326 [enterprise-4.7] The fields in this module are duplicated elsewhere
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/installation-configuration-parameters.adoc
  modules/nw-install-config-parameters.adoc
Labels: branch/enterprise-4.7, size/L

#31327 [enterprise-4.6] The fields in this module are duplicated elsewhere
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/installation-configuration-parameters.adoc
  modules/nw-install-config-parameters.adoc
Labels: branch/enterprise-4.6, size/L

#31320 Manual CP of PR #31302 to 4.7 yet again
  jaeger/jaeger_install/rhbjaeger-removing.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-upgrading.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-deploying.adoc
  logging/dedicated-cluster-logging.adoc
  logging/troubleshooting/cluster-logging-log-store-status.adoc
  modules/cluster-logging-about-collector.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-multitenant.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-log-store-status-viewing.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-about.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-release-notes-5.0.0.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/dedicated-cluster-install-deploy.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deploy-production-es.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-install-overview.adoc
  modules/jaeger-install.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/metering-install-verify.adoc
  modules/ossm-install-ossm-operator.adoc
  modules/ossm-installation-activities.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-rn-fixed-issues-1x.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/security-monitoring-cluster-logging.adoc
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
Labels: size/L

#31321 updated cp to 4.8
  jaeger/jaeger_install/rhbjaeger-removing.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-upgrading.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/dedicated-cluster-deploying.adoc
  logging/dedicated-cluster-logging.adoc
  logging/troubleshooting/cluster-logging-log-store-status.adoc
  modules/cluster-logging-about-collector.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-deploy-multitenant.adoc
  modules/cluster-logging-deploy-storage-considerations.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-ha.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-elasticsearch-storage.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/cluster-logging-log-store-status-viewing.adoc
  modules/cluster-logging-logstore-limits.adoc
  modules/cluster-logging-maintenance-support-about.adoc
  modules/cluster-logging-maintenance-support-list.adoc
  modules/cluster-logging-release-notes-5.0.0.adoc
  modules/cluster-logging-troubleshooting-unknown.adoc
  modules/cluster-logging-uninstall.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/dedicated-cluster-install-deploy.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deploy-production-es.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-install-overview.adoc
  modules/jaeger-install.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/metering-install-verify.adoc
  modules/ossm-install-ossm-operator.adoc
  modules/ossm-installation-activities.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-rn-fixed-issues-1x.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/security-monitoring-cluster-logging.adoc
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v2x/installing-ossm.adoc
Labels: size/L

#31154 BZ#1943601 | Fixed typo in two sample config YAML files
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31211 Jira CNV10449 Correcting description of operating system in VM Wizard fields
  modules/virt-vm-wizard-fields-web.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#31242 GA Vertical Pod Autoscaling
  nodes/pods/nodes-pods-vertical-autoscaler.adoc
Labels: Peer Review Done, branch/enterprise-4.8, lgtm, size/XS

#30822 ISSUE-29111 Updated code to include missing label
  modules/deployments-ab-testing-lb.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#31155 BZ1942895 change note for ibm z
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#28358 Bug 1910665: Kuryr: Add note about expected OpenStack subnet
  modules/installation-osp-kuryr-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, bugzilla/severity-low, bugzilla/valid-bug, size/S

#31137 BZ#1787999: Add description/displayName to OSDK CSV
  modules/managing-memcached-operator-using-olm.adoc
Labels: Peer Review Done, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, size/S

#31197 [enterprise-4.5] Add description/displayName to OSDK CSV
  modules/managing-memcached-operator-using-olm.adoc
Labels: size/S

#31193 [enterprise-4.4] Add description/displayName to OSDK CSV
  modules/managing-memcached-operator-using-olm.adoc
Labels: size/S

#31129 Jira:OSDOCS-2001:Fix formatting issues in autoscaling topics
  modules/rosa-about-autoscaling-nodes.adoc
  modules/rosa-adding-instance-types.adoc
  modules/rosa-disabling-autoscaling-nodes.adoc
  modules/rosa-enabling-autoscaling-nodes.adoc
Labels: Peer Review Done, size/XS

#31356 [enterprise-4.8] Documentation indicates OpenShiftSDN is a (preferred) supported default network CNI Provider
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/nw-operator-cr.adoc
Labels: size/M

#31360 [enterprise-4.5] Documentation indicates OpenShiftSDN is a preferred supported default network CNI Provider
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installing-rhv-config-yaml.adoc
  modules/nw-operator-cr.adoc
Labels: size/M

#31362 Fix OSDK version typo
  operators/operator_sdk/osdk-about.adoc
Labels: branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31367 [enterprise-4.6] Documentation indicates OpenShiftSDN is a preferred supported default network CNI Provider
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/nw-operator-cr.adoc
Labels: size/M

#31368 [enterprise-4.7] Documentation indicates OpenShiftSDN is a preferred supported default network CNI Provider
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/nw-operator-cr.adoc
Labels: size/M

#31313 BZ1862279: Corrected syntax for export commands
  modules/installation-creating-gcp-bootstrap.adoc
  modules/installation-creating-gcp-control-plane.adoc
  modules/installation-creating-gcp-iam-shared-vpc.adoc
  modules/installation-creating-gcp-lb.adoc
  modules/installation-creating-gcp-worker.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#31371 fix error from recent cherrypick
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#29511 Adjust CSV infra feat annotations
  modules/osdk-csv-manual-annotations.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#31375 [enterprise-4.5] Rename RHV to include/switch to oVirt
  installing/install_config/installation-types.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installing-rhv-verifying-the-rhv-environment.adoc
Labels: size/M

#31379 Clarify maximum node count
  modules/rosa-sdpolicy-account-management.adoc
Labels: Peer Review Done, size/XS

#31382 [enterprise-4.7] Rename RHV to include/switch to oVirt
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installing-rhv-verifying-rhv-environment.adoc
Labels: size/M

#31084 Changed text regarding modification of manifest files. BZ1904138
  modules/nw-modifying-operator-install-config.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31393 [enterprise-4.5] removing RHEL supported version from OKD
  modules/installation-requirements-user-infra.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/S

#30606 BZ-1937617 Setting log level - remove Alertmanager and add Thanos Querier
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30618 BZ-1937617 Remove Alertmanager mention from setting log level
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#31344 OSDCOS-2030: Changed URL and name of console.
  modules/rosa-setting-up-environment.adoc
Labels: Peer Review Done, size/XS

#31399 [enterprise-4.6] Add module for manual CSV annotations
  modules/osdk-csv-manual-annotations.adoc
  modules/osdk-manually-defined-csv-fields.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
Labels: size/M

#31400 Enterprise 4.5
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/security-compliance-nist.adoc
  modules/security-hosts-vms-openshift.adoc
  security/container_security/security-hardening.adoc
Labels: size/L

#31316 Jira:OSDOCS-1992 Add instances types to ROSA service definition
  modules/rosa-aws-provisioned.adoc
  modules/rosa-sdpolicy-account-management.adoc
Labels: Peer Review Done, size/S

#30949 Jira:1986 - Fix link in ROSA Service Definition
  modules/rosa-sdpolicy-account-management.adoc
  modules/rosa-sdpolicy-security.adoc
  rosa_policy/rosa-service-definition.adoc
Labels: Peer Review Done, size/XS

#31402 [enterprise-4.7] Documentation wrong regarding FIPS mode and FCOS
  installing/installing-preparing.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/security-compliance-nist.adoc
  modules/security-hosts-vms-openshift.adoc
  security/container_security/security-hardening.adoc
Labels: size/L

#31312 [virt] HCO bump for 2.6.1
  modules/virt-document-attributes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, size/XS

#31255 OSDOCS-1807: sr-iov supp x710
  modules/nw-sriov-supported-devices.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#31401 [enterprise-4.6] Documentation wrong regarding FIPS mode and FCOS
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/security-compliance-nist.adoc
  modules/security-hosts-vms-openshift.adoc
  security/container_security/security-hardening.adoc
Labels: size/L

#31130 CNV-5268 virtctl vnc proxy
  modules/virt-virtctl-commands.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/S

#31355 Fixed indentation in sample proxy certificate. Closes #31018
  security/certificate_types_descriptions/proxy-certificates.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30735 BZ1899171
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#31270 [enterprise-4.7] Include namespace referring to image stream # 31225 : security/compliance_operator/compliance-operator-manage.adoc
  modules/compliance-imagestreams.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31311 BZ1892213: Added an important note
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31358 BZ#1927841: host network routers and OVN-K
  modules/nw-networkpolicy-project-defaults.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#31420 [enterprise-4.5] BZ1892213: Added an important note
  modules/installation-requirements-user-infra.adoc
Labels: size/S

#31421 [enterprise-4.6] BZ1892213: Added an important note
  modules/installation-requirements-user-infra.adoc
Labels: size/S

#30642 CNV-10988 Updated virt sizing guidelines
  modules/virt-cluster-resource-requirements.adoc
Labels: CNV, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29673 Updating Compliance Operator docs
  _topic_map.yml
  modules/compliance-anatomy.adoc
  modules/compliance-apply-remediations-from-scans.adoc
  modules/compliance-auto-update-remediations.adoc
  modules/compliance-custom-storage.adoc
  modules/compliance-filtering-failed-results.adoc
  modules/compliance-inconsistent.adoc
  modules/compliance-operator-cli-installation.adoc
  modules/compliance-operator-console-installation.adoc
  modules/compliance-profilebundle.adoc
  modules/running-compliance-scans.adoc
  security/compliance_operator/compliance-operator-advanced.adoc
  security/compliance_operator/compliance-operator-installation.adoc
  security/compliance_operator/compliance-operator-manage.adoc
  security/compliance_operator/compliance-operator-remediation.adoc
  security/compliance_operator/compliance-scans.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31323 Added "ec2:DeleteTags" to EC2 permissions table per BZ1926543
  modules/installation-aws-permissions.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31443 [enterprise-4.5] Added "ec2:DeleteTags" to EC2 permissions table per BZ1926543
  modules/installation-aws-permissions.adoc
Labels: size/XS

#31444 Adding base ACS/StackRox docs
  _distro_map.yml
Labels: size/S

#31343 Remove extra characters from prompts
  modules/ipi-install-creating-a-disconnected-registry.adoc
  modules/ipi-install-troubleshooting-registry-issues.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#30387 CNV - BZ#1917499 - net-attach-def and the overall improvement
  modules/virt-attaching-vm-secondary-network-cli.adoc
  modules/virt-creating-bridge-nad-cli.adoc
  modules/virt-vm-creating-nic-web.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
Labels: CNV, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31204 CNV-9053 KubeMacPool enabled by default
  modules/virt-about-kubemacpool.adoc
  modules/virt-disabling-mac-address-pool-for-namespace-cli.adoc
  modules/virt-enabling-mac-address-pool-for-namespace-cli.adoc
  modules/virt-networking-wizard-fields-web.adoc
  modules/virt-pxe-booting-with-mac-address.adoc
  modules/virt-reenabling-mac-address-pool-for-namespace-cli.adoc
  virt/install/installing-virt-cli.adoc
  virt/install/installing-virt-web.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
  virt/virtual_machines/vm_networking/virt-using-mac-address-pool-for-vms.adoc
  virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/M

#31456 OSDCOS-2949: Added clarifier to last step
  modules/osd-monitoring-troubleshooting-issues.adoc
Labels: Peer Review Done, size/XS

#30367 OSSMDOC169 Update CR configuring Jaeger.
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  jaeger/jaeger_install/rhbjaeger-installation.adoc
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
  modules/jaeger-config-query.adoc
  modules/jaeger-config-sampling.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deployment-best-practices.adoc
  modules/jaeger-document-attributes.adoc
  modules/ossm-configuring-external-jaeger.adoc
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-enabling-jaeger.adoc
  modules/ossm-jaeger-service-mesh.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31459 OSDOCS-2034Moved rosa login step to earlier in the procedure
  modules/rosa-setting-up-environment.adoc
Labels: Peer Review Done, size/M

#31460 [4.6] Manual CP OSSMDOC-169 Jaeger updates #30367
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  jaeger/jaeger_install/rhbjaeger-installation.adoc
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
  modules/jaeger-config-query.adoc
  modules/jaeger-config-sampling.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deployment-best-practices.adoc
  modules/jaeger-document-attributes.adoc
  modules/ossm-configuring-external-jaeger.adoc
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-enabling-jaeger.adoc
  modules/ossm-jaeger-service-mesh.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
Labels: Service Mesh, size/L

#31462 [4.7] manual CP of OSSMDOC-169 Update CR configuring Jaeger. #30376
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  jaeger/jaeger_install/rhbjaeger-installation.adoc
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
  modules/jaeger-config-query.adoc
  modules/jaeger-config-sampling.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deployment-best-practices.adoc
  modules/jaeger-document-attributes.adoc
  modules/ossm-configuring-external-jaeger.adoc
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-enabling-jaeger.adoc
  modules/ossm-jaeger-service-mesh.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
Labels: Service Mesh, size/L

#31463 [4.8] Manual CP of OSSMDOC-169 Update CR configuring Jaeger. #30376
  jaeger/jaeger_install/rhbjaeger-deploying.adoc
  jaeger/jaeger_install/rhbjaeger-installation.adoc
  modules/jaeger-config-collector.adoc
  modules/jaeger-config-ingester.adoc
  modules/jaeger-config-query.adoc
  modules/jaeger-config-sampling.adoc
  modules/jaeger-config-storage.adoc
  modules/jaeger-deployment-best-practices.adoc
  modules/jaeger-document-attributes.adoc
  modules/ossm-configuring-external-jaeger.adoc
  modules/ossm-configuring-jaeger.adoc
  modules/ossm-cr-example.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-enabling-jaeger.adoc
  modules/ossm-jaeger-service-mesh.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  service_mesh/v2x/ossm-custom-resources.adoc
Labels: Service Mesh, size/L

#31196 Updating the File Integrity Operator content
  _topic_map.yml
  modules/checking-file-intergrity-cr-status.adoc
  modules/file-integrity-CR-phases.adoc
  modules/file-integrity-node-status-failure.adoc
  modules/file-integrity-node-status-success.adoc
  modules/file-integrity-node-status.adoc
  modules/file-integrity-operator-installing-cli.adoc
  modules/file-integrity-operator-installing-web-console.adoc
  modules/file-integrity-operator-reinitializing-database.adoc
  modules/file-integrity-operator-viewing-attributes.adoc
  modules/file-integrity-understanding-file-integrity-cr.adoc
  modules/file-integrity-understanding-file-integrity-node-statuses-object.adoc
  security/compliance_operator/compliance-operator-installation.adoc
  security/file_integrity_operator/file-integrity-operator-installation.adoc
  security/file_integrity_operator/file-integrity-operator-troubleshooting.adoc
  security/file_integrity_operator/file-integrity-operator-understanding.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31466 [enterprise-4.6]Updating the File Integrity Operator content
  _topic_map.yml
  modules/checking-file-intergrity-cr-status.adoc
  modules/file-integrity-CR-phases.adoc
  modules/file-integrity-node-status-failure.adoc
  modules/file-integrity-node-status-success.adoc
  modules/file-integrity-node-status.adoc
  modules/file-integrity-operator-installing-cli.adoc
  modules/file-integrity-operator-installing-web-console.adoc
  modules/file-integrity-operator-reinitializing-database.adoc
  modules/file-integrity-operator-viewing-attributes.adoc
  modules/file-integrity-understanding-file-integrity-cr.adoc
  modules/file-integrity-understanding-file-integrity-node-statuses-object.adoc
  security/compliance_operator/compliance-operator-installation.adoc
  security/file_integrity_operator/file-integrity-operator-installation.adoc
  security/file_integrity_operator/file-integrity-operator-troubleshooting.adoc
  security/file_integrity_operator/file-integrity-operator-understanding.adoc
Labels: size/L

#30722 BZ1937051: DVM proxy configuration (1.4.3)
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-configuring-proxy-for-dvm.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#31416 Updating 4.7 release notes link to be 1.20-specific
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#31414 Adds oc get images to CLI reference
  cli_reference/basic_cli_operations.adoc
Labels: branch/enterprise-3.11, size/S

#31431 Fixed the example to have the correct escaped values.
  modules/templates-writing-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31398 BZ1806511 - Add local volume provisioning to Storage docs
  modules/persistent-storage-local-create-cr-manual.adoc
  modules/persistent-storage-local-create-cr.adoc
  storage/persistent_storage/persistent-storage-local.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31494 [enterprise-4.6] Add local volume provisioning to Storage docs
  modules/persistent-storage-local-create-cr-manual.adoc
  modules/persistent-storage-local-create-cr.adoc
  storage/persistent_storage/persistent-storage-local.adoc
Labels: size/L

#31317 BZ#1945244 Note hybrid networking requirement for WINC
  installing/installing-preparing.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31113 OSDOCS-1857 Empty RG for Azure
  modules/installation-azure-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#31495 [enterprise-4.5] Add local volume provisioning to Storage docs
  modules/persistent-storage-local-create-cr-manual.adoc
  modules/persistent-storage-local-create-cr.adoc
  storage/persistent_storage/persistent-storage-local.adoc
Labels: size/L

#31417 BZ1859731: removed sudo now that podman supports rootless execution.
  modules/installing-cluster-loader.adoc
  modules/running-cluster-loader.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31506 Mig-615: Deprecated APIs in 4.x migration
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-updating-deprecated-gvks.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31458 Adds 4.7.6 RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#30797 ShiftStack - Replace lbFloatingIP with apiFloatingIP
  modules/installation-configuration-parameters.adoc
  modules/installation-osp-accessing-api-floating.adoc
  modules/installation-osp-accessing-api-no-floating.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-configuring-api-floating-ip.adoc
  modules/installation-osp-kuryr-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, issue-burndown, size/S

#31522 [enterprise-4.7] ShiftStack - Replace lbFloatingIP with apiFloatingIP
  modules/installation-configuration-parameters.adoc
  modules/installation-osp-accessing-api-floating.adoc
  modules/installation-osp-accessing-api-no-floating.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-configuring-api-floating-ip.adoc
  modules/installation-osp-kuryr-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
Labels: size/S

#31523 [enterprise-4.8] ShiftStack - Replace lbFloatingIP with apiFloatingIP
  modules/installation-configuration-parameters.adoc
  modules/installation-osp-accessing-api-floating.adoc
  modules/installation-osp-accessing-api-no-floating.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-configuring-api-floating-ip.adoc
  modules/installation-osp-kuryr-config-yaml.adoc
  modules/installation-osp-restricted-config-yaml.adoc
Labels: size/S

#31215 Rel Notes doc text for 4.5.37 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/S

#31520 BZ1859731: removed sudo now that podman supports rootless execution.
  modules/installing-cluster-loader.adoc
  modules/running-cluster-loader.adoc
Labels: size/XS

#31519 BZ1859731: removed sudo now that podman supports rootless execution.
  modules/installing-cluster-loader.adoc
  modules/running-cluster-loader.adoc
Labels: size/XS

#31467 BZ1871798 - Revised a sentence explaining how hyperthreaded CPUs relate to vCPUs
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31541 [enterprise-4.6] Clarified how hyperthreaded CPUs relate to vCPUs.
  modules/installation-requirements-user-infra.adoc
Labels: size/S

#31540 [enterprise-4.5] Clarified how hyperthreaded CPUs relate to vCPUs.
  modules/installation-requirements-user-infra.adoc
Labels: size/S

#31544 [enterprise-4.5] Removes back ticks in headings
  applications/deployments/managing-deployment-processes.adoc
  applications/deployments/what-deployments-are.adoc
  authentication/impersonating-system-admin.adoc
  cli_reference/developer_cli_odo/creating-a-single-component-application-with-odo.adoc
  cli_reference/developer_cli_odo/understanding-odo.adoc
  cli_reference/kn-cli-tools.adoc
  cli_reference/tkn_cli/op-configuring-tkn.adoc
  cli_reference/tkn_cli/op-tkn-reference.adoc
  modules/about-sosreport.adoc
  modules/cluster-autoscaler-cr.adoc
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-exported-fields-systemd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  modules/delete-kn-trigger.adoc
  modules/deployments-accessing-private-repos.adoc
  modules/deployments-comparing-deploymentconfigs.adoc
  modules/deployments-deploymentconfigs.adoc
  modules/developer-cli-odo-about-devfiles-in-odo.adoc
  modules/developer-cli-odo-openshift-cluster-objects.adoc
  modules/developer-cli-odo-push-workflow.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-a-mirror-registry.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-an-internal-registry-directly.adoc
  modules/dynamic-provisioning-storage-class-definition.adoc
  modules/ephemeral-storage-csi-inline-pod.adoc
  modules/impersonation-system-admin-group.adoc
  modules/impersonation-system-admin-user.adoc
  modules/kn-trigger-describe.adoc
  modules/kn-trigger-list.adoc
  modules/kn-trigger-update.adoc
  modules/machine-autoscaler-cr.adoc
  modules/machine-health-checks-creating.adoc
  modules/machine-health-checks-resource.adoc
  modules/migration-error-messages.adoc
  modules/migration-using-must-gather.adoc
  modules/nodes-containers-projected-volumes-about.adoc
  modules/nw-sriov-device-discovery.adoc
  modules/ossm-cr-parameters.adoc
  modules/pruning-deployments.adoc
  modules/serverless-create-kn-trigger.adoc
  modules/serverless-installing-cli-linux-rpm.adoc
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-installing-cli-macos.adoc
  modules/serverless-installing-cli-web-console.adoc
  modules/serverless-installing-cli-windows.adoc
  modules/support-generating-a-sosreport-archive.adoc
  modules/troubleshooting-openshift-install-command-issues.adoc
  modules/virt-additional-scc-for-kubevirt-controller.adoc
  modules/virt-configuring-vm-live-migration-cli.adoc
  modules/virt-editing-kubevirtstorageclassdefaults-cli.adoc
  modules/virt-editing-kubevirtstorageclassdefaults-web.adoc
  modules/virt-installing-virtctl-client.adoc
  virt/install/virt-installing-virtctl.adoc
Labels: size/L

#31318 BZ1878472: correction
  modules/installation-about-custom-azure-vnet.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31547 BZ1949193 z/VM version
  modules/installation-requirements-user-infra.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31549 Changed base64 option to make it platform-agnostic. Closes #28376
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/customize-certificates-manually-rotate-service-ca.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-a-mirror-registry.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-an-internal-registry-directly.adoc
  modules/file-integrity-node-status-failure.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/ignition-config-viewing.adoc
  modules/ipi-install-troubleshooting-misc-issues.adoc
  modules/migration-configuring-mcg.adoc
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#30339 GH#30325 Update disk-container file path param for custom RHCOS AMI imports
  modules/installation-aws-upload-custom-rhcos-ami.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31562 [enterprise-4.6]Changed base64 option to make it platform-agnostic
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/customize-certificates-manually-rotate-service-ca.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-a-mirror-registry.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-an-internal-registry-directly.adoc
  modules/file-integrity-node-status-failure.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/ignition-config-viewing.adoc
  modules/ipi-install-troubleshooting-misc-issues.adoc
  modules/migration-configuring-mcg.adoc
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
Labels: size/M

#29501 Updates for MGMT-298
  _topic_map.yml
  modules/virt-automatic-certificates-renewal.adoc
  modules/virt-checking_status_of_node_maintenance_cr_tasks.adoc
  modules/virt-maintaining-bare-metal-nodes.adoc
  modules/virt-resuming-node-from-maintenance-mode-with-cr.adoc
  modules/virt-setting-node-to-maintenance-mode-with-cr.adoc
  modules/virt-understanding-node-maintenance.adoc
  virt/live_migration/virt-live-migration.adoc
  virt/node_maintenance/virt-about-node-maintenance.adoc
  virt/node_maintenance/virt-resuming-node.adoc
  virt/node_maintenance/virt-setting-node-maintenance.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#31567 [enterprise-4.5]Changed base64 option to make it platform-agnostic
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/customize-certificates-manually-rotate-service-ca.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-a-mirror-registry.adoc
  modules/developer-cli-odo-pushing-the-odo-init-image-to-an-internal-registry-directly.adoc
  modules/identity-provider-htpasswd-update-users.adoc
  modules/ignition-config-viewing.adoc
  modules/ipi-install-troubleshooting-misc-issues.adoc
  modules/migration-configuring-mcg.adoc
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
Labels: size/S

#31538 BZ#1943587 WINC minor updates and typos
  modules/collecting-kube-node-logs-windows.adoc
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/enabling-internal-api-server-vsphere.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31470 RHDEVDOCS-2778 Edit suggested in file builds/running-entitled-builds.…
  cicd/builds/build-strategies.adoc
  cicd/builds/running-entitled-builds.adoc
Labels: size/XS

#31572 [enterprise-4.6] BZ#1943587 WINC minor updates and typos
  modules/collecting-kube-node-logs-windows.adoc
Labels: branch/enterprise-4.6, size/XS

#31575 Trivial word change to follow ISG
  modules/collecting-kube-node-logs-windows.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31551 Descheduler: create namespace with openshift.io/cluster-monitoring=true label set
  modules/nodes-descheduler-installing.adoc
Labels: Peer Review Done, branch/enterprise-4.8, lgtm, size/XS

#31579 RHDEVDOCS-2778-cp-31470-to-4.5
  builds/build-strategies.adoc
  builds/running-entitled-builds.adoc
Labels: size/XS

#31580 RHDEVDOCS-2778-cp-31470-to-4.6
  builds/build-strategies.adoc
  builds/running-entitled-builds.adoc
Labels: size/XS

#31332 GH#31328 - Added subjectAltName to the registry certificate
  modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#31468 JIRA: OSDOCS-1964: User must be an IAM user
  modules/rosa-aws-requirements.adoc
  modules/rosa-setting-up-environment.adoc
Labels: Peer Review Done, size/XS

#31525 RHDEVDOCS-2931 Build 4.8: Release note images removed
  release_notes/ocp-4-8-release-notes.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.8, lgtm, size/S

#31501 Removed unlimited memory wording from limit range topic
  modules/nodes-cluster-limit-ranges-limits.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31590 BZ1534863: Adds note to suggest avoiding environment variable manipulation
  architecture/service_catalog/index.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#31598 BZ 1932254: Removes timeoutSeconds note
  modules/application-health-about.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#31542 Removes instances of Containerized Install
  install/index.adoc
Labels: branch/enterprise-3.11, size/XS

#31589 BZ: 1666515 Adds Master Events section to 3.11
  install_config/aggregate_logging_sizing.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/S

#31620 Added closing quotes
  modules/compliance-filtering-failed-results.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30340 CNV-10445 [1926199] VM Migration of mixed CPU (AMD,Intel)
  virt/install/preparing-cluster-for-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30615 [WIP] Argo CD getting started guide.
  _topic_map.yml
  cicd/gitops/configuring-sso-for-argo-cd-on-openshift.adoc
  cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/deploying-a-spring-boot-application-with-argo-cd.adoc
  cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/images
  cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/modules
  cicd/gitops/getting-started-with-openshift-gitops.adoc
  cicd/gitops/installing-openshift-gitops.adoc
  images/red-hat-applications-menu-icon.jpg
  modules/gitops-configuring-argo-cd-oidc.adoc
  modules/gitops-configuring-groups-and-argocd-rbac.adoc
  modules/gitops-configuring-the-groups-claim.adoc
  modules/gitops-creating-a-new-client-in-keycloak.adoc
  modules/gitops-creating-an-application-by-using-the-argo-cd-dashboard.adoc
  modules/gitops-creating-an-application-by-using-the-oc-tool.adoc
  modules/gitops-document-attributes.adoc
  modules/gitops-enabling-dex.adoc
  modules/gitops-in-built-permissions.adoc
  modules/gitops-keycloak-identity-brokering-with-openshift-oauthclient.adoc
  modules/gitops-registering-an-additional-oauth-client.adoc
  modules/gitops-registering-an-oauth-client.adoc
  modules/gitops-synchronizing-your-application-application-with-your-git-repository.adoc
  modules/gitops-verifying-argo-cd-self-healing-behavior.adoc
  modules/installing-gitops-operator-in-web-console.adoc
  modules/launching-the-operator-provided-argocd-instance.adoc
  modules/logging-in-to-the-argo-cd-instance-by-using-your-openshift-credentials.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, do-not-merge/work-in-progress, size/XL

#31047 [enterprise-4.x]Fix callouts typo in sample install-config.yaml file for bare metal
  modules/installation-bare-metal-config-yaml.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#31435 BZ: 1538917 Adds Persistent storage + mount propagation section to 3.11
  _topic_map.yml
  architecture/additional_concepts/storage.adoc
  install_config/persistent_storage/persistent_storage_hostpath.adoc
  install_config/storage_examples/mount_propagation.adoc
  modules/persistent-storage-hostpath-about.adoc
  modules/persistent-storage-hostpath-pod.adoc
  modules/persistent-storage-hostpath-static-provisioning.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#31641 [enterprise-4.5] [enterprise-4.x]Fix callouts typo in sample install-config.yaml file for bare metal
  modules/installation-bare-metal-config-yaml.adoc
Labels: branch/enterprise-4.5, size/S

#31644 BZ1884640: removed space causing wonky admonition formatting
  modules/installation-vsphere-infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#31477 BZ#1890659 - Include ssh reboot note
  modules/nw-ovn-kubernetes-migration.adoc
Labels: branch/enterprise-4.6, size/XS
