Repository openshift/openshift-docs, pull requests merged in 2021-12, with the labels that each got.

#38979 [RHACS] Release notes for 3.67.0
  _topic_map.yml
  modules/acs-requirements.adoc
  modules/common-attributes.adoc
  modules/fetching-vulnerability-definitions.adoc
  modules/rbac-system-roles-3630.adoc
  modules/scanning-images.adoc
  release_notes/3056-release-notes.adoc
  release_notes/3057-release-notes.adoc
  release_notes/3058-release-notes.adoc
  release_notes/3059-release-notes.adoc
  release_notes/367-release-notes.adoc
Labels: Peer Review Done, size/XL, RHACS/next

#38980 [RHACS] OCP OAuth integration
  _topic_map.yml
  modules/common-attributes.adoc
  modules/configure-ocp-oauth-identity-provider.adoc
  operating/manage-user-access/configure-ocp-oauth.adoc
Labels: Peer Review Done, size/M, RHACS/next

#39287 [RHACS] Operator install instructions update for 3.67
  modules/install-acs-operator.adoc
  modules/install-central-operator.adoc
Labels: Peer Review Done, size/S, RHACS/next

#38978 [RHACS] Upgrade guide updates for 3.67
  _topic_map.yml
  modules/uninstall-roxctl-cli.adoc
  modules/update-openshift-security-context-constraints.adoc
  modules/update-other-images.adoc
  modules/update-readiness-probes.adoc
  modules/upgrade-central.adoc
  modules/upgrade-scanner.adoc
  modules/verify-central-cluster-upgrade.adoc
  modules/verify-last-check-in-time.adoc
  modules/verify-upgrades.adoc
  upgrading/upgrade-roxctl.adoc
  upgrading/upgrading_roxctl/images
  upgrading/upgrading_roxctl/modules
  upgrading/upgrading_roxctl/upgrade-from-40-43.adoc
Labels: Peer Review Done, size/L, RHACS/next

#38738 BZ1954146: add labels to namespace while using egress with ovn
  modules/nw-egress-ips-assign.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39406 [RHDEVDOCS-3114] Helm chart side panel updates
  images/odc_helm_chart_devcatalog.png
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#39389 RHDEVDOCS-3490 Pipelines 1.6 RN
  cicd/pipelines/op-release-notes.adoc
  modules/op-release-notes-1-4.adoc
  modules/op-release-notes-1-5.adoc
  modules/op-release-notes-1-6.adoc
  modules/op-tkn-pipeline-run.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#38898 GH38823: Fixing typo for namespace selector in 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8

#38235 Reorganize Multus related CNI plug-in content
  _topic_maps/_topic_map.yml
  modules/nw-multus-bridge-object.adoc
  modules/nw-multus-create-network-apply.adoc
  modules/nw-multus-create-network.adoc
  modules/nw-multus-host-device-object.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-multus-ipvlan-object.adoc
  modules/nw-multus-macvlan-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/configuring-bridge.adoc
  networking/multiple_networks/configuring-host-device.adoc
  networking/multiple_networks/configuring-ipvlan.adoc
  networking/multiple_networks/configuring-macvlan-basic.adoc
  networking/multiple_networks/configuring-macvlan.adoc
  networking/multiple_networks/configuring-multi-network-policy.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: Peer Review Done, size/XXL, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39409 Fixing a little typo as it is bootstrap servers, not just a single server
  modules/serverless-kafka-sasl.adoc
  modules/serverless-kafka-tls.adoc
  serverless/knative_eventing/serverless-kafka.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39210 [BZ2024985] add multi-nic to IBM Z KVM install docs
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#38800 SRVKS-573: Add target utilization docs
  modules/serverless-autoscaling-maxscale-kn.adoc
  modules/serverless-autoscaling-minscale-kn.adoc
  modules/serverless-concurrency-limits-configure-hard.adoc
  modules/serverless-concurrency-limits-configure-soft.adoc
  modules/serverless-target-utilization.adoc
  serverless/autoscaling/modules
  serverless/autoscaling/serverless-autoscaling-concurrency.adoc
  serverless/autoscaling/serverless-autoscaling-scale-bounds.adoc
  serverless/autoscaling/serverless-autoscaling.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39393 OSDOCS-2995: Updated a note in ROSA policy documentation
  modules/rosa-sdpolicy-account-management.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38918 CNV-12277: Removed mention of sriovLiveMigration feature gate
  modules/virt-about-live-migration.adoc
  modules/virt-about-upgrading-virt.adoc
  modules/virt-features-for-storage-matrix.adoc
  virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
Labels: size/S, CNV, branch/enterprise-4.10

#39325 Adds 4.7.38 RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Needed, Peer Review Done, size/S, branch/enterprise-4.7

#38452 CNV-13214: Revising cloning checkbox step for users without supporting storage
  modules/virt-creating-a-vm-from-a-template-with-an-attached-boot-source.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39457 [RHACS] Fix release date for 3.67
  release_notes/367-release-notes.adoc
Labels: Peer Review Done, size/XS, RHACS/next

#39459 [enterprise-4.7] CNV-13214: Adding NOTE to check for storage supporting cloning
  modules/virt-creating-a-vm-from-a-template-with-an-attached-boot-source.adoc
Labels: size/XS

#39410 fixes footer overlap on welcome page
  _templates/_page_openshift.html.erb
Labels: size/M

#39460 release ACS 3.67
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
  index-commercial.html
Labels: size/S

#39443 [enterprise-4.7] Reorganize Multus related CNI plug-in content
  _topic_maps/_topic_map.yml
  modules/nw-multus-bridge-object.adoc
  modules/nw-multus-create-network-apply.adoc
  modules/nw-multus-create-network.adoc
  modules/nw-multus-host-device-object.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-multus-ipvlan-object.adoc
  modules/nw-multus-macvlan-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/configuring-bridge.adoc
  networking/multiple_networks/configuring-host-device.adoc
  networking/multiple_networks/configuring-ipvlan.adoc
  networking/multiple_networks/configuring-macvlan-basic.adoc
  networking/multiple_networks/configuring-macvlan.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: size/XXL

#39440 SDN-1340: remove warning about OVN-Kubernetes and HostNetwork
  modules/nw-networkpolicy-project-defaults.adoc
Labels: lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38902 BZ1902748: Split the ELB and ELBv2 permissions
  modules/installation-aws-permissions.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39356 BZ2024214: Changed latest versions to stable
  modules/ipi-install-retrieving-the-openshift-installer.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9

#39445 [enterprise-4.6] Reorganize Multus related CNI plug-in content
  _topic_maps/_topic_map.yml
  modules/nw-multus-bridge-object.adoc
  modules/nw-multus-create-network-apply.adoc
  modules/nw-multus-create-network.adoc
  modules/nw-multus-host-device-object.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-multus-ipvlan-object.adoc
  modules/nw-multus-macvlan-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/configuring-bridge.adoc
  networking/multiple_networks/configuring-host-device.adoc
  networking/multiple_networks/configuring-ipvlan.adoc
  networking/multiple_networks/configuring-macvlan-basic.adoc
  networking/multiple_networks/configuring-macvlan.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: size/XXL, branch/enterprise-4.6

#37811 [enterprise-4.8] OSDOCS-2711 Add known issue and info for projected volumes and Windows pods
  modules/nodes-containers-projected-volumes-about.adoc
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.7, branch/enterprise-4.8

#39448 BZ:1996503 - Changing table in aws machine types
  modules/installation-supported-aws-machine-types.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39488 [enterprise-4.8] Follow-up peer review comments for WinC known issue
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#39484 [MULTIARCH-1965] IBM Z remove cio_ignore parm from 4.6 docs
  modules/installation-ibm-z-user-infra-machines-iso.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6

#39476 [MULTIARCH-1966] Remove cio_ignore parm from 4.7 docs
  modules/installation-ibm-z-user-infra-machines-iso.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.7

#39314 [MULTIARCH-1967] IBM Z remove cio_ignore parm from 4.8 and later docs
  modules/installation-ibm-z-user-infra-machines-iso.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39453 BZ#2016983 Tweak install dir param syntax to avoid syntax issue with tilda
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-azure-user-infra-completing.adoc
  modules/installation-azure-user-infra-wait-for-bootstrap.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-getting-debug-information.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-initializing.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-launching-installer.adoc
  modules/installation-osp-kuryr-settings-installing.adoc
  modules/installation-osp-setting-worker-affinity.adoc
  modules/installation-special-config-kargs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-uninstall-clouds.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-user-infra-machines-advanced.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/manually-create-identity-access-management.adoc
  modules/nw-aws-nlb-new-cluster.adoc
  modules/nw-gcp-installing-global-access-configuration.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/restarting-installation.adoc
  modules/rhcos-enabling-multipath-day-1-power.adoc
  modules/specifying-openshift-installer-log-levels.adoc
  modules/sts-mode-installing-manual-run-installer.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39498 [enterprise-4.8] Tweak install dir param syntax to avoid syntax issue with tilda
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-azure-user-infra-completing.adoc
  modules/installation-azure-user-infra-wait-for-bootstrap.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-getting-debug-information.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-initializing.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-launching-installer.adoc
  modules/installation-osp-kuryr-settings-installing.adoc
  modules/installation-special-config-kargs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-uninstall-clouds.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-user-infra-machines-advanced.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/manually-create-identity-access-management.adoc
  modules/nw-aws-nlb-new-cluster.adoc
  modules/nw-gcp-installing-global-access-configuration.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/restarting-installation.adoc
  modules/specifying-openshift-installer-log-levels.adoc
  modules/sts-mode-installing-manual-run-installer.adoc
Labels: size/M, branch/enterprise-4.8

#39499 [enterprise-4.7] Tweak install dir param syntax to avoid syntax issue with tilda
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-azure-user-infra-completing.adoc
  modules/installation-azure-user-infra-wait-for-bootstrap.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-getting-debug-information.adoc
  modules/installation-initializing.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-launching-installer.adoc
  modules/installation-osp-kuryr-settings-installing.adoc
  modules/installation-special-config-encrypt-disk-tang.adoc
  modules/installation-special-config-encrypt-disk-tpm2.adoc
  modules/installation-special-config-kargs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/installation-uninstall-clouds.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/manually-create-identity-access-management.adoc
  modules/nw-aws-nlb-new-cluster.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/restarting-installation.adoc
  modules/specifying-openshift-installer-log-levels.adoc
Labels: size/M, branch/enterprise-4.7

#39500 [enterprise-4.6] Tweak install dir param syntax to avoid syntax issue with tilda
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-azure-user-infra-completing.adoc
  modules/installation-azure-user-infra-wait-for-bootstrap.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-generate-ignition-configs.adoc
  modules/installation-getting-debug-information.adoc
  modules/installation-initializing.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-launching-installer.adoc
  modules/installation-osp-kuryr-settings-installing.adoc
  modules/installation-special-config-encrypt-disk-tang.adoc
  modules/installation-special-config-encrypt-disk-tpm2.adoc
  modules/installation-special-config-kargs.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/installation-uninstall-clouds.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/manually-create-identity-access-management.adoc
  modules/nw-aws-nlb-new-cluster.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/restarting-installation.adoc
  modules/specifying-openshift-installer-log-levels.adoc
Labels: size/M, branch/enterprise-4.6

#39196 OSSMDOC-434: Clarify 3scale Nav headings.
  _topic_maps/_topic_map.yml
  service_mesh/v2x/ossm-threescale-webassembly-module.adoc
  service_mesh/v2x/threescale-adapter.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38886 CNV-14200: HCO bump for 4.8.3
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.8

#39503 [enterprise-4.6] OSSMDOC-434: Clarify 3scale nNav headings.
  _topic_maps/_topic_map.yml
  service_mesh/v2x/ossm-threescale-webassembly-module.adoc
  service_mesh/v2x/threescale-adapter.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh

#39504 [enterprise-4.7] OSSMDOC-434: Clarify 3scale nNav headings.
  _topic_maps/_topic_map.yml
  service_mesh/v2x/ossm-threescale-webassembly-module.adoc
  service_mesh/v2x/threescale-adapter.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/S, Service Mesh, branch/enterprise-4.7

#39505 [enterprise-4.8] OSSMDOC-434: Clarify 3scale Nav headings.
  _topic_maps/_topic_map.yml
  service_mesh/v2x/ossm-threescale-webassembly-module.adoc
  service_mesh/v2x/threescale-adapter.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/S, Service Mesh, branch/enterprise-4.8

#39370 Added notes for release 4.6.51
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.6

#39340 OSDOCS-3014: Add links to pruning for disconnected OLM
  installing/installing-mirroring-installation-images.adoc
  modules/olm-mirroring-catalog-prereqs.adoc
  modules/olm-pruning-index-image.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#39046 [BZ1886092]: Resume all workloads after disaster recovery
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39471 GH#39470 Add 4.9 to docs.okd.io
  _distro_map.yml
  index-community.html
Labels: okd-only, size/XS

#39326 Added notes for 3.11.569 release
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-3.11

#39442 BZ1926013: added an admonition for subscriptions
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/nodes-nodes-working-marking.adoc
  modules/nodes-nodes-working-master-schedulable.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39324 OSDOCS-2975: Add supported profiles table
  _topic_maps/_topic_map.yml
  modules/compliance-supported-profiles.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
  security/compliance_operator/compliance-operator-supported-profiles.adoc
Labels: lgtm, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39137 [OSDOCS-1451] - Specified Managing Security Context Constraints
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  authentication/managing-security-context-constraints.adoc
  modules/security-context-constraints-about.adoc
  modules/security-context-constraints-pre-allocated-values.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#39348 Include RHACS link for preview builds
  scripts/ocpdocs/_previewpage
Labels: size/S

#39351 [RHACS] Imported style edits from main
  _stylesheets/docs.css
  _templates/_page_openshift.html.erb
Labels: size/XXL, RHACS

#39542 Fixed preview page alignment and formatting
  scripts/ocpdocs/_previewpage
Labels: size/L

#39546 BZ1926013: new PR to rectify mistake in PR39442
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: size/XS

#39551 [enterprise-4.7] [skip netlify] new PR to rectify mistake in PR39442
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: size/XS

#39552 [enterprise-4.6] [skip netlify] new PR to rectify mistake in PR39442
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: size/XS

#39558 [enterprise-4.6]: added admonition to this file
  modules/nodes-nodes-working-master-schedulable.adoc
Labels: size/XS

#39557 [enterprise-4.7]: added admonition to this file
  modules/nodes-nodes-working-master-schedulable.adoc
Labels: size/XS

#39538 MIG-972: 1.5.3 legacy operator
  migrating_from_ocp_3_to_4/upgrading-3-4.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
  modules/common-attributes.adoc
  modules/migration-compatibility-guidelines.adoc
  modules/migration-installing-legacy-operator.adoc
  modules/migration-upgrading-mtc-with-legacy-operator.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39563 [enterprise-4.6] MIG-972: 1.5.3 legacy operator
  migrating_from_ocp_3_to_4/upgrading-3-4.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
  modules/common-attributes.adoc
  modules/migration-compatibility-guidelines.adoc
  modules/migration-installing-legacy-operator.adoc
  modules/migration-upgrading-mtc-with-legacy-operator.adoc
Labels: size/L

#39564 [enterprise-4.7] MIG-972: 1.5.3 legacy operator
  migrating_from_ocp_3_to_4/upgrading-3-4.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
  modules/common-attributes.adoc
  modules/migration-compatibility-guidelines.adoc
  modules/migration-installing-legacy-operator.adoc
  modules/migration-upgrading-mtc-with-legacy-operator.adoc
Labels: size/L

#39565 [enterprise-4.8] MIG-972: 1.5.3 legacy operator
  migrating_from_ocp_3_to_4/upgrading-3-4.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
  modules/common-attributes.adoc
  modules/migration-compatibility-guidelines.adoc
  modules/migration-installing-legacy-operator.adoc
  modules/migration-upgrading-mtc-with-legacy-operator.adoc
Labels: size/L

#39280 BZ1945405: Adding port access requirement
  modules/ipi-install-network-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39441 File Integrity Operator release notes
  _topic_maps/_topic_map.yml
  security/file_integrity_operator/file-integrity-operator-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39519 Added notes for release 4.9.10
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#39334 BZ#2023799: clarify installation prog role
  modules/rhcos-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39272 BZ2005326: 4.8 updating quay.io to registry.redhat.io
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8

#39234 BZ2005326: 4.9 updating quay.io to registry.redhat.io
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#39274 BZ2005326: 4.10 updating quay.io to registry.redhat.io
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#39339 CNV-4971: Replace kubevirt api version with v1 version
  modules/virt-about-runstrategies-vms.adoc
  modules/virt-configuring-masquerade-mode-dual-stack.adoc
  modules/virt-configuring-vm-live-migration-cli.adoc
  modules/virt-creating-a-service-from-a-virtual-machine.adoc
  modules/virt-creating-new-vm-from-cloned-pvc-using-datavolumetemplate.adoc
  modules/virt-example-vm-node-placement-node-affinity.adoc
  modules/virt-example-vm-node-placement-node-selector.adoc
  modules/virt-example-vm-node-placement-pod-affinity.adoc
  modules/virt-example-vm-node-placement-tolerations.adoc
  modules/virt-importing-vm-datavolume.adoc
  modules/virt-initiating-vm-migration-cli.adoc
  modules/virt-restoring-vm-from-snapshot-cli.adoc
  modules/virt-schedule-supported-cpu-model-vms.adoc
  modules/virt-template-datavolume-vm.adoc
  modules/virt-template-vm-config.adoc
  modules/virt-template-vm-probe-config.adoc
  modules/virt-template-vm-pxe-config.adoc
  modules/virt-template-windows-vm.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39568 OSDOCS-2974: Updated the Service Definitions regions
  modules/rosa-sdpolicy-account-management.adoc
  modules/sdpolicy-account-management.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39585 Clarify prerequisites for Windows Container Workloads
  windows_containers/enabling-windows-container-workloads.adoc
Labels: lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39509 [RHACS] Fixes to OAuth server docs
  operating/manage-user-access/configure-ocp-oauth.adoc
Labels: Peer Review Done, size/S

#39590 [enterprise-4.8] CNV-4971: Replace kubevirt api version with v1 version
  modules/virt-about-runstrategies-vms.adoc
  modules/virt-configuring-masquerade-mode-dual-stack.adoc
  modules/virt-configuring-vm-live-migration-cli.adoc
  modules/virt-creating-a-service-from-a-virtual-machine.adoc
  modules/virt-creating-new-vm-from-cloned-pvc-using-datavolumetemplate.adoc
  modules/virt-example-vm-node-placement-node-affinity.adoc
  modules/virt-example-vm-node-placement-node-selector.adoc
  modules/virt-example-vm-node-placement-pod-affinity.adoc
  modules/virt-example-vm-node-placement-tolerations.adoc
  modules/virt-importing-vm-datavolume.adoc
  modules/virt-initiating-vm-migration-cli.adoc
  modules/virt-restoring-vm-from-snapshot-cli.adoc
  modules/virt-schedule-supported-cpu-model-vms.adoc
  modules/virt-template-datavolume-vm.adoc
  modules/virt-template-vm-config.adoc
  modules/virt-template-vmi-probe-config.adoc
  modules/virt-template-vmi-pxe-config.adoc
  modules/virt-template-windows-vmi.adoc
Labels: size/M

#39540 [RHACS] Release notes for 3.67.1
  modules/common-attributes.adoc
  release_notes/367-release-notes.adoc
Labels: size/S, RHACS/patch

#39596 Revert MTC legacy operator version number
  modules/common-attributes.adoc
Labels: size/XS

#39416 BZ2015103 Fixed broken URL
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#39574 BZ1945405: Adding port access requirement
  modules/ipi-install-network-requirements.adoc
Labels: size/XS, branch/enterprise-4.6

#39575 BZ1945405: Adding port access requirement
  modules/ipi-install-network-requirements.adoc
Labels: size/XS, branch/enterprise-4.7

#39576 BZ1945405: Adding port access requirement
  modules/ipi-install-network-requirements.adoc
Labels: size/XS, branch/enterprise-4.8

#39506 adds notes for 4.8.23 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#39211 [RHACS] Added ScannerDB restart command
  configuration/reissue-internal-certificates.adoc
  modules/restart-scanner-and-scannerdb-containers.adoc
Labels: Peer Review Done, size/M, RHACS

#39537 BZ2028880: Clarify that MTC installation is for OCP4
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  modules/migration-compatibility-guidelines.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39604 OSDOCS-2988 - Updating the quick ROSA creation procedure
  modules/rosa-sts-creating-a-cluster-quickly.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#39545 BZ2012715: add information about opm index export command
  modules/opm-cli-ref-index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#39554 Adds 4.7.39 release notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7

#39204 BZ2006232: add cloud.redhat.com to the list
  modules/configuring-firewall.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38832 DOCS: Document ODC 4.8 new features and known issues
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, Dev Tools, branch/enterprise-4.8

#38619 CNV-11202: Documenting rollout of node network configuration policy
  modules/virt-creating-interface-on-nodes.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.10

#39357 [MULTIARCH-1073, 1074]:SBO updates for OCP 4.9 from P and Z
  _topic_maps/_topic_map.yml
  applications/connecting_applications_to_services/getting-started-with-service-binding-ibm-power-ibm-z.adoc
  images/img_power.png
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service-power-z.adoc
  modules/sbo-creating-a-postgresql-database-instance-power-z.adoc
  modules/sbo-deploying-a-postgresql-database-operator-power-z.adoc
  modules/sbo-deploying-the-spring-petclinic-sample-application-power-z.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.9, branch/enterprise-4.10

#39184 BZ1900182: Removes versioning-policy section and adds content to usage-oc module
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.9

#39187 Removes versioning policy section in 4.6
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.6

#39185 Removes versioning policy section
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.8

#39186 Removes versioning policy module
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/ocp-4-7-release-notes.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.7

#39188 removes versioning policy module
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#39189 Removes versioning policy section
  _topic_maps/_topic_map.yml
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  release_notes/versioning-policy.adoc
Labels: Peer Review Done, size/M

#39399 RHDEVDOCS-3513 - Update OpenShift Logging Compatibility Table
  logging/cluster-logging-release-notes.adoc
  logging/cluster-logging-upgrading.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#39541 [RHACS] Fix typo in the security context section
  modules/violations-view-deployment-tab.adoc
Labels: Peer Review Done, size/XS

#38778 [RHACS] Added a note about proxy configuration for Helm and Operator
  installing/install-ocp-operator.adoc
  modules/acs-quick-install-using-helm.adoc
  modules/install-central-operator.adoc
Labels: Peer Review Done, size/S, RHACS

#38821 WMCO 3.1.1 RNs
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#39656 Testing search by title
  _javascripts/page-loader.js
Labels: size/M

#39657 Testing search by title
  _javascripts/page-loader.js
Labels: size/XS

#39658 [skip netlify] Update site search
  _javascripts/page-loader.js
Labels: size/XS

#39622 RHDEVDOCS-3566 - Added 4.6 for v1.3.1
  modules/gitops-release-notes-1-3-1.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39665 Update version number of legacy MTC operator for 1.5.3
  modules/common-attributes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38550 BZ1866692: Removed broken MITM transparent proxy information
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39678 [enterprise-4.6] BZ1866692 Removed broken MITM transparent proxy information
  modules/installation-configure-proxy.adoc
Labels: size/XS

#39677 [enterprise-4.7] BZ1866692 Removed broken MITM transparent proxy information
  modules/installation-configure-proxy.adoc
Labels: size/XS

#39612 BZ1960541: annotations
  modules/nw-route-specific-annotations.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39659 BZ1980122: Add quotes arounnd annotation value
  modules/nw-route-specific-annotations.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39629 Added notes for release 3.11.570
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-3.11

#39592 [RHACS]: OCDOCS-2857 - RHACS 3.64 collector version
  release_notes/364-release-notes.adoc
Labels: Peer Review Done, size/XS

#39257 OSDOCS-2557: Add the overview page for registry book
  _topic_maps/_topic_map.yml
  architecture/architecture.adoc
  modules/registry-authentication-enabled-registry-overview.adoc
  modules/registry-authentication.adoc
  modules/registry-integrated-openshift-registry.adoc
  modules/registry-quay-overview.adoc
  modules/registry-third-party-registries.adoc
  registry/architecture-component-imageregistry.adoc
  registry/index.adoc
  registry/registry-options.adoc
  security/container_security/security-registries.adoc
  welcome/index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39672 BZ2018902: Adds removal of Prometheus UI link in 4.9 release notes
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#39690 [enterprise-4.7]BZ1980122: Add quotes arounnd annotation value
  modules/nw-route-specific-annotations.adoc
Labels: size/XS

#39390 OSDOCS-2359 Remove admonition on outdated Azure feature requirement
  modules/installation-about-custom-azure-vnet.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39688 Fix incorrect indefinite article used with {product-title}
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/common-attributes.adoc
  modules/crd-creating-aggregated-cluster-roles.adoc
  modules/infrastructure-node-sizing.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-cluster-nodes-will-not-pxe.adoc
  modules/machineset-osp-adding-bare-metal.adoc
  modules/olm-dependency-resolution-preferences.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  modules/psap-node-feature-discovery-operator.adoc
  post_installation_configuration/network-configuration.adoc
  sandboxed_containers/sandboxed-containers-4.9-release-notes.adoc
  serverless/admin_guide/serverless-cluster-admin-serving.adoc
  serverless/functions/serverless-functions-eventing.adoc
  serverless/knative_serving/serverless-configuring-routes.adoc
  storage/container_storage_interface/persistent-storage-csi-ebs.adoc
  storage/persistent_storage/osd-persistent-storage-aws.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#39283 Document changes to annotation examples
  modules/sbo-categories-of-exposable-binding-data.adoc
  modules/sbo-methods-of-exposing-binding-data.adoc
Labels: Peer Review Done, lgtm, size/M, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#39180 OSDOCS-3000:Changing tab name in web console documentation to match UI
  modules/customizing-project-request-message.adoc
  modules/identity-provider-configuring-using-web-console.adoc
  modules/modifying-template-for-new-projects.adoc
  modules/olm-removing-catalogs.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/quotas-requiring-explicit-quota.adoc
Labels: Peer Review Done, size/S, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10

#39705 Fixing indefinite article errors for {product-title}.
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/common-attributes.adoc
  modules/crd-creating-aggregated-cluster-roles.adoc
  modules/infrastructure-node-sizing.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/ipi-install-troubleshooting-cluster-nodes-will-not-pxe.adoc
  modules/machineset-osp-adding-bare-metal.adoc
  modules/olm-dependency-resolution-preferences.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  modules/psap-node-feature-discovery-operator.adoc
  post_installation_configuration/network-configuration.adoc
  serverless/admin_guide/serverless-cluster-admin-serving.adoc
  serverless/functions/serverless-functions-eventing.adoc
  serverless/knative_serving/serverless-configuring-routes.adoc
  storage/container_storage_interface/persistent-storage-csi-ebs.adoc
  storage/persistent_storage/osd-persistent-storage-aws.adoc
Labels: size/M

#39642 BZ2013910: Updating extra note section
  modules/troubleshooting-disabling-autoreboot-mco-cli.adoc
  modules/troubleshooting-disabling-autoreboot-mco-console.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#39518 CCXDEV-6549: enabling remote health monitoring
  _topic_maps/_topic_map.yml
  modules/insights-operator-new-pull-secret-enable.adoc
  support/remote_health_monitoring/enabling-remote-health-reporting.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#39623 Add links to Helm welcome page and SBO topics with minor edits
  applications/connecting_applications_to_services/getting-started-with-service-binding.adoc
  applications/connecting_applications_to_services/odc-connecting-an-application-to-a-service-using-the-developer-perspective.adoc
  applications/connecting_applications_to_services/projecting-binding-data.adoc
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service.adoc
  welcome/index.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#39256 OSDOCS-2532: Add overview page for a support
  _topic_maps/_topic_map.yml
  support/index.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39732 [enterprise-4.6] OSDOCS-2557: Add the overview page for registry book
  _topic_maps/_topic_map.yml
  architecture/architecture.adoc
  modules/registry-authentication-enabled-registry-overview.adoc
  modules/registry-integrated-openshift-registry.adoc
  modules/registry-quay-overview.adoc
  modules/registry-third-party-registries.adoc
  registry/architecture-component-imageregistry.adoc
  registry/index.adoc
  registry/registry-options.adoc
  security/container_security/security-registries.adoc
  welcome/index.adoc
Labels: size/M

#39452 STOR-679: Cinder CSI TP-> GA RN 4.7
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7

#39437 STOR-679: Cinder CSI TP-> GA RN 4.9
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9

#39660 BZ2020144: Add an option to opm index add command
  modules/olm-updating-index-image.adoc
Labels: Peer Review Done, lgtm, size/XS, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39259 Installing the OpenShift CLI by using the web console
  cli_reference/openshift_cli/getting-started-cli.adoc
  images/CLI-list.png
  images/click-question-mark.png
  modules/cli-installing-cli-web-console-linux.adoc
  modules/cli-installing-cli-web-console-macos.adoc
  modules/cli-installing-cli-web-console-windows.adoc
  modules/cli-installing-cli-web-console.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39318 [enterprise-4.8] [BZ1894774] Add set affinity at installation module to some pages
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-setting-worker-affinity.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.8

#39319 [enterprise-4.7] [BZ1894774] Add set affinity at installation module to some pages
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-setting-worker-affinity.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7

#39320 [enterprise-4.6] [BZ1894774] Add set affinity at installation module to some pages
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-setting-worker-affinity.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6

#39722 Adds a small known issue to the 4.9 RNs
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Needed, size/XS, branch/enterprise-4.9

#39237 Document data model
  applications/connecting_applications_to_services/exposing-binding-data-from-a-service.adoc
  modules/sbo-data-model.adoc
Labels: Peer Review Done, lgtm, size/M, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#39760 SRVCOM-1621: Remove outdated note
  modules/serverless-cluster-sizing-req.adoc
Labels: size/XS, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39613 OTA-472: Reorganizing and adding a channel management chapter
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/machine-health-checks-pausing.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-changing-update-server-web.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  modules/updating-sno.adoc
  post_installation_configuration/cluster-tasks.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-cluster.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.10

#39706 [enterprise-4.9] OTA-472: Adding channel management chapter and remove redundancy
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/machine-health-checks-pausing.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  modules/updating-sno.adoc
  post_installation_configuration/cluster-tasks.adoc
  release_notes/ocp-4-9-release-notes.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-cluster.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.9

#39725 [enterprise-4.8] OTA-472: Adding a chapter and reorganizing
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  post_installation_configuration/cluster-tasks.adoc
  release_notes/ocp-4-8-release-notes.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.8

#39727 [enterprise-4.7] OTA-472: Adding a chapter and removing reorganizing
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/cluster-logging-release-notes-5.0.0.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  post_installation_configuration/cluster-tasks.adoc
  release_notes/ocp-4-7-release-notes.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7

#39728 [enterprise-4.6] OTA-472: Adding a chapter and reorganizing
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/install_config/customizations.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  release_notes/ocp-4-6-release-notes.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6

#39768 [enterprise-4.10] OTA-472: Reorganizing and adding a channel management chapter
  _javascripts/page-loader.js
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/validating-an-installation.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/machine-health-checks-pausing.adoc
  modules/understanding-upgrade-channels.adoc
  modules/unmanaged-operators.adoc
  modules/update-changing-update-server-web.adoc
  modules/update-service-overview.adoc
  modules/update-upgrading-web.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  modules/updating-sno.adoc
  post_installation_configuration/cluster-tasks.adoc
  release_notes/ocp-4-10-release-notes.adoc
  security/container_security/security-hosts-vms.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  updating/installing-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  welcome/index.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: size/L, branch/enterprise-4.10

#39648 BZ1811047: Add RHCOS network teaming example
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39719 BZ2020573: Fix typo in pipelines release notes
  modules/op-release-notes-1-5.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39779 [enterprise-4.8] BZ1811047: Add RHCOS network teaming example
  modules/installation-user-infra-machines-static-network.adoc
Labels: size/S

#39778 [enterprise-4.7] BZ1811047: Add RHCOS network teaming example
  modules/installation-user-infra-machines-static-network.adoc
Labels: size/S, branch/enterprise-4.7

#39777 [enterprise-4.6] BZ1811047: Add RHCOS network teaming example
  modules/installation-user-infra-machines-static-network.adoc
Labels: size/S, branch/enterprise-4.6

#38820 BZ2003722: Add bare metal as platform for SR-IOV Network Operator
  modules/nw-sriov-supported-platforms.adoc
  networking/hardware_networks/about-sriov.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39788 [enterprise 4.6] OSDOCS-2532: Add overview page for a support
  _topic_maps/_topic_map.yml
  support/index.adoc
Labels: size/L

#38896 TELCODOCS: 357 - moving sandboxed containers to dedicated release not…
  _topic_maps/_topic_map.yml
  release_notes/ocp-4-8-release-notes.adoc
  sandboxed_containers/sandboxed-containers-4-8-release-notes.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.8

#39109 WMCO 4.0.1 RNs
  windows_containers/windows-containers-release-notes-4-x.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#39647 Adds a small note that talks about master and node versions matching
  modules/architecture-machine-roles.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39532 Update Web Terminal Operator uninstall docs
  modules/odc-uninstalling-web-terminal.adoc
Labels: Peer Review Done, size/M, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10
