Repository openshift/openshift-docs, pull requests merged in 2021-09, with the labels that each got.

#35866 BZ1994413: Adding info about firewalld to NOTE
  modules/rhel-compute-updating.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35405 Updating console route procedures with formatting changes from OAuth …
  modules/customizing-the-web-console-URL.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.8, branch/enterprise-4.9

#35813 [RHACS]Added release notes for 3.64.1 patch
  modules/acs-quick-install-secured-cluster-using-helm.adoc
  modules/central-configuration-options-operator.adoc
  modules/central-services-private-config.adoc
  modules/central-services-public-config.adoc
  modules/common-attributes.adoc
  modules/download-sensor-bundle.adoc
  modules/enable-traffic-flow-through-custom-ports.adoc
  modules/install-secured-cluster-operator.adoc
  modules/install-sensor-roxctl.adoc
  modules/policy-criteria.adoc
  modules/policy-generation-strategy.adoc
  modules/secured-cluster-services-config.adoc
  modules/using-cli.adoc
  release_notes/364-release-notes.adoc
Labels: Peer Review Done, size/M

#35979 BZ1986796: Controller takes too long to restart on OCP 3.10
  modules/migration-mtc-release-notes-1-5.adoc
Labels: Peer Review Needed, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9

#35922 Update node creation image
  images/create-nodes.png
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35986 [enterprise-4.9] Updating instances of 'host name' to 'hostname'
  contributing_to_docs/term_glossary.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/configuring-firewall.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/identity-provider-github-CR.adoc
  modules/images-configuration-cas.adoc
  modules/images-configuration-parameters.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-creating-aws-dns.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-osp-converting-ignition-resources.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/investigating-kubelet-api-installation-issues.adoc
  modules/ipi-install-bmc-addressing-for-dell-idrac.adoc
  modules/ipi-install-bmc-addressing-for-fujitsu-irmc.adoc
  modules/ipi-install-bmc-addressing-for-hpe-ilo.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nw-annotating-a-route-with-a-cookie-name.adoc
  modules/nw-egress-router-dest-var.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate.adoc
  modules/nw-ingress-creating-an-edge-route-with-a-custom-certificate.adoc
  modules/nw-ipfailover-remove.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-path-based-routes.adoc
  modules/nw-route-admission-policy.adoc
  modules/nw-route-specific-annotations.adoc
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
  modules/osdk-apiservices.adoc
  modules/ossm-routing-ingress.adoc
  modules/ossm-routing.adoc
  modules/persistent-storage-local-create-cr.adoc
  modules/pruning-images-manual.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-platform-certificates.adoc
  modules/serverless-ossm-v1x-tls.adoc
  modules/serverless-ossm-v2x-tls.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/setting-up-vmc-for-vsphere.adoc
  modules/storage-persistent-storage-nfs-provisioning.adoc
  modules/telemetry-what-information-is-collected.adoc
  modules/templates-writing-parameters.adoc
  modules/upi-installation-considerations.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-about-qemu-guest-agent-web.adoc
  modules/virt-cloning-local-volume-to-another-node.adoc
  modules/virt-cloud-init-fields-web.adoc
  modules/virt-disabling-tls-for-registry.adoc
  modules/virt-importing-vm-wizard.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  security/certificate_types_descriptions/user-provided-certificates-for-api-server.adoc
Labels: size/XXL

#35987 [enterprise-4.8] Updating instances of 'host name' to 'hostname'
  contributing_to_docs/term_glossary.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/configuring-firewall.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/identity-provider-github-CR.adoc
  modules/images-configuration-cas.adoc
  modules/images-configuration-parameters.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-creating-aws-dns.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-osp-converting-ignition-resources.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/investigating-kubelet-api-installation-issues.adoc
  modules/ipi-install-bmc-addressing-for-dell-idrac.adoc
  modules/ipi-install-bmc-addressing-for-fujitsu-irmc.adoc
  modules/ipi-install-bmc-addressing-for-hpe-ilo.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nw-annotating-a-route-with-a-cookie-name.adoc
  modules/nw-egress-router-dest-var.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate.adoc
  modules/nw-ingress-creating-an-edge-route-with-a-custom-certificate.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-path-based-routes.adoc
  modules/nw-route-admission-policy.adoc
  modules/nw-route-specific-annotations.adoc
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
  modules/osdk-apiservices.adoc
  modules/ossm-routing-ingress.adoc
  modules/ossm-routing.adoc
  modules/persistent-storage-local-create-cr.adoc
  modules/pruning-images-manual.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-platform-certificates.adoc
  modules/serverless-ossm-v1x-tls.adoc
  modules/serverless-ossm-v2x-tls.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/setting-up-vmc-for-vsphere.adoc
  modules/storage-persistent-storage-nfs-provisioning.adoc
  modules/telemetry-what-information-is-collected.adoc
  modules/templates-writing-parameters.adoc
  modules/upi-installation-considerations.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-about-qemu-guest-agent-web.adoc
  modules/virt-cloning-local-volume-to-another-node.adoc
  modules/virt-cloud-init-fields-web.adoc
  modules/virt-disabling-tls-for-registry.adoc
  modules/virt-importing-vm-wizard.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  security/certificate_types_descriptions/user-provided-certificates-for-api-server.adoc
Labels: size/XXL

#35988 [enterprise-4.7] Updating instances of 'host name' to 'hostname'
  contributing_to_docs/term_glossary.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/configuring-firewall.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/identity-provider-github-CR.adoc
  modules/images-configuration-cas.adoc
  modules/images-configuration-parameters.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-creating-aws-dns.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-osp-converting-ignition-resources.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/investigating-kubelet-api-installation-issues.adoc
  modules/ipi-install-bmc-addressing-for-dell.adoc
  modules/ipi-install-bmc-addressing-for-hpe.adoc
  modules/ipi-install-bmc-addressing.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nw-annotating-a-route-with-a-cookie-name.adoc
  modules/nw-egress-router-dest-var.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate.adoc
  modules/nw-ingress-creating-an-edge-route-with-a-custom-certificate.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-path-based-routes.adoc
  modules/nw-route-admission-policy.adoc
  modules/nw-route-specific-annotations.adoc
  modules/osdk-apiservices.adoc
  modules/ossm-routing-ingress.adoc
  modules/ossm-routing.adoc
  modules/persistent-storage-local-create-cr.adoc
  modules/pruning-images-manual.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-platform-certificates.adoc
  modules/serverless-ossm-v1x-tls.adoc
  modules/serverless-ossm-v2x-tls.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/setting-up-vmc-for-vsphere.adoc
  modules/storage-persistent-storage-nfs-provisioning.adoc
  modules/telemetry-what-information-is-collected.adoc
  modules/templates-writing-parameters.adoc
  modules/upi-installation-considerations.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-about-qemu-guest-agent-web.adoc
  modules/virt-cloning-local-volume-to-another-node.adoc
  modules/virt-cloud-init-fields-web.adoc
  modules/virt-importing-vm-wizard.adoc
  security/certificate_types_descriptions/user-provided-certificates-for-api-server.adoc
Labels: size/L

#35990 [enterprise-4.6] Updating instances of 'host name' to 'hostname'
  contributing_to_docs/term_glossary.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/auth-allowing-javascript-access-api-server.adoc
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/configuring-firewall.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/identity-provider-github-CR.adoc
  modules/images-configuration-cas.adoc
  modules/images-configuration-parameters.adoc
  modules/installation-bootstrap-gather.adoc
  modules/installation-creating-aws-dns.adoc
  modules/installation-creating-mirror-registry.adoc
  modules/installation-osp-converting-ignition-resources.adoc
  modules/installation-osp-creating-control-plane-ignition.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/investigating-kubelet-api-installation-issues.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nw-annotating-a-route-with-a-cookie-name.adoc
  modules/nw-egress-router-dest-var.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-ingress-creating-a-reencrypt-route-with-a-custom-certificate.adoc
  modules/nw-ingress-creating-an-edge-route-with-a-custom-certificate.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-path-based-routes.adoc
  modules/nw-route-admission-policy.adoc
  modules/nw-route-specific-annotations.adoc
  modules/osdk-apiservices.adoc
  modules/ossm-routing-ingress.adoc
  modules/ossm-routing.adoc
  modules/persistent-storage-local-create-cr.adoc
  modules/pruning-images-manual.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-platform-certificates.adoc
  modules/serverless-ossm-v1x-tls.adoc
  modules/serverless-ossm-v2x-tls.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/setting-up-vmc-for-vsphere.adoc
  modules/storage-persistent-storage-nfs-provisioning.adoc
  modules/telemetry-what-information-is-collected.adoc
  modules/templates-writing-parameters.adoc
  modules/upi-installation-considerations.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-about-qemu-guest-agent-web.adoc
  modules/virt-cloning-local-volume-to-another-node.adoc
  modules/virt-cloud-init-fields-web.adoc
  modules/virt-importing-vm-wizard.adoc
  security/certificate_types_descriptions/user-provided-certificates-for-api-server.adoc
Labels: size/L

#35587 SRVOCF-341: Add docs on developing TypeScript functions
  _topic_map.yml
  modules/serverless-testing-typescript-functions.adoc
  modules/serverless-typescript-context-object-reference.adoc
  modules/serverless-typescript-function-return-values.adoc
  modules/serverless-typescript-functions-context-objects.adoc
  modules/serverless-typescript-template.adoc
  serverless/functions/serverless-developing-typescript-functions.adoc
  serverless/functions/serverless-functions-reference-guide.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36000 OSSMDOC-359: Update supported configurations
  modules/ossm-supported-configurations.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35283 BZ1976328: Document the CRI-O can logs the image pull source in the info level log
  installing/installing-mirroring-installation-images.adoc
  installing/validating-an-installation.adoc
  modules/installation-about-mirror-registry.adoc
  modules/viewing-the-image-pull-source.adoc
  openshift_images/samples-operator-alt-registry.adoc
  scalability_and_performance/ztp-deploying-disconnected.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36017 [enterprise-4.6} BZ1976328: Document the CRI-O can logs the image pull source in the info level log
  installing/installing-mirroring-installation-images.adoc
  installing/validating-an-installation.adoc
  modules/installation-about-mirror-registry.adoc
  modules/viewing-the-image-pull-source.adoc
  openshift_images/samples-operator-alt-registry.adoc
Labels: size/M

#36018 [enterprise-4.7} BZ1976328: Document the CRI-O can logs the image pull source in the info level log
  installing/installing-mirroring-installation-images.adoc
  installing/validating-an-installation.adoc
  modules/installation-about-mirror-registry.adoc
  modules/viewing-the-image-pull-source.adoc
  openshift_images/samples-operator-alt-registry.adoc
Labels: size/M

#35208 BZ-1870696: Adding a basic landing page for the security book
  _topic_map.yml
  security/audit-log-view.adoc
  security/compliance_operator/oc-compliance-plug-in-using.adoc
  security/index.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35995 BZ1871806: Split the scaled registry recommendation into two sentences
  modules/recommended-configurable-storage-technology.adoc
Labels: lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35532 GitHub-34018: Updating audit log location to /var/log/origin
  install_config/master_node_configuration.adoc
  security/monitoring.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-3.11

#35961 Adds 4.7.28 release notes
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7

#36034 [enterprise-4.7] BZ-1870696: Adding a basic landing page for the security book
  _topic_map.yml
  security/audit-log-view.adoc
  security/index.adoc
Labels: size/L

#35957 BZ1970360: Adding RHEL 8 requirement for opm
  modules/olm-installing-opm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36035 [enterprise-4.6] BZ-1870696: Adding a basic landing page for the security book
  _topic_map.yml
  security/audit-log-view.adoc
  security/index.adoc
Labels: size/L

#36021 BZ1970360: Adding RHEL 8 requirement for opm - 4.6
  modules/olm-installing-opm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6

#35822 OCPBUGSM-3153: New IBM Z Recommended host practices section in Scalability and Performance
  _topic_map.yml
  modules/ibm-z-boost-networking-performance-with-rfs.adoc
  modules/ibm-z-choose-networking-setup.adoc
  modules/ibm-z-disable-thp.adoc
  modules/ibm-z-ensure-high-disk-performance-hyperpav.adoc
  modules/ibm-z-managing-cpu-overcommitment.adoc
  modules/ibm-z-rhel-kvm-host-recommendations.adoc
  scalability_and_performance/ibm-z-recommended-host-practices.adoc
Labels: Peer Review Done, size/XL, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35608 BZ1949965 - Added Networking Requirements module to RHV UPI
  installing/installing_rhv/installing-rhv-user-infra.adoc
  modules/installation-network-user-infra.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36049 [enterprise-4.7] BZ1949965 - Added Networking Requirements module to RHV UPI
  installing/installing_rhv/installing-rhv-user-infra.adoc
  modules/installation-network-user-infra.adoc
Labels: size/M, branch/enterprise-4.7

#36050 [enterprise-4.6] BZ1949965 - Added Networking Requirements module to RHV UPI
  installing/installing_rhv/installing-rhv-user-infra.adoc
  modules/installation-network-user-infra.adoc
Labels: size/M, branch/enterprise-4.6

#35643 OSDOCS-2395: Add release note for DPDK GA
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#35287 OSDOCS-2225: Multiple egressIPs are load balanced with OVN-Kubernetes
  modules/nw-egress-ips-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#35174 Changed supported NIC device list to table
  modules/nw-sriov-supported-devices.adoc
Labels: lgtm, size/M, branch/enterprise-4.9

#35977 Changed supported NIC device list to table 4.7
  modules/nw-sriov-supported-devices.adoc
Labels: Peer Review Done, lgtm, size/M

#35976 Changed supported NIC device list to table 4.6
  modules/nw-sriov-supported-devices.adoc
Labels: Peer Review Done, lgtm, size/M

#35883 RHDEVDOCS-3176: Add release notes for 4.7 ZStream
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7

#35884 RHDEVDOCS-3176: Add release notes for 4.8 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8

#35882 RHDEVDOCS-3176: Add release notes for 4.6 ZStream
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6

#36072 IBM Z Performance Recommendations - update attribute for rhel first
  scalability_and_performance/ibm-z-recommended-host-practices.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36056 BYO RHEL 7 compute machines is still deprecated in 4.8
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#36058 BYO RHEL 7 compute machines is still deprecated in 4.9
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#36061 [osdocs-2348]: Add auto rotation of etcd certificates for 4.9
  security/certificate_types_descriptions/etcd-certificates.adoc
Labels: size/XS, branch/enterprise-4.9

#35928 OSDOCS-2423 RHEL 8 compute node support
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/installation-requirements-user-infra.adoc
  modules/rhel-adding-more-nodes.adoc
  modules/rhel-adding-node.adoc
  modules/rhel-compute-requirements.adoc
  modules/rhel-compute-updating.adoc
  modules/rhel-images-aws.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
  modules/security-hosts-vms-rhcos.adoc
  post_installation_configuration/node-tasks.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.9

#36012 BZ1918136: adding note re: DDoS protection
  modules/nw-route-specific-annotations.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36080 Clarify specific RHEL 8.y worker node support in RNs
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#35268 CNV-13252: BZ1987068 Adding Prereqs warning of provider limitations
  modules/virt-customizing-storage-profile.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.8, branch/enterprise-4.9

#35748 RHDEVDOCS-3168: Document warning about escalated pipelines SCC privileges in Pipelines TP versions
  modules/op-about-tasks.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, Dev Tools

#35307 OSDOCS-2225: Add release note for OVN-Kubernetes egress IP balancing
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#36097 Adds 4.8.10 release notes
  release_notes/ocp-4-8-release-notes.adoc
Labels: lgtm, size/S

#36078 BZ#1889250: Add the output for "openshift create manifests" command
  modules/installation-disk-partitioning-upi-templates.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35288 OSDOCS-2022: Added support for wildcard domains in Image CR
  modules/images-configuration-parameters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#36057 BZ#1975622-4.7 Resolve merge conflicts during cherry-pick to enterprise-4.7 of PR openshift#35508
  _unused_topics/cluster-logging-exported-fields-ovirt.2021-06-04.adoc
  installing/installing_rhv/installing-rhv-user-infra.adoc
  modules/common-attributes.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-rhv-about-inventory-yml.adoc
  modules/installation-rhv-creating-install-config-file.adoc
  modules/installation-rhv-creating-templates-virtual-machines.adoc
  modules/installing-rhv-requirements.adoc
  modules/installing-rhv-setting-up-ca-certificate.adoc
  modules/installing-rhv-setting-up-installation-machine.adoc
  modules/installing-rhv-verifying-rhv-environment.adoc
  modules/virt-importing-vm-cli.adoc
Labels: size/M

#34704 BZ:1917646: Review documentation to pause MachineConfigPool
  modules/troubleshooting-disabling-autoreboot-mco-cli.adoc
  modules/troubleshooting-disabling-autoreboot-mco-console.adoc
  modules/troubleshooting-disabling-autoreboot-mco.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35588 SRVOCF-346: Add a section on fine-tuning log levels in Node.js functions
  modules/serverless-nodejs-context-object-reference.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34947 Custom certs for the oAuth server route
  authentication/configuring-internal-oauth.adoc
  modules/customizing-the-web-console-URL.adoc
  modules/oauth-customizing-the-oauth-server-URL.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.9

#36066 OSDOCS-2362: Adding release notes for the new descheduler profiles
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.9

#36062 OSDOCS-2362: Adding new descheduler profiles and config
  modules/nodes-descheduler-configuring-profiles.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-descheduler-profiles.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.9

#36069 [RHACS] Added release notes for 3.65
  _topic_map.yml
  configuration/enable-offline-mode.adoc
  modules/common-attributes.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  release_notes/365-release-notes.adoc
Labels: Peer Review Done, lgtm, size/L

#35593 Autogenerate updated CLI docs for 4.9
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.9

#36059 BZ1997621: New RN known issue for 2.5.8
  virt/virt-2-5-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, CNV

#35862 CNV13049: Adding OCS to supported CSI drivers
  modules/persistent-storage-csi-drivers-supported.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36146 CNV-13292: bumping HCO var for 2.5.8
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, CNV

#35958 OSDOCS-2363: Updating Kubernetes version to 1.22.1 for GA
  _unused_topics/looking-inside-nodes.adoc
  _unused_topics/understanding-workers-masters.adoc
  metering/configuring_metering/metering-common-config-options.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/graceful-restart.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-rhv-creating-control-plane-nodes.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-scheduler-node-selectors-cluster.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nodes-scheduler-node-selectors-project.adoc
  modules/querying-the-status-of-cluster-nodes-using-the-cli.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/rhcos-add-extensions.adoc
  modules/rhcos-enabling-multipath-day-2.adoc
  modules/rhel-compute-updating.adoc
  modules/update-upgrading-cli.adoc
  modules/virt-accessing-vm-yaml-ssh.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.9

#30617 OSDOCS-1898: Improving About SCC docs
  modules/security-context-constraints-about.adoc
  modules/security-context-constraints-command-reference.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8

#36071 Added notes for release 4.7.29
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S

#35887 BZ1882568: Added OS Disk requirements for installation
  modules/installation-azure-limits.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36092 Added kubeletConfig API note to the Nodes docs
  modules/nodes-nodes-managing-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35420 GH34445: Doc on using machine config pool during update 2
  _topic_map.yml
  modules/update-using-custom-machine-config-pools-about.adoc
  modules/update-using-custom-machine-config-pools-canary.adoc
  modules/update-using-custom-machine-config-pools-mcp-remove.adoc
  modules/update-using-custom-machine-config-pools-mcp.adoc
  modules/update-using-custom-machine-config-pools-pause.adoc
  modules/update-using-custom-machine-config-pools-unpause.adoc
  updating/update-using-custom-machine-config-pools.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster.adoc
  updating/updating-restricted-network-cluster.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35770 OSSMDOC-213: Update existing federation reference.
  modules/ossm-supported-configurations.adoc
Labels: size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35480 OSDOCS-1488: Add more info to InstallPlan section
  modules/olm-installplan.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35540 Updates to fix #35299 BZ1996069
  modules/cnf-assigning-a-secondary-network-to-a-vrf.adoc
  modules/cnf-assigning-a-sriov-network-to-a-vrf.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36121 RHDEVDOCS-3285 Tracker for 1988271 ClusterLogging retentionPolicy doe…
  modules/cluster-logging-elasticsearch-retention.adoc
Labels: size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35917 [SRVKE-893] Add sink binding ODC docs
  _topic_map.yml
  images/verify-sinkbinding-odc.png
  modules/serverless-pingsource-odc.adoc
  modules/serverless-sinkbinding-odc.adoc
  serverless/event_sources/serverless-sinkbinding.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36180 [enterprise-4.6] [SRVKE-893] Add sink binding ODC docs
  _topic_map.yml
  images/verify-sinkbinding-odc.png
  modules/serverless-pingsource-odc.adoc
  modules/serverless-sinkbinding-odc.adoc
  serverless/event_sources/serverless-sinkbinding.adoc
Labels: size/L

#36178 [enterprise-4.6] OSDOCS-1488: Add more info to InstallPlan section
  modules/olm-installplan.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
Labels: size/L

#36181 SRVKE-893: Follow up with note for 4.7+
  modules/serverless-sinkbinding-odc.adoc
Labels: Peer Review Done, size/XS, Dev Tools, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36149 Adds xref to understanding compute resources section to configuring cluster memory assembly
  nodes/clusters/nodes-cluster-resource-configure.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36190 [enterprise-4.6]RHDEVDOCS-3285 Tracker for 1988271 ClusterLogging ret…
  modules/cluster-logging-elasticsearch-retention.adoc
Labels: size/M

#36196 [enterprise-4.6] OSDOCS-1898: Improving About SCC docs
  modules/security-context-constraints-about.adoc
  modules/security-context-constraints-command-reference.adoc
Labels: size/L

#36060 added notes for 4.6.44 release
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6

#36200 BZ1867056: remove legacy forwarding from fluentd
  modules/cluster-logging-collector-legacy-fluentd.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35743 TELCODOCS-249 - Memory manager release note
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#36134 BZ1921568: Updated parameters description to provision a machine with multiple network interfaces
  modules/machineset-yaml-osp.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36044 Reorganizing "Advanced migration options" assembly
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migrating_from_ocp_3_to_4/advanced-migration-options-3-4.adoc
  migrating_from_ocp_3_to_4/troubleshooting-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
  migration_toolkit_for_containers/troubleshooting-mtc.adoc
  modules/migration-about-migrating-applications-api.adoc
  modules/migration-creating-registry-route-for-dim.adoc
  modules/migration-hooks.adoc
  modules/migration-mapping-destination-namespaces-in-the-migplan-cr.adoc
  modules/migration-mtc-workflow.adoc
  modules/migration-terminology.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9

#36216 [enterprise-4.6] Terminology module
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migrating_from_ocp_3_to_4/advanced-migration-options-3-4.adoc
  migrating_from_ocp_3_to_4/troubleshooting-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
  migration_toolkit_for_containers/troubleshooting-mtc.adoc
  modules/migration-about-migrating-applications-api.adoc
  modules/migration-creating-registry-route-for-dim.adoc
  modules/migration-enabling-cached-kubernetes-clients.adoc
  modules/migration-enabling-pv-resizing-dvm.adoc
  modules/migration-hooks.adoc
  modules/migration-mapping-destination-namespaces-in-the-migplan-cr.adoc
  modules/migration-mtc-workflow.adoc
  modules/migration-terminology.adoc
Labels: size/L

#36217 [enterprise-4.7] Terminology module
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migrating_from_ocp_3_to_4/advanced-migration-options-3-4.adoc
  migrating_from_ocp_3_to_4/troubleshooting-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
  migration_toolkit_for_containers/troubleshooting-mtc.adoc
  modules/migration-about-migrating-applications-api.adoc
  modules/migration-creating-registry-route-for-dim.adoc
  modules/migration-enabling-cached-kubernetes-clients.adoc
  modules/migration-enabling-pv-resizing-dvm.adoc
  modules/migration-hooks.adoc
  modules/migration-mapping-destination-namespaces-in-the-migplan-cr.adoc
  modules/migration-mtc-workflow.adoc
  modules/migration-terminology.adoc
Labels: size/L

#36215 RHDEVDOCS-3288 Formatting fix
  modules/cluster-logging-release-notes-5.1.0.adoc
Labels: size/XS

#36202 [BZ2002579] Restricted install RHEL KVM on IBM Z - add missing sections
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9

#35938 CCXDEV-5554 Insights Operator importing SCA from OCM
  _topic_map.yml
  modules/insights-operator-configuring-sca.adoc
  modules/insights-operator-disabling-sca.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  support/remote_health_monitoring/insights-operator-simple-access.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#36128 OSDOCS-2423 RHEL8 control hosts not yet supported
  modules/rhel-preparing-playbook-machine.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#36238 [Enterprise 4.6] OSSMDOC-213: Update existing federatin reference.
  modules/ossm-supported-configurations.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh

#36164 BZ-2002311: Removing stray paragraph
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  modules/modify-unavailable-workers.adoc
  post_installation_configuration/node-tasks.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36052 OSDOCS-2483: Added note about STS requirements.
  modules/rosa-aws-scp.adoc
Labels: branch/dedicated, Peer Review Done, size/S

#36242 OSSMDOC-213: Update existing federation reference.
  modules/ossm-supported-configurations.adoc
Labels: size/XS, Service Mesh, branch/enterprise-4.7

#36053 Reverting install files incorrectly changed by 35839
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing.adoc
Labels: size/L

#36235 OSSMDOC-376: Fixing YAML indentation in Gateway file.
  modules/ossm-routing.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36158 GH#36147 BM IPI support missed in intro text
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36260 [enterprise-4.6] GH#36147 BM IPI support missed in intro text
  modules/installation-overview.adoc
Labels: size/XS, branch/enterprise-4.6

#35853 OSDOCS-2602: Improve CatalogSource concept docs
  _topic_map.yml
  modules/olm-catalogsource.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/olm-subscription.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36131 OSDOCS-2400: Document how to create custom domains for applications.
  _topic_map.yml
  applications/deployments/osd-config-custom-domains-applications.adoc
  modules/osd-applications-config-custom-domains.adoc
Labels: branch/dedicated, Peer Review Done, size/L

#34739 BZ1917336: add UEFI instructions when using PXE 4.7
  modules/installation-user-infra-machines-pxe.adoc
Labels: size/M, branch/enterprise-4.7

#34732 BZ1917336: add UEFI instructions when using PXE 4.6
  modules/installation-user-infra-machines-pxe.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6

#34743 BZ1917336: add UEFI instructions when using PXE 4.8
  modules/installation-user-infra-machines-pxe.adoc
Labels: size/M, branch/enterprise-4.8, branch/enterprise-4.9

#36093 OSDOCS-2617: clarify credentials rotation for Azure
  modules/manually-rotating-cloud-creds.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36089 TELCODOCS-250: D/S Docs & RN: MPINSTALL-1, Worker deployment via virtualmedia on either provisioning/controlplane network
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-preparing-to-deploy-with-virtual-media-on-the-baremetal-network.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.9

#36246 Picking OCM SCA merge from enterprise-4.9 to main
  _topic_map.yml
  modules/insights-operator-configuring-sca.adoc
  modules/insights-operator-disabling-sca.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  support/remote_health_monitoring/insights-operator-simple-access.adoc
Labels: Peer Review Done, size/M

#36276 Cleanup language for network providers
  _topic_map.yml
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
  networking/ovn_kubernetes_network_provider/rollback-to-openshift-sdn.adoc
Labels: size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34450 Bz1964321 bpg route host names section added to mtc
  migrating_from_ocp_3_to_4/premigration-checklists-3-4.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35749 BZ1997024 'excluded resources' list updated (MTC 1.6.0)
  modules/migration-excluding-resources.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9

#36227 [enterprise-4.6] BZ1921568: Updated parameters description to provision a machine with multiple network interfaces
  modules/machineset-yaml-osp.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6

#36132 [MULTIARCH-1125, 1067] Adding images for IBM Z and Power
  applications/working_with_helm_charts/installing-helm.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.9

#36182 CCO-15: update process for upgrading manually maintained creds
  modules/manually-maintained-credentials-upgrade.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9

#35956 Removing a warning that no longer applies in 4.8+
  modules/nodes-nodes-audit-config-about.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9

#36270 TELCODOCS-250: D/S Docs & RN: MPINSTALL-1, Worker deployment via virtualmedia on either provisioning/controlplane network
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#35037 Updates for publishing on PV2
  _snippets/glusterfs.adoc
  _topic_map.yml
  architecture/acs-architecture.adoc
  installing/install-ocp-operator.adoc
  installing/install-quick-roxctl.adoc
  installing/installing_helm/install-helm-customization.adoc
  installing/installing_helm/install-helm-quick.adoc
  modules/acs-architecture-overview.adoc
  pantheon2.yml
Labels: size/M

#36320 [enterprise-4.6] Remove default custom certificate for Ingress Controller
  modules/nw-ingress-custom-default-certificate-remove.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  networking/ingress-operator.adoc
Labels: size/M, branch/enterprise-4.6

#36321 [enterprise-4.7] Remove default custom certificate for Ingress Controller
  modules/nw-ingress-custom-default-certificate-remove.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  networking/ingress-operator.adoc
Labels: size/M, branch/enterprise-4.7

#35762 OSDOCS-2272 - Enhancing the ROSA STS documentation
  modules/rosa-deleting-aws-resources-aws-console.adoc
  modules/rosa-deleting-aws-resources-cli.adoc
  modules/rosa-deleting-cluster.adoc
  modules/rosa-sts-about-iam-resources.adoc
  modules/rosa-sts-creating-cluster.adoc
  modules/rosa-using-sts.adoc
  rosa_architecture/rosa-understanding.adoc
  rosa_getting_started_sts/rosa-sts-creating-cluster.adoc
  rosa_getting_started_sts/rosa-sts-deleting-cluster.adoc
  rosa_getting_started_sts/rosa-sts-getting-started-workflow.adoc
Labels: Peer Review Done, size/L

#36264 4.9 rn dummy
  virt/virt-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, CNV

#36236 RN: Addition of 4-9 RN file.
  _topic_map.yml
  modules/virt-supported-cluster-version.adoc
  virt/virt-4-8-release-notes.adoc
  virt/virt-4-9-release-notes.adoc
Labels: Peer Review Done, size/L, CNV, branch/enterprise-4.9

#36328 GH#36271: redirect loop on docs.okd.io
  welcome/index.adoc
Labels: okd-only, size/S, branch/enterprise-4.8, branch/enterprise-4.9

#36255 Added notes for 4.8.11 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#35276 OSDOCS-2395: Graduate DPDK to GA
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
  networking/hardware_networks/using-dpdk-and-rdma.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#35934 OSDOCS-2471: Update capabilities list for SR-IOV DPDK and RDMA examples
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-example-vf-function-in-pod.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
Labels: size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36129 Remove text that pull secret change reboots node
  modules/images-update-global-pull-secret.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34728 OSDOCS-2174: MetalLB Operator and load balancer
  _topic_map.yml
  images/nw-metallb-layer2.png
  modules/nw-metallb-addresspool-cr.adoc
  modules/nw-metallb-configure-address-pool.adoc
  modules/nw-metallb-configure-svc.adoc
  modules/nw-metallb-example-addresspool.adoc
  modules/nw-metallb-infra-considerations.adoc
  modules/nw-metallb-installing-operator-cli.adoc
  modules/nw-metallb-layer2-extern-traffic-pol.adoc
  modules/nw-metallb-layer2-limitations.adoc
  modules/nw-metallb-layer2.adoc
  modules/nw-metallb-operator-custom-resources.adoc
  modules/nw-metallb-operator-initial-config.adoc
  modules/nw-metallb-software-components.adoc
  modules/nw-metallb-when-metallb.adoc
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  networking/configuring_ingress_cluster_traffic/overview-traffic.adoc
  networking/metallb/about-metallb.adoc
  networking/metallb/images
  networking/metallb/metallb-configure-address-pools.adoc
  networking/metallb/metallb-configure-services.adoc
  networking/metallb/metallb-operator-install.adoc
  networking/metallb/modules
Labels: Peer Review Done, size/XL, branch/enterprise-4.9

#35852 Add warning about runlevels.
  modules/cnf-installing-the-operators.adoc
  modules/cnf-installing-the-performance-addon-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/security-context-constraints-about.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36345 [enterprise-4.7] Add warning about runlevels.
  modules/cnf-installing-the-operators.adoc
  modules/cnf-installing-the-performance-addon-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/security-context-constraints-about.adoc
Labels: size/M

#36346 [enterprise-4.6] Add warning about runlevels.
  modules/cnf-installing-the-performance-addon-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/security-context-constraints-about.adoc
Labels: size/M

#35311 BZ1988324: Add note that egress firewall blocks API endpoints
  modules/nw-egressnetworkpolicy-about.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36363 [enterprise-4.7] Update capabilities list for SR-IOV DPDK and RDMA examples
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-example-vf-function-in-pod.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
Labels: size/M, branch/enterprise-4.7

#36364 [enterprise-4.6] Update capabilities list for SR-IOV DPDK and RDMA examples
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-example-vf-function-in-pod.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
Labels: size/M, branch/enterprise-4.6

#35705 OSDOCS-2174: RN for MetalLB
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#36367 Typo fix: added missing full stop
  modules/images-configuration-parameters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#36325 [BZ2003724] Add installer note for IBM Z and P
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36115 CNV-5635: Documented UI for sysprep
  modules/virt-creating-vm-wizard-web.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.9

#36308 CNV11325: Adding information about support for preallocation disk parameter
  modules/virt-add-disk-to-vm.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.9

#36380 [BZ2003724] Enterprise 4.7 only Add installer note for IBM Z and P
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7

#36113 TELCODOCS-268: Removed TP, added new note
  modules/cnf-assigning-a-secondary-network-to-a-vrf.adoc
  modules/cnf-assigning-a-sriov-network-to-a-vrf.adoc
  networking/hardware_networks/configuring-sriov-device.adoc
  networking/multiple_networks/assigning-a-secondary-network-to-a-vrf.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#36104 [BZ1886382] Added prerequisites for provisioning local volumes
  modules/persistent-storage-local-create-cr.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36389 [enterprise-4.6] Add note that egress firewall blocks API endpoints
  modules/nw-egressnetworkpolicy-about.adoc
Labels: size/M, branch/enterprise-4.6

#36301 Adds 4.7.30 RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7

#35589 BZ-1982575: Adding a note about worker node verification
  modules/update-upgrading-web.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35854 Update steps to account for cross-namespace Argo CD permission cleanup
  modules/gitops-creating-an-application-by-using-the-argo-cd-dashboard.adoc
  modules/gitops-creating-an-application-by-using-the-oc-tool.adoc
Labels: Peer Review Done, size/S, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36394 [enterprise-4.6][BZ1982575] Adding a note about worker node verification
  modules/update-upgrading-web.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6

#36400 [enterprise-4.8] OSDOCS-2602: Improve CatalogSource concept docs
  _topic_map.yml
  modules/olm-catalogsource.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/olm-subscription.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
Labels: size/L

#36369 Adds 3.11.521 release notes
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-3.11

#36402 [enterprise-4.6] OSDOCS-2602: Improve CatalogSource concept docs
  _topic_map.yml
  modules/olm-catalogsource.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/olm-subscription.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
Labels: size/L

#36234 OSDOCS-1801: Adding release notes for new audit policy options
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.9

#36341 Removing root prompt that isn't necessary
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36303 bz1944506: added alternative actions.
  modules/compliance-tailored-profiles.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#36401 [enterprise-4.7] OSDOCS-2602: Improve CatalogSource concept docs
  _topic_map.yml
  modules/olm-catalogsource.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/olm-subscription.adoc
  operators/admin/olm-status.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
Labels: size/L

#36136 Pulling in CLI doc updates after freeze
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: Peer Review Done, lgtm, size/XL, branch/enterprise-4.9

#36002 OSDOCS-2366: Release notes for customizing the OAuth server URL
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9
