Repository openshift/openshift-docs, pull requests merged in 2021-08, with the labels that each got.

#34931 BZ1964901: Manually rolling back migration, uninstalling
  migrating_from_ocp_3_to_4/troubleshooting-3-4.adoc
  migration_toolkit_for_containers/troubleshooting-mtc.adoc
  modules/migration-rolling-back-migration-cli.adoc
  modules/migration-rolling-back-migration-manually.adoc
  modules/migration-rolling-back-migration-web-console.adoc
  modules/migration-uninstalling-mtc-clean-up.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, qe-approved, size/L

#35066 Small fixes
  migrating_from_ocp_3_to_4/migrating-applications-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/migrating-applications-with-mtc.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#35069 [enterprise-4.6] Small fixes
  migrating_from_ocp_3_to_4/migrating-applications-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/migrating-applications-with-mtc.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
Labels: size/S

#35070 [enterprise-4.7] Small fixes
  migrating_from_ocp_3_to_4/migrating-applications-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  migration_toolkit_for_containers/migrating-applications-with-mtc.adoc
  migration_toolkit_for_containers/upgrading-mtc.adoc
Labels: size/S

#35071 [skip netlify] added 4.9 site
  _distro_map.yml
Labels: size/XS

#35050 RNs: Added notes for release 4.8.3
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#35044 BZ1987326: Enhance note for IBM Z reqs for three-node cluster
  installing/installing_ibm_z/installing-ibm-z.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-operators-config.adoc
  modules/installation-three-node-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/L

#34700 SRVKS-562: Restrictive network policy docs for Knative services
  modules/serverless-services-network-policies.adoc
  serverless/knative_serving/serverless-applications.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/M

#34810 BZ1840935: Adding configuration APIs for control plane
  _topic_map.yml
  modules/tls-profiles-ingress-configuring.adoc
  modules/tls-profiles-kubernetes-configuring.adoc
  modules/tls-profiles-understanding.adoc
  modules/tls-profiles-view-details.adoc
  networking/ingress-operator.adoc
  security/tls-security-profiles.adoc
Labels: size/L

#35048 Correcting some style issues
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  contributing_to_docs/doc_guidelines.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/adding-bare-metal-host-to-cluster-using-web-console.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/builds-buildconfig.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-dashboards-access.adoc
  modules/compliance-review.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/dedicated-storage-expanding-filesystem-pvc.adoc
  modules/install-sno-installing-with-usb-media.adoc
  modules/installation-approve-csrs.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/monitoring-running-metrics-queries.adoc
  modules/nodes-containers-init-creating.adoc
  modules/nodes-nodes-jobs-creating.adoc
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
  modules/odc-monitoring-your-project-metrics.adoc
  modules/op-about-triggers.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-vs-istio-1x.adoc
  modules/ossm-vs-istio.adoc
  modules/persistent-storage-local-uninstall-operator.adoc
  modules/psap-driver-toolkit-using.adoc
  modules/rbac-users.adoc
  modules/registry-quay-overview.adoc
  modules/security-pod-scan-cso.adoc
  modules/security-registries-ecosystem.adoc
  modules/serverless-getting-support.adoc
  modules/setting-up-topology-manager.adoc
  modules/support.adoc
  modules/templates-rails-creating-frontend-service.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-installing-virtio-drivers-existing-windows.adoc
  modules/virt-installing-virtio-drivers-installing-windows.adoc
  modules/web-console-overview.adoc
  nodes/edge/nodes-edge-remote-workers.adoc
  openshift_images/managing_images/image-pull-policy.adoc
  security/certificate_types_descriptions/node-certificates.adoc
  serverless/functions/serverless-functions-about.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes-block.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.adoc
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/L

#35081 [enterprise-4.8] Correcting some style issues
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  contributing_to_docs/doc_guidelines.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/adding-bare-metal-host-to-cluster-using-web-console.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/builds-buildconfig.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-dashboards-access.adoc
  modules/compliance-review.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/dedicated-storage-expanding-filesystem-pvc.adoc
  modules/install-sno-installing-with-usb-media.adoc
  modules/installation-approve-csrs.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/monitoring-running-metrics-queries.adoc
  modules/nodes-containers-init-creating.adoc
  modules/nodes-nodes-jobs-creating.adoc
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
  modules/odc-monitoring-your-project-metrics.adoc
  modules/op-about-triggers.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-vs-istio-1x.adoc
  modules/ossm-vs-istio.adoc
  modules/persistent-storage-local-uninstall-operator.adoc
  modules/psap-driver-toolkit-using.adoc
  modules/rbac-users.adoc
  modules/registry-quay-overview.adoc
  modules/security-pod-scan-cso.adoc
  modules/security-registries-ecosystem.adoc
  modules/serverless-getting-support.adoc
  modules/setting-up-topology-manager.adoc
  modules/support.adoc
  modules/templates-rails-creating-frontend-service.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-installing-virtio-drivers-existing-windows.adoc
  modules/virt-installing-virtio-drivers-installing-windows.adoc
  modules/web-console-overview.adoc
  nodes/edge/nodes-edge-remote-workers.adoc
  openshift_images/managing_images/image-pull-policy.adoc
  security/certificate_types_descriptions/node-certificates.adoc
  serverless/functions/serverless-functions-about.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes-block.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.adoc
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: size/L

#35080 [enterprise-4.9] Correcting some style issues
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  modules/accessing-hosts-on-aws.adoc
  modules/adding-bare-metal-host-to-cluster-using-web-console.adoc
  modules/bound-sa-tokens-configuring.adoc
  modules/builds-buildconfig.adoc
  modules/builds-tutorial-pipeline.adoc
  modules/cluster-logging-about-logstore.adoc
  modules/cluster-logging-dashboards-access.adoc
  modules/compliance-review.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/dedicated-storage-expanding-filesystem-pvc.adoc
  modules/install-sno-installing-with-usb-media.adoc
  modules/installation-approve-csrs.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-troubleshooting-bootstrap-vm.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  modules/metering-exposing-the-reporting-api.adoc
  modules/monitoring-running-metrics-queries.adoc
  modules/nodes-containers-init-creating.adoc
  modules/nodes-nodes-jobs-creating.adoc
  modules/nw-sriov-dpdk-example-intel.adoc
  modules/nw-sriov-dpdk-example-mellanox.adoc
  modules/nw-sriov-rdma-example-mellanox.adoc
  modules/odc-monitoring-your-project-metrics.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/ossm-remove-operators.adoc
  modules/ossm-vs-istio-1x.adoc
  modules/ossm-vs-istio.adoc
  modules/persistent-storage-local-uninstall-operator.adoc
  modules/psap-driver-toolkit-using.adoc
  modules/rbac-users.adoc
  modules/registry-quay-overview.adoc
  modules/security-pod-scan-cso.adoc
  modules/security-registries-ecosystem.adoc
  modules/serverless-getting-support.adoc
  modules/setting-up-topology-manager.adoc
  modules/support.adoc
  modules/templates-rails-creating-frontend-service.adoc
  modules/using-wildcard-routes.adoc
  modules/virt-installing-virtio-drivers-existing-windows.adoc
  modules/virt-installing-virtio-drivers-installing-windows.adoc
  modules/web-console-overview.adoc
  nodes/edge/nodes-edge-remote-workers.adoc
  openshift_images/managing_images/image-pull-policy.adoc
  security/certificate_types_descriptions/node-certificates.adoc
  serverless/functions/serverless-functions-about.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes-block.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.adoc
  welcome/index.adoc
  welcome/oke_about.adoc
Labels: size/L

#35054 BZ#1986989: known issue and workaround for 4.8 upgrade bug
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/M

#35084 Fixing indentation and formatting
  modules/creating-a-project-using-the-CLI.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#34821 RHDEVDOCS-3181: Instructions for updating to OpenShift Logging 5.1
  logging/cluster-logging-release-notes.adoc
  logging/cluster-logging-upgrading.adoc
  logging/troubleshooting/cluster-logging-troubleshooting-for-critical-alerts.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-updating-logging-to-5-0.adoc
  modules/cluster-logging-updating-logging-to-5-1.adoc
Labels: size/L

#35100 [enterprise-4.7] RHDEVDOCS-3181: Instructions for updating to OpenShift Logging 5.1
  logging/cluster-logging-release-notes.adoc
  logging/cluster-logging-upgrading.adoc
  logging/troubleshooting/cluster-logging-troubleshooting-for-critical-alerts.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-updating-logging-to-5-0.adoc
  modules/cluster-logging-updating-logging-to-5-1.adoc
Labels: size/L

#34455 Added endpoint config topic
  _topic_map.yml
  configuration/configure-endpoints.adoc
  modules/configure-endpoints-existing.adoc
  modules/configure-endpoints-new-install.adoc
  modules/custom-yaml-configuration.adoc
  modules/enable-traffic-flow-through-custom-ports.adoc
  modules/restart-central-container.adoc
Labels: Peer Review Done, size/L

#34988 BZ-1869593: Recommend against modifying the default roles
  modules/rbac-overview.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/XS

#34587 RHDEVDOCS-2882-2: Tracker for Bug 1942908 - Include prerequisites sect…
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: lgtm, size/M

#35088 BZ1857153: Renamed the section title in TOC and in the section itself for consistency
  _topic_map.yml
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35001 BZ1945073: Replace DeploymentConfig with Deployment
  applications/deployments/route-based-deployment-strategies.adoc
  modules/deployments-ab-testing-lb.adoc
  modules/deployments-blue-green.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/S

#35121 [enterprise-4.6] RHDEVDOCS-2882-2: Tracker for Bug 1942908 - Include …
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: size/M

#35119 [enterprise-4.7] RHDEVDOCS-2882-2: Tracker for Bug 1942908 - Include …
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: size/M

#35057 OSSMDOC-371: Remove stray character in output
  modules/ossm-tutorial-bookinfo-install.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35106 [Enterprise-4.7+]: Azure Installation Note Cleanup
  modules/installation-initializing.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35094 Fixing build and some other minor issues
  cicd/pipelines/securing-webhooks-with-event-listeners.adoc
  logging/troubleshooting/cluster-logging-troubleshooting-for-critical-alerts.adoc
  modules/builds-identifying-image-change-triggers.adoc
  modules/cnf-adjusting-nic-queues-with-the-performance-profile.adoc
  modules/cnf-logging-associated-with-adjusting-nic-queues.adoc
  modules/cnf-verifying-queue-status.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  modules/nw-router-configuring-dual-stack.adoc
  modules/op-providing-secure-connection.adoc
  modules/op-release-notes-1-5.adoc
  modules/op-sample-eventlistener-resource.adoc
  modules/ossm-observability-visual.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/tls-profiles-ingress-configuring.adoc
  modules/virt-cloning-a-datavolume.adoc
  modules/ztp-acm-adding-images-to-mirror-registry.adoc
  serverless/knative_serving/serverless-ossm-with-kourier-jwt.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/ossm-reference-smcp.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/M

#30719 GH#30718: Modify code block options in RHV playbooks module
  modules/installation-rhv-downloading-ansible-playbooks.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35128 TELCODOCS-111: KNIDEPLOY-3655, Support Fujitsu nodes in OCP Metal
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35146 [enterprise-4.7] Fixing build and some other minor issues
  logging/troubleshooting/cluster-logging-troubleshooting-for-critical-alerts.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
  modules/ossm-observability-visual.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/tls-profiles-ingress-configuring.adoc
  serverless/knative_serving/serverless-ossm-with-kourier-jwt.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/ossm-reference-smcp.adoc
Labels: size/M

#35147 [enterprise-4.6] Fixing build and some other minor issues
  modules/ossm-observability-visual.adoc
  modules/ossm-rn-technology-preview.adoc
  serverless/knative_serving/serverless-ossm-with-kourier-jwt.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/ossm-reference-smcp.adoc
Labels: size/M

#35149 RFE-1839: Including GCP Global Access module in assembly where it is missing
  installing/installing_gcp/installing-gcp-private.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35086 CNV-12482: New content for skip node annotation
  _topic_map.yml
  modules/virt-using-skip-node.adoc
  virt/node_maintenance/virt-preventing-node-reconciliation.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/M

#35137 [WMCO-3.x]: Revealed the hidden WMCO 3.x content for 4.8+
  _topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  windows_containers/disabling-windows-container-workloads.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/M

#35111 virt: node placement: there are two nodePlacement fields
  modules/virt-about-node-placement-virtualization-components.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35059 Rel Notes doc text for 4.7.22 release
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#34932 [BZ1986947] Change volumeMode value in OSP custom PVC mode
  modules/installation-registry-osp-creating-custom-pvc.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/XS

#34975 BZ-1855261: Updating to approve pending kubelet serving CSRs
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/S

#35056 Bug 1988311: Fix typo in modules/psap-driver-toolkit-using.adoc
  modules/psap-driver-toolkit-using.adoc
Labels: branch/enterprise-4.8, branch/enterprise-4.9, bugzilla/invalid-bug, bugzilla/severity-high, lgtm, size/XS

#35122 vsphere: move nsx-t lower in table; mark optional
  modules/installation-vsphere-infrastructure.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#35120 Fixed broken links and changed title for release 4.5.35
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/XS

#35170 RHDEVDOCS-3203 Document stable option
  modules/cluster-logging-deploy-cli.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/S

#35087 BZ1867031: Added missing preposition, "to"
  modules/nodes-scheduler-node-selectors-pod.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/XS

#32545 OSDOCS-2012 Draft start for WMCO 3.x release notes
  _topic_map.yml
  windows_containers/windows-containers-release-notes-2-x.adoc
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: Peer Review Needed, branch/enterprise-4.8, branch/enterprise-4.9, size/L

#35187 [enterprise-4.6] vsphere: move nsx-t lower in table; mark optional
  modules/installation-vsphere-infrastructure.adoc
Labels: size/XS

#35051 Added notes for release 3.11.487
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/L

#35179 [WMCO-2.x]: Added a note to the WMCO 2.x release note set
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#35190 [WMCO-3.x]: Updated the WMCO 3.x release notes with some feedback
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: Peer Review Done, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#30926 GH#27491: Added Network Time Protocol (NPT) as a Networking req
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XS

#34943 OSDOCS-2229: Added `list instance-types` command to ROSA CLI documentation.
  modules/rosa-list-objects.adoc
  modules/rosa-upgrade-cluster-cli.adoc
Labels: Peer Review Done, size/M

#35025 GH32085: Add note to etcd encryption section
  modules/about-etcd-encryption.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/XS

#32871 GH#32345: Fix example pod configuration
  modules/nodes-pods-using-example.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/M

#35096 CNV-10740: FIPS compliant mode
  virt/install/preparing-cluster-for-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.9, size/XS

#35020 OSDOCS-2336: Added consequences about shutting down the infrastructure through the…
  modules/rosa-sdpolicy-account-management.adoc
  modules/rosa-sdpolicy-networking.adoc
Labels: Peer Review Done, size/XS

#35107 BZ1840935: Adding config APIs for control plane - Backporting from 4.7 to 4.6
  _topic_map.yml
  modules/tls-profiles-ingress-configuring.adoc
  modules/tls-profiles-kubernetes-configuring.adoc
  modules/tls-profiles-understanding.adoc
  modules/tls-profiles-view-details.adoc
  networking/ingress-operator.adoc
  security/tls-security-profiles.adoc
Labels: Peer Review Needed, branch/enterprise-4.6, size/L

#35046 Added notes for release 4.6.41
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#34913 OSDOCS-2294: Clarified the OCM console steps for IDPs and accessing the ROSA cluste…
  _topic_map.yml
  modules/config-github-idp.adoc
  modules/config-gitlab-idp.adoc
  modules/config-google-idp.adoc
  modules/config-ldap-idp.adoc
  modules/config-openid-idp.adoc
  modules/rosa-creating-cluster.adoc
  modules/understanding-idp.adoc
  rosa_getting_started/rosa-accessing-cluster.adoc
  rosa_getting_started/rosa-config-identity-providers.adoc
  rosa_getting_started/rosa-getting-started-workflow.adoc
  rosa_getting_started_sts/rosa-sts-accessing-cluster.adoc
  rosa_getting_started_sts/rosa-sts-config-identity-providers.adoc
  rosa_getting_started_sts/rosa-sts-getting-started-workflow.adoc
Labels: Peer Review Done, size/M

#35209 [enterprise-4.6]GH32085: Add note to etcd encryption section
  modules/about-etcd-encryption.adoc
Labels: size/XS

#34811 SME Edit Requests
  _topic_map.yml
  administering_a_cluster/dedicated-admin-role.adoc
  modules/ccs-aws-iam.adoc
  modules/ccs-aws-provisioned.adoc
  modules/managing-dedicated-administrators.adoc
  modules/osd-intro.adoc
  modules/osd-vs-ocp.adoc
  modules/sdpolicy-account-management.adoc
  modules/sdpolicy-logging.adoc
  modules/sdpolicy-monitoring.adoc
  modules/sdpolicy-networking.adoc
  modules/sdpolicy-platform.adoc
  modules/sdpolicy-security.adoc
  modules/sdpolicy-storage.adoc
  modules/upgrade-auto.adoc
  modules/upgrade.adoc
  osd_planning/aws-ccs.adoc
  osd_planning/config-aws-account.adoc
  osd_planning/config-gcp-account.adoc
  osd_planning/gcp-ccs.adoc
  osd_private_connections/private-cluster.adoc
  upgrading/osd-upgrades.adoc
Labels: Peer Review Done, branch/dedicated, size/L

#35222 [skip netlify] Dedicated 4 redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#34899 WMCO-2.0.3: Added a new bug fix for the WMCO 2.0.3 release note set.
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/S

#34934 BZ1945837: Revised second application example
  modules/deployments-ab-testing-lb.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, lgtm, size/XS

#34891 RHDEVDOCS-2677 Document "Allow storing and querying of structured log…
  _topic_map.yml
  logging/cluster-logging-enabling-json-logging.adoc
  logging/cluster-logging-exported-fields.adoc
  logging/cluster-logging-external.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-collector.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-kafka.adoc
  modules/cluster-logging-collector-log-forward-logs-from-application-pods.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-configuration-of-json-log-data-for-default-elasticsearch.adoc
  modules/cluster-logging-exported-fields-kubernetes.adoc
  modules/cluster-logging-exported-fields-top-level-fields.adoc
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
  modules/cluster-logging-json-log-forwarding.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/XL

#35095 BZ:1886814 Updated image repository from MyBox to RedHat
  modules/nodes-containers-init-creating.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#35218 BZ1869798: Change message to have only IPI cluster
  modules/private-clusters-setting-api-private.adoc
  post_installation_configuration/configuring-private-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#35219 BZ1869798: Change in message to show only IPI cluster for 4.6
  installing/install_config/configuring-private-cluster.adoc
  modules/private-clusters-setting-api-private.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#35150 BZ1989538: Remove trust bundle steps from ShiftStack clouds.yaml definition procedure
  modules/installation-osp-describing-cloud-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, size/S

#35197 BZ1933909: Removed ClusterPV from table
  modules/vsphere-problem-detector-config-checks.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34896 BZ1917343: Additional steps for adding nodes to an existing cluster is missing.
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6

#35249 Added missing tech preview label to Driver Toolkit docs
  scalability_and_performance/psap-driver-toolkit.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9

#35251 Updated 4.8 RNs to reflect Driver Toolkit's Tech Preview status
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#35250 Fix an indentation issue
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34475 BZ1980340: [DOC-OCPRHV] Add resize to ovirt CSI driver
  modules/dynamic-provisioning-aws-definition.adoc
  modules/dynamic-provisioning-ceph-rbd-definition.adoc
  modules/ovirt-csi-driver-storage-class.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/persistent-storage-rhv.adoc
  post_installation_configuration/storage-configuration.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#35254 [enterprise-4.7] Fix an indentation issue
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35257 [enterprise-4.8] Fix an indentation issue
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35258 [enterprise-4.9] Fix an indentation issue
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35210 OSSMDOC-374: Jaeger 1.24.0 Release Notes.
  jaeger/jaeger_install/rhbjaeger-updating.adoc
  modules/jaeger-document-attributes.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-known-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/ossm-install-ossm-operator.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35248 RHDEVDOCS-3217 Tweaks to JSON parsing topics
  logging/cluster-logging.adoc
  modules/cluster-logging-configuration-of-json-log-data-for-default-elasticsearch.adoc
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
  modules/cluster-logging-json-log-forwarding.adoc
  modules/cluster-logging-maintenance-support-list.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35198 BZ1973254: Added requested additional RBAC rules to Mirroring to the cluster internal registry
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9

#35264 RHDEVDOCS-3217 Tweaks to JSON logging topics
  logging/cluster-logging.adoc
  modules/cluster-logging-configuration-of-json-log-data-for-default-elasticsearch.adoc
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
  modules/cluster-logging-json-log-forwarding.adoc
  modules/cluster-logging-maintenance-support-list.adoc
Labels: size/S

#35270 Refix format issue where indentation is not correct
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35273 [enterprise-4.7] Refix format issue where indentation is not correct
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35274 [enterprise-4.8] Refix format issue where indentation is not correct
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35275 [enterprise-4.9] Refix format issue where indentation is not correct
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/XS

#35244 [BZ1990497]: Removed a redundant URL from the allowlist.
  modules/configuring-firewall.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35277 Fix kubelet typo again
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35286 [skip netlify] update index - add ACS
  index-commercial.html
Labels: size/M

#35272 [enterprise-4.7] OSSMDOC-374: Jaeger 1.24.0 Release Notes.
  jaeger/jaeger_install/rhbjaeger-updating.adoc
  modules/jaeger-document-attributes.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-known-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/ossm-install-ossm-operator.adoc
Labels: size/M

#35271 [enterprise-4.6] OSSMDOC-374: Jaeger 1.24.0 Release Notes.
  jaeger/jaeger_install/rhbjaeger-updating.adoc
  modules/jaeger-document-attributes.adoc
  modules/jaeger-install-elasticsearch.adoc
  modules/jaeger-rn-fixed-issues.adoc
  modules/jaeger-rn-known-issues.adoc
  modules/jaeger-rn-new-features.adoc
  modules/ossm-install-ossm-operator.adoc
Labels: size/M

#34592 RHDEVDOCS-2836: Document on when expressions and final tasks of the finally section for Pipelines 1.5
  cicd/pipelines/understanding-openshift-pipelines.adoc
  images/op-pipeline-details.png
  modules/op-about-finally_tasks.adoc
  modules/op-about-whenexpression.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
Labels: Peer Review Done, size/L, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9

#35215 BZ1973602: Update operator conditions and operator overrides
  modules/olm-operatorconditions-about.adoc
  modules/olm-overriding-operatorconditions.adoc
  modules/olm-supported-operatorconditions.adoc
Labels: Peer Review Done, lgtm, size/XS, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9

#35034 BZ1984781: Add SCC step to Helm OSDK guides
  modules/osdk-create-cr.adoc
  modules/osdk-quickstart.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35189 Bug 1975784, added oc-compliance plug-in installation procedure
  modules/oc-compliance-installing.adoc
  security/oc_compliance_plug_in/oc-compliance-plug-in-using.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9

#35310 OSDOCS-2304: Add back supported platforms for OVN-Kubernetes migration
  modules/nw-ovn-kubernetes-migration-about.adoc
Labels: size/S, branch/enterprise-4.8, branch/enterprise-4.9

#35318 OSDOCS-2409: Update name of role for SRE access to AWS
  modules/policy-identity-access-management.adoc
  modules/rosa-policy-identity-access-management.adoc
Labels: size/XS

#35109 BZ1888035: Replace MCG module with link to OCS doc
  migrating_from_ocp_3_to_4/installing-3-4.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-mtc-workflow.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9

#35322 [enterprise-4.6] BZ1888035: Update MCG procedure
  migrating_from_ocp_3_to_4/installing-3-4.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-mtc-workflow.adoc
Labels: size/L

#35323 BZ1888035: Update MCG procedure
  migrating_from_ocp_3_to_4/installing-3-4.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-mtc-workflow.adoc
Labels: size/L

#35110 Adding a conscious language section to the guidelines
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/S

#35325 Planning considerations assembly added
  _topic_map.yml
  migrating_from_ocp_3_to_4/planning-considerations-3-4.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35333 Commenting out unused assembly
  _topic_map.yml
Labels: size/XS

#35334 commenting out unused assembly
  _topic_map.yml
Labels: size/XS

#35335 commenting out unused assembly
  _topic_map.yml
Labels: size/XS

#35336 Commenting out unused assembly
  _topic_map.yml
Labels: size/XS

#35337 Commenting out unused assembly
  _topic_map.yml
Labels: size/XS

#34906 BZ1664914: descheduler documentation lack of the introduction of 'nodeaffinity' strategy
  admin_guide/scheduling/descheduler.adoc
Labels: Peer Review Done, size/M, branch/enterprise-3.11

#35298 Bug 1974241, clarified infra node sizing guidance
  modules/infrastructure-node-sizing.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9

#35221 [BZ1952192]: add ovn and networking sections to IBM Z
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-configuration-parameters.adoc
  modules/nw-operator-cr.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9

#35060 BZ1858166 Clarify maxUnhealthy in machine health check
  modules/machine-health-checks-resource.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35055 BZ1986619: Changing description of vCPU metrics related to kernel arguments
  modules/virt-querying-metrics.adoc
  virt/logging_events_monitoring/virt-prometheus-queries.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.8, branch/enterprise-4.9

#35038 Recommendation around control plane sizing to handle chaotic conditions
  modules/master-node-sizing.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35353 BZ1989147: Changed lsbkk to lsblk
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#34970 BZ1694497: Wrong explanation in docs
  admin_guide/manage_nodes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-3.11

#33203 OSSMDOC-217: Initial Service Mesh deployment model documentation.
  _topic_map.yml
  modules/ossm-deploy-multi-mesh.adoc
  modules/ossm-deploy-multitenant.adoc
  modules/ossm-deploy-single-mesh.adoc
  modules/ossm-deploy-single-tenant.adoc
  service_mesh/v2x/ossm-deployment-models.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#33962 Added Evaluate security risks and process baselining
  _topic_map.yml
  modules/add-process-to-baseline.adoc
  modules/adding-comments.adoc
  modules/adding-tags.adoc
  modules/common-attributes.adoc
  modules/compliance-dashboard.adoc
  modules/create-policy-from-risk-view.adoc
  modules/filter-compliance-status.adoc
  modules/find-critical-cves-impacting-your-infrastructure.adoc
  modules/find-the-most-vulnerable-image-components.adoc
  modules/generate-compliance-reports.adoc
  modules/identify-operating-system-of-the-base-image.adoc
  modules/identify-top-risky-objects.adoc
  modules/identify-which-layer-of-the-container-image-introduces-vulnerabilities.adoc
  modules/lock-and-unlock-process-baselines.adoc
  modules/navigate-vulnerability-management-view.adoc
  modules/open-risk-view.adoc
  modules/process-discovery-event-timeline.adoc
  modules/process-discovery-tab.adoc
  modules/remove-process-from-baseline.adoc
  modules/risk-deployment-details-container-configuration.adoc
  modules/risk-deployment-details-overview.adoc
  modules/risk-deployment-details-security-context.adoc
  modules/risk-indicators-tab.adoc
  modules/risk-view-details.adoc
  modules/run-compliance-scan.adoc
  modules/top-risky-images-components.adoc
  modules/understanding-filtering-to-policy-mapping.adoc
  modules/use-process-baselines.adoc
  modules/view-compliance-status-for-cluster.adoc
  modules/view-compliance-status-for-control.adoc
  modules/view-compliance-status-for-namespaces.adoc
  modules/view-compliance-status-for-standard.adoc
  modules/view-details-only-for-fixable-cves.adoc
  modules/view-dockerfile-for-image.adoc
  modules/view-freq-violated-policies.adoc
  modules/view-process-baselines.adoc
  modules/vulnerability-management-view.adoc
  operating/evaluate-security-risks.adoc
  operating/manage-vulnerabilities.adoc
Labels: Peer Review Done, size/XL

#35315 Rel Notes doc text for 4.8.4 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8

#35278 add release note for gitops 1.2
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-2.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34517 BZ1966642: updated load balancer source range documentation
  modules/nw-create-load-balancer-service.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35368 Change to sshAuthorizedKeys path
  modules/troubleshooting-disabling-autoreboot-mco.adoc
  modules/understanding-machine-config-operator.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9

#35360 RHDEVDOCS-3090 1494416 - The logging_mux_memory_limit is different wi…
  install_config/aggregate_logging.adoc
Labels: lgtm, size/XS

#35188 BZ1980479: Removing problematic language
  post_installation_configuration/cluster-tasks.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35327 CNV-12358: Bumping HCO version to 2.6.6
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, lgtm, size/XS, CNV, branch/enterprise-4.7

#34822 OSDOCS-2354: adding information about ASH CCO support for CCO-22
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-mint.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-passthrough.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#35072 MON-1801: Document disabling Grafana in monitoring stack
  modules/monitoring-disabling-grafana.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#35390 Fix an OL formatting error in contributor guide
  contributing_to_docs/tools_and_setup.adoc
Labels: Peer Review Done, size/XS

#34584 RHDEVDOCS-2882 Tracker for Bug 1942908 - mention syslog prerequisite
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
Labels: lgtm, size/S

#35388 OSSMDOC-391: Back out #33203.
  _topic_map.yml
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35403 [enterprise-4.9] MON-1801: Document disabling Grafana in monitoring stack
  modules/monitoring-disabling-grafana.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: size/M

#35404 [enterprise-4.6] RHDEVDOCS-2882 Tracker for Bug 1942908 - mention sys…
  modules/cluster-logging-collector-legacy-fluentd.adoc
  modules/cluster-logging-collector-legacy-syslog.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
Labels: size/S

#35408 Updating to use 1.21-specific RN link
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#35402 RHDEVDOCS-2624 Improve <file-name> specifying better what's referenci…
  modules/cluster-logging-elasticsearch-exposing.adoc
Labels: size/XS

#35326 Adding quick start to glossary
  contributing_to_docs/term_glossary.adoc
Labels: Peer Review Done, size/S

#35424 Added a subsection to link to subprocessors
  modules/policy-identity-access-management.adoc
  modules/rosa-policy-identity-access-management.adoc
Labels: Peer Review Done, size/S

#35324 Updating quickstart to quick start
  modules/samples-operator-overview.adoc
  modules/templates-cli-parameters.adoc
  modules/templates-quickstart.adoc
  modules/templates-using-instant-app-quickstart.adoc
  modules/templates-waiting-for-readiness.adoc
  openshift_images/using-templates.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35136 Bump Contour v1.18.0
  modules/nw-install-config-gateway-api.adoc
  modules/nw-install-contour-operator.adoc
Labels: okd-only, size/XS, branch/enterprise-4.8, branch/enterprise-4.9

#35202 BZ1987058: updated text for CD-ROM boot source selection and added explanations for the Advanced Storage settings
  modules/virt-about-vms-and-boot-sources.adoc
  modules/virt-adding-a-boot-source-web.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.8, branch/enterprise-4.9

#35099 BZ:1973274 Added a note on maximum cluster downtime
  modules/graceful-shutdown.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35153 CNV-8578: Documenting CNV integration with Service Mesh
  _topic_map.yml
  modules/virt-adding-vm-to-service-mesh.adoc
  virt/virtual_machines/vm_networking/virt-connecting-vm-to-service-mesh.adoc
Labels: Peer Review Done, size/L, CNV, branch/enterprise-4.9

#35296 Add 4.8 release dates
  modules/life-cycle-dates.adoc
Labels: size/S

#35308 Adds 4.7.23 RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7

#35426 Added release notes for 3.64
  _topic_map.yml
  modules/common-attributes.adoc
  release_notes/364-release-notes.adoc
Labels: Peer Review Done, size/M

#35458 Update upgrade instructions for SCCs
  modules/update-openshift-security-context-constraints.adoc
Labels: Peer Review Done, size/L

#35343 Replaced some stock text and added notes for 4.6.42
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6

#35462 Update master/worker subnet CIDR examples
  modules/installation-creating-gcp-vpc.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9

#35457 BZ1883782: Removing LatencySensitive reference
  modules/nw-sriov-topology-manager.adoc
  networking/hardware_networks/add-pod.adoc
Labels: branch/enterprise-3.4, Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#35423 RHDEVDOCS-2768 Migrate Logging attributes to /modules/common-attribut…
  logging/troubleshooting/cluster-logging-must-gather.adoc
  modules/cluster-logging-document-attributes.adoc
  serverless/knative_serving/cluster-logging-serverless.adoc
Labels: size/M

#35472 RHDEVDOCS-2753 Provide an example ClusterLogging CR for forwarding only
  modules/cluster-logging-deploy-console.adoc
Labels: size/XS

#35482 GH#35450: Fix typo
  modules/install-acs-operator.adoc
Labels: size/XS

#30286 OSDOCS-1872: Added API support and compatability docs
  _topic_map.yml
  modules/api-compatibility-common-terminology.adoc
  modules/api-compatibility-exceptions.adoc
  modules/api-compatibility-guidelines.adoc
  modules/api-support-deprecation-policy.adoc
  modules/api-support-tiers.adoc
  rest_api/understanding-api-support-tiers.adoc
  rest_api/understanding-compatibility-guidelines.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.8, branch/enterprise-4.9

#34310 Fix callouts in samples of machineset
  modules/installation-osp-configuring-sr-iov.adoc
  modules/machineset-osp-adding-bare-metal.adoc
  modules/machineset-yaml-aws.adoc
  modules/machineset-yaml-azure.adoc
  modules/machineset-yaml-gcp.adoc
  modules/machineset-yaml-osp-sr-iov-port-security.adoc
  modules/machineset-yaml-osp-sr-iov.adoc
  modules/machineset-yaml-osp.adoc
  modules/machineset-yaml-vsphere.adoc
  modules/private-clusters-setting-dns-private.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#34712 BZ1967077: Updating the nodeSelector YAML for moving the registry
  modules/infrastructure-moving-registry.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9
