Repository openshift/openshift-docs, pull requests merged in 2021-07, with the labels that each got.

#34192 [enterprise-4.6] Cleanup listing blocks
  modules/adding-custom-notification-banners.adoc
  modules/builds-strategy-custom-environment-variables.adoc
  modules/builds-strategy-pipeline-environment-variables.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-kibana-limits.adoc
  modules/cluster-logging-updating-logging.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/compliance-anatomy.adoc
  modules/dedicated-admin-granting-permissions.adoc
  modules/dedicated-admin-role-overview.adoc
  modules/dedicated-aws-vpn-troubleshooting.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/dedicated-logging-in-and-verifying-permissions.adoc
  modules/dedicated-managing-service-accounts.adoc
  modules/developer-cli-odo-basic-odo-cli-commands.adoc
  modules/functions-list-kn.adoc
  modules/identity-provider-oidc-CR.adoc
  modules/infrastructure-moving-logging.adoc
  modules/jaeger-config-query.adoc
  modules/jaeger-config-storage.adoc
  modules/nodes-cluster-overcommit-buffer-chunk.adoc
  modules/nodes-cluster-resource-configure.adoc
  modules/nodes-cluster-resource-override-deploy-cli.adoc
  modules/nodes-cluster-resource-override.adoc
  modules/nodes-nodes-audit-log-basic.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-scheduler-default-priorities.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-adding.adoc
  modules/nw-enabling-multicast.adoc
  modules/nw-how-nw-iface-selected.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/ossm-configuring-kiali.adoc
  modules/ossm-cr-mixer-1x.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-jaeger-config-es-cleaner-v1x.adoc
  modules/ossm-members.adoc
  modules/persistent-storage-csi-manila-install-driver.adoc
  modules/persistent-storage-local-tolerations.adoc
  modules/rbac-viewing-cluster-roles.adoc
  modules/service-accounts-as-oauth-clients.adoc
  modules/service-accounts-overview.adoc
  modules/storage-persistent-storage-iscsi-volume-security.adoc
  modules/templates-waiting-for-readiness.adoc
  modules/updating-clear.adoc
  modules/virt-analyzing-datavolume-conditions-and-events.adoc
  modules/virt-creating-offline-vm-snapshot-cli.adoc
  modules/virt-restoring-vm-from-snapshot-cli.adoc
Labels: branch/enterprise-4.6, size/L

#34184 4.8 RNs: enhancements for 2nd L10N drop deadline
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34193 4.8 RNs: removing 4.7 RNs inclusive lang text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.8, size/XS

#33863 Added registry integration topic
  _topic_map.yml
  integration/images
  integration/integrate-with-image-registries.adoc
  integration/modules
  modules/automatic-configuration-image-registry.adoc
  modules/manual-configuration-image-registry-acr.adoc
  modules/manual-configuration-image-registry-dtr.adoc
  modules/manual-configuration-image-registry-ecr.adoc
  modules/manual-configuration-image-registry-gar.adoc
  modules/manual-configuration-image-registry-gcr.adoc
  modules/manual-configuration-image-registry-ibm.adoc
  modules/manual-configuration-image-registry-jfrog.adoc
  modules/manual-configuration-image-registry-qcr.adoc
  modules/manual-configuration-image-registry-redhat.adoc
Labels: Peer Review Done, size/L

#33677 Added Uninstall topic
  _topic_map.yml
  installing/uninstall-acs.adoc
  modules/delete-acs-global-resources.adoc
  modules/delete-acs-label-annotation.adoc
  modules/delete-acs-namespace.adoc
Labels: Peer Review Done, size/L

#34204 testing l10n links
  _javascripts/page-loader.js
  _templates/_page_openshift.html.erb
Labels: size/M

#34208 Small fixes to MTC RN
  modules/migration-mtc-release-notes-1-5.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34078 TELCODOCS-286: BIOS update for SR-IOV prereqs
  modules/cnf-programming-the-sriov-fec-operator-acc100.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#34165 OSDOCS-1977:Preparing to Install on VMC
  _topic_map.yml
  installing/installing_vmc/preparing-to-install-on-vmc.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#33359 TELCODOCS-236: 4.8 Release Notes
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/M

#34206 6894-3scaleIstioAdapterUpdates: Added updates for the procedure to configure the integration setting in 3scale
  modules/ossm-cr-example.adoc
  modules/ossm-mixer-policy-1x.adoc
  modules/ossm-mixer-policy.adoc
  modules/ossm-threescale-integrate-1x.adoc
  modules/ossm-threescale-integrate.adoc
  modules/ossm-threescale-integration-settings.adoc
  modules/ossm-threescale-manifests.adoc
  modules/ossm-threescale-templates.adoc
Labels: size/M

#34121 IPI network requirements feedback
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#34171 OSDOCS-2293: Document HAProxy tunable buffer sizes parameters
  modules/nw-ingress-controller-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34152 OSDOCS-1854: Updating control plane component list
  modules/tls-profiles-understanding.adoc
  modules/tls-profiles-view-details.adoc
  security/tls-security-profiles.adoc
Labels: Peer Review Done, branch/enterprise-4.8, lgtm, size/S

#33658 CNV-10283: CDI customizations in HCO
  modules/virt-about-cpu-and-memory-quota-namespace.adoc
  modules/virt-defining-storageclass-in-cdi.adoc
  modules/virt-defining-storageclass.adoc
  modules/virt-editing-cdi-cpu-and-memory-defaults.adoc
  modules/virt-overriding-cpu-and-memory-defaults.adoc
  modules/virt-understanding-scratch-space.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes-block.adoc
  virt/virtual_machines/importing_vms/virt-importing-virtual-machine-images-datavolumes.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-cdi-for-namespace-resourcequota.adoc
  virt/virtual_machines/virtual_disks/virt-preparing-cdi-scratch-space.adoc
  virt/virtual_machines/virtual_disks/virt-uploading-local-disk-images-block.adoc
  virt/virtual_machines/virtual_disks/virt-uploading-local-disk-images-virtctl.adoc
  virt/virtual_machines/virtual_disks/virt-uploading-local-disk-images-web.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/L

#34175 OSDOCS-1839: Add release note for configurable tune.maxrewrite and tune.bufsize for HAProxy
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34189 TELCODOCS-216: Update to release notes.
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34217 4.8 RNs: OSUS GA blurb try 2
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34130 WMCO-2.0.1 Release Notes
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, branch/enterprise-4.7, lgtm, size/M

#34213 Bug 1978057, removed mention of annotation to force reconciliation of the fileintegrity object
  modules/file-integrity-operator-changing-custom-config.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#34110 CNV-4788 Add calico information
  virt/about-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34229 [enterprise-4.6]Bug 1978057, removed mention of annotation to force reconciliation of the fileintegrity object
  modules/file-integrity-operator-changing-custom-config.adoc
Labels: size/S

#32826 OSDOCS-1846, WRKLDS-241/242: Consolidated assembly for TLS profiles
  _topic_map.yml
  modules/tls-profiles-ingress-configuring.adoc
  modules/tls-profiles-kubelet-configuring.adoc
  modules/tls-profiles-kubernetes-configuring.adoc
  modules/tls-profiles-understanding.adoc
  networking/ingress-operator.adoc
  nodes/nodes/nodes-nodes-tls.adoc
  security/tls-security-profiles.adoc
Labels: branch/enterprise-4.8, size/L

#34224 CCO-21: followup - adding links to STS content in a few key places
  installing/installing_aws/manually-creating-iam.adoc
  installing/installing_aws/preparing-to-install-on-aws.adoc
  modules/alternatives-to-storing-admin-secrets-in-kube-system.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34231 BZ1978241: Bump remaining OSDK ver for 4.8
  cli_reference/osdk/cli-osdk-install.adoc
  modules/osdk-ansible-inside-operator-local.adoc
  modules/osdk-ansible-inside-operator-logs-view.adoc
  modules/osdk-operatorconditions.adoc
  modules/osdk-scorecard-parallel.adoc
  operators/operator_sdk/osdk-about.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34232 BZ1978248: Rm fixed OSDK Golang workaround
  modules/osdk-create-project.adoc
  modules/osdk-quickstart.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34233 BZ1978250: Rm image prep from OSDK Ansible/Helm guide
  modules/osdk-prepare-supported-images.adoc
  operators/operator_sdk/ansible/osdk-ansible-tutorial.adoc
  operators/operator_sdk/helm/osdk-helm-tutorial.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34198 Rm remaining refs to package manifest format
  cli_reference/opm-cli.adoc
  modules/olm-about-catalogs.adoc
  modules/olm-accessing-images-private-registries.adoc
  modules/olm-bundle-format.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-package-manifest-format-catalogsource.adoc
  modules/olm-package-manifest-format.adoc
  modules/olm-terms.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
  operators/operator_sdk/osdk-pkgman-to-bundle.adoc
  operators/operator_sdk/osdk-working-bundle-images.adoc
  operators/understanding/olm-common-terms.adoc
  operators/understanding/olm-packaging-format.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/L

#34200 Update 4.8 RN for pkgman format removal
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34203 Add OSDK v1.8.0 notable technical change to 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34179 Adds second batch of 4.8 bug fix summaries and enhancements
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34235 TELCODOCS-204 release notes. Enabling managed Secure Boot.
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34194 Adding bug fixes for Node, MCO, Insights Op, and Cloud Compute
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#32023 CNV-9852: New content to configure a watchdog
  _topic_map.yml
  modules/virt-defining-a-watchdog.adoc
  modules/virt-installing-a-watchdog.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-a-watchdog.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/L

#34245 [enterprise-4.7]GH#30879: Adding a note about SSH keys and FIPS-enabled clusters
  modules/ssh-agent-using.adoc
Labels: size/XS

#34247 [enterprise-4.6]GH#30879: Adding a note about SSH keys and FIPS-enabled clusters
  modules/ssh-agent-using.adoc
Labels: size/XS

#34250 [enterprise-4.5]GH#30879: Adding a note about SSH keys and FIPS-enabled clusters
  modules/ssh-agent-using.adoc
Labels: size/XS

#28775 OSDOCS-1772: document dual-stack router configuration
  modules/nw-router-configuring-dual-stack.adoc
  networking/routes/route-configuration.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#33609 4.8 RNs: Add section in RNs explaining asynch add-on support status
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34249 Some minor wording adjustments
  _topic_map.yml
  modules/authentication-configmaps-use-case-consuming-in-env-vars.adoc
  modules/cnf-associating-secondary-interfaces-metrics-to-network-attachments.adoc
  modules/cnf-verifying-queue-status.adoc
  modules/infrastructure-moving-logging.adoc
  modules/jaeger-config-storage.adoc
  modules/ossm-remove-operators.adoc
  modules/tls-profiles-ingress-configuring.adoc
  modules/tls-profiles-kubelet-configuring.adoc
  modules/tls-profiles-kubernetes-configuring.adoc
  networking/ingress-operator.adoc
  security/certificate_types_descriptions/control-plane-certificates.adoc
  security/certificate_types_descriptions/service-ca-certificates.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34251 Add 4.8 RN for catalog-build & bundle-upgrade
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34147 KNIDEPLOY-2111 - Managed Baremetal Day2 reliability/error-path UX
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-diagnosing-duplicate-mac-address.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#34241 Adds third batch of 4.8 doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/S

#32485 New content for configuring cert rotation params
  _topic_map.yml
  modules/virt-configuring-certificate-rotation.adoc
  modules/virt-troubleshooting-cert-rotation-parameters.adoc
  virt/install/installing-virt-cli.adoc
  virt/virtual_machines/vm_networking/virt-configuring-certificate-rotation.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/L

#34166 BZ1973377: Add OSDK / OCP compat notices & steps
  modules/olm-about-catalogs.adoc
  modules/osdk-control-compat.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
  operators/operator_sdk/osdk-working-bundle-images.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#33107 CNV-10280: configuring obsolete CPU models in HCO
  modules/virt-about-node-labeling-cpu-features.adoc
  modules/virt-about-node-labeling-obsolete-cpu-models.adoc
  modules/virt-configuring-configmap-for-obsolete-cpu-models.adoc
  modules/virt-configuring-obsolete-cpu-models.adoc
  modules/virt-understanding-node-labeling-obsolete-cpu-models.adoc
  virt/node_maintenance/virt-managing-node-labeling-obsolete-cpu-models.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/L

#33769 [OSDOCS-2252] Update OKE vs OCP features table
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/L

#34258 Add 4.8 RN for OSDK compat section
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, size/XS

#33057 RFE-1136 BZ#1796054 Infra node improvements and updates for new workflow
  machine_management/creating-infrastructure-machinesets.adoc
  modules/binding-infra-node-workloads-using-taints-tolerations.adoc
  modules/creating-infra-machines.adoc
  modules/machineset-creating.adoc
  modules/machineset-yaml-aws.adoc
  modules/machineset-yaml-azure.adoc
  modules/machineset-yaml-gcp.adoc
  modules/machineset-yaml-osp.adoc
  modules/machineset-yaml-vsphere.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XL

#34264 [enterprise-4.5] RFE-1136 BZ#1796054 Infra node improvements and updates for new workflow
  machine_management/creating-infrastructure-machinesets.adoc
  modules/binding-infra-node-workloads-using-taints-tolerations.adoc
  modules/creating-infra-machines.adoc
  modules/machineset-creating.adoc
  modules/machineset-yaml-aws.adoc
  modules/machineset-yaml-azure.adoc
  modules/machineset-yaml-gcp.adoc
  modules/machineset-yaml-osp.adoc
  modules/machineset-yaml-vsphere.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/XL

#34265 [enterprise-4.6] RFE-1136 BZ#1796054 Infra node improvements and updates for new workflow
  machine_management/creating-infrastructure-machinesets.adoc
  modules/binding-infra-node-workloads-using-taints-tolerations.adoc
  modules/creating-infra-machines.adoc
  modules/machineset-creating.adoc
  modules/machineset-yaml-aws.adoc
  modules/machineset-yaml-azure.adoc
  modules/machineset-yaml-gcp.adoc
  modules/machineset-yaml-osp.adoc
  modules/machineset-yaml-vsphere.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/XL

#33056 BZ1962490: Machine-config-controller not generating new machineconfigs for new Kubeletconfig CR
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#34268 [enterprise-4.7] BZ1962490: Machine-config-controller not generating new machineconfigs for new Kubeletconfig CR
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/L

#34269 [enterprise-4.8] BZ1962490: Machine-config-controller not generating new machineconfigs for new Kubeletconfig CR
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/L

#32404 OCPRHV-433: Document optimal vm placement configuration options
  installing/installing-preparing.adoc
  installing/installing_rhv/installing-rhv-default.adoc
  modules/installation-configuration-parameters.adoc
  modules/installing-rhv-accessing-ocp-web-console.adoc
  modules/installing-rhv-example-install-config-yaml.adoc
  modules/installing-rhv-insecure-mode.adoc
  modules/installing-rhv-preparing-network-environment.adoc
  modules/installing-rhv-requirements.adoc
  modules/installing-rhv-setting-up-ca-certificate.adoc
  modules/installing-rhv-verifying-rhv-environment.adoc
  modules/machineset-yaml-rhv.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/L

#34271 [skip netlify] Added codeowners
  .github/CODEOWNERS
Labels: size/XS

#33809 BZ1808776: Fixed incorrect route in step 3 of the blue-green deployment procedure
  modules/deployments-blue-green.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#33966 BZ1895054: OperatorGroup CSV annotations- changed olm.operatorGroupNamespace to olm.operatorNamespace
  modules/olm-operatorgroups-csv-annotations.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#33750 BZ1875952: Fixed vague information about cpu resource limits (number of cores and GPUs)
  modules/cluster-autoscaler-cr.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#34207 Added kubevirt bugs to RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S

#34257 Adds fourth batch of 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34246 ROSA STS creation command clean ups
  modules/rosa-sts-creating-cluster.adoc
  modules/rosa-sts-creating-roles.adoc
Labels: Peer Review Needed, QE Required, size/L

#34286 4.8 RNs: TP/GA and dep/rem feature tables
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34289 Adds 5th batch of 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34293 Bugzilla #1878068: Remove outdated images
  images/serverless-create-sub.png
  images/serverless-operator.png
  modules/serverless-install-web-console.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.5, kind/bug, size/XS

#34292 Added bugs to 4.8 RN for Console Storage Plugin
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34290 Removing docs for TP feature Prometheus Adapter
  _topic_map.yml
  modules/monitoring-exposing-custom-application-metrics-for-horizontal-pod-autoscaling.adoc
  monitoring/accessing-third-party-uis.adoc
  monitoring/exposing-custom-application-metrics-for-autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34295 Rel Notes doc text for 4.8.0 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.8, size/S

#34259 4.8 RNs: bugfixes volume 1
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.8, size/M

#34307 Updating quick start references in 4.8 release notes
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34218 Specifying that disaster recovery requires a healthy node
  backup_and_restore/disaster_recovery/about-disaster-recovery.adoc
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#34322 Added Webscale private docs
  _distro_map.yml
Labels: size/XS

#34323 added and updated welcome page for webscale
  _topic_map.yml
  welcome/index.adoc
Labels: size/S

#33557 MON-1229: Use our own prometheus-example-app image
  modules/monitoring-configuring-monitoring-for-an-application.adoc
  modules/monitoring-deploying-a-sample-service.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#33852 Since version compliance-operator-0.1.35 and file-integrity-operator-0.1.16, the channel is release-0.1
  modules/compliance-operator-cli-installation.adoc
  modules/file-integrity-operator-installing-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#33718 CNV-12348: RN - Added note about new virtctl vnc sub-command
  virt/virt-4-8-release-notes.adoc
Labels: CNV, branch/enterprise-4.8, lgtm, size/XS

#34326 Added notes for release 4.7.19
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, size/S

#34309 Add OLM BZs for 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34308 Adds 7th batch of 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34335 Adds 8th batch of 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34338 modules/master-node-sizing: Fix "at least" to "at most" typo
  modules/master-node-sizing.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#34305 Adds 6th batch of 4.8 RNs bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34346 CNV-12465: creating deprecated feature module for virt
  modules/virt-deprecated-feature.adoc
  virt/virtual_machines/importing_vms/virt-importing-rhv-vm.adoc
  virt/virtual_machines/importing_vms/virt-importing-vmware-vm.adoc
Labels: CNV, branch/enterprise-4.8, size/S

#34340 Adds 9th batch of 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#33745 Release notes for Node and MCO follow up
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34350 Updating topic_map for webscale
  _topic_map.yml
Labels: size/S

#34351 [enterprise-4.8] Updating topic_map for webscale
  _topic_map.yml
Labels: size/S

#33462 BZ1923767: adding module to disable OperatorHub in restricted installs
  installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_rhv/installing-rhv-restricted-network.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-restricted-networks-vmc.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#34070 TELCODOCS-82: Preliminary ZTP
  _topic_map.yml
  modules/ztp-about-ztp-and-distributed-units-on-single-node-openshift-clusters.adoc
  modules/ztp-low-latency-for-distributed-units-dus.adoc
  modules/ztp-single-node-clusters.adoc
  modules/ztp-the-gitops-approach.adoc
  modules/ztp-ztp-building-blocks.adoc
  scalability_and_performance/cnf-provisioning-and-deploying-a-distributed-unit.adoc
  scalability_and_performance/ztp-zero-touch-provisioning.adoc
Labels: Peer Review Needed, Telco, branch/enterprise-4.8, size/L

#34357 4.8 RN: Added known issue for BZ1977184
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/XS

#34362 BZ1924568 Added known issue to 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/XS

#34222 CNV-10989: updating version attributes for OpenShift Virtualization 4.8
  modules/virt-document-attributes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34369 Added technology preview feature statuses for 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/XS

#33927 TELCODOCS-157: workload partitioning
  modules/cnf-deploying-the-du-infrastructure-profile.adoc
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-configuring-workload-partitioning.adoc
  modules/cnf-du-creating-a-machine-config-manifest-for-workload-partitioning.adoc
  modules/cnf-du-crio-configuration-for-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/cnf-du-partitioning-management-workloads.adoc
  modules/cnf-du-required-annotations-for-workload-partitioning.adoc
  modules/cnf-du-workload-partitioning-pod-mutation.adoc
  scalability_and_performance/cnf-provisioning-and-deploying-a-distributed-unit.adoc
Labels: Peer Review Done, Telco, branch/enterprise-4.8, size/XL

#34349 Adds RN batch to 4.8
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34372 CNV-12677: changing about-virt to placeholder
  virt/about-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/S

#34285 BZ1976232: Added known issue to 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34291 BZ1978250: Rm img prep from Golang tutorial
  modules/osdk-prepare-supported-images.adoc
  operators/operator_sdk/golang/osdk-golang-tutorial.adoc
Labels: Peer Review Done, branch/enterprise-4.8, lgtm, size/M

#33590 Release note: CDI uses OCP cluster-wide proxy config
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, lgtm, size/XS

#34379 Release notes for 3.11.465
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/M

#34383 [enterprise-4.7] BZ1923767: adding module to disable OperatorHub in restricted installs
  installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_rhv/installing-rhv-restricted-network.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-restricted-networks-vmc.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: size/M

#34384 [enterprise-4.6] BZ1923767: adding module to disable OperatorHub in restricted installs
  installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-restricted-networks-vmc.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
Labels: size/M

#32785 [WIP] Telcodocs 85: Validate and Document Intel SRO and SRIOV FEC Operator
  _topic_map.yml
  modules/cnf-installing-sriov-fec-operator.adoc
  modules/cnf-installing-the-n3000-operator.adoc
  modules/cnf-intel-n3000-optimize-data-plane.adoc
  modules/cnf-programming-the-n3000-operator.adoc
  modules/cnf-programming-the-sriov-fec-operator-acc100.adoc
  modules/cnf-programming-the-sriov-operator.adoc
  modules/cnf-verify-sriov-operator-n3000.adoc
  scalability_and_performance/cnf-optimize-data-performance-n3000.adoc
Labels: Peer Review Done, branch/enterprise-4.6, do-not-merge/work-in-progress, size/XXL

#34386 Adds 4.8 RN bug doc text
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34306 [Enterprise-4.8]: Updated links to latest OpenShift version
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  modules/update-upgrading-web.adoc
Labels: branch/enterprise-4.8, size/XS

#34297 CNV-12271: Adding new tech preview feature RN
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#33662 Added upgrade docs
  _topic_map.yml
  modules/back-up-central-database.adoc
  modules/revoke-the-api-token.adoc
  modules/rollback-central-forced.adoc
  modules/rollback-central-normal.adoc
  modules/roxctl-generate-init-bundle.adoc
  modules/search-attributes.adoc
  modules/update-admission-controller.adoc
  modules/update-openshift-security-context-constraints.adoc
  modules/update-other-images.adoc
  modules/updating-helm-repository.adoc
  modules/upgrade-central.adoc
  modules/upgrade-scanner.adoc
  modules/verify-central-cluster-upgrade.adoc
  modules/verify-last-check-in-time.adoc
  modules/verify-secured-cluster-upgrade.adoc
  upgrading/images
  upgrading/modules
  upgrading/upgrade-helm.adoc
  upgrading/upgrading_roxctl/images
  upgrading/upgrading_roxctl/modules
  upgrading/upgrading_roxctl/upgrade-from-44.adoc
Labels: Peer Review Done, size/XL

#34234 CNV-12268: Adding new storage feature to RN
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#33867 Added managing compliance topic
  _topic_map.yml
  modules/compliance-dashboard.adoc
  modules/compliance-evidence-reports.adoc
  modules/filter-compliance-status.adoc
  modules/generate-compliance-reports.adoc
  modules/run-compliance-scan.adoc
  modules/supported-benchmark-versions.adoc
  modules/view-compliance-status-for-cluster.adoc
  modules/view-compliance-status-for-control.adoc
  modules/view-compliance-status-for-namespaces.adoc
  modules/view-compliance-status-for-standard.adoc
  operating/manage-compliance.adoc
Labels: Peer Review Done, size/L

#34014 Added monitoring topic
  _topic_map.yml
  configuration/monitor-acs.adoc
  modules/enable-monitoring-customize-port.adoc
  modules/enable-monitoring.adoc
Labels: Peer Review Done, size/M

#33875 TELCODOCS-237: updating version number 4.7 to 4.8
  modules/cnf-configure_for_irq_dynamic_load_balancing.adoc
  modules/cnf-installing-the-performance-addon-operator.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  modules/cnf-upgrading-performance-addon-operator.adoc
Labels: branch/enterprise-4.8, size/M

#34223 CNV-12628: updating repo names for virt 4.8
  modules/virt-enabling-virt-repos.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, lgtm, size/XS

#33963 Added release notes
  _topic_map.yml
  configuration/enable-offline-mode.adoc
  configuration/reissue-internal-certificates.adoc
  modules/common-attributes.adoc
  modules/configure-alert-data-retention.adoc
  modules/download-kernel-support-package.adoc
  release_notes/3056-release-notes.adoc
  release_notes/3057-release-notes.adoc
  release_notes/3058-release-notes.adoc
  release_notes/3059-release-notes.adoc
  release_notes/3060-release-notes.adoc
  release_notes/3061-release-notes.adoc
  release_notes/3062-release-notes.adoc
  release_notes/images
  release_notes/modules
Labels: Peer Review Done, size/XL

#34395 Fixes minor nits in 4.8 RNs
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34300 CNV-11965: for defect 1959287 CPU vendors
  virt/install/preparing-cluster-for-virt.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34399 OSDOS-1890: Updated two Azure links in the contribution doc.
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34392 [enterprise-4.7] IPI network requirements feedback
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: size/L

#33956 Added online telemetry topic
  _topic_map.yml
  configuration/online-telemetry.adoc
  modules/disable-online-telemetry-new-install.adoc
  modules/enable-disable-online-telemetry-existing.adoc
  modules/inspect-online-telemetry-data.adoc
  modules/online-telemetry-collected-data.adoc
Labels: Peer Review Done, size/L

#34415 Telcodocs 85 update: Fixing a minor grammar error in original PR 32785
  modules/cnf-verify-sriov-operator-n3000.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/XS

#33676 Added Managing role-based access control topic
  _topic_map.yml
  api-config.yaml
  modules/configure-minimum-access-role.adoc
  modules/create-a-custom-role.adoc
  modules/delete-a-custom-role.adoc
  modules/manage-access-for-specific-users-or-groups.adoc
  modules/modify-a-custom-role.adoc
  modules/rbac-custom-roles.adoc
  modules/rbac-resource-definitions.adoc
  modules/rbac-system-roles.adoc
  modules/view-system-roles.adoc
  operating/manage-user-access/manage-role-based-access-control.adoc
Labels: Peer Review Done, size/L

#34353 BZ1979803: Importing RHV VM fails if migratable
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, Peer Review Needed, branch/enterprise-4.8, qe-approved, size/XS

#34396 Add 4.8 RN known issue for BZ#1967369
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/M

#34359 Changed Service Binding to TP in 4.7
  release_notes/ocp-4-7-release-notes.adoc
Labels: size/XS

#34390 BZ1977658: Adding known issue related to No registered model warning message appearing in the VM creation wizard
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34287 CNV 12272: Adding 4.8 release note for cloning between data volume modes
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34417 Cleanup work for 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/L

#34348 Updates to OSDK / OCP compat guidance
  modules/osdk-control-compat.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34423 Minor cleanup to 4.8 RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/S

#34236 CNV-12270: Adding new storage feature to RN
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34302 CNV-12542: Adding new feature for Storage RN
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/XS

#34416 [RHDEVDOCS-3027] ODC Release Notes, Known Issues, and Bug Fixes for 4.7.z
  release_notes/ocp-4-7-release-notes.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.7, lgtm, size/XS

#34411 [RHDEVDOCS-3027] ODC Release Notes, Known Issues, and Bug Fixes for 4.8
  release_notes/ocp-4-8-release-notes.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.8, size/L

#34370 WMCO-2.0.2: Added a release note to the WMCO 2.0.2 release
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/M

#34429 Fixes a small grammatical error in the 4.8 RNs
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34382 Typo fixes for IPfailover
  modules/nw-ipfailover-configuration.adoc
  modules/nw-ipfailover-configuring-check-notify-scripts.adoc
  modules/nw-ipfailover-environment-variables.adoc
Labels: Peer Review Done, branch/enterprise-4.8, size/XS

#34436 remove Builds RN commit
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/L

#34433 WMCO-3.0: Hide WMCO from the general 4.8 release notes
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/XS

#34441 Rishu's RN 4.8 updates
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/S

#33147 Telcodocs 85 RN: 4.6 Release Notes description for Intel N3000 and ACC100 cards
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#33356 CNF-620: RN 47 Documenting support for the OpenNESS SR-IOV Operator for Wireless FEC Accelerators and ACC100 card
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/S

#34401 BZ#1974403: Upgrade workaround for OVN-K
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, branch/enterprise-4.8, lgtm, size/XS

#33835 OSDOCS-2271: Changed docs.openshift URLs to Customer Portal URLs
  monitoring/osd-understanding-the-monitoring-stack.adoc
Labels: size/XS

#33864 Added viewing dashboard topic
  _topic_map.yml
  operating/view-dashboard.adoc
Labels: Peer Review Done, size/M

#34031 Added audit log topic
  _topic_map.yml
  configuration/configure-audit-logging.adoc
  modules/enable-audit-log.adoc
  modules/sample-audit-log-message.adoc
Labels: Peer Review Done, size/L

#34021 Added integrating with CI topic
  _topic_map.yml
  integration/integrate-with-ci-systems.adoc
  modules/check-for-existing-registry-integration.adoc
  modules/create-new-system-policy.adoc
  modules/integrate-ci-check-existing-build-phase-policies.adoc
  modules/integrate-circle-ci.adoc
Labels: Peer Review Done, size/L

#34123 OSDOCS-1627: Adding architecture information
  _topic_map.yml
  images/156_OpenShift_ROSA_Arch_0621_arch.png
  images/156_OpenShift_ROSA_Arch_0621_arch.svg
  modules/osd-aws-privatelink-architecture.adoc
  modules/rosa-architecture.adoc
  rosa_architecture/images
  rosa_architecture/rosa-architecture-models.adoc
  rosa_getting_started/osd-aws-privatelink-creating-cluster.adoc
Labels: Peer Review Done, size/M

#34074 Added Responding to violations topic
  _topic_map.yml
  modules/violation-view-enforcement-tab.adoc
  modules/violation-view-policy-tab.adoc
  modules/violation-view-violation-tab.adoc
  modules/violations-view-deployment-tab.adoc
  modules/violations-view.adoc
  operating/respond-to-violations.adoc
Labels: Peer Review Done, size/L

#34073 Added roxctl quick install topic
  _topic_map.yml
  installing/install-quick-roxctl.adoc
  modules/install-central-roxctl.adoc
  modules/install-scanner-roxctl.adoc
  modules/install-sensor-roxctl.adoc
  modules/using-the-interactive-installer.adoc
Labels: Peer Review Done, size/L

#34467 Remove empty lines from additional resources sections
  configuration/enable-offline-mode.adoc
  configuration/online-telemetry.adoc
  installing/install-quick-roxctl.adoc
  installing/installing_helm/install-helm-quick.adoc
  modules/roxctl-generate-init-bundle.adoc
  upgrading/upgrade-helm.adoc
Labels: Peer Review Done, size/XS

#34375 BZ1974689: CNV VM import UI error message
  virt/virt-4-8-release-notes.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.8, size/S
