Repository openshift/openshift-docs, pull requests merged in 2021-03, with the labels that each got.

#29429 BZ#1916578 - Fix ingress controller headers policy
  modules/nw-using-ingress-forwarded.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#29472 update link to deployment resources
  nodes/clusters/nodes-cluster-overcommit.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29882 Adds 4.6.19 RNs
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/S

#29925 [SRVCOM-1190] 1.13.0 release notes
  modules/serverless-rn-1-13-0.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.7, size/M

#29682 Add egress-router-cni to the docs (OSDOCS-979)
  modules/nw-ovn-kubernetes-matrix.adoc
Labels: branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29915 GH#29862 - Fix typo
  security/compliance_operator/compliance-operator-troubleshooting.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29500 [SRVLS][SRVKS-681] Domain mapping for ksvcs
  _topic_map.yml
  modules/serverless-create-domain-mapping.adoc
  serverless/networking/serverless-domain-mapping.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.6, branch/enterprise-4.7, size/M

#29914 GH#29443 - Fix typo
  modules/nodes-scheduler-pod-affinity-configuring.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29908 GH#29481 - Fix typos
  nodes/jobs/nodes-pods-daemonsets.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29948 Updated auto table numbering
  modules/virt-features-for-storage-matrix.adoc
  modules/virt-live-migration-limits-reftable.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#29598 GH#29109 - Fix typo
  modules/deployments-ab-testing-lb.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#28953 BZ#1907505 - Fix ExternalIP assignment
  modules/nw-externalip-about.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#28666 BZ#1890607 - Add OpenShift SDN egress IP sharing limitation
  modules/nw-egress-ips-about.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29967 Update mtc version (1.4.1)
  modules/common-attributes.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8

#29262 OSDOCS-1477 Monitoring capabilities for WINC
  modules/installing-wmco-using-cli.adoc
  modules/installing-wmco-using-web-console.adoc
  modules/windows-workload-management.adoc
  modules/wmco-upgrades.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#28832 OSDOCS-1766 WINC vSphere support
  _topic_map.yml
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/enabling-internal-api-server-vsphere.adoc
  modules/machine-api-overview.adoc
  modules/machineset-creating.adoc
  modules/windows-machineset-vsphere.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.adoc
  windows_containers/understanding-windows-container-workloads.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#29848 Rns 4.5.33
  release_notes/ocp-4-5-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, size/M

#29937 Changed to in Update Channels section of upgrade docs
  modules/understanding-upgrade-channels.adoc
Labels: size/XS

#29674 removing XREFs from modules
  modules/ossm-rn-technology-preview.adoc
  modules/ossm-threescale-integrate.adoc
  modules/threescale-backend-cache.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
  service_mesh/v2x/threescale-adapter.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29902 BZ#1909152: Add refreshing Operator sub t'shooting
  modules/olm-refresh-subs.adoc
  operators/admin/olm-deleting-operators-from-cluster.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/L

#29829 Manual cherrypick of PR#29409 RHDEVDOCS-2608 The name of the indices …
  modules/cluster-logging-updating-logging.adoc
Labels: size/S

#29310 RHDEVDOCS-2550 & RHDEVDOCS-2608
  modules/cluster-logging-elasticsearch-retention.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/M

#29931 BZ1933244 - update to machineconfig example
  modules/installation-complete-user-infra.adoc
Labels: Multi-Arch, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29378 RHDEVDOCS-2603
  modules/cluster-logging-collector-legacy-fluentd.adoc
Labels: Peer Review Done, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#29399 RHDEVDOCS-2605 Add an example for sending to several Kafka brokers using only one output entry
  modules/cluster-logging-collector-log-forward-kafka.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#29339 Remove misleading lines in builds-create-custom-build-artifacts
  modules/builds-create-custom-build-artifacts.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29994 [enterprise-4.6]RHDEVDOCS-2608
  modules/cluster-logging-updating-logging.adoc
Labels: size/XS

#29998 RHDEVDOCS-2602 In secure forward the self_hostname the definition and…
  _unused_topics/cluster-logging-elasticsearch-admin.adoc
Labels: Peer Review Done, size/S

#29430 GH#29370 - Fix typo
  modules/nodes-scheduler-default-creating.adoc
  modules/nodes-scheduler-default-priorities.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30012 BZ#1932032 Typo fixes
  modules/builds-source-secret-combinations-basic-auth-ca.adoc
  modules/builds-source-secret-combinations-basic-auth-gitconfig-ca.adoc
  modules/builds-source-secret-combinations-basic-auth-gitconfig.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30013 Manual CP of RHDEVDOCS-2617 #29491
  modules/cluster-logging-deploy-storage-considerations.adoc
Labels: size/S

#30016 Manual CP of RHDEVDOCS-2617 #29491
  modules/cluster-logging-deploy-storage-considerations.adoc
Labels: size/S

#30018 Manual CP of RHDEVDOCS-2617 #29491
  modules/cluster-logging-deploy-storage-considerations.adoc
Labels: size/S

#29886 BZ1850965: removed wildcard domain name statement
  modules/images-configuration-parameters.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29539 CNV-BZ-1918467 Added note to install doc about RHCOS support
  virt/install/preparing-cluster-for-virt.adoc
Labels: CNV, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#29807 Add Known Issue for Ingress Canary route edge termination
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#29475 Remove finalizers on CSI snapshot objects
  modules/persistent-storage-csi-snapshots-delete.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#29907 GH#29486 - Fix typo
  modules/nodes-nodes-managing-about.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30006 Adjusted column width proportions
  modules/virt-live-migration-limits-reftable.adoc
Labels: CNV, Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#30030 Add missing wipeVolume to MachineConfig luks sections
  modules/installation-special-config-encrypt-disk-tang.adoc
  modules/installation-special-config-encrypt-disk-tpm2.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29234 GH#28550 - Fix oc command
  modules/cluster-logging-updating-logging.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#30050 [skip netlify] updated index-commercial
  index-commercial.html
Labels: size/M

#29269 ocprhv-66 RHV - CSI driver provisioning [enterprise-4.7]
  modules/ovirt-csi-driver-storage-class.adoc
  modules/persistent-storage-rhv.adoc
  storage/container_storage_interface/persistent-storage-csi-ovirt.adoc
Labels: branch/enterprise-4.7, branch/enterprise-4.8, size/L

#29687 Notes for pipeline run and task failures in side panel and PLR details page
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-starting-pipelines.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30005 Removing note that is no longer applicable
  modules/bound-sa-tokens-about.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29988 BZ1851320 - Updated metadata file extension
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30063 [enterprise-4.5] BZ1851320 - updated metadata file extension
  modules/installation-osp-creating-bootstrap-machine.adoc
  modules/installation-osp-creating-compute-machines.adoc
Labels: branch/enterprise-4.5, size/XS

#29873 BZ#1838164: prereqs for multiple interfaces
  install/prerequisites.adoc
Labels: Peer Review Done, branch/enterprise-3.11, size/XS

#29835 URGENT - BZ1930469 and BZ1918456
  release_notes/ocp-4-7-release-notes.adoc
Labels: Telco, branch/enterprise-4.7, size/S

#29952 Errata update for 3.11.394 release
  install/disconnected_install.adoc
  install_config/aggregate_logging.adoc
  release_notes/ocp_3_11_release_notes.adoc
  upgrading/automated_upgrades.adoc
Labels: branch/enterprise-3.11, size/L

#30038 RHDEVDOCS-2734 Logging: CP topic_map, RNs, attributes, and related to…
  _topic_map.yml
  logging/cluster-logging-release-notes.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-document-attributes.adoc
Labels: size/L

#30041 RHDEVDOCS-2734 Logging: CP topic_map, RNs, attributes, and related to…
  _topic_map.yml
  logging/cluster-logging-release-notes.adoc
  logging/cluster-logging.adoc
  modules/cluster-logging-document-attributes.adoc
Labels: size/L

#30048 Silence warning about duplicate callout
  modules/cluster-logging-deploy-console.adoc
Labels: Peer Review Needed, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30069 GitHub-28639: Adding slash
  modules/nw-dns-forward.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30047 Remove prompt with hostname
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29750 OSDOCS-1786: Adding a link to common parameters to all IDP assemblies
  authentication/identity_providers/configuring-basic-authentication-identity-provider.adoc
  authentication/identity_providers/configuring-github-identity-provider.adoc
  authentication/identity_providers/configuring-gitlab-identity-provider.adoc
  authentication/identity_providers/configuring-google-identity-provider.adoc
  authentication/identity_providers/configuring-htpasswd-identity-provider.adoc
  authentication/identity_providers/configuring-keystone-identity-provider.adoc
  authentication/identity_providers/configuring-ldap-identity-provider.adoc
  authentication/identity_providers/configuring-oidc-identity-provider.adoc
  authentication/identity_providers/configuring-request-header-identity-provider.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30067 [enterprise-4.6] Notes for pipeline run and task failures in side panel and PLR details page
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-starting-pipelines.adoc
Labels: size/M

#30042 Fix subsequent paras for same callout
  _stylesheets/docs.css
Labels: Peer Review Needed, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29833 MIG-549: MigHook doc improvement
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-about-migration-hooks.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-mtc-cr-manifests.adoc
  modules/migration-prerequisites.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-internal-images.adoc
  modules/migration-writing-ansible-playbook-hook.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30099 migration hooks 4.5
  migration/migrating_3_4/migrating-application-workloads-3-4.adoc
  migration/migrating_3_4/migrating-applications-with-cam-3-4.adoc
  migration/migrating_3_4/troubleshooting-3-4.adoc
  migration/migrating_4_1_4/migrating-application-workloads-4-1-4.adoc
  migration/migrating_4_1_4/migrating-applications-with-cam-4-1-4.adoc
  migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
  migration/migrating_4_2_4/migrating-application-workloads-4-2-4.adoc
  migration/migrating_4_2_4/migrating-applications-with-cam-4-2-4.adoc
  migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
  modules/migration-about-migration-hooks.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-mtc-cr-manifests.adoc
  modules/migration-mtc-custom-resources.adoc
  modules/migration-mtc-workflow.adoc
  modules/migration-prerequisites.adoc
  modules/migration-understanding-migration-hooks.adoc
  modules/migration-updating-internal-images.adoc
  modules/migration-writing-ansible-playbook-hook.adoc
Labels: size/XL

#29492 Add module on odo storage.
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/working-with-storage.adoc
  modules/developer-cli-odo-basic-odo-cli-commands.adoc
  modules/developer-cli-odo-switching-between-ephemeral-and-persistent-storage.adoc
Labels: Dev Tools, Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#29978 [srvls] add 1.10.1 CVE fix release notes
  modules/serverless-rn-1-10-1.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.5, size/S

#29102 Highlight relantionship between defaultNodeSelector and pod's nodeSelector
  modules/nodes-scheduler-node-selectors-pod.adoc
  nodes/scheduling/nodes-scheduler-default.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29354 OSDOCS-1532: Adding docs for filtering audit logs
  modules/security-audit-log-filtering.adoc
  security/audit-log-view.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/M

#30077 BZ-1920414: Clarifying the revision numbers are examples
  modules/dr-restoring-cluster-state.adoc
  modules/nodes-nodes-audit-policy.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#30112 BZ-1920414: Clarifying the revision numbers are examples
  modules/dr-restoring-cluster-state.adoc
Labels: size/S

#30116 ISSUE-27701 - Minor edit for emphasis
  modules/storage-multi-attach-error.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30120 Manually CP RHDEVDOCS-2697 #29671 to 4.8
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: Peer Review Done, size/M

#30122 Manually CP RHDEVDOCS-2697 #29671 to 4.7
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: Peer Review Done, size/M

#30124 Manually CP RHDEVDOCS-2697 #29671 to 4.6
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forwarding-about.adoc
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: Peer Review Done, size/M

#30125 Minor fix for clarity after PR25072
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/XS

#30132 Add \ to multi-line pruning cmd
  modules/olm-pruning-index-image.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29093 For global proxy `noProxy` can be ignored
  modules/nw-proxy-configure-object.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#30086 BZ1867205: clarification
  modules/nw-dns-forward.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30117 RHDEVDOCS-2744 fix minor link text
  logging/config/cluster-logging-storage-considerations.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29867 Missing note that HPA feature is in Tech preview for 3.11
  dev_guide/pod_autoscaling.adoc
  release_notes/ocp_3_11_release_notes.adoc
Labels: branch/enterprise-3.11, lgtm, size/S

#30113 vSphere provides IPI network customization docs
  installing/installing-preparing.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30155 [enterprise-4.6] vSphere provides IPI network customization docs
  installing/install_config/installation-types.adoc
Labels: branch/enterprise-4.6, size/XS

#30157 [enterprise-4.5] vSphere provides IPI network customization docs
  installing/install_config/installation-types.adoc
Labels: branch/enterprise-4.5, size/XS

#29587 Added note and removed arguments
  modules/installation-user-infra-machines-pxe.adoc
  modules/machine-user-infra-machines-pxe.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#29621 [srvls] [SRVKS-693] Route docs for serverless
  _topic_map.yml
  modules/serverless-openshift-routes.adoc
  serverless/networking/serverless-configuring-routes.adoc
  serverless/networking/serverless-domain-mapping.adoc
Labels: Peer Review Done, Serverless, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30169 47RN
  release_notes/ocp-4-7-release-notes.adoc
Labels: size/XS

#29679 [enterprise-4.5]Fix URLs in the cluster logging templates
  modules/cluster-logging-collector-log-forward-about.adoc
  modules/cluster-logging-collector-log-forward-configure.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
Labels: Peer Review Done, size/XS

#30173 migrating from managed docs repo PR#26
  .travis.yml
  _distro_map.yml
  logging/dedicated-cluster-deploying.adoc
  modules/dedicated-cluster-logging-deploy-cli.adoc
  modules/dedicated-cluster-logging-deploy-console.adoc
  modules/dedicated-cluster-logging-deploy-multitenant.adoc
Labels: size/XL

#30011 BZ1850429 Added proxy instructions to the installation section
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30182 update _distro_map
  _distro_map.yml
Labels: size/S

#29637 Fix typo in the cluster logging templates
  modules/cluster-logging-elasticsearch-audit.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#30172 BZ1933188: DVM does not work with source cluster proxy (MTC 1.4.0)
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-migrating-applications-api.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, qe-approved, size/S

#30189 mtc-proxy-4-5
  modules/migration-adding-cluster-to-cam.adoc
  modules/migration-creating-migration-plan-cam.adoc
  modules/migration-migrating-applications-api.adoc
Labels: size/M

#30171 BZ1913075: Improve the wording of exposed image registry route in UI (1.4.2)
  modules/migration-adding-cluster-to-cam.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, qe-approved, size/S

#30170 Rhdevdocs 2752
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30199 GitHub-30095: Fixing formatting error
  modules/differences-between-machinesets-and-machineconfigpool.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#29668 OSDOCS-1818 for MON-1520 Resource usage of PVC backed Prometheus during upgrades
  monitoring/configuring-the-monitoring-stack.adoc
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster.adoc
  updating/updating-restricted-network-cluster.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30210 Manual CP of Rhdevdocs 2752 #30170 to enterprise-4.5
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-logstore-limits.adoc
Labels: branch/enterprise-4.5, size/M

#30209 GitHub-26850: Removing duplicate paragraphs
  modules/nodes-cluster-overcommit-configure-nodes.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#23317 add --reserved-cpus kubelet command option
  _topic_map.yml
  modules/nodes-nodes-resources-configuring-about.adoc
  modules/nodes-nodes-resources-cpus-reserve.adoc
  nodes/nodes/nodes-nodes-resources-cpus.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30224 typo
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
Labels: size/XS

#30233 [skip netlify] undo merge
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
Labels: size/XS

#30239 [skip netlify] another test
  mod_docs_guide/mod-docs-conventions-ocp.adoc
Labels: size/XS

#30245 [skip netlify] test merge
  mod_docs_guide/mod-docs-conventions-ocp.adoc
Labels: size/XS

#30251 [skip netlify] update test
  mod_docs_guide/getting-started-modular-docs-ocp.adoc
Labels: size/XS

#30223 RHDEVDOCS-2765 Fix product name in enterprise-4.7 release notes
  logging/cluster-logging-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/XS

#30211 GitHub-27639: Switching blue and green references
  applications/deployments/route-based-deployment-strategies.adoc
  modules/deployments-blue-green.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#30156 RNs 4.7.1
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.7, size/S

#30271 [enterprise-4.5] Provide clarity that UPI docs are example only
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
Labels: branch/enterprise-4.5, size/M

#30079 adding alternate codeblock annotations
  contributing_to_docs/doc_guidelines.adoc
Labels: size/S

#30076 updating guidelines for emphasis
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#30280 Manual CP of RHDEVDOCS-2583 to 4.6
  logging/cluster-logging-uninstall.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-logging-uninstall.adoc
  modules/virt-importing-vm-cli.adoc
Labels: branch/enterprise-4.6, size/S

#29818 BZ1879833: backporting cred rotation to 4.6.z
  installing/installing_aws/manually-creating-iam.adoc
  installing/installing_azure/manually-creating-iam-azure.adoc
  installing/installing_gcp/manually-creating-iam-gcp.adoc
  modules/alternatives-to-storing-admin-secrets-in-kube-system.adoc
  modules/manually-removing-cloud-creds.adoc
  modules/manually-rotating-cloud-creds.adoc
  post_installation_configuration/cluster-tasks.adoc
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, branch/enterprise-4.6, size/L

#29972 Update mtc version 1.4.2 (Mar 10)
  modules/common-attributes.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8

#29716 CNV - 2.6 release - returning about-virt assembly
  virt/about-virt.adoc
Labels: CNV, size/S

#29717 CNV - Removing the virt* redirects for 2.6 release
  .s2i/httpd-cfg/01-commercial.conf
Labels: CNV, size/XS

#30272 BZ1852900 Added a GCP link to proc
  modules/installation-gcp-install-cli.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30068 OSSMDOC-234
  modules/ossm-rn-technology-preview.adoc
  modules/ossm-supported-configurations.adoc
Labels: Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#30121 Improvements to admonition blocks
  _stylesheets/docs.css
Labels: branch/enterprise-4.1, branch/enterprise-4.2, branch/enterprise-4.3, branch/enterprise-4.4, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30143 Added ODC Web Console Bug Fixes
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/XS

#28692 Eliminate unclear descriptions on the 'Setting Deployment Resources' section follow up
  dev_guide/deployments/basic_deployment_operations.adoc
Labels: branch/enterprise-3.11, size/M

#29459 Page not found following "Learn more about OpenShift update channels"
  modules/understanding-upgrade-channels.adoc
  modules/update-upgrading-web.adoc
Labels: size/M

#29496 Bug 1888925, removed statement about custom CSS
  modules/templates-writing-description.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/L

#29625 adding missing components allowed for infrastructure nodes
  modules/infrastructure-components.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30330 [enterprise-4.5] Change [CAUTION] admonitions to supported types
  modules/installation-osp-creating-image-restricted.adoc
Labels: size/XS

#30281 ossmdoc-277 and ossmdoc-262
  modules/ossm-cr-istio-global-1x.adoc
  modules/ossm-cr-istio-global.adoc
  modules/ossm-cr-mixer-1x.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-document-attributes-1x.adoc
  modules/ossm-document-attributes.adoc
Labels: Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/S

#30332 [enterprise-4.5]adding missing components allowed for infrastructure nodes
  modules/infrastructure-components.adoc
Labels: branch/enterprise-4.5

#30326 ossmdoc-277 and ossmdoc-262 for 4.5
  modules/ossm-cr-istio-global.adoc
  modules/ossm-cr-mixer-1x.adoc
  modules/ossm-cr-mixer.adoc
  modules/ossm-document-attributes-1x.adoc
Labels: Service Mesh, branch/enterprise-4.5, size/S

#30131 OSSMDOC-203
  modules/ossm-security-mtls-1x.adoc
  modules/ossm-security-mtls.adoc
Labels: Peer Review Done, Service Mesh, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30222 Errata update for 4.5.34 release
  release_notes/ocp-4-5-release-notes.adoc
Labels: branch/enterprise-4.5, size/S

#30342 updating with rosa/dedicated to no version
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
Labels: size/S

#30197 BZ-1931838: Removing the ALL option and additional clarification
  modules/security-context-constraints-about.adoc
  modules/security-context-constraints-creating.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30221 Change 'node selector` to 'label' and fix secret name in example
  modules/nodes-pods-secrets-certificates-creating.adoc
  modules/nodes-scheduler-node-selectors-cluster.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nodes-scheduler-node-selectors-project.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/M

#30365 Adding titles and content missing from the migration to the new repo.
  _topic_map.yml
  cloud_infrastructure_access/rosa-private-cluster.adoc
  cloud_infrastructure_access/rosa-understanding-aws.adoc
  logging/rosa-install-logging.adoc
  logging/rosa-viewing-logs.adoc
  modules/config-idp.adoc
  modules/dedicated-aws-dc-existing.adoc
  modules/dedicated-aws-dc-hvif.adoc
  modules/dedicated-aws-dc-methods.adoc
  modules/dedicated-aws-vpc-accepting-peering.adoc
  modules/dedicated-aws-vpc-configuring-routing-tables.adoc
  modules/dedicated-aws-vpc-initiating-peering.adoc
  modules/dedicated-aws-vpc-peering-terms.adoc
  modules/dedicated-aws-vpn-creating.adoc
  modules/enable-gcp-private.adoc
  modules/osd-rhoam.adoc
  modules/rosa-adding-instance-types.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-enable-private-cluster-existing.adoc
  modules/rosa-enable-private-cluster-new.adoc
  modules/rosa-getting-support.adoc
  modules/rosa-install-logging-addon.adoc
  modules/rosa-scaling-worker-nodes.adoc
  modules/rosa-view-cloudwatch-logs.adoc
  nodes/nodes/rosa-autoscale-nodes.adoc
  nodes/nodes/rosa-managing-worker-nodes.adoc
  rosa_architecture/rosa-basic-architecture-concepts.adoc
  rosa_architecture/rosa-understanding.adoc
  rosa_cli/rosa-get-started-cli.adoc
  rosa_cli/rosa-manage-objects-cli.adoc
  rosa_cli/rosa-troubleshoot-cli.adoc
  rosa_getting_started/rosa-accessing-cluster.adoc
  rosa_getting_started/rosa-aws-prereqs.adoc
  rosa_getting_started/rosa-config-identity-providers.adoc
  rosa_getting_started/rosa-creating-cluster.adoc
  rosa_getting_started/rosa-deleting-access-cluster.adoc
  rosa_getting_started/rosa-deleting-cluster.adoc
  rosa_getting_started/rosa-faq.adoc
  rosa_getting_started/rosa-quickstart.adoc
  rosa_getting_started/rosa-required-aws-service-quotas.adoc
  rosa_getting_started/rosa-setting-up-environment.adoc
  rosa_policy/images
  rosa_policy/modules
  rosa_policy/rosa-policy-process-security.adoc
  rosa_policy/rosa-policy-responsibility-matrix.adoc
  rosa_policy/rosa-policy-understand-availability.adoc
  rosa_policy/rosa-service-definition.adoc
  rosa_support/rosa-getting-support.adoc
  rosa_understanding/rosa-basic-concepts.adoc
  rosa_understanding/rosa-understanding.adoc
  rosa_upgrading/rosa-upgrading.adoc
Labels: size/XL

#30358 Fixed a typo in a comment in `build_for_portal.py`
  build_for_portal.py
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30359 Fix incorrect use of taint, should be toleration
  modules/nodes-scheduler-taints-tolerations-about.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#30356 Need to correct example from my-config to my-username
  modules/nodes-containers-projected-volumes-about.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#30369 Issue#30180 replace X with Yes
  welcome/oce_about.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#29499 Improve docs about vmotion
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/S

#30284 Bz1825256: added xref to a cross-namespace image access module
  registry/accessing-the-registry.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30274 [srvls] Updates to serverless docs for OCP guidelines
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  modules/deleting-pingsource-kn.adoc
  modules/deleting-pingsource-yaml.adoc
  modules/odc-creating-apiserversource.adoc
  modules/odc-deleting-apiserversource.adoc
  modules/serverless-list-source-types-kn.adoc
  modules/serverless-list-source-types-odc.adoc
  modules/serverless-list-source.adoc
  modules/serverless-monitoring-serving-cpu-memory.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-odc.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/event_sources/serverless-apiserversource.adoc
  serverless/event_sources/serverless-listing-event-sources.adoc
  serverless/event_sources/serverless-pingsource.adoc
  serverless/event_sources/serverless-sinkbinding.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30361 Changed "Network Operator" table headings to "Network customization".
  installing/installing-preparing.adoc
Labels: Peer Review Done, branch/enterprise-4.7, branch/enterprise-4.8, lgtm, size/XS

#30401 [enterprise-4.5] Improve docs about vmotion and vsphere
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: branch/enterprise-4.5, size/S

#30357 Adding Known Issue to RNs
  release_notes/ocp-4-7-release-notes.adoc
Labels: branch/enterprise-4.7, size/S

#29298 bug 1914896 - add warning note re security risk due to auto im…
  security/container_security/security-understanding.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30220 BZ#1936541 Add missing AWS permission
  modules/installation-aws-permissions.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#30230 Add OLM mirroring using offline media
  modules/olm-creating-catalog-from-index.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-pruning-index-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: Peer Review Done, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30416 [enterprise-4.6] Add OLM mirroring using offline media
  modules/olm-creating-catalog-from-index.adoc
  modules/olm-mirroring-catalog.adoc
  modules/olm-pruning-index-image.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: size/L

#30417 Unset :olm-restricted-networks:
  modules/olm-creating-catalog-from-index.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/XS

#23557 Need new section to address horizontal-pod-autoscaler-downscale-stabilization parameter
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-policies.adoc
  nodes/pods/nodes-pods-autoscaling.adoc
Labels: Peer Review Done, branch/enterprise-4.5, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, size/L

#30386 Update Welcome topic to be ROSA-centric
  welcome/index.adoc
Labels: Peer Review Done, branch/dedicated, size/M

#30432 remove dedicated going to 3
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#30433 updated version-less dedicated welcome page
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#30406 [enterprise-4.6] [srvls] Updates to serverless docs for OCP guidelines
  modules/apiserversource-kn-delete.adoc
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml-delete.adoc
  modules/apiserversource-yaml.adoc
  modules/deleting-pingsource-kn.adoc
  modules/deleting-pingsource-yaml.adoc
  modules/odc-creating-apiserversource.adoc
  modules/odc-deleting-apiserversource.adoc
  modules/serverless-list-source-types-kn.adoc
  modules/serverless-list-source-types-odc.adoc
  modules/serverless-list-source.adoc
  modules/serverless-monitoring-serving-cpu-memory.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-odc.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-yaml.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/event_sources/serverless-apiserversource.adoc
  serverless/event_sources/serverless-listing-event-sources.adoc
  serverless/event_sources/serverless-pingsource.adoc
  serverless/event_sources/serverless-sinkbinding.adoc
Labels: size/L
