Repository openshift/openshift-docs, pull requests merged in 2021-11, with the labels that each got.

#38061 BZ:1927776 - Adding clarification for regionEndpoint section
  modules/registry-operator-configuration-resource-overview-aws-s3.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37886 Fix YAML validation errors
  modules/builds-docker-credentials-private-registries.adoc
  modules/cnf-adjusting-nic-queues-with-the-performance-profile.adoc
  modules/cnf-deploying-the-du-infrastructure-profile.adoc
  modules/cnf-installing-the-operators.adoc
  modules/cnf-provisioning-deploying-a-distributed-unit-manually.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-verifying-queue-status.adoc
  modules/eco-configuring-machine-health-check-with-poison-pill.adoc
  modules/ibm-z-ensure-high-disk-performance-hyperpav.adoc
  modules/install-ibm-cloud-configuring-the-install-config-file.adoc
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-scheduler-pod-affinity-configuring.adoc
  modules/nodes-scheduler-pod-affinity-example.adoc
  modules/oauth-register-additional-client.adoc
  modules/ossm-cr-general.adoc
  modules/ztp-configuring-the-cluster-for-a-disconnected-environment.adoc
  modules/ztp-the-policygentemplate.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: size/L, branch/enterprise-4.10

#37657 BZ1986542: Updated example prometheus queries
  modules/virt-querying-metrics.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37887 BZ1994507: HPP backing directory must not be in root
  modules/virt-about-hostpath-provisioner.adoc
  modules/virt-configuring-selinux-hpp-on-rhcos8.adoc
  modules/virt-creating-storage-class.adoc
  modules/virt-using-hostpath-provisioner.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, CNV, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38093 BZ-2016270- updated correct image url for must-gather
  modules/sandboxed-containers-collecting-data.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38261 [enterprise-4.6] BZ1994507: HPP backing directory must not be in root
  modules/virt-about-hostpath-provisioner.adoc
  modules/virt-configuring-selinux-hpp-on-rhcos8.adoc
  modules/virt-creating-storage-class.adoc
  modules/virt-using-hostpath-provisioner.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc
Labels: size/M, branch/enterprise-4.6, CNV

#38149 BZ2017573: CNV-9800 is now TP for 4.9
  modules/virt-about-upgrading-virt.adoc
  modules/virt-about-workload-updates.adoc
  modules/virt-configuring-workload-update-methods.adoc
  virt/upgrading-virt.adoc
Labels: Peer Review Done, size/L, CNV, branch/enterprise-4.9, branch/enterprise-4.10

#37885 Fix all missing gcp attribute closures
  modules/admin-credentials-root-secret-formats.adoc
  modules/alternatives-to-storing-admin-secrets-in-kube-system.adoc
  modules/installation-uninstall-clouds.adoc
  modules/machineset-creating-non-guaranteed-instances.adoc
  modules/machineset-non-guaranteed-instance.adoc
  modules/manually-create-identity-access-management.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38265 PR37292: Fix two SRO YAML examples
  modules/psap-special-resource-operator-installing-using-cli.adoc
  modules/psap-special-resource-operator-using-configmaps.adoc
Labels: lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38272 [enterprise-4.6] Fix all missing gcp attribute closures
  modules/admin-credentials-root-secret-formats.adoc
  modules/alternatives-to-storing-admin-secrets-in-kube-system.adoc
  modules/installation-uninstall-clouds.adoc
  modules/machineset-creating-non-guaranteed-instances.adoc
  modules/machineset-non-guaranteed-instance.adoc
  modules/manually-create-identity-access-management.adoc
Labels: size/M, branch/enterprise-4.6

#38212 BZ:1902044 - Changing apiVersion in yaml for ClusterResourceQuota
  modules/quotas-selecting-projects.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38288 [virt] Removing xref prefix from commented-out xref
  virt/upgrading-virt.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.9

#38242 search: add ACS versioning
  _templates/_page_openshift.html.erb
Labels: size/XS

#38226 Modularize CSR management text
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_ibm_power/installing-ibm-power.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/csr-management.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/installation-requirements-user-infra.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38292 [enterprise-4.8] Modularize CSR management text
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_ibm_power/installing-ibm-power.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/csr-management.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/installation-requirements-user-infra.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/L, branch/enterprise-4.8

#38293 [enterprise-4.7] Modularize CSR management text
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_ibm_power/installing-ibm-power.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/csr-management.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/installation-requirements-user-infra.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/L, branch/enterprise-4.7

#38294 [enterprise-4.6] Modularize CSR management text
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_ibm_power/installing-ibm-power.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_platform_agnostic/installing-platform-agnostic.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/csr-management.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-requirements-user-infra.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/L, branch/enterprise-4.6

#38302 Fixed spelling mistake in RN
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS

#38224 Adds RNs for 4.9.5 to be released 11-1
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#38277 Removes https:// from console.redhat.com/api/ingress
  modules/configuring-firewall.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38260 BZ2010913: Updated note about bare metal cloud providers
  virt/install/preparing-cluster-for-virt.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.9, branch/enterprise-4.10

#36417 BZ1902087: Swapped mysql example for nodejs
  modules/nw-creating-project-and-service.adoc
  modules/nw-exposing-service.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36858 OSSMDOC-214 Release Notes for Service Mesh 2.1
  modules/ossm-document-attributes.adoc
  modules/ossm-rn-deprecated-features.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/ossm-supported-configurations.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37452 CNV-12828: reversing about-virt placeholder
  virt/about-virt.adoc
Labels: size/S, CNV, branch/enterprise-4.9

#37526 CNV-12828: reversing redirects to allow CNV content to be available a…
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS, CNV

#38184 OSSMDOC-210: Upgrading service mesh from 2.0 to 2.1
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37269 OSSMDOC-415: Document confirmation step for service mesh configuration tasks
  modules/ossm-federation-create-export.adoc
  modules/ossm-federation-create-import.adoc
  modules/ossm-federation-create-meshPeer.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36857 OSSMDOC-404 Update control plane profiles documentation
  modules/ossm-control-plane-profiles.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37052 OSSMDOC-382: add federation images to existing docs
  images/ossm-architecture.png
  images/ossm-federated-mesh.png
  images/ossm-federation-export-service.png
  images/ossm-federation-import-service.png
  images/ossm-federation.png
  modules/ossm-architecture.adoc
  modules/ossm-federation-config-export.adoc
  modules/ossm-federation-config-import.adoc
  modules/ossm-federation-config-meshPeer.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38223 OSSMDOC-424: Update supported CNI plugins service mesh
  modules/ossm-supported-configurations.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38239 Added notes for release 4.8.18
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#38337 OSSMDOC-383: Tasks to publish OSSM 2.1
  _topic_map.yml
  service_mesh/v2x/ossm-federation.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38369 [enterprise-4.8] OSSMDOC-383: Tasks to publish OSSM 2.1
  _topic_map.yml
  service_mesh/v2x/ossm-federation.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/M

#38368 [enterprise-4.7] OSSMDOC-383: Tasks to publish OSSM 2.1
  _topic_map.yml
  service_mesh/v2x/ossm-federation.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/M

#38367 [enterprise-4.6] OSSMDOC-383: Tasks to publish OSSM 2.1
  _topic_map.yml
  service_mesh/v2x/ossm-federation.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
Labels: size/M

#38357 [enterprise-4.7] Fix YAML validation errors
  modules/cnf-deploying-the-du-infrastructure-profile.adoc
  modules/cnf-installing-the-operators.adoc
  modules/cnf-provisioning-deploying-a-distributed-unit-manually.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/ibm-z-ensure-high-disk-performance-hyperpav.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-scheduler-pod-affinity-configuring.adoc
  modules/nodes-scheduler-pod-affinity-example.adoc
  modules/oauth-register-additional-client.adoc
  modules/ossm-cr-general.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: size/M, branch/enterprise-4.7

#38356 [enterprise-4.8] Fix YAML validation errors
  modules/cnf-adjusting-nic-queues-with-the-performance-profile.adoc
  modules/cnf-deploying-the-du-infrastructure-profile.adoc
  modules/cnf-installing-the-operators.adoc
  modules/cnf-provisioning-deploying-a-distributed-unit-manually.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-verifying-queue-status.adoc
  modules/eco-configuring-machine-health-check-with-poison-pill.adoc
  modules/ibm-z-ensure-high-disk-performance-hyperpav.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-scheduler-pod-affinity-configuring.adoc
  modules/nodes-scheduler-pod-affinity-example.adoc
  modules/oauth-register-additional-client.adoc
  modules/ossm-cr-general.adoc
  modules/ztp-configuring-the-cluster-for-a-disconnected-environment.adoc
  modules/ztp-the-policygentemplate.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: size/L, branch/enterprise-4.8

#38353 GH#38299: Use correct example for egress firewall
  modules/nw-egressnetworkpolicy-about.adoc
Labels: branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38126 Fix OVN-Kubernetes rollback table
  modules/nw-ovn-kubernetes-migration-about.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38127 OSDOCS--2572: Machine management overview page
  _topic_map.yml
  machine_management/index.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37941 OSDOCS-2403 RHOAM Addons
  adding_service_cluster/available-services.adoc
  adding_service_cluster/rosa-available-services.adoc
  modules/aws-cloudwatch.adoc
  modules/codeready-workspaces.adoc
  modules/osd-rhoam.adoc
Labels: branch/dedicated, Peer Review Done, size/M

#38039 MULTIARCH-1670, 1673: Backport multi-nic to IBM P/Z to OCP 4.8
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8

#38094 MULTIARCH-1671, 1674: Backport multi-nic to IBM P/Z to OCP 4.7
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7

#38177 MULTIARCH-1672, 1675: Backport multi-nic to IBM P/Z to OCP 4.6
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-user-infra-machines-static-network.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6

#38394 OSDOCS-2403: Fixed a mistyped sentence
  modules/osd-rhoam.adoc
Labels: size/XS

#37997 added network policy enhancement to networking.
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#38382 BZ2018486: Remove ipsec row for IBM Z
  modules/nw-operator-cr.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36588 Remove the cluster max limits for minor releases
  modules/openshift-cluster-maximums.adoc
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#38398 [enterprise-4.6] Remove the cluster max limits for minor releases
  modules/openshift-cluster-maximums.adoc
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: size/L

#38399 [enterprise-4.7] Remove the cluster max limits for minor releases
  modules/openshift-cluster-maximums.adoc
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: size/L

#38401 [enterprise-4.8] Remove the cluster max limits for minor releases
  modules/openshift-cluster-maximums.adoc
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: size/M

#37928 WINC-551 New auto-scaling feature for historical tracking
  windows_containers/windows-containers-release-notes-2-x.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7

#38404 JIRA-OSDOCS2735: Updated the default setting of preferred cluster privacy
  modules/create-aws-cluster.adoc
Labels: branch/dedicated, Peer Review Done, size/XS

#36351 GH#36350: Create conneted to disconnected cluster document
  _topic_map.yml
  images/create-nodes-okd.png
  modules/connected-to-disconnected-config-registry.adoc
  modules/connected-to-disconnected-disconnect.adoc
  modules/connected-to-disconnected-mirror-images.adoc
  modules/connected-to-disconnected-prepare-mirror.adoc
  modules/connected-to-disconnected-restore-insights.adoc
  modules/connected-to-disconnected-restore.adoc
  modules/connected-to-disconnected-verify.adoc
  post_installation_configuration/connected-to-disconnected.adoc
Labels: size/XL, branch/enterprise-4.9, branch/enterprise-4.10

#38416 [enterprise-4.6] Fix YAML validation errors
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-scheduler-pod-affinity-configuring.adoc
  modules/nodes-scheduler-pod-affinity-example.adoc
  modules/oauth-register-additional-client.adoc
  modules/ossm-cr-general.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: branch/enterprise-4.6

#38310 Adds 4.6.49 release notes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6

#36305 BZ#1949274: New info on migrating compute and control nodes to a different RHV storage domain.
  machine_management/modifying-machineset.adoc
  modules/machineset-migrating-compute-nodes-to-diff-sd-rhv.adoc
  modules/machineset-migrating-control-plane-nodes-to-diff-sd-rhv.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38417 update OCS version in links
  modules/migration-configuring-mcg.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38426 [enterprise-4.8] update OCS version in links
  modules/migration-configuring-mcg.adoc
Labels: size/XS, branch/enterprise-4.8

#37548 UPI is now supported for select platforms on WINC
  modules/wmco-prerequisites.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38371 Include Windows Server 20H2 image
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38434 PR38413: fix get packagemanifest command for SRO
  modules/psap-special-resource-operator-installing-using-cli.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38435 OSSMDOC-429: Small edits to service mesh release notes
  modules/ossm-rn-new-features.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38360 Adding a contribution workflow summary
  contributing_to_docs/contributing.adoc
  contributing_to_docs/create_or_edit_content.adoc
  images/osdocs-contribution-workflow.png
Labels: Peer Review Done, size/M

#37993 Adds a module that shows how to replace CLB with NLB
  modules/nw-aws-replacing-clb-with-nlb.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws-network-load-balancer.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38445 BZ#2020414: OSDK `operator-lib` version bump
  modules/osdk-run-proxy.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38267 RHDEVDOCS-3421 - TLSSecurityProfile setting for cluster monitoring
  modules/monitoring-default-monitoring-components.adoc
  monitoring/understanding-the-monitoring-stack.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#38259 SRVKE-940: Add note about at least once delivery for Kafka
  serverless/knative_eventing/serverless-kafka.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37963 Updated docs.css for sidebar toc and in page nav updates
  _stylesheets/docs.css
Labels: size/XXL

#32704 _templates/_page_openshift.html.erb changes to fix the sidebar, breadcrumb, and navbar
  _stylesheets/docs.css
  _templates/_page_openshift.html.erb
Labels: size/XXL

#38225 OSDOCS-1145: Reorganized the autoscaling documentation to one file.
  _topic_map.yml
  modules/ocm-enabling-autoscaling-nodes.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-enabling-autoscaling-nodes.adoc
  nodes/nodes-about-autoscaling-nodes.adoc
  nodes/nodes-disabling-autoscaling-nodes.adoc
  nodes/nodes-enabling-autoscaling-nodes.adoc
  nodes/nodes-machinepools-about.adoc
  nodes/rosa-managing-worker-nodes.adoc
Labels: branch/dedicated, Peer Review Done, size/L

#38479 [skip netlify] fixed template paths
  _templates/_page_openshift.html.erb
Labels: size/S

#38481 added 410 WIP site
  _distro_map.yml
Labels: size/XS

#38297 Update docs about how SRE access OSD clusters
  modules/policy-identity-access-management.adoc
Labels: size/XS

#38483 Add back annoying alert box on mobile
  _templates/_page_openshift.html.erb
Labels: size/M

#37369 RHDEVDOCS-3308 [Recurring] Release Notes, Known Issues, and Bug Fixes…
  cicd/pipelines/op-release-notes.adoc
  modules/op-release-notes-1-4.adoc
  modules/op-release-notes-1-5.adoc
  modules/op-release-notes-1-6.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#36961 RHDEVDOCS-3314 Add link from 5.0 RNs to RHBA-2021:81705-01 Openshift …
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-release-notes-5.0.9.adoc
Labels: Peer Review Done, size/S

#38020 BZ2013911: correct webUI navigation step for mco
  modules/troubleshooting-disabling-autoreboot-mco-console.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37510 RN-TELCODOCS-358: New release notes for sandboxed containers 4.9
  _topic_map.yml
  sandboxed_containers/deploying-sandboxed-container-workloads.adoc
  sandboxed_containers/sandboxed-containers-4.9-release-notes.adoc
  sandboxed_containers/troubleshooting-sandboxed-containers.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#38487 Updating 'login' to the verb 'log in' in policy doc
  modules/policy-identity-access-management.adoc
Labels: Peer Review Done, size/XS

#38497 fix OKD css
  _stylesheets/docs.css
Labels: size/S

#38510 Revert "RHDEVDOCS-3308 [Recurring] Release Notes, Known Issues, and Bug Fixes…"
  cicd/pipelines/op-release-notes.adoc
  modules/op-release-notes-1-4.adoc
  modules/op-release-notes-1-5.adoc
  modules/op-release-notes-1-6.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/L

#38513 CNV-13464: Updated HCO variable for 2.6.8
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, lgtm, size/XS, CNV, branch/enterprise-4.7

#37974 BZ1899491: adding an admonition to cautiously use LocalVolumeSet
  modules/persistent-storage-local-discovery.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38519 Revert "CNV-13464: Updated HCO variable for 2.6.8"
  modules/virt-document-attributes.adoc
Labels: size/XS

#38472 OSDOCS-2709: Added troubleshooting information for ELB failures.
  modules/rosa-troubleshooting-deployment.adoc
Labels: branch/dedicated, Peer Review Done, size/S

#38266 BZ:1908066 - Updating image build guidelines
  modules/images-create-guide-openshift.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38343 BZ1859396: Fixed out-of-date oc expose command
  modules/nw-exposing-service.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38283 Update matchLabels parameter in network-policy
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38410 Fix some nits on psap-configuring-node-feature-discovery.adoc
  modules/psap-configuring-node-feature-discovery.adoc
Labels: size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38542 Updates the network policy namespace selector
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6

#38505 Consistency with helm repository local naming.
  modules/adding-helm-repository.adoc
Labels: Peer Review Done, size/XS

#36448 GitOps- Change default namespace to spring-petclinic namespace
  modules/gitops-creating-an-application-by-using-the-argo-cd-dashboard.adoc
  modules/gitops-creating-an-application-by-using-the-oc-tool.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38555 TELCODOCS: 358 - added xref in 4.9 OCP release notes, in the Sandboxe…
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#37968 RHDEVDOCS-3411- added release notes for 1.3.0
  cicd/gitops/configuring-sso-for-argo-cd-on-openshift.adoc
  cicd/gitops/configuring_argo_cd_to_recursively_sync_a_git_repository_with_your_application/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-3-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
  modules/go-run-argo-cd-instance-on-infrastructure-nodes.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38449 BZ-2006004: Correcting version in repo names
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8

#38450 BZ-2006004: Correcting version in repo names
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9

#38451 BZ-2006004: Correcting version in repo names
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#38446 OSDOCS-2909: Removing admin ack docs for 4.10
  _topic_map.yml
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-prepare.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10

#38566 OSDOCS-2909: Removing admin ack docs for 4.10
  _topic_map.yml
  updating/updating-cluster-between-minor.adoc
  updating/updating-cluster-prepare.adoc
Labels: size/S

#38138 GH#38021:Fix ClusterResourceOverride examples
  modules/nodes-cluster-resource-configure.adoc
  modules/nodes-cluster-resource-override.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38276 GH#32985: Fix rsync examples
  modules/nodes-containers-copying-files-procedure.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38393 Adding guidance on text snippets
  contributing_to_docs/doc_guidelines.adoc
Labels: size/M

#37066 BZ#1881453: Document unused namespace for Manila CSI driver operator after upgrading from 4.5 to 4.6
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6

#38498 BZ-1952538: Update virtctl command options
  modules/virt-virtctl-commands.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36079 OSDOCS-2284: Added enabling multicast to ROSA and OSD with dedicated-admin ability…
  _topic_map.yml
  modules/nw-enabling-multicast.adoc
  networking/openshift_sdn/enabling-multicast.adoc
Labels: branch/dedicated, Peer Review Needed, size/S

#38543 adds notes for 4.9.6 release
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9

#38406 OSDOCS-2883: add balancing algorithm known issue
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#38488 fix footer overlap of sidebar and toc
  _templates/_page_openshift.html.erb
Labels: size/L

#38106 [enterprise-4.7]Fix case sensitive for Argo CD
  modules/gitops-creating-an-application-by-using-the-argo-cd-dashboard.adoc
  modules/gitops-synchronizing-your-application-application-with-your-git-repository.adoc
  modules/gitops-verifying-argo-cd-self-healing-behavior.adoc
  modules/logging-in-to-the-argo-cd-instance-by-using-your-openshift-credentials.adoc
Labels: Peer Review Done, lgtm, size/S, Dev Tools, branch/enterprise-4.7

#38585 RHDEVDOCS-3123 - removed gitops openshift service from support matrix tables
  modules/gitops-release-notes-1-1.adoc
  modules/gitops-release-notes-1-2-1.adoc
  modules/gitops-release-notes-1-2.adoc
Labels: lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38453 [RHACS] Added Kubernetes related guidence commands in the upgrade guide
  modules/disable-language-specific-vulneribility-scanning.adoc
  modules/enable-admission-controller-enforcement-54.adoc
  modules/enable-admission-controller-enforcement-55.adoc
  modules/enable-monitoring-customize-port.adoc
  modules/enable-monitoring.adoc
  modules/rollback-central-forced.adoc
  modules/rollback-central-normal.adoc
  modules/test-generated-policies.adoc
  modules/update-admission-controller.adoc
  modules/update-openshift-security-context-constraints.adoc
  modules/update-other-images.adoc
  modules/update-readiness-probes.adoc
  modules/upgrade-central.adoc
  modules/upgrade-scanner.adoc
  modules/validatingwebhookconfiguration-yaml-changes.adoc
  modules/verify-central-cluster-upgrade.adoc
  modules/verify-secured-cluster-upgrade.adoc
  upgrading/upgrading_roxctl/upgrade-from-44.adoc
Labels: Peer Review Done, size/L

#38298 [RHACS] Added required FQDNs in Central prereq
  modules/central-requirements.adoc
Labels: Peer Review Done, lgtm, size/XS

#38237 Updated builds-source-input-satellite-config.adoc corrected repo-file for sample repository configuration.
  modules/builds-source-input-satellite-config.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, Dev Tools, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37975 OSDOCS-2722: Create release note section for Compliance Operator
  _topic_map.yml
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38606 s/desired/required
  security/compliance_operator/compliance-operator-release-notes.adoc
  security/compliance_operator/compliance-operator-understanding.adoc
Labels: size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38553 BZ: 2021245 - Updated title of release notes with correct version of …
  sandboxed_containers/sandboxed-containers-4.9-release-notes.adoc
Labels: Peer Review Done, size/S

#38560 SRVOCF-360: Updated curl command to kn
  modules/serverless-nodejs-context-object-reference.adoc
Labels: size/S, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38436 BZ2016590: Adding explicit ref IPI to dual-stack bare metal note
  networking/ovn_kubernetes_network_provider/converting-to-dual-stack.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36249 THREESCALE-7497: Removal of 3scale Istio adapter docs to add 3scale WebAssembly docs.
  _topic_map.yml
  modules/ossm-configuring-the-threescale-wasm-auth-module.adoc
  modules/ossm-extensions-wasm-deploy.adoc
  modules/ossm-threescale-applying-external-service-entry-objects.adoc
  modules/ossm-threescale-configuring-the-threescale-webassembly-module.adoc
  modules/ossm-threescale-webassembly-module-api-object.adoc
  modules/ossm-threescale-webassembly-module-backend-object.adoc
  modules/ossm-threescale-webassembly-module-configuration.adoc
  modules/ossm-threescale-webassembly-module-credentials-object.adoc
  modules/ossm-threescale-webassembly-module-examples-for-credentials-use-cases.adoc
  modules/ossm-threescale-webassembly-module-lookup-queries.adoc
  modules/ossm-threescale-webassembly-module-mapping-rule-object.adoc
  modules/ossm-threescale-webassembly-module-mapping-rules-object.adoc
  modules/ossm-threescale-webassembly-module-minimal-working-configuration.adoc
  modules/ossm-threescale-webassembly-module-operations-object.adoc
  modules/ossm-threescale-webassembly-module-services-object.adoc
  modules/ossm-threescale-webassembly-module-source-object.adoc
  modules/ossm-threescale-webassembly-module-system-object.adoc
  modules/ossm-threescale-webassembly-module-upstream-object.adoc
  service_mesh/v2x/ossm-threescale-webassembly-module.adoc
Labels: Peer Review Done, size/XXL, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38500 Adding a note that you must have cluster-admin permissions to use oc …
  cli_reference/openshift_cli/administrator-cli-commands.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38501 Adding a note that you must have cluster-admin permissions to use oc …
  cli_reference/openshift_cli/administrator-cli-commands.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7

#38631 Adding a note that you must have cluster-admin permissions to use oc …
  cli_reference/openshift_cli/administrator-cli-commands.adoc
Labels: size/XS, branch/enterprise-4.6

#38559 GH#37930 Update RHCOS registry URL for firewall
  modules/configuring-firewall.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38157 OSDOCS-2711 PV note for Windows
  modules/nodes-containers-projected-volumes-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#38625 SRVCOM-1606: Remove outdated images, general cleanup
  images/eventing-form-view.png
  images/eventing-installed-operator.png
  images/eventing-tab-created.png
  images/kafka-installed-operator.png
  images/kafka-tab-created.png
  images/serverless-create-eventing-yaml.png
  images/serverless-create-eventing.png
  images/serverless-create-serving-yaml.png
  images/serverless-create-serving.png
  images/serverless-search.png
  images/serving-form-view.png
  images/serving-installed-operator.png
  images/serving-tab-created.png
  modules/knative-serving-advanced-config.adoc
  modules/serverless-config-replicas-eventing.adoc
  modules/serverless-config-replicas-kafka.adoc
  modules/serverless-config-replicas-serving.adoc
  modules/serverless-install-eventing-web-console.adoc
  modules/serverless-install-serving-web-console.adoc
  modules/serverless-install-web-console.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38644 [virt] Removing CNV must-gather docs from OKD
  _topic_map.yml
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.9, branch/enterprise-4.10

#38405 OSDOCS-2883: add balancing algorithm known issue
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#38470 Added notes for release 4.8.19
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#38656 Added icons and pdf
  _templates/_page_openshift.html.erb
Labels: size/M

#38658 [skip netlify] add tool tips
  _templates/_page_openshift.html.erb
Labels: size/XS

#38584 RHDEVDOCS-3458 - GitOps 1.3.1 release notes
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-3-1.adoc
Labels: Peer Review Done, size/S, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38484 CCXDEV-4810 Add the Insights Operator to the "Red Hat Operators"
  modules/insights-operator.adoc
  operators/operator-reference.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37992 BZ2006013: add a line which clarifies why additionalbundletrust does not work without proxy
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38651 Remove "virtual" wording for bare metal resource requirements
  modules/installation-requirements-user-infra.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#36621 Add restrictions and requirements of Proxy installation with Kuryr
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38211 RHDEVDOCS-3428 - Replaced instances of 8Gi req mem with 16Gi.
  modules/cluster-logging-about-crd.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/dedicated-cluster-install-deploy.adoc
  modules/images-create-metadata-define.adoc
  modules/images-create-metadata.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.6, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38654 [enterprise-4.6] SRVCOM-1606: Remove outdated images, general cleanup
  images/eventing-form-view.png
  images/eventing-installed-operator.png
  images/eventing-tab-created.png
  images/kafka-installed-operator.png
  images/kafka-tab-created.png
  images/serverless-create-eventing-yaml.png
  images/serverless-create-eventing.png
  images/serverless-create-serving-yaml.png
  images/serverless-create-serving.png
  images/serverless-search.png
  images/serving-form-view.png
  images/serving-installed-operator.png
  images/serving-tab-created.png
  modules/knative-serving-advanced-config.adoc
  modules/serverless-config-replicas-eventing.adoc
  modules/serverless-config-replicas-kafka.adoc
  modules/serverless-config-replicas-serving.adoc
  modules/serverless-install-eventing-web-console.adoc
  modules/serverless-install-serving-web-console.adoc
  modules/serverless-install-web-console.adoc
Labels: size/L

#36314 RHDEVDOCS-3095: cluster logging updates
  modules/cluster-logging-logstore-limits.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38463 BZ-2020416: IPv6 is not supported for user-provisioned clusters
  modules/installation-configuration-parameters.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38234 BZ1990953: Only the first container can use SR-IOV network attachment
  modules/nw-multus-add-pod.adoc
  networking/hardware_networks/about-sriov.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38657 Fix duplicate words RHOSP/RHV
  installing/installing-preparing.adoc
Labels: size/XS

#38296 [RHACS] Updated the support page for uploading diagnostic bundle
  configuration/generate-diagnostic-bundle.adoc
  modules/acs-requirements.adoc
  modules/support-submitting-a-case.adoc
  support/getting-support-stackrox.adoc
  support/getting-support.adoc
Labels: Peer Review Done, size/M

#38471 gh#36355 - Clarify isolated and reserved CPUs information
  modules/configuring_hyperthreading_for_a_cluster.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37577 BZ1971700: Add a section to expose default registry
  modules/registry-exposing-default-registry-manually.adoc
  registry/securing-exposing-registry.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38712 [enterprise-4.7] changes for gh#36355 on ent-4.7
  modules/configuring_hyperthreading_for_a_cluster.adoc
Labels: size/S, branch/enterprise-4.7

#38095 MIG-834: More PV values to edit in MigPlan
  migrating_from_ocp_3_to_4/advanced-migration-options-3-4.adoc
  migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
  modules/migration-editing-pvs-in-migplan.adoc
  modules/migration-understanding-data-copy-methods.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38718 Removing OSD references from the topic map
  _topic_map.yml
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37905 OSDOCS2582: include overview for the backup and restore book
  _topic_map.yml
  backup_and_restore/index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38728 [enterprise-4.8] Removing OSD references from the topic map
  _topic_map.yml
Labels: size/L
