Repository openshift/openshift-docs, pull requests merged in 2022-01, with the labels that each got.

#40167 BZ2033541: changed container image source
  modules/deployments-creating-rolling-deployment.adoc
Labels: Peer Review Needed, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40187 BZ2032670: Remove CommonName workaround for OCP 4.10 restricted install doc
  modules/installation-mirror-repository.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#39793 BZ1825250: Managing cluster resources
  _topic_maps/_topic_map.yml
  modules/cluster-resources.adoc
  support/managing-cluster-resources.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40109 BZ1964932: Add warning
  modules/nw-ingress-sharding-namespace-labels.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40088 BZ1961559: Add nmcli modify command
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40098 RNs 4-9-12
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#40013 BZ#2033699 Clarify restricted network statement
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40213 [enterprise-4.6] Clarify restricted network statement
  modules/installation-overview.adoc
Labels: size/XS, branch/enterprise-4.6

#40146 THREESCALE-7940: Updated to correct image.
  modules/ossm-threescale-webassembly-module-minimal-working-configuration.adoc
Labels: size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39985 GH#39949 Fix command typo
  modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40139 BZ:1965420 - Adding note section to show why we do not have guidance on support limits
  modules/openshift-cluster-maximums-major-releases.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39753 Setting VHD URL without referencing RHCOS file directly on GH
  modules/installation-azure-user-infra-uploading-rhcos.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#40240 Make the TOC text unselectable
  _stylesheets/docs.css
Labels: size/XS

#40075 BZ-2034325: correcting typo on DICOVERY and adding ROLE_WORKER_CNF=worker-cnf
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40207 BZ1999786: added a KCS ref link for system reserved values
  modules/nodes-nodes-resources-configuring-setting.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7

#40235 Change copyright from 2021 -> 2022
  404-commercial.html
  _templates/_footer_other.html.erb
  index-commercial.html
  welcome/legal-notice.adoc
Labels: Peer Review Needed, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40021 OSDOCS-2677: Added a link to a Knowledge base article for SRE Residency.
  modules/policy-security-regulation-compliance.adoc
  modules/rosa-policy-security-regulation-compliance.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40236 GH#40104 Hide AWS-specific configs for installer proxy information
  modules/installation-configure-proxy.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40265 [enterprise-4.8] GH#40104 Hide AWS-specific configs for installer proxy information
  modules/installation-configure-proxy.adoc
Labels: size/M, branch/enterprise-4.8

#40266 [enterprise-4.7] GH#40104 Hide AWS-specific configs for installer proxy information
  modules/installation-configure-proxy.adoc
Labels: size/M, branch/enterprise-4.7

#40267 [enterprise-4.6] GH#40104 Hide AWS-specific configs for installer proxy information
  modules/installation-configure-proxy.adoc
Labels: size/M, branch/enterprise-4.6

#40046 BZ-1892611: adding first commit for BZ-1892611
  modules/ipi-install-creating-a-disconnected-registry.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40181 Adds 4.8.25 release notes
  release_notes/ocp-4-8-release-notes.adoc
Labels: size/S

#40281 Minor update to master to force publish to d.o.c.
  contributing_to_docs/contributing.adoc
Labels: size/XS

#40228 Add the cluster-monitoring namespace label to CO and FIO cli instructions
  modules/compliance-operator-cli-installation.adoc
  modules/file-integrity-operator-installing-cli.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40025 [virt] removing dedicated section from virt attrib file
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.9, branch/enterprise-4.10

#40133 OSDOCS-3040: Check for config drift regularly
  architecture/control-plane.adoc
  modules/architecture-machine-config-pools.adoc
  modules/machine-config-drift-detection.adoc
  modules/machine-config-overview.adoc
  modules/understanding-machine-config-operator.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#38485 BZ1964380: remove etcd DNS records from Azure ARM templates
  modules/installation-creating-azure-bootstrap.adoc
  modules/installation-creating-azure-control-plane.adoc
  modules/installation-creating-azure-worker.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#39771 BZ2016892 Remove reboot note on ImageContentSourcePolicy change
  modules/olm-mirroring-catalog-icsp.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39342 JIRA-OSDOCS3005: Removed one reference of deprecated --prefix flag
  modules/rosa-upgrading-preparing-4-7-to-4-8.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39931 OSSMDOC-337: Document how to access logs from Kiali.
  _topic_maps/_topic_map.yml
  modules/ossm-access-grafana.adoc
  modules/ossm-access-prometheus.adoc
  modules/ossm-config-dist-trac.adoc
  modules/ossm-config-external-jaeger.adoc
  modules/ossm-config-sampling.adoc
  modules/ossm-control-plane-cli.adoc
  modules/ossm-distr-tracing.adoc
  modules/ossm-document-attributes-1x.adoc
  modules/ossm-jaeger-accessing-console.adoc
  modules/ossm-kiali-accessing-console.adoc
  modules/ossm-kiali-viewing-logs.adoc
  modules/ossm-kiali-viewing-metrics.adoc
  modules/ossm-observability-addresses.adoc
  modules/ossm-observability-cli.adoc
  modules/ossm-observability-visual.adoc
  modules/ossm-tutorial-bookinfo-install.adoc
  modules/ossm-tutorial-jaeger-generating-traces.adoc
  service_mesh/v2x/ossm-distr-tracing.adoc
  service_mesh/v2x/ossm-observability.adoc
  service_mesh/v2x/ossm-troubleshooting-istio.adoc
Labels: size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40299 Dev Preview: Cgroups v2 phase 2 RN
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#40304 adding some symlinks to module directories
  cli_reference/opm/images
  cli_reference/opm/modules
  serverless/security/images
  serverless/security/modules
  serverless/update/images
  serverless/update/modules
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40017 OSDOCS-2977: Updated the descriptions for interactive creation mode.
  modules/rosa-sts-interactive-mode-reference.adoc
  rosa_getting_started_sts/rosa_creating_a_cluster_with_sts/rosa-sts-interactive-mode-reference.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40085 OSDOCS-2736 - Adding etcd encryption steps for OSD and ROSA
  modules/create-aws-cluster.adoc
  modules/create-gcp-cluster.adoc
  modules/rosa-sdpolicy-security.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations.adoc
  modules/rosa-sts-interactive-mode-reference.adoc
  modules/sdpolicy-security.adoc
  osd_cluster_create/creating-your-cluster.adoc
  rosa_getting_started_sts/rosa_creating_a_cluster_with_sts/rosa-sts-creating-a-cluster-with-customizations.adoc
  rosa_getting_started_sts/rosa_creating_a_cluster_with_sts/rosa-sts-interactive-mode-reference.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#40076 BZ2005023: Updates MaxCSIVolumeCount namespace
  modules/nodes-scheduler-default-predicates.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40327 Add symlinks for REST API directories
  rest_api/authorization_apis/modules
  rest_api/autoscale_apis/modules
  rest_api/config_apis/modules
  rest_api/console_apis/modules
  rest_api/extension_apis/modules
  rest_api/image_apis/modules
  rest_api/machine_apis/modules
  rest_api/metadata_apis/modules
  rest_api/monitoring_apis/modules
  rest_api/network_apis/modules
  rest_api/node_apis/modules
  rest_api/oauth_apis/modules
  rest_api/objects/modules
  rest_api/operator_apis/modules
  rest_api/operatorhub_apis/modules
  rest_api/policy_apis/modules
  rest_api/project_apis/modules
  rest_api/provisioning_apis/modules
  rest_api/rbac_apis/modules
  rest_api/role_apis/modules
  rest_api/schedule_and_quota_apis/modules
  rest_api/security_apis/modules
  rest_api/storage_apis/modules
  rest_api/template_apis/modules
  rest_api/user_and_group_apis/modules
  rest_api/workloads_apis/modules
Labels: Peer Review Done, size/S

#39873 RHDEVDOCS-3570 Docs: Use sidecar pattern for Jenkins pod templates
  modules/images-other-jenkins-config-kubernetes.adoc
  modules/images-other-jenkins-create-service.adoc
  modules/images-other-jenkins-env-var.adoc
  modules/images-other-jenkins-kubernetes-plugin.adoc
  openshift_images/using_images/images-other-jenkins-agent.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.10

#39936 BZ2033449: Configuring FIFO priority scheduling for PTP hardware
  modules/cnf-about-ptp-and-clock-synchronization.adoc
  modules/cnf-about-ptp-fast-event-notifications-framework.adoc
  modules/cnf-configuring-fifo-priority-scheduling-for-ptp.adoc
  modules/cnf-configuring-the-ptp-fast-event-publisher.adoc
  modules/cnf-fast-event-notifications-api-refererence.adoc
  modules/cnf-installing-amq-interconnect-messaging-bus.adoc
  modules/cnf-monitoring-fast-events-metrics-using-cli.adoc
  modules/cnf-ptp-fast-event-metrics-in-prometheus.adoc
  modules/cnf-troubleshooting-common-ptp-operator-issues.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  modules/nw-ptp-device-discovery.adoc
  modules/nw-ptp-introduction.adoc
  networking/configuring-ptp.adoc
  networking/using-ptp.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.9, branch/enterprise-4.10

#40344 [enterprise-4.10] BZ2002582: Rewording supported cluster section
  modules/virt-supported-cluster-version.adoc
Labels: size/XS

#40346 [enterprise-4.9] BZ2002582: Rewording supported cluster section
  modules/virt-supported-cluster-version.adoc
Labels: size/XS

#40347 [enterprise-4.8] BZ2002582: Rewording supported cluster section
  modules/virt-supported-cluster-version.adoc
Labels: size/XS

#40348 [enterprise-4.7] BZ2002582: Rewording supported cluster section
  modules/virt-supported-cluster-version.adoc
Labels: size/XS

#40280 SRVKS-552: Add information about serverless configuration options
  _topic_maps/_topic_map.yml
  modules/knative-serving-advanced-config.adoc
  serverless/admin_guide/serverless-configuration.adoc
  serverless/develop/serverless-configuring-routes.adoc
  serverless/develop/serverless-traffic-management.adoc
  serverless/knative_serving/images
  serverless/knative_serving/modules
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40180 RHDEVDOCS-3360 - How to run OpenShift GitOps control plane on infra nodes
  _topic_maps/_topic_map.yml
  cicd/gitops/run-gitops-control-plane-workload-on-infra-nodes.adoc
  modules/go-add-infra-nodes.adoc
Labels: Peer Review Done, size/M, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40175 BZ1995934: add the IPv6 prereq for converting to dual stack
  modules/nw-dual-stack-convert.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40208 BZ2013874: Added a note to use same Ignition config file and ISO
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40378 Adds notes for 4.9.13 release
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#40342 BZ:1865848 - Adding inventory variable to chart and warning label
  install/configuring_inventory_file.adoc
  install_config/adding_hosts_to_existing_cluster.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-3.11

#40262 BZ2029542: FC fully supported for 4.6
  modules/storage-persistent-storage-block-volume.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6

#40258 BZ2029542: FC fully supported for 4.7
  modules/storage-persistent-storage-block-volume.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.7

#40361 OSDOCS-3150: Add flag argument to the Unapply a remediation command
  modules/compliance-unapplying.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40012 OSDOCS2506: Architecture Overview
  _topic_maps/_topic_map.yml
  architecture/index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40105 Update contrib guideline for lowercase in ID metadata
  contributing_to_docs/doc_guidelines.adoc
Labels: Peer Review Done, size/XS

#40405 #40283 and #40336, fixing variables in H1s.
  _topic_maps/_topic_map.yml
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v1x/ossm-architecture.adoc
  service_mesh/v1x/ossm-config.adoc
  service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v1x/removing-ossm.adoc
  service_mesh/v2x/ossm-architecture.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  service_mesh/v2x/removing-ossm.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39260 [Updated] Image Registry Operator configuration parameters `disableRe…
  modules/registry-operator-configuration-resource-overview.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40413 [enterprise-4.6] #40283 and #40336, fixing variables in H1s.
  _topic_maps/_topic_map.yml
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v1x/ossm-architecture.adoc
  service_mesh/v1x/ossm-config.adoc
  service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v1x/removing-ossm.adoc
  service_mesh/v2x/ossm-architecture.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  service_mesh/v2x/removing-ossm.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh

#40414 [enterprise-4.7] #40283 and #40336, fixing variables in H1s.
  _topic_maps/_topic_map.yml
  service_mesh/v1x/installing-ossm.adoc
  service_mesh/v1x/ossm-architecture.adoc
  service_mesh/v1x/ossm-config.adoc
  service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc
  service_mesh/v1x/preparing-ossm-installation.adoc
  service_mesh/v1x/removing-ossm.adoc
  service_mesh/v2x/ossm-architecture.adoc
  service_mesh/v2x/ossm-deploy-production.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  service_mesh/v2x/removing-ossm.adoc
  service_mesh/v2x/upgrading-ossm-to-2-1.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: size/S, Service Mesh, branch/enterprise-4.7

#40417 Follow-up to PR39260: Add Image Registry Operator configuration parameter `disabledRegistry`
  modules/registry-operator-configuration-resource-overview.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40424 [enterprise-4.7] Follow-up to PR39260: Add Image Registry Operator configuration parameter `disabledRegistry`
  modules/registry-operator-configuration-resource-overview.adoc
Labels: size/XS

#40423 RHDEVDOCS-3249 - correct outputref code sample.
  modules/cluster-logging-configuration-of-json-log-data-for-default-elasticsearch.adoc
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
Labels: Peer Review Done, size/XS, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40419 OKD replacing oVirt install docs
  _topic_maps/_topic_map.yml
Labels: size/S

#40425 RHDEVDOCS-3294 to main - Correcting outputrefs code sample.
  modules/cluster-logging-configuration-of-json-log-data-for-default-elasticsearch.adoc
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.10

#40411 GH22601: Adding link to limits and requests
  applications/deployments/managing-deployment-processes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39808 Bug 2025488: Remove namespace selection
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, bugzilla/valid-bug, bugzilla/severity-low, branch/enterprise-4.9, branch/enterprise-4.10

#40300 BZ2029403: Replace duplicated paragraph
  modules/update-oc-configmap-signature-verification.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#39852 BZ2025482: Required Azure roles
  modules/installation-azure-permissions.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40352 OSDOCS-2647: Adding release note for RHOCS AMI for AWS GovCloud
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#40436 BZ1804551:Updates Multiple zone limitations URL and link text
  install_config/topics/manually_configuring_for_vsphere.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-3.11

#40453 GH38678: Adding info on playbook to preparing for playbook topic
  modules/rhel-preparing-playbook-machine.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40454 [enterprise-4.6] GH38678: Adding info on playbook to preparing for playbook topic
  modules/rhel-preparing-playbook-machine.adoc
Labels: size/XS

#40455 [enterprise-4.7] GH38678: Adding info on playbook to preparing for playbook topic
  modules/rhel-preparing-playbook-machine.adoc
Labels: size/XS

#40456 [enterprise-4.8] GH38678: Adding info on playbook to preparing for playbook topic
  modules/rhel-preparing-playbook-machine.adoc
Labels: size/XS

#40269 BZ#2027477: ipvlan does not support dhcp
  modules/nw-multus-ipvlan-object.adoc
Labels: Peer Review Needed, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40301 [RHACS]: Update the button label for generating an init bundle
  modules/portal-generate-init-bundle.adoc
Labels: Peer Review Done, size/XS

#40308 OSDOCS-2661: Add console customization types for bundles in 4.10
  modules/olm-bundle-format.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#40418 SRVCOM-1580: move conceptual info to Discover section
  _topic_maps/_topic_map.yml
  modules/security-build-knative.adoc
  security/container_security/security-build.adoc
  serverless/discover/about-serverless.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/discover/serverless-eventing-components.adoc
  serverless/discover/serverless-functions-about.adoc
  serverless/discover/serverless-serving-components.adoc
  serverless/discover/serverless-understanding-eventing.adoc
  serverless/discover/serverless-understanding-serving.adoc
  serverless/knative_eventing/serverless-event-sinks.adoc
Labels: size/L, kind/cleanup, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40467 [enterprise-4.6] SRVCOM-1580: move conceptual info to Discover section
  _topic_maps/_topic_map.yml
  modules/security-build-knative.adoc
  security/container_security/security-build.adoc
  serverless/discover/about-serverless.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/discover/serverless-eventing-components.adoc
  serverless/discover/serverless-functions-about.adoc
  serverless/discover/serverless-serving-components.adoc
  serverless/discover/serverless-understanding-eventing.adoc
  serverless/discover/serverless-understanding-serving.adoc
  serverless/knative_eventing/serverless-event-sinks.adoc
Labels: size/L

#40324 OSDOCS-2679: Add missing networking metrics
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.10

#40468 Move additional resouces heading
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40303 CNV-14482: Adding back the VM integration with service mesh assembly
  _topic_maps/_topic_map.yml
  modules/virt-adding-vm-to-service-mesh.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.10

#40461 SRVCOM-1580: Content reorg, review and editing
  _topic_maps/_topic_map.yml
  serverless/admin_guide/serverless-cluster-admin-eventing.adoc
  serverless/admin_guide/serverless-configuring-channels.adoc
  serverless/develop/serverless-apiserversource.adoc
  serverless/develop/serverless-creating-channels.adoc
  serverless/develop/serverless-custom-event-sources.adoc
  serverless/develop/serverless-event-sinks.adoc
  serverless/develop/serverless-kafka-source.adoc
  serverless/develop/serverless-pingsource.adoc
  serverless/develop/serverless-subs.adoc
  serverless/discover/about-serverless.adoc
  serverless/discover/knative-event-sources.adoc
  serverless/discover/serverless-channels.adoc
  serverless/discover/serverless-eventing-components.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/knative_eventing/serverless-event-delivery.adoc
  serverless/knative_eventing/serverless-kafka.adoc
  serverless/knative_eventing/serverless-using-brokers.adoc
  serverless/reference/images
  serverless/reference/kn-eventing-ref.adoc
  serverless/reference/kn-flags-reference.adoc
  serverless/reference/kn-func-ref.adoc
  serverless/reference/kn-serving-ref.adoc
  serverless/reference/modules
  serverless/reference/serverless-listing-event-sources.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40487 [enterprise-4.6] SRVCOM-1580: Move content under new headings
  _topic_maps/_topic_map.yml
  serverless/admin_guide/serverless-configuring-channels.adoc
  serverless/develop/serverless-apiserversource.adoc
  serverless/develop/serverless-creating-channels.adoc
  serverless/develop/serverless-custom-event-sources.adoc
  serverless/develop/serverless-event-sinks.adoc
  serverless/develop/serverless-kafka-source.adoc
  serverless/develop/serverless-pingsource.adoc
  serverless/develop/serverless-subs.adoc
  serverless/discover/about-serverless.adoc
  serverless/discover/knative-event-sources.adoc
  serverless/discover/serverless-channels.adoc
  serverless/discover/serverless-eventing-components.adoc
  serverless/event_sources/knative-event-sources.adoc
  serverless/knative_eventing/serverless-event-delivery.adoc
  serverless/knative_eventing/serverless-kafka.adoc
  serverless/knative_eventing/serverless-using-brokers.adoc
  serverless/reference/images
  serverless/reference/kn-eventing-ref.adoc
  serverless/reference/kn-flags-reference.adoc
  serverless/reference/kn-func-ref.adoc
  serverless/reference/kn-serving-ref.adoc
  serverless/reference/modules
  serverless/reference/serverless-listing-event-sources.adoc
Labels: size/L

#40491 Fixed preview page alignment and formatting
  scripts/ocpdocs/_previewpage
Labels: size/L, RHACS

#40376 Added notes for release 4.8.26
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8

#39661 NE-743: include upstream resolvers in the DNS Opertaor CRD
  modules/nw-dns-forward.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#40499 Adds 4.6.53 release notes
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6

#40404 IBM Cloud release note for OCP 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#40481 BZ#2014982: adding missing link to how cluster is configured to trust…
  updating/installing-update-service.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40014 OSDOCS-2506: architecture overview
  _topic_maps/_topic_map.yml
  architecture/index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6

#40475 GH38690: Update link to kubernetes config options
  modules/nodes-nodes-managing-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40239 OSSMDOC-139: Document installing the OTEL Operator.
  _topic_maps/_topic_map.yml
  distr_tracing/distr_tracing_install/distr-tracing-deploying-otel.adoc
  distr_tracing/distr_tracing_install/distr-tracing-installing.adoc
  modules/distr-tracing-deploy-default.adoc
  modules/distr-tracing-deploy-otel-collector.adoc
  modules/distr-tracing-deploy-production-es.adoc
  modules/distr-tracing-deploy-streaming.adoc
  modules/distr-tracing-install-jaeger-operator.adoc
  modules/distr-tracing-install-otel-operator.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40473 GH39759: Remove SNO assisted installer from OKD
  installing/installing_sno/install-sno-installing-sno.adoc
Labels: okd-only, Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40527 BZ1683050: Fix oc logs command
  dev_guide/dev_tutorials/ruby_on_rails.adoc
Labels: size/XS, branch/enterprise-3.11

#40343 OSDOCS-3053: Removing a KubeletConfig remediation
  modules/compliance-removing-kubeletconfig.adoc
  security/compliance_operator/compliance-operator-remediation.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40506 [enterprise-4.7]BZ:2013668 - Updating the values in ContainerRuntimeConfig
  modules/create-a-containerruntimeconfig-crd.adoc
Labels: size/XS

#40505 [enterprise-4.8]BZ:2013668 - Updating the values in ContainerRuntimeConfig
  modules/create-a-containerruntimeconfig-crd.adoc
Labels: size/XS

#40403 osdocs3148: clearing build errors
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  getting_started/accessing-your-services.adoc
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  modules/api-support-tiers-mapping.adoc
  modules/api-support-tiers.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/developer-cli-odo-sample-applications-binary.adoc
  modules/developer-cli-odo-sample-applications-git.adoc
  modules/developer-cli-odo-sample-applications-github.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/dr-scenario-cluster-state-issues.adoc
  modules/migration-direct-volume-migration-and-direct-image-migration.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/nodes-cluster-overcommit-qos-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-qos-about-swap.adoc
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-high-performance-multicast.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/osdk-leader-election-types.adoc
  modules/ossm-auto-route-annotations.adoc
  modules/ossm-auto-route-enable.adoc
  modules/ossm-auto-route.adoc
  modules/serverless-domain-mapping-custom-tls-cert.adoc
  networking/hardware_networks/using-sriov-multicast.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  operators/operator_sdk/osdk-leader-election.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/node-tasks.adoc
  rest_api/images
  rest_api/modules
  rest_api/understanding-api-support-tiers.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/security/serverless-custom-tls-cert-domain-mapping.adoc
  service_mesh/v2x/ossm-config.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: Peer Review Done, size/XL, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40540 [enterprise-4.8] osdocs3148: clearing build errors
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  getting_started/accessing-your-services.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  modules/api-support-tiers-mapping.adoc
  modules/api-support-tiers.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/developer-cli-odo-sample-applications-binary.adoc
  modules/developer-cli-odo-sample-applications-git.adoc
  modules/developer-cli-odo-sample-applications-github.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/dr-scenario-cluster-state-issues.adoc
  modules/migration-direct-volume-migration-and-direct-image-migration.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/nodes-cluster-overcommit-qos-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-qos-about-swap.adoc
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-high-performance-multicast.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/osdk-leader-election-types.adoc
  modules/ossm-auto-route-annotations.adoc
  modules/ossm-auto-route-enable.adoc
  modules/ossm-auto-route.adoc
  modules/serverless-domain-mapping-custom-tls-cert.adoc
  networking/hardware_networks/using-sriov-multicast.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  operators/operator_sdk/osdk-leader-election.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/node-tasks.adoc
  rest_api/images
  rest_api/modules
  rest_api/understanding-api-support-tiers.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/security/serverless-custom-tls-cert-domain-mapping.adoc
  service_mesh/v2x/ossm-config.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: size/XL

#40074 BUILD-275: add support for build csi volume source
  modules/builds-using-build-volumes.adoc
Labels: Peer Review Done, lgtm, size/M, Dev Tools, docs-approved, branch/enterprise-4.10

#40547 Revert "JIRA743:include upstream resolvers in the DNS Opertaor CRD"
  modules/nw-dns-forward.adoc
Labels: size/M

#40548 Revert "JIRA743:include upstream resolvers in the DNS Opertaor CRD"
  modules/nw-dns-forward.adoc
Labels: size/M

#40546 Revert "JIRA743:include upstream resolvers in the DNS Opertaor CRD"
  modules/nw-dns-forward.adoc
Labels: size/M

#40222 [4.9] Use official NFD image
  modules/psap-using-node-feature-discovery-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9

#40221 Use official image for NFD Operator
  modules/psap-using-node-feature-discovery-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#40513 OSDOCS-3160: NFD Update version in examples for next release
  modules/psap-installing-node-feature-discovery-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#40362 CNV-15340: Relocate content for configuring certificate rotation
  _topic_maps/_topic_map.yml
  modules/virt-troubleshooting-cert-rotation-parameters.adoc
  virt/install/installing-virt-cli.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-certificate-rotation.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40541 OSDOCS-3077: Removed a sentence on restricted access.
  modules/sdpolicy-account-management.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39792 BZ2020713: Remove DU requirement tables and merge info with procedures
  modules/ztp-configuring-a-static-ip.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  modules/ztp-du-host-requirements.adoc
  scalability_and_performance/ztp-deploying-disconnected.adoc
Labels: lgtm, size/L, branch/enterprise-4.9, branch/enterprise-4.10

#40433 OSSMDOC-451: Service Mesh 2.1.1 Release Notes
  modules/ossm-config-disable-networkpolicy.adoc
  modules/ossm-document-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
Labels: size/L, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40294 BZ1997540: replacing virt object maximum doc with KBase link
  modules/virt-about-cluster-limits.adoc
  modules/virt-tested-cluster-maximums.adoc
  virt/install/virt-planning-environment-object-maximums.adoc
Labels: Peer Review Done, size/M, CNV, branch/enterprise-4.9, branch/enterprise-4.10

#40242 Hide elements from print preview
  _stylesheets/docs.css
  _templates/_page_openshift.html.erb
Labels: size/S

#40345 [RHACS]: Update Circle CI commands and correct spelling error
  modules/integrate-circle-ci.adoc
Labels: lgtm, size/S, RHACS

#40412 OSDOCS-2911: Adding documentation about conditional updates
  modules/understanding-upgrade-channels.adoc
  modules/update-conditional-updates.adoc
  updating/understanding-the-update-service.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-within-minor.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.10

#40552 BZ: 2036962 - Updating performance addon operator must-gather image info
  modules/cnf-collecting-low-latency-tuning-debugging-data-for-red-hat-support.adoc
Labels: lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40108 BZ2030356: Add priorityclass
  modules/nodes-pods-priority-about.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40549 BZ:2039742 - Adding warning about exec probes
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40526 BZ1669050: Use oc exec instead of oc rsh in Customized HAProxy Router steps
  install_config/router/customized_haproxy_router.adoc
Labels: lgtm, size/S, branch/enterprise-3.11

#40415 OSDOCS-2911: Adding release notes about conditional updates
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10

#39615 OSDOCS-2171: run tcpdump from must gather
  modules/support-collecting-host-network-trace.adoc
  modules/support-network-trace-methods.adoc
  support/gathering-cluster-data.adoc
Labels: Peer Review Needed, size/L, branch/enterprise-4.10

#40577 Issue 40259, fixed incorrect variable for Red Hat OpenShift Cluster Manager
  modules/distr-tracing-document-attributes.adoc
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Needed, Peer Review Done, lgtm, size/XS, branch/enterprise-4.9

#40360 OSDOCS-2171: RN for tcpdump from must-gather
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#40611 [enterprise-4.9] CNV-15340: Relocate content for config cert rotation
  _topic_maps/_topic_map.yml
  modules/virt-troubleshooting-cert-rotation-parameters.adoc
  virt/install/installing-virt-cli.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-certificate-rotation.adoc
Labels: size/XS

#40612 [enterprise-4.8] CNV-15340: Relocate content for config cert rotation
  _topic_maps/_topic_map.yml
  modules/virt-troubleshooting-cert-rotation-parameters.adoc
  virt/install/installing-virt-cli.adoc
  virt/virt-4-8-release-notes.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-certificate-rotation.adoc
Labels: size/S

#40618 [enterprise-4.7] osdocs3148: clearing build errors
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  getting_started/accessing-your-services.adoc
  installing/installing_bare_metal_ipi/ipi-install-configuration-files.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/developer-cli-odo-sample-applications-binary.adoc
  modules/developer-cli-odo-sample-applications-git.adoc
  modules/developer-cli-odo-sample-applications-github.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/dr-scenario-cluster-state-issues.adoc
  modules/migration-direct-volume-migration-and-direct-image-migration.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/nodes-cluster-overcommit-qos-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-qos-about-swap.adoc
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-high-performance-multicast.adoc
  modules/osdk-leader-election-types.adoc
  modules/ossm-auto-route-annotations.adoc
  modules/ossm-auto-route-enable.adoc
  modules/ossm-auto-route.adoc
  modules/serverless-domain-mapping-custom-tls-cert.adoc
  networking/hardware_networks/using-sriov-multicast.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  operators/operator_sdk/osdk-leader-election.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/node-tasks.adoc
  rest_api/images
  rest_api/modules
  rest_api/understanding-api-support-tiers.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/security/serverless-custom-tls-cert-domain-mapping.adoc
  service_mesh/v2x/ossm-config.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: size/XL

#40621 [enterprise-4.6] osdocs3148: clearing build errors
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  getting_started/accessing-your-services.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  migrating_from_ocp_3_to_4/about-mtc-3-4.adoc
  migration_toolkit_for_containers/about-mtc.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/developer-cli-odo-sample-applications-binary.adoc
  modules/developer-cli-odo-sample-applications-git.adoc
  modules/developer-cli-odo-sample-applications-github.adoc
  modules/dr-scenario-cluster-state-issues.adoc
  modules/migration-direct-volume-migration-and-direct-image-migration.adoc
  modules/migration-understanding-data-copy-methods.adoc
  modules/nodes-cluster-overcommit-qos-about.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-qos-about-swap.adoc
  modules/nw-configuring-high-performance-multicast-with-sriov.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-high-performance-multicast.adoc
  modules/osdk-leader-election-types.adoc
  modules/ossm-auto-route-annotations.adoc
  modules/ossm-auto-route-enable.adoc
  modules/ossm-auto-route.adoc
  modules/serverless-domain-mapping-custom-tls-cert.adoc
  networking/hardware_networks/using-sriov-multicast.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  operators/operator_sdk/osdk-leader-election.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/node-tasks.adoc
  rest_api/images
  rest_api/modules
  rest_api/understanding-api-support-tiers.adoc
  serverless/discover/images
  serverless/discover/modules
  serverless/security/serverless-custom-tls-cert-domain-mapping.adoc
  service_mesh/v2x/ossm-config.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: size/XL

#40560 SRVKE-747: Split knative kafka docs into different personas
  _topic_maps/_topic_map.yml
  modules/serverless-install-kafka-odc.adoc
  modules/serverless-kafka-event-delivery.adoc
  modules/serverless-kafka-source-kn.adoc
  modules/serverless-kafka-source-odc.adoc
  modules/serverless-kafka-source-yaml.adoc
  serverless/admin_guide/serverless-cluster-admin-eventing.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/develop/serverless-kafka-developer.adoc
  serverless/develop/serverless-kafka-source.adoc
  serverless/discover/knative-event-sources.adoc
  serverless/knative_eventing/serverless-kafka.adoc
  serverless/security/serverless-kafka-security.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40623 osdocs3148: restoring heading in 4.7
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
Labels: size/S

#40614 CNV-14944: Updating version attributes for 4.10
  modules/virt-document-attributes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.10

#40630 [enterprise-4.6] SRVKE-747: Split knative kafka docs into different personas
  _topic_maps/_topic_map.yml
  modules/serverless-install-kafka-odc.adoc
  modules/serverless-kafka-event-delivery.adoc
  modules/serverless-kafka-source-kn.adoc
  modules/serverless-kafka-source-odc.adoc
  modules/serverless-kafka-source-yaml.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/develop/serverless-kafka-developer.adoc
  serverless/develop/serverless-kafka-source.adoc
  serverless/discover/knative-event-sources.adoc
  serverless/knative_eventing/serverless-kafka.adoc
  serverless/security/serverless-kafka-security.adoc
Labels: size/L

#40245 [enterprise-4.7] BZ1825250: Managing cluster resources
  _topic_maps/_topic_map.yml
  modules/cluster-resources.adoc
  support/managing-cluster-resources.adoc
Labels: size/M

#40584 [MULTIARCH-1494] Ipsec support on IBM Z for 4.10
  modules/nw-operator-cr.adoc
Labels: lgtm, size/S, branch/enterprise-4.10

#40573 Standardize compliance table for OSD/ROSA; add HIPAA
  modules/policy-security-regulation-compliance.adoc
  modules/rosa-policy-security-regulation-compliance.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40555 NE743: document upstream resolvers
  modules/nw-dns-forward.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.10

#40359 RHDEVDOCS 3420 - Show Monitoring target info in UI admin perspective
  _topic_maps/_topic_map.yml
  modules/monitoring-accessing-the-metrics-targets-page.adoc
  modules/monitoring-getting-detailed-information-about-a-target.adoc
  modules/monitoring-searching-and-filtering-metrics-targets.adoc
  monitoring/managing-metrics-targets.adoc
  monitoring/managing-metrics.adoc
Labels: size/L

#40622 Adds 4.9.15 RNs
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.9

#40572 BZ-2017416-2017418: Fixed port list description in the masquerade bin…
  modules/virt-configuring-masquerade-mode-cli.adoc
Labels: size/S, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40416 updating/updating-cluster-within-minor: Replace --force with --clear
  updating/updating-cluster-within-minor.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40337 BZ2020756: Specifying that policyGenerator is a Kustomize plugin
  modules/ztp-generating-ran-policies.adoc
Labels: lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40531 OSDOCS-3161 Add Compliance benchmark column to Supported profiles table
  modules/compliance-supported-profiles.adoc
Labels: lgtm, size/M

#40633 Move uninstall module to installation assemblies
  migrating_from_ocp_3_to_4/installing-3-4.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migrating_from_ocp_3_to_4/troubleshooting-3-4.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  migration_toolkit_for_containers/troubleshooting-mtc.adoc
  modules/migration-uninstalling-mtc-clean-up.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#38248 OADP-72: Configuration
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/configuring-oadp.adoc
  backup_and_restore/application_backup_and_restore/placeholder.adoc
  modules/oadp-self-signed-certificate.adoc
  modules/oadp-setting-resource-limits-and-requests.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#37971 OADP-106: OADP installation
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/installing/modules
  modules/migration-configuring-aws-s3.adoc
  modules/migration-configuring-azure.adoc
  modules/migration-configuring-gcp.adoc
  modules/migration-configuring-mcg.adoc
  modules/migration-migrating-applications-api.adoc
  modules/migration-mtc-cr-manifests.adoc
  modules/migration-rolling-back-migration-cli.adoc
  modules/migration-rolling-back-migration-manually.adoc
  modules/migration-rolling-back-migration-web-console.adoc
  modules/oadp-about-bsl.adoc
  modules/oadp-about-vsl.adoc
  modules/oadp-configuring-default-plug-ins.adoc
  modules/oadp-installing-dpa.adoc
  modules/oadp-installing-operator.adoc
Labels: Peer Review Done, size/XXL, branch/enterprise-4.6, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40610 Adds notes for 4.8.27 release
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.8

#40159 BZ2030784: remove ipam from the host-device CNI plug-in configuration
  modules/nw-multus-host-device-object.adoc
Labels: lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40679 BZ2028380: Removed Important block
  installing/installing-mirroring-installation-images.adoc
Labels: lgtm, size/XS

#39726 BZ 1998580, BZ 2006334 and BZ 2007529 documentation fixes.
  images/210_OpenShift_Baremetal_IPI_Deployment_updates_0122_1.png
  images/210_OpenShift_Baremetal_IPI_Deployment_updates_0122_2.png
  installing/installing_bare_metal_ipi/ipi-install-overview.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configure-network-components-to-run-on-the-control-plane.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-out-of-band-management.adoc
  modules/ipi-install-required-data-for-installation.adoc
  modules/ipi-install-validation-checklist-for-nodes.adoc
Labels: size/L, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40658 Removing files no longer relevant for 4.10
  modules/update-preparing-ack.adoc
  modules/update-preparing-evaluate-alerts.adoc
  modules/update-preparing-evaluate-apirequestcount-workloads.adoc
  modules/update-preparing-evaluate-apirequestcount.adoc
  modules/update-preparing-list.adoc
  modules/update-preparing-migrate.adoc
  updating/updating-cluster-prepare.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.10

#40660 Add subs=attributes for FeatureName in TP&DP modules
  modules/deprecated-feature.adoc
  modules/technology-preview.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#40670 Change the representation of a variable
  modules/cluster-resources.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10
