Repository openshift/openshift-docs, pull requests merged in 2022-11, with the labels that each got.

#52185 OCPBUGS#2788: Adding DHCP:flase to static IP snippet
  modules/virt-example-nmstate-IP-management.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-important, jira/invalid-bug, branch/enterprise-4.12

#51191 Adds import mode to images new features in the 4.12 release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12

#51669 CNV-16413: Remove TP note from critical alerts
  virt/logging_events_monitoring/virt-virtualization-alerts.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11, branch/enterprise-4.12

#52144 OCPBUGS-2524 correcting version numbers and adding variable substitution
  modules/cnf-checking-numa-aware-scheduler-logs.adoc
  modules/cnf-deploying-the-numa-aware-scheduler.adoc
  modules/cnf-installing-numa-resources-operator-cli.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.11, branch/enterprise-4.12

#52358 [enterprise-4.12] GH#5117 Updated cluster-logging-loki.adoc
  .s2i/httpd-cfg/01-commercial.conf
  modules/cluster-logging-loki-deploy.adoc
Labels: size/S

#52339 RHDEVDOCS-4346 - 1 character correction
  modules/cluster-logging-collector-log-forwarding-about.adoc
Labels: lgtm, size/XS, dev-tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52095 Build script investigation
  build_for_portal.py
Labels: size/L

#51637 OCPBUGS#2226: ptpSchedulingPriority value updated to 10
  modules/cnf-configuring-fifo-priority-scheduling-for-ptp.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  networking/using-ptp.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#51678 OSDOCS-3520: Adding steps to deploy with a GCP Marketplace image
  installing/installing_gcp/installing-gcp-customizations.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12

#52376 Remove type hints from build_for_portal.py
  build_for_portal.py
Labels: size/XS

#52378 Remove final hint of type hints from build_for_portal.py
  build_for_portal.py
Labels: size/XS

#52375 Reverts accidental redirect update
  .s2i/httpd-cfg/01-commercial.conf
Labels: peer-review-done, size/XS, branch/enterprise-4.10

#52374 Reverts accidental redirect update
  .s2i/httpd-cfg/01-commercial.conf
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#52383 [enterprise-4.11] GH#5117 Updated cluster-logging-loki.adoc
  modules/cluster-logging-loki-deploy.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11

#52098 CNV-21872: Removed resolved known issues from 4.11 release notes
  virt/virt-4-11-release-notes.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.11

#50187 CNV-20429: Updated latency check documentation
  modules/virt-measuring-latency-vm-secondary-network.adoc
Labels: size/L, CNV, branch/enterprise-4.12

#49354 CNV-17636: Moved the service section to separate assembly
  _topic_maps/_topic_map.yml
  modules/virt-about-services.adoc
  modules/virt-creating-a-service-from-a-virtual-machine.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
  virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.adoc
Labels: size/L, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52326 OSDOCS-3889_FIX remove broken footnote and omitted caps
  modules/installation-aws-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress

#52399 OCPBUGS#2226: ptpSchedulingPriority value updated to 10
  modules/cnf-configuring-fifo-priority-scheduling-for-ptp.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  networking/using-ptp.adoc
Labels: size/S, branch/enterprise-4.9, merge-review-in-progress

#52349 [OSDOCS-4413]: AWS STS uses regional endpoints (4.12 RN)
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#52381 [OSDOCS-4405]: ccoctl gcp delete specify dir param (4.12 RN)
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#52260 OSDOCS-4387: adds zstream update for 4.11.12
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/M

#52396 RHDEVDOCS-4602 `tkn-pac` CLI installation instructions need to use only productized artifacts
  modules/op-installing-pipelines-as-code-cli.adoc
Labels: size/M

#51966 Updates the Web Console release notes to make notes for each perspective clear
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12

#52145 BZ2093811: Remove obsolete Custom boot source module and links
  modules/virt-creating-a-custom-image-boot-source-web.adoc
  virt/virtual_machines/virtual_disks/virt-creating-and-using-boot-sources.adoc
Labels: peer-review-done, size/M, CNV, branch/enterprise-4.11, branch/enterprise-4.12

#52408 [enterprise-4.8] CNV-17636: Moved the service section to separate assembly
  _topic_maps/_topic_map.yml
  modules/virt-about-services.adoc
  modules/virt-creating-a-service-from-a-virtual-machine.adoc
  virt/virt-4-8-release-notes.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
  virt/virtual_machines/vm_networking/virt-using-the-default-pod-network-with-virt.adoc
Labels: size/L

#51600 BZ2128785: RN known issue OVN-Kubernetes cannot handle large number of NodePort services
  virt/virt-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.11

#52236 OCPBUGS#1989 - removing authfile flag
  modules/mirror-registry-localhost.adoc
  modules/mirror-registry-remote.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#52394 [enterprise-4.9] RHDEVDOCS-3763 - Added custom properties
  cicd/gitops/argo-cd-custom-resource-properties.adoc
  modules/gitops-argo-cd-notification.adoc
  modules/gitops-argo-cd-properties.adoc
  modules/gitops-repo-server-properties.adoc
Labels: size/L

#51957 GH#51954 - Adding affinity rules to pod limitation documentation
  modules/nw-metallb-operator-limit-speaker-to-nodes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52234 GH#52123 Initial Planning Configuration to resources rosa-sts-aws-prereqs
  modules/rosa-aws-provisioned.adoc
  rosa_planning/rosa-sts-aws-prereqs.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52412 [enterprise-4.11] OSDOCS-4339: Added gcp to platform parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#52430 [enterprise-4.10] OSDOCS-4339: Added gcp to platform parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#52431 OSDOCS-4339: Added gcp to platform parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#52433 OSDOCS-4474: Removed unsupported platform references
  modules/installation-configuration-parameters.adoc
Labels: size/XS, branch/enterprise-4.9

#52432 [enterprise-4.8] OSDOCS-4339: Added gcp to platform parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#52434 OSDOCS-4475: Removed unsupported platform and GCP param
  modules/installation-configuration-parameters.adoc
Labels: size/XS, branch/enterprise-4.10

#52435 OSDOCS-4476: Removed unsupported GCP parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS, branch/enterprise-4.11

#50778 Compliance Operator v0.1.57 release notes and enhancements added
  modules/compliance-applying-resource-requests-and-limits.adoc
  modules/compliance-custom-node-pools.adoc
  modules/compliance-evaluate-kubeletconfig-rules.adoc
  modules/compliance-increasing-operator-limits.adoc
  modules/compliance-kubeletconfig-sub-pool-remediation.adoc
  modules/compliance-priorityclass.adoc
  modules/compliance-scansetting-cr.adoc
  modules/compliance-scheduling-pods-with-resource-requests.adoc
  modules/compliance-supported-profiles.adoc
  modules/operator-resource-constraints.adoc
  security/compliance_operator/compliance-operator-advanced.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
  security/compliance_operator/compliance-operator-remediation.adoc
  security/compliance_operator/compliance-operator-troubleshooting.adoc
  security/compliance_operator/compliance-scans.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#48673 Created a sub-dir for Agent-based Installer with a proposed TOC
  _topic_maps/_topic_map.yml
  images/agent-based-installer-workflow.png
  installing/installing_with_agent_based_installer/attributes
  installing/installing_with_agent_based_installer/images
  installing/installing_with_agent_based_installer/installing-with-agent-based-installer.adoc
  installing/installing_with_agent_based_installer/modules
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  installing/installing_with_agent_based_installer/snippets
  modules/installation-bare-metal-agent-installer-config-yaml.adoc
  modules/installing-ocp-agent.adoc
  modules/sample-ztp-custom-resources.adoc
  modules/understanding-agent-install.adoc
  modules/validations-before-agent-iso-creation.adoc
Labels: lgtm, size/XL, branch/enterprise-4.12, merge-review-in-progress

#52293 Bug OCPBUGS-2886: Add note about unnecessary load-balancer setting on CP
  modules/installation-osp-setting-cloud-provider-options.adoc
Labels: peer-review-done, lgtm, size/XS, bugzilla/valid-bug, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, jira/valid-bug, branch/enterprise-4.12

#52439 GH52417: Add AWS link
  modules/virt-hardware-os-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52319 OSDOCS-4365: Added RN for enabling a feature set at install
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#51569 BZ2107507: Added 4.11-specific note about checkup permissions
  modules/virt-about-cluster-checkup-framework.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.11

#52308 RNs-4.9.51 Added with Bug Fix & Security Update
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#52021 RHDEVDOCS-4282 - Doc: Pipelines Usability & Customer Happiness
  images/op-pipeline-details1.png
  images/op_pipeline_run2.png
  images/op_pipeline_topology1.png
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-starting-pipelines-from-pipelines-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, qe-approved, branch/enterprise-4.12

#52380 [OSDOCS-4464]: ccoctl gcp delete specify dir param
  modules/cco-ccoctl-deleting-sts-resources.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52451 adding microshift to the main distro map
  _distro_map.yml
Labels: size/S

#52382 [enterprise 4.10] TELCODOCS-380-day0
  modules/sandboxed-containers-building-blocks.adoc
  modules/sandboxed-containers-common-terms.adoc
  modules/sandboxed-containers-deploying-osc-with-other-ocp-components.adoc
  modules/sandboxed-containers-rhcos-extensions.adoc
  sandboxed_containers/understanding-sandboxed-containers.adoc
Labels: size/M

#52188 TELCODOCS-972 - update ptpClockThreshold description
  modules/cnf-configuring-the-ptp-fast-event-publisher.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  modules/ztp-configuring-ptp-fast-events.adoc
Labels: peer-review-done, lgtm, size/S, telco, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52391 adds description for targetPort
  modules/nw-creating-a-route.adoc
Labels: size/XS

#52268 BZ#2104394: removing unnecessary steps
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#44823 BZ#2065695: PAO - cnf-tests Documentation of PAO should not cover all cnf-tests as only the latency launchers are supported
  _topic_maps/_topic_map.yml
  modules/cnf-latency-tests-discovery-mode.adoc
  modules/cnf-measuring-latency.adoc
  modules/cnf-performing-end-to-end-tests-disconnected-mode.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-performing-end-to-end-tests-junit-test-output.adoc
  modules/cnf-performing-end-to-end-tests-running-cyclictest.adoc
  modules/cnf-performing-end-to-end-tests-running-hwlatdetect.adoc
  modules/cnf-performing-end-to-end-tests-running-in-single-node-cluster.adoc
  modules/cnf-performing-end-to-end-tests-running-oslat.adoc
  modules/cnf-performing-end-to-end-tests-running-the-tests.adoc
  modules/cnf-performing-end-to-end-tests-test-failure-report.adoc
  modules/cnf-performing-end-to-end-tests-troubleshooting.adoc
  scalability_and_performance/cnf-low-latency-tuning.adoc
  scalability_and_performance/cnf-performing-platform-verification-latency-tests.adoc
Labels: peer-review-done, size/XXL, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed

#51706 OSDOCS-3520: RN for GCP Marketplace support
  release_notes/ocp-4-12-release-notes.adoc
Labels: size/S, qe-approved, branch/enterprise-4.12

#52470 CNV-20429: Peer review edits for latency check documentation
  modules/virt-measuring-latency-vm-secondary-network.adoc
Labels: size/XS, CNV, branch/enterprise-4.12

#50974 BZ2107507: Added note about checkup permissions
  modules/virt-about-cluster-checkup-framework.adoc
Labels: peer-review-done, lgtm, size/S, CNV, branch/enterprise-4.12

#52478 [enterprise-4.12] adding microshift to the main distro map
  _distro_map.yml
Labels: size/S

#50054 USHIFT-267: stubs for MicroShift product documentation
  .travis.yml
  _attributes/attributes-microshift.adoc
  _topic_maps/_topic_map_ms.yml
  cli_reference/index.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  cli_reference/openshift_cli/managing-cli-profiles.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  microshift_architecture/attributes
  microshift_architecture/images
  microshift_architecture/microshift-apis.adoc
  microshift_architecture/microshift-understanding.adoc
  microshift_architecture/modules
  microshift_architecture/snippets
  microshift_install/attributes
  microshift_install/images
  microshift_install/microshift-install-rhel-for-edge.adoc
  microshift_install/microshift-install-rpm.adoc
  microshift_install/modules
  microshift_install/snippets
  microshift_support/attributes
  microshift_support/images
  microshift_support/microshift-version.adoc
  microshift_support/modules
  microshift_support/snippets
  modules/cli-about-cli.adoc
  modules/cli-using-cli.adoc
  welcome/index.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12

#52481 [enterprise-4.12] microshift: initial structure
  .travis.yml
  _attributes/attributes-microshift.adoc
  _topic_maps/_topic_map_ms.yml
  cli_reference/index.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  cli_reference/openshift_cli/managing-cli-profiles.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  microshift_architecture/attributes
  microshift_architecture/images
  microshift_architecture/microshift-apis.adoc
  microshift_architecture/microshift-understanding.adoc
  microshift_architecture/modules
  microshift_architecture/snippets
  microshift_install/attributes
  microshift_install/images
  microshift_install/microshift-install-rhel-for-edge.adoc
  microshift_install/microshift-install-rpm.adoc
  microshift_install/modules
  microshift_install/snippets
  microshift_support/attributes
  microshift_support/images
  microshift_support/microshift-version.adoc
  microshift_support/modules
  microshift_support/snippets
  modules/cli-about-cli.adoc
  modules/cli-using-cli.adoc
  welcome/index.adoc
Labels: size/L

#52256 OCPBUGS#2283: Added new `allow-from-kube-apiserver-operator` policy
  modules/nw-networkpolicy-multitenant-isolation.adoc
  modules/nw-networkpolicy-project-defaults.adoc
Labels: peer-review-done, size/M

#52485 adds description for targetPort
  modules/nw-creating-a-route.adoc
Labels: size/XS

#52487 adds dscription for targetPort
  modules/nw-creating-a-route.adoc
Labels: size/XS

#51338 RHDEVDOCS-4497:- Release note for doc: Improve awareness of resource/project limits and quota issues for developers
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.12

#51733 RHDEVDOCS-4410 - Doc: Resource type updates-Import from Git & deploy image
  modules/odc-deploying-java-applications.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.12

#52493 [OCPBUGS-2886] Add note about unnecessary load-balancer settting on CP
  modules/installation-osp-setting-cloud-provider-options.adoc
Labels: size/XS, branch/enterprise-4.9, jira/invalid-bug

#52178 OSDOCS-4365: Added ability to enable a feature set during install
  modules/installation-configuration-parameters.adoc
  modules/nodes-cluster-enabling-features-install.adoc
  nodes/clusters/nodes-cluster-enabling-features.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#48671 RHDEVDOCS-4169+4392: Tekton Hub and auth changes for Pipelines 1.8
  cicd/pipelines/using-tekton-hub-with-openshift-pipelines.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-and-deploying-tekton-hub-on-an-openshift-cluster.adoc
  modules/op-installing-tekton-hub-with-login-and-rating.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-manually-refreshing-the-catalog-in-tekton-hub.adoc
  modules/op-opting-out-of-tekton-hub-in-the-developer-perspective.adoc
  modules/op-setting-a-cron-job-for-refreshing-catalog-in-tekton-hub.adoc
  modules/op-using-a-custom-database-in-tekton-hub.adoc
Labels: peer-review-done, lgtm, size/XL, dev-tools, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12

#51612 TELCODOCS-644/645: Per-Core Runtime Tuning of power states - CRI-O and PAO/NTO
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-understanding-workload-hints.adoc
  modules/ztp-du-bios-config-reference.adoc
  scalability_and_performance/cnf-low-latency-tuning.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#51705 vSphere Windows Server 2022 support for WMCO 3.x
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.8

#52464 TELCODOCS-972 - update ptpClockThreshold description - enterprise-4.9 manual CP
  modules/cnf-configuring-the-ptp-fast-event-publisher.adoc
Labels: size/S, branch/enterprise-4.9, merge-review-in-progress

#52509 Revert "vSphere Windows Server 2022 support for WMCO 3.x"
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: size/S

#52515 vSphere Windows Server 2022 support for WMCO 3.x Take 2
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: size/S

#50943 OSDOCS-4151: Adding section on using custom machine types
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  modules/installation-using-gcp-custom-machine-types.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#51418 OCPBUGS#2006: Added custom tags to example
  modules/machineset-yaml-azure.adoc
  storage/container_storage_interface/persistent-storage-csi-aws-efs.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52480 RHDEVDOCS-3771 - Fluentd to collector
  modules/cluster-logging-manual-rollout-rolling.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52542 Revert "vSphere Windows Server 2022 support for WMCO 3.x Take 2"
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: size/S

#52397 [AWS Installation] Fixes typo in the permissions for the IAM user
  modules/installation-aws-permissions.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12

#52213 CFE-473: Add information about profiling data lifetime
  modules/node-observability-run-profiling-query.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#49778 OSDOCS-3546: Egress firewall supports logging
  _topic_maps/_topic_map.yml
  logging/cluster-logging-external.adoc
  modules/nw-networkpolicy-audit-concept.adoc
  modules/nw-networkpolicy-audit-configure.adoc
  modules/nw-networkpolicy-audit-disable.adoc
  modules/nw-networkpolicy-audit-enable.adoc
  networking/network_policy/creating-network-policy.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/logging-network-policy.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#52462 BZ#2115606: adding sudo to command
  modules/installation-user-infra-machines-advanced.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#50264 OSDOCS-3801: Add OVN-Kubernetes internal subnet configuration
  modules/nw-operator-cr.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#52502 USHIFT-267: address comments from #50054
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  microshift_architecture/microshift-understanding.adoc
  microshift_support/attributes
  microshift_support/images
  microshift_support/microshift-version.adoc
  microshift_support/modules
  microshift_support/snippets
  modules/microshift-version-api.adoc
  modules/microshift-version-command-line.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12

#52548 Convert Feature Set Verification steps to snippet
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
  modules/nodes-cluster-enabling-features-install.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52441 OCPBUGS3004: updating step_threshold from 0.0 to 2.0 across doc set
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  modules/sno-du-configuring-ptp.adoc
Labels: peer-review-done, lgtm, size/XS, telco, jira/invalid-bug, merge-review-needed

#52249 document TLS port 6183 for redfish installation
  modules/ipi-install-network-requirements.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed

#52571 [enterprise-4.10] Convert Feature Set Verification steps to snippet
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: size/L

#52570 [enterprise-4.9] Convert Feature Set Verification steps to snippet
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: size/L

#52569 [enterprise-4.8] Convert Feature Set Verification steps to snippet
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: size/L

#52580 [enterprise-4.11] Convert Feature Set Verification steps to snippet
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: size/L

#52212 RHDEVDOCS-4111 - Added deployment history details
  modules/go-health-monitoring.adoc
Labels: size/XS

#52589 [enterprise-4.9] OSDOCS-4151: Adding section on using custom machine types
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  modules/installation-using-gcp-custom-machine-types.adoc
Labels: size/M

#51736 added prerequisite to enable marketplace
  applications/connecting_applications_to_services/installing-sbo.adoc
  cicd/gitops/installing-openshift-gitops.adoc
  cicd/pipelines/installing-pipelines.adoc
  modules/installing-gitops-operator-in-web-console.adoc
  modules/op-installing-sbo-operator-using-the-web-console.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52572 Change the chroot /host step for accuracy
  modules/backup-etcd.adoc
  modules/containers-signature-verify-enable.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/nodes-nodes-rebooting-gracefully.adoc
  modules/persistent-storage-local-removing-devices.adoc
  modules/registry-accessing-directly.adoc
  modules/restore-replace-crashlooping-etcd-member.adoc
  snippets/nodes-cluster-enabling-features-verification.adoc
Labels: size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52486 TELCODOCS-644/645: Per-core runtime tuning of power states RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, telco, merge-review-needed

#52609 [enterprise-4.8] OSDOCS-4151: Adding section on using custom machine types
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  modules/installation-using-gcp-custom-machine-types.adoc
Labels: size/M

#52608 Updating the Compliance Operator supported profiles
  modules/compliance-supported-profiles.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#51308 Adds known issue to 4.12 regarding image indexes and oc adm catalog a…
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#52629 [enterprise-4.12] Adds important admonition when running oc adm catalog mirror
  modules/installation-mirror-repository.adoc
  modules/olm-mirroring-catalog.adoc
Labels: size/S, branch/enterprise-4.12

#51311 Adds known issue for oc adm catalog and oc image mirror command
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, merge-review-in-progress

#52544 vSphere Windows Server 2022 support for WMCO 3.x Take 3
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: size/S, branch/enterprise-4.8

#51603 adds bug fixes and feature to 3.1.2 rel notes
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: peer-review-done, lgtm, size/S

#52630 [enterprise-4.11] Adds important admonition and note to disconnected installations
  modules/installation-mirror-repository.adoc
  modules/olm-mirroring-catalog.adoc
Labels: size/S, branch/enterprise-4.11

#52631 [enterprise-4.10] Adds important admonition to disconnected installations
  modules/installation-mirror-repository.adoc
  modules/olm-mirroring-catalog.adoc
Labels: size/S, branch/enterprise-4.10

#52621 OCPBUGS#3213: adds api version to agent-config file
  modules/installing-ocp-agent.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress

#52555 RNs-4.10.40 Added with Bug Fix Update
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, merge-review-in-progress

#52492 Telcodocs 1016 411 RN Adding Release note for bug 2050824
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.11, merge-review-in-progress

#52491 Replacing PR 52419 - Documenting 2050824 in main body of text where deemed relevant
  modules/nw-metallb-example-bgppeer.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#52620 removes repeat content and correct replica
  modules/installation-bare-metal-agent-installer-config-yaml.adoc
  modules/installing-ocp-agent.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress

#52628 BZ-2061452: Removing removed annotation in favor of using priority class
  modules/psap-special-resource-operator-using-configmaps.adoc
  modules/psap-special-resource-operator-using-crd.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52632 Replacing removed flag with scheduler profile config
  modules/nodes-custom-scheduler-deploying.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#52642 [enterprise-4.10] BZ-2061452: Removing removed annotation in favor of using priority class
  modules/psap-special-resource-operator-using-configmaps.adoc
Labels: size/S

#52643 [enterprise-4.9] BZ-2061452: Removing removed annotation in favor of using priority class
  modules/psap-special-resource-operator-using-configmaps.adoc
Labels: size/XS

#52529 Fix typo
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#52617 OSDOCS-4506: Updated GCP marketplace doc with missing offers
  _attributes/common-attributes.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12

#52186 [OSDOCS-4013] added suggested sentence to change management policy info
  modules/policy-change-management.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12

#51302 [OSDOCS-3974]: new node tuning topic for hosted control planes
  modules/advanced-node-tuning-hosted-cluster.adoc
  modules/node-tuning-hosted-cluster.adoc
  scalability_and_performance/using-node-tuning-operator.adoc
Labels: peer-review-done, size/L

#51726 OSDOCS-4352: Updated cluster-wide proxy documentation
  modules/configuring-a-proxy-after-installation.adoc
  modules/configuring-a-proxy-during-installation.adoc
  modules/nw-proxy-remove.adoc
  modules/nw-rosa-proxy-remove-cli.adoc
  networking/configuring-cluster-wide-proxy.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12

#52530 RHDEVDOVS-4440 - Logging Z-Stream RNs (5.3.13, 5.4.8, 5.5.4)
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.3.13.adoc
  modules/cluster-logging-rn-5.4.8.adoc
  modules/cluster-logging-rn-5.5.4.adoc
Labels: size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#51036 kubelet is not able to convert TLS Security profile 1.0 to 1.1 for old, 1.3 to 1.2 for intermediate.
  modules/tls-profiles-kubelet-configuring.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#50631 OCP BUGS-1585: Adding how to find workloads causing pod security viol…
  authentication/understanding-and-managing-pod-security-admission.adoc
  modules/security-context-constraints-psa-alert-eval.adoc
  modules/security-context-constraints-psa-rectifying.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12

#52527 RHDEVDOCS-4583 Document changes in installation and upgrade channels
  modules/op-installing-pipelines-operator-in-web-console.adoc
  modules/op-release-notes-1-8.adoc
Labels: size/S, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12

#52551 OSDOCS-4469: Adds notes for 4.11.13 release
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11

#52479 GH#52440: attribute switch
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#47461 BZ-2099319: Adding option to perform rolling node restart
  authentication/bound-service-account-tokens.adoc
  modules/bound-sa-tokens-configuring.adoc
Labels: lgtm, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52684 [enterprise-4.8] Convert from KCS (L): Infrastructure Nodes in OpenShift 4
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/machine-user-provisioned-limitations.adoc
  nodes/nodes/nodes-nodes-creating-infrastructure-nodes.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/L

#52685 [enterprise-4.9] Convert from KCS (L): Infrastructure Nodes in OpenShift 4
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/machine-user-provisioned-limitations.adoc
  nodes/nodes/nodes-nodes-creating-infrastructure-nodes.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/L

#52691 [enterprise-4.11] Convert from KCS (L): Infrastructure Nodes in OpenShift 4
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/machine-user-provisioned-limitations.adoc
  nodes/nodes/nodes-nodes-creating-infrastructure-nodes.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/L

#52692 [enterprise-4.12] Convert from KCS (L): Infrastructure Nodes in OpenShift 4
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/machine-user-provisioned-limitations.adoc
  nodes/nodes/nodes-nodes-creating-infrastructure-nodes.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/L

#52488 Changed Atom reference to VS Code
  contributing_to_docs/tools_and_setup.adoc
Labels: peer-review-done, size/XS

#52690 [enterprise-4.10] Convert from KCS (L): Infrastructure Nodes in OpenShift 4
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  modules/infrastructure-components.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-monitoring.adoc
  modules/infrastructure-moving-registry.adoc
  modules/infrastructure-moving-router.adoc
  modules/machine-user-provisioned-limitations.adoc
  nodes/nodes/nodes-nodes-creating-infrastructure-nodes.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/L

#52528 OCPBUGS-3313: Change the label name
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, bugzilla/valid-bug, qe-approved, jira/valid-bug, branch/enterprise-4.12, merge-review-in-progress

#52697 adding customer information to ROSA docs
  modules/rosa-policy-change-management.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12

#51574 OCPBUGS-2049: Adding known issue about Nutanix install to 4.12 RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, branch/enterprise-4.12

#52654 OSDOCS-4503: Remove "Limited Availability" in ROSA RHODS
  modules/rosa-rhods.adoc
Labels: peer-review-done, lgtm, size/XS

#52638 GH#52610 updating deprecated parameter name
  modules/how-to-plan-your-environment-according-to-application-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52110 RNs-0.1.32 Added with Bug Fix
  security/file_integrity_operator/file-integrity-operator-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52718 RHDEVDOVS-4440 - Logging Z-Stream RNs (5.5.4)
  logging/cluster-logging-release-notes.adoc
Labels: size/XS, dev-tools, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52437 RHDEVDOCS-4661 - Added 1.6.2, 1.4.13 1nd 1.5.7 release notes
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-4-13.adoc
  modules/gitops-release-notes-1-5-7.adoc
  modules/gitops-release-notes-1-6-2.adoc
Labels: size/M

#51171 OSDOCS-3940 Enabling GCP Shared VPC IPI installation
  _topic_maps/_topic_map.yml
  installing/installing_gcp/installing-gcp-shared-vpc.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-permissions.adoc
  modules/installation-gcp-shared-vpc-config.adoc
  modules/installation-gcp-shared-vpc-ingress.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-user-infra-generate.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52616 OSDOCS-4472:adds zstream update
  release_notes/ocp-4-7-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed

#52504 OSDOCS-4473:updates zstream 4.6.62
  release_notes/ocp-4-6-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#52586 CFE-640: Add the EDNS resource limitation details
  modules/nw-external-dns-operator-logs.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12

#51892 OSDOCS-3937: Configure HAProxy reload interval
  modules/configuring-haproxy-interval.adoc
  modules/ingress-liveness-readiness-startup-probes.adoc
  modules/router-performance-optimizations.adoc
  post_installation_configuration/network-configuration.adoc
  scalability_and_performance/routing-optimization.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52695 Adds 129 update for OMR
  modules/mirror-registry-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, ok-to-merge, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#52587 OCPBUGS 3004-49 Updating step_threshold for 49
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/sno-du-configuring-ptp.adoc
Labels: size/XS, telco, branch/enterprise-4.9, merge-review-needed

#52711 OSDOCS-4533: CIT Remove xrefs in module and clean up
  modules/osdk-common-prereqs.adoc
  operators/operator_sdk/ansible/osdk-ansible-quickstart.adoc
  operators/operator_sdk/ansible/osdk-ansible-tutorial.adoc
  operators/operator_sdk/golang/osdk-golang-quickstart.adoc
  operators/operator_sdk/golang/osdk-golang-tutorial.adoc
  operators/operator_sdk/helm/osdk-helm-quickstart.adoc
  operators/operator_sdk/helm/osdk-helm-tutorial.adoc
  operators/operator_sdk/helm/osdk-hybrid-helm.adoc
  operators/operator_sdk/java/osdk-java-quickstart.adoc
  operators/operator_sdk/java/osdk-java-tutorial.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12

#52741 [enterprise-4.12]OSDOCS-3937: Configure HAProxy reload interval
  modules/configuring-haproxy-interval.adoc
  modules/ingress-liveness-readiness-startup-probes.adoc
  modules/router-performance-optimizations.adoc
  post_installation_configuration/network-configuration.adoc
  scalability_and_performance/routing-optimization.adoc
Labels: size/L

#52393 BZ1957067: Explain the route domain configuration
  modules/nw-creating-a-route.adoc
  modules/nw-ingress-configuring-application-domain.adoc
  networking/routes/route-configuration.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#52749 [enterprise-4.10]BZ1957067: Explain the route domain configuration
  modules/nw-creating-a-route.adoc
  modules/nw-ingress-configuring-application-domain.adoc
  networking/routes/route-configuration.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed

#52748 [enterprise-4.9]BZ1957067: Explain the route domain configuration
  modules/nw-creating-a-route.adoc
  modules/nw-ingress-configuring-application-domain.adoc
  networking/routes/route-configuration.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed
