Repository openshift/openshift-docs, pull requests merged in 2022-07, with the labels that each got.

#47040 BZ-2097748 creating the initial PR for this BZ
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  modules/dr-restoring-cluster-state.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#45298 OSDOCS3023: Updating clusters overview
  _topic_maps/_topic_map.yml
  updating/index.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6

#46106 OSDOCS-3676: Arm support for disconnected install
  modules/installation-mirror-repository.adoc
  modules/olm-mirroring-catalog-airgapped.adoc
  modules/olm-mirroring-catalog-colocated.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11

#47348 [SRVCOM-1918] Update instances of drop-down to list
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/serverless-connect-sink-source-odc.adoc
  modules/serverless-create-channel-odc.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-channel-admin-web-console.adoc
  modules/serverless-creating-subscriptions-odc.adoc
  modules/serverless-domain-mapping-odc-developer.adoc
  modules/serverless-installing-cli-web-console.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47353 [enterprise-4.8] [SRVCOM-1918] Update instances of drop-down to list
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/serverless-connect-sink-source-odc.adoc
  modules/serverless-create-channel-odc.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-channel-admin-web-console.adoc
  modules/serverless-creating-subscriptions-odc.adoc
  modules/serverless-installing-cli-web-console.adoc
Labels: size/S

#47354 [enterprise-4.7] [SRVCOM-1918] Update instances of drop-down to list
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/serverless-connect-sink-source-odc.adoc
  modules/serverless-create-channel-odc.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-channel-admin-web-console.adoc
  modules/serverless-creating-subscriptions-odc.adoc
  modules/serverless-installing-cli-web-console.adoc
Labels: size/S

#47355 [enterprise-4.6] [SRVCOM-1918] Update instances of drop-down to list
  modules/olm-deleting-operators-from-a-cluster-using-web-console.adoc
  modules/serverless-connect-sink-source-odc.adoc
  modules/serverless-create-channel-odc.adoc
  modules/serverless-create-trigger-odc.adoc
  modules/serverless-creating-subscriptions-odc.adoc
  modules/serverless-installing-cli-web-console.adoc
Labels: size/S

#47357 This PR adds the .vscode folder to git ignore
  .gitignore
Labels: Peer Review Done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#46908 BZ-2093995: Add content of creating type: kubernetes.io/service-account-token secret
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-creating-basic.adoc
  modules/nodes-pods-secrets-creating-docker.adoc
  modules/nodes-pods-secrets-creating-opaque.adoc
  modules/nodes-pods-secrets-creating-sa.adoc
  modules/nodes-pods-secrets-creating-ssh.adoc
  modules/nodes-pods-secrets-creating-tls.adoc
  modules/nodes-pods-secrets-creating.adoc
  nodes/pods/nodes-pods-secrets.adoc
Labels: size/XL, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47366 [enterprise-4.6] BZ-2093995: Add content of creating type: kubernetes io/service-account-token secret
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-creating-basic.adoc
  modules/nodes-pods-secrets-creating-docker.adoc
  modules/nodes-pods-secrets-creating-opaque.adoc
  modules/nodes-pods-secrets-creating-sa.adoc
  modules/nodes-pods-secrets-creating-ssh.adoc
  modules/nodes-pods-secrets-creating-tls.adoc
  modules/nodes-pods-secrets-creating.adoc
  nodes/pods/nodes-pods-secrets.adoc
Labels: size/XL

#47373 Fixed spacing to kick off docs build
  modules/nodes-pods-secrets-about.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47284 "single-node OpenShift" - Adding {sno} variables and updating existing incorrect references
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  installing/installing-preparing.adoc
  modules/cnf-du-configuring-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/cnf-du-partitioning-management-workloads.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/install-sno-about-installing-on-a-single-node.adoc
  modules/install-sno-generating-the-discovery-iso-manually.adoc
  modules/nodes-nodes-rebooting-gracefully.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/osdk-ha-sno-api.adoc
  modules/sno-du-applying-the-distributed-unit-configuration-to-sno.adoc
  modules/sno-du-applying-the-extra-installation-manifests.adoc
  modules/sno-du-configuring-the-distributed-units.adoc
  modules/sno-du-enabling-workload-partitioning.adoc
  modules/virt-about-vm-templates.adoc
  modules/ztp-about-ztp-and-distributed-units-on-single-node-openshift-clusters.adoc
  modules/ztp-ai-install-ocp-clusters-on-bare-metal.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  modules/ztp-single-node-clusters.adoc
  modules/ztp-ztp-building-blocks.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  operators/operator_sdk/osdk-ha-sno.adoc
  scalability_and_performance/sno-du-enabling-workload-partitioning-on-single-node-openshift.adoc
  scalability_and_performance/ztp-configuring-single-node-cluster-deployment-during-installation.adoc
  updating/index.adoc
  updating/preparing-eus-eus-upgrade.adoc
  virt/install/preparing-cluster-for-virt.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10, branch/enterprise-4.11

#46559 RHDEVDOCS-3824 - Added setting up argo cd instance
  _topic_maps/_topic_map.yml
  cicd/gitops/setting-up-argocd-instance.adoc
  modules/gitops-argo-cd-installation.adoc
  modules/gitops-deploy-resources-different-namespaces.adoc
  modules/gitops-enable-replicas-for-argo-cd-server.adoc
Labels: lgtm, size/L, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#47285 BZ2035855: Changes the default container_heap_percentage value
  using_images/other_images/jenkins_slaves.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-3.11

#47225 BZ#2094901: Adding note for random master pick
  modules/support-gather-data.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#44881 [enterprise-4.7] Updating BZ-1903943-4.7
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.7

#47394 [enterprise-4.9 cherrypick] Adding sno variables and updating existing incorrect references
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  installing/installing-preparing.adoc
  modules/cnf-du-configuring-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/cnf-du-partitioning-management-workloads.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/install-sno-about-installing-on-a-single-node.adoc
  modules/nodes-nodes-rebooting-gracefully.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/osdk-ha-sno-api.adoc
  modules/sno-du-applying-the-distributed-unit-configuration-to-sno.adoc
  modules/sno-du-applying-the-extra-installation-manifests.adoc
  modules/sno-du-configuring-the-distributed-units.adoc
  modules/sno-du-enabling-workload-partitioning.adoc
  modules/ztp-about-ztp-and-distributed-units-on-single-node-openshift-clusters.adoc
  modules/ztp-ai-install-ocp-clusters-on-bare-metal.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  modules/ztp-single-node-clusters.adoc
  modules/ztp-ztp-building-blocks.adoc
  operators/operator_sdk/osdk-ha-sno.adoc
  scalability_and_performance/sno-du-enabling-workload-partitioning-on-single-node-openshift.adoc
  scalability_and_performance/ztp-configuring-single-node-cluster-deployment-during-installation.adoc
  updating/index.adoc
  updating/preparing-eus-eus-upgrade.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/L

#47395 [enterprise-4.10 cherrypick] Adding sno variables and updating existing incorrect references
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  installing/installing-preparing.adoc
  modules/cnf-du-configuring-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/cnf-du-partitioning-management-workloads.adoc
  modules/cnf-performing-end-to-end-tests-for-platform-verification.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/install-sno-about-installing-on-a-single-node.adoc
  modules/nodes-nodes-rebooting-gracefully.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/osdk-ha-sno-api.adoc
  modules/sno-du-applying-the-distributed-unit-configuration-to-sno.adoc
  modules/sno-du-applying-the-extra-installation-manifests.adoc
  modules/sno-du-configuring-the-distributed-units.adoc
  modules/sno-du-enabling-workload-partitioning.adoc
  modules/virt-about-vm-templates.adoc
  modules/ztp-about-ztp-and-distributed-units-on-single-node-openshift-clusters.adoc
  modules/ztp-ai-install-ocp-clusters-on-bare-metal.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  modules/ztp-single-node-clusters.adoc
  modules/ztp-ztp-building-blocks.adoc
  operators/operator_sdk/osdk-ha-sno.adoc
  scalability_and_performance/sno-du-enabling-workload-partitioning-on-single-node-openshift.adoc
  scalability_and_performance/ztp-configuring-single-node-cluster-deployment-during-installation.adoc
  updating/index.adoc
  updating/preparing-eus-eus-upgrade.adoc
  virt/install/preparing-cluster-for-virt.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: size/L

#46282 OSDOCS-3557: Generating CLI docs for 4.11
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.11

#47195 Removing RHEL 7 support for the oc CLI
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.11

#47308 OSDOCS-3779 adding instructions to remove unhealthy etcd member
  modules/restore-replace-stopped-etcd-member.adoc
Labels: size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47185 GitHub-43249: Added 3 oc items from the release notes tracker
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.11

#47340 Adding the context to an additional resources ID
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
Labels: Peer Review Needed, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#46767 CNV-16812: Update Start Here page
  _topic_maps/_topic_map.yml
  virt/install/preparing-cluster-for-virt.adoc
  virt/virt-learn-more-about-openshift-virtualization.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#47347 Added Pensando RN
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47361 CNV-18642: Removing specific Quick Start titles in VM Quick Start
  modules/virt-creating-vm-quick-start-web.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47411 CNV-19603: RN for Compliance Operator
  virt/virt-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47414 CNV-16554: Reverting Backup/Restore to Tech Preview
  virt/backup_restore/virt-backup-restore-overview.adoc
Labels: size/XS, branch/enterprise-4.11

#47362 CNV-18642: Adding general QS note to Boot Sources
  virt/virtual_machines/virtual_disks/virt-creating-and-using-boot-sources.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47422 Revert "CNV-16554: Reverting Backup/Restore to Tech Preview"
  virt/backup_restore/virt-backup-restore-overview.adoc
Labels: size/XS

#46386 OSDOCS-3326: ARM updates to AWS UPI install
  installing/installing-preparing.adoc
  modules/installation-aws-ami-stream-metadata.adoc
  modules/installation-aws-upload-custom-rhcos-ami.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-creating-aws-bootstrap.adoc
  modules/installation-creating-aws-control-plane.adoc
  modules/installation-creating-aws-worker.adoc
  modules/installation-supported-aws-machine-types.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#47440 Removes 4.10 doc updates from 4.11 RN draft
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.11

#47388 RNs-4.9.41 Added with bug fix update
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#47437 BZ2092324 - fixed bullet formatting issue
  modules/virt-about-the-vm-dashboard.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, CNV, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47460 BZ#2094901: Adding note for random control plane pick Cherry pick - 4.11
  modules/support-gather-data.adoc
Labels: size/S

#47459 BZ#2094901: Adding note for random control plane pick Cherry pick - 4.10
  modules/support-gather-data.adoc
Labels: size/S

#47453 BZ#2094901: Adding note for random control plane pick Cherry pick - 4.7
  modules/support-gather-data.adoc
Labels: size/S

#47474 removed numbering
  machine_management/index.adoc
Labels: lgtm, size/S

#47248 ocprhv-814 add enhanced logging as Technical Preview enterprise-4.11 rel notes
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#46293 TELCODOCS-416: CNF-3205 Telco friendly workload specific PerformanceProfile API WIP
  modules/cnf-configuring-workload-hints.adoc
  modules/cnf-performance-profile-creator-arguments.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/cnf-understanding-low-latency.adoc
  modules/cnf-understanding-workload-hints.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: size/L, branch/enterprise-4.11

#47381 RHDEVDOCS-4112 - Updated spec.sso operator documentation
  cicd/gitops/configuring-sso-on-argo-cd-using-dex.adoc
  modules/gitops-disable-dex-using-spec-sso.adoc
  modules/gitops-disable-dex.adoc
Labels: size/M, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#47349 OSSMDOC-615: Update supported configurations topic for 2.2
  modules/ossm-supported-configurations.adoc
Labels: size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47383 [ROX-8051]: make ebpf default collection method
  modules/secured-cluster-configuration-options-operator.adoc
Labels: Peer Review Done, size/XS, RHACS

#47473 Fixes upgrading section in z-stream to be consistent
  release_notes/ocp_3_11_release_notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-3.11

#47404 CNV-13998: Compliance Operator and CNV
  virt/about-virt.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47519 [enterprise-4.11] CNV-13998: Compliance Operator
  virt/about-virt.adoc
Labels: size/S

#47515 [enterprise-4.6] osdocs 3717 update etcd recommendations for scalability and performance
  modules/recommended-etcd-practices.adoc
Labels: size/M

#45515 OSDOCS3082: Networking Operators
  _topic_maps/_topic_map.yml
  networking/networking-operators-overview.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9

#47468 RNs-4.8.46:adds zstream update
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.8

#47399 Adds notes for 4.10.21
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#46865 RHDEVDOCS-4159 - Release Notes for SBO 1.1.1
  applications/connecting_applications_to_services/sbo-release-notes.adoc
  modules/sbo-release-notes-1-1-1.adoc
Labels: lgtm, size/M, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#47401 [SRVCOM-1832] Update Serverless abstracts for Jupiter readiness
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-getting-support.adoc
  modules/serverless-kafka-broker-sasl-default-config.adoc
  modules/serverless-kafka-broker-tls-default-config.adoc
  modules/serverless-kafka-sasl-channels.adoc
  modules/serverless-kafka-sasl-public-certs.adoc
  modules/serverless-kafka-tls-channels.adoc
  modules/support-knowledgebase-about.adoc
  modules/support-knowledgebase-search.adoc
  modules/support-submitting-a-case.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/security/serverless-kafka-security.adoc
  serverless/serverless-support.adoc
Labels: Peer Review Done, size/L, kind/cleanup, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47532 [enterprise-4.11] [SRVCOM-1832] Update abstracts for Jupiter readiness
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-getting-support.adoc
  modules/serverless-kafka-broker-sasl-default-config.adoc
  modules/serverless-kafka-broker-tls-default-config.adoc
  modules/serverless-kafka-sasl-channels.adoc
  modules/serverless-kafka-sasl-public-certs.adoc
  modules/serverless-kafka-tls-channels.adoc
  modules/support-knowledgebase-about.adoc
  modules/support-knowledgebase-search.adoc
  modules/support-submitting-a-case.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/security/serverless-kafka-security.adoc
  serverless/serverless-support.adoc
Labels: size/L

#47533 [enterprise-4.10] [SRVCOM-1832] Update abstracts for Jupiter readiness
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-getting-support.adoc
  modules/serverless-kafka-broker-sasl-default-config.adoc
  modules/serverless-kafka-broker-tls-default-config.adoc
  modules/serverless-kafka-sasl-channels.adoc
  modules/serverless-kafka-sasl-public-certs.adoc
  modules/serverless-kafka-tls-channels.adoc
  modules/support-knowledgebase-about.adoc
  modules/support-knowledgebase-search.adoc
  modules/support-submitting-a-case.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/security/serverless-kafka-security.adoc
  serverless/serverless-support.adoc
Labels: size/L

#47534 [enterprise-4.9] [SRVCOM-1832] Update abstracts for Jupiter readiness
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-getting-support.adoc
  modules/serverless-kafka-broker-sasl-default-config.adoc
  modules/serverless-kafka-broker-tls-default-config.adoc
  modules/serverless-kafka-sasl-channels.adoc
  modules/serverless-kafka-sasl-public-certs.adoc
  modules/serverless-kafka-tls-channels.adoc
  modules/support-knowledgebase-about.adoc
  modules/support-knowledgebase-search.adoc
  modules/support-submitting-a-case.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  serverless/security/serverless-kafka-security.adoc
  serverless/serverless-support.adoc
Labels: size/L

#47531 BZ#2097051: Add info regarding credrequest directory - enteprise-4.8
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cco-ccoctl-creating-individually.adoc
Labels: size/S

#47336 OSSMDOC-597: Document support for ROSA.
  modules/ossm-federation-limitations.adoc
  modules/ossm-supported-configurations.adoc
Labels: size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47334 OSSMDOC-626: Check known issues file for fixed issues.
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
Labels: size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47572 removing some books
  _topic_map.yml
  release_notes/attributes
  release_notes/images
  release_notes/modules
  release_notes/opp-release-notes.adoc
  release_notes/snippets
  support/attributes
  support/getting-support.adoc
  support/images
  support/modules
  support/snippets
  welcome/attributes
  welcome/images
  welcome/index.adoc
  welcome/modules
  welcome/snippets
Labels: size/M

#47525 R ns 4.7 updating
  release_notes/ocp-4-7-release-notes.adoc
Labels: size/L

#47576 BZ#2097051: Add info regarding credrequest directory - enteprise-4.9
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cco-ccoctl-creating-individually.adoc
  modules/cco-ccoctl-upgrading.adoc
Labels: size/S

#47581 OSDOCS3082: Networking Operators overview
  networking/networking-operators-overview.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#47589 [enterprise-4.10] OSDOCS3082: Networking Operators
  _topic_maps/_topic_map.yml
  networking/networking-operators-overview.adoc
Labels: size/S

#47593 [enterprise-4.11] OSDOCS3082: Networking Operators
  _topic_maps/_topic_map.yml
  networking/networking-operators-overview.adoc
Labels: size/S

#47504 RNs-typo:changes updating to upgrading
  release_notes/ocp-4-9-release-notes.adoc
Labels: lgtm, size/M

#47384 OSDOCS3023: Updating clusters overview enhancement
  updating/index.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47030 BZ2089283: PolicyGenTemplate musthave complianceType changes applied to resources may not be corrected represented
  modules/ztp-things-to-consider-when-creating-custom-resource-policies.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#47510 CNV-17453: RN Network latency checkup
  virt/virt-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, CNV, branch/enterprise-4.11

#47598 OSDOCS3023: Updating clusters overview enhancement
  updating/index.adoc
Labels: size/S

#47599 OSDOCS3023: Updating clusters overview enhancement
  updating/index.adoc
Labels: size/S

#47600 OSDOCS3023: Updating clusters overview enhancement
  updating/index.adoc
Labels: size/S

#47387 CNV-19159: adding KB link to 4.10 RNs
  virt/virt-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.10

#47523 Correct capitalization for OpenShift in the sno attributes
  _attributes/common-attributes.adoc
Labels: Peer Review Done, size/XS, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47283 CNV-16793: VM Overview page
  modules/virt-about-the-vm-dashboard.adoc
Labels: Peer Review Done, size/M, CNV, branch/enterprise-4.11

#47605 removed the table and modified the existing link
  storage/persistent_storage/persistent-storage-ocs.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#47594 [RHACS] ROX-9760: Add network policy list
  modules/violations-view-deployment-tab.adoc
Labels: Peer Review Done, size/S, RHACS/next

#47615 Fix capitalization
  modules/virt-hardware-os-requirements.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#47618 Fix capitalization in TP note
  modules/virt-hardware-os-requirements.adoc
Labels: size/XS

#47614 BZ1960690-47 - Booting the image with virtual media doesn't work
  modules/ipi-install-node-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7

#47489 BZ1960690-48 - Booting the image with virtual media doesn't work
  modules/ipi-install-node-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#47470 BZ1960690-49 - Booting the image with virtual media doesn't work
  modules/ipi-install-node-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#46627 BZ-207662-main:adds to important message
  modules/nw-externalip-about.adoc
Labels: size/XS, px-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#46659 BZ-2076662:adds changes to 4.9 RNs
  release_notes/ocp-4-9-release-notes.adoc
Labels: size/XS

#47511 [OSDOCS-3320] removed inline from policy table descriptions
  modules/rosa-deleting-account-wide-iam-roles-and-policies.adoc
  modules/rosa-sts-account-wide-roles-and-policies.adoc
  modules/rosa-sts-creating-a-cluster-quickly-ocm.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations-ocm.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10, branch/enterprise-4.11

#46625 BZ-2076662: adds ExternalIPs bug fix to RNs
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#47641 TELCODOCS-658: Added a release note
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.11

#47640 TELCODOCS-658: D/S Docs & RN: MGMT-8551 4.11 change
  modules/install-sno-about-installing-on-a-single-node.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.11

#46357 RHDEVDOCS-3918 - Document Alertmanager for user workload monitoring
  modules/monitoring-applying-a-custom-configuration-to-alertmanager-for-user-defined-alert-routing.adoc
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-configurable-monitoring-components.adoc
  modules/monitoring-creating-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-disabling-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-enabling-a-separate-alertmanager-instance-for-user-defined-alert-routing.adoc
  modules/monitoring-enabling-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-enabling-the-platform-alertmanager-instance-for-user-defined-alert-routing.adoc
  modules/monitoring-support-considerations.adoc
  modules/monitoring-understanding-alert-routing-for-user-defined-projects.adoc
  monitoring/enabling-alert-routing-for-user-defined-projects.adoc
  monitoring/enabling-monitoring-for-user-defined-projects.adoc
  monitoring/managing-alerts.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, qe-approved, branch/enterprise-4.11

#46991 TELCODOCS-655: D/S Docs & RN: AI SaaS - Installing with the AI - Updates to existing content
  installing/installing_on_prem_assisted/installing-on-prem-assisted.adoc
  modules/assisted-installer-using-the-assisted-installer.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10, branch/enterprise-4.11

#47643 [enterprise-4.9]-BZ-2076662-4.9-CP
  modules/nw-externalip-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#46758 OSDOCS-3661: Adding section for blocking payload registries
  modules/images-configuration-blocked-payload.adoc
  openshift_images/image-configuration.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#47630 RNs-4.10.22:adds zstream notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#47673 [enterprise-4.10] CNV-16812: Update Start Here page
  _topic_maps/_topic_map.yml
  virt/install/preparing-cluster-for-virt.adoc
  virt/virt-learn-more-about-openshift-virtualization.adoc
Labels: size/L

#47390 TELCODOCS:605 - cleaned up release notes document for incoming featur…
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  sandboxed_containers/sandboxed-containers-4.11-release-notes.adoc
  sandboxed_containers/sandboxed-containers-4.9-release-notes.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#44364 OCDOCS-3446: Recommend support of alternative VPA recommender to the community
  modules/nodes-pods-vertical-autoscaler-about.adoc
  modules/nodes-pods-vertical-autoscaler-configuring.adoc
  modules/nodes-pods-vertical-autoscaler-custom.adoc
  nodes/pods/nodes-pods-vertical-autoscaler.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#45801 OSDOCS-2890: RNs for OAuth server audit logging
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.11

#47604 [BZ#2100766] Update BYOH docs for RHEL 8 openshift-ansible
  modules/rhel-compute-updating.adoc
  modules/rhel-preparing-node.adoc
  modules/rhel-preparing-playbook-machine.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#45057 OSDOCS-3568: Adding RN about future Kubernetes API removals
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47516 RNs-4.6-updating:changes upgrade to update
  release_notes/ocp-4-6-release-notes.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6

#47602 OSDOCS-3550: Updated OCP mirror links for installations
  modules/installation-gcp-user-infra-rhcos.adoc
  modules/installation-rhv-about-inventory-yml.adoc
  modules/installation-rhv-specifying-rhcos-image-settings.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#47415 [OSDOCS-3716]: Add etcd hardware recommendations
  modules/recommended-etcd-practices.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#47405 Adding RHEL 9 support for oc
  modules/cli-installing-cli-rpm.adoc
Labels: Peer Review Done, lgtm, size/XS, qe-approved, branch/enterprise-4.11

#47439 OSDOCS-3800: Release notes for RHEL 9 support with oc
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#44565 OSDOCS-3517: Azure File CSI Driver Operator TP->GA
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi-azure-file.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#47389 ECOPROJECT-411: Add info about the SNR CR and lastError field
  modules/eco-poison-pill-operator-about.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#47728 GH-46243:adds external DNS Operator to table
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#47736 [enterprise-4.11] OSDOCS-3517: Azure File CSI Driver Operator TP->GA
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi-azure-file.adoc
Labels: size/S

#47737 OSDOCS-3517: Azure File CSI Driver Operator TP->GA Fixes
  storage/container_storage_interface/persistent-storage-csi-azure-file.adoc
Labels: size/XS, branch/enterprise-4.11

#47211 OSDOCS-3742: Add bug text for Ignition configs on VMware
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47738 [enterprise-4.11] OSDOCS-3517: Azure File CSI Driver Operator TP->GA Fixes
  storage/container_storage_interface/persistent-storage-csi-azure-file.adoc
Labels: size/XS

#47341 [OSDOCS-3595]: pd-balanced disks for GCP
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-gcp-pd-disk-types.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#47711 RHDEVDOCS-3549-2
  modules/cluster-logging-collector-log-forward-fluentd.adoc
Labels: size/S, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47704 Adds 373 RNs to OMR
  modules/mirror-registry-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#47741 [enterprise-4.11] updates 4.11 tech preview table
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#38819 OSDOCS-2098: IPsec can be enabled at runtime
  _topic_maps/_topic_map.yml
  modules/nw-operator-cr.adoc
  modules/nw-ovn-ipsec-certificates.adoc
  modules/nw-ovn-ipsec-disable.adoc
  modules/nw-ovn-ipsec-enable.adoc
  modules/nw-ovn-ipsec-encryption.adoc
  modules/nw-ovn-ipsec-traffic.adoc
  modules/nw-ovn-ipsec-verification.adoc
  networking/ovn_kubernetes_network_provider/about-ipsec-ovn.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc
  post_installation_configuration/network-configuration.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#47752 [enterprise-4.11] IPsec can be enabled at runtime
  _topic_maps/_topic_map.yml
  modules/nw-operator-cr.adoc
  modules/nw-ovn-ipsec-certificates.adoc
  modules/nw-ovn-ipsec-disable.adoc
  modules/nw-ovn-ipsec-enable.adoc
  modules/nw-ovn-ipsec-encryption.adoc
  modules/nw-ovn-ipsec-traffic.adoc
  modules/nw-ovn-ipsec-verification.adoc
  networking/ovn_kubernetes_network_provider/about-ipsec-ovn.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc
  post_installation_configuration/network-configuration.adoc
Labels: size/L, branch/enterprise-4.11

#47757 Fixed typo, some reorg
  virt/virt-learn-more-about-openshift-virtualization.adoc
Labels: size/M, branch/enterprise-4.10, branch/enterprise-4.11

#47681 BZ2089527: Add a note about olm.maxOpenShiftVersion annotation
  modules/osdk-control-compat.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47659 CMP-1426 CO 0.1.53 release notes
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47669 OSDOCS-2978: Upstream Kubernetes Overview
  _topic_maps/_topic_map.yml
  getting_started/kubernetes-overview.adoc
  images/247-OpenShift-Kubernetes-Overview.png
  images/247_OpenShift_Kubernetes_Overview-1.png
  images/247_OpenShift_Kubernetes_Overview-2.png
  modules/kubernetes-components.adoc
  modules/kubernetes-conceptual-guidelines.adoc
  modules/kubernetes-resources.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47790 [SRVCOM-1958] Updating semantics at PM request
  modules/serverless-create-func-kn.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47449 OSSMDOC-581 Update load test results topic
  modules/ossm-load-test-results.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46421 Added common terms section to the Installing Book
  installing/index.adoc
  modules/install-openshift-common-terms.adoc
  modules/installation-overview.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#46521 OSDOCS-3503: RelNotes for Defining Kuryr ports pools & CIDR Ranges
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47665 CNV-18318: boot mode switcher in UI
  modules/virt-editing-vm-web.adoc
Labels: size/XS, CNV, branch/enterprise-4.11

#47817 EDNS-Operator: Addresses the issue in EDNS operator
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: Peer Review Needed, branch/enterprise-4.10, branch/enterprise-4.11

#47819 [enterprise-4.10] EDNS-Operator: Addresses the issue in EDNS operator
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#47788 Adding redirect rule for 404'd external DNS page
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#46831 Updates for BZ2033931 adding info on CPU capacity related to pod scheduling
  modules/cnf-cpu-infra-container.adoc
  scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.adoc
Labels: size/M

#47611 [RHACS] Updated docs for new dashboard
  operating/view-dashboard.adoc
Labels: Peer Review Done, size/L, RHACS/next

#47820 [enterprise-4.6] OSDOCS-2978: Upstream Kubernetes Overview
  _topic_maps/_topic_map.yml
  images/247-OpenShift-Kubernetes-Overview.png
  images/247_OpenShift_Kubernetes_Overview-1.png
  images/247_OpenShift_Kubernetes_Overview-2.png
  modules/kubernetes-components.adoc
  modules/kubernetes-conceptual-guidelines.adoc
  modules/kubernetes-resources.adoc
  welcome/kubernetes-overview.adoc
Labels: size/L

#47821 [enterprise-4.7] OSDOCS-2978: Upstream Kubernetes Overview
  _topic_maps/_topic_map.yml
  images/247-OpenShift-Kubernetes-Overview.png
  images/247_OpenShift_Kubernetes_Overview-1.png
  images/247_OpenShift_Kubernetes_Overview-2.png
  modules/kubernetes-components.adoc
  modules/kubernetes-conceptual-guidelines.adoc
  modules/kubernetes-resources.adoc
  welcome/kubernetes-overview.adoc
Labels: size/L

#47822 [enterprise-4.8] OSDOCS-2978: Upstream Kubernetes Overview
  _topic_maps/_topic_map.yml
  images/247-OpenShift-Kubernetes-Overview.png
  images/247_OpenShift_Kubernetes_Overview-1.png
  images/247_OpenShift_Kubernetes_Overview-2.png
  modules/kubernetes-components.adoc
  modules/kubernetes-conceptual-guidelines.adoc
  modules/kubernetes-resources.adoc
  welcome/kubernetes-overview.adoc
Labels: size/L

#47823 [enterprise-4.9] OSDOCS-2978: Upstream Kubernetes Overview
  _topic_maps/_topic_map.yml
  images/247-OpenShift-Kubernetes-Overview.png
  images/247_OpenShift_Kubernetes_Overview-1.png
  images/247_OpenShift_Kubernetes_Overview-2.png
  modules/kubernetes-components.adoc
  modules/kubernetes-conceptual-guidelines.adoc
  modules/kubernetes-resources.adoc
  welcome/kubernetes-overview.adoc
Labels: size/L

#47768 BZ2093076: Adds MetalLB in feature summary table
  welcome/oke_about.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46441 OCP 4.11 Release Notes for P/Z
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.11

#47356 [OSDOCS-3594]: Nutanix MAPI
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-nutanix.adoc
  modules/machineset-yaml-nutanix.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#47454 RHDEVDOCS-3903: Added a note related to add tasks from your local tek…
  cicd/pipelines/working-with-pipelines-using-the-developer-perspective.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
Labels: size/S, Dev Tools, branch/enterprise-4.11

#44527 OSDOCS-3328: add kerberos extension
  modules/rhcos-add-extensions.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#47831 GH#47228: Adding CLI tool
  modules/odc-using-web-terminal.adoc
  web_console/odc-about-web-terminal.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47457 RHDEVDOCS-3817 - Added cluster permission management
  cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  modules/gitops-additional-permissions-for-cluster-config.adoc
  modules/gitops-inbuilt-permissions-for-cluster-config.adoc
Labels: size/M, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#47845 [enterprise-4.10] Changed latest versions to stable
  modules/ipi-install-retrieving-the-openshift-installer.adoc
Labels: size/XS

#47852 [enterprise-4.11] Changed latest versions to stable
  modules/ipi-install-retrieving-the-openshift-installer.adoc
Labels: size/XS

#47837 Fix asciibinder build errors introduced in #47681
  modules/osdk-control-compat.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47854 OSSMDOC-632: Remove duplicate table
  modules/ossm-rn-new-features.adoc
Labels: size/S, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47363 ECOPROJECT-615:Doc changes for updating the name of Poison Pill Operator to Self Node Remediation Operator
  _topic_maps/_topic_map.yml
  modules/eco-configuring-machine-health-check-with-self-node-remediation.adoc
  modules/eco-poison-pill-operator-about.adoc
  modules/eco-poison-pill-operator-installation-cli.adoc
  modules/eco-poison-pill-operator-troubleshooting.adoc
  modules/eco-self-node-remediation-about-watchdog.adoc
  modules/eco-self-node-remediation-operator-about.adoc
  modules/eco-self-node-remediation-operator-installation-cli.adoc
  modules/eco-self-node-remediation-operator-installation-web-console.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  nodes/nodes/eco-node-health-check-operator.adoc
  nodes/nodes/eco-poison-pill-operator.adoc
  nodes/nodes/eco-self-node-remediation-operator.adoc
Labels: Peer Review Done, size/XL, branch/enterprise-4.11

#47563 OSSMDOC-522: Update installation for ROSA.
  modules/ossm-install-rosa.adoc
  service_mesh/v2x/ossm-create-smcp.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#47877 [enterprise-4.11] CP doc changes for TELCODOCS-581
  _topic_maps/_topic_map.yml
  modules/eco-configuring-machine-health-check-with-self-node-remediation.adoc
  modules/eco-poison-pill-operator-about.adoc
  modules/eco-poison-pill-operator-installation-cli.adoc
  modules/eco-poison-pill-operator-troubleshooting.adoc
  modules/eco-self-node-remediation-about-watchdog.adoc
  modules/eco-self-node-remediation-operator-about.adoc
  modules/eco-self-node-remediation-operator-installation-cli.adoc
  modules/eco-self-node-remediation-operator-installation-web-console.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  nodes/nodes/eco-node-health-check-operator.adoc
  nodes/nodes/eco-poison-pill-operator.adoc
  nodes/nodes/eco-self-node-remediation-operator.adoc
Labels: size/XL

#46893 OSDOCS-3621: add spec.subdomain enhancement
  modules/nw-ingress-sharding-route-configuration.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc
  networking/routes/route-configuration.adoc
Labels: Peer Review Done, size/L, qe-approved, branch/enterprise-4.11

#39426 OSDOCS-2098: Add release note for IPsec encryption
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11
