Repository openshift/openshift-docs, pull requests merged in 2022-06, with the labels that each got.

#46179 [RHACS] Fixed the release date in 3.70 release notes.
  release_notes/370-release-notes.adoc
Labels: size/XS, RHACS/next

#45663 Gh-issue-40595: Updates oc adm upgrade example output
  modules/update-upgrading-cli.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11

#46121 Add 6.0 RN, update prereqs and index to match 4.10 table changes PR
  _topic_maps/_topic_map.yml
  modules/wmco-prerequisites.adoc
  windows_containers/index.adoc
  windows_containers/windows-containers-release-notes-5-x.adoc
  windows_containers/windows-containers-release-notes-6-x.adoc
Labels: size/L

#46127 BZ:2086925b - Added must-gather image to Support section in documenta…
  modules/gathering-data-specific-features.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#46024 OSDOCS-3679: Release notes for descheduler defaulting to simulating e…
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.11

#46136 [BZ2091564] Change Prometheus version to 0.4.1
  modules/monitoring-deploying-a-sample-service.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46180 [enterprise-4.6]SRVCOM-1865 Merge IBM P/Z into Linux procedures
  modules/serverless-installing-cli-linux-ibm-power-rpm.adoc
  modules/serverless-installing-cli-linux-ibm-power-tarball.adoc
  modules/serverless-installing-cli-linux-ibm-z-rpm.adoc
  modules/serverless-installing-cli-linux-ibm-z-tarball.adoc
  modules/serverless-installing-cli-linux-rpm-package-manager.adoc
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-installing-cli-web-console.adoc
  serverless/cli_tools/installing-kn.adoc
Labels: size/L

#46186 Updated WMCO 5.0 Platform Support Tables -take 2
  modules/wmco-prerequisites.adoc
  windows_containers/windows-containers-release-notes-5-x.adoc
Labels: size/M, branch/enterprise-4.10

#46069 OADP 473 - Document how to enable Velero debug loglevel
  modules/oadp-debugging-oc-cli.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46197 Add carriage return that prevented an include
  windows_containers/windows-containers-release-notes-6-x.adoc
Labels: size/XS

#45767 [SRVCOM-780]: Add performance and scaling info for Serverless on OCP
  serverless/discover/about-serverless.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#44807 BZ1873212: added two tested maxs
  modules/openshift-cluster-maximums-major-releases.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46214 [enterprise-4.8] [SRVCOM-780]: Add performance and scaling info for Serverless on OCP
  serverless/discover/about-serverless.adoc
Labels: size/XS

#46220 [enterprise-4.9] [SRVCOM-780]: Add performance and scaling info for Serverless on OCP
  serverless/discover/about-serverless.adoc
Labels: size/S

#46215 [enterprise-4.6] BZ1873212-4.6: tested maxs
  modules/openshift-cluster-maximums-major-releases.adoc
Labels: size/S

#46216 [enterprise-4.7] BZ1873212-4.7: tested maxs
  modules/openshift-cluster-maximums-major-releases.adoc
Labels: size/S

#45722 [SRVOCF-288] Add on-cluster build docs
  modules/serverless-functions-on-cluster-builds.adoc
  serverless/functions/serverless-functions-getting-started.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46176 [RHACS] Minor updates to Release Notes
  release_notes/370-release-notes.adoc
Labels: size/S, RHACS/next

#45708 BZ#085084 - Fix to premigration checklist
  migrating_from_ocp_3_to_4/premigration-checklists-3-4.adoc
  migration_toolkit_for_containers/premigration-checklists-mtc.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45916 [BZ2079656]:Correct the storage space value for the compute and control nodes
  modules/installation-osp-bootstrap-machine.adoc
  modules/installation-osp-control-compute-machines.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45618 [Enterprise-4.10]BZ2075111: Add a new section
  release_notes/ocp-4-10-release-notes.adoc
Labels: size/XS

#45581 [Enterprise-4.9]BZ2075111: Add a new section
  release_notes/ocp-4-9-release-notes.adoc
Labels: size/XS

#45577 [Enterprise-4.6] BZ2075111: Add a new section
  release_notes/ocp-4-6-release-notes.adoc
Labels: size/XS

#46232 [SRVCOM-1874] Update pingsource API version and data spec
  modules/serverless-pingsource-yaml.adoc
Labels: size/S, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46182 BZ2091930 - SRO install - remove instructions to create namespace and OperatorGroup
  modules/psap-special-resource-operator-installing-using-cli.adoc
  modules/psap-special-resource-operator-installing-using-web-console.adoc
Labels: size/M, branch/enterprise-4.10, branch/enterprise-4.11

#45907 RHACS docs 3.70 release
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
  index-commercial.html
Labels: Peer Review Done, size/S

#45425 TELCODOCS-428: Update RAM in Minimum resource requirements
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: Peer Review Done, size/XS, Telco, branch/enterprise-4.10, branch/enterprise-4.11

#46128 Update for BZ2089766
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46239 rel note addition for node certificates
  windows_containers/windows-containers-release-notes-5-x.adoc
Labels: lgtm, size/S, branch/enterprise-4.10

#46286 [RHACS] ROX-10627: Add fixed bug to Release Notes
  release_notes/370-release-notes.adoc
Labels: lgtm, size/XS, RHACS/next, RHACS

#46289 [RHACS] Merge 3.70 into the main `rhacs-docs` branch
  _topic_map.yml
  build_for_portal.py
  integration/integrate-with-image-registries.adoc
  modules/automatic-configuration-image-registry.adoc
  modules/common-attributes.adoc
  modules/configure-ocp-oauth-identity-provider.adoc
  modules/configure-policy-notifications.adoc
  modules/configure-signature-integration.adoc
  modules/configuring-assumerole-acs.adoc
  modules/delete-generated-policies.adoc
  modules/disable-admission-controller-enforcement-54.adoc
  modules/disable-admission-controller-enforcement.adoc
  modules/enable-admission-controller-enforcement-54.adoc
  modules/enable-admission-controller-enforcement.adoc
  modules/generate-network-policies.adoc
  modules/identify-vulnerabilities-in-nodes.adoc
  modules/manual-configuration-image-registry-acr.adoc
  modules/manual-configuration-image-registry-dtr.adoc
  modules/manual-configuration-image-registry-ecr.adoc
  modules/manual-configuration-image-registry-gar.adoc
  modules/manual-configuration-image-registry-gcr.adoc
  modules/manual-configuration-image-registry-ibm.adoc
  modules/manual-configuration-image-registry-jfrog.adoc
  modules/manual-configuration-image-registry-ocp.adoc
  modules/manual-configuration-image-registry-qcr.adoc
  modules/manual-configuration-image-registry-redhat.adoc
  modules/network-graph-view.adoc
  modules/policy-criteria.adoc
  modules/simulate-network-policies.adoc
  modules/understand-admission-controller-enforcement.adoc
  modules/use-signature-verification.adoc
  modules/validatingwebhookconfiguration-yaml-changes.adoc
  modules/verify-central-install-operator.adoc
  modules/view-network-baselines.adoc
  operating/manage-user-access/configure-ocp-oauth.adoc
  operating/use-admission-controller-enforcement.adoc
  operating/verify-image-signatures.adoc
  release_notes/370-release-notes.adoc
Labels: size/XL

#46292 [enterprise-4.9] BZ2089766: Updating additional resources, prereqs and first step
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
Labels: size/M

#44501 BZ2072425: oc binary is not sending authentication headers when using a http proxy
  modules/cli-logging-in.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46230 [RHACS] Fix typo in installation instructions
  modules/install-acs-operator.adoc
Labels: size/XS

#45760 [RHACS] ROX-10747: Add platform plus requirement
  modules/support-submitting-a-case.adoc
Labels: Peer Review Needed, size/XS, RHACS

#46290 [RHACS] Fixes portal format issue
  modules/acs-quick-install-secured-cluster-using-helm.adoc
Labels: size/XS, RHACS

#46240 rel note addition for node certificates
  windows_containers/windows-containers-release-notes-6-x.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#46314 [rhacs-docs-3.68] Fix cherry pick errors
  modules/install-acs-operator.adoc
Labels: size/XS

#45917 Behavior of non-versioned and versioned cluster tasks
  _topic_maps/_topic_map.yml
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  cicd/pipelines/managing-nonversioned-and-versioned-cluster-tasks.adoc
  modules/op-advantages-and-disadvantages-of-non-versioned-and-versioned-cluster-tasks.adoc
  modules/op-differences-between-non-versioned-and-versioned-cluster-tasks.adoc
  modules/op-disabling-non-versioned-and-versioned-cluster-tasks.adoc
Labels: lgtm, size/L, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46323 [RHACS] Add deprecated item to Release Notes
  release_notes/370-release-notes.adoc
Labels: size/XS, RHACS

#46324 Add back in Adobe DTM for analytics
  _templates/_page_openshift.html.erb
Labels: size/XS

#46275 OSDOCS-3628: Adding ability to create an ingress route with a custom certificate
  modules/nw-ingress-creating-a-route-via-an-ingress.adoc
  modules/nw-ingress-reencrypt-route-custom-cert.adoc
  networking/routes/route-configuration.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.11

#45889 OADP-440 DeploymentConfig restic workaround to include templateinstances
  modules/oadp-restic-issues.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46331 OKD Hide Web Terminal Assembly
  _topic_maps/_topic_map.yml
Labels: okd-only, lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46334 WINC replace troubleshooting assembly
  _topic_maps/_topic_map.yml
Labels: lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#46328 [RHACS] Clarify default policy options
  modules/create-policy-from-system-policies-view.adoc
  modules/modify-existing-security-policies.adoc
  modules/use-default-security-policies.adoc
Labels: size/S

#46302 OSDOCS-3435: RN for Nutanix IPI installation
  release_notes/ocp-4-11-release-notes.adoc
Labels: size/XS, branch/enterprise-4.11

#44534 bz2062068 updating CA bundle certificates
  _topic_maps/_topic_map.yml
  modules/ca-bundle-replacing.adoc
  modules/ca-bundle-understanding.adoc
  networking/enable-cluster-wide-proxy.adoc
  security/certificates/replacing-default-ingress-certificate.adoc
  security/certificates/updating-ca-bundle.adoc
Labels: size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45441 MIG-1045 Instructions for state-only transfer and CD migration
  modules/migration-state-migration-cli.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46109 Compliance Operator v0.1.52 release notes stub
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46231 Add the oVirt restricted install to OKD
  _topic_maps/_topic_map.yml
  installing/installing_rhv/preparing-to-install-on-rhv.adoc
Labels: lgtm, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46384 [enterprise-4.7] Add the oVirt restricted install to OKD
  _topic_maps/_topic_map.yml
Labels: size/XS

#46385 [enterprise-4.11] Add the oVirt restricted install to OKD
  _topic_maps/_topic_map.yml
  installing/installing_rhv/preparing-to-install-on-rhv.adoc
Labels: size/S

#46333 Correct the oc delete command for manual storage reclaim
  modules/storage-persistent-storage-reclaim-manual.adoc
Labels: lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46272 fixed broken link in Regulatory Compliance section
  modules/policy-security-regulation-compliance.adoc
  modules/sdpolicy-security.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46401 [GH#46394] Restore leveloffset for oadp-restic-issues module to 1
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46409 [enterprise-4.10] CP doc changes for BZ-2082671
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: size/M

#46410 [enterprise-4.11] CP doc changes for BZ-2082671
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: size/M

#46380 [RHACS] ROX-11277: Add removed API parameter to RNs
  release_notes/370-release-notes.adoc
Labels: lgtm, size/XS

#46429 [enterprise-4.6] BZ2080277 - Adding warning for RAID config
  modules/recommended-configurable-storage-technology.adoc
Labels: size/XS

#44434 BZ:2069259 - Update correct port access for out-of-band management IP…
  modules/ipi-install-network-requirements.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46434 Revert " rel note addition for node certificates"
  windows_containers/windows-containers-release-notes-5-x.adoc
Labels: size/S

#46439 [enterprise-4.9] BZ:2069259 - Update correct port access for out-of-band management IP…
  modules/ipi-install-network-requirements.adoc
Labels: size/XS

#46418 RNs-4.10.17:adds z-stream notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S

#46432 [enterprise-4.8] BZ2080277 - Adding warning for RAID config
  modules/recommended-configurable-storage-technology.adoc
Labels: size/XS

#46433 [enterprise-4.9] BZ2080277 - Adding warning for RAID config
  modules/recommended-configurable-storage-technology.adoc
Labels: size/XS

#46437 [enterprise-4.10] BZ2080277 - Adding warning for RAID config
  modules/recommended-configurable-storage-technology.adoc
Labels: size/XS

#46320 [SRVCOM-1829] Update abstracts and structure for admin console topics
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  modules/creating-serverless-apps-admin-console.adoc
  modules/serverless-creating-broker-admin-web-console.adoc
  modules/serverless-creating-channel-admin-web-console.adoc
  modules/serverless-creating-event-source-admin-web-console.adoc
  modules/serverless-creating-subscription-admin-web-console.adoc
  modules/serverless-creating-trigger-admin-web-console.adoc
  serverless/admin_guide/serverless-admin-perspective.adoc
  serverless/admin_guide/serverless-cluster-admin-serving.adoc
  serverless/develop/serverless-applications.adoc
  snippets/serverless-apps.adoc
  snippets/serverless-brokers-intro.adoc
  snippets/serverless-channels-intro.adoc
Labels: Peer Review Needed, size/L, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45429 Configure CSM for Fujitsu iRMC
  modules/ipi-install-configuring-nodes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46448 [enterprise-4.7] [SRVCOM-1829] Update abstracts for admin console topics
  _topic_maps/_topic_map.yml
  modules/creating-serverless-apps-admin-console.adoc
  modules/serverless-creating-broker-admin-web-console.adoc
  modules/serverless-creating-channel-admin-web-console.adoc
  modules/serverless-creating-event-source-admin-web-console.adoc
  modules/serverless-creating-subscription-admin-web-console.adoc
  modules/serverless-creating-trigger-admin-web-console.adoc
  serverless/admin_guide/serverless-admin-perspective.adoc
  serverless/admin_guide/serverless-cluster-admin-serving.adoc
  serverless/develop/serverless-applications.adoc
  snippets/serverless-apps.adoc
  snippets/serverless-brokers-intro.adoc
  snippets/serverless-channels-intro.adoc
Labels: size/L

#46452 [enterprise-4.6] [SRVCOM-1829] Update abstracts for admin console topics
  _topic_maps/_topic_map.yml
  modules/creating-serverless-apps-admin-console.adoc
  serverless/admin_guide/serverless-admin-perspective.adoc
  serverless/admin_guide/serverless-cluster-admin-serving.adoc
  serverless/develop/serverless-applications.adoc
  snippets/serverless-apps.adoc
  snippets/serverless-brokers-intro.adoc
  snippets/serverless-channels-intro.adoc
Labels: size/L

#46395 TELCODOCS-430: Support of multiple simultaneous patch (x.y.z) versions of Release/OS images
  modules/ztp-ai-install-ocp-clusters-on-bare-metal.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11

#46283 BZ2068399:Clarifying where an Egress Firewall can be created
  modules/nw-egressnetworkpolicy-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46446 Adds a release note for implement internal traffic support for OVN K
  release_notes/ocp-4-11-release-notes.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11

#46412 OSDOCS-3713 RN: Azure Ultra SSD
  release_notes/ocp-4-11-release-notes.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11

#46469 [enterprise-4.7[BZ2068399:Clarifying where an Egress Firewall can be created
  modules/nw-egressnetworkpolicy-about.adoc
Labels: size/XS

#44079 BZ1709936: Information bubble contains contradictory statement on feature availability
  admin_guide/managing_networking.adoc
Labels: lgtm, size/XS, branch/enterprise-3.11

#46453 WINC 3/4.8 fix repeated heading
  windows_containers/windows-containers-release-notes-3-x.adoc
Labels: size/XS, branch/enterprise-4.8

#45828 RHDEVDOCS-3629- Correct output example per QE - Branches 4.7+
  modules/cluster-logging-eventrouter-deploy.adoc
Labels: lgtm, size/XS, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46483 [enterprise-4.8] Configure CSM for Fujitsu iRMC
  modules/ipi-install-configuring-nodes.adoc
Labels: size/M, branch/enterprise-4.8

#45266 bz2078943 updated workload partitioning procedure
  modules/sno-du-enabling-workload-partitioning.adoc
Labels: size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46396 RNs-4.9.37 Added with bug fix update
  release_notes/ocp-4-9-release-notes.adoc
Labels: size/S

#46423 OSDOCS-2478: Multicluster console
  modules/enabling-multi-cluster-console.adoc
  modules/multi-cluster-about.adoc
  web_console/web-console.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10, branch/enterprise-4.11

#46472 GH#41565: updating the OSDK make bundle procedure
  modules/osdk-bundle-operator.adoc
Labels: lgtm, size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46500 [enterprise-4.10]OSDOCS-2478: Multicluster console
  modules/enabling-multi-cluster-console.adoc
  modules/multi-cluster-about.adoc
  web_console/web-console.adoc
Labels: size/M

#43801 OSDOCS-3428: Adds clarity to multicluster release note
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#46502 [enterprise-4.11]OSDOCS-2478: Multicluster console
  modules/enabling-multi-cluster-console.adoc
  modules/multi-cluster-about.adoc
  web_console/web-console.adoc
Labels: size/M

#46511 [enteprise-4.8] [SRVCOM-1829]: Update autoscaling abstracts and structure
  _topic_maps/_topic_map.yml
  modules/serverless-enable-scale-to-zero.adoc
  modules/serverless-scale-to-zero-grace-period.adoc
  serverless/admin_guide/serverless-admin-autoscaling.adoc
  serverless/admin_guide/serverless-configuration.adoc
  serverless/develop/serverless-autoscaling-developer.adoc
Labels: size/M

#45296 OSDOCS-3501: add clb timeouts and restructure
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-network-customizations.adoc
  modules/nw-aws-nlb-existing-cluster.adoc
  modules/nw-aws-nlb-new-cluster.adoc
  modules/nw-aws-replacing-clb-with-nlb.adoc
  modules/nw-configuring-clb-timeouts.adoc
  modules/nw-configuring-elb-timeouts-aws-classic.adoc
  modules/nw-configuring-ingress-cluster-traffic-aws-networking-load-balancer.adoc
  modules/nw-configuring-route-timeouts.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws-network-load-balancer.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws.adoc
Labels: Peer Review Needed, lgtm, size/L, branch/enterprise-4.11

#46488 Fixing AsciiBinder warning in the about NMState page
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#46491 [enterprise-4.8] Fixing common attribute includes
  networking/hardware_networks/uninstalling-sriov-operator.adoc
  updating/index.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8

#46425 RHDEVDOCS-3837 - Adding manual subscription option to CLI instructions.
  modules/cluster-logging-deploy-cli.adoc
Labels: lgtm, size/XS, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46474 GH#42468 updated the globallyDisableIrqLoadBalancing function defintion
  modules/cnf-use-device-interrupt-processing-for-isolated-cpus.adoc
Labels: lgtm, size/XS, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46191 Bug 2026192, noted new limitation of OVN environment
  modules/nw-ovn-kuberentes-limitations.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46547 Gh46484
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Needed, lgtm, size/XS, branch/enterprise-4.9

#46475 Adds notes for 4.7.52 release
  release_notes/ocp-4-7-release-notes.adoc
Labels: size/S

#46336 [virt] Removing old redirects and clarifying redirect comments
  .s2i/httpd-cfg/01-commercial.conf
Labels: Peer Review Done, size/XS, CNV

#46549 BZ2087697: Added section on Verifying that the interface is successfully partitioned
  modules/nw-sriov-nic-partitioning.adoc
Labels: lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#46513 fix typo
  modules/rbac-users.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45571 Update the 'Updating a cluster using the CLI' section
  updating/updating-cluster-cli.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46473 OSSMDOC-227: update output from comand oc get smcp
  modules/ossm-control-plane-deploy-1x.adoc
Labels: size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46534 Added bug fix,known issues and improvements to the Release notes
  windows_containers/windows-containers-release-notes-5-x.adoc
Labels: size/S, branch/enterprise-4.10

#46460 OSDOCS-3575: Windows Server 2022 support in WINC 5.1.0 Take 2
  modules/creating-the-vsphere-windows-vm-golden-image.adoc
  modules/wmco-prerequisites.adoc
Labels: size/M, branch/enterprise-4.10

#46551 Corrects az role assignment command
  modules/installation-azure-service-principal.adoc
Labels: lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46223 OSSMDOC-595: service mesh 2.1.3 z stream release notes
  _attributes/common-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/ossm-rn-new-features.adoc
Labels: size/M, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46600 WINC update link to 5.1.0 errata
  windows_containers/windows-containers-release-notes-5-x.adoc
Labels: size/XS, branch/enterprise-4.10

#46471 [OSDOCS-3608]: Relnotes for Enhancement to scale-up operations for etcd clusters
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.11

#46614 Adds a technology preview note to the External DNS Operator page
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#45944 OSDOCS-3677: Add no backup statement for ROSA STS clusters
  modules/rosa-policy-incident.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#46628 Adds notes for 4.10.18 release
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#46430 BZ2079092: Add SELinux warnings and fix hard returns
  modules/security-hardening-how.adoc
  modules/security-hosts-vms-rhcos.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46640 Fixes minor error by including snippet
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#46642 46089 401
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: size/S, branch/enterprise-4.10

#44809 RHDEVDOCS-3868 - Review RNs for OCP 4.10.z bug fix update
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, docs-approved, qe-approved, px-approved, branch/enterprise-4.10

#46487 OADP-512 Remove grep from `oc exec .. velero` examples
  modules/migration-debugging-velero-resources.adoc
  modules/migration-partial-failure-velero.adoc
  modules/oadp-backup-restore-cr-issues.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#45431 MIG-1030: Document downstream network policy configuration compatibility with DVM
  migrating_from_ocp_3_to_4/advanced-migration-options-3-4.adoc
  migrating_from_ocp_3_to_4/installing-3-4.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migration_toolkit_for_containers/advanced-migration-options-mtc.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  migration_toolkit_for_containers/installing-mtc.adoc
  modules/migration-about-configuring-proxies.adoc
  modules/migration-configuring-proxies.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46643 RHDEVDOCS-4113 - Added steps for enabling notifications
  cicd/gitops/argo-cd-custom-resource-properties.adoc
  modules/gitops-argo-cd-notification.adoc
Labels: size/S, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#46658 RNs-4.9.38 Added with bug fix and security update
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9

#46618 Updates a command because there are no pods labeled fluentd in OCP
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
  modules/cluster-logging-troubleshooting-log-forwarding.adoc
Labels: lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46671 BZ#2070016: Adds "Increase network MTU" section to 4.8.
  modules/ipi-install-network-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#46680 Removes an accidentally deleted callout
  modules/installation-azure-service-principal.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46679 46618 fix
  modules/cluster-logging-forwarding-json-logs-to-the-default-elasticsearch.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7

#46631 Updates creating a private cluster with no internet access
  modules/installation-azure-user-defined-routing.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46693 1920488 47
  modules/installation-azure-user-defined-routing.adoc
Labels: size/XS, branch/enterprise-4.7

#45104 TELCODOCS-489: D/S Docs & RN: METAL-175 Add bootstrap external IP field to install-config API for bare metal
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
Labels: Peer Review Done, lgtm, size/M, Telco, branch/enterprise-4.11

#46589 Updates command results to reflect proper version
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#46578 Changes the example to the relative version
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#46701 TELCODOCS-414-rn
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  release_notes/ocp-4-11-release-notes.adoc
Labels: size/XS

#46702 [enterprise-4.7] BZ2079092: Add SELinux warnings and fix hard returns
  modules/security-hardening-how.adoc
  modules/security-hosts-vms-rhcos.adoc
Labels: size/L

#46703 [enterprise-4.6] BZ2079092: Add SELinux warnings and fix hard returns
  modules/security-hardening-how.adoc
  modules/security-hosts-vms-rhcos.adoc
Labels: size/L

#46692 OSDOCS-3735: Clarify ROSA and OSD process security documentation
  modules/policy-change-management.adoc
  modules/rosa-policy-change-management.adoc
Labels: Peer Review Done, size/L, px-approved, branch/enterprise-4.10, branch/enterprise-4.11

#46470 Ovn k limitation removal
  modules/nw-ovn-kuberentes-limitations.adoc
Labels: size/XS, branch/enterprise-4.11

#46486 TELCODOCS-627: updating operator reference to include PA controller
  modules/node-tuning-operator.adoc
  operators/operator-reference.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.11

#45514 No_bug_assigned: Update EDNS Operator content
  _topic_maps/_topic_map.yml
  modules/nw-control-dns-records-public-hosted-zone-aws.adoc
  modules/nw-control-dns-records-public-hosted-zone-azure.adoc
  modules/nw-control-dns-records-public-managed-zone-gcp.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-external-dns-operator-logs.adoc
  modules/nw-external-dns-operator.adoc
  modules/nw-installing-external-dns-operator.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
  networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc
  networking/external_dns_operator/understanding-external-dns-operator.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10, branch/enterprise-4.11

#46669 OSDOCS-3532: Updating example output to 1.24
  _unused_topics/looking-inside-nodes.adoc
  _unused_topics/understanding-workers-masters.adoc
  metering/configuring_metering/metering-common-config-options.adoc
  modules/cleaning-crio-storage.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/compliance-apply-remediation-for-customized-mcp.adoc
  modules/connected-to-disconnected-verify.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/graceful-restart.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/infrastructure-moving-logging.adoc
  modules/infrastructure-moving-router.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-rhv-creating-control-plane-nodes.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/machine-node-custom-partition.adoc
  modules/nodes-nodes-cgroups-2.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-scheduler-node-selectors-cluster.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nodes-scheduler-node-selectors-project.adoc
  modules/nw-sriov-hwol-configuring-machine-config-pool.adoc
  modules/olm-catalogsource-image-template.adoc
  modules/querying-the-status-of-cluster-nodes-using-the-cli.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/rhcos-add-extensions.adoc
  modules/rhcos-enabling-multipath-day-2.adoc
  modules/rhel-compute-updating.adoc
  modules/sandboxed-containers-check-node-eligiblilty.adoc
  modules/update-upgrading-cli.adoc
  modules/update-vsphere-virtual-hardware-on-compute-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-control-plane-nodes.adoc
  modules/virt-accessing-vm-yaml-ssh.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.11

#45589 BZ2083845: poddisruptionbudget example contains deprecated policy/v1beta1
  modules/nodes-pods-pod-disruption-configuring.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.8, branch/enterprise-4.10, branch/enterprise-4.11

#46736 Removes two limitations of OVN K that are being remove for 4.11
  modules/nw-ovn-kuberentes-limitations.adoc
Labels: Peer Review Done, size/XS

#46026 RHDEVDOCS-4073 - Document on binding workloads using the label selector feature as per the spec 1.0
  modules/sbo-advanced-binding-options.adoc
Labels: lgtm, size/M, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#46008 RHDEVDOCS-3777- Release Notes, New Features, and Known Issues for SBO 1.1
  applications/connecting_applications_to_services/sbo-release-notes.adoc
  modules/sbo-release-notes-1-1.adoc
Labels: lgtm, size/L, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#46315 RHDEVDOCS-3491 - Document support for Workload Resource Mapping
  applications/connecting_applications_to_services/binding-workloads-using-sbo.adoc
  modules/sbo-binding-workloads-that-are-not-compliant-with-PodSpec.adoc
  modules/sbo-methods-of-exposing-binding-data.adoc
Labels: lgtm, size/M, Dev Tools, branch/enterprise-4.10, branch/enterprise-4.11

#46387 [RHACS] ROX-10853: Update documentation on reissuing certificates
  configuration/reissue-internal-certificates.adoc
  modules/portal-generate-init-bundle.adoc
  modules/reissue-internal-certificates-secured-clusters-automatic-upgrades.adoc
  modules/reissue-internal-certificates-secured-clusters-download-yaml.adoc
  modules/reissue-internal-certificates-secured-clusters.adoc
Labels: Peer Review Done, size/L

#46708 TELCODOCS-430-rn
  release_notes/ocp-4-11-release-notes.adoc
Labels: Peer Review Done, size/XS, Telco, branch/enterprise-4.11

#46744 Update control plane node sizing
  modules/master-node-sizing.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10, branch/enterprise-4.11

#46766 Re-adds an OVNK Limitation
  modules/nw-ovn-kuberentes-limitations.adoc
Labels: Peer Review Done, size/XS

#46768 BZ#2093054: remove tech-preview warning from Web Terminal Operator docs as it is now GA
  web_console/odc-about-web-terminal.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#46773 [enterprise-4.10]:Update EDNS Operator content
  _topic_maps/_topic_map.yml
  modules/nw-control-dns-records-public-hosted-zone-aws.adoc
  modules/nw-control-dns-records-public-hosted-zone-azure.adoc
  modules/nw-control-dns-records-public-managed-zone-gcp.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-external-dns-operator-logs.adoc
  modules/nw-external-dns-operator.adoc
  modules/nw-installing-external-dns-operator.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
  networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc
  networking/external_dns_operator/understanding-external-dns-operator.adoc
  release_notes/ocp-4-10-release-notes.adoc
Labels: size/L

#46764 [RHACS] Fix typo in RHACS docs
  modules/create-a-custom-access-scope.adoc
Labels: Peer Review Done, size/XS, RHACS

#46716 BZ2085097 Document limitations of PV data transfer to AWS EFS storage
  modules/migration-mtc-release-notes-1-7.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#46722 OSDOCS-3663-PT2: Fixed some issues that were missed when merging this PR
  modules/rosa-troubleshooting-elb-service-role.adoc
  modules/rosa-troubleshooting-general-deployment.adoc
  modules/rosa-troubleshooting-osdccsadmin-deployment.adoc
  rosa_planning/rosa-sts-aws-prereqs.adoc
  rosa_support/rosa-troubleshooting-deployments.adoc
Labels: size/M, branch/enterprise-4.10, branch/enterprise-4.11

#46776 Issue #44643 updating Understanding Operators
  modules/olm-why-use-operators.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11
