Repository openshift/openshift-docs, pull requests merged in 2022-03, with the labels that each got.

#42505 SBO 1.0.1 Release updates
  applications/connecting_applications_to_services/binding-workloads-using-sbo.adoc
  applications/connecting_applications_to_services/exposing-binding-data-from-a-service.adoc
  applications/connecting_applications_to_services/getting-started-with-service-binding.adoc
  applications/connecting_applications_to_services/installing-sbo.adoc
  applications/connecting_applications_to_services/odc-connecting-an-application-to-a-service-using-the-developer-perspective.adoc
  applications/connecting_applications_to_services/projecting-binding-data.adoc
  applications/connecting_applications_to_services/sbo-release-notes.adoc
  applications/connecting_applications_to_services/understanding-service-binding-operator.adoc
  images/odc-binding-connector.png
  images/odc_connecting_multiple_applications.png
  images/odc_connector.png
  modules/sbo-advanced-binding-options.adoc
  modules/sbo-binding-workloads-that-are-not-compliant-with-PodSpec.adoc
  modules/sbo-categories-of-exposable-binding-data.adoc
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service.adoc
  modules/sbo-creating-a-postgresql-database-instance.adoc
  modules/sbo-data-model.adoc
  modules/sbo-deploying-the-spring-petclinic-sample-application.adoc
  modules/sbo-methods-of-exposing-binding-data.adoc
  modules/sbo-naming-strategies.adoc
  modules/sbo-rbac-requirements.adoc
  modules/sbo-release-notes-1-0-1.adoc
  modules/sbo-unbinding-workloads-from-a-backing-service.adoc
Labels: Peer Review Done, lgtm, size/XL, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#42412 BZ2054750: added annotation
  modules/nw-sriov-installing-operator.adoc
Labels: size/S

#42418 TELCODOCS-365: Using pod-level bonding -- TERMINOLOGY FIX
  modules/nw-sriov-cfg-bond-interface-with-virtual-functions.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42404 Telcodocs 43
  release_notes/ocp-4-10-release-notes.adoc
Labels: lgtm, size/XS

#42552 fixing attributes
  installing/installing_aws/installing-aws-secret-region.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-default.adoc
  installing/installing_azure_stack_hub/uninstalling-cluster-azure-stack-hub.adoc
  installing/installing_ibm_cloud_public/configuring-iam-ibm-cloud.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-account.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.adoc
  installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.adoc
  installing/installing_ibm_cloud_public/uninstalling-cluster-ibm-cloud.adoc
  machine_management/creating_machinesets/creating-machineset-ibm-cloud.adoc
  networking/external_dns_operator/nw-configuration-parameters.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-aws.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-azure.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
  networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc
  networking/hardware_networks/configuring-hardware-offloading.adoc
  networking/hardware_networks/using-pod-level-bonding.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/operator_sdk/osdk-pruning-utility.adoc
  virt/backup_restore/virt-backing-up-vms.adoc
  virt/backup_restore/virt-backup-restore-overview.adoc
  virt/backup_restore/virt-installing-configuring-oadp.adoc
  virt/backup_restore/virt-restoring-vms.adoc
  virt/logging_events_monitoring/virt-exposing-custom-metrics-for-vms.adoc
  virt/logging_events_monitoring/virt-virtualization-alerts.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-vgpu-passthrough.adoc
  virt/virtual_machines/advanced_vm_management/virt-enabling-descheduler-evictions.adoc
  virt/virtual_machines/virt-automating-windows-sysprep.adoc
  web_console/dynamic-plug-ins.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42553 [enterprise-4.10] fixing attributes
  installing/installing_ibm_cloud_public/configuring-iam-ibm-cloud.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-account.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-customizations.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-network-customizations.adoc
  installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.adoc
  installing/installing_ibm_cloud_public/uninstalling-cluster-ibm-cloud.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  virt/logging_events_monitoring/virt-virtualization-alerts.adoc
  virt/virtual_machines/advanced_vm_management/virt-enabling-descheduler-evictions.adoc
  web_console/dynamic-plug-ins.adoc
Labels: size/S

#42489 OSDOCS-2900: Update AWS AMIs
  modules/installation-aws-user-infra-rhcos-ami.adoc
Labels: size/XS, branch/enterprise-4.10

#42477 [enterprise-4.9][BZ1836311]: Change the position of the callout
  modules/graceful-shutdown.adoc
Labels: size/XS

#41279 [TELCODOCS-323] [OpenShift 4.10 release notes] - CNF-2772 PTP updates
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42549 Remove CNF-2772 ZTP PTP procedure that references AMQ
  scalability_and_performance/ztp-deploying-disconnected.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42516 Fixing two build errors
  modules/nw-sriov-hwol-configuring-machine-config-pool.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42532 CNV-14945: Updating repo names for 4.10
  modules/virt-enabling-virt-repos.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.10

#42121 RHEVDOCS3492, 3761: Aligned SBO 1.0.1 changes for IBM Z and Power
  applications/connecting_applications_to_services/getting-started-with-service-binding-ibm-power-ibm-z.adoc
  images/img_power.png
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service-power-z.adoc
  modules/sbo-creating-a-postgresql-database-instance-power-z.adoc
  modules/sbo-deploying-a-postgresql-database-operator-power-z.adoc
  modules/sbo-deploying-the-spring-petclinic-sample-application-power-z.adoc
Labels: Peer Review Done, size/L, Multi-Arch, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10

#42448 TELCODOCS-321 D/S Docs & RN: METAL-1 (MPINSTALL-72) Metal Day 1 Networking
  installing/installing_bare_metal_ipi/ipi-install-expanding-the-cluster.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-additional-install-config-parameters.adoc
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-configuring-the-install-config-file.adoc
  modules/ipi-install-creating-an-rhcos-images-cache.adoc
  modules/ipi-install-network-requirements.adoc
  modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42447 BZ1891361: Added note block about vSphere volume is not deleted after the cluster is destroyed
  installing/installing_vsphere/uninstalling-cluster-vsphere-installer-provisioned.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42519 OSDOCS-2841: Updating CCO support table and links for IBM Cloud
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42421 GH#42369: fixes command by adding node_name
  modules/displaying-ovs-logs.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42510 OSDOCS-2855: Adding xref to IBM Cloud IPI release note
  release_notes/ocp-4-10-release-notes.adoc
Labels: size/XS, branch/enterprise-4.10

#42534 40665: Updated command in Installing Bookinfo topic.
  modules/ossm-tutorial-bookinfo-install.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, Service Mesh, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#42579 CNV-14946: Adding about-virt placeholder
  virt/about-virt.adoc
Labels: Peer Review Done, size/S, CNV, branch/enterprise-4.10

#42585 CNV-15863: Broken link
  _attributes/virt-document-attributes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.7

#42425 [BZ2056621] An attempt to add the description for cluster-reader
  modules/rbac-overview.adoc
Labels: lgtm, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42451 GH#36916: fixed headings for procedure
  modules/templates-rails-creating-frontend-service.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42439 RHDEVDOCS-3594: Update odo config docs
  cli_reference/developer_cli_odo/configuring-the-odo-cli.adoc
  modules/developer-cli-odo-preference-table.adoc
  modules/developer-cli-odo-set-config.adoc
  modules/developer-cli-odo-unset-config.adoc
  modules/developer-cli-odo-view-config.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42318 OSDOCS-2940/2941: OLM arbitrary prop & compound constraints
  modules/olm-bundle-format-dependencies-file.adoc
  modules/olm-dependencies.adoc
  modules/olm-dependency-resolution-about.adoc
  modules/olm-generic-constraints.adoc
  modules/olm-properties.adoc
  operators/understanding/olm-packaging-format.adoc
  operators/understanding/olm/olm-understanding-dependency-resolution.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.10

#41136 OSDOCS-2931: Add Hybrid Helm Operator (TP) to OSDK docs
  _topic_maps/_topic_map.yml
  cli_reference/osdk/cli-osdk-install.adoc
  modules/osdk-common-prereqs.adoc
  modules/osdk-hh-create-cr.adoc
  modules/osdk-hh-create-go-api.adoc
  modules/osdk-hh-create-helm-api.adoc
  modules/osdk-hh-create-project.adoc
  modules/osdk-hh-defining-go-api.adoc
  modules/osdk-hh-helm-api-logic.adoc
  modules/osdk-hh-helm-reconciler.adoc
  modules/osdk-hh-implement-controller.adoc
  modules/osdk-hh-main-go.adoc
  modules/osdk-hh-project-layout.adoc
  modules/osdk-hh-rbac.adoc
  modules/osdk-run-operator.adoc
  operators/operator_sdk/helm/osdk-hybrid-helm.adoc
Labels: Peer Review Done, size/XL, branch/enterprise-4.10

#42324 Add heading back for control plane Operators overview
  architecture/control-plane.adoc
  modules/operators-overview.adoc
  operators/index.adoc
Labels: size/S, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#41171 OSDOCS-2859: Add Ansible Operator metrics
  modules/osdk-ansible-inside-operator-local.adoc
  modules/osdk-ansible-metrics.adoc
  modules/osdk-common-prereqs.adoc
  modules/osdk-monitoring-custom-metrics.adoc
  operators/operator_sdk/osdk-monitoring-prometheus.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42246 Various OSDK/OLM feats for 4.10 RN
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42485 Added notes for release 4.8.33
  release_notes/ocp-4-8-release-notes.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.8

#42475 [enterprise-4.7][BZ1836311]: Change the position of the callout
  modules/graceful-shutdown.adoc
Labels: size/XS

#42539 TELCODOCS-362: D/S Documentation & RN: SDN-2215/MPNETWORK-4:Track Kubernetes NMstate to be GA for the bare metal platform
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS

#42550 BZ-2055147: correcting output of oc get bmh
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#40748 RHDEVDOCS-3283 Document advanced prunning options
  _topic_maps/_topic_map.yml
  cicd/pipelines/automatic-pruning-taskrun-pipelinerun.adoc
  modules/op-annotations-for-automatic-pruning-taskruns-pipelineruns.adoc
Labels: Peer Review Done, lgtm, size/M, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#42143 Hide winc content for OCP rel 4.10 so its OCP 4.10 operator compatible
  _topic_maps/_topic_map.yml
Labels: lgtm, size/M

#40747 RHDEVDOC-2855 Document namespace selector for multi-tenant eventListener
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  modules/op-configuring-eventlisteners-to-serve-multiple-namespaces.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#41489 BZ2044242 corrected path for SELinux context
  modules/ipi-install-creating-an-rhcos-images-cache.adoc
Labels: Peer Review Done, size/XS, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10

#42630 Adds release notes 4.7.44
  release_notes/ocp-4-7-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.7

#42612 Fix typo in feature gates 4.8
  modules/nodes-cluster-enabling-features-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#42559 BZ2055902:Missing permissions - vsphere gap analysis
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42623 BZ-2008919: Fixing device list
  modules/cnf-adjusting-nic-queues-with-the-performance-profile.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42107 ECOPROJECT-5: Documentation for the standalone Node Maintenance Operator
  _topic_maps/_topic_map.yml
  modules/eco-about-node-maintenance-standalone.adoc
  modules/eco-checking_status_of_node_maintenance_cr_tasks.adoc
  modules/eco-maintaining-bare-metal-nodes.adoc
  modules/eco-node-maintenance-operator-installation-cli.adoc
  modules/eco-node-maintenance-operator-installation-web-console.adoc
  modules/eco-resuming-node-from-maintenance-mode-with-cr.adoc
  modules/eco-resuming-node-maintenance-cli.adoc
  modules/eco-setting-node-maintenance-cli.adoc
  modules/eco-setting-node-to-maintenance-mode-with-cr.adoc
  nodes/nodes/eco-node-maintenance-operator.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42659 Remove #TODO note from output.
  distr_tracing/distr_tracing_arch/distr-tracing-architecture.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, distributed tracing

#42631 BZ2030026: BMH status ready changed to available
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10

#42671 [enterprise-4.10] BZBZ2030026: BMH status ready changed to available
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
Labels: size/S

#41972 RHDEVDOCS-3619: Update the creating applications flow as per the latest UI changes
  modules/odc-importing-codebase-from-git-to-create-application.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.10

#42178 CNV-11176: Recommend use of CSI driver for HPP new users
  modules/virt-about-hostpath-provisioner.adoc
  modules/virt-creating-custom-resources-hpp.adoc
  modules/virt-creating-single-pvc-template-storage-pool.adoc
  modules/virt-creating-storage-class.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42574 CNV-13807: RN Linked to KBase article for list of supported guest os
  virt/virt-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, CNV, branch/enterprise-4.10

#42653 A few doc texts
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42613 Fix typo in feature gates 4.9
  modules/nodes-cluster-enabling-features-about.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#42562 BZ-1699472: adds note recommedning OverlayFS and fixes hyperlink
  scaling_performance/optimizing_storage.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-3.11

#42626 OSDOCS-3307: Update 4.8 EOL date for OSD/ROSA
  modules/life-cycle-dates.adoc
Labels: Peer Review Needed, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40380 ECOPROJECT-3- Documentation changes for Poison Pill 4.9
  modules/eco-poison-pill-about-watchdog.adoc
  modules/eco-poison-pill-operator-about.adoc
  modules/eco-poison-pill-operator-installation-cli.adoc
  modules/eco-poison-pill-operator-installation-web-console.adoc
  nodes/nodes/eco-poison-pill-operator.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.9, branch/enterprise-4.10

#41724 ECOPROJECT-250- Documentation changes for NHC 4.10
  modules/eco-node-health-check-operator-about.adoc
  modules/eco-node-health-check-operator-installation-cli.adoc
  nodes/nodes/eco-node-health-check-operator.adoc
Labels: size/M

#41743 Release note for NHC 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: size/XS

#41180 Release note for Poison Pill 4.9
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#41695 OSDOCS-3302: Updating the TechPreviewNoUpdate list in 4.10
  modules/nodes-cluster-enabling-features-about.adoc
  nodes/clusters/nodes-cluster-enabling-features.adoc
Labels: size/M, branch/enterprise-4.10

#42647 MULTIARCH-696 - NMState Operator - Add IBM P/Z to supported platforms
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#42632 [RHDEVDOCS-3620] Document the ability to name a service binding connector
  applications/connecting_applications_to_services/odc-connecting-an-application-to-a-service-using-the-developer-perspective.adoc
  images/odc-sbc-modal.png
Labels: size/S, Dev Tools, branch/enterprise-4.10

#42408 OSDOCS-3278: GPU support for GCP
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-gcp-enabling-gpu-support.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42687 [enterprise-4.10] CNV-11176: Recommend use of CSI driver for HPP new users
  modules/virt-about-hostpath-provisioner.adoc
  modules/virt-creating-custom-resources-hpp.adoc
  modules/virt-creating-single-pvc-template-storage-pool.adoc
  modules/virt-creating-storage-class.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc
Labels: size/L

#42691 Moves RNs up aabove the Getting Started section
  _topic_maps/_topic_map.yml
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42517 BZ2056623: Deploy templates to default namespace
  virt/virt-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, CNV, branch/enterprise-4.10

#41943 OSDOCS-2853: Alibaba Cloud machine management
  _topic_maps/_topic_map.yml
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-alibaba.adoc
  modules/machineset-yaml-alibaba-usage-stats.adoc
  modules/machineset-yaml-alibaba.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42633 BZ2056452: Table description changed to reflect that 4789 is for VXLAN while 6081 is for Geneve.
  modules/installation-network-user-infra.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42690 TELCODOCS-243: D/S Docs & RN: METAL-6 (MPHARDWARE-4/KNIDEPLOY-2108) BIOS Settings Configuration (set values)
  modules/bmo-about-the-firmwareschema-resource.adoc
  modules/bmo-about-the-hostfirmwaresettings-resource.adoc
  modules/bmo-editing-the-hostfirmwaresettings-resource.adoc
  modules/bmo-getting-the-baremetalhost-resource.adoc
  modules/bmo-getting-the-firmwareschema-resource.adoc
  modules/bmo-getting-the-hostfirmwaresettings-resource.adoc
  modules/bmo-verifying-the-hostfirmware-settings-resource-is-valid.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  post_installation_configuration/bare-metal-configuration.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42329 CNV-13531: mdev/vGPU configuration
  _topic_maps/_topic_map.yml
  modules/virt-about-using-virtual-gpus.adoc
  modules/virt-assigning-mediated-device-virtual-machine.adoc
  modules/virt-creating-and-exposing-mediated-devices.adoc
  modules/virt-removing-mediated-device-from-cluster-cli.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-mediated-devices.adoc
Labels: Peer Review Done, size/L, CNV, branch/enterprise-4.10

#38891 OSDOCS-1810: Add MTU configuration change for installed clusters
  _topic_maps/_topic_map.yml
  modules/nw-cluster-mtu-change-about.adoc
  modules/nw-cluster-mtu-change.adoc
  modules/nw-operator-cr.adoc
  networking/changing-cluster-network-mtu.adoc
Labels: Peer Review Done, size/XL, branch/enterprise-4.10

#41269 Document adding namepsace-scoped Helm Chart Repository and Note on disabling Helm for the Multicluster Console (TP)
  applications/working_with_helm_charts/configuring-custom-helm-chart-repositories.adoc
  applications/working_with_helm_charts/understanding-helm.adoc
  images/odc_namespace_helm_chart_repo_filter.png
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
Labels: Peer Review Done, lgtm, size/L, Dev Tools, branch/enterprise-4.10

#41851 OSDOCS-2891: Adding release notes for oc-mirror
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42627 NE-753: Update the branch name
  networking/external_dns_operator/nw-installing-external-dns-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42710 [NE-808]- RN for External DNS Operator
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42445 BZ2056590: Added note block about /dev/disk/by-path not supported for local storage
  modules/persistent-storage-local-create-cr.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42513 Added bugs for RN 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.10

#42341 TELCODOCS-261: Removed Redfish entry as feature won't be in base release
  release_notes/ocp-4-10-release-notes.adoc
Labels: lgtm, size/S

#42655 BZ2037717: Adds clarification about complianceType value
  modules/ztp-the-policygentemplate.adoc
Labels: size/XS

#42368 BZ2057165: added details about mode
  modules/installation-special-config-chrony.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42371 BZ2057165: added details about mode
  modules/installation-special-config-chrony.adoc
Labels: size/XS, branch/enterprise-4.6, branch/enterprise-4.7

#42714 BZ2050796: Removes RHEL versions in Prerequisites section in OSC deploy guide
  modules/sandboxed-containers-preparing-openshift-cluster.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42734 OSDOCS-3245: Reworded a proxy warning
  modules/cluster-wide-proxy.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#39485 OSDOCS-1810: Add release note for cluster network MTU migration
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42682 CNV-16642: Release note text for CNV dashboard
  virt/virt-4-10-release-notes.adoc
Labels: size/XS

#42704 Multiple cards: 4.10 machine mgmt rel notes
  machine_management/creating_machinesets/creating-machineset-alibaba.adoc
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42743 fixing attribute path in a newish file
  machine_management/creating_machinesets/creating-machineset-alibaba.adoc
Labels: Peer Review Done, size/XS

#42701 OSDOCS-3137: Removed a version flag.
  modules/rosa-sts-creating-a-cluster-quickly.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42728 19th batch of bug doc text
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42606 RHDEVDOCS-3667 - OCP 4.10 Monitoring Release Notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/L, qe-approved

#42699 OSDOCS-3032: Removed a customer support line
  modules/understanding-admin-roles.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42597 CNV-14946: placing redirects to prevent CNV from releasing with OCP
  .s2i/httpd-cfg/01-commercial.conf
Labels: Peer Review Done, size/XS, CNV

#42715 BZ2054753: Removes incorrect prerequisite from Installing the OpenShift sandboxed containers Operator using the web console section
  modules/sandboxed-containers-installing-operator-web-console.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42744 Typo Fix for "offset"
  networking/dns-operator.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42578 Update BM IBM Cloud label in TOC
  _topic_maps/_topic_map.yml
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42733 20th batch of RN bug doc text
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42232 Added version requirements to vSphere installation preparation doc
  modules/installation-vsphere-infrastructure.adoc
  snippets/vmware-csi-driver-reqs.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10

#42693 Updating version numbers for 4.10
  modules/about-must-gather.adoc
  modules/architecture-machine-roles.adoc
  modules/cluster-logging-systemd-scaling.adoc
  modules/containers-signature-verify-enable.adoc
  modules/developer-cli-odo-installing-odo-on-linux-rpm.adoc
  modules/gathering-data-specific-features.adoc
  modules/graceful-restart.adoc
  modules/insights-operator-one-time-gather.adoc
  modules/installation-aws-upload-custom-rhcos-ami.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-disk-partitioning-upi-templates.adoc
  modules/installation-disk-partitioning.adoc
  modules/installation-operators-config.adoc
  modules/installation-special-config-butane-create.adoc
  modules/installation-special-config-chrony.adoc
  modules/installation-special-config-kmod.adoc
  modules/installation-special-config-raid.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-user-infra-machines-advanced.adoc
  modules/investigating-kernel-crashes.adoc
  modules/ipi-install-configuring-ntp-for-disconnected-clusters.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/machineconfig-modify-journald.adoc
  modules/nodes-cluster-resource-override-deploy-cli.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nw-enabling-a-provisioning-network-after-installation.adoc
  modules/nw-ingress-converting-http-header-case.adoc
  modules/nw-sriov-cfg-bond-interface-with-virtual-functions.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/oauth-configuring-token-inactivity-timeout.adoc
  modules/olm-catalogsource-image-template.adoc
  modules/psap-driver-toolkit-pulling.adoc
  modules/rhcos-load-firmware-blobs.adoc
  modules/update-upgrading-cli.adoc
  modules/viewing-the-image-pull-source.adoc
  modules/virt-binding-devices-vfio-driver.adoc
  modules/ztp-acm-adding-images-to-mirror-registry.adoc
  modules/ztp-creating-siteconfig-custom-resources.adoc
  modules/ztp-creating-the-siteconfig-custom-resources.adoc
  modules/ztp-preparing-the-hub-cluster-for-ztp.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42747 BZ2050796: Removes RHEL versions in Prerequisites section in OSC deploy guide
  modules/sandboxed-containers-preparing-openshift-cluster.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#42320 OSDOCS-3001: Added Day 2 information for proxies
  modules/cluster-wide-proxy-updates.adoc
  modules/cluster-wide-proxy.adoc
  networking/configuring-cluster-wide-proxy.adoc
Labels: size/L, branch/enterprise-4.9, branch/enterprise-4.10

#42748 [enterprise-4.10] BZ-2055147-410: correcting output of oc get bmh
  modules/ipi-install-preparing-the-bare-metal-node.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
Labels: size/S

#42759 Update to reflect Ali Cloud TP status in 4.10
  modules/cluster-cloud-controller-manager-operator.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42695 TELCODOCS 243: Release Notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/S, branch/enterprise-4.10

#41754 Release note for Poison Pill 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42771 Fixing some typos
  modules/azure-stack-hub-internal-ca.adoc
  modules/bmo-about-the-baremetalhost-resource.adoc
  modules/eco-poison-pill-operator-about.adoc
  modules/installation-azure-user-infra-uploading-rhcos.adoc
  modules/kube-apiserver-operator.adoc
  modules/machineset-gcp-enabling-gpu-support.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/serverless-autoscaling-dashboard-navigating.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42773 [enterprise-4.9] Fixing some typos
  modules/eco-poison-pill-operator-about.adoc
  modules/installation-azure-user-infra-uploading-rhcos.adoc
  modules/kube-apiserver-operator.adoc
  modules/serverless-autoscaling-dashboard-navigating.adoc
Labels: size/S

#42774 [enterprise-4.8] Fixing some typos
  modules/eco-poison-pill-operator-about.adoc
  modules/kube-apiserver-operator.adoc
  modules/serverless-autoscaling-dashboard-navigating.adoc
Labels: size/S

#42775 [enterprise-4.7] Fixing some typos
  modules/kube-apiserver-operator.adoc
  modules/serverless-autoscaling-dashboard-navigating.adoc
Labels: size/XS

#42776 [enterprise-4.6] Fixing some typos
  modules/kube-apiserver-operator.adoc
  modules/serverless-autoscaling-dashboard-navigating.adoc
Labels: size/XS

#42783 OSDOCS-3315: urgent change: ROSA upgrade prep CLI version
  modules/rosa-upgrading-preparing-4-8-to-4-9.adoc
Labels: size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#40136 [OSDOCS-3064] Allow strict anti-affinity for servers at install time - ShiftStack
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-osp-default-deployment.adoc
  modules/installation-osp-default-kuryr-deployment.adoc
  modules/installation-osp-setting-worker-affinity.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42769 OSDOCS-2691: Fixing some post merge typos and style guide issues
  _topic_maps/_topic_map.yml
  getting_started/openshift-cli.adoc
  getting_started/openshift-overview.adoc
  getting_started/openshift-web-console.adoc
  modules/getting-started-cli-connecting-a-database.adoc
  modules/getting-started-cli-creating-new-project.adoc
  modules/getting-started-cli-creating-route.adoc
  modules/getting-started-cli-creating-secret.adoc
  modules/getting-started-cli-deploying-first-image.adoc
  modules/getting-started-cli-deploying-python-app.adoc
  modules/getting-started-cli-examining-pod.adoc
  modules/getting-started-cli-granting-permissions.adoc
  modules/getting-started-cli-load-data-output.adoc
  modules/getting-started-cli-login.adoc
  modules/getting-started-cli-scaling-app.adoc
  modules/getting-started-openshift-common-terms.adoc
  modules/getting-started-web-console-connecting-a-database.adoc
  modules/getting-started-web-console-creating-new-project.adoc
  modules/getting-started-web-console-creating-secret.adoc
  modules/getting-started-web-console-deploying-first-image.adoc
  modules/getting-started-web-console-deploying-python-app.adoc
  modules/getting-started-web-console-examining-pod.adoc
  modules/getting-started-web-console-granting-permissions.adoc
  modules/getting-started-web-console-load-data-output.adoc
  modules/getting-started-web-console-login.adoc
  modules/getting-started-web-console-scaling-app.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42725 RHDEVDOCS-3829 Additional ODC release notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.10

#38258 Storage 4.10 Rel Notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42635 BZ2037544: Clarifies how to get nodeLabel and nodeName
  modules/nw-ptp-configuring-linuxptp.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.8

#42634 BZ2037544: Clarifies how to get nodeLabel and nodeName
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42313 RHDEVDOCS-3589: understanding odo
  cli_reference/developer_cli_odo/attributes
  cli_reference/developer_cli_odo/understanding-odo.adoc
  modules/odo-core-concepts.adoc
  modules/odo-key-features.adoc
  modules/odo-listing-components.adoc
  modules/odo-telemetry.adoc
Labels: Peer Review Done, lgtm, size/L, branch/enterprise-4.6, Dev Tools, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42789 [enterprise-4.10]OSDOCS-2691: Fixing some post merge typos and style guide issues
  _topic_maps/_topic_map.yml
  getting_started/openshift-cli.adoc
  getting_started/openshift-overview.adoc
  getting_started/openshift-web-console.adoc
  modules/getting-started-cli-connecting-a-database.adoc
  modules/getting-started-cli-creating-new-project.adoc
  modules/getting-started-cli-creating-route.adoc
  modules/getting-started-cli-creating-secret.adoc
  modules/getting-started-cli-deploying-first-image.adoc
  modules/getting-started-cli-deploying-python-app.adoc
  modules/getting-started-cli-examining-pod.adoc
  modules/getting-started-cli-granting-permissions.adoc
  modules/getting-started-cli-load-data-output.adoc
  modules/getting-started-cli-login.adoc
  modules/getting-started-cli-scaling-app.adoc
  modules/getting-started-openshift-common-terms.adoc
  modules/getting-started-web-console-connecting-a-database.adoc
  modules/getting-started-web-console-creating-new-project.adoc
  modules/getting-started-web-console-creating-secret.adoc
  modules/getting-started-web-console-deploying-first-image.adoc
  modules/getting-started-web-console-deploying-python-app.adoc
  modules/getting-started-web-console-examining-pod.adoc
  modules/getting-started-web-console-granting-permissions.adoc
  modules/getting-started-web-console-load-data-output.adoc
  modules/getting-started-web-console-login.adoc
  modules/getting-started-web-console-scaling-app.adoc
Labels: size/L, branch/enterprise-4.10

#42780 BZ2029731: add unique VM name requirement for vSphere UPI
  modules/installation-machine-requirements.adoc
  modules/installation-vsphere-machines.adoc
  modules/machine-vsphere-machines.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.10

#42804 BZ2037544: Clarifies how to get nodeLabel and nodeName
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
Labels: size/XS, branch/enterprise-4.9

#42685 OSDOCS-2329: Rel Notes for GCP Workload Identity
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42757 JIRA-OSDOCS3069: Corrected the IOPS for Infrastructure and Worker nodes
  modules/ccs-aws-provisioned.adoc
  modules/rosa-aws-provisioned.adoc
Labels: Peer Review Done, size/S, branch/enterprise-4.9, branch/enterprise-4.10

#42790 BZ2025230: small BZ RN text tweak
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42754 JIRA-OSDOCS3185: Removed sentence about creating cluster from AWS console
  modules/rosa-understanding.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#41968 CCXDEV-7143 Assessing and managing issues with advisor
  modules/disabling-insights-advisor-recommendations.adoc
  modules/displaying-all-insights-advisor-recommendations.adoc
  modules/displaying-potential-issues-with-your-cluster.adoc
  modules/displaying-the-insights-status-in-the-web-console.adoc
  modules/enabling-insights-advisor-recommendations.adoc
  support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42766 JIRA-OSDOCS3169: Added hyperlink to RWX KB article
  modules/rosa-sdpolicy-storage.adoc
  modules/sdpolicy-storage.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10

#42315 OSDOCS-2932: OSDK-1760: digest bundle for disconnected environments
  modules/olm-enabling-operator-restricted-network.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42081 RHDEVDOCS-3701 - Remove warning in monitoring scalability topic
  scalability_and_performance/scaling-cluster-monitoring-operator.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42796 BZ2060714: monitoring: Fix example writeRelabelConfig field name in remoteWrite …
  modules/monitoring-configuring-remote-write.adoc
Labels: Peer Review Done, lgtm, size/XS, Dev Tools, branch/enterprise-4.9, branch/enterprise-4.10

#42346 Adding a new openshift-dpu distro
  _distro_map.yml
  _templates/_page_openshift.html.erb
  _topic_maps/_topic_map.yml
Labels: Peer Review Done, size/S

#39641 [BZ1810461] ShiftStack - Add procedure to allow Image Registry Operator to trust Swift
  _topic_maps/_topic_map.yml
  modules/registry-configuring-registry-storage-swift-trust.adoc
  registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.10

#42124 Updating the TechPreviewNoUpdate list in 4.7
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.7

#42125 Updating the TechPreviewNoUpdate list in 4.6
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-cluster-enabling-features-cli.adoc
  modules/nodes-cluster-enabling-features-console.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.6

#42648 OSDOCS-3192: vSphere install requirements (adding to storage content area)
  modules/persistent-storage-csi-vsphere-install-issues.adoc
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
Labels: Peer Review Needed, size/S, branch/enterprise-4.10

#42844 Adding known issue and workaround for oc-mirror
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42765 Adds and updates the GA status tracker
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.10

#42670 OSDOCS-2950: Adding support default IPI cluster installation to Azure…
  _topic_maps/_topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  modules/cluster-entitlements.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-azure-stack-hub-config-yaml.adoc
  modules/installation-azure-user-infra-uploading-rhcos.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/manually-create-identity-access-management.adoc
  modules/nw-modifying-operator-install-config.adoc
  modules/nw-network-config.adoc
  modules/nw-operator-cr.adoc
Labels: size/L, branch/enterprise-4.10

#42848 [enterprise-4.10] Adding a new openshift-dpu distro
  _topic_maps/_topic_map.yml
Labels: size/XS

#42835 [enterprise-4.8] OSS-Docs-32: Removed instances of OCM
  _attributes/common-attributes.adoc
  _attributes/distr-tracing-document-attributes.adoc
  _attributes/jaeger-document-attributes.adoc
  _attributes/ossm-document-attributes-1x.adoc
  _attributes/ossm-document-attributes.adoc
  cicd/pipelines/installing-pipelines.adoc
  cloud_infrastructure_access/dedicated-aws-access.adoc
  cloud_infrastructure_access/dedicated-aws-private-cluster.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/validating-an-installation.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-telemetry.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-cluster-admin-enable.adoc
  modules/dedicated-cluster-admin-grant.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/dedicated-enable-private-cluster-existing.adoc
  modules/dedicated-enable-private-cluster-new.adoc
  modules/dedicated-enable-public-cluster.adoc
  modules/dedicated-managing-dedicated-administrators.adoc
  modules/dedicated-scaling-your-cluster.adoc
  modules/displaying-potential-issues-with-your-cluster.adoc
  modules/displaying-the-insights-status-in-the-web-console.adoc
  modules/generating-icsp-object-scoped-to-a-registry.adoc
  modules/images-update-global-pull-secret.adoc
  modules/insights-operator-about.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-mirror-repository.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-process.adoc
  modules/installation-rhv-creating-install-config-file.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/migration-configuring-mcg.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-pods-vertical-autoscaler-install.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  modules/psap-driver-toolkit-pulling.adoc
  modules/reviewing-cluster-status-from-the-openshift-cluster-manager.adoc
  modules/support.adoc
  modules/telemetry-consequences-of-disabling-telemetry.adoc
  modules/update-service-mirror-release.adoc
  modules/ztp-the-gitops-approach.adoc
  openshift_images/managing_images/using-image-pull-secrets.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
  support/index.adoc
  support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.8

#42837 OSS-Docs-32: Removed instances of OCM
  _attributes/common-attributes.adoc
  _attributes/distr-tracing-document-attributes.adoc
  _attributes/jaeger-document-attributes.adoc
  _attributes/ossm-document-attributes-1x.adoc
  _attributes/ossm-document-attributes.adoc
  cicd/pipelines/installing-pipelines.adoc
  cloud_infrastructure_access/dedicated-aws-access.adoc
  cloud_infrastructure_access/dedicated-aws-private-cluster.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/validating-an-installation.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-telemetry.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-cluster-admin-enable.adoc
  modules/dedicated-cluster-admin-grant.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/dedicated-enable-private-cluster-existing.adoc
  modules/dedicated-enable-private-cluster-new.adoc
  modules/dedicated-enable-public-cluster.adoc
  modules/dedicated-managing-dedicated-administrators.adoc
  modules/dedicated-scaling-your-cluster.adoc
  modules/displaying-potential-issues-with-your-cluster.adoc
  modules/displaying-the-insights-status-in-the-web-console.adoc
  modules/generating-icsp-object-scoped-to-a-registry.adoc
  modules/images-update-global-pull-secret.adoc
  modules/insights-operator-about.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-mirror-repository.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-process.adoc
  modules/installation-rhv-creating-install-config-file.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/migration-configuring-mcg.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-pods-vertical-autoscaler-install.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  modules/reviewing-cluster-status-from-the-openshift-cluster-manager.adoc
  modules/support.adoc
  modules/telemetry-consequences-of-disabling-telemetry.adoc
  modules/update-service-mirror-release.adoc
  openshift_images/managing_images/using-image-pull-secrets.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
  support/index.adoc
  support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.7

#42850 OSS-Docs-32: Removed instances of OCM
  _attributes/common-attributes.adoc
  _attributes/distr-tracing-document-attributes.adoc
  _attributes/jaeger-document-attributes.adoc
  _attributes/ossm-document-attributes-1x.adoc
  _attributes/ossm-document-attributes.adoc
  cloud_infrastructure_access/dedicated-aws-access.adoc
  cloud_infrastructure_access/dedicated-aws-private-cluster.adoc
  contributing_to_docs/doc_guidelines.adoc
  installing/validating-an-installation.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-logging-deploy-cli.adoc
  modules/cluster-logging-deploy-console.adoc
  modules/cluster-telemetry.adoc
  modules/dedicated-accessing-your-cluster.adoc
  modules/dedicated-cluster-admin-enable.adoc
  modules/dedicated-cluster-admin-grant.adoc
  modules/dedicated-creating-your-cluster.adoc
  modules/dedicated-enable-private-cluster-existing.adoc
  modules/dedicated-enable-private-cluster-new.adoc
  modules/dedicated-enable-public-cluster.adoc
  modules/dedicated-managing-dedicated-administrators.adoc
  modules/dedicated-scaling-your-cluster.adoc
  modules/displaying-potential-issues-with-your-cluster.adoc
  modules/generating-icsp-object-scoped-to-a-registry.adoc
  modules/images-update-global-pull-secret.adoc
  modules/insights-operator-about.adoc
  modules/installation-adding-registry-pull-secret.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-mirror-repository.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-rhv-creating-install-config-file.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/migration-configuring-mcg.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-descheduler-installing.adoc
  modules/nodes-pods-vertical-autoscaler-install.adoc
  modules/olm-installing-operators-from-operatorhub-configure.adoc
  modules/reviewing-cluster-status-from-the-openshift-cluster-manager.adoc
  modules/support.adoc
  modules/telemetry-consequences-of-disabling-telemetry.adoc
  modules/update-service-mirror-release.adoc
  openshift_images/managing_images/using-image-pull-secrets.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
  support/index.adoc
  support/remote_health_monitoring/using-insights-to-identify-issues-with-your-cluster.adoc
  welcome/oke_about.adoc
Labels: Peer Review Done, size/L, branch/enterprise-4.6

#42851 GH42529: Typo in GC headings
  modules/nodes-nodes-garbage-collection-containers.adoc
  modules/nodes-nodes-garbage-collection-images.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.6, branch/enterprise-4.7, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#41323 OSDOCS-1694 Add mutable Ingress Controller endpoint publishing strategy release note
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.10

#42764 SRVKS-852: Add additional knative serving admin config docs
  modules/serverless-kourier-gateway-service-type.adoc
  modules/serverless-rn-1-21-0.adoc
  modules/serverless-url-scheme-external-routes.adoc
  serverless/admin_guide/knative-serving-CR-config.adoc
  serverless/serverless-release-notes.adoc
Labels: Peer Review Done, size/M, branch/enterprise-4.6, Serverless, branch/enterprise-4.7, qe-approved, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10

#42784 BZ2059762: Adds known issue to 4.9.23 release notes
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, lgtm, size/XS, branch/enterprise-4.10

#42859 [enterprise-4.6] SRVKS-852: Add additional knative serving admin config docs
  modules/serverless-kourier-gateway-service-type.adoc
  modules/serverless-rn-1-21-0.adoc
  modules/serverless-url-scheme-external-routes.adoc
  serverless/admin_guide/knative-serving-CR-config.adoc
Labels: size/M

#42860 [enterprise-4.7] SRVKS-852: Add additional knative serving admin config docs
  modules/serverless-kourier-gateway-service-type.adoc
  modules/serverless-rn-1-21-0.adoc
  modules/serverless-url-scheme-external-routes.adoc
  serverless/admin_guide/knative-serving-CR-config.adoc
Labels: size/M

#42862 [enterprise-4.8] SRVKS-852: Add additional knative serving admin config docs
  modules/serverless-kourier-gateway-service-type.adoc
  modules/serverless-rn-1-21-0.adoc
  modules/serverless-url-scheme-external-routes.adoc
  serverless/admin_guide/knative-serving-CR-config.adoc
Labels: size/M

#42861 Fixes a few issues with Olivia's PR
  release_notes/ocp-4-9-release-notes.adoc
Labels: Peer Review Done, size/XS, branch/enterprise-4.9

#42865 TELCODOCS:518 - Creating template for sandboxed containers release no…
  _topic_maps/_topic_map.yml
  sandboxed_containers/sandboxed-containers-4.9-release-notes.adoc
  sandboxed_containers/sandboxed-containers-release-notes.adoc
Labels: size/L

#42867 RHDEVDOCS-3237: Document configuring the access to product devfiles
  applications/creating_applications/odc-creating-applications-using-developer-perspective.adoc
  modules/odc-using-the-devfile-registry.adoc
Labels: Peer Review Done, lgtm, size/S, Dev Tools, branch/enterprise-4.10

#42794 ECOPORJECT-201: Documentation for the Poison Pill Operator for 4.10
  modules/eco-poison-pill-operator-about.adoc
Labels: Peer Review Done, lgtm, size/M, branch/enterprise-4.10

#42692 OSDOCS-3233: Rel Note for Azure minting removal
  release_notes/ocp-4-10-release-notes.adoc
Labels: Peer Review Needed, size/M, branch/enterprise-4.10
