Repository openshift/openshift-docs, pull requests merged in 2023-04, with the labels that each got.

#57600 [OSDOCS-5554]: UPI VMware MachineSet reqs/proc
  _topic_maps/_topic_map.yml
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  machine_management/user_infra/adding-compute-user-infra-general.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  modules/compute-machineset-upi-reqs.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/machine-user-provisioned-limitations.adoc
  modules/machineset-creating.adoc
  modules/machineset-upi-reqs-ignition-config.adoc
  modules/machineset-upi-reqs-infra-id.adoc
  modules/machineset-upi-reqs-vsphere-creds.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58013 Add TP note to "Monitoring overview" page
  virt/support/monitoring/virt-monitoring-overview.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.13

#56937 ROX-14549: Explaining Red Hat SSO configuration in ACS Console
  _topic_map.yml
  installing/getting-started-rhacs-cloud-ocp.adoc
  operating/manage-user-access/configuring-identity-providers/configure-google-workspace-identity.adoc
  operating/manage-user-access/configuring-identity-providers/configure-ocp-oauth.adoc
  operating/manage-user-access/configuring-identity-providers/configure-okta-identity-cloud.adoc
  operating/manage-user-access/configuring-identity-providers/connecting-azure-ad-to-rhacs-using-sso-configuration.adoc
  operating/manage-user-access/understanding-authentication-providers.adoc
Labels: peer-review-done, size/L, RHACS, rhacs-docs-3.74, jira/valid-reference, rhacs-docs-4.0

#57764 RHDEVDOCS-5069: Adding 4.13 version to GitOps v1.8 RN after OCP 4.13 …
  modules/gitops-release-notes-1-8-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#57039 HPA with custom metrics typo, 4.10, 4.11 & 4.12
  modules/nodes-pods-autoscaling-custom-creating-trigger-auth.adoc
  modules/nodes-pods-autoscaling-custom-creating-workload.adoc
  modules/nodes-pods-autoscaling-custom-trigger-auth.adoc
  modules/nodes-pods-autoscaling-custom-trigger.adoc
Labels: size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58131 Revert "RHDEVDOCS-5069: Adding 4.13 version to GitOps v1.8 RN after OCP 4.13 …"
  modules/gitops-release-notes-1-8-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/XS, jira/valid-reference

#58132 Revert "[enterprise-4.10] RHDEVDOCS-5069: Adding 4.13 version to GitOps v1.8 RN after OCP 4.13 …"
  modules/gitops-release-notes-1-8-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/XS, jira/valid-reference

#58134 Revert "[enterprise-4.11] RHDEVDOCS-5069: Adding 4.13 version to GitOps v1.8 RN after OCP 4.13 …"
  modules/gitops-release-notes-1-8-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/XS, jira/valid-reference

#58133 Revert "[enterprise-4.12] RHDEVDOCS-5069: Adding 4.13 version to GitOps v1.8 RN after OCP 4.13 …"
  modules/gitops-release-notes-1-8-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/XS, jira/valid-reference

#58110 Windows driver checkbox
  virt/virt-web-console-overview.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.13

#56878 TELCODOCS-654: updating procedure to make it work for IPI baremetal installs
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58091 Updated EUS module to be version-agnostic
  modules/updating-eus-to-eus-upgrade.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58008 OCPBUGS#8378: Change the value for the type field
  modules/nodes-pods-autoscaling-creating-memory.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#58158 [enterprise-4.11] [OSDOCS-5554]: UPI VMware MachineSet reqs/proc
  _topic_maps/_topic_map.yml
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  machine_management/user_infra/adding-compute-user-infra-general.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  modules/compute-machineset-upi-reqs.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/machine-user-provisioned-limitations.adoc
  modules/machineset-creating.adoc
  modules/machineset-upi-reqs-ignition-config.adoc
  modules/machineset-upi-reqs-infra-id.adoc
  modules/machineset-upi-reqs-vsphere-creds.adoc
Labels: size/L

#58159 [enterprise-4.10] [OSDOCS-5554]: UPI VMware MachineSet reqs/proc
  _topic_maps/_topic_map.yml
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  machine_management/user_infra/adding-compute-user-infra-general.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  modules/compute-machineset-upi-reqs.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/machine-user-provisioned-limitations.adoc
  modules/machineset-creating.adoc
  modules/machineset-upi-reqs-ignition-config.adoc
  modules/machineset-upi-reqs-infra-id.adoc
  modules/machineset-upi-reqs-vsphere-creds.adoc
Labels: size/L

#58160 [enterprise-4.9] [OSDOCS-5554]: UPI VMware MachineSet reqs/proc
  _topic_maps/_topic_map.yml
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  machine_management/user_infra/adding-compute-user-infra-general.adoc
  machine_management/user_infra/adding-vsphere-compute-user-infra.adoc
  modules/compute-machineset-upi-reqs.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/machine-user-provisioned-limitations.adoc
  modules/machineset-creating.adoc
  modules/machineset-upi-reqs-ignition-config.adoc
  modules/machineset-upi-reqs-infra-id.adoc
  modules/machineset-upi-reqs-vsphere-creds.adoc
Labels: size/L

#57452 TELCODOCS-1052: Added requirements for installing an SNO cluster on AWS.
  installing/installing_aws/preparing-to-install-on-aws.adoc
  installing/installing_sno/install-sno-installing-sno.adoc
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
  modules/install-sno_additional-requirements-for-installing-on-a-single-node-on-aws.adoc
  modules/installation-aws_con_installing-sno-on-aws.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#57448 OSDOCS-5459: Adding note of plans for PSA restricted enforcement
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.13

#57245 OCPBUGS2214: Deploying an extension rpm with a MachineConfig and a custom osImage at the same time breaks the machine config pool
  post_installation_configuration/coreos-layering.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#58112 OSDOCS#5116: Updating image for remote workers support for vSphere
  images/325_OpenShift_vSphere_Deployment_updates_0323.png
Labels: peer-review-done, size/XS

#57916 Update OCP-4-13-release-notes for Developer Perspective: New Features
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, dev-tools, qe-approved, branch/enterprise-4.13

#57766 TELCODOCS-1232: Remove duplicated field macAddress from Siteconfigs
  snippets/ztp-example-siteconfig.adoc
Labels: size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#57999 OCPBUG#10383: Added a note to clarify the time taken during the start of an upgrade.
  modules/upgrade.adoc
  upgrading/rosa-upgrading.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55929 CNV-23823: QEMU and VirtIO updates
  _topic_maps/_topic_map.yml
  modules/virt-about-virtio-drivers.adoc
  modules/virt-adding-virtio-drivers-vm-yaml.adoc
  modules/virt-installing-qemu-guest-agent-on-linux-vm.adoc
  modules/virt-installing-qemu-guest-agent-on-windows-vm.adoc
  modules/virt-installing-virtio-drivers-existing-windows.adoc
  modules/virt-installing-virtio-drivers-installing-windows.adoc
  modules/virt-removing-virtio-disk-from-vm.adoc
  modules/virt-supported-virtio-drivers.adoc
  virt/virtual_machines/virt-installing-qemu-guest-agent.adoc
  virt/virtual_machines/virt-installing-virtio-drivers-on-existing-windows-vm.adoc
  virt/virtual_machines/virt-installing-virtio-drivers-on-new-windows-vm.adoc
  virt/virtual_machines/virtual_disks/virt-managing-vm-snapshots.adoc
Labels: peer-review-done, size/L, merge-review-needed, jira/valid-reference

#58101 OSDOCS-5673: Greenboot release note
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#57514 CNV-23499: 4.10+ HPP CSI only (4.13 RN repeat)
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, jira/valid-reference

#57355 CNV-23499: 4.10+ HPP CSI only (4.12 RN update)
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#57511 OSDOCS-5545: guidance for updating to a new minor version
  modules/understanding-upgrade-channels.adoc
  modules/update-upgrading-cli.adoc
  modules/update-upgrading-web.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#57887 OSDOCS-10288: Update Domain Names
  modules/osd-applications-config-custom-domains.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13

#56723 OSDOCS-4810: Added module for deleting AWS LZ cluster
  installing/installing_aws/installing-aws-localzone.adoc
  installing/installing_aws/uninstalling-cluster-aws.adoc
  modules/installation-aws-delete-cluster.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#57954 OSDOCS-5647 z-stream release notes 4.11.34
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed

#57369 document V2 limitation for CPU pinning
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-understanding-low-latency.adoc
  modules/node-tuning-operator.adoc
  modules/nodes-clusters-cgroups-2.adoc
  scalability_and_performance/cnf-create-performance-profiles.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13

#57832 Remove RuntimeRequestTimeout from list of Kubernetes options that cannot be set
  modules/nodes-nodes-managing-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#57087 typo: cgroup_no_vi should be cgroup_no_v1
  modules/nodes-clusters-cgroups-2.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#58227 [enterprise-4.12]CP-OCPBUGS10029: correct cluster access modules MicroShift
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  modules/microshift-accessing-cluster-locally.adoc
  modules/microshift-accessing-cluster-open-firewall.adoc
  modules/microshift-accessing-cluster-remotely-non-admin.adoc
  modules/microshift-accessing-cluster-remotely.adoc
  modules/microshift-accessing.adoc
  modules/microshift-install-rpm-preparing.adoc
Labels: size/L, branch/enterprise-4.12

#58224 [enterprise-4.10]OSDOCS-5545: manual CP of #57511
  modules/understanding-upgrade-channels.adoc
  modules/update-upgrading-cli.adoc
  modules/update-upgrading-web.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: size/M, branch/enterprise-4.10, jira/valid-reference

#58222 [enterprise-4.11]OSDOCS-5545: manual CP of #57511
  modules/understanding-upgrade-channels.adoc
  modules/update-upgrading-cli.adoc
  modules/update-upgrading-web.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: size/M, branch/enterprise-4.11, jira/valid-reference

#57904 Add europe-west12 GCP region as supported region
  modules/installation-gcp-regions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#58200 OSDOCS-5367:adds console bugs to RNs for 4.13 GA
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56274 OSDOCS#5384: Document the explicit list of required credential permissions for Azure
  installing/installing_azure/installing-azure-account.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  modules/installation-azure-create-resource-group-and-identity.adoc
  modules/installation-azure-finalizing-encryption.adoc
  modules/installation-azure-permissions.adoc
  modules/installation-azure-service-principal.adoc
  modules/minimum-required-permissions-ipi-azure.adoc
  modules/minimum-required-permissions-upi-azure.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58166 Fixing heading levels that were out of order
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#58024 Telcodocs 992: deploying modules and creating a multiloader image
  hardware_enablement/kmm-kernel-module-management.adoc
  modules/kmm-building-in-cluster.adoc
  modules/kmm-creating-module-cr.adoc
  modules/kmm-creating-moduleloader-image.adoc
  modules/kmm-deploying-modules.adoc
  modules/kmm-example-module-cr.adoc
  modules/kmm-running-depmod.adoc
  modules/kmm-security.adoc
  modules/kmm-using-driver-toolkit.adoc
  modules/virt-prerequisites-mediated-devices.adoc
Labels: size/L, telco, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#57884 RHDEVDOCS-4849-monitoring-4.13-RN-new-features
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, dev-tools, qe-approved, branch/enterprise-4.13

#58070 OSDOCS-5667: microshift release notes about OS and container runtime support
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58249 Bump OMR version to 385
  modules/mirror-registry-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58255 Revert "OCPBUGS#5449: Change the cluster MTU"
  modules/nw-cluster-mtu-change.adoc
Labels: size/L, merge-review-in-progress

#57336 OSDOCS#5550: Add release notes for minimum required permissions for Azure
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#57044 TELCODOCS-1077: Add LVM Storage in far edge content
  modules/ztp-lvms-installing-lvms-cli.adoc
  modules/ztp-lvms-installing-lvms-web-console.adoc
  modules/ztp-sno-du-configuring-lvms.adoc
  scalability_and_performance/ztp_far_edge/ztp-manual-install.adoc
  scalability_and_performance/ztp_far_edge/ztp-reference-cluster-configuration-for-vdu.adoc
  snippets/ztp-storage-lvms.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#57392 ML-RHDEVDOCS-3382: Updated the Pipeline builder instances
  cicd/pipelines/working-with-pipelines-using-the-developer-perspective.adoc
  modules/cnf-installing-numa-resources-operator-cli.adoc
  modules/nw-ptp-installing-operator-web-console.adoc
  modules/nw-rfhe-installing-operator-web-console.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-editing-pipelines.adoc
  modules/op-opting-out-of-tekton-hub-in-the-developer-perspective.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/op-using-custom-pipeline-template-for-git-import.adoc
  modules/ztp-configuring-cluster-policies.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#57893 OSDOCS-4864: Updating CLI ref docs for 4.13
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.13

#57736 OSDOCS-5605: Added a module to detail AWS LZ cluster limitations
  installing/installing_aws/installing-aws-localzone.adoc
  modules/cluster-limitations-local-zone.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58016 CNV-25574: Release note: NEW - UI - Ability to make a hot-plug disk part of the VM
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#57960 CNV-25138: storage volume requirements/removing assembly
  _topic_maps/_topic_map.yml
  modules/virt-about-storage-volumes-for-vm-disks.adoc
  modules/virt-features-for-storage-matrix.adoc
  virt/about-virt.adoc
  virt/install/preparing-cluster-for-virt.adoc
  virt/virt-getting-started.adoc
  virt/virtual_machines/virtual_disks/virt-features-for-storage.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.13

#58049 [enterprise-4.13] OSDOCS-5611: add ssh key location
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.13

#58257 CNV: Commenting out about-virt placeholder
  virt/about-virt.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.13

#58171 [enterprise-4.13] OSDOCS-5676: add lsof rn entry
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.13

#58223 Typo fix: Removed duplicate paragraph
  scalability_and_performance/scaling-worker-latency-profiles.adoc
  snippets/worker-latency-profile-intro.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58065 OSDOCS-3905 ROSA what's new page updates
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-update-cli-tool.adoc
  rosa_release_notes/rosa-release-notes.adoc
  rosa_release_notes/whats-new-template.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, branch/enterprise-4.13

#57079 OSDOCS-5509 Update Customer Cloud Subscription AWS Accounts
  modules/ccs-aws-iam.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#58140 [SRVCOM-2222] Add Serverless 1.28.0 release notes, update feature tables
  modules/serverless-deprecated-removed-features.adoc
  modules/serverless-functions-creating-on-cluster-builds.adoc
  modules/serverless-rn-1-28-0.adoc
  modules/serverless-tech-preview-features.adoc
  serverless/functions/serverless-developing-nodejs-functions.adoc
  serverless/functions/serverless-developing-typescript-functions.adoc
  serverless/serverless-release-notes.adoc
Labels: peer-review-done, lgtm, size/L, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#57324 OSDOCS-5442: add info on lvmd and ovn yaml files
  microshift_storage/microshift-storage-plugin-overview.adoc
  modules/microshift-configuring-ovn.adoc
  modules/microshift-lvmd-yaml-creating.adoc
  modules/microshift-lvms-configuring.adoc
  modules/microshift-lvms-deployment.adoc
  modules/microshift-lvms-setting-path.adoc
  modules/microshift-lvms-system-requirements.adoc
  modules/microshift-lvms-using.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58299 [enterprise-4.12]CP-OSDOCS-5442: add info on lvmd and ovn yaml files
  microshift_storage/microshift-storage-plugin-overview.adoc
  modules/microshift-configuring-ovn.adoc
  modules/microshift-lvmd-yaml-creating.adoc
  modules/microshift-lvms-configuring.adoc
  modules/microshift-lvms-deployment.adoc
  modules/microshift-lvms-setting-path.adoc
  modules/microshift-lvms-system-requirements.adoc
  modules/microshift-lvms-using.adoc
Labels: size/L, jira/valid-reference

#58228 TELCODOCS-1242: [Doc Bug] Short secret name while following worker scale-up for agent-based clusters
  modules/sno-adding-worker-nodes-to-sno-clusters-manually.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56794 OSDOCS#5303: Add OLM multitenancy doc
  _topic_maps/_topic_map.yml
  modules/olm-colocation-namespaces.adoc
  modules/olm-default-install-behavior.adoc
  modules/olm-installing-global-namespaces.adoc
  modules/olm-multitenancy-solution.adoc
  modules/olm-operatorgroups-limitations.adoc
  modules/olm-preparing-multitenant-operators.adoc
  modules/olm-terms.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/understanding/olm-multitenancy.adoc
  operators/understanding/olm/olm-understanding-dependency-resolution.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  operators/understanding/olm/olm-understanding-operatorgroups.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58208 OSDOCS-4336: Content audit for Requesting CRI-O and Kubelet profiling data by using the Node Observability Operator
  modules/node-observability-install-cli.adoc
  modules/node-observability-run-profiling-query.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#57765 OSDOCS#5615: Adding prereq for a restricted OCP cluster on GCP
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#58240 OCPBUGS#5449: Change the cluster MTU
  modules/nw-cluster-mtu-change.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58236 Update OCP-4-13-release-notes for Developer Perspective: Known Issue
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.13

#58312 OCPBUGS#9158: Change the default value of coresPerSocket
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#58034 OCPBUG#11043: Corrected the command related to oc-mirror.
  modules/oc-mirror-installing-plugin.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58313 OCPBUGS#9375: Add csi ephemeral volumes
  modules/security-context-constraints-about.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.13

#57841 OCPBUGS#10911: Change the heading
  modules/nw-ovn-kubernetes-examine-sb-database-contents-ref.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#58066 OCPBUGS#9090: A service principal validity can be extended
  modules/installation-azure-service-principal.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58157 OSDOCS-5644:adds 4.9.49 to RNs
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9, merge-review-in-progress, jira/valid-reference

#58245 [SRVCOM-2105] Serverless: s/v1alpha/v1beta1 in examples
  modules/knative-serving-CR-system-deployments.adoc
  modules/knative-serving-controller-custom-certs-secrets.adoc
  modules/serverless-admin-init-containers.adoc
  modules/serverless-channel-default.adoc
  modules/serverless-config-emptydir.adoc
  modules/serverless-config-replicas-eventing.adoc
  modules/serverless-config-replicas-serving.adoc
  modules/serverless-enable-scale-to-zero.adoc
  modules/serverless-https-redirect-global.adoc
  modules/serverless-install-eventing-yaml.adoc
  modules/serverless-install-serving-yaml.adoc
  modules/serverless-jaeger-config.adoc
  modules/serverless-open-telemetry.adoc
  modules/serverless-ossm-secret-filtering.adoc
  modules/serverless-ossm-setup.adoc
  modules/serverless-rn-1-23-0.adoc
  modules/serverless-rn-1-26-0.adoc
  modules/serverless-scale-to-zero-grace-period.adoc
  serverless/eventing/brokers/serverless-broker-backing-channel-default.adoc
  serverless/eventing/brokers/serverless-global-config-broker-class-default.adoc
Labels: peer-review-done, size/M, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56678 OSDOCS-4757:adds session affinity to OVN-K
  modules/nw-ovn-kubernetes-session-affinity.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58017 Document GitOps 1.8.2 Release Notes
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-8-2.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58180 OSDOCS-5277-rn-update: Update the CSI ref in a vSphere RN
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS

#58233 [OCPBUGS-11019]: Update the version of a bare metal Operator command
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, merge-review-in-progress

#58370 [CP of #58140] Enterprise 4.8 manual cp srvls 1.28 rel notes
  modules/serverless-deprecated-removed-features.adoc
  modules/serverless-functions-creating-on-cluster-builds.adoc
  modules/serverless-rn-1-28-0.adoc
  modules/serverless-tech-preview-features.adoc
  serverless/functions/serverless-developing-nodejs-functions.adoc
  serverless/functions/serverless-developing-typescript-functions.adoc
  serverless/serverless-release-notes.adoc
Labels: size/L

#58297 OCPBUGS-11451: update prereqs
  modules/installing-aws-load-balancer-operator.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#58254 OSDOCS-5454: remove irrelevant OCP APIs from tier table
  modules/api-support-tiers-mapping.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58025 CNV-27611: Adding image parameters to config map
  modules/virt-checking-cluster-dpdk-readiness.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.13

#58382 SRVKE-1215 FIPS issue in Knative Broker for Apache Kafka is fixed
  snippets/serverless-about-kafka-broker.adoc
Labels: lgtm, size/XS

#58237 [SRVCOM-2210] Add notes on restrictions for overriding probes
  serverless/eventing/tuning/overriding-config-eventing.adoc
  serverless/knative-serving/config-applications/overriding-config-serving.adoc
Labels: peer-review-done, size/S, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58238 [SRVKS-957] Add section on resolving Serverless operator upgrade failure
  modules/serverless-resolving-operator-upgrade-failure.adoc
  serverless/admin_guide/serverless-upgrades.adoc
Labels: peer-review-done, size/M, serverless, merge-review-needed

#58047 OSDOCS-3796: Private/Public Subnet
  modules/ccs-aws-provisioned.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/rosa-aws-provisioned.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58232 OCPBUGS#11363: Expose the node port for the application
  modules/nw-exposing-service.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#58310 [OSDOCS-5684]:Update link for ROSA service definition
  modules/rosa-architecture.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#57805 CNV-25427: Release note NEW - UI - Enable SSH over LB
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58172 OSDOCS#5661: Reorganizing required gcp permissions
  installing/installing_gcp/installing-gcp-account.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  modules/installation-gcp-permissions.adoc
  modules/minimum-required-permissions-ipi-gcp.adoc
  modules/minimum-required-permissions-upi-gcp.adoc
Labels: peer-review-done, lgtm, size/XL, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#57249 Add Operator rollback instructions for RHACS
  _topic_map.yml
  modules/rollback-operator-upgrades-cli.adoc
  modules/rollback-operator-upgrades-console.adoc
  upgrading/upgrade-operator.adoc
Labels: peer-review-done, size/L, RHACS, merge-review-in-progress

#58263 OSDOCS-5662: add prereq for VG capacity
  microshift_install/microshift-install-rpm.adoc
  modules/microshift-install-rpm-before.adoc
  modules/microshift-install-rpm-preparing.adoc
  modules/microshift-install-rpms.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.13

#58374 OCPBUGS-11249 v4.12: add rhel VG name info to 4.12 docs
  modules/microshift-install-rpm-preparing.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#58375 OCPBUGS8700: correct kustomize language
  modules/microshift-applying-manifests-example.adoc
  modules/microshift-manifests-overview.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#57963 SPLAT-1015: fix Labels for MachineSet on AWS Local Zone deployment page
  modules/installation-localzone-generate-k8s-manifest.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#58383 OSDOCS-5681: Add link to logical volume management
  microshift_install/microshift-install-rpm.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference

#58440 [enterprise-4.12] CP-OSDOCS-5681
  microshift_install/microshift-install-rpm.adoc
Labels: size/XS

#58188 [SRVKS-1003] Add a section on multi-container support for Serving
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-configuring-multi-container-service.adoc
  serverless/knative-serving/config-applications/multi-container-support-for-serving.adoc
Labels: peer-review-done, size/M, serverless, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#57970 Update availability zone with Europe
  modules/cloud-create-instance-steps.adoc
Labels: peer-review-done, size/S, RHACS, merge-review-in-progress, rhacs-docs-4.0

#58062 OCPBUGS#9407: Update the ingress controller sharding procedure
  modules/nw-ingress-sharding-namespace-labels.adoc
  modules/nw-ingress-sharding-route-labels.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#58231 Update configuring cluster-wide proxy section for ALBO
  modules/configuring-egress-proxy.adoc
  networking/aws_load_balancer_operator/configure-egress-proxy-aws-load-balancer-operator.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13

#58012 CNV-25573: UI - Ability to make a hot-plug disk part of the VM
  modules/virt-about-hot-plugging-virtual-disks.adoc
  virt/virt-web-console-overview.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#58100 OSDOCS-5584-RN:updates 4.13 tables
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#58045 ML-RHDEVDOCS-2857: Added a step to verify that all components were installed
  modules/op-installing-pipelines-operator-in-web-console.adoc
Labels: peer-review-done, size/M, dev-tools, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#58432 OSDOCS-5637-cloud-compute: adds bug batch 4.13
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#58428 [enterprise-4.9] ML-RHDEVDOCS-3382: Updated the Pipeline builder and other instances o…
  cicd/pipelines/working-with-pipelines-using-the-developer-perspective.adoc
  modules/nw-ptp-installing-operator-web-console.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-editing-pipelines.adoc
  modules/op-opting-out-of-tekton-hub-in-the-developer-perspective.adoc
  modules/op-using-custom-pipeline-template-for-git-import.adoc
Labels: size/M, jira/valid-reference

#58476 [enterprise-4.11] [RHDEVDOCS-4271]: Added a procedure to export an application in Add vie…
  applications/creating_applications/odc-creating-applications-using-developer-perspective.adoc
  applications/odc-viewing-application-composition-using-topology-view.adoc
  images/export-application-dialog-box.png
  modules/odc-exporting-an-application-to-another-project-or-cluster.adoc
  modules/odc-viewing-application-topology.adoc
Labels: size/M

#58214 [RHDEVDOCS-3624] Move export app docs to higher level for findability
  _topic_maps/_topic_map.yml
  applications/creating_applications/odc-creating-applications-using-developer-perspective.adoc
  applications/odc-exporting-applications.adoc
  applications/odc-viewing-application-composition-using-topology-view.adoc
Labels: peer-review-done, lgtm, size/M, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58482 [enterprise-4.11]OSDOCS-5537: Update Infrastructure sizing table and…
  modules/infrastructure-node-sizing.adoc
Labels: size/S, jira/valid-reference

#58311 OCPBUGS#11430: Add namespace openshift-machine-api in static configuration
  modules/ipi-install-preparing-the-bare-metal-node.adoc
Labels: peer-review-done, size/XS, qe-approved, merge-review-in-progress, merge-review-needed

#58475 OSDOCS#5690: Adds notes for MS 4.12.11 release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#58455 [continuation of #58238] Move and include the Serverless upgrades section
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/serverless-resolving-operator-upgrade-failure.adoc
  serverless/install/serverless-upgrades.adoc
Labels: peer-review-done, lgtm, size/XS, serverless, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58177 [SRVKS-869] Document gRPC over HTTP2 for 4.10+
  modules/interacting-serverless-apps-http2-gRPC-up-to-4-9.adoc
  modules/interacting-serverless-apps-http2-gRPC.adoc
  serverless/knative-serving/external-ingress-routing/using-http2-gRPC.adoc
Labels: peer-review-done, size/L, serverless, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56336 [OSDOCS-5327]: Adding updates docs for hosted control planes
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-managing.adoc
  modules/configuring-node-pools-for-hcp.adoc
  modules/updates-for-hosted-control-planes.adoc
  modules/updating-node-pools-for-hcp.adoc
  updating/index.adoc
  updating/understanding-openshift-updates.adoc
  updating/updating-hosted-control-planes.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.13

#57994 RHDEVDOCS-5090: Update the subscription to the latest in the OCP GitO…
  cicd/gitops/installing-openshift-gitops.adoc
  modules/installing-gitops-operator-in-web-console.adoc
  modules/installing-gitops-operator-using-cli.adoc
  modules/logging-in-to-the-argo-cd-instance-by-using-the-argo-cd-admin-account.adoc
Labels: peer-review-done, size/S, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#58393 OSDOCS-5689:adds 4.12.11 to RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#56234 OSDOCS-5323: Multi-arch AWS support
  modules/multi-architecture-modify-machine-set-aws.adoc
  post_installation_configuration/multi-architecture-configuration.adoc
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, branch/enterprise-4.13

#58439 OCPBUGS#4956:AWS_EFS
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58384 OSDOCS-5686: Added a note about OVN-Kubernetes migration
  modules/nw-ovn-kubernetes-migration-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#57513 OSDOCS-5157:Updates to dynamic plugin extensions and api docs
  modules/dynamic-plug-in-api.adoc
  modules/dynamic-plug-in-sdk-extensions.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.13

#57896 OCPBUGS-10984: Document the --skip-pruning oc-mirror flag
  modules/oc-mirror-command-reference.adoc
  modules/oc-mirror-updating-registry-about.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#58507 updating the copyright date on the legal notice
  welcome/legal-notice.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58286 Update release notes for 3.73.4 patch
  release_notes/373-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS, merge-review-in-progress, merge-review-needed

#55182 Document limitation in [Spike] Secure MCS Endpoint MCO-59
  modules/installation-about-custom-azure-vnet.adoc
  modules/machine-config-operator.adoc
  security/certificate_types_descriptions/machine-config-operator-certificates.adoc
  snippets/mcs-endpoint-limitation.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58560 [enterprise-4.11]OCPBUGS-4946:AWS_EFS
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: size/S, jira/severity-low, jira/invalid-bug, jira/valid-reference

#58562 [enterprise-4.10]OCPBUGS-4946:AWS_EFS
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: size/S, jira/severity-low, jira/invalid-bug, jira/valid-reference

#58433 OCPBUGS#4956:AliCloud & IBM
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58567 [enterprise-4.10]OCPBUGS-4956:AliCloud & IBM
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference

#57548 SRVKE-1366 Namespaced Kafka broker
  modules/serverless-create-kafka-namespaced-broker.adoc
  modules/serverless-kafka-broker-with-isolated-dataplane.adoc
  serverless/eventing/brokers/kafka-broker.adoc
Labels: size/M

#54769 BZ2045952: Adds back in accidental removal of 4.9.13
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, px-approved, branch/enterprise-4.9

#58436 OSDOCS-5692 Z-stream release notes 4.11.35
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11

#58098 [OSDOCS-5672]: Deprecated k8s topo labels
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#58173 OCPBUGS#5899: Bootstrap CA renewal
  security/certificate_types_descriptions/bootstrap-certificates.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55704 TELCODOCS-1039 - Westport channel NIC PTP grandmaster clock
  modules/nw-ptp-configuring-linuxptp-services-as-grandmaster-clock.adoc
  modules/nw-ptp-grandmaster-clock-configuration-reference.adoc
  modules/nw-ptp-introduction.adoc
  modules/ptp-linuxptp-introduction.adoc
  networking/using-ptp.adoc
  snippets/grandmaster-clock-ptp-config.adoc
Labels: peer-review-done, size/L, telco, merge-review-in-progress, merge-review-needed

#57989 OCPBUGS#11050: Explanation of option for ImageSetConfiguration
  modules/oc-mirror-creating-image-set-config.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#57725 [MULTIARCH-1443] Add fips support for IBM zSystems and IBM Power
  installing/installing-fips.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/machine-config-overview.adoc
  modules/osdk-csv-manual-annotations.adoc
  modules/rhel-compute-requirements.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#58457 OCPBUGS#793: Replace "base64-encoded certificate"
  modules/images-configuration-cas.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-low, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58296 GH53988: Add missing node label
  modules/nodes-scheduler-node-selectors-about.adoc
Labels: peer-review-done, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#57660 TELCODOCS-1077: Release note for adding LVMS via ZTP
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#58330 OSDOCS-5269: add network topology diagram
  images/317_RHbM_OVN_topology_0323.png
  microshift_networking/microshift-networking.adoc
  modules/microshift-cni.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58554 [OSDOCS-5327]: Release note for updating hosted control planes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#58206 [OSDOCS-5532]: Manual creds YAML cleanup
  modules/manually-create-identity-access-management.adoc
Labels: size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58085 OSDOCS-5577: oc-mirror tarball release note
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58608 [enterprise-4.11] [OSDOCS-5532]: Manual creds YAML cleanup
  modules/manually-create-identity-access-management.adoc
Labels: size/L

#58609 [enterprise-4.10] [OSDOCS-5532]: Manual creds YAML cleanup
  modules/manually-create-identity-access-management.adoc
Labels: size/L

#58182 TELCODOCS-1210: Update ACM version for Telco RAN ZTP solution
  modules/ztp-telco-ran-software-versions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58612 [OSDOCS-5532]: Manual creds YAML cleanup
  modules/manually-create-identity-access-management.adoc
Labels: size/L

#57944 OSDOCS-3875: Update Admin Roles
  modules/managing-dedicated-administrators.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#58481 OCPBUGS-8814: add note for admin kubeconfig location
  modules/querying-kubelet-status-on-a-node.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13
