Repository openshift/openshift-docs, pull requests merged in 2023-07, with the labels that each got.

#61977 OCPBUGS-15760 Issue in table describing Supported Compliance Profiles
  modules/compliance-supported-profiles.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61878 Fix feature gate/set conflation
  machine_management/capi-machine-management.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60910 BZ#2024126: Added note about concurrent live migrations
  virt/install/preparing-cluster-for-virt.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61995 [enterprise-4.12] BZ#2024126: Guidelines to optimize concurrent migrations
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/S

#61997 [enterprise-4.10] BZ#2024126: Guidelines to optimize concurrent migrations
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/S

#61996 [enterprise-4.11] BZ#2024126: Guidelines to optimize concurrent migrations
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/S

#61992 [enterprise-4.13] Fix feature gate/set conflation
  machine_management/capi-machine-management.adoc
Labels: size/XS

#61755 [OCPBUGS-15195] Apply new naming guidelines for IBM Z
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
Labels: peer-review-done, size/S, branch/enterprise-4.13, branch/enterprise-4.14

#62004 CMA remove Kafka TP note
  modules/nodes-cma-autoscaling-custom-trigger-kafka.adoc
  nodes/cma/nodes-cma-autoscaling-custom-rn.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62000 [enterprise-4.11] Fix feature gate/set conflation
  machine_management/capi-machine-management.adoc
Labels: size/XS, merge-review-needed

#61999 [enterprise-4.12] Fix feature gate/set conflation
  machine_management/capi-machine-management.adoc
Labels: size/XS, merge-review-needed

#61903 OCPBUGS-15307: Clarity around MetalLB address resolution for L2
  modules/nw-metallb-layer2.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61906 [OCPBUGS#12934] Update RHOSP legacy HTTPS cert script
  installing/installing_openstack/preparing-to-install-on-openstack.adoc
  modules/security-osp-validating-certificates-manually.adoc
  modules/security-osp-validating-certificates.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62013 OCPBUGS-11991: Updating RHACM variable
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, telco, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference

#62014 OCPBUGS-1378: fixing RHACM variable for OCP 4.11
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference

#60860 OSDOCS-3366: Adding steps to check kubelet cert expirations
  modules/graceful-shutdown.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61938 [OSDOCS]:Expand ROSA/OSD lifecycle to 16 months
  modules/life-cycle-dates.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61114 OCPBUGS#14442:Change vSphere CSI driver to 2.71 for OCP 4.12
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#61537 OCPBUGS-15098: Add step to LokiStack procedure
  modules/network-observability-lokistack-create.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#61434 MIG-1320 Issue in file migrating_from_ocp_3_to_4/premigration-checklists-3-4.adoc
  migrating_from_ocp_3_to_4/premigration-checklists-3-4.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61802 OSDOCS#6464: Added bug fix for parse image reference for oc-mirror in the release note
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#61905 CNV -28700: Update YAMLs and mention default VM route
  modules/virt-configuring-ip-for-new-vm-cloud-init.adoc
  virt/virtual_machines/vm_networking/virt-configuring-ip-for-vms.adoc
Labels: peer-review-done, size/M, CNV, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61976 ROX-18157: Add missing image to 4.1 Release Notes
  release_notes/41-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, rhacs-docs-4.1

#61974 ROX-18157: Add missing image to 4.0 RNs
  release_notes/40-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, rhacs-docs-4.0

#61107 OCPBUGS-8813: Network policy protocol support
  modules/nw-networkpolicy-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61924 [OCPBUGS-14619]: Update order of etcd restore docs
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#61733 RHDEVDOCS-5435: Clean up Web Terminal Operator uninstall documentation
  modules/removing-devworkspace-operator.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61907 Makes slight changes to MultiNic docs
  modules/overriding-default-node-ip-selection-logic.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#54412 Adding difference in Operator capitalization for marketing vs technic…
  contributing_to_docs/doc_guidelines.adoc
Labels: peer-review-done, size/XS

#61528 OSSM-3988: [DOC] Update cert-manager procedure intro for installation and verification
  modules/ossm-cert-manager-installation.adoc
Labels: peer-review-done, lgtm, size/XS, service-mesh, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62026 [enterprise-4.10] Adding FIPS admonition to install doc
  installing/installing-fips.adoc
  modules/distr-tracing-product-overview.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-azure-stack-hub-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/osdk-csv-manual-annotations.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-compliance-nist.adoc
  modules/ssh-agent-using.adoc
  service_mesh/v2x/ossm-reference-jaeger.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10

#62027 [enterprise-4.11] Adding FIPS admonition to install doc
  installing/installing-fips.adoc
  modules/distr-tracing-product-overview.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-azure-stack-hub-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/osdk-csv-manual-annotations.adoc
  modules/rhel-compute-requirements.adoc
  modules/security-compliance-nist.adoc
  modules/ssh-agent-using.adoc
  service_mesh/v2x/ossm-reference-jaeger.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11

#61561 OCPBUGS#14864: Add known issue for Selinux relabeling issue for 4.13
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13

#61568 OCPBUGS#14864: Add known issue for Selinux relabeling issue for 4.12
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#61569 OCPBUGS#14864_4_11:Add known issue Selinux relabeling issue
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11

#61570 OCPBUGS#14864 4.10: Add known issue Selinux relabeling
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10

#62071 Fixing update wording in conceptual assemblies
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/understanding-upgrade-channels.adoc
  modules/update-service-overview.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#62085 [enterprise-4.12] CNV -28700: Update VM static IP YAML
  modules/virt-configuring-ip-for-new-vm-cloud-init.adoc
  virt/virtual_machines/vm_networking/virt-configuring-ip-for-vms.adoc
Labels: size/M

#62086 Move RN
  _topic_maps/_topic_map.yml
  virt/release_notes/_attributes
  virt/release_notes/images
  virt/release_notes/modules
  virt/release_notes/placeholder-release-notes.adoc
  virt/release_notes/snippets
  virt/virt-2-3-release-notes.adoc
  virt/virt-2-4-release-notes.adoc
  virt/virt-2-5-release-notes.adoc
  virt/virt-2-6-release-notes.adoc
  virt/virt-4-10-release-notes.adoc
  virt/virt-4-11-release-notes.adoc
  virt/virt-4-12-release-notes.adoc
  virt/virt-4-13-release-notes.adoc
  virt/virt-4-14-release-notes.adoc
  virt/virt-4-8-release-notes.adoc
Labels: peer-review-done, size/L, CNV

#61748 OSDOCS#6645: Update the cert-manager subscription name
  modules/cert-manager-proxy-support.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#62087 [Enterprise 4.11] Cherry-picks 54123 to OCP 4.11
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, OADP

#62088 [enterprise-4.12] Correctly adds resource requests/limits to Troubleshooting
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, OADP

#62089 [enterprise-4.10] Correctly adds resource requests/limits to Troubleshooting
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, OADP

#62005 PR for SRVKS-1004: [DOC] networking.knative.dev/http-option is wrong
  modules/serverless-https-redirect-service.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, serverless, jira/valid-reference

#62006 PR for SRVCOM-2478: [DOC] Rephrase misleading documentation
  modules/serverless-enabling-tls-internal-traffic.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, serverless, jira/valid-reference

#61785 4.10-RN-update: adds 4.10.63 to RNs
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10

#61428 Modularized version of PR 60936
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  modules/oadp-ceph-cephfs-back-up-dba.adoc
  modules/oadp-ceph-cephfs-back-up.adoc
  modules/oadp-ceph-cephfs-restore.adoc
  modules/oadp-ceph-cephfs.adoc
  modules/oadp-ceph-preparing-cephfs-crs.adoc
  modules/oadp-ceph-preparing-cephrbd-crs.adoc
  modules/oadp-ceph-preparing-crs-additional.adoc
  modules/oadp-ceph-preparing-crs.adoc
  modules/oadp-ceph-split-back-up-dba.adoc
  modules/oadp-ceph-split.adoc
  modules/oadp-cleaning-up-after-data-mover-snapshots.adoc
  snippets/oadp-ceph-cr-prerequisites.adoc
Labels: peer-review-done, size/XXL, branch/enterprise-4.12, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#62109 [enterprise-4.10] Manual CP for #62071
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/understanding-upgrade-channels.adoc
  modules/update-service-overview.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: size/M

#62106 [enterprise-4.13] Manual CP for #62071
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/understanding-upgrade-channels.adoc
  modules/update-service-overview.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: size/M

#62105 [enterprise-4.14] Manual CP for #62071
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/understanding-upgrade-channels.adoc
  modules/update-service-overview.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
Labels: size/M

#62112 [RHACS] ROX-17988: Fixing typo in sentence
  modules/configuring-an-authentication-provider-in-central.adoc
Labels: size/XS, RHACS, jira/valid-reference

#61937 OSDOCS-6710 4.11.44 z-stream RNs
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S

#62113 RHDEVDOC-5441: more work for content separation for pipelines
  .travis.yml
  modules/op-about-pipelinerun.adoc
  modules/op-alternative-approaches-compute-resource-quota-pipelines.adoc
  modules/op-creating-pipelines-along-with-applications.adoc
  modules/op-running-a-pipeline.adoc
Labels: size/L

#61657 OSDOCS#6618: Update availability FAQ
  modules/update-availability-faq.adoc
  updating/understanding_updates/intro-to-updates.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#61957 OSDOCS-6705: Adds notes for 4.12.23 MS release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#61998 OSDOCS-6712: adds 4.12.23 to RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference

#62082 Adding FIPS admonition about installing from FIPS enabled system
  installing/installing-fips.adoc
  modules/agent-installer-fips-compliance.adoc
  modules/distr-tracing-product-overview.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-azure-stack-hub-config-yaml.adoc
  modules/installation-bare-metal-agent-installer-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
  modules/installation-nutanix-config-yaml.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/osdk-csv-manual-annotations.adoc
  modules/rhel-compute-overview.adoc
  modules/rhel-compute-requirements.adoc
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
  modules/security-compliance-nist.adoc
  modules/ssh-agent-using.adoc
  service_mesh/v2x/ossm-reference-jaeger.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#62070 OCPBUGS-10830: Adding bare metal restricted UPI for 64-bit ARM support to chart
  installing/installing-preparing.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-bug, jira/valid-reference

#60803 CNV-28722 - InstanceTypes content
  modules/virt-creating-vm-instancetype.adoc
  virt/getting_started/virt-web-console-overview.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.14

#62124 RHDEVDOCS-5441: change travis.yml based on main, add scripts from main
  .travis.yml
  scripts/analytics_fix.sh
  scripts/check-asciidoctor-build.sh
  scripts/check-with-vale.sh
  scripts/checkrefs.js
  scripts/find_unused.py
  scripts/list_assemblies_used_by_modules.sh
  scripts/manualpreview.sh
  scripts/ocp_preview.sh
  scripts/ocpdocs/_analytics_other.html
  scripts/ocpdocs/_footer_other.html.erb
  scripts/ocpdocs/_previewpage
  scripts/ocpdocs/_topnav_other.html
  scripts/ocpdocs/index-commercial.html
  scripts/ocpdocs/robots_preview.txt
  scripts/ocpdocs/search-commercial.html
  scripts/push_to_netlify.sh
Labels: size/XXL, jira/valid-reference

#60539 TELCODOCS-1238: Adding ability to exclude SR-IOV from Topology Manager
  modules/nw-sriov-configure-exclude-topology-manager.adoc
  modules/nw-sriov-exclude-topology-manager.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/nw-sriov-topology-manager.adoc
  networking/hardware_networks/add-pod.adoc
  networking/hardware_networks/configuring-sriov-device.adoc
Labels: peer-review-done, size/L, telco, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#62146 fixing portal build
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/XS, branch/enterprise-4.11

#62104 [OSDOCS-6756]:Persistent Storage using Amazon EBS Prebuilt Storage Classes
  storage/persistent_storage/persistent-storage-aws.adoc
Labels: peer-review-done, size/S

#62017 [enterprise-4.12] TELCODOCS-1175: Remove remediation content from docs.openshift.com
  _topic_maps/_topic_map.yml
  nodes/nodes/nodes-remediating-fencing-maintaining-rhwa.adoc
  release_notes/ocp-4-12-release-notes.adoc
  virt/install/preparing-cluster-for-virt.adoc
  virt/node_maintenance/virt-about-node-maintenance.adoc
  virt/upgrading-virt.adoc
Labels: size/M, jira/valid-reference

#61136 OCPBUGS-11455: add kernel override
  modules/coreos-layering-configuring.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference

#62137 ROX-18324: Add known issue for operator upgrades with ebpf and instructions
  release_notes/41-release-notes.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.1

#62162 RHDEVDOCS-5441: fix inclusion of attributes in Pipelines
  pipelines/authenticating-pipelines-using-git-secret.adoc
  pipelines/creating-applications-with-cicd-pipelines.adoc
  pipelines/customizing-configurations-in-the-tektonconfig-cr.adoc
  pipelines/installing-pipelines.adoc
  pipelines/managing-nonversioned-and-versioned-cluster-tasks.adoc
  pipelines/op-release-notes.adoc
  pipelines/reducing-pipelines-resource-consumption.adoc
  pipelines/remote-pipelines-tasks-resolvers.adoc
  pipelines/securing-webhooks-with-event-listeners.adoc
  pipelines/setting-compute-resource-quota-for-openshift-pipelines.adoc
  pipelines/understanding-openshift-pipelines.adoc
  pipelines/uninstalling-pipelines.adoc
  pipelines/unprivileged-building-of-container-images-using-buildah.adoc
  pipelines/using-pipelines-as-code.adoc
  pipelines/using-pods-in-a-privileged-security-context.adoc
  pipelines/using-tekton-chains-for-openshift-pipelines-supply-chain-security.adoc
  pipelines/using-tekton-hub-with-openshift-pipelines.adoc
  pipelines/viewing-pipeline-logs-using-the-openshift-logging-operator.adoc
  pipelines/working-with-pipelines-using-the-developer-perspective.adoc
Labels: size/M, jira/valid-reference

#61617 OCPBUGS-10548: fix doc issues about unprivileged runs of Buildah in Pipelines
  cicd/pipelines/unprivileged-building-of-container-images-using-buildah.adoc
  modules/op-configuring-buildah-to-use-build-user.adoc
  modules/op-configuring-custom-sa-and-scc.adoc
  modules/op-starting-a-task-run-pipeline-run-build-user.adoc
Labels: lgtm, size/M, jira/severity-important, jira/invalid-bug, merge-review-in-progress, jira/valid-reference

#62165 CNV -30797: Runbook title update
  modules/virt-runbook-kubemacpooldown.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.14

#61909 OCPBUGS#8693: Deleted hyperVGeneration entry
  modules/installation-minimum-resource-requirements.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62175 OCPBUGS-15984 - reverting changes regarding BMH
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#59740 Backing up from one cluster and restoring to another
  backup_and_restore/application_backup_and_restore/oadp-advanced-topics.adoc
  modules/oadp-about-backing-and-restoring-from-cluster-to-cluster.adoc
  modules/oadp-backing-and-restoring-from-cluster-to-cluster.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#62210 [RHACS] Fixes broken link in 4.1 release notes
  release_notes/41-release-notes.adoc
Labels: size/XS, RHACS, rhacs-docs-4.1

#61615 OSDOCS-6552: GA for matchLabelKeys for pod topology spread constraints
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-scheduler-pod-topology-spread-constraints-configuring.adoc
  nodes/clusters/nodes-cluster-enabling-features.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.14

#60819 OCPBUGS#13396 Add cpuPartitioningMode to Optional config params
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#62206 OSDOCS-6773: Bug fix oc v kubectl
  modules/microshift-k8s-apis.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62186 [OSDOCS-6828]: AWS STS and GCP WID diagram enhancement
  authentication/managing_cloud_provider_credentials/cco-mode-gcp-workload-identity.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  images/142_OpenShift_credentials_STS_0221.png
  images/347_OpenShift_credentials_with_STS_updates_0623_AWS.png
  images/347_OpenShift_credentials_with_STS_updates_0623_GCP.png
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62207 OSDOCS-6771: fix sys requirements bug
  modules/microshift-install-system-requirements.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62236 OADP-1549 fixing call-outs
  modules/dr-recover-expired-control-plane-certs.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#62252 [enterprise-4.10] Add info on repo name when mirroring catalog img
  installing/disconnected_install/installing-mirroring-installation-images.adoc
  modules/olm-mirroring-catalog-airgapped.adoc
  modules/olm-mirroring-catalog-colocated.adoc
  modules/olm-mirroring-catalog-manifests.adoc
Labels: size/S

#62181 Remove outdated tech preview language for postgresql
  modules/create-collection-rules.adoc
  modules/migrate-scope-collections.adoc
  modules/object-collections.adoc
  operating/create-use-collections.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.0, rhacs-docs-4.1

#62059 RHDEVDOCS-5236: Add docs for creating a function via ODC
  functions/serverless-functions-getting-started.adoc
  modules/odc-creating-functions.adoc
  modules/serverless-create-func-kn.adoc
Labels: peer-review-done, size/M, dev-tools, serverless, jira/valid-reference

#62257 [serverless-docs-1.29] RHDEVDOCS-5236: Add docs for creating a function via ODC
  functions/serverless-functions-getting-started.adoc
  modules/odc-creating-functions.adoc
  modules/serverless-create-func-kn.adoc
Labels: size/M, jira/valid-reference

#62125 RHDEVDOCS-5163: Document connecting an event sink to a broker via dev console
  _topic_maps/_topic_map.yml
  about/about-knative-eventing.adoc
  eventing/brokers/serverless-event-delivery.adoc
  eventing/brokers/serverless-using-brokers-managing-brokers.adoc
  eventing/brokers/serverless-using-brokers.adoc
  eventing/channels/connecting-channels-sinks.adoc
  eventing/channels/serverless-creating-channels.adoc
  eventing/serverless-event-delivery.adoc
  eventing/subscriptions/serverless-subs.adoc
  eventing/triggers/serverless-triggers.adoc
  modules/serverless-configuring-event-delivery-examples.adoc
  modules/serverless-connect-sink-broker-odc.adoc
  modules/serverless-event-delivery-component-behaviors.adoc
  modules/serverless-event-delivery-parameters.adoc
  modules/trigger-event-delivery-config.adoc
Labels: peer-review-done, size/L, dev-tools, serverless, jira/valid-reference

#62155 OCPBUGS#9440: Update FBC filtering proc to encompass general updates
  installing/disconnected_install/installing-mirroring-installation-images.adoc
  modules/olm-filtering-fbc.adoc
  modules/olm-updating-index-image.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62180 ROX-18295: Add info about upcoming report deletion to RNs
  release_notes/41-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.1

#62208 [RHACS] Removed old release notes, added patch release notes
  modules/common-attributes.adoc
  release_notes/40-release-notes.adoc
  release_notes/41-release-notes.adoc
Labels: peer-review-done, size/XL, RHACS/patch, rhacs-docs-4.1

#62271 [RHACS] Manual cherry-pick of PR#62208
  modules/common-attributes.adoc
  release_notes/40-release-notes.adoc
  release_notes/41-release-notes.adoc
Labels: size/XL

#62160 OSDOCS-6811: Added IMDSv2 CLI instructions
  modules/rosa-imds-machine-pools-cli.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
Labels: peer-review-in-progress, peer-review-needed, size/M, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62205 Nodes docs fixes during ROSA review
  modules/nodes-pods-configmap-overview.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-env-vars.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-volumes.adoc
  modules/nodes-pods-configmaps-use-case-setting-command-line-arguments.adoc
  modules/nodes-pods-configuring-pod-critical.adoc
  modules/nodes-pods-pod-disruption-about.adoc
  modules/nodes-pods-pod-disruption-configuring.adoc
  modules/nodes-pods-secrets-certificates-creating.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/nodes-pods-viewing-project.adoc
  modules/nodes-pods-viewing-usage.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/pod-disruption-eviction-policy.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62221 [OSDOCS-6403]: Add warning on cluster deletion docs
  modules/rosa-deleting-cluster.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#62280 [enterprise-4.10] Nodes docs fixes during ROSA review
  modules/nodes-pods-configmap-overview.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-env-vars.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-volumes.adoc
  modules/nodes-pods-configmaps-use-case-setting-command-line-arguments.adoc
  modules/nodes-pods-configuring-pod-critical.adoc
  modules/nodes-pods-pod-disruption-about.adoc
  modules/nodes-pods-pod-disruption-configuring.adoc
  modules/nodes-pods-secrets-certificates-creating.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/nodes-pods-viewing-project.adoc
  modules/nodes-pods-viewing-usage.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
Labels: size/M

#62281 [enterprise-4.11] Nodes docs fixes during ROSA review
  modules/nodes-pods-configmap-overview.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-env-vars.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-volumes.adoc
  modules/nodes-pods-configmaps-use-case-setting-command-line-arguments.adoc
  modules/nodes-pods-configuring-pod-critical.adoc
  modules/nodes-pods-pod-disruption-about.adoc
  modules/nodes-pods-pod-disruption-configuring.adoc
  modules/nodes-pods-secrets-certificates-creating.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/nodes-pods-viewing-project.adoc
  modules/nodes-pods-viewing-usage.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
Labels: size/M

#62282 [enterprise-4.12] Nodes docs fixes during ROSA review
  modules/nodes-pods-configmap-overview.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-env-vars.adoc
  modules/nodes-pods-configmaps-use-case-consuming-in-volumes.adoc
  modules/nodes-pods-configmaps-use-case-setting-command-line-arguments.adoc
  modules/nodes-pods-configuring-pod-critical.adoc
  modules/nodes-pods-pod-disruption-about.adoc
  modules/nodes-pods-pod-disruption-configuring.adoc
  modules/nodes-pods-secrets-certificates-creating.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/nodes-pods-viewing-project.adoc
  modules/nodes-pods-viewing-usage.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
Labels: size/M

#62234 CNV-22637 update HCO version in attributes
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV

#62227 TOC and small fixes
  modules/virt-cluster-resource-requirements.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.14

#62230 UI overview changes
  virt/getting_started/virt-web-console-overview.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
Labels: peer-review-needed, size/XL, CNV, branch/enterprise-4.14

#62286 Revert "UI overview changes"
  virt/getting_started/virt-web-console-overview.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
Labels: size/XL

#61893 OBSDOCS-215: how-to-enable-dedicated-service-monitor
  modules/monitoring-configuring-dedicated-service-monitors.adoc
  modules/monitoring-enabling-a-dedicated-service-monitor.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62158 OSDOCS-6804 Z-stream RNs for 4.12.24
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, merge-review-in-progress

#62178 OSDOCS-6824: Adds notes for 4.12.24 MS release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference

#62297 [enterprise-4.10] OBSDOCS-215: how-to-enable-dedicated-service-monitor
  modules/monitoring-configuring-dedicated-service-monitors.adoc
  modules/monitoring-enabling-a-dedicated-service-monitor.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: size/M, jira/valid-reference

#62149 TELCODOCS-1342: NUMA scheduling GA for 4.12.24
  scalability_and_performance/cnf-numa-aware-scheduling.adoc
Labels: size/XS, branch/enterprise-4.12, jira/valid-reference

#62299 OSDOCS-6804: Used the wrong syntax for the SNO variable, fixing
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.12, jira/valid-reference

#60623 CNV-27208: OKD virt installation procedures
  _attributes/common-attributes.adoc
  modules/virt-about-node-placement-virtualization-components.adoc
  modules/virt-deploying-operator-cli.adoc
  modules/virt-example-node-placement-affinity-hyperconverged-cr.adoc
  modules/virt-example-node-placement-node-selector-hyperconverged-cr.adoc
  modules/virt-example-node-placement-node-selector-olm-subscription.adoc
  modules/virt-example-node-placement-tolerations-hyperconverged-cr.adoc
  modules/virt-example-node-placement-tolerations-olm-subscription.adoc
  modules/virt-installing-virt-operator.adoc
  modules/virt-subscribing-cli.adoc
Labels: peer-review-done, size/L, CNV, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61947 OCPBUGS#15423: Fixed link pointing to RHV-H for vSphere docs
  _attributes/common-attributes.adoc
  modules/installation-vsphere-infrastructure.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#62310 OBSDOCS-338: typo fix in cluster labels config topic in monitoring docs
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
Labels: size/S, jira/valid-reference

#62318 [enterprise-4.13] OBSDOCS-338: typo-fix-in-configuring-monitoring-stack
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
Labels: size/XS, jira/valid-reference

#62235 OSDOCS-6772-all: move welcome page microshift
  _topic_maps/_topic_map_ms.yml
  microshift_welcome/_attributes
  microshift_welcome/images
  microshift_welcome/index.adoc
  microshift_welcome/modules
  microshift_welcome/snippets
  welcome/index.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61181 CNV-29398_2: [2212293] "Usage and examples" in OpenShift Virtualization must gather is wrong
  modules/virt-must-gather-options.adoc
  modules/virt-using-virt-must-gather.adoc
  virt/support/virt-collecting-virt-data.adoc
Labels: peer-review-done, size/M, CNV, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62330 [enterprise-4.13] CNV-27208
  _attributes/common-attributes.adoc
  modules/virt-about-node-placement-virtualization-components.adoc
  modules/virt-deploying-operator-cli.adoc
  modules/virt-example-node-placement-affinity-hyperconverged-cr.adoc
  modules/virt-example-node-placement-node-selector-hyperconverged-cr.adoc
  modules/virt-example-node-placement-node-selector-olm-subscription.adoc
  modules/virt-example-node-placement-tolerations-hyperconverged-cr.adoc
  modules/virt-example-node-placement-tolerations-olm-subscription.adoc
  modules/virt-installing-virt-operator.adoc
  modules/virt-subscribing-cli.adoc
Labels: size/L, CNV

#62328 CP-OSDOCS-6772-4.13: move welcome page microshift
  _topic_maps/_topic_map_ms.yml
  microshift_welcome/_attributes
  microshift_welcome/images
  microshift_welcome/index.adoc
  microshift_welcome/modules
  microshift_welcome/snippets
  welcome/index.adoc
Labels: size/M, merge-review-in-progress

#62329 CP-OSDOCS-6772-4.12: move welcome page microshift
  _topic_maps/_topic_map_ms.yml
  microshift_welcome/_attributes
  microshift_welcome/images
  microshift_welcome/index.adoc
  microshift_welcome/modules
  microshift_welcome/snippets
  welcome/index.adoc
Labels: size/M, merge-review-needed

#62168 [RHACS] ROX-18160: Release notes and errata update for patch 3.74.5
  release_notes/374-release-notes.adoc
Labels: size/S, RHACS, jira/valid-reference

#62344 [RHACS] ROX-18160: Fixing typo
  release_notes/374-release-notes.adoc
Labels: size/XS, RHACS, rhacs-docs-3.74, jira/valid-reference

#62177 [RHACS] ROX-13807: Removing reference to telemetry from Helm chart documentation
  modules/central-services-public-config.adoc
Labels: peer-review-in-progress, size/XS, rhacs-docs-3.74, jira/valid-reference, rhacs-docs-4.0, rhacs-docs-4.1

#61958 CMP-2030: CO 1.1.0 release notes
  modules/compliance-operator-hcp-install.adoc
  security/compliance_operator/compliance-operator-installation.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: peer-review-done, size/L, do-not-merge/hold, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62338 OCPBUGS-15423-10: Fixed link pointing to RHV-H for vSphere docs
  _attributes/common-attributes.adoc
  modules/installation-vsphere-infrastructure.adoc
Labels: size/XS

#62337 OCPBUGS#15423: Fixed link pointing to RHV-H for vSphere docs
  _attributes/common-attributes.adoc
  modules/installation-vsphere-infrastructure.adoc
Labels: size/XS

#62320 ROX-15826: Add GUI method for using init bundle
  modules/compliance-operator-configure-scanning.adoc
  modules/create-resource-init-bundle.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-3.74, jira/valid-reference, rhacs-docs-4.0, rhacs-docs-4.1

#62355 [enterprise-4.12] CMP-2030: CO 1.1.0 release notes
  modules/compliance-operator-hcp-install.adoc
  security/compliance_operator/compliance-operator-installation.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/L, jira/valid-reference

#62251 OCPBUGS#16038: Replace fake passwords with standard replace values
  _unused_topics/completing-installation.adoc
  contributing_to_docs/doc_guidelines.adoc
  modules/builds-creating-secrets.adoc
  modules/builds-secrets-overview.adoc
  modules/builds-using-secrets.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/core-user-password.adoc
  modules/developer-cli-odo-creating-a-database-with-odo.adoc
  modules/gitops-logging-into-keycloak.adoc
  modules/identity-provider-creating-htpasswd-file-linux.adoc
  modules/identity-provider-creating-htpasswd-file-windows.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-launching-installer.adoc
  modules/installation-nutanix-config-yaml.adoc
  modules/installation-osp-describing-cloud-parameters.adoc
  modules/ipi-install-configuring-managed-secure-boot-in-the-install-config-file.adoc
  modules/ldap-syncing-about.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
  modules/nodes-containers-downward-api-container-secrets.adoc
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-creating-basic.adoc
  modules/nodes-pods-secrets-creating-opaque.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/op-configuring-basic-authentication-for-git.adoc
  modules/op-installing-crunchy-postgres-database-and-tekton-hub.adoc
  modules/op-release-notes-1-8.adoc
  modules/op-understanding-credential-selection.adoc
  modules/op-using-a-custom-database-in-tekton-hub.adoc
  modules/reviewing-the-installation-log.adoc
  modules/sbo-categories-of-exposable-binding-data.adoc
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service.adoc
  modules/sbo-methods-of-exposing-binding-data.adoc
  modules/serverless-kafka-sasl-source.adoc
  modules/templates-exposing-object-fields.adoc
  modules/templates-rails-writing-application.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62361 [enterprise-4.10] CMP-2030: CO 1.1.0 release notes
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/M, jira/valid-reference

#61727 Updates scanning pods for vulernabilities docs
  modules/security-pod-scan-cso-using.adoc
  modules/security-pod-scan-cso.adoc
  modules/security-pod-scan-query-cli.adoc
  security/pod-vulnerability-scan.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62374 OCPBUGS#16038: Replace fake passwords with standard replace values
  contributing_to_docs/doc_guidelines.adoc
  modules/builds-creating-secrets.adoc
  modules/builds-secrets-overview.adoc
  modules/builds-using-secrets.adoc
  modules/cluster-logging-collector-log-forward-es.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/completing-installation.adoc
  modules/developer-cli-odo-creating-a-database-with-odo.adoc
  modules/gitops-logging-into-keycloak.adoc
  modules/identity-provider-creating-htpasswd-file-linux.adoc
  modules/identity-provider-creating-htpasswd-file-windows.adoc
  modules/installation-aws-user-infra-installation.adoc
  modules/installation-launching-installer.adoc
  modules/installation-nutanix-config-yaml.adoc
  modules/installation-osp-describing-cloud-parameters.adoc
  modules/ipi-install-configuring-managed-secure-boot-in-the-install-config-file.adoc
  modules/ldap-syncing-about.adoc
  modules/metering-use-mysql-or-postgresql-for-hive.adoc
  modules/nodes-containers-downward-api-container-secrets.adoc
  modules/nodes-pods-secrets-about.adoc
  modules/nodes-pods-secrets-creating-basic.adoc
  modules/nodes-pods-secrets-creating-opaque.adoc
  modules/nodes-pods-secrets-creating.adoc
  modules/op-configuring-basic-authentication-for-git.adoc
  modules/op-installing-crunchy-postgres-database-and-tekton-hub.adoc
  modules/op-release-notes-1-8.adoc
  modules/op-understanding-credential-selection.adoc
  modules/op-using-a-custom-database-in-tekton-hub.adoc
  modules/reviewing-the-installation-log.adoc
  modules/sbo-categories-of-exposable-binding-data.adoc
  modules/sbo-connecting-spring-petclinic-sample-app-to-postgresql-database-service.adoc
  modules/sbo-methods-of-exposing-binding-data.adoc
  modules/serverless-kafka-sasl-source.adoc
  modules/templates-exposing-object-fields.adoc
  modules/templates-rails-writing-application.adoc
Labels: size/L

#61653 OSDOCS-5631: Greenboot app health check script tutorial
  _topic_maps/_topic_map_ms.yml
  microshift_running_apps/microshift-greenboot-workload-scripts.adoc
  modules/microshift-greenboot-create-health-check-script.adoc
  modules/microshift-greenboot-how-workload-health-check-scripts-work.adoc
  modules/microshift-greenboot-included-health-checks.adoc
  modules/microshift-greenboot-testing-workload-script.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62244 ROX-18181: Add 4.0.3 patch info to RNs
  release_notes/40-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, rhacs-docs-4.0

#62150 OSDOCS-6482: Update uname command usage
  _unused_topics/microshift-adding-containers-to-blueprint.adoc
  modules/microshift-install-rpms.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62346 OCPBUGS-15730: fixes typo in kind parameter of yaml file
  modules/nw-egressnetworkpolicy-object.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-important, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62397 [RHACS] ROX-13807: Manual CP from #62177 to 4.0
  modules/central-services-public-config.adoc
Labels: size/XS, RHACS, jira/valid-reference

#62398 [RHACS] ROX-13807: Manual CP from #62177 to 3.74
  modules/central-services-public-config.adoc
Labels: size/XS, RHACS, jira/valid-reference

#62133 OCPBUGS-11739: Changed number of isolated/reserved CPUs
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference

#60221 OCPBUGS#13813: update GCP IP Alias capacity from 10 to 100
  modules/nw-egress-ips-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62409 Obsdocs 332 on 4.10
  logging/cluster-logging-release-notes.adoc
  modules/logging-rn-5.5.13.adoc
Labels: size/S

#62411 Obsdocs332 on 4.11
  logging/cluster-logging-release-notes.adoc
  modules/logging-rn-5.5.13.adoc
Labels: size/S

#61968 OBSDOCS-216 - Logging 5.5.12 on 4.12
  logging/cluster-logging-release-notes.adoc
  logging/v5_5/logging-5-5-release-notes.adoc
  modules/logging-rn-5.5.12.adoc
Labels: size/M

#62340 RHDEVDOCS-5523: Pipelines 1.9.3 Release Notes
  modules/op-release-notes-1-9.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60979 OSDOCS-6205: Added note for default OperatorHub source pods
  modules/disabling-catalogsource-objects.adoc
  operators/admin/olm-cs-podsched.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62420 [enterprise-4.10] RHDEVDOCS-5523: Pipelines 1.9.3 Release Notes
  cicd/pipelines/op-release-notes.adoc
  modules/op-release-notes-1-9.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/L, merge-review-in-progress, jira/valid-reference

#62417 [enterprise-4.11] RHDEVDOCS-5523: Pipelines 1.9.3 Release Notes
  modules/op-release-notes-1-9.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/M, jira/valid-reference

#61919 OCPBUGS-8097-re: Updated ELB nomenclature throughout docs
  modules/aws-limits.adoc
  modules/ccs-aws-provisioned.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/installation-aws-limits.adoc
  modules/rosa-aws-provisioned.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62288 PR for SRVKE-1386: [DOC] Create listed 2 times in Knative Eventing installation
  modules/serverless-install-eventing-web-console.adoc
Labels: peer-review-done, size/S, dev-tools, serverless, jira/valid-reference

#62372 OSDOCS-6885: Added note for RHCOS, RHEL nodes not supported
  security/security_profiles_operator/spo-enabling.adoc
  security/security_profiles_operator/spo-seccomp.adoc
  security/security_profiles_operator/spo-selinux.adoc
  security/security_profiles_operator/spo-understanding.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61855 CMA Adding 2.10.1-267 Release Notes
  nodes/cma/nodes-cma-autoscaling-custom-rn.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61722 OSDOCS#6499: GCP - move install config parameters out of assemblies
  _topic_maps/_topic_map.yml
  installing/installing_gcp/installation-config-parameters-gcp.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-network-customizations.adoc
  installing/installing_gcp/installing-gcp-private.adoc
  installing/installing_gcp/installing-gcp-shared-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra-vpc.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  installing/installing_gcp/installing-gcp-vpc.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14

#62432 OCPBUGS-8097-re: Updated ELB nomenclature throughout docs
  modules/aws-limits.adoc
  modules/ccs-aws-provisioned.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/installation-aws-limits.adoc
  modules/rosa-aws-provisioned.adoc
Labels: size/S

#62359 OCPRHV-773 remove RH-Virtualization from common_attributes file
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#62433 [enterprise-4.10] OCPBUGS-8097-re: Updated ELB nomenclature throughout docs
  modules/aws-limits.adoc
  modules/ccs-aws-provisioned.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/dedicated-exposing-TCP-services.adoc
  modules/installation-aws-limits.adoc
  modules/rosa-aws-provisioned.adoc
Labels: size/S

#62134 TELCODOCS-1238: RN for excluding SR-IOV from Topology Manager
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, telco, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#62229 OCPBUGS-9347RE: Removed block statement for 3rd party vSphere CSI Driver
  modules/persistent-storage-csi-vsphere-install-issues.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed
