Repository openshift/openshift-docs, pull requests merged in 2023-06, with the labels that each got.

#60433 OSDOCS#6057: Authenticating cert-manager Operator on the GCP (without workload identity)
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-non-sts-gcp.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed

#60117 OSDOCS-5746
  modules/rosa-sts-creating-a-cluster-with-customizations-cli.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations-ocm.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.13, branch/enterprise-4.14

#60776 SRVCOM-2437 Add info about versioned docs
  about/about-serverless.adoc
Labels: size/XS

#60436 OSDOCS-6143: Added vCenter requirements section to vSphere UPI docs
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference, branch/enterprise-4.14

#60604 Adding some OCP terms for Vale
  .vale/styles/Vocab/OpenShiftDocs/accept.txt
  .vale/styles/Vocab/OpenShiftDocs/reject.txt
Labels: lgtm, size/XS

#60788 [enterprise-4.12] OCPBUGS-13383_412: affinity rules in the YAML correction
  modules/virt-example-vm-node-placement-node-affinity.adoc
  modules/virt-example-vm-node-placement-pod-affinity.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#60643 RHDEVDOCS-5170: Updating 1.9 and 1.10 RNs to clearly mention compatib…
  modules/op-release-notes-1-10.adoc
  modules/op-release-notes-1-9.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, qe-approved, px-approved, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60799 [enterprise-4.12] SRVCOM-2437 Cut serverless content from main distro topic maps - enterprise, dedicated and ROSA
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  serverless/about/about-serverless.adoc
Labels: size/XXL

#60802 [enterprise-4.10] SRVCOM-2437 Cut serverless content from main disto topic maps - enterprise, dedicated and ROSA
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  serverless/about/about-serverless.adoc
Labels: size/XXL

#60801 [enterprise-4.11] SRVCOM-2437 Cut serverless content from main disto topic maps - enterprise, dedicated and ROSA
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  serverless/about/about-serverless.adoc
Labels: size/XXL

#60662 SRVCOM-2381 Info on selecting channel for Serverless operator other than stable
  modules/serverless-install-cli.adoc
  modules/serverless-install-web-console.adoc
Labels: size/XS

#60663 SRVCOM-2474 Add docs on locking kn CLI version, and on upgrading after locking
  install/installing-kn.adoc
  modules/serverless-locking-version-for-cli-installed-with-rpm-package-manager.adoc
  modules/serverless-upgrading-cli-with-locked-version.adoc
Labels: size/M

#60664 SRVOCF-528 Update tekton tasks links to 1.29
  modules/serverless-functions-creating-on-cluster-builds.adoc
Labels: size/XS

#60665 ROX-16454: Kernel Module removal and Collector Logs adjustment
  modules/failing-to-load-the-kernel-driver.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
  modules/unable-to-connect-to-the-sensor.adoc
  modules/unavailability-of-the-kernel-driver.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.1

#60763 OSDOCS-6353
  modules/rosa-hcp-classic-comparison.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#60225 OSDOCS-6027: Added the OIDC Configuration to ROSA content
  _attributes/attributes-openshift-dedicated.adoc
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-hcp-byo-oidc-options.adoc
  modules/rosa-hcp-byo-oidc.adoc
  modules/rosa-oidc-config-overview.adoc
  modules/rosa-oidc-understanding.adoc
  modules/rosa-sts-oidc-provider-command.adoc
  modules/rosa-sts-oidc-provider.adoc
  rosa_architecture/rosa-oidc-overview.adoc
  rosa_architecture/rosa-sts-about-iam-resources.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60800 CNV-26234: replace cluster tasks with tasks
  modules/virt-deploying-tto.adoc
  modules/virt-supported-tekton-tasks.adoc
  virt/virtual_machines/virt-managing-vms-openshift-pipelines.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#60650 SRVCOM-2320 Add Serverless 1.29.0 release notes, update feature tables
  about/serverless-release-notes.adoc
  knative-serving/config-applications/multi-container-support-for-serving.adoc
  modules/serverless-deprecated-removed-features.adoc
  modules/serverless-rn-1-29-0.adoc
  modules/serverless-tech-preview-features.adoc
Labels: size/L

#60826 OCPBUGS-14494: Temporarily remove Support for FIPS cryptography topic
  _topic_maps/_topic_map.yml
  installing/install_config/installing-customizing.adoc
  installing/installing-preparing.adoc
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
  security/container_security/security-compliance.adoc
  security/container_security/security-hardening.adoc
  security/container_security/security-hosts-vms.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60829 OCPBUGS-14494:Added FIPS statement to 4.13 RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#60833 fix(typo in hcp creation documentation)
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#60520 OSDOCS-5762: clarify firewalld use language
  microshift_networking/microshift-firewall.adoc
  modules/microshift-firewall-about.adoc
  modules/microshift-firewall-allow-traffic.adoc
  modules/microshift-firewall-config.adoc
  modules/microshift-firewalld-install.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60804 TRACING-3227 | Remove misleading comment in distributed tracing
  modules/distr-tracing-product-overview.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, distributed-tracing, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60053 BZ#2176838: Updated VM SSH procedure
  modules/virt-accessing-vmi-ssh.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60414 OSDOCS-6146: Fix verification steps and misc copy edits
  _topic_maps/_topic_map_ms.yml
  microshift_cli_ref/microshift-cli-overview.adoc
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
  microshift_cli_ref/microshift-cli-using-oc.adoc
  microshift_cli_ref/microshift-oc-cli-commands-list.adoc
  microshift_cli_ref/microshift-usage-oc-kubectl.adoc
  microshift_networking/microshift-networking.adoc
  microshift_support/microshift-etcd.adoc
  modules/microshift-accessing-cluster-locally.adoc
  modules/microshift-accessing-cluster-open-firewall.adoc
  modules/microshift-accessing-cluster-remotely.adoc
  modules/microshift-accessing.adoc
  modules/microshift-adding-repos-to-image-builder.adoc
  modules/microshift-blocking-nodeport-access.adoc
  modules/microshift-cli-oc-about.adoc
  modules/microshift-config-cli-manifests.adoc
  modules/microshift-config-etcd.adoc
  modules/microshift-config-nodeport-limits.adoc
  modules/microshift-config-yaml.adoc
  modules/microshift-cri-o-container-runtime.adoc
  modules/microshift-deploying-a-load-balancer.adoc
  modules/microshift-firewall-allow-traffic.adoc
  modules/microshift-firewall-apply-settings.adoc
  modules/microshift-firewall-known-issue.adoc
  modules/microshift-firewalld-install.adoc
  modules/microshift-greenboot-prerollback-log.adoc
  modules/microshift-greenboot-systemd-journal-data.adoc
  modules/microshift-ki-cni-iptables-deleted.adoc
  modules/microshift-lvms-config-example-basic.adoc
  modules/microshift-mDNS.adoc
  modules/microshift-man-config-ovs-bridge.adoc
  modules/microshift-nodeport-unreachable-workaround.adoc
  modules/microshift-observe-debug-etcd-server.adoc
  modules/microshift-oc-adm-by-example-content.adoc
  modules/microshift-oc-by-example-content-gen.adoc
  modules/microshift-oc-by-example-content.adoc
  modules/microshift-preparing-for-image-building.adoc
  modules/microshift-provisioning-ostree.adoc
  modules/microshift-rpm-ostree-https.adoc
  modules/microshift-troubleshooting-nodeport.adoc
Labels: peer-review-done, size/XXL, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60831 Formatting and consistency in Data Mover cleanup section
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  modules/oadp-cleaning-up-after-data-mover-snapshots.adoc
  modules/oadp-deleting-cluster-resources-following-failure.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#60294 OADP: matchLabels should be a map of {key,value} pairs
  modules/oadp-creating-backup-cr.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#60861 Fixing PV1 build
  cicd/pipelines/customizing-configurations-in-the-tektonconfig-cr.adoc
Labels: branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60642 [RHACS] Release Notes for 3.74.4 patch
  modules/common-attributes.adoc
  release_notes/374-release-notes.adoc
Labels: peer-review-done, size/S, RHACS/patch, rhacs-docs-3.74

#59064 OADP-1582 s3 backup storage providers
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  modules/oadp-s3-compatible-backup-storage-providers.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#60813 TELCODOCS-1077 - remove outdated link from 4.13 release notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS

#60812 TELCODOCS-1077 - Remove misplaced topics in "Manually installing a single-node OpenShift cluster with ZTP" book
  scalability_and_performance/ztp_far_edge/ztp-manual-install.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13, branch/enterprise-4.14

#60876 [SRVCOM-2490] Add the FIPS note to 1.29 release notes
  modules/serverless-rn-1-29-0.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, serverless, qe-approved

#60654 OCPBUGS#8745: Removed part of the Dell iDRAC note
  modules/ipi-install-bmc-addressing-for-dell-idrac.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60902 [enterprise-4.12] RHDEVDOCS-5264 + RHDEVDOCS-5304 + RHDEVDOCS-5349: Clean up web terminal docs and add new config section
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  applications/working_with_helm_charts/configuring-custom-helm-chart-repositories.adoc
  modules/disable-quickstarts-admin-console.adoc
  modules/odc-access-web-terminal.adoc
  modules/odc-uninstalling-web-terminal.adoc
  modules/removing-devworkspace-operator.adoc
  modules/removing-web-terminal-operator.adoc
  snippets/access-cluster-configuration-console.adoc
  web_console/odc-using-web-terminal.adoc
  web_console/web-console-overview.adoc
  web_console/web_terminal/_attributes
  web_console/web_terminal/images
  web_console/web_terminal/installing-web-terminal.adoc
  web_console/web_terminal/modules
  web_console/web_terminal/odc-using-web-terminal.adoc
  web_console/web_terminal/snippets
  web_console/web_terminal/troubleshooting-web-terminal.adoc
  web_console/web_terminal/uninstalling-web-terminal.adoc
Labels: size/L, jira/valid-reference

#60905 [enterprise-4.10] RHDEVDOCS-5264 + RHDEVDOCS-5304 + RHDEVDOCS-5349: Clean up web terminal docs and add new config section
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  applications/working_with_helm_charts/configuring-custom-helm-chart-repositories.adoc
  modules/disable-quickstarts-admin-console.adoc
  modules/odc-access-web-terminal.adoc
  modules/odc-uninstalling-web-terminal.adoc
  modules/removing-devworkspace-operator.adoc
  modules/removing-web-terminal-operator.adoc
  snippets/access-cluster-configuration-console.adoc
  web_console/odc-using-web-terminal.adoc
  web_console/web-console-overview.adoc
  web_console/web_terminal/_attributes
  web_console/web_terminal/images
  web_console/web_terminal/installing-web-terminal.adoc
  web_console/web_terminal/modules
  web_console/web_terminal/odc-using-web-terminal.adoc
  web_console/web_terminal/snippets
  web_console/web_terminal/troubleshooting-web-terminal.adoc
  web_console/web_terminal/uninstalling-web-terminal.adoc
Labels: size/L, jira/valid-reference

#60770 SRVCOM-2437 Update Serverless redirects to 1.29 release
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/S, serverless

#60706 [RHACS] ROX-14958: Adding steps to Configure proxy for on prem Secured Cluster services
  _topic_map.yml
  cloud_service/installing_cloud_ocp/configuring-the-proxy-for-secured-cluster-services-in-rhacs-cloud-service.adoc
  modules/specifying-the-environment-variables-in-the-securedcluster-cr.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.0, rhacs-docs-4.1

#60828 [Osdocs 6373]: Fix the audit log documentation for OSD/ROSA
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
Labels: peer-review-done, lgtm, size/M, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60574 [OSDOCS#6098]: Add egress IP support on Nutanix
  modules/nw-egress-ips-about.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.14

#60929 TELCODOCS-1249: URGENT: Updating OSC variables
  _attributes/common-attributes.adoc
Labels: peer-review-done, lgtm, size/XS, telco, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#60814 Updates manifest listed images on image streams from TP to GA
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#60113 OCPBUG#10295:Modified the note related to network policy.
  modules/nw-networkpolicy-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60955 Fixed missing previews for 4.14 branch
  .travis.yml
Labels: size/XS

#60892 BZ#2212847: Fix mustgather image name
  modules/about-must-gather.adoc
  modules/gathering-data-specific-features.adoc
  modules/virt-must-gather-options.adoc
  modules/virt-using-virt-must-gather.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.13, branch/enterprise-4.14

#60891 CNV -29445: RN FIPS not supported
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.13

#60498 CNV- 28046: Adding KubeVirtDeprecatedAPIsRequested runbook
  modules/virt-runbook-kubevirtdeprecatedapisrequested.adoc
  virt/support/virt-runbooks.adoc
Labels: peer-review-done, lgtm, size/M, CNV, branch/enterprise-4.14

#60940 OSDOCS-6318: updates RNs 4.12.20
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference

#60954 OCPBUGS-14502 Simple Typo Fix
  modules/nodes-edge-remote-workers-strategies.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#60931 TELCODOCS-1319: URGENT: Removing OSC content from OCP docs starting from 4.13…
  _topic_maps/_topic_map.yml
  modules/sandboxed-containers-building-blocks.adoc
  modules/sandboxed-containers-check-node-eligiblilty.adoc
  modules/sandboxed-containers-collect-data-support.adoc
  modules/sandboxed-containers-collecting-data.adoc
  modules/sandboxed-containers-common-terms.adoc
  modules/sandboxed-containers-create-kata-config-resource-cli.adoc
  modules/sandboxed-containers-create-kataconfig-resource-web-console.adoc
  modules/sandboxed-containers-dashboard.adoc
  modules/sandboxed-containers-deleting-kataconfig-cli.adoc
  modules/sandboxed-containers-deleting-kataconfig-crd-cli.adoc
  modules/sandboxed-containers-deleting-kataconfig-crd-web.adoc
  modules/sandboxed-containers-deleting-kataconfig-web-console.adoc
  modules/sandboxed-containers-deleting-namespace-web-console.adoc
  modules/sandboxed-containers-deleting-operator-cli.adoc
  modules/sandboxed-containers-deleting-operator-web-console.adoc
  modules/sandboxed-containers-deleting-pods-cli.adoc
  modules/sandboxed-containers-deleting-pods-web-console.adoc
  modules/sandboxed-containers-deploying-osc-with-other-ocp-components.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-cli.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-web.adoc
  modules/sandboxed-containers-enable-debug-crio.adoc
  modules/sandboxed-containers-installing-operator-cli.adoc
  modules/sandboxed-containers-installing-operator-web-console.adoc
  modules/sandboxed-containers-installing-operator.adoc
  modules/sandboxed-containers-metrics-list.adoc
  modules/sandboxed-containers-preparing-openshift-cluster.adoc
  modules/sandboxed-containers-query-metrics.adoc
  modules/sandboxed-containers-rhcos-extensions.adoc
  modules/sandboxed-containers-selecting-nodes-web-console.adoc
  modules/sandboxed-containers-selecting-nodes.adoc
  modules/sandboxed-containers-supported-platforms.adoc
  modules/sandboxed-containers-upgrading-monitor-pods-cli.adoc
  modules/sandboxed-containers-upgrading-monitor-pods-web.adoc
  modules/sandboxed-containers-viewing-logs.adoc
  modules/sandboxed-containers-viewing-workloads-from-cli.adoc
  modules/sandboxed-containers-viewing-workloads-from-web-console.adoc
  sandboxed_containers/deploying-sandboxed-container-workloads.adoc
  sandboxed_containers/monitoring-sandboxed-containers.adoc
  sandboxed_containers/sandboxed-containers-moved.adoc
  sandboxed_containers/sandboxed-containers-release-notes.adoc
  sandboxed_containers/troubleshooting-sandboxed-containers.adoc
  sandboxed_containers/understanding-sandboxed-containers.adoc
  sandboxed_containers/uninstalling-sandboxed-containers.adoc
  sandboxed_containers/upgrading-sandboxed-containers.adoc
Labels: peer-review-done, size/XXL, telco, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60911 OBSDOCS-191: Remove TP status and update API version for alert relabelings and overrides
  modules/monitoring-creating-new-alerting-rules.adoc
  modules/monitoring-managing-core-platform-alerting-rules.adoc
  modules/monitoring-modifying-core-platform-alerting-rules.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, qe-approved, jira/valid-reference, branch/enterprise-4.14

#60985 [enterprise-4.13] TELCODOCS-1319: Removing OSC content from OCP docs starting from 4.13…
  _topic_maps/_topic_map.yml
  modules/sandboxed-containers-building-blocks.adoc
  modules/sandboxed-containers-check-node-eligiblilty.adoc
  modules/sandboxed-containers-collect-data-support.adoc
  modules/sandboxed-containers-collecting-data.adoc
  modules/sandboxed-containers-common-terms.adoc
  modules/sandboxed-containers-create-kata-config-resource-cli.adoc
  modules/sandboxed-containers-create-kataconfig-resource-web-console.adoc
  modules/sandboxed-containers-dashboard.adoc
  modules/sandboxed-containers-deleting-kataconfig-cli.adoc
  modules/sandboxed-containers-deleting-kataconfig-crd-cli.adoc
  modules/sandboxed-containers-deleting-kataconfig-crd-web.adoc
  modules/sandboxed-containers-deleting-kataconfig-web-console.adoc
  modules/sandboxed-containers-deleting-namespace-web-console.adoc
  modules/sandboxed-containers-deleting-operator-cli.adoc
  modules/sandboxed-containers-deleting-operator-web-console.adoc
  modules/sandboxed-containers-deleting-pods-cli.adoc
  modules/sandboxed-containers-deleting-pods-web-console.adoc
  modules/sandboxed-containers-deploying-osc-with-other-ocp-components.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-cli.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-web.adoc
  modules/sandboxed-containers-enable-debug-crio.adoc
  modules/sandboxed-containers-installing-operator-cli.adoc
  modules/sandboxed-containers-installing-operator-web-console.adoc
  modules/sandboxed-containers-installing-operator.adoc
  modules/sandboxed-containers-metrics-list.adoc
  modules/sandboxed-containers-preparing-openshift-cluster.adoc
  modules/sandboxed-containers-query-metrics.adoc
  modules/sandboxed-containers-rhcos-extensions.adoc
  modules/sandboxed-containers-selecting-nodes-web-console.adoc
  modules/sandboxed-containers-selecting-nodes.adoc
  modules/sandboxed-containers-supported-platforms.adoc
  modules/sandboxed-containers-upgrading-monitor-pods-cli.adoc
  modules/sandboxed-containers-upgrading-monitor-pods-web.adoc
  modules/sandboxed-containers-viewing-logs.adoc
  modules/sandboxed-containers-viewing-workloads-from-cli.adoc
  modules/sandboxed-containers-viewing-workloads-from-web-console.adoc
  sandboxed_containers/deploying-sandboxed-container-workloads.adoc
  sandboxed_containers/monitoring-sandboxed-containers.adoc
  sandboxed_containers/sandboxed-containers-moved.adoc
  sandboxed_containers/troubleshooting-sandboxed-containers.adoc
  sandboxed_containers/understanding-sandboxed-containers.adoc
  sandboxed_containers/uninstalling-sandboxed-containers.adoc
  sandboxed_containers/upgrading-sandboxed-containers.adoc
Labels: size/XXL, merge-review-in-progress, jira/valid-reference

#60933 OCPBUGS-14078: Port 80 no longer used by metal components from 4.13
  modules/ipi-install-network-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, telco, jira/severity-important, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60982 Remove misleading verify deployment from OTEL
  distr_tracing/distr_tracing_install/distr-tracing-deploying-otel.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, distributed-tracing, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60994 RHDEVDOCS-5384: Fix formatting in the migrating procedure for Tekton Hub in Pipelines doc
  modules/op-migrating-tekton-hub-data-to-an-existing-crunchy-postgres-database.adoc
Labels: peer-review-done, size/M, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60691 Removes inaccurate entry from 4.10 release notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10

#60942 [OSDOCS-6250]: Update to hosted control planes DR docs
  modules/dr-hosted-cluster-within-aws-region-script.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60908 OCPBUGS#14600 Changes the description of HPA Scaling policy
  modules/nodes-pods-autoscaling-policies.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#60986 Revert "OSDOCS#6055: Authenticating cert-manager Operator on GCP workload identity"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-gcp.adoc
Labels: size/L

#60988 Revert "[enterprise-4.14] OSDOCS#6055: Authenticating cert-manager Operator on GCP workload identity"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-gcp.adoc
Labels: size/L

#60987 Revert "[enterprise-4.13] OSDOCS#6055: Authenticating cert-manager Operator on GCP workload identity"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-gcp.adoc
Labels: size/L

#60981 Revert "OSDOCS#6374: Update the GCP without workload identity section"
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
Labels: size/S

#60984 Revert "[enterprise-4.14] OSDOCS#6374: Update the GCP without workload identity section"
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
Labels: size/S

#60983 Revert "[enterprise-4.13] OSDOCS#6374: Update the GCP without workload identity section"
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
Labels: size/S

#61020 Revert "OSDOCS#6057: Authenticating cert-manager Operator on the GCP (without workload identity)"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-non-sts-gcp.adoc
Labels: size/L

#61022 Revert "[enterprise-4.14] OSDOCS#6057: Authenticating cert-manager Operator on the GCP (without workload identity)"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-non-sts-gcp.adoc
Labels: size/L

#61021 Revert "[enterprise-4.13] OSDOCS#6057: Authenticating cert-manager Operator on the GCP (without workload identity)"
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-non-sts-gcp.adoc
Labels: size/L

#61023 Revert "OSDOCS#6030: cert-manager: setting log levels"
  _topic_maps/_topic_map.yml
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  security/cert_manager_operator/cert-manager-log-levels.adoc
Labels: size/L

#61024 Revert "[enterprise-4.13] OSDOCS#6030: cert-manager: setting log levels"
  _topic_maps/_topic_map.yml
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  security/cert_manager_operator/cert-manager-log-levels.adoc
Labels: size/L

#60957 Sync Travis file with the `main` branch
  .travis.yml
Labels: size/XS

#61027 Update travis validate step to use version 4.14
  .travis.yml
Labels: size/XS

#60738 OCPBUGS#14365: clarifying platform support for agent
  modules/understanding-agent-install.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60976 OCPBUGS-10969 Disabling CPU CFS quota pod example has wrong api version
  modules/cnf-managing-device-interrupt-processing-for-guaranteed-pod-isolated-cpus.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#60989 OCPBUGS-14131 update v4.{product-version} to read v4{product-version}
  modules/cnf-configure_for_irq_dynamic_load_balancing.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#60835 Tweaks term item to match better
  .vale/styles/Vocab/OpenShiftDocs/accept.txt
Labels: lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#60572 [OSDOCS-6241]: CPMS for Nutanix: YAML samples
  machine_management/control_plane_machine_management/cpmso-configuration.adoc
  machine_management/index.adoc
  modules/cpmso-yaml-provider-spec-aws.adoc
  modules/cpmso-yaml-provider-spec-gcp.adoc
  modules/cpmso-yaml-provider-spec-nutanix.adoc
  modules/cpmso-yaml-provider-spec-vsphere.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14

#60873 OSDOCS#14494: Removed references to FIP across the doc set
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  modules/cluster-logging-feature-reference.adoc
  modules/cluster-logging-vector-tech-preview.adoc
  modules/compliance-filtering-results.adoc
  modules/ibmz-configure-nbde-with-static-ip.adoc
  modules/images-other-jenkins-env-var.adoc
  modules/installation-aws-config-yaml.adoc
  modules/installation-azure-config-yaml.adoc
  modules/installation-azure-stack-hub-config-yaml.adoc
  modules/installation-bare-metal-agent-installer-config-yaml.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-user-infra-shared-vpc-config-yaml.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
  modules/installation-nutanix-config-yaml.adoc
  modules/installation-special-config-storage.adoc
  modules/installation-vsphere-config-yaml.adoc
  modules/machine-config-overview.adoc
  modules/osdk-csv-manual-annotations.adoc
  modules/rhcos-about.adoc
  modules/rhel-compute-requirements.adoc
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
  modules/security-compliance-nist.adoc
  modules/security-hosts-vms-openshift.adoc
  modules/ssh-agent-using.adoc
  rest_api/machine_apis/machineconfig-machineconfiguration-openshift-io-v1.adoc
  security/container_security/security-hardening.adoc
  storage/container_storage_interface/persistent-storage-csi-azure-file.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.13

#60968 OSDOCS-14350:fixes rem/dep tables
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.13

#60740 OSDOCS-6344: updates MTU parameter for InFw operator for 4.14
  modules/nw-infw-operator-cr.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14

#60822 OSDOCS-5702:updates ovn-k docs to include egressIP config object
  modules/nw-egress-ips-config-object.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60704 ROX-17267: Ability to remove default compliance info from scan results
  modules/run-compliance-scan.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.1

#60965 CNV- 28046: Update runbooks
  modules/virt-runbook-kubevirtdeprecatedapisrequested.adoc
  modules/virt-runbook-kubevirtnoavailablenodestorunvms.adoc
  virt/support/virt-runbooks.adoc
Labels: peer-review-done, size/M, CNV, branch/enterprise-4.14

#61068 4.10 typo fix
  modules/virt-using-virt-must-gather.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.10

#61069 4.12 typo fix
  modules/virt-using-virt-must-gather.adoc
Labels: peer-review-done, CNV, branch/enterprise-4.12

#61070 4.11 typo fix
  modules/virt-using-virt-must-gather.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11

#61033 Adds EOL banner for RHACS 3.73 docs
  _templates/_page_openshift.html.erb
Labels: size/XS

#60484 [RHACS] Added a note for cluster-wide proxy
  modules/configure-proxy-on-an-existing-deployment.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-3.73, rhacs-docs-3.74, rhacs-docs-4.0, rhacs-docs-4.1

#60649 Document GitOps v1.9 Release Notes
  _topic_maps/_topic_map.yml
  cicd/gitops/configuring-sso-on-argo-cd-using-dex.adoc
  cicd/gitops/gitops-release-notes.adoc
  modules/gathering-data-specific-features.adoc
  modules/gitops-disable-dex.adoc
  modules/gitops-release-notes-1-9-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: lgtm, size/L, dev-tools, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61079 [enterprise-4.12] Document GitOps v1.9 Release Notes
  _topic_maps/_topic_map.yml
  cicd/gitops/configuring-sso-on-argo-cd-using-dex.adoc
  cicd/gitops/gitops-release-notes.adoc
  modules/gathering-data-specific-features.adoc
  modules/gitops-disable-dex.adoc
  modules/gitops-release-notes-1-9-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: lgtm, size/L, dev-tools, branch/enterprise-4.12

#60930 OSDOCS#6410: Release notes: user-defined tags for Azure is generally available
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#60421 OCPBUGS-9989: Add comment to minimum vCPU requirement for Assisted In…
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: peer-review-done, size/S, telco, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60888 OCPBUGS 13867: Clarifying --manifests-only depends on --from
  modules/oc-mirror-command-reference.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61091 [enterprise-4.10] CMA add TP note for the Kafka scaler
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: size/S

#61093 [enterprise-4.12] CMA add TP note for the Kafka scaler
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: size/S

#61092 [enterprise-4.11] CMA add TP note for the Kafka scaler
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: size/S

#60993 WMCO Add note that WMCO 8.0.0 is not available
  windows_containers/windows-containers-release-notes-8-x.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#61121 CMA Adding 2.10 Release Notes
  modules/nodes-pods-autoscaling-custom-about.adoc
  modules/nodes-pods-autoscaling-custom-adding.adoc
  modules/nodes-pods-autoscaling-custom-creating-job.adoc
  modules/nodes-pods-autoscaling-custom-creating-workload.adoc
  modules/nodes-pods-autoscaling-custom-pausing.adoc
  modules/nodes-pods-autoscaling-custom-rn-210.adoc
  modules/nodes-pods-autoscaling-custom-rn.adoc
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: size/L

#60529 OSDOCS#6181: Amend references to `k8s.v1.cni.cncf.io/networks-status`
  modules/cnf-associating-secondary-interfaces-metrics-to-network-attachments.adoc
  modules/configuring-default-seccomp-profile.adoc
  modules/getting-started-cli-examining-pod.adoc
  modules/nw-multus-add-pod.adoc
  modules/nw-multus-advanced-annotations.adoc
Labels: peer-review-needed, peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#61064 OSDOCS-6473 Change images from the 48 to the 413 ones
  modules/installation-creating-gcp-worker.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, size/S, qe-approved, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61147 ROSA remove temporary test directory without symlinks for WFM
  rosa-wfm-test-directory/rosa-quickstart-guide-ui.adoc
Labels: peer-review-done, size/L, SD-docs

#60612 OSDOCS#6207: Installing a three-node Nutanix cluster
  _topic_maps/_topic_map.yml
  installing/installing_nutanix/installing-nutanix-installer-provisioned.adoc
  installing/installing_nutanix/installing-nutanix-three-node.adoc
  modules/installation-initializing.adoc
  modules/installation-three-node-cluster-cloud-provider.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.14

#60928 OSDOCS#6467: user-defined Azure tags are GA: Remove "featureSet: TechPreviewNoUpgrade"
  modules/installation-user-defined-tags-azure.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#61096 OCPBUGS#14474: Fix cols in CSI driver support table
  modules/persistent-storage-csi-drivers-supported.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#61087 Update KubeVirtDeprecatedAPIRequested runbook name
  modules/virt-runbook-kubevirtdeprecatedapirequested.adoc
  virt/support/virt-runbooks.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.14

#53699 OSDOCS-4686: Created a table for the VPC requirements
  modules/osd-aws-vpc-required-resources.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#59780 [OADP-1631] Velero CSI plugin now determines whether to restore Volume’s data from snapshots on the restore’s restorePVs setting.
  modules/oadp-creating-restore-cr.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#60877 OADP cannot create backups for customer-created volume snapshots
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications.adoc
  backup_and_restore/index.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#61055 [OSDOCS-6223]: amending IAM service account in GCP roles, removing OWNER…
  modules/osd-create-cluster-ccs.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61137 CMA adding the Kafka TP note back
  modules/nodes-cma-autoscaling-custom-install.adoc
  modules/nodes-cma-autoscaling-custom-pausing-restart.adoc
  modules/nodes-cma-autoscaling-custom-pausing-workload.adoc
  modules/nodes-cma-autoscaling-custom-trigger-kafka.adoc
  nodes/cma/nodes-cma-autoscaling-custom-rn.adoc
  nodes/cma/snippets
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61149 Replacing links that were removed in error
  modules/nodes-pods-autoscaling-custom-rn-210.adoc
  networking/ingress-operator.adoc
Labels: size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61180 [enterprise-4.10] CMA adding the Kafka TP note back
  modules/nodes-cma-autoscaling-custom-install.adoc
  modules/nodes-cma-autoscaling-custom-pausing-restart.adoc
  modules/nodes-cma-autoscaling-custom-pausing-workload.adoc
  modules/nodes-cma-autoscaling-custom-trigger-kafka.adoc
  nodes/cma/nodes-cma-autoscaling-custom-rn.adoc
Labels: size/S

#60257 Add link to SSG for admonitions
  contributing_to_docs/doc_guidelines.adoc
Labels: peer-review-done, size/XS

#59690 OSDOCS-5755
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61133 OSDOCS-6438: adds 4.13.3 to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, telco, jira/valid-reference, branch/enterprise-4.13

#59514 TELCODOCS-432: Adding iPXE content again for RHACM 2.8 release
  modules/ztp-deploying-a-site.adoc
  modules/ztp-installation-crs.adoc
  snippets/ztp-example-siteconfig.adoc
Labels: peer-review-done, size/XS, telco, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61183 OSDOCS#6465: Adds notes for 4.13.3 MS release
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#61082 [RHACS] Added removing central-attached PV instructions
  modules/remove-central-attached-pv-helm.adoc
  modules/remove-central-attached-pv-operator.adoc
  modules/remove-central-attached-pv-overview.adoc
  modules/remove-central-attached-pv-roxctl.adoc
  upgrading/upgrade-helm.adoc
  upgrading/upgrade-operator.adoc
  upgrading/upgrade-roxctl.adoc
Labels: peer-review-done, size/L, RHACS, rhacs-docs-4.1

#61032 Added tech preview and optional secured cluster settings for Operator
  _topic_map.yml
  installing/installing_ocp/install-secured-cluster-config-options-ocp.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-3.74, rhacs-docs-4.0, rhacs-docs-4.1

#54563 [RHACS] Updated backup restore procedures
  backup_and_restore/backing-up-acs.adoc
  backup_and_restore/restore-acs.adoc
  modules/backup-deployment-config-helm.adoc
  modules/backup-deployment-config-operator.adoc
  modules/on-demand-backups-roxctl-admin-pass.adoc
  modules/on-demand-backups-roxctl-api.adoc
  modules/restore-cert-roxctl.adoc
  modules/restore-deployment-config-helm.adoc
  modules/restore-deployment-config-operator.adoc
  release_notes/374-release-notes.adoc
Labels: peer-review-done, size/XL, RHACS, rhacs-docs-3.73, rhacs-docs-3.74, rhacs-docs-4.0, rhacs-docs-4.1

#60978 OCPBUGS-12982 making clarification about iDRAC firmware version
  modules/ipi-install-bmc-addressing-for-dell-idrac.adoc
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61196 OSDOCS#6466: Adds notes for 4.12.21 microshift release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12

#61080 RHDEVDOCS-5371: Correct the namespace in Pipelines as Code chapter
  modules/op-customizing-pipelines-as-code-configuration.adoc
  modules/op-pipelines-as-code-command-reference.adoc
  modules/op-using-pipelines-as-code-with-bitbucket-cloud.adoc
  modules/op-using-pipelines-as-code-with-bitbucket-server.adoc
  modules/op-using-pipelines-as-code-with-github-webhook.adoc
  modules/op-using-pipelines-as-code-with-gitlab.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61194 [MicroShift] Add an attribute for the first instance of 'oc'
  _attributes/attributes-microshift.adoc
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61216 CNV-28577: Document RXBounce option for Windows VM with ODF
  modules/virt-about-storage-volumes-for-vm-disks.adoc
  modules/virt-hardware-os-requirements.adoc
Labels: size/S, CNV, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61224 [enterprise-4.12] [MicroShift] Add an attribute for the first instance of 'oc'
  _attributes/attributes-microshift.adoc
Labels: size/XS

#60702 OSDOCS-6315: Updated Terraform VPC path
  modules/rosa-hcp-byo-oidc.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-vpc-terraform.adoc
  modules/rosa-operator-config.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
Labels: peer-review-in-progress, size/L, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61228 [enterprise-4.10] CNV-28577: Document RXBounce option for Windows VM …
  modules/virt-hardware-os-requirements.adoc
  virt/about-virt.adoc
Labels: size/S, jira/valid-reference

#61230 [enterprise-4.11] CNV-28577: Document RXBounce option for Windows VMs
  modules/virt-hardware-os-requirements.adoc
  virt/about-virt.adoc
Labels: size/S, jira/valid-reference

#61231 [enterprise-4.12] CNV-28577: Document RXBounce option for Windows VMs
  modules/virt-hardware-os-requirements.adoc
  virt/about-virt.adoc
Labels: size/S, jira/valid-reference

#61232 fix attribute
  modules/virt-about-storage-volumes-for-vm-disks.adoc
  modules/virt-hardware-os-requirements.adoc
Labels: peer-review-needed, CNV, branch/enterprise-4.13, branch/enterprise-4.14

#60941 [OSDOCS-6391]: Adds & fixes Nutanix compute machine set YAML params
  modules/machineset-yaml-nutanix.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.13, branch/enterprise-4.14

#61056 OSDOCS-6439 Z-stream RNs for 4.12.21
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress

#61241 fixing sync error
  _topic_maps/_topic_map_rosa.yml
Labels: size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#61195 CNV-25105: Create dummy 4.14 release notes file
  virt/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/S, CNV, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#61140 CNV: 24860: 4.14 RN shell creation
  _topic_maps/_topic_map.yml
  virt/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/L, CNV, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#60992 RHDEVDOCS-1817 + RHDEVDOCS-2454: Creating a VM via the +Add view of ODC and viewing VMs
  modules/odc-creating-vms.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: peer-review-done, size/M, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61135 Remove multi-arch docs from OKD
  _topic_maps/_topic_map.yml
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61122 MIG-1341 MTC 1.7.10 Release Notes
  _attributes/common-attributes.adoc
  migration_toolkit_for_containers/mtc-release-notes.adoc
  modules/migration-mtc-release-notes-1-7-10.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61004 OSDOCS-6331: Add ROSA Interactive Walkthrough link to documentation
  rosa_architecture/rosa-understanding.adoc
  rosa_getting_started/rosa-quickstart-guide-ui.adoc
Labels: size/XS, merge-review-needed, jira/valid-reference

#61256 [enterprise-4.12] Remove multi-arch doc from OKD
  _topic_maps/_topic_map.yml
Labels: size/XS, branch/enterprise-4.12

#60483 [RHACS] Added link to ACS support policy page
  installing/acs-installation-platforms.adoc
  modules/acs-requirements.adoc
  modules/amazon-s3-configuring-acs.adoc
  modules/common-attributes.adoc
  modules/configure-proxy-on-an-existing-deployment.adoc
  modules/configure-slack.adoc
  modules/identify-vulnerabilities-in-nodes.adoc
  modules/install-acs-operator-cloud.adoc
  modules/install-acs-operator.adoc
  modules/install-central-operator-tech-preview.adoc
  modules/install-central-operator.adoc
  modules/installation-methods-for-different-architectures.adoc
  modules/rhcos-analyse-detect.adoc
  modules/rhcos-enable-node-scan.adoc
  modules/rhcos-environment-variables.adoc
  modules/rhcos-match-vulnerability.adoc
  modules/secured-cluster-services-config.adoc
  modules/update-admission-controller.adoc
  operating/manage-vulnerabilities/scan-rhcos-node-host.adoc
  upgrading/upgrade-roxctl.adoc
Labels: peer-review-done, size/L, RHACS, rhacs-docs-3.74, rhacs-docs-4.0, rhacs-docs-4.1

#61264 [rhacs-docs-4.1] Manual cherry-pick of #60483
  installing/acs-installation-platforms.adoc
  modules/acs-requirements.adoc
  modules/amazon-s3-configuring-acs.adoc
  modules/common-attributes.adoc
  modules/configure-proxy-on-an-existing-deployment.adoc
  modules/configure-slack.adoc
  modules/identify-vulnerabilities-in-nodes.adoc
  modules/install-acs-operator-cloud.adoc
  modules/install-acs-operator.adoc
  modules/install-central-operator-tech-preview.adoc
  modules/install-central-operator.adoc
  modules/installation-methods-for-different-architectures.adoc
  modules/rhcos-analyse-detect.adoc
  modules/rhcos-enable-node-scan.adoc
  modules/rhcos-environment-variables.adoc
  modules/rhcos-match-vulnerability.adoc
  modules/secured-cluster-services-config.adoc
  modules/update-admission-controller.adoc
  operating/manage-vulnerabilities/scan-rhcos-node-host.adoc
  upgrading/upgrade-roxctl.adoc
Labels: size/L

#61265 Fixed supported ocp version variable
  modules/common-attributes.adoc
  modules/install-acs-operator-cloud.adoc
  modules/install-acs-operator.adoc
  modules/install-central-operator-tech-preview.adoc
  modules/install-central-operator.adoc
  modules/install-secured-cluster-operator.adoc
  modules/installation-methods-for-different-architectures.adoc
  modules/rhcos-enable-node-scan.adoc
  release_notes/40-release-notes.adoc
Labels: size/S

#61271 [rhacs-docs-4.1] Manual cherry-pick of #61265
  modules/common-attributes.adoc
  modules/install-acs-operator-cloud.adoc
  modules/install-acs-operator.adoc
  modules/install-central-operator-tech-preview.adoc
  modules/install-central-operator.adoc
  modules/install-secured-cluster-operator.adoc
  modules/installation-methods-for-different-architectures.adoc
  modules/rhcos-enable-node-scan.adoc
  release_notes/41-release-notes.adoc
Labels: size/S

#60760 CNV-19775: configuring the default CPU model
  _topic_maps/_topic_map.yml
  modules/virt-configuring-default-cpu-model.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-default-cpu-model.adoc
Labels: peer-review-done, size/M, CNV, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60114 Fix the `autopreview.sh` script
  autopreview.sh
Labels: size/M

#61272 Adjust topic-map check
  scripts/check-asciidoctor-build.sh
Labels: size/XS

#61269 4.13+: move rxbounce warning
  modules/virt-about-storage-volumes-for-vm-disks.adoc
  modules/virt-what-you-can-do-with-virt.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#61268 Move rxbounce warning
  modules/virt-what-you-can-do-with-virt.adoc
  virt/about-virt.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#60423 Allow default machinepool to be removed when another machinepool exists
  modules/creating-a-machine-pool.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-adding-taints.adoc
  modules/rosa-sdpolicy-am-compute.adoc
  osd_cluster_admin/osd_nodes/osd-managing-worker-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13, branch/enterprise-4.14
