Repository openshift/openshift-docs, pull requests merged in 2023-02, with the labels that each got.

#55225 OCPBUGS-908 updating custom seccomp profile procedures
  modules/creating-custom-seccomp-profile.adoc
  security/seccomp-profiles.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#54138 OADP-1059: Remove featureFlags field from downstream documentation
  modules/oadp-enabling-csi-dpa.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13

#55341 OSDOCS-5037:updates anchor ids for updating in 4.10 branch
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#54025 OCPBUGS#4080 explanation about VMWare licenses
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55429 OSDOCS#5035 Updates anchor IDs for updating in 4.9 branch
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, lgtm, size/M

#55435 OSDOCS#5038 Updates anchor IDs for updating in 4.11 branch
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-needed, size/M

#55428 OSDOCS-5145: comment out invalid module in install
  microshift_install/microshift-embed-in-rpm-ostree.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#55039 BZ1990455: Added importing of image stream tags
  modules/images-cluster-sample-imagestream-import.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55457 [enterprise-4.11] BZ1990455: Added importing of image stream tags
  modules/images-cluster-sample-imagestream-import.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/M

#55459 [enterprise-4.10] BZ1990455: Added importing of image stream tags
  modules/images-cluster-sample-imagestream-import.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/M

#55460 [enterprise-4.9] BZ1990455: Added importing of image stream tags
  modules/images-cluster-sample-imagestream-import.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: size/M

#55373 BZ2068397 Updating machine_management/modules/machineset-yaml-aws.adoc
  modules/machineset-yaml-aws.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55458 OCPBUGS-6886-12: Fix typo in Ironic provisioning service update release note
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS

#55473 [enterprise-4.11] OCPBUGS-6886-12: Fix typo in Ironic provisioning service update release note
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#55465 OCPBUGS#6918: Updated csi version
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: peer-review-done, lgtm, size/XS

#55120 OSDOCS-4824: Update ROSA Quotas Table
  modules/rosa-required-aws-service-quotas.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55415 OCPBUGS-6886: Add Ironic provisioning service update release note
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#54772 OSDOCS-4826: Update getting version string
  modules/microshift-adding-containers-to-blueprint.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#55426 OSDOCS-5142 and OSDOCS-5143: Use RHEL major version instead of full version
  _attributes/attributes-microshift.adoc
  modules/microshift-adding-repos-to-image-builder.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#55237 RHDEVDOCS-4426 - Loki Retention
  logging/.meta-logging-quickref.adoc
  logging/cluster-logging-loki.adoc
  modules/logging-loki-retention.adoc
  snippets/logging-create-apply-cr-snip.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55463 OCPBUGS-6802 - final tidy up for GitOps ZTP SNO worker nodes
  _topic_maps/_topic_map.yml
  modules/ztp-additional-worker-to-sno-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-sno-additional-worker-node.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#53441 BZ1998059: Adding parameters to ingress controller
  modules/nw-ingress-controller-configuration-parameters.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55434 OSDOCS-5107:updates K8s 1.26 in 4.13 RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-needed, jira/valid-reference

#55505 BZ1998059: Adding parameters to ingress controller
  modules/nw-ingress-controller-configuration-parameters.adoc
Labels: size/M, branch/enterprise-4.8

#55512 RHDEVDOCS-4426 - Formatting fix
  modules/logging-loki-retention.adoc
Labels: size/XS

#55066 OSDOCS-4813: Added the SCP requirements to AWS STS prerequisites
  modules/rosa-aws-scp.adoc
  rosa_architecture/rosa-sts-about-iam-resources.adoc
  rosa_install_access_delete_clusters/rosa_getting_started_iam/rosa-aws-prereqs.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#50538 Adding .png image format req
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#54813 OSDOCS-4592 - Create JIRA issues from docs.openshift pages
  _templates/_page_openshift.html.erb
Labels: size/S

#53697 BZ2117138 Reducing recommended vCPU and RAM values for OCP on OpenStack
  modules/installation-osp-default-deployment.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#55485 [OCPBUGS-4561]: Small update to revised instance type proc
  modules/aws-console-changing-aws-instance-type.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#55431 OSDOCS-5131: arches and dev preview nit change
  microshift_install/microshift-install-rpm.adoc
  modules/microshift-accessing-cluster-remotely-non-admin.adoc
  modules/microshift-adding-repos-to-image-builder.adoc
  modules/microshift-install-system-requirements.adoc
  modules/microshift-ovs-snapshot.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#54882 [OSDOCS-4833]: Document private S3 bucket for OIDC in AWS STS
  modules/cco-ccoctl-creating-at-once.adoc
Labels: peer-review-done, size/S, px-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55547 [enterprise-4.10] [OSDOCS-4833]: Document private S3 bucket for OIDC in AWS STS
  modules/cco-ccoctl-creating-at-once.adoc
Labels: size/S

#55546 [enterprise-4.11] [OSDOCS-4833]: Document private S3 bucket for OIDC in AWS STS
  modules/cco-ccoctl-creating-at-once.adoc
Labels: size/S

#55468 TELCODOCS-1169: Corrections to power saving configuration docs
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#55480 BZ2068397 Manualling copying changes from PR 55373 to 4.8 due to merge conflict
  modules/machineset-yaml-aws.adoc
Labels: peer-review-done, lgtm, size/S

#55193 OCPBUGS-6268 updated the hardware enablement guide
  _topic_maps/_topic_map.yml
  hardware_enablement/about-hardware-enablement.adoc
  hardware_enablement/he-driver-toolkit.adoc
  modules/psap-driver-toolkit-pulling.adoc
  modules/psap-driver-toolkit-using.adoc
  modules/psap-driver-toolkit.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55495 OSDOCS-4824_PT2: Additional AWS Quota Updates
  modules/rosa-required-aws-service-quotas.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13

#55444 CNV-23962: Added missing content-type attribute
  virt/virtual_machines/advanced_vm_management/virt-configuring-vgpu-passthrough.adoc
  virt/vm_templates/virt-deploying-vm-template-to-custom-namespace.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55549 OSDOCS-4813 Pt2: Corrected some typos and added a link
  modules/rosa-aws-scp.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#55556 CNV19923: updates to reserving PVC space
  modules/virt-how-fs-overhead-affects-space-vm-disks.adoc
  modules/virt-overriding-default-fs-overhead-value.adoc
  virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.adoc
Labels: size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55419 OSDOCS-4903: v2 PM pre-release comments nits
  _attributes/attributes-microshift.adoc
  images/311_RHDevice_Edge_Overview_0223_1.png
  images/311_RHDevice_Edge_Overview_0223_2.png
  microshift_getting_started/microshift-architecture.adoc
  microshift_getting_started/microshift-understanding.adoc
  microshift_storage/expanding-persistent-volumes-microshift.adoc
  modules/microshift-about.adoc
  modules/microshift-oc-apis-errors.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#55447 OCPBUGS-5834:specifies naming parameters for SR-IOV resourceName
  modules/nw-sriov-networknodepolicy-object.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55093 RHDEVDOCS-4448-Snippets
  modules/logging-feature-reference-5.6.adoc
  snippets/logging-elastic-dep-snip.adoc
  snippets/logging-fluentd-dep-snip.adoc
  snippets/logging-outputs-5.5-snip.adoc
  snippets/logging-outputs-5.6-snip.adoc
  snippets/logging-restructure-snip.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55234 CNV-18515: CNV 4.13 release note shell
  _topic_maps/_topic_map.yml
  virt/virt-4-12-release-notes.adoc
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XL, CNV, jira/valid-reference, branch/enterprise-4.13

#55466 MIG-1300: fix error in MTC workflow sample use case
  modules/migration-mtc-workflow.adoc
Labels: peer-review-done, size/XS, OADP, jira/valid-reference

#55364 [RHACS] Patch release updates for 3.73.2
  modules/common-attributes.adoc
  release_notes/373-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS/patch, merge-review-needed, rhacs-docs-3.73

#55534 BZ2068397 Manualling copying changes from PR 55480 to 4.9
  modules/machineset-yaml-aws.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9

#55596 CNV-25104: CNV 4.13 RN dummy file
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/S, CNV, jira/valid-reference

#55296 MIG-1282: Configure DVM to use alternative network connection strategies
  modules/migration-about-configuring-proxies.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference

#55059 OSDOCS-4868: Add step to remove manifests for control plane machine set
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#55353 Add Compliance Operator info to RHACS docs
  _topic_map.yml
  modules/compliance-operator-configure-scanning.adoc
  modules/compliance-operator-install.adoc
  modules/view-compliance-status-for-standard.adoc
  modules/vulnerability-management-scheduled-report.adoc
  operating/manage-compliance-operator/compliance-operator-rhacs.adoc
  operating/manage-compliance.adoc
Labels: peer-review-done, size/L, RHACS, merge-review-in-progress, merge-review-needed

#55569 OSDOCS-5146 added channel upgrade modules
  _topic_maps/_topic_map.yml
  modules/file-integrity-operator-release-channel.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
  security/compliance_operator/compliance-operator-updating.adoc
  security/file_integrity_operator/file-integrity-operator-configuring.adoc
  security/file_integrity_operator/file-integrity-operator-release-notes.adoc
  security/file_integrity_operator/file-integrity-operator-updating.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#55528 [RHACS] ROX13642 Fixing terminal display issue in the customer portal
  modules/retrieving-the-logs-with-the-oc-or-kubectl-command.adoc
  modules/unavailability-of-the-kernel-driver.adoc
Labels: peer-review-done, lgtm, size/XS, RHACS, rhacs-docs-3.73, rhacs-docs-3.74

#55626 Added preview page entry for RHDE docs
  scripts/ocpdocs/_previewpage
Labels: size/S

#55597 updates after initial sync
  modules/about-rhde.adoc
  overview/rhde-overview.adoc
Labels: size/XS

#55005 GH#53054 modules/update-upgrading-cli: Use 'oc adm upgrade' for current status
  modules/update-upgrading-cli.adoc
  updating/updating-cluster-cli.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55061 OSDOCS-4853: Add step to remove manifests for control plane machine set
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#55256 TELCODOCS-982 - About KMM
  _topic_maps/_topic_map.yml
  hardware_enablement/kmm-kernel-module-management.adoc
  modules/kmm-about-kmm.adoc
Labels: peer-review-done, lgtm, size/M, telco, merge-review-in-progress, merge-review-needed

#55513 OSDOCS-4912:updates RNs for zstream
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#55499 RHDEVDOCS-4892-add-deprecated-alertmanager-key-names
  modules/monitoring-applying-custom-alertmanager-configuration.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#54608 GitHub-54059: Fixing typo with field name
  modules/oc-mirror-imageset-config-params.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55411 [OCPBUGS-6849]: Update commands to find etcd pods
  modules/dr-restoring-cluster-state.adoc
  modules/etcd-defrag.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/restore-replace-crashlooping-etcd-member.adoc
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55609 CNV-19624: HCO bump 4.11.3
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11, jira/valid-reference

#55645 [enterprise-4.10] GH#53054 modules/update-upgrading-cli: Use 'oc adm upgrade' for current status
  modules/update-upgrading-cli.adoc
  updating/updating-cluster-cli.adoc
Labels: size/L

#55648 [enterprise-4.11] GH#53054 modules/update-upgrading-cli: Use 'oc adm upgrade' for current status
  modules/update-upgrading-cli.adoc
  updating/updating-cluster-cli.adoc
Labels: size/L

#55647 [enterprise-4.12] GH#53054 modules/update-upgrading-cli: Use 'oc adm upgrade' for current status
  modules/update-upgrading-cli.adoc
  updating/updating-cluster-cli.adoc
Labels: size/L

#55646 [enterprise-4.13] GH#53054 modules/update-upgrading-cli: Use 'oc adm upgrade' for current status
  modules/update-upgrading-cli.adoc
  updating/updating-cluster-cli.adoc
Labels: size/L

#55663 Fix versioning that was changed in 55005
  modules/update-upgrading-cli.adoc
Labels: size/S, branch/enterprise-4.13

#55590 BZ2038282:adds correct definition of annotation
  modules/osdk-csv-manual-annotations.adoc
  modules/osdk-init-resource.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55514 OSDOCS-5180:adds zstream update 4.12
  microshift_release_notes/microshift-4-12-release-notes.adoc
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#55040 Added the new changes for 1.9 Pipelines RN
  modules/op-release-notes-1-9.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#54155 TELCODOCS-778 OVN/OVS Troubleshooting guide
  _topic_maps/_topic_map.yml
  images/299_OpenShift_OVN-Kubernetes_arch_0123_2.png
  images/299_OpenShift_OVN-Kubernetes_arch_0223_1.png
  modules/nw-ovn-kubernetes-alerts-cli.adoc
  modules/nw-ovn-kubernetes-alerts-console.adoc
  modules/nw-ovn-kubernetes-change-log-levels.adoc
  modules/nw-ovn-kubernetes-examine-nb-database-contents-ref.adoc
  modules/nw-ovn-kubernetes-examine-sb-database-contents-ref.adoc
  modules/nw-ovn-kubernetes-install-ovnkube-trace-local.adoc
  modules/nw-ovn-kubernetes-installing-network-tools.adoc
  modules/nw-ovn-kubernetes-list-database-contents.adoc
  modules/nw-ovn-kubernetes-list-resources.adoc
  modules/nw-ovn-kubernetes-list-southbound-database-contents.adoc
  modules/nw-ovn-kubernetes-logs-cli.adoc
  modules/nw-ovn-kubernetes-logs-console.adoc
  modules/nw-ovn-kubernetes-pod-connectivity-checks.adoc
  modules/nw-ovn-kubernetes-readiness-probes.adoc
  modules/nw-ovn-kubernetes-resources-con.adoc
  modules/nw-ovn-kubernetes-running-network-tools.adoc
  modules/nw-ovn-kubernetes-running-ovnkube-trace.adoc
  modules/ovn-kubernetes-architecture-con.adoc
  modules/ovn-kubernetes-logical-architecture-con.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
  networking/ovn_kubernetes_network_provider/ovn-kubernetes-architecture-assembly.adoc
  networking/ovn_kubernetes_network_provider/ovn-kubernetes-tracing-using-ovntrace.adoc
  networking/ovn_kubernetes_network_provider/ovn-kubernetes-troubleshooting-sources.adoc
Labels: peer-review-done, size/XXL, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55263 OCPBUGS#5852 Edited Azure OS disk requirement to add "tested and recommended"
  modules/installation-azure-limits.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#54987 TELCODOCS-429 removing TP from Pod-level bonding for secondary networks CNF-3877 (TELCODOCS-429)
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#55496 OSDOCS-5184: OSDK 1.25.4 Patch release: main docs content
  modules/osdk-installing-cli-linux-macos.adoc
  modules/osdk-scorecard-config.adoc
  modules/osdk-scorecard-output.adoc
  modules/osdk-scorecard-parallel.adoc
  modules/osdk-updating-v1220-to-v1250.adoc
  operators/operator_sdk/ansible/osdk-ansible-updating-projects.adoc
  operators/operator_sdk/golang/osdk-golang-updating-projects.adoc
  operators/operator_sdk/helm/osdk-helm-updating-projects.adoc
  operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.adoc
  operators/operator_sdk/java/osdk-java-updating-projects.adoc
  operators/operator_sdk/osdk-about.adoc
  operators/operator_sdk/osdk-installing-cli.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55381 Updating TP table updating Pod-level bonding to GA for 411
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-in-progress, size/S, branch/enterprise-4.11

#55382 Updating TP table updating Pod-level bonding to GA for 412
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#55591 OCPBUGS 6674 410 the ifname parameter is now obsolete, it will not be used. The name will be taken from the pod annotation
  modules/nw-sriov-cfg-bond-interface-with-virtual-functions.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.10, merge-review-in-progress, merge-review-needed

#55012 TELCODOCS-964: Adding procedure for adding kernel arguments in ZTP
  modules/ztp-configuring-kernel-arguments-for-discovery-iso-in-manual-installations.adoc
  modules/ztp-configuring-kernel-arguments-for-discovery-iso.adoc
  scalability_and_performance/ztp_far_edge/ztp-deploying-far-edge-sites.adoc
  scalability_and_performance/ztp_far_edge/ztp-manual-install.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#55545 [OSDOCS-4808] Changing "region" to "aws_region" (within open/close tags) where appropriate.
  modules/cluster-wide-proxy-preqs.adoc
  modules/installation-aws-user-infra-requirements.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-creating-aws-bootstrap.adoc
  modules/installation-creating-aws-control-plane.adoc
  modules/installation-custom-aws-vpc.adoc
  modules/rosa-sts-setting-up-environment.adoc
  modules/storage-persistent-storage-efs-provisioner.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55375 BZ1998132: Clarified image short name note in Image configuration res…
  modules/images-configuration-shortname.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#55644 RHDEVDOCS-4817 - Logging 5.4.3 release notes errata link fix.
  modules/cluster-logging-rn-5.4.3.adoc
Labels: lgtm, size/XS

#55723 [enterprise-4.11] OSDOCS-3417: separate out sharding docs
  _topic_maps/_topic_map.yml
  images/nw-sharding-namespace-labels.png
  images/nw-sharding-route-labels.png
  modules/nw-ingress-sharding-default.adoc
  modules/nw-ingress-sharding-dns.adoc
  modules/nw-ingress-sharding-namespace-labels.adoc
  modules/nw-ingress-sharding-route-labels.adoc
  modules/nw-ingress-sharding.adoc
  networking/ingress-operator.adoc
  networking/ingress-sharding.adoc
Labels: size/L, jira/valid-reference

#55627 OSDOCS-4913:add zstream update for 4.10.51
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#53509 OpenShift Virtualization mediated devices restructure
  modules/about-using-gpu-operator.adoc
  modules/using-mediated-devices.adoc
  modules/virt-about-changing-removing-mediated-devices.adoc
  modules/virt-about-using-virtual-gpus.adoc
  modules/virt-add-remove-mediated-devices.adoc
  modules/virt-how-virtual-gpus-assigned-nodes.adoc
  modules/virt-preparing-hosts-for-mediated-devices.adoc
  modules/virt-prerequisites-mediated-devices.adoc
  modules/virt-virtual-gpus-config-overview.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-mediated-devices.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55728 [OSDOCS-5271]: Fix AWS STS terms
  _topic_maps/_topic_map.yml
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  modules/bootstrap-aws-load-balancer-operator.adoc
  modules/configuring-albo-on-sts-cluster-predefined-credentials.adoc
  modules/configuring-albo-on-sts-cluster.adoc
  modules/persistent-storage-csi-efs-sts.adoc
  modules/persistent-storage-csi-olm-operator-install.adoc
  networking/aws_load_balancer_operator/installing-albo-sts-cluster.adoc
  rosa_planning/rosa-sts-ocm-role.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-restricted-network-cluster/restricted-network-update.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55739 [enterprise-4.10] [OSDOCS-5271]: Fix AWS STS terms
  _topic_maps/_topic_map.yml
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  modules/persistent-storage-csi-efs-sts.adoc
  modules/persistent-storage-csi-olm-operator-install.adoc
  rosa_planning/rosa-sts-ocm-role.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-restricted-network-cluster/restricted-network-update.adoc
Labels: size/S

#55740 [enterprise-4.9] [OSDOCS-5271]: Fix AWS STS terms
  _topic_maps/_topic_map.yml
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-restricted-network-cluster/restricted-network-update.adoc
Labels: size/S

#55738 [enterprise-4.11] [OSDOCS-5271]: Fix AWS STS terms
  _topic_maps/_topic_map.yml
  authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
  authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
  modules/persistent-storage-csi-efs-sts.adoc
  modules/persistent-storage-csi-olm-operator-install.adoc
  rosa_planning/rosa-sts-ocm-role.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-cluster-rhel-compute.adoc
  updating/updating-cluster-within-minor.adoc
  updating/updating-restricted-network-cluster/restricted-network-update.adoc
Labels: size/M

#54913 [SRVCOM-2166] Add Serverless 1.27.0 release notes
  modules/serverless-deprecated-removed-features.adoc
  modules/serverless-kafka-sink.adoc
  modules/serverless-rn-1-27-0.adoc
  modules/serverless-tech-preview-features.adoc
  serverless/serverless-release-notes.adoc
Labels: peer-review-done, size/L, ok-to-merge, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55643 OCPBUGS#7164: Fix typo in quorum guard instruction
  modules/restore-replace-crashlooping-etcd-member.adoc
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#55192 [SRVCOM-2104] Add the info on installing kn cli older that latest
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-installing-cli-macos.adoc
  modules/serverless-installing-cli-windows.adoc
Labels: peer-review-done, size/S, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55720 Backporting netobserv to 4.10, 4.11
  _topic_maps/_topic_map.yml
  modules/network-observability-configuring-FLP-sampling.adoc
  modules/network-observability-configuring-options-overview.adoc
  modules/network-observability-configuring-options-topology.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-configuring-quickfilters-flowcollector.adoc
  modules/network-observability-flowcollector-api-specifications.adoc
  modules/network-observability-flowcollector-kafka-config.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-lokistack-create.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/network-observability-overview.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-topology.adoc
  modules/network-observability-trafficflow.adoc
  modules/network-observability-working-with-overview.adoc
  modules/network-observability-working-with-topology.adoc
  modules/network-observability-working-with-trafficflow.adoc
  modules/nw-network-observability-operator.adoc
  modules/nw-view-status-configuration-network-observability-operator.adoc
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-flowlogs-pipeline-kafka.adoc
  modules/troubleshooting-network-observability-network-flow.adoc
  networking/network_observability/_attributes
  networking/network_observability/configuring-operator.adoc
  networking/network_observability/flowcollector-api.adoc
  networking/network_observability/images
  networking/network_observability/installing-operators.adoc
  networking/network_observability/modules
  networking/network_observability/network-observability-overview.adoc
  networking/network_observability/observing-network-traffic.adoc
  networking/network_observability/snippets
  networking/network_observability/troubleshooting-network-observability.adoc
  networking/network_observability/understanding-network-observability-operator.adoc
Labels: peer-review-done, size/XXL, qe-approved, px-approved, branch/enterprise-4.10, branch/enterprise-4.11

#52395 CCXDEV-6528 Insights Operator configuration
  modules/disabling-insights-operator-alerts.adoc
  modules/disabling-insights-operator-gather.adoc
  modules/insights-operator-configuring.adoc
  modules/understanding-insights-operator-alerts.adoc
  support/remote_health_monitoring/using-insights-operator.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#54469 Updating TP snippet to match SSG
  backup_and_restore/application_backup_and_restore/oadp-api.adoc
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
  modules/distr-tracing-config-otel-collector.adoc
  modules/distr-tracing-config-storage.adoc
  modules/distr-tracing-install-otel-operator.adoc
  modules/distr-tracing-rn-technology-preview.adoc
  modules/identity-provider-about-request-header.adoc
  modules/nodes-clusters-cgroups-2.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nw-metallb-l2padvertisement-cr.adoc
  modules/ossm-cr-techPreview.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/persistent-storage-local-discovery.adoc
  modules/sbo-release-notes-1-0-1.adoc
  modules/sbo-release-notes-1-0.adoc
  modules/storage-persistent-storage-block-volume.adoc
  modules/update-network-sysctl-allowlist.adoc
  networking/multiple_networks/configuring-multi-network-policy.adoc
  snippets/technology-preview.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55771 [enterprise-4.11] Updating TP snippet to match SSG
  backup_and_restore/application_backup_and_restore/oadp-api.adoc
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
  modules/distr-tracing-config-otel-collector.adoc
  modules/distr-tracing-config-storage.adoc
  modules/distr-tracing-install-otel-operator.adoc
  modules/distr-tracing-rn-technology-preview.adoc
  modules/identity-provider-about-request-header.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nw-metallb-l2padvertisement-cr.adoc
  modules/ossm-cr-techPreview.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/persistent-storage-local-discovery.adoc
  modules/sbo-release-notes-1-0-1.adoc
  modules/sbo-release-notes-1-0.adoc
  modules/storage-persistent-storage-block-volume.adoc
  snippets/technology-preview.adoc
Labels: size/L

#55772 [enterprise-4.10] Updating TP snippet to match SSG
  backup_and_restore/application_backup_and_restore/oadp-api.adoc
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
  modules/distr-tracing-config-otel-collector.adoc
  modules/distr-tracing-config-storage.adoc
  modules/distr-tracing-install-otel-operator.adoc
  modules/distr-tracing-rn-technology-preview.adoc
  modules/identity-provider-about-request-header.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/ossm-cr-techPreview.adoc
  modules/ossm-rn-technology-preview.adoc
  modules/persistent-storage-local-discovery.adoc
  modules/sbo-release-notes-1-0-1.adoc
  modules/sbo-release-notes-1-0.adoc
  modules/storage-persistent-storage-block-volume.adoc
  snippets/technology-preview.adoc
Labels: size/L

#55733 [OCPBUGS-6506] Note in IBM Power docs not resolving correctly on access.redhat.com
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#55691 OCP BUGS 1042: Adding caveat about LowNodeUtilization not honoring ex…
  modules/nodes-descheduler-configuring-profiles.adoc
  modules/nodes-descheduler-installing.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#51013 CCXDEV-9284: Clarify SCA entitlement section
  _topic_maps/_topic_map.yml
  modules/insights-operator-configuring-sca.adoc
  modules/insights-operator-disabling-sca.adoc
  support/remote_health_monitoring/insights-operator-simple-access.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#55779 [enterprise-4.9] OCPBUGS#5852-4.9 Adding "tested and recommended"
  modules/installation-azure-limits.adoc
Labels: size/XS

#55327 OCPBUGS#6800: change the MTU in Local Zones deployments
  installing/installing_aws/installing-aws-localzone.adoc
  modules/installation-localzone-generate-k8s-manifest.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55635 RHDEVDOCS-4872 - Logging 5.6.1 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.6.1.adoc
Labels: lgtm, size/M

#55464 RHDEVDOCS-4940-firstPR: Covers CVE update for GitOps 1.7.1, 1.6.4, and 1.5.9
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-2-2.adoc
  modules/gitops-release-notes-1-4-12.adoc
  modules/gitops-release-notes-1-4-2.adoc
  modules/gitops-release-notes-1-5-6.adoc
  modules/gitops-release-notes-1-5-9.adoc
  modules/gitops-release-notes-1-6-2.adoc
  modules/gitops-release-notes-1-6-4.adoc
  modules/gitops-release-notes-1-7-0.adoc
  modules/gitops-release-notes-1-7-1.adoc
Labels: lgtm, size/M, px-approved

#55761 ACM-2.7-link:updates link to 2.7 docs
  architecture/control-plane.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55774 OSDOCS-5281: update module to procedure format
  modules/microshift-troubleshooting-nodeport.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#55432 TELCODOCS 993 - Update or replace the "Installing" topic
  hardware_enablement/kmm-kernel-module-management.adoc
  modules/kmm-installation.adoc
  modules/kmm-installing-older-versions.adoc
  modules/kmm-installing-using-cli.adoc
  modules/kmm-installing-using-web-console.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55700 BZ1996674: Removed status entry from Removing the cluster-wide proxy
  modules/nw-proxy-remove.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55806 [OCPBUGS-6506] Follow up error
  modules/registry-configuring-storage-baremetal.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55640 OSDOCS-4444 and OSDOCS-5270: adding Running Apps book and operators content
  _topic_maps/_topic_map_ms.yml
  images/microshift_ovn_topology.png
  microshift_running_apps/_attributes
  microshift_running_apps/images
  microshift_running_apps/microshift-operators.adoc
  microshift_running_apps/modules
  microshift_running_apps/snippets
  modules/microshift-deploying-operators.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#55805 Slight change to TP snippet to match SSG
  snippets/technology-preview.adoc
Labels: peer-review-done, size/XS, RHACS, merge-review-in-progress, merge-review-needed

#55837 [enterprise-4.11] Manual cherry-pick #54803
  .travis.yml
Labels: size/XS

#55838 [enterprise-4.12] Manual cherry-pick #54803
  .travis.yml
Labels: size/XS

#55839 [enterprise-4.13] Manual cherry-pick #54803
  .travis.yml
Labels: size/XS

#55804 R ns 4.99.55 date
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9

#55067 CNV-15757: Data volume garbage collection
  _topic_maps/_topic_map.yml
  modules/virt-about-datavolumes.adoc
  modules/virt-deleting-dvs.adoc
  modules/virt-deleting-virt-cli.adoc
  modules/virt-listing-dvs.adoc
  virt/install/uninstalling-virt.adoc
  virt/virtual_machines/cloning_vms/virt-enabling-user-permissions-to-clone-datavolumes.adoc
  virt/virtual_machines/virtual_disks/virt-cloning-a-datavolume-using-smart-cloning.adoc
  virt/virtual_machines/virtual_disks/virt-creating-data-volumes.adoc
  virt/virtual_machines/virtual_disks/virt-deleting-datavolumes.adoc
Labels: peer-review-done, size/L, CNV, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55665 OSDOCS-4642: Updating procedure to include multi-arch (Update in heterogeneous clusters)
  modules/cnf-topology-aware-lifecycle-manager-preparing-for-updates.adoc
  modules/installation-mirror-repository.adoc
  modules/ipi-install-mirroring-for-disconnected-registry.adoc
  modules/update-configuring-image-signature.adoc
  modules/update-mirror-repository.adoc
  modules/update-service-mirror-release.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#55589 OADP-1223: Fix callouts in example Backup CR
  modules/oadp-creating-backup-cr.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, OADP, jira/valid-reference, branch/enterprise-4.13

#55694 OSDOCS-5180-followup: Replaced refer to entries with see entries
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, size/XS

#55849 WMCO 7.0.1 release notes
  windows_containers/windows-containers-release-notes-7-x.adoc
Labels: peer-review-done, lgtm, size/S

#55775 [OSDOCS-5257] Additional support statements in ROSA docs
  modules/rosa-getting-support.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#55521 OSDOCS-4971: Restructure CLI reference book
  _attributes/attributes-microshift.adoc
  _topic_maps/_topic_map_ms.yml
  cli_reference/index.adoc
  cli_reference/openshift_cli/getting-started-cli.adoc
  microshift_cli_ref/_attributes
  microshift_cli_ref/images
  microshift_cli_ref/microshift-cli-overview.adoc
  microshift_cli_ref/microshift-cli-using-oc.adoc
  microshift_cli_ref/microshift-oc-cli-commands-list.adoc
  microshift_cli_ref/microshift-oc-cli-install.adoc
  microshift_cli_ref/microshift-oc-config.adoc
  microshift_cli_ref/microshift-usage-oc-kubectl.adoc
  microshift_cli_ref/modules
  microshift_cli_ref/snippets
  microshift_getting_started/microshift-architecture.adoc
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  modules/cli-installing-cli-brew.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli.adoc
  modules/microshift-cli-oc-about.adoc
  modules/microshift-cli-oc-get-help.adoc
  modules/microshift-oc-apis-errors.adoc
  modules/microshift-oc-by-example-content.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, jira/valid-reference

#55760 [OCPBUGS-7283]: Revert etcd disk latency to 10ms
  modules/recommended-etcd-practices.adoc
Labels: size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#53254 Add OpenShift SDN network policy fully supported in matrix
  modules/nw-ovn-kubernetes-matrix.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55685 OSDOCS-5246: RN for backporting Network Observability Operator to 4.11
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, px-approved, branch/enterprise-4.11, jira/valid-reference

#55687 OSDOCS-5246: RN for backporting Network Observability Operator to 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, px-approved, branch/enterprise-4.10, jira/valid-reference

#55762 GH#55397 Updated 4.8 to 4.10 references to 4.10 to 4.12 for EUS updates
  modules/updating-eus-to-eus-upgrade.adoc
  updating/index.adoc
  updating/preparing-eus-eus-upgrade.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55587 [RHACS] Updated integration docs for the new Clair v4 integration
  integration/integrate-with-image-vulnerability-scanners.adoc
  modules/integrate-with-clair.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-3.74

#55405 OSDOCS-4802: Clarifying life cycle language
  modules/life-cycle-mandatory-upgrades.adoc
Labels: size/XS, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#55734 RHDEVDOCS-4826-Topology support for Service Binding Label Selector Implementation
  applications/connecting_applications_to_services/odc-connecting-an-application-to-a-service-using-the-developer-perspective.adoc
  images/odc-delete-service-binding.png
  images/odc-label-selector-sb-details.png
  images/odc-label-selector-topology-side-panel.png
  modules/odc-visualizing-the-binding-connections-to-resources.adoc
  modules/odc_customizing-a-developer-catalog-or-its-sub-catalogs-using-the-form-view.adoc
Labels: size/M

#55868 [OCPBUGS-6506] Backport to 4.11
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/registry-configuring-storage-baremetal.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11

#55871 [OCPBUGS-6506] Backport to 4.10
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/registry-configuring-storage-baremetal.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10

#55873 [OCPBUGS-6506] Backport to 4.9
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/registry-configuring-storage-baremetal.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9

#55894 OSDOCS-5339-okd: fix dedead links OKD oc install
  modules/cli-installing-cli.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11

#55223 OSDOCS-3969c Alibaba VPC Installation
  _topic_maps/_topic_map.yml
  installing/installing_alibaba/installing-alibaba-vpc.adoc
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-telemetry.adoc
  modules/installation-alibaba-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-custom-alibaba-vpc.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/logging-in-by-using-the-web-console.adoc
  modules/manually-creating-alibaba-manifests.adoc
  modules/ssh-agent-using.adoc
  snippets/custom-dns-server.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#55832 OSDOCS-5306: changing authToken to FORWARD
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-roles-create.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#55867 OSDOCS-5273-R: Documented 4.11.27 z-stream release
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11

#55637 RHDEVDOCS-4926- Logging 5.4.11 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.4.11.adoc
Labels: size/S

#55638 RHDEVDOCS-4927 - Logging 5.5.7 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.5.7.adoc
Labels: lgtm, size/S, dev-tools, branch/enterprise-4.9, branch/enterprise-4.12, branch/enterprise-4.13

#54703 [GH#53801]: Updating the openshift loki documentation to improve "Deploying the LokiStack" section.
  modules/cluster-logging-loki-deploy.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55856 [OSDOCS-4944]: updating links in hosted control plane docs to point to the latest MCE doc version
  architecture/control-plane.adoc
  architecture/mce-overview-ocp.adoc
  modules/hosted-control-planes-overview.adoc
  modules/sriov-operator-hosted-control-planes.adoc
  scalability_and_performance/using-node-tuning-operator.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55737 BZ2094492: Added removing backup section to Backup & restore docs
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  modules/oadp-deleting-backups.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#53597 TELCODOCS-804 adding conceptual info about the BMO
  images/302_OpenShift_Bare_Metal_Operator_0223.png
  modules/bmo-about-the-bare-metal-operator.adoc
  modules/con_bmo-bare-metal-operator-architecture.adoc
  post_installation_configuration/bare-metal-configuration.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#55924 OCPBUGS#5194: Fix 'aggregate' typo in PO
  modules/olm-installing-po-after.adoc
  modules/olm-installing-po-during.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#55858 OCPBUGS-411: Amend `oc` prerequisite to adhere to glossary usage.
  modules/getting-started-cli-deploying-first-image.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#54736 OSDOCS-5119 Removing DNS zones and createfirewallrules from GCP XPN
  installing/installing_gcp/installing-gcp-shared-vpc.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-shared-vpc-config.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed

#55968 enterprise-4.10 OSDOCS-3969c Alibaba-VPC cherrypick to 4.10
  _topic_maps/_topic_map.yml
  installing/installing_alibaba/installing-alibaba-vpc.adoc
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-telemetry.adoc
  modules/installation-alibaba-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-custom-alibaba-vpc.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/logging-in-by-using-the-web-console.adoc
  modules/manually-creating-alibaba-manifests.adoc
  modules/ssh-agent-using.adoc
  snippets/custom-dns-server.adoc
Labels: size/L, merge-review-in-progress

#55964 enterprise-4.11 OSDOCS-3969c Alibaba-VPC cherrypick to 4.11 - fixing merge conflicts
  _topic_maps/_topic_map.yml
  installing/installing_alibaba/installing-alibaba-vpc.adoc
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-telemetry.adoc
  modules/installation-alibaba-config-yaml.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-custom-alibaba-vpc.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-obtaining-installer.adoc
  modules/logging-in-by-using-the-web-console.adoc
  modules/manually-creating-alibaba-manifests.adoc
  modules/ssh-agent-using.adoc
  snippets/custom-dns-server.adoc
Labels: size/L, merge-review-in-progress

#55967 RHDEVDOCS-4927 - Manual CP of 55638
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.5.6.adoc
  modules/cluster-logging-rn-5.5.7.adoc
Labels: size/M
