Repository openshift/openshift-docs, pull requests merged in 2023-08, with the labels that each got.

#62913 [enterprise-4.12] OSDOCS#6055: Authenticating cert-manager Operator with GCP workload identity
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-gcp.adoc
Labels: size/L

#62915 [enterprise-4.12] OSDOCS#6057: Authenticating cert-manager Operator on GCP (without workload identity)
  _topic_maps/_topic_map.yml
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  security/cert_manager_operator/cert-manager-authenticate-non-sts-gcp.adoc
Labels: size/L

#62929 [enterprise-4.12] OSDOCS#6017 cert-manager : Configuring an ACME issuer
  modules/cert-manager-acme-about.adoc
  modules/cert-manager-acme-dns-providers.adoc
  modules/cert-manager-acme-dns01-ambient-aws.adoc
  modules/cert-manager-acme-dns01-ambient-gcp.adoc
  modules/cert-manager-acme-dns01-explicit-aws.adoc
  modules/cert-manager-acme-dns01-explicit-azure.adoc
  modules/cert-manager-acme-dns01-explicit-gcp.adoc
  modules/cert-manager-override-arguments.adoc
  security/cert_manager_operator/cert-manager-operator-issuer-acme.adoc
Labels: size/XL

#62916 [enterprise-4.12] OSDOCS#6275: Add release notes for cert-manager Operator 1.11
  modules/cert-manager-issuer-types.adoc
  security/cert_manager_operator/cert-manager-operator-release-notes.adoc
Labels: size/M

#62991 Remove-Virt-files
  modules/virt-cluster-resource-requirements.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/L

#62911 [OCPBUGS16738] Broken links to IBM docs - change zvm/71 to latest
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/minimum-ibm-z-system-requirements.adoc
  modules/preferred-ibm-z-system-requirements.adoc
  scalability_and_performance/ibm-z-recommended-host-practices.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#62948 OCPBUGS-17057: Removed tech preview callout and joined tables
  modules/nw-sriov-hwol-supported-devices.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62804 virt: Update DPDK checkup's documentation
  modules/virt-checking-cluster-dpdk-readiness.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: peer-review-done, lgtm, size/M, CNV, branch/enterprise-4.14

#62963 OCPBUGS-16441: Correct indentation issues in LVMS YAML files
  modules/lvms-creating-logical-volume-manager-cluster.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-cli.adoc
Labels: lgtm, size/S, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62938 Removing PV and PVC for PTP events docs
  modules/cnf-about-ptp-fast-event-notifications-framework.adoc
  modules/cnf-configuring-the-ptp-fast-event-publisher.adoc
  modules/cnf-migrating-from-amqp-to-http-transport.adoc
  modules/nw-rfhe-creating-hardware-event.adoc
  modules/ztp-configuring-hwevents-using-pgt.adoc
  modules/ztp-configuring-ptp-fast-events.adoc
  networking/using-ptp.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.13, branch/enterprise-4.14

#62988 [enterprise-4.10] RHDEVDOCS-5412: GitOps 1.8.4 release notes
  cicd/gitops/gitops-release-notes.adoc
  cicd/gitops/installing-openshift-gitops.adoc
  modules/gitops-release-notes-1-8-4.adoc
Labels: size/M, jira/valid-reference

#62809 OCPBUGS#9210: Updated folder parameter info in vSphere UPI docs
  modules/installation-vsphere-config-yaml.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#62848 OCPBUGS#9122: Improved configuring your firewall install info
  modules/configuring-firewall.adoc
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63022 [enterprise-4.10] OCPBUGS-9122: Improved configuring your firewall install info
  modules/configuring-firewall.adoc
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: size/S, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#63012 [OSDOCS-7140]: Removing node tuning topic from assembly
  hosted_control_planes/hcp-managing.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14

#62825 OSDOCS#7012: Platform none support
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  modules/agent-install-dns-none.adoc
  modules/agent-install-load-balancing-none.adoc
  modules/understanding-agent-install.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.14

#62016 [OSDOCS-6598]: Defined ARN role, by adding new module for preparing aws account and seperating code into into subtask commands
  modules/oadp-installing-oadp-rosa-sts.adoc
  modules/oadp-preparing-aws-credentials.adoc
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63039 [enterprise-4.13] [OSDOCS-6598]: Defined ARN role, by adding new module for preparing aws account and seperating code into into subtask commands
  modules/oadp-installing-oadp-rosa-sts.adoc
  modules/oadp-preparing-aws-credentials.adoc
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
Labels: size/L

#62591 OSDOCS-6454 Tech preview and RN for MaxUnavailableStatefulSet
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#63033 OSDOCS-6454 featureset addition
  modules/nodes-cluster-enabling-features-about.adoc
Labels: size/XS, branch/enterprise-4.14

#63041 [RHACS] xref fixes for build failure on portal
  installing/acs-high-level-overview.adoc
  installing/acs-installation-platforms.adoc
Labels: size/S

#62930 OSDOCS#7109: Adds notes for Microshift 4.12.27 release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#61786 OSDOCS-6655: Release notes for admin-ack for upgrading 4.13 to 4.14
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#63026 OSDOCS-7202: Fix broken link in ROSA CLI Tools
  cli_reference/rosa_cli/rosa-get-started-cli.adoc
  modules/rosa-configure.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61787 OSDOCS-6656: Updating for admin-ack for 4.14
  _topic_maps/_topic_map.yml
  modules/update-preparing-ack.adoc
  modules/update-preparing-evaluate-apirequestcount-workloads.adoc
  modules/update-preparing-evaluate-apirequestcount.adoc
  modules/update-preparing-list.adoc
  modules/update-preparing-migrate.adoc
  updating/preparing_for_updates/updating-cluster-prepare.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
  updating/updating_a_cluster/updating-cluster-web-console.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.14

#63044 OCPBUGS-9122-RE: Change noun for OCPBUGS-9122 update
  modules/configuring-firewall.adoc
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63065 Fix error in PTP 4.13 RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#63045 [enterprise-4.12] OCPBUGS-9210: Updated folder parameter info in vSphere UPI docs
  modules/installation-vsphere-config-yaml.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#63046 [enterprise-4.11] OCPBUGS-9210: Updated folder parameter info in vSphere UPI docs
  modules/installation-vsphere-config-yaml.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#63047 [enterprise-4.10] OCPBUGS-9210: Updated folder parameter info in vSphere UPI docs
  modules/installation-vsphere-config-yaml.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#62852 OSDOCS#6278: Release note for Nutanix three-node cluster
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#63004 OBSDOCS-406 - Logging 5.6.8 & 5.5.14 RNs
  logging/cluster-logging-release-notes.adoc
  logging/v5_5/logging-5-5-release-notes.adoc
  modules/logging-rn-5.5.14.adoc
  modules/logging-rn-5.6.9.adoc
Labels: peer-review-done, size/M

#60348 OSDOCS#5975: Custom RHCOS image for control plane and compute machines
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.14

#62992 OBSDOCS-406 - Logging 5.7.4 Release Notes
  logging/cluster-logging-release-notes.adoc
  logging/v5_7/logging-5-7-release-notes.adoc
  modules/logging-rn-5.7.4.adoc
Labels: peer-review-done, size/M

#62673 Splunk addon name change and related updates
  integration/integrate-with-splunk.adoc
  modules/install-and-configure-the-splunk-add-on.adoc
  modules/troubleshoot-the-splunk-add-on.adoc
  modules/update-the-splunk-add-on.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.1

#62962 OSDOCS#7094: Added warning for MTU value
  modules/nw-sriov-networknodepolicy-object.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#63108 Fix a typo in node garbage collection docs
  modules/nodes-nodes-garbage-collection-images.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63116 RHDEVDOCS-5172 add preview to travis
  .travis.yml
Labels: size/M

#62228 RHDEVDOCS-4110: GitOps Operator to configure secure communication wit…
  _topic_maps/_topic_map.yml
  cicd/gitops/configuring-secure-communication-with-redis.adoc
  modules/gitops-configuring-tls-for-redis-with-autotls-disabled.adoc
  modules/gitops-configuring-tls-for-redis-with-autotls-enabled.adoc
Labels: lgtm, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63048 TRACING-3319: Migrate upstream Tempo operator upstream docs to Grafana
  modules/distr-tracing-rn-technology-preview.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63077 [enterprise-4.14] OSDOCS-5051: update RN for haproxy
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14

#61985 [enterprise-4.12] OSDOCS-4799: Add release note for post-install hybrid network configuration
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference

#63106 [OSDOCS-7284.1]: Numbered list in documentation incorrectly formatted
  modules/cluster-autoscaler-cr.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#60476 OSDOCS#6119: Minimum req permissions to deploy OpenShift on Nutanix
  modules/installation-nutanix-installer-infra-reqs.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13, branch/enterprise-4.14

#60569 OSDOCS#6119: Minimum req permissions to deploy OpenShift on Nutanix
  modules/installation-nutanix-installer-infra-reqs.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#60570 OSDOCS#6119: Minimum req permissions to deploy OpenShift on Nutanix
  modules/installation-nutanix-installer-infra-reqs.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11

#62581 [SRVKS-1081, SRVCOM-2511] Serverless release notes 1.29.1
  about/serverless-release-notes.adoc
  modules/release-notes-template.adoc
  modules/serverless-rn-1-29-1.adoc
Labels: peer-review-done, size/M, serverless

#56171 OSDOCS-4879: Region Addition
  modules/rosa-sdpolicy-am-regions-az.adoc
  modules/sdpolicy-am-regions-availability-zones.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-needed, jira/valid-reference

#61527 OCPBUGS#15206: Specify `ref` option as mandatory if branch is not "master"
  modules/builds-source-code.adoc
  modules/builds-using-github-webhooks.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63076 OCPBUGS#15879: etcd-defrag: remove disk quota note from Next Steps
  modules/etcd-defrag.adoc
Labels: peer-review-done, size/XS

#63057 OCPBUGS#16708: greenboot RPM name correction
  microshift_install/microshift-greenboot.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#62824 [OSDOCS-7069]: Add entry to hosted control planes glossary
  modules/hosted-control-planes-concepts-personas.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#63074 OCPBUGS-9217 Include caveats for load balancer services
  modules/nw-create-load-balancer-service.adoc
Labels: peer-review-done, lgtm, size/XS

#62864 OSSM-4529: added "the" to sentence to fix typo/dropped word
  modules/ossm-install-ossm-operator.adoc
Labels: size/XS, jira/valid-reference

#62753 Fix mixed up Pods and Nodes in taint/toleration examples
  modules/nodes-scheduler-taints-tolerations-about.adoc
  modules/nodes-scheduler-taints-tolerations-adding-machineset.adoc
  modules/nodes-scheduler-taints-tolerations-adding.adoc
  modules/nodes-scheduler-taints-tolerations-binding.adoc
  modules/nodes-scheduler-taints-tolerations-removing.adoc
  modules/nodes-scheduler-taints-tolerations-special.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#62599 OCPBUGS-16180 Values incorrect in recommended control plane practices
  modules/recommended-scale-practices.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14

#63185 RHDEVDOCS-5172 set main branch to gitops-docs for netlify build
  .travis.yml
Labels: size/XS

#62131 [OCPBUGS-14626]: Removing references to oc login from etcd restore doc
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63117 OSDOCS-7285: IMDSv2 OCP version limitation
  modules/machineset-creating-imds-options.adoc
  modules/machineset-imds-options.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60107 [multiple]: AWS and Azure CCMs TP to GA
  modules/cluster-cloud-controller-manager-operator.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#63120 OCPBUGS-7621-vsphere-only: Added ifdef statement to isolate update fr…
  modules/installation-launching-installer.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#63213 [enterprise-4.11] OSDOCS-7285: IMDSv2 OCP version limitation
  modules/machineset-creating-imds-options.adoc
  modules/machineset-imds-options.adoc
Labels: size/XS, jira/valid-reference

#60764 OSDOCS#4429: Scrub the OpFrame docs for `default` namespaces
  modules/osdk-ansible-k8s-local.adoc
  modules/osdk-crd-templates.adoc
  modules/osdk-pruning-utility-config.adoc
  modules/osdk-publish-catalog.adoc
  modules/osdk-run-deployment.adoc
  modules/osdk-run-locally.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#61358 OSDOCS-4561: Removed Latency Sensitivity references from vSphere UPI …
  modules/installation-vsphere-machines.adoc
  modules/machine-vsphere-machines.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61043 OCPBUGS-11113 making clarification about add the annotation cpu-quota…
  modules/cnf-configuring-workload-hints.adoc
  scalability_and_performance/cnf-low-latency-tuning.adoc
Labels: peer-review-done, lgtm, size/S, telco

#62844 OCPBUG#16746: Modified steps related to local OCI catalogs.
  modules/oc-mirror-command-reference.adoc
  modules/oc-mirror-oci-format.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.14

#63035 OSDOCS-7087: remove "optional" from greenboot
  microshift_install/microshift-greenboot.adoc
  microshift_running_apps/microshift-greenboot-workload-scripts.adoc
  modules/microshift-adding-service-to-blueprint.adoc
  modules/microshift-greenboot-microshift-health-script.adoc
  modules/microshift-greenboot-systemd-journal-data.adoc
  modules/microshift-install-rpms.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#61725 [enterprise-4.12] CNV-22631: HCO Bump 4.12.5
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference

#62960 CNV- 31215: customize VM settings
  modules/virt-creating-vm-template.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.14

#63252 fix admonition
  virt/virtual_machines/virt-create-vms.adoc
Labels: peer-review-done, CNV

#63251 RHDEVDOCS-5483: Updated the travis file for netlify preview
  .travis.yml
Labels: size/M, jira/valid-reference

#63094 OSDOCS-7050: cluster wide proxy doc issues
  modules/cluster-wide-proxy-preqs.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63230 Nodes Miscellaneous docs fixes during ROSA review
  modules/nodes-pods-pod-disruption-about.adoc
  nodes/containers/nodes-containers-using.adoc
  nodes/jobs/nodes-nodes-jobs.adoc
  nodes/scheduling/nodes-scheduler-node-affinity.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63249 [OCPBUGS-17411]: Create ServiceAccount cluster-capacity-sa in default namespace
  modules/nodes-cluster-resource-levels-job.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63121 RN-about-eus: updates EUS statement in RNs for 4.14
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#63049 ML-OCPBUGS-10583: Corrected a typo.
  modules/op-installing-and-deploying-tekton-hub-on-an-openshift-cluster.adoc
Labels: lgtm, size/XS, branch/enterprise-4.11, jira/severity-low, jira/invalid-bug, merge-review-needed, jira/valid-reference

#63264 Placing the guidance about user-replaced values to its appropriate lo…
  contributing_to_docs/doc_guidelines.adoc
Labels: peer-review-done, size/S

#63188 OSDOCS#7302: Release notes for the cert-manager Operator 1.10.3
  security/cert_manager_operator/cert-manager-operator-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#63285 add 1.10 preview to .travis.yml
  .travis.yml
Labels: size/XS

#59526 Telcodocs 994 Documenting TAP device plugin
  modules/nw-multus-tap-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.14

#63257 Removes prune-registry flag - false from documentation
  modules/pruning-images.adoc
  registry/configuring-registry-operator.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#56176 OSDOCS-4877 Availability Zones Switzerland
  modules/rosa-sdpolicy-am-regions-az.adoc
  modules/sdpolicy-am-regions-availability-zones.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#63216 OSDOCS-7286 Z-stream RNs for 4.13.8
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#62676 [OSDOCS 6508] Restructure install config parms to book level IBM Z
  _topic_maps/_topic_map.yml
  installing/installing_ibm_z/installation-config-parameters-ibm-z-kvm.adoc
  installing/installing_ibm_z/installation-config-parameters-ibm-z.adoc
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.14

#63075 OSDOCS#6982: Nutanix CCM steps for installs
  installing/installing_nutanix/installing-nutanix-installer-provisioned.adoc
  modules/installation-nutanix-ccm.adoc
  modules/manually-configure-iam-nutanix.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#61150 OSDOCS-6297: Removed dual stack limitation note
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.14

#63274 OSDOCS#7310: Adds notes for MS 4.13.8 release
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#63241 RHDEVDOCS-5589: Pipelines 1.11.1 release notes
  modules/op-release-notes-1-11.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#63273 OSDOCS-6646: remove CIDR from clusterNetwork parameter
  modules/microshift-config-yaml.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#63334 [enterprise-4.14]OSDOCS-6297: Removed dual stack limitation note
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
Labels: size/S, jira/valid-reference

#63322 OCPBUGS-15937: small syntax fix
  modules/update-vsphere-virtual-hardware-on-template.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63283 OSDOCS-7288: Documented 4.10.65 z-stream release notes
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#62967 [virt] DPDK Checkup: Update user facing API
  modules/virt-checking-cluster-dpdk-readiness.adoc
  modules/virt-dpdk-config-map-parameters.adoc
Labels: peer-review-done, lgtm, size/M, CNV, branch/enterprise-4.14

#62953 OSSM-4463: Link out to KCS from relevant docs location
  _attributes/common-attributes.adoc
  modules/ossm-about-smcp.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63037 CNV-30685: RHEL subscription info
  modules/virt-about-auto-bootsource-updates.adoc
  virt/getting_started/virt-web-console-overview.adoc
  virt/virtual_machines/virt-create-vms.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.14

#63348 OSDOCS-7287: adds 4.12.28 RNs and fixes link typo
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference

#63270 [enterprise-4.14] CNV-30838: RN - DV GC is now disabled by default
  virt/release_notes/virt-4-14-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference

#62426 CNV-14623: Hot plugging network interfaces
  _topic_maps/_topic_map.yml
  modules/virt-hot-plugging-bridge-network-interface-cli.adoc
  modules/virt-hot-unplugging-bridge-network-interface-cli.adoc
  modules/virt-virtctl-commands.adoc
  virt/vm_networking/virt-hot-plugging-network-interfaces.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.14

#63202 OSDOCS-7311: adds release note MShift 4.12.28
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#62606 [OSDOCS-6908] IMDSv2 Documentation wrongly under Node Management
  modules/rosa-create-objects.adoc
  modules/rosa-imds-cli.adoc
  modules/rosa-imds-ui.adoc
  modules/rosa-imds.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations-cli.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations-ocm.adoc
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63325 OCPBUGS#17482: vSphere version number updates
  modules/update-vsphere-virtual-hardware-on-compute-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-control-plane-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-template.adoc
  updating/index.adoc
  updating/updating-hardware-on-nodes-running-on-vsphere.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.13

#63323 OSDOCS#6193: Version bump in links to UPI install JSON templates
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-control-plane.adoc
  modules/installation-arm-dns.adoc
  modules/installation-arm-image-storage.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-arm-worker.adoc
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-dns.adoc
  modules/installation-cloudformation-security.adoc
  modules/installation-cloudformation-vpc.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-deployment-manager-bootstrap.adoc
  modules/installation-deployment-manager-control-plane.adoc
  modules/installation-deployment-manager-ext-lb.adoc
  modules/installation-deployment-manager-firewall-rules.adoc
  modules/installation-deployment-manager-iam-shared-vpc.adoc
  modules/installation-deployment-manager-int-lb.adoc
  modules/installation-deployment-manager-private-dns.adoc
  modules/installation-deployment-manager-vpc.adoc
  modules/installation-deployment-manager-worker.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.14

#63327 OCPBUGS#17482: vSphere version number updates
  modules/update-vsphere-virtual-hardware-on-compute-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-control-plane-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-template.adoc
  updating/index.adoc
  updating/updating_a_cluster/updating-hardware-on-nodes-running-on-vsphere.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.14

#63132 OCPBUGS-11810-12: Updated RHEL versions for install-bare-metal-min-res…
  modules/installation-minimum-resource-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#63218 OSDOCS-5912: OSUS architecture recommendations
  modules/disconnected-osus-overview.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62643 Optimize the Travis build
  .travis.yml
  requirements.txt
Labels: peer-review-done, size/M

#63383 RHACS: Update date for patch release
  release_notes/40-release-notes.adoc
Labels: size/XS, rhacs-docs-4.0

#63321 OSSM-3033: [DOC] Document supported authentication strategies for Kiali
  modules/ossm-supported-configurations.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63384 [enterprise-4.10] Manual cherrypick of #62643
  .travis.yml
  requirements.txt
Labels: size/M

#63391 [enterprise-4.12] Manual cherrypick of #62643
  .travis.yml
  requirements.txt
Labels: size/M

#63393 [enterprise-4.13] Manual cherrypick of #62643
  .travis.yml
  requirements.txt
Labels: size/M

#63392 [enterprise-4.14] Manual cherrypick of #62643
  .travis.yml
  requirements.txt
Labels: size/M

#62805 OADP - 2041 Timeouts
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  modules/oadp-csi-snapshot-timeouts.adoc
  modules/oadp-datamover-timeouts.adoc
  modules/oadp-item-backup-timeouts.adoc
  modules/oadp-item-restore-timeouts.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
  modules/oadp-velero-default-timeouts.adoc
  modules/oadp-velero-timeouts.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#63295 RHDEVDOCS-5356 add gitops to preview page
  scripts/ocpdocs/_previewpage
Labels: size/S

#62863 [enterprise-4.13] OSDOCS-7126: Added vCenter requirements section to vSphere UPI docs
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#62868 [enterprise-4.12] OSDOCS-7126: Added vCenter requirements section to vSphere UPI docs
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#62492 OSDOCS#5810: Adding NNCP from console
  images/fa-minus-circle.svg
  modules/virt-create-node-network-config-console.adoc
  modules/virt-delete-node-network-config.adoc
  modules/virt-monitor-node-network-config-console.adoc
  modules/virt-node-network-config-console.adoc
  modules/virt-update-node-network-config-form.adoc
  modules/virt-update-node-network-config-yaml.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14

#63402 RHDEVDOCS-5483-preview: Adding Builds to preview page
  scripts/ocpdocs/_previewpage
Labels: size/S

#63078 OSDOCS#CP-1892 - ROSA redirects to customer portal
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/M

#63404 [enterprise-4.11] OCPBUGS#16299: Add AWS Load Balancer Operator considerations
  modules/nw-aws-load-balancer-operator-considerations.adoc
  networking/aws_load_balancer_operator/understanding-aws-load-balancer-operator.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed

#62570 ROX-18347: CORE_BPF collection method prerequisits
  modules/default-requirements-secured-cluster-services.adoc
Labels: peer-review-done, size/S, RHACS, jira/valid-reference, rhacs-docs-4.2

#57451 OSDOCS-5543:Adding performance and resource recommendatiaons
  modules/network-observability-resource-recommendations.adoc
  modules/network-observability-resources-table.adoc
  networking/network_observability/configuring-operator.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63320 OCPBUGS#10741: Removed footnote for IAM services
  modules/installation-ibm-cloud-iam-policies-api-key.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62996 OCPBUGS#10815: Enhance K8s API server LB note
  modules/installation-load-balancing-user-infra.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#63425 OSDOCS#CP-1892 - Removed redirect rules for ROSA to CustomerPortal leaving only registry book redirect
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/M

#63412 OADP 2041fixes
  modules/oadp-csi-snapshot-timeouts.adoc
  modules/oadp-datamover-timeouts.adoc
  modules/oadp-item-backup-timeouts.adoc
  modules/oadp-item-restore-timeouts.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
  modules/oadp-velero-default-timeouts.adoc
  modules/oadp-velero-timeouts.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63326 OSDOCS#6188: Version bump in mirror links
  modules/installation-gcp-user-infra-rhcos.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-vsphere-machines.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.14

#62838 [OSDOCS-7023]: Updating references to hypershift CLI
  modules/advanced-node-tuning-hosted-cluster.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14

#63372 [OSDOCS-7397] adding new regions to ROSA
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.13, branch/enterprise-4.14

#62798 OSDOCS-4806: Expanded OIDC config instructions
  modules/rosa-sts-byo-oidc-options.adoc
  modules/rosa-sts-byo-oidc.adoc
  rosa_architecture/rosa-oidc-overview.adoc
  rosa_architecture/rosa-sts-about-iam-resources.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.adoc
Labels: peer-review-done, size/M, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61715 CNV-26876: Document golden images
  modules/virt-golden-images.adoc
  virt/virtual_machines/virtual_disks/virt-using-container-disks-with-vms.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14

#62710 OADP- 2300 OADP Metric Collection
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  images/oadp-backup-failing-alert.png
  images/oadp-metrics-query.png
  images/oadp-metrics-targets.png
  modules/migration-using-must-gather.adoc
  modules/oadp-creating-alerting-rule.adoc
  modules/oadp-creating-service-monitor.adoc
  modules/oadp-list-of-metrics.adoc
  modules/oadp-monitoring-setup.adoc
  modules/oadp-monitoring.adoc
  modules/oadp-viewing-metrics-ui.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14

#63456 test content
  gitops/understanding-openshift-gitops.adoc
Labels: size/XS

#63271 OCPBUGS#16043: Clarify mountOptions for MicroShift
  microshift_storage/understanding-persistent-storage-microshift.adoc
  modules/storage-persistent-storage-pv.adoc
  modules/storage-persistent-storage-pvc.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63428 [enterprise-4.14] OCPBUGS-10815: Enhance K8s API server LB note
  modules/installation-load-balancing-user-infra.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#63455 [enterprise-4.12] OCPBUGS-10815: Enhance K8s API server LB note
  modules/installation-load-balancing-user-infra.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#63459 [enterprise-4.11] OCPBUGS-10815: Enhance K8s API server LB note
  modules/installation-load-balancing-user-infra.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#63460 [enterprise-4.10] OCPBUGS-10815: Enhance K8s API server LB note
  modules/installation-load-balancing-user-infra.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#63190 OSDOCS#7303: Update release notes for the cert-manager Operator 1.11
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-needed, branch/enterprise-4.14

#61747 OCPBUGS#15328: Update notes
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63193 OSDOCS#7309: Update upstream versions of the cert-manager Operator
  security/cert_manager_operator/cert-manager-operator-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63304 Updates manual pruning command in Images docs
  modules/pruning-images-manual.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63085 Nodes Clusters docs fixes during ROSA review
  _topic_maps/_topic_map.yml
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
  modules/nodes-cluster-limit-ranges-creating.adoc
  modules/nodes-cluster-limit-ranges-deleting.adoc
  modules/nodes-cluster-limit-ranges-viewing.adoc
  modules/nodes-cluster-overcommit-node-enforcing.adoc
  modules/nodes-cluster-overcommit-project-disable.adoc
  modules/nodes-cluster-resource-configure-jdk.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/nodes-cluster-resource-configure.adoc
  modules/nodes-cluster-resource-levels-about.adoc
  modules/nodes-cluster-resource-levels-command.adoc
  modules/nodes-cluster-resource-levels-job.adoc
  modules/nodes-cluster-resource-override-deploy-cli.adoc
  modules/nodes-cluster-resource-override-deploy-console.adoc
  modules/nodes-cluster-resource-override.adoc
  nodes/clusters/nodes-cluster-resource-levels.adoc
  nodes/nodes/nodes-nodes-machine-config-daemon-metrics.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63475 Issue 63319: fixed unsubstituted variable
  hardware_enablement/about-hardware-enablement.adoc
Labels: peer-review-in-progress, peer-review-needed, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62577 OSDOCS-6130: Added IMDS information to OSD
  modules/osd-create-cluster-ccs.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#62693 OSSM-4535: Service Mesh 2.4.2 Z Stream Release Notes
  _attributes/common-attributes.adoc
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/M, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63277 OSDOCS-6386: Remove mention of ccoctl in the cloudwatch log forwarding and efs csi driver rosa procedures
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forward-secret-cloudwatch.adoc
  modules/osd-persistent-storage-csi-efs-sts.adoc
  modules/rosa-cluster-logging-collector-log-forward-sts-cloudwatch.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63093 RHDEVDOCS-5456: Documenting the OpenShift Builds overview
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  builds/core-builds/_attributes
  builds/core-builds/images
  builds/core-builds/modules
  builds/core-builds/snippets
  builds/overview-openshift-builds.adoc
  builds/sample-folder/_attributes
  builds/sample-folder/images
  builds/sample-folder/modules
  builds/sample-folder/snippets
  builds/understanding-image-builds.adoc
  modules/builds-about.adoc
  modules/builds-strategy-docker-build.adoc
  modules/ob-about-build-controller.adoc
  modules/ob-about-build-strategies.adoc
  modules/ob-about-buildrun.adoc
  modules/ob-about-builds.adoc
  modules/ob-build-validation.adoc
  modules/ob-controller-settings.adoc
Labels: peer-review-done, size/L, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference

#62110 [OSDOCS-6793] Remove 4.13-specific failure domains content for ShiftStack
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_openstack/installing-openstack-user-kuryr.adoc
  installing/installing_openstack/installing-openstack-user.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-osp-failure-domains-config.adoc
Labels: peer-review-done, size/L, merge-review-needed, branch/enterprise-4.14

#63281 [RHACS] ROX-18293: Updating telemetry documentation to include self-managed
  modules/information-collected-by-telemetry.adoc
Labels: peer-review-done, size/XS, RHACS, merge-review-in-progress, merge-review-needed, jira/valid-reference
