Repository openshift/openshift-docs, pull requests merged in 2023-03, with the labels that each got.

#56626 [rhacs-docs-3.72] Manual cherrypick - Fixed roxctl installation gaps for 3.72
  modules/acs-quick-install-using-helm.adoc
  modules/install-secured-cluster-services-helm-chart.adoc
  modules/install-sensor-roxctl.adoc
  modules/run-roxctl-from-container.adoc
  modules/using-cli.adoc
  modules/using-the-interactive-installer.adoc
Labels: size/M, RHACS, rhacs-docs-3.72

#56629 [enterprise-4.13] Rename CNV logging.. to Support
  _topic_maps/_topic_map.yml
Labels: size/XS

#56475 OCPBUGS#7958: fix the JSON command
  modules/nw-ovn-kubernetes-migration.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56518 OCPBUGS#1653: Rapidly changing clusters can lower the maximum practical size of a cluster
  scalability_and_performance/planning-your-environment-according-to-object-maximums.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56483 OCPBUGS#3646: service account is used to admit the pods
  modules/security-context-constraints-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55321 Updating ROSA docs to match AWS docs in regards to NLB, ELB, CLB, etc.
  modules/ccs-aws-provisioned.adoc
  modules/dedicated-configuring-your-application-routes.adoc
  modules/installation-aws-permissions.adoc
  modules/rosa-aws-provisioned.adoc
  modules/rosa-sts-aws-requirements-account.adoc
  modules/rosa-troubleshooting-elb-service-role.adoc
  rosa_planning/rosa-sts-aws-prereqs.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56625 OCPBUGS#5448: Add brackets to user-defined values
  modules/registry-accessing-directly.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56320 [OCPBUGS-7817] Apply new naming guidelines for IBM Z and IBM LinuxONE
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  applications/connecting_applications_to_services/getting-started-with-service-binding-ibm-power-ibm-z.adoc
  applications/index.adoc
  applications/working_with_helm_charts/installing-helm.adoc
  distr_tracing/distr_tracing_install/distr-tracing-deploying-jaeger.adoc
  installing/installing-preparing.adoc
  installing/installing_ibm_z/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_ibm_z/preparing-to-install-on-ibm-z-kvm.adoc
  installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc
  modules/cluster-logging-feature-reference.adoc
  modules/developer-cli-odo-installing-odo-on-linux-on-ibm-z.adoc
  modules/developer-cli-odo-installing-odo-on-linux.adoc
  modules/distr-tracing-deploy-streaming.adoc
  modules/ibm-z-choose-networking-setup.adoc
  modules/ibm-z-ensure-high-disk-performance-hyperpav.adoc
  modules/ibm-z-managing-cpu-overcommitment.adoc
  modules/ibm-z-rhel-kvm-host-recommendations.adoc
  modules/ibm-z-secure-execution.adoc
  modules/ibmz-configure-devices-manually.adoc
  modules/ibmz-configure-devices-mco.adoc
  modules/ibmz-enable-multipathing-fcp-luns.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-ibm-z-kvm-user-infra-installing-rhcos.adoc
  modules/installation-ibm-z-troubleshooting-and-debugging.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/logging-feature-reference-5.6.adoc
  modules/minimum-ibm-z-system-requirements.adoc
  modules/olm-arch-os-support.adoc
  modules/olm-pruning-index-image.adoc
  modules/op-installing-pipelines-as-code-cli.adoc
  modules/op-installing-tkn-on-linux.adoc
  modules/ossm-federation-across-cluster.adoc
  modules/ossm-supported-configurations.adoc
  modules/ossm-tutorial-bookinfo-install.adoc
  modules/rhcos-enabling-multipath-day-2.adoc
  modules/rhcos-enabling-multipath.adoc
  modules/sbo-deploying-a-postgresql-database-operator-power-z.adoc
  modules/serverless-gpu-resources-kn.adoc
  modules/serverless-installing-cli-linux-rpm-package-manager.adoc
  modules/serverless-installing-cli-linux.adoc
  modules/serverless-kafka-developer.adoc
  modules/supported-platforms-for-openshift-clusters.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/admin/olm-restricted-networks.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/ibmz-post-install.adoc
  scalability_and_performance/ibm-z-recommended-host-practices.adoc
  serverless/admin_guide/serverless-kafka-admin.adoc
  service_mesh/v2x/ossm-extensions.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
  welcome/index.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#56599 Adds a link to the procedure for manifest lists
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13

#56472 OCPBUGS#7984: Installing OCP on a single node is supported on certified third-party hypervisors
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#56484 Updates RNs for 4.10.53 z-stream release
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10

#56456 OSDOCS-5419: Added VMWare Cloud Verified info to vSphere docs
  modules/installation-vsphere-infrastructure.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#55612 OSDOCS#4896: Adding new parameter for IBM Cloud VPC BYON install use cases
  modules/installation-configuration-parameters.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.13

#55577 TELCODOCS-757-AZURE
  machine_management/creating_machinesets/creating-machineset-azure.adoc
  modules/nvidia-gpu-aws-deploying-the-node-feature-discovery-operator.adoc
  modules/nvidia-gpu-azure-adding-a-gpu-node.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13

#56656 Add missing symbolic links for snippet folder
  installing/installing_cloud_ocp/snippets
  installing/installing_cloud_other/snippets
Labels: size/XS

#56365 SRVCOM-2114 restructure CLI
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  serverless/cli_tools/eventing_cli/_attribute
  serverless/cli_tools/eventing_cli/images
  serverless/cli_tools/eventing_cli/kn-source.adoc
  serverless/cli_tools/eventing_cli/modules
  serverless/cli_tools/eventing_cli/snippets
  serverless/cli_tools/functions_cli/_attribute
  serverless/cli_tools/functions_cli/images
  serverless/cli_tools/functions_cli/kn-functions.adoc
  serverless/cli_tools/functions_cli/modules
  serverless/cli_tools/functions_cli/snippets
  serverless/cli_tools/kn-eventing-ref.adoc
  serverless/cli_tools/kn-plugins.adoc
  serverless/cli_tools/kn-serving-ref.adoc
  serverless/cli_tools/serving_cli/_attributes
  serverless/cli_tools/serving_cli/images
  serverless/cli_tools/serving_cli/kn-container.adoc
  serverless/cli_tools/serving_cli/kn-domain.adoc
  serverless/cli_tools/serving_cli/kn-service-offline.adoc
  serverless/cli_tools/serving_cli/kn-service.adoc
  serverless/cli_tools/serving_cli/modules
  serverless/cli_tools/serving_cli/snippets
  serverless/eventing/kn-event-plugin/kn-plugins-events.adoc
  serverless/knative-serving/getting-started/serverless-applications.adoc
Labels: size/L, serverless, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56186 OCPBUGS#3629: Add a note regarding enabling SCP in AWS account
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55467 BZ2111793: Improved OCM text in section 24.6 of Installation guide
  modules/reviewing-cluster-status-from-the-openshift-cluster-manager.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56427 RHDEVDOCS-4842-how-to-configure-secrets-in-alertmanager
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-configuring-secrets-for-alertmanager.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.13

#55731 OSDOCS-5032 GA for Custom Metric Autoscaler
  modules/nodes-pods-autoscaling-custom-about.adoc
  modules/nodes-pods-autoscaling-custom-audit.adoc
  modules/nodes-pods-autoscaling-custom-creating-workload.adoc
  modules/nodes-pods-autoscaling-custom-install.adoc
  modules/nodes-pods-autoscaling-custom-pausing.adoc
  modules/nodes-pods-autoscaling-custom-prometheus-config.adoc
  modules/nodes-pods-autoscaling-custom-rn.adoc
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.13

#55595 [SRVOCF-508] Update Tekton task links for 1.27
  modules/serverless-functions-creating-on-cluster-builds.adoc
Labels: peer-review-done, size/XS, serverless, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56622 add quorum guard instructions for etcd restoring from disaster
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56318 [OSDOCS-5388]:Remove a section from the OSD/ROSA documentation for the Logging stack
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56603 [OSDOCS-5436]: Adding versioning info about HyperShift Operator
  modules/hosted-control-planes-version-support.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.13

#56609 OSDOCS-5061: Update ARM64 azure cloud provider docs
  installing/installing-preparing.adoc
  installing/installing_azure/installing-azure-government-region.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#56602 OSDOCS-4798 Added another GCP Constraint
  modules/ccs-gcp-customer-procedure.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#56345 OSDOCS-4967:adds OVN health monitoring to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#41148 BZ-2022831 Clarified unique domain requirements for Ingress Controller
  modules/nw-aws-nlb-existing-cluster.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56253 OSDOCS#4894: Installing a three-node AWS cluster
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-three-node.adoc
  modules/installation-creating-aws-worker.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-initializing.adoc
  modules/installation-three-node-cluster-cloud-provider.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.13

#56698 [Enterprise-4.9]: RHDEVDOCS-4958: Updating the matrix table to fill in identified gaps
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-2-1.adoc
  modules/gitops-release-notes-1-2.adoc
  modules/gitops-release-notes-1-3-0.adoc
  modules/gitops-release-notes-1-3-1.adoc
  modules/gitops-release-notes-1-3-2.adoc
  modules/gitops-release-notes-1-3-3.adoc
  modules/gitops-release-notes-1-3-6.adoc
  modules/gitops-release-notes-1-3-7.adoc
  modules/gitops-release-notes-1-4-0.adoc
  modules/gitops-release-notes-1-4-1.adoc
  modules/gitops-release-notes-1-4-11.adoc
  modules/gitops-release-notes-1-4-12.adoc
  modules/gitops-release-notes-1-4-13.adoc
  modules/gitops-release-notes-1-4-2.adoc
  modules/gitops-release-notes-1-4-3.adoc
  modules/gitops-release-notes-1-4-5.adoc
  modules/gitops-release-notes-1-5-0.adoc
  modules/gitops-release-notes-1-5-1.adoc
  modules/gitops-release-notes-1-5-2.adoc
  modules/gitops-release-notes-1-5-3.adoc
  modules/gitops-release-notes-1-5-4.adoc
  modules/gitops-release-notes-1-5-5.adoc
  modules/gitops-release-notes-1-5-6.adoc
  modules/gitops-release-notes-1-5-7.adoc
  modules/gitops-release-notes-1-5-9.adoc
  modules/gitops-release-notes-1-6-0.adoc
  modules/gitops-release-notes-1-6-1.adoc
  modules/gitops-release-notes-1-6-4.adoc
  modules/gitops-release-notes-1-7-0.adoc
  modules/gitops-release-notes-1-7-1.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/L, jira/valid-reference

#56715 improve documentation about autogenerated SA tokens
  snippets/service-account-auto-secret-removed.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56753 Fix version in out-of-date OSDK note
  cli_reference/osdk/cli-osdk-install.adoc
  operators/operator_sdk/osdk-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#56756 [enterprise-4.11] Fix version in out-of-date OSDK note
  cli_reference/osdk/cli-osdk-install.adoc
  operators/operator_sdk/osdk-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11

#56755 [enterprise-4.10] Fix version in out-of-date OSDK note
  cli_reference/osdk/cli-osdk-install.adoc
  operators/operator_sdk/osdk-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10

#56765 oadp backup word misspelling
  modules/oadp-backing-up-applications-restic.adoc
  modules/oadp-self-signed-certificate.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56042 OSDOCS-5379: Defining cv condition types/updating condition type doc (4.9)
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/determining-upgrade-viability-cv-conditiontype.adoc
  updating/index.adoc
Labels: peer-review-in-progress, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56395 OSDOCS-5379: Defining cv condition types/updating condition type doc (4.11+)
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/determining-upgrade-viability-cv-conditiontype.adoc
  updating/index.adoc
Labels: peer-review-in-progress, peer-review-needed, size/M, merge-review-needed, jira/valid-reference

#56394 OSDOCS-5379: Defining cv condition types/updating condition type doc (4.10)
  modules/determining-upgrade-viability-conditiontype.adoc
  modules/determining-upgrade-viability-cv-conditiontype.adoc
  updating/index.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#56607 BZ#2056337 Add `opm migrate` to the `opm` CLI tool reference
  cli_reference/opm/cli-opm-ref.adoc
  modules/opm-cli-ref-migrate.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56587 OSDOCS-5395: create an uninstalling OSUS page
  _topic_maps/_topic_map.yml
  modules/update-service-delete-service-cli.adoc
  modules/update-service-delete-service-web-console.adoc
  modules/update-service-uninstall-cli.adoc
  modules/update-service-uninstall-web-console.adoc
  updating/index.adoc
  updating/updating-restricted-network-cluster/restricted-network-update-osus.adoc
  updating/updating-restricted-network-cluster/uninstalling-osus.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#55835 OCPBUGS-6709-main: adding note
  modules/psap-driver-toolkit-pulling.adoc
Labels: peer-review-done, lgtm, size/XS, telco

#56073 RHDEVDOCS-4340-document-scrape-profiles-in-CMO
  modules/monitoring-choosing-a-metrics-collection-profile.adoc
  modules/monitoring-configuring-metrics-collection-profiles.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: lgtm, size/L, docs-approved, qe-approved, branch/enterprise-4.13

#56355 RHDEVDOCS-4985: Updated the matrix table to fill in identified gaps
  modules/op-release-notes-1-5.adoc
  modules/op-release-notes-1-8.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/S, dev-tools, px-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#56676 Updates for patch release for 3.72.4
  release_notes/372-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, merge-review-in-progress, rhacs-docs-3.72

#54975 OCPBUGS#6060 Firewall documentation should mention load balancer config
  installing/installing-troubleshooting.adoc
  modules/configuring-firewall.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56772 Updates to RHACS RNs for patch release 3.73.3
  release_notes/373-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, merge-review-in-progress, rhacs-docs-3.73

#56821 [enterprise-13] Update anchor IDs for 4.13
  modules/virt-runbook-cdidataimportcronoutdated.adoc
  modules/virt-runbook-cdidatavolumeunusualrestartcount.adoc
  modules/virt-runbook-cdinotready.adoc
  modules/virt-runbook-cdioperatordown.adoc
  modules/virt-runbook-cdistorageprofilesincomplete.adoc
  modules/virt-runbook-cnaodown.adoc
  modules/virt-runbook-hppnotready.adoc
  modules/virt-runbook-hppoperatordown.adoc
  modules/virt-runbook-hppsharingpoolpathwithos.adoc
  modules/virt-runbook-kubemacpooldown.adoc
  modules/virt-runbook-kubemacpoolduplicatemacsfound.adoc
  modules/virt-runbook-kubevirtcomponentexceedsrequestedcpu.adoc
  modules/virt-runbook-kubevirtcomponentexceedsrequestedmemory.adoc
  modules/virt-runbook-kubevirthyperconvergedclusteroperatorcrmodification.adoc
  modules/virt-runbook-kubevirthyperconvergedclusteroperatorinstallationnotcompletedalert.adoc
  modules/virt-runbook-kubevirthyperconvergedclusteroperatorusmodification.adoc
  modules/virt-runbook-kubevirtvmhighmemoryusage.adoc
  modules/virt-runbook-kubevirtvmiexcessivemigrations.adoc
  modules/virt-runbook-kubevirtvmstuckinerrorstate.adoc
  modules/virt-runbook-kubevirtvmstuckinmigratingstate.adoc
  modules/virt-runbook-kubevirtvmstuckinstartingstate.adoc
  modules/virt-runbook-lowkvmnodescount.adoc
  modules/virt-runbook-lowreadyvirtcontrollerscount.adoc
  modules/virt-runbook-lowreadyvirtoperatorscount.adoc
  modules/virt-runbook-lowvirtapicount.adoc
  modules/virt-runbook-lowvirtcontrollerscount.adoc
  modules/virt-runbook-lowvirtoperatorcount.adoc
  modules/virt-runbook-networkaddonsconfignotready.adoc
  modules/virt-runbook-nodestatusmaximagesexceeded.adoc
  modules/virt-runbook-noleadingvirtoperator.adoc
  modules/virt-runbook-noreadyvirtcontroller.adoc
  modules/virt-runbook-noreadyvirtoperator.adoc
  modules/virt-runbook-orphanedvirtualmachineinstances.adoc
  modules/virt-runbook-outdatedvirtualmachineinstanceworkloads.adoc
  modules/virt-runbook-sspcommontemplatesmodificationreverted.adoc
  modules/virt-runbook-sspfailingtoreconcile.adoc
  modules/virt-runbook-ssphighraterejectedvms.adoc
  modules/virt-runbook-sspoperatordown.adoc
  modules/virt-runbook-ssptemplatevalidatordown.adoc
  modules/virt-runbook-virtapidown.adoc
  modules/virt-runbook-virtapiresterrorsburst.adoc
  modules/virt-runbook-virtapiresterrorshigh.adoc
  modules/virt-runbook-virtcontrollerdown.adoc
  modules/virt-runbook-virtcontrollerresterrorsburst.adoc
  modules/virt-runbook-virtcontrollerresterrorshigh.adoc
  modules/virt-runbook-virthandlerdaemonsetrolloutfailing.adoc
  modules/virt-runbook-virthandlerresterrorsburst.adoc
  modules/virt-runbook-virthandlerresterrorshigh.adoc
  modules/virt-runbook-virtoperatordown.adoc
  modules/virt-runbook-virtoperatorresterrorsburst.adoc
  modules/virt-runbook-virtoperatorresterrorshigh.adoc
  modules/virt-runbook-vmcannotbeevicted.adoc
Labels: size/XL

#56467 TELCODOCS-1143: Correcting odf4 image tag
  modules/lvms-download-log-files-and-diagnostics.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56606 OSDOCS#5003: Updating list of supported AWS regions
  modules/installation-aws-regions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56752 TELCODOCS-1083: Added x86_64 and arm64 as supported CPU architectures.
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: peer-review-done, lgtm, size/XS, telco, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56528 OADP-1324: Correct typos
  modules/modules
  modules/oadp-checking-api-group-versions.adoc
  modules/osdk-run-deployment.adoc
  modules/velero-obtaining-by-downloading.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56841 Fixing typo
  modules/images-other-jenkins-config-kubernetes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56777 OSDOCS-4755: mark out confusing paragraphs
  microshift_rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.adoc
  modules/api-compatibility-exceptions.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56466 OCPBUGS-5983: Adding LVMS limits
  modules/deploying-lvms-on-sno-cluster.adoc
Labels: peer-review-done, lgtm, size/M, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#56443 Corrected indentation of collection section YAML
  modules/cluster-logging-vector-tech-preview.adoc
Labels: lgtm, size/XS

#56855 Manual CP 56443 to 4.11
  modules/cluster-logging-vector-tech-preview.adoc
Labels: size/XS

#56436 OSDOCS#5056: GA CgroupV2 in Openshift 4.13
  _topic_maps/_topic_map.yml
  installing/install_config/enabling-cgroup-v2.adoc
  modules/nodes-clusters-cgroups-2-install.adoc
  modules/nodes-clusters-cgroups-2.adoc
  modules/nodes-clusters-cgroups-okd-configure.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  nodes/clusters/nodes-cluster-cgroups-2.adoc
  nodes/clusters/nodes-cluster-cgroups-okd.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#56856 Manual CP of 56443 to 4.12
  modules/cluster-logging-vector-tech-preview.adoc
Labels: size/XS

#56858 Manual CP of 56443 to 4.13
  modules/cluster-logging-vector-tech-preview.adoc
Labels: size/XS

#56854 Manual CP of 56443 to 4.10
  modules/cluster-logging-vector-tech-preview.adoc
Labels: size/XS

#56779 TELCODOCS-1083 Release Note
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, telco, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56868 RHDEVDOCS-4958: Updated the matrix table to fill in identified gaps
  modules/go-compatibility-and-support-matrix.adoc
  modules/op-release-notes-1-5.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/S, branch/enterprise-4.9, jira/valid-reference

#56867 RHDEVDOCS-4958: Updated the matrix table to fill in identified gaps
  modules/op-release-notes-1-5.adoc
  modules/op-release-notes-1-8.adoc
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: size/S, branch/enterprise-4.10, jira/valid-reference

#56632 RHDEVDOCS-4365-new: Added a procedure to customize the Argo CD link
  cicd/gitops/setting-up-argocd-instance.adoc
  modules/gitops-argo-cd-installation.adoc
  modules/gitops-customize-argo-cd-consolelink.adoc
  modules/gitops-deploy-resources-different-namespaces.adoc
  modules/gitops-enable-replicas-for-argo-cd-server.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: lgtm, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56361 RHDEVDOCS-3436 | Updated OCP>Support and OKD>Support pages for missing link to pipelines must-gather
  modules/gathering-data-specific-features.adoc
Labels: lgtm, size/XS

#55095 Add release notes for SBO v1.3.3
  applications/connecting_applications_to_services/sbo-release-notes.adoc
  modules/sbo-release-notes-1-3-3.adoc
Labels: size/S, branch/enterprise-4.11, branch/enterprise-4.12

#56521 SO-100: Adding the announcement for Downsizing of Samples operator
  openshift_images/configuring-samples-operator.adoc
Labels: peer-review-needed, lgtm, size/S, dev-tools, qe-approved, jira/valid-reference

#56880 [enterprise-4.13] Updates OMR docs in .13
  installing/disconnected_install/installing-mirroring-creating-registry.adoc
  modules/mirror-registry-localhost.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
  modules/mirror-registry-remote.adoc
  modules/mirror-registry-uninstall.adoc
Labels: size/S

#56882 [enterprise-4.12] Makes OMR updates for 4.12 branch
  installing/disconnected_install/installing-mirroring-creating-registry.adoc
  modules/mirror-registry-localhost.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
  modules/mirror-registry-remote.adoc
  modules/mirror-registry-uninstall.adoc
Labels: size/S

#56884 [enterprise-4.11] Updates OMR docs for 4.11 branch
  installing/disconnected_install/installing-mirroring-creating-registry.adoc
  modules/mirror-registry-localhost.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
  modules/mirror-registry-remote.adoc
  modules/mirror-registry-uninstall.adoc
Labels: size/M

#56885 Revert "RHDEVDOCS-3436 | Updated OCP>Support and OKD>Support pages for missing link to pipelines must-gather"
  modules/gathering-data-specific-features.adoc
Labels: size/XS

#56189 BZ#1998450: Updated procedure related to accessing registry metrics.
  modules/registry-accessing-metrics.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56354 BZ#2071184: Added eus channel info in updating a cluster using the web console se…
  modules/update-upgrading-web.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56729 OSDOCS#4895: Installing a three-node vSphere cluster
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_vmc/installing-vmc-customizations.adoc
  installing/installing_vmc/installing-vmc-three-node.adoc
  installing/installing_vmc/installing-vmc-user-infra.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/installing-vsphere-three-node.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-initializing.adoc
  modules/installation-three-node-cluster-cloud-provider.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/machine-vsphere-machines.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#56886 Updates OMR to 1.3.1
  modules/mirror-registry-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56658 OCPBUG#7145: Deleted a step in 'Restoring to a previous cluster state'
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56696 OCP1883: Removed deprecated metric in defragmenting etcd data
  modules/etcd-defrag.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56610 OSDOCS-5318: remove fixed iptable and node port workarounds
  microshift_troubleshooting/microshift-troubleshooting.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56604 Adds known limitation when working with manifest lists
  modules/images-imagestream-import-import-mode.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56862 OSDOCS-5447:adds to RNs for 4.11.30
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#56863 OSDOCS-4846: first round update Tech Preview language
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  snippets/microshift-tech-preview-snip.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56788 RNs for zstream 4.12.6
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#56697 OCP6264: Added RHEL 8.6 version in OCP 4.12 release note
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#56893 Fix deprecated module for opm CLI reference
  cli_reference/opm/cli-opm-ref.adoc
  modules/opm-cli-ref-migrate.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56498 RHDEVDOCS-2755 Logging 5.6 API Ref
  logging/cluster-logging-loki.adoc
  logging/cluster-logging.adoc
  modules/logging-5.6-api-ref.adoc
Labels: size/XXL

#56807 OCPBUGS-5054-chronyd-4_10: Disable chronyd in PolicyGenTemplate CR se…
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.10, merge-review-in-progress

#56934 Fixed misspelled PostgreSQL
  release_notes/374-release-notes.adoc
Labels: size/XS, RHACS, rhacs-docs-3.74

#55918 OSDOCS-5350 Security Profiles Operator 0.5.2 release notes
  security/security_profiles_operator/spo-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12, branch/enterprise-4.13

#55123 OCPBUGS-4561 update recommended host practices
  modules/aws-console-changing-aws-instance-type.adoc
  modules/master-node-sizing.adoc
  scalability_and_performance/recommended-host-practices.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11

#56921 CNV-25641: Adding the deprecation of marking virtual machine templates as favorites to the release notes
  virt/virt-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, merge-review-in-progress, jira/valid-reference

#56525 [OSDOCS-5101]: Replacement control plane nodes in correct group
  release_notes/ocp-4-13-release-notes.adoc
Labels: size/XS, branch/enterprise-4.13

#56757 OSDOCS-3338: Added FIPS installation option to ROSA
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#56933 [enterprise-4.13] OSDOCS-5051: add haproxy update
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#56348 [OSDOCS-5090]: GCP Confidential VM options
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-gcp-confidential-vm.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#56477 RHDEVDOCS-4931 - Logging 5.6.3 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.6.3.adoc
Labels: lgtm, size/S

#56857 Clean up citation/reference info and add style guide note
  contributing_to_docs/doc_guidelines.adoc
Labels: peer-review-done, size/M

#56476 RHDEVDOCS-4930 - Logging 5.4.12 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.4.12.adoc
Labels: lgtm, size/S

#56474 RHDEVDOCS-4929 - Logging 5.5.8 Release Notes
  logging/cluster-logging-release-notes.adoc
  modules/cluster-logging-rn-5.5.8.adoc
Labels: lgtm, size/S

#56949 OSDOCS#4862: Version bump in links to UPI install JSON templates
  modules/installation-arm-bootstrap.adoc
  modules/installation-arm-control-plane.adoc
  modules/installation-arm-dns.adoc
  modules/installation-arm-image-storage.adoc
  modules/installation-arm-vnet.adoc
  modules/installation-arm-worker.adoc
  modules/installation-cloudformation-bootstrap.adoc
  modules/installation-cloudformation-control-plane.adoc
  modules/installation-cloudformation-dns.adoc
  modules/installation-cloudformation-security.adoc
  modules/installation-cloudformation-vpc.adoc
  modules/installation-cloudformation-worker.adoc
  modules/installation-deployment-manager-bootstrap.adoc
  modules/installation-deployment-manager-control-plane.adoc
  modules/installation-deployment-manager-ext-lb.adoc
  modules/installation-deployment-manager-firewall-rules.adoc
  modules/installation-deployment-manager-iam-shared-vpc.adoc
  modules/installation-deployment-manager-int-lb.adoc
  modules/installation-deployment-manager-private-dns.adoc
  modules/installation-deployment-manager-vpc.adoc
  modules/installation-deployment-manager-worker.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.13

#56814 OSDOCS-5448: Documented 4.9.57 z-stream release notes
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#56747 OSDOCS#5140:Adds a step that console supports Operator to specify where to run with CSV suggested namespace
  modules/osdk-csv-manual-annotations.adoc
  modules/osdk-suggested-namespace-node-selector.adoc
  operators/operator_sdk/osdk-generating-csvs.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#56983 SRVCOM-2313 initial redirects for restructuring
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS, serverless

#56984 Update runbooks for 4.13
  modules/virt-runbook-nodestatusmaximagesexceeded.adoc
  virt/support/virt-runbooks.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.13

#56624 OCPBUGS#8025: Fix tar command
  modules/cli-installing-cli-web-console-linux.adoc
  modules/cli-installing-cli.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#55836 TELCODOCS-1142: MGMT-10209 assisted-service ICSP support
  modules/ztp-configuring-the-cluster-for-a-disconnected-environment.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56997 [enterprise-4.9 ]OADP-773:Velero version by OADP and OCP version
  backup_and_restore/index.adoc
  modules/velero-obtaining-by-downloading.adoc
Labels: size/S, merge-review-needed, OADP, jira/valid-reference

#56998 [enterprise-4.10] OADP-773:Velero version by OADP and OCP version
  backup_and_restore/index.adoc
  modules/velero-obtaining-by-downloading.adoc
Labels: size/S, merge-review-needed, OADP, jira/valid-reference

#56648 OCPBUGS#8088: Replace the owner role with the contributor role
  modules/installation-azure-permissions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56465 OCPBUGS-5981: Add to LVM Storage docs how to expand a PVC
  modules/lvms-scaling-storage-expand-pvc.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, lgtm, size/M, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#56789 FDN#57: changing 4.13's banner text
  _templates/_page_openshift.html.erb
Labels: size/S

#56976 [GH56976]: Minor grammatical change to "Responsibility assignment matrix" doc
  modules/rosa-policy-responsibilities.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#56842 OSDOCS#5230: Installing a three-node GCP cluster
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-three-node.adoc
  installing/installing_gcp/installing-gcp-customizations.adoc
  installing/installing_gcp/installing-gcp-three-node.adoc
  installing/installing_gcp/installing-gcp-user-infra.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-generate-aws-user-infra-install-config.adoc
  modules/installation-initializing.adoc
  modules/installation-three-node-cluster-cloud-provider.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.13

#54222 BZ1989855 Adding cluster-ingress-default-ingresscontroller.yaml step
  modules/nw-gcp-installing-global-access-configuration.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-needed

#56979 change hard link to xref
  security/network_bound_disk_encryption/nbde-tang-server-installation-considerations.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#55613 reformatting OSDOCS issue format in template
  .github/pull_request_template.md
Labels: size/XS

#57029 adding a missing quotation mark
  _templates/_page_openshift.html.erb
Labels: size/XS

#57032 fixing </strong>
  _templates/_page_openshift.html.erb
Labels: size/XS

#56940 OADP 1.1.2 Release notes
  backup_and_restore/application_backup_and_restore/oadp-release-notes.adoc
  modules/oadp-release-notes-1-1-2.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56005 TELCODOCS-1179 fixing BGP communities doc bugs
  modules/nw-metallb-community-cr.adoc
  modules/nw-metallb-configure-community-bgp-advertisement.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56364 BZ#2071184: Added eus channel info in the note in 'Updating a cluster using the CLI' section.
  modules/update-upgrading-cli.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, merge-review-in-progress

#54522 RHDEVDOCS-4719+4724 Improve Tekton Hub config UX + Support for Crunchy Postgres with Tekton Hub
  cicd/pipelines/using-tekton-hub-with-openshift-pipelines.adoc
  modules/op-adding-new-users-in-tekton-hub-configuration.adoc
  modules/op-installing-crunchy-postgres-database-and-tekton-hub.adoc
  modules/op-installing-tekton-hub-with-login-and-rating.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-migrating-tekton-hub-data-to-an-existing-crunchy-postgres-database.adoc
  modules/op-modifying-catalog-refresh-interval-tekton-hub.adoc
  modules/op-updating-tekton-hub-with-custom-categories-and-catalogs.adoc
  modules/op-using-a-custom-database-in-tekton-hub.adoc
Labels: lgtm, size/XL

#56956 OADP-1378: Check OADP 1.1.2 documentation for references to earlier versions
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-using-data-mover-for-csi-snapshots.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#55407 [OSDOCS-5012]: Full Azure CPMS support
  machine_management/control_plane_machine_management/cpmso-getting-started.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#56859 OSDOCS#5228: Installing a three-node Azure cluster
  _topic_maps/_topic_map.yml
  installing/installing_azure/installing-azure-customizations.adoc
  installing/installing_azure/installing-azure-three-node.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  modules/installation-creating-azure-worker.adoc
  modules/installation-initializing.adoc
  modules/installation-three-node-cluster-cloud-provider.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.13

#55409 [OSDOCS-5012]: Full Azure CPMS support (rel notes)
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#56192 OCPBUGS-7538 - updates fast events notifications REST API URI > ocloudNotifications
  modules/cnf-fast-event-notifications-api-refererence.adoc
  modules/cnf-rfhe-notifications-api-refererence.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56945 [OSDOCS-4456]: Update documentation to reflect ROSA Route Sharding for Custom Domain
  modules/osd-applications-config-custom-domains.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#57070 Manual CP for #56192 - ptp events
  modules/cnf-fast-event-notifications-api-refererence.adoc
  modules/cnf-rfhe-notifications-api-refererence.adoc
Labels: size/M

#56305 [OSDOCS-5013]: CPMS for GCP: Supported features
  machine_management/control_plane_machine_management/cpmso-using.adoc
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  modules/machineset-enabling-customer-managed-encryption.adoc
  modules/machineset-gcp-enabling-customer-managed-encryption.adoc
  modules/machineset-gcp-pd-disk-types.adoc
  modules/machineset-gcp-shielded-vms.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#57030 OSDOCS-4718 vSphere DRS Anti-Affinity Rule configuration During UPI Install 2nd PR
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  modules/vsphere-anti-affinity.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, merge-review-in-progress

#57048 OSDOCS-5451: move KI to release notes
  _attributes/attributes-microshift.adoc
  _topic_maps/_topic_map_ms.yml
  microshift_networking/microshift-firewall.adoc
  microshift_networking/microshift-networking.adoc
  microshift_release_notes/microshift-4-13-release-notes.adoc
  microshift_troubleshooting/microshift-troubleshooting.adoc
  modules/microshift-cni.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#57062 OSDOCS-5488: fix typo
  microshift_getting_started/microshift-architecture.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#54890 OSDOCS-4838: Document network policy requirements for Web Terminal Operator
  modules/odc-using-web-terminal.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#57090 OCPBUGS#9916: Fix the typo
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#56750 [OSDOCS-5013]: GCP CPMS support (rel notes)
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#56165 CNV-13359: VMI to VM
  _topic_maps/_topic_map.yml
  modules/virt-about-readiness-liveness-probes.adoc
  modules/virt-define-guest-agent-ping-probe.adoc
  modules/virt-define-http-liveness-probe.adoc
  modules/virt-define-http-readiness-probe.adoc
  modules/virt-define-tcp-readiness-probe.adoc
  virt/support/virt-monitoring-vm-health.adoc
Labels: peer-review-done, lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.13

#56874 backupStorageLocation ns should be consistent with Backup
  modules/oadp-creating-backup-cr.adoc
  modules/oadp-scheduling-backups.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#56096 RHDEVDOCS-4448 - Restructure Phase 1
  _topic_maps/_topic_map.yml
  logging/v5_5/logging-5-5-administration.adoc
  logging/v5_5/logging-5-5-architecture.adoc
  logging/v5_5/logging-5-5-configuration.adoc
  logging/v5_5/logging-5-5-getting-started.adoc
  logging/v5_6/logging-5-6-administration.adoc
  logging/v5_6/logging-5-6-architecture.adoc
  logging/v5_6/logging-5-6-configuration.adoc
  logging/v5_6/logging-5-6-getting-started.adoc
  logging/v5_6/logging-5-6-release-notes.adoc
  modules/logging-architecture-overview.adoc
  modules/logging-deploy-RHOL-console.adoc
  modules/logging-deploy-loki-console.adoc
  modules/logging-loki-retention.adoc
  modules/logging-rn-5.5.8.adoc
  modules/logging-rn-5.6.0.adoc
  modules/logging-rn-5.6.1.adoc
  modules/logging-rn-5.6.2.adoc
  modules/logging-rn-5.6.3.adoc
  snippets/logging-crs-by-operator-snip.adoc
  snippets/logging-elastic-dep-snip.adoc
  snippets/logging-fluentd-dep-snip.adoc
  snippets/logging-log-types-snip.adoc
  snippets/logging-under-construction-snip.adoc
Labels: lgtm, size/XL

#57086 [enterprise-4.10] Document network policy requirements for web terminal operator
  modules/odc-using-web-terminal.adoc
Labels: size/XS

#57031 OSDOCS#5498: Adds notes for MicroShift 4.12.7 release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#56356 BZ#1986055: Remove contradictory information about NFS for Logging
  modules/recommended-configurable-storage-technology.adoc
  post_installation_configuration/storage-configuration.adoc
  scalability_and_performance/optimizing-storage.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#56366 TELCODOCS-1165 - Support multiple storage/device classes
  modules/lvms-creating-an-logical-volume-manager-cluster.adoc
  modules/lvms-creating-logical-volume-manager-cluster.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-cli.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-openshift-web-console.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-rhacm.adoc
  modules/lvms-reference-file.adoc
  modules/lvms-scaling-storage-of-single-node-openshift-cluster-using-rhacm.adoc
  modules/lvms-scaling-storage-of-single-node-openshift-cluster.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, branch/enterprise-4.13

#56691 Fixup mod included in
  modules/proc-switching-bf2-nic.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#57076 [OSDOCS-5514]: Add hosted control planes book
  _topic_maps/_topic_map.yml
  hosted_control_planes/_attributes
  hosted_control_planes/hcp-managing.adoc
  hosted_control_planes/images
  hosted_control_planes/index.adoc
  hosted_control_planes/modules
  hosted_control_planes/snippets
  modules/hosted-control-planes-overview.adoc
  modules/hosted-control-planes-version-support.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.13

#57093 OSDOCS-5495: Documented 4.12.7 z-stream relase notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, jira/valid-reference

#57143 [enterprise-4.13]CP-OSDOCS-5480: Update welcome page 4.13
  welcome/index.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.13

#57085 OCPBUGS8098: troubleshooting broken API links
  _topic_maps/_topic_map_ms.yml
  microshift_getting_started/microshift-architecture.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#56323 OCPBUGS#7608: iPXE for ZTP not default behaviour
  modules/ztp-installation-crs.adoc
  snippets/ztp-example-siteconfig.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#57072 RNs for 4.11.31 z-stream release
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11

#55861 OSDOCS-5058: Azure UPI support on 64-bit ARM systems
  installing/installing-preparing.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  modules/installation-azure-user-infra-deploying-rhcos.adoc
  modules/installation-azure-user-infra-uploading-rhcos.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/valid-reference, branch/enterprise-4.13
