Repository openshift/openshift-docs, pull requests merged in 2023-09, with the labels that each got.

#64190 RHDEVDOCS#5443 Minor fixes for Pipelines 1.11 and 1.12
  _attributes/common-attributes.adoc
  create/creating-applications-with-cicd-pipelines.adoc
  install_config/installing-pipelines.adoc
  modules/op-about-pipelinerun.adoc
  pac/install-config-pipelines-as-code.adoc
  pac/pac-command-reference.adoc
Labels: size/S

#60666 TELCODOCS-776: First draft
  _topic_maps/_topic_map.yml
  architecture/nvidia-gpu-architecture-overview.adoc
  images/349_OpenShift_NVIDIA_GPU_arch_0723.png
  modules/about-using-gpu-operator.adoc
  modules/nvidia-gpu-bare-metal.adoc
  modules/nvidia-gpu-csps.adoc
  modules/nvidia-gpu-enablement.adoc
  modules/nvidia-gpu-features.adoc
  modules/nvidia-gpu-kvm.adoc
  modules/nvidia-gpu-prerequisites.adoc
  modules/nvidia-gpu-red-hat-device-edge.adoc
  modules/nvidia-gpu-virtualization.adoc
  modules/nvidia-gpu-vsphere.adoc
Labels: peer-review-done, size/L, telco, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63736 OSDOCS#5335: Hosted control planes: Debug nodes
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-debugging-nodes.adoc
  modules/debug-nodes-hcp.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.14

#63861 OSDOCS#6990: Add CPMS variable root volume types
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.14

#64208 RHDEVDOCS#5443 Remove invalid anchors in some links, remove a small part that never got included
  about/understanding-openshift-pipelines.adoc
  create/creating-applications-with-cicd-pipelines.adoc
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  install_config/installing-pipelines.adoc
  install_config/uninstalling-pipelines.adoc
  modules/op-alternative-approaches-compute-resource-quota-pipelines.adoc
  pac/managing-pipeline-runs-pac.adoc
  pac/using-pipelines-as-code-repos.adoc
  resource/reducing-pipelines-resource-consumption.adoc
  resource/setting-compute-resource-quota-for-openshift-pipelines.adoc
  secure/unprivileged-building-of-container-images-using-buildah.adoc
Labels: size/M

#64225 RHDEVDOCS#5443 Remove invalid anchors in some links, remove a small part that never got included
  about/understanding-openshift-pipelines.adoc
  create/creating-applications-with-cicd-pipelines.adoc
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  install_config/installing-pipelines.adoc
  install_config/uninstalling-pipelines.adoc
  modules/op-alternative-approaches-compute-resource-quota-pipelines.adoc
  resource/reducing-pipelines-resource-consumption.adoc
  secure/unprivileged-building-of-container-images-using-buildah.adoc
Labels: size/M

#64103 OSDOCS#6504: IBM Power VS - move install config parameters out of ass…
  _topic_maps/_topic_map.yml
  installing/installing_ibm_powervs/installation-config-parameters-ibm-power-vs.adoc
  installing/installing_ibm_powervs/installing-ibm-power-vs-customizations.adoc
  installing/installing_ibm_powervs/installing-ibm-power-vs-private-cluster.adoc
  installing/installing_ibm_powervs/installing-ibm-powervs-vpc.adoc
  installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs.adoc
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14

#63872 OBSDOCS-204: Bug fix for configurable parameter and doc editing
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  logging/cluster-logging-external.adoc
  logging/cluster-logging-loki.adoc
  modules/cluster-logging-forwarding-lokistack.adoc
  modules/cluster-logging-loki-deploy.adoc
  modules/cluster-logging-troubleshooting-loki-entry-out-of-order-errors.adoc
  modules/loki-deployment-sizing.adoc
  modules/loki-rate-limit-errors.adoc
Labels: peer-review-done, size/L, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63849 MetalLB updating the pod affinity example OCPBUGS-17959
  modules/nw-metallb-operator-setting-pod-priority-affinity.adoc
  modules/nw-metallb-operator-setting-runtimeclass.adoc
  networking/metallb/metallb-operator-install.adoc
Labels: peer-review-done, lgtm, size/M, telco, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#64207 OSDOCS-3562: Add SRE access assembly
  _topic_maps/_topic_map_rosa.yml
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64241 [enterprise-4.11] OBSDOCS-204: Bug fix for configurable parameter and doc editing
  _topic_maps/_topic_map.yml
  logging/cluster-logging-external.adoc
  logging/cluster-logging-loki.adoc
  modules/cluster-logging-forwarding-lokistack.adoc
  modules/cluster-logging-loki-deploy.adoc
  modules/cluster-logging-troubleshooting-loki-entry-out-of-order-errors.adoc
  modules/loki-deployment-sizing.adoc
  modules/loki-rate-limit-errors.adoc
Labels: size/L, jira/valid-reference

#64240 [enterprise-4.10] OBSDOCS-204: Bug fix for configurable parameter and doc editing
  _topic_maps/_topic_map.yml
  logging/cluster-logging-external.adoc
  logging/cluster-logging-loki.adoc
  modules/cluster-logging-forwarding-lokistack.adoc
  modules/cluster-logging-loki-deploy.adoc
  modules/cluster-logging-troubleshooting-loki-entry-out-of-order-errors.adoc
  modules/loki-deployment-sizing.adoc
  modules/loki-rate-limit-errors.adoc
Labels: size/L, jira/valid-reference

#64168 OCPBUGS 18108 updating image to http://registry.access.redhat.com/rhel:latest
  modules/cnf-scheduling-numa-aware-workloads.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#63740 OCPBUGS#12930: Created a register cluster section
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63486 OSDOCS-6479: update RHDE page with compat matrix
  _attributes/common-attributes.adoc
  _topic_map.yml
  modules/about-rhde.adoc
  overview/rhde-overview.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, jira/valid-reference

#64247 [enterprise-4.10] OCPBUGS#12930: Created a register cluster section
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
Labels: branch/enterprise-4.10, branch/enterprise-4.13

#64250 [enterprise-4.11] OCPBUGS#12930: Created a register cluster section
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
Labels: size/M, branch/enterprise-4.11

#64249 [enterprise-4.12] OCPBUGS#12930: Created a register cluster section
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
Labels: size/M, branch/enterprise-4.12

#64251 [enterprise-4.13] OCPBUGS#12930: Created a register cluster section
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
Labels: size/M

#60772 SRVCOM-1359: Use Serverless's showcase app to showcase Serving & Eventing
  images/serverless-apiserversource-eventdisplay-gui.png
  images/servlerless-pingsource-showcase-gui.png
  modules/apiserversource-kn.adoc
  modules/apiserversource-yaml.adoc
  modules/creating-serverless-apps-kn.adoc
  modules/creating-serverless-apps-yaml.adoc
  modules/kn-service-describe.adoc
  modules/kn-service-offline-create.adoc
  modules/serverless-autoscaling-developer-maxscale.adoc
  modules/serverless-autoscaling-developer-minscale.adoc
  modules/serverless-autoscaling-maxscale-kn.adoc
  modules/serverless-autoscaling-minscale-kn.adoc
  modules/serverless-blue-green-deploy.adoc
  modules/serverless-concurrency-limits-configure-hard.adoc
  modules/serverless-concurrency-limits-configure-soft.adoc
  modules/serverless-containersource-guidelines.adoc
  modules/serverless-cost-management-labels.adoc
  modules/serverless-create-domain-mapping-kn.adoc
  modules/serverless-create-domain-mapping.adoc
  modules/serverless-create-traffic-split-kn.adoc
  modules/serverless-domain-mapping-odc-admin.adoc
  modules/serverless-domain-mapping-odc-developer.adoc
  modules/serverless-kafka-source-kn.adoc
  modules/serverless-pingsource-kn.adoc
  modules/serverless-pingsource-odc.adoc
  modules/serverless-pingsource-yaml.adoc
  modules/serverless-sinkbinding-kn.adoc
  modules/serverless-sinkbinding-odc.adoc
  modules/serverless-sinkbinding-yaml.adoc
  modules/serverless-target-utilization.adoc
  modules/verifying-serverless-app-deployment.adoc
  snippets/serverless-apps.adoc
Labels: peer-review-done, size/L, serverless, jira/valid-reference

#64174 TELCODOCS-1324: Moving TALM content under network far edge section
  _topic_maps/_topic_map.yml
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: peer-review-done, lgtm, size/S, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#60615 TELCODOCS-1215 - Adding GitOps ZTP managed cluster maximums info
  .vale/styles/Vocab/OpenShiftDocs/accept.txt
  modules/ztp-gitops-ztp-max-spoke-clusters.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#63900 OCPBUGS#18029: Changed example from baremetal to vsphere
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.13, branch/enterprise-4.14

#64213 TELCODOCS-1417 Adding content manually copied from PR #59607
  modules/nw-multus-vlan-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: peer-review-done, size/M, telco, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#64272 Adding OpenShift Telco distro
  _distro_map.yml
  _templates/_page_openshift.html.erb
  _topic_maps/_topic_map.yml
  telco_ref_design_specs/_attributes
  telco_ref_design_specs/cnf-core-reference-design.adoc
  telco_ref_design_specs/images
  telco_ref_design_specs/modules
  telco_ref_design_specs/snippets
  telco_ref_design_specs/ztp-ran-reference-design.adoc
Labels: size/M

#64292 Revert "Adding OpenShift Telco distro"
  _distro_map.yml
  _templates/_page_openshift.html.erb
  _topic_maps/_topic_map.yml
  telco_ref_design_specs/_attributes
  telco_ref_design_specs/cnf-core-reference-design.adoc
  telco_ref_design_specs/images
  telco_ref_design_specs/modules
  telco_ref_design_specs/snippets
  telco_ref_design_specs/ztp-ran-reference-design.adoc
Labels: size/M

#64271 TELCODOCS-1324: CP to 4.13
  _topic_maps/_topic_map.yml
  release_notes/ocp-4-13-release-notes.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: size/S, jira/valid-reference

#64269 TELCODOCS-1324: CP to 4.12
  _topic_maps/_topic_map.yml
  release_notes/ocp-4-12-release-notes.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: size/S, jira/valid-reference

#63411 CNV- 31197: 4.12.6 HCO version
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.12

#64293 Adding new OCP Telco distro infrastructure
  _distro_map.yml
  _templates/_page_openshift.html.erb
  _templates/_search.html.erb
  _templates/_search_telco.html.erb
Labels: size/M

#62429 OSDOCS-6566: Add IPsec support for IBM Cloud
  modules/nw-modifying-operator-install-config.adoc
  modules/nw-operator-cr.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.14

#62463 RHDEVDOCS-5518: Documenting Pipelines templates in the admin console
  _topic_maps/_topic_map.yml
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  cicd/pipelines/customizing-configurations-in-the-tektonconfig-cr.adoc
  cicd/pipelines/working-with-pipelines-using-the-developer-perspective.adoc
  cicd/pipelines/working-with-pipelines-web-console.adoc
  images/import-icon.png
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-creating-pipeline-templates-admin-console.adoc
  modules/op-creating-pipelines-along-with-applications.adoc
  modules/op-deleting-pipelines.adoc
  modules/op-editing-pipelines.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-odc-pipelines-abstract.adoc
  modules/op-starting-pipelines-from-pipelines-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/op-using-custom-pipeline-template-for-git-import.adoc
Labels: peer-review-needed, size/L, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64298 OSDOCS#7648: Release note for MicroShift 4.13.11
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#64085 OSDOCS-7517: 4.13 ZTP manifests
  installing/installing_with_agent_based_installer/installing-with-agent-based-installer.adoc
  modules/installing-ocp-agent-ZTP.adoc
  modules/installing-ocp-agent-boot.adoc
  modules/installing-ocp-agent-inputs.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.13

#64299 Updates deprecated links for two Container descrptions
  _unused_topics/nodes-containers-using-about.adoc
  modules/containers-about.adoc
  nodes/containers/nodes-containers-using.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64326 [enterprise-4.14] OCPBUGS-18432: Updated TuneD bootloader supportability note
  modules/configuring-huge-pages.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#64327 [enterprise-4.12] OCPBUGS-18432: Updated TuneD bootloader supportability note
  modules/configuring-huge-pages.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#64328 [enterprise-4.11] OCPBUGS-18432: Updated TuneD bootloader supportability note
  modules/configuring-huge-pages.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#64329 [enterprise-4.10] OCPBUGS-18432: Updated TuneD bootloader supportability note
  modules/configuring-huge-pages.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#64196 Migrates 3.11 note regarding routes to 4.x
  modules/deployments-ab-testing-lb.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64289 [RHACS] ROX-19225: Updating architecture module to reflect scanner-slim
  images/acs-architecture-kubernetes.png
  images/acs-architecture-ocp.png
Labels: lgtm, size/XS, RHACS, jira/valid-reference

#62611 OSDOCS-5470: Rework Responsibility Assignment and Process/Security
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-policy-change-management.adoc
  modules/rosa-policy-customer-responsibility.adoc
  modules/rosa-policy-disaster-recovery.adoc
  modules/rosa-policy-identity-access-management.adoc
  modules/rosa-policy-incident.adoc
  modules/rosa-policy-responsibilities.adoc
  modules/rosa-policy-security-and-compliance.adoc
  modules/rosa-policy-security-regulation-compliance.adoc
  modules/rosa-policy-shared-responsibility.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-policy-process-security.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.adoc
Labels: peer-review-done, size/XXL, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64342 [OSDOCS-7624]1.2.26 what's new
  rosa_release_notes/rosa-release-notes.adoc
Labels: size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#64318 [pipelines-docs] RHDEVDOCS-5518: Documenting Pipelines templates in the admin console
  _topic_maps/_topic_map.yml
  create/creating-applications-with-cicd-pipelines.adoc
  create/working-with-pipelines-using-the-developer-perspective.adoc
  create/working-with-pipelines-web-console.adoc
  images/import-icon.png
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/odc-adding-a-GitHub-repository-containing-pipelines.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-creating-pipeline-templates-admin-console.adoc
  modules/op-creating-pipelines-along-with-applications.adoc
  modules/op-deleting-pipelines.adoc
  modules/op-editing-pipelines.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-odc-pipelines-abstract.adoc
  modules/op-starting-pipelines-from-pipelines-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/op-using-custom-pipeline-template-for-git-import.adoc
Labels: size/L, jira/valid-reference

#64353 [pipelines-docs-1.10] RHDEVDOCS-5518: Documenting Pipelines templates in the admin console
  _topic_maps/_topic_map.yml
  create/creating-applications-with-cicd-pipelines.adoc
  create/working-with-pipelines-using-the-developer-perspective.adoc
  create/working-with-pipelines-web-console.adoc
  images/import-icon.png
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-creating-pipeline-templates-admin-console.adoc
  modules/op-creating-pipelines-along-with-applications.adoc
  modules/op-deleting-pipelines.adoc
  modules/op-editing-pipelines.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-interacting-with-pipelines-using-the-developer-perspective.adoc
  modules/op-odc-pipelines-abstract.adoc
  modules/op-starting-pipelines-from-pipelines-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/op-using-custom-pipeline-template-for-git-import.adoc
Labels: size/L, jira/valid-reference

#62742 OSDOCS-6566: Add release note for IPsec on IBM Cloud
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14

#64294 Adding new Openshift Telco distro content files
  _topic_maps/_topic_map.yml
  telco_ref_design_specs/_attributes
  telco_ref_design_specs/cnf-core-reference-design.adoc
  telco_ref_design_specs/images
  telco_ref_design_specs/modules
  telco_ref_design_specs/snippets
  telco_ref_design_specs/ztp-ran-reference-design.adoc
  welcome/index.adoc
Labels: size/M

#64319 OSDOCS#7647: Adds notes for MS 4.12.32 release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#64266 TELCODOCS-1535-ocp-4.10: Updated correct YAML file for pod deployment
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-cli.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-web.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.10, merge-review-needed

#64268 TELCODOCS-1535-ocp-4.12: Updated correct YAML file for pod deployment
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-cli.adoc
  modules/sandboxed-containers-deploying-workloads-with-kata-runtime-web.adoc
Labels: peer-review-done, lgtm, size/L, telco, branch/enterprise-4.12, merge-review-in-progress

#64296 OCPBUGS-12930-link-fix
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_powervs/installing-restricted-networks-ibm-power-vs.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_nutanix/installing-restricted-networks-nutanix-installer-provisioned.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64010 OCPBUGS#18100-New: Revert optional step in vSphere docs
  modules/installation-vsphere-machines.adoc
  modules/machine-vsphere-machines.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64228 OCPBUGS-18429: Clarifying best practices for nncp deployment across mcps
  modules/nw-sriov-networknodepolicy-object.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64066 Removed the "catalog" column from the compatability matrix for consis…
  modules/op-tkn-pipelines-compatibility-support-matrix.adoc
Labels: lgtm, size/S, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64363 [enterprise-4.10] Ocpbugs 14777 410
  modules/virt-prerequisites-mediated-devices.adoc
  modules/virt-virtual-gpus-config-overview.adoc
Labels: size/S

#53871 BZ2149119: Cron job limitation in_MTC 1.7.6
  modules/migration-mtc-release-notes-1-7.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, MTC, branch/enterprise-4.13, branch/enterprise-4.14

#64202 OSDOCS-7631 Z-stream RNs for 4.12.32
  release_notes/ocp-4-12-release-notes.adoc
Labels: lgtm, size/S, branch/enterprise-4.12

#64067 Updated the section for uninstalling Pipeline Operator.
  cicd/pipelines/uninstalling-pipelines.adoc
  modules/op-deleting-the-pipelines-component-and-custom-resources.adoc
Labels: lgtm, size/XS, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64307 OCPBUGS#11516: Noted that custom rules are ignored if the audit log p…
  modules/nodes-nodes-audit-config-about.adoc
  modules/nodes-nodes-audit-policy-custom.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64393 [OSDOCS-7634] shared VPC what's new blurb
  rosa_release_notes/rosa-release-notes.adoc
Labels: size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#64005 OCPBUGS#13199-RE: Updated the Required permissions and prop settings vSphere table
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#64392 OSDOCS-3562: Add SRE access assembly for OSD
  _topic_maps/_topic_map_osd.yml
  osd_architecture/osd-sre-access.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#63953 CNV-29940: Release note Preview bridge NIC hot-plug
  virt/release_notes/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.14

#64195 OSDOCS-7625: add GA and update release notes 4.14
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#63481 TELCODOCS-1433 Docs NRO Must Gather
  modules/cnf-about-collecting-nro-data.adoc
  modules/gathering-data-specific-features.adoc
  scalability_and_performance/cnf-numa-aware-scheduling.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.14

#64205 OSDOCS-7650: release note MicroShift network changes
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.14

#64237 OSDOCS-7626: adds release note backup and restore MicroShift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14

#64340 OBSDOCS-106: Remove outdated configmap refs
  logging/cluster-logging-external.adoc
  modules/cluster-logging-collector-log-forward-fluentd.adoc
  modules/cluster-logging-collector-log-forward-syslog.adoc
Labels: peer-review-done, lgtm, size/S, dev-tools, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64284 OCPBUGS-10696 - SNO clusters upgrade with TALM docs are missing infor…
  modules/cnf-topology-aware-lifecycle-manager-policies-concept.adoc
  snippets/cnf-example-upgrade-policy.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64308 ROX-18669: Add listening endpoints info
  _topic_map.yml
  operating/audit-listening-endpoints.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.2

#64376 removing dead link from homepage
  index-commercial.html
Labels: size/S

#64084 docs: It's supported to change files via Ignition
  installing/install_config/installing-customizing.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#63778 ROX-18667: Update policy criteria for add and drop changes and new criteria
  modules/policy-criteria.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.2

#42126 CNV-16295: Prevent NVIDIA GPU operands from deploying on nodes
  modules/virt-preventing-nvidia-gpu-operands-from-deploying-on-nodes.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-pci-passthrough.adoc
Labels: peer-review-done, size/M, CNV, jira/valid-reference, branch/enterprise-4.14

#63830 OSDOCS-6661: Updates to MicroShift manifests
  microshift_running_apps/microshift-applications.adoc
  microshift_running_apps/microshift-greenboot-workload-scripts.adoc
  microshift_running_apps/microshift-operators.adoc
  modules/microshift-applying-manifests-example.adoc
  modules/microshift-manifests-override-paths.adoc
  modules/microshift-manifests-overview.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#64045 [OSDOCS-6598] Added information on what role is required for OADP installation on ROSA STS
  modules/oadp-installing-oadp-rosa-sts.adoc
  modules/oadp-preparing-aws-credentials.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#62166 CNV- 30800: RN for runbook changes
  virt/release_notes/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.14

#64303 OCPBUGS#17754: Updated cocode snippet installation-cis-ibm-cloud.adoc
  modules/installation-cis-ibm-cloud.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#64172 [RHACS] ROX-18663: Documenting delegated image scanning feature
  modules/accessing-delegated-image-scanning.adoc
  modules/acs-quick-install-secured-cluster-using-helm.adoc
  modules/configuring-delegated-image-scanning.adoc
  modules/enhancing-image-scanning-by-accessing-delegated-image-scanning.adoc
  operating/examine-images-for-vulnerabilities.adoc
Labels: peer-review-done, size/L, RHACS, merge-review-in-progress, merge-review-needed, jira/valid-reference, rhacs-docs-4.2

#64300 [RHACS] ROX-19179: Updating roxctl netpol commands
  modules/generate-build-time-network-policies.adoc
Labels: peer-review-done, size/XS, RHACS, merge-review-in-progress, merge-review-needed, jira/valid-reference, rhacs-docs-4.2

#64466 OSDOCS-3562: Move OSD assembly to correct sub-directory
  osd_architecture/osd_policy/osd-sre-access.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64475 [OSDOCS-7635] adding new region and machine pool disk volume size what's new
  rosa_release_notes/rosa-release-notes.adoc
Labels: size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#63890 RHDEVDOCS-5511: Authenticating build images
  _topic_maps/_topic_map.yml
  builds/authenticating-build-images.adoc
  modules/ob-authentication-to-container-registries.adoc
  modules/ob-authentication-to-git-repositories.adoc
  modules/ob-basic-authentication.adoc
  modules/ob-build-secret-annotation.adoc
  modules/ob-defining-the-build-specification.adoc
  modules/ob-role-based-access-control.adoc
  modules/ob-ssh-authentication.adoc
  modules/ob-usage-of-git-secret.adoc
Labels: peer-review-done, size/L, dev-tools, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference

#64309 [OSDOCS-7673]: Clarifying hosted cluster definition
  modules/hosted-control-planes-concepts-personas.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14

#64405 OSDOCS-7644
  modules/rosa-policy-identity-access-management.adoc
  osd_architecture/osd_policy/osd-sre-access.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64391 OSDOCS-7643: Privatelink endpoint creation
  modules/rosa-sre-access-privatelink-vpc.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: lgtm, size/S, jira/valid-reference, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#63822 ROX-17466: Updates for Vuln Mgt Reporting 2.0
  modules/vulnerability-management-accept-risks.adoc
  modules/vulnerability-management-delete-report.adoc
  modules/vulnerability-management-edit-report.adoc
  modules/vulnerability-management-mark-false-positive.adoc
  modules/vulnerability-management-reporting20.adoc
  modules/vulnerability-management-review-deferred.adoc
  modules/vulnerability-management-scheduled-report.adoc
  modules/vulnerability-management-send-report.adoc
  modules/vulnerability-management-upgrade-component.adoc
  modules/vulnerability-management-view-applications-vulnerability.adoc
  modules/vulnerability-management-view-image-vulnerability.adoc
  modules/vulnerability-management-view-infrastructure-vulnerability.adoc
  modules/vulnerability-management-view-node-vulnerability.adoc
  modules/vulnerability-management20-clone-reports.adoc
  modules/vulnerability-management20-configure-report-delivery-destinations-schedule.adoc
  modules/vulnerability-management20-creating-report.adoc
  modules/vulnerability-management20-delete-reports.adoc
  modules/vulnerability-management20-download-reports.adoc
  modules/vulnerability-management20-edit-reports.adoc
  modules/vulnerability-management20-permissions.adoc
  modules/vulnerability-management20-report-review-create.adoc
  modules/vulnerability-management20-retention-settings.adoc
  modules/vulnerability-management20-send-reports.adoc
  operating/manage-vulnerabilities/images
  operating/manage-vulnerabilities/snippets
  operating/manage-vulnerabilities/vulnerability-management.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.2

#64331 OSDOCS-7640: Doc how service accounts assume AWS IAM roles
  _topic_maps/_topic_map_osd.yml
  authentication/assuming-an-aws-iam-role-for-a-service-account.adoc
  modules/how-service-accounts-assume-aws-iam-roles-in-sre-owned-projects.adoc
  modules/understanding-pod-identity-webhook-workflow-in-user-defined-projects.adoc
  osd_architecture/osd_policy/osd-sre-access.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: size/M, jira/valid-reference

#64491 [OSDOCS-7642] SRE STS access updates
  modules/rosa-policy-identity-access-management.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64354 [OSDOCS-7641]: SRE cluster access
  modules/sre-cluster-access.adoc
  osd_architecture/osd_policy/osd-sre-access.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: size/M, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64433 OSDOCS-7680: Remove "must" from CIDR text
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
  networking/cidr-range-definitions.adoc
Labels: peer-review-done, size/XS, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64499 OSDOCS-3562: Added SRE topics to topic maps.
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  rosa_architecture/rosa_policy_service_definition/rosa-sre-access.adoc
Labels: size/XS, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64507 OSDOCS-6352.2: Remove topic maps for SRE
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
Labels: size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#63576 TELCODOCS-1347: Add support for node labels to SiteConfig RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#64297 OCPBUGS-17409 Adding link to KB article
  modules/nw-sriov-configuring-operator.adoc
Labels: peer-review-done, size/XS, telco, merge-review-in-progress

#64498 Expand CO docs to not claim compliance based on usage
  security/compliance_operator/compliance-operator-supported-profiles.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64511 RHDEVDOCS-5484: add builds distro to main
  _distro_map.yml
Labels: lgtm, size/S, jira/valid-reference

#64259 OSSM-4779: spec section appears twice in the SMCP yaml sample
  modules/ossm-integrating-with-user-workload-monitoring.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64452 ROX-18793: openshift monitoring
  _topic_map.yml
  configuration/monitor-acs.adoc
  modules/central-configuration-options-operator.adoc
  modules/enable-monitoring-central-helm.adoc
  modules/enable-monitoring-central-operator.adoc
  modules/enable-monitoring-customize-port.adoc
  modules/enable-monitoring-manual.adoc
  modules/monitor-osp-disable-helm.adoc
  modules/monitor-osp-disable-operator.adoc
  modules/monitoring-custom-prometheus.adoc
  modules/monitoring-osp.adoc
  modules/prometheus-service-monitor.adoc
  modules/secured-cluster-services-config.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.2

#63944 OBSDOCS-352: document-new-silences-panel-in-monitoring-dev-console
  modules/monitoring-editing-silences.adoc
  modules/monitoring-expiring-silences.adoc
  modules/monitoring-managing-silences.adoc
  modules/monitoring-silencing-alerts.adoc
Labels: peer-review-done, size/L, dev-tools, qe-approved, jira/valid-reference, branch/enterprise-4.14

#64510 OSDOCS-3562: SRE and service account access for ROSA and OSD
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-policy-identity-access-management.adoc
  osd_architecture/osd_policy/osd-sre-access.adoc
  osd_architecture/osd_policy/policy-process-security.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.adoc
Labels: peer-review-done, lgtm, size/S, px-approved, jira/valid-reference, branch/enterprise-4.13, SD-docs, branch/enterprise-4.14

#64189 [OSDOCS-7645]: Remove Note Regarding Inability to Delete Default Machine Pool, other MP updates
  modules/creating-a-machine-pool-ocm.adoc
  modules/creating-a-machine-pool.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools.adoc
  modules/rosa-adding-taints-cli.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
Labels: peer-review-done, size/M, merge-review-needed

#63690 OCPBUGS#13837: Improve the note
  security/certificate_types_descriptions/bootstrap-certificates.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#64185 GitOps 1.9.2 release notes documentation.
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-9-2.adoc
Labels: lgtm, size/M, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#63998 ROX-18668: Network graph changes for 4.2
  modules/apply-generated-policies-ng20.adoc
  modules/generate-network-policies-ng20.adoc
  modules/rbac-for-network-graph.adoc
  modules/simulate-network-policies-ng20.adoc
  modules/test-generated-policies-ng20.adoc
  operating/manage-network-policies.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.2

#64356 Updating MTC release notes 1.7.01 to 1.7.12
  migration_toolkit_for_containers/mtc-release-notes.adoc
  modules/migration-mtc-release-notes-1-7-01.adoc
  modules/migration-mtc-release-notes-1-7-02.adoc
  modules/migration-mtc-release-notes-1-7-03.adoc
  modules/migration-mtc-release-notes-1-7-04.adoc
  modules/migration-mtc-release-notes-1-7-05.adoc
  modules/migration-mtc-release-notes-1-7-06.adoc
  modules/migration-mtc-release-notes-1-7-07.adoc
  modules/migration-mtc-release-notes-1-7-08.adoc
  modules/migration-mtc-release-notes-1-7-09.adoc
  modules/migration-mtc-release-notes-1-7-10.adoc
  modules/migration-mtc-release-notes-1-7-11.adoc
  modules/migration-mtc-release-notes-1-7-12.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, MTC, branch/enterprise-4.13, branch/enterprise-4.14

#64301 OSSM-4795: Variable appears in code block
  modules/ossm-deploy-cluster-wide-control-plane-console.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64260 OSSM-4778: Sample command line is missing closing parenthesis
  modules/ossm-integrating-with-user-workload-monitoring.adoc
Labels: size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#61548 TELCODOCS-1237: VRFs for consistent isolated routes
  _topic_maps/_topic_map.yml
  images/357_OpenShift_MetalLB_VRF_0823.png
  modules/nw-egress-service-cr.adoc
  modules/nw-egress-service-ovn.adoc
  modules/nw-metallb-configure-return-traffic-proc.adoc
  modules/nw-metallb-configure-vrf-bgppeer.adoc
  modules/virt-example-host-vrf.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
  networking/metallb/metallb-configure-bgp-peers.adoc
  networking/metallb/metallb-configure-return-traffic.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-traffic-for-vrf-loadbalancer-services.adoc
Labels: peer-review-done, size/XL, telco, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#64246 CNV 28726: Release note: NEW Windows 11 / 2022
  virt/release_notes/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-needed

#63976 [HCCDOC-1094] Insights DataGather
  modules/disabling-insights-operator-gather.adoc
  modules/running-insights-operator-gather-cli.adoc
  modules/running-insights-operator-gather-web-console.adoc
  support/remote_health_monitoring/using-insights-operator.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#60607 OSDOCS-5785#Secret Store CSI operator (TP)
  _topic_maps/_topic_map.yml
  modules/persistent-storage-csi-secrets-store-driver-install.adoc
  modules/persistent-storage-csi-secrets-store-driver-overview.adoc
  modules/persistent-storage-csi-secrets-store-driver-uninstall.adoc
  storage/container_storage_interface/ephemeral-storage-csi-inline.adoc
  storage/container_storage_interface/persistent-storage-csi-secrets-store.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.14

#63939 OSDOCS#7577: Release note for single stack support for k8s nmstate
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14

#64537 OSDOCS-7212: Machine configs are processed in order of their name
  modules/machine-config-overview.adoc
Labels: peer-review-done, lgtm, size/XS, priority/critical-urgent, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#63604 OSDOCS#6381:Adds release notes for console RFEs
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14

#64407 OCPBUGS-18100-New:
  modules/installation-vsphere-machines.adoc
  modules/machine-vsphere-machines.adoc
Labels: size/M, branch/enterprise-4.12, merge-review-in-progress

#64390 OCPBUGS-12930-link-fix
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
Labels: size/S

#64389 OCPBUGS-12930-link-fix
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_ibm_power/installing-restricted-networks-ibm-power.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
Labels: size/S

#64524 OSDOCS#6190: Update minimum support period to 16 months
  modules/life-cycle-minor-versions.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14

#64473 CNV- 28484: Bootable volumes on web UI overview
  virt/getting_started/virt-web-console-overview.adoc
Labels: peer-review-done, lgtm, size/M, CNV, branch/enterprise-4.14

#64526 4.10 end of maintenance
  _templates/_page_openshift.html.erb
Labels: size/XS

#64591 Follow-up for 4.14 typo
  modules/nw-egress-service-ovn.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14

#62439 Remove mentions of `use-octavia`
  modules/cluster-cloud-controller-config-osp.adoc
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nw-openstack-external-ccm.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.14

#64546 Support removal of OpenShift Default Registry RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#64603 fixing broken portal build
  scalability_and_performance/scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: size/S

#63593 TELCODOCS-1237 release notes
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.14

#63930 OSDOCS#7498: Adding known issue related to GCP service account
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.14

#64606 [enterprise-4.13] fixing broken portal build
  scalability_and_performance/scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: size/S

#64607 [enterprise-4.12] fixing broken portal build
  scalability_and_performance/scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-preparing-the-hub-cluster.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
  scalability_and_performance/ztp_far_edge/ztp-updating-gitops.adoc
Labels: size/S

#64341 ROX-19549: Update violations info and include network policy yaml availability
  modules/violation-view-policy-tab.adoc
  modules/violations-view-deployment-tab.adoc
  modules/violations-view.adoc
  operating/respond-to-violations.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.2

#63874 OSDOCS#7563: Custom RHCOS image for control plane and compute machines
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, lgtm, size/L, qe-approved, branch/enterprise-4.12

#63767 OSDOCS#7519: Custom RHCOS image for control plane and compute machines
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-config-yaml.adoc
  modules/installation-gcp-marketplace.adoc
Labels: peer-review-done, lgtm, size/L, qe-approved, branch/enterprise-4.13

#64545 OSDOCS-7670: adds 4.13.12 to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#64158 [enterprise-4.13] TELCODOCS-1409: CP to 4.13
  modules/nw-sriov-configure-exclude-topology-manager.adoc
  modules/nw-sriov-exclude-topology-manager.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/nw-sriov-topology-manager.adoc
  networking/hardware_networks/add-pod.adoc
  networking/hardware_networks/configuring-sriov-device.adoc
Labels: size/L, jira/valid-reference

#64456 OCPBUGS-18653: OpenStack: Remove mentions of OSP 16.1
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-osp-loadbalancer-etp-local.adoc
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: peer-review-done, size/S, jira/severity-moderate, jira/valid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#63510 CNV- 31957: 4.11.6 HCO version
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11

#64598 [OSDOCS-7705] machine pool what's new
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13, branch/enterprise-4.14

#64625 [enterprise-4.13] OpenStack: Remove mentions of OSP 16.1
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-osp-loadbalancer-etp-local.adoc
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: size/S

#64624 [enterprise-4.12] OpenStack: Remove mentions of OSP 16.1
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-osp-loadbalancer-etp-local.adoc
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: size/S

#64626 [enterprise-4.14] OpenStack: Remove mentions of OSP 16.1
  modules/installation-osp-setting-cloud-provider-options.adoc
  modules/nw-ingress-controller-configuration-parameters.adoc
  modules/nw-osp-loadbalancer-etp-local.adoc
  modules/supported-platforms-for-openshift-clusters.adoc
Labels: size/S

#64593 OSDOCS-7697: Documented the 4.12.33 z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-needed, jira/valid-reference

#64212 OSDOCS#7545: Release Notes for root volume types
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14

#64595 [OSDOCS-7196]: Removing step about manual rollout
  modules/etcd-tuning-parameters.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.14

#62775 TELCODOCS-1178: Remove content from a CR on managed clusters
  modules/ztp-removing-content-from-managed-clusters.adoc
  scalability_and_performance/ztp_far_edge/ztp-configuring-managed-clusters-policies.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#64578 OSDOCS 7678: Included missing policy info and instructions for ROSA Shared VPC
  modules/rosa-sharing-vpc-creation-and-sharing.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13, branch/enterprise-4.14

#64187 GitOps 1.8.5 release notes documentation.
  cicd/gitops/gitops-release-notes.adoc
  modules/gitops-release-notes-1-8-5.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#64614 OCPBUGS#15261: fix issue with callout rendering on the customer portal
  modules/ipi-install-configuring-the-install-config-file.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#62928 TELCODOCS-1415: Add information about status.state.AtLatestKnown for Subscription CRs
  modules/cnf-topology-aware-lifecycle-manager-about-subscription-crs.adoc
  scalability_and_performance/ztp_far_edge/cnf-talm-for-cluster-upgrades.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#64474 CNV-26971: Updating repo names for 4.14
  modules/virt-installing-virtctl-client-yum.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, jira/valid-reference, branch/enterprise-4.14

#63815 [OSDOCS-6752]: AWS placement groups support
  machine_management/control_plane_machine_management/cpmso-using.adoc
  machine_management/creating_machinesets/creating-machineset-aws.adoc
  modules/machineset-aws-existing-placement-group.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.14
