Repository openshift/openshift-docs, pull requests merged in 2023-01, with the labels that each got.

#54146 OCPBUGS4880 Changing 'data' to 'binaryData' avoid storing the logo in the wrong file
  modules/adding-a-custom-logo.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54035 OSDOCS-4661:adds Agent-based Intaller to the Installing overview page
  installing/index.adoc
  modules/installation-overview.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54154 OSDOCS-4521: clean-up of #54113
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#53968 OSSMDOC-731: Change OSSM Console from Dev Preview to Tech Preview
  modules/ossm-rn-new-features.adoc
Labels: lgtm, size/XS, px-approved

#52463 OSDOCS-3786:Local ephemeral storage resource mgmt
  modules/storage-ephemeral-storage-manage.adoc
  storage/understanding-ephemeral-storage.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#54158 fix typo in RHACS docs
  modules/disable-language-specific-vulnerability-scanning.adoc
Labels: peer-review-done, lgtm, size/XS, RHACS, merge-review-in-progress

#52907 OSDOCS-4012: Add platform Operator and RukPak docs
  _topic_maps/_topic_map.yml
  architecture/control-plane.adoc
  modules/arch-platform-operators.adoc
  modules/olm-deleting-po.adoc
  modules/olm-installing-from-operatorhub-using-cli.adoc
  modules/olm-installing-from-operatorhub-using-web-console.adoc
  modules/olm-installing-operators-from-operatorhub.adoc
  modules/olm-installing-po-after.adoc
  modules/olm-installing-po-during.adoc
  modules/olm-po-techpreview.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/olm-rukpak-about.adoc
  modules/olm-rukpak-bd.adoc
  modules/olm-rukpak-bundle-immutability.adoc
  modules/olm-rukpak-bundle.adoc
  modules/olm-rukpak-plain-bundle.adoc
  modules/olm-rukpak-provisioner.adoc
  modules/olm-rukpak-registry-bundle.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/admin/olm-creating-policy.adoc
  operators/admin/olm-managing-po.adoc
  operators/understanding/olm-packaging-format.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.12

#54095 [enterprise-4.12] add CoreDNS bump updates
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54172 OSDOCS-4521: Fixes a few nits in #54117
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#50697 OSDOCS-4183: add enabling serial console
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  modules/installation-user-infra-machines-advanced-console-configuration.adoc
  modules/installation-user-infra-machines-advanced-customizing-live-serial-console.adoc
  modules/installation-user-infra-machines-advanced-enabling-serial-console.adoc
  modules/installation-user-infra-machines-pxe.adoc
  modules/installation-user-infra-machines-static-network.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12

#53859 [enterprise-4.12] Add platform Operators / RukPak to 4.12 RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#51732 [enterprise-4.12] OSDOCS-4137: add SE RN entry
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54175 Update document with proper information
  nodes/jobs/nodes-pods-daemonsets.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54164 OSDOCS-4080: Updated AWS AMI image IDs
  modules/installation-aws-user-infra-rhcos-ami.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12

#49375 OSDOCS-2175: Add optional migration of OpenShift SDN features
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ovn-kubernetes-migration-about.adoc
  modules/nw-ovn-kubernetes-migration.adoc
  modules/nw-ovn-kubernetes-rollback.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12

#50241 TELCODCS#835: RN - Ironic API served by proxy server in MB installations with a provisioning network
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, telco, branch/enterprise-4.12, merge-review-in-progress

#54099 OSDOCS4709: Release notes for Network Observability Operator
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.12

#53976 CNV-16073: Export VM disk
  _topic_maps/_topic_map.yml
  modules/virt-creating-virtualmachineexport.adoc
  modules/virt-virtctl-commands.adoc
  virt/virtual_machines/virt-exporting-vms.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12

#54124 CNV-15830: Memory dump RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.12

#54144 Update known issue text
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54126 CNV-18880: Update virt SR-IOV network
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/nw-sriov-configuring-device.adoc
  modules/nw-sriov-network-attachment.adoc
  modules/virt-attaching-vm-to-sriov-network.adoc
  networking/hardware_networks/about-sriov.adoc
  virt/virt-getting-started.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc
  virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
  virt/virtual_machines/vm_networking/virt-connecting-vm-to-service-mesh.adoc
  virt/virtual_machines/vm_networking/virt-defining-an-sriov-network.adoc
  virt/vm_templates/virt-creating-vm-template.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54128 CNV-20936: Live YAML view RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.12

#54191 [enterprise-4.9] CNV-18880: Update SR-IOV network doc
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/nw-sriov-configuring-device.adoc
  modules/nw-sriov-network-attachment.adoc
  modules/virt-attaching-vm-to-sriov-network.adoc
  networking/hardware_networks/about-sriov.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc
  virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
  virt/virtual_machines/vm_networking/virt-connecting-vm-to-service-mesh.adoc
  virt/virtual_machines/vm_networking/virt-defining-an-sriov-network.adoc
  virt/vm_templates/virt-creating-vm-template.adoc
Labels: size/L

#54192 [enterprise-4.10] CNV-18880: Update SR-IOV network doc
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/nw-sriov-configuring-device.adoc
  modules/nw-sriov-network-attachment.adoc
  modules/virt-attaching-vm-to-sriov-network.adoc
  networking/hardware_networks/about-sriov.adoc
  virt/virt-learn-more-about-openshift-virtualization.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc
  virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
  virt/virtual_machines/vm_networking/virt-connecting-vm-to-service-mesh.adoc
  virt/virtual_machines/vm_networking/virt-defining-an-sriov-network.adoc
  virt/vm_templates/virt-creating-vm-template.adoc
Labels: size/L

#54193 [enterprise-4.11] CNV-18880: Update SR-IOV network doc
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/nw-sriov-configuring-device.adoc
  modules/nw-sriov-network-attachment.adoc
  modules/virt-attaching-vm-to-sriov-network.adoc
  networking/hardware_networks/about-sriov.adoc
  virt/virt-learn-more-about-openshift-virtualization.adoc
  virt/virtual_machines/virt-create-vms.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc
  virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc
  virt/virtual_machines/vm_networking/virt-connecting-vm-to-service-mesh.adoc
  virt/virtual_machines/vm_networking/virt-defining-an-sriov-network.adoc
  virt/vm_templates/virt-creating-vm-template.adoc
Labels: size/L

#54145 4.12 installation doc updates from IBM P
  modules/registry-configuring-storage-baremetal.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54196 TELCODOCS-432 - RN for iPXE network booting
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#51073 Replace machine-os-content with new format base image (Layering)
  _topic_maps/_topic_map.yml
  modules/coreos-layering-configuring.adoc
  modules/coreos-layering-removing.adoc
  modules/coreos-layering-updating.adoc
  post_installation_configuration/coreos-layering.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12

#53895 OCPBUGS#4782 Added product variable to 4.9
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, merge-review-in-progress

#53760 OCPBUGS#4782 First known issue in OCP RN needs updated to reflect version
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#53847 OCPBUGS#4782 added product version variable in 4.10
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#53898 OCPBUGS#4782 Product version variable added to 4.12
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#54199 Add back in accidentally deleted RHACS info
  installing/installing_ocp/install-central-ocp.adoc
  modules/central-configuration-options-operator.adoc
Labels: peer-review-done, lgtm, size/S, RHACS, merge-review-in-progress

#53956 TELCODOCS-905: expanding networkType explanation
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, merge-review-in-progress

#54092 BZ#2059725 Added oc edit storageclass command
  modules/storage-expanding-add-volume-expansion.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-needed

#53879 CNV-17809: RN for live migration UI update
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.12, merge-review-in-progress

#54184 OCPDOCS-4341-RN Authenticating installer using VM service account
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#51575 Replace machine-os-content with new format base image (Layering) RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS

#52426 OSDOCS-3792:Volume populators
  modules/persistent-storage-csi-vol-populator.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54207 OSDOCS-4521: Adds another batch of 4.12 bugs to release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54204 OSDOCS-4724: Adds notes for 4.11.21 release
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11

#53482 Osdocs-4240 Added "only if you are using non-STS." to init command info for ROSA
  modules/dedicated-aws-vpc-initiating-peering.adoc
  modules/rosa-initialize.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12

#53508 OSDOCS#4612: Document the understanding Network Observability page
  _topic_maps/_topic_map.yml
  modules/nw-network-observability-operator.adoc
  modules/nw-view-status-configuration-network-observability-operator.adoc
  networking/network_observability/understanding-network-observability-operator.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12, merge-review-in-progress

#54111 TELCODOCS-640 updates
  modules/enabling-encapsulation.adoc
  modules/optimizing-by-encapsulation.adoc
  modules/running-services-with-encapsulation.adoc
  modules/supporting-encapsulation.adoc
  modules/supporting_encapsulation.adoc
  scalability_and_performance/optimizing-cpu-usage.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress

#54220 OSDOCS-4726: Adds notes for 4.10.46 release
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10

#53466 [enterprise-4.11] OSDOCS-4024: Add MT2892 Family SR-IOV hardware
  modules/nw-sriov-supported-devices.adoc
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11

#53612 [enterprise-4.10] OSDOCS-4024: Add MT2892 Family SR-IOV hardware
  modules/nw-sriov-supported-devices.adoc
  release_notes/ocp-4-10-release-notes.adoc
Labels: lgtm, size/S, branch/enterprise-4.10

#53663 CNV web UI overview
  _topic_maps/_topic_map.yml
  images/icon-link.svg
  images/icon-pencil.svg
  virt/virt-web-console-overview.adoc
Labels: peer-review-done, size/XL, qe-approved, branch/enterprise-4.12

#54132 CNV-18432: migrations tab on overview page RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.12

#54129 CNV-20482: Overview page enhancements RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12

#54136 CNV-18460: update virt overview assembly
  _topic_maps/_topic_map.yml
  modules/virt-resources-monitored-actively-in-Virtualization-Overview-page.adoc
  modules/virt-resources-monitored-for-top-consumption.adoc
  modules/virt-reviewing-top-consumers-projects-vms-nodes.adoc
  virt/logging_events_monitoring/virt-reviewing-virtualization-overview.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#54131 CNV-18453: MigrationPolicies page RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54130 CNV-18769: VM metrics tab RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54228 OSDOCS-4747: adds user tag for aws resource Release Note entry
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress

#54234 [SRVCOM-2213] Remove TP notes for features that went GA
  modules/serverless-admin-init-containers.adoc
  modules/serverless-enabling-pvc-support.adoc
Labels: peer-review-done, size/XS, serverless, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#54001 OSDOCS-4298: Updating to allow relative path
  modules/oc-mirror-oci-format.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54201 OSDOCS-4591: Adding to install the resources as next steps
  modules/oc-mirror-oci-format.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54174 OSSMDOC-721: Update Istio must-gather tag
  modules/gathering-data-specific-features.adoc
  modules/ossm-about-collecting-ossm-data.adoc
Labels: size/XS

#54251 fix assembly metadata
  virt/install/uninstalling-virt.adoc
  virt/live_migration/virt-cancel-vmi-migration.adoc
  virt/upgrading-virt.adoc
  virt/virt-getting-started.adoc
  virt/virt-web-console-overview.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.12

#54087 CNV-20998: add pause mode content
  modules/virt-vm-fields-web.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#50208 TELCODOCS#842 - release note - Ironic now uses RHEL 9 base image
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, telco, branch/enterprise-4.12

#53180 TELCODOCS-642: Factory precaching tool
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  installing/installing_sno/install-sno-installing-sno.adoc
  modules/creating-custom-live-rhcos-iso.adoc
  modules/ztp-precaching-booting-from-live-os.adoc
  modules/ztp-precaching-downloading-artifacts.adoc
  modules/ztp-precaching-getting-tool.adoc
  modules/ztp-precaching-partitioning.adoc
  scalability_and_performance/ztp_far_edge/ztp-precaching-tool.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress

#53513 OSDOCS-4591: Adding known issues for oc-mirror OCI feature
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54213 [enterprise-4.12] Add xrefs for platform Operators in 4.12 RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#53263 OSDOCS-3917:Installing and Configuring the Network Observability operator
  _topic_maps/_topic_map.yml
  modules/network-observability-configuring-FLP-sampling.adoc
  modules/network-observability-configuring-quickfilters-flowcollector.adoc
  modules/network-observability-flowcollector-api-specifications.adoc
  modules/network-observability-flowcollector-kafka-config.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-lokistack-create.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/network-observability-roles-create.adoc
  networking/network_observability/configuring-operator.adoc
  networking/network_observability/flowcollector-api.adoc
  networking/network_observability/installing-operators.adoc
Labels: peer-review-done, size/XXL, qe-approved, branch/enterprise-4.12

#53953 update refs in Telco related modules for 411 to 412 or product-version
  modules/about-must-gather.adoc
  modules/cnf-collecting-low-latency-tuning-debugging-data-for-red-hat-support.adoc
  modules/cnf-configure_for_irq_dynamic_load_balancing.adoc
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-reducing-netqueues-using-nto.adoc
  modules/eco-node-maintenance-operator-installation-cli.adoc
  modules/gathering-data-specific-features.adoc
  modules/node-tuning-operator.adoc
  modules/nw-metalLB-monitor-upgrading.adoc
  modules/nw-ptp-installing-operator-cli.adoc
  modules/nw-sriov-cfg-bond-interface-with-virtual-functions.adoc
  modules/nw-sriov-installing-operator.adoc
  modules/ztp-sno-du-configuring-performance-addons.adoc
Labels: peer-review-done, lgtm, size/M, telco, branch/enterprise-4.11, branch/enterprise-4.12

#50830 OSDOCS-4198: Explain optional capabilities
  modules/cluster-bare-metal-operator.adoc
  modules/cluster-samples-operator.adoc
  modules/explanation-of-capabilities.adoc
  modules/operator-marketplace.adoc
  operators/operator-reference.adoc
  post_installation_configuration/cluster-capabilities.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12

#51467 [BZ#2102680] Address load balancer service creation limitation when the IP is specified with the in-tree cloud provider (and OSP)
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-cloud-provider-lb-fip.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#54273 Fixes post merge netobserv operator
  _topic_maps/_topic_map.yml
Labels: peer-review-done, size/XS

#54278 [enterprise-4.11] OSDOCS-4198 Explain the optional capabilities in installer docs
  modules/cluster-bare-metal-operator.adoc
  modules/cluster-samples-operator.adoc
  modules/explanation-of-capabilities.adoc
  modules/operator-marketplace.adoc
  operators/operator-reference.adoc
  post_installation_configuration/cluster-capabilities.adoc
Labels: size/L

#54217 [enterprise-4.12] OSDOCS-4708: add haproxy reload RN entry
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#54264 OSDOCS-4521: Adds another batch of release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#54029 OSDOCS-4706-v2 update Architecture section k8s APIs
  modules/microshift-k8s-apis.adoc
  modules/microshift-openshift-apis.adoc
Labels: peer-review-done, size/M, merge-review-in-progress

#53525 OSSMDOC-726:Create or revise task for creating a gateway
  modules/ossm-auto-route-enable.adoc
  modules/ossm-deploying-automatic-gateway-injection.adoc
  modules/ossm-gateways.adoc
Labels: peer-review-done, size/L, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#53713 OSDOCS#4604: Document troubleshooting Network Observability
  _topic_maps/_topic_map.yml
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-flowlogs-pipeline-kafka.adoc
  modules/troubleshooting-network-observability-network-flow.adoc
  networking/network_observability/troubleshooting-network-observability.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54103 TELCODOCS-642: Factory pre-caching tool RN
  _attributes/common-attributes.adoc
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12

#54246 OSDOCS-4725: Adds notes for 4.9.54 release
  release_notes/ocp-4-9-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.9

#54190 GH#54189
  security/container_security/security-understanding.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#53975 Add EOL versions to noindex - 4.6, 4.7
  _templates/_page_openshift.html.erb
Labels: size/XS

#51059 RHDEVDOCS-4472 -Add query to view metrics collected by Telemetry
  modules/telemetry-showing-data-collected-from-the-cluster.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.12

#51504 RHDEVDOCS-4472 - add query to view metrics collected by telemetry - v4.11 only
  modules/telemetry-showing-data-collected-from-the-cluster.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.11

#54097 BZ2101827: adds examples for RunAsUser
  modules/security-context-constraints-about.adoc
Labels: peer-review-done, size/M

#53827 OCPBUGS#4826: Azure disk set bug added to 4.11.16
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, merge-review-in-progress

#54308 TELCODOCS-905-4.11: merge conflict resolution
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#54311 TELCODOCS-905-4.10: merge conflict resolution
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#54314 TELCODOCS-905-4.9: merge conflict resolution
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#54221 [OSDOCS-4123]: adding rel note for HyperShift API
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#53941 TELCODOCS-887 412 Telco Core RN bug fixes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, telco, merge-review-in-progress

#53209 TELCODOCS-469 - Document GitOps ZTP specifics of hub-side CR templating
  modules/ztp-example-hub-template-functions.adoc
  modules/ztp-managing-sriov-vlan-with-hub-cluster-templates-in-pgt.adoc
  modules/ztp-preparing-the-hub-cluster-for-ztp.adoc
  modules/ztp-specifying-nics-in-pgt-crs-with-hub-cluster-templates.adoc
  modules/ztp-syncing-new-configmap-changes-to-existing-pgt-crs.adoc
  modules/ztp-using-hub-cluster-templates.adoc
  scalability_and_performance/ztp_far_edge/ztp-advanced-policy-config.adoc
  scalability_and_performance/ztp_far_edge/ztp-talm-updating-managed-policies.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12, merge-review-in-progress

#54260 4.12 install doc updates from IBM P
  modules/minimum-ibm-power-system-requirements.adoc
  modules/recommended-ibm-power-system-requirements.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12

#54255 [OSDOCS-4297]: adding release note for versioning support for hosted control planes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#54315 OSSMDOC-743: Update rel notes text after blog post gets revised
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, qe-approved, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54320 OCPBUGS#5248 Removed duplicate update service overview module.
  architecture/control-plane.adoc
  modules/update-service-overview.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#54309 OSDOCS-4646: add api tier and compatibility guidelines for microshift
  _topic_maps/_topic_map_ms.yml
  microshift_rest_api/modules
  microshift_rest_api/understanding-api-support-tiers.adoc
  microshift_rest_api/understanding-compatibility-guidelines.adoc
  modules/api-compatibility-exceptions.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12

#54125 CNV-20148: VM export RN
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54232 RN for web console overview doc
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54238 CNV-18452-migration-policies-ui
  modules/virt-configuring-a-live-migration-policy.adoc
  virt/live_migration/virt-configuring-live-migration-policies.adoc
Labels: peer-review-done, lgtm, size/XS

#52809 OCPBUGS#2012: Added Azure cloud provider clause
  installing/installing-preparing.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54353 [enterprise-4.9] OCPBUGS#2012: Added Azure cloud provider clause
  installing/installing-preparing.adoc
Labels: size/XS

#53799 OSDOCS-4693: Update firewall docs to allow MicroShift API
  microshift_networking/microshift-networking.adoc
  modules/about-microshift.adoc
  modules/microshift-configuring-ovn.adoc
  modules/microshift-cri-o-container-runtime.adoc
  modules/microshift-firewall-allow-traffic.adoc
  modules/microshift-firewall-config.adoc
  modules/microshift-firewall-known-issue.adoc
  modules/microshift-firewall-opt-settings.adoc
  modules/microshift-firewall-req-settings.adoc
  modules/microshift-firewall-verify-settings.adoc
  modules/microshift-firewalld-install.adoc
  modules/microshift-http-proxy.adoc
  modules/microshift-lvms-configuring.adoc
  modules/microshift-lvms-deployment.adoc
  modules/microshift-lvms-system-requirements.adoc
  modules/microshift-mDNS.adoc
  modules/microshift-ovs-snapshot.adoc
  modules/microshift-rpm-ostree.adoc
  modules/microshift-setting-lvms-path.adoc
  modules/microshift-using-lvms.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54337 CNV-18431: Monitoring live migrations UI
  _topic_maps/_topic_map.yml
  modules/virt-monitoring-vm-migration-web.adoc
  virt/live_migration/virt-monitor-vmi-migration.adoc
Labels: peer-review-done, size/M

#52911 OCP BUGS-1156: Adding download for macOS arm64 oc binary
  modules/cli-installing-cli-web-console-macos.adoc
  modules/cli-installing-cli.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.11, branch/enterprise-4.12

#54301 GH#49547 updating oc adm upgrade command
  modules/update-upgrading-cli.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#54357 Fix formatting issue
  virt/logging_events_monitoring/virt-reviewing-vm-dashboard.adoc
Labels: peer-review-done, size/XS

#54254 [OSDOCS-3974]: adding relnote about node tuning hosted cluster
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS

#54341 TELCODOCS 477 CNF-3882 4.12 ACM Topology Aware Lifecycle Manager
  modules/cnf-topology-aware-lifecycle-manager-about-cgu-crs.adoc
Labels: peer-review-done, lgtm, size/XS, telco, merge-review-in-progress, merge-review-needed

#54316 OSDOCS-4667: document known issue with spare-gb feature of LVMS in microshift
  modules/microshift-lvms-configuring.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54321 add link to kbase solution
  modules/installation-disk-partitioning.adoc
  modules/installation-user-infra-machines-advanced.adoc
Labels: peer-review-done, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54030 OSDOCS-4449: OSDK Release notes: incl. SDK 1.25.0 & Kubernetes 1.25
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12

#54064 OSDOCS-4719: Drop OSDK version to 1.25.0
  modules/osdk-installing-cli-linux-macos.adoc
  modules/osdk-scorecard-config.adoc
  modules/osdk-scorecard-output.adoc
  modules/osdk-scorecard-parallel.adoc
  modules/osdk-updating-projects.adoc
  modules/osdk-updating-v1220-to-v1250.adoc
  operators/operator_sdk/ansible/osdk-ansible-updating-projects.adoc
  operators/operator_sdk/golang/osdk-golang-updating-projects.adoc
  operators/operator_sdk/helm/osdk-helm-updating-projects.adoc
  operators/operator_sdk/helm/osdk-hybrid-helm-updating-projects.adoc
  operators/operator_sdk/java/osdk-java-updating-projects.adoc
  operators/operator_sdk/osdk-installing-cli.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12

#54351 FIO and CO removed from release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/M

#53655 OSDOCS-4383: BYOKMS for ROSA Clusters
  modules/rosa-sts-creating-a-cluster-with-customizations-cli.adoc
  modules/rosa-sts-creating-a-cluster-with-customizations-ocm.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12

#49647 Tuning CNI IFNAME clarification (omits using eth0)
  modules/nodes-safe-sysctls-list.adoc
  nodes/containers/nodes-containers-sysctls.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54384 OSSMDOC-738 Fixed noun/verb agreement.
  modules/ossm-architecture.adoc
Labels: peer-review-done, size/XS, dev-tools, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.12

#54331 OSDOCS-4756: Adds notes for 4.11.22 release
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11

#54334 OSDOCS-4761: fix attribute substitution in command block
  modules/installing-microshift-rpm.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress

#54371 [OSDOCS-4297]: updating relnote about hosted control planes versioning
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#54400 TELCODOCS-889 redoing PR-54102 in new clean PR
  release_notes/ocp-4-12-release-notes.adoc
Labels: size/S, merge-review-needed

#54235 OSDOCS-4748: Adds SME tech feedback on the whole agent content
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  modules/agent-install-ipi-install-root-device-hints.adoc
  modules/agent-install-networking.adoc
  modules/installing-ocp-agent.adoc
  modules/sample-ztp-custom-resources.adoc
  modules/understanding-agent-install.adoc
  modules/validations-before-agent-iso-creation.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed

#54385 OSDOCS-4074:adds InFW Operator to RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54261 [OSDOCS-3951]: adding relnote for sr-iov operator on hosted control planes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#51737 TELCODOCS-328 - RN for IPv6 support for VIPs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.12, merge-review-in-progress

#54343 BZ1998936 - No doc to introduce swift storage for image registry (4.9)
  _topic_maps/_topic_map.yml
  modules/registry-configuring-registry-storage-swift-trust.adoc
  registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.9, merge-review-in-progress, merge-review-needed

#54404 BZ1998936 No doc to introduce swift storage for image registry (4.8)
  _topic_maps/_topic_map.yml
  modules/registry-configuring-registry-storage-swift-trust.adoc
  registry/configuring_registry_storage/configuring-registry-storage-openstack-user-infrastructure.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.8, merge-review-needed

#54258 OSDOCS-3920: Adds release note for supported cluster products
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54419 Revert "bz#2117604: Added section on steal clock accounting"
  installing/installing_vmc/installing-restricted-networks-vmc.adoc
  installing/installing_vmc/installing-vmc-customizations.adoc
  installing/installing_vmc/installing-vmc-network-customizations.adoc
  installing/installing_vmc/installing-vmc.adoc
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc
  modules/installation-vsphere-steal-clock-accounting.adoc
Labels: size/M

#53698 BZ2117154 Reword storage space for OpenShift Container Platform cluster on RHOSP
  modules/installation-osp-bootstrap-machine.adoc
  modules/installation-osp-control-compute-machines.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54399 ECOPROJECT-1127: NHC update channel is stable since 4.11
  modules/eco-node-health-check-operator-installation-cli.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54431 [Enterprise-4.9] OCP#5305 Removed duplicate update service overview module 4.9.
  architecture/control-plane.adoc
  modules/update-service-overview.adoc
Labels: size/XS

#53515 TELCODOCS-1014 - Detailing methods for adding worker nodes
  post_installation_configuration/cluster-tasks.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54415 OSDOCS-4521: Adds another batch of 4.12 bugs and removes some duplicates
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54052 Added SDN support notes + noted performance improvements
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54262 [OSDOCS-4297]: Updating new docs about versioning for hosted control planes
  modules/hosted-control-planes-version-support.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54435 OSDOCS-4297: Update release note about hosted control plane versioning
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#54446 Revert misfire commits
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-cloud-provider-lb-fip.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#53658 [enterprise-4.10] NE-989: Add nw-ingress-edge-route-default-certificate
  modules/nw-ingress-edge-route-default-certificate.adoc
  networking/routes/route-configuration.adoc
Labels: size/M

#54454 [enterprise-4.11] [BZ#2102680] Address load balancer service creation limitation when the IP is specified with the in-tree cloud provider (and OSP)
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  modules/installation-osp-cloud-provider-lb-fip.adoc
Labels: size/S

#54434 [OSDOCS-4775] Create deprecated feature snippet
  snippets/deprecated-feature.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54408 OSDOCS-4521: Adds another batch of bugs to RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12

#54429 Updates CX6 family name to correct ID
  modules/nw-sriov-supported-devices.adoc
  modules/ref_hardware-compatibility-with-irq-affinity.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress

#54471 Pseudo cherry-pick of 54429
  modules/nw-sriov-supported-devices.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11

#54472 [enterprise-4.10] Updates CX6 family name to correct ID
  modules/nw-sriov-supported-devices.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10

#54473 [enterprise-4.9] Updates CX6 family name to correct ID
  modules/nw-sriov-supported-devices.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.9

#54432 Updates supported network interface controllers
  modules/nw-sriov-hwol-supported-devices.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54468 OSDOCS-4524:adds update to TP table in RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#54474 Revert "HOLD: Docs: Move MCD drain alert into the MCC, revisit error modes"
  modules/machine-config-daemon-metrics.adoc
Labels: size/XS

#54215 CNV-19780: new rn data volumes
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#54094 OSDOCS-4727: Noting an OVN-K limitation
  modules/nw-egressnetworkpolicy-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.8, branch/enterprise-4.9, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12

#54450 OSDOCS-4521:adds storage and OLM bug batch
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12

#54439 adding OCPBUGS-2618 and removing duplicate BZ-2051443
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, telco, merge-review-in-progress, merge-review-needed
