Repository openshift/openshift-docs, pull requests merged in 2023-05, with the labels that each got.

#59372 BZ2190236: Update SCC for DPDK checkup
  modules/virt-checking-cluster-dpdk-readiness.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.13

#59422 Remove context tags from assembly anchor IDs
  virt/live_migration/virt-configuring-live-migration-policies.adoc
  virt/live_migration/virt-migrate-vmi.adoc
  virt/support/virt-runbooks.adoc
  virt/support/virt-support-overview.adoc
  virt/support/virt-troubleshooting.adoc
  virt/virt-web-console-overview.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
Labels: peer-review-in-progress, peer-review-needed, size/L, CNV, branch/enterprise-4.13

#59428 [enterprise-4.13] Remove context tags from assembly anchor IDs
  virt/live_migration/virt-configuring-live-migration-policies.adoc
  virt/live_migration/virt-migrate-vmi.adoc
  virt/support/virt-runbooks.adoc
  virt/support/virt-support-overview.adoc
  virt/support/virt-troubleshooting.adoc
  virt/virt-4-13-release-notes.adoc
  virt/virt-web-console-overview.adoc
  virt/virtual_machines/vm_networking/virt-creating-service-vm.adoc
Labels: size/L

#59332 OSDOCS#5326: Added warning regarding rollbacks specific to TALM/SNO
  modules/cnf-topology-aware-lifecycle-manager-backup-recovery.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58844 Release notes for multi-arch compute machines on 4.13
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.13

#59175 OCPBUGS-3388: updates OVN-K configs
  release_notes/ocp-4-10-release-notes.adoc
Labels: lgtm, size/XS, branch/enterprise-4.10, jira/invalid-bug, jira/valid-reference

#58842 OSDOCS-3908-RN: adds node selector as enhancement to 4.13 RN
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13

#59383 ROSA-HCP: Renamed the product to ROSA with hosted control planes.
  _attributes/attributes-openshift-dedicated.adoc
  modules/rosa-hcp-byo-oidc-options.adoc
  modules/rosa-hcp-byo-oidc.adoc
  modules/rosa-hcp-classic-comparison.adoc
  modules/rosa-hcp-creating-account-wide-sts-roles-and-policies.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-vpc-manual.adoc
  modules/rosa-hcp-vpc-terraform.adoc
  modules/rosa-sts-associating-your-aws-account.adoc
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
  modules/rosa-sts-understanding-aws-account-association.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  snippets/rosa-hcp-rn.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#58341 OSSM-3695: 2.3.3 Z Stream Release Notes, Known Issues and Bug Fixes for OSSM
  _attributes/common-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-new-features.adoc
Labels: size/M, jira/valid-reference

#59448 SRVCOM-2269 add link to install docs for knative kafka
  serverless/eventing/event-sources/serverless-kafka-developer-source.adoc
Labels: lgtm, size/XS

#59184 OCPBUGS#11673: Confirm that the default CNI network provider is Openshift SDN
  modules/nw-ovn-kubernetes-rollback.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, merge-review-in-progress

#59411 ROX-16716: Update Release Notes for 3.74.3 patch
  release_notes/374-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, RHACS, merge-review-in-progress, rhacs-docs-3.74, jira/valid-reference

#58693 OCPBUGS#11815: Required Azure parameters
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#59447 [RHACS] [rhacs-docs-3.73] Manual CP from #59187 to 3.73
  integration/integrate-with-image-vulnerability-scanners.adoc
Labels: size/M

#59463 [enterprise-4.11] OCPBUGS#11815: required Azure parameters
  modules/installation-configuration-parameters.adoc
Labels: size/XS, merge-review-needed

#59040 OSDOCS5736: Document CMA metrics
  modules/nodes-pods-autoscaling-custom-metrics-access.adoc
  modules/nodes-pods-autoscaling-custom-metrics.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58175 OSDOCS#5597: Added regionalized AWS STS URLs to the allow list for PrivateLink (DRAFT)
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
  modules/rosa-sts-oidc-provider-command.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#58784 OADP 1366 - Channel update
  modules/about-oadp-update-channels.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#59402 [enterprise-4.11] OSDOCS-5694-feature:Drop macOS reference and add a note about golang
  modules/installation-obtaining-installer.adoc
Labels: size/M

#59483 Removed Tech Preview note from AWS Load Balancer Operator docs
  networking/aws_load_balancer_operator/install-aws-load-balancer-operator.adoc
Labels: size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59367 OSSM-3149 Update the 2.x docs note to say "recent version" instead of "all versions"
  service_mesh/v2x/ossm-about.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59501 [RHACS] 3.73 Fix the version number in common attributes
  modules/common-attributes.adoc
Labels: size/XS, RHACS, rhacs-docs-3.73

#58684 [RHACS] Added instructions for Operator upgrade
  modules/operator-upgrade-centraldb-cannot-be-scheduled.adoc
  modules/operator-upgrade-change-subscription-channel.adoc
  modules/operator-upgrade-fail-to-deploy.adoc
  modules/operator-upgrade-modify-central-custom-resource.adoc
  modules/prepare-operator-upgrades.adoc
  modules/rollback-operator-upgrades-cli.adoc
  modules/rollback-operator-upgrades-console.adoc
  upgrading/upgrade-operator.adoc
Labels: size/L, RHACS, rhacs-docs-4.0

#59283 ROX-15845: Release notes for ACS 4.0
  _topic_map.yml
  modules/common-attributes.adoc
  release_notes/40-release-notes.adoc
Labels: peer-review-done, lgtm, size/L, RHACS, merge-review-needed, jira/valid-reference

#59502 [rhacs-docs-4.0] Added instructions for Operator upgrade
  modules/operator-upgrade-centraldb-cannot-be-scheduled.adoc
  modules/operator-upgrade-change-subscription-channel.adoc
  modules/operator-upgrade-fail-to-deploy.adoc
  modules/operator-upgrade-modify-central-custom-resource.adoc
  modules/prepare-operator-upgrades.adoc
  modules/rollback-operator-upgrades-cli.adoc
  modules/rollback-operator-upgrades-console.adoc
  upgrading/upgrade-operator.adoc
Labels: size/L, rhacs-docs-4.0

#59505 [rhacs-docs-4.0] Release notes for ACS 4.0
  _topic_map.yml
  release_notes/374-release-notes.adoc
  release_notes/40-release-notes.adoc
Labels: size/XL, rhacs-docs-4.0

#58967 [RHACS] Added Helm upgrade instructions
  files/create_certificate_values_file.sh
  modules/central-services-private-config.adoc
  modules/central-services-public-config.adoc
  modules/helm-generate-root-certificates.adoc
  modules/helm-optimize-central-db-and-pvc.adoc
  modules/rollback-helm-upgrade.adoc
  modules/updating-helm-repository.adoc
  modules/upgrade-helm-chart.adoc
  upgrading/upgrade-helm.adoc
Labels: size/L, RHACS, rhacs-docs-4.0

#55453 [RHACS] Updated upgrade process for RHACS 4.0
  modules/back-up-central-database.adoc
  modules/create-resource-central-db-bundle.adoc
  modules/generate-central-database-provisioning-bundle.adoc
  modules/rollback-central-forced.adoc
  modules/rollback-central-normal.adoc
  modules/upgrade-central-cluster-central.adoc
  modules/upgrade-central-cluster-scanner.adoc
  modules/verify-central-cluster-upgrade.adoc
  upgrading/upgrade-roxctl.adoc
Labels: size/L, RHACS, rhacs-docs-4.0

#59393 OSDOCS#5808: Added NMState operator prerequisite
  modules/virt-creating-linux-bridge-nncp.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59455 Remove unused files
  modules/virt-about-hostpath-provisioner.adoc
  modules/virt-cli-reference-controlling-vms.adoc
  modules/virt-creating-storage-class-legacy-hpp.adoc
  modules/virt-importing-vm-to-block-pv.adoc
  modules/virt-removing-virtio-disk-from-vm.adoc
  modules/virt-resuming-node-from-maintenance-mode-with-cr.adoc
  modules/virt-resuming-node-maintenance-cli.adoc
  modules/virt-resuming-node-maintenance-web.adoc
  modules/virt-reviewing-top-consumers.adoc
  modules/virt-setting-node-maintenance-cli.adoc
  modules/virt-setting-node-maintenance-web.adoc
  modules/virt-setting-node-to-maintenance-mode-with-cr.adoc
  modules/virt-template-datavolume-import.adoc
Labels: peer-review-done, size/L, CNV, branch/enterprise-4.13

#58469 RHDEVDOCS-5176 - 5.7 Release Pre-reqs
  _topic_maps/_topic_map.yml
  logging/v5_5/logging-5-5-getting-started.adoc
  logging/v5_6/logging-5-6-architecture.adoc
  logging/v5_6/logging-5-6-getting-started.adoc
  logging/v5_7/attributes
  logging/v5_7/images
  logging/v5_7/logging-5-7-administration.adoc
  logging/v5_7/logging-5-7-architecture.adoc
  logging/v5_7/logging-5-7-configuration.adoc
  logging/v5_7/logging-5-7-getting-started.adoc
  logging/v5_7/logging-5-7-reference.adoc
  logging/v5_7/logging-5-7-release-notes.adoc
  logging/v5_7/modules
  logging/v5_7/snippets
  modules/logging-getting-started.adoc
  snippets/logging-compatibility-snip.adoc
  snippets/logging-elastic-dep-snip.adoc
Labels: lgtm, size/L

#59395 RHDEVDOCS-5251: Added bug fixes for pipelines 1.10.1 release
  modules/op-release-notes-1-10.adoc
Labels: lgtm, size/S, jira/valid-reference

#59394 OSDOCS-5889: Documented the 4.12.15 z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#59441 OSDOCS#5765: Replacing 3.3 podman recommendation to 3.4.2.0+
  installing/disconnected_install/installing-mirroring-creating-registry.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13

#59438 OSDOCS#5936: Adds notes for Microshift 4.12.15 release
  microshift_release_notes/microshift-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#58371 OCPBUGS-11488: Removing announcement of TP PSA since it is coming fir…
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#59508 OCPBUGS#11815: Remove double descriptions in the table
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, merge-review-in-progress

#59484 Mhess fix rhacs docs
  modules/create-policy-from-risk-view.adoc
  modules/use-process-baselines.adoc
Labels: peer-review-done, lgtm, size/S, RHACS, rhacs-docs-3.73, rhacs-docs-3.74, rhacs-docs-4.0

#59161 Tech preview no update features
  modules/nodes-cluster-enabling-features-about.adoc
  nodes/clusters/nodes-cluster-enabling-features.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#59482 OSDOCS#5652: Updated installation docs: vSphere 3rd party CSI driver
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59435 OSDOCS-5891: adds 4.10.59 to RN
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, jira/valid-reference

#59504 RHACS docs 4.0 release 2 of 2
  _javascripts/page-loader.js
Labels: size/XS

#58657 CNV-24741: Fix DV/PVC terminology in storage modules
  _topic_maps/_topic_map.yml
  modules/virt-about-block-pvs.adoc
  modules/virt-about-datavolumes.adoc
  modules/virt-cdi-supported-operations-matrix.adoc
  modules/virt-cloning-pvc-of-vm-disk-into-new-datavolume.adoc
  modules/virt-creating-local-block-pv.adoc
  virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-block-storage-PVC.adoc
  virt/virtual_machines/cloning_vms/virt-cloning-vm-disk-into-new-block-storage-pvc.adoc
  virt/virtual_machines/virtual_disks/virt-uploading-local-disk-images-block.adoc
  virt/virtual_machines/virtual_disks/virt-uploading-local-disk-images-virtctl.adoc
Labels: peer-review-done, lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.13

#59382 OCPBUGS#5852 updating minimum storage requirements
  installing/installing_azure/installing-azure-account.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-account.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc
  modules/installation-azure-limits.adoc
  modules/optimizing-storage-azure.adoc
  scalability_and_performance/optimizing-storage.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59544 [enterprise-4.10] OCPBUGS#5852 updating minimum storage requirements cherrypick
  installing/installing_azure/installing-azure-account.adoc
  installing/installing_azure/installing-azure-user-infra.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-account.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc
  modules/installation-azure-limits.adoc
  modules/optimizing-storage-azure.adoc
  scalability_and_performance/optimizing-storage.adoc
Labels: size/M

#59490 ALBO: Note that the Operator is now generally available
  networking/aws_load_balancer_operator/aws-load-balancer-operator-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#59537 [enterprise-4.10] Updated installation docs: vSphere 3rd party CSI
  installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/installing-vsphere.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: size/S

#59492 OCP 4.12 RNs: Note that ALBO is GA in 4.12
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#59551 fixing image filename
  images/odc_helm_chart_devcatalog_new.png
Labels: size/XS, branch/enterprise-4.13

#59550 OSDOCS-5109-ALBO: updates RNs for GA of ALBO
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#58423 CNV-24129: Diagnostics tab documentation on virt troubleshooting assembly
  virt/support/virt-support-overview.adoc
  virt/support/virt-troubleshooting.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#53183 Update disable-language-specific-vulnerability-scanning.adoc
  modules/disable-language-specific-vulnerability-scanning.adoc
Labels: size/XS, lifecycle/rotten, RHACS

#59063 [RHACS] RHCOS Scanning for 4.0
  _topic_map.yml
  modules/common-attributes.adoc
  modules/identify-vulnerabilities-in-nodes.adoc
  modules/rhcos-analyse-detect.adoc
  modules/rhcos-environment-variables.adoc
  modules/rhcos-match-vulnerability.adoc
  operating/create-use-collections.adoc
  operating/examine-images-for-vulnerabilities.adoc
  operating/manage-vulnerabilities.adoc
  operating/manage-vulnerabilities/common-vuln-management-tasks.adoc
  operating/manage-vulnerabilities/field-trial.adoc
  operating/manage-vulnerabilities/images
  operating/manage-vulnerabilities/modules
  operating/manage-vulnerabilities/scan-rhcos-node-host.adoc
  operating/manage-vulnerabilities/technology-preview.adoc
  operating/manage-vulnerabilities/vulnerability-management.adoc
  release_notes/40-release-notes.adoc
  welcome/index.adoc
Labels: size/L, RHACS, rhacs-docs-4.0

#59251 OSDOCS-5817
  adding_service_cluster/rosa-available-services.adoc
  modules/rosa-rhoda.adoc
Labels: peer-review-done, size/XS, px-approved, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, SD-docs

#57587 OSDOCS-5324: Multi-arch on bare metal docs TP and cluster compatibility section
  modules/machine-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-pxe.adoc
  modules/multi-architecture-verifying-cluster-compatibility.adoc
  post_installation_configuration/multi-architecture-configuration.adoc
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, branch/enterprise-4.13

#57520 [OSDOCS-5261] TP - External load balancers in place of default for ShiftStack IPI
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  installing/installing_openstack/installing-openstack-installer-kuryr.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-load-balancing-user-infra.adoc
  modules/installation-osp-external-lb-config.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#57993 OCPBUGS-10695: Forbid IPv4-mapped IPv6 addresses in dual-stack
  networking/ovn_kubernetes_network_provider/converting-to-dual-stack.adoc
Labels: peer-review-done, size/XS, bugzilla/valid-bug, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-important, jira/valid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#57371 RHDEVDOCS-4430 - Loki Log Based Alerting
  logging/v5_6/logging-5-6-configuration.adoc
  logging/v5_7/logging-5-7-configuration.adoc
  modules/logging-loki-alerts.adoc
  snippets/logging-alertingrule-app-callouts-snip.adoc
  snippets/logging-alertingrule-inf-callouts-snip.adoc
  snippets/logging-alertingruleCR-callouts-snip.adoc
  snippets/logging-alertingruleCR-snip.adoc
Labels: size/L

#59331 CMA edits per Zbynek Roubalik
  modules/nodes-pods-autoscaling-custom-about.adoc
  modules/nodes-pods-autoscaling-custom-adding.adoc
  modules/nodes-pods-autoscaling-custom-creating-job.adoc
  modules/nodes-pods-autoscaling-custom-creating-workload.adoc
  modules/nodes-pods-autoscaling-custom-pausing.adoc
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59341 OSDOCS-5544: documenting signature digest extraction
  modules/update-restricted-image-digests.adoc
  modules/update-restricted.adoc
  updating/updating-restricted-network-cluster/restricted-network-update.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#58614 OSDOCS-5502 adding link to VMware cloud provider program doc 4.10 and 4.11
  modules/installation-vsphere-infrastructure.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.11

#59588 [enterprise-4.10] OSDOCS-5502 adding link to VMware cloud provider program doc
  modules/installation-vsphere-infrastructure.adoc
Labels: size/S

#59568 Swaps order of assembly content to render product-registry
  registry/index.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59559 [RHACS] Updated arch modules for node scanning info
  modules/acs-architecture-interaction-between-services.adoc
  modules/acs-central-services-overview.adoc
Labels: peer-review-done, RHACS, rhacs-docs-4.0

#59596 [RHACS] ROX16927 Content re-structuring 'Understanding authentication providers' section
  operating/manage-user-access/understanding-authentication-providers.adoc
Labels: peer-review-done, lgtm, size/S, RHACS, rhacs-docs-3.74, rhacs-docs-4.0

#58230 CMA add TP note for the Kafka scaler
  modules/nodes-pods-autoscaling-custom-trigger.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59567 CNV-5774: Add links to tuning and scaling guide
  virt/about-virt.adoc
  virt/live_migration/virt-live-migration.adoc
  virt/virt-getting-started.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#59598 [SRVCOM-2444] Remove IBM P/Z restriction
  serverless/install/serverless-kafka-admin.adoc
Labels: peer-review-done, size/XS, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58755 RHDEVDOCS-4967-update-nodeselector-example-for-moving-monitoring-components
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-using-node-selectors-to-move-monitoring-components.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, lgtm, size/L, dev-tools, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, sme-review-done

#59615 [enterprise-4.10] RHDEVDOCS-4967-update-nodeselector-example-for-moving-monitoring-comp…
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-using-node-selectors-to-move-monitoring-components.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: size/L

#58198 TELCODOCS-903: Graceful node shutdown
  _topic_maps/_topic_map.yml
  modules/nodes-nodes-cluster-timeout-graceful-shutdown.adoc
  modules/nodes-nodes-configuring-graceful-shutdown.adoc
  nodes/nodes/nodes-nodes-graceful-shutdown.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#59617 [enterprise-4.12] RHDEVDOCS-4967-update-nodeselector-example-for-moving-monitoring-comp…
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-using-node-selectors-to-move-monitoring-components.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: size/L

#59616 [enterprise-4.11] RHDEVDOCS-4967-update-nodeselector-example-for-moving-monitoring-comp…
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-using-node-selectors-to-move-monitoring-components.adoc
  monitoring/configuring-the-monitoring-stack.adoc
Labels: size/L

#59536 OSDOCS-5637: adds monitoring and networking bug batch to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.13

#59273 OSDOCS-5826: MicroShift networking release note
  microshift_release_notes/microshift-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.13

#59614 OSDOCS-5637-console: adds last 2 console bugs to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#53695 OSDOCS-4491 / OSDOCS-5258: Adding local zones documentation
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-nodes-machine-pools-local-zones.adoc
  modules/rosa-sdpolicy-am-local-zones.adoc
  modules/rosa-sdpolicy-am-regions-az.adoc
  modules/rosa-sdpolicy-am-sla.adoc
  modules/rosa-sdpolicy-am-support.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-service-definition.adoc
  rosa_cli/rosa-manage-objects-cli.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-configuring.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#59602 Updated preview receiver for PR Previews
  autopreview.sh
Labels: size/XS

#59535 Update OCG YAML ellipsis guidelines and examples
  contributing_to_docs/doc_guidelines.adoc
Labels: size/S

#58767 Add Central DB to Central services components
  modules/acs-central-services-overview.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.0

#56441 OCPBUGS#7489: Webhook OpenShift timeout cannot be increased above 13s
  modules/admission-webhooks-about.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#58668 ROX-16495: Installation instructions for PostgreSQL tech preview
  installing/installing_ocp/install-central-ocp.adoc
  modules/install-central-operator-tech-preview.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference

#59642 [RHACS] Fix 4.0 roxctl upgrade
  modules/generate-central-database-provisioning-bundle.adoc
Labels: size/XS, RHACS, rhacs-docs-4.0

#59114 [RHACS] Add the steps for tech preview upgrade for RHACS 4.0
  modules/operator-upgrade-modify-central-custom-resource-tech-preview.adoc
  upgrading/upgrade-operator.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.0

#58873 OCPBUGS#9937: Document how to expose router metrics
  modules/nw-exposing-router-metrics.adoc
  networking/ingress-operator.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#59636 OCPBUGS#6828: Correct the supported RHEL versions
  modules/rhel-compute-updating.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#59560 For RHACS docs: Added a rewrite rule for Managing vulnerabilities section
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#59632 BZ2193267: 4.13 single-stack IPv6 not supported
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.13

#59630 BZ2193267: 4.12 single-stack IPv6 not supported
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.12

#59008 Document on how to use Argo CD for managing OpenShift cluster configurations across multiple clusters
  cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-installing-olm-operators-using-gitops.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
Labels: size/L

#59633 BZ2193267: Preparing cluster IPv6
  virt/install/preparing-cluster-for-virt.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59629 BZ2193267: 4.11 single-stack IPv6 not supported
  virt/virt-4-11-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11

#59628 Update YAML ellipses
  modules/virt-about-runstrategies-vms.adoc
  modules/virt-adding-kernel-arguments-enable-iommu.adoc
  modules/virt-adding-vtpm-to-vm.adoc
  modules/virt-attaching-vm-secondary-network-cli.adoc
  modules/virt-attaching-vm-to-sriov-network.adoc
  modules/virt-booting-vms-uefi-mode.adoc
  modules/virt-cloning-local-volume-to-another-node.adoc
  modules/virt-configuring-huge-pages-for-vms.adoc
  modules/virt-configuring-ip-for-new-vm-cloud-init.adoc
  modules/virt-configuring-masquerade-mode-dual-stack.adoc
  modules/virt-configuring-secondary-dns-server.adoc
  modules/virt-configuring-secondary-network-vm-live-migration.adoc
  modules/virt-configuring-storage-class-bootsource-update.adoc
  modules/virt-configuring-vm-live-migration-cli.adoc
  modules/virt-configuring-workload-update-methods.adoc
  modules/virt-connecting-vm-secondarynw-using-fqdn.adoc
  modules/virt-creating-and-exposing-mediated-devices.adoc
  modules/virt-customizing-storage-profile.adoc
  modules/virt-define-tcp-readiness-probe.adoc
  modules/virt-defining-watchdog-device-vm.adoc
  modules/virt-deploying-tto.adoc
  modules/virt-disable-individual-bootsource-update.adoc
  modules/virt-enlarging-vm-disk.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-example-nmstate-multiple-interfaces.adoc
  modules/virt-example-vm-node-placement-node-affinity.adoc
  modules/virt-example-vm-node-placement-node-selector.adoc
  modules/virt-example-vm-node-placement-pod-affinity.adoc
  modules/virt-example-vm-node-placement-tolerations.adoc
  modules/virt-exposing-pci-device-in-cluster-cli.adoc
  modules/virt-how-virtual-gpus-assigned-nodes.adoc
  modules/virt-monitoring-vm-migration-cli.adoc
  modules/virt-overriding-default-fs-overhead-value.adoc
  modules/virt-removing-pci-device-from-cluster-cli.adoc
  modules/virt-runbook-outdatedvirtualmachineinstanceworkloads.adoc
  modules/virt-troubleshooting-incorrect-policy-config.adoc
  modules/virt-verify-status-bootsource-update.adoc
  modules/virt-viewing-network-state-of-node.adoc
  modules/virt-viewing-vmi-ip-cli.adoc
  modules/virt-virtual-gpus-config-overview.adoc
Labels: peer-review-done, size/L, CNV, branch/enterprise-4.13

#59651 BZ2193267: 4.10 single stack IPv6 not supported
  virt/virt-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.10

#59554 Adding aesgcm info back in and mentioning migrating between types
  modules/enabling-etcd-encryption.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.13

#59464 OSDOCS-5275-link-redo:Updated vSphere release notes by adding links t…
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#59669 typo fix 4.13
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#59401 OSDOCS-4244: The cluster nodes accessed by SSH are not tainting.
  modules/gathering-application-diagnostic-data.adoc
  modules/gathering-crio-logs.adoc
  modules/gathering-operator-logs.adoc
  modules/investigating-etcd-installation-issues.adoc
  modules/investigating-kubelet-api-installation-issues.adoc
  modules/investigating-master-node-installation-issues.adoc
  modules/investigating-worker-node-installation-issues.adoc
  modules/querying-cluster-node-journal-logs.adoc
  modules/querying-kubelet-status-on-a-node.adoc
  modules/querying-operator-pod-status.adoc
  modules/support-collecting-network-trace.adoc
  modules/support-generating-a-sosreport-archive.adoc
  modules/support-providing-diagnostic-data-to-red-hat.adoc
  modules/verifying-crio-status.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#59670 [enterprise-4.9] Document on how to use Argo CD for managing OpenShift cluster configu…
  cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  modules/gitops-additional-permissions-for-cluster-config.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-inbuilt-permissions-for-cluster-config.adoc
  modules/gitops-installing-olm-operators-using-gitops.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
Labels: size/L

#59343 CMA Adding 2.10 Release Notes
  modules/nodes-pods-autoscaling-custom-rn-210.adoc
  modules/nodes-pods-autoscaling-custom-rn.adoc
  nodes/pods/nodes-pods-autoscaling-custom.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#59456 OSDOCS-5637-bugbatch2: Documented another batch of 4.13 z-stream notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.13

#59236 OCPBUGS#8058: Rm opm index prune from disconnected install
  installing/disconnected_install/installing-mirroring-installation-images.adoc
  modules/connected-to-disconnected-mirror-images.adoc
  modules/olm-mirroring-catalog-airgapped.adoc
  modules/olm-mirroring-catalog-colocated.adoc
  operators/admin/olm-restricted-networks.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#58640 OSDOCS-5479: Documented the Welcome page for the 4.13 release notes do…
  welcome/index.adoc
Labels: peer-review-needed, size/L, jira/valid-reference

#59241 OCPBUG8885: Added 'available' definition in 'understanding how to use PDBs' section.
  modules/nodes-pods-pod-disruption-about.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#59683 OSDOCS-5109: edits to RNs for feedback
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#59696 Re-enable non tech preview upgrade instructions
  upgrading/upgrade-operator.adoc
Labels: peer-review-done, lgtm, size/XS

#59704 SRVCOM-2432 add serverless distro
  _distro_map.yml
Labels: size/S, serverless

#59603 turn-off-rn-vale-rule: Updated the vale.ini vile to turn off a rule
  .vale.ini
Labels: size/XS, branch/enterprise-4.1, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#56655 OSDOCS-5223: vSphere encryption
  modules/persistent-storage-csi-vsphere-encryption-datastore-url.adoc
  modules/persistent-storage-csi-vsphere-encryption-tag-based.adoc
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference, branch/enterprise-4.13

#58584 CNV-21826: Configuring VM for DPDK
  modules/virt-configuring-cluster-dpdk.adoc
  modules/virt-configuring-vm-dpdk.adoc
  modules/virt-configuring-vm-project-dpdk.adoc
  virt/virtual_machines/vm_networking/virt-attaching-vm-to-sriov-network.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.13

#58855 OSDOCS-5735: Added note about OCI feature not supporting pruning
  modules/oc-mirror-oci-format.adoc
  modules/oc-mirror-updating-registry-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference

#58933 OSDOCS-4906: Adding oc-mirror OCI GA to RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.13

#58962 OCPBUGS#11905: cert-manager Operator is GA in 4.12
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress

#47603 OSDOCS-3788:CSI inline ephemeral vols TP-> GA
  modules/ephemeral-storage-csi-inline-overview-admin-plugin.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/ephemeral-storage-csi-inline.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#58552 OSDOCS-4906: Updating oc-mirror docs for OCI FBC GA
  installing/disconnected_install/installing-mirroring-disconnected.adoc
  modules/oc-mirror-command-reference.adoc
  modules/oc-mirror-creating-image-set-config.adoc
  modules/oc-mirror-image-set-config-examples.adoc
  modules/oc-mirror-imageset-config-params.adoc
  modules/oc-mirror-oci-format.adoc
  modules/oc-mirror-support.adoc
  modules/preparing-an-inital-cluster-deployment-for-mce-disconnected.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.13

#59595 OSDOCS-5637-bugbatch3: Documented another batch of 4.13 z-stream notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.13

#59675 OSDOCS#4858: Updated AWS AMI image IDs
  modules/installation-aws-user-infra-rhcos-ami.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.13

#59230 OCPBUGS-9238: moving must-gather note
  modules/installation-mirror-repository.adoc
  modules/support-gather-data.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11, jira/severity-low, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#59181 OCPBUGS#5194: Use `opm generate` for FBC Dockerfile gen
  cli_reference/opm/cli-opm-ref.adoc
  modules/olm-creating-fb-catalog-image.adoc
  modules/opm-cli-ref-generate.adoc
  modules/opm-cli-ref-migrate.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
Labels: size/L, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13

#54742 OSDOCS-4816: Added certificate renewal instructions
  applications/deployments/osd-config-custom-domains-applications.adoc
  modules/osd-applications-renew-custom-domains.adoc
Labels: peer-review-done, size/M, SD-docs

#59493 TELCODOCS-1306: D/S: MGMT-7878 Expose the ability of creating partitions on nodes
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-configuring-storage-on-nodes.adoc
Labels: lgtm, size/M, telco, jira/valid-reference, branch/enterprise-4.13

#59621 OSDOCS-5995: Adding Network Observability to the NW Operators Overview
  networking/network_observability/network-observability-overview.adoc
  networking/networking-operators-overview.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#59586 OCP 4.10 Netobserv updates RN
  release_notes/ocp-4-10-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.10

#59029 OCP 4.13/NetObserv 1.1, 1.2 release note
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.13

#59414 OCP 4.12/NetObserv updates release note
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12

#59178 [OSDOCS-3790]: Add note about ensuring node is completely shut down.
  modules/persistent-storage-csi-vol-detach-non-graceful-shutdown-procedure.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.13

#59485 [OSDOCS-5697] added decprecation to ROSA what's new
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, SD-docs, sme-review-needed

#59606 OSDOCS-5392 Fixing vsphere 6.7 references
  modules/installation-vsphere-infrastructure.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.10, branch/enterprise-4.11

#59219 Updates misleading example on ONVK additional network config
  modules/configuration-ovnk-network-plugin-json-object.adoc
  modules/configuring-layer-two-switched-topology.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.13

#59755 OSDOCS-5392 Fixing vsphere 6.7 references
  modules/installation-vsphere-infrastructure.adoc
Labels: size/S

#59744 CNV-21919: RHEL 9 release note
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.13

#59180 CNV-21610: 4.13 updates re: security/privileges
  _topic_maps/_topic_map.yml
  modules/virt-about-workload-security.adoc
  modules/virt-additional-scc-for-kubevirt-controller.adoc
  modules/virt-extended-selinux-policies-for-virt-launcher.adoc
  virt/virt-additional-security-privileges-controller-and-launcher.adoc
  virt/virt-security-policies.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.13

#59769 CNV-15240: follow-up PR to comment out module
  virt/upgrading-virt.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.13

#59420 CNV-22038: VM definition links in VME manifest
  modules/virt-accessing-exported-vm-manifests.adoc
  virt/virtual_machines/virt-exporting-vms.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.13

#59751 OSDOCS-5537-batch4: bug batch for RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#59764 [enterprise-4.11] Use `opm generate` for FBC Dockerfile gen
  cli_reference/opm/cli-opm-ref.adoc
  modules/olm-creating-fb-catalog-image.adoc
  modules/opm-cli-ref-generate.adoc
  modules/opm-cli-ref-migrate.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
Labels: size/L

#59763 OSDOCS-5995: Adding Network Observability to the NW Operators Overview
  networking/network_observability/network-observability-overview.adoc
  networking/networking-operators-overview.adoc
Labels: size/XS, jira/valid-reference

#59766 OSDOCS-5995: Adding Network Observability to the NW Operators Overview
  networking/network_observability/network-observability-overview.adoc
  networking/networking-operators-overview.adoc
Labels: size/XS, jira/valid-reference

#59721 BZ2196526: Run pods and VMs together
  modules/virt-what-you-can-do-with-virt.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.13

#59140 [RHACS] ROX15257 ACSCS service description documentation
  _topic_map.yml
  cloud_service/attributes
  cloud_service/images
  cloud_service/modules
  cloud_service/rhacs-cloud-service-service-description.adoc
  cloud_service/snippets
  modules/availability.adoc
  modules/billing.adoc
  modules/introduction-to-rhacs.adoc
  modules/metrics-and-logging.adoc
  modules/pricing.adoc
  modules/scalability-and-service-level.adoc
  modules/service-level-agreement.adoc
  modules/timelines.adoc
  modules/updates-and-upgrades.adoc
Labels: peer-review-done, size/L, RHACS

#55014 OSDOCS-3780&3781&3782:BYOK encryption
  modules/persistent-storage-byok.adoc
  storage/container_storage_interface/persistent-storage-csi-azure.adoc
  storage/container_storage_interface/persistent-storage-csi-ebs.adoc
  storage/container_storage_interface/persistent-storage-csi-gcp-pd.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#58111 OADP 1442 - resourceTimeouts
  modules/oadp-installing-dpa.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, OADP, branch/enterprise-4.13

#57986 TELCODOCS-329: MachineHealthCheck: Implement metal3 remediation using new external API
  modules/mgmt-power-remediation-baremetal-about.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#59770 [enterprise-4.12] Cherry-pick of #54742: renewing certificate
  applications/deployments/osd-config-custom-domains-applications.adoc
  modules/osd-applications-renew-custom-domains.adoc
Labels: size/M, branch/enterprise-4.12

#58197 TELCODOCS-903: release note
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#59706 [WIP][DOC] PR for SRVCOM-2443: Remove references to OpenShift Streams for Apache Kafka
  modules/serverless-kafka-sasl-source.adoc
  modules/serverless-kafka-sink-security-config.adoc
Labels: lgtm, size/XS, serverless, branch/enterprise-4.10, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#57799 TELCODOCS-1184: Configuring vSphere Connection Details
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/installing-vsphere-post-installation-configuration.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/configuring-vsphere-connection-settings.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#59731 CNV-18330: RN DPDK checkup and configuring VM for DPDK
  virt/virt-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.13

#58993 CNV- 20433: Loki logging queries
  modules/virt-configuring-pod-log-verbosity.adoc
  modules/virt-loki-log-queries.adoc
  modules/virt-viewing-logs-cli.adoc
  modules/virt-viewing-logs-loki.adoc
  virt/support/virt-troubleshooting.adoc
Labels: peer-review-done, size/L, CNV, branch/enterprise-4.13

#59819 SRVCOM-2443 Remove streams for Kafka - sync to standalone docs
  modules/serverless-kafka-sasl-source.adoc
  modules/serverless-kafka-sink-security-config.adoc
Labels: size/XS
