Repository openshift/openshift-docs, pull requests merged in 2024-12, with the labels that each got.

#85647 [RHACS][Docs][4.6 and later] ROX-27210: Fixing format issue
  operating/manage-vulnerabilities/common-vuln-management-tasks.adoc
Labels: size/XS, RHACS, jira/valid-reference, rhacs-docs-4.6

#85564 [RHACS] remove central.persistence values from docs, removed central attached…
  modules/central-configuration-options-operator.adoc
  modules/central-services-public-config.adoc
  modules/install-central-operator.adoc
  modules/remove-central-attached-pv-helm.adoc
  modules/remove-central-attached-pv-operator.adoc
  modules/remove-central-attached-pv-overview.adoc
  modules/remove-central-attached-pv-roxctl.adoc
  modules/roxctl-central-generate-k8s-hostpath.adoc
  modules/roxctl-central-generate-k8s-pvc.adoc
  modules/roxctl-central-generate-openshift-hostpath.adoc
  modules/roxctl-central-generate-openshift-pvc.adoc
  modules/using-the-interactive-installer.adoc
  upgrading/upgrade-helm.adoc
  upgrading/upgrade-operator.adoc
  upgrading/upgrade-roxctl.adoc
Labels: peer-review-done, size/L, RHACS, merge-review-in-progress, rhacs-docs-4.6

#84710 OCPBUGS-44416: Directory name fix in installation workflow for IBM cloud bare metal (classic)
  modules/install-ibm-cloud-classic-configuring-the-install-config-file.adoc
Labels: peer-review-done, size/XS, ok-to-test, qe-approved, jira/valid-bug, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85177 OSDOCS#12715: Release notes for descheduler 5.1.1
  nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#85173 OSDOCS#12500: Release notes for descheduler 5.0.2
  nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.15, branch/enterprise-4.16

#85637 RHDEVDOCS 6279 fix formatting in Results configuration for LokiStack
  modules/op-results-storage.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#85308 OSDOCS-12743: added product compliance link to docs
  security/compliance_operator/co-overview.adoc
  security/compliance_operator/co-scans/compliance-operator-supported-profiles.adoc
  security/compliance_operator/co-support.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83655 [OCPBUGS-41344] Update minor version of RHEL 8 for worker node
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, needs-ok-to-test, branch/enterprise-4.13

#85683 [enterprise-4.12] OSDOCS-12743: added product compliance link to docs
  security/compliance_operator/co-overview.adoc
  security/compliance_operator/co-scans/compliance-operator-supported-profiles.adoc
  security/compliance_operator/co-support.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/XS, jira/valid-reference

#85684 [enterprise-4.14] OSDOCS-12743: added product compliance link to docs
  security/compliance_operator/co-overview.adoc
  security/compliance_operator/co-scans/compliance-operator-supported-profiles.adoc
  security/compliance_operator/co-support.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/XS, jira/valid-reference

#85490 [OSDOCS-12700]: Replacing older HCP update content with newer content
  _topic_maps/_topic_map.yml
  modules/configuring-node-pools-for-hcp.adoc
  modules/hcp-update-node-pools.adoc
  modules/hcp-update-ocp-hc.adoc
  modules/hcp-updates-hosted-cluster.adoc
  modules/hcp-updates-node-pools.adoc
  updating/index.adoc
  updating/updating_a_cluster/updating-hosted-control-planes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#85520 HCP updating reorg redirect
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#85357 OLS-1217: Update distro map for OLS GA release
  _distro_map.yml
Labels: size/XS, jira/valid-reference

#85690 [enterprise-4.13] OSDOCS-12743: added product compliance link to docs
  security/compliance_operator/co-overview.adoc
  security/compliance_operator/co-scans/compliance-operator-supported-profiles.adoc
  security/compliance_operator/co-support.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: size/XS, jira/valid-reference

#85696 adjusting banner for OSD and ROSA
  _templates/_page_openshift.html.erb
Labels: size/S

#85117 OSSM 3.0.0TP1: OSSM-8380 Revision Based label set is missing in the Distributed Tracing doc
  modules/ossm-config-otel.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#84635 OLS-1198: Remove drop down used to ask a question
  modules/ols-initiating-chat-using-actions-list.adoc
  modules/ols-initiating-chat-using-node-options-icon.adoc
  operate/ols-using-openshift-lightspeed.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84967 HCCDOC3138:Add Insights Runtime Extractor TP feature to Insights Operator release notes
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.18

#85706 [RHACS][Docs][4.6 and later] ROX-27229: Updating the release date in the 4.6 release notes
  release_notes/46-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.6

#85537 RHDEVDOCS-6183: Content creation for EnableRolloutsUI field
  argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.adoc
  modules/gitops-enabling-argo-rollouts-ui-on-an-argo-cd-instance.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, gitops

#85273 TELCODOCS-2113 - PTP events subscription status codes
  modules/cnf-fast-event-notifications-api-reference-v2.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85702 OCPBUGS#44334: Fixing a hyperlink related to policy generator
  edge_computing/policygenerator_for_ztp/ztp-advanced-policygenerator-config.adoc
  snippets/pgt-deprecation-notice.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85715 Update date on 4.6 RNs
  release_notes/46-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, RHACS, rhacs-docs-4.6

#84968 networking-operators-redirects: Created redirects for AWS Operator docs
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85655 Updates a few IR commands
  modules/registry-configuring-registry-storage-rhodf-cephrgw.adoc
  modules/registry-exposing-default-registry-manually.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85311 OADP-5261: Update the OADP introduction to include entire cluster backup unsupported
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, OADP, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85242 [OSDOCS-11894] Explain why and in what context are the required GCP APIs used by OSD
  modules/ccs-gcp-customer-procedure.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#85653 OSDOCS-12494: adds 4.17.7 relnote MicroShift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#85685 Update docs for ACS 4.6
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
  _templates/_page_openshift.html.erb
  index-commercial.html
Labels: peer-review-done, size/S

#85628 OSDOCS-12800: Documented the 4.17.7 z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.17

#85356 OSSM-8333: Set up gateways in Pantheon
  gateways/docinfo.xml
Labels: peer-review-done, lgtm, size/S, service-mesh, merge-review-in-progress, jira/valid-reference

#85538 CNV-51635: move tekton-tasks-operator from deprecated to removed feaures in RN. Also tracks CNV-41244
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17

#85264 OADP-5010 delete backups
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-deleting-backups-doc.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-deleting-backups.adoc
  modules/oadp-about-kopia-repo-maintenance.adoc
  modules/oadp-deleting-backup-repository.adoc
  modules/oadp-deleting-backups-using-oc.adoc
  modules/oadp-deleting-backups-using-velero.adoc
  modules/oadp-deleting-backups.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85384 Create folder for new section
  _topic_maps/_topic_map.yml
  work_with_shared_resources/_attributes
  work_with_shared_resources/docinfo.xml
  work_with_shared_resources/images
  work_with_shared_resources/modules
  work_with_shared_resources/snippets
  work_with_shared_resources/using-shared-resource-csi-driver.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress

#85760 Added d.r.c banner on main page
  index-commercial.html
Labels: size/XS

#85777 Formatting/build fixes for CI/CD overview and Serverless
  _topic_maps/_topic_map.yml
  serverless/about/about-serverless.adoc
Labels: size/XS

#85756 OSDOCS-12821: Added the updated diagrams to the image directory of our repo
  images/522-shared-vpc-overview.png
  images/522-shared-vpc-step-1.png
  images/522-shared-vpc-step-2.png
  images/522-shared-vpc-step-3.png
  images/522-shared-vpc-step-4.png
Labels: size/XS, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#85733 [OSDOCS-12826]: Adding link to HCP-specific ACM doc from OCP docs
  hosted_control_planes/index.adoc
  modules/hcp-acm-discover.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#83470 OCPBUGS#28655: Removing core API group from example
  modules/ldap-auto-syncing.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85513 OSDOCS-12780: Update incorrect GPU values in CAS example spec
  modules/cluster-autoscaler-cr.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84682 OSSM-4835 [Doc] Capture Differences between OSSM 2.x and OSSM 3.0
  _topic_maps/_topic_map.yml
  migrating/_attributes
  migrating/docinfo.xml
  migrating/images
  migrating/modules
  migrating/ossm-migrating-read-me-assembly.adoc
  migrating/snippets
  modules/ossm-migrating-2-and-3-differences.adoc
  modules/ossm-migrating-read-me-explicitly-create-openshift-routes.adoc
  modules/ossm-migrating-read-me-independently-managed-gateways.adoc
  modules/ossm-migrating-read-me-introducing-canary-updates.adoc
  modules/ossm-migrating-read-me-kubernetes-network-policy-management.adoc
  modules/ossm-migrating-read-me-new-operator.adoc
  modules/ossm-migrating-read-me-new-resources.adoc
  modules/ossm-migrating-read-me-observability-integrations.adoc
  modules/ossm-migrating-read-me-scoping-discovery-selectors.adoc
  modules/ossm-migrating-read-me-sidecar-injection-considerations.adoc
  modules/ossm-migrating-read-me-support-for-istioctl.adoc
  modules/ossm-migrating-read-me-support-for-multiple-control-planes.adoc
  modules/ossm-migrating-read-me-supported-multi-cluster-topologies.adoc
  modules/ossm-migrating-read-me-tls-configuration-change.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress, merge-review-needed

#85773 Fix occurrences of 'polices' used in place of 'policies'
  _topic_maps/_topic_map.yml
  modules/logging-release-notes-5-8-0.adoc
  modules/nw-secondary-ext-gw-object.adoc
  modules/nw-sriov-topology-manager.adoc
  modules/rosa-aws-scp.adoc
  modules/rosa-sts-account-wide-roles-and-policies.adoc
  modules/ztp-preparing-the-ztp-git-repository.adoc
  modules/ztp-the-policygentemplate.adoc
  modules/ztp-updating-gitops-ztp.adoc
  snippets/pgt-deprecation-notice.adoc
  snippets/pgt-ztp-adding-new-content-to-gitops-ztp.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#85779 OCPBUGS-38864: Update link to Red Hat Best Practices for Kubernetes in Telco Core RDS
  modules/telco-core-ref-application-workloads.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#85804 OLS-1280: Update main distro map for Lightspeed
  _distro_map.yml
Labels: size/XS, jira/valid-reference

#85780 OCPBUGS-38864: Update link to Red Hat Best Practices for Kubernetes in Telco Core RDS
  modules/telco-core-ref-application-workloads.adoc
Labels: size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15

#85781 OCPBUGS-38864: Update link to Red Hat Best Practices for Kubernetes in Telco Core RDS
  modules/telco-core-ref-application-workloads.adoc
Labels: size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#85519 OSDOCS-12677: Edit ROSA Autoscaling Docs
  modules/rosa-cluster-autoscaler-cli-after.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#85802 [enterprise-4.15] OSDOCS-12780: Update incorrect GPU values in CAS example spec
  modules/cluster-autoscaler-cr.adoc
Labels: size/S, jira/valid-reference

#85803 [RHACS] [Docs] [main] ROX-27247: Remove unsupported banner for 4.4
  _templates/_page_openshift.html.erb
Labels: peer-review-in-progress, size/XS, RHACS, jira/valid-reference

#85758 Fix typo in Understanding Machine Config Daemon metrics
  modules/machine-config-daemon-metrics-understanding.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85699 Deploying a secondary scheduler has bad link
  modules/nodes-secondary-scheduler-configuring-console.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85823 OSSM-8514 Troubleshooting Observbaility
  observability/docinfo.xml
Labels: peer-review-done, size/XS

#85841 OSSM-8516 +1 to leveloffsets
  observability/kiali/ossm-kiali-assembly.adoc
  observability/traces/ossm-distr-tracing-assembly.adoc
Labels: peer-review-done, size/S

#85621 OSDOCS-12799: Documented the 4.14.42 z-stream release notes
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#85774 Fixed broken links in API docs, added file genration script
  rest_api/AuthService/_v1_auth_m2m_config.id_put.adoc
  rest_api/CloudSourcesService/_v1_cloud-sources_cloudSource.id_put.adoc
  rest_api/ExternalBackupService/_v1_externalbackups_externalBackup.id_patch.adoc
  rest_api/ImageIntegrationService/_v1_imageintegrations_config.id_patch.adoc
  rest_api/NotifierService/_v1_notifiers_notifier.id_patch.adoc
  scripts/process-apidocs-for-pantheon.sh
Labels: rhacs-docs-4.6

#85052 OSDOCS-11935: adds bootc updates to greenboot checks
  modules/microshift-config-parameters-table.adoc
  modules/microshift-greenboot-testing-workload-script.adoc
Labels: peer-review-done, size/M, QE Required, qe-approved, jira/valid-reference, branch/enterprise-4.18

#85757 OSDOCS11998 Docs for OCPSTRAT-1656 Updated boot images: Phase 3 (AWS GA)
  machine_configuration/mco-update-boot-images.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#85119 TELCODOCS-1931 Describe source IP NAT for MetalLB return traffic
  modules/nw-metallb-when-metallb.adoc
Labels: peer-review-done, lgtm, size/XS, telco, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85844 OSSM-8519 docinfo.xml
  migrating/docinfo.xml
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#85540 CNV-51136: Updated yaml in 'Creating a Linux bridge NAD' to reference standard Linux NNCP bridge name
  modules/virt-creating-linux-bridge-nad-cli.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85754 ROX-25773: Fix error in declarative config yaml
  modules/declarative-configuration-examples.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6

#85629 OCPBUGS-31413: Remove mention of PtpConfigSlaveCvl.yaml from docs
  snippets/pg-ztp-configuring-ptp-fast-events-linuxptp.adoc
  snippets/pgt-ztp-configuring-ptp-fast-events-linuxptp.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85630 [enterprise-4.15] OCPBUGS-31413: Remove mention of PtpConfigSlaveCvl.yaml from docs
  modules/ztp-configuring-ptp-fast-events-amqp.adoc
  modules/ztp-configuring-ptp-fast-events.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15

#85631 [enterprise-4.14] OCPBUGS-31413: Remove mention of PtpConfigSlaveCvl.yaml from docs
  modules/ztp-configuring-ptp-fast-events-amqp.adoc
  modules/ztp-configuring-ptp-fast-events.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#85682 OSDOCS-12797: 4.12.70 z-stream RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference

#85851 Add option to include API book in Prow smoke test and makeBuild
  makeBuild.py
  scripts/prow-smoke-test.sh
Labels: size/S

#83242 RHDEVDOCS-6197: Content creation for cluster-scoped installation
  _topic_maps/_topic_map.yml
  argo_rollouts/using-cluster-scoped-rollouts-instance-to-manage-rollouts-resources.adoc
  modules/gitops-configuring-a-cluster-scoped-argo-rollouts-instance-to-manage-rollouts-resources.adoc
  modules/gitops-creating-rolloutmanager-custom-resource.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, gitops

#85751 OSDOCS-12585 Updating Kubernetes version in OCP 4.18 RNs.
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#85881 OSSM-8523 Trying to get matching titles for Pantheon to be happy
  migrating/docinfo.xml
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#85507 TELCODOCS-1956: Move NVIDIA GPU architecture content to Hardware Acce…
  _topic_maps/_topic_map.yml
  hardware_accelerators/about-hardware-accelerators.adoc
  hardware_accelerators/nvidia-gpu-architecture.adoc
  images/OCP_HW_Accelerators_5.png
  modules/nvidia-gpu-architecture.adoc
  modules/nvidia-gpu-bare-metal.adoc
  modules/nvidia-gpu-csps.adoc
  modules/nvidia-gpu-cuda-mps.adoc
  modules/nvidia-gpu-cuda-streams.adoc
  modules/nvidia-gpu-enablement.adoc
  modules/nvidia-gpu-features.adoc
  modules/nvidia-gpu-kvm.adoc
  modules/nvidia-gpu-mig-gpu.adoc
  modules/nvidia-gpu-prerequisites.adoc
  modules/nvidia-gpu-red-hat-device-edge.adoc
  modules/nvidia-gpu-sharing-methods.adoc
  modules/nvidia-gpu-time-slicing.adoc
  modules/nvidia-gpu-virtualization-with-gpu.adoc
  modules/nvidia-gpu-virtualization.adoc
  modules/nvidia-gpu-vsphere.adoc
Labels: peer-review-done, size/L, telco, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#81148 Don't catch commented includes in the build_for_portal script
  build_for_portal.py
Labels: size/XS

#85648 OSDOCS-12806: Corrected the toolbox image for 4.16+
  modules/support-installing-packages-to-a-toolbox-container.adoc
  modules/support-starting-an-alternative-image-with-toolbox.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85448 fix: opentelemetry collector config templates
  observability/otel/otel-collector/otel-collector-processors.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83771 Clean out single-line xrefs that are commented in build_for_portal
  build_for_portal.py
Labels: size/XS

#85809 OCPBUGS-36835 - Adding missing NMState Operator CRs
  modules/telco-core-crs-networking.adoc
  modules/telco-core-crs-other.adoc
  modules/telco-core-crs-resource-tuning.adoc
  modules/telco-core-crs-scheduling.adoc
  modules/telco-core-crs-storage.adoc
  modules/telco-core-yaml-ref-networking.adoc
  modules/telco-core-yaml-ref-other.adoc
  modules/telco-core-yaml-ref-resource-tuning.adoc
  modules/telco-core-yaml-ref-scheduling.adoc
  modules/telco-core-yaml-ref-storage.adoc
  snippets/telco-core_NMState.yaml
  snippets/telco-core_NMStateNS.yaml
  snippets/telco-core_NMStateOperGroup.yaml
  snippets/telco-core_NMStateSubscription.yaml
Labels: size/M, branch/enterprise-4.15

#85885 Adds ipsec note to 414 and earlier
  networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#85766 OBSDOCS-1549: Create the topic maps with replacement assemblies while…
  _topic_maps/_topic_map.yml
  observability/monitoring/about-ocp-monitoring/_attributes
  observability/monitoring/about-ocp-monitoring/about-ocp-monitoring.adoc
  observability/monitoring/about-ocp-monitoring/images
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/about-ocp-monitoring/modules
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/about-ocp-monitoring/snippets
  observability/monitoring/accessing-metrics/_attributes
  observability/monitoring/accessing-metrics/accessing-metrics-as-a-developer.adoc
  observability/monitoring/accessing-metrics/accessing-metrics-as-an-administrator.adoc
  observability/monitoring/accessing-metrics/accessing-monitoring-apis-by-using-the-CLI.adoc
  observability/monitoring/accessing-metrics/images
  observability/monitoring/accessing-metrics/modules
  observability/monitoring/accessing-metrics/snippets
  observability/monitoring/configuring-core-platform-monitoring/_attributes
  observability/monitoring/configuring-core-platform-monitoring/before-you-begin.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-alerts-and-notifications.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-metrics.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/images
  observability/monitoring/configuring-core-platform-monitoring/modules
  observability/monitoring/configuring-core-platform-monitoring/snippets
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-user-workload-monitoring/_attributes
  observability/monitoring/configuring-user-workload-monitoring/before-you-begin-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-alerts-and-notifications-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-metrics-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/images
  observability/monitoring/configuring-user-workload-monitoring/modules
  observability/monitoring/configuring-user-workload-monitoring/snippets
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
  observability/monitoring/getting-started/_attributes
  observability/monitoring/getting-started/common-monitoring-scenarios.adoc
  observability/monitoring/getting-started/core-platform-monitoring-first-steps.adoc
  observability/monitoring/getting-started/developer-and-non-administrator-steps.adoc
  observability/monitoring/getting-started/images
  observability/monitoring/getting-started/maintenance-and-support-for-monitoring.adoc
  observability/monitoring/getting-started/modules
  observability/monitoring/getting-started/snippets
  observability/monitoring/getting-started/user-workload-monitoring-first-steps.adoc
  observability/monitoring/managing-alerts/_attributes
  observability/monitoring/managing-alerts/images
  observability/monitoring/managing-alerts/managing-alerts-for-core-platform-monitoring.adoc
  observability/monitoring/managing-alerts/managing-alerts-for-user-workload-monitoring.adoc
  observability/monitoring/managing-alerts/modules
  observability/monitoring/managing-alerts/snippets
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#85915 [enterprise-4.13] Adds ipsec note to 413 and earlier
  networking/ovn_kubernetes_network_provider/configuring-ipsec-ovn.adoc
Labels: size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#85006 OSDOCS-12094: Add auto-recovery to Backup and restore section
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.18

#85897 [OCPBUGS-45655]: Rearranging order of HCP on AWS docs
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  modules/hcp-aws-enable-ext-dns-prereq.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#84553 OSDOCS-11181: adds ingress control release note MicroShift
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#85810 [RHACS] [Docs] [4.4] ROX-27249: Updating RN for 4.4.6 and 4.4.7
  modules/common-attributes.adoc
  release_notes/44-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, RHACS, jira/valid-reference, rhacs-docs-4.4

#85924 OSSM-8325 Update _attributes
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#83970 CNV#38773: Regional-DR with ODF for virt
  modules/virt-about-dr-methods.adoc
  modules/virt-defining-apps-for-dr.adoc
  modules/virt-metro-dr-odf.adoc
  modules/virt-regional-dr-odf.adoc
  modules/virt-vm-behavior-dr.adoc
  virt/backup_restore/virt-disaster-recovery.adoc
Labels: peer-review-done, size/M, CNV, branch/enterprise-4.17, branch/enterprise-4.18

#85878 Allowing includes to use content from openshift-kni repo as well as openshift repo
  build_for_portal.py
  contributing_to_docs/doc_guidelines.adoc
Labels: lgtm, size/S

#85941 Check google search console for why old versions appear, before d.o.c goes away for good
  index-commercial.html
  index-community.html
Labels: size/XS

#84548 OSDOCS-11183: adds ingress control defaults MicroShift
  modules/microshift-config-parameters-table.adoc
  modules/microshift-default-settings.adoc
Labels: peer-review-done, lgtm, size/L, QE Required, jira/valid-reference, branch/enterprise-4.18

#85943 TELCODOCS-2005: Adding structure for Telco Day 2 Troubleshooting
  _topic_maps/_topic_map.yml
  edge_computing/day_2_core_cnf_clusters/troubleshooting/_attributes
  edge_computing/day_2_core_cnf_clusters/troubleshooting/images
  edge_computing/day_2_core_cnf_clusters/troubleshooting/modules
  edge_computing/day_2_core_cnf_clusters/troubleshooting/snippets
Labels: peer-review-needed, lgtm, size/S, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84640 OSSM-8190: Add product documentation for Multi-Cluster Topology
  _topic_maps/_topic_map.yml
  install/ossm-installing-openshift-service-mesh.adoc
  install/ossm-multi-cluster-topologies.adoc
  modules/ossm-about-multi-cluster-mesh-topologies.adoc
  modules/ossm-applying-certificates-to-a-multi-cluster-topology.adoc
  modules/ossm-creating-certificates-for-a-multi-cluster-topology.adoc
  modules/ossm-multi-cluster-configuration-overview.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress, jira/valid-reference

#85615 Rename oc commands to use velero.io
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc
  cloud_experts_tutorials/cloud-experts-deploy-api-data-protection.adoc
  modules/backup-hosted-cluster-virt.adoc
  modules/cleanup-a-backup-oadp-aws-sts.adoc
  modules/cleanup-a-backup-oadp-rosa-sts.adoc
  modules/hcp-dr-oadp-backup-cp-workload.adoc
  modules/hcp-dr-oadp-observe.adoc
  modules/oadp-backup-restore-cr-issues.adoc
  modules/oadp-creating-backup-cr.adoc
  modules/oadp-creating-restore-cr.adoc
  modules/oadp-features-plugins-known-issues.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-multiple-bsl-use-case.adoc
  modules/oadp-operator-issues.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/oadp-usecase-restore.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
  modules/restore-hosted-cluster-virt.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85642 PR for SRVCOM-3457: Update the Serverless 1.33.3 release notes
  about/serverless-release-notes.adoc
  modules/serverless-rn-1-33-3.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference

#85814 [OSDOCS-11922]:Update "SRE and service account access" page to include GCP Private Service Connect-based access
  modules/sre-cluster-access.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#85937 OSDOCS-12872: updating the heading to automated recovery
  _topic_maps/_topic_map_ms.yml
  microshift_backup_and_restore/microshift-auto-recover-manual-backup.adoc
  modules/microshift-creating-backups.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.18

#85903 OSDOCS-12406:Amended ROSA Classic private/public arch image.
  images/156_OpenShift_ROSA_Arch_0621_private_public_classic.png
Labels: peer-review-done, size/XS, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#85477 Updates subnet value in offline migration docs
  modules/nw-ovn-kubernetes-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#85981 [enterprise-4.15] Updates subnet value in offline migration docs
  modules/nw-ovn-kubernetes-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S

#85918 OSDOCS-11938: adds greenboot test release note MicroShift
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-reference

#85936 [enterprise-4.14] CNV-51136: Updated yaml in 'Creating a Linux bridge NAD' to reference…
  modules/virt-creating-linux-bridge-nad-cli.adoc
Labels: size/XS, jira/valid-reference

#85984 [enterprise-4.14] Updates subnet value in offline migration docs
  modules/nw-ovn-kubernetes-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S

#85987 [enterprise-4.12] Updates subnet value in offline migration docs
  modules/nw-ovn-kubernetes-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, branch/enterprise-4.12

#85985 [enterprise-4.13] Updates subnet value in offline migration docs
  modules/nw-ovn-kubernetes-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S

#85785 OCPBUGS-36911: Update PTP docs as per the Concious Language initiative
  snippets/ztp_PtpConfigSlave.yaml
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, jira/valid-reference

#85891 OCPBUGS-43762: adds day 2 operation for masquerade to docs
  modules/nw-ovn-k-day-2-masq-subnet.adoc
  modules/nw-ovn-kubernetes-change-join-subnet.adoc
  modules/nw-ovn-kubernetes-change-transit-subnet.adoc
  networking/ovn_kubernetes_network_provider/configure-ovn-kubernetes-subnets.adoc
Labels: peer-review-done, size/M, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#84976 CNV#48752: (ContentX) Changes in and additions to Creating a VM TOC structure
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/virt-about-instance-types.adoc
  modules/virt-cloud-init-fields-web.adoc
  modules/virt-common-instancetypes.adoc
  modules/virt-creating-template.adoc
  modules/virt-creating-vm-from-template.adoc
  modules/virt-creating-vm-instancetype.adoc
  modules/virt-customizing-vm-template-web.adoc
  modules/virt-networking-wizard-fields-web.adoc
  modules/virt-storage-wizard-fields-web.adoc
  modules/virt-vm-storage-volume-types.adoc
  virt/getting_started/virt-getting-started.adoc
  virt/virtual_machines/creating_vm/_attributes
  virt/virtual_machines/creating_vm/images
  virt/virtual_machines/creating_vm/modules
  virt/virtual_machines/creating_vm/snippets
  virt/virtual_machines/creating_vm/virt-basic-vm-overview.adoc
  virt/virtual_machines/creating_vm/virt-creating-vms-from-instance-types.adoc
  virt/virtual_machines/creating_vm/virt-creating-vms-from-templates.adoc
  virt/virtual_machines/creating_vm/virt-setting-up-environment.adoc
  virt/virtual_machines/creating_vms_rh/virt-creating-vms-from-cli.adoc
  virt/virtual_machines/creating_vms_rh/virt-creating-vms-from-rh-images-overview.adoc
  virt/virtual_machines/creating_vms_rh/virt-creating-vms-from-templates.adoc
Labels: peer-review-done, size/L, CNV, merge-review-in-progress, branch/enterprise-4.18

#85956 RHDEVDOCS-6228 Update _distro_map.yml
  _distro_map.yml
Labels: peer-review-done, size/XS, gitops

#85581 OCPBUGS#44659-13: Added important note for disabling IPsec for 4.13 a…
  modules/nw-ovn-ipsec-disable.adoc
  modules/nw-ovn-ipsec-enable.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#86009 4.15-OADP-5268-Rename-oc-commands
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc
  cloud_experts_tutorials/cloud-experts-deploy-api-data-protection.adoc
  modules/cleanup-a-backup-oadp-aws-sts.adoc
  modules/cleanup-a-backup-oadp-rosa-sts.adoc
  modules/oadp-backup-restore-cr-issues.adoc
  modules/oadp-creating-backup-cr.adoc
  modules/oadp-creating-restore-cr.adoc
  modules/oadp-features-plugins-known-issues.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-multiple-bsl-use-case.adoc
  modules/oadp-operator-issues.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/oadp-usecase-restore.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
Labels: size/M, OADP

#86013 4.16-OADP-5268-Rename-oc-commands
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc
  cloud_experts_tutorials/cloud-experts-deploy-api-data-protection.adoc
  modules/cleanup-a-backup-oadp-aws-sts.adoc
  modules/cleanup-a-backup-oadp-rosa-sts.adoc
  modules/hcp-dr-oadp-backup-cp-workload.adoc
  modules/hcp-dr-oadp-observe.adoc
  modules/oadp-backup-restore-cr-issues.adoc
  modules/oadp-creating-backup-cr.adoc
  modules/oadp-creating-restore-cr.adoc
  modules/oadp-features-plugins-known-issues.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-multiple-bsl-use-case.adoc
  modules/oadp-operator-issues.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/oadp-usecase-restore.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
Labels: size/M, OADP

#86015 4.14-OADP-5268-Rename-oc-commands
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc
  cloud_experts_tutorials/cloud-experts-deploy-api-data-protection.adoc
  modules/cleanup-a-backup-oadp-aws-sts.adoc
  modules/cleanup-a-backup-oadp-rosa-sts.adoc
  modules/oadp-backup-restore-cr-issues.adoc
  modules/oadp-creating-backup-cr.adoc
  modules/oadp-creating-restore-cr.adoc
  modules/oadp-features-plugins-known-issues.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-multiple-bsl-use-case.adoc
  modules/oadp-operator-issues.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/oadp-usecase-restore.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
Labels: size/M, OADP

#84545 MIG-1665-MTC-1.8.5-attributes
  _attributes/common-attributes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.10, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.17, branch/enterprise-4.18

#85467 CMP-2985: Added FIO 1.3.5 release notes
  security/file_integrity_operator/file-integrity-operator-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85488 CMP-2972: added SPO 0.8.6 release notes
  security/security_profiles_operator/spo-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86005 ROX-27320: update StackRox Scanner vuln source link rendering
  modules/con-vuln-sources.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.6

#85824 [OSDOCS-12847]:Removing topics from installing OSD clusters section of docs
  _topic_maps/_topic_map_osd.yml
  authentication/osd-revoking-cluster-privileges.adoc
  osd_getting_started/osd-getting-started.adoc
  osd_install_access_delete_cluster/creating-a-gcp-cluster-with-workload-identity-federation.adoc
  osd_install_access_delete_cluster/creating-a-gcp-cluster.adoc
  osd_install_access_delete_cluster/creating-an-aws-cluster.adoc
Labels: peer-review-done, lgtm, size/S, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#86023 OSDOCS-12877: Update heading in release note
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#85815 [OCPBUGS-38909]: Fixing ignition version in etcd docs
  modules/move-etcd-different-disk.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#84634 HCCDOC3143 Add content about the Insights Operator TP feature InsightsRuntimeExtractor
  modules/insights-operator-what-information-is-collected.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#85503 [OSDOCS-11923]: [OSD-GCP] review changes to "Responsibility assignment matrix" page with introduction of GCP PSC
  modules/policy-shared-responsibility.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#85926 [OCPBUGS-45851]: Correcting etcd backup docs
  backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85786 [enterprise-4.13] OCPBUGS-36911: Update PTP docs as per the Concious Language initiative
  modules/ztp-sno-du-configuring-ptp.adoc
  snippets/ztp_PtpConfigSlave.yaml
Labels: peer-review-done, size/S, jira/invalid-bug, merge-review-in-progress, jira/valid-reference

#86057 [enterprise-4.15] OCPBUGS-36911: Update PTP docs as per the Concious Language initiative
  snippets/ztp_PtpConfigSlave.yaml
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#86056 [enterprise-4.14] OCPBUGS-36911: Update PTP docs as per the Concious Language initiative
  snippets/ztp_PtpConfigSlave.yaml
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#86071 [enterprise-4.15][OCPBUGS-12781]: Correcting etcd backup docs
  backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.adoc
Labels: size/XS

#86070 [enterprise-4.14][OCPBUGS-12781]: Correcting etcd backup docs
  backup_and_restore/control_plane_backup_and_restore/backing-up-etcd.adoc
Labels: size/XS

#86012 OCPBUGS-33399: Correct product version in Low latency note
  modules/cnf-understanding-low-latency.adoc
Labels: peer-review-done, size/XS, merge-review-needed, jira/valid-reference

#85933 OSSM-8536: Add procedure section title
  modules/ossm-deploying-bookinfo-application.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#85731 OSDOCS#12812: Remove TP, pull secret, and private catalog snippets
  extensions/arch/catalogd.adoc
  extensions/arch/components.adoc
  extensions/arch/operator-controller.adoc
  extensions/catalogs/creating-catalogs.adoc
  extensions/catalogs/fbc.adoc
  extensions/catalogs/managing-catalogs.adoc
  extensions/catalogs/rh-catalogs.adoc
  extensions/ce/crd-upgrade-safety.adoc
  extensions/ce/managing-ce.adoc
  extensions/ce/upgrade-edges.adoc
  extensions/index.adoc
  extensions/of-terms.adoc
  modules/olmv1-adding-a-catalog.adoc
  modules/olmv1-installing-an-operator.adoc
  modules/olmv1-red-hat-catalogs.adoc
  operators/olm_v1/index.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.18

#85761 CNV-51691: Updated note about OVN-Kubernetes IPAM support
  virt/vm_networking/virt-connecting-vm-to-ovn-secondary-network.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84677 MIG-1664: MTC-1.8.5-release-notes
  migration_toolkit_for_containers/release_notes/mtc-release-notes.adoc
  modules/migration-mtc-release-notes-1-8-5.adoc
Labels: peer-review-done, size/M, MTC, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86059 OSDOCS-12705:Copy edits in install section
  modules/microshift-install-system-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#84204 RHDEVDOCS-6210: Remove deprecated ClusterTask from docs
  _topic_maps/_topic_map.yml
  create/creating-applications-with-cicd-pipelines.adoc
  create/managing-nonversioned-and-versioned-cluster-tasks.adoc
  create/remote-pipelines-tasks-resolvers.adoc
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/op-about-pipelines-as-code-resolver.adoc
  modules/op-advantages-and-disadvantages-of-non-versioned-and-versioned-cluster-tasks.adoc
  modules/op-constructing-pipelines-using-pipeline-builder.adoc
  modules/op-creating-pipeline-tasks.adoc
  modules/op-differences-between-non-versioned-and-versioned-cluster-tasks.adoc
  modules/op-disabling-automatic-creation-of-rbac-resources.adoc
  modules/op-disabling-cluster-tasks-and-pipeline-templates.adoc
  modules/op-disabling-non-versioned-and-versioned-cluster-tasks.adoc
  modules/op-disabling-pipeline-templates.adoc
  modules/op-installing-pipelines-operator-in-web-console.adoc
  modules/op-nonroot-buildah-user-namespaces.adoc
  modules/op-resolver-cluster-tasks-ref.adoc
  modules/op-resolver-tasks-step-actions-about.adoc
  modules/op-starting-a-task-run-pipeline-run-build-user.adoc
  modules/op-tkn-clustertask-management.adoc
  secure/configuring-security-context-for-pods.adoc
  snippets/ref-s2i-task.adoc
  tkn_cli/op-tkn-reference.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, pipelines

#86108 CNV#50729: HCO bump 4.17.2
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.17

#86080 [OSDOCS-12684]: Updating HCP must gather docs
  modules/hosted-control-planes-troubleshooting.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#83770 OBSDOCS-1414: Release notes for Distributed tracing 3.4
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-rn.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84482 OBSDOCS-1412: Add must-gather docs for Tempo and OpenTelemetry
  _topic_maps/_topic_map.yml
  modules/distr-tracing-tempo-troubleshoot-collecting-diagnostic-data-from-command-line.adoc
  modules/otel-troubleshoot-collecting-diagnostic-data-from-command-line.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-troubleshooting.adoc
  observability/otel/otel-troubleshooting.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84370 OBSDOCS-1423: Document that instrumentation injection is GA
  modules/otel-config-instrumentation.adoc
  observability/otel/otel-configuration-of-instrumentation.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#78020 OBSDOCS-1231/OBSDOCS-1058: Update docs about instrumentation for multi-container pods
  modules/otel-config-instrumentation.adoc
Labels: peer-review-done, size/M, ok-to-merge, do-not-merge/hold, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84251 OBSDOCS-1317: Add docs for the OTLP JSON File Receiver
  observability/otel/otel-collector/otel-collector-receivers.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86134 [enterprise-4.13] Cherry-pick of OBSDOCS-1414: Release notes for Distributed tracing 3.4
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-rn.adoc
Labels: size/L, jira/valid-reference

#84281 OBSDOCS-1405: Add docs for the Count Connector
  observability/otel/otel-collector/otel-collector-connectors.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85762 RHDEVDOCS-6276: Update OCP docs to reflect that Shared Resource CSI Driver is removed from OCP but is GA in Builds
  modules/ephemeral-storage-additional-support-limitations-for-shared-resource-csi-driver.adoc
  modules/ephemeral-storage-csi-inline-overview.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  release_notes/ocp-4-17-release-notes.adoc
  storage/container_storage_interface/ephemeral-storage-shared-resource-csi-driver-operator.adoc
Labels: peer-review-done, size/M, merge-review-needed, jira/valid-reference, branch/enterprise-4.17

#85651 OBSDOCS-1478: Ability to modify UWM Prometheus scrape interval
  modules/monitoring-limiting-scrape-samples-in-user-defined-projects.adoc
  modules/monitoring-setting-scrape-and-evaluation-intervals-limits-for-user-defined-projects.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
  support/troubleshooting/investigating-monitoring-issues.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18

#85977 OSDOCS-7651: Moving MCO info 4.12
  architecture/control-plane.adoc
  modules/machine-config-overview.adoc
  modules/understanding-machine-config-operator.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-needed, jira/valid-reference

#85995 OSDOCS-7561-413: Moving MCO info
  architecture/control-plane.adoc
  modules/machine-config-overview.adoc
  modules/understanding-machine-config-operator.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: peer-review-done, size/M, merge-review-needed, jira/valid-reference, branch/enterprise-4.13

#86000 OSDOCS-7651-414: Moving MCO info
  architecture/control-plane.adoc
  modules/machine-config-overview.adoc
  modules/understanding-machine-config-operator.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-needed, jira/valid-reference

#83951 OSDOCS-7651: Removing MCO info (4.16+)
  architecture/control-plane.adoc
  modules/understanding-machine-config-operator.adoc
Labels: size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85993 adding contexts and IDs in Agent docs
  installing/installing_oci/installing-oci-agent-based-installer.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
  installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc
  installing/installing_with_agent_based_installer/understanding-disconnected-installation-mirroring.adoc
  modules/agent-install-networking.adoc
  modules/understanding-agent-install.adoc
  modules/validations-before-agent-iso-creation.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86155 [enterprise-4.13] Cherry-pick of OBSDOCS-1412: Add must-gather docs for Tempo and OpenTelemetry
  _topic_maps/_topic_map.yml
  modules/distr-tracing-tempo-troubleshoot-collecting-diagnostic-data-from-command-line.adoc
  modules/otel-troubleshoot-collecting-diagnostic-data-from-command-line.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-troubleshooting.adoc
  observability/otel/otel-troubleshooting.adoc
Labels: size/M, jira/valid-reference

#85996 OCPBUGS-36480:updates nwt optimization MTU
  modules/optimizing-mtu-networking.adoc
  scalability_and_performance/optimization/optimizing-networking.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86163 [enterprise-4.15] Cherry-pick of OBSDOCS-1423: Document that instrumentation injection is GA
  modules/otel-config-instrumentation.adoc
  observability/otel/otel-configuration-of-instrumentation.adoc
Labels: size/M, jira/valid-reference
