Repository openshift/openshift-docs, pull requests merged in 2024-01, with the labels that each got.

#69718 [opp-docs] Add conditional checks for PR and slug in autopreview.sh
  .vscode/settings.json
  autopreview.sh
Labels: size/M

#64787 clarifying that links between distros are links
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS, lifecycle/stale

#69680 OBSDOCS-603: Update attributes in upgrading docs
  logging/cluster-logging-upgrading.adoc
  modules/cluster-logging-upgrading-elasticsearch.adoc
  modules/logging-operator-upgrading-all-ns.adoc
  modules/logging-upgrading-clo.adoc
  modules/logging-upgrading-loki.adoc
Labels: peer-review-done, size/M, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69675 OSDOCS#8721: Refactor of vSphere install reqs for IPI
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/installation-vsphere-installer-infra-static-ip-nodes.adoc
  modules/installation-vsphere-installer-network-requirements.adoc
  modules/vmware-csi-driver-reqs.adoc
  post_installation_configuration/node-tasks.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#69726 [enterprise-4.11] OBSDOCS-603: Update attributes in upgrading docs
  logging/cluster-logging-upgrading.adoc
  modules/cluster-logging-upgrading-elasticsearch.adoc
  modules/logging-upgrading-clo.adoc
  modules/logging-upgrading-loki.adoc
Labels: size/S, jira/valid-reference

#69730 [enterprise-4.15] OSDOCS#8721: Refactor of vSphere install reqs for IPI
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/installation-vsphere-installer-infra-static-ip-nodes.adoc
  modules/installation-vsphere-installer-network-requirements.adoc
  modules/vmware-csi-driver-reqs.adoc
  post_installation_configuration/node-tasks.adoc
  windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.adoc
Labels: size/L

#69717 [OSDOCS-9186]: Include a note on DDOS protection Service for OSD on Google Cloud in OSD service definition doc
  modules/sdpolicy-security.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15

#69647 OBSDOCS-78: Update eventrouter docs
  modules/cluster-logging-eventrouter-deploy.adoc
Labels: peer-review-done, size/S, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69256 OCPBUGS-23237: Add missing advisory RHSA-2023:6143 to 4.14 release notes
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#69263 OCPBUGS-23237: Adding RHSA-2023:3342 advisory to 4.13 release notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#69741 [enterprise-4.12] HCIDOCS- 104: Update Assisted Installer links
  _attributes/common-attributes.adoc
  installing/index.adoc
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_nutanix/installing-nutanix-installer-provisioned.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/assisted-installer-using-the-assisted-installer.adoc
  modules/install-openshift-common-terms.adoc
  modules/installation-overview.adoc
  modules/installation-process.adoc
Labels: size/M

#69743 [enterprise-4.13] HCIDOCS- 104: Update Assisted Installer links
  _attributes/common-attributes.adoc
  installing/index.adoc
  installing/installing_bare_metal/preparing-to-install-on-bare-metal.adoc
  installing/installing_nutanix/installing-nutanix-installer-provisioned.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  modules/assisted-installer-using-the-assisted-installer.adoc
  modules/install-openshift-common-terms.adoc
  modules/installation-overview.adoc
  modules/installation-process.adoc
Labels: size/M

#69715 OCPBUGS-25839: Added arch support for SPO
  security/security_profiles_operator/spo-enabling.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69600 OCPBUGS#25683: Updated the errors in compute machine set sample yaml
  modules/machineset-yaml-aws.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15

#69584 OVN-K-ISG:removes may in favor of might
  modules/configuring-ovnk-additional-networks.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69748 [OSDOCS-9190]:Rewrite and/or remove duplicate information
  osd_planning/gcp-ccs.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69602 OBSDOCS-664: Add demo size for loki and update lokistack CR docs
  logging/log_storage/installing-log-storage.adoc
  modules/create-lokistack-cr-cli.adoc
  modules/create-lokistack-cr-console.adoc
  modules/loki-deployment-sizing.adoc
Labels: peer-review-done, lgtm, size/M, dev-tools, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69768 [enterprise-4.13] Add note to 'Scheduling Backup' section to set backup every 10 minutes
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-scheduling-backups-doc.adoc
  modules/oadp-scheduling-backups.adoc
  virt/backup_restore/virt-backing-up-vms.adoc
Labels: size/M

#69771 [enterprise-4.12] Add note to 'Scheduling Backup' section to set backup every 10 minutes
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-scheduling-backups-doc.adoc
  modules/oadp-scheduling-backups.adoc
  virt/backup_restore/virt-backing-up-vms.adoc
Labels: size/M

#69750 [INTERNAL-FIX] vsphere-static-nodes-xrefs
  modules/installation-vsphere-installer-infra-static-ip-nodes.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15

#68666 OCPBUGS-18377: Updated SPO documentation
  modules/spo-applying-profiles.adoc
  modules/spo-binding-workloads.adoc
  modules/spo-creating-profiles.adoc
  modules/spo-recording-profiles.adoc
  modules/spo-replicating-controllers.adoc
Labels: peer-review-done, size/M, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#68398 CNV#35113: Remove obsolete 4.13 note from upgrade assembly
  virt/updating/upgrading-virt.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#69489 [enterprise-4.13] CNV35107: memory overhead bugfix
  modules/virt-cluster-resource-requirements.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.13

#69490 [enterprise-4.12] CNV35107: memory overhead bugfix
  modules/virt-cluster-resource-requirements.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.12

#69491 [enterprise-4.11] CNV35107: memory overhead bugfix
  modules/virt-cluster-resource-requirements.adoc
Labels: peer-review-done, size/S, CNV, branch/enterprise-4.11

#69442 OSDOCS-8807: Small update to firewalls
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#64339 OSDOCS-7663: Added a new Quick Start Guide that uses Terraform
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-sts-account-roles-terraform.adoc
  modules/rosa-sts-cluster-terraform-destroy.adoc
  modules/rosa-sts-cluster-terraform.adoc
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
  modules/rosa-sts-terraform-prerequisites.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly-terraform.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69721 OSDOCS#9051: Release note z stream 4.14.7
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#69729 OSDOCS-9121 z-stream RNs for 4.14.7
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.14

#69280 OBSDOCS-124: Added details for ES8 in the log forwarder example
  modules/cluster-logging-collector-log-forward-es.adoc
Labels: peer-review-done, lgtm, size/M, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69173 CNV- 36234: HCO 4.14.2
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.14

#69531 Update link checker
  scripts/check-rn-link-perms.sh
Labels: size/M

#68970 OpenShift Compliance Operator 1.4.0
  modules/compliance-custom-node-pools.adoc
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#68677 OCPBUGS-15542: added a note for CA bundle updates
  security/certificates/updating-ca-bundle.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69698 Added comprehensive steps for enabling notifications for ArgoCD appli…
  argocd_instance/argo-cd-cr-component-properties.adoc
  modules/gitops-argo-cd-notification.adoc
Labels: peer-review-done, size/M, qe-approved, merge-review-in-progress, sme-review-done

#68979 OCPBUGS-13794: Added NodeFeatureRule to the docs
  hardware_enablement/psap-node-feature-discovery-operator.adoc
  modules/nfd-rules-about.adoc
  modules/nfd-rules-using.adoc
Labels: peer-review-done, size/M, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69826 adding new API assembly to the topic map
  _topic_maps/_topic_map.yml
Labels: size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69767 OSDOCS-9123: Documented the 4.12.46 z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference

#69791 CNV#36931: Updating machine type section for 4.14+
  modules/virt-rhel-9.adoc
Labels: lgtm, size/S, CNV, branch/enterprise-4.14, branch/enterprise-4.15

#69832 adding more APIS to the 4.15 docs
  _topic_maps/_topic_map.yml
Labels: size/XS, branch/enterprise-4.15

#69505 OSDOCS-8983: Update Ushift docs to reflect lvmd.yaml not required
  modules/microshift-lvms-system-requirements.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69150 Updates release notes to call out macvlan ipv6 support
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15

#68025 OSDOCS-8728: Reviewed the Entra ID as Identity Provider tutorial.
  cloud_experts_tutorials/cloud-experts-entra-id-idp.adoc
  images/azure-portal_add-a-client-secret-page.png
  images/azure-portal_add-optional-claims-graph-permissions-prompt.png
  images/azure-portal_add-optional-claims-page.png
  images/azure-portal_add-optional-email-claims-page.png
  images/azure-portal_add-optional-preferred_username-claims-page.png
  images/azure-portal_edit-group-claims-page.png
  images/azure-portal_register-an-application-page.png
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, SD-docs, branch/enterprise-4.14, cloud-experts, branch/enterprise-4.15

#68089 OCPBUGS-23361 [DOC] Updated documentation to configure and verify different cgroup versions
  modules/nodes-clusters-cgroups-2.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.14, branch/enterprise-4.15

#69787 [OSDOCS#9122]: 4.13.27 release notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.13

#69849 Fixing OWNER and OWNER-ALIASES indents for Prow CI
  OWNERS
  OWNERS-ALIASES
Labels: size/M, do-not-merge/invalid-owners-file

#69815 Fixing typos in PTP config reference tables
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
  modules/nw-ptp-grandmaster-clock-configuration-reference.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#68626 OCPBUGS-18370 Updating SNO supported platforms
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: peer-review-done, lgtm, size/XS, telco, qe-approved, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69858 Fixing typos in PTP config ref tables
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
Labels: size/S

#69857 Fixing typos in PTP config ref tables
  modules/nw-ptp-configuring-linuxptp-services-as-boundary-clock.adoc
  modules/nw-ptp-configuring-linuxptp-services-as-ordinary-clock.adoc
Labels: size/S

#69774 OSDOCS#9205: Removed reference to CNS not being supported.
  modules/available-persistent-storage-options.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69788 #CNV-33128: adjust tp tab section to web console overview
  virt/getting_started/virt-web-console-overview.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.15

#69837 updating copyright year to 2024
  LICENSE
  welcome/legal-notice.adoc
Labels: size/XS

#69831 OBSDOCS-698: Update rhel8 to rhel9
  modules/cluster-logging-eventrouter-deploy.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69866 [OSDOCS-9232]: Issue in file rosa_hcp/rosa-tuning-config.adoc
  modules/custom-tuning-specification.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69713 [virt] DPDK cluster config: Enable AlignCPUs
  modules/virt-configuring-cluster-dpdk.adoc
Labels: peer-review-done, lgtm, size/S, CNV, branch/enterprise-4.15

#69342 ROX-21385: Update RNs for patch release 4.3.2
  modules/common-attributes.adoc
  release_notes/43-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, rhacs-docs-4.3

#69911 fix 4.14 topic map
  _topic_maps/_topic_map.yml
Labels: size/M

#69892 CNV- 36956: VirtualMachineCRCErrors update
  modules/virt-runbook-virtualmachinecrcerrors.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69931 updating get-updated-distros logic
  scripts/get-updated-distros.sh
Labels: size/XS

#69932 Fix ROSA topic map
  _topic_maps/_topic_map_rosa.yml
Labels: peer-review-needed, peer-review-done, size/XS

#69819 Updating GitOps Operator reqs
  modules/ztp-telco-ran-software-versions.adoc
Labels: peer-review-in-progress, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69906 OCPBUGS-26482 - PTP E810 T-GM tech preview typo
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, lgtm, size/S

#69881 [OSDOCS-9233]:Red Hat OpenShift Service on AWS Images book typo
  modules/samples-operator-overview.adoc
Labels: peer-review-done, size/XS, ok-to-merge, branch/enterprise-4.14, branch/enterprise-4.15

#69773 [OSDOCS-7743]: ROSA Operator, Invalid IAM Policy
  modules/oadp-preparing-aws-credentials.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-merge, branch/enterprise-4.14, branch/enterprise-4.15

#68130 OSDOCS#7674:LSO option to wipe LVs
  modules/persistent-storage-local-create-cr.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#67893 OSDOCS#7671: Retroactive SC TP-> GA
  modules/persistent-storage-csi-sc-multiple-none.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.15

#69894 OCPBUGS#13638: Important section under discovery for local storage de…
  modules/persistent-storage-local-discovery.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-merge, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69820 OSDOCS#9216:Corrected typo in first step of creating ROSA cluster with Terraform procedure
  modules/rosa-sts-cluster-terraform.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#69254 CNV-35286: fix bandwidthPerMigration documentation
  modules/virt-configuring-live-migration-limits.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69891 HCIDOCS-133: [enterprise-4.13] Issue in file installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  _attributes/common-attributes.adoc
  installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc
  modules/ipi-install-configuring-nodes.adoc
  modules/ipi-install-node-requirements.adoc
  modules/ipi-install-preparing-the-provisioner-node-for-openshift-install.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69907 OCPBUGS-18370 adding simple change AWS to AWS cloud
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: size/XS, telco, branch/enterprise-4.13

#69508 OADP 3183 Doc improvements - Installing and configuring OADP & Uninst…
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/about-installing-oadp-on-multiple-namespaces.adoc
  modules/migration-configuring-azure.adoc
  modules/oadp-about-backup-snapshot-locations-secrets.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-setting-resource-limits-and-requests.adoc
  modules/oadp-velero-cpu-memory-requirements.adoc
Labels: peer-review-done, size/M, ok-to-merge, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69882 OSDOCS-9002: Note about default host config values
  modules/installing-ocp-agent-inputs.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.15

#69663 [OSDOCS-6455] Azure AD Workload ID for OLM Operators (CCO reference)
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
  modules/cco-short-term-creds-azure-olm.adoc
Labels: peer-review-done, size/S, ok-to-merge, branch/enterprise-4.15

#69910 [OSDOCS#9221]: 4.14.8 errata/rn
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#69728 CNV#34998 - change authorized ssh key to public ssh key
  virt/getting_started/virt-web-console-overview.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#69902 OSDOCS-9236: adds 4.14.8 release note to MicroShift docs
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14

#69896 OSDOCS-3462-re: Removed port 80 reference from AWS firewall pre in RO…
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, SD-docs, branch/enterprise-4.14, branch/enterprise-4.15

#69942 OCPBUGS#25249:Corrected typo in Frankfurt region in HCP classic comparison doc
  modules/rosa-hcp-classic-comparison.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69656 OCPBUGS#17511 updating docker build arguments link
  modules/builds-strategy-docker-build-arguments.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69914 #CNV-36461 - rearrange map
  _topic_maps/_topic_map.yml
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#68703 OSDOCS-8381: Migrate "Getting Started with Rosa - Managing your Worker Nodes"
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-managing-worker-nodes.adoc
  images/cloud-experts-getting-started-managing-describe.png
  images/cloud-experts-getting-started-managing-large-mp.png
  images/cloud-experts-getting-started-managing-mp-fromui.png
  images/cloud-experts-getting-started-managing-mp-interactive.png
  images/cloud-experts-getting-started-managing-mp-nlt.png
  images/cloud-experts-getting-started-managing-mp-ocm.png
  images/cloud-experts-getting-started-managing-mp-scale.png
  images/cloud-experts-getting-started-managing-mp.png
  images/cloud-experts-getting-started-managing-new-mp.png
  images/cloud-experts-getting-started-managing-ocm-cluster.png
  images/cloud-experts-getting-started-managing-ocm-nodes.png
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#67308 CNV- 31294: 4.11.8 HCO version
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.11

#69944 [virt] DPDK: Remove nodeSelector from VM def
  modules/virt-configuring-vm-dpdk.adoc
Labels: peer-review-done, lgtm, size/S, CNV, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69918 OSDOCS-8962: adds etcd query feature to release notes MicroShift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.15

#68949 OCPBUGS#19749: add verification for unsigned containers
  modules/containers-signature-verify-skopeo.adoc
  modules/containers-signature-verify-unsigned.adoc
  security/container_security/security-container-signature.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69551 CNV#25649: Added networking overview
  _topic_maps/_topic_map.yml
  modules/virt-networking-glossary.adoc
  virt/vm_networking/virt-networking-overview.adoc
  virt/vm_networking/virt-using-mac-address-pool-for-vms.adoc
Labels: peer-review-done, size/L, CNV, branch/enterprise-4.14, branch/enterprise-4.15

#69678 OCPBUGS-25807: Add note to clarify node delete process
  modules/nodes-nodes-working-deleting.adoc
  nodes/nodes/nodes-nodes-working.adoc
Labels: peer-review-done, size/M, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69924 OSDOCS#8505: Removing auth dep/rem table since there are no items
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#69740 [OCPBUGS-25925]
  hosted_control_planes/hcp-configuring.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#69895 Retiring Travis build
  .travis.yml.old
Labels: size/XS

#70001 OBSDOCS-719: Add checkmark for PHP support
  modules/logging-multiline-except.adoc
Labels: peer-review-done, size/XS, dev-tools, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69929 OCPBUGS#24512: Added info on devices not supported for LVM Storage operations
  modules/lvms-creating-logical-volume-manager-cluster.adoc
  modules/lvms-unsupported-devices.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#69298 TELCODOCS#1255: Added limitations related to creating snapshots and clones in multi-node topology
  modules/lvms-creating-volume-clones-in-single-node-openshift.adoc
  modules/lvms-limitations-for-creating-snapshots-and-clones.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.15

#69900 OSDOCS-9215: Documented the 4.11.56 z-stream release notes
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference

#69885 OSDOCS-9220 z-stream RNs for 4.13.28
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13

#70035 OCPBUGS-19883: Move reboot warning in "Replacing an unhealthy etcd member"
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69087 Adds procedure to create private cluster with private image registry
  installing/installing_azure/installing-azure-private.adoc
  modules/installing-private-image-registry-private-azure.adoc
  modules/minimum-required-permissions-ipi-azure.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.15

#69952 [OSDOCS-6893]Field presentation mistake in example, string instead of list of strings
  modules/nodes-cma-autoscaling-custom-install.adoc
  modules/sd-nodes-cma-autoscaling-custom-install.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#70050 OCPBUGS:24018 Remove extra 'Configuring an OpenShift Container Platform cluster for pods' module
  _topic_maps/_topic_map.yml
  nodes/clusters/nodes-cluster-pods-configuring.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70075 [enterprise-4.11] OCPBUGS:24018 Remove extra 'Configuring an OpenShift Container Platform cluster for pods' module
  _topic_maps/_topic_map.yml
  nodes/clusters/nodes-cluster-pods-configuring.adoc
Labels: size/M

#69921 OSDOCS-8834: Updated images to change format from SVG to PNG
  images/156_OpenShift_ROSA_Arch_0621_private_public_classic.png
  images/156_OpenShift_ROSA_Arch_0621_privatelink.svg
  images/156_OpenShift_ROSA_Arch_1221_privatelink.png
  images/ossm-node-badge-missing-sidecar.png
  images/ossm-node-badge-missing-sidecar.svg
  images/telmetry-and-insights-operator-data-flow.png
  images/telmetry-and-insights-operator-data-flow.svg
  modules/osd-aws-privatelink-architecture.adoc
  modules/ossm-sidecar-validate-kiali.adoc
  modules/rosa-architecture.adoc
  modules/rosa-hcp-classic-comparison.adoc
  modules/understanding-telemetry-and-insights-operator-data-flow.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#70080 [enterprise-4.13] OCPBUGS:24018 Remove extra 'Configuring an OpenShift Container Platform cluster for pods' module
  _topic_maps/_topic_map.yml
  nodes/clusters/nodes-cluster-pods-configuring.adoc
Labels: size/M

#70077 [enterprise-4.12] OCPBUGS:24018 Remove extra 'Configuring an OpenShift Container Platform cluster for pods' module
  _topic_maps/_topic_map.yml
  nodes/clusters/nodes-cluster-pods-configuring.adoc
Labels: size/M

#69847 OSDOCS-8382: Migrate "Getting Started with ROSA: Autoscaling" from rosaworkshop.io into product documentation
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-autoscaling.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#70082 [enterprise-4.12] OBSDOCS-719: Add checkmark for PHP support
  logging/cluster-logging-upgrading.adoc
  logging/log_storage/cluster-logging-loki.adoc
  logging/logging_alerts/troubleshooting-logging-alerts.adoc
  modules/logging-multiline-except.adoc
Labels: size/S, jira/valid-reference

#70045 OSDOCS-7475: Add il-central-1 (Tel Aviv) region as supported region
  modules/installation-aws-regions.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.15

#69919 OSDOCS-8923: adds RHEL 9.3 to MicroShift V4.15 relnotes
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.15

#69917 OSDOCS-8805: Adds etcd version query to MicroShift
  microshift_support/microshift-etcd.adoc
  microshift_support/microshift-getting-support.adoc
  microshift_troubleshooting/microshift-version.adoc
  modules/microshift-etcd-version.adoc
Labels: peer-review-done, size/M, qe-approved, jira/valid-reference, branch/enterprise-4.15

#68467 OCPBUGS-234060: clarifies example labels
  modules/nw-infw-operator-rules-object.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69727 OBSDOCS-603: Update instances of Loki Operator to use attribute
  logging/log_storage/cluster-logging-loki.adoc
  modules/cluster-logging-about.adoc
  modules/logging-loki-reliability-hardening.adoc
  modules/logging-loki-restart-hardening.adoc
  modules/logging-loki-zone-aware-rep.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-loki-secret.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/nw-network-observability-operator.adoc
  modules/recommended-configurable-storage-technology.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  network_observability/installing-operators.adoc
  network_observability/network-observability-overview.adoc
  snippets/logging-alertingruleCR-callouts-snip.adoc
  snippets/logging-alertingruleCR-snip.adoc
Labels: peer-review-done, size/L, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70107 [enterprise-4.11] OBSDOCS-603: Update instances of Loki Operator to use attribute
  modules/cluster-logging-about.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-loki-secret.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/nw-network-observability-operator.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  network_observability/installing-operators.adoc
  network_observability/network-observability-overview.adoc
  snippets/logging-alertingruleCR-callouts-snip.adoc
  snippets/logging-alertingruleCR-snip.adoc
Labels: size/L, jira/valid-reference

#70108 [enterprise-4.12] OBSDOCS-603: Update instances of Loki Operator to use attribute
  logging/log_storage/cluster-logging-loki.adoc
  modules/cluster-logging-about.adoc
  modules/logging-loki-reliability-hardening.adoc
  modules/logging-loki-restart-hardening.adoc
  modules/logging-loki-zone-aware-rep.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-loki-secret.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/nw-network-observability-operator.adoc
  modules/recommended-configurable-storage-technology.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  network_observability/installing-operators.adoc
  network_observability/network-observability-overview.adoc
  snippets/logging-alertingruleCR-callouts-snip.adoc
  snippets/logging-alertingruleCR-snip.adoc
Labels: size/L, jira/valid-reference

#70109 [enterprise-4.13] OBSDOCS-603: Update instances of Loki Operator to use attribute
  logging/log_storage/cluster-logging-loki.adoc
  modules/cluster-logging-about.adoc
  modules/logging-loki-reliability-hardening.adoc
  modules/logging-loki-restart-hardening.adoc
  modules/logging-loki-zone-aware-rep.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-kafka-option.adoc
  modules/network-observability-loki-install.adoc
  modules/network-observability-loki-secret.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-operator-install.adoc
  modules/network-observability-operator-uninstall.adoc
  modules/nw-network-observability-operator.adoc
  modules/recommended-configurable-storage-technology.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  network_observability/installing-operators.adoc
  network_observability/network-observability-overview.adoc
  snippets/logging-alertingruleCR-callouts-snip.adoc
  snippets/logging-alertingruleCR-snip.adoc
Labels: size/L, jira/valid-reference

#69957 [OKD] GH #68234 Parse correct field for OKD
  _javascripts/page-loader.js
Labels: size/XS, ok-to-test

#69829 OBSDOCS-83: Removed JSON message field
  modules/cluster-logging-json-log-forwarding.adoc
Labels: peer-review-done, size/S, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70089 RHDEVDOCS-5766: Update travis.yml for the new version Builds 1.1
  .travis.yml
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference

#69956 OSDOCS-6537: adds RHEL 9.3 to MicroShift 4.14 docs
  microshift_release_notes/microshift-4-14-release-notes.adoc
  microshift_updating/microshift-about-updates.adoc
  microshift_updating/microshift-update-options.adoc
  snippets/microshift-rhde-compatibility-table-snip.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/valid-reference, branch/enterprise-4.14

#69960 OSDOCS-9284: adds RHEL 9.3 to MicroShift 4.15 docs
  _topic_maps/_topic_map_ms.yml
  microshift_updating/microshift-about-updates.adoc
  microshift_updating/microshift-update-options.adoc
  microshift_updating/microshift-update-rpms-manually.adoc
  microshift_updating/microshift-update-rpms-ostree.adoc
  snippets/microshift-rhde-compatibility-table-snip.adoc
  snippets/microshift-update-paths-snip.adoc
Labels: peer-review-done, size/M, qe-approved, jira/valid-reference, branch/enterprise-4.15

#70086 OCPBUGS-26932 unify cgroups docs for okd 4.14 and ocp 4.14
  _topic_maps/_topic_map.yml
  modules/nodes-clusters-cgroups-2.adoc
  modules/nodes-clusters-cgroups-okd-configure.adoc
  nodes/clusters/nodes-cluster-cgroups-2.adoc
  nodes/clusters/nodes-cluster-cgroups-okd.adoc
  post_installation_configuration/cluster-tasks.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.14, branch/enterprise-4.15

#69889 OSDOCS#8880: OLM 1.0 Adding a catalog to a cluster
  modules/olmv1-adding-a-catalog.adoc
  modules/olmv1-creating-a-pull-secret-for-catalogd.adoc
  modules/olmv1-red-hat-catalogs.adoc
  operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.adoc
  snippets/olmv1-secure-registry-pull-secret.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.15

#70091 OCPBUGS#13638-rework: Important section under discovery for local sto…
  modules/persistent-storage-local-discovery.adoc
Labels: size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70052 [rosa hcp] to add ap-southeast-2 and ap-southeast-4 regions
  modules/rosa-hcp-classic-comparison.adoc
  modules/rosa-sdpolicy-am-regions-az.adoc
Labels: size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#69980 OSDOCS-9287: revise install books RHEL versions MicroShift
  microshift_install/microshift-embed-in-rpm-ostree-offline-use.adoc
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  modules/microshift-install-system-requirements.adoc
  modules/microshift-preparing-for-image-building.adoc
Labels: peer-review-done, size/M, qe-approved, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69352 OSDOCS-8615: Configuring PID limits
  _topic_maps/_topic_map_rosa.yml
  modules/risks-setting-higher-process-id-limits.adoc
  modules/sd-understanding-process-id-limits.adoc
  modules/setting-higher-pid-limit-on-existing-cluster.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-service-definition.adoc
  rosa_cluster_admin/rosa-configuring-pid-limits.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
  snippets/pid-limits.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#68875 HCIDOCS-8: Fix 'Postinstallation' spelling
  _topic_maps/_topic_map.yml
  modules/installation-complete-user-infra.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/machine-user-infra-machines-ibm-z.adoc
  modules/sd-planning-considerations.adoc
  post_installation_configuration/ibmz-post-install.adoc
  security/seccomp-profiles.adoc
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-pci-passthrough.adoc
Labels: peer-review-done, size/S, ok-to-test, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69838 [enterprise-4.12] CNV#33811 - RN for VMs that use LVM with block storage on RHCOS
  virt/virt-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#69888 OSDOCS-6090: GCP CCM is GA (RNs)
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.15

#69927 OSDOCS-8383: Migrate "Getting Started with Rosa - Upgrade the Cluster"
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-upgrading.adoc
  images/cloud-experts-getting-started-cluster-upgrade.png
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69986 OSDOCS-9004 Adding 4.15 operator not available
  nodes/pods/run_once_duration_override/index.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-install.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-release-notes.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-uninstall.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#69887 OSDOCS-6090: GCP CCM is GA
  modules/cluster-cloud-controller-manager-operator.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.15

#69897 OSDOCS#24488: Changed example values for cert-manager
  modules/cert-manager-configure-cpu-memory.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70092 [virt] DPDK Checkup: Update upstream tags
  modules/virt-checking-cluster-dpdk-readiness.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.15

#70164 [OSDOCS-9319] ROSA CLI 1.2.33 release what's new
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-in-progress, size/XS

#70143 OSDOCS-8924: update RHDE page for MicroShift 4.15
  _attributes/common-attributes.adoc
  modules/about-rhde.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference

#69159 TELCODOCS-1476 Hub-side templating
  modules/ztp-managing-sriov-vlan-with-hub-cluster-templates-in-pgt.adoc
  modules/ztp-specifying-nics-in-pgt-crs-with-hub-cluster-templates.adoc
  scalability_and_performance/ztp_far_edge/ztp-advanced-policy-config.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.15

#69913 OSDOCS#8722: Refactor of vSphere install reqs for UPI
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/upi/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/upi/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/upi/installing-vsphere.adoc
  installing/installing_vsphere/upi/upi-vsphere-installation-reqs.adoc
  modules/csr-management.adoc
  modules/installation-dns-user-infra.adoc
  modules/installation-load-balancing-user-infra.adoc
  modules/installation-machine-requirements.adoc
  modules/installation-minimum-resource-requirements.adoc
  modules/installation-network-user-infra.adoc
  modules/installation-vsphere-encrypted-vms.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installation-vsphere-installer-infra-requirements.adoc
  modules/vmware-csi-driver-reqs.adoc
  post_installation_configuration/vsphere-post-installation-encryption.adoc
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#70151 OADP-3341: quick formatting fix in oadp-installing-dpa-1-3.adoc
  modules/oadp-installing-dpa-1-3.adoc
Labels: peer-review-done, lgtm, size/XS, OADP, jira/valid-reference, branch/enterprise-4.15

#70068 OSDOCS-8966 updating 4.15 RNs to K8s 1.28 info
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#70158 RHDEVDOCS-5864: Updated compatibility table to correct compatible pip…
  about/build-strategies.adoc
  modules/ob-compatibility-support-matrix.adoc
  modules/ob-creating-a-buildah-build.adoc
  modules/ob-creating-a-s2i-build.adoc
  modules/ob-deleting-a-resource.adoc
  work_with_builds/using-builds.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference

#70138 OADP-3183: Doc improvements as CherryPick for 4.13
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/about-installing-oadp-on-multiple-namespaces.adoc
  modules/migration-configuring-azure.adoc
  modules/oadp-about-backup-snapshot-locations-secrets.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-setting-resource-limits-and-requests.adoc
  modules/oadp-velero-cpu-memory-requirements.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference, branch/enterprise-4.13

#70159 RHDEVDOCS-5865: To correct the component ID in the bug reporting URL …
  _templates/_page_openshift.html.erb
Labels: peer-review-done, size/XS, jira/valid-reference

#70134 OBSDOCS-721: add Vector to monitoring components list
  modules/monitoring-default-monitoring-targets.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69149 NETOBSERV-1060: loki empty ring troubleshooting
  modules/troubleshooting-network-observability-loki-empty-ring.adoc
  network_observability/troubleshooting-network-observability.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#68507 OSDOCS-8429: DNS Improvements
  modules/network-observability-dns-overview.adoc
  modules/network-observability-dns-tracking.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70153 OCPBUGS-7355: Some rules will FAIL after auto remediation applied
  security/compliance_operator/compliance-operator-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70197 [enterprise-4.14]OCPBUGS#13638-rework: Important section under discovery for local sto…
  modules/persistent-storage-local-discovery.adoc
Labels: size/XS

#70200 [enterprise-4.15]OCPBUGS#13638-rework: Important section under discovery for local sto…
  modules/persistent-storage-local-discovery.adoc
Labels: size/XS

#69859 Updates macvlan release note
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15
