Repository openshift/openshift-docs, pull requests merged in 2024-10, with the labels that each got.

#82687 [RHACS] Patch release notes for 4.5.3
  release_notes/45-release-notes.adoc
Labels: peer-review-done, size/S, rhacs-docs-4.5

#82741 Oadp 1793 remove old note enterprise 4 13
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
Labels: size/XS, merge-review-needed, OADP

#82740 Oadp 1793 remove old note enterprise 4 14
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
Labels: size/XS, ok-to-merge, OADP

#82765 fix errors in patch release notes
  modules/common-attributes.adoc
  release_notes/45-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.5

#82711 OSSM-8195: Create docinfo.xml files for service mesh mirroring process with Pantheon
  _attributes/common-attributes.adoc
  about/docinfo.xml
  install/docinfo.xml
  kiali/docinfo.xml
  metrics/docinfo.xml
  ossm-release-notes/docinfo.xml
  update/docinfo.xml
Labels: peer-review-done, size/M, jira/valid-reference

#81070 [SRVOCF-620] Developing Go functions in Serverless Functions - TP
  _topic_maps/_topic_map.yml
Labels: peer-review-done, size/XS, serverless

#82666 4.17 GA
  .github/CODEOWNERS
  .s2i/httpd-cfg/01-commercial.conf
  _distro_map.yml
  _templates/_page_openshift.html.erb
  contributing_to_docs/doc_guidelines.adoc
  index-commercial.html
  index-community.html
Labels: size/M

#82455 OSDOCS-12049 multi-arch upgrades
  rosa_release_notes/rosa-release-notes.adoc
  upgrading/rosa-hcp-upgrading.adoc
Labels: peer-review-done, size/S

#70742 OCPBUGS 20370:Added a note in supported ACME challenge types
  modules/cert-manager-acme-challenges-types.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-merge, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81881 WMCO 10.17.0 release notes
  _topic_maps/_topic_map.yml
  windows_containers/windows-containers-release-notes-10-15-x.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-10-17-x.adoc
Labels: size/L

#82543 [OSDOCS-12141]: Add additional role to OSD on GCP shared VPC note
  modules/osd-create-cluster-ccs.adoc
  modules/osd-create-cluster-gcp-account.adoc
  modules/osd-create-cluster-rhm-gcp-account.adoc
Labels: peer-review-done, lgtm, size/XS

#82498 MIG-1651: Adding Support Matrix to MTC
  migration_toolkit_for_containers/about-mtc.adoc
  modules/migration-mtc-support.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, MTC, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82624 OSDOCS-11641 HCP 500 Node Limit Increase
  modules/rosa-sdpolicy-instance-types.adoc
  modules/sd-hcp-planning-cluster-maximums.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-hcp-instance-types.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, lgtm, size/S

#81803 TELCODOCS-1977: Document tagging behaviour
  modules/kmm-example-module-cr.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#82726 OSDOCS-12100: Fixed links for Baseline Ingress Controller (router) pe…
  scalability_and_performance/optimization/routing-optimization.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82535 OSDOCS-12135: Documented the 4.15.35 z-stream RNs
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#82762 CMP-2685: Added lifecycle support information for FIO and SPO
  _topic_maps/_topic_map.yml
  security/file_integrity_operator/fio-overview.adoc
  security/file_integrity_operator/fio-support.adoc
  security/security_profiles_operator/spo-support.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82763 OCPBUGS-42031: Known issue for failing to revert bond br-ex mode
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, jira/severity-important, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17

#82002 OBSDOCS-1319: Update monitoring config map API reference content for …
  observability/monitoring/config-map-reference-for-the-cluster-monitoring-operator.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#82648 OSDOCS-12003: adds 4.16.15 relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#82621 TRACING-4456: improve documentation about zPages extension
  observability/otel/otel-collector/otel-collector-extensions.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82689 OBSDOCS-1302: Logging Z-Stream Release Notes - 5.8.13
  modules/logging-release-notes-5-8-13.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#82613 RHDEVDOCS 6185 redirects for release notes for GitOps and Pipelines
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/S

#82755 TELCODOCS-2052 - Update Cluster logging for Telco SNO clusters
  modules/ztp-sno-du-configuring-logging-locally-and-forwarding.adoc
  snippets/ztp_ClusterLogForwarder.yaml
  snippets/ztp_ClusterLogServiceAccount.yaml
  snippets/ztp_ClusterLogServiceAccountAuditBinding.yaml
  snippets/ztp_ClusterLogServiceAccountInfrastructureBinding.yaml
  snippets/ztp_ClusterLogSubscription.yaml
Labels: peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#82803 OSDOCS-11737-backport
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#82800 Welcome index bullet tweak
  welcome/index.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#82649 OSDOCS-12009: adds 4.15.35 relnote MicroShift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#82331 OSDOCS-11989:Update OADP ROSA docs with uninstalling info
  _topic_maps/_topic_map_rosa.yml
  modules/installing-oadp-rosa-sts.adoc
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#78504 Provide example network policies for the web terminal operator
  modules/odc-access-web-terminal.adoc
  web_console/web_terminal/troubleshooting-web-terminal.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82845 [OCPBUGS-42690] Added $ before the start of the comment
  modules/dr-hosted-cluster-within-aws-region-restore.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82846 adding hugebook flag to 4.16
  installing/hugeBook.flag
Labels: size/XS, branch/enterprise-4.16

#82732 OSSM-8212: Fix errors in bookinfo installation instructions
  modules/ossm-accessing-bookinfo-application-using-istio-gateway-injection.adoc
  modules/ossm-deploying-bookinfo-application.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#82868 adding hugebook flag to 4.15
  installing/hugeBook.flag
Labels: size/XS, branch/enterprise-4.15

#82869 adding hugebook flag to 4.14
  installing/hugeBook.flag
Labels: size/XS, branch/enterprise-4.14

#82870 adding hugebook flag to 4.13
  installing/hugeBook.flag
Labels: size/XS, branch/enterprise-4.13

#81607 [SRVCOM-2667] Improve the Serverless Overview page
  about/about-serverless.adoc
Labels: peer-review-done, size/M, serverless

#82857 [OCPBUGS-42690]Added $ before the start of the comment in `Deleting a hosted cluster from your source management cluster` procedure
  modules/dr-hosted-cluster-within-aws-region-delete.adoc
Labels: peer-review-needed, size/M, merge-review-in-progress, merge-review-needed

#82664 OSDOCS-12136 OCP 4.16.15 release notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.16

#82214 Re-arranging steps for `oc adm wait-for-stable-cluster` command
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/S, needs-ok-to-test, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17

#82633 [RHACS] [Docs] [4.4] ROX-26426: Mark RHACS 4.4 as EOL
  _templates/_page_openshift.html.erb
Labels: peer-review-done, size/XS, RHACS, merge-review-in-progress, jira/valid-reference

#82619 TRACING-4562: Improve Prometheus port and services documentation
  modules/otel-config-send-metrics-monitoring-stack.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-configuring-otelcol-metrics.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#79529 OBSDOCS-1114: Document OTLP HTTP on Tempo Gateway
  modules/distr-tracing-tempo-config-multitenancy.adoc
Labels: peer-review-done, size/S, ok-to-test, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82681 Update oc edit command from the "Scaling down the data plane to zero" section.
  modules/scale-down-data-plane.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82778 [OSDOCS-12204][OSD-GCP] Remove outdated note and add RH Marketplace option link to docs
  modules/policy-security-regulation-compliance.adoc
  osd_getting_started/osd-getting-started.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#82683 OBSDOCS-1303: Logging Z-Stream Release Notes - 5.9.7
  modules/logging-release-notes-5-9-7.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, jira/valid-reference

#82770 OLS-1103: Change value of type parameter for rhoai configuration file
  modules/ols-creating-lightspeed-custom-resource-file-using-cli.adoc
  modules/ols-creating-lightspeed-custom-resource-file-using-web-console.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference

#82928 OSDOCS-12214: Remove 10 character project name limit from OSD on GCP
  modules/ccs-gcp-customer-procedure.adoc
  modules/osd-create-cluster-ccs.adoc
Labels: peer-review-done, size/S, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#82929 fixing xref
  installing/overview/installing-preparing.adoc
Labels: branch/enterprise-4.13

#81835 CNV#35090_417: Release note: NEW GA Host-side USB passthrough
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress

#82882 [OCPBUGS-42560] Update command to add the configmap in nodepool
  modules/configuring-node-pools-for-hcp.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82907 reordering TOC to try to fix PV1
  _topic_maps/_topic_map.yml
Labels: size/S, branch/enterprise-4.13

#82720 [enterprise-4.17] CNV#37643: RN - Hot plug memory
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS

#82938 fixing xrefs
  installing/disconnected_install/installing-mirroring-installation-images.adoc
  installing/installing_alibaba/installing-alibaba-customizations.adoc
  installing/installing_alibaba/installing-alibaba-default.adoc
  installing/installing_alibaba/installing-alibaba-network-customizations.adoc
  installing/installing_alibaba/installing-alibaba-vpc.adoc
  installing/installing_aws/installing-aws-china.adoc
  installing/installing_aws/installing-aws-customizations.adoc
  installing/installing_aws/installing-aws-default.adoc
  installing/installing_aws/installing-aws-government-region.adoc
  installing/installing_aws/installing-aws-localzone.adoc
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_aws/installing-aws-outposts-remote-workers.adoc
  installing/installing_aws/installing-aws-private.adoc
  installing/installing_aws/installing-aws-secret-region.adoc
  installing/installing_aws/installing-aws-user-infra.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.adoc
  installing/installing_aws/installing-restricted-networks-aws.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-default.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/overview/index.adoc
  installing/overview/installing-preparing.adoc
  modules/viewing-the-image-pull-source.adoc
Labels: size/M, branch/enterprise-4.14

#82760 OSDOCS#12186: Remove the mention of replicas:0 in the nodepool
  modules/hcp-nodepool-hc.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82541 OSDOCS#12138: Supported openshift versions for hosted clusters
  hosted_control_planes/hcp-updating.adoc
  modules/hcp-get-ocp-channel.adoc
  modules/hcp-get-upgrade-versions.adoc
  modules/hcp-update-node-pools.adoc
  modules/hcp-update-ocp-hc.adoc
  modules/hcp-update-using-mce-console.adoc
  modules/hcp-updating-requirements.adoc
Labels: peer-review-done, size/L, ok-to-merge, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82395 OSDOCS#11326: Release notes for OSSO 1.3.1
  nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17

#82749 [DOCS] OSSM-8201- 2.5.x release notes Istio version update
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#82776 Minor edits as follow-up to WMCO hiding docs from 10.17
  installing/installing_aws/ipi/installing-aws-network-customizations.adoc
  installing/installing_azure/ipi/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/ipi/installing-azure-stack-hub-network-customizations.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82601 OSDOCS-11794: ROSA CLI security refinements adding CLI output examples - UPDATE
  modules/rosa-sts-account-wide-roles-and-policies.adoc
Labels: peer-review-done, size/M, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#82436 OSDOCS 12042: Added release note update for supporting partition placement group in AWS
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#82751 [DOCS] OSSM-8201- 2.5.x release notes Istio version update
  modules/ossm-release-2-5-2.adoc
  modules/ossm-release-2-5-3.adoc
  modules/ossm-release-2-5-4.adoc
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82464 CFE 1136: Removed ExternalRouteCertificate from the understanding feature gates section
  modules/nodes-cluster-enabling-features-about.adoc
Labels: peer-review-done, lgtm, size/XS

#82241 OSDOCS#10927: Adding support for secrets store with GCP
  modules/secrets-store-aws.adoc
  modules/secrets-store-azure.adoc
  modules/secrets-store-google.adoc
  modules/secrets-store-providers.adoc
  modules/secrets-store-vault.adoc
  nodes/pods/nodes-pods-secrets-store.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#80452 OBSDOCS-1229: Correct the name of the mentioned exporter
  main
  observability/otel/otel-collector/otel-collector-exporters.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#82617 OSDOCS-11751: adds 4.14.38 relnotes Microshift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14

#82213 WIP: [MULTIARCH-4995] ABI documentation updates for 4.17
  installing/installing_with_agent_based_installer/prepare-pxe-assets-agent.adoc
  modules/adding-ibmz-lpar-agent.adoc
  modules/configuring-network-overrides-ibmz.adoc
  modules/installing-ocp-agent-ibm-z-kvm.adoc
  modules/installing-ocp-agent-ibm-z-zvm.adoc
  modules/installing-ocp-agent-ibm-z.adoc
Labels: peer-review-done, size/L, do-not-merge/work-in-progress, merge-review-in-progress, merge-review-needed, branch/enterprise-4.17, branch/enterprise-4.18

#82992 [enterprise-4.13] Minor edits as follow-up to WMCO hiding docs from 10.17
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
Labels: size/S

#82555 Adding GCP as available to use with the SSCSI operator
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#82942 OSDOCS#10994: rewording cert-manager Operator prereq
  modules/cert-manager-certificate-api-server.adoc
  modules/cert-manager-certificate-ingress.adoc
  modules/cert-manager-configure-cloud-credentials-aws-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  modules/cert-manager-configure-cpu-memory.adoc
  modules/cert-manager-configuring-routes.adoc
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  modules/cert-manager-override-flag-controller.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82998 [enterprise-4.14] Minor edits as follow-up to WMCO hiding docs from 10.17
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
Labels: size/S, branch/enterprise-4.14

#82990 [enterprise-4.12] Minor edits as follow-up to WMCO hiding docs from 10.17
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
Labels: size/XS, branch/enterprise-4.12

#83006 [enterprise-4.15] Minor edits as follow-up to WMCO hiding docs from 10.17
  installing/installing_aws/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/S

#83018 [enterprise-4.14] OSDOCS#10994: rewording cert-manager Operator prereq
  modules/cert-manager-certificate-api-server.adoc
  modules/cert-manager-certificate-ingress.adoc
  modules/cert-manager-configure-cloud-credentials-aws-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  modules/cert-manager-configure-cpu-memory.adoc
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  modules/cert-manager-override-flag-controller.adoc
Labels: size/S

#83017 [enterprise-4.15] OSDOCS#10994: rewording cert-manager Operator prereq
  modules/cert-manager-certificate-api-server.adoc
  modules/cert-manager-certificate-ingress.adoc
  modules/cert-manager-configure-cloud-credentials-aws-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  modules/cert-manager-configure-cpu-memory.adoc
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  modules/cert-manager-override-flag-controller.adoc
Labels: size/S

#83019 [enterprise-4.13] OSDOCS#10994: rewording cert-manager Operator prereq
  modules/cert-manager-certificate-api-server.adoc
  modules/cert-manager-certificate-ingress.adoc
  modules/cert-manager-configure-cloud-credentials-aws-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  modules/cert-manager-configure-cpu-memory.adoc
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  modules/cert-manager-override-flag-controller.adoc
Labels: size/S

#79344 [SRVCOM-3149] Change sidecar injection from annotations to labels
  modules/serverless-ossm-installing-and-configuring-openshift-serverless.adoc
  modules/serverless-ossm-setup.adoc
Labels: peer-review-done, size/M, serverless, merge-review-in-progress

#83020 [enterprise-4.12] OSDOCS#10994: rewording cert-manager Operator prereq
  modules/cert-manager-configure-cloud-credentials-aws-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-non-sts.adoc
  modules/cert-manager-configure-cloud-credentials-gcp-sts.adoc
  modules/cert-manager-configure-cpu-memory.adoc
  modules/cert-manager-enable-operand-log-level.adoc
  modules/cert-manager-enable-operator-log-level.adoc
  modules/cert-manager-override-flag-controller.adoc
Labels: size/S

#82771 OLS-1104: Update api token parameter
  modules/ols-creating-the-credentials-secret-using-cli.adoc
  modules/ols-creating-the-credentials-secret-using-web-console.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference

#83013 OSDOCS-12217: adds oc to prereqs embed for offline use
  modules/microshift-embed-images-offline-use.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82939 OCPBUGS-42711 Removing snippet from 4.15 branch
  nodes/pods/run_once_duration_override/index.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-install.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-uninstall.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.15

#82927 OSDOCS-12215 Removing unsupported RODOO versions from 4.17 branch
  nodes/pods/run_once_duration_override/run-once-duration-override-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed

#82880 [enterprise-4.17] CNV#40187: RN - VM eviction strategies
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#82567 [RHACS] [Docs] [4.5 and later versions] ROX-21863: Setting up image mirroring for registries
  modules/common-attributes.adoc
  modules/configuring-delegated-image-scanning.adoc
  modules/redirecting-image-pulls-from-a-source-registry-to-a-mirrored-registry.adoc
  modules/scanning-images-by-using-secured-clusters.adoc
  operating/examine-images-for-vulnerabilities.adoc
Labels: peer-review-done, size/L, RHACS, merge-review-in-progress, jira/valid-reference

#83034 PLMCORE-10438: Clarifying that the referenced metrics are Prometheus
  modules/nw-metallb-metrics.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#83016 OSDOCS-12131-416: adds immutable setting note to configuration doc
  microshift_configuring/microshift-using-config-tools.adoc
  modules/microshift-default-settings.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/valid-reference

#83015 OSDOCS-12131: adds immutable setting note to configuration doc
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift-using-config-yaml.adoc
  microshift_configuring/microshift_low_latency/microshift-low-latency.adoc
  microshift_install_rpm/microshift-install-rpm.adoc
  microshift_networking/microshift-cni.adoc
  microshift_networking/microshift-nw-router.adoc
  modules/microshift-default-settings.adoc
  snippets/microshift-greenboot-status-snip.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#83021 alphabetizes modules in the cluster capabilities assembly (4.16+)
  installing/overview/cluster-capabilities.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83023 alphabetizes modules in the cluster capabilities assembly (4.15)
  installing/overview/cluster-capabilities.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#83024 alphabetizes and labels modules in the cluster capabilities assembly (4.14)
  installing/overview/cluster-capabilities.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.14

#83025 labels modules in the cluster capabilities assembly (4.13)
  installing/overview/cluster-capabilities.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#83026 labels modules in the cluster capabilities assembly (4.12)
  installing/overview/cluster-capabilities.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12

#82960 OSSM-8224: change labelSelectors to memberSelector
  modules/ossm-about-adding-namespace.adoc
  modules/ossm-deploy-cluster-wide-mesh.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82940 OCPBUGS-42711 removing snippets
  nodes/pods/run_once_duration_override/index.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-install.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-release-notes.adoc
  nodes/pods/run_once_duration_override/run-once-duration-override-uninstall.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.16

#83005 [enterprise-4.16] Update oc edit command from the "Scaling down the data plane to zero"
  modules/scale-down-data-plane.adoc
Labels: size/XS

#83004 [enterprise-4.15] Update oc edit command from the "Scaling down the data plane to zero"
  modules/scale-down-data-plane.adoc
Labels: size/XS

#83003 [enterprise-4.14] Update oc edit command from the "Scaling down the data plane to zero"
  modules/scale-down-data-plane.adoc
Labels: size/XS

#82678 HCIDOCS-139: Fix nohup command in network config for IPI/bare metal installation
  modules/ipi-install-configuring-networking.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82995 OSDOCS-12134: 4.14.38 z-stream RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#83027 Fixing unresolved attribute
  modules/configuring-network-overrides-ibmz.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#83035 CNV#40187: Remove TP from cluster eviction
  modules/virt-configuring-cluster-eviction-strategy-cli.adoc
  virt/nodes/virt-node-maintenance.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#82958 OSDOCS#12222: Update acm 2.10 links to 2.11 for enterprise-4.16
  hosted_control_planes/hcp-getting-started.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.16

#82972 OSDOCS-11945: adds 4.18 MicroShift relnotes build file to main
  _topic_maps/_topic_map_ms.yml
  microshift_release_notes/microshift-4-18-release-notes.adoc
  microshift_welcome/index.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#82742 [OSDOCS-12177] removing firewall prereqs
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
  modules/rosa-hcp-firewall-prerequisites.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#83071 [enterprise-4.16]PLMCORE-10438: Clarifying that the referenced metrics are Prometheus
  modules/nw-metallb-metrics.adoc
Labels: size/XS, jira/valid-reference

#83072 [enterprise-4.14]PLMCORE-10438: Clarifying that the referenced metrics are Prometheus
  modules/nw-metallb-metrics.adoc
Labels: size/XS, jira/valid-reference

#82971 OSDOCS-11946: adds MicroShift 4.18 relnotes file to branch
  _topic_maps/_topic_map_ms.yml
  microshift_release_notes/microshift-4-17-release-notes.adoc
  microshift_release_notes/microshift-4-18-release-notes.adoc
  microshift_welcome/index.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#78824 [SRVKS-962] Add docs on setting timeouts for revisions
  _topic_maps/_topic_map.yml
  knative-serving/config-applications/configuring-revision-timeouts.adoc
  modules/configuring-maximum-revision-timeout.adoc
  modules/configuring-revision-timeout.adoc
Labels: peer-review-done, size/M, serverless

#83074 [enterprise-4.13]PLMCORE-10438: Clarifying that the referenced metrics are Prometheus
  modules/nw-metallb-metrics.adoc
Labels: size/XS, jira/valid-reference

#83075 [enterprise-4.12]PLMCORE-10438: Clarifying that the referenced metrics are Prometheus
  modules/nw-metallb-metrics.adoc
Labels: size/XS, jira/valid-reference

#81819 OSDOCS-11609 NodePort Service noted in considerations
  modules/nw-aws-load-balancer-operator-considerations.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82468 OCPBUGS#33115: Update backup/restore, disaster recovery for HCP
  modules/hcp-recover-failing-etcd-pods.adoc
  modules/hosted-cluster-etcd-status.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#80341 TELCODOCS-1750: Refactoring the performance profile section for the content improvement initiative
  modules/cnf-about-the-profile-creator-tool.adoc
  modules/cnf-creating-mcp-for-ppc.adoc
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-performance-profile-creator-arguments.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/cnf-telco-core-reference-design-performance-profile-template.adoc
  modules/cnf-telco-ran-reference-design-performance-profile-template.adoc
  scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#83067 OCPBUGS#42773:updates RN with masquerade subnet
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#82908 ROX-26244: bug fix for ROX-26244
  modules/policy-criteria.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.4, rhacs-docs-4.5

#82232 OCPBUGS#33927: Add long-lived token/secret step to OLM policy scoping
  modules/olm-policy-scoping-operator-install.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83123 [enterprise-4.15] TELCODOCS-1750: Refactoring the performance profile section for the content improvement initiative
  modules/cnf-about-the-profile-creator-tool.adoc
  modules/cnf-creating-mcp-for-ppc.adoc
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-performance-profile-creator-arguments.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/cnf-telco-core-reference-design-performance-profile-template.adoc
  modules/cnf-telco-ran-reference-design-performance-profile-template.adoc
  scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.adoc
Labels: size/XL, jira/valid-reference

#83124 [enterprise-4.14] TELCODOCS-1750: Refactoring the performance profile section for the content improvement initiative
  modules/cnf-about-the-profile-creator-tool.adoc
  modules/cnf-creating-mcp-for-ppc.adoc
  modules/cnf-gathering-data-about-cluster-using-must-gather.adoc
  modules/cnf-how-run-podman-to-create-profile.adoc
  modules/cnf-performance-profile-creator-arguments.adoc
  modules/cnf-running-the-performance-creator-profile-offline.adoc
  modules/cnf-running-the-performance-creator-profile.adoc
  modules/cnf-telco-core-reference-design-performance-profile-template.adoc
  modules/cnf-telco-ran-reference-design-performance-profile-template.adoc
  scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.adoc
Labels: size/XL, jira/valid-reference

#83014 Remove empty file accidentally added
  main
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#81964 RHDEVDOCS 6173 remove incorrect statement about task resource consumption
  modules/op-understanding-pipelines-resource-consumption.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, pipelines

#83126 [enterprise-4.17] Syncing RDS files across main, current and future versions
  modules/telco-ran-yaml-ref-machine-configuration.adoc
  snippets/ztp_ClusterLogging.yaml
Labels: size/S, branch/enterprise-4.17

#83125 [enterprise-4.18] Syncing RDS files across main, current and future versions
  modules/telco-ran-yaml-ref-machine-configuration.adoc
  snippets/ztp_ClusterLogging.yaml
Labels: size/S, branch/enterprise-4.18

#83143 [enterprise-4.17] Fixing broken RDS xref
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-design-components.adoc
Labels: size/XS, branch/enterprise-4.17

#83144 [enterprise-4.18] Fixing broken RDS xref
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-design-components.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-components.adoc
Labels: size/XS, branch/enterprise-4.18

#83120 Syncing RDS files across main, current and future versions
  modules/telco-ran-yaml-ref-machine-configuration.adoc
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-design-components.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-components.adoc
  snippets/ztp_ClusterLogging.yaml
Labels: size/S

#83115 OLS-1118: Update label for RHOAI in OLSConfig
  modules/ols-creating-lightspeed-custom-resource-file-using-cli.adoc
  modules/ols-creating-lightspeed-custom-resource-file-using-web-console.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-needed, jira/valid-reference

#83134 OSDOCS-11864: remove unneeded and confusing line from adding RHEL compute
  modules/rhel-compute-overview.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83156 Syncing RDS files
  modules/telco-ran-yaml-ref-machine-configuration.adoc
Labels: size/XS

#83122 OSSM-8133 [DOC] OSSM 3.0-TP2: Add link to Sail operator user documentation as "Additional Resource"
  modules/ossm-customizing-istio-configuration.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#82442 OSSM- 7920 OSSM 2.6.2 (At Stage): [DOC] Release Notes, Known Issues and Bug Fixes
  _attributes/common-attributes.adoc
  modules/ossm-release-2-4-11.adoc
  modules/ossm-release-2-5-5.adoc
  modules/ossm-release-2-6-0.adoc
  modules/ossm-release-2-6-1.adoc
  modules/ossm-release-2-6-2.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#82690 OSDOCS-12181:Added FIPS cryptography option in create classic cluster ROSA CLI workflow.
  modules/rosa-sts-creating-a-cluster-with-customizations-cli.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#82758 TELCODOCS-1949 - RHACM support for templates changes from partial ful…
  edge_computing/ztp-using-hub-cluster-templates.adoc
  modules/ztp-example-hub-template-functions.adoc
  modules/ztp-specifying-nics-in-pgt-crs-with-hub-cluster-templates.adoc
  modules/ztp-using-rhacm-hub-cluster-templates.adoc
Labels: peer-review-done, size/M, telco, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#79150 RHDEVDOCS 5985 changes for HashiCorp Vault integration
  _attributes/common-attributes.adoc
  modules/op-creating-mounting-kms-authentication-token-secret.adoc
  modules/op-creating-mounting-mongo-server-url-secret.adoc
  modules/op-supported-parameters-tekton-chains-configuration.adoc
  secure/using-tekton-chains-for-openshift-pipelines-supply-chain-security.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, pipelines

#83142 [SRVOCF-617] Update installing func-s2i and func-deploy tasks
  modules/odc-creating-functions.adoc
Labels: peer-review-done, size/S, serverless

#82943 RHDEVDOCS 6195 configure LokiStack log forwarding when installing Results
  modules/op-installing-results.adoc
  modules/op-results-storage.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, pipelines

#81537 OCPBUGS-34048:clarifies multi network NAD creation for localnet
  modules/configuring-localnet-switched-topology.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82682 OBSDOCS-1301: Logging Z-Stream Release Notes - 5.6.24
  modules/logging-release-notes-5-6-24.adoc
  observability/logging/logging_release_notes/logging-5-6-release-notes.adoc
Labels: peer-review-done, size/M, ok-to-merge, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#83185 advisory link patch
  modules/logging-release-notes-5-6-24.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13

#83188 ROX-24169: migrate OCM cloud source to service account
  modules/cloud-management-platforms-ocm.adoc
Labels: size/XS, jira/valid-reference

#83190 OSDOCS-12282: Follow-up to OSD-25873/OSDOCS-12177
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
  modules/rosa-hcp-firewall-prerequisites.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17

#81470 OSDOCS#11815: VCF versions added
  modules/installation-vsphere-infrastructure.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83199 OSDOCS#11815: VCF versions added
  modules/installation-vsphere-infrastructure.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#83200 [enterprise-4.13] OSDOCS#11815: VCF version addition
  modules/installation-vsphere-infrastructure.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: size/S

#83201 [enterprise-4.12] OSDOCS#11815: VCF version addition
  modules/installation-vsphere-infrastructure.adoc
  modules/vmware-csi-driver-reqs.adoc
Labels: size/S

#83146 TELCODOCS-1887-release-note
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#83211 TThe > The typo fixes
  edge_computing/image-base-install/ibi-understanding-image-based-install.adoc
  modules/installation-nutanix-config-yaml.adoc
  modules/nw-ovn-k-adminnetwork-policy-action-rules.adoc
Labels: size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#79033 RHDEVDOCS 6104 support for StepActions
  _attributes/common-attributes.adoc
  about/understanding-openshift-pipelines.adoc
  create/remote-pipelines-tasks-resolvers.adoc
  modules/op-about-stepactions.adoc
  modules/op-resolver-bundle.adoc
  modules/op-resolver-cluster.adoc
  modules/op-resolver-git-anon.adoc
  modules/op-resolver-git-scm.adoc
  modules/op-resolver-http.adoc
  modules/op-resolver-hub.adoc
  modules/op-resolver-stepactions-ref.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed

#83218 OSDOCS-12285.1:Updated HCP topic map
  _topic_maps/_topic_map_rosa_hcp.yml
Labels: size/XS

#82841 OSDOCS#11850: migrating disconnected OLM content
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/aws-sts/oadp-aws-sts.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-kubevirt.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  disconnected/connected-to-disconnected.adoc
  disconnected/mirroring/installing-mirroring-installation-images.adoc
  disconnected/updating/disconnected-update-osus.adoc
  disconnected/updating/disconnected-update.adoc
  disconnected/using-olm.adoc
  edge_computing/ztp-preparing-the-hub-cluster.adoc
  extensions/catalogs/creating-catalogs.adoc
  installing/installing_aws/ipi/installing-restricted-networks-aws-installer-provisioned.adoc
  installing/installing_aws/upi/installing-restricted-networks-aws.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
  installing/installing_gcp/installing-restricted-networks-gcp.adoc
  installing/installing_openstack/installing-openstack-installer-restricted.adoc
  installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
  migrating_from_ocp_3_to_4/installing-restricted-3-4.adoc
  migration_toolkit_for_containers/installing-mtc-restricted.adoc
  nodes/nodes/ecosystems/eco-node-health-check-operator.adoc
  nodes/nodes/ecosystems/eco-node-maintenance-operator.adoc
  nodes/nodes/ecosystems/eco-self-node-remediation-operator.adoc
  operators/admin/olm-cs-podsched.adoc
  operators/admin/olm-managing-custom-catalogs.adoc
  operators/admin/olm-restricted-networks.adoc
  operators/admin/olm-upgrading-operators.adoc
  operators/index.adoc
  operators/understanding/olm-rh-catalogs.adoc
  security/compliance_operator/co-management/compliance-operator-installation.adoc
  security/compliance_operator/co-management/compliance-operator-manage.adoc
  security/file_integrity_operator/file-integrity-operator-installation.adoc
  serverless/install/preparing-serverless-install.adoc
  virt/backup_restore/virt-backup-restore-overview.adoc
  virt/install/installing-virt.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#83173 Adds a warning not to automate the migration
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#82875 CNV-49363: Release note: (two notes) New focused view and guided tour in OpenShift Virtualization
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, jira/valid-reference, branch/enterprise-4.17
