Repository openshift/openshift-docs, pull requests merged in 2024-05, with the labels that each got.

#74821 OADP 3905 - Azure missing steps
  modules/migration-configuring-azure.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75377 OSDOCS-10406: updating and re-enabling the gather data support page
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  modules/about-must-gather.adoc
  modules/gathering-data-network-logs.adoc
  modules/gathering-data-specific-features.adoc
  modules/querying-cluster-node-journal-logs.adoc
  modules/support-collecting-host-network-trace.adoc
  modules/support-collecting-network-trace.adoc
  modules/support-gather-data.adoc
  modules/support-get-cluster-id.adoc
  modules/support-providing-diagnostic-data-to-red-hat.adoc
  modules/support-submitting-a-case.adoc
  observability/logging/cluster-logging-support.adoc
  security/audit-log-view.adoc
  support/gathering-cluster-data.adoc
Labels: peer-review-done, size/L, jira/valid-reference, SD-docs, branch/enterprise-4.15, branch/enterprise-4.16

#75137 MIG-1509: MTC 1.7.15 Release Notes
  migration_toolkit_for_containers/mtc-release-notes.adoc
  modules/migration-mtc-release-notes-1-7-15.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-needed, MTC, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#70982 CNV#37086: HCO 4.12.11
  _attributes/common-attributes.adoc
Labels: size/XS, CNV, branch/enterprise-4.12

#74872 TELCODOCS-1690 - support node deletion via gitops ztp
  edge_computing/ztp-advanced-install-ztp.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75372 ocpbugs32742: removing redundant sentence
  modules/nw-networkpolicy-multitenant-isolation.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75094 OSSM-6347: SM 3.0 Deploying Istio
  _attributes/common-attributes.adoc
  install/ossm-installing-openshift-service-mesh.adoc
  modules/ossm-about-istio-deployment.adoc
  modules/ossm-creating-istio-cni-project-using-console.adoc
  modules/ossm-creating-istio-project-using-console.adoc
  modules/ossm-creating-istio-resource-using-console.adoc
  modules/ossm-creating-istiocni-resource-using-console.adoc
Labels: size/L, jira/valid-reference

#75398 OSDOCS 10426 fix exit code in case of an ERROR message in build_for_portal.py
  build_for_portal.py
Labels: size/S

#75160 OSDOCS-9910:updates support limitations for InFW on AWS
  modules/nw-infw-operator-cr.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#74877 OCPBUGS-32475: Remove direct AI OCI steps from RH docs
  installing/installing_oci/installing-oci-assisted-installer.adoc
  modules/complete-assisted-installer-oci.adoc
  modules/creating-oci-infra-resources-services.adoc
  modules/creating-oci-resources-services.adoc
  modules/downloading-manifest-files-resources-oci.adoc
  modules/installation-vsphere-infrastructure.adoc
  modules/installing-oci-about-agent-based-installer.adoc
  modules/installing-oci-about-assisted-installer.adoc
  modules/installing-troubleshooting-assisted-installer-oci.adoc
  modules/provision-oci-infrastructure-ocp-cluster.adoc
  modules/running-cluster-oci-agent-based.adoc
  modules/using-assisted-installer-oci-agent-iso.adoc
  modules/verifying-cluster-install-ai-oci.adoc
Labels: peer-review-done, size/L, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75245 OBSDOCS-973 - Logging 5.6.18 Release Notes
  modules/logging-release-notes-5-6-18.adoc
  observability/logging/logging_release_notes/logging-5-6-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13

#73708 RHDEVDOCS-5627: Adds missing 4.15 release note for builds
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.15

#75242 OBSDOCS-1008 - 5.9.1 Release Notes
  modules/logging-release-notes-5-9-1.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75451 [internal fix] missing-agent-eval-table
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75440 OSDOCS#10440: Added eu-west-3 region to ROSA with HCP docs
  modules/rosa-sdpolicy-am-regions-az.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#75243 OBSDOCS-975 - Logging 5.8.6 Release Notes
  modules/logging-release-notes-5-8-6.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#75348 OSDOCS-10365: 4.14.23 RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#75293 OSDOCS-10366 OCP Core 4.13.41 RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#75244 OBSDOCS-974 - Logging 5.7.13 Release Notes
  modules/logging-release-notes-5-7-13.adoc
  observability/logging/logging_release_notes/logging-5-7-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed

#75450 [enterprise-4.12] manual cherry-pick OSDOCS-9910:updates support limitations for InFW on AWS
  modules/nw-infw-operator-cr.adoc
Labels: size/XS, jira/valid-reference

#75449 [enterprise-4.13]manual cp of OSDOCS-9910:updates support limitations for InFW on AWS
  modules/nw-infw-operator-cr.adoc
Labels: size/XS, jira/valid-reference

#75445 [enterprise-414] manual cp of OSDOCS-9910:updates support limitations for InFW on AWS
  modules/nw-infw-operator-cr.adoc
Labels: size/XS, jira/valid-reference

#73787 TELCODOCS-1485: Updates to reflect new backend remediation process by TALM
  modules/cnf-about-topology-aware-lifecycle-manager-blocking-crs.adoc
  modules/cnf-topology-aware-lifecycle-manager-apply-policies.adoc
  modules/cnf-topology-aware-lifecycle-manager-installation-cli.adoc
  modules/cnf-topology-aware-lifecycle-manager-installation-web-console.adoc
  modules/cnf-topology-aware-lifecycle-manager-policies-concept.adoc
  modules/cnf-topology-aware-lifecycle-manager-troubleshooting.adoc
Labels: peer-review-done, size/L, telco, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16

#75336 OSDOCS-10364: Documented the 4.15.11 z-stream release notes
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15

#75366 [OSDOCS-10334]:ROSA with HCP Upgrade Section
  upgrading/rosa-hcp-upgrading.adoc
Labels: peer-review-done, size/XS, SD-docs, branch/enterprise-4.15, branch/enterprise-4.16

#74910 OCPBUGS-32490: Removed OCI steps from ABI docs
  installing/installing_oci/installing-oci-agent-based-installer.adoc
  modules/abi-oci-resources-services.adoc
  modules/creating-config-files-cluster-install-oci.adoc
  modules/creating-oci-infra-resources-services.adoc
  modules/installing-oci-about-agent-based-installer.adoc
  modules/running-cluster-oci-agent-based.adoc
  modules/using-assisted-installer-oci-agent-iso.adoc
  modules/verifying-cluster-install-oci-agent-based.adoc
Labels: peer-review-done, size/L, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75473 OSDOCS-10448: Create attribute set for CAPI providers
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75504 [enterprise-4.15] OSDOCS-10448: Create attribute set for CAPI providers
  _attributes/common-attributes.adoc
Labels: size/M, jira/valid-reference

#75412 TELCODOCS-1825: Add a webhook for namespace deletion
  modules/kmm-unloading-kernel-module.adoc
Labels: peer-review-done, size/XS, telco, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75507 [enterprise-4.13] OSDOCS-10448: Create attribute set for CAPI providers
  _attributes/common-attributes.adoc
Labels: size/M, jira/valid-reference

#75508 [enterprise-4.14] OSDOCS-10448: Create attribute set for CAPI providers
  _attributes/common-attributes.adoc
Labels: size/M, jira/valid-reference

#75512 replace CAPO with attribute
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15

#75472 MIG-1539: incorrect command in modules/migration-migrating-applications-api.adoc
  modules/migration-migrating-applications-api.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, MTC, jira/valid-reference

#74999 OCPBUGS#32582: Removes accidental addition of multicluster TP entry from 4.15 release notes
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, branch/enterprise-4.15

#73013 OSSM-6086: Formatting issue in federation gateway parameters table
  modules/ossm-federation-config-smcp.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75174 OSDOCS#6251: Release note for warning on duplicate short names
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.16

#75041 OSDOCS#10117: Doc sweep for updating to Kubernetes 1.29
  metering/configuring_metering/metering-common-config-options.adoc
  modules/ai-adding-worker-nodes-to-cluster.adoc
  modules/aws-outposts-load-balancer-clb.adoc
  modules/capi-machine-set-creating.adoc
  modules/cleaning-crio-storage.adoc
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/compliance-apply-remediation-for-customized-mcp.adoc
  modules/connected-to-disconnected-verify.adoc
  modules/coreos-layering-configuring.adoc
  modules/coreos-layering-removing.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/graceful-restart.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-registry-mirror-configuring.adoc
  modules/infrastructure-moving-router.adoc
  modules/install-sno-monitoring-the-installation-manually.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/machine-node-custom-partition.adoc
  modules/nodes-clusters-cgroups-2.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-scheduler-node-selectors-cluster.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nodes-scheduler-node-selectors-project.adoc
  modules/nvidia-gpu-aws-adding-a-gpu-node.adoc
  modules/nvidia-gpu-azure-adding-a-gpu-node.adoc
  modules/nvidia-gpu-gcp-adding-a-gpu-node.adoc
  modules/nw-sriov-hwol-configuring-machine-config-pool.adoc
  modules/olm-catalogsource-image-template.adoc
  modules/querying-the-status-of-cluster-nodes-using-the-cli.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/rhcos-add-extensions.adoc
  modules/rhcos-enabling-multipath-day-2.adoc
  modules/rhel-compute-updating.adoc
  modules/sno-adding-worker-nodes-to-sno-clusters-manually.adoc
  modules/update-upgrading-cli.adoc
  modules/update-vsphere-virtual-hardware-on-compute-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-control-plane-nodes.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.16

#71991 OCPBUGS#29657: Mention known issues while moving etcd to a different disk
  modules/move-etcd-different-disk.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75516 OCPBUGS-9064:Carriage Return / Newline in Custom Ingress Certificate
  modules/customize-certificates-replace-default-router.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75491 OSDOCS-10456: Clarify CPMS AWS and Azure specs for ext LB
  modules/cpmso-yaml-provider-spec-aws.adoc
  modules/cpmso-yaml-provider-spec-azure.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75563 [enterprise-4.14] OSDOCS-10456: Clarify CPMS AWS and Azure specs for ext LB
  modules/cpmso-yaml-provider-spec-aws.adoc
  modules/cpmso-yaml-provider-spec-azure.adoc
Labels: size/S, jira/valid-reference

#75556 OCPBUGS-33313:removes SSH as limitation from InFW webhook
  modules/nw-infw-operator-rules-object.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16

#75380 [virt] DPDK Checkup: Update upstream image tags
  modules/virt-checking-cluster-dpdk-readiness.adoc
  modules/virt-dpdk-config-map-parameters.adoc
Labels: peer-review-done, lgtm, size/S, CNV, branch/enterprise-4.16

#74800 OCPBUGS#32312: Adds missing mentions of service proxy in dynamic plugin docs
  modules/dynamic-plugin-api.adoc
  modules/dynamic-plugin-proxy-service.adoc
  web_console/dynamic-plugin/deploy-plugin-cluster.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.15, branch/enterprise-4.16

#74831 [RHACS] ROX-21700: Updating documentation for ACSCS certificate rotation
  cloud_service/installing_cloud_ocp/init-bundle-cloud-ocp-apply.adoc
  cloud_service/installing_cloud_ocp/init-bundle-cloud-ocp-generate.adoc
  cloud_service/installing_cloud_other/init-bundle-cloud-other-apply.adoc
  cloud_service/installing_cloud_other/init-bundle-cloud-other-generate.adoc
  installing/installing_ocp/init-bundle-ocp.adoc
  installing/installing_other/init-bundle-other.adoc
  modules/configuring-and-using-the-roxctl-cli-in-rhacs-cloud-service.adoc
  modules/create-resource-init-bundle.adoc
  modules/roxctl-generate-init-bundle.adoc
Labels: peer-review-in-progress, size/L, RHACS, jira/valid-reference, rhacs-docs-4.3, rhacs-docs-4.4, rhacs-docs-4.5

#74365 CNV-13710: Configuring cluster for real-time workloads
  _topic_maps/_topic_map.yml
  modules/virt-configuring-cluster-real-time.adoc
  modules/virt-configuring-vm-real-time.adoc
  virt/virtual_machines/advanced_vm_management/virt-configuring-cluster-realtime-workloads.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.16

#75570 [enterprise-4.13] Resolve merge conflict for OCPBUGS-29657
  modules/move-etcd-different-disk.adoc
Labels: size/L

#75568 [enterprise-4.14] Resolve merge conflict for OCPBUGS-29657
  modules/move-etcd-different-disk.adoc
Labels: size/L

#74541 HCIDOCS-122: SNO Networking Requirements Update
  installing/installing_sno/install-sno-installing-sno.adoc
  modules/install-sno-generating-the-install-iso-manually.adoc
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75577 WMCO 10.15.2 RN Fix Link
  windows_containers/windows-containers-release-notes-10-15-x.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15

#75329 [RHACS] Update Alpine Linux version format in release notes
  release_notes/44-release-notes.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.4

#70384 RHDEVDOCS 4233 add information on Pipelines authentication using workspaces, container registries
  _topic_maps/_topic_map.yml
  about/understanding-openshift-pipelines.adoc
  create/creating-applications-with-cicd-pipelines.adoc
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/op-about-pipelinerun.adoc
  modules/op-configuring-basic-authentication-for-git.adoc
  modules/op-configuring-container-registry-authentication-using-workspaces.adoc
  modules/op-configuring-git-ssh-authentication-using-workspaces.adoc
  modules/op-configuring-registry-authentication-sa.adoc
  modules/op-configuring-ssh-authentication-for-git.adoc
  modules/op-limiting-secret-access-to-specific-steps.adoc
  modules/op-limiting-secret-workspace-to-step.adoc
  modules/op-running-a-pipeline.adoc
  modules/op-types-annotation-secrets.adoc
  modules/op-understanding-credential-selection.adoc
  modules/op-using-secrets-as-a-nonroot-user.adoc
  modules/op-using-ssh-authentication-in-git-type-tasks.adoc
  secure/authenticating-pipelines-repos-using-secrets.adoc
  secure/authenticating-pipelines-using-git-secret.adoc
Labels: peer-review-done, size/XL, dev-tools, merge-review-needed, pipelines

#75365 Removes unnecessary CIDR information in subnet description
  modules/configuration-ovnk-network-plugin-json-object.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75598 [enterprise-4.13] Removes unnecessary CIDR information from subnet parameter
  modules/configuration-ovnk-network-plugin-json-object.adoc
Labels: size/XS, branch/enterprise-4.13

#75258 OADP-3179: Release Notes for OADP 1.2.4
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-2.adoc
  modules/oadp-release-notes-1-2-4.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75488 OBSDOCS-1029
  modules/cluster-logging-collector-limits.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75265 TELCODOCS#1844: Warnings for not configuring the deviceSelector field
  modules/lvms-about-adding-devices-to-a-vg.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#75613 Adding rosa/OSD redirects for observability
  .s2i/httpd-cfg/01-commercial.conf
Labels: peer-review-done, size/XS

#74703 OSDOCS-10429 HCP topic map
  _topic_maps/_topic_map_rosa_hcp.yml
Labels: size/XXL, branch/enterprise-4.15, branch/enterprise-4.16

#75373 OSDOCS-9813: adds custom CA relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#75514 OSDOCS#10460: Document configuring OAuth for the hosted cluster by using the web console
  hosted_control_planes/hcp-authentication-authorization.adoc
  modules/hcp-configuring-oauth-console.adoc
  modules/hcp-configuring-oauth.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75481 RHDEVDOCS 6048 Release Notes for Pipelines 1.14.4
  modules/op-release-notes-1-14.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#75616 [RHACS] [rhacs-docs-4.3] ROX-21700: Updating documentation for Cloud Service certificate rotation
  cloud_service/installing_cloud_ocp/init-bundle-cloud-ocp-apply.adoc
  cloud_service/installing_cloud_ocp/init-bundle-cloud-ocp-generate.adoc
  cloud_service/installing_cloud_other/init-bundle-cloud-other-apply.adoc
  cloud_service/installing_cloud_other/init-bundle-cloud-other-generate.adoc
  installing/installing_ocp/init-bundle-ocp.adoc
  installing/installing_other/init-bundle-other.adoc
  modules/configuring-and-using-the-roxctl-cli-in-rhacs-cloud-service.adoc
  modules/create-resource-init-bundle.adoc
  modules/roxctl-generate-init-bundle.adoc
Labels: size/L, jira/valid-reference

#75615 Fixing tables with no borders
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75644 [enterprise-4.12] WMCO supports English only
  modules/windows-containers-release-notes-limitations.adoc
Labels: size/XS

#75645 [enterprise-4.13] WMCO supports English only
  modules/windows-containers-release-notes-limitations.adoc
Labels: size/XS

#75585 RHDEVDOCS-5819 Update _distro_map.yml
  _distro_map.yml
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, gitops

#75409 RHDEVDOCS 5979 starting pipeline runs manually and on chatops, support OWNERS fully
  modules/op-creating-pipeline-run-using-pipelines-as-code.adoc
  modules/op-restarting-or-canceling-pipeline-run-using-pipelines-as-code.adoc
  modules/op-running-pipeline-run-using-pipelines-as-code.adoc
  pac/about-pipelines-as-code.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#74931 [enterprise-4.14] OCPBUGS#32509: Doc improvements related to installation and uninstallation modules
  modules/lvms-about-lvm-storage-installation.adoc
  modules/lvms-installing-logical-volume-manager-operator-disconnected-environment.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-cli.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-openshift-web-console.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-openshift-web-console.adoc
  snippets/lvms-disconnected-ImageSetConfig.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.14

#75334 Updated yaml and added a couple of notes for clarity
  modules/op-setting-up-openshift-pipelines-to-view-project-vulnerabilities.adoc
Labels: peer-review-done, size/S, ok-to-test, merge-review-in-progress, pipelines

#75658 OCPBUGS-33407 - Adding missing PTP features to TP table
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S

#74871 RHDEVDOCS-5955: Replacing the {product-title} attribute with the {OCP} attribute
  modules/gitops-configuring-sscsi-driver-to-mount-secrets-from-aws-secrets-manager.adoc
  modules/gitops-enabling-dex.adoc
  modules/gitops-keycloak-identity-brokering-with-openshift-oauthclient.adoc
  modules/gitops-registering-an-additional-oauth-client.adoc
  modules/gitops-registering-an-oauth-client.adoc
  modules/gitops-storing-aws-secret-manager-resources-in-gitops-repository.adoc
  modules/go-settings-for-environment-labels-and-annotations.adoc
  release_notes/gitops-release-notes.adoc
  troubleshooting_gitops_issues/auto-reboot-during-argo-cd-sync-with-machine-configurations.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#74937 [enterprise-4.14] OCPBUGS#32522: Doc improvements related to LVMCluster CR
  modules/lvms-about-adding-devices-to-a-vg.adoc
  modules/lvms-about-creating-lvmcluster-cr.adoc
  modules/lvms-about-deleting-lvmcluster-cr.adoc
  modules/lvms-about-lvmcluster-cr.adoc
  modules/lvms-creating-lvms-cluster-using-cli.adoc
  modules/lvms-creating-lvms-cluster-using-web-console.adoc
  modules/lvms-deleting-lvmcluster-using-cli.adoc
  modules/lvms-deleting-lvmcluster-using-web-console.adoc
  modules/lvms-reference-file.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, branch/enterprise-4.14

#75657 Remove docs about disabling web console from ROSA and OSD
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  web_console/web-console-overview.adoc
Labels: size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#75667 OSDOCS-10498 remove disabling web console from HCP Topic Map
  _topic_maps/_topic_map_rosa_hcp.yml
Labels: size/XS

#73839 OSDOCS-9614: Created documentation to create a ROSA with HCP cluster that uses external auth for OIDC
  _attributes/attributes-openshift-dedicated.adoc
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-create-objects.adoc
  modules/rosa-delete-objects.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-delete-cli.adoc
  modules/rosa-list-objects.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16

#75670 [enterprise-4.15] OSDOCS#9614: Created documentation to create a ROSA with HCP cluster …
  _attributes/attributes-openshift-dedicated.adoc
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-create-objects.adoc
  modules/rosa-delete-objects.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-delete-cli.adoc
  modules/rosa-list-objects.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: size/XL, branch/enterprise-4.15

#75671 [enterprise-4.16] OSDOCS#9614: Created documentation to create a ROSA with HCP cluster …
  _attributes/attributes-openshift-dedicated.adoc
  _topic_maps/_topic_map_rosa.yml
  modules/rosa-create-objects.adoc
  modules/rosa-delete-objects.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-delete-cli.adoc
  modules/rosa-list-objects.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: size/XL, branch/enterprise-4.16

#75177 RHDEVDOCS-5912 - Updates to the argo cd CLI installation and reference sections
  _attributes/common-attributes.adoc
  gitops_cli_argocd/argocd-gitops-cli-reference.adoc
  installing_gitops/installing-argocd-gitops-cli.adoc
  modules/gitops-installing-argocd-cli-on-linux-using-rpm.adoc
  modules/gitops-installing-argocd-cli-on-linux.adoc
  modules/gitops-installing-argocd-cli-on-macos.adoc
  modules/gitops-installing-argocd-cli-on-windows.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, gitops

#75330 [enterprise-4.14] OCPBUGS#33113: Doc improvements related to volume cloning/snapshots
  modules/lvms-about-volume-clones.adoc
  modules/lvms-about-volume-snapshots.adoc
  modules/lvms-creating-volume-clones-in-single-node-openshift.adoc
  modules/lvms-creating-volume-clones.adoc
  modules/lvms-creating-volume-snapshots-in-single-node-openshift.adoc
  modules/lvms-creating-volume-snapshots.adoc
  modules/lvms-deleting-cloned-volumes-in-single-node-openshift.adoc
  modules/lvms-deleting-volume-clones.adoc
  modules/lvms-deleting-volume-snapshots-in-single-node-openshift.adoc
  modules/lvms-deleting-volume-snapshots.adoc
  modules/lvms-restoring-volume-snapshots-in-single-node-openshift.adoc
  modules/lvms-restoring-volume-snapshots.adoc
  modules/lvms-volume-clones-in-single-node-openshift.adoc
  modules/lvms-volume-snapshots-in-single-node-openshift.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#75066 [enterprise-4.14] OCPBUGS#32782: Doc improvements related to scaling storage of clusters
  modules/lvms-about-scaling-storage-of-clusters.adoc
  modules/lvms-scaling-storage-of-clusters-using-cli.adoc
  modules/lvms-scaling-storage-of-clusters-using-web-console.adoc
  modules/lvms-scaling-storage-of-single-node-open-concept.adoc
  modules/lvms-scaling-storage-of-single-node-openshift-cluster.adoc
  snippets/lvms-scaling-up-storage-lvmcluster-cr-snippet.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#75672 [test PR] Replaces instance of STS with attribute
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
Labels: size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#75621 OSDOCS#10489: Move the Deleting a hosted cluster section
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-getting-started.adoc
  hosted_control_planes/hcp-managing.adoc
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/delete-hosted-cluster.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75543 [OSDOCS-10464] Remove HCP references in OSD docs
  modules/creating-a-machine-pool-ocm.adoc
  modules/openshift-architecture-common-terms.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-needed, branch/enterprise-4.15, branch/enterprise-4.16

#75456 MIG-1362: Issue in modules/migration-adding-cluster-to-cam.adoc
  modules/migration-adding-cluster-to-cam.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, MTC, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75542 Fix typo in CAS docs
  modules/cluster-autoscaler-cr.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75559 OCPBUGS#33168 Correcting acronyms 4.15.10
  release_notes/ocp-4-15-release-notes.adoc
Labels: size/XS, qe-approved

#75694 [enterprise-4.15] Fix typo in CAS docs
  modules/cluster-autoscaler-cr.adoc
Labels: size/XS

#75537 OCPBUGS#31543: Adding TopoLVM to the storage tables
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75693 [enterprise-4.14] Fix up LVMS xref due to out-of-sequence PR merging
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#75692 [enterprise-4.12] Mention known issues while moving etcd to a different disk
  modules/move-etcd-different-disk.adoc
Labels: size/L

#75690 OSDOCS-9614.2: HCP Ext Auth Cleanup
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-ext-auth-provider-delete-cli.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: lgtm, size/S, branch/enterprise-4.15, branch/enterprise-4.16

#75515 OSDOCS-9801: New Diagram for HCP Architecture Section
  images/ROSA-HCP-architecture-model.png
  modules/rosa-hcp-architecture.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16

#75483 OBSDOCS-1009 List MS Teams as a supported receiver for monitoring alerts
  modules/monitoring-sending-notifications-to-external-systems.adoc
  post_installation_configuration/configuring-alert-notifications.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16

#75498 OCPBUGS#33258: Adding back in support for the descheduler in OKE
  nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc
  welcome/oke_about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#75033 OSDOCS-7074: Documented external LB for managing api/ingress traffic
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-post-installation-configuration.adoc
  installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations.adoc
  modules/installation-launching-installer.adoc
  modules/installation-load-balancing-user-infra.adoc
  modules/installation-osp-balancing-external-loads.adoc
  modules/nw-osp-configuring-external-load-balancer.adoc
  modules/nw-osp-services-external-load-balancer.adoc
  networking/load-balancing-openstack.adoc
  rest_api/operator_apis/ingresscontroller-operator-openshift-io-v1.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#75711 [enterprise-4.13] OCPBUGS#31543: Adding TopoLVM to the storage tables
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: size/XS

#75709 [enterprise-4.12] OCPBUGS#31543: Adding TopoLVM to the storage tables
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: size/S

#75712 [enterprise-4.14] OSDOCS#10489: Move the Deleting a hosted cluster section
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-getting-started.adoc
  hosted_control_planes/hcp-managing.adoc
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/delete-hosted-cluster.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#74394 CNV_30921: Document new behaviour of must-gather
  modules/virt-must-gather-options.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#75109 OSDOCS-10271: VMware CPMS TP to GA RN table
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.16

#75232 OSDOCS-8931: Detail step for adding IPv6 to existing dual-stack clusters
  modules/nw-dual-stack-convert.adoc
  networking/ovn_kubernetes_network_provider/converting-to-dual-stack.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16

#75716 {gitops-docs-1.9} RHDEVDOCS-5955: Removal of the {product-title} attribute in the content
  modules/gitops-enabling-dex.adoc
  modules/gitops-keycloak-identity-brokering-with-openshift-oauthclient.adoc
  modules/gitops-registering-an-additional-oauth-client.adoc
  modules/gitops-registering-an-oauth-client.adoc
  modules/go-settings-for-environment-labels-and-annotations.adoc
  troubleshooting_gitops_issues/auto-reboot-during-argo-cd-sync-with-machine-configurations.adoc
Labels: size/S, jira/valid-reference

#75539 OSDOCS-10110: adds 4.15.12 relnote MicroShift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#75662 TELCODOCS-1703 removing notes as no longer relevant Cgroups v1 and v2
  modules/cnf-provisioning-real-time-and-low-latency-workloads.adoc
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  modules/cnf-understanding-low-latency.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed

#75493 OSDOCS-9448: modified the updating section for Microshift 4.16
  microshift_updating/microshift-about-updates.adoc
  microshift_updating/microshift-update-rpms-manually.adoc
  microshift_updating/microshift-update-rpms-ostree.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#75106 OSDOCS-10271: VMware CPMS TP to GA
  machine_management/control_plane_machine_management/cpmso-getting-started.adoc
  modules/cpmso-yaml-failure-domain-vsphere.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.16

#75540 OSDOCS-9449: adds RHEL 9.4 to Microshift 4.16 relnotes
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-reference

#75528 OSDOCS-10445: 4.15.12 RN
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, ok-to-merge, jira/valid-reference, branch/enterprise-4.15

#75738 OSSM-6424: Incorrect procedure for installing the ossmconsole CR
  modules/ossm-kiali-ossmc-plugin-install-web-console.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75740 HCIDOCS-189: Add note with link to OCP docs about exposed CoreDNS port
  installing/installing_bare_metal_ipi/ipi-install-overview.adoc
  modules/ipi-install-network-requirements.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75560 OSDOCS-10446 OCP 4.14.24 RNs
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.14

#73863 OSDOCS#9971:Added breakglass feature modules for HCP clusters
  cli_reference/rosa_cli/rosa-manage-objects-cli.adoc
  modules/rosa-create-objects.adoc
  modules/rosa-hcp-sts-accessing-a-break-glass-cred-cli.adoc
  modules/rosa-hcp-sts-creating-a-break-glass-cred-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-provider-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-provider-delete-cli.adoc
  modules/rosa-hcp-sts-revoking-a-break-glass-cred-cli.adoc
  modules/rosa-list-objects.adoc
  modules/rosa-revoke-objects.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15, branch/enterprise-4.16

#75762 Put back cgroups note
  modules/cnf-node-tuning-operator-disabling-cpu-load-balancing-for-dpdk.adoc
Labels: size/XS

#75763 TELCODOCS-1731 - fix broken xref
  release_notes/ocp-4-15-release-notes.adoc
Labels: size/XS

#74766 RHDEVDOCS-5954: Fixing typos in pre-reqs
  accesscontrol_usermanagement/configuring-argo-cd-rbac.adoc
  accesscontrol_usermanagement/configuring-sso-for-argo-cd-using-keycloak.adoc
  argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.adoc
  modules/gitops-additional-permissions-for-cluster-config.adoc
  modules/gitops-argo-cd-dynamic-scaling-by-using-cli.adoc
  modules/gitops-argo-cd-dynamic-scaling-in-web-console.adoc
  modules/gitops-argo-cd-installation.adoc
  modules/gitops-argo-cd-notification.adoc
  modules/gitops-configuring-user-level-access.adoc
  modules/gitops-creating-rolloutmanager-custom-resource.adoc
  modules/gitops-deleting-rolloutmanager-custom-resource.adoc
  modules/gitops-enabling-the-round-robin-sharding-algorithm-in-web-console.adoc
  modules/gitops-enabling-the-round-robin-sharding-algorithm-using-cli.adoc
  modules/gitops-release-notes-1-12-0.adoc
  modules/gitops-storing-and-retrieving-argo-cd-logs.adoc
  modules/logging-in-to-the-argo-cd-instance-by-using-the-argo-cd-admin-account.adoc
  modules/moving-the-gitops-operator-pod-to-infrastructure-nodes.adoc
  modules/proc_configuring-by-using-the-ocp-web-console.adoc
  observability/monitoring/monitoring-argo-cd-custom-resource-workloads.adoc
  observability/monitoring/monitoring-argo-cd-instances.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, gitops

#75538 OSDOCS-10107: adds 4.14.24 relnotes Microshift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14

#75484 OSDOCS-9431: update RHDE page for Microshift 4.16
  _attributes/common-attributes.adoc
  modules/about-rhde.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/valid-reference

#75464 OSDOCS-10444: updated the offline deployments links in relnotes Micros…
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, jira/valid-reference, branch/enterprise-4.15

#75655 Update eus-eus-update.adoc
  modules/updating-eus-to-eus-upgrade-cli.adoc
  updating/updating_a_cluster/eus-eus-update.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75753 [gitops-docs-1.10] RHDEVDOCS-5955: Removal of the {product-title} attribute in the content
  modules/gitops-enabling-dex.adoc
  modules/gitops-keycloak-identity-brokering-with-openshift-oauthclient.adoc
  modules/gitops-registering-an-additional-oauth-client.adoc
  modules/gitops-registering-an-oauth-client.adoc
  modules/go-settings-for-environment-labels-and-annotations.adoc
  troubleshooting_gitops_issues/auto-reboot-during-argo-cd-sync-with-machine-configurations.adoc
Labels: size/S, jira/valid-reference

#75754 [gitops-docs-1.11] RHDEVDOCS-5955: Removal of the {product-title} attribute in the content
  modules/gitops-configuring-sscsi-driver-to-mount-secrets-from-aws-secrets-manager.adoc
  modules/gitops-enabling-dex.adoc
  modules/gitops-keycloak-identity-brokering-with-openshift-oauthclient.adoc
  modules/gitops-registering-an-additional-oauth-client.adoc
  modules/gitops-registering-an-oauth-client.adoc
  modules/gitops-storing-aws-secret-manager-resources-in-gitops-repository.adoc
  modules/go-settings-for-environment-labels-and-annotations.adoc
  release_notes/gitops-release-notes.adoc
  troubleshooting_gitops_issues/auto-reboot-during-argo-cd-sync-with-machine-configurations.adoc
Labels: size/S, jira/valid-reference

#75201 OBSDOCS-1011: Fix information about the user-workload-monitoring-conf…
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-configuring-a-local-persistent-volume-claim.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-configuring-pod-topology-spread-constraints.adoc
  modules/monitoring-configuring-remote-write-storage.adoc
  modules/monitoring-configuring-the-monitoring-stack.adoc
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
  modules/monitoring-creating-scrape-sample-alerts.adoc
  modules/monitoring-creating-user-defined-workload-monitoring-configmap.adoc
  modules/monitoring-enabling-a-separate-alertmanager-instance-for-user-defined-alert-routing.adoc
  modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
  modules/monitoring-granting-users-permission-to-configure-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
  modules/monitoring-modifying-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-modifying-the-retention-time-for-thanos-ruler-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-resizing-a-persistent-storage-volume.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-query-log-file-for-prometheus.adoc
  modules/monitoring-setting-scrape-sample-and-label-limits-for-user-defined-projects.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#73772 TELCODOCS#1831: Local storage overview
  _topic_maps/_topic_map.yml
  modules/comparison-of-solutions-to-provision-node-local-storage.adoc
  storage/persistent_storage/persistent_storage_local/ways-to-provision-local-storage.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#73646 OSDOCS-10020: CPMS per-provider breakout
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  machine_management/control_plane_machine_management/cpmso-about.adoc
  machine_management/control_plane_machine_management/cpmso-configuration.adoc
  machine_management/control_plane_machine_management/cpmso-getting-started.adoc
  machine_management/control_plane_machine_management/cpmso-managing-machines.adoc
  machine_management/control_plane_machine_management/cpmso-resiliency.adoc
  machine_management/control_plane_machine_management/cpmso-troubleshooting.adoc
  machine_management/control_plane_machine_management/cpmso-using.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/_attributes
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-aws.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-gcp.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-nutanix.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-openstack.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-vsphere.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/images
  machine_management/control_plane_machine_management/cpmso_provider_configurations/modules
  machine_management/control_plane_machine_management/cpmso_provider_configurations/snippets
  machine_management/deleting-machine.adoc
  machine_management/index.adoc
  modules/cpms-changing-aws-instance-type.adoc
  modules/cpms-changing-openstack-flavor-type.adoc
  modules/cpmso-failure-domains-provider.adoc
  modules/cpmso-feat-auto-update.adoc
  modules/cpmso-feat-config-update.adoc
  modules/cpmso-feat-ondelete-update.adoc
  modules/cpmso-feat-replace.adoc
  modules/cpmso-yaml-failure-domain-vsphere.adoc
  modules/installation-azure-marketplace-subscribe.adoc
  modules/machineset-aws-existing-placement-group.adoc
  modules/machineset-azure-accelerated-networking.adoc
  modules/machineset-azure-boot-diagnostics.adoc
  modules/machineset-azure-confidential-vms.adoc
  modules/machineset-azure-enabling-accelerated-networking-existing.adoc
  modules/machineset-azure-trusted-launch.adoc
  modules/machineset-azure-ultra-disk.adoc
  modules/machineset-creating-azure-ultra-disk.adoc
  modules/machineset-creating-dedicated-instances.adoc
  modules/machineset-creating-imds-options.adoc
  modules/machineset-customer-managed-encryption-azure.adoc
  modules/machineset-dedicated-instances.adoc
  modules/machineset-gcp-confidential-vm.adoc
  modules/machineset-gcp-enabling-customer-managed-encryption.adoc
  modules/machineset-gcp-pd-disk-types.adoc
  modules/machineset-gcp-shielded-vms.adoc
  modules/machineset-imds-options.adoc
  modules/machineset-troubleshooting-azure-ultra-disk.adoc
  modules/private-clusters-setting-api-private.adoc
  nodes/nodes/nodes-nodes-managing.adoc
  post_installation_configuration/adding-nutanix-failure-domains.adoc
  post_installation_configuration/configuring-private-cluster.adoc
  post_installation_configuration/post-install-vsphere-zones-regions-configuration.adoc
  scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16

#75772 OSDOCS-30188: Typo fix for StorageClass plug-iin to plug-in
  modules/dynamic-provisioning-storage-class-definition.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75790 [enterprise-4.15] OSDOCS-10020: CPMS per-provider breakout
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  machine_management/control_plane_machine_management/cpmso-about.adoc
  machine_management/control_plane_machine_management/cpmso-configuration.adoc
  machine_management/control_plane_machine_management/cpmso-getting-started.adoc
  machine_management/control_plane_machine_management/cpmso-managing-machines.adoc
  machine_management/control_plane_machine_management/cpmso-resiliency.adoc
  machine_management/control_plane_machine_management/cpmso-troubleshooting.adoc
  machine_management/control_plane_machine_management/cpmso-using.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/_attributes
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-aws.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-gcp.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-nutanix.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-openstack.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-vsphere.adoc
  machine_management/control_plane_machine_management/cpmso_provider_configurations/images
  machine_management/control_plane_machine_management/cpmso_provider_configurations/modules
  machine_management/control_plane_machine_management/cpmso_provider_configurations/snippets
  machine_management/deleting-machine.adoc
  machine_management/index.adoc
  modules/cpms-changing-aws-instance-type.adoc
  modules/cpms-changing-openstack-flavor-type.adoc
  modules/cpmso-failure-domains-provider.adoc
  modules/cpmso-feat-auto-update.adoc
  modules/cpmso-feat-config-update.adoc
  modules/cpmso-feat-ondelete-update.adoc
  modules/cpmso-feat-replace.adoc
  modules/cpmso-yaml-failure-domain-vsphere.adoc
  modules/installation-azure-marketplace-subscribe.adoc
  modules/machineset-aws-existing-placement-group.adoc
  modules/machineset-azure-accelerated-networking.adoc
  modules/machineset-azure-boot-diagnostics.adoc
  modules/machineset-azure-confidential-vms.adoc
  modules/machineset-azure-enabling-accelerated-networking-existing.adoc
  modules/machineset-azure-trusted-launch.adoc
  modules/machineset-azure-ultra-disk.adoc
  modules/machineset-creating-azure-ultra-disk.adoc
  modules/machineset-creating-dedicated-instances.adoc
  modules/machineset-creating-imds-options.adoc
  modules/machineset-customer-managed-encryption-azure.adoc
  modules/machineset-dedicated-instances.adoc
  modules/machineset-gcp-confidential-vm.adoc
  modules/machineset-gcp-enabling-customer-managed-encryption.adoc
  modules/machineset-gcp-pd-disk-types.adoc
  modules/machineset-gcp-shielded-vms.adoc
  modules/machineset-imds-options.adoc
  modules/machineset-troubleshooting-azure-ultra-disk.adoc
  modules/private-clusters-setting-api-private.adoc
  nodes/nodes/nodes-nodes-managing.adoc
  post_installation_configuration/adding-nutanix-failure-domains.adoc
  post_installation_configuration/configuring-private-cluster.adoc
  post_installation_configuration/post-install-vsphere-zones-regions-configuration.adoc
  scalability_and_performance/recommended-performance-scale-practices/recommended-control-plane-practices.adoc
Labels: size/XL, jira/valid-reference

#75791 OSDOCS#9971.2:Changed additional resources formatting
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#75731 OSDOCS#10509: RHEL deprecation notice in OTA docs
  updating/updating_a_cluster/updating-cluster-rhel-compute.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16

#73909 OSDOCS-9915 machine pool grace periods during upgrades
  modules/rosa-edit-objects.adoc
  modules/rosa-node-drain-grace-period.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15, branch/enterprise-4.16

#75078 Telcodocs 1771 Extend workload partitioning to support cpu limits
  modules/create-perf-profile-workload-partitioning.adoc
  modules/enabling-workload-partitioning.adoc
  scalability_and_performance/enabling-workload-partitioning.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#75736 Correcting the channel name for specific version operator installatio…
  modules/olm-installing-specific-version-cli.adoc
Labels: peer-review-done, size/XS, needs-ok-to-test, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#74920 CNV-27866: [Doc] expose the downwardMetrics through a virtio-serial channel
  _topic_maps/_topic_map.yml
  modules/virt-configuring-downward-metrics.adoc
  modules/virt-enabling-disabling-downward-metrics-feature-gate-cli.adoc
  modules/virt-enabling-disabling-downward-metrics-feature-gate-yaml.adoc
  modules/virt-viewing-downward-metrics-cli.adoc
  modules/virt-viewing-downward-metrics-tool.adoc
  modules/virt-viewing-downward-metrics.adoc
  virt/monitoring/virt-exposing-downward-metrics.adoc
Labels: peer-review-done, size/L, CNV, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#74064 OSDOCS-8661: Configuring IP failover content audit
  modules/nw-ipfailover-cluster-ha-ingress.adoc
  modules/nw-ipfailover-configuration.adoc
  modules/nw-ipfailover-configuring-check-notify-scripts.adoc
  modules/nw-ipfailover-configuring-vrrp-preemption.adoc
  modules/nw-ipfailover-remove.adoc
  modules/nw-ipfailover-virtual-ip-addresses-concept.adoc
  modules/nw-ipfailover-vrrp-ip-offset.adoc
  networking/configuring-ipfailover.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75783 Add new attributes for MCE and hosted control planes
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75027 OSDOCS-9427: adds multus procedures MicroShift
  _topic_maps/_topic_map_ms.yml
  microshift_networking/microshift_multiple_networks/microshift-cni-multus-using.adoc
  microshift_networking/microshift_multiple_networks/microshift-cni-multus.adoc
  modules/microshift-cni-multus-add-network-example-config.adoc
  modules/microshift-cni-multus-nad-additional-network.adoc
  modules/microshift-cni-multus-troubleshoot.adoc
  modules/microshift-cni-multus-using-ipam.adoc
  modules/microshift-nw-multus-add-pod.adoc
  modules/nw-multus-remove-pod.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.16

#75702 OSDOCS-9763-2: Debug GitOps MicroShift
  microshift_running_apps/microshift-gitops.adoc
  modules/microshift-gitops-debug.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16

#75831 TELCODOCS-1731 - Redirects for refactored low latency tuning pages
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#75832 Adding PPC section to low latency redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#75068 OSDOCS#10324: Removed Tech Preview snippet and reference for Static IP assignment feature
  modules/installation-vsphere-installer-infra-static-ip-nodes.adoc
  modules/nodes-vsphere-machine-set-concept-static-ip.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nodes-vsphere-scaling-machines-static-ip.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16

#75127 TELCDOCS-1771-RN-416 Adding RN for 4.16
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/S, telco, qe-approved, merge-review-in-progress, sme-review-done, branch/enterprise-4.16

#75071 OCPBUGS32411: Updated prerequisites for oc-mirror plugin
  modules/oc-mirror-installing-plugin.adoc
Labels: peer-review-done, size/XS, qe-approved, merge-review-in-progress, sme-review-done, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#75776 OSDOCS-10496: Added scenarios for adding IPV6s to upgraded dual-stack…
  modules/nw-dual-stack-convert.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, jira/valid-reference, sme-review-done, branch/enterprise-4.16

#75486 RHDEVDOCS-6046: Content creation for GitOps 1.10.5 RN
  modules/gitops-release-notes-1-10-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/M, qe-approved, merge-review-in-progress, jira/valid-reference, sme-review-done, gitops

#75582 [enterprise-4.14] OCPBUGS#33334: Doc improvements related to RHACM procedures
  modules/lvms-about-lvm-storage-installation.adoc
  modules/lvms-creating-lvmcluster-using-rhacm.adoc
  modules/lvms-deleting-lvmcluster-using-rhacm.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-rhacm.adoc
  modules/lvms-scaling-storage-of-single-node-openshift-cluster-using-rhacm.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-rhacm.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/XL, qe-approved, merge-review-in-progress, sme-review-done, branch/enterprise-4.14

#75682 OSDOCS-10419#adding two new support regions
  modules/installation-gcp-regions.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, sme-review-done, branch/enterprise-4.16

#75842 Missed reverse redirects for low latency tuning
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#75485 RHDEVDOCS-6045: Content creation for GitOps 1.11.4 RN
  modules/gitops-release-notes-1-11-4.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, merge-review-in-progress, jira/valid-reference, sme-review-done, gitops

#75846 Copying Script files
  scripts/prow-smoke-test.sh
Labels: size/XS

#75848 <gitops-docs-1.10> RHDEVDOCS-6046: Content creation for GitOps 1.10.5 RN
  modules/gitops-release-notes-1-10-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: size/M, jira/valid-reference
