Repository openshift/openshift-docs, pull requests merged in 2024-02, with the labels that each got.

#71050 [enterprise-4.11] TELCODOCS-1678 Adding note to clarify that the Kubernetes NMState Operator
  _topic_maps/_topic_map.yml
  modules/virt-about-nmstate.adoc
  modules/virt-viewing-network-state-of-node.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-observing-node-network-state.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M

#71052 [enterprise-4.13] TELCODOCS-1678 Adding note to clarify that the Kubernetes NMState Operator
  _topic_maps/_topic_map.yml
  modules/virt-about-nmstate.adoc
  modules/virt-viewing-network-state-of-node.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-observing-node-network-state.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M

#71051 [enterprise-4.12] TELCODOCS-1678 Adding note to clarify that the Kubernetes NMState Operator
  _topic_maps/_topic_map.yml
  modules/virt-about-nmstate.adoc
  modules/virt-viewing-network-state-of-node.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-observing-node-network-state.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M

#70711 OBSDOCS-582: Docs for Power Monitoring Tech Preview
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  images/power-monitoring-component-power-source.png
  modules/power-monitoring-about-power-monitoring.adoc
  modules/power-monitoring-accessing-dashboards.adoc
  modules/power-monitoring-dashboards-overview.adoc
  modules/power-monitoring-deleting-kepler.adoc
  modules/power-monitoring-deploying-kepler.adoc
  modules/power-monitoring-hardware-virtualization-support.adoc
  modules/power-monitoring-installing-pmo.adoc
  modules/power-monitoring-kepler-architecture.adoc
  modules/power-monitoring-kepler-configuration.adoc
  modules/power-monitoring-metrics-overview.adoc
  modules/power-monitoring-monitoring-kepler-status.adoc
  modules/power-monitoring-uninstalling-pmo.adoc
  power_monitoring/_attributes
  power_monitoring/configuring-power-monitoring.adoc
  power_monitoring/images
  power_monitoring/installing-power-monitoring.adoc
  power_monitoring/modules
  power_monitoring/power-monitoring-overview.adoc
  power_monitoring/power-monitoring-release-notes.adoc
  power_monitoring/snippets
  power_monitoring/uninstalling-power-monitoring.adoc
  power_monitoring/visualizing-power-monitoring-metrics.adoc
Labels: peer-review-done, lgtm, size/XL, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#70949 OSDOCS#8720: Clean up redundant content in Preparing to install on vS…
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/preparing-to-install-on-vsphere.adoc
  installing/installing_vsphere/upi/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/upi/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/upi/installing-vsphere.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#71073 OSDOCS#8867: Adding xref to failure domain release note
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15

#70904 OSDOCS-6778
  modules/ossm-installation-activities.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#70584 OSDOCS#9413: OLM 1.0 supports AllNamespace install and no webhooks
  modules/olmv1-catalog-queries.adoc
  modules/olmv1-finding-operators-to-install.adoc
Labels: peer-review-in-progress, lgtm, size/M, qe-approved, branch/enterprise-4.15

#70668 [TRACING-3556] Document disable_keep_alives
  modules/otel-config-collector.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71011 [OSDOCS#9208]: Docs work for IPI: ShiftStack dual stack support
  modules/install-osp-deploy-dualstack.adoc
  modules/install-osp-dualstack.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, branch/enterprise-4.15

#70912 CNV#35089 - Document MTV support for VM migration
  virt/virtual_machines/virt-exporting-vms.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15

#70698 OCPBUGS#18942: Update etcd restore procedure for Keepalived
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70837 OCPBUGS-23427: Updated Example load balancer configuration for user-p…
  modules/installation-load-balancing-user-infra.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70714 OSDOCS-8955
  modules/rosa-create-an-identity-based-policy.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#71034 #CNV-31114: new rn for update to ssh secret use
  virt/release_notes/virt-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#71023 OSDOCS-9505 updated create cluster command
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#71044 OSDOCS#8863 & 8864: Version range comparison strings
  modules/olmv1-version-range-comparisons.adoc
  modules/olmv1-version-range-support.adoc
  operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.15

#70753 OCPBUGS#27841: Removed "Adding a storage class" proc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#70608 OBSDOCS-205 - CLF audit log filtering
  logging/log_collection_forwarding/configuring-log-forwarding.adoc
  modules/logging-audit-log-filtering.adoc
Labels: size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71095 OSDOCS#8882 OLM 1.0 admonition for multicatalog conflicts
  modules/olmv1-about-catalogs.adoc
  snippets/olmv1-multi-catalog-admon.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#70359 OSDOCS#8989: Installing OLM on MicroShift
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  modules/microshift-adding-olm-to-blueprint.adoc
  modules/microshift-install-rpms-olm.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, branch/enterprise-4.15

#70967 OSDOCS-9460: Documented the 4.13.31 z-stream release notes
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13

#69886 OSDOCS-4157: GCP Role Administrator role
  authentication/managing_cloud_provider_credentials/cco-mode-mint.adoc
  modules/cco-ccoctl-configuring.adoc
  modules/cco-ccoctl-deleting-sts-resources.adoc
  modules/cco-ccoctl-install-creating-manifests.adoc
  modules/installation-gcp-permissions.adoc
  modules/manually-create-identity-access-management.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.15

#70216 clarifying QE exception
  contributing_to_docs/doc_guidelines.adoc
Labels: size/XS

#71020 #CNV-30291 - remove tp snippet
  virt/vm_networking/virt-using-dpdk-with-sriov.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#70911 OSDOCS#6797: linking Operator update compatbility app in OTA docs
  modules/update-conditional-web-console.adoc
  modules/update-upgrading-web.adoc
  modules/updating-eus-to-eus-layered-products.adoc
  operators/admin/olm-restricted-networks.adoc
  operators/admin/olm-upgrading-operators.adoc
  updating/updating_a_cluster/eus-eus-update.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
  updating/updating_a_cluster/updating-cluster-rhel-compute.adoc
  updating/updating_a_cluster/updating-cluster-web-console.adoc
  updating/updating_a_cluster/updating_disconnected_cluster/disconnected-update.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71103 Adds link to garbage collection feature for Quay
  installing/disconnected_install/installing-mirroring-creating-registry.adoc
  modules/mirror-registry-introduction.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14

#70268 OSDOCS#9207 Mixed public/private API and Ingress during azure installation
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.15

#69212 OSDOCS#6518: 64k pages in the RHCOS kernal support on multi-arch compute
  modules/multi-architecture-enabling-64k-pages.adoc
  post_installation_configuration/configuring-multi-arch-compute-machines/multi-architecture-compute-managing.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.15

#71155 [OSDOCS-9552] ROSA CLI what's new for 1.2.34
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/XS, SD-docs, branch/enterprise-4.14, branch/enterprise-4.15

#70625 TELCODOCS#1254: Using software RAID in LVM Storage
  _attributes/common-attributes.adoc
  modules/lvms-creating-logical-volume-manager-cluster.adoc
  modules/lvms-integrating-software-raid-arrays.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.15

#70665 OADP - 3343 Update Using the must-gather tool
  modules/migration-combining-must-gather.adoc
  modules/migration-using-must-gather.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71143 OBSDOCS-798: add missing monitoring-plugin info to in-cluster monitoring docs
  modules/monitoring-configurable-monitoring-components.adoc
  modules/monitoring-default-monitoring-components.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#71077 [virt] DPDK checkup: fix image build instruction
  modules/virt-building-vm-containerdisk-image.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.15

#69629 TELCODOCS#1626: Recovering VGs from previous LVM Storage installation
  modules/lvms-creating-logical-volume-manager-cluster.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#71117 TELCODOCS#1759: Added must gather images
  modules/gathering-data-specific-features.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-openshift-web-console.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#71116 TELCODOCS#1759: Added must gather images for LVM Operator
  modules/gathering-data-specific-features.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-openshift-web-console.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed

#70486 OADP-3365: Fix issues in OADP docs
  modules/installing-oadp-rosa-sts.adoc
  modules/performing-a-backup-oadp-rosa-sts.adoc
  modules/preparing-aws-credentials-for-oadp.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.12, OADP, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71084 [OSDCOCS8489 ] 4.15 changes for multi-architecture tp and depr tables
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#69106 OSDOCS-8427: Dashboard enhancements for lokiless use
  _topic_maps/_topic_map.yml
  modules/network-observability-includelist-example.adoc
  modules/network-observability-metrics.adoc
  modules/network-observability-rate-limit-alert.adoc
  modules/network-observability-viewing-alerts.adoc
  modules/network-observability-viewing-dashboards.adoc
  network_observability/metrics-alerts-dashboards.adoc
  network_observability/network-observability-operator-release-notes.adoc
  network_observability/network-observability-overview.adoc
  network_observability/observing-network-traffic.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71115 ER-OBSDOCS-795: Fix rendering issue for power monitoing docs
  modules/power-monitoring-hardware-virtualization-support.adoc
  power_monitoring/power-monitoring-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, jira/valid-reference, sme-review-done, branch/enterprise-4.14, branch/enterprise-4.15

#64186 simplify snippet for querying effective_affinity
  modules/cnf-about-irq-affinity-setting.adoc
Labels: lgtm, size/XS, qe-approved, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71093 OSDOCS#8719: Refactor of pre-installation tasks for an IPI installation
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/ipi/installing-restricted-networks-installer-provisioned-vsphere.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned-network-customizations.adoc
  installing/installing_vsphere/ipi/installing-vsphere-installer-provisioned.adoc
  installing/installing_vsphere/ipi/ipi-vsphere-preparing-to-install.adoc
  modules/cli-installing-cli.adoc
  modules/installation-adding-vcenter-root-certificates.adoc
  modules/installation-obtaining-installer.adoc
  modules/ssh-agent-using.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#70849 OSSM-5816 Clarify circumstances to use strict mTLS
  modules/ossm-security-mtls.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71062 [enterprise-4.13] OCPBUGS-20194: Stop other control plane components on non-recovery hosts during etcd restore procedure
  modules/dr-restoring-cluster-state.adoc
Labels: size/L, jira/severity-important, jira/invalid-bug, jira/valid-reference

#71209 [enterprise-4.11] OCPBUGS-20194: Stop other control plane components on non-recovery hosts during etcd restore procedure
  modules/dr-restoring-cluster-state.adoc
Labels: size/L, branch/enterprise-4.11, jira/severity-important, jira/invalid-bug, jira/valid-reference

#71164 OSDOCS#9555: Refactor of pre-installation tasks for a UPI installation
  _topic_maps/_topic_map.yml
  installing/installing_vsphere/upi/installing-restricted-networks-vsphere.adoc
  installing/installing_vsphere/upi/installing-vsphere-network-customizations.adoc
  installing/installing_vsphere/upi/installing-vsphere.adoc
  installing/installing_vsphere/upi/upi-vsphere-preparing-to-install.adoc
  modules/cli-installing-cli.adoc
  modules/installation-infrastructure-user-infra.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-user-provisioned-validating-dns.adoc
  modules/ssh-agent-using.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#71113 TELCODOCS#1255: Added a warning in "Deploying LVM Storage" section
  modules/deploying-lvms-on-sno-cluster.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.15

#70801 OBSDOCS-481 - Logging attributes update
  _attributes/common-attributes.adoc
  cicd/gitops/viewing-argo-cd-logs.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-support.adoc
  logging/cluster-logging-uninstall.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/dedicated-cluster-logging.adoc
  logging/logging_alerts/default-logging-alerts.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/gitops-storing-and-retrieving-argo-cd-logs.adoc
  modules/logging-architecture-overview.adoc
  modules/logging-plugin-es-loki.adoc
  snippets/logging-log-types-snip.adoc
  snippets/logging-loki-vs-lokistack-snip.adoc
  snippets/logging-supported-config-snip.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71009 OSDOCS#8865 Installing extensions on a cluster in OLM 1.0
  modules/olmv1-installing-an-operator.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#71198 OSDOCS-8484: Fixing cron job timezone's support status
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.15

#71220 [Enterprise-4.13] manual CP of #70801
  _attributes/common-attributes.adoc
  cicd/gitops/viewing-argo-cd-logs.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-support.adoc
  logging/cluster-logging-uninstall.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/dedicated-cluster-logging.adoc
  logging/logging_alerts/default-logging-alerts.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/gitops-storing-and-retrieving-argo-cd-logs.adoc
  modules/logging-architecture-overview.adoc
  modules/logging-plugin-es-loki.adoc
  snippets/logging-log-types-snip.adoc
  snippets/logging-loki-vs-lokistack-snip.adoc
  snippets/logging-supported-config-snip.adoc
Labels: size/M

#71223 [Enterprise-4.12] manual CP of #70801
  _attributes/common-attributes.adoc
  cicd/gitops/viewing-argo-cd-logs.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-support.adoc
  logging/cluster-logging-uninstall.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/dedicated-cluster-logging.adoc
  logging/logging_alerts/default-logging-alerts.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/gitops-storing-and-retrieving-argo-cd-logs.adoc
  modules/logging-architecture-overview.adoc
  modules/logging-plugin-es-loki.adoc
  snippets/logging-log-types-snip.adoc
  snippets/logging-loki-vs-lokistack-snip.adoc
  snippets/logging-supported-config-snip.adoc
Labels: size/M

#71225 [Enterprise-4.11] - Manual CP of #70801
  _attributes/common-attributes.adoc
  cicd/gitops/viewing-argo-cd-logs.adoc
  logging/cluster-logging-deploying.adoc
  logging/cluster-logging-support.adoc
  logging/cluster-logging-uninstall.adoc
  logging/cluster-logging.adoc
  logging/config/cluster-logging-configuring.adoc
  logging/dedicated-cluster-logging.adoc
  logging/logging_alerts/default-logging-alerts.adoc
  modules/cluster-logging-about.adoc
  modules/cluster-logging-clo-status-comp.adoc
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-collector-tuning.adoc
  modules/cluster-logging-configuring-image-about.adoc
  modules/cluster-logging-deploying-about.adoc
  modules/cluster-logging-elasticsearch-audit.adoc
  modules/cluster-logging-elasticsearch-exposing.adoc
  modules/cluster-logging-elasticsearch-retention.adoc
  modules/cluster-logging-eventrouter-about.adoc
  modules/cluster-logging-eventrouter-deploy.adoc
  modules/gitops-storing-and-retrieving-argo-cd-logs.adoc
  modules/logging-architecture-overview.adoc
  snippets/logging-log-types-snip.adoc
  snippets/logging-loki-vs-lokistack-snip.adoc
  snippets/logging-supported-config-snip.adoc
Labels: size/M

#70955 RHDEVDOCS-5881 - Document Release Notes for 1.11.1 release
  modules/gitops-release-notes-1-10-2.adoc
  modules/gitops-release-notes-1-11-1.adoc
  modules/gitops-release-notes-1-9-4.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/M, ok-to-merge, qe-approved, sme-review-done, gitops

#70972 RHDEVDOCS-5880 - Document for GitOps 1.9.4 Release Notes
  modules/gitops-release-notes-1-9-4.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/S, ok-to-merge, qe-approved, sme-review-done, gitops

#70965 RHDEVDOCS-5879 - Document for GitOps 1.10.2 Release Notes
  modules/gitops-release-notes-1-10-2.adoc
  modules/gitops-release-notes-1-9-4.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/M, ok-to-merge, qe-approved, sme-review-done, gitops

#55526 OSDOCS#4348: Installing an IBM Cloud VPC cluster in restricted env
  _topic_maps/_topic_map.yml
  installing/installing-preparing.adoc
  installing/installing_ibm_cloud_public/installing-ibm-cloud-restricted.adoc
  installing/installing_ibm_cloud_public/preparing-to-install-on-ibm-cloud.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-telemetry.adoc
  modules/installation-about-restricted-network.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-custom-ibm-cloud-vpc.adoc
  modules/installation-ibm-cloud-config-yaml.adoc
  modules/installation-ibm-cloud-configure-vpc-for-endpoint-gateways.adoc
  modules/installation-ibm-cloud-download-rhcos.adoc
  modules/installation-ibm-cloud-export-variables.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  modules/installation-minimum-resource-requirements.adoc
  modules/manually-create-iam-ibm-cloud.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/ssh-agent-using.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.15

#71229 OSDOCS#4348: Adding xref to IBM Cloud restricted installs release note
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.15

#70012 [RHACS] Added filter criteria for component and component source
  modules/vulnerability-management20-view-cve.adoc
Labels: peer-review-done, lgtm, size/XS, RHACS, rhacs-docs-4.4

#71183 Revert "[enterprise-4.14] HCIDOCS-125: Updating AI docs location in OCP docs."
  installing/installing_sno/install-sno-installing-sno.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#71184 Revert "HCIDOCS-125: Updating AI docs location in OCP docs."
  installing/installing_sno/install-sno-installing-sno.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#71182 Revert "[enterprise-4.13] HCIDOCS-125"
  installing/installing_sno/install-sno-installing-sno.adoc
Labels: peer-review-done, lgtm, size/S

#71105 Fix mustgather image location for secrets-store-csi-driver-operator
  modules/gathering-data-specific-features.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15

#71114 TELCODOCS#1759: Adding must gather image for LVM Storage
  modules/gathering-data-specific-features.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-openshift-web-console.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15

#71230 OSDOCS#9566: Removing Assisted Installer references from failure doma…
  installing/installing_nutanix/nutanix-failure-domains.adoc
  post_installation_configuration/adding-nutanix-failure-domains.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#70909 OSDOCS-9364 updated ROSA PV Storage options
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/storage-persistent-storage-block-volume.adoc
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70463 MIG 1512 - MTC 1.8 only supports OCP4->4 migrations
  modules/migration-compatibility-guidelines.adoc
  modules/migration-installing-legacy-operator.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, MTC, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71222 OSDOCS-9562 Changing tech preview title heading
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-needed

#70593 OSDOCS-9369: add improved mco status updates tech preview
  modules/checking-mco-node-status.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.15

#70879 OBSDOCS-760: Update structure of resource scheduling docs
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/scheduling_resources/_attributes
  logging/scheduling_resources/images
  logging/scheduling_resources/logging-node-selectors.adoc
  logging/scheduling_resources/logging-taints-tolerations.adoc
  logging/scheduling_resources/modules
  logging/scheduling_resources/snippets
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-logstore-tolerations.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  snippets/about-node-selectors.adoc
Labels: peer-review-done, size/XL, dev-tools, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71275 [enterprise-4.13] OBSDOCS-760: Update structure of resource scheduling docs
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/scheduling_resources/_attributes
  logging/scheduling_resources/images
  logging/scheduling_resources/logging-node-selectors.adoc
  logging/scheduling_resources/logging-taints-tolerations.adoc
  logging/scheduling_resources/modules
  logging/scheduling_resources/snippets
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-logstore-tolerations.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  post_installation_configuration/cluster-tasks.adoc
  snippets/about-node-selectors.adoc
Labels: size/XL, jira/valid-reference

#71274 [enterprise-4.12] OBSDOCS-760: Update structure of resource scheduling docs
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/scheduling_resources/_attributes
  logging/scheduling_resources/images
  logging/scheduling_resources/logging-node-selectors.adoc
  logging/scheduling_resources/logging-taints-tolerations.adoc
  logging/scheduling_resources/modules
  logging/scheduling_resources/snippets
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-logstore-tolerations.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  post_installation_configuration/cluster-tasks.adoc
  snippets/about-node-selectors.adoc
Labels: size/XL, jira/valid-reference

#71272 [enterprise-4.11] OBSDOCS-760: Update structure of resource scheduling docs
  _topic_maps/_topic_map.yml
  logging/config/cluster-logging-moving-nodes.adoc
  logging/config/cluster-logging-tolerations.adoc
  logging/log_collection_forwarding/cluster-logging-collector.adoc
  logging/scheduling_resources/_attributes
  logging/scheduling_resources/images
  logging/scheduling_resources/logging-node-selectors.adoc
  logging/scheduling_resources/logging-taints-tolerations.adoc
  logging/scheduling_resources/modules
  logging/scheduling_resources/snippets
  modules/cluster-logging-collector-tolerations.adoc
  modules/cluster-logging-elasticsearch-tolerations.adoc
  modules/cluster-logging-kibana-tolerations.adoc
  modules/cluster-logging-logstore-tolerations.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-taints-tolerations-about.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  snippets/about-node-selectors.adoc
Labels: size/XL, jira/valid-reference

#71276 Logging redirects
  .s2i/httpd-cfg/01-commercial.conf
Labels: size/XS

#70727 OSDOCS-9146 Updated ShiftStack UPI playbooks, dual stack support
  installing/installing_openstack/installing-openstack-user.adoc
  modules/installation-osp-config-yaml.adoc
  modules/installation-osp-creating-network-resources.adoc
  modules/installation-osp-downloading-playbooks.adoc
  modules/installation-osp-fixing-subnet.adoc
  modules/installation-osp-updating-network-resources.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#71126 Adds Tuning etcd latency tolerances to 4.14 RNs as Tech preview
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14

#71219 Adds prereq section to changing hardware speed tolerance
  modules/etcd-tuning-parameters.adoc
  scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#70560 OCPBUGS#11325-4.13: Supported access table is modified for Fibre Chan…
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#70559 OCPBUGS#11325-4.14: Supported access table is modified for Fibre Chan…
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15

#70128 OSDOCS-8991: OLM on MicroShift intro
  _topic_maps/_topic_map_ms.yml
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  microshift_running_apps/microshift-operators-olm.adoc
  microshift_running_apps/microshift-operators.adoc
  modules/microshift-get-mirror-reg-container-image-list.adoc
  modules/microshift-olm-build-op-catalogs.adoc
  modules/microshift-olm-deploy-op-disconnected.adoc
  modules/microshift-olm-deploy-ops-con.adoc
  modules/microshift-olm-deploy-ops-global-ns.adoc
  modules/microshift-olm-deploy-ops-spec-ns.adoc
  modules/microshift-olm-namespaces.adoc
Labels: peer-review-done, size/XL, qe-approved, jira/valid-reference, branch/enterprise-4.15

#71315 Adding prow tools to no-1.5
  .yamllint
  scripts/check-asciidoctor-build.sh
  scripts/check-rn-link-perms.sh
  scripts/get-updated-distros.sh
  scripts/get-updated-preview-urls.sh
  scripts/lint-topicmaps.sh
  scripts/manualpreview.sh
  scripts/ocpdocs/_previewpage
Labels: size/L, openshift-docs-prow

#71311 Adding prow tools to gitops-docs
  .yamllint
  build_for_portal.py
  makeBuild.py
  scripts/check-asciidoctor-build.sh
  scripts/check-rn-link-perms.sh
  scripts/get-updated-distros.sh
  scripts/get-updated-preview-urls.sh
  scripts/lint-topicmaps.sh
  scripts/manualpreview.sh
  scripts/ocpdocs/_previewpage
Labels: size/XL, openshift-docs-prow

#71304 Adding prow tools to opp-docs
  .gitignore
  .vale.ini
  .yamllint
  _topic_maps/_topic_map.yml
  build.py
  build_for_portal.py
  makeBuild.py
  scripts/analytics_fix.sh
  scripts/check-asciidoctor-build.sh
  scripts/check-rn-link-perms.sh
  scripts/check-with-vale.sh
  scripts/find_unused.py
  scripts/get-updated-distros.sh
  scripts/get-updated-preview-urls.sh
  scripts/lint-topicmaps.sh
  scripts/manualpreview.sh
  scripts/ocp_preview.sh
  scripts/ocpdocs/_previewpage
  scripts/ocpdocs/_topnav_other.html
  scripts/ocpdocs/index-commercial.html
  scripts/ocpdocs/search-commercial.html
Labels: size/XXL, openshift-docs-prow

#71301 Adding prow tools to serverless-docs
  .yamllint
  build_for_portal.py
  makeBuild.py
  scripts/check-asciidoctor-build.sh
  scripts/check-rn-link-perms.sh
  scripts/get-updated-distros.sh
  scripts/get-updated-preview-urls.sh
  scripts/lint-topicmaps.sh
  scripts/manualpreview.sh
  scripts/ocpdocs/_previewpage
Labels: size/XL, openshift-docs-prow

#71298 OCPBUGS#29178: replacing RBAC image
  images/rbac.png
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70825 [OSDOCS-3989] OCP content port to ROSA and OSD: Nodes Follow Up
  _topic_maps/_topic_map_osd.yml
Labels: size/M, branch/enterprise-4.14, branch/enterprise-4.15

#71321 [CP-OCPBUGS-11325-4.12] OCPBUGS-11325-4.13: Supported access table is modified for Fibre Chan…
  modules/storage-persistent-storage-pv.adoc
Labels: size/S

#71322 OCPBUGS-11325-4.11: Supported access table is modified for Fibre C…
  modules/storage-persistent-storage-pv.adoc
Labels: size/XS

#71134 OSDOCS-9263: adds 4.14.11 relnote MicroShift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14

#71281 OCPBUGS#24512: Minor doc updates
  modules/lvms-unsupported-devices.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#71260 [OSDOCS#9544]: Release Notes 4.13.32
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#71094 OSDOCS-9541 OCP z-stream RNs 4.14.11
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed, branch/enterprise-4.14

#71267 OSDOCS-8491: Specialized hardware and driver enablement
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#71320 Fixing bad xref in Virt Post-install
  virt/post_installation_configuration/virt-post-install-config.adoc
Labels: size/XS, branch/enterprise-4.14, branch/enterprise-4.15

#71306 OSDOCS#9546: Adding known issue for OpenSSL error with oc
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15

#70680 OBSDOCS-642: Add docs for creating the LogFileMetricExporter CR
  logging/log_collection_forwarding/cluster-logging-collector.adoc
  modules/creating-logfilesmetricexporter.adoc
  modules/logging-release-notes-5-8-0.adoc
Labels: peer-review-done, size/M, do-not-merge/hold, dev-tools, px-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#68395 GH#38141: Remove invalid identity provider parameter
  modules/identity-provider-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71234 Logging 5.6.16 Release Notes
  logging/logging_release_notes/logging-5-6-release-notes.adoc
  modules/logging-release-notes-5-6-16.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#70210 OSDOCS-8767: Adding information about configuring consistent IP
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-consistent-egress-ip.adoc
  modules/nw-egress-ips-about.adoc
  modules/nw-egress-ips-node.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#70451 OSDOCS-8904: Private Cluster on ROSA with HCP docs
  _topic_maps/_topic_map_rosa.yml
  modules/osd-aws-privatelink-about.adoc
  modules/osd-aws-privatelink-required-resources.adoc
  modules/rosa-aws-privatelink-create-cluster.adoc
  modules/rosa-hcp-aws-privatelink-create-cluster.adoc
  modules/rosa-hcp-aws-privatelink-security-groups.adoc
  rosa_hcp/rosa-hcp-aws-privatelink-creating-cluster.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#71175 Do not emphasize disabling SELinux in examples
  modules/installation-special-config-kargs.adoc
  modules/nodes-nodes-kernel-arguments.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.11, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#69218 OSDOCS#9040: Adding note warning of future PSA restricted enforcement
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.15

#71258 OSDOCS#8861: Semver support and updating Operators
  modules/olmv1-about-target-versions.adoc
  modules/olmv1-forcing-an-update-or-rollback.adoc
  modules/olmv1-installing-an-operator.adoc
  modules/olmv1-semver-support.adoc
  modules/olmv1-updating-an-operator.adoc
  operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.adoc
  snippets/olmv1-version-range-cr-adomn.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.15

#71317 #CNV-37343 - minor update
  modules/virt-adding-public-key-cli.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.15

#71213 OSDOCS#8476: Adding CLI docs for 4.15
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.15

#69006 OSDOCS-8953: Add supported SR-IOV device
  modules/nw-sriov-supported-devices.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.15

#71180 avoid setenforce 0 in etcd disk moves
  modules/move-etcd-different-disk.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71081 OCPBUGS-27961 Procedure for configuring Whereabouts IP reconciler schedule
  modules/nw-multus-configuring-whereabouts-ip-reconciler-schedule.adoc
  modules/nw-multus-creating-whereabouts-reconciler-daemon-set.adoc
  modules/nw-multus-ipam-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
Labels: peer-review-done, size/L, telco, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#71300 [OSDOCS-9483]: Typo In Red Hat OpenShift on a single node Installation documentation
  modules/install-sno-generating-the-install-iso-manually.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#71104 HCIDOCS-202: Document updated RAID support
  modules/bmo-about-the-baremetalhost-resource.adoc
  modules/ipi-install-configuring-the-raid.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15

#69671 OCPBUGS-22397: clarify netobserv network policy
  network_observability/network-observability-network-policy.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.11, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70639 CNV#32030 - Default storage class - planning cluster
  virt/install/preparing-cluster-for-virt.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#71255 OSDOCS#9574: Release notes for OCP on ARM 4.15
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, branch/enterprise-4.15

#67001 OSDOCS-8401: Migrate "ROSA with STS Explained"
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-rosa-sts-explained.adoc
  images/cloud-expert-sts-explained_cli_flow.png
  images/cloud-experts-sts-explained_creation_flow.png
  images/cloud-experts-sts-explained_entire_flow.png
  images/cloud-experts-sts-explained_highlevel.png
  images/cloud-experts-sts-explained_oidc_op_roles.png
Labels: peer-review-done, size/L, jira/valid-reference, SD-docs, branch/enterprise-4.14, cloud-experts, branch/enterprise-4.15

#70974 OSDOCS-9419: Adding zones to Overview
  modules/network-observability-configuring-options-overview.adoc
  modules/network-observability-working-with-conversations.adoc
  modules/network-observability-working-with-zones.adoc
  network_observability/network-observability-overview.adoc
  network_observability/observing-network-traffic.adoc
Labels: peer-review-done, size/M, qe-approved, jira/valid-reference

#71217 OSDOCS-9563 OCP z-stream RNs 4.11.58
  release_notes/ocp-4-11-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#71404 [RHACS] Sync latest changes from the main branch
  scripts/get-updated-preview-urls.sh
  scripts/manualpreview.sh
Labels: size/M, RHACS, rhacs-docs-4.1, rhacs-docs-4.2, rhacs-docs-4.3, rhacs-docs-4.4

#70669 OSDOCS-8481: Updated the TechPreviewNoUpgrade list
  modules/nodes-cluster-enabling-features-about.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.15

#71305 OSDOCS-8707: clarification for external gateway
  modules/nw-secondary-ext-gw-about.adoc
  modules/nw-secondary-ext-gw-object.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#71344 OBSDOCS-813: Update rhobs/prometheus-example-app version in monitoring docs to 0.4.2
  modules/monitoring-configuring-monitoring-for-an-application.adoc
  modules/monitoring-deploying-a-sample-service-for-cluster-observability-operator.adoc
  modules/monitoring-deploying-a-sample-service.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.11, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70120 OSDOCS-8515: Documented the 4.15 Welcome page
  _attributes/common-attributes.adoc
  welcome/index.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.15

#71069 TELCODOCS-1724: Adding OLM cluster capability
  installing/cluster-capabilities.adoc
  modules/olm-overview.adoc
  snippets/capabilities-table.adoc
Labels: peer-review-done, size/M, telco, qe-approved, jira/valid-reference, sme-review-done, branch/enterprise-4.15

#70141 OSDOCS#8947: Creating new section for capabilities and layered products in the web console
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/optional-capabilities-operators.adoc
  modules/pipelines-web-console.adoc
  modules/rhdh-web-console.adoc
  modules/serverless-web-console.adoc
  web_console/capabilities_layered-products/_attributes
  web_console/capabilities_layered-products/capabilities-web-console.adoc
  web_console/capabilities_layered-products/images
  web_console/capabilities_layered-products/layered-products-web-console.adoc
  web_console/capabilities_layered-products/modules
  web_console/capabilities_layered-products/snippets
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.15

#71399 Re-adding removed RTT overview info
  network_observability/observing-network-traffic.adoc
Labels: peer-review-done, size/XS

#71256 OSDOCS#8971: Docs for change in secret generation behavior when the i…
  installing/cluster-capabilities.adoc
  modules/cluster-image-registry-operator.adoc
  modules/service-account-auto-secret-removed.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#71257 OSDOCS#8971: Adding release note for secret generation behavior change
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15

#71345 TELCODOCS-1724: Release note for optional OLM capability
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, telco, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15

#71337 OSDOCS-8774:fixes code syntax
  modules/nw-sriov-ibnetwork-object.adoc
  modules/nw-sriov-network-object.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#71414 OCPBUGS-29234 Add in link to correct section
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#71112 OSDOCS-9249: Create an installation guide for enabling autoscaling on a cluster with Terraform
  modules/rosa-cluster-cluster-role-name-change.adoc
  modules/rosa-cluster-enable-autoscaling-terraform.adoc
  modules/rosa-sts-cluster-terraform-file-creation.adoc
  rosa_install_access_delete_clusters/terraform/rosa-sts-creating-a-cluster-with-customizations-terraform.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15

#69821 OSDOCS-8701: Update resource considerations table
  modules/network-observability-resources-table.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/valid-reference

#70512 OBSDOCS-577: Docs bug fix for an incorrect API
  distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  modules/distr-tracing-tempo-config-default.adoc
  modules/distr-tracing-tempo-config-query-frontend.adoc
  modules/distr-tracing-tempo-config-spanmetrics.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71233 Logging 5.7.11 Release Notes
  logging/logging_release_notes/logging-5-7-release-notes.adoc
  modules/logging-release-notes-5-7-11.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14

#71277 HCIDOCS-125: Updating AI docs location in OCP docs.
  installing/installing_sno/install-sno-installing-sno.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#71419 OSSM-5900 Update v2 to match v1 change request from outside OSSM
  modules/ossm-add-project-using-label-selectors-cli.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#70885 OCP 4.15: IPI for PowerVS updates
  modules/installation-configuration-parameters.adoc
  modules/installation-ibm-cloud-iam-policies-api-key.adoc
  modules/installation-ibm-cloud-regions.adoc
  modules/installation-ibm-power-vs-config-yaml.adoc
  modules/quotas-and-limits-ibm-power-vs.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.15

#71456 OSSM-5904 Troubleshooting your service mesh has a typo
  modules/ossm-about-collecting-ossm-data.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.11, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71282 OSDOCS-9545: Documented the 4.12.49 z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference

#71482 OCPBUG29107: Added endif in additional resources.
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-ingress-controller.adoc
Labels: peer-review-done, size/XS

#71430 Adding EOL message to 4.11
  _templates/_page_openshift.html.erb
Labels: peer-review-done, size/XS

#71464 #CNV-36602 - bootable volume favorites
  modules/virt-creating-vm-instancetype.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15

#71087 OCPBUGS-24272: Added missing kdump manifests to recommended cluster install manifests
  modules/ztp-sno-du-enabling-kdump.adoc
  snippets/ztp_05-kdump-config-master.yaml
  snippets/ztp_05-kdump-config-worker.yaml
  snippets/ztp_06-kdump-master.yaml
  snippets/ztp_06-kdump-worker.yaml
Labels: peer-review-done, size/L, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference

#71071 [MULTIARCH-3975] New IBM Z LPAR installation assembly
  _topic_maps/_topic_map.yml
  installing/installing_ibm_z/installing-ibm-z-lpar.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-lpar.adoc
  installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/csr-management.adoc
  modules/ibmz-configure-nbde-with-static-ip.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-bare-metal-config-yaml.adoc
  modules/installation-complete-user-infra.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-dns-user-infra.adoc
  modules/installation-ibm-z-user-infra-machines-iso.adoc
  modules/installation-infrastructure-user-infra.adoc
  modules/installation-initializing-manual.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-load-balancing-user-infra.adoc
  modules/installation-machine-requirements.adoc
  modules/installation-minimum-resource-requirements.adoc
  modules/installation-network-user-infra.adoc
  modules/installation-operators-config.adoc
  modules/installation-registry-storage-config.adoc
  modules/installation-registry-storage-non-production.adoc
  modules/installation-three-node-cluster.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
  modules/installation-user-infra-machines-static-network.adoc
  modules/installation-user-provisioned-validating-dns.adoc
  modules/minimum-ibm-z-system-requirements.adoc
  modules/nw-operator-cr.adoc
  modules/olm-restricted-networks-configuring-operatorhub.adoc
  modules/preferred-ibm-z-system-requirements.adoc
  modules/registry-configuring-storage-baremetal.adoc
  modules/ssh-agent-using.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, branch/enterprise-4.15

#71475 [enterprise-4.13 CP] OCPBUGS-27961 Procedure for configuring Whereabouts IP reconciler sch…
  modules/nw-multus-configuring-whereabouts-ip-reconciler-schedule.adoc
  modules/nw-multus-creating-whereabouts-reconciler-daemon-set.adoc
  modules/nw-multus-ipam-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  release_notes/ocp-4-13-release-notes.adoc
Labels: size/L, merge-review-in-progress

#71413 OCPBUGS-27961-RN-415-NF RN Description for whereabouts schedule
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#71372 OBSDOCS-814: Fixing typo in CLI install
  modules/logging-loki-cli-install.adoc
Labels: peer-review-done, lgtm, size/XS, dev-tools, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71330 RHDEVDOCS-5907: Updated the shp CLI command examples
  _topic_maps/_topic_map.yml
  modules/ob-creating-a-buildah-build.adoc
  modules/ob-creating-a-s2i-build.adoc
  work_with_builds/using-builds.adoc
Labels: peer-review-done, size/S, qe-approved, merge-review-in-progress, jira/valid-reference

#71379 TELCODOCS-900 DHCP must be used for IPI installations
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-setting-cluster-node-hostnames-dhcp.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#71488 OSDOCS-9559: Added OIDC provider note to prereqs
  rosa_planning/rosa-cloud-expert-prereq-checklist.adoc
Labels: size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15
