Repository openshift/openshift-docs, pull requests merged in 2024-08, with the labels that each got.

#79804 RHDEVDOCS-6123: Content creation for GitOps 1.12.5 RN
  modules/gitops-release-notes-1-12-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-in-progress, size/M, jira/valid-reference

#79752 RHDEVDOCS-6122: Content creation for GitOps 1.11.7 Release Notes
  modules/gitops-release-notes-1-11-7.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-in-progress, size/M, jira/valid-reference, gitops

#79819 Revert "RHDEVDOCS-6123: Content creation for GitOps 1.12.5 RN"
  modules/gitops-release-notes-1-12-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: size/M, jira/valid-reference

#79821 removing the hugebook flag from 4.12 installing
  installing/hugeBook.flag
Labels: size/XS, branch/enterprise-4.12

#79827 GitOps 1.11.7 RN New PR
  modules/gitops-release-notes-1-11-7.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, sme-review-done, gitops

#79829 GitOps 1.12.5 RN New PR
  modules/gitops-release-notes-1-12-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, qe-approved, merge-review-in-progress, sme-review-done, gitops

#79826 OCPBUGS-37364-13: Cherry-pick for OCPBUGS-37364
  networking/aws_load_balancer_operator/aws-load-balancer-operator-release-notes.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-azure.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
Labels: size/S, jira/severity-important, jira/invalid-bug, jira/valid-reference

#79830 OCPBUGS-37364-12: Cherry-pick for OCPBUGS-37364
  networking/aws_load_balancer_operator/aws-load-balancer-operator-release-notes.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-azure.adoc
  networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
Labels: lgtm, size/S, jira/severity-important, jira/invalid-bug, merge-review-in-progress, jira/valid-reference

#79739 OBSDOCS-1097: Add more two callouts in the File Storage Extension section
  observability/otel/otel-collector/otel-collector-extensions.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79837 [gitops-1.12.0] GitOps 1.12.5 RN New PR
  modules/gitops-release-notes-1-12-5.adoc
  release_notes/gitops-release-notes.adoc
Labels: lgtm, size/M, merge-review-in-progress

#79847 [gitops-docs-1.11.0] GitOps 1.11.7 RN New PR
  modules/gitops-release-notes-1-11-7.adoc
  release_notes/gitops-release-notes.adoc
Labels: lgtm, size/M, merge-review-in-progress

#79533 OCPBUGS-37195: Clarify which OADP manifests are for target clusters in IBU docs
  modules/ztp-image-based-upgrade-installing-oadp.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#79785 Adds additional URLs to allowlist
  modules/configuring-firewall.adoc
Labels: peer-review-in-progress, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#78982 OSDOCS#39419: Fixing procedure for creating live migration policies
  modules/virt-configuring-a-live-migration-policy.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78357 OCPBUGS-32775#update requirements
  machine_management/adding-rhel-compute.adoc
  machine_management/more-rhel-compute.adoc
  modules/rhel-compute-requirements.adoc
  post_installation_configuration/node-tasks.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#79754 OSDOCS-11553: Move AWS Outposts content to install book
  _topic_maps/_topic_map.yml
  installing/installing_aws/ipi/installing-aws-outposts.adoc
  installing/installing_aws/ipi/installing-aws-vpc.adoc
  modules/aws-outposts-environment-info-aws.adoc
  modules/aws-outposts-environment-info-oc.adoc
  modules/aws-outposts-load-balancer-clb.adoc
  modules/aws-outposts-machine-set.adoc
  modules/aws-outposts-requirements-limitations.adoc
  modules/create-user-workloads-aws-edge.adoc
  modules/installation-cloudformation-subnet-localzone.adoc
  modules/installation-creating-aws-vpc-subnets-edge.adoc
  modules/nw-aws-load-balancer-with-outposts.adoc
  modules/nw-cluster-mtu-change.adoc
  post_installation_configuration/configuring-aws-outposts.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79860 [gitops-docs-1.14] Manual cp 79827 to 1.14
  modules/gitops-release-notes-1-11-6.adoc
  modules/gitops-release-notes-1-11-7.adoc
  release_notes/gitops-release-notes.adoc
Labels: lgtm, size/M, merge-review-in-progress

#76037 OSDOCS-3799 External DNS install CLI instructions
  modules/nw-installing-external-dns-operator-cli.adoc
  modules/nw-installing-external-dns-operator.adoc
  networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc
Labels: peer-review-done, size/L, qe-approved, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79646 OCPBUGS#37036: Fix `opm` base image
  modules/olm-creating-fb-catalog-image.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79717 OCPBUGS#32777: Update OperatorConditions to `v2`
  modules/olm-overriding-operatorconditions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79863 [enterprise-4.15] OSDOCS-11553: Move AWS Outposts content to install book
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-outposts.adoc
  installing/installing_aws/installing-aws-vpc.adoc
  modules/aws-outposts-environment-info-aws.adoc
  modules/aws-outposts-environment-info-oc.adoc
  modules/aws-outposts-load-balancer-clb.adoc
  modules/aws-outposts-machine-set.adoc
  modules/aws-outposts-requirements-limitations.adoc
  modules/create-user-workloads-aws-edge.adoc
  modules/installation-cloudformation-subnet-localzone.adoc
  modules/installation-creating-aws-vpc-subnets-edge.adoc
  modules/nw-aws-load-balancer-with-outposts.adoc
  modules/nw-cluster-mtu-change.adoc
  post_installation_configuration/configuring-aws-outposts.adoc
  release_notes/ocp-4-15-release-notes.adoc
Labels: size/L, jira/valid-reference

#79771 HCIDOCS-400: Wrong title for baremetal installation section
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_ibm_cloud/install-ibm-cloud-installation-workflow.adoc
  installing/overview/index.adoc
  modules/ipi-install-following-the-progress-of-the-installation.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#79596 OCPBUGS-30108: Move scattered postinstall content to image config section and remove unpublished content
  _topic_maps/_topic_map.yml
  modules/images-configuration-cas.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-parameters.adoc
  modules/images-configuration-registry-mirror-configuring.adoc
  modules/images-configuration-registry-mirror-convert.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/images-update-global-pull-secret.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/post-install-image-config.adoc
  post_installation_configuration/preparing-for-users.adoc
Labels: peer-review-done, size/L, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79890 [enterprise-4.13] Move scattered postinstall content to image config section
  _topic_maps/_topic_map.yml
  modules/images-configuration-cas.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-parameters.adoc
  modules/images-configuration-registry-mirror-configuring.adoc
  modules/images-configuration-registry-mirror-convert.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/images-update-global-pull-secret.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/post-install-image-config.adoc
  post_installation_configuration/preparing-for-users.adoc
Labels: size/L

#79891 [enterprise-4.12] Move scattered postinstall content to image config section
  _topic_maps/_topic_map.yml
  modules/images-configuration-cas.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-parameters.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/images-update-global-pull-secret.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/post-install-image-config.adoc
  post_installation_configuration/preparing-for-users.adoc
Labels: size/L

#79038 OSDOCS#11160: New max-unavailable and max-surge parameters
  modules/rosa-create-objects.adoc
  modules/rosa-edit-objects.adoc
  modules/rosa-hcp-upgrade-options.adoc
  modules/rosa-hcp-upgrading-cli-control-plane.adoc
  modules/rosa-hcp-upgrading-cli-machinepool.adoc
  modules/rosa-upgrade-cluster-cli.adoc
  rosa_release_notes/rosa-release-notes.adoc
  upgrading/rosa-hcp-upgrading.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78487 OSDOCS: CNV-40769 - Correcting SCSI type in LUN disk sharing doc (re-redux)
  modules/virt-configuring-disk-sharing-lun.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-shared-volumes-for-vms.adoc
Labels: size/S, CNV, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79839 OCPBUGS-37812: Removing erroneous mention of MTU
  modules/virt-example-vf-host-services.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#79838 [OSDOCS-11567]:Fix typo in "Creating a machine pool using the ROSA CLI" docs
  modules/creating-a-machine-pool-cli.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17

#79780 OBSDOCS-744: Document taint and toleration usage for Tempo/Jaeger/OTEL
  observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/otel/otel-installing.adoc
Labels: peer-review-done, lgtm, size/M, ok-to-test, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79879 Fix 404'd logo images and remove old OpenShift Online images
  404-commercial.html
  _templates/_footer_origin.html.erb
  _templates/_footer_other.html.erb
  index-commercial.html
  index-community.html
  scripts/ocpdocs/_footer_other.html.erb
  scripts/ocpdocs/index-commercial.html
  scripts/ocpdocs/search-commercial.html
  search-commercial.html
Labels: size/M

#79611 OCPBUGS#31297: Fixed typos
  modules/cnf-checking-numa-aware-scheduler-logs.adoc
  modules/cnf-reporting-more-exact-reource-availability.adoc
  modules/cnf-troubleshooting-numa-aware-workloads.adoc
  modules/nodes-vsphere-machine-set-concept-static-ip.adoc
  rest_api/console_apis/consolequickstart-console-openshift-io-v1.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79842 OCPBUGS-37808-412 removing vlanTrunk from bridge CNI
  modules/nw-multus-bridge-object.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress

#79919 Temp change for OWNERS
  OWNERS_ALIASES
Labels: size/S

#76262 Adjust private registry support statement
  modules/windows-containers-release-notes-limitations.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78920 TELCODOCS#1912: Added API endpoints for delete subscription and delete all subscriptions
  modules/cnf-fast-event-notifications-api-refererence.adoc
  networking/ptp/using-ptp-events.adoc
Labels: peer-review-done, size/M, telco, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79683 OADP-2493 Added a section for info about disable/enable node agent
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/oadp-about-disable-node-agent-dpa.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79942 Revert 79683: OADP-2493 Added a section for info about disable/enable node …
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/oadp-about-disable-node-agent-dpa.adoc
Labels: size/M

#79598 OSDOCS-10815:Troubleshooting long range Loki queries
  modules/troubleshooting-network-observability-loki-large-query-timeout.adoc
  observability/network_observability/troubleshooting-network-observability.adoc
Labels: peer-review-done, size/M, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79209 OCPBUGS-31434#adding IngressController update
  installing/overview/installing-preparing.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17

#79933 OCPBUGS-31434_4.13_2#adding IngressController update
  installing/overview/installing-preparing.adoc
Labels: size/XS, branch/enterprise-4.13

#79935 OCPBUGS-31434_4.14#adding IngressController update
  installing/overview/installing-preparing.adoc
Labels: size/XS, branch/enterprise-4.14

#79941 OCPBUGS-31434_4.15_2#adding IngressController update
  installing/overview/installing-preparing.adoc
Labels: size/XS, branch/enterprise-4.15

#79802 OSDOCS#10721: Disaster recovery - add a step to wait for redeployment to complete
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17

#79720 OSDOCS#10361: Removed Configuring AWS security groups to access the API.
  _unused_topics/rosa-hcp-aws-private-security-groups.adoc
  rosa_hcp/rosa-hcp-aws-private-creating-cluster.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17

#78695 OSDOCS#10151 - Improving ROSA disaster recovery and cluster state backup info
  modules/rosa-sdpolicy-platform.adoc
Labels: peer-review-in-progress, peer-review-done, size/L, SD-docs, branch/enterprise-4.16, branch/enterprise-4.17

#79680 Added few missing entries
  _templates/_page_openshift.html.erb
Labels: lgtm, size/XS

#79970 [enterprise-4.13] OCPBUGS#31297: Fixed typos
  modules/cnf-checking-numa-aware-scheduler-logs.adoc
  modules/cnf-reporting-more-exact-reource-availability.adoc
  modules/cnf-troubleshooting-numa-aware-workloads.adoc
  rest_api/console_apis/consolequickstart-console-openshift-io-v1.adoc
Labels: size/S

#79969 [enterprise-4.12] OCPBUGS#31297: Fixed typos
  modules/cnf-checking-numa-aware-scheduler-logs.adoc
  modules/cnf-reporting-more-exact-reource-availability.adoc
  modules/cnf-troubleshooting-numa-aware-workloads.adoc
  rest_api/console_apis/consolequickstart-console-openshift-io-v1.adoc
Labels: size/S

#79968 [enterprise-4.13] TELCODOCS#1912: Added API endpoints for delete subscription and delete all subscriptions
  modules/cnf-fast-event-notifications-api-refererence.adoc
Labels: size/M

#79967 [enterprise-4.12] TELCODOCS#1912: Added API endpoints for delete subscription and delete all subscriptions
  modules/cnf-fast-event-notifications-api-refererence.adoc
Labels: size/M

#79684 OCPBUGS-37699: Remove mode=6 balance-alb from networking docs
  modules/ipi-install-configuring-host-dual-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/virt-example-bond-nncp.adoc
  modules/virt-example-nmstate-multiple-interfaces.adoc
Labels: peer-review-done, lgtm, size/S, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79229 CNV-43385: Added networking architecture diagram
  images/318_OpenShift_Virtualization_Networking_0423.png
  virt/vm_networking/virt-networking-overview.adoc
Labels: peer-review-done, size/S, CNV, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79914 OCPBUGS-37863: Documented a private infra notice for ARO
  modules/installing-private-image-registry-private-azure.adoc
  modules/registry-configuring-private-storage-endpoint-azure.adoc
Labels: peer-review-done, lgtm, size/S, qe-approved, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79982 [enterprise-4.15] CNV-43385: Added networking architecture diagram
  images/318_OpenShift_Virtualization_Networking_0423.png
  virt/vm_networking/virt-networking-overview.adoc
Labels: size/S, jira/valid-reference

#79983 [enterprise-4.16] CNV-43385: Added networking architecture diagram
  images/318_OpenShift_Virtualization_Networking_0423.png
  virt/vm_networking/virt-networking-overview.adoc
Labels: size/S, jira/valid-reference

#79377 CNV-37647: 4.16-specific table comparing bridge CNI and OVN-K localnet
  virt/vm_networking/virt-networking-overview.adoc
Labels: lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.16

#79378 CNV-37647: 4.15-specific table comparing bridge CNI and OVN-K localnet
  virt/vm_networking/virt-networking-overview.adoc
Labels: lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.15

#79986 [enterprise-4.17] CNV-43385: Added networking architecture diagram
  images/318_OpenShift_Virtualization_Networking_0423.png
  virt/vm_networking/virt-networking-overview.adoc
Labels: size/S, jira/valid-reference

#79139 [OSDOCS-11353] Document the whitelist IPs required for the ingress access to the API server
  _topic_maps/_topic_map_osd.yml
  modules/ccs-gcp-customer-requirements.adoc
  osd_planning/gcp-ccs.adoc
  security/rh-required-whitelisted-IP-addresses-for-sre-access.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.16, branch/enterprise-4.17

#78942 OADP-4439: Release Notes for 1.3.3 and Version updates
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-release-notes-1-3-3.adoc
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference

#79245 OADP-4360 added troubleshooting info for PVR fail
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79963 [enterprise-4.15] OBSDOCS-1235: Removed 5.7z from 4.15
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.15

#80010 OSDOCS-42796: Fixed the default value of macspoofchk
  modules/virt-creating-linux-bridge-nad-cli.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#79192 CNV-37647: Added table comparing bridge CNI and OVN-K localnet
  virt/vm_networking/virt-networking-overview.adoc
Labels: peer-review-done, lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.17

#79971 Highlighted the verification command
  modules/etcd-increase-db.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#80020 WMCO unhiding docs from 10.16
  _topic_maps/_topic_map.yml
  installing/installing_aws/ipi/installing-aws-network-customizations.adoc
  installing/installing_azure/installing-azure-network-customizations.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  installing/overview/installing-preparing.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  welcome/index.adoc
  windows_containers/index.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.16

#74918 WMCO applies image mirroring settings to Windows instances and disconnected support
  modules/images-configuration-registry-mirror-configuring.adoc
  modules/images-configuration-registry-mirror.adoc
  modules/machineset-creating.adoc
  modules/wmco-disconnected-cluster.adoc
  snippets/idms-global-pull-secret.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.16, branch/enterprise-4.17

#80018 OSDOCS-11614: SPO 0.8.5 release notes
  security/security_profiles_operator/spo-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79796 OSDOCS-10967: Update responsibility matrix
  modules/rosa-policy-change-management.adoc
  modules/rosa-policy-responsibilities.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#78178 Updates limited live migration procedure to find various resources
  modules/checking-cluster-resources-after-initiating-limited-live-migration.adoc
  modules/checking-cluster-resources-before-initiating-limited-live-migration.adoc
  modules/initiating-limited-live-migration.adoc
  modules/nw-ovn-kubernetes-live-migration-about.adoc
  modules/nw-ovn-kubernetes-live-migration.adoc
  modules/patching-ovnk-address-ranges.adoc
  modules/removing-egress-router-pods-before-initiating-limited-live-migration.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
  networking/ovn_kubernetes_network_provider/rollback-to-openshift-sdn.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.16, branch/enterprise-4.17

#79655 Removing backtic from ovn checking migration command
  modules/nw-ovn-kubernetes-checking-live-migration-metrics.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#79783 [enterprise-4.17] CNV#40186: Placeholder file for 4.17 RN
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17

#80021 OCP-4.13: OADP-4439: Release Notes and Atrributes Update for OADP 1.3.3
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-release-notes-1-3-3.adoc
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-done, size/M, OADP, jira/valid-reference, branch/enterprise-4.13

#75198 WMCO 10.16.0 release notes
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/wmco-prerequisites.adoc
  windows_containers/windows-containers-release-notes-10-15-x.adoc
  windows_containers/windows-containers-release-notes-10-16-x.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.16

#80023 OCP-4.12: OADP-4439: Release Notes and Attributes for OADP 1.3.3
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-release-notes-1-3-3.adoc
  modules/velero-oadp-version-relationship.adoc
Labels: size/M, OADP, jira/valid-reference

#80049 [ENTERPRISE-4.12] OCPBUGS-37699: Remove mode=6 balance-alb from networking docs
  modules/virt-example-bond-nncp.adoc
  modules/virt-example-nmstate-multiple-interfaces.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference

#79972 Highlight the `oc patch etcd/cluster` command
  modules/etcd-tuning-parameters.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#75737 OCPBUGS-19976: Update NFD operator installation to add label cluster-monitoring=true
  modules/psap-installing-node-feature-discovery-operator.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79682 Add feature gate prerequisite for machine config nodes feature
  machine_configuration/index.adoc
  modules/checking-mco-node-status.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#79965 CNV-41664: Wording improvement to monitoring alerts
  observability/monitoring/managing-alerts.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78778 OSDOCS-9350-deepdive-1 for External IP assigned to a svc
  modules/nw-externalip-about.adoc
  modules/nw-ingress-sharding-route-labels.adoc
  modules/nw-overlapped-sharding.adoc
  modules/nw-service-externalip-create.adoc
  networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79962 [enterprise-4.16] OBSDOCS-1235: Removed Logging 5.7z and 5.8z from 4.16
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#78823 OSDOCS#42796: Fixing the default value of macspoofchk
  modules/virt-creating-linux-bridge-nad-cli.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78439 TELCODOCS-1932: Implement post-GA SME feedback
  modules/cnf-image-based-upgrade-backup-guide.adoc
  modules/cnf-image-based-upgrade-extra-manifests-guide.adoc
  modules/cnf-image-based-upgrade-generate-seed-image.adoc
  modules/cnf-image-based-upgrade-seed-image-config.adoc
  modules/cnf-image-based-upgrade-seed-image-guide.adoc
  modules/cnf-image-based-upgrade-shared-container-partition.adoc
  modules/cnf-image-based-upgrade-troubleshooting.adoc
  modules/cnf-image-based-upgrade.adoc
  modules/ztp-image-based-upgrade-shared-container-partition.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#78382 Pipelines 5988: Update override for git resolver
  create/remote-pipelines-tasks-resolvers.adoc
  modules/op-resolver-git-anon.adoc
  modules/op-resolver-git-config-scm.adoc
  modules/op-resolver-git-override-scm.adoc
  modules/op-resolver-git-scm.adoc
Labels: peer-review-done, size/L, ok-to-test, merge-review-in-progress, merge-review-needed, pipelines

#79107 RHDEVDOCS-6101: DOC: Add a flag on controllers to configure resyncPeriod in openshift-pipelines
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/op-setting-resync-period.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#79927 [SRVOCF-569] Fix pipeline tasks links
  modules/odc-creating-functions.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-in-progress, merge-review-needed

#80082 CNV-37089: HCO version bump for 4.15.4
  _attributes/common-attributes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.15

#79374 Replace script in 'Creating a Restore CR'
  modules/oadp-creating-restore-cr.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80085 OSDOCS-11592 Changing date format in OCP 4.13 RNs
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13

#80038 OSDOCS-11564 Core OCP 4.16.6 Release Notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#80083 Update rosa-sdpolicy-am-limited-support.adoc
  modules/rosa-sdpolicy-am-limited-support.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#75742 "drop" config should be an array in ClusterLogForwarder
  modules/logging-content-filter-drop-records.adoc
Labels: lgtm, size/XS, ok-to-test, merge-review-in-progress, merge-review-needed

#79985 CNV-45636: WASP documentation fix
  modules/virt-using-wasp-agent-to-configure-higher-vm-workload-density.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#80086 OSDOCS-11592 4.14 RNs date format change
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed, branch/enterprise-4.14

#80094 OSDOCS-11592 OCP 4.16 RNs updating date format
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-needed

#80093 OSSM:6889: Update scripts directory for service mesh 3.0 standalone doc
  scripts/check-asciidoctor-build.sh
  scripts/check-rn-link-perms.sh
  scripts/get-updated-distros.sh
  scripts/manualpreview.sh
  scripts/ocpdocs/_footer_other.html.erb
  scripts/ocpdocs/_previewpage
  scripts/ocpdocs/index-commercial.html
  scripts/ocpdocs/search-commercial.html
  scripts/prow-smoke-test.sh
  scripts/prow/README.adoc
  scripts/prow/add-new-prow-config.sh
  scripts/prow/openshift-openshift-docs-BRANCH.yaml
Labels: lgtm, size/L

#78619 OADP-4452 updated kubernetes images to kubernetes resources
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-cr.adoc
  modules/oadp-creating-backup-cr.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79916 OSDOCS-10922: adds 4.16.6 async relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#79918 OSDOCS-11137: adds 4.15.25 async relnote MicroShift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#79961 OSDOCS-11160 OSDOCS-11610 Updates to max-surge and max-unavailable
  modules/rosa-hcp-upgrade-options.adoc
  modules/rosa-hcp-upgrading-cli-machinepool.adoc
  modules/rosa-hcp-upgrading-cli-tutorial.adoc
  modules/rosa-upgrade-cluster-cli.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79848 OCPBUGS-37822: Add new permission required for forwarding rules labels
  modules/minimum-required-permissions-ipi-gcp.adoc
  modules/minimum-required-permissions-upi-gcp.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference, branch/enterprise-4.17

#78480 OSDOCS#11053: Removing incorrect name attribute for rosa edit mpool
  modules/creating-a-machine-pool-cli.adoc
  modules/removing-custom-config-from-machinepool.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-edit-objects.adoc
  modules/rosa-list-objects.adoc
  modules/rosa-node-drain-grace-period.adoc
  modules/setting-higher-pid-limit-on-machinepool.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#80081 OSDOCS-40769: Corrected SCSI type in LUN disk sharing section
  modules/virt-configuring-disk-sharing-lun.adoc
  virt/virtual_machines/virtual_disks/virt-configuring-shared-volumes-for-vms.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed

#80107 TELCODOCS-1980: fixing broken link
  modules/telco-core-ref-application-workloads.adoc
  modules/telco-ran-du-application-workloads.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80129 [OCPSTRAT-1516]: Adding known issue back to the release notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: size/XS

#80112 CNV_36963: Fixing broken xrefs in CNV 4.14 (cherrypick OCPBUGS_24463 to 4.14)
  virt/vm_networking/virt-connecting-vm-to-linux-bridge.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed

#79163 RHDEVDOCS-6086: Enable Tekton Chains to operate only in selected name…
  modules/op-enabling-tekton-chains-to-operate-only-in-selected-namespaces.adoc
  secure/using-tekton-chains-for-openshift-pipelines-supply-chain-security.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#79906 OSDOCS-11347: adds 4.14.34 relnotes Microshift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-needed, jira/valid-reference

#79380 OSDOCS-11435: Network Observability 1.6.1 release notes
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80137 [enterprise-4.14] TELCODOCS-1980: fixing broken link
  modules/telco-core-ref-application-workloads.adoc
  modules/telco-ran-du-application-workloads.adoc
Labels: size/XS, jira/valid-reference

#77982 OSSM-6457 OSSM 2.6.0 (At Stage): [DOC] Release Notes, Known Issues an…
  _attributes/common-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78463 OSSM-6772 [DOC] Remove commands from Clean up Operator resources
  modules/ossm-remove-cleanup.adoc
Labels: peer-review-done, size/S, service-mesh, merge-review-in-progress, merge-review-needed

#78142 OSSM-6713 [DOC] Installation and upgrade tasks for OSSM 2.6 release
  modules/ossm-upgrade-25-26-changes.adoc
  service_mesh/v2x/upgrading-ossm.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#77583 OSSM-6302 [DOC] Tempo + OTEL configuration
  modules/ossm-configuring-distr-tracing-tempo.adoc
  modules/ossm-enabling-jaeger.adoc
  service_mesh/v2x/ossm-observability.adoc
Labels: peer-review-done, size/L, service-mesh, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#77073 OSDOCS-10467: Update AWS EFS for ROSA/OSD
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-what-is-rosa.adoc
  modules/persistent-storage-csi-about.adoc
  modules/persistent-storage-csi-efs-driver-install.adoc
  modules/persistent-storage-csi-olm-operator-install.adoc
  modules/persistent-storage-efs-csi-driver-operator-setup.adoc
  modules/sd-persistent-storage-csi-efs-sts.adoc
  storage/container_storage_interface/persistent-storage-csi-aws-efs.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#80181 Revert "OADP-4439: Release Notes for 1.3.3 and Version updates"
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-release-notes-1-3-3.adoc
  modules/velero-oadp-version-relationship.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#80150 Fixing link formatting in release notes
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78340 OSSM-6260: Document migration from SMCP managed gateways Part of Service Mesh 2.6 release
  _topic_maps/_topic_map.yml
  modules/ossm-about-gateway-migration.adoc
  modules/ossm-migrating-from-ior-to-explicitly-managed-routes.adoc
  modules/ossm-migrating-from-smcp-defined-gateways-to-gateway-injection.adoc
  service_mesh/v2x/ossm-gateway-migration.adoc
  service_mesh/v2x/ossm-route-migration.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference

#80155 [enterprise-4.13] Updates firewall config docs for 4.13
  modules/configuring-firewall.adoc
Labels: size/S, branch/enterprise-4.13

#80022 11612 ir release note
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#80156 ROX:14466: Update docs for default network policy disable
  modules/central-configuration-options-operator.adoc
  modules/central-services-public-config.adoc
  modules/install-central-operator.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: size/M

#79342 Replace 'minio' with a generic term in sample YAML files
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-secrets-for-different-credentials.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80092 OSDOCS-11592 OCP RN 4.15 Changing date format
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#78179 [OCPBUGS#25223] Document changes needed on installer host when running dualstack when using a proxy
  modules/install-osp-deploy-dualstack.adoc
  modules/install-osp-dualstack.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80206 [enterprise-4.13] OSSM-6260: Document migration from SMCP managed gateways
  _topic_maps/_topic_map.yml
  modules/ossm-about-gateway-migration.adoc
  modules/ossm-migrating-from-ior-to-explicitly-managed-routes.adoc
  modules/ossm-migrating-from-smcp-defined-gateways-to-gateway-injection.adoc
  service_mesh/v2x/ossm-gateway-migration.adoc
  service_mesh/v2x/ossm-route-migration.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: size/L, jira/valid-reference

#80204 [enterprise-4.12] OSSM-6260: Document migration from SMCP managed gateways
  _topic_maps/_topic_map.yml
  modules/ossm-about-gateway-migration.adoc
  modules/ossm-migrating-from-ior-to-explicitly-managed-routes.adoc
  modules/ossm-migrating-from-smcp-defined-gateways-to-gateway-injection.adoc
  service_mesh/v2x/ossm-gateway-migration.adoc
  service_mesh/v2x/ossm-route-migration.adoc
  service_mesh/v2x/ossm-traffic-manage.adoc
Labels: size/L, jira/valid-reference

#80048 RHDEVDOCS-5983: DOC: Records/Logs retention configuration in Tekton R…
  modules/op-configuring-retention-policy-results.adoc
  records/using-tekton-results-for-openshift-pipelines-observability.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#80136 [OSDOCS-11199] changing instances of Clusters to Cluster List with new OCM UI change
  modules/access-service.adoc
  modules/add-user.adoc
  modules/adding-service-existing.adoc
  modules/config-github-idp.adoc
  modules/config-gitlab-idp.adoc
  modules/config-google-idp.adoc
  modules/config-htpasswd-idp.adoc
  modules/config-ldap-idp.adoc
  modules/config-openid-idp.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/deleting-service.adoc
  modules/deploy-app.adoc
  modules/insights-operator-manual-upload.adoc
  modules/insights-operator-register-disconnected-cluster.adoc
  modules/ocm-disabling-autoscaling-nodes.adoc
  modules/ocm-enabling-autoscaling-nodes.adoc
  modules/reviewing-cluster-status-from-the-openshift-cluster-manager.adoc
  modules/rosa-delete-users.adoc
  modules/support-get-cluster-id.adoc
  modules/support-reviewing-an-access-request-from-the-hybrid-console.adoc
  modules/support-submitting-a-case.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#80215 Revert "Update docs for default network policy disable"
  modules/central-configuration-options-operator.adoc
  modules/central-services-public-config.adoc
  modules/install-central-operator.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: size/M

#80128 Adds an ifdef to remove content from SDN docs
  modules/nw-egress-ips-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80133 OSDOCS-11565: 4.14.34 rn
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14

#80227 [enterprise-414.] Adds an ifdef to remove content from SDN docs
  modules/nw-egress-ips-about.adoc
Labels: size/XS

#79006 CNV#41400 : Storage checkup is missing UI documentation
  modules/virt-checking-cluster-dpdk-readiness.adoc
  modules/virt-checking-storage-configuration.adoc
  modules/virt-latency-checkup-web-console.adoc
  modules/virt-measuring-latency-vm-secondary-network.adoc
  modules/virt-storage-checkup-web-console.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: peer-review-done, size/M, CNV, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79883 OCPBUGS#35942: Remove OLMv1 dependency resolution topics
  _topic_maps/_topic_map.yml
  _unused_topics/olmv1-dependency-concepts.adoc
  _unused_topics/olmv1-dependency.adoc
  modules/olmv1-finding-operators-to-install.adoc
  modules/olmv1-version-range-support.adoc
  operators/olm_v1/olmv1-installing-an-operator-from-a-catalog.adoc
  snippets/olmv1-multi-catalog-admon.adoc
  snippets/olmv1-tp-extension-support.adoc
Labels: peer-review-done, size/S, px-approved, branch/enterprise-4.16, branch/enterprise-4.17

#80214 OCPBUGS-35405-414 Enabling cgroup v2 is not possible if you are using
  modules/nodes-clusters-cgroups-2.adoc
  scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#80146 OSDOCS-11563-known-issue
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#80222 [enterprise-4.13] Replace 'minio' with a generic term in sample YAML files
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-secrets-for-different-credentials.adoc
Labels: size/M

#80145 OCPBUGS#21125: Add scope and type to `allowedSourceRanges` example command
  modules/nw-configuring-lb-allowed-source-ranges.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80084 OCPBUGS-37993: List "Configuring MetalLB with an L2 advertisement and label" in "Next Steps"
  networking/metallb/metallb-configure-address-pools.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#79836 OADP-4657: velero relationship table to include 4.13
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference

#80261 [enterprise-4.13]: OADP-4657: velero relationship table to include 4.13
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-needed, size/XS, OADP, jira/valid-reference

#80262 [enterprise-4.14]: OADP-4657: velero relationship table to include 4.13
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-needed, size/XS, OADP, jira/valid-reference

#80265 [enterprise-4.15]: OADP-4657: velero relationship table to include 4.13
  modules/velero-oadp-version-relationship.adoc
Labels: peer-review-needed, size/XS, OADP, jira/valid-reference

#80071 OCPBUGS-35405 Enabling cgroup v2 is not possible if you are using performance profiles.
  modules/nodes-clusters-cgroups-2.adoc
  scalability_and_performance/low_latency_tuning/cnf-tuning-low-latency-nodes-with-perf-profile.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#80271 HCIDOCS-400: cherry pick for 79078
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_ibm_cloud/install-ibm-cloud-installation-workflow.adoc
  installing/overview/index.adoc
  modules/ipi-install-following-the-progress-of-the-installation.adoc
Labels: size/M, jira/valid-reference

#80272 HCIDOCS-400 cherry pick for 79078
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_ibm_cloud/install-ibm-cloud-installation-workflow.adoc
  installing/overview/index.adoc
  modules/ipi-install-following-the-progress-of-the-installation.adoc
Labels: size/M

#80273 HCIDOCS-400: Cherry pick for 79078
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_ibm_cloud/install-ibm-cloud-installation-workflow.adoc
  installing/overview/index.adoc
  modules/ipi-install-following-the-progress-of-the-installation.adoc
Labels: size/M, jira/valid-reference

#80274 HCIDOCS-400: Cherry pick for 79078
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_ibm_cloud/install-ibm-cloud-installation-workflow.adoc
  installing/overview/index.adoc
  modules/ipi-install-following-the-progress-of-the-installation.adoc
Labels: size/M, jira/valid-reference
