Repository openshift/openshift-docs, pull requests merged in 2024-09, with the labels that each got.

#81207 [enterprise-4.12] OBSDOCS-71: [POC] Observability operators upgrade resource
  observability/index.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference

#81208 [enterprise-4.13] OBSDOCS-71: [POC] Observability operators upgrade resource
  observability/index.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, jira/valid-reference

#81068 [OSDOCS-11363] Updating images-configuration-allowed to correct MCO…
  modules/images-configuration-allowed.adoc
Labels: peer-review-in-progress, peer-review-needed, lgtm, size/XS, ok-to-test, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#78839 OCPBUGS-34611-new: Documented the additional br-ex
  modules/configuring-ovnk-use-second-ovs-bridge.adoc
  support/troubleshooting/troubleshooting-network-issues.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80236 OSDOCS-11444: Adds low latency to MicroShift
  _attributes/attributes-microshift.adoc
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift_low_latency/_attributes
  microshift_configuring/microshift_low_latency/images
  microshift_configuring/microshift_low_latency/microshift-low-latency.adoc
  microshift_configuring/microshift_low_latency/microshift-workload-partitioning.adoc
  microshift_configuring/microshift_low_latency/modules
  microshift_configuring/microshift_low_latency/snippets
  modules/microshift-config-yaml.adoc
  modules/microshift-install-rpms-low-latency.adoc
  modules/microshift-low-latency-concept.adoc
  modules/microshift-low-latency-config-yaml.adoc
  modules/microshift-low-latency-install-kernelrt-rhel-edge.adoc
  modules/microshift-low-latency-install-kernelrt-rpm.adoc
  modules/microshift-low-latency-kernelrt-conc.adoc
  modules/microshift-low-latency-prepare-workload.adoc
  modules/microshift-low-latency-rhel-edge-blueprint-rtk.adoc
  modules/microshift-low-latency-tuned-auto.adoc
  modules/microshift-low-latency-tuned-conc.adoc
  modules/microshift-low-latency-tuned-profile.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.17

#80723 OSSM-7054 OSSM 2.6.1 (At Stage): [DOC] Release Notes, Known Issues and Bug Fixes
  _attributes/common-attributes.adoc
  modules/ossm-release-2-4-10.adoc
  modules/ossm-release-2-5-4.adoc
  modules/ossm-release-2-6-1.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
Labels: peer-review-done, size/L, service-mesh, qe-approved, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81218 OSDOCS-11865: remove unresolved attribute
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80603 Adds docs for OMR version 2
  modules/mirror-registry-flags.adoc
  modules/mirror-registry-localhost-update.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.16, branch/enterprise-4.17

#81246 OSDOCS-11870: remove broken xref MicroShift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#78987 OPCBUGS-36928#Enabling swap node clarification
  modules/nodes-nodes-swap-memory.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17

#81251 OSSM 3.0 TP1: OSSM-8038 [DOC] Swap Kiali and Metrics in _topic_map
  _topic_maps/_topic_map.yml
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed

#81254 [enterprise-4.17] Adds docs for OMR version 2
  modules/mirror-registry-flags.adoc
  modules/mirror-registry-localhost-update.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
Labels: size/L, branch/enterprise-4.16, branch/enterprise-4.17

#81178 [OSDOCS-11001]: Adding more virt docs for HCP
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  hosted_control_planes/hcp-manage/hcp-manage-virt.adoc
  modules/hcp-virt-access.adoc
  modules/hcp-virt-csi-snapshot.adoc
  modules/hcp-virt-etcd-storage.adoc
  modules/hcp-virt-image-caching.adoc
  modules/hcp-virt-map-storage.adoc
  modules/hcp-virt-multiple-snapshots.adoc
  modules/hcp-virt-root-volume.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17

#81268 [enterprise-4.15] Adds OMR 2.0 release notes
  modules/mirror-registry-flags.adoc
  modules/mirror-registry-localhost-update.adoc
  modules/mirror-registry-release-notes.adoc
  modules/mirror-registry-remote-host-update.adoc
Labels: size/M, branch/enterprise-4.15

#81260 OSDOCS-11870-2: update xrefs MicroShift 4.17.y
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#81247 OSDOCS-11835: 4.16.10 RN
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.16

#81124 OSDOCS-11680: adds relnote 4.16.10 MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#81274 [11868]:What's new for OSD on GCP: Support Document Support A2 (NVIDIA A100 80 GB) GCP nodes
  osd_whats_new/osd-whats-new.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.16, branch/enterprise-4.17

#80911 OSDOCS-11784: removes SDN from commands and misc spots
  _unused_topics/monitoring-monitoring-overview.adoc
  modules/assisted-installer-using-the-assisted-installer.adoc
  modules/baseline-router-performance.adoc
  modules/configuring-default-seccomp-profile.adoc
  modules/dr-restoring-cluster-state-about.adoc
  modules/getting-started-cli-examining-pod.adoc
  modules/how-to-plan-your-environment-according-to-cluster-maximums.adoc
  modules/ibm-z-choose-networking-setup.adoc
  modules/installation-osp-creating-sr-iov-compute-machines.adoc
  modules/installation-osp-modifying-networktype.adoc
  modules/installation-vsphere-installer-network-requirements.adoc
  modules/investigating-master-node-installation-issues.adoc
  modules/metering-viewing-report-results.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nodes-containers-events-viewing.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-pods-priority-about.adoc
  modules/nw-cno-view.adoc
  modules/nw-egress-router-about.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-high-performance-multicast.adoc
  modules/nw-metallb-infra-considerations.adoc
  modules/nw-multus-add-pod.adoc
  modules/nw-networkpolicy-about.adoc
  modules/nw-ovn-kubernetes-live-migration-about.adoc
  modules/nw-ovn-kubernetes-migration-about.adoc
  modules/policy-shared-responsibility.adoc
  modules/security-network-egress.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.17

#81151 OBSDOCS-1272: Add documentation for Prometheus Remote Write Exporter
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#79422 OSDOCS-11236: Add guidance about dual-stack networking limitations
  installing/installing_bare_metal/installation-config-parameters-bare-metal.adoc
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/S, ok-to-merge, jira/valid-reference

#80135 OBSDOCS-1124: Release notes for Distributed tracing 3.3
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/otel/otel-rn.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#81063 OSDOCS-11539: Cluster administration - Classic to HCP migration
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/creating-a-machine-pool-cli.adoc
  modules/creating-a-machine-pool-ocm.adoc
  modules/dedicated-aws-vpc-verifying-troubleshooting.adoc
  modules/dedicated-aws-vpn-verifying.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/nodes-cluster-resource-configure-about.adoc
  modules/nodes-cluster-resource-configure-jdk.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/ocm-disabling-autoscaling-nodes.adoc
  modules/ocm-enabling-autoscaling-nodes.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-adding-taints.adoc
  modules/rosa-adding-tuning.adoc
  modules/rosa-disabling-autoscaling-nodes.adoc
  modules/rosa-enabling-autoscaling-nodes.adoc
  modules/rosa-node-drain-grace-period.adoc
  modules/rosa-scaling-worker-nodes.adoc
  nodes/clusters/nodes-cluster-resource-configure.adoc
  rosa_cluster_admin/cloud_infrastructure_access/rosa-configuring-private-connections.adoc
  rosa_cluster_admin/rosa-cluster-notifications.adoc
  rosa_cluster_admin/rosa-configuring-pid-limits.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
Labels: lgtm, size/XL, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#81240 OSDOCS#38323: Adding BZ#2151169 to known issues in 4.15 - 4.17
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS

#81291 MCO node disruption policy typo fixes
  modules/machine-config-node-disruption-example.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.16, branch/enterprise-4.17

#81128 CNV#40179: Doc VMSnapshot API is now v1beta1
  modules/virt-creating-vm-snapshot-cli.adoc
  modules/virt-restoring-vm-from-snapshot-cli.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress

#81253 OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80284 [enterprise-4.13] TELCODOCS-1838-413 Update reference SiteConfig to use rootDeviceHints wit…
  modules/ztp-configuring-disk-partitioning.adoc
  modules/ztp-deploying-a-site.adoc
  modules/ztp-precaching-ztp-config.adoc
  modules/ztp-sno-siteconfig-config-reference.adoc
Labels: peer-review-done, size/L, telco, branch/enterprise-4.13

#81302 [enterprise-4.16] MCO node disruption policy typo fixes
  modules/machine-config-node-disruption-example.adoc
Labels: size/XS

#81303 [enterprise-4.16] MCO node disruption policy typo fixes
  modules/machine-config-node-disruption-example.adoc
Labels: size/XS

#81275 OCPBUGS-17663: add admonition about multipathing
  modules/troubleshooting-enabling-kdump.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-moderate, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81310 [enterprise-4.17] Cherry-pick of OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs #81253
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, jira/valid-reference

#81309 [enterprise-4.16] Cherry-pick of OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs #81253
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, jira/valid-reference

#81307 [enterprise-4.15] Cherry-pick of OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs #81253
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, jira/valid-reference

#81306 [enterprise-4.14] Cherry-pick of OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs #81253
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, jira/valid-reference

#81304 [enterprise-4.12] Cherry-pick of OBSDOCS-1293: Distributed Tracing and OpenTelemetry 3.3 docs #81253
  modules/distr-tracing-tempo-config-receiver-tls-for-tempomonolithic.adoc
  modules/distr-tracing-tempo-config-receiver-tls-for-tempostack.adoc
  modules/distr-tracing-tempo-object-storage-setup-aws-sts-install.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-installing.adoc
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
  observability/otel/otel-rn.adoc
  snippets/distr-tracing-tempo-required-secret-parameters.adoc
Labels: size/XL, needs-rebase, jira/valid-reference

#81281 OSDOCS#35593: Updated example resource for auto-updates - redux
  modules/virt-autoupdate-custom-bootsource.adoc
Labels: size/XS, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80746 OSDOCS#11238: Add relnote for etcd certificate automatic rotation
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17

#81300 Revert "OSSM-6457 OSSM 2.6.0 (At Stage): [DOC] Release Notes, Known I…
  _attributes/common-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.13

#81301 Revert "OSSM-6457 OSSM 2.6.0 (At Stage): [DOC] Release Notes, Known I…
  _attributes/common-attributes.adoc
  modules/ossm-rn-fixed-issues.adoc
  modules/ossm-rn-known-issues.adoc
  modules/ossm-rn-new-features.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.14

#75864 OCPBUGS#33598: The FROM clauses on Containerfile examples of RHCOS image layering are wrong
  machine_configuration/mco-coreos-layering.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81122 OSDOCS-11547: adds relnote MicroShift 4.15.30
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#81331 [enterprise-4.15] OCPBUGS#33606-15: Added z-stream update note for SDN to OVNK migration
  modules/nw-ovn-kubernetes-migration-about.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, merge-review-in-progress

#81332 [enterprise-4.14] OCPBUGS#33606-14: Added z-stream update note for SDN to OVNK migration
  modules/nw-ovn-kubernetes-migration-about.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, merge-review-in-progress

#81333 [enterprise-4.13] OCPBUGS-33606#13: Added z-stream update note for SDN to OVNK migration
  modules/nw-ovn-kubernetes-migration-about.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, merge-review-in-progress

#81334 [enterprise-4.12] OCPBUGS#33606-12: Added z-stream update note for SDN to OVNK migration
  modules/nw-ovn-kubernetes-migration-about.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, merge-review-in-progress

#81219 CNV-46221: Add link to upstream docs metric list
  modules/virt-querying-metrics.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference

#81323 [OSDOCS-11001]: Moving HCP distributing workloads docs
  hosted_control_planes/hcp-prepare/hcp-distribute-workloads.adoc
  modules/hcp-labels-taints.adoc
  modules/hcp-priority-classes.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.17

#80285 [enterprise-4.12] TELCODOCS-1838-412 Update reference SiteConfig to use rootDeviceHints
  _attributes/common-attributes.adoc
  modules/ztp-configuring-disk-partitioning.adoc
  modules/ztp-deploying-a-site.adoc
  modules/ztp-precaching-ztp-config.adoc
  modules/ztp-sno-siteconfig-config-reference.adoc
  snippets/ztp_example-sno.yaml
Labels: peer-review-done, size/L, telco, branch/enterprise-4.12

#81277 Adds azure shared access key bug doc text to release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17

#81156 OSDOCS-11561: adding back ticks for user values in microshift
  modules/microshift-adding-other-packages-to-blueprint.adoc
  modules/microshift-adding-service-to-blueprint.adoc
  modules/microshift-audit-logs-config-proc.adoc
  modules/microshift-check-journal-logs-updates.adoc
  modules/microshift-creating-ostree-iso.adoc
  modules/microshift-gitops-adding-apps.adoc
  modules/microshift-nw-enforcing-hsts-per-domain.adoc
  modules/microshift-nw-multus-add-pod.adoc
  modules/microshift-olm-deploy-ops-spec-ns.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.17

#81265 CNV-47108: HCO version update for 4.16.2
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.16

#80755 [OSDOCS-11408] bug fix updates from PM feedback
  modules/rosa-create-objects.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17

#81199 PR for SRVCOM-3241: Update broken links in "Observability → Tracing → Tracing Requests" Section.
  observability/tracing/serverless-tracing.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference

#80732 OSDOCS 11742 fix direct https includes with huge books
  build_for_portal.py
Labels: size/XS

#81311 MCO node disruption policy typo fixes 2
  modules/machine-config-node-disruption-example.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17

#81347 OBSDOCS-1124: Update
  observability/otel/otel-rn.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80234 ROX:25607: disable RHACS default network policies option
  modules/central-configuration-options-operator.adoc
  modules/central-services-public-config.adoc
  modules/install-central-operator.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.5, rhacs-docs-4.6

#81344 PR for SRVLOGIC-370: Create an initial PR that sets up the basic OSL "Supporting services" directory structure.
  _topic_maps/_topic_map.yml
  serverless-logic/serverless-logic-supporting-services/_attributes
  serverless-logic/serverless-logic-supporting-services/images
  serverless-logic/serverless-logic-supporting-services/modules
  serverless-logic/serverless-logic-supporting-services/serverless-logic-data-index.adoc
  serverless-logic/serverless-logic-supporting-services/serverless-logic-job-service.adoc
  serverless-logic/serverless-logic-supporting-services/snippets
Labels: peer-review-done, size/M, serverless, jira/valid-reference

#81054 Update logging-audit-log-filtering.adoc
  modules/logging-audit-log-filtering.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81177 OSDOCS-11837 OCP Release Notes 4.15.30
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#80835 OCPBUGS-15814 Updated step 5 in the Running the Installation section
  modules/cco-ccoctl-install-creating-manifests.adoc
  modules/sts-mode-installing-manual-run-installer.adoc
Labels: peer-review-done, size/XS, ok-to-test, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81324 [OSDOCS-11001]: Moving IBM Z docs for HCP
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
  hosted_control_planes/hcp-manage/hcp-manage-ibmz.adoc
  modules/hcp-bm-hc.adoc
  modules/hcp-ibmz-dns.adoc
  modules/hcp-ibmz-infra-reqs.adoc
  modules/hcp-ibmz-infraenv.adoc
  modules/hcp-ibmz-kvm-agents.adoc
  modules/hcp-ibmz-lpar-agents.adoc
  modules/hcp-ibmz-prereqs.adoc
  modules/hcp-ibmz-scale-np.adoc
  modules/hcp-ibmz-zvm-agents.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.17

#81407 Updating Prow README
  scripts/prow/README.adoc
Labels: size/S

#80365 OCPBUGS#38352: Updated the Supported network plugin feature matrix table
  _attributes/common-attributes.adoc
  modules/nw-ovn-kubernetes-features.adoc
  modules/nw-ovn-kubernetes-matrix.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80936 [SRVCOM-2455] Add a mention of disconnected support
  install/preparing-serverless-install.adoc
Labels: peer-review-done, lgtm, size/XS, serverless

#80940 OSDOCS-11783:updates metadata on SDN removal
  modules/nw-egress-ips-static.adoc
  modules/nw-egress-router-about.adoc
  modules/nw-egress-router-configmap.adoc
  modules/nw-egress-router-dest-var.adoc
  modules/nw-egress-router-dns-mode.adoc
  modules/nw-egress-router-http-proxy-mode.adoc
  modules/nw-egress-router-pod.adoc
  modules/nw-egress-router-redirect-mode.adoc
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-egressnetworkpolicy-delete.adoc
  modules/nw-egressnetworkpolicy-edit.adoc
  modules/nw-egressnetworkpolicy-object.adoc
  modules/nw-egressnetworkpolicy-view.adoc
  modules/nw-enabling-multicast.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17

#80881 OCPBUGS#38762: Updated the Creating an IAM role for the AWS Load Bala…
  _topic_maps/_topic_map.yml
  modules/aws-installing-an-aws-load-balancer-operator.adoc
  modules/specifying-role-arn-albo-sts.adoc
  modules/using-aws-cli-create-iam-role-alb-controller.adoc
  modules/using-aws-cli-create-iam-role-alb-operator.adoc
  modules/using-ccoctl-create-iam-role-alb-controller.adoc
  modules/using-ccoctl-create-iam-role-alb-operator.adoc
  networking/aws_load_balancer_operator/installing-albo-sts-cluster.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.16, branch/enterprise-4.17

#78023 OSDOCS - CNV-38323: Reverting a bug fix description in the RNs
  virt/release_notes/virt-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#81418 OSDOCS#38323 - moving KI#2151169 to the proper section
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: size/XS, branch/enterprise-4.17

#81422 OSDOCS#38323: Adding a description for KI #2151169
  virt/release_notes/virt-4-16-release-notes.adoc
Labels: size/XS, merge-review-in-progress

#80515 #CNV41848 - nhc vs mhc edit
  virt/nodes/virt-triggering-vm-failover-resolving-failed-node.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81255 OSSM 3.0 TP1: OSSM-8039 [DOC] Additional Prereq needed for Configuring OpenShift Monitoring with Kiali
  kiali/ossm-kiali-assembly.adoc
  modules/ossm-config-openshift-monitoring-kiali.adoc
Labels: peer-review-done, size/XS, service-mesh, merge-review-in-progress, merge-review-needed

#81115 OSDOCS#11824: Remove the architecture diagram from the OPP doc
  modules/opp-architecture-architecture.adoc
Labels: peer-review-done, size/XS, merge-review-needed

#81429 Enterprise#4-12 - OADP-4750: configure OADP NodeAgents on nodes with worker, infra or custom labels
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/oadp-api.adoc
  modules/oadp-configuring-node-agents.adoc
  modules/oadp-setting-resource-limits-and-requests.adoc
  snippets/oadp-nodeselector-snippet.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference

#81326 OSDOCS-11886: Adding tutorial for custom dhcp option sets
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-custom-dns-resolver.adoc
Labels: peer-review-done, size/L, jira/valid-reference, SD-docs, branch/enterprise-4.16, branch/enterprise-4.17

#81278 RHDEVDOCS 6160 fix examples in Git SCM resolver
  modules/op-resolver-git-scm.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, pipelines

#80623 OCPBUGS-35851_4.13#adding missing port details
  modules/installation-about-custom-azure-vnet.adoc
Labels: size/M

#80624 OCPBUGS-35851_4.14#adding missing port details
  modules/installation-about-custom-azure-vnet.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#80601 OCPBUGS-35851_4.15#adding missing port details
  modules/installation-about-custom-azure-vnet.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#80600 OCPBUGS-35851_4.16#adding missing port details
  modules/installation-about-custom-azure-vnet.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#81446 [enterprise-4.12] OSDOCS#11823: Resolved merge conflict for cherry-picking to enterprise-4.12
  modules/restore-replace-stopped-etcd-member.adoc
Labels: size/XS

#81346 MCO114: tlsSecurityProfile parameter for MCO & MCS
  modules/tls-profiles-kubernetes-configuring.adoc
  security/tls-security-profiles.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17

#81438 [OSDOCS-11001]: Moving HCP troubleshooting docs to OCP
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-must-gather-dc.adoc
  modules/hcp-ts-hc-stuck.adoc
  modules/hcp-ts-ingress-not-online.adoc
  modules/hcp-ts-load-balancer-svcs.adoc
  modules/hcp-ts-no-nodes-reg.adoc
  modules/hcp-ts-nodes-stuck.adoc
  modules/hcp-ts-non-bm.adoc
  modules/hcp-ts-pvcs-not-avail.adoc
  modules/hcp-ts-rhcos.adoc
  modules/hcp-ts-vm-nodes.adoc
  modules/hosted-control-planes-pause-reconciliation.adoc
  modules/hosted-control-planes-troubleshooting.adoc
  modules/hosted-restart-hcp-components.adoc
  modules/scale-down-data-plane.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17

#81453 Fixing errors in HCP troubleshooting file
  modules/hcp-ts-hc-stuck.adoc
  modules/hosted-control-planes-troubleshooting.adoc
Labels: size/XS

#81457 [OSDOCS-11001]: Moving HCP troubleshooting updates to 4.17
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-must-gather-dc.adoc
  modules/hcp-ts-hc-stuck.adoc
  modules/hcp-ts-ingress-not-online.adoc
  modules/hcp-ts-load-balancer-svcs.adoc
  modules/hcp-ts-no-nodes-reg.adoc
  modules/hcp-ts-nodes-stuck.adoc
  modules/hcp-ts-non-bm.adoc
  modules/hcp-ts-pvcs-not-avail.adoc
  modules/hcp-ts-rhcos.adoc
  modules/hcp-ts-vm-nodes.adoc
  modules/hosted-control-planes-pause-reconciliation.adoc
  modules/hosted-control-planes-troubleshooting.adoc
  modules/hosted-restart-hcp-components.adoc
  modules/scale-down-data-plane.adoc
Labels: size/L, branch/enterprise-4.17

#81455 RHDEVDOCS 5889: Update override for resolver
  create/remote-pipelines-tasks-resolvers.adoc
  modules/op-resolver-git-anon.adoc
  modules/op-resolver-git-config-scm.adoc
  modules/op-resolver-git-override-scm.adoc
  modules/op-resolver-git-scm.adoc
Labels: size/L

#81359 WMCO new past release notes assembly and other changes
  _topic_maps/_topic_map.yml
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/windows-containers-support.adoc
  windows_containers/wmco_rn/_attributes
  windows_containers/wmco_rn/images
  windows_containers/wmco_rn/modules
  windows_containers/wmco_rn/snippets
  windows_containers/wmco_rn/windows-containers-release-notes-8-x-past.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-8-x.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.13

#79396 OSDOCS-11382: Renaming the user in ANP
  networking/network_security/network_policy/about-network-policy.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80754 TELCODOCS#1877: Enabling the SR-IOV network metrics exporter
  modules/nw-sriov-configuring-operator.adoc
  modules/sriov-network-metrics-exporter.adoc
  modules/sriov-operator-metrics.adoc
  networking/hardware_networks/configuring-sriov-operator.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.17

#81147 RHDEVDOCS-6148: Content creation for init and sidecar containers
  argocd_instance/setting-up-argocd-instance.adoc
  modules/gitops-argo-cd-notification.adoc
  modules/gitops-repo-server-properties.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#78981 TELCODOCS#1889: Size info for LVMS
  modules/lvms-about-lvmcluster-cr.adoc
  modules/lvms-limitations-to-configure-size-of-devices.adoc
  snippets/lvms-creating-lvmcluster.adoc
  storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81256 OSDOCS-11206: Update the 4.17 About this release RN Doc section
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference

#81385 OSDOCS-10767: Re-work first half of the "Getting Started with ROSA" Tutorials to be HCP specific
  _topic_maps/_topic_map_rosa_hcp.yml
  rosa_learning/creating_cluster_workshop/cloud-experts-getting-started-accessing.adoc
  rosa_learning/creating_cluster_workshop/cloud-experts-getting-started-admin-rights.adoc
  rosa_learning/creating_cluster_workshop/cloud-experts-getting-started-admin.adoc
  rosa_learning/creating_cluster_workshop/cloud-experts-getting-started-idp.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#80609 HCIDOCS-376: Fix indents in networkConfig stanza, install-config.yml (IPI)
  modules/ipi-install-configuring-host-network-interfaces-for-subnets.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80604 HCIDOCS-376: Fix indents in networkConfig stanza, install-config.yml (IPI)
  modules/ipi-install-configuring-host-dual-network-interfaces-in-the-install-config.yaml-file.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#80974 ROX:24323: update architecture graphic
  architecture/acs-architecture.adoc
  images/acs-architecture-scannerv4.png
  modules/acs-architecture-differences-ocp-kube.adoc
  modules/acs-architecture-interaction-between-services.adoc
  modules/acs-architecture-overview.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: peer-review-done, size/M, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6

#80721 OSDOCS-11734: GCP Workload ID OLM stub and related updates
  _attributes/common-attributes.adoc
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
  modules/cco-short-term-creds-aws-olm.adoc
  modules/cco-short-term-creds-azure-olm.adoc
  modules/cco-short-term-creds-gcp-olm.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.17

#81515 [rhacs-docs-4.4] update architecture graphic
  architecture/acs-architecture.adoc
  images/acs-architecture-scannerv4.png
  modules/acs-architecture-differences-ocp-kube.adoc
  modules/acs-architecture-interaction-between-services.adoc
  modules/acs-architecture-overview.adoc
  modules/secured-cluster-configuration-options-operator.adoc
  modules/secured-cluster-services-config.adoc
Labels: size/M

#81074 OSDOCS#11000: Migrating and modularizing HCP requirements from RHACM to OCP
  hosted_control_planes/hcp-prepare/hcp-requirements.adoc
  modules/hcp-requirements-platform-version.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17

#80788 RHDEVDOCS-6127: Content creation for Persistent volumes for Repo server storage
  argocd_instance/setting-up-argocd-instance.adoc
  modules/gitops-repo-server-properties.adoc
Labels: peer-review-done, size/S, merge-review-needed, jira/valid-reference, gitops

#81478 OCPBUGS-39421: Correct IBU policy name for consistency
  modules/ztp-image-based-upgrade-prep-oadp.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, jira/valid-reference

#81485 OCPBUGS-39229: Add reference IBU from ztp-site-generate
  modules/ztp-image-based-upgrade-prep.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#81472 TELCODOCS-1879 - Adding release note for PTP leap-seconds feature
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17

#80041 OSDOCS-11417#Reworking ASH topic map/TOC, creating IPI and UPI directories, updating 'Preparing to install a cluster' assembly
  _topic_maps/_topic_map.yml
  installing/installing_azure_stack_hub/installing-azure-stack-hub-account.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-default.adoc
  installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc
  installing/installing_azure_stack_hub/ipi/_attributes
  installing/installing_azure_stack_hub/ipi/images
  installing/installing_azure_stack_hub/ipi/installing-azure-stack-hub-default.adoc
  installing/installing_azure_stack_hub/ipi/installing-azure-stack-hub-network-customizations.adoc
  installing/installing_azure_stack_hub/ipi/ipi-ash-preparing-to-install.adoc
  installing/installing_azure_stack_hub/ipi/modules
  installing/installing_azure_stack_hub/ipi/snippets
  installing/installing_azure_stack_hub/manually-creating-iam-azure-stack-hub.adoc
  installing/installing_azure_stack_hub/preparing-to-install-on-azure-stack-hub.adoc
  installing/installing_azure_stack_hub/upi/_attributes
  installing/installing_azure_stack_hub/upi/images
  installing/installing_azure_stack_hub/upi/installing-azure-stack-hub-user-infra.adoc
  installing/installing_azure_stack_hub/upi/modules
  installing/installing_azure_stack_hub/upi/snippets
  installing/installing_azure_stack_hub/upi/upi-ash-preparing-to-install.adoc
  installing/overview/installing-preparing.adoc
  machine_management/user_infra/adding-compute-user-infra-general.adoc
  modules/cli-installing-cli.adoc
  modules/cluster-entitlements.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-obtaining-installer.adoc
  modules/ssh-agent-using.adoc
  updating/preparing_for_updates/preparing-manual-creds-update.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, branch/enterprise-4.17

#81548 CNV-47109: Updated HCO version for 4.14.8
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.14

#75236 MIG-1549: Attribute Updates for MTC 1.8.4
  _attributes/common-attributes.adoc
Labels: peer-review-done, lgtm, size/XS, MTC, jira/valid-reference

#81232 OCPBUGS-38757 Safe and Unsafe Sysctls in OpenShift 4.14+ Documentatio…
  modules/nodes-safe-sysctls-list.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14, branch/enterprise-4.15

#81556 Fixes a formatting error for OMR
  modules/mirror-registry-localhost-update.adoc
  modules/mirror-registry-remote-host-update.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81267 OSDOCS-11869 instance type heading fix
  modules/rosa-sdpolicy-am-aws-compute-types.adoc
  modules/rosa-sdpolicy-instance-types.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-hcp-instance-types.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-instance-types.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-service-definition.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.16, branch/enterprise-4.17

#81563 restructuring API docs
  _topic_maps/_topic_map.yml
  getting_started/openshift-overview.adoc
  rest_api/index.adoc
  rest_api/overview/_attributes
  rest_api/overview/editing-kubelet-log-level-verbosity.adoc
  rest_api/overview/images
  rest_api/overview/index.adoc
  rest_api/overview/modules
  rest_api/overview/snippets
  rest_api/overview/understanding-api-support-tiers.adoc
  rest_api/overview/understanding-compatibility-guidelines.adoc
  rosa_architecture/index.adoc
  welcome/index.adoc
Labels: size/XXL

#81585 [enterprise-4.16] Reverts for OSDOCS-11534 stories
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/creating-a-machine-pool-cli.adoc
  modules/creating-a-machine-pool-ocm.adoc
  modules/dedicated-aws-vpc-verifying-troubleshooting.adoc
  modules/dedicated-aws-vpn-verifying.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/nodes-cluster-resource-configure-about.adoc
  modules/nodes-cluster-resource-configure-jdk.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/ocm-disabling-autoscaling-nodes.adoc
  modules/ocm-enabling-autoscaling-nodes.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-adding-taints.adoc
  modules/rosa-adding-tuning.adoc
  modules/rosa-disabling-autoscaling-nodes.adoc
  modules/rosa-enabling-autoscaling-nodes.adoc
  modules/rosa-hcp-upgrading-cli-control-plane.adoc
  modules/rosa-hcp-upgrading-cli-machinepool.adoc
  modules/rosa-hcp-upgrading-cli-tutorial.adoc
  modules/rosa-node-drain-grace-period.adoc
  modules/rosa-scaling-worker-nodes.adoc
  nodes/clusters/nodes-cluster-resource-configure.adoc
  rosa_cluster_admin/cloud_infrastructure_access/rosa-configuring-private-connections.adoc
  rosa_cluster_admin/rosa-cluster-notifications.adoc
  rosa_cluster_admin/rosa-configuring-pid-limits.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
  security/audit-log-view.adoc
Labels: lgtm, size/XL, SD-docs, branch/enterprise-4.16

#80745 Updated the docs to include annotaion info in the steps
  modules/amazon-s3-configuring-acs.adoc
  modules/cloud-management-platforms-ocm.adoc
  modules/cloud-management-platforms-paladin-cloud.adoc
  modules/configure-custom-priorities-in-jira.adoc
  modules/create-issues-in-different-jira-projects.adoc
  modules/google-cloud-scc-configuring-acs.adoc
  modules/google-cloud-storage-configuring-acs.adoc
  modules/jira-configuring-acs.adoc
  modules/pagerduty-configuring-acs.adoc
  modules/s3-api-compatible-services-configuring-acs.adoc
  modules/slack-configuring-acs.adoc
  modules/splunk-configuring-acs.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6

#81486 TELCODOCS-1862 - Adding release note for PTP events REST API v2
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-needed, peer-review-done, size/S, branch/enterprise-4.17

#81487 Adds a few KCS links to migration and SDN dep docs
  modules/nw-ovn-kubernetes-live-migration-about.adoc
  modules/nw-ovn-kubernetes-migration-about.adoc
  snippets/sdn-deprecation-statement.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16

#81462 Additional S3 endpoints for use with OADP
  modules/oadp-about-backup-snapshot-locations-secrets.adoc
  modules/oadp-s3-compatible-backup-storage-providers.adoc
Labels: peer-review-done, lgtm, size/XS, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81577 HCIDOCS-376: Cherry pick.
  modules/ipi-install-configuring-host-network-interfaces-for-subnets.adoc
Labels: size/S, jira/valid-reference

#81578 HCIDOCS-376: Cherry pick.
  modules/ipi-install-configuring-host-network-interfaces-for-subnets.adoc
Labels: size/S, jira/valid-reference

#81579 HCIDOCS-376: Cherry pick.
  modules/ipi-install-configuring-host-network-interfaces-for-subnets.adoc
Labels: size/S, jira/valid-reference

#81434 OSDOCS-11898: Documented the 4.15.31 zstream release notes
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#81433 OSDOCS-11678: adds 4.15.31 relnote and other updates MicroShift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#81591 OCPBUGS#9181: Switch OSDK init to use my.domain to match files
  modules/osdk-hh-create-project.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81447 OSDOCS-11601: adds getting ready to install title MicroShift
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift_low_latency/microshift-low-latency.adoc
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_install/microshift-install-rpm.adoc
  microshift_install_get_ready/_attributes
  microshift_install_get_ready/images
  microshift_install_get_ready/microshift-fips.adoc
  microshift_install_get_ready/microshift-greenboot.adoc
  microshift_install_get_ready/microshift-install-get-ready.adoc
  microshift_install_get_ready/modules
  microshift_install_get_ready/snippets
  microshift_running_apps/microshift-embed-apps-offline-use.adoc
  microshift_running_apps/microshift-greenboot-workload-scripts.adoc
  microshift_troubleshooting/microshift-troubleshoot-updates.adoc
  microshift_updating/microshift-update-options.adoc
  modules/microshift-add-blueprint-build-iso.adoc
  modules/microshift-adding-app-rpms-to-blueprint.adoc
  modules/microshift-adding-containers-to-blueprint.adoc
  modules/microshift-adding-other-packages-to-blueprint.adoc
  modules/microshift-adding-repos-to-image-builder.adoc
  modules/microshift-adding-service-to-blueprint.adoc
  modules/microshift-building-apps-rpms.adoc
  modules/microshift-ca-adding-bundle-ostree.adoc
  modules/microshift-embed-images-offline-use.adoc
  modules/microshift-embed-microshift-build-image.adoc
  modules/microshift-embed-microshift-image-offline-deploy.adoc
  modules/microshift-fips-rpm-system.adoc
  modules/microshift-greenboot-check-update.adoc
  modules/microshift-greenboot-dir-structure.adoc
  modules/microshift-greenboot-health-check-log.adoc
  modules/microshift-greenboot-microshift-health-script.adoc
  modules/microshift-greenboot-prerollback-log.adoc
  modules/microshift-greenboot-systemd-journal-data.adoc
  modules/microshift-greenboot-updates-workloads.adoc
  modules/microshift-greenboot-workloads-validation.adoc
  modules/microshift-install-system-requirements.adoc
  modules/microshift-ops-config-embed-ostree.adoc
  modules/microshift-preparing-for-image-building.adoc
  modules/microshift-preparing-to-make-app-rpms.adoc
  modules/microshift-updating-rpms-ostree.adoc
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, branch/enterprise-4.17

#81501 HCIDOCS-316: Add information about Metal3 database to bare-metal IPI troubleshooting
  installing/installing_bare_metal_ipi/ipi-install-post-installation-configuration.adoc
  modules/bmo-troubleshooting-latency-when-deleting-a-baremetalhost-resource.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#81522 HCIDOCS-413: IPI install no longer requires disk reformat
  _topic_maps/_topic_map.yml
  installing/installing_bare_metal_ipi/ipi-install-installing-a-cluster.adoc
  installing/installing_bare_metal_ipi/ipi-install-troubleshooting.adoc
  modules/ipi-install-troubleshooting-cleaning-up-previous-installations.adoc
  modules/ipi-preparing-reinstall-cluster-bare-metal.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81589 RHDEVDOCS 6161 fix wording for HTTP resolver
  modules/op-resolver-http-config.adoc
  modules/op-resolver-http.adoc
Labels: peer-review-done, size/S, pipelines

#81516 OSDOCS-11899: 4.14.36 RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed, jira/valid-reference

#81423 OSDOCS-11681: adds 4.16.11 async relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#81451 OSDOCS-11918: creates rpm ostree install title MicroShift
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift_low_latency/microshift-low-latency.adoc
  microshift_install_rpm_ostree/_attributes
  microshift_install_rpm_ostree/images
  microshift_install_rpm_ostree/microshift-deploy-with-mirror-registry.adoc
  microshift_install_rpm_ostree/microshift-embed-in-rpm-ostree-offline-use.adoc
  microshift_install_rpm_ostree/microshift-embed-in-rpm-ostree.adoc
  microshift_install_rpm_ostree/modules
  microshift_install_rpm_ostree/snippets
  microshift_running_apps/microshift-embed-apps-offline-use.adoc
  microshift_running_apps/microshift-embedded-apps-on-rhel-edge.adoc
  microshift_running_apps/microshift-embedding-apps-tutorial.adoc
  microshift_running_apps/microshift_operators/microshift-operators-oc-mirror-disconnected.adoc
  microshift_running_apps/microshift_operators/microshift-operators-oc-mirror.adoc
  microshift_running_apps/microshift_operators/microshift-operators-olm.adoc
  modules/microshift-accessing-cluster-locally.adoc
  modules/microshift-accessing-cluster-open-firewall.adoc
  modules/microshift-accessing-cluster-remotely.adoc
  modules/microshift-accessing.adoc
  modules/microshift-add-blueprint-build-iso.adoc
  modules/microshift-adding-other-packages-to-blueprint.adoc
  modules/microshift-adding-repos-to-image-builder.adoc
  modules/microshift-adding-service-to-blueprint.adoc
  modules/microshift-ca-adding-bundle-ostree.adoc
  modules/microshift-ca-adding-bundle.adoc
  modules/microshift-embed-microshift-image-offline-deploy.adoc
  modules/microshift-oc-mirror-creating-imageset-config.adoc
  modules/microshift-preparing-for-image-building.adoc
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, branch/enterprise-4.17

#81582 OSDOCS-11956: Multi-line Code Copy/Paste Incorrect
  cloud_experts_tutorials/cloud-experts-aws-secret-manager.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#81510 OSDOCS-11900 OCP Release Notes 4.16.11
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M

#81588 RHDEVDOCS 6161 remove the word remote from cluster resolver docs
  create/remote-pipelines-tasks-resolvers.adoc
  modules/op-resolver-cluster.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, pipelines

#81657 [rhacs-docs-4.4] Manual cherrypick: Updated the docs to include annotaion info in the steps
  modules/amazon-s3-configuring-acs.adoc
  modules/cloud-management-platforms-ocm.adoc
  modules/cloud-management-platforms-paladin-cloud.adoc
  modules/configure-custom-priorities-in-jira.adoc
  modules/create-issues-in-different-jira-projects.adoc
  modules/google-cloud-scc-configuring-acs.adoc
  modules/google-cloud-storage-configuring-acs.adoc
  modules/jira-configuring-acs.adoc
  modules/pagerduty-configuring-acs.adoc
  modules/slack-configuring-acs.adoc
  modules/splunk-configuring-acs.adoc
Labels: size/M

#81658 [rhacs-docs-4.4] Manual cherrypick: Updated the docs to include annotaion info in the steps
  modules/amazon-s3-configuring-acs.adoc
  modules/cloud-management-platforms-ocm.adoc
  modules/cloud-management-platforms-paladin-cloud.adoc
  modules/configure-custom-priorities-in-jira.adoc
  modules/create-issues-in-different-jira-projects.adoc
  modules/google-cloud-scc-configuring-acs.adoc
  modules/google-cloud-storage-configuring-acs.adoc
  modules/jira-configuring-acs.adoc
  modules/pagerduty-configuring-acs.adoc
  modules/slack-configuring-acs.adoc
  modules/splunk-configuring-acs.adoc
Labels: size/M

#79537 OSDOCS#11414: IPI improvements - Part 2
  installing/installing_azure/ipi/installing-azure-government-region.adoc
  installing/installing_azure/ipi/installing-azure-network-customizations.adoc
  installing/installing_azure/ipi/installing-azure-private.adoc
  installing/installing_azure/ipi/installing-azure-vnet.adoc
  installing/installing_azure/ipi/installing-restricted-networks-azure-installer-provisioned.adoc
  modules/installation-azure-confidential-vms.adoc
  modules/installation-azure-trusted-launch.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17

#81573 OSDOCS-11643: updates relnotes text MicroShift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#81200 Indentation correction
  security/certificate_types_descriptions/proxy-certificates.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81283 [SRVCOM-3270] Fix links in Dev metrics overview
  observability/developer-metrics/serverless-developer-metrics.adoc
Labels: peer-review-done, size/XS, serverless

#81611 OCPBUGS-31380: Add prerequisite to IBU rollback to check for expired certs
  edge_computing/image_based_upgrade/cnf-image-based-upgrade-base.adoc
  edge_computing/image_based_upgrade/ztp-image-based-upgrade.adoc
  modules/cnf-image-based-upgrade-rollback.adoc
  modules/ztp-image-based-upgrade-rollback.adoc
Labels: peer-review-done, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17

#81483 OBSDOCS-1280: Logging 5.6.23 Release Notes
  modules/logging-release-notes-5-6-23.adoc
  observability/logging/logging_release_notes/logging-5-6-release-notes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13

#81482 OBSDOCS-1281: Logging 5.8.12 release notes
  modules/logging-release-notes-5-8-12.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14

#81473 OBSDOCS-1284: Logging 5.9.6 Release Notes
  modules/logging-release-notes-5-9-6.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#78536 [OSDOCS#11152]: Update to prereqs for configuring email notifications
  modules/managed-cluster-add-notification-contacts.adoc
  modules/managed-cluster-remove-notification-contacts.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81212 OBSDOCS-957: Add Technology Preview docs for Loki Exporter to RH Collector
  _topic_maps/_topic_map.yml
  modules/otel-forwarding-logs-to-tempostack.adoc
  modules/otel-forwarding-traces.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/otel/otel-forwarding-telemetry-data.adoc
  observability/otel/otel-rn.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81528 OSDOCS-11774: Move IBM Z post-install
  _topic_maps/_topic_map.yml
  installing/installing_ibm_z/ibmz-post-install.adoc
  modules/ibmz-configure-devices-manually.adoc
  modules/ibmz-configure-devices-mco.adoc
  modules/ibmz-enable-multipathing-fcp-luns.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#81171 CNV#40181: Doc VMExport API now v1beta1
  modules/virt-accessing-exported-vm-manifests.adoc
  modules/virt-creating-virtualmachineexport.adoc
Labels: peer-review-done, lgtm, size/S, CNV, merge-review-in-progress, branch/enterprise-4.17

#81183 CNV#40182: Release note: VM Export API now beta
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, branch/enterprise-4.17

#80859 OCPBUGS-31071: Changing catalog source name in disconnected workflow
  modules/cnf-topology-aware-lifecycle-manager-operator-troubleshooting.adoc
  modules/cnf-topology-aware-lifecycle-manager-operator-update.adoc
  snippets/pg-cnf-topology-aware-lifecycle-manager-operator-troubleshooting.adoc
  snippets/pg-cnf-topology-aware-lifecycle-manager-operator-update.adoc
  snippets/pgt-cnf-topology-aware-lifecycle-manager-operator-troubleshooting.adoc
  snippets/pgt-cnf-topology-aware-lifecycle-manager-operator-update.adoc
Labels: peer-review-done, size/M, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#81406 TELCODOCS-1868: Remove TP notes
  modules/agent-install-sample-config-bond-sriov.adoc
  modules/installation-user-infra-machines-static-network.adoc
  modules/ipi-install-configuring-host-dual-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/nw-sriov-dual-nic-con.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.17

#81584 [enterprise-4.17] Reverts for OSDOCS-11534 stories
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/creating-a-machine-pool-cli.adoc
  modules/creating-a-machine-pool-ocm.adoc
  modules/dedicated-aws-vpc-verifying-troubleshooting.adoc
  modules/dedicated-aws-vpn-verifying.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/nodes-cluster-resource-configure-about.adoc
  modules/nodes-cluster-resource-configure-jdk.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/ocm-disabling-autoscaling-nodes.adoc
  modules/ocm-enabling-autoscaling-nodes.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-adding-taints.adoc
  modules/rosa-adding-tuning.adoc
  modules/rosa-disabling-autoscaling-nodes.adoc
  modules/rosa-enabling-autoscaling-nodes.adoc
  modules/rosa-hcp-upgrading-cli-control-plane.adoc
  modules/rosa-hcp-upgrading-cli-machinepool.adoc
  modules/rosa-hcp-upgrading-cli-tutorial.adoc
  modules/rosa-node-drain-grace-period.adoc
  modules/rosa-scaling-worker-nodes.adoc
  nodes/clusters/nodes-cluster-resource-configure.adoc
  rosa_cluster_admin/cloud_infrastructure_access/rosa-configuring-private-connections.adoc
  rosa_cluster_admin/rosa-cluster-notifications.adoc
  rosa_cluster_admin/rosa-configuring-pid-limits.adoc
  rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
  security/audit-log-view.adoc
Labels: size/XL, branch/enterprise-4.17
