Repository openshift/openshift-docs, pull requests merged in 2024-11, with the labels that each got.

#84148 OSDOCS-12158: adds 4.15.37 relnotes Microshift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#83474 OCPBUGS-43331: update release note for 4.15.18
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#84354 Fix attr precedence error
  scalability_and_performance/telco_ref_design_specs/core/telco-core-rds-overview.adoc
  scalability_and_performance/telco_ref_design_specs/core/telco-core-rds-use-cases.adoc
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-crs.adoc
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-design-components.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-du-overview.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-design-spec.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-components.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-crs.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-software-artifacts.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83560 OSSM 3.0 TP1 OSSM-8153 [DOC] OSSM 3.x Concepts
  _topic_maps/_topic_map.yml
  about/ossm-about-concepts-assembly.adoc
  modules/ossm-about-concepts-argo-rollouts.adoc
  modules/ossm-about-concepts-cert-manager.adoc
  modules/ossm-about-concepts-kiali.adoc
  modules/ossm-about-concepts-observability.adoc
  modules/ossm-about-concepts-resources.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress

#84344 OSSM-8331 Remove attributes from docinfo.xml files
  about/docinfo.xml
  install/docinfo.xml
  update/docinfo.xml
Labels: peer-review-done, size/XS, merge-review-needed

#84359 OSDOCS-6582: enterprise-4.13 cherrypick of PR 82199
  _topic_maps/_topic_map.yml
  modules/admin-limit-operations.adoc
  modules/admin-quota-limits.adoc
  modules/admin-quota-overview.adoc
  modules/admin-quota-usage.adoc
  scalability_and_performance/compute-resource-quotas.adoc
Labels: size/XXL, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84353 OSDOCS-6582: enterprise-4.12 cherrypick of PR 82199
  _topic_maps/_topic_map.yml
  modules/admin-limit-operations.adoc
  modules/admin-quota-limits.adoc
  modules/admin-quota-overview.adoc
  modules/admin-quota-usage.adoc
  scalability_and_performance/compute-resource-quotas.adoc
Labels: size/XXL, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84309 OSDOCS#11934: Multiarch Tuning Operator release date update
  post_installation_configuration/configuring-multi-arch-compute-machines/multi-arch-tuning-operator-release-notes.adoc
Labels: size/XS, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84364 OSDOCS-1117: enterprise-4.13 manual cherrypick of PR 80080
  _topic_maps/_topic_map.yml
  scalability_and_performance/index.adoc
Labels: size/M, jira/valid-reference

#83372 OSDOCS-11695 Adding Nutanix Flow Virtual Networking RN
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, px-approved, branch/enterprise-4.17

#83373 OSDOCS-11695 adding Nutanix FVN to docs
  modules/installation-nutanix-installer-infra-reqs.adoc
Labels: peer-review-done, lgtm, size/XS, px-approved, branch/enterprise-4.17, branch/enterprise-4.18

#84036 [RHACS][Docs][4.6 and later versions]ROX-26681: NVD CVSS documentation
  modules/identify-vulnerabilities-in-nodes-vm20.adoc
  modules/vulnerability-management20-creating-report.adoc
  modules/vulnerability-management20-view-cve.adoc
Labels: peer-review-done, lgtm, size/M, RHACS, jira/valid-reference

#84399 Adding new script for bccutil portal scratch build
  scripts/get-updated-portal-books.sh
Labels: size/M

#84023 OBSDOCS-1440: Separate UWM and core platform monitoring (part 4)
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84291 OSDOCS#44051: Removing the reference to a certificate file
  modules/identity-provider-secret.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84192 Adds OMR release notes 2.0.2
  modules/mirror-registry-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#84397 OSDOCS 12369: Updated cert-manager release note for 1.14.1 version
  security/cert_manager_operator/cert-manager-operator-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.17

#84363 OSDOCS-1117: enterprise-4.12 manual cherrypick of PR 80080
  _topic_maps/_topic_map.yml
  scalability_and_performance/index.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84372 OCPBUGS-44122: xref link not working in docs.redhat.com
  scalability_and_performance/index.adoc
Labels: peer-review-done, size/XS, jira/severity-important, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84362 Add OpenShift 4.17.3 APIs
  _topic_maps/_topic_map.yml
  api-config.yaml
  rest_api/image_apis/imagestreamimport-image-openshift-io-v1.adoc
  rest_api/monitoring_apis/podmonitor-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/probe-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/prometheus-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.adoc
  rest_api/network_apis/multinetworkpolicy-k8s-cni-cncf-io-v1beta1.adoc
  rest_api/network_apis/network-apis-index.adoc
  rest_api/objects/index.adoc
  rest_api/operator_apis/clustercsidriver-operator-openshift-io-v1.adoc
  rest_api/operator_apis/ingresscontroller-operator-openshift-io-v1.adoc
  rest_api/operator_apis/network-operator-openshift-io-v1.adoc
  rest_api/overview/index.adoc
  rest_api/template_apis/templateinstance-template-openshift-io-v1.adoc
  rest_api/workloads_apis/build-build-openshift-io-v1.adoc
  rest_api/workloads_apis/buildconfig-build-openshift-io-v1.adoc
  rest_api/workloads_apis/pod-v1.adoc
Labels: size/XXL, branch/enterprise-4.17, branch/enterprise-4.18

#84415 Delete repeated sentence in module
  modules/secured-cluster-configuration-options-operator.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.5, rhacs-docs-4.6

#84230 ExternalDNS Operator update to release notes OSDOCS-12457
  networking/external_dns_operator/external-dns-operator-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, merge-review-in-progress, merge-review-needed, branch/enterprise-4.17, branch/enterprise-4.18

#84260 [enterprise-4.14] OCPBUGS-43376: add known issue
  modules/update-best-practices.adoc
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, jira/severity-critical, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#84194 OSDOCS#12398: IDPs need workers for DNS resolution
  modules/hcp-configuring-oauth-console.adoc
  modules/hcp-configuring-oauth.adoc
Labels: peer-review-done, size/XS, ok-to-merge, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84439 OSDOCS-40768: Clarifying CSI driver type - take 2
  modules/virt-configuring-disk-sharing-lun.adoc
  modules/virt-enabling-persistentreservation-feature-gate.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84241 OCPBUGS-43885:Updating NetObserv w/o Loki table for multi-tenancy
  modules/network-observability-without-loki.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84446 OCPBUGS-44122: xref link not working docs.redhat.com 4.14 version
  scalability_and_performance/index.adoc
Labels: size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference

#84450 OCPBUGS-44122: xref link not working docs.redhat.com 4.15 version
  scalability_and_performance/index.adoc
Labels: size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference

#84255 OSSM-8318 Explanation of Kiali CR in TP1 doc
  modules/ossm-config-otel-kiali.adoc
  modules/ossm-config-otel.adoc
Labels: peer-review-done, size/M, service-mesh

#84448 CNV#50724: TP notice fix for descheduler
  virt/virtual_machines/advanced_vm_management/virt-enabling-descheduler-evictions.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#83327 OADP-3472 Added warning for windows vm backup fail
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-kubevirt.adoc
  snippets/oadp-windows-vm-backup-fails.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84395 [gitops-docs-1.13] RHDEVDOCS-6203: Content creation for GitOps 1.12.6 RN
  modules/gitops-release-notes-1-12-6.adoc
  release_notes/gitops-release-notes.adoc
Labels: size/M, jira/valid-reference

#83246 OSDOCS-12183: adding how to delete manifests
  _topic_maps/_topic_map_ms.yml
  microshift_running_apps/microshift-deleting-resource-manifests.adoc
  modules/microshift-manifests-deletion-overview.adoc
  modules/microshift-manifests-removal-scenario-ostree.adoc
  modules/microshift-manifests-removal-scenario-rpm.adoc
  modules/microshift-manifests-upgrade-scenario-ostree.adoc
  modules/microshift-manifests-upgrade-scenario-rpm.adoc
Labels: peer-review-done, size/L, qe-approved, jira/valid-reference, branch/enterprise-4.18

#84460 [enterprise-4.15] OSDOCS-40768: Clarifying CSI driver type - take 2 - 4.15
  modules/virt-configuring-disk-sharing-lun.adoc
  modules/virt-enabling-persistentreservation-feature-gate.adoc
Labels: size/XS

#84461 [enterprise-4.16] OSDOCS-40768: Clarifying CSI driver type - take 2 - 4.16
  modules/virt-configuring-disk-sharing-lun.adoc
  modules/virt-enabling-persistentreservation-feature-gate.adoc
Labels: size/XS

#80962 OSDOCS-11802 Information added to 4.14.z Known Issue
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-needed, branch/enterprise-4.14

#84452 removes remaining SDN entries from 4.18+
  modules/nw-egress-router-about.adoc
  modules/nw-networkpolicy-allow-application-all-namespaces.adoc
  modules/nw-networkpolicy-allow-application-particular-namespace.adoc
  modules/nw-networkpolicy-allow-external-clients.adoc
  modules/nw-networkpolicy-create-cli.adoc
  modules/nw-networkpolicy-delete-cli.adoc
  modules/nw-networkpolicy-deny-all-allowed.adoc
  modules/nw-networkpolicy-edit.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
  modules/nw-networkpolicy-project-defaults.adoc
  modules/nw-osp-loadbalancer-etp-local.adoc
  modules/nw-throughput-troubleshoot.adoc
  modules/rosa-nodes-machine-pools-local-zones.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/network_security/network_policy/about-network-policy.adoc
  networking/network_security/network_policy/multitenant-network-policy.adoc
  observability/logging/cluster-logging-deploying.adoc
  virt/about_virt/about-virt.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#81649 OSDOCS-11352: update examples with dnf
  machine_configuration/mco-coreos-layering.adoc
  modules/coreos-layering-configuring-on.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#82722 OADP-4941: Removing OADP 1.2 references from docs
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/oadp-advanced-topics.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-operator-supported.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#81026 Add 'Additional release notes' page
  _topic_maps/_topic_map.yml
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  release_notes/addtl-release-notes.adoc
  release_notes/ocp-release-notes.adoc
  rosa_architecture/index.adoc
Labels: size/L

#84058 ROX-26396: Add compliance certification for cloud
  cloud_service/rhacs-cloud-service-service-description.adoc
  modules/cloud-svc-compliance.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.6

#83239 bugfix: ibm-power filename consistency
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-destroy/hcp-destroy-ibm-power.adoc
  hosted_control_planes/hcp-manage/hcp-manage-ibm-power.adoc
  modules/destroy-hc-ibm-power-cli.adoc
  modules/hcp-bm-hc.adoc
  modules/hcp-ibm-power-add-agents.adoc
  modules/hcp-ibm-power-dns.adoc
  modules/hcp-ibm-power-infra-reqs.adoc
  modules/hcp-ibm-power-infraenv.adoc
  modules/hcp-ibm-power-prereqs.adoc
  modules/hcp-ibm-power-scale-np.adoc
  modules/oadp-ibm-power-and-z-known-issues.adoc
  modules/storage-persistent-storage-pv.adoc
  storage/container_storage_interface/persistent-storage-csi-ibm-cloud-vpc-block.adoc
  storage/container_storage_interface/persistent-storage-csi-sc-manage.adoc
Labels: peer-review-done, size/M, ok-to-test, branch/enterprise-4.17, branch/enterprise-4.18

#84499 [enterprise-4.17] Add 'Additional release notes' page
  _topic_maps/_topic_map.yml
  release_notes/addtl-release-notes.adoc
Labels: size/L

#83385 bugfix: inconsistent install methods content cross-vendor
  installing/installing_ibm_cloud/preparing-to-install-on-ibm-cloud.adoc
  installing/installing_ibm_power/preparing-to-install-on-ibm-power.adoc
  installing/installing_ibm_powervs/preparing-to-install-on-ibm-power-vs.adoc
  installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc
Labels: peer-review-done, size/M, ok-to-test, branch/enterprise-4.17, branch/enterprise-4.18

#84464 OCPBUGS-44024 Clarify that bonding mode 6 is not supported 4.12+
  modules/virt-example-bond-nncp.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84462 OSDOCS-11980: Migrate Nodes to ROSA HCP
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/accessing-an-example-cluster-node-tuning-operator-specification.adoc
  modules/cluster-node-tuning-operator-default-profiles-set.adoc
  modules/custom-tuning-specification.adoc
  modules/node-tuning-operator-supported-tuned-daemon-plug-ins.adoc
  modules/node-tuning-operator.adoc
  modules/nodes-cluster-overcommit-configure-nodes.adoc
  modules/nodes-cluster-resource-levels-job.adoc
  modules/nodes-cma-autoscaling-custom-audit.adoc
  modules/nodes-cma-autoscaling-custom-gather.adoc
  modules/nodes-cma-autoscaling-custom-uninstalling.adoc
  modules/nodes-containers-volumes-subpath.adoc
  modules/nodes-nodes-jobs-about.adoc
  modules/nodes-nodes-jobs-creating-cron.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-pods-daemonsets-creating.adoc
  modules/nodes-pods-priority-configuring.adoc
  modules/nodes-pods-secrets-creating-basic.adoc
  modules/nodes-pods-secrets-creating-docker.adoc
  modules/nodes-pods-secrets-creating-opaque.adoc
  modules/nodes-pods-secrets-creating-sa.adoc
  modules/nodes-scheduler-node-affinity-configuring-preferred.adoc
  modules/nodes-scheduler-node-affinity-configuring-required.adoc
  modules/nodes-scheduler-node-selectors-about.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/rosa-creating-node-tuning.adoc
  modules/rosa-deleting-node-tuning.adoc
  modules/rosa-modifying-node-tuning.adoc
  nodes/clusters/nodes-cluster-overcommit.adoc
  nodes/cma/nodes-cma-autoscaling-custom-adding.adoc
  nodes/cma/nodes-cma-autoscaling-custom-debugging.adoc
  nodes/cma/nodes-cma-autoscaling-custom-install.adoc
  nodes/cma/nodes-cma-autoscaling-custom-removing.adoc
  nodes/cma/nodes-cma-autoscaling-custom-trigger-auth.adoc
  nodes/containers/nodes-containers-using.adoc
  nodes/index.adoc
  nodes/nodes/nodes-node-tuning-operator.adoc
  nodes/nodes/nodes-nodes-viewing.adoc
  nodes/nodes/nodes-nodes-working.adoc
  nodes/nodes/rosa-tuning-config.adoc
  nodes/pods/nodes-pods-configuring.adoc
  nodes/pods/nodes-pods-priority.adoc
  nodes/pods/nodes-pods-secrets.adoc
  nodes/pods/nodes-pods-using.adoc
  nodes/scheduling/nodes-scheduler-about.adoc
  nodes/scheduling/nodes-scheduler-node-affinity.adoc
  nodes/scheduling/nodes-scheduler-node-selectors.adoc
  nodes/scheduling/nodes-scheduler-pod-affinity.adoc
  nodes/scheduling/nodes-scheduler-pod-topology-spread-constraints.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, merge-review-needed, jira/valid-reference

#83941 OCPBUGS#43078: RE-added statement about pods and conversion to dual-s…
  modules/nw-dual-stack-convert.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83678 RHDEVDOCS-6202: Content creation for GitOps 1.13.2 RN
  modules/gitops-release-notes-1-13-1.adoc
  modules/gitops-release-notes-1-13-2.adoc
  release_notes/gitops-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, gitops

#84345 OSDOCS-12513: Documented the 4.16.20 z-stream release notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.16

#84279 OBSDOCS-1467: Separate UWM and core platform monitoring (part 5)
  modules/monitoring-configuring-pod-topology-spread-constraints.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-query-log-file-for-prometheus.adoc
  modules/monitoring-using-pod-topology-spread-constraints-for-monitoring.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, jira/valid-reference

#84501 Minor fix with missed manual CP
  modules/nw-egress-ips-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#83248 [OSDOCS-11101]: Updating multiarch docs for HCP
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  modules/hcp-aws-deploy-hc.adoc
  modules/hcp-create-hc-arm64-aws.adoc
  modules/hcp-enable-arm-amd.adoc
Labels: peer-review-done, size/M, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#83719 [OSDOCS-12035]: Adding tenancy docs to HCP on AWS
  modules/hcp-aws-deploy-hc.adoc
  modules/hcp-aws-hc-ext-dns.adoc
Labels: peer-review-done, size/M, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#84312 CNV#50448: workaround KCS link for storage LM
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.17

#84179 [OSDOCS-12142]: Adding backup/restore docs for HCP on OpenShift Virt
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp_high_availability/hcp-backup-restore-virt.adoc
  modules/backup-hosted-cluster-virt.adoc
  modules/restore-hosted-cluster-virt.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#84335 [OSDOCS-11350]: Adding more versioning details to HCP docs
  hosted_control_planes/index.adoc
  modules/hosted-control-planes-version-support.adoc
Labels: peer-review-done, size/M, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#83370 [OSDOCS-12120]: Move HCP on CNV docs from TP to GA
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  modules/hosted-control-planes-overview.adoc
Labels: peer-review-done, size/XS, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#84483 OSDOCS-12559: Add Known Issue
  osd_whats_new/osd-whats-new.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#84119 Removing TP statements for HCP on IBM Z and IBM Power
  modules/hosted-control-planes-overview.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#84500 Updating PR template to warn against topic map changes
  .github/pull_request_template.md
Labels: size/XS

#84416 OCPBUGS-42243#updating firewall list
  modules/configuring-firewall.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84479 OSDOCS-12552 Wrong SLA link in Service Definition
  modules/rosa-sdpolicy-am-support.adoc
Labels: peer-review-done, lgtm, size/XS

#84554 [enterprise-4.17] Applying HCP on IBM Power updates to 4.17
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  modules/hcp-ibm-power-prereqs.adoc
Labels: size/XS, branch/enterprise-4.17

#84046 Applying 4.17 updates to IBM Z content
  _topic_maps/_topic_map.yml
  hosted_control_planes/hcp-disconnected/disconnected-install-ibmz-hcp.adoc
  modules/destroy-hc-ibmz-cli.adoc
  modules/hcp-bm-autoscale.adoc
  modules/hcp-ibmz-adding-credentials-registry.adoc
  modules/hcp-ibmz-adding-reg-ca-hostedcluster.adoc
  modules/hcp-ibmz-lpar-agents.adoc
  modules/hcp-ibmz-update-reg-ca.adoc
  modules/hosted-control-planes-version-support.adoc
  modules/oc-mirror-image-set-config-examples.adoc
Labels: size/L, ok-to-merge, branch/enterprise-4.17

#84538 [enterprise-4.17] [OSDOCS-11350]: Adding more versioning details to HCP docs
  hosted_control_planes/index.adoc
  modules/hosted-control-planes-version-support.adoc
Labels: size/M

#83981 OCPBUGS-20134: additions for example completion
  installing/installing_bare_metal/upi/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/upi/installing-bare-metal.adoc
  installing/installing_bare_metal/upi/installing-restricted-networks-bare-metal.adoc
  modules/rhcos-enabling-multipath.adoc
  modules/rhcos-multipath-secondary-disk.adoc
Labels: peer-review-done, size/L, jira/severity-important, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84552 Fixed problematic ifeval
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84519 Addtl RN: Change to single list
  release_notes/addtl-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#84566 [enterprise-4.17] Addtl RN: Change to single list
  release_notes/addtl-release-notes.adoc
Labels: size/M

#84567 [enterprise-4.16] Fixed problematic ifeval
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S, branch/enterprise-4.16

#84568 [enterprise-4.17] Fixed problematic ifeval
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S, branch/enterprise-4.18

#84569 [enterprise-4.18] Fixed problematic ifeval
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S

#83853 OSDOCS#10737: Changed note for clarity reg IPI parameter
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84577 [enterprise-4.13] OSDOCS#10737: Changed note for clarity reg IPI parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#84578 [enterprise-4.17] OSDOCS#10737: Changed note for clarity reg IPI parameter
  modules/installation-configuration-parameters.adoc
Labels: size/XS

#83766 [RHACS][Docs][4.6 and later versions] ROX-25681: Adding Microsoft Sentinel integration documentation
  _topic_maps/_topic_map.yml
  integration/integrating-with-microsoft-sentinel-notifier.adoc
  modules/viewing-the-log-analytics-to-detect-threats.adoc
Labels: peer-review-done, lgtm, size/M, RHACS, jira/valid-reference

#83506 OSDOCS#12312: Limitations of managing imported hosted clusters
  hosted_control_planes/hcp-import.adoc
  modules/hcp-import-limitations.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84590 No#jira: Break paragraphs for readability
  modules/hcp-import-limitations.adoc
Labels: size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#84586 [enterprise-4.14] OSDOCS#12312: hcp import limitations
  hosted_control_planes/hcp-updating.adoc
  modules/hcp-import-limitations.adoc
Labels: size/S

#84589 [enterprise-4.16] OSDOCS#12312: hcp import limitations
  hosted_control_planes/hcp-updating.adoc
  modules/hcp-import-limitations.adoc
Labels: size/S

#84588 [enterprise-4.15] OSDOCS#12312: hcp import limitations
  hosted_control_planes/hcp-updating.adoc
  modules/hcp-import-limitations.adoc
Labels: size/S

#84526 4.15 - OADP-4941: Removing OADP 1.2 references from docs
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-operator-supported.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, OADP, jira/valid-reference

#84581 OBSDOCS-1481: Fix docs bug - wrong CR mentioned
  modules/otel-config-instrumentation.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84282 OBSDOCS-1464: Separate Modifying the retention time and size for Prom…
  modules/monitoring-modifying-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-retention-time-and-size-for-prometheus-metrics-data.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84521 OSDOCS-12183-1: changes in delete Kustomize manifest resources
  _topic_maps/_topic_map_ms.yml
  microshift_running_apps/microshift-applications.adoc
  microshift_running_apps/microshift-deleting-resource-manifests.adoc
  modules/microshift-manifests-deletion-overview.adoc
  modules/microshift-manifests-overview.adoc
  modules/microshift-manifests-removal-scenario-ostree.adoc
  modules/microshift-manifests-removal-scenario-rpm.adoc
  modules/microshift-manifests-upgrade-scenario-ostree.adoc
  modules/microshift-manifests-upgrade-scenario-rpm.adoc
Labels: peer-review-in-progress, peer-review-needed, size/M, jira/valid-reference, branch/enterprise-4.18

#84598 [enterprise-4.18] Add 'Additional release notes' page
  _topic_maps/_topic_map.yml
  release_notes/addtl-release-notes.adoc
Labels: size/L

#84609 Revert "OSDOCS-12183-1: changes in delete Kustomize manifest resources"
  _topic_maps/_topic_map_ms.yml
  microshift_running_apps/microshift-applications.adoc
  microshift_running_apps/microshift-deleting-resource-manifests.adoc
  modules/microshift-manifests-deletion-overview.adoc
  modules/microshift-manifests-overview.adoc
  modules/microshift-manifests-removal-scenario-ostree.adoc
  modules/microshift-manifests-removal-scenario-rpm.adoc
  modules/microshift-manifests-upgrade-scenario-ostree.adoc
  modules/microshift-manifests-upgrade-scenario-rpm.adoc
Labels: size/M, jira/valid-reference

#84624 Stub out the Addtl RN file on main
  release_notes/addtl-release-notes.adoc
Labels: peer-review-done, size/M

#84101 [OSDOCS-12093]: Adding HCP content to 4.17 Welcome
  welcome/learn_more_about_openshift.adoc
Labels: peer-review-done, size/M, ok-to-merge, branch/enterprise-4.17

#84572 [enterprise-4.17] Add IPsec known issue
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17

#84571 [enterprise-4.16] Add IPsec known issue
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.16

#84118 Update links to ACM in HCP docs
  architecture/mce-overview-ocp.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-bm.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  hosted_control_planes/hcp-troubleshooting.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
  modules/hcp-dc-image-mirror.adoc
  modules/hcp-dr-oadp-restore.adoc
  modules/hcp-non-bm-prepare.adoc
  modules/hcp-non-bm-prereqs.adoc
  modules/hcp-virt-reqs.adoc
  modules/hosted-control-planes-concepts-personas.adoc
  modules/hosted-control-planes-overview.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#84639 [enterprise-4.16] OADP-4597: Fix build-errors in Prow local validation
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S, jira/valid-reference

#84637 [enterprise-4.17] OADP-4597: Fix build-errors in Prow local validation
  modules/nw-traditional-sharding.adoc
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.17

#84643 [enterprise-4.18] OADP-4597: Fix build-errors in Prow local validation
  modules/nw-traditional-sharding.adoc
  modules/olm-overriding-operator-pod-affinity.adoc
Labels: size/S, jira/valid-reference

#84644 [enterprise-4.18] Update links to ACM in HCP docs
  architecture/mce-overview-ocp.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-bm.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  hosted_control_planes/hcp-troubleshooting.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
  modules/hcp-dc-image-mirror.adoc
  modules/hcp-dr-oadp-restore.adoc
  modules/hcp-non-bm-prepare.adoc
  modules/hcp-non-bm-prereqs.adoc
  modules/hcp-virt-reqs.adoc
  modules/hosted-control-planes-concepts-personas.adoc
  modules/hosted-control-planes-overview.adoc
Labels: size/M

#84611 [OSDOCS-12602]: Moving HCP updates content to note
  hosted_control_planes/hcp-updating.adoc
  modules/hcp-updating-requirements.adoc
Labels: peer-review-done, lgtm, size/XS

#84606 OSDOCS-12511: 4.12.68 RN
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference

#84645 [OSDOCS-12444]: Fixing links to ACM
  architecture/mce-overview-ocp.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
Labels: size/XS

#84638 [OSDOCS-12033]: Removing TP boilerplate and MCE version reference
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
Labels: size/XS

#84652 [enterprise-4.17] [OSDOCS-12033]: Removing TP boilerplate and MCE version reference
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
Labels: size/XS

#83599 OSDOCS#12121:HCP KubeVirt Nvidia GPU support
  hosted_control_planes/hcp-manage/hcp-manage-virt.adoc
  modules/hcp-virt-attach-nvidia-gpus-np-api.adoc
  modules/hcp-virt-attach-nvidia-gpus.adoc
Labels: peer-review-done, size/L, ok-to-merge, branch/enterprise-4.17, branch/enterprise-4.18

#83238 OSDOCS#12284: HCP: Update OADP backup, restore, and disaster recovery
  modules/hcp-dr-oadp-backup-cp-workload.adoc
  modules/hcp-dr-oadp-restore.adoc
Labels: peer-review-done, size/M, ok-to-merge, OADP, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#83594 OSDOCS#11133: Hosted control planes release notes
  _topic_maps/_topic_map.yml
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#84105 OSDOCS#11133: Add a link for async RN for HCP
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, px-approved, branch/enterprise-4.17

#84509 4.13 - OADP-4941: Removing OADP 1.2 references from docs
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/oadp-advanced-topics.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-operator-supported.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, OADP, jira/valid-reference

#84648 OADP-5191: Fix Attributes in Support for OpenShift API for Data Prote…
  backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.adoc
  modules/oadp-operator-supported.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, OADP, jira/valid-reference

#84398 [RHACS][Docs][4.6 and later versions] ROX-26683: Violations documentation updates
  modules/analyzing-all-violations.adoc
  modules/mark-violations-resolved.adoc
  modules/namespace-conditions-for-platform-components.adoc
  modules/network-policies-tab.adoc
  modules/violations-page-overview.adoc
  modules/violations-view.adoc
  operating/respond-to-violations.adoc
Labels: peer-review-done, lgtm, size/L, RHACS, jira/valid-reference

#84520 4.14 - OADP-4941: Removing OADP 1.2 references from docs
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/about-oadp-data-mover.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  backup_and_restore/application_backup_and_restore/oadp-advanced-topics.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-operator-supported.adoc
  modules/oadp-verifying-upgrade-1-4-0.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14

#84679 [enterprise-4.18] Remove items that are already GA
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: size/XS

#84485 OSDOCS-12510: Documented the 4.14.40 z-stream RNs
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#84684 [enterprise-4.17] TELCODOCS-1887: Image Based Install Operator
  _topic_maps/_topic_map.yml
  edge_computing/image-base-install/ibi-understanding-image-based-install.adoc
  edge_computing/image_base_install/_attributes
  edge_computing/image_base_install/ibi-factory-image-based-install.adoc
  edge_computing/image_base_install/ibi-preparing-for-image-based-install.adoc
  edge_computing/image_base_install/ibi-understanding-image-based-install.adoc
  edge_computing/image_base_install/ibi_deploying_sno_clusters/_attributes
  edge_computing/image_base_install/ibi_deploying_sno_clusters/ibi-edge-image-based-install-standalone.adoc
  edge_computing/image_base_install/ibi_deploying_sno_clusters/ibi-edge-image-based-install.adoc
  edge_computing/image_base_install/ibi_deploying_sno_clusters/images
  edge_computing/image_base_install/ibi_deploying_sno_clusters/modules
  edge_computing/image_base_install/ibi_deploying_sno_clusters/snippets
  edge_computing/image_base_install/images
  edge_computing/image_base_install/modules
  edge_computing/image_base_install/snippets
  images/711_OpenShift_IBI_Installation_high-level_0624.png
  modules/cnf-image-based-upgrade-generate-seed-image.adoc
  modules/cnf-image-based-upgrade-seed-image-config.adoc
  modules/ibi-create-config-iso.adoc
  modules/ibi-create-iso-for-bmh.adoc
  modules/ibi-create-standalone-config-iso.adoc
  modules/ibi-extra-manifests-configmap.adoc
  modules/ibi-image-based-install-cluster-guide.adoc
  modules/ibi-image-cluster-install-api-spec.adoc
  modules/ibi-install-ibi-operator.adoc
  modules/ibi-managed-cluster-config-resources.adoc
  modules/ibi-validated-software-versions.adoc
  release_notes/ocp-4-17-release-notes.adoc
Labels: size/XL, jira/valid-reference

#84654 RHDEVDOCS 6263 Release notes for Pipelines 1.16.1
  modules/op-release-notes-1-16.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#84386 Oadp 4074 network settings follow up
  backup_and_restore/application_backup_and_restore/oadp-performance/oadp-recommended-network-settings.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84004 OSSM-8185 Document installing OSSM 3 on a cluster with OSSM 2 (without interfering with the OSSM 2)
  _topic_maps/_topic_map.yml
  install/ossm-running-v2-same-cluster-as-v3-assembly.adoc
  modules/ossm-running-v2-v3-cluster-wide-deployment-model.adoc
  modules/ossm-running-v2-v3-multitenant-deployment-model.adoc
Labels: peer-review-done, size/L, merge-review-needed

#84636 [OSDOCS-12371] adding rosa create network documentation
  modules/rosa-create-objects.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed, branch/enterprise-4.17, branch/enterprise-4.18

#84708 Revert "Adding Python 2.7 compatible version of build_for_portal.py for use with bccutil in Prow CI"
  scripts/prow/prow_ci/build_for_portal_py27.py
Labels: size/XXL

#84560 [RHACS][Docs][4.6 and later versions] ROX-26679: Compliance reporting documentation
  modules/all-report-jobs-tab.adoc
  modules/analyzing-compliance-scan-schedules.adoc
  modules/configuration-details-tab.adoc
  modules/customizing-and-automating-your-compliance-scans.adoc
  modules/schedules-page-overview.adoc
  operating/manage-compliance/scheduling-compliance-scans-and-assessing-profile-compliance.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference

#84633 OSDOCS-12183-rework: rework of changes in delete Kustomize manifest resources
  _topic_maps/_topic_map_ms.yml
  microshift_running_apps/microshift-applications.adoc
  microshift_running_apps/microshift-deleting-resource-manifests.adoc
  modules/microshift-manifests-deletion-overview.adoc
  modules/microshift-manifests-overview.adoc
  modules/microshift-manifests-removal-scenario-ostree.adoc
  modules/microshift-manifests-removal-scenario-rpm.adoc
  modules/microshift-manifests-upgrade-scenario-ostree.adoc
  modules/microshift-manifests-upgrade-scenario-rpm.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.18

#84391 OSDOCS-12166: adds 4.14.40 relnotes Microshift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#83850 OBSDOCS-1359_New and OBSDOCS-817 (partially covered)
  _topic_maps/_topic_map.yml
  modules/log6x-configuring-lokistack-otlp-data-ingestion.adoc
  modules/log6x-quickstart-opentelemetry.adoc
  modules/log6x-quickstart-viaq.adoc
  observability/logging/logging-6.0/log6x-about.adoc
  observability/logging/logging-6.0/log6x-configuring-lokistack-otlp.adoc
  observability/logging/logging-6.0/log6x-loki.adoc
  observability/logging/logging-6.0/log6x-opentelemetry-data-model.adoc
Labels: peer-review-done, size/XXL, merge-review-in-progress

#83844 OSDOCS 12388 create dirs for CICD and Observability overviews to make books
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  cicd/overview/index.adoc
  modules/op-about-workspace-optional.adoc
  observability/overview/index.adoc
Labels: size/M

#78735 OSDOCS#41196: Reordering steps for configuring a DNS server
  modules/virt-configuring-secondary-dns-server.adoc
  modules/virt-connecting-vm-secondarynw-using-fqdn.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84587 OSDOCS#11845:MTO Operator Upgrate from TP to GA
  modules/multi-arch-installing-using-cli.adoc
  modules/multi-arch-installing-using-web-console.adoc
  modules/multi-arch-uninstalling-using-cli.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#82367 TRACING-4559: clarify replication factor
  modules/distr-tracing-tempo-config-default.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84384 OCPBUGS-38025: Add Network Observability Operator must-gather link to must-gather page listing
  modules/gathering-data-specific-features.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84027 RHDEVDOCS-6199 - Builds for OpenShift: Install and Config Documentation Obsolete
  installing/installing-openshift-builds.adoc
  modules/ob-creating-a-shipwright-build-resource-cli.adoc
  modules/ob-creating-a-shipwright-build-resource-console.adoc
  modules/ob-installing-builds-using-CLI.adoc
  modules/ob-installing-builds-using-cli.adoc
  modules/ob-installing-builds-with-operator.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#84735 [OSDOCS-12639]: Add HCP to addl RNs
  release_notes/addtl-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17

#84111 MCO add links to runbooks
  modules/machine-config-node-drain.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84727 [SRVKS-1061] Update readiness/liveness default availability
  eventing/tuning/overriding-config-eventing.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-needed

#83922 [SRVCOM-3354] Correct inline pass-through to +++
  modules/knative-eventing-modifying-consumer-group-ids-and-topic-names.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-in-progress

#84086 RHDEVDOCS-5845-new: Adding missing content to the gitops-docs-main repo
  argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.adoc
  argocd_application_sets/managing-app-sets-in-non-control-plane-namespaces.adoc
  declarative_clusterconfig/customizing-permissions-by-creating-aggregated-cluster-roles.adoc
  modules/gitops-argo-cd-properties.adoc
  modules/gitops-creating-aggregated-cluster-roles.adoc
  modules/gitops-release-notes-1-14-0.adoc
  modules/gitops-release-notes-1-14-1.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: peer-review-done, size/M, merge-review-needed, gitops

#84082 Updated docs issue RHDEVDOCS-6084
  modules/con_notifications-configuration.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-test, merge-review-needed, gitops

#84081 updated doc issue OEIIITB-16
  modules/gitops-modifying-keycloak-requests-limits.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-test, qe-approved, merge-review-in-progress, gitops

#84737 TELCODOCS-1960-RE: Expanded a sentence for offline migration to the O…
  modules/nw-ovn-kubernetes-migration-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.16

#84664 OCPBUGS#12622: Fixed Statically provisioning hostPath volumes bug
  modules/persistent-storage-hostpath-static-provisioning.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#84813 OSDOCS 12388 create symlinks in new overview directories
  cicd/overview/_attributes
  cicd/overview/images
  cicd/overview/modules
  cicd/overview/snippets
  observability/overview/_attributes
  observability/overview/images
  observability/overview/modules
  observability/overview/snippets
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#82600 [OSDOCS-7329]:Need Firewall prerequisites for OSD on GCP/[OSDOCS-12451]: Update "Customer Cloud Subscriptions on GCP" topic
  _topic_maps/_topic_map_osd.yml
  modules/ccs-gcp-customer-requirements.adoc
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
  modules/osd-gcp-psc-firewall-prerequisites.adoc
  osd_planning/gcp-ccs.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#84143 [OSDOCS-12383]Add PSC option to CCS infrastructure models in OSD GCP docs
  modules/osd-create-cluster-ccs.adoc
  modules/osd-create-cluster-gcp-account.adoc
  modules/osd-create-cluster-rhm-gcp-account.adoc
Labels: peer-review-in-progress, peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#83582 [OSDOCS-9401]:Document support for Private Service Connect on OSD-GCP
  _topic_maps/_topic_map_osd.yml
  images/psc-arch-overview.png
  modules/private-service-connect-create.adoc
  modules/private-service-connect-overview.adoc
  modules/private-service-connect-prereqs.adoc
  osd_install_access_delete_cluster/creating-a-gcp-psc-enabled-private-cluster.adoc
Labels: peer-review-in-progress, peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#83595 OSDOCS-12297:Added WIF as auth type in create cluster on GCP workflow.
  modules/osd-create-cluster-ccs.adoc
  modules/osd-create-cluster-gcp-account.adoc
  modules/osd-create-cluster-rhm-gcp-account.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#76600 [OSDOCS-10694]: OSD-GCP - Document GCP Workload Identity Federation
  _topic_maps/_topic_map_osd.yml
  modules/ccs-gcp-customer-procedure-serviceaccount.adoc
  modules/ccs-gcp-customer-procedure-wif.adoc
  modules/ccs-gcp-customer-procedure.adoc
  modules/ccs-gcp-customer-requirements.adoc
  modules/ccs-gcp-iam.adoc
  modules/ccs-gcp-understand.adoc
  modules/create-wif-cluster-cli.adoc
  modules/create-wif-cluster-ocm.adoc
  modules/policy-identity-access-management.adoc
  modules/wif-overview.adoc
  osd_architecture/osd_policy/osd-sre-access.adoc
  osd_install_access_delete_cluster/creating-a-gcp-cluster-with-workload-identity-federation.adoc
  osd_install_access_delete_cluster/creating-a-gcp-cluster.adoc
  osd_planning/gcp-ccs.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.17, branch/enterprise-4.18

#84835 OSDOCS-12654:Replace Accessing service logs link with Rosa cluster notifications link
  support/approved-access.adoc
Labels: lgtm, size/XS, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#83579 [OSDOCS-11924]: Getting started with OpenShift Dedicated
  osd_getting_started/osd-getting-started.adoc
Labels: peer-review-in-progress, peer-review-done, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#84593 OBSDOCS-1473: Prepare Enabling alert routing for user-defined project…
  modules/monitoring-enabling-alert-routing-for-user-defined-projects.adoc
  observability/monitoring/enabling-alert-routing-for-user-defined-projects.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-needed, jira/valid-reference

#83509 OADP 4878 Added install section for IBM Cloud
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud.adoc
  modules/configuring-ibm-cos.adoc
  modules/oadp-installing-dpa-1-3.adoc
  modules/oadp-secrets-for-different-credentials.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#84793 CNV-40192:Placeholder file for 4.18 RN
  virt/release_notes/virt-4-18-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#84202 [SRVCOM-2442] Improve links and linking for restructured content
  about/about-knative-eventing.adoc
  about/about-serverless.adoc
  about/serverless-logic-overview.adoc
  functions/serverless-functions-getting-started.adoc
  install/preparing-serverless-install.adoc
  integrations/serverless-pipelines-integration.adoc
  modules/serving-transport-encryption-overview.adoc
  observability/admin-metrics/serverless-admin-metrics.adoc
Labels: peer-review-done, size/S, serverless, merge-review-in-progress

#83741 Rhdevdocs 6204: Creating a separate release note folder and a tile for docs.redhat.com for Builds 1.2
  _topic_maps/_topic_map.yml
  modules/ob-compatibility-support-matrix.adoc
  modules/ob-release-notes-1-2.adoc
  release_notes/_attributes
  release_notes/docinfo.xml
  release_notes/images
  release_notes/modules
  release_notes/ob-release-notes.adoc
  release_notes/snippets
Labels: peer-review-done, size/M, merge-review-in-progress, openshift-builds

#84788 [gitops-docs-1.14] Adding missing content to the main gitops repo
  argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.adoc
  modules/gitops-release-notes-1-14-0.adoc
  modules/gitops-release-notes-1-14-1.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/S
