Repository openshift/openshift-docs, pull requests merged in 2025-02, with the labels that each got.

#87633 OBSDOCS-1607: Create better topic map name entries
  _topic_maps/_topic_map.yml
  cicd/gitops/monitoring-argo-cd-custom-resource-workloads.adoc
  cicd/pipelines/creating-applications-with-cicd-pipelines.adoc
  installing/overview/installing-preparing.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  networking/ingress-operator.adoc
  observability/distr_tracing/distr_tracing_tempo/distr-tracing-tempo-configuring.adoc
  observability/monitoring/about-ocp-monitoring/about-ocp-monitoring.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/accessing-metrics/accessing-monitoring-apis-by-using-the-cli.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-alerts-and-notifications.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-metrics.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/preparing-to-configure-the-monitoring-stack.adoc
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-alerts-and-notifications-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-metrics-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
  observability/monitoring/enabling-monitoring-for-user-defined-projects.adoc
  observability/monitoring/getting-started/core-platform-monitoring-first-steps.adoc
  observability/monitoring/getting-started/user-workload-monitoring-first-steps.adoc
  observability/monitoring/managing-alerts.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
  observability/otel/otel-configuring-otelcol-metrics.adoc
  observability/power_monitoring/visualizing-power-monitoring-metrics.adoc
  serverless/observability/developer-metrics/serverless-developer-metrics.adoc
  service_mesh/v2x/ossm-observability.adoc
  support/troubleshooting/investigating-monitoring-issues.adoc
  virt/monitoring/virt-exposing-custom-metrics-for-vms.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#87958 Remove prerequisite from builds
  modules/ob-creating-a-buildah-build.adoc
  modules/ob-creating-a-s2i-build.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#87943 [enterprise-4.15] OCPBUGS48047 As per the document it does not states that 'evictionPressureTransitionPeriod configuration' cannot be set to '0s'.
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-garbage-collection-containers.adoc
Labels: size/S, branch/enterprise-4.15

#87944 [enterprise-4.16] OCPBUGS48047 As per the document it does not states that 'evictionPressureTransitionPeriod configuration' cannot be set to '0s'.
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-garbage-collection-containers.adoc
Labels: size/S, branch/enterprise-4.16

#85974 OCPBUGS-45538:updates supported roles for UDN
  modules/nw-udn-cr.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#81800 OSDOCS-11826 ROSA/OSD increase to 249 nodes
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-what-is-rosa.adoc
  modules/rosa-sts-interactive-cluster-creation-mode-options.adoc
  modules/sd-planning-cluster-maximums.adoc
  modules/sd-planning-considerations.adoc
  osd_whats_new/osd-whats-new.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: lgtm, size/S, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#87857 doc: replace references to RHACS resources grouped under Administration
  modules/add-a-custom-header-and-footer.adoc
  modules/add-a-custom-login-message.adoc
  modules/configure-alert-data-retention.adoc
  modules/generate-diagnostic-bundle-using-acs-portal.adoc
  modules/generate-diagnostic-bundle-using-roxctl-cli.adoc
  modules/reissue-internal-certificates-central.adoc
  modules/reissue-internal-certificates-scanner.adoc
  modules/reissue-internal-certificates-secured-clusters-automatic-upgrades.adoc
  modules/reissue-internal-certificates-secured-clusters.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#87890 docs: replace references to RHACS resources grouped under Access
  modules/configure-minimum-access-role.adoc
  modules/create-a-custom-access-scope.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#87739 OSDOCS-13238 RODOO admonition added
  modules/rodoo-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.18

#83995 OBSDOCS-980: Add Jaeger deprecation notice and migration recommendations to the DT architecture page
  modules/distr-tracing-architecture.adoc
  modules/otel-collector-config-options.adoc
  modules/otel-forwarding-traces.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
  observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-configuring.adoc
  observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-installing.adoc
  observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-removing.adoc
  observability/distr_tracing/distr_tracing_jaeger/distr-tracing-jaeger-updating.adoc
  observability/otel/otel-config-multicluster.adoc
  snippets/distr-tracing-assembly-tip-for-jaeger-replacements.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85272 OSSM-8215 [DOC] Document using multiple control planes on a single cluster
  _topic_maps/_topic_map.yml
  install/ossm-deploying-multiple-service-meshes-on-single-cluster.adoc
  modules/ossm-about-deploying-multiple-control-planes.adoc
  modules/ossm-deploy-application-workloads-in-each-mesh.adoc
  modules/ossm-deploying-first-control-plane.adoc
  modules/ossm-deploying-second-control-plane.adoc
  modules/ossm-multiple-control-planes-single-cluster.adoc
  modules/ossm-verifying-multiple-control-planes.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress

#87821 OLS-1199: Document OCP layered product coverage
  _attributes/common-attributes.adoc
  about/ols-about-openshift-lightspeed.adoc
  modules/ols-about-product-coverage.adoc
  modules/ols-openshift-lightspeed-overview.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#87919 docs: replace references to RHACS resources grouped under WorkflowAdministration
  modules/create-a-custom-role.adoc
Labels: peer-review-done, size/M, RHACS, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#87186 [RHACS] [Docs] [4.6 only] ROX-27715: Updating release notes for 4.6.2
  modules/common-attributes.adoc
  release_notes/46-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, jira/valid-reference, rhacs-docs-4.6

#87920 OSDOCS-12449: adds Additional release notes to MicroShift
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#86295 CNV-46630: Connecting VMs to primary UDNs (GA)
  _topic_maps/_topic_map.yml
  modules/virt-attaching-vm-to-primary-udn.adoc
  modules/virt-creating-a-primary-cluster-udn.adoc
  modules/virt-creating-a-primary-udn.adoc
  virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.18

#88013 CNV#54753: 4.17.4 HCO bump
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.17

#87421 OCPBUGS-18537: (Release note) ingressClassName is required for all ingress objects
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, jira/severity-important, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference

#87106 OSDOCS-13053: add sysstat as available extension
  modules/rhcos-add-extensions.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.18

#87630 [OCPBUGS-49341] troubleshooting/operating-system: Fix incomplete note for kdump
  modules/troubleshooting-enabling-kdump-day-one.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87839 OCPBUGS-34880: Clarifying flow for disconnected with different registries for seed and target
  edge_computing/image_based_upgrade/cnf-image-based-upgrade-base.adoc
  modules/cnf-image-based-upgrade-prep.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87976 Fixing some typos
  modules/nodes-pods-vertical-autoscaler-custom-resource.adoc
  modules/nodes-sigstore-configure-cluster-policy.adoc
  modules/nodes-sigstore-configure-image-policy.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
  observability/logging/logging-6.0/log6x-meta-contributing.adoc
  scalability_and_performance/index.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87688 OBSDOCS-1638: Ensure all the content was transfered succesfully
  modules/monitoring-about-specifying-limits-and-requests-for-monitoring-components.adoc
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/accessing-metrics/accessing-metrics-as-a-developer.adoc
  observability/monitoring/accessing-metrics/accessing-metrics-as-an-administrator.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-alerts-and-notifications.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-metrics.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-alerts-and-notifications-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-metrics-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#87993 OSDOCS-13277: 4.17.2 Security Group Update for ROSA HCP
  modules/rosa-hcp-aws-private-security-groups.adoc
  rosa_hcp/rosa-hcp-aws-private-creating-cluster.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#88036 [enterprise-4.17] Fixing some typos
  modules/nodes-pods-vertical-autoscaler-custom-resource.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
  observability/logging/logging-6.0/log6x-meta-contributing.adoc
  scalability_and_performance/index.adoc
Labels: size/S

#88038 [enterprise-4.16] Fixing some typos
  modules/nodes-pods-vertical-autoscaler-custom-resource.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
  observability/logging/logging-6.0/log6x-meta-contributing.adoc
  scalability_and_performance/index.adoc
Labels: size/S

#88039 [enterprise-4.15] Fixing some typos
  modules/nodes-pods-vertical-autoscaler-custom-resource.adoc
  modules/ossm-rn-new-features-1x.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
  observability/logging/logging-6.0/log6x-meta-contributing.adoc
  scalability_and_performance/index.adoc
Labels: size/S

#88041 [enterprise-4.12] Fixing some typos
  modules/ossm-rn-new-features-1x.adoc
  scalability_and_performance/index.adoc
Labels: size/XS

#88040 [enterprise-4.14] Fixing some typos
  modules/ossm-rn-new-features-1x.adoc
  modules/ztp-deleting-node-using-siteconfig.adoc
  observability/logging/logging-6.0/log6x-meta-contributing.adoc
  scalability_and_performance/index.adoc
Labels: size/S

#88043 [enterprise-4.13] Fixing some typos
  modules/ossm-rn-new-features-1x.adoc
  scalability_and_performance/index.adoc
Labels: size/XS

#87194 OCPBUGS-39579_RN#adding NC2 rn
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#87970 CNV#48756: Create Advanced VM Creation Overview content
  _topic_maps/_topic_map.yml
  virt/creating_vms_advanced/advanced-vm-creation-overview.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.18

#87635 RHDEVDOCS-6303: Builds - Update _page_openshift_html
  .s2i/httpd-cfg/01-commercial.conf
  _templates/_page_openshift.html.erb
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#87681 HCIDOCS-586-OCP: OCI integration day 2
  installing/installing_oci/installing-oci-assisted-installer.adoc
  modules/installing-oci-adding-hosts-day-two.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#87422 OCPBUGS#38212: Added missing OVN Infra Controller default range to 4.…
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#87678 OSSM-8570: 2.6.5 (At Stage): [DOC] Release Notes
  _attributes/common-attributes.adoc
  modules/ossm-release-2-4-14.adoc
  modules/ossm-release-2-5-8.adoc
  modules/ossm-release-2-6-0.adoc
  modules/ossm-release-2-6-4.adoc
  modules/ossm-release-2-6-5.adoc
  service_mesh/v2x/servicemesh-release-notes.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87956 OBSDOCS-1637: Ensure the ROSA/OSD distros are rendering correctly.
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-configurable-monitoring-components.adoc
  modules/monitoring-configuring-a-persistent-volume-claim.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-configuring-pod-topology-spread-constraints.adoc
  modules/monitoring-configuring-remote-write-storage.adoc
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
  modules/monitoring-example-remote-write-authentication-settings.adoc
  modules/monitoring-example-remote-write-queue-configuration.adoc
  modules/monitoring-modifying-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-resizing-a-persistent-volume.adoc
  modules/monitoring-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-query-log-file-for-prometheus.adoc
  modules/monitoring-specifying-limits-and-requests-for-monitoring-components.adoc
  observability/monitoring/accessing-metrics/accessing-monitoring-apis-by-using-the-cli.adoc
  observability/monitoring/accessing-third-party-monitoring-apis.adoc
  observability/monitoring/common-monitoring-configuration-scenarios.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
  observability/monitoring/getting-started/core-platform-monitoring-first-steps.adoc
  observability/monitoring/monitoring-overview.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#88012 TELCODOCS-2051 NUMA-aware scheduling: clarify the operator configuration
  modules/cnf-creating-nrop-cr.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86873 OSDOCS#12867: Docs for hibernating a cluster
  _topic_maps/_topic_map.yml
  backup_and_restore/hibernating-cluster.adoc
  modules/hibernating-cluster-about.adoc
  modules/hibernating-cluster-hibernate.adoc
  modules/hibernating-cluster-resume.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.18

#85994 OADP-4058: Adding structure for OADP and 3scale user story
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-scheduling-backups-doc.adoc
  backup_and_restore/application_backup_and_restore/oadp-3scale/_attributes
  backup_and_restore/application_backup_and_restore/oadp-3scale/backing-up-and-restoring-3scale-by-using-oadp.adoc
  backup_and_restore/application_backup_and_restore/oadp-3scale/images
  backup_and_restore/application_backup_and_restore/oadp-3scale/modules
  backup_and_restore/application_backup_and_restore/oadp-3scale/snippets
  modules/backing-up-the-3scale-operator.adoc
  modules/backing-up-the-backend-redis-database.adoc
  modules/backing-up-the-mysql-database.adoc
  modules/creating-the-data-protection-application.adoc
  modules/restoring-the-backend-redis-database.adoc
  modules/restoring-the-mysql-database.adoc
  modules/restoring-the-secrets-and-apimanager.adoc
  modules/scaling-up-the-3scale-operator-and-deployment.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88034 [OCPBUGS-44218]: Fixing command in HCP backup docs
  modules/hosted-cluster-etcd-backup-restore-on-premise.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87708 OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/networking_operators/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88091 [enterprise-4.16] OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/networking_operators/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.16

#87341 OCPBUGS 43007: Removed the acme.cert-manager.io/http01-ingress-class annotation
  modules/cert-manager-acme-http01.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#88092 [enterprise-4.15] OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.15

#88093 [enterprise-4.14] OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.14

#88094 [enterprise-4.13] OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.13

#83968 [OCPBUGS-37638]: Add troubleshooting docs for HCP on bare metal
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-ts-bm-nodes-not-added.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#88095 [enterprise-4.12] OSDOCS-13230: Documenting uninstalling the K8S NMState Operator
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-uninstall-operator.adoc
  networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  operators/understanding/olm/olm-workflow.adoc
Labels: size/M, branch/enterprise-4.12, jira/valid-reference

#87907 OSDOCS-13271: Documented the 4.17.15 z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.17

#88042 Adds warning messages for readonly IR storage backend
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#86889 CNV#48755: (ContentX) Rework Creating VMs from templates
  modules/virt-creating-vm-from-template.adoc
  modules/virt-customizing-vm-template-web.adoc
  modules/virt-storage-wizard-fields-web.adoc
  modules/virt-vm-storage-volume-types.adoc
  virt/creating_vm/virt-creating-vms-from-templates.adoc
Labels: peer-review-done, size/M, CNV, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#88109 OCPBUGS-13065 removing incorrect output line
  modules/getting-started-cli-creating-secret.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88020 OBSDOCS-1670: Add TOC links to OTel Collector component-listing pages
  observability/otel/otel-collector/otel-collector-connectors.adoc
  observability/otel/otel-collector/otel-collector-exporters.adoc
  observability/otel/otel-collector/otel-collector-extensions.adoc
  observability/otel/otel-collector/otel-collector-processors.adoc
  observability/otel/otel-collector/otel-collector-receivers.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88049 OSDOCS-11792#adding new parameter
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.18

#87969 RHDEVDOCS-6365: Release Notes for Pipelines 1.17.1
  modules/op-release-notes-1-17.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#87975 OSDOCS#13261: Update the 4.12.72 z-stream RNs
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-needed

#88082 OCPBUGS#41513: Updating secrets store image to RHEL 9
  modules/gathering-data-specific-features.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88137 [enterprise-4.12] OCPBUGS-44843 Update guidance on why why you would one way over the o…
  networking/multiple_networks/configuring-additional-network.adoc
Labels: size/M, merge-review-in-progress

#88146 [enterprise-4.15] OCPBUGS-44843 Update guidance on why why you would one way over the o…
  networking/multiple_networks/configuring-additional-network.adoc
Labels: size/M, merge-review-in-progress

#88140 [enterprise-4.13] OCPBUGS-44843 Update guidance on why why you would one way over the o…
  networking/multiple_networks/configuring-additional-network.adoc
Labels: size/M, merge-review-in-progress

#88135 OCPBUGS-46510-label
  images/510-OpenShift-arch-012025.png
  images/525-OpenShift-arch-012025.png
  modules/architecture-platform-introduction.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#87952 RHDEVDOCS 6363 fix broken links - GitOps
  modules/gitops-argo-cd-properties.adoc
Labels: peer-review-done, size/XS

#88162 [OCPBUGS-37638]: Fixing typo in HCP troubleshooting docs
  hosted_control_planes/hcp-troubleshooting.adoc
Labels: size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#88029 CNV-40195: Updated version attributes for 4.18
  _attributes/common-attributes.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, jira/valid-reference, branch/enterprise-4.18

#86793 OSDOCS-12745: Rotating OIDC bound service account signer keys
  _attributes/common-attributes.adoc
  _unused_topics/manually-creating-iam-gcp.adoc
  modules/cco-ccoctl-configuring.adoc
  modules/refreshing-service-ids-ibm-cloud.adoc
  modules/rotating-bound-service-keys.adoc
  post_installation_configuration/changing-cloud-credentials-configuration.adoc
  snippets/ccoctl-provider-permissions-requirements.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.18

#88059 OSDOCS-12856-RN_2#C4 release note
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#87894 OSDOCS-13262: Documented the 4.16.33 z-stream notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.16

#88090 OSDOCS-13266: z-stream 4.14.46 RN
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#87900 OSDOCS-13311: Removed bundles feature from the oc-mirror v2 documentation
  modules/oc-mirror-imageset-config-parameters-v2.adoc
  modules/oc-mirror-operator-catalog-filtering.adoc
  modules/oc-mirror-v2-about.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.18

#88104 HCCDOC3485 Correct term disable to disabled in Insights-operator procedure
  modules/insights-operator-configuring.adoc
Labels: peer-review-done, size/XS, ok-to-test, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88151 [enterprise-4.16] OCPBUGS-44843 Update guidance on why why you would one way over the o…
  networking/multiple_networks/configuring-additional-network.adoc
Labels: size/M, merge-review-needed

#88081 [OSDOCS-7205] fixing CIDR default
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#88181 Add note on NM behavior with additional networks
  modules/install-osp-deploy-dualstack.adoc
Labels: size/XS

#87917 TELCODOCS-1975 - ZTP Configuring the hub cluster for backup and restore
  edge_computing/ztp-preparing-the-hub-cluster.adoc
  modules/ztp-configuring-the-hub-cluster-for-backup-and-restore.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, branch/enterprise-4.18

#88108 OSSM-5365: Delete CRDs when deleting the operator
  modules/ossm-uninstalling-service-mesh-operator-control-plane-web-console.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#87228 OSDOCS-8646: Rewriting introduction to networking (ContentX)
  _topic_maps/_topic_map.yml
  modules/nw-load-balancing-about.adoc
  modules/nw-load-balancing-configure-define-type.adoc
  modules/nw-load-balancing-configure-specify-behavior.adoc
  modules/nw-load-balancing-configure.adoc
  modules/nw-understanding-networking-choosing-service-types.adoc
  modules/nw-understanding-networking-common-practices.adoc
  modules/nw-understanding-networking-concepts-components.adoc
  modules/nw-understanding-networking-controls.adoc
  modules/nw-understanding-networking-dns-example.adoc
  modules/nw-understanding-networking-dns-terms.adoc
  modules/nw-understanding-networking-dns.adoc
  modules/nw-understanding-networking-exposing-applications.adoc
  modules/nw-understanding-networking-features.adoc
  modules/nw-understanding-networking-how-pods-communicate.adoc
  modules/nw-understanding-networking-ingress.adoc
  modules/nw-understanding-networking-networking-in-OpenShift.adoc
  modules/nw-understanding-networking-nodes-clients-clusters.adoc
  modules/nw-understanding-networking-pod-to-pod-example.adoc
  modules/nw-understanding-networking-pod-to-pod.adoc
  modules/nw-understanding-networking-routes-ingress-example.adoc
  modules/nw-understanding-networking-routes-ingress.adoc
  modules/nw-understanding-networking-routes-vs-ingress.adoc
  modules/nw-understanding-networking-routes.adoc
  modules/nw-understanding-networking-securing-connections.adoc
  modules/nw-understanding-networking-security-example.adoc
  modules/nw-understanding-networking-security.adoc
  modules/nw-understanding-networking-service-to-pod-example.adoc
  modules/nw-understanding-networking-service-to-pod.adoc
  modules/nw-understanding-networking-what-is-a-client.adoc
  modules/nw-understanding-networking-what-is-a-cluster.adoc
  modules/nw-understanding-networking-what-is-a-node.adoc
  networking/about-networking.adoc
  networking/understanding-networking.adoc
Labels: peer-review-done, size/XL, qe-approved, merge-review-in-progress, merge-review-needed, jira/valid-reference

#87731 OSDOCS-11795: Shared VPC doc updates.
  modules/rosa-sharing-vpc-dns-and-roles.adoc
  modules/rosa-sharing-vpc-hosted-zones.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, SD-docs, branch/enterprise-4.17, branch/enterprise-4.18

#87977 OSDOCS#12867: Release note for hibernating up to 90 days
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.18

#87965 OCPBUGS#43809: Clarifying what's created for each service account
  authentication/understanding-and-creating-service-accounts.adoc
  modules/service-accounts-creating.adoc
  modules/service-accounts-granting-roles.adoc
  modules/service-accounts-overview.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88197 Add note on NM behavior with additional networks
  modules/install-osp-deploy-dualstack.adoc
Labels: size/XS

#86404 [OCPBUGS-42779]: Adding known issue to HCP release notes
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, px-approved

#88207 RHDEVDOCS 6363 fix broken links - GitOps
  modules/gitops-argo-cd-properties.adoc
Labels: lgtm, size/XS

#88208 RHDEVDOCS 6363 fix broken links - GitOps
  modules/gitops-argo-cd-properties.adoc
Labels: lgtm, size/XS

#87304 RHDEVDOCS 6356 set version attributes to 1.18
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#87951 RHDEVDOCS 6363 fix broken links - Pipelines
  create/creating-applications-with-cicd-pipelines.adoc
  install_config/installing-pipelines.adoc
  modules/op-chains-signing-secrets-cosign.adoc
  modules/op-creating-and-verifying-task-run-signatures-without-any-additional-authentication.adoc
  modules/op-creating-repository-cr.adoc
  modules/op-setting-up-openshift-pipelines-to-download-or-view-sboms.adoc
  modules/op-supported-parameters-tekton-chains-configuration.adoc
  modules/op-using-remote-task-annotations-with-pipelines-as-code.adoc
  modules/op-using-tekton-chains-to-sign-and-verify-image-and-provenance.adoc
  records/viewing-pipeline-logs-using-the-openshift-logging-operator.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, pipelines

#85632 [RHACS][Docs][4.6 and later] ROX-26389: Updating system health documentation
  modules/administration-usage-page-overview.adoc
  modules/analyzing-and-managing-the-system-health-information.adoc
  modules/cluster-status-section.adoc
  modules/image-integrations-section.adoc
  modules/sensor-upgrade-section.adoc
  modules/system-health-dashboard-details.adoc
  modules/system-health-dashboard-page-overview.adoc
  modules/viewing-product-usage.adoc
  operating/use-system-health-dashboard.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.7

#87279 OSDOCS-12746: Rotating OIDC bound keys (RN)
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.18

#88221 OCPBUGS-46428-4-18-known-issue: Adding KI to 4.18 release notes for Telco team
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#88141 OSDOCS-13044-RN_2#Adding BYO PHZ RN
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, merge-review-in-progress, merge-review-needed

#88178 fixing agent headings
  installing/installing_with_agent_based_installer/installing-with-agent-based-installer.adoc
  installing/installing_with_agent_based_installer/prepare-pxe-assets-agent.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.18

#88225 [rhacs-docs-4.4] docs: replace references to RHACS resources grouped under WFA
  modules/create-a-custom-role.adoc
Labels: size/M

#88224 change short attribute to first
  modules/rotating-bound-service-keys.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#87908 adding providing feedback topic
  _topic_maps/_topic_map.yml
  welcome/providing-feedback-on-red-hat-documentation.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#88239 [enterprise-4.18] adding providing feedback topic
  _topic_maps/_topic_map.yml
  welcome/providing-feedback-on-red-hat-documentation.adoc
Labels: size/S

#88218 OADP-4882: Update OADP version to 1.4.2
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88229 TELCODOCS-1975 - ZTP Configuring the hub cluster for backup and restore
  edge_computing/ztp-preparing-the-hub-cluster.adoc
  modules/ztp-configuring-the-hub-cluster-for-backup-and-restore.adoc
Labels: peer-review-done, size/L, merge-review-needed

#87152 OLS-1346: Document the use of AdditionalCAConfigMapRef in CRD file
  configure/ols-configuring-openshift-lightspeed.adoc
  modules/ols-configuring-lightspeed-with-a-trust-provider-certificate-for-the-llm.adoc
  modules/ols-creating-lightspeed-custom-resource-file-using-cli.adoc
  modules/ols-creating-lightspeed-custom-resource-file-using-web-console.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#87629 TELCODOCS#2136: Deprecation of SiteConfig v1
  edge_computing/ztp-advanced-install-ztp.adoc
  modules/ztp-creating-ztp-crs-for-multiple-managed-clusters.adoc
  modules/ztp-deploying-a-site.adoc
  modules/ztp-generating-install-and-config-crs-manually.adoc
  modules/ztp-precaching-ztp-config.adoc
  snippets/siteconfig-deprecation-notice.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.18

#88066 OCPBUGS#49859: Added br-ex note to the networking route doc
  modules/virt-example-nmstate-IP-management.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88157 TELCODOCS-1871 - Corrected typo - Configuring an RDMA subsystem for …
  _topic_maps/_topic_map.yml
  networking/hardware_networks/configuring-sriov-rdma-cni.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#88275 [enterprise-4.14] OCPBUGS-49859: Added br-ex note to the networking route doc
  modules/virt-example-nmstate-IP-management.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#88274 [enterprise-4.15] OCPBUGS-49859-15
  modules/virt-example-nmstate-IP-management.adoc
Labels: size/S, branch/enterprise-4.15

#87603 OCPBUGS#48847: Documented IPoIB support for nmstate
  installing/installing_bare_metal/ipi/ipi-install-post-installation-configuration.adoc
  modules/creating-manifest-file-customized-br-ex-bridge.adoc
  modules/virt-creating-infiniband-interface-on-nodes.adoc
Labels: peer-review-done, size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87835 CNV-55143: Fix machine configuration and add explicit warning about usage of resources.requests.memory
  modules/virt-using-wasp-agent-to-configure-higher-vm-workload-density.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#87656 CNV-51078: Document bulk VM operations
  modules/virt-controlling-multiple-vms.adoc
  virt/managing_vms/virt-controlling-vm-states.adoc
Labels: peer-review-done, lgtm, size/S, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18

#88285 [enterprise-4.16] OCPBUGS-48847: Documented IPoIB support for nmstate
  modules/creating-manifest-file-customized-br-ex-bridge.adoc
  modules/virt-creating-infiniband-interface-on-nodes.adoc
  post_installation_configuration/post-install-bare-metal-configuration.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16

#88289 [enterprise-4.15] OCPBUGS-48847: Documented IPoIB support for nmstate
  installing/installing_bare_metal_ipi/ipi-install-post-installation-configuration.adoc
  modules/nw-enabling-a-provisioning-network-after-installation.adoc
  modules/virt-creating-infiniband-interface-on-nodes.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#87836 OCPBUGS#41970: Updated MTU data type in MACVLAN table
  modules/nw-multus-macvlan-object.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88180 HCIDOCS-417: Remove IDRAC 8 from Firmware requirements for installing with virtual media
  modules/ipi-install-firmware-requirements-for-installing-with-virtual-media.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference

#88048 OSDOCS#12883: Granting user access to OLMv1 extension resources
  _topic_maps/_topic_map.yml
  extensions/ce/user-access-resources.adoc
  modules/olmv1-default-cluster-roles-users.adoc
  modules/olmv1-finding-ce-resources.adoc
  modules/olmv1-granting-user-access-aggregated.adoc
  modules/olmv1-granting-user-access-binding.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.18

#88294 [enterprise-4.15] OCPBUGS-41970: Updated MTU data type in MACVLAN table
  modules/nw-multus-macvlan-object.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#88296 [enterprise-4.13] OCPBUGS-41970: Updated MTU data type in MACVLAN table
  modules/nw-multus-macvlan-object.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#88297 [enterprise-4.12] OCPBUGS-41970: Updated MTU data type in MACVLAN table
  modules/nw-multus-macvlan-object.adoc
Labels: size/XS, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference

#85554 [OSDOCS#12598] GA single stack IPv6 for ShiftStack
  installing/installing_openstack/installing-openstack-installer-custom.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-configuring-shiftstack-single-ipv6.adoc
  modules/nw-ovn-kubernetes-features.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.18

#87921 OSDOCS-9718 add two new steps under the Creating a route using the de…
  modules/nw-ingress-reencrypt-route-custom-cert.adoc
Labels: peer-review-done, size/S, qe-approved, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88190 OSDOCS-13318: adds missing steps to EUS repo config MicroShift
  modules/microshift-embed-ostree-enable-eus-repos.adoc
  modules/microshift-updating-rpms-y.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#86102 OSDOCS-12842#Remove Shared Resource CSI Driver
  _topic_maps/_topic_map.yml
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-additional-details-about-volumeattributes-on-shared-resource-pod-volumes.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-additional-support-limitations-for-shared-resource-csi-driver.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-integration-between-shared-resources-insights-operator-and-openshift-builds.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-sharing-configmaps-across-namespaces.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-sharing-secrets-across-namespaces.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-using-a-sharedconfigmap-object-in-a-pod.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/Modules/ephemeral-storage-using-a-sharedsecrets-resource-in-a-pod.adoc
  _unused_topics/Storage_Shared_Resource_CSI_Driver/ephemeral-storage-shared-resource-csi-driver-operator.adoc
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
  modules/ephemeral-storage-csi-inline-overview-admin-plugin.adoc
  modules/ephemeral-storage-csi-inline-overview.adoc
  modules/gathering-data-specific-features.adoc
  modules/nodes-cluster-enabling-features-about.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/ephemeral-storage-csi-inline.adoc
Labels: peer-review-in-progress, peer-review-needed, peer-review-done, lgtm, size/M, branch/enterprise-4.18

#88037 OSDOCS-13070: backport adding EUS repos to MicroShift 4.14
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_updating/microshift-update-options.adoc
  microshift_updating/microshift-update-rpms-manually.adoc
  modules/microshift-embed-ostree-enable-eus-repos.adoc
  modules/microshift-updating-rpms-y.adoc
  snippets/microshift-unsupported-config-warn.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.14

#87964 OADP-4883: Added 1.4.3 release notes
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/oadp-1-4-3-release-notes.adoc
Labels: peer-review-done, size/S, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87729 OCPBUGS#23172 adding RODOO known issue to 4.17 RNs
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, px-approved, merge-review-in-progress, merge-review-needed, branch/enterprise-4.17

#74611 OCPBUGS#23172 4.15 RN RODOO can't run on hypershift
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.15

#74608 OCPBUGS#23172 RN RODOO can't run on hypershift clusters
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14

#84937 OSDOCS-11831: Add Support book to ROSA HCP
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/accessing-running-pods.adoc
  modules/cluster-resources.adoc
  modules/copying-files-pods-and-containers.adoc
  modules/inspecting-pod-and-container-logs.adoc
  modules/monitoring-determining-why-prometheus-is-consuming-disk-space.adoc
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
  modules/monitoring-resolving-the-kubepersistentvolumefillingup-alert-firing-for-prometheus.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/querying-cluster-node-journal-logs.adoc
  modules/querying-operator-pod-status.adoc
  modules/reviewing-node-status-usage-and-configuration.adoc
  modules/reviewing-pod-status.adoc
  modules/rosa-sts-aws-requirements-creating-association.adoc
  modules/rosa-sts-ocm-and-user-role-troubleshooting.adoc
  modules/rosa-sts-ocm-role-creation.adoc
  modules/rosa-sts-user-role-creation.adoc
  modules/rosa-troubleshooting-cluster-deletion.adoc
  modules/rosa-troubleshooting-elb-service-role.adoc
  modules/rosa-troubleshooting-general-deployment.adoc
  modules/rosa-troubleshooting-installing.adoc
  modules/rosa-troubleshooting-networking-nlb.adoc
  modules/starting-debug-pods-with-root-access.adoc
  modules/summarizing-cluster-specifications-through-clusterversion.adoc
  modules/support-collecting-host-network-trace.adoc
  modules/support-collecting-network-trace.adoc
  modules/support-providing-diagnostic-data-to-red-hat.adoc
  modules/support-reviewing-an-access-request-from-an-email-notification.adoc
  modules/support-reviewing-an-access-request-from-the-hybrid-console.adoc
  modules/support-submitting-a-case-enable-approved-access.adoc
  modules/telemetry-showing-data-collected-from-the-cluster.adoc
  modules/telemetry-what-information-is-collected.adoc
  support/approved-access.adoc
  support/gathering-cluster-data.adoc
  support/index.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring.adoc
  support/remote_health_monitoring/using-insights-operator.adoc
  support/troubleshooting/investigating-monitoring-issues.adoc
  support/troubleshooting/investigating-pod-issues.adoc
  support/troubleshooting/rosa-troubleshooting-iam-resources.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
  support/troubleshooting/verifying-node-health.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, jira/valid-reference

#88266 TELCODOCS-1975 - fixing typo
  modules/ztp-configuring-the-hub-cluster-for-backup-and-restore.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.18

#86171 OCPBUGS-44063: Removing RHEL 9.2 update requirement 4.15+
  modules/installation-minimum-resource-requirements.adoc
  modules/installation-vsphere-infrastructure.adoc
  updating/preparing_for_updates/updating-cluster-prepare.adoc
Labels: peer-review-done, size/S, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88331 OCPBUGS#50553: Fix typo
  modules/containers-signature-verify-unsigned.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88144 4.18 RN - TELCODOCS-1871 - Configuring an RDMA subsystem for SR-IOV
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.18

#87680 OADP-4161 ImagePullPolicy
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-kubevirt.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/oadp-configuring-imagepullpolicy.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, OADP, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88352 Revert "OADP-4883: Added 1.4.3 release notes"
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/oadp-1-4-3-release-notes.adoc
Labels: size/S, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#88192 OSDOCS-13070-415: backport adding EUS repos MicroShift 4.15
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_updating/microshift-update-options.adoc
  microshift_updating/microshift-update-rpms-manually.adoc
  modules/microshift-embed-ostree-enable-eus-repos.adoc
  modules/microshift-updating-rpms-y.adoc
  snippets/microshift-unsupported-config-warn.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.15

#88184 OSDOCS-13069: backport adding EUS repos to MicroShift 4.16
  microshift_install/microshift-embed-in-rpm-ostree.adoc
  microshift_updating/microshift-update-options.adoc
  microshift_updating/microshift-update-rpms-manually.adoc
  modules/microshift-embed-ostree-enable-eus-repos.adoc
  modules/microshift-updating-rpms-y.adoc
  snippets/microshift-unsupported-config-warn.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.16

#88232 4.15 - OADP-5489: release notes for OADP 1.3.5
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-5.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, OADP, jira/valid-reference

#88253 4.12 - OADP-5489: release notes for OADP 1.3.5
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-5.adoc
Labels: size/S, branch/enterprise-4.12, merge-review-in-progress, OADP, jira/valid-reference

#88055 OCPBUGS-42798:updates ip forwarding CNO
  modules/nw-operator-cr.adoc
  networking/networking_operators/cluster-network-operator.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#88215 OSSM-8700: [DOC] Remove 2.6 and 3.0 side-by-side content
  _topic_maps/_topic_map.yml
  migrating/ossm-migrating-read-me-assembly.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#87340 TELCODOCS-2149 RN: deferred tuned updates RN 418
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS

#88194 adding redirects for PR87901
  .s2i/httpd-cfg/01-commercial.conf
Labels: lgtm, size/XS

#88216 OSSM-8699: [DOC] Add warning to installation documentation about potential conflicts with 2.6
  install/ossm-installing-openshift-service-mesh.adoc
Labels: peer-review-done, size/XS, service-mesh, merge-review-in-progress, merge-review-needed, jira/valid-reference

#88366 OSDOCS#13353: Add hosted control planes to term glossary
  contributing_to_docs/term_glossary.adoc
Labels: peer-review-done, size/S

#87834 OCPBUGS-39568-fix: Added note about 3rd party plugin to OVNK plugin]
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#88209 OSDOCS#12828: Remove references to pull secrets in cluster catalog CRs
  _unused_topics/olmv1-creating-a-pull-secret-for-catalogd.adoc
  modules/olmv1-about-catalogs.adoc
  modules/olmv1-adding-a-catalog.adoc
  modules/olmv1-installing-an-operator.adoc
  snippets/olmv1-multi-catalog-admon.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.18

#88384 [enterprise-4.15] OCPBUGS-39568-fix: Added note about 3rd party plugin to OVNK plugin]
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, branch/enterprise-4.15

#88386 [enterprise-4.13] OCPBUGS-39568-fix: Added note about 3rd party plugin to OVNK plugin]
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, branch/enterprise-4.13

#88385 [enterprise-4.14] OCPBUGS-39568-fix: Added note about 3rd party plugin to OVNK plugin]
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, branch/enterprise-4.14

#88390 [enterprise-4.17] OSDOCS-11831: Add Support book to ROSA HCP
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  modules/accessing-running-pods.adoc
  modules/cluster-resources.adoc
  modules/copying-files-pods-and-containers.adoc
  modules/inspecting-pod-and-container-logs.adoc
  modules/monitoring-determining-why-prometheus-is-consuming-disk-space.adoc
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
  modules/monitoring-resolving-the-kubepersistentvolumefillingup-alert-firing-for-prometheus.adoc
  modules/olm-cs-status-cli.adoc
  modules/olm-status-viewing-cli.adoc
  modules/querying-cluster-node-journal-logs.adoc
  modules/querying-operator-pod-status.adoc
  modules/reviewing-node-status-usage-and-configuration.adoc
  modules/reviewing-pod-status.adoc
  modules/rosa-sts-aws-requirements-creating-association.adoc
  modules/rosa-sts-ocm-and-user-role-troubleshooting.adoc
  modules/rosa-sts-ocm-role-creation.adoc
  modules/rosa-sts-user-role-creation.adoc
  modules/rosa-troubleshooting-cluster-deletion.adoc
  modules/rosa-troubleshooting-elb-service-role.adoc
  modules/rosa-troubleshooting-general-deployment.adoc
  modules/rosa-troubleshooting-installing.adoc
  modules/rosa-troubleshooting-networking-nlb.adoc
  modules/starting-debug-pods-with-root-access.adoc
  modules/summarizing-cluster-specifications-through-clusterversion.adoc
  modules/support-collecting-host-network-trace.adoc
  modules/support-collecting-network-trace.adoc
  modules/support-providing-diagnostic-data-to-red-hat.adoc
  modules/support-reviewing-an-access-request-from-an-email-notification.adoc
  modules/support-reviewing-an-access-request-from-the-hybrid-console.adoc
  modules/support-submitting-a-case-enable-approved-access.adoc
  modules/telemetry-showing-data-collected-from-the-cluster.adoc
  modules/telemetry-what-information-is-collected.adoc
  support/approved-access.adoc
  support/gathering-cluster-data.adoc
  support/index.adoc
  support/remote_health_monitoring/about-remote-health-monitoring.adoc
  support/remote_health_monitoring/showing-data-collected-by-remote-health-monitoring.adoc
  support/remote_health_monitoring/using-insights-operator.adoc
  support/troubleshooting/investigating-monitoring-issues.adoc
  support/troubleshooting/investigating-pod-issues.adoc
  support/troubleshooting/rosa-troubleshooting-iam-resources.adoc
  support/troubleshooting/troubleshooting-operator-issues.adoc
  support/troubleshooting/verifying-node-health.adoc
Labels: size/XL, jira/valid-reference

#88254 4.13 - OADP-5489: release notes for OADP 1.3.5
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-5.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, OADP, jira/valid-reference

#87204 ROX-27514: Updates to RNs for patch release 4.5.6
  modules/common-attributes.adoc
  release_notes/45-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, rhacs-docs-4.5

#88044 [OSDOCS-13017]: Adding missing link to etcd docs
  scalability_and_performance/recommended-performance-scale-practices/recommended-etcd-practices.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#87439 MCO On Cluster Layering Quickstart Edits
  modules/coreos-layering-configuring-on.adoc
  modules/coreos-layering-configuring.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18
