Repository openshift/openshift-docs, pull requests merged in 2025-03, with the labels that each got.

#89381 OCPBUGS#49648: Fix the table formatting
  modules/hcp-aws-create-dns-hosted-zone.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89397 moves table to correct section
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#89394 OSDOCS-13518: adds clarification on xrefs for snippets
  contributing_to_docs/doc_guidelines.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#89109 OKD-234: Clarify usage of external operator catalog sources
  modules/olm-installing-operators-from-operatorhub-configure.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89050 GH-81519: Update mirroring instructions for OKD
  modules/installation-mirror-repository.adoc
  modules/ipi-install-mirroring-for-disconnected-registry.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89237 [OSDOCS-13239]: Adding pointer from OCP support docs to HCP must gather docs
  modules/support-gather-data.adoc
  support/gathering-cluster-data.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89437 OSDOCS-13525 4.14 lifecycle update to May 1, 2025
  modules/life-cycle-dates.adoc
Labels: lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#87695 RHDEVDOCS-6343: Content creation for respectRBAC operator
  declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  modules/gitops-configuring-respect-rbac-using-gitops.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#89110 Fix incorrect nesting of monitoring docs
  observability/monitoring/configuring-core-platform-monitoring/configuring-alerts-and-notifications.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-alerts-and-notifications-uwm.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  observability/monitoring/managing-alerts.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89278 [OCPBUGS48728] Remove step to disable udp aggregation
  modules/machine-user-infra-machines-ibm-z-kvm.adoc
  modules/machine-user-infra-machines-ibm-z.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89464 fixing oc-mirror typo
  modules/microshift-oc-mirror-creating-imageset-config.adoc
  modules/oc-mirror-creating-image-set-config.adoc
Labels: size/XS, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89463 Minor updates to What's New for the OCP 4.18 release.
  rosa_release_notes/rosa-release-notes.adoc
Labels: lgtm, size/S, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#89425 updating logic for OKD banner
  _templates/_page_openshift.html.erb
Labels: size/XS

#89424 OSSM-8988 Update mention of 1.24.1 in an example output to 1.24.3
  modules/ossm-migrating-multitenant-workloads-with-cert-manager.adoc
  modules/ossm-migrating-multitenant-workloads.adoc
Labels: peer-review-done, lgtm, size/XS

#89435 Minor fixes in CUDN docs
  modules/nw-cudn-cr.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89409 logging: consolidated cherry-picks for OCP 4.17
  _topic_maps/_topic_map.yml
  modules/log6x-enabling-loki-alerts.adoc
  modules/log6x-identity-federation.adoc
  modules/log6x-loki-memberlist-ip.adoc
  modules/log6x-loki-pod-placement.adoc
  modules/log6x-loki-rate-limit-errors.adoc
  modules/log6x-loki-rbac-rules-perms.adoc
  modules/log6x-loki-reliability-hardening.adoc
  modules/log6x-loki-restart-hardening.adoc
  modules/log6x-loki-retention.adoc
  modules/log6x-loki-sizing.adoc
  modules/log6x-loki-zone-aware-rep.adoc
  modules/log6x-loki-zone-fail-recovery.adoc
  observability/logging/logging-6.2/log6x-loki-6.2.adoc
  observability/logging/logging-6.2/log6x-visual-6.2.adoc
  snippets/log6x-loki-statement-snip.adoc
Labels: size/M, merge-review-in-progress

#89476 OSDOCS-13352 Adding information to note in updating the disconnected…
  modules/update-restricted.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89465 OSSM-8990 Typo in file name
  migrating/done/ossm-migrating-complete-assembly.adoc
  modules/ossm-migrating-complete-multitenant-cert-manager.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#89234 CNV#56500: [Docs] Incorrect yaml for HostPathProvisioner
  modules/virt-creating-hpp-basic-storage-pool.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, merge-review-in-progress

#89452 OSSM-8939 Add xrefs for Mulitenant Migration Guide
  migrating/multitenant/ossm-migrating-multitenant-assembly.adoc
Labels: peer-review-done, size/S

#89030 Update the steps for restricting build strategies to a user within a …
  modules/builds-restricting-build-strategy-to-user.adoc
Labels: peer-review-done, lgtm, size/XS, ok-to-test, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89273 OSSM-8769 [DOCS] 3.0 Known Issues
  modules/ossm-release-notes-3-0-known-issues.adoc
  ossm-release-notes/ossm-release-notes-assembly.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#89178 RHDEVDOCS 6347 PAC: on-path-changed, on-path-changed-ignore annotations
  modules/op-matching-pipeline-run-using-pipelines-as-code.adoc
Labels: peer-review-done, size/M, merge-review-in-progress

#89514 OCPBUGS#50691: Add link to prevent workload updates section
  updating/updating_a_cluster/control-plane-only-update.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89515 Removes Collector slim references
  modules/image-versions.adoc
  modules/update-other-images.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.7

#79801 OSDOCS#11394: Added documentation for the External ID flag
  modules/rosa-create-objects.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-list-objects.adoc
Labels: size/S, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89475 OCPBUGS-36535# typo in Release Notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#89521 Change RHEL version to 8.8 or later
  modules/rhel-images-aws.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.18, branch/enterprise-4.19

#89534 MCO remove TP note from Updated Boot Images
  modules/mco-update-boot-images-configuring.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89523 CNV-39983: Fix a typo in the virtctl command
  modules/virt-virtctl-commands.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.14

#89531 fix typos in cloud docs
  modules/cloud-info-security.adoc
Labels: peer-review-done, size/XS, RHACS, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#89549 CNV#54758: HCO version bump 4.17.5
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.17

#89550 CNV#57438: HCO version bump 4.14.11
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.14

#89421 OSDOCS-13100: adds 4.18.2 relnote MicroShift
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference

#89339 OSDOCS-13225 Admonition note for HighNodeUtilization
  modules/nodes-scheduler-profiles-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#88965 OSSM-8770 Update feature support tables
  _topic_maps/_topic_map.yml
  modules/ossm-release-notes-consoles-and-dashboards.adoc
  modules/ossm-release-notes-extensibility-features.adoc
  modules/ossm-release-notes-istio-ambient-mode.adoc
  modules/ossm-release-notes-istio-deployment-lifecycle.adoc
  modules/ossm-release-notes-istio-traffic-management.adoc
  modules/ossm-release-notes-kubernetes-gateway-api.adoc
  modules/ossm-release-notes-making-open-source-inclusive.adoc
  modules/ossm-release-notes-observability-features.adoc
  modules/ossm-release-notes-sail-operator-apis.adoc
  modules/ossm-release-notes-security-features.adoc
  modules/ossm-release-notes-supported-versions.adoc
  ossm-release-notes/ossm-release-notes-assembly.adoc
  ossm-release-notes/ossm-release-notes-support-tables-assembly.adoc
  snippets/technology-preview.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed

#88198 OSSM-8759 Pre-migration checklist for product docs
  _topic_maps/_topic_map.yml
  migrating/checklists/docinfo.xml
  migrating/checklists/ossm-migrating-network-policies-assembly.adoc
  migrating/checklists/ossm-migrating-premigration-checklists-assembly.adoc
  migrating/ossm-migrating-from-service-mesh-2-to-3-assembly.adoc
  modules/ossm-migrating-premigration-checklists-resource-files.adoc
  modules/ossm-migrating-premigration-checklists-using-the-cert-manager-tool-with-your-deployment.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress

#88330 OBSDOCS-1665: Update docs for FIPS enablement in power monitoring
  modules/power-monitoring-fips-support.adoc
  observability/power_monitoring/power-monitoring-overview.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#87880 OBSDOCS-1664: Power monitoring Tech Preview 0.4 release notes
  observability/power_monitoring/power-monitoring-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89449 imagedigestmirrorset and imagetagmirrorset is cluster wide resource hence need to update OCP DOC
  modules/oc-mirror-migration-process.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89583 OBSDOCS-1742: Fixing doc bugs in FIPS enablement content
  modules/power-monitoring-fips-support.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89588 [enterprise-4.15] OCPBUGS#50691: Add link to prevent workload updates section
  updating/updating_a_cluster/control-plane-only-update.adoc
Labels: size/XS

#89589 [enterprise-4.16] OCPBUGS#50691: Add link to prevent workload updates section
  updating/updating_a_cluster/control-plane-only-update.adoc
Labels: size/XS

#87882 RHDEVDOCS-6342: Content creation for sensitive annotations feature
  _topic_maps/_topic_map.yml
  modules/gitops_enabling_sensitive_annotations_in_the_argo_cd_web_ui.adoc
  securing_openshift_gitops/masking-sensitive-annotations-in-the-argo-cd-web-ui.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#89415 OSDOCS-13464: Documented the 4.18.2 z-stream release notes
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.18

#87145 OSDOCS-12906: Linked HTTP/2 doc in route config guide
  modules/nw-creating-a-route.adoc
  modules/nw-enabling-hsts-per-route.adoc
  modules/nw-http2-haproxy.adoc
  networking/networking_operators/ingress-operator.adoc
  networking/routes/route-configuration.adoc
Labels: peer-review-done, size/M, qe-approved, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#89420 OBSDOCS-1734: Logging 6.0.5 release notes
  modules/log6x-rn-6.0.5.adoc
  observability/logging/logging-6.0/log6x-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17

#89383 OCPBUGS#51001: Update disconnected mirroring steps for HCP
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-bm.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  modules/hcp-dc-image-mirror.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#88028 TELCODOCS-1840 siteConfigError created to surface more info on error …
  modules/ztp-troubleshooting-ztp-gitops-installation-crs.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.17, branch/enterprise-4.18

#89601 TELCODOCS-1840 416 siteConfigError created to surface more info on error
  modules/ztp-troubleshooting-ztp-gitops-installation-crs.adoc
Labels: lgtm, size/S, merge-review-needed, branch/enterprise-4.16

#89418 OBSDOCS-1733: Logging 6.1.3 release notes
  modules/log6x-6-1-3-rn.adoc
  observability/logging/logging-6.1/log6x-release-notes-6.1.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference

#89326 OCPBUGS-27077:updates routingViaHost limitations
  modules/nw-operator-cr.adoc
Labels: peer-review-done, size/XS, jira/severity-critical, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference

#89299 RHDEVDOCS-6383 - fixed example file
  modules/ob-creating-a-s2i-build.adoc
Labels: peer-review-done, size/XS, ok-to-test

#89536 OSDOCS#13461: Update z-stream RNs for 4.17.19
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17

#89436 DIAGRAMS-500-17
  images/527-OpenShift-UDN-isolation-012025.png
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.17

#88975 CNV-47160: UDN support on public clouds
  _topic_maps/_topic_map_rosa.yml
  modules/virt-about-services.adoc
  modules/virt-networking-glossary.adoc
  virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc
  virt/vm_networking/virt-networking-overview.adoc
Labels: peer-review-done, lgtm, size/M, CNV, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#88722 [OSDOCS-12833]Allow specification of az zones for new/secondary machine pools
  modules/sdpolicy-am-gcp-compute-types.adoc
  osd_cluster_admin/osd_nodes/osd-nodes-machinepools-about.adoc
  osd_whats_new/osd-whats-new.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.18, branch/enterprise-4.19

#89646 DIAGRAMS-500
  modules/nw-cudn-about.adoc
  modules/nw-udn-about.adoc
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
Labels: size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89164 OSSM-8952: Cluster-wide migration using the istio revision label
  migrating/cluster-wide/ossm-migrating-cluster-wide-assembly.adoc
  modules/ossm-migrating-a-cluster-wide-deployment-using-the-istio-revision-label.adoc
  modules/ossm-migrating-workloads-using-the-istio-revision-label.adoc
Labels: peer-review-done, size/L, service-mesh, jira/valid-reference

#89564 OSDOCS-13462: 4.16.37 RN
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#89622 OSSM-9007 Update link to migration content
  install/ossm-installing-openshift-service-mesh.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#89642 CNV-57546: Add a release note for vTPM RWO support
  virt/release_notes/virt-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference

#89619 OCPBUGS:44488 Fix API version changed in error
  modules/nodes-clusters-cgroups-2.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89656 OCPBUGS-50010: Fix Azure Marketplace module title reference
  machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure.adoc
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-azure.adoc
  modules/machineset-yaml-azure.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89685 [enterprise-4.14] OCPBUGS-50010: Fix Azure Marketplace module title reference
  machine_management/creating-infrastructure-machinesets.adoc
  machine_management/creating_machinesets/creating-machineset-azure.adoc
  modules/machineset-yaml-azure.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference

#88035 OSDOCS#12887: adding external platform
  modules/understanding-agent-install.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89647 [enterprise-4.18] TELCODOCS-1840 siteConfigError created to surface more info on error …
  modules/ztp-troubleshooting-ztp-gitops-installation-crs.adoc
Labels: size/S, merge-review-in-progress

#89600 Update monitoring-creating-cross-project-alerting-rules-for-user-defi…
  modules/monitoring-creating-cross-project-alerting-rules-for-user-defined-projects.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89699 [enterprise-4.17] OCPBUGS#51001: Update disconnected mirroring steps for HCP
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-bm.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  modules/hcp-dc-image-mirror.adoc
Labels: branch/enterprise-4.17

#89592 OCPBUGS#52185: Add unique value for topology.kubernetes.io/zone in HCP
  modules/hcp-bm-prereqs.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89657 OBSDOCS-1733: Logging 6.1.3 release notes-fix
  modules/log6x-6-1-3-rn.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18

#89414 OBSDOCS-1735: Logging 5.9.12 release notes
  modules/logging-release-notes-5-9-12.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16

#89519 change disk.enableUUID to TRUE
  modules/rhel-compute-requirements.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89413 OBSDOCS-1736: Logging 5.8.18 release notes
  modules/logging-release-notes-5-8-18.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, size/S, do-not-merge/hold, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15

#89176 OBSDOCS-1730: Port Configuring the logging collector to 5.8 and 6.y docs
  _topic_maps/_topic_map.yml
  modules/log-collector-http-server.adoc
  modules/log-collector-rsyslog-server.adoc
  modules/log6x-cluster-logging-collector-limits.adoc
  modules/log6x-configuring-logging-collector.adoc
  modules/log6x-creating-logfilesmetricexporter.adoc
  modules/log6x-log-collector-http-server.adoc
  modules/log6x-log-collector-syslog-server.adoc
  observability/logging/logging-6.0/6x-cluster-logging-collector-6.0.adoc
  observability/logging/logging-6.1/6x-cluster-logging-collector-6.1.adoc
  observability/logging/logging-6.2/6x-cluster-logging-collector-6.2.adoc
  observability/logging/logging_release_notes/cluster-logging-collector.adoc
  snippets/logging-http-sys-input-support.adoc
Labels: peer-review-done, size/XL, jira/valid-reference

#89716 [enterprise-4.15] TELCODOCS-1840 416 siteConfigError created to surface more info on er…
  modules/ztp-troubleshooting-ztp-gitops-installation-crs.adoc
Labels: size/S, merge-review-in-progress

#89568 TELCODOCS-2197: Add support for user defined tolerations to modules
  hardware_enablement/kmm-kernel-module-management.adoc
  modules/kmm-applying-tolerations-to-kernel-module-pods.adoc
  modules/kmm-using-tolerations-for-kernel-module-scheduling.adoc
Labels: peer-review-done, size/M, telco, jira/valid-reference

#89719 No#jira: Add header for table
  modules/hosted-control-planes-monitoring-dashboard.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89570 OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89407 OBSDOCS-1640: Document HTTP output proxy should be configurable
  modules/log6x-cluster-logging-collector-log-forward-syslog.adoc
  modules/log6x-logging-http-forward-6-2.adoc
  observability/logging/logging-6.2/log6x-clf-6.2.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#89537 OSDOCS-13541: Documented the 4.18.3 z-stream release
  release_notes/ocp-4-18-release-notes.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.18

#89743 [enterprise-4.13] OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M

#89745 [enterprise-4.16] OCPBUGS:33455 Configuration in CRI-O is deprecated Manual cherrypick of #89570
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M

#89746 [enterprise-4.15] OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M, branch/enterprise-4.15

#89747 [enterprise-4.17] OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M, branch/enterprise-4.17

#89744 [enterprise-4.14] OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M, branch/enterprise-4.14

#89742 [enterprise-4.12] OCPBUGS:33455 Configuration in CRI-O is deprecated in favor of the configuration in the KubeletConfig
  modules/create-a-containerruntimeconfig-crd.adoc
  modules/create-a-kubeletconfig-crd-to-edit-kubelet-parameters.adoc
Labels: size/M, branch/enterprise-4.12

#89706 OSSM-9014 Replace sailoperator.io/v1alpha1 with sailoperator.io/v1
  modules/ossm-installing-multi-primary-multi-network-mesh.adoc
  modules/ossm-migrating-a-cluster-wide-deployment-using-the-istio-revision-label.adoc
  modules/ossm-running-v2-v3-multitenant-deployment-model.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#89067 OSDOCS-13414#Fix docs for non-graceful node shutdown
  _topic_maps/_topic_map.yml
  modules/persistent-storage-csi-vol-detach-non-graceful-shutdown-procedure.adoc
  storage/persistent-storage-csi-vol-detach-non-graceful-shutdown.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89658 OSDOCS-4486: add Azure AZ warning in MAPI compute spec
  modules/machineset-yaml-azure.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#88047 ROX-22488: Update recommended resource requirements for ACS
  modules/recommended-requirements-central-services.adoc
  modules/recommended-requirements-secured-cluster-services.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#89282 OCPBUGS#49922: Deleted pod examples from nmstate-deploying-nmstate-CL…
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#88033 OSDOCS#12864: node adding procedure enhancements
  nodes/nodes/nodes-nodes-adding-node-iso.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89784 Revert "ROX-22488: Update recommended resource requirements for ACS"
  modules/recommended-requirements-central-services.adoc
  modules/recommended-requirements-secured-cluster-services.adoc
Labels: size/M, jira/valid-reference

#89783 [enterprise-4.17] OCPBUGS#49922: Deleted pod examples from nmstate-deploying-nmstate-CL…
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
Labels: size/S, branch/enterprise-4.17

#89785 [enterprise-4.16] OCPBUGS#49922: Deleted pod examples from nmstate-deploying-nmstate-CL…
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
Labels: size/S, branch/enterprise-4.16

#89796 OSSM-9013 Fix minor issues in Updating OpenShift Service Mesh
  modules/ossm-performing-inplace-update.adoc
  modules/ossm-performing-revisionbased-update.adoc
  modules/ossm-select-revisionbased-strategy.adoc
Labels: peer-review-done, lgtm, size/S

#89792 OBSDOCS-1730: Port the "Configuring the logging collector" chapter to…
  _topic_maps/_topic_map.yml
  modules/log-collector-http-server.adoc
  modules/log-collector-rsyslog-server.adoc
  modules/log6x-cluster-logging-collector-limits.adoc
  modules/log6x-configuring-logging-collector.adoc
  modules/log6x-creating-logfilesmetricexporter.adoc
  modules/log6x-log-collector-http-server.adoc
  modules/log6x-log-collector-syslog-server.adoc
  observability/logging/logging-6.0/6x-cluster-logging-collector-6.0.adoc
  observability/logging/logging-6.1/6x-cluster-logging-collector-6.1.adoc
  observability/logging/logging-6.2/6x-cluster-logging-collector-6.2.adoc
  observability/logging/logging_release_notes/cluster-logging-collector.adoc
  snippets/logging-http-sys-input-support.adoc
Labels: size/XL, merge-review-in-progress, jira/valid-reference

#89793 [enterprise-4.16] OCPBUGS:35825 Chronyd examples for nodeDisruptionPolicy are wrong/example of node disruption policy is incorrect/Missing metadata in one of the Node Disruption Policy examples
  modules/machine-config-node-disruption-config.adoc
  modules/machine-config-node-disruption-example.adoc
Labels: size/S, branch/enterprise-4.16

#89749 OSSM-9016 Premigration Checklist find your deployment model needs a *Note*
  migrating/checklists/ossm-migrating-premigration-checklists-assembly.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#89195 OSSM-8849 New Features
  modules/ossm-release-notes-3-0-deprecated-removed-features.adoc
  modules/ossm-release-notes-3-0-new-features.adoc
  modules/snippets
  ossm-release-notes/ossm-release-notes-assembly.adoc
  ossm-release-notes/snippets/deprecated-feature.adoc
  ossm-release-notes/snippets/developer-preview.adoc
  ossm-release-notes/snippets/ossm-out-of-support.adoc
  ossm-release-notes/snippets/technology-preview.adoc
Labels: peer-review-done, size/L, merge-review-in-progress

#89797 OSSM-9017 In the migrating gateways there is a errata in a command
  modules/ossm-migrating-gateways-canary.adoc
  modules/ossm-migrating-gateways-in-place.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#89638 OCPBUGS:45742 Incorrect channel setting for installing the Cluster Resource Override Operator using the CLI
  modules/nodes-cluster-resource-override-deploy-cli.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89810 [service-mesh-docs-3.0] OSSM-8849 New Features
  modules/ossm-release-notes-3-0-deprecated-removed-features.adoc
  modules/ossm-release-notes-3-0-new-features.adoc
  modules/snippets
  ossm-release-notes/ossm-release-notes-assembly.adoc
  ossm-release-notes/snippets/deprecated-feature.adoc
  ossm-release-notes/snippets/developer-preview.adoc
  ossm-release-notes/snippets/ossm-out-of-support.adoc
  ossm-release-notes/snippets/technology-preview.adoc
Labels: size/L

#89822 [enterprise-4.14] OCPBUGS:45742 Incorrect channel setting for installing the Cluster Resource Override Operator using the CLI
  modules/nodes-cluster-resource-override-deploy-cli.adoc
Labels: size/XS, branch/enterprise-4.12

#89626 OCPBUGS 51385: Updated the supported versions for cert-manager section
  modules/cert-manager-supported-versions.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89112 OADP-5658 Release Notes for OADP 1.3.6
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-6.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, OADP

#89142 4.12: OADP-5658 Release Notes for OADP 1.3.6
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-6.adoc
Labels: size/S

#89136 4.13: OADP-5658 Release Notes for OADP 1.3.6
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-6.adoc
Labels: size/S

#89114 4.14: OADP-5658 Release Notes for OADP 1.3.6
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-release-notes-1-3.adoc
  modules/oadp-release-notes-1-3-6.adoc
Labels: size/S

#89561 OSSM-9000: Create a default revision tag and relabel namespace
  migrating/cluster-wide/ossm-migrating-cluster-wide-assembly.adoc
  modules/ossm-creating-a-default-revision-tag-and-relabeling-the-namespaces.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#89786 [enterprise-4.15] OCPBUGS#49922: Deleted pod examples from nmstate-deploying-nmstate-CL…
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
Labels: size/S, branch/enterprise-4.15

#89787 [enterprise-4.14]OCPBUGS-49922: Deleted pod examples from nmstate-deploying-nmstate-CL…
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#89717 OCPBUGS-44288-14: Updated the cidr-range-definitions.adoc file
  networking/cidr-range-definitions.adoc
Labels: lgtm, size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#89325 OCPBUGS-44288-earlier: Updated the cidr-range-definitions.adoc file
  networking/cidr-range-definitions.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#85599 OCPBUGS#44288: Updated the cidr-range-definitions.adoc file
  networking/cidr-range-definitions.adoc
  networking/ovn_kubernetes_network_provider/configure-ovn-kubernetes-subnets.adoc
Labels: peer-review-done, lgtm, size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89513 Content creation for respectRBAC operator
  declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc
  modules/gitops-configuring-respect-rbac-using-gitops.adoc
Labels: size/L

#89059 OCPBUGS-50848 Section IP address assignment for additional networks missing from docs after reorg
  modules/nw-multus-ipam-object.adoc
  networking/multiple_networks/secondary_networks/configuring-ip-secondary-nwt.adoc
Labels: peer-review-done, size/S, merge-review-needed

#89673 OCPBUGS:39408 Custom Metrics Autoscaler Cron trigger missing from supported trigger list
  nodes/cma/nodes-cma-autoscaling-custom-trigger.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89551 OCPBUGS:42836 On-cluster layering uses example uses package not in RHEL
  modules/coreos-layering-configuring-on.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.16, branch/enterprise-4.17

#89324 OSSM-8958: Cluster-wide migration using istio injection label
  migrating/cluster-wide/ossm-migrating-cluster-wide-assembly.adoc
  modules/ossm-migrating-a-cluster-wide-deployment-using-the-istio-injection-label.adoc
  modules/ossm-migrating-workloads-using-the-istio-injection-label.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#89858 [enterprise-4.12] OCPBUGS:39347 Consider removing references to old versions
  modules/rhcos-enabling-multipath-day-2.adoc
Labels: size/XS, branch/enterprise-4.12

#89857 fix command typo from related review
  modules/capi-modifying-machine-template.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89862 [enterprise-4.14] OCPBUGS:39347 Consider removing references to old versions
  modules/rhcos-enabling-multipath-day-2.adoc
Labels: size/XS, branch/enterprise-4.14

#89824 OSSM-9022 Fix Command in Uninstalling OpenShift Service Mesh
  modules/ossm-uninstalling-service-mesh-operator-control-plane-cli.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#89864 [enterprise-4.15] OCPBUGS:39347 Consider removing references to old versions
  modules/rhcos-enabling-multipath-day-2.adoc
Labels: size/XS

#88981 OSSM-8490 Adds service-mesh-docs-3.0
  _distro_map.yml
Labels: size/XS, service-mesh, merge-review-in-progress, merge-review-needed

#89879 osdocs-13599 added admonition for Egress IPs on HCP clusters
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#89235 OCPBUGS#38094: Correcting the image name for cluster node tuning operator
  modules/cnf-configuring-power-saving-for-nodes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89874 OSSM-9025: Update YAML example in multitenant migration with cert-manager
  modules/ossm-migrating-multitenant-with-cert-manager.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#89837 OSSM-8991: Verify installation for OSSM 3 in doc
  install/ossm-enabling-mtls.adoc
  modules/ossm-accessing-bookinfo-application-using-gateway-api.adoc
  modules/ossm-accessing-bookinfo-application-using-istio-gateway-injection.adoc
  modules/ossm-cert-manager-installing-istio-resource.adoc
  modules/ossm-cert-manager-istio-csr-revisionbased-strategy.adoc
  modules/ossm-cert-manager-update-istio-csr-revisionbased-only.adoc
  modules/ossm-config-otel.adoc
  modules/ossm-deploy-application-workloads-in-each-mesh.adoc
  modules/ossm-deploying-bookinfo-application.adoc
  modules/ossm-enabling-sidecar-injection.adoc
  modules/ossm-installing-multi-primary-multi-network-mesh.adoc
  modules/ossm-installing-primary-remote-multi-network-mesh.adoc
Labels: peer-review-done, size/M, dev-tools, jira/valid-reference

#89863 OSSM-9024 Additional issues in Updating OpenShift Service Mesh
  modules/ossm-about-revisionbased-strategy.adoc
  modules/ossm-attach-workloads-to-control-plane.adoc
  modules/ossm-performing-inplace-update.adoc
  modules/ossm-performing-revisionbased-update.adoc
  modules/ossm-select-revisionbased-strategy.adoc
Labels: peer-review-done, size/S, service-mesh, merge-review-in-progress, merge-review-needed

#89161 OCPBUGS50980 Need to make changes in the garbage collection documentation
  modules/nodes-nodes-garbage-collection-configuring.adoc
  modules/nodes-nodes-garbage-collection-images.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89877 CNV-57710: Add a missing note to Release Notes
  virt/release_notes/virt-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18

#89788 TELCODOCS-2221-RN: KMM 2.3 release notes.
  _topic_maps/_topic_map.yml
  hardware_enablement/kmm-release-notes.adoc
  hardware_enablement/release-notes/_attributes
Labels: peer-review-done, size/M, telco, merge-review-needed, branch/enterprise-4.18, branch/enterprise-4.19

#89803 OSDOCS-13465: Bringing OCP audit logging for network security doc into ROSA
  _topic_maps/_topic_map_rosa.yml
  networking/network_security/logging-network-security.adoc
Labels: size/XS, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#89902 OSSM-9029 Wrong indent on Istio resource in multitenant with cert manager migration
  modules/ossm-migrating-multitenant-with-cert-manager.adoc
Labels: peer-review-done, size/XS, service-mesh, merge-review-in-progress, merge-review-needed

#89910 OSSM-9028 update some command in observability doc
  modules/ossm-config-openshift-monitoring-kiali.adoc
  modules/ossm-config-otel.adoc
Labels: peer-review-done, size/S

#89624 OSDOCS-13445-2: adds fixes to Red Hat Device Edge page
  _attributes/common-attributes.adoc
  modules/about-rhde.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#89883 [enterprise-4.17] OCPBUGS-50848 Section IP address assignment for additional networks missing from docs after reorg
  modules/nw-multus-ipam-object.adoc
  networking/multiple_networks/secondary_networks/configuring-ip-secondary-nwt.adoc
Labels: size/S, merge-review-in-progress

#89923 OCPBUG 19873: Created Cri-O default capabilities section - redo
  modules/create-crio-default-capabilities.adoc
  post_installation_configuration/machine-configuration-tasks.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.13

#89111 [RHACS][Docs][4.7 and later versions] ROX-28197: Adding docs for ACS Dev Hub Integration
  _topic_maps/_topic_map.yml
  configuration/configuring-and-integrating-the-rhacs-plugin-with-red-hat-developer-hub.adoc
  modules/common-attributes.adoc
  modules/viewing-security-information-in-red-hat-developer-hub.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.7

#89929 Version change from 4.17 to 4.18 in navigation bar
  _topic_maps/_topic_map.yml
Labels: peer-review-done, size/XS

#89820 OSSM-9019 update some command in gateway doc
  modules/ossm-directing-egress-traffic-through-a-gateway-using-istio-apis.adoc
  modules/ossm-exposing-a-gateway-to-traffic-outside-the-cluster-using-openshift-routes.adoc
  modules/ossm-exposing-service-using-istio-gateway-and-virtualservice.adoc
Labels: peer-review-done, size/M, merge-review-in-progress

#89882 OSSM-9027 Add xrefs to Gateway migration guide
  migrating/done/ossm-migrating-complete-assembly.adoc
  migrating/migrating-gateways/ossm-migrating-gateways-assembly.adoc
Labels: peer-review-done, size/S

#86437 OSDOCS-8677-SRIOV-1: First ContentX PR for reorg of SR-IOV
  _topic_maps/_topic_map.yml
  installing/installing_openstack/installing-openstack-nfv-preparing.adoc
  modules/cnf-assigning-a-sriov-network-to-a-vrf.adoc
  modules/cnf-creating-an-additional-sriov-network-with-vrf-plug-in.adoc
  modules/nw-multus-add-pod.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-openstack-sr-iov-testpmd-pod.adoc
  modules/nw-sr-iov-network-node-configuration-examples.adoc
  modules/nw-sriov-configuring-operator.adoc
  modules/nw-sriov-expose-mtu.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/nw-sriov-runtime-config-ethernet.adoc
  modules/nw-sriov-runtime-config-sriov-ib.adoc
  modules/nw-sriov-topology-manager.adoc
  networking/hardware_networks/about-sriov.adoc
  networking/hardware_networks/add-pod.adoc
  networking/hardware_networks/configuring-sriov-device.adoc
  networking/hardware_networks/configuring-sriov-ib-attach.adoc
  networking/hardware_networks/configuring-sriov-net-attach.adoc
  networking/hardware_networks/using-dpdk-and-rdma.adoc
  networking/networking_operators/sr-iov-operator/configuring-sriov-operator.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89959 Removing 'custom resources?' from Vale accept list
  .vale/styles/config/vocabularies/OpenShiftDocs/accept.txt
Labels: peer-review-done, lgtm, size/XS

#89859 OBSDOCS-1755: Need to remove additional nodeSelector and tolerations from Lokistack CR
  modules/log6x-loki-pod-placement.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89886 ROX-22488: Update recommended resource requirements for ACS 2
  modules/recommended-requirements-central-services.adoc
  modules/recommended-requirements-secured-cluster-services.adoc
Labels: lgtm, size/M, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#89530 [OSDOCS-13538]Change TOC order of GCP and AWS cluster creation in OSD docs
  _topic_maps/_topic_map_osd.yml
Labels: peer-review-done, lgtm, size/XS, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19
