Repository openshift/openshift-docs, pull requests merged in 2025-09, with the labels that each got.

#98320 OBSDOCS-2366 migrate admin, developer perspective changes
  about/cluster-observability-operator-overview.adoc
  installing/installing-the-cluster-observability-operator.adoc
  modules/coo-advantages.adoc
  modules/coo-dashboard-ui-plugin-configure.adoc
  modules/coo-dashboard-ui-plugin-install.adoc
  modules/coo-distributed-tracing-ui-plugin-install.adoc
  modules/coo-distributed-tracing-ui-plugin-using.adoc
  modules/coo-incident-detection-using.adoc
  modules/coo-logging-ui-plugin-install.adoc
  modules/coo-monitoring-ui-plugin-install.adoc
  modules/coo-target-users.adoc
  modules/coo-troubleshooting-ui-plugin-install.adoc
  modules/coo-troubleshooting-ui-plugin-using.adoc
  modules/coo-versus-default-ocp-monitoring.adoc
  modules/monitoring-installing-cluster-observability-operator-using-the-web-console.adoc
  modules/monitoring-uninstalling-cluster-observability-operator-using-the-web-console.adoc
  release-notes/cluster-observability-operator-release-notes.adoc
  snippets/unified-perspective-web-console.adoc
  ui_plugins/dashboard-ui-plugin.adoc
  ui_plugins/distributed-tracing-ui-plugin.adoc
  ui_plugins/logging-ui-plugin.adoc
  ui_plugins/monitoring-ui-plugin.adoc
  ui_plugins/observability-ui-plugins-overview.adoc
  ui_plugins/troubleshooting-ui-plugin.adoc
Labels: size/L

#98328 Move 4.15 monitoring RNs to standalone
  modules/monitoring-4-15-release-notes.adoc
  modules/monitoring-4-20-release-notes.adoc
  release-notes/monitoring-release-notes.adoc
Labels: size/L

#98272 [enterprise-4.14] OCPBUGS-60660-15: Added proxy attribute to the Insights Operator configu
  modules/insights-operator-configuring.adoc
Labels: size/M, branch/enterprise-4.14

#96701 TELCODOCS-2273 - Remove Tech Preview Notifications
  modules/nw-metallb-bgppeer-cr.adoc
  modules/nw-metallb-example-bgppeer.adoc
  modules/nw-metallb-frr-k8s-configuration-crd.adoc
Labels: lgtm, size/S, branch/enterprise-4.20

#97318 TELCODOCS-2430 - Correcting PTP event notification examples
  modules/cnf-fast-event-notifications-api-reference-v2.adoc
Labels: lgtm, size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98351 Fixes the broken HCP build.
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
Labels: lgtm, size/XS, branch/enterprise-4.19, branch/enterprise-4.20

#98355 CP413-OSDOCS-15449: manual backport CQA
  installing/disconnected_install/index.adoc
  modules/installing-mirroring-disconnected-con.adoc
Labels: size/S, jira/valid-reference

#98371 [enterprise-4.15] OSDOCS-15972 [NETOBSERV] Module Aditi tool results: AuthorLine
  modules/network-observability-SRIOV-configuration.adoc
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-cli-capturing-packets.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-netobserv-cli-install.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-virtualization-configuration.adoc
  observability/network_observability/network-observability-release-notes-1-9-2.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#98370 [enterprise-4.14] OSDOCS-15972 [NETOBSERV] Module Aditi tool results: AuthorLine
  modules/network-observability-SRIOV-configuration.adoc
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-cli-capturing-packets.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-netobserv-cli-install.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-virtualization-configuration.adoc
  observability/network_observability/network-observability-release-notes-1-9-2.adoc
Labels: size/M

#98281 [enterprise-4.20] Add release note for BGP routing
  release_notes/ocp-4-20-release-notes.adoc
Labels: size/M, branch/enterprise-4.20

#98376 [enterprise-4-18] OSDOCS-15972 [NETOBSERV] Module Aditi tool results: AuthorLine
  _topic_maps/_topic_map.yml
  modules/network-observability-SRIOV-configuration.adoc
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-cli-capturing-packets.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-netobserv-cli-install.adoc
  modules/network-observability-networking-events-overview.adoc
  modules/network-observability-operator-release-notes-1-9-2-advisory.adoc
  modules/network-observability-release-notes-1-9-2-bug-fixes.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-viewing-network-events.adoc
  modules/network-observability-virtualization-configuration.adoc
  observability/network_observability/network-observability-release-notes-1-9-2.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#98374 [enterprise-4.17] OSDOCS-15972 [NETOBSERV] Module Aditi tool results: AuthorLine
  modules/network-observability-SRIOV-configuration.adoc
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-cli-capturing-packets.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-netobserv-cli-install.adoc
  modules/network-observability-networking-events-overview.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-viewing-network-events.adoc
  modules/network-observability-virtualization-configuration.adoc
  observability/network_observability/network-observability-release-notes-1-9-2.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#98373 [enterprise-4.16] OSDOCS-15972 [NETOBSERV] Module Aditi tool results: AuthorLine
  modules/network-observability-SRIOV-configuration.adoc
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-cli-capturing-packets.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-netobserv-cli-install.adoc
  modules/network-observability-roles-create.adoc
  modules/network-observability-virtualization-configuration.adoc
  observability/network_observability/network-observability-release-notes-1-9-2.adoc
Labels: size/M, merge-review-in-progress, merge-review-needed

#97897 OCPBUGS-59924: Added disk wipe note to Removing a cluster that uses i…
  installing/installing_openstack/uninstalling-cluster-openstack.adoc
  modules/installation-uninstall-clouds.adoc
Labels: size/M, jira/severity-moderate, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96779 OSDOCS-15577#combining AWS assemblies
  _topic_maps/_topic_map.yml
  installing/installing_aws/installing-aws-account.adoc
  installing/installing_aws/ipi/installing-aws-customizations.adoc
  installing/installing_aws/preparing-to-install-on-aws.adoc
  installing/overview/installing-preparing.adoc
  modules/cco-ccoctl-configuring.adoc
  modules/cco-ccoctl-creating-at-once.adoc
  modules/cco-ccoctl-creating-individually.adoc
  modules/cco-ccoctl-install-creating-manifests.adoc
  modules/cli-installing-cli.adoc
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/cluster-telemetry.adoc
  modules/configuring-hybrid-ovnkubernetes.adoc
  modules/installation-aws-arm-tested-machine-types.adoc
  modules/installation-aws-tested-machine-types.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-initializing.adoc
  modules/installation-launching-installer.adoc
  networking/ingress_load_balancing/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws.adoc
  networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.adoc
  post_installation_configuration/cluster-tasks.adoc
  scalability_and_performance/optimization/optimizing-networking.adoc
Labels: size/L, merge-review-in-progress, branch/enterprise-4.20

#98393 OSDOCS-15585-v2: deletes unused modules MicroShift
  modules/microshift-adding-containers-to-blueprint.adoc
  modules/microshift-config-cli-manifests.adoc
  modules/microshift-exposed-audit-ports.adoc
  modules/microshift-ki-cni-iptables-deleted.adoc
  modules/microshift-nodeport-unreachable-workaround.adoc
  modules/microshift-troubleshooting-nodeport.adoc
Labels: size/L, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98004 OSDOCS-14500: Prune "Tutorials"
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  cloud_experts_tutorials/cloud-experts-aws-load-balancer-operator.adoc
  cloud_experts_tutorials/cloud-experts-aws-secret-manager.adoc
  cloud_experts_tutorials/cloud-experts-consistent-egress-ip.adoc
  cloud_experts_tutorials/cloud-experts-custom-dns-resolver.adoc
  cloud_experts_tutorials/cloud-experts-deploy-api-data-protection.adoc
  cloud_experts_tutorials/cloud-experts-dynamic-certificate-custom-domain.adoc
  cloud_experts_tutorials/cloud-experts-entra-id-idp.adoc
  cloud_experts_tutorials/cloud-experts-external-dns.adoc
  cloud_experts_tutorials/cloud-experts-rosa-hcp-activation-and-account-linking-tutorial.adoc
  cloud_experts_tutorials/cloud-experts-rosa-with-hcp-private-offer-acceptance-and-sharing.adoc
  cloud_experts_tutorials/cloud-experts-template-tutorial.adoc
  cloud_experts_tutorials/cloud-experts-update-component-routes.adoc
  cloud_experts_tutorials/cloud-experts-using-alb-and-waf.adoc
  cloud_experts_tutorials/cloud-experts-using-aws-ack.adoc
  cloud_experts_tutorials/cloud-experts-using-cloudfront-and-waf.adoc
  cloud_experts_tutorials/rosa-mobb-cli-quickstart.adoc
  cloud_experts_tutorials/rosa-mobb-prerequisites-tutorial.adoc
  cloud_experts_tutorials/rosa-mobb-verify-permissions-sts-deployment.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#98423 Add monitoring 4.17 RNs to standalone
  modules/monitoring-4-17-release-notes.adoc
  modules/monitoring-4-20-release-notes.adoc
  release-notes/monitoring-release-notes.adoc
Labels: size/L

#97999 Adds limitation to UDN docs
  modules/nw-udn-limitations.adoc
Labels: size/XS, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96925 TELCODOCS-2259: Add TP support for ARM dual-port OC
  modules/nw-ptp-configuring-linuxptp-services-dual-port-oc.adoc
  modules/ptp-dual-ports-oc.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.20

#96071 Adding Power11 to the Supported Architectures of OCP 4.19
  modules/minimum-ibm-power-system-requirements.adoc
Labels: lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.19

#96719 Update mco-update-boot-images-configuring.adoc to add correct label with "=" instead of ":"
  modules/mco-update-boot-images-configuring.adoc
Labels: lgtm, size/XS, ok-to-test, merge-review-in-progress, branch/enterprise-4.19, branch/enterprise-4.20

#98449 OBSDOCS-2372 fixes for issus found in review
  _attributes/common-attributes.adoc
Labels: size/XS

#98287 CNV-62387-62385: RN DPDK checkup and NIC hot plug/unplug
  virt/release_notes/virt-4-20-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.20

#98458 [OSDOCS-15125]: Clarifying DNS prereq
  modules/hcp-virt-prereqs.adoc
Labels: lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98476 [OSDOCS-14504]Prune "Registry"
  modules/pruning-images.adoc
Labels: size/XS, branch/enterprise-4.19, branch/enterprise-4.20

#98223 DITA fixes for OADP troubleshooting
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/restoring-workarounds-for-velero-backups-that-use-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/velero-cli-tool.adoc
  modules/avoiding-the-velero-plugin-panic-error.adoc
  modules/migration-debugging-velero-admission-webhooks-ibm-appconnect.adoc
  modules/migration-debugging-velero-admission-webhooks-knative.adoc
  modules/migration-debugging-velero-resources.adoc
  modules/oadp-creating-alerting-rule.adoc
  modules/oadp-creating-service-monitor.adoc
  modules/oadp-csi-snapshot-timeouts.adoc
  modules/oadp-datamover-timeouts.adoc
  modules/oadp-debugging-oc-cli.adoc
  modules/oadp-item-backup-timeouts.adoc
  modules/oadp-item-restore-timeouts.adoc
  modules/oadp-list-of-metrics.adoc
  modules/oadp-monitoring-setup.adoc
  modules/oadp-pod-crash-set-resource-request-restic.adoc
  modules/oadp-pod-crash-set-resource-request-velero.adoc
  modules/oadp-restic-restore-failing-psa-policy.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-velero-default-timeouts.adoc
  modules/oadp-velero-timeouts.adoc
  modules/oadp-viewing-metrics-ui.adoc
  modules/resolving-backup-storage-contains-invalid-directories-issue.adoc
  modules/resolving-incorrect-aws-credentials-issue.adoc
  modules/resolving-oadp-operator-fails-silently-issue.adoc
  modules/restic-backup-cr-cannot-be-recreated-after-bucket-is-emptied.adoc
  modules/restic-permission-error-for-nfs-data-volumes-with-root-squash-enabled.adoc
  modules/setting-resource-requests-for-a-nodeagent-pod.adoc
  modules/troubleshooting-backup-cr-cannot-retrieve-volume-issue.adoc
  modules/troubleshooting-backup-cr-status-remains-in-partiallyfailed-issue.adoc
  modules/troubleshooting-backup-cr-status-remains-in-progress-issue.adoc
  modules/using-must-gather.adoc
  modules/velero-oadp-version-relationship.adoc
  modules/velero-obtaining-by-accessing-binary.adoc
  modules/velero-obtaining-by-downloading.adoc
  modules/workaround-for-openshift-adp-controller-segmentation-fault.adoc
Labels: size/L, OADP, branch/enterprise-4.19, branch/enterprise-4.20

#98246 Dita vale fixes for OADP API
  backup_and_restore/application_backup_and_restore/oadp-api.adoc
  modules/applicationconfig-type.adoc
  modules/backuplocation-type.adoc
  modules/customplugin-type.adoc
  modules/datamover-type.adoc
  modules/dataprotectionapplicationspec-type.adoc
  modules/features-type.adoc
  modules/podconfig-type.adoc
  modules/resticconfig-type.adoc
  modules/snapshotlocation-type.adoc
  modules/veleroconfig-type.adoc
Labels: size/S, OADP, branch/enterprise-4.19, branch/enterprise-4.20

#97613 Telcodocs 2270: topology-aware scheduler: HA by default
  modules/cnf-customizing-schedulder-ha-nro.adoc
  modules/cnf-disabling-schedulder-ha-nro.adoc
  modules/cnf-managing-ha-nrop-scheduler.adoc
  modules/cnf-verifying-schedulder-ha-status.adoc
  scalability_and_performance/cnf-numa-aware-scheduling.adoc
Labels: size/L, branch/enterprise-4.20

#95399 OSDOCS-15110 incorporated edits
  _topic_maps/_topic_map.yml
  modules/zero-trust-manager-about-agent.adoc
  modules/zero-trust-manager-about-attestation.adoc
  modules/zero-trust-manager-about-components.adoc
  modules/zero-trust-manager-about-features.adoc
  modules/zero-trust-manager-about-spire.adoc
  modules/zero-trust-manager-enable-metrics-agent.adoc
  modules/zero-trust-manager-enable-metrics-server.adoc
  modules/zero-trust-manager-how-it-works.adoc
  modules/zero-trust-manager-install-cli.adoc
  modules/zero-trust-manager-install-console.adoc
  modules/zero-trust-manager-oidc-config.adoc
  modules/zero-trust-manager-query-metrics.adoc
  modules/zero-trust-manager-spiffe-csidriver-config.adoc
  modules/zero-trust-manager-spire-agent-config.adoc
  modules/zero-trust-manager-spire-server-config.adoc
  modules/zero-trust-manager-uninstall-console.adoc
  modules/zero-trust-manager-uninstall-resources.adoc
  security/zero_trust_workload_identity_manager/zero-trust-manager-configuration.adoc
  security/zero_trust_workload_identity_manager/zero-trust-manager-overview.adoc
  security/zero_trust_workload_identity_manager/zero-trust-manager-release-notes.adoc
Labels: peer-review-done, size/L, ok-to-merge, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#91162 Telcodocs 2124: Ensure NUMA Resources Operator Works on HyperShift Hosted Clusters
  modules/cnf-configuring-kubelet-nro.adoc
  modules/cnf-creating-nrop-cr-hosted-control-plane.adoc
  modules/cnf-deploying-the-numa-aware-scheduler.adoc
  modules/cnf-sample-single-numa-policy-from-pp.adoc
  scalability_and_performance/cnf-numa-aware-scheduling.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19, branch/enterprise-4.20

#98462 [OSDOCS-15308]: Fixing incorrect command in etcd docs
  modules/restore-identify-unhealthy-etcd-member.adoc
Labels: lgtm, size/XS, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98323 OCPBUGS-58134: Added datastore to table 2.4 in vSphere docs
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: lgtm, size/M, ok-to-merge, jira/severity-low, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98532 [enterprise-4.18] OCPBUGS-58134: Added datastore to table 2.4 in vSphere docs
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: size/M, jira/severity-low, jira/invalid-bug, jira/valid-reference

#98533 [enterprise-4.17] OCPBUGS-58134: Added datastore to table 2.4 in vSphere docs
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: size/M, jira/severity-low, jira/invalid-bug, jira/valid-reference

#98349 OSDOCS-14643: adds 4.16.47 relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: size/XS, ok-to-merge, jira/valid-reference

#98372 CNV-67472: Clean up docs structure before adding new content
  modules/virt-about-cluster-checkup-framework.adoc
  modules/virt-checking-storage-configuration.adoc
  modules/virt-latency-checkup-web-console.adoc
  modules/virt-measuring-latency-vm-secondary-network.adoc
  snippets/virt-about-running-checkups.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: size/M, merge-review-in-progress, jira/valid-reference

#98396 OSDOCS-16028-1:Update the z-stream RNs for 4.18.23
  release_notes/ocp-4-18-release-notes.adoc
Labels: size/M, jira/valid-reference

#97852 OSDOCS-15910: Removes HCP install content from Classic distro
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  cloud_experts_tutorials/cloud-experts-custom-dns-resolver.adoc
  cloud_experts_tutorials/cloud-experts-rosa-hcp-activation-and-account-linking-tutorial.adoc
  modules/creating-cluster-with-aws-kms-key.adoc
  modules/rosa-additional-principals-create.adoc
  modules/rosa-additional-principals-edit.adoc
  modules/rosa-additional-principals-overview.adoc
  modules/rosa-deleting-account-wide-iam-roles-and-policies.adoc
  modules/rosa-deleting-sts-iam-resources-account-wide.adoc
  modules/rosa-getting-started-access-cluster-web-console.adoc
  modules/rosa-getting-started-deleting-a-cluster.adoc
  modules/rosa-getting-started-enable-rosa.adoc
  modules/rosa-getting-started-environment-setup.adoc
  modules/rosa-getting-started-grant-admin-privileges.adoc
  modules/rosa-getting-started-grant-user-access.adoc
  modules/rosa-getting-started-install-configure-cli-tools.adoc
  modules/rosa-getting-started-revoke-admin-privileges.adoc
  modules/rosa-getting-started-revoke-user-access.adoc
  modules/rosa-getting-started-revoking-admin-privileges-and-user-access.adoc
  modules/rosa-hcp-aws-private-create-cluster.adoc
  modules/rosa-hcp-aws-private-security-groups.adoc
  modules/rosa-hcp-create-network.adoc
  modules/rosa-hcp-creating-account-wide-sts-roles-and-policies.adoc
  modules/rosa-hcp-deleting-cluster.adoc
  modules/rosa-hcp-set-environment-variables.adoc
  modules/rosa-hcp-sts-accessing-a-break-glass-cred-cli.adoc
  modules/rosa-hcp-sts-creating-a-break-glass-cred-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli-no-cni-plugin.adoc
  modules/rosa-hcp-sts-creating-a-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-egress-lockdown-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-cluster-cli.adoc
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-provider-cli.adoc
  modules/rosa-hcp-sts-revoking-a-break-glass-cred-cli.adoc
  modules/rosa-hcp-vpc-manual.adoc
  modules/rosa-hcp-vpc-subnet-tagging.adoc
  modules/rosa-hcp-vpc-terraform.adoc
  modules/rosa-operator-config.adoc
  modules/rosa-sts-byo-oidc.adoc
  modules/rosa-sts-cluster-terraform-destroy.adoc
  modules/rosa-sts-cluster-terraform-execute.adoc
  modules/rosa-sts-creating-account-wide-sts-roles-and-policies.adoc
  modules/rosa-sts-terraform-considerations.adoc
  modules/rosa-sts-terraform-prerequisites.adoc
  modules/rosa-terraform-overview.adoc
  modules/rosa-unlinking-and-deleting-ocm-and-user-iam-roles.adoc
  rosa_architecture/rosa-oidc-overview.adoc
  rosa_hcp/rosa-hcp-aws-private-creating-cluster.adoc
  rosa_hcp/rosa-hcp-creating-cluster-with-aws-kms-key.adoc
  rosa_hcp/rosa-hcp-deleting-cluster.adoc
  rosa_hcp/rosa-hcp-egress-zero-install.adoc
  rosa_hcp/rosa-hcp-quickstart-guide.adoc
  rosa_hcp/rosa-hcp-shared-vpc-config.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.adoc
  rosa_release_notes/rosa-release-notes.adoc
  snippets/rosa-hcp-rn.adoc
  snippets/vpc-troubleshooting.adoc
Labels: size/XL, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#98534 [enterprise-4.16] OCPBUGS-58134: Added datastore to table 2.4 in vSphere docs
  modules/installation-vsphere-installer-infra-requirements.adoc
Labels: size/M, jira/severity-low, jira/invalid-bug, jira/valid-reference

#98570 [enterprise-4.19] CNV-67472: Clean up docs structure before adding new content
  modules/virt-about-cluster-checkup-framework.adoc
  modules/virt-checking-storage-configuration.adoc
  modules/virt-latency-checkup-web-console.adoc
  modules/virt-measuring-latency-vm-secondary-network.adoc
  snippets/virt-about-running-checkups.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: size/L, jira/valid-reference

#98571 [enterprise-4.17] CNV-67472: Clean up docs structure before adding new content
  modules/virt-about-cluster-checkup-framework.adoc
  modules/virt-checking-storage-configuration.adoc
  modules/virt-latency-checkup-web-console.adoc
  modules/virt-measuring-latency-vm-secondary-network.adoc
  snippets/virt-about-running-checkups.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: size/L, jira/valid-reference

#98574 [enterprise-4.14] CNV-67472: Clean up docs structure before adding new content
  modules/virt-about-cluster-checkup-framework.adoc
  modules/virt-measuring-latency-vm-secondary-network.adoc
  snippets/virt-about-running-checkups.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
Labels: size/M, jira/valid-reference

#98468 [OSDOCS-16012]: Adding namespace to etcd docs
  security/certificate_types_descriptions/etcd-certificates.adoc
Labels: size/XS, ok-to-merge, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98568 [enterprise-4.18] OSDOCS WMCO rework RN to make more version generic
  _topic_maps/_topic_map.yml
  modules/windows-containers-release-notes-10-18-0.adoc
  release_notes/addtl-release-notes.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/index.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-limitations.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-past.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-prereqs.adoc
  windows_containers/wmco_rn/windows-containers-release-notes.adoc
Labels: size/M

#96617 TELCODOCS-2081#Update network type from OpenShiftSDN to OVNKubernetes in Cluster Network Operator docs
  modules/nw-cno-view.adoc
Labels: lgtm, size/XS, branch/enterprise-4.13

#96407 TELCODOCS-2081#Update network type from OpenShiftSDN to OVNKubernetes in Cluster Network Operator docs
  modules/nw-cno-view.adoc
Labels: lgtm, size/XS

#98600 [enterprise-4.12] HCIDOCS-218: Static dual-stack bootstrap network configuration
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
Labels: size/S, jira/valid-reference

#98601 [enterprise-4.14] HCIDOCS-218: Static dual-stack bootstrap network configuration
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
Labels: size/S, jira/valid-reference

#98602 [enterprise-4.15] HCIDOCS-218: Static dual-stack bootstrap network configuration
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
Labels: size/S, jira/valid-reference

#98603 [enterprise-4.16] HCIDOCS-218: Static dual-stack bootstrap network configuration
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
Labels: size/S, jira/valid-reference

#98554 OSDOCS#16031: Update the z-stream RNs for 4.14.56
  release_notes/ocp-4-14-release-notes.adoc
Labels: size/S

#92589 Telcodocs 2124 RN Ensure NUMA Resources Operator Works on HyperShift Hosted Clusters
  release_notes/ocp-4-19-release-notes.adoc
Labels: lgtm, size/S, lifecycle/stale, branch/enterprise-4.19

#98575 [enterprise-4.19] OSDOCS WMCO rework RN to make more version generic
  _topic_maps/_topic_map.yml
  modules/windows-containers-release-notes-10-19-0.adoc
  release_notes/addtl-release-notes.adoc
  windows_containers/enabling-windows-container-workloads.adoc
  windows_containers/index.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-limitations.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-past.adoc
  windows_containers/wmco_rn/windows-containers-release-notes-prereqs.adoc
  windows_containers/wmco_rn/windows-containers-release-notes.adoc
Labels: size/M

#96337 OSDOCS 15419 CMA Automatically create KedaController during CMA Operator installation process
  modules/nodes-cma-autoscaling-custom-install.adoc
  modules/nodes-cma-autoscaling-keda-controller-edit.adoc
  modules/sd-nodes-cma-autoscaling-custom-install.adoc
  nodes/cma/nodes-cma-autoscaling-custom-install.adoc
Labels: size/L, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98256 OSDOCS-15754: adds concept module RHDE config
  microshift_configuring/microshift-using-config-yaml.adoc
  modules/microshift-config-rhde-con.adoc
  modules/microshift-config-yaml.adoc
Labels: size/M, ok-to-merge, qe-approved, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98052 CNV#59584_419: CNV with Descheduler
  modules/virt-enabling-descheduler-evictions.adoc
Labels: lgtm, size/S, CNV

#97745 [DOCS] Shared Resource CSI Driver wording update
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
Labels: size/L

#97821 [DOCS] Shared Resource CSI Driver wording update
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
Labels: size/L

#96332 OCP 4.19 RN's update to add Power11 support
  release_notes/ocp-4-19-release-notes.adoc
Labels: size/XS, merge-review-in-progress

#98356 OCPBUGS-54547 added NOTE to documentation
  modules/oc-mirror-imageset-config-parameters-v2.adoc
  modules/oc-mirror-operator-catalog-filtering.adoc
Labels: lgtm, size/L, qe-approved, merge-review-in-progress, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98629 CP416-OSDOCS-15754: manual CP
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift-using-config-yaml.adoc
  microshift_install/microshift-install-rpm.adoc
  microshift_networking/microshift-cni.adoc
  microshift_networking/microshift-nw-router.adoc
  modules/microshift-config-rhde-con.adoc
  modules/microshift-config-yaml.adoc
  modules/microshift-default-settings.adoc
  snippets/microshift-greenboot-status-snip.adoc
Labels: size/M, jira/valid-reference

#98165 OSDOCS#15974: Removing unused assemblies (Control plane pod)
  authentication/configuring-ldap-failover.adoc
  authentication/dedicated-understanding-authentication.adoc
  cli_reference/developer_cli_odo/configuring-the-odo-cli.adoc
  cli_reference/developer_cli_odo/creating-instances-of-services-managed-by-operators.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-java-application-with-a-database.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-multicomponent-application-with-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-a-single-component-application-with-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/creating-an-application-with-a-database.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/debugging-applications-in-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/deleting-applications.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/sample-applications.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/using-devfiles-in-odo.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/working-with-projects.adoc
  cli_reference/developer_cli_odo/creating_and_deploying_applications_with_odo/working-with-storage.adoc
  cli_reference/developer_cli_odo/installing-odo.adoc
  cli_reference/developer_cli_odo/managing-environment-variables-in-odo.adoc
  cli_reference/developer_cli_odo/odo-architecture.adoc
  cli_reference/developer_cli_odo/odo-cli-reference.adoc
  cli_reference/developer_cli_odo/understanding-odo.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/about-odo-in-a-restricted-environment.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/creating-and-deploying-a-component-to-the-disconnected-cluster.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/creating-and-deploying-devfile-components-to-the-disconnected-cluster.adoc
  cli_reference/developer_cli_odo/using_odo_in_a_restricted_environment/pushing-the-odo-init-image-to-the-restricted-cluster-registry.adoc
  etcd/control-plane-overview.adoc
  etcd/etcd-4-5-node.adoc
  etcd/etcd-fault-tolerant.adoc
  hosted_control_planes/hcp-backup-restore-dr.adoc
  nodes/cma/nodes-cma-autoscaling-custom-about.adoc
  nodes/nodes-about-autoscaling-nodes.adoc
  nodes/nodes-machinepools-about.adoc
  nodes/nodes/ecosystems/eco-about-remediation-fencing-maintenance.adoc
  nodes/nodes/ecosystems/eco-machine-health-checks.adoc
  nodes/nodes/ecosystems/eco-node-health-check-operator.adoc
  nodes/nodes/ecosystems/eco-node-maintenance-operator.adoc
  nodes/nodes/ecosystems/eco-self-node-remediation-operator.adoc
  nodes/nodes/nodes-nodes-graceful-shutdown.adoc
  nodes/nodes/nodes-nodes-modifying.adoc
  nodes/scheduling/nodes-scheduler-node-names.adoc
  nodes/scheduling/nodes-scheduler-node-projects.adoc
Labels: size/XXL, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98618 [enterprise-4.18] OSDOCS-14022#Move local storage info up a level for visibility
  _topic_maps/_topic_map.yml
  edge_computing/day_2_core_cnf_clusters/observability/telco-observability.adoc
  edge_computing/ztp-manual-install.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  installing/installing_ibm_z/ibmz-post-install.adoc
  installing/installing_sno/install-sno-installing-sno.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  release_notes/ocp-4-18-release-notes.adoc
  scalability_and_performance/telco-hub-rds.adoc
  storage/persistent_storage_local/_attributes
  storage/persistent_storage_local/images
  storage/persistent_storage_local/modules
  storage/persistent_storage_local/persistent-storage-hostpath.adoc
  storage/persistent_storage_local/persistent-storage-local.adoc
  storage/persistent_storage_local/persistent-storage-using-lvms.adoc
  storage/persistent_storage_local/snippets
  storage/persistent_storage_local/ways-to-provision-local-storage.adoc
Labels: size/L

#98453 CNV-55995: Host network configuration visualization (4.20)
  modules/virt-create-node-network-config-console.adoc
  modules/virt-viewing-graphical-representation-of-network-state-of-node-console.adoc
  modules/virt-viewing-list-of-nodenetworkstate-resources-console.adoc
  modules/virt-viewing-network-state-of-node-console.adoc
  networking/k8s_nmstate/k8s-nmstate-observing-node-network-state.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/L, CNV, jira/valid-reference, branch/enterprise-4.20

#98505 OSDOCS-14511:Pruning Building apps book.
  snippets/unified-perspective-web-console.adoc
Labels: size/XS, jira/valid-reference

#98470 OLS-1974: Update LLM requirements topic
  modules/ols-large-language-model-requirements.adoc
Labels: size/XS, jira/valid-reference

#97791 ROX-11689: Add info about key value pairs and roles
  modules/assign-role-to-user-or-group.adoc
Labels: size/XS, jira/valid-reference, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8, rhacs-docs-4.9

#98653 [RHACS][Docs] ROX-30574: Release notes for 4.8.3
  modules/common-attributes.adoc
  release_notes/48-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, jira/valid-reference, rhacs-docs-4.8

#98547 Telcodocs-2140 RN
  release_notes/ocp-4-19-release-notes.adoc
Labels: size/S

#98581 TELCODOCS-2259: Release note for ARM dual port OC for PTP
  release_notes/ocp-4-20-release-notes.adoc
Labels: size/S, jira/valid-reference, branch/enterprise-4.20

#98338 OSDOCS-12324: Added passthrough mode to config in installing-gcp-clus…
  installing/installing_gcp/installing-gcp-customizations.adoc
  modules/installing-gcp-cluster-creation.adoc
  modules/installing-gcp-cluster-label-tag-reference.adoc
Labels: size/M, ok-to-merge, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97979 OSDOCS#13845: Add information for encrypt etcd data
  microshift_install_get_ready/microshift-install-get-ready.adoc
  modules/microshift-encrypt-etcd-data.adoc
Labels: size/S, ok-to-merge, qe-approved, branch/enterprise-4.19, branch/enterprise-4.20

#98697 OSDOCS-16104: mirror-to-disk and disk-to-mirror
  modules/oc-mirror-about-cache-and-workspace-dirs.adoc
Labels: lgtm, size/XS, jira/valid-reference, sme-review-needed, branch/enterprise-4.19, branch/enterprise-4.20, verified

#96078 [OSDOCS-15138]ROSA HCP Cluster Deletion Policy
  modules/life-cycle-deletion.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-hcp-life-cycle.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: size/M

#98222 OLS-2045: Inform user about expected prompt output on OLS when using…
  modules/ols-thinking-model-generates-delineator-prompt.adoc
  troubleshoot/ols-troubleshooting-openshift-lightspeed.adoc
Labels: size/S, jira/valid-reference

#98670 OSDOCS-16096 added assembly and modules for reconciliation plus updat…
  _topic_maps/_topic_map.yml
  modules/zero-trust-manager-pause-reconciliation.adoc
  modules/zero-trust-manager-restart-reconciliation.adoc
  security/zero_trust_workload_identity_manager/zero-trust-manager-reconciliation.adoc
Labels: size/L, merge-review-in-progress, branch/enterprise-4.19, branch/enterprise-4.20

#97670 OSDOCS-15874: adds physically bound image building to bootc docs Micr…
  _topic_maps/_topic_map_ms.yml
  microshift_install_bootc/microshift-about-rhel-image-mode.adoc
  microshift_install_bootc/microshift-install-bootc-image.adoc
  microshift_install_bootc/microshift-install-bootc-physically-bound.adoc
  modules/microshift-embed-cont-images-bootc-image.adoc
  modules/microshift-greenboot-check-update.adoc
  modules/microshift-install-bootc-build-image.adoc
  modules/microshift-install-bootc-physically-bound-con.adoc
  modules/microshift-preparing-for-image-building-bootc.adoc
  modules/microshift-preparing-for-image-building.adoc
Labels: size/L, qe-approved, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#97827 OLS-2038: Update Azure OpenAI example in creating custom resource
  modules/ols-creating-lightspeed-custom-resource-file-using-cli.adoc
  modules/ols-creating-lightspeed-custom-resource-file-using-web-console.adoc
Labels: lgtm, size/XS, jira/valid-reference

#98607 OSDOCS-16081 created release notes for 0.2.0
  security/zero_trust_workload_identity_manager/zero-trust-manager-release-notes.adoc
Labels: size/M, branch/enterprise-4.19, branch/enterprise-4.20

#97325 OSDOSC-15511: Added Firewall rules into bastion host
  modules/rosa-hcp-firewall-prerequisites.adoc
  rosa_hcp/rosa-hcp-egress-zero-install.adoc
Labels: size/M, branch/enterprise-4.19, branch/enterprise-4.20

#98471 OSDOCS#15784: oc-mirror verification RN
  release_notes/ocp-4-20-release-notes.adoc
Labels: lgtm, size/XS, ok-to-merge, branch/enterprise-4.20

#98726 CNV-66307-b: fixed obsolete prereq
  modules/virt-creating-linux-bridge-nad-cli.adoc
Labels: size/XS, CNV, branch/enterprise-4.16, branch/enterprise-4.17

#96854 [OSDOCS-14567] Doc Story for Cross-Project Federated Identity Authentication for OSD-GCP
  modules/create-wif-cluster-cli.adoc
  modules/create-wif-cluster-ocm.adoc
  osd_whats_new/osd-whats-new.adoc
Labels: size/S

#98769 [enterprise-4.17][OSDOCS-15986]: HCP on OpenShift Virtualization CQA cleanup
  modules/hcp-virt-add-node.adoc
  modules/hcp-virt-create-hc-cli.adoc
  modules/hcp-virt-create-hc-console.adoc
  modules/hcp-virt-hc-base-domain.adoc
  modules/hcp-virt-load-balancer.adoc
  modules/hcp-virt-sched-vms.adoc
  modules/hcp-virt-wildcard-dns.adoc
  modules/hosted-control-planes-concepts-personas.adoc
Labels: size/M

#98772 [enterprise-4.15] OSDOCS-14022#Move local storage info up a level for visibility
  _topic_maps/_topic_map.yml
  edge_computing/ztp-manual-install.adoc
  installing/installing_sno/install-sno-installing-sno.adoc
  installing/installing_with_agent_based_installer/preparing-an-agent-based-installed-cluster-for-mce.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  post_installation_configuration/ibmz-post-install.adoc
  release_notes/ocp-4-15-release-notes.adoc
  scalability_and_performance/using-rfhe.adoc
  storage/persistent_storage_local/_attributes
  storage/persistent_storage_local/images
  storage/persistent_storage_local/modules
  storage/persistent_storage_local/persistent-storage-hostpath.adoc
  storage/persistent_storage_local/persistent-storage-local.adoc
  storage/persistent_storage_local/persistent-storage-using-lvms.adoc
  storage/persistent_storage_local/snippets
  storage/persistent_storage_local/ways-to-provision-local-storage.adoc
Labels: size/L

#98413 PR for SRVLOGIC-537: Add "Configuring custom Maven mirrors" section in the OpenShift Serverless Logic docs
  _topic_maps/_topic_map.yml
  modules/serverless-logic-adding-maven-mirror-building-workflows.adoc
  modules/serverless-logic-adding-maven-mirror-deploy-dev-mode.adoc
  modules/serverless-logic-config-maven-mirror-on-custom-image.adoc
  serverless-logic/serverless-logic-configuring-custom-maven-mirrors.adoc
Labels: size/L, serverless, jira/valid-reference

#98301 OBSDOCS-2325: Logging Z-Stream Release Notes - 6.0.10
  modules/logging-release-notes-6-0-10.adoc
  release_notes/logging-release-notes-6-0.adoc
Labels: size/S, jira/valid-reference

#98794 OSDOCS-16067:Removed incorrect init command sections from ROSA CLI doc.
  cli_reference/rosa_cli/rosa-get-started-cli.adoc
Labels: size/XS, jira/valid-reference

#98327 CNV-43322: Release note for OCI GA
  virt/release_notes/virt-4-20-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.20

#98813 Memory overhead equation bugfix
  modules/virt-cluster-resource-requirements.adoc
Labels: size/XS, CNV, branch/enterprise-4.12, branch/enterprise-4.14, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98631 OSDOCS-12405 Bonding Mode additional information
  modules/virt-example-bond-nncp.adoc
Labels: size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98057 OCPDOCS MCO add pinned image podman inspect note
  modules/machine-config-pin-preload-images.adoc
Labels: size/XS, branch/enterprise-4.20

#97090 OSDOCS-13847:Generic Device Plugin Feature
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift-gdp.adoc
  modules/microshift-con-limitations-of-generic-device-plugin.adoc
  modules/microshift-con-understanding-generic-device-plugin.adoc
  modules/microshift-proc-configuring-generic-device-plugin.adoc
  modules/microshift-proc-deploying-applications-with-generic-devices.adoc
  modules/microshift-ref-generic-device-plugin-configuration-parameters.adoc
  modules/microshift-ref-generic-device-plugin-troubleshooting.adoc
Labels: lgtm, size/L, jira/valid-reference, branch/enterprise-4.20

#98782 Adding content type attributes to OSD
  modules/osd-aws-privatelink-architecture.adoc
  modules/osd-aws-privatelink-required-resources.adoc
  modules/osd-intro.adoc
  modules/osd-update-preparing-evaluate-alerts.adoc
  modules/osd-update-preparing-list.adoc
  modules/osd-update-preparing-migrate.adoc
Labels: size/XS, ok-to-test, branch/enterprise-4.19, branch/enterprise-4.20

#98932 OBSDOCS-2226: fix issues identified by the CQA
  modules/monitoring-common-terms.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-default-monitoring-components.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98987 [enterprise-4.18] OBSDOCS-2226: fix issues identified by the CQA
  modules/monitoring-common-terms.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-default-monitoring-components.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
Labels: size/M, jira/valid-reference

#98991 [enterprise-4.15] OBSDOCS-2226: fix issues identified by the CQA
  modules/monitoring-common-terms.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-default-monitoring-components.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
Labels: size/M, jira/valid-reference

#98998 [monitoring-docs-4.16] OBSDOCS-2226: fix issues identified by the CQA
  about-ocp-monitoring/monitoring-stack-architecture.adoc
  modules/monitoring-common-terms.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-default-monitoring-components.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
Labels: size/M, jira/valid-reference

#98999 [monitoring-docs-4.15] OBSDOCS-2226: fix issues identified by the CQA
  about-ocp-monitoring/monitoring-stack-architecture.adoc
  modules/monitoring-common-terms.adoc
  modules/monitoring-components-for-monitoring-user-defined-projects.adoc
  modules/monitoring-default-monitoring-components.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
Labels: size/M, jira/valid-reference

#98973 ROX-30869: Release notes for 4.8.4
  modules/common-attributes.adoc
  release_notes/48-release-notes.adoc
Labels: size/S, jira/valid-reference, rhacs-docs-4.8

#98304 RHDEVDOCS-6646: Builds Operator is creating a conflicting Pipelines Operator
  installing/installing-openshift-builds.adoc
  modules/ob-installing-builds-by-using-the-web-console.adoc
  modules/ob-installing-builds-using-cli.adoc
Labels: size/M, jira/valid-reference

#97444 OSDOCS-13364:adds ovn-k conditional for egress firewall
  modules/nw-egressnetworkpolicy-about.adoc
Labels: size/XS, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#93676 Update log6x-oc-explain.adoc
  modules/log6x-oc-explain.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.16

#93678 Update log6x-oc-explain.adoc
  modules/log6x-oc-explain.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14

#98036 RHDEVDOCS-6621: Content changes for Keycloak removal
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/gitops-argo-cd-properties.adoc
  modules/gitops-release-notes-1-18-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
  release_notes/gitops-release-notes-1-18.adoc
Labels: size/M, jira/valid-reference

#98487 OCPBUGS-61216: Removed SLB doc from DAY 2 BM book
  installing/installing_bare_metal/bare-metal-postinstallation-configuration.adoc
  modules/enabling-OVS-balance-slb-mode.adoc
Labels: lgtm, size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#99035 Manual CP 1.3
  modules/ob-creating-a-build-with-oci-artifacts.adoc
  modules/ob-uploading-the-OCI-artifact-by-using-the-CLI.adoc
  modules/ob-uploading-the-OCI-artifact-manually.adoc
  work_with_builds/using-builds.adoc
Labels: size/L

#98725 OSDOCS-15460: CQA install vSphere config parameters
  installing/installing_vsphere/installation-config-parameters-vsphere.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99014 [enterprise-4.15] OSDOCS-15411_a#CQA updates
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/nodes-pods-autoscaling-policies.adoc
  modules/nodes-pods-vertical-autoscaler-about.adoc
  modules/nodes-pods-vertical-autoscaler-configuring.adoc
  modules/nodes-pods-vertical-autoscaler-custom-resource.adoc
  modules/nodes-pods-vertical-autoscaler-custom.adoc
  modules/nodes-pods-vertical-autoscaler-install.adoc
  modules/nodes-pods-vertical-autoscaler-oom.adoc
  modules/nodes-pods-vertical-autoscaler-tuning.adoc
  modules/nodes-pods-vertical-autoscaler-uninstall.adoc
  modules/nodes-pods-vertical-autoscaler-using-about.adoc
  nodes/pods/nodes-pods-vertical-autoscaler.adoc
Labels: size/L

#99005 Add 4.20.0 rc0 APIs
  rest_api/autoscale_apis/clusterautoscaler-autoscaling-openshift-io-v1.adoc
  rest_api/machine_apis/containerruntimeconfig-machineconfiguration-openshift-io-v1.adoc
  rest_api/monitoring_apis/alertmanager-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/alertmanagerconfig-monitoring-coreos-com-v1beta1.adoc
  rest_api/monitoring_apis/podmonitor-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/probe-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/prometheus-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.adoc
  rest_api/monitoring_apis/thanosruler-monitoring-coreos-com-v1.adoc
  rest_api/network_apis/ipamclaim-k8s-cni-cncf-io-v1alpha1.adoc
  rest_api/objects/index.adoc
  rest_api/operator_apis/network-operator-openshift-io-v1.adoc
Labels: size/XXL, branch/enterprise-4.20

#97655 PR for SRVKE-1692: Add authorization and eventpolicy subsection in the Eventing section
  _topic_maps/_topic_map.yml
  eventing/serverless-event-authorization-eventpolicy.adoc
  modules/serverless-event-auth-advanced-cloudevent-filtering-criteria.adoc
  modules/serverless-event-auth-applying-eventpolicy.adoc
  modules/serverless-event-auth-defining-senders.adoc
  modules/serverless-event-auth-defining-targets.adoc
  modules/serverless-event-auth-eventpolicy-status-application.adoc
  modules/serverless-event-default-authorization-mode.adoc
  modules/serverless-eventpolicy-resource-overview.adoc
Labels: size/L, serverless, merge-review-in-progress, jira/valid-reference

#99042 OBSDOCS-2413 remove unused attributes
  _attributes/common-attributes.adoc
Labels: size/L

#99105 [service-mesh-docs-3.1] Manual CP OSSM-10535 Check and remove ":context:" and check mod-docs type format from modules
  about/ossm-about-concepts.adoc
  install/ossm-deploying-multiple-service-meshes-on-single-cluster.adoc
  install/ossm-installing-openshift-service-mesh.adoc
  install/ossm-istio-ambient-mode.adoc
  install/ossm-sidecar-injection.adoc
  migrating/checklists/ossm-migrating-read-me.adoc
  migrating/cluster-wide/ossm-migrating-cluster-wide.adoc
  modules/ossm-about-accessing-bookinfo-application-using-gateway.adoc
  modules/ossm-about-bookinfo-application.adoc
  modules/ossm-about-configuring-a-gateway-to-accept-ingress-traffic.adoc
  modules/ossm-about-deploying-istio-using-service-mesh-operator.adoc
  modules/ossm-about-discoveryselectors.adoc
  modules/ossm-about-exposing-services-to-traffic-outside-a-cluster.adoc
  modules/ossm-about-gateway-injection.adoc
  modules/ossm-about-inplace-strategy.adoc
  modules/ossm-about-istio-deployment.adoc
  modules/ossm-about-mtls.adoc
  modules/ossm-about-operator-update-process.adoc
  modules/ossm-accessing-bookinfo-application-using-gateway-api.adoc
  modules/ossm-creating-istio-cni-project-using-console.adoc
  modules/ossm-creating-istio-project-using-console.adoc
  modules/ossm-creating-istio-resource-using-console.adoc
  modules/ossm-creating-istiocni-resource-using-console.adoc
  modules/ossm-customizing-istio-configuration.adoc
  modules/ossm-deploying-istio.adoc
  modules/ossm-exposing-a-gateway-to-traffic-outside-the-cluster-using-openshift-routes.adoc
  modules/ossm-exposing-service-using-istio-gateway-and-virtualservice.adoc
  modules/ossm-installing-gateway-using-gateway-injection.adoc
  modules/ossm-scoping-service-mesh-with-discoveryselectors.adoc
  modules/ossm-selecting-inplace-strategy.adoc
  modules/ossm-selecting-revisionbased-strategy.adoc
  modules/ossm-service-mesh-overview.adoc
  modules/ossm-understanding-operator-updates-and-channels.adoc
  modules/ossm-understanding-sm-istio-versions.adoc
  modules/ossm-understanding-versioning.adoc
  modules/ossm-using-discoveryselectors-scope-service-mesh.adoc
Labels: size/M

#97170 OSDOCS-15644#Add LVM to supported PV types
  modules/storage-persistent-storage-pv.adoc
Labels: size/XS, px-approved, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#98649 OSSM-10715-3.1.2 (At ReleaseCandidate): [DOC] Release Notes, Known Issues and Bug Fixes
  _attributes/common-attributes.adoc
  modules/ossm-release-notes-3-1-2.adoc
  modules/ossm-release-notes-supported-versions.adoc
  ossm-release-notes/ossm-release-notes.adoc
Labels: size/M

#98648 OSSM-10715-3.0.5 (At ReleaseCandidate): [DOC] Release Notes, Known Issues and Bug Fixes
  _attributes/common-attributes.adoc
  modules/ossm-release-notes-3-0-5.adoc
  modules/ossm-release-notes-supported-versions.adoc
  ossm-release-notes/ossm-release-notes.adoc
Labels: size/M

#98549 OSDOCS-16077 [NETOBSERV] 1.9.3 release notes
  _topic_maps/_topic_map.yml
  modules/network-observability-operator-release-notes-1-9-3-advisory.adoc
  observability/network_observability/network-observability-release-notes-1-9-3.adoc
Labels: size/S, qe-approved, branch/enterprise-4.12, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97322 OSDOCS 15410 CQA: Automatically scaling pods with the horizontal pod autoscaler
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/nodes-pods-autoscaling-creating-cpu-percent.adoc
  modules/nodes-pods-autoscaling-creating-cpu-specific.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory-percent.adoc
  modules/nodes-pods-autoscaling-creating-memory-specific.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-creating-web-console-edit.adoc
  modules/nodes-pods-autoscaling-creating-web-console-remove.adoc
  modules/nodes-pods-autoscaling-creating-web-console.adoc
  modules/nodes-pods-autoscaling-requests-and-limits-hpa.adoc
  modules/nodes-pods-autoscaling-status-about.adoc
  modules/nodes-pods-autoscaling-status-viewing.adoc
  modules/nodes-pods-autoscaling-workflow-hpa.adoc
  nodes/pods/nodes-pods-autoscaling.adoc
  nodes/pods/nodes-pods-configuring.adoc
  snippets/nodes-pods-autoscaling-creating-cpu-prereqs.adoc
Labels: size/XL, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99161 OLS-2091: Update OLS version
  modules/ols-installing-operator.adoc
  modules/ols-openshift-requirements.adoc
Labels: lgtm, size/XS, jira/valid-reference

#99169 [enterprise-4.12] OSDOCS 15410 CQA: Automatically scaling pods with the horizontal pod autoscaler
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/nodes-pods-autoscaling-creating-cpu-percent.adoc
  modules/nodes-pods-autoscaling-creating-cpu-specific.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory-percent.adoc
  modules/nodes-pods-autoscaling-creating-memory-specific.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-creating-web-console-edit.adoc
  modules/nodes-pods-autoscaling-creating-web-console-remove.adoc
  modules/nodes-pods-autoscaling-creating-web-console.adoc
  modules/nodes-pods-autoscaling-requests-and-limits-hpa.adoc
  modules/nodes-pods-autoscaling-status-about.adoc
  modules/nodes-pods-autoscaling-status-viewing.adoc
  modules/nodes-pods-autoscaling-workflow-hpa.adoc
  nodes/pods/nodes-pods-autoscaling.adoc
  snippets/nodes-pods-autoscaling-creating-cpu-prereqs.adoc
Labels: size/XL, branch/enterprise-4.12

#99171 [enterprise-4.14] OSDOCS 15410 CQA: Automatically scaling pods with the horizontal pod autoscaler
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/nodes-pods-autoscaling-creating-cpu-percent.adoc
  modules/nodes-pods-autoscaling-creating-cpu-specific.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory-percent.adoc
  modules/nodes-pods-autoscaling-creating-memory-specific.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-creating-web-console-edit.adoc
  modules/nodes-pods-autoscaling-creating-web-console-remove.adoc
  modules/nodes-pods-autoscaling-creating-web-console.adoc
  modules/nodes-pods-autoscaling-requests-and-limits-hpa.adoc
  modules/nodes-pods-autoscaling-status-about.adoc
  modules/nodes-pods-autoscaling-status-viewing.adoc
  modules/nodes-pods-autoscaling-workflow-hpa.adoc
  nodes/pods/nodes-pods-autoscaling.adoc
  nodes/pods/nodes-pods-configuring.adoc
  snippets/nodes-pods-autoscaling-creating-cpu-prereqs.adoc
Labels: size/XL, branch/enterprise-4.14

#99173 [enterprise-4.16] OSDOCS 15410 CQA: Automatically scaling pods with the horizontal pod autoscaler
  modules/nodes-pods-autoscaling-about.adoc
  modules/nodes-pods-autoscaling-best-practices-hpa.adoc
  modules/nodes-pods-autoscaling-creating-cpu-percent.adoc
  modules/nodes-pods-autoscaling-creating-cpu-specific.adoc
  modules/nodes-pods-autoscaling-creating-cpu.adoc
  modules/nodes-pods-autoscaling-creating-memory-percent.adoc
  modules/nodes-pods-autoscaling-creating-memory-specific.adoc
  modules/nodes-pods-autoscaling-creating-memory.adoc
  modules/nodes-pods-autoscaling-creating-web-console-edit.adoc
  modules/nodes-pods-autoscaling-creating-web-console-remove.adoc
  modules/nodes-pods-autoscaling-creating-web-console.adoc
  modules/nodes-pods-autoscaling-requests-and-limits-hpa.adoc
  modules/nodes-pods-autoscaling-status-about.adoc
  modules/nodes-pods-autoscaling-status-viewing.adoc
  modules/nodes-pods-autoscaling-workflow-hpa.adoc
  nodes/pods/nodes-pods-autoscaling.adoc
  nodes/pods/nodes-pods-configuring.adoc
  snippets/nodes-pods-autoscaling-creating-cpu-prereqs.adoc
Labels: size/XL, branch/enterprise-4.16

#99160 OSDOCS-15638#Add link for 3rd-party-certified CSI drivers
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: size/S

#99176 [enterprise-4.15] OSDOCS-15638#Add link for 3rd-party-certified CSI drivers
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: size/S

#98783 [OSDOCS-16123]:Prune "CLI Tools" Phase 2
  cli_reference/index.adoc
  cli_reference/kn-cli-tools.adoc
  cli_reference/openshift_cli/managing-cli-profiles.adoc
  cli_reference/openshift_cli/usage-oc-kubectl.adoc
  cli_reference/rosa_cli/rosa-cli-permission-examples.adoc
  cli_reference/rosa_cli/rosa-manage-objects-cli.adoc
  cli_reference/rosa_cli/rosa-updating-billing-account-cli.adoc
  modules/about-cli-profiles-switch.adoc
  modules/cli-extending-plugins-installing.adoc
  modules/cli-extending-plugins-writing.adoc
  modules/cli-getting-help.adoc
  modules/cli-installing-cli-rpm.adoc
  modules/cli-installing-cli-web-console.adoc
  modules/cli-logging-in.adoc
  modules/olm-installing-opm.adoc
  modules/op-installing-tkn-on-linux.adoc
  modules/op-installing-tkn-on-macos.adoc
  modules/op-installing-tkn-on-windows.adoc
  modules/opm-cli-ref-index.adoc
  modules/rosa-about.adoc
  modules/rosa-cli-classic-examples.adoc
  modules/rosa-cli-hcp-examples.adoc
  modules/rosa-common-commands.adoc
  modules/rosa-configure.adoc
  modules/rosa-create-objects.adoc
  modules/rosa-edit-objects.adoc
  modules/rosa-initialize.adoc
  modules/rosa-list-objects.adoc
  modules/rosa-parent-commands.adoc
  modules/rosa-revoke-objects.adoc
  modules/rosa-update-billing-cli.adoc
  modules/rosa-updating-rosa-cli.adoc
  modules/rosa-upgrade-cluster-cli.adoc
  modules/rosa-using-bash-script.adoc
Labels: size/XL

#98714 [RHACS] [Docs] ROX-30531: Adding clarification regarding external databases and backups
  backup_and_restore/backing-up-acs.adoc
  backup_and_restore/restore-acs.adoc
  modules/backing-up-your-postgresql-database-and-certificates.adoc
  modules/backup-considerations-for-external-databases-and-cloud-users.adoc
  modules/restoring-an-external-postgresql-database.adoc
  modules/restoring-central-certificates-and-redeploying-central.adoc
Labels: peer-review-done, size/L, RHACS, jira/valid-reference, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8, rhacs-docs-4.9

#98798 RHDEVDOCS-6537: Content creation for RBAC and Trusted CA flags
  install_config/customizing-configurations-in-the-tektonconfig-cr.adoc
  modules/op-configuration-rbac-trusted-ca-flags.adoc
Labels: size/M, jira/valid-reference

#98353 RHDEVDOCS-6531: Adding content for buildah-ns task
  _topic_maps/_topic_map.yml
  modules/op-differences-between-buildah-buildah-ns-tasks.adoc
  modules/op-running-buildah-ns-task.adoc
  modules/op-security-model-buildah-ns-task.adoc
  modules/op-workspaces-parameters-results-buildah-ns-task.adoc
  secure/using-buildah-ns-tekton-task.adoc
Labels: size/L, jira/valid-reference

#94410 PT2: Port the Log collection and forwarding chapter to 6.x
  configuring/configuring-log-forwarding.adoc
  modules/cluster-logging-collector-log-forward-gcp.adoc
  modules/cluster-logging-collector-log-forward-logs-from-application-pods.adoc
  modules/cluster-logging-collector-log-forward-project.adoc
  modules/logging-forward-splunk.adoc
  modules/logging-forwarding-azure.adoc
Labels: size/L

#99199 [enterprise-4.17] OBSDOCS-2299: doc mismatches dev console
  modules/monitoring-reviewing-monitoring-dashboards-admin.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
Labels: size/S, jira/valid-reference

#99200 [enterprise-4.16] OBSDOCS-2299: doc mismatches dev console
  modules/monitoring-reviewing-monitoring-dashboards-admin.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
Labels: size/S, jira/valid-reference

#99204 [monitoring-docs-4.17] OBSDOCS-2299: doc mismatches dev console
  modules/monitoring-reviewing-monitoring-dashboards-admin.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
Labels: size/S, jira/valid-reference

#98504 CNV-65228: Improvement in CNV docs specifically for AWS networking
  modules/virt-aws-bm.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99102 OCPBUGS-61722: Reverting PTP v1 content removed in error
  _topic_maps/_topic_map.yml
  networking/advanced_networking/ptp/ptp-cloud-events-consumer-dev-reference.adoc
Labels: lgtm, size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17

#98983 OBSDOCS-2403: Logging Z-Stream Release Notes - 6.2.5
  modules/logging-release-notes-6-2-4.adoc
  modules/logging-release-notes-6-2-5.adoc
  release_notes/logging-release-notes-6.2.adoc
Labels: size/M, jira/valid-reference

#99211 OSDOCS-15460-CP417: CQA install vSphere config parameters
  installing/installing_vsphere/installation-config-parameters-vsphere.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/L

#98450 OSDOCS#15493: New AI workloads book and LWS docs
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  ai_workloads/_attributes
  ai_workloads/images
  ai_workloads/index.adoc
  ai_workloads/leader_worker_set/_attributes
  ai_workloads/leader_worker_set/images
  ai_workloads/leader_worker_set/index.adoc
  ai_workloads/leader_worker_set/lws-managing.adoc
  ai_workloads/leader_worker_set/lws-release-notes.adoc
  ai_workloads/leader_worker_set/lws-uninstalling.adoc
  ai_workloads/leader_worker_set/modules
  ai_workloads/leader_worker_set/snippets
  ai_workloads/modules
  ai_workloads/snippets
  images/587_OpenShift_lws_0925.png
  modules/ai-operators.adoc
  modules/ai-rhoai.adoc
  modules/lws-about.adoc
  modules/lws-arch.adoc
  modules/lws-config.adoc
  modules/lws-install-operator.adoc
  modules/lws-remove-resources.adoc
  modules/lws-rn-1.0.0.adoc
  modules/lws-uninstall.adoc
Labels: size/L, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99229 [enterprise-4.14] OSDOCS-15638#Add link for 3rd-party-certified CSI drivers
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: size/S

#99246 [enterprise-4.12] OSDOCS-15638#Add link for 3rd-party-certified CSI drivers
  modules/persistent-storage-csi-drivers-supported.adoc
  storage/container_storage_interface/persistent-storage-csi.adoc
Labels: size/M

#98802 TELCODOCS-2465: Adding dual-stacking networking to IBI and IBU
  modules/cnf-image-based-upgrade-seed-image-config.adoc
  modules/cnf-image-based-upgrade-seed-image-guide.adoc
  modules/ibi-create-config-iso.adoc
  modules/ibi-create-standalone-config-iso.adoc
  modules/ibi-image-based-install-cluster-guide.adoc
  modules/ibi-image-cluster-install-api-spec.adoc
Labels: lgtm, size/M, jira/valid-reference, branch/enterprise-4.20

#99243 [OSDOCS-16199]Update title to reflect product-title
  rosa_architecture/rosa_policy_service_definition/rosa-policy-responsibility-matrix.adoc
Labels: size/XS

#98847 [enterprise-4.19] OSDOCS#15493: Adding LWS to RN list
  release_notes/addtl-release-notes.adoc
Labels: size/XS, merge-review-needed, branch/enterprise-4.19

#98848 [enterprise-4.18] OSDOCS#15493: Adding LWS to RN list
  release_notes/addtl-release-notes.adoc
Labels: size/XS, merge-review-needed, branch/enterprise-4.18

#98992 OBSDOCS-2404: Logging Z-Stream Release Notes - 6.3.1
  modules/logging-release-notes-6-3-1.adoc
  release_notes/logging-release-notes.adoc
Labels: size/S, jira/valid-reference

#98475 OSDOCS-14899:Adding GDP configs to defaults table
  microshift_configuring/microshift-using-config-yaml.adoc
  modules/microshift-config-parameters-table.adoc
  modules/microshift-default-settings.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.20

#98728 OSDOCS-14897:Add GDP feature to release notes
  microshift_release_notes/microshift-4-20-release-notes.adoc
Labels: lgtm, size/S, jira/valid-reference

#99144 CNV-15425: Clean up NUMA conceptual docs
  modules/cnf-about-numa-aware-scheduling.adoc
  scalability_and_performance/cnf-numa-aware-scheduling.adoc
  snippets/about-numa.adoc
Labels: lgtm, size/M, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99282 OSDOCS-16189-419: adds corrections 4.17+
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift-cluster-access-kubeconfig.adoc
  microshift_networking/microshift-cni.adoc
  microshift_welcome/index.adoc
  modules/microshift-arch-design.adoc
  modules/microshift-check-journal-logs-updates.adoc
Labels: size/S, jira/valid-reference

#99285 OSDOCS-16189-417: adds corrections 4.17+
  _topic_maps/_topic_map_ms.yml
  microshift_configuring/microshift-cluster-access-kubeconfig.adoc
  microshift_networking/microshift-cni.adoc
  microshift_welcome/index.adoc
  modules/microshift-arch-design.adoc
  modules/microshift-check-journal-logs-updates.adoc
Labels: size/S, jira/valid-reference
