Repository openshift/openshift-docs, pull requests merged in 2025-08, with the labels that each got.

#96800 OBSDOCS-2214: Change module type for metrics server audit logs module
  modules/monitoring-configuring-audit-logs-for-metrics-server.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96406 OSSM-9075: Minor updates for Kiali and Distributed Tracing
  modules/ossm-config-otel-kiali.adoc
Labels: lgtm, size/S, jira/valid-reference

#96352 Updated the Tech Prev features table for Edge Computing
  release_notes/ocp-4-19-release-notes.adoc
Labels: lgtm, size/S, merge-review-in-progress, branch/enterprise-4.19

#96993 [OCPBUGS-60040] Add IBM z17 and LinuxONE 5 as supported
  modules/installation-requirements-user-infra-ibm-z-kvm.adoc
  modules/minimum-ibm-z-system-requirements.adoc
Labels: lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.16

#97002 [enterprise-4.14] HCIDOCS-644: Create diagram for OCI integration section
  images/569_OpenShift_ai_install_oci_0725.png
  modules/installing-oci-about-assisted-installer.adoc
Labels: size/M, needs-rebase, jira/valid-reference

#97004 [enterprise-4.15] HCIDOCS-644: Create diagram for OCI integration section
  images/569_OpenShift_ai_install_oci_0725.png
  modules/installing-oci-about-assisted-installer.adoc
Labels: size/M, jira/valid-reference

#97017 [enterprise-4.14] [NETOBSERV] OSDOCS-15503 Vale updates for network-observability-loki-secret.adoc
  modules/network-observability-loki-secret.adoc
  observability/network_observability/installing-operators.adoc
Labels: size/S, merge-review-in-progress, branch/enterprise-4.14

#97013 [enterprise-4.12] [NETOBSERV] OSDOCS-15503 Vale updates for network-observability-loki-secret.adoc
  modules/network-observability-loki-secret.adoc
  observability/network_observability/installing-operators.adoc
Labels: size/S, branch/enterprise-4.12, merge-review-in-progress

#96020 Updated KMM Operator modules to pass DITA validation
  modules/kmm-applying-tolerations-to-kernel-module-pods.adoc
  modules/kmm-building-and-signing-a-kmod-image.adoc
  modules/kmm-building-and-signing-a-moduleloader-container-image.adoc
  modules/kmm-configuring-kmmo.adoc
  modules/kmm-gathering-data-for-kmm-hub.adoc
  modules/kmm-gathering-data-for-kmm.adoc
  modules/kmm-hub-installing-kmm-hub-creating-resources.adoc
  modules/kmm-hub-running-kmm-on-the-spoke.adoc
  modules/kmm-installing-older-versions.adoc
  modules/kmm-installing-using-cli.adoc
  modules/kmm-observing-events.adoc
  modules/kmm-reading-operator-logs.adoc
  modules/kmm-running-depmod.adoc
  modules/kmm-signing-a-prebuilt-driver-container.adoc
  modules/kmm-signing-kmods-in-a-prebuilt-image.adoc
  modules/kmm-uninstalling-kmmo-red-hat-catalog.adoc
  modules/kmm-using-driver-toolkit.adoc
  modules/kmm-using-intree-modules.adoc
  modules/kmm-using-signing-with-kmm.adoc
  modules/kmm-validation-status.adoc
Labels: peer-review-done, size/L, merge-review-needed, branch/enterprise-4.19, branch/enterprise-4.20

#97022 [enterprise-4.14] OSDOCS-15521: Fix discrete headings
  applications/deployments/what-deployments-are.adoc
  applications/pruning-objects.adoc
  modules/deployment-specific-features.adoc
  modules/deploymentconfig-object-specific-features.adoc
  modules/deployments-comparing-deploymentconfigs.adoc
  modules/deployments-lifecycle-hooks.adoc
  modules/deployments-triggers.adoc
  modules/nodes-pods-plugins-about.adoc
  modules/nw-infw-operator-rules-object.adoc
  modules/olm-dependency-resolution-examples.adoc
  modules/olm-operatorgroups-intersections.adoc
  modules/olm-operatorgroups-troubleshooting.adoc
  modules/pruning-images-manual.adoc
  modules/pruning-images-troubleshooting.adoc
  security/compliance_operator/co-overview.adoc
Labels: size/L, jira/valid-reference

#97023 [enterprise-4.13] OSDOCS-15521: Fix discrete headings
  applications/deployments/what-deployments-are.adoc
  applications/pruning-objects.adoc
  modules/deployment-specific-features.adoc
  modules/deploymentconfig-object-specific-features.adoc
  modules/deployments-comparing-deploymentconfigs.adoc
  modules/deployments-lifecycle-hooks.adoc
  modules/deployments-triggers.adoc
  modules/nodes-pods-plugins-about.adoc
  modules/nw-infw-operator-rules-object.adoc
  modules/olm-dependency-resolution-examples.adoc
  modules/olm-operatorgroups-intersections.adoc
  modules/olm-operatorgroups-troubleshooting.adoc
  modules/pruning-images-manual.adoc
  modules/pruning-images-troubleshooting.adoc
  security/compliance_operator/co-overview.adoc
Labels: size/L, jira/valid-reference

#97024 [enterprise-4.12] OSDOCS-15521: Fix discrete headings
  applications/deployments/what-deployments-are.adoc
  applications/pruning-objects.adoc
  modules/deployment-specific-features.adoc
  modules/deploymentconfig-object-specific-features.adoc
  modules/deployments-comparing-deploymentconfigs.adoc
  modules/deployments-lifecycle-hooks.adoc
  modules/deployments-triggers.adoc
  modules/nodes-pods-plugins-about.adoc
  modules/nw-infw-operator-rules-object.adoc
  modules/olm-dependency-resolution-examples.adoc
  modules/olm-operatorgroups-intersections.adoc
  modules/olm-operatorgroups-troubleshooting.adoc
  modules/pruning-images-manual.adoc
  modules/pruning-images-troubleshooting.adoc
  security/compliance_operator/co-overview.adoc
Labels: size/L, jira/valid-reference

#97019 [enterprise-4.16] [NETOBSERV] OSDOCS-15503 Vale updates for network-observability-loki-secret.adoc
  modules/network-observability-loki-secret.adoc
  observability/network_observability/installing-operators.adoc
Labels: size/S, branch/enterprise-4.16

#97006 [enterprise-4.12] OSDOCS-3467: Updated configuration-externalip.adoc for private cluster
  modules/cluster-cloud-controller-manager-operator.adoc
  modules/configuration-externalip.adoc
  modules/installation-initializing-manual.adoc
  networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc
Labels: size/M, branch/enterprise-4.12, jira/valid-reference

#97005 [enterprise-4.13] OSDOCS-3467-13: Updated configuration-externalip.adoc for private cluster
  modules/cluster-cloud-controller-manager-operator.adoc
  modules/configuration-externalip.adoc
  modules/installation-initializing-manual.adoc
  networking/configuring_ingress_cluster_traffic/configuring-externalip.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.13

#96548 [NETOBSERV] OSDOCS-15495 Vale updates for network-observability-loki-install.adoc
  modules/network-observability-loki-install.adoc
Labels: size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.17, branch/enterprise-4.19, branch/enterprise-4.20

#96966 OSDOCS-14543 [NETOBSERV] Change Network Observability to network observability when not referencing the Operator
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-con_filter-network-flows-at-ingestion.adoc
  modules/network-observability-create-network-policy.adoc
  modules/network-observability-deploy-network-policy.adoc
  modules/network-observability-ebpf-agent-alert.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-metrics-names.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-networking-events-overview.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-proc_working-with-udn.adoc
  modules/network-observability-resource-recommendations.adoc
  modules/network-observability-viewing-dashboards.adoc
  modules/network-observability-without-loki.adoc
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/troubleshooting-network-observability.adoc
Labels: size/M, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97039 [enterprise-4.12] OSDOCS-14543 [NETOBSERV] Change Network Observability to network observability when not referencing the Operator
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-con_filter-network-flows-at-ingestion.adoc
  modules/network-observability-create-network-policy.adoc
  modules/network-observability-deploy-network-policy.adoc
  modules/network-observability-ebpf-agent-alert.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-metrics-names.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-resource-recommendations.adoc
  modules/network-observability-viewing-dashboards.adoc
  modules/network-observability-without-loki.adoc
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/troubleshooting-network-observability.adoc
Labels: size/M, branch/enterprise-4.12, merge-review-in-progress

#97033 [enterprise-4.15] [NETOBSERV] OSDOCS-15495 Vale updates for network-observability-loki-installation.adoc
  modules/network-observability-loki-install.adoc
Labels: size/XS, merge-review-in-progress

#97040 [enterprise-4.14] OSDOCS-14543 [NETOBSERV] Change Network Observability to network observability when not referencing the Operator
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-con_filter-network-flows-at-ingestion.adoc
  modules/network-observability-create-network-policy.adoc
  modules/network-observability-deploy-network-policy.adoc
  modules/network-observability-ebpf-agent-alert.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-metrics-names.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-resource-recommendations.adoc
  modules/network-observability-viewing-dashboards.adoc
  modules/network-observability-without-loki.adoc
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/troubleshooting-network-observability.adoc
Labels: size/M, merge-review-in-progress

#97041 [enterprise-4.15] OSDOCS-14543 [NETOBSERV] Change Network Observability to network obse…
  modules/network-observability-cli-capturing-metrics.adoc
  modules/network-observability-create-network-policy.adoc
  modules/network-observability-deploy-network-policy.adoc
  modules/network-observability-ebpf-agent-alert.adoc
  modules/network-observability-flowcollector-view.adoc
  modules/network-observability-metrics-names.adoc
  modules/network-observability-multitenancy.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-resource-recommendations.adoc
  modules/network-observability-tcp-flag-syn-flood.adoc
  modules/network-observability-viewing-dashboards.adoc
  modules/network-observability-without-loki.adoc
  modules/troubleshooting-network-observability-after-installation.adoc
  modules/troubleshooting-network-observability-controller-manager-pod-out-of-memory.adoc
  modules/troubleshooting-network-observability-loki-resource-exhausted.adoc
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/troubleshooting-network-observability.adoc
Labels: size/M, merge-review-in-progress

#96006 [OSDOCS-14938]: HCP 4.19 release notes
  _unused_topics/hosted-control-planes-release-notes.adoc
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: peer-review-done, lgtm, size/L, ok-to-merge, branch/enterprise-4.19, branch/enterprise-4.20

#97047 [enterprise-4.19][OSDOCS-14938]: HCP 4.19 release notes
  _unused_topics/hosted-control-planes-release-notes.adoc
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: size/L

#97048 [enterprise-4.20][OSDOCS-14938]: HCP 4.19 release notes
  _unused_topics/hosted-control-planes-release-notes.adoc
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: size/L

#96367 OSDOCS#14018: Configuring node pool capacity blocks in HCP
  hosted_control_planes/hcp-manage/hcp-manage-aws.adoc
  modules/hcp-np-capacity-blocks-destroy.adoc
  modules/hcp-np-capacity-blocks.adoc
Labels: size/L, ok-to-merge, branch/enterprise-4.19, branch/enterprise-4.20

#95155 [OSDOCS-15034]: Updating links in HCP/MCE content to latest ACM version
  architecture/mce-overview-ocp.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-bm.adoc
  hosted_control_planes/hcp-disconnected/hcp-deploy-dc-virt.adoc
  hosted_control_planes/hcp-machine-config.adoc
  hosted_control_planes/hcp-prepare/hcp-requirements.adoc
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-dc-image-mirror.adoc
  modules/hcp-dr-oadp-restore.adoc
  modules/hcp-get-upgrade-versions.adoc
  modules/hcp-non-bm-prereqs.adoc
  modules/hosted-control-planes-concepts-personas.adoc
  modules/hosted-control-planes-overview.adoc
Labels: size/M, branch/enterprise-4.19, branch/enterprise-4.20

#96777 OCPBUGS 59892 Update Description for READYMACHINECOUNT
  modules/checking-mco-status.adoc
Labels: size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97012 TELCODOCS#2397
  modules/nw-metallb-frr-k8s-configuration-crd.adoc
Labels: lgtm, size/M

#97066 OSDOCS#15662: RN for node pool capacity blocks feature
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.19, branch/enterprise-4.20

#96640 [enterprise-4.16] OBSDOCS-2209: Place a redirect notice on OCP logging docs
  _topic_maps/_topic_map.yml
  observability/logging/logging-6.0/log6x-about-logging.adoc
  observability/logging/logging-6.1/log6x-about-logging.adoc
  observability/logging/logging-6.2/log6x-about-logging.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-components.adoc
Labels: size/L, jira/valid-reference

#96908 add vale DITA rule
  .gitignore
  .vale.ini
Labels: size/XS

#96169 OSDOCS-13052: updates and clarifies API server custom CAs MicroShift
  microshift_configuring/microshift_auth_security/microshift-custom-ca.adoc
  modules/microshift-custom-ca-con.adoc
  modules/microshift-custom-ca-proc.adoc
Labels: size/M, ok-to-merge, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#97092 add vale DITA rule to modules vale.ini
  modules/.vale.ini
Labels: size/XS

#96933 OBSDOCS-1576: Update any YAML blocks affected by the API change in the linked PR
  modules/log-collector-http-server.adoc
  modules/logging-delivery-tuning.adoc
Labels: size/S, jira/valid-reference

#97101 [enterprise-4.18] OBSDOCS-2224b: fix xref in 'Storing and recording data'
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
Labels: size/XS

#97102 [enterprise-4.17] OBSDOCS-2224b: fix xref in 'Storing and recording data'
  observability/monitoring/configuring-core-platform-monitoring/storing-and-recording-data.adoc
  observability/monitoring/configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
Labels: size/XS

#97059 OBSDOCS-2252: Vale dita compatibility assessment - verify assemblies
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/preparing-to-configure-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/getting-started/maintenance-and-support-for-monitoring.adoc
  observability/monitoring/getting-started/sd-accessing-monitoring-for-user-defined-projects.adoc
  observability/monitoring/getting-started/sd-disabling-monitoring-for-user-defined-projects.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97108 [enterprise-4.18] OBSDOCS-2224a: fix oc CLI attribute
  modules/monitoring-accessing-alerting-rules-for-your-project.adoc
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-choosing-a-metrics-collection-profile.adoc
  modules/monitoring-configuring-a-persistent-volume-claim.adoc
  modules/monitoring-configuring-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-configuring-alert-routing-user-defined-alerts-secret.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-configuring-pod-topology-spread-constraints.adoc
  modules/monitoring-configuring-remote-write-storage.adoc
  modules/monitoring-creating-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  modules/monitoring-creating-cross-project-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-creating-new-alerting-rules.adoc
  modules/monitoring-creating-scrape-sample-alerts.adoc
  modules/monitoring-creating-user-defined-workload-monitoring-configmap.adoc
  modules/monitoring-determining-why-prometheus-is-consuming-disk-space.adoc
  modules/monitoring-disabling-cross-project-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-disabling-the-local-alertmanager.adoc
  modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
  modules/monitoring-enabling-query-logging-for-thanos-querier.adoc
  modules/monitoring-enabling-the-platform-alertmanager-instance-for-user-defined-alert-routing.adoc
  modules/monitoring-granting-users-permission-to-configure-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-granting-users-permission-to-configure-monitoring-for-user-defined-projects.adoc
  modules/monitoring-installation-progress.adoc
  modules/monitoring-listing-alerting-rules-for-all-projects-in-a-single-view.adoc
  modules/monitoring-modifying-core-platform-alerting-rules.adoc
  modules/monitoring-modifying-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-modifying-the-retention-time-for-thanos-ruler-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-querying-metrics-by-using-the-federation-endpoint-for-prometheus.adoc
  modules/monitoring-querying-metrics-for-all-projects-with-mon-dashboard.adoc
  modules/monitoring-removing-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-resizing-a-persistent-volume.adoc
  modules/monitoring-resolving-the-kubepersistentvolumefillingup-alert-firing-for-prometheus.adoc
  modules/monitoring-setting-audit-log-levels-for-the-prometheus-adapter.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-query-log-file-for-prometheus.adoc
  modules/monitoring-setting-scrape-and-evaluation-intervals-limits-for-user-defined-projects.adoc
  modules/monitoring-setting-the-body-size-limit-for-metrics-scraping.adoc
  modules/monitoring-specifying-limits-and-requests-for-monitoring-components.adoc
Labels: size/M

#97112 [enterprise-4.14] OBSDOCS-2224a: fix oc CLI attribute
  modules/monitoring-accessing-alerting-rules-for-your-project.adoc
  modules/monitoring-adding-a-secret-to-the-alertmanager-configuration.adoc
  modules/monitoring-assigning-tolerations-to-monitoring-components.adoc
  modules/monitoring-attaching-additional-labels-to-your-time-series-and-alerts.adoc
  modules/monitoring-choosing-a-metrics-collection-profile.adoc
  modules/monitoring-configuring-a-persistent-volume-claim.adoc
  modules/monitoring-configuring-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-configuring-alert-routing-user-defined-alerts-secret.adoc
  modules/monitoring-configuring-external-alertmanagers.adoc
  modules/monitoring-configuring-pod-topology-spread-constraints.adoc
  modules/monitoring-configuring-remote-write-storage.adoc
  modules/monitoring-creating-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-creating-cluster-id-labels-for-metrics.adoc
  modules/monitoring-creating-cluster-monitoring-configmap.adoc
  modules/monitoring-creating-new-alerting-rules.adoc
  modules/monitoring-creating-scrape-sample-alerts.adoc
  modules/monitoring-creating-user-defined-workload-monitoring-configmap.adoc
  modules/monitoring-determining-why-prometheus-is-consuming-disk-space.adoc
  modules/monitoring-disabling-the-local-alertmanager.adoc
  modules/monitoring-enabling-monitoring-for-user-defined-projects.adoc
  modules/monitoring-enabling-query-logging-for-thanos-querier.adoc
  modules/monitoring-enabling-the-platform-alertmanager-instance-for-user-defined-alert-routing.adoc
  modules/monitoring-granting-users-permission-to-configure-alert-routing-for-user-defined-projects.adoc
  modules/monitoring-granting-users-permission-to-configure-monitoring-for-user-defined-projects.adoc
  modules/monitoring-installation-progress.adoc
  modules/monitoring-listing-alerting-rules-for-all-projects-in-a-single-view.adoc
  modules/monitoring-modifying-core-platform-alerting-rules.adoc
  modules/monitoring-modifying-retention-time-and-size-for-prometheus-metrics-data.adoc
  modules/monitoring-modifying-the-retention-time-for-thanos-ruler-metrics-data.adoc
  modules/monitoring-moving-monitoring-components-to-different-nodes.adoc
  modules/monitoring-querying-metrics-by-using-the-federation-endpoint-for-prometheus.adoc
  modules/monitoring-querying-metrics-for-all-projects-with-mon-dashboard.adoc
  modules/monitoring-removing-alerting-rules-for-user-defined-projects.adoc
  modules/monitoring-resizing-a-persistent-volume.adoc
  modules/monitoring-resolving-the-kubepersistentvolumefillingup-alert-firing-for-prometheus.adoc
  modules/monitoring-setting-audit-log-levels-for-the-prometheus-adapter.adoc
  modules/monitoring-setting-log-levels-for-monitoring-components.adoc
  modules/monitoring-setting-query-log-file-for-prometheus.adoc
  modules/monitoring-setting-scrape-sample-and-label-limits-for-user-defined-projects.adoc
  modules/monitoring-setting-the-body-size-limit-for-metrics-scraping.adoc
  modules/monitoring-specifying-limits-and-requests-for-monitoring-components.adoc
Labels: size/M

#96098 OADP-1791: Added suggestions for the backup types
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
Labels: size/XS, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97128 [enterprise-4.18] OADP-1791: Added suggestions for the backup types
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
Labels: size/XS, jira/valid-reference

#97115 [enterprise-4.18] OBSDOCS-2252: Vale dita compatibility assessment - verify assemblies
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/preparing-to-configure-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/getting-started/maintenance-and-support-for-monitoring.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
  observability/monitoring/sd-accessing-monitoring-for-user-defined-projects.adoc
  observability/monitoring/sd-disabling-monitoring-for-user-defined-projects.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: size/M, jira/valid-reference

#97117 [enterprise-4.16] OBSDOCS-2252: Vale dita compatibility assessment - verify assemblies
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/preparing-to-configure-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/getting-started/maintenance-and-support-for-monitoring.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
  observability/monitoring/sd-accessing-monitoring-for-user-defined-projects.adoc
  observability/monitoring/sd-disabling-monitoring-for-user-defined-projects.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: size/M, jira/valid-reference

#97120 [enterprise-4.14] OBSDOCS-2252: Vale dita compatibility assessment - verify assemblies
  observability/monitoring/about-ocp-monitoring/key-concepts.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  observability/monitoring/configuring-core-platform-monitoring/preparing-to-configure-the-monitoring-stack.adoc
  observability/monitoring/configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  observability/monitoring/getting-started/maintenance-and-support-for-monitoring.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-a-developer.adoc
  observability/monitoring/managing-alerts/managing-alerts-as-an-administrator.adoc
  observability/monitoring/sd-accessing-monitoring-for-user-defined-projects.adoc
  observability/monitoring/sd-disabling-monitoring-for-user-defined-projects.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: size/M, jira/valid-reference

#96996 OCPBUGS-54709: Fixed the link to Assisted Installer docs on the Aliba…
  installing/installing_alibaba/installing-alibaba-assisted-installer.adoc
Labels: size/XS, jira/severity-moderate, jira/invalid-bug, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96787 OSSM-9881 Update version support table for 3.1
  _attributes/common-attributes.adoc
  install/ossm-supported-platforms-configurations.adoc
  modules/ossm-release-notes-3-1-new-features-enhancements.adoc
  modules/ossm-release-notes-supported-versions.adoc
  observability/kiali/ossm-console-plugin.adoc
Labels: size/M, service-mesh

#97133 Initialize CCO standalone docs so they will build
  _attributes/common-attributes.adoc
  _distro_map.yml
  _topic_maps/_topic_map.yml
  about/about-cluster-observability-operator.adoc
  about/about-standalone.adoc
Labels: size/M

#97148 [enterprise-4.16] CNV-66175: Removed virtctl prereq and command from NIC hot plug proce…
  modules/virt-hot-plugging-bridge-network-interface-cli.adoc
Labels: size/S, jira/valid-reference

#97154 CP-OSDOCS-15233: RFE-bootc image mode for RHEL
  microshift_install_bootc/microshift-about-rhel-image-mode.adoc
  modules/microshift-install-bootc-build-image.adoc
  modules/microshift-preparing-for-image-building-bootc.adoc
Labels: lgtm, size/S, jira/valid-reference, branch/enterprise-4.20

#96824 OSDOCS#15587: CQA updates
  modules/cli-logging-in-kubeadmin.adoc
  modules/cluster-entitlements.adoc
  modules/configuring-vsphere-regions-zones.adoc
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
  modules/installation-launching-installer.adoc
  modules/installation-registry-storage-block-recreate-rollout.adoc
  modules/ipi-install-modifying-install-config-for-dual-stack-network.adoc
  modules/registry-configuring-storage-vsphere.adoc
Labels: size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97211 [enterprise-4.20] OSDOCS#15433: Updated the default namespace LVMS to openshift-lvm-storage
  modules/lvms-creating-lvmcluster-using-rhacm.adoc
  modules/lvms-creating-lvms-cluster-using-cli.adoc
  modules/lvms-creating-lvms-cluster-using-web-console.adoc
  modules/lvms-deleting-lvmcluster-using-cli.adoc
  modules/lvms-deleting-lvmcluster-using-rhacm.adoc
  modules/lvms-deleting-lvmcluster-using-web-console.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-cli.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-openshift-web-console.adoc
  modules/lvms-installing-logical-volume-manager-operator-using-rhacm.adoc
  modules/lvms-scaling-storage-of-clusters-using-rhacm.adoc
  modules/lvms-scaling-storage-of-clusters-using-web-console.adoc
  modules/lvms-troubleshooting-performing-a-forced-cleanup.adoc
  modules/lvms-troubleshooting-recovering-from-missing-lvms-or-operator-components.adoc
  modules/lvms-troubleshooting-recovering-from-node-failure.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-openshift-web-console.adoc
  modules/lvms-uninstalling-logical-volume-manager-operator-using-rhacm.adoc
  modules/lvms-updating-lvms.adoc
Labels: size/M, branch/enterprise-4.20

#95714 [OSDOCS-15132]Improve the ROSA docs for secure auth flows (XCMSTRAT-600)
  modules/rosa-configure.adoc
  support/troubleshooting/sd-red
Labels: size/M

#96464 OSDOCS-15470: Removed low-level example output blocks from Network Op…
  modules/configuring-egress-proxy-edns-operator.adoc
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  modules/nw-autoscaling-ingress-controller.adoc
  modules/nw-aws-load-balancer-operator.adoc
  modules/nw-bpfman-operator-deploy.adoc
  modules/nw-control-dns-records-public-hosted-zone-aws.adoc
  modules/nw-control-dns-records-public-managed-zone-gcp.adoc
  modules/nw-dns-cache-tuning.adoc
  modules/nw-dns-forward.adoc
  modules/nw-dns-operator-managementState.adoc
  modules/nw-dns-view.adoc
  modules/nw-dpu-configuring-operator.adoc
  modules/nw-dpu-installing-operator-cli.adoc
  modules/nw-dpu-operator-uninstall.adoc
  modules/nw-external-dns-operator.adoc
  modules/nw-ingress-configuring-application-domain.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  modules/nw-installing-external-dns-operator-cli.adoc
  modules/nw-metalLB-basic-upgrade-operator.adoc
  modules/nw-metallb-installing-operator-cli.adoc
  modules/nw-scaling-ingress-controller.adoc
  modules/nw-sriov-installing-operator.adoc
Labels: lgtm, size/L, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97063 OBSDOCS-2221: Logging Z-Stream Release Notes - 6.2.4
  modules/logging-release-notes-6-2-4.adoc
  release_notes/logging-release-notes-6.2.adoc
Labels: size/S, jira/valid-reference

#97222 [enterprise-4.19] OSDOCS-15470: Removed low-level example output blocks from Network Op…
  modules/configuring-egress-proxy-edns-operator.adoc
  modules/k8s-nmstate-deploying-nmstate-CLI.adoc
  modules/k8s-nmstate-installing-the-kubernetes-nmstate-operator.adoc
  modules/nw-autoscaling-ingress-controller.adoc
  modules/nw-aws-load-balancer-operator.adoc
  modules/nw-bpfman-operator-deploy.adoc
  modules/nw-control-dns-records-public-hosted-zone-aws.adoc
  modules/nw-control-dns-records-public-managed-zone-gcp.adoc
  modules/nw-dns-cache-tuning.adoc
  modules/nw-dns-forward.adoc
  modules/nw-dns-operator-managementState.adoc
  modules/nw-dns-view.adoc
  modules/nw-dpu-configuring-operator.adoc
  modules/nw-dpu-installing-operator-cli.adoc
  modules/nw-dpu-operator-uninstall.adoc
  modules/nw-external-dns-operator.adoc
  modules/nw-ingress-configuring-application-domain.adoc
  modules/nw-ingress-setting-a-custom-default-certificate.adoc
  modules/nw-installing-external-dns-operator-cli.adoc
  modules/nw-metalLB-basic-upgrade-operator.adoc
  modules/nw-metallb-installing-operator-cli.adoc
  modules/nw-scaling-ingress-controller.adoc
  modules/nw-sriov-installing-operator.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.19

#97152 OSDOCS-15287 [NETOBSERV] Line breaks for observing-network-traffic.adoc assembly and its includes
  modules/network-observability-RTT-overview.adoc
  modules/network-observability-RTT.adoc
  modules/network-observability-configuring-options-overview.adoc
  modules/network-observability-configuring-options-topology.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-dns-overview.adoc
  modules/network-observability-dns-tracking.adoc
  modules/network-observability-ebpf-rule-flow-filter.adoc
  modules/network-observability-filtering-ebpf-rule.adoc
  modules/network-observability-flow-filter-parameters.adoc
  modules/network-observability-histogram-trafficflow.adoc
  modules/network-observability-network-traffic-overview-view.adoc
  modules/network-observability-packet-drops.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-pktdrop-overview.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-topology.adoc
  modules/network-observability-trafficflow.adoc
  modules/network-observability-working-with-conversations.adoc
  modules/network-observability-working-with-overview.adoc
  modules/network-observability-working-with-topology.adoc
  modules/network-observability-working-with-trafficflow.adoc
  modules/network-observability-working-with-zones.adoc
Labels: size/M

#97050 OCPBUGS-60065# Add RN for automatic CNS volume deletion.
  release_notes/ocp-4-19-release-notes.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.19

#96099 OSDOCS 15312 removing cli manager 0.1.0 from ocp 4.19
  cli_reference/cli_manager/cli-manager-release-notes.adoc
Labels: peer-review-in-progress, lgtm, size/S

#97093 OSDOCS#13788: Added info for cache and workspace directories in oc-mirror doc
  disconnected/mirroring/about-installing-oc-mirror-v2.adoc
  modules/oc-mirror-about-cache-and-workspace-dirs.adoc
  modules/oc-mirror-command-reference-v2-delete.adoc
  modules/oc-mirror-command-reference-v2.adoc
Labels: size/M, qe-approved, merge-review-in-progress, branch/enterprise-4.19, branch/enterprise-4.20

#96350 Release notes for LVMS
  release_notes/ocp-4-20-release-notes.adoc
Labels: lgtm, size/S, merge-review-needed

#97185 OSDOCS#15617: Update the z-stream release notes for 4.15.56
  release_notes/ocp-4-15-release-notes.adoc
Labels: size/S, merge-review-in-progress, branch/enterprise-4.15

#97153 OSDOCS#59806: Correct the bug text for OCPBUGS-55016 for 4.18
  release_notes/ocp-4-18-release-notes.adoc
Labels: lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.18

#97150 OSDOCS-15679: Added missing underscore to {context} attributes
  disconnected/updating/uninstalling-osus.adoc
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/configuring-machine-pool-disk-volume-ocm.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
  modules/k8s-nmstate-troubleshooting-dns-disconnected-env-resolv.adoc
  modules/logging-release-notes-5-8-0.adoc
  modules/logging-release-notes-5-8-1.adoc
  modules/logging-release-notes-5-8-2.adoc
  modules/logging-release-notes-5-9-0.adoc
  modules/logging-release-notes-5-9-1.adoc
  modules/logging-rn-5.7.0.adoc
  modules/microshift-disconnected-host-con.adoc
  modules/monitoring-shiftstack-metrics.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-viewing-network-events.adoc
  modules/network-observability-working-with-zones.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/persistent-storage-csi-vsphere-encryption-datastore-url.adoc
  modules/persistent-storage-csi-vsphere-encryption-tag-based.adoc
  modules/persistent-storage-csi-vsphere-limitations.adoc
  modules/persistent-storage-csi-vsphere-top-aware-during-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-infra-top.adoc
  modules/persistent-storage-csi-vsphere-top-aware-overview.adoc
  modules/persistent-storage-csi-vsphere-top-aware-post-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-results.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-imds.adoc
  modules/rosa-update-cli-tool.adoc
  modules/sdpolicy-networking.adoc
  modules/sre-cluster-access.adoc
  modules/update-conditional-updates.adoc
  modules/virt-about-dv-conditions-and-events.adoc
  modules/virt-deprecated-tasks-web.adoc
  modules/virt-linux-bridge-nad-port-isolation.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  updating/understanding_updates/understanding-update-channels-release.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
Labels: lgtm, size/L, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97258 OCPBUGS-60065pt2# Remove note about necessary manual deletion of vsphere volumes.
  installing/installing_vsphere/uninstalling-cluster-vsphere-installer-provisioned.adoc
Labels: lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.19, branch/enterprise-4.20

#97199 OSDOCS#15157: Release notes for the cert-manager Operator v1.17.0
  security/cert_manager_operator/cert-manager-operator-release-notes.adoc
Labels: size/M, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97295 [enterprise-4.18] OSDOCS-15679: Added missing underscore to {context} attributes
  disconnected/updating/uninstalling-osus.adoc
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/configuring-machine-pool-disk-volume-ocm.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
  modules/logging-release-notes-5-8-0.adoc
  modules/logging-release-notes-5-8-1.adoc
  modules/logging-release-notes-5-8-2.adoc
  modules/logging-release-notes-5-9-0.adoc
  modules/logging-release-notes-5-9-1.adoc
  modules/logging-rn-5.7.0.adoc
  modules/microshift-disconnected-host-con.adoc
  modules/monitoring-shiftstack-metrics.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-viewing-network-events.adoc
  modules/network-observability-working-with-zones.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/persistent-storage-csi-vsphere-encryption-datastore-url.adoc
  modules/persistent-storage-csi-vsphere-encryption-tag-based.adoc
  modules/persistent-storage-csi-vsphere-limitations.adoc
  modules/persistent-storage-csi-vsphere-top-aware-during-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-infra-top.adoc
  modules/persistent-storage-csi-vsphere-top-aware-overview.adoc
  modules/persistent-storage-csi-vsphere-top-aware-post-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-results.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-imds.adoc
  modules/rosa-update-cli-tool.adoc
  modules/sdpolicy-networking.adoc
  modules/sre-cluster-access.adoc
  modules/update-conditional-updates.adoc
  modules/virt-about-dv-conditions-and-events.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  updating/understanding_updates/understanding-update-channels-release.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.18

#97300 [enterprise-4.16] OSDOCS-15679: Added missing underscore to {context} attributes
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/configuring-machine-pool-disk-volume-ocm.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
  modules/logging-release-notes-5-8-0.adoc
  modules/logging-release-notes-5-8-1.adoc
  modules/logging-release-notes-5-8-2.adoc
  modules/logging-release-notes-5-9-0.adoc
  modules/logging-release-notes-5-9-1.adoc
  modules/logging-rn-5.7.0.adoc
  modules/microshift-disconnected-host-con.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-working-with-zones.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/persistent-storage-csi-vsphere-encryption-datastore-url.adoc
  modules/persistent-storage-csi-vsphere-encryption-tag-based.adoc
  modules/persistent-storage-csi-vsphere-limitations.adoc
  modules/persistent-storage-csi-vsphere-top-aware-during-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-infra-top.adoc
  modules/persistent-storage-csi-vsphere-top-aware-overview.adoc
  modules/persistent-storage-csi-vsphere-top-aware-post-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-results.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-imds.adoc
  modules/rosa-update-cli-tool.adoc
  modules/sdpolicy-networking.adoc
  modules/sre-cluster-access.adoc
  modules/update-conditional-updates.adoc
  modules/virt-about-dv-conditions-and-events.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  updating/understanding_updates/understanding-update-channels-release.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
  updating/updating_a_cluster/updating_disconnected_cluster/uninstalling-osus.adoc
Labels: size/L, branch/enterprise-4.16

#97310 [enterprise-4.13] OSDOCS-15679: Added missing underscore to {context} attributes
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/configuring-machine-pool-disk-volume-cli.adoc
  modules/configuring-machine-pool-disk-volume-ocm.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
  modules/deleting-machine-pools-cli.adoc
  modules/deleting-machine-pools-ocm.adoc
  modules/deleting-machine-pools.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
  modules/logging-release-notes-5-8-0.adoc
  modules/logging-release-notes-5-8-1.adoc
  modules/logging-release-notes-5-8-2.adoc
  modules/logging-release-notes-5-9-0.adoc
  modules/logging-release-notes-5-9-1.adoc
  modules/logging-rn-5.7.0.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-working-with-zones.adoc
  modules/oadp-usecase-kopia-override-algorithms.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/persistent-storage-csi-vsphere-encryption-datastore-url.adoc
  modules/persistent-storage-csi-vsphere-encryption-tag-based.adoc
  modules/persistent-storage-csi-vsphere-limitations.adoc
  modules/persistent-storage-csi-vsphere-top-aware-during-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-infra-top.adoc
  modules/persistent-storage-csi-vsphere-top-aware-overview.adoc
  modules/persistent-storage-csi-vsphere-top-aware-post-install.adoc
  modules/persistent-storage-csi-vsphere-top-aware-results.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-imds.adoc
  modules/rosa-update-cli-tool.adoc
  modules/sdpolicy-networking.adoc
  modules/update-conditional-updates.adoc
  modules/virt-about-dv-conditions-and-events.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-restricted-network-cluster/uninstalling-osus.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.13

#97311 [enterprise-4.12] OSDOCS-15679: Added missing underscore to {context} attributes
  modules/cnf-du-configuring-a-performance-profile-to-support-workload-partitioning.adoc
  modules/cnf-du-management-pods.adoc
  modules/configuring-vsphere-verifying-configuration.adoc
  modules/eco-self-node-remediation-operator-troubleshooting.adoc
  modules/gitops-default-permissions-of-an-argocd-instance.adoc
  modules/gitops-using-argo-cd-instance-to-manage-cluster-scoped-resources.adoc
  modules/helm-adding-namespace-scoped-helm-chart-repositories.adoc
  modules/logging-release-notes-5-8-0.adoc
  modules/logging-release-notes-5-8-1.adoc
  modules/logging-release-notes-5-8-2.adoc
  modules/logging-rn-5.7.0.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/network-observability-nodes-taints-tolerations.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-working-with-zones.adoc
  modules/op-disabling-tekton-hub-authorization-after-upgrade.adoc
  modules/op-installing-tekton-hub-without-login-and-rating.adoc
  modules/op-interacting-pipelines-from-topology-view.adoc
  modules/op-starting-pipelines-from-topology-view.adoc
  modules/osd-aws-privatelink-architecture.adoc
  modules/persistent-storage-csi-vsphere-limitations.adoc
  modules/rosa-update-cli-tool.adoc
  modules/sdpolicy-networking.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  updating/index.adoc
  updating/understanding-upgrade-channels-release.adoc
  updating/updating-cluster-cli.adoc
  updating/updating-restricted-network-cluster/uninstalling-osus.adoc
Labels: size/M, branch/enterprise-4.12

#97184 [OSDOCS-15316]: Revising formatting in HCP bare metal docs
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  modules/hcp-bm-hc-console.adoc
  modules/hcp-bm-hc-mirror.adoc
Labels: size/S, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97038 OSDOCS 15615 Clarity on bootimage changes on AWS and GCP
  modules/mco-update-boot-images-about.adoc
  modules/mco-update-boot-images-configuring.adoc
  modules/mco-update-boot-images-disable.adoc
  snippets/mco-update-boot-images-verification.adoc
Labels: size/L, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97317 [enterprise-4.18]No Jira: Revising formatting in HCP bare metal docs
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  modules/hcp-bm-hc-console.adoc
  modules/hcp-bm-hc-mirror.adoc
Labels: size/S

#97326 [enterprise-4.17] OSDOCS 15615 Clarity on bootimage changes on AWS and GCP
  machine_configuration/mco-update-boot-images.adoc
  modules/mco-update-boot-images-configuring.adoc
Labels: size/M

#97324 [enterprise-4.15] CNV#39976for415: Fix for cherrypicking issue in CNV-39976
  modules/virt-about-storage-volumes-for-vm-disks.adoc
  virt/about_virt/about-virt.adoc
Labels: size/XS, CNV, branch/enterprise-4.15

#96515 RHDEVDOCS-6452: Content creation for GitOps 1.17 RN
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/gitops-release-notes-1-17-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
  release_notes/gitops-release-notes-1-17.adoc
Labels: size/L, jira/valid-reference

#97044 OSDOCS-15618 created 4.17.37 z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: size/M, merge-review-in-progress, branch/enterprise-4.17

#97212 RHDEVDOCS-6522: Updating YAML for eventListener RN in Pipelines 1.19
  modules/op-release-notes-1-19.adoc
Labels: lgtm, size/S, merge-review-in-progress, jira/valid-reference

#97247 [enterprise-4.15] OSDOCS-15287 [NETOBSERV] Line breaks for observing-network-traffic.adoc assembly and its includes
  modules/network-observability-RTT-overview.adoc
  modules/network-observability-RTT.adoc
  modules/network-observability-configuring-options-overview.adoc
  modules/network-observability-configuring-options-topology.adoc
  modules/network-observability-configuring-options-trafficflow.adoc
  modules/network-observability-dns-overview.adoc
  modules/network-observability-dns-tracking.adoc
  modules/network-observability-ebpf-rule-flow-filter.adoc
  modules/network-observability-filtering-ebpf-rule.adoc
  modules/network-observability-flow-filter-parameters.adoc
  modules/network-observability-histogram-trafficflow.adoc
  modules/network-observability-network-traffic-overview-view.adoc
  modules/network-observability-packet-drops.adoc
  modules/network-observability-packet-translation-overview.adoc
  modules/network-observability-packet-translation.adoc
  modules/network-observability-pktdrop-overview.adoc
  modules/network-observability-quickfilter.adoc
  modules/network-observability-topology.adoc
  modules/network-observability-trafficflow.adoc
  modules/network-observability-working-with-conversations.adoc
  modules/network-observability-working-with-overview.adoc
  modules/network-observability-working-with-topology.adoc
  modules/network-observability-working-with-trafficflow.adoc
  modules/network-observability-working-with-zones.adoc
Labels: size/M

#97254 OLS-1990 removed virtual machine, OKE is now a subscription service
  modules/ols-about-subscription-requirements.adoc
Labels: size/XS

#96619 Update Collector troubleshooting guide
  modules/failing-to-load-the-ebpf-probe.adoc
  modules/failing-to-load-the-kernel-driver.adoc
  modules/unable-to-connect-to-the-sensor.adoc
  troubleshooting/commonly-occurring-error-conditions.adoc
Labels: peer-review-done, size/L, RHACS

#97272 [WIP] OCPBUGS#59683: OLMv1: Fix CRD update check spec
  modules/disabling-crd-preflight.adoc
Labels: lgtm, size/M, do-not-merge/work-in-progress, qe-approved, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96815 OSDOCS-14097: Review: Cluster administration - Classic to HCP migration
  modules/creating-a-machine-pool-ocm.adoc
  modules/dedicated-aws-dc-existing.adoc
  modules/dedicated-aws-dc-hvif.adoc
  modules/dedicated-aws-vpc-configuring-routing-tables.adoc
  modules/dedicated-aws-vpc-initiating-peering.adoc
  modules/dedicated-aws-vpn-creating.adoc
  modules/dedicated-aws-vpn-verifying.adoc
  modules/machine-pools-hcp.adoc
  modules/nodes-cluster-resource-configure-oom.adoc
  modules/nodes-cluster-resource-configure-request-limit.adoc
  modules/removing-custom-config-from-machinepool.adoc
  modules/rosa-adding-node-labels.adoc
  modules/rosa-adding-tags-cli.adoc
  modules/rosa-adding-tags.adoc
  modules/rosa-adding-taints-cli.adoc
  modules/rosa-adding-taints-ocm.adoc
  modules/rosa-adding-taints.adoc
  modules/rosa-adding-tuning.adoc
  modules/rosa-autorepair-cli.adoc
  modules/rosa-cluster-autoscaler-cli-edit.adoc
  modules/setting-higher-pid-limit-on-machinepool.adoc
  rosa_cluster_admin/rosa-cluster-autoscaling-hcp.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-machinepools-about.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#97321 add package addition to modules vale.ini
  .vale.ini
  modules/.vale.ini
Labels: size/XS

#97345 MCO Backport OCL to 4.18 part II
  machine_configuration/mco-coreos-layering.adoc
Labels: size/XS, branch/enterprise-4.18

#97369 Fix missing newline at end of topic map
  _topic_maps/_topic_map.yml
Labels: size/XS

#97279 OBSDOCS-2273 migrate main content, fix xrefs
  _attributes/common-attributes.adoc
  _distro_map.yml
  _topic_maps/_topic_map.yml
  about/about-cluster-observability-operator.adoc
  about/cluster-observability-operator-overview.adoc
  about/cluster-observability-operator-release-notes.adoc
  about/docinfo.xml
  images/app-launcher.png
  images/coo-custom-dashboard.png
  images/coo-incident-alerts-components-expanded.png
  images/coo-incident-alerts-components.png
  images/coo-incident-alerts-timeline.png
  images/coo-incidents-timeline-daily.png
  images/coo-incidents-timeline-weekly.png
  images/coo-incidents-timeline.png
  images/coo-troubleshooting-experimental.png
  images/coo-troubleshooting-panel-graph.png
  images/coo-troubleshooting-panel-link.png
  images/kebab.png
  installing/_attributes
  installing/configuring-the-cluster-observability-operator-to-monitor-a-service.adoc
  installing/docinfo.xml
  installing/images
  installing/installing-the-cluster-observability-operator.adoc
  installing/modules
  installing/snippets
  modules/coo-advantages.adoc
  modules/coo-dashboard-ui-plugin-configure.adoc
  modules/coo-dashboard-ui-plugin-install.adoc
  modules/coo-distributed-tracing-ui-plugin-install.adoc
  modules/coo-distributed-tracing-ui-plugin-using.adoc
  modules/coo-incident-detection-overview.adoc
  modules/coo-incident-detection-using.adoc
  modules/coo-logging-ui-plugin-install.adoc
  modules/coo-monitoring-ui-plugin-install.adoc
  modules/coo-server-side-apply.adoc
  modules/coo-target-users.adoc
  modules/coo-troubleshooting-ui-plugin-creating-alert.adoc
  modules/coo-troubleshooting-ui-plugin-install.adoc
  modules/coo-troubleshooting-ui-plugin-using.adoc
  modules/coo-versus-default-ocp-monitoring.adoc
  modules/monitoring-creating-a-monitoringstack-object-for-cluster-observability-operator.adoc
  modules/monitoring-deploying-a-sample-service-for-cluster-observability-operator.adoc
  modules/monitoring-installing-cluster-observability-operator-using-the-web-console.adoc
  modules/monitoring-specifying-how-a-service-is-monitored-by-cluster-observability-operator.adoc
  modules/monitoring-uninstalling-cluster-observability-operator-using-the-web-console.adoc
  modules/monitoring-validating-a-monitoringstack-for-cluster-observability-operator.adoc
  snippets/technology-preview.adoc
  ui_plugins/_attributes
  ui_plugins/dashboard-ui-plugin.adoc
  ui_plugins/distributed-tracing-ui-plugin.adoc
  ui_plugins/docinfo.xml
  ui_plugins/images
  ui_plugins/logging-ui-plugin.adoc
  ui_plugins/modules
  ui_plugins/monitoring-ui-plugin.adoc
  ui_plugins/observability-ui-plugins-overview.adoc
  ui_plugins/snippets
  ui_plugins/troubleshooting-ui-plugin.adoc
Labels: size/XXL

#97389 [enterprise-4.16] OSDOCS-15731 [NETOBSERV] Add space between each include in all assemblies
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/metrics-alerts-dashboards.adoc
  observability/network_observability/network-observability-network-policy.adoc
  observability/network_observability/network-observability-operator-monitoring.adoc
  observability/network_observability/observing-network-traffic.adoc
Labels: size/M

#97379 OSDOCS-15305 [NETOBSERV] Update nw-network-observability-operator to fit proc template
  modules/nw-network-observability-operator.adoc
Labels: size/XS, branch/enterprise-4.12, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97388 [enterprise-4.15] OSDOCS-15731 [NETOBSERV] Add space between each include in all assemblies
  observability/network_observability/configuring-operator.adoc
  observability/network_observability/installing-operators.adoc
  observability/network_observability/metrics-alerts-dashboards.adoc
  observability/network_observability/network-observability-network-policy.adoc
  observability/network_observability/network-observability-operator-monitoring.adoc
  observability/network_observability/observing-network-traffic.adoc
Labels: size/M

#97391 Fix COO titles for Pantheon
  _topic_maps/_topic_map.yml
Labels: size/XS

#97412 OBSDOCS-2290 Add coo branch to distro_map
  _distro_map.yml
Labels: size/S

#96451 CNV#63741 Add general availibility for IBM Z
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: size/S, CNV, branch/enterprise-4.19, branch/enterprise-4.20

#96444 CNV#65955 Remove Tech Preview for IBM Z
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/S, CNV, branch/enterprise-4.19, branch/enterprise-4.20

#97441 OBSDOCS-2273 update docs to 1.2.2
  _topic_maps/_topic_map.yml
  about/cluster-observability-operator-overview.adoc
  about/cluster-observability-operator-release-notes.adoc
  api/_attributes
  api/api-monitoring-package.adoc
  api/api-observability-package.adoc
  api/docinfo.xml
  api/images
  api/modules
  api/snippets
  installing/configuring-the-cluster-observability-operator-to-monitor-a-service.adoc
  modules/coo-incident-detection-using.adoc
  modules/coo-logging-ui-plugin-install.adoc
  modules/monitoring-scrape-targets-in-multiple-namespaces.adoc
Labels: size/XXL

#97409 add second rule and change severity level
  modules/.vale.ini
Labels: size/XS

#97197 OBSDOCS-2211: Provide a cross link for enablement of developer view to view metrics as developer
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
Labels: lgtm, size/XS, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#97340 OBSDOCS-1779: Uninstalling logging (mcp-6.2)
  _topic_maps/_topic_map.yml
  images/kebab.png
  modules/deleting-logging-pvcs-by-using-the-cli.adoc
  modules/deleting-logging-pvcs-by-using-the-web-console.adoc
  modules/deleting-the-cluster-logging-operator-by-using-the-cli.adoc
  modules/deleting-the-cluster-logging-operator-by-using-the-web-console.adoc
  modules/deleting-the-loki-operator-by-using-the-cli.adoc
  modules/deleting-the-loki-operator-by-using-the-web-console.adoc
  modules/deleting-the-uiplugin-by-using-the-cli.adoc
  modules/deleting-the-uiplugin-by-using-the-web-console.adoc
  uninstalling/_attributes
  uninstalling/docinfo.xml
  uninstalling/images
  uninstalling/modules
  uninstalling/snippets
  uninstalling/uninstalling-logging.adoc
Labels: peer-review-done, size/L, jira/valid-reference, logging

#97288 RHDEVDOCS-6524: Content removal and modification for some issues in the Pipelines 1.19 RN
  modules/op-release-notes-1-19.adoc
Labels: size/S, jira/valid-reference

#97338 OBSDOCS-1779: Uninstalling logging (mcp-6.0)
  _topic_maps/_topic_map.yml
  images/kebab.png
  modules/deleting-logging-pvcs-by-using-the-cli.adoc
  modules/deleting-logging-pvcs-by-using-the-web-console.adoc
  modules/deleting-the-cluster-logging-operator-by-using-the-cli.adoc
  modules/deleting-the-cluster-logging-operator-by-using-the-web-console.adoc
  modules/deleting-the-loki-operator-by-using-the-cli.adoc
  modules/deleting-the-loki-operator-by-using-the-web-console.adoc
  modules/deleting-the-uiplugin-by-using-the-cli.adoc
  modules/deleting-the-uiplugin-by-using-the-web-console.adoc
  uninstalling/_attributes
  uninstalling/docinfo.xml
  uninstalling/images
  uninstalling/modules
  uninstalling/snippets
  uninstalling/uninstalling-logging.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference, logging

#97443 RHDEVDOCS-6384: Reference Documentation for Build Strategies
  modules/ob-about-buildah.adoc
Labels: lgtm, size/XS, jira/valid-reference

#97453 [NETOBSERV] OSDOCS-15626 Update Network Observability to network observability in release notes
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: size/M, branch/enterprise-4.12, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97291 RHDEVDOCS-6521: Content updates for Docker config authentication RN
  modules/op-release-notes-1-19.adoc
Labels: lgtm, size/M, jira/valid-reference

#97477 OCPBUGS#57827: Replaced duplicate title with required text in the 4.1…
  release_notes/ocp-4-17-release-notes.adoc
Labels: size/XS, jira/severity-low, branch/enterprise-4.17

#97458 OCPBUG-6952: Closing out PR started by Subhashini
  modules/nodes-cluster-resource-configure-jdk.adoc
Labels: size/M, ok-to-merge, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97081 [OSDOCS-14647]: Config custom API server cert for a hosted cluster
  hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc
  modules/hcp-access-hc-aws.adoc
  modules/hcp-aws-create-secret-s3.adoc
  modules/hcp-custom-cert.adoc
  security/certificates/api-server.adoc
Labels: size/L, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#95660 OCPBUGS#57005: Updates the Introduction to OVN-Kubernetes architectur…
  images/299_OpenShift_OVN-Kubernetes_arch_0123_2.png
  images/299_OpenShift_OVN-Kubernetes_arch_0223_1.png
  images/299_OpenShift_OVN-Kubernetes_arch_1023_1.png
  images/299_OpenShift_OVN_Kubernetes_arch_1_0725.png
  modules/ovn-kubernetes-architecture-con.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97516 [enterprise-4.13] OCPBUGS-57005-13: Updates the Introduction to OVN-Kubernetes architectur…
  images/299_OpenShift_OVN-Kubernetes_arch_0223_1.png
  images/299_OpenShift_OVN_Kubernetes_arch_1_0725.png
  modules/ovn-kubernetes-architecture-con.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#97524 [enterprise-4.14] OCPBUGS-6952: Closing out PR started by Subhashini
  modules/nodes-cluster-resource-configure-jdk.adoc
Labels: size/M, jira/severity-important, jira/invalid-bug, jira/valid-reference

#97528 [enterprise-4.12] OCPBUGS-6952: Closing out PR started by Subhashini
  modules/nodes-cluster-resource-configure-jdk.adoc
Labels: size/M, jira/severity-important, jira/invalid-bug, jira/valid-reference

#97523 [enterprise-4.15] OCPBUGS-6952: Closing out PR started by Subhashini
  modules/nodes-cluster-resource-configure-jdk.adoc
Labels: size/M, jira/severity-important, jira/invalid-bug, jira/valid-reference

#97449 OCPBUGS#54405 removing invalid parameters from AWS
  modules/installation-configuration-parameters.adoc
Labels: lgtm, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97437 [enterprise-4.16] Very manual CP 93993 OCP-55628
  modules/nw-multus-bond-cni-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: size/L

#97432 [enterprise-4.15] Very manual CP 93993 OCP-55628
  modules/nw-multus-bond-cni-object.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: size/L

#97550 ROSA migration fixes
  modules/rosa-sts-cluster-terraform-execute.adoc
  modules/rosa-sts-cluster-terraform-setup.adoc
  modules/rosa-sts-overview-of-the-default-cluster-specifications.adoc
  modules/rosa-sts-terraform-prerequisites.adoc
  rosa_hcp/rosa-hcp-aws-private-creating-cluster.adoc
  rosa_hcp/rosa-hcp-cluster-no-cni.adoc
  rosa_hcp/rosa-hcp-creating-cluster-with-aws-kms-key.adoc
  rosa_hcp/rosa-hcp-deleting-cluster.adoc
  rosa_hcp/rosa-hcp-egress-zero-install.adoc
  rosa_hcp/rosa-hcp-quickstart-guide.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.adoc
Labels: lgtm, size/L, branch/enterprise-4.19, branch/enterprise-4.20

#97455 OSDOCS-8659: Apply CQA updates
  modules/nw-nodeport-service-range-edit.adoc
  networking/configuring_network_settings/configuring-node-port-service-range.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97460 OBSDOCS-2298: change the structure based on approved template
  _topic_maps/_topic_map.yml
  accessing-metrics/accessing-metrics-as-a-developer.adoc
  accessing-metrics/accessing-metrics-as-an-administrator.adoc
  config-map-reference/config-map-reference-for-the-cluster-monitoring-operator.adoc
  configuring-core-platform-monitoring/configuring-alerts-and-notifications.adoc
  configuring-core-platform-monitoring/configuring-metrics.adoc
  configuring-core-platform-monitoring/configuring-performance-and-scalability.adoc
  configuring-core-platform-monitoring/storing-and-recording-data.adoc
  configuring-user-workload-monitoring/configuring-alerts-and-notifications-uwm.adoc
  configuring-user-workload-monitoring/configuring-metrics-uwm.adoc
  configuring-user-workload-monitoring/configuring-performance-and-scalability-uwm.adoc
  configuring-user-workload-monitoring/preparing-to-configure-the-monitoring-stack-uwm.adoc
  configuring-user-workload-monitoring/storing-and-recording-data-uwm.adoc
  key-concepts/_attributes
  key-concepts/images
  key-concepts/key-concepts.adoc
  key-concepts/modules
  key-concepts/snippets
  managing-alerts/managing-alerts-as-a-developer.adoc
  managing-alerts/managing-alerts-as-an-administrator.adoc
  rosa_osd_assemblies/sd-accessing-monitoring-for-user-defined-projects.adoc
  rosa_osd_assemblies/sd-disabling-monitoring-for-user-defined-projects.adoc
  support-for-monitoring/_attributes
  support-for-monitoring/images
  support-for-monitoring/maintenance-and-support-for-monitoring.adoc
  support-for-monitoring/modules
  support-for-monitoring/snippets
Labels: size/M, jira/valid-reference

#97387 OCPBUGS-36674-re: Adding DAY 2 limitations for configuring the primary interface by using the OVNK plug-in
  modules/nw-ovn-kuberentes-limitations.adoc
  modules/nw-ovn-kubernetes-features.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97563 [enterprise-4.16] OCPBUGS-36674-re: Documented support limitations for day 2 OVNK confi…
  modules/nw-ovn-kuberentes-limitations.adoc
  modules/nw-ovn-kubernetes-features.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: size/M, branch/enterprise-4.16

#97566 [enterprise-4.14] OCPBUGS-36674-re: Documented support limitations for day 2 OVNK confi…
  modules/nw-ovn-kuberentes-limitations.adoc
  modules/nw-ovn-kubernetes-features.adoc
  networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc
Labels: size/M, branch/enterprise-4.14

#97538 [enterprise-4.14] [NETOBSERV] OSDOCS-15626 Update Network Observability to network observability in release notes
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: size/M

#97533 [enterprise-4.15] [NETOBSERV] OSDOCS-15626 Update Network Observability to network observability in release notes
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: size/M, branch/enterprise-4.15

#97368 OCPBUGS-60290 ensure each MCP targets nodes with a unique nodeSelector label that is applied only to these specific node set
  modules/cnf-creating-nrop-cr.adoc
Labels: size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#96737 OSDOCS-15470-security: Removed unneccessary code blocks for net secur…
  installing/installing_aws/ipi/installing-aws-localzone.adoc
  modules/cnf-performing-end-to-end-tests-junit-test-output.adoc
  modules/hcp-deploy-openstack-create.adoc
  modules/hosted-clusters-openstack-upload-rhcos.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-networkpolicy-allow-application-all-namespaces.adoc
  modules/nw-networkpolicy-allow-application-particular-namespace.adoc
  modules/nw-networkpolicy-allow-external-clients.adoc
  modules/nw-networkpolicy-audit-configure.adoc
  modules/nw-networkpolicy-audit-disable.adoc
  modules/nw-networkpolicy-audit-enable.adoc
  modules/nw-networkpolicy-create-cli.adoc
  modules/nw-networkpolicy-delete-cli.adoc
  modules/nw-networkpolicy-deny-all-allowed.adoc
  modules/nw-networkpolicy-project-defaults.adoc
  modules/nw-ovn-ipsec-enable.adoc
  modules/nw-ovn-ipsec-north-south-enable.adoc
Labels: lgtm, size/L, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97583 [enterprise-4.17] OSDOCS-15470-security: Removed unneccessary code blocks for net secur…
  installing/installing_aws/ipi/installing-aws-localzone.adoc
  modules/cnf-performing-end-to-end-tests-junit-test-output.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-networkpolicy-allow-application-all-namespaces.adoc
  modules/nw-networkpolicy-allow-application-particular-namespace.adoc
  modules/nw-networkpolicy-allow-external-clients.adoc
  modules/nw-networkpolicy-audit-configure.adoc
  modules/nw-networkpolicy-audit-disable.adoc
  modules/nw-networkpolicy-audit-enable.adoc
  modules/nw-networkpolicy-create-cli.adoc
  modules/nw-networkpolicy-delete-cli.adoc
  modules/nw-networkpolicy-deny-all-allowed.adoc
  modules/nw-networkpolicy-project-defaults.adoc
  modules/nw-ovn-ipsec-enable.adoc
  modules/nw-ovn-ipsec-north-south-enable.adoc
Labels: size/L, branch/enterprise-4.17

#97584 [enterprise-4.16] OSDOCS-15470-security: Removed unneccessary code blocks for net secur…
  installing/installing_aws/ipi/installing-aws-localzone.adoc
  modules/cnf-performing-end-to-end-tests-junit-test-output.adoc
  modules/nw-egressnetworkpolicy-create.adoc
  modules/nw-networkpolicy-allow-application-all-namespaces.adoc
  modules/nw-networkpolicy-allow-application-particular-namespace.adoc
  modules/nw-networkpolicy-allow-external-clients.adoc
  modules/nw-networkpolicy-audit-configure.adoc
  modules/nw-networkpolicy-audit-disable.adoc
  modules/nw-networkpolicy-audit-enable.adoc
  modules/nw-networkpolicy-create-cli.adoc
  modules/nw-networkpolicy-delete-cli.adoc
  modules/nw-networkpolicy-deny-all-allowed.adoc
  modules/nw-networkpolicy-project-defaults.adoc
  modules/nw-ovn-ipsec-enable.adoc
  modules/nw-ovn-ipsec-north-south-enable.adoc
Labels: size/L, branch/enterprise-4.16

#97568 OCPBUGS#60416 [enterprise-4.12] There is one more wrong example in FROM clause of image layering docs
  modules/coreos-layering-configuring.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed

#97534 OSDOCS-15831: modularize install get ready assembly MicroShift
  microshift_install_get_ready/microshift-install-get-ready.adoc
  modules/microshift-install-rhde-compat-table.adoc
  modules/microshift-install-rhde-steps.adoc
  modules/microshift-install-rhel-tools-concepts.adoc
  modules/microshift-install-rhel-types.adoc
  modules/microshift-install-system-requirements.adoc
  modules/microshift-install-tools-intro.adoc
Labels: size/L, ok-to-merge, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97456 OSDOCS-15763:Update the z-stream RNs for 4.18.22
  release_notes/ocp-4-18-release-notes.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.18

#97602 CP-419-OSDOCS-15307: adds filename for CA bundle MicroShift
  modules/microshift-ingress-controller-config.adoc
Labels: size/S, ok-to-merge, jira/valid-reference

#97531 CNV#63768: Doc: TP to GA - remove TP notice from docs
  modules/virt-migrating-bulk-vms-different-storage-class-web.adoc
  virt/managing_vms/virt-migrating-vms-in-single-cluster-to-different-storage-class.adoc
Labels: size/S, CNV, branch/enterprise-4.19, branch/enterprise-4.20

#97609 CP-417-OSDOCS-15831: mod get ready to install assembly MicroShift
  microshift_install_get_ready/microshift-install-get-ready.adoc
  modules/microshift-install-rhde-compat-table.adoc
  modules/microshift-install-rhde-steps.adoc
  modules/microshift-install-rhel-tools-concepts.adoc
  modules/microshift-install-rhel-types.adoc
  modules/microshift-install-system-requirements.adoc
  modules/microshift-install-tools-intro.adoc
Labels: size/L, jira/valid-reference

#97612 OSDOCS-15849: fix unrendered attribute for RHEL
  modules/microshift-greenboot-testing-workload-script.adoc
  modules/microshift-install-rhde-compat-table.adoc
Labels: size/XS, jira/valid-reference, branch/enterprise-4.19, branch/enterprise-4.20

#97414 RHDEVDOCS-6546: Incorporating additional changes in GitOps 1.17 RN
  modules/gitops-release-notes-1-17-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
Labels: size/M, jira/valid-reference

#97634 Change test to use openshift-monitoring by default
  scripts/prow-smoke-test.sh
Labels: size/XS

#97635 OBSDOCS-2302: Add TP snippet
  modules/monitoring-4-20-release-notes.adoc
  snippets/technology-preview.adoc
Labels: size/S, jira/valid-reference

#97522 CNV#63767: Release note: TP to GA
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: size/XS, CNV, branch/enterprise-4.19

#97624 CNV-62384: Removed DPDK checkup docs
  modules/virt-configuring-vm-project-dpdk.adoc
  virt/monitoring/virt-running-cluster-checkups.adoc
  virt/vm_networking/virt-using-dpdk-with-sriov.adoc
Labels: size/M, CNV, jira/valid-reference, branch/enterprise-4.20

#97645 Updated Distro Map names
  _attributes/attributes-openshift-dedicated.adoc
  _distro_map.yml
  modules/rosa-create-objects.adoc
  rosa_cluster_admin/rosa-cluster-autoscaling.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: size/S, branch/enterprise-4.19, branch/enterprise-4.20

#97709 OADP-6353 Added role to mark DITA descriptions and removed an extra para
  backup_and_restore/application_backup_and_restore/oadp-advanced-topics.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  backup_and_restore/application_backup_and_restore/oadp-performance/oadp-recommended-network-settings.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-5-release-notes.adoc
  modules/changes-from-oadp-1-4-to-1-5.adoc
  modules/converting-dpa-to-the-new-version-for-oadp-1-5-0.adoc
  modules/oadp-backing-up-dpa-configuration-1-5-0.adoc
  modules/oadp-configuring-velero-plugins.adoc
  modules/oadp-features.adoc
  modules/oadp-fips.adoc
  modules/oadp-ibm-power-and-z-known-issues.adoc
  modules/oadp-ibm-power-test-support.adoc
  modules/oadp-ibm-z-test-support.adoc
  modules/oadp-plugins.adoc
  modules/oadp-supported-architecture.adoc
  modules/oadp-upgrading-oadp-operator-1-5-0.adoc
  modules/oadp-verifying-upgrade-1-5-0.adoc
Labels: size/S, OADP, branch/enterprise-4.20

#97569 OSDOCS-15608-re: Updated curl command in containers-signature-verify-…
  modules/containers-signature-verify-skopeo.adoc
Labels: lgtm, size/XS, ok-to-merge, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97434 OADP-3149: Clarify example block titles in OADP 1.3.0 RNs
  modules/oadp-verifying-upgrade-1-3-0.adoc
Labels: size/XS, branch/enterprise-4.12, OADP, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#97726 Fix product name
  _distro_map.yml
Labels: size/XS

#97672 OCPBUGS#54741: Removed balance-tlb references from Agent Installer docs
  modules/agent-install-sample-config-bond-sriov.adoc
  modules/ipi-install-configuring-host-dual-network-interfaces-in-the-install-config.yaml-file.adoc
Labels: lgtm, size/S, ok-to-merge, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97567 OSSM-10533 [DOC] Update for Pod healthchecks not working in ambient mode with OVN-K CNI
  install/ossm-istio-ambient-mode.adoc
  modules/ossm-installing-istio-ambient-mode.adoc
  modules/ossm-release-notes-3-1-known-issues.adoc
  ossm-release-notes/ossm-release-notes.adoc
Labels: size/S, service-mesh

#97742 [enterprise-4.16] OCPBUGS-54741: Removed balance-tlb references from Agent Installer docs
  modules/agent-install-sample-config-bond-sriov.adoc
  modules/ipi-install-configuring-host-dual-network-interfaces-in-the-install-config.yaml-file.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16

#97669 [OSDOCS-15876]Prune "About"
  _topic_maps/_topic_map_rosa.yml
  cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-rosa-sts-explained.adoc
  support/troubleshooting/rosa-troubleshooting-installations-hcp.adoc
Labels: lgtm, size/M

#97747 CP418-OSDOCS-15879: CP storage fix MicroShift
  modules/storage-persistent-storage-pv.adoc
Labels: size/S, jira/valid-reference

#97479 OCPBUGS#59857: Added KBase link to modules/nw-configure-ingress-acces…
  modules/nw-configure-ingress-access-logging.adoc
  networking/networking_operators/ingress-operator.adoc
Labels: size/S, qe-approved, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#97706 ROX-30508: Correct language for sizing requirements
  modules/recommended-requirements-central-services.adoc
Labels: size/S, RHACS, jira/valid-reference, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8, rhacs-docs-4.9

#97790 OSSM-10604: Move location of installing Kiali multi-cluster task topi…
  install/ossm-multi-cluster-topologies.adoc
Labels: size/XS, jira/valid-reference
