Repository openshift/openshift-docs, pull requests merged in 2025-01, with the labels that each got.

#83662 [OCPBUGS-41344] Updated the RHEL8 versions for worker nodes
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, needs-ok-to-test, merge-review-in-progress, branch/enterprise-4.15

#85265 Shared resources 1.2
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
  modules/ephemeral-storage-additional-details-about-volumeattributes-on-shared-resource-pod-volumes.adoc
  modules/ephemeral-storage-integration-between-shared-resources-insights-operator-and-openshift-builds.adoc
  modules/ephemeral-storage-sharing-configmaps-across-namespaces.adoc
  modules/ephemeral-storage-sharing-secrets-across-namespaces.adoc
  modules/ephemeral-storage-using-a-sharedconfigmap-object-in-a-pod.adoc
  modules/ephemeral-storage-using-a-sharedsecret-object-in-a-pod.adoc
  modules/persistent-storage-csi-about.adoc
  work_with_shared_resources/using-shared-resource-csi-driver.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress

#86638 Updated note
  modules/builds-running-entitled-builds-with-sharedsecret-objects.adoc
Labels: size/XS

#85399 Added a reference link for pre-allocated huge pages
  modules/virt-configuring-huge-pages-for-vms.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85991 OSDOCS#50922: Fixing doc for setting up memory overcommit
  modules/virt-using-wasp-agent-to-configure-higher-vm-workload-density.adoc
Labels: peer-review-done, size/M, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86631 OSDOCS-12814: adds 4.16.28 relnotes Microshift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.16

#86630 OSDOCS-12162: adds 4.15.42 relnotes Microshift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15

#86632 OSDOCS-12497: adds 4.17.10 relnotes Microshift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17

#86637 Indentation Fault in Viewing Logging status Documentation
  modules/cluster-logging-clo-status.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#86525 OSDOCS-12973: Documented the 4.17.10 z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.17

#86282 OCPBUGS-35276 Feedback on PR 62354
  modules/nw-sriov-networknodepolicy-object.adoc
Labels: peer-review-done, size/S, merge-review-in-progress

#86671 [enterprise-4.16] OSDOCS#50922: Improving docs for setting up memory overcommit
  modules/virt-using-wasp-agent-to-configure-higher-vm-workload-density.adoc
Labels: size/M

#86227 OSDOCS-12920: oc adm upgrade recommend TP doc
  modules/update-upgrading-oc-adm-upgrade-recommend.adoc
  modules/update-upgrading-oc-adm-upgrade-status.adoc
  updating/updating_a_cluster/updating-cluster-cli.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.18

#86400 OSDOCS-12946: machine set feature REF bare metal
  _topic_maps/_topic_map.yml
  _unused_topics/machine-set-CLOUD-options-FEATURE.adoc
  _unused_topics/machine-set-CLOUD-using-FEATURE.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-aws.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-azure.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-bare-metal.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-gcp.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-nutanix.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-openstack.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-vsphere.adoc
  machine_management/creating_machinesets/creating-machineset-aws.adoc
  machine_management/creating_machinesets/creating-machineset-azure-stack-hub.adoc
  machine_management/creating_machinesets/creating-machineset-azure.adoc
  machine_management/creating_machinesets/creating-machineset-bare-metal.adoc
  machine_management/creating_machinesets/creating-machineset-gcp.adoc
  machine_management/creating_machinesets/creating-machineset-ibm-cloud.adoc
  machine_management/creating_machinesets/creating-machineset-ibm-power-vs.adoc
  machine_management/creating_machinesets/creating-machineset-nutanix.adoc
  machine_management/creating_machinesets/creating-machineset-osp.adoc
  machine_management/creating_machinesets/creating-machineset-vsphere.adoc
  modules/machine-set-agnostic-options-label-gpu-autoscaler.adoc
  modules/machine-set-agnostic-using-label-gpu-autoscaler.adoc
  modules/machine-set-yaml-bare-metal.adoc
  modules/machineset-label-gpu-autoscaler.adoc
  post_installation_configuration/cluster-tasks.adoc
  snippets/machine-set-ifeval-close.adoc
  snippets/machine-set-ifeval-open.adoc
Labels: size/XL, jira/valid-reference

#86672 Incorrect configuration of namespace object for the Red Hat OpenShift Logging Operator
  modules/logging-loki-cli-install.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#86670 outputRefs value is missing in Forwarding logs over HTTP documentation
  modules/logging-http-forward.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#85578 PR for SRVLOGIC-436: Document "Global configuration settings" section in the OSL docs.
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/serverless-logic-global-config-customization.adoc
  serverless-logic/serverless-logic-global-config-settings.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#86705 [enterprise-4.14] Incorrect configuration of namespace object for the Red Hat OpenShift Logging Operator
  modules/logging-loki-cli-install.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.14

#86707 [enterprise-4.15] Incorrect configuration of namespace object for the Red Hat OpenShift Logging Operator
  modules/logging-loki-cli-install.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.15

#86516 [OSDOCS-12971]Document command line verification of WIF resources
  modules/create-wif-cluster-cli.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18

#81408 OSDOCS#38323: Added a description for KI - BZ#2151169
  virt/release_notes/virt-4-15-release-notes.adoc
Labels: size/XS, merge-review-in-progress, merge-review-needed

#85091 OSSM-8385: Installing multi-primary multi-network mesh
  _attributes/common-attributes.adoc
  install/ossm-multi-cluster-topologies.adoc
  modules/ossm-installing-multi-primary-multi-network-mesh.adoc
  modules/ossm-removing-multi-cluster-installation-from-development-environment.adoc
  modules/ossm-verifying-multi-cluster-topology.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress, jira/valid-reference

#74790 Added command for removing the taint
  modules/persistent-storage-csi-vol-detach-non-graceful-shutdown-procedure.adoc
Labels: lgtm, size/XS, ok-to-test, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85350 OSDOCS-5074: Choosing subnets when creating a LoadBalancerService ingress Controller
  modules/nw-ingress-setting-select-subnet-loadbalancerservice.adoc
  modules/nw-ingress-setting-update-subnet-loadbalancerservice.adoc
  networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-aws.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#85633 PR for SRVLOGIC-353: Document "Managing persistence" section in the OSL docs.
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/serverless-logic-config-persistence-using-sonataflow-cr.adoc
  modules/serverless-logic-config-persistence-using-sonataflowplaform-cr.adoc
  modules/serverless-logic-persistence-db-schema-initialization.adoc
  modules/serverless-logic-persistence-precedence-rules.adoc
  modules/serverless-logic-profile-persistence-requirements.adoc
  serverless-logic/serverless-logic-managing-persistence.adoc
Labels: peer-review-done, size/L, serverless, merge-review-in-progress, jira/valid-reference

#86736 OADP-5423: Update OADP support table to include 4.17
  modules/oadp-operator-supported.adoc
  modules/oadp-s3-compatible-backup-storage-providers.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, OADP, jira/valid-reference

#86419 OSSM-8630: Documentation for primary-remote multi-network topology
  install/ossm-multi-cluster-topologies.adoc
  modules/ossm-installing-primary-remote-multi-network-mesh.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#86706 OADP-5176: Support custom RBAC OADP to multi-tenancy
  backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.adoc
  modules/about-installing-oadp-on-multiple-namespaces.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86687 OCPBUGS#46535: Fixed the link in the deployments-ab-testing-lb.adoc file
  applications/deployments/route-based-deployment-strategies.adoc
  modules/deployments-ab-testing-lb.adoc
Labels: peer-review-done, size/XS, jira/severity-low, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86079 Adds ovnk observ with ovs sampling to docs
  modules/nodes-cluster-enabling-features-about.adoc
  modules/nw-ovn-kubernetes-observability.adoc
  modules/observability-ovs-sampling-flags.adoc
  networking/ovn_kubernetes_network_provider/ovn-kubernetes-troubleshooting-sources.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.18

#86769 Revert 86400
  _topic_maps/_topic_map.yml
  _unused_topics/machine-set-CLOUD-options-FEATURE.adoc
  _unused_topics/machine-set-CLOUD-using-FEATURE.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-aws.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-azure.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-bare-metal.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-gcp.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-nutanix.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-openstack.adoc
  machine_management/compute_machine_management/mapi_compute_provider_configurations/mapi-compute-config-options-vsphere.adoc
  machine_management/creating_machinesets/creating-machineset-bare-metal.adoc
  modules/machine-set-agnostic-options-label-gpu-autoscaler.adoc
  modules/machine-set-agnostic-using-label-gpu-autoscaler.adoc
  modules/machineset-label-gpu-autoscaler.adoc
  modules/machineset-yaml-baremetal.adoc
  snippets/machine-set-ifeval-close.adoc
  snippets/machine-set-ifeval-open.adoc
Labels: size/XL

#86775 [enterprise-4.12] OCPBUGS-46535: Fixed the link in the deployments-ab-testing-lb.adoc file
  applications/deployments/route-based-deployment-strategies.adoc
  modules/deployments-ab-testing-lb.adoc
Labels: size/XS, jira/severity-low, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference

#86553 Adds OVS sampling using the cli to release notes
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#86779 [enterprise-4.18]OSDOCS-12429#CIFS/SMB CSI driver TP -> GA
  modules/persistent-storage-csi-smb-cifs-limits.adoc
  storage/container_storage_interface/persistent-storage-csi-smb-cifs.adoc
Labels: size/S

#84311 OSDOCS#11144:Secret Store TP->GA
  nodes/pods/nodes-pods-secrets-store.adoc
  storage/container_storage_interface/persistent-storage-csi-secrets-store.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#86027 OSDOCS#378545 - Improving description for secondary network interface hot plugs
  virt/vm_networking/virt-hot-plugging-network-interfaces.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#86767 OSSM-8668 Update link to redirect to 3.x on docs.redhat
  service_mesh/v3x/ossm-service-mesh-3-0-overview.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86576 ALBO: Follow-up edits for #86081
  modules/creating-multiple-ingress-through-single-alb.adoc
  networking/networking_operators/aws_load_balancer_operator/add-tls-termination.adoc
  networking/networking_operators/aws_load_balancer_operator/configuring-aws-load-balancer-operator.adoc
  networking/networking_operators/aws_load_balancer_operator/create-instance-aws-load-balancer-controller.adoc
  networking/networking_operators/aws_load_balancer_operator/multiple-ingress-through-single-alb.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86304 OADP-5316 must gather for 4.15 and 4.14
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  modules/migration-combining-must-gather.adoc
  modules/migration-using-must-gather.adoc
  modules/support-insecure-tls-connections.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.15

#86301 OADP-5316-must-gather for 4.16-4.18
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  modules/migration-combining-must-gather.adoc
  modules/migration-using-must-gather.adoc
  modules/support-insecure-tls-connections.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86313 OADP-5316-must-gather-for-4.13
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  modules/migration-combining-must-gather.adoc
  modules/migration-using-must-gather.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, OADP, branch/enterprise-4.13

#86800 OADP-5316-must-gather-4.14
  _attributes/common-attributes.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  modules/migration-combining-must-gather.adoc
  modules/migration-using-must-gather.adoc
  modules/support-insecure-tls-connections.adoc
Labels: size/L, OADP, branch/enterprise-4.14

#86759 OBSDOCS-1552: Add assembly content for 'Accessing metrics' section
  observability/monitoring/accessing-metrics/accessing-metrics-as-a-developer.adoc
  observability/monitoring/accessing-metrics/accessing-metrics-as-an-administrator.adoc
  observability/monitoring/accessing-metrics/accessing-monitoring-apis-by-using-the-CLI.adoc
  observability/monitoring/accessing-third-party-monitoring-apis.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#86781 RHDEVDOCS 6332 fix docs.openshift.com redirect for Pipelines RN
  .s2i/httpd-cfg/01-commercial.conf
Labels: lgtm, size/XS

#86682 NE-1809: adding release notes for AWS Load Balancer Operator v1.2
  networking/networking_operators/aws_load_balancer_operator/aws-load-balancer-operator-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86750 OSDOCS#10488: Differences between OCP and HCP
  hosted_control_planes/index.adoc
  modules/hcp-ocp-differences.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86772 Removes azurefile csi limitation from docs
  modules/registry-configuring-private-storage-endpoint-azure.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#86660 HCIDOCS-188: Scaling UPI cluster with BMO doesn't explain host networking
  installing/installing_bare_metal/upi/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.18

#85822 [OCPBUGS-38910]: Update ignition version in 4.14+ docs for etcd
  modules/move-etcd-different-disk.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86811 updating context values from content migration
  modules/cco-ccoctl-configuring.adoc
  modules/manually-rotating-cloud-creds.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86830 [enterprise-4.14][OCPBUGS-38910]: Update ignition version in 4.14+ docs for etcd
  modules/move-etcd-different-disk.adoc
Labels: size/XS

#86831 [enterprise-4.15][OCPBUGS-38910]: Update ignition version in 4.14+ docs for etcd
  modules/move-etcd-different-disk.adoc
Labels: size/XS

#86832 [enterprise-4.16][OCPBUGS-38910]: Update ignition version in 4.14+ docs for etcd
  modules/move-etcd-different-disk.adoc
Labels: size/XS

#86833 [enterprise-4.17][OCPBUGS-38910]: Update ignition version in 4.14+ docs for etcd
  modules/move-etcd-different-disk.adoc
Labels: size/XS

#86633 OSDOCS#12975: Update relnotes for 4.16.28 z-stream
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16

#86742 OSDOCS#13024: 4.17.11 z-stream RN
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17

#85650 PR for SRVLOGIC-482: Add "Supporting services eventing system configurations" section in the OSL product docs.
  modules/serverless-logic-supporting-services-cluster-scoped-eventing-system-config.adoc
  modules/serverless-logic-supporting-services-data-index-eventing-system-config.adoc
  modules/serverless-logic-supporting-services-eventing-system-config.adoc
  modules/serverless-logic-supporting-services-eventing-system-linking-objects.adoc
  modules/serverless-logic-supporting-services-eventing-system-precedence-rule.adoc
  modules/serverless-logic-supporting-services-job-service-eventing-system-config.adoc
  modules/serverless-logic-supporting-services-platform-scoped-eventing-system-config.adoc
  modules/serverless-logic-supporting-services-service-scoped-eventing-system-config.adoc
  serverless-logic/serverless-logic-supporting-services/serverless-logic-managing-supporting-services.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#86680 OSDOCS-13027: Documented the 4.12.71 z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference

#85644 PR for SRVLOGIC-481: Document "workflow eventing system" section in the Serverless Logic product docs
  _topic_maps/_topic_map.yml
  modules/serverless-logic-cluster-scoped-eventing-system-config.adoc
  modules/serverless-logic-eventing-system-config-precedence-rule.adoc
  modules/serverless-logic-linking-workflows-eventing-system.adoc
  modules/serverless-logic-platform-scoped-eventing-system-config.adoc
  modules/serverless-logic-workflow-scoped-eventing-system-config.adoc
  serverless-logic/serverless-logic-workflow-eventing-system.adoc
Labels: peer-review-done, size/L, jira/valid-reference

#86801 OBSDOCS-1561: Add assemblies to the 'About OpenShift Container Platfo…
  modules/monitoring-common-terms.adoc
  modules/monitoring-monitoring-stack-in-ha-clusters.adoc
  modules/monitoring-understanding-the-monitoring-stack.adoc
  observability/monitoring/about-ocp-monitoring/about-ocp-monitoring.adoc
  observability/monitoring/about-ocp-monitoring/monitoring-stack-architecture.adoc
  observability/monitoring/monitoring-overview.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference

#86803 RHDEVDOCS-6320: Update installation instructions
  modules/ob-installing-builds-with-operator.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#85899 [OCPBUGS-45810]: Correct SMB CSI volumeHandle fomat
  modules/persistent-storage-csi-smb-cifs-provision-static.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86851 CNV-54749: Updated HCO version variable for 4.17.3
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, jira/valid-reference, branch/enterprise-4.17

#86777 OCPBUGS#47532: Added note to the nw-operator-cr file
  modules/nw-network-config.adoc
  modules/nw-operator-cr.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86715 TELCODOCS-1828: Clarify supported format for osImages.openshiftVersion in ZTP docs
  modules/ztp-configuring-the-cluster-for-a-disconnected-environment.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#85256 CNV-23190: custom namespace for golden images
  modules/virt-golden-images-namespace-cli.adoc
  modules/virt-golden-images-namespace-web.adoc
  virt/creating_vms_advanced/creating_vms_advanced_web/virt-creating-vms-from-rh-images-overview.adoc
Labels: peer-review-done, size/M, CNV, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#84350 OSDOCS-12428# PV Vol last phase transition time
  modules/storage-persistent-storage-pv.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#86812 TELCODOCS-2155: Fix indentation in IBGU examples
  modules/cnf-image-based-upgrade-troubleshooting.adoc
  modules/ztp-image-based-upgrade-concept.adoc
  modules/ztp-image-based-upgrade-procedure-cancel.adoc
  modules/ztp-image-based-upgrade-procedure-rollback.adoc
  modules/ztp-image-based-upgrade-procedure-steps.adoc
  snippets/ibu-ImageBasedGroupUpgrade.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#86869 [OCPBUGS-48114]: HCP doc fixes: node pool description and sizing guidance
  hosted_control_planes/hcp-prepare/hcp-sizing-guidance.adoc
  modules/hosted-control-planes-concepts-personas.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#86712 OSDOCS-12815: adds 4.16.29 relnotes Microshift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#86353 OSDOCS-12918:Corrected links to create cluster guides in Getting started section
  modules/understanding-clusters.adoc
  osd_getting_started/osd-getting-started.adoc
  osd_getting_started/osd-understanding-your-cloud-deployment-options.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#86880 HCIDOCS-188: 4.17 cherry pick for 86660
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: size/L, jira/valid-reference

#86881 HCIDOCS-188: 4.16 cherry pick for 86660.
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: size/L, jira/valid-reference

#86884 HCIDOCS-188: 4.15 cherry pick for 86660.
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: size/L, jira/valid-reference

#86886 HCIDOCS-188: 4.14 cherry pick for 86660.
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: size/L, jira/valid-reference

#86887 HCIDOCS-188: 4.13 cherry pick of 86660
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  modules/about-scaling-a-user-provisioned-installation-with-the-bare-metal-operator.adoc
  modules/upi-provisioning-new-hosts-in-a-upi-cluster.adoc
  modules/upi-removing-hosts-from-a-upi-cluster.adoc
Labels: size/L, jira/valid-reference

#86709 OSDOCS-12949: adds 4.14.44 relnotes Microshift
  microshift_release_notes/microshift-4-14-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#84676 OCPBUGS#44367: Error of SCC example yaml file is fixed
  modules/security-context-constraints-example.adoc
Labels: peer-review-done, size/XS, ok-to-test, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86861 OSDOCS-13027-year-fix
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12

#86867 OSDOCS-13047-YEAR-FIX
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#86860 OSDOCS-13025: Documented the 4.16.29 z-stream notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.16

#86897 [build-docs-1.2] Updated installation instructions
  modules/ob-installing-builds-with-operator.adoc
Labels: size/S, merge-review-in-progress

#86727 OSDOCS-13041: Documented the 4.14.44 z-stream RNs
  release_notes/ocp-4-14-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.14

#86523 OCPBUGS-44422-RN: Added KBase article for RHCOS versions to RN doc
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#86903 OCPBUGS-44422-15: Added KBase article for RHCOS versions to RN doc
  release_notes/ocp-4-15-release-notes.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#86771 Removal of known issue in 4.17 release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17

#86901 OCPBUGS-44422-17: Added KBase article for RHCOS versions to RN doc
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.17

#86905 OCPBUGS-44422-13: Added KBase article for RHCOS versions to RN doc
  release_notes/ocp-4-13-release-notes.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#86902 OCPBUGS-44422-16: Added KBase article for RHCOS versions to RN doc
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16

#86879 OCPBUGS-37110: fix security group tag in MAPI docs
  modules/machineset-yaml-aws.adoc
Labels: peer-review-done, lgtm, size/M, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86778 OSDOCS-9444 changed 3 to F in installation-network-user-infra file
  modules/installation-network-user-infra.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86603 TELCODOCS#2004: Day 2 Operations - Security Doc
  _topic_maps/_topic_map.yml
  edge_computing/day_2_core_cnf_clusters/security/_attributes
  edge_computing/day_2_core_cnf_clusters/security/images
  edge_computing/day_2_core_cnf_clusters/security/modules
  edge_computing/day_2_core_cnf_clusters/security/snippets
  edge_computing/day_2_core_cnf_clusters/security/telco-security-basics.adoc
  edge_computing/day_2_core_cnf_clusters/security/telco-security-host-sec.adoc
  edge_computing/day_2_core_cnf_clusters/security/telco-security-sec-context-constraints.adoc
  modules/telco-security-command-line-host-access.adoc
  modules/telco-security-evolu-nf-to-cnf.adoc
  modules/telco-security-identity-prov-config.adoc
  modules/telco-security-infra.adoc
  modules/telco-security-key-areas-for-cnf-deploy.adoc
  modules/telco-security-lifecycle-mgmnt.adoc
  modules/telco-security-linux-capabilities-overview.adoc
  modules/telco-security-pod-sec-in-kub-and-ocp.adoc
  modules/telco-security-rbac-overview.adoc
  modules/telco-security-replacing-kubeadmin-user.adoc
  modules/telco-security-rhcos-overview.adoc
  modules/telco-security-sec-accounts-overview.adoc
  modules/telco-security-sec-considerations-telco.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, merge-review-needed, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86003 OSDOCS-12690: Add OADP to ROSA docs
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-use-cases/oadp-rosa-backup-restore.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/installing-oadp-rosa-sts.adoc
  modules/oadp-1-4-1-release-notes.adoc
  modules/oadp-configuring-velero-plugins.adoc
  modules/oadp-plugins.adoc
  modules/preparing-aws-credentials-for-oadp.adoc
  rosa_architecture/about-hcp.adoc
  rosa_backing_up_and_restoring_applications/_attributes
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
  rosa_backing_up_and_restoring_applications/images
  rosa_backing_up_and_restoring_applications/modules
  rosa_backing_up_and_restoring_applications/snippets
  welcome/about-hcp.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-needed, jira/valid-reference

#86622 OSDOCS#11510: HCP: single-architecture to multi-architecture migration
  hosted_control_planes/hcp-manage/hcp-manage-aws.adoc
  modules/hcp-migrate-aws-multiarch-nodepools.adoc
  modules/hcp-migrate-aws-single-to-multiarch.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.17, branch/enterprise-4.18

#86931 [enterprise-4.17] OSDOCS#11510: HCP: The multi-architecture migration flag: `multiArch`
  modules/hcp-migrate-aws-single-to-multiarch.adoc
Labels: size/S, branch/enterprise-4.17

#86708 OBSDOCS-1555: Add missing RN entry for OCP 4.15
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, px-approved, jira/valid-reference, branch/enterprise-4.15

#80453 CNV-45187: Restore section Creating VM templates above 4.13
  modules/virt-creating-template.adoc
  virt/creating_vm/virt-creating-vms-from-templates.adoc
Labels: peer-review-done, size/XS, lifecycle/rotten, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86937 [enterprise-4.17] Simplify IBM Z installation docs - manual CP417
  _topic_maps/_topic_map.yml
  disconnected/installing.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
  hosted_control_planes/hcp-manage/hcp-manage-ibm-power.adoc
  installing/installing_ibm_z/installing-ibm-z-lpar.adoc
  installing/installing_ibm_z/installing-ibm-z.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z-lpar.adoc
  installing/installing_ibm_z/installing-restricted-networks-ibm-z.adoc
  installing/installing_ibm_z/preparing-to-install-on-ibm-z.adoc
  installing/installing_ibm_z/upi/installing-ibm-z-kvm.adoc
  installing/installing_ibm_z/upi/installing-ibm-z-lpar.adoc
  installing/installing_ibm_z/upi/installing-ibm-z-reqs.adoc
  installing/installing_ibm_z/upi/installing-ibm-z.adoc
  installing/installing_ibm_z/upi/installing-restricted-networks-ibm-z-kvm.adoc
  installing/installing_ibm_z/upi/installing-restricted-networks-ibm-z-lpar.adoc
  installing/installing_ibm_z/upi/installing-restricted-networks-ibm-z.adoc
  installing/installing_ibm_z/upi/upi-ibm-z-preparing-to-install.adoc
  installing/installing_sno/install-sno-installing-sno.adoc
  installing/installing_with_agent_based_installer/prepare-pxe-assets-agent.adoc
  installing/overview/installing-fips.adoc
  installing/overview/installing-preparing.adoc
  modules/cli-installing-cli.adoc
  modules/cluster-entitlements.adoc
  modules/installation-machine-requirements.adoc
  modules/installation-minimum-resource-requirements.adoc
  modules/installation-network-user-infra.adoc
  modules/installation-obtaining-installer.adoc
  modules/installation-requirements-ibm-z.adoc
  modules/installation-user-provisioned-validating-dns.adoc
  modules/preferred-installation-requirements-ibm-z.adoc
  modules/ssh-agent-using.adoc
  service_mesh/v2x/preparing-ossm-installation.adoc
Labels: size/XXL

#86846 OCPBUGS-44284: Update Uninstalling SR-IOV Operator section
  modules/nw-sriov-operator-uninstall.adoc
Labels: peer-review-done, lgtm, size/S, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.18

#85310 Updating the capabilities set table for 4.18
  snippets/capabilities-table.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, branch/enterprise-4.18

#86823 HCIDOCS-260: Clarification on configuring RAID with RHOCP
  modules/bmo-about-the-baremetalhost-resource.adoc
  modules/installation-special-config-raid.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86913 [OCPBUGS-44731]: Add note about service publishing for HCP on BM
  modules/hcp-bm-hc.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#86964 [enterprise-4.17] OSDOCS-12690: Add OADP to ROSA docs
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-use-cases/oadp-rosa-backup-restore.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/installing-oadp-rosa-sts.adoc
  modules/oadp-1-4-1-release-notes.adoc
  modules/oadp-configuring-velero-plugins.adoc
  modules/oadp-plugins.adoc
  modules/preparing-aws-credentials-for-oadp.adoc
  rosa_architecture/about-hcp.adoc
  rosa_backing_up_and_restoring_applications/_attributes
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
  rosa_backing_up_and_restoring_applications/images
  rosa_backing_up_and_restoring_applications/modules
  rosa_backing_up_and_restoring_applications/snippets
  welcome/about-hcp.adoc
Labels: size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference

#86961 Retitling OVE from Architecture to Overview
  _topic_maps/_topic_map.yml
  overview/_attributes
  overview/attributes
  overview/images
  overview/modules
  overview/ove-overview.adoc
  overview/snippets
Labels: size/S

#86868 OSSM-8312: Wrong namespace in examples
  modules/ossm-accessing-bookinfo-application-using-istio-gateway-injection.adoc
Labels: peer-review-done, size/M, service-mesh, jira/valid-reference

#86971 [enterprise-4.18] OSDOCS-12690: Add OADP to ROSA docs
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-features-plugins.adoc
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
  backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-use-cases/oadp-rosa-backup-restore.adoc
  backup_and_restore/application_backup_and_restore/release-notes/oadp-1-4-release-notes.adoc
  modules/installing-oadp-rosa-sts.adoc
  modules/oadp-1-4-1-release-notes.adoc
  modules/oadp-configuring-velero-plugins.adoc
  modules/oadp-plugins.adoc
  modules/preparing-aws-credentials-for-oadp.adoc
  rosa_architecture/about-hcp.adoc
  rosa_backing_up_and_restoring_applications/_attributes
  rosa_backing_up_and_restoring_applications/backing-up-applications.adoc
  rosa_backing_up_and_restoring_applications/images
  rosa_backing_up_and_restoring_applications/modules
  rosa_backing_up_and_restoring_applications/snippets
  welcome/about-hcp.adoc
Labels: size/L, merge-review-needed, jira/valid-reference

#86792 osdocs10893rn: Release note for dynamic configuration manager
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-needed

#86906 OSDOCS-12499: adds 4.17.12 relnote MicroShift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#86947 [RHACS] Fix error in RNs for API deprecation
  release_notes/46-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.6, rhacs-docs-4.7

#86944 [RHACS] Fix error with API deprecation
  release_notes/44-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.4

#86973 OCPBUGS-48304: Remove duplicate steps
  modules/running-insights-operator-gather-web-console.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86970 One step needs to be added to the Quick Start point of About Logging 6.0 documentation
  observability/logging/logging-6.0/log6x-about.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86898 OCPBUGS-44284: Add RN for changing the flow of removing SR-IOV Network Operator
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, jira/severity-important, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.18

#86969 [OSDOCS-13105][OSD-GCP] Update the documentation for constraints/iam.allowedPolicyMemberDomains in "Required customer procedure"
  modules/ccs-gcp-customer-procedure.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18

#86978 TELCODOCS-2156: Updating label for /var/lib/containers partition
  modules/ibi-install-shared-partition.adoc
  modules/ibi-installer-installation-config.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#85152 MGMT-19226: Addition specs and procedure for creating additional partitions
  edge_computing/image_base_install/ibi-factory-image-based-install.adoc
  modules/ibi-extra-partition-ibi-install-iso.adoc
  modules/ibi-installer-installation-config.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#86852 OSDOCS-13061: DOcumented the 4.17.12 z-stream notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17

#86710 OBSDOCS-1527: Add missing information to the monitoring dashboards se…
  images/observe-dashboard-developer.png
  modules/monitoring-querying-metrics-for-all-projects-as-an-administrator.adoc
  modules/monitoring-querying-metrics-for-user-defined-projects-as-a-developer.adoc
  modules/monitoring-reviewing-monitoring-dashboards-admin.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
  modules/sd-monitoring-troubleshooting-issues.adoc
  observability/monitoring/reviewing-monitoring-dashboards.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#84718 OSDOCS-12577#removing duplicate prereqs
  modules/cli-logging-in-kubeadmin.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-creating-gcp-bootstrap.adoc
  modules/installation-creating-gcp-control-plane.adoc
  modules/installation-creating-gcp-firewall-rules-vpc.adoc
  modules/installation-creating-gcp-iam-shared-vpc.adoc
  modules/installation-creating-gcp-lb.adoc
  modules/installation-creating-gcp-private-dns.adoc
  modules/installation-creating-gcp-vpc.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-extracting-infraid.adoc
  modules/installation-gcp-enabling-confidential-vms.adoc
  modules/installation-gcp-enabling-shielded-vms.adoc
  modules/installation-gcp-user-infra-adding-ingress.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-initializing.adoc
  modules/installation-user-infra-exporting-common-variables.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86995 Fixing some typos
  edge_computing/day_2_core_cnf_clusters/observability/telco-observability.adoc
  modules/ibi-create-config-iso.adoc
  modules/microshift-automation-example-bootc-systems.adoc
  modules/microshift-ingress-controller-config.adoc
  modules/network-observability-multitenancy.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nw-bpfman-operator-deploy.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/telco-troubleshooting-mco-purpose.adoc
  modules/virt-configuring-vm-use-usb-device.adoc
  modules/virt-enabling-usb-host-passthrough.adoc
  networking/multiple_networks/primary_networks/about-primary-nwt-nad.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#87026 HCIDOCS-260: 4.14 cherry pick for 86823
  modules/bmo-about-the-baremetalhost-resource.adoc
  modules/installation-special-config-raid.adoc
Labels: size/S, jira/valid-reference

#87021 HCIDOCS-260: 4.15 cherry pick for 86823
  modules/bmo-about-the-baremetalhost-resource.adoc
  modules/installation-special-config-raid.adoc
Labels: size/S, jira/valid-reference

#86953 CNV#54774: OVE overview
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/ove-about.adoc
  modules/ove-support.adoc
  overview/ove-overview.adoc
Labels: peer-review-done, size/M

#85820 ROX-21712: Add note about compliance operator
  operating/compliance-operator-rhacs.adoc
Labels: peer-review-done, size/S, RHACS, jira/valid-reference, rhacs-docs-4.4, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7

#87032 [enterprise-4.17] Fixing some typos
  edge_computing/day_2_core_cnf_clusters/observability/telco-observability.adoc
  modules/ibi-create-config-iso.adoc
  modules/network-observability-multitenancy.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nw-bpfman-operator-deploy.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/telco-troubleshooting-mco-purpose.adoc
  modules/virt-configuring-vm-use-usb-device.adoc
  modules/virt-enabling-usb-host-passthrough.adoc
  networking/multiple_networks/primary_networks/about-primary-nwt-nad.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/L

#87033 [enterprise-4.16] Fixing some typos
  edge_computing/day_2_core_cnf_clusters/observability/telco-observability.adoc
  modules/network-observability-multitenancy.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  modules/telco-observability-key-performance-metrics.adoc
  modules/telco-troubleshooting-mco-purpose.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/M

#87034 [enterprise-4.15] Fixing some typos
  modules/network-observability-multitenancy.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/M

#87035 [enterprise-4.14] Fixing some typos
  modules/network-observability-multitenancy.adoc
  modules/nodes-vsphere-machine-set-scaling-static-ip.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/M

#87037 [enterprise-4.13] Fixing some typos
  modules/network-observability-multitenancy.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  modules/oadp-usecase-include-ca-cert-backup.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/M

#87036 [enterprise-4.12] Fixing some typos
  modules/network-observability-multitenancy.adoc
  modules/nw-external-dns-operator-configuration-parameters.adoc
  modules/nw-sriov-networknodepolicy-object.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: size/S

#86934 RHDEVDOCS-6320: Update Installation instructions
  modules/ob-installing-builds-with-operator.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference

#86935 OSDOCS-12163: adds 4.15.43 relnotes Microshift
  microshift_release_notes/microshift-4-15-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference

#86799 OSDOCS#12803: Pausing the node health check in HCP during updates
  modules/hcp-updates-hosted-cluster.adoc
Labels: peer-review-done, size/XS, ok-to-merge, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86999 [enterprise-4.14] TELCODOCS-1990: Latency tests content feedback from docfooding workshop
  modules/cnf-performing-end-to-end-tests-running-cyclictest.adoc
  modules/cnf-performing-end-to-end-tests-running-hwlatdetect.adoc
  modules/cnf-performing-end-to-end-tests-running-oslat.adoc
  modules/cnf-performing-end-to-end-tests-running-the-tests.adoc
  scalability_and_performance/low_latency_tuning/cnf-performing-platform-verification-latency-tests.adoc
Labels: size/M, jira/valid-reference

#87046 RHDEVDOCS 6349 fix Pipelines version - Pipelines doc
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress

#87062 [enterprise-4.14] OSDOCS-12577:removing duplicate prereqs
  modules/cli-logging-in-kubeadmin.adoc
  modules/installation-configure-proxy.adoc
  modules/installation-creating-gcp-bootstrap.adoc
  modules/installation-creating-gcp-control-plane.adoc
  modules/installation-creating-gcp-firewall-rules-vpc.adoc
  modules/installation-creating-gcp-iam-shared-vpc.adoc
  modules/installation-creating-gcp-lb.adoc
  modules/installation-creating-gcp-private-dns.adoc
  modules/installation-creating-gcp-vpc.adoc
  modules/installation-creating-gcp-worker.adoc
  modules/installation-extracting-infraid.adoc
  modules/installation-gcp-enabling-confidential-vms.adoc
  modules/installation-gcp-enabling-shielded-vms.adoc
  modules/installation-gcp-user-infra-adding-ingress.adoc
  modules/installation-gcp-user-infra-completing.adoc
  modules/installation-gcp-user-infra-wait-for-bootstrap.adoc
  modules/installation-initializing.adoc
  modules/installation-user-infra-exporting-common-variables.adoc
  modules/installation-user-infra-generate-k8s-manifest-ignition.adoc
Labels: size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference

#87020 OSSM-8666: Wrong extensionProviders name in example
  modules/ossm-config-otel.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#87051 [monitoring-docs-restructure] OBSDOCS-1527: Add missing information to the monitoring dashboards se…
  images/observe-dashboard-developer.png
  modules/monitoring-about-monitoring-dashboards.adoc
  modules/monitoring-querying-metrics-for-all-projects-with-mon-dashboard.adoc
  modules/monitoring-querying-metrics-for-user-defined-projects-with-mon-dashboard.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
  modules/sd-monitoring-troubleshooting-issues.adoc
Labels: size/M, jira/valid-reference

#86343 OBSDOCS-1546: Logging Z-Stream Release Notes - 6.1.1
  modules/log6x-6-1-1-rn.adoc
  observability/logging/logging-6.1/log6x-release-notes-6.1.adoc
Labels: peer-review-done, size/M, ok-to-merge, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18

#86340 OBSDOCS-1545: Logging Z-Stream Release Notes - 6.0.3
  modules/log6x-rn-6.0.3.adoc
  observability/logging/logging-6.0/log6x-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17

#86355 OBSDOCS-1544: Logging Z-Stream Release Notes - 5.9.10
  modules/logging-release-notes-5-9-10.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, size/M, ok-to-merge, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#87073 Fixing heading offsets
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18

#87019 OSDOCS-13114: Update short-term creds note for Entra postinstall
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#86911 OSDOCS-12922: adds 4.16.30 relnote MicroShift
  microshift_release_notes/microshift-4-16-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#86554 [OSDOCS-12980]Non-ROSA workloads on control plane and infra nodes
  modules/rosa-sdpolicy-instance-types.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-hcp-service-definition.adoc
  rosa_architecture/rosa_policy_service_definition/rosa-service-definition.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18

#87000 OSDOCS-13063: 4.15.43 RN
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.15

#87083 [enterprise-4.16] OSDOCS-13114: Update short-term creds note for Entra postinstall
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
Labels: size/XS, jira/valid-reference

#87085 [enterprise-4.14] OSDOCS-13114: Update short-term creds note for Entra postinstall
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
Labels: size/XS, jira/valid-reference

#87084 [enterprise-4.15] OSDOCS-13114: Update short-term creds note for Entra postinstall
  authentication/managing_cloud_provider_credentials/cco-short-term-creds.adoc
Labels: size/XS, jira/valid-reference

#87089 Revert "OCPBUGS-48192: clarifying the role of the root cred in CCO mint mode"
  authentication/managing_cloud_provider_credentials/cco-mode-mint.adoc
  modules/manually-removing-cloud-creds.adoc
  post_installation_configuration/changing-cloud-credentials-configuration.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference
