Repository openshift/openshift-docs, pull requests merged in 2025-10, with the labels that each got.

#99895 [RHACS] [Docs] ROX-31094: Updating rhacs version
  modules/common-attributes.adoc
Labels: size/XS, RHACS, jira/valid-reference, rhacs-docs-4.9

#98792 PR for SRVKE-1740: Document "IntegrationSource" section in OpenShift Serverless Eventing docs
  _topic_maps/_topic_map.yml
  eventing/event-sources/serverless-getting-started-integrationsource.adoc
  modules/serverless-creating-integrationsource-for-aws-sqs.adoc
  modules/serverless-creating-integrationsource-for-aws-sss.adoc
  modules/serverless-creating-integrationsource-for-dynamodbstreams.adoc
  modules/serverless-creating-integrationsource-for-timer.adoc
  modules/serverless-integrationsource-aws-dynamodb-streams.adoc
  modules/serverless-integrationsource-aws-simple-queue-service.adoc
  modules/serverless-integrationsource-aws-simple-storage-service.adoc
  modules/serverless-integrationsource-aws-timer-source.adoc
  modules/serverless-integrationsource-creating-aws-credentials.adoc
Labels: size/L, serverless, jira/valid-reference

#99848 OSDOCS-16288:Removed duplicate AWS prereqs section from HCP docs.
  modules/osd-aws-privatelink-firewall-prerequisites.adoc
  modules/rosa-hcp-firewall-prerequisites.adoc
  rosa_planning/rosa-sts-aws-prereqs.adoc
Labels: lgtm, size/S, jira/valid-reference

#98723 OCPBUGS-46042: Swapped out Shared Gateway Mode for routingViaHost
  _topic_maps/_topic_map.yml
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ovn-ipsec-north-south-enable.adoc
  modules/nw-routeadvertisements-about.adoc
  modules/nw-routeadvertisements-example.adoc
  modules/nwt-configure-egress-routing-policies.adoc
  modules/telco-core-cluster-network-operator.adoc
  modules/telco-core-load-balancer.adoc
  networking/network_security/configuring-ipsec-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-gateway-mode.adoc
  networking/ovn_kubernetes_network_provider/configuring-gateway.adoc
Labels: lgtm, size/L, jira/invalid-bug, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99930 [enterprise-4.16] : Swapped out Shared Gateway Mode for routingViaHost
  _topic_maps/_topic_map.yml
  modules/nw-egressnetworkpolicy-about.adoc
  modules/nw-ovn-ipsec-north-south-enable.adoc
  modules/nw-routeadvertisements-about.adoc
  modules/nwt-configure-egress-routing-policies.adoc
  modules/telco-core-cluster-network-operator.adoc
  modules/telco-core-load-balancer.adoc
  networking/network_security/configuring-ipsec-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-gateway-mode.adoc
  networking/ovn_kubernetes_network_provider/configuring-gateway.adoc
Labels: size/L

#99943 [enterprise-4.14] OCPBUGS-46042: Swapped out Shared Gateway Mode for routingViaHost
  modules/nw-egressnetworkpolicy-about.adoc
  modules/telco-core-load-balancer.adoc
  networking/ovn_kubernetes_network_provider/configuring-gateway.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference

#99912 CNV-69519: Fix multipath commands
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: lgtm, size/XS, CNV, jira/valid-reference, branch/enterprise-4.19

#92107 OSDOCS-14021#adding port info
  modules/installation-network-user-infra.adoc
Labels: peer-review-done, size/XS, lifecycle/stale, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#99928 OSDOCS-15107 Updating firewall reqs in RN
  release_notes/ocp-4-20-release-notes.adoc
Labels: size/XS, branch/enterprise-4.20

#99981 Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99984 [monitoring-docs-4.19] Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99985 [monitoring-docs-4.18] Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99986 [monitoring-docs-4.17] Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99987 [monitoring-docs-4.16] Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99988 [monitoring-docs-4.15] Fix RN link from single page to multi-page
  release-notes/monitoring-release-notes.adoc
Labels: size/XS

#99861 OBSDOCS-2379: Logging Z-Stream Release Notes - 5.8.22
  modules/logging-release-notes-5-8-22.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: size/S, jira/valid-reference

#99884 OSDOCS-14980-417: manual CP
  _topic_maps/_topic_map_ms.yml
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
  microshift_configuring/microshift-config-snippets.adoc
  microshift_configuring/microshift-default-config-yaml.adoc
  microshift_configuring/microshift-node-access-kubeconfig.adoc
  microshift_configuring/microshift_auth_security/_attributes
  microshift_configuring/microshift_auth_security/images
  microshift_configuring/microshift_auth_security/microshift-audit-logs-config.adoc
  microshift_configuring/microshift_auth_security/microshift-custom-ca.adoc
  microshift_configuring/microshift_auth_security/modules
  microshift_configuring/microshift_auth_security/snippets
  microshift_install_bootc/microshift-install-rhel-image-mode.adoc
  microshift_install_rpm/microshift-access-node.adoc
  microshift_install_rpm/microshift-install-rpm.adoc
  microshift_install_rpm/microshift-stop-start.adoc
  microshift_install_rpm/microshift-uninstall-rpm.adoc
  microshift_install_rpm_ostree/microshift-embed-in-rpm-ostree-offline-use.adoc
  microshift_install_rpm_ostree/microshift-embed-in-rpm-ostree.adoc
  microshift_running_apps/microshift-authentication.adoc
  modules/microshift-accessing-node-locally.adoc
  modules/microshift-accessing-node-open-firewall.adoc
  modules/microshift-accessing-node-remotely.adoc
  modules/microshift-accessing.adoc
  modules/microshift-kubeconfig-generating-additional-files.adoc
  modules/microshift-kubeconfig-local-access.adoc
  modules/microshift-kubeconfig-overview.adoc
  modules/microshift-kubeconfig-remote-con.adoc
Labels: size/L, jira/valid-reference

#100023 add table for BSI fix typos
  modules/compliance-supported-profiles.adoc
Labels: lgtm, size/XS, ok-to-merge, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#100041 CNV: 66740 - Deleted Admonition
  modules/virt-define-guest-agent-ping-probe.adoc
Labels: size/XS, CNV, branch/enterprise-4.20

#100058 [enterprise-4.14] OSDOCS#16255: Removing unused modules from main+back
  modules/builds-image-change-trigger-identification.adoc
  modules/builds-source-input-subman-config.adoc
  modules/builds-strategy-docker-force-pull-example.adoc
  modules/builds-strategy-force-pull-procedure.adoc
  modules/builds-strategy-s2i-force-pull-example.adoc
  modules/configuring-hpa-based-on-application-metrics.adoc
  modules/dynamic-provisioning-ceph-rbd-definition.adoc
  modules/dynamic-provisioning-gluster-definition.adoc
  modules/enabling-multi-cluster-console.adoc
  modules/enabling-plug-in-browser.adoc
  modules/images-create-metadata-define.adoc
  modules/ldap-failover-configure-apache.adoc
  modules/ldap-failover-configure-openshift.adoc
  modules/ldap-failover-configure-sssd.adoc
  modules/ldap-failover-generate-certs.adoc
  modules/ldap-failover-overview.adoc
  modules/ldap-failover-prereqs.adoc
  modules/multi-cluster-about.adoc
  modules/nodes-cluster-overcommit-buffer-chunk.adoc
  modules/nodes-cluster-resource-override-deploy.adoc
  modules/nodes-nodes-cluster-timeout-graceful-shutdown.adoc
  modules/nodes-nodes-configuring-graceful-shutdown.adoc
  modules/nodes-pods-secrets-creating-tls.adoc
  modules/nodes-scheduler-node-names-configuring.adoc
  modules/nodes-scheduler-node-projects-about.adoc
  modules/nodes-scheduler-node-projects-configuring.adoc
  modules/nodes-scheduler-node-selectors-configuring.adoc
  modules/persistent-storage-csi-ebs-operator-install-driver.adoc
  modules/persistent-storage-csi-ebs-operator-install.adoc
  modules/persistent-storage-csi-manila-install-driver.adoc
  modules/persistent-storage-csi-manila-install-operator.adoc
  modules/persistent-storage-csi-manila-uninstall-operator.adoc
  modules/persistent-storage-csi-migration-automatic-ga.adoc
  modules/persistent-storage-csi-migration-enable.adoc
  modules/persistent-storage-csi-migration-overview-support-level.adoc
  modules/persistent-storage-csi-olm-driver-uninstall.adoc
  modules/persistent-storage-csi-tp-enable.adoc
  modules/persistent-storage-manila-install.adoc
  modules/persistent-storage-manila-usage.adoc
  modules/persistent-storage-vsphere-backup.adoc
  modules/prometheus-operator.adoc
  modules/service-accounts-configuration-parameters.adoc
  modules/service-accounts-enabling-authentication.adoc
  modules/service-accounts-using-credentials-inside-a-container.adoc
  modules/service-ca-certificates.adoc
  modules/storage-persistent-storage-efs-authorization.adoc
  modules/storage-persistent-storage-efs-configmap.adoc
  modules/storage-persistent-storage-efs-provisioner.adoc
  modules/storage-persistent-storage-efs-pvc.adoc
  modules/storage-persistent-storage-efs-storage-class.adoc
  modules/upgrade-49-acknowledgement.adoc
Labels: size/XXL

#99927 Fixing some typos
  hosted_control_planes/hosted-control-planes-release-notes.adoc
  modules/coo-troubleshooting-ui-plugin-using.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/machine-config-pin-preload-images.adoc
  modules/microshift-verify-container-signatures-sigstore.adoc
  modules/monitoring-reviewing-monitoring-dashboards-developer.adoc
  modules/network-observability-filtering-ebpf-rule.adoc
  modules/persistent-storage-csi-azure-file-static-provisioning-procedure.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/rosa-sdpolicy-platform.adoc
  modules/virt-creating-fusionaccess-cr.adoc
  networking/network_security/network-policy-apis.adoc
  rosa_release_notes/rosa-release-notes.adoc
  security/zero_trust_workload_identity_manager/zero-trust-manager-release-notes.adoc
Labels: lgtm, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#100070 [enterprise-4.15] Fixing some typos
  modules/coo-troubleshooting-ui-plugin-using.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/network-observability-filtering-ebpf-rule.adoc
  modules/persistent-storage-csi-azure-file-static-provisioning-procedure.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
  modules/rosa-sdpolicy-platform.adoc
Labels: size/M

#100073 [enterprise-4.12] Fixing some typos
  modules/coo-troubleshooting-ui-plugin-using.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/network-observability-filtering-ebpf-rule.adoc
  modules/persistent-storage-csi-drivers-supported.adoc
Labels: size/S

#100007 OSDOCS-16392 Updating remaining install config param tables for readability
  modules/agent-configuration-parameters.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/XXL, merge-review-in-progress, merge-review-needed, branch/enterprise-4.19, branch/enterprise-4.20

#100080 [enterprise-4.19] OSDOCS-16392 Updating remaining install config param tables for readability
  modules/agent-configuration-parameters.adoc
  modules/installation-configuration-parameters.adoc
Labels: size/XXL, branch/enterprise-4.19

#97530 OSDOCS#66695: Reworking the virtctl commands module
  modules/virt-generating-a-vm-memory-dump.adoc
  modules/virt-hot-plug-and-hot-unplug-commands.adoc
  modules/virt-image-upload-commands.adoc
  modules/virt-virtctl-commands.adoc
  modules/virt-virtctl-information-commands.adoc
  modules/virt-vm-connection-commands.adoc
  modules/virt-vm-export-commands.adoc
  modules/virt-vm-information-commands.adoc
  modules/virt-vm-management-commands.adoc
  modules/virt-vm-manifest-creation-commands.adoc
  virt/about_virt/virt-architecture.adoc
  virt/getting_started/virt-getting-started.adoc
  virt/getting_started/virt-using-the-cli-tools.adoc
  virt/managing_vms/virt-exporting-vms.adoc
  virt/support/virt-collecting-virt-data.adoc
Labels: size/XL, CNV, branch/enterprise-4.20

#100084 OSDOCS#16526: Removed unused modules
  modules/kubernetes-about.adoc
  modules/oc-mirror-differential-updates.adoc
Labels: size/M

#100108 Fix vale for 4.19
  modules/monitoring-4-19-release-notes.adoc
Labels: size/XS

#100114 (enterprise-4.18) Moving PIS and MCN release notes to 4.19.12 and updating PIS tech preview table to GA
  release_notes/ocp-4-18-release-notes.adoc
Labels: size/S, branch/enterprise-4.18

#100118 OSDOCS-16326-419: manual CP
  _topic_maps/_topic_map_ms.yml
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
  microshift_cli_ref/microshift-cli-using-oc.adoc
  microshift_configuring/microshift-config-snippets.adoc
  microshift_configuring/microshift-default-config-yaml.adoc
  microshift_configuring/microshift-greenboot-checking-status.adoc
  microshift_configuring/microshift-ingress-controller.adoc
  microshift_configuring/microshift-using-config-yaml.adoc
  microshift_configuring/microshift_auth_security/microshift-tls-config.adoc
  microshift_configuring/microshift_low_latency/microshift-low-latency.adoc
  microshift_install_get_ready/microshift-install-get-ready.adoc
  microshift_install_rpm/microshift-install-rpm.adoc
  microshift_networking/microshift-cni.adoc
  microshift_networking/microshift-nw-router.adoc
  microshift_support/microshift-remote-cluster-monitoring.adoc
  modules/microshift-ingress-controller-conc.adoc
  modules/microshift-ingress-controller-config.adoc
  modules/microshift-ingress-controller-create-cert-secret.adoc
  modules/microshift-ingress-controller-tls-config.adoc
Labels: size/M, jira/valid-reference

#100136 [enterprise-4.17][OSDOCS-16219]: Removing duplication from procedure to create a hosted cluster on bare metal
  hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
  hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
Labels: size/XS

#100137 OSDOCS-16326-416: manual CP
  microshift_cli_ref/microshift-cli-tools-introduction.adoc
  microshift_cli_ref/microshift-cli-using-oc.adoc
  microshift_configuring/microshift-default-config-yaml.adoc
  microshift_configuring/microshift-greenboot-checking-status.adoc
  microshift_configuring/microshift-using-config-yaml.adoc
  microshift_install_get_ready/microshift-install-get-ready.adoc
  microshift_networking/microshift-cni.adoc
  microshift_networking/microshift-nw-router.adoc
Labels: size/M, jira/valid-reference

#99972 OSDOCS-16383:Update the z-stream RNs for 4.19.15
  release_notes/ocp-4-19-release-notes.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#100123 [OSDOCS#15979] Remove deprecated assemblies
  metering/configuring_metering/metering-about-configuring.adoc
  metering/configuring_metering/metering-common-config-options.adoc
  metering/configuring_metering/metering-configure-aws-billing-correlation.adoc
  metering/configuring_metering/metering-configure-hive-metastore.adoc
  metering/configuring_metering/metering-configure-persistent-storage.adoc
  metering/configuring_metering/metering-configure-reporting-operator.adoc
  metering/metering-about-metering.adoc
  metering/metering-installing-metering.adoc
  metering/metering-troubleshooting-debugging.adoc
  metering/metering-uninstall.adoc
  metering/metering-upgrading-metering.adoc
  metering/metering-usage-examples.adoc
  metering/metering-using-metering.adoc
  metering/reports/metering-about-reports.adoc
  metering/reports/metering-storage-locations.adoc
Labels: lgtm, size/XL, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20

#95877 [enterprise-4.19] Need to add colon and remove bold object names from documentation
  observability/logging/logging-6.0/log6x-upgrading-to-6.adoc
Labels: size/S

#99508 OSDOCS#16195 removing [discrete] tags from ROSA and OSD
  cloud_experts_tutorials/cloud-experts-aws-secret-manager.adoc
  cloud_experts_tutorials/cloud-experts-deploying-application/cloud-experts-deploying-application-prerequisites.adoc
  modules/rosa-hcp-create-network.adoc
  modules/rosa-hcp-vpc-manual.adoc
  modules/rosa-hcp-vpc-terraform.adoc
  modules/rosa-sts-account-wide-role-and-policy-commands.adoc
  modules/rosa-sts-account-wide-roles-and-policies.adoc
  modules/rosa-sts-byo-oidc-options.adoc
  osd_cluster_admin/osd_nodes/osd-nodes-about-autoscaling-nodes.adoc
  rosa_architecture/rosa-oidc-overview.adoc
  rosa_architecture/rosa-sts-about-iam-resources.adoc
  rosa_architecture/rosa-understanding.adoc
  rosa_cluster_admin/rosa-cluster-autoscaling-hcp.adoc
  rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc
  rosa_getting_started/rosa-quickstart-guide-ui.adoc
  rosa_hcp/rosa-hcp-creating-cluster-with-aws-kms-key.adoc
  rosa_hcp/rosa-hcp-egress-zero-install.adoc
  rosa_hcp/rosa-hcp-quickstart-guide.adoc
  rosa_hcp/rosa-hcp-shared-vpc-config.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  rosa_hcp/terraform/rosa-hcp-creating-a-cluster-quickly-terraform.adoc
  rosa_install_access_delete_clusters/rosa-shared-vpc-config.adoc
  rosa_install_access_delete_clusters/terraform/rosa-classic-creating-a-cluster-quickly-terraform.adoc
  rosa_planning/rosa-hcp-aws-prereqs.adoc
  rosa_planning/rosa-sts-aws-prereqs.adoc
  rosa_planning/rosa-sts-ocm-role.adoc
Labels: size/L, branch/enterprise-4.19, branch/enterprise-4.20

#99979 delete unused files
  backup_and_restore/application_backup_and_restore/installing/oadp-12-data-mover-ceph-doc.adoc
  backup_and_restore/application_backup_and_restore/installing/oadp-cleaning-up-after-data-mover-1-1-backup-doc.adoc
  modules/oadp-ceph-cephfs-back-up-dba.adoc
  modules/oadp-ceph-cephfs-back-up.adoc
  modules/oadp-ceph-cephfs-restore.adoc
  modules/oadp-ceph-preparing-cephfs-crs.adoc
  modules/oadp-ceph-preparing-cephrbd-crs.adoc
  modules/oadp-ceph-preparing-crs-additional.adoc
  modules/oadp-ceph-prerequisites.adoc
  modules/oadp-ceph-split-back-up-dba.adoc
  modules/oadp-cleaning-up-after-data-mover-snapshots.adoc
  modules/oadp-converting-dpa-to-new-version-1-3-0.adoc
  modules/oadp-converting-to-new-dpa-1-2-0.adoc
  modules/oadp-deleting-cluster-resources-following-failure.adoc
  modules/oadp-deleting-cluster-resources-following-success.adoc
  modules/oadp-deletion-policy-1-2.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-oadp-rosa-sts.adoc
  modules/oadp-preparing-aws-credentials.adoc
  modules/oadp-upgrade-from-oadp-data-mover-1-2-0.adoc
  modules/oadp-upgrading-oadp-operator-1-2-0.adoc
  modules/oadp-upgrading-oadp-operator-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-vsb-cleanup-after-scheduler.adoc
  modules/support-insecure-tls-connections.adoc
Labels: size/XXL, OADP, branch/enterprise-4.17

#100163 OSDOCS#16135: Adding Kueue to additional resources
  release_notes/addtl-release-notes.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.18

#99907 Oadp delete unused files
  backup_and_restore/application_backup_and_restore/installing/oadp-12-data-mover-ceph-doc.adoc
  backup_and_restore/application_backup_and_restore/installing/oadp-cleaning-up-after-data-mover-1-1-backup-doc.adoc
  modules/migration-combining-must-gather.adoc
  modules/migration-creating-ca-bundle.adoc
  modules/oadp-backing-up-dpa-configuration-1-2-0.adoc
  modules/oadp-backing-up-dpa-configuration-1-3-0.adoc
  modules/oadp-ceph-cephfs-back-up-dba.adoc
  modules/oadp-ceph-cephfs-back-up.adoc
  modules/oadp-ceph-cephfs-restore.adoc
  modules/oadp-ceph-preparing-cephfs-crs.adoc
  modules/oadp-ceph-preparing-cephrbd-crs.adoc
  modules/oadp-ceph-preparing-crs-additional.adoc
  modules/oadp-ceph-prerequisites.adoc
  modules/oadp-ceph-split-back-up-dba.adoc
  modules/oadp-cleaning-up-after-data-mover-snapshots.adoc
  modules/oadp-converting-dpa-to-new-version-1-3-0.adoc
  modules/oadp-converting-to-new-dpa-1-2-0.adoc
  modules/oadp-deleting-cluster-resources-following-failure.adoc
  modules/oadp-deleting-cluster-resources-following-success.adoc
  modules/oadp-deletion-policy-1-2.adoc
  modules/oadp-installing-dpa-1-2-and-earlier.adoc
  modules/oadp-installing-oadp-rosa-sts.adoc
  modules/oadp-preparing-aws-credentials.adoc
  modules/oadp-upgrade-from-oadp-data-mover-1-2-0.adoc
  modules/oadp-upgrading-oadp-operator-1-2-0.adoc
  modules/oadp-upgrading-oadp-operator-1-3-0.adoc
  modules/oadp-verifying-upgrade-1-3-0.adoc
  modules/oadp-vsb-cleanup-after-scheduler.adoc
  modules/support-insecure-tls-connections.adoc
Labels: size/XXL, OADP, branch/enterprise-4.18

#100160 OSDOCS#16135: Adding Kueue to additional resources
  release_notes/addtl-release-notes.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.20

#100162 OSDOCS#16135: Adding Kueue to additional resources
  release_notes/addtl-release-notes.adoc
Labels: size/XS, merge-review-in-progress, branch/enterprise-4.19

#99761 [RHDEVDOCS-6764] Add IBM Z env into 1.20 RN
  modules/op-release-notes-1-20-0.adoc
Labels: size/XS

#96680 OSDOCS-13806: Add AWS region Mexico Central.
  modules/installation-aws-regions.adoc
Labels: size/XS, ok-to-merge, jira/valid-reference, branch/enterprise-4.20

#100026 OSDOCS#16398: rename operatorhub to software catalog in filenames, ids, xrefs, and topic maps
  _topic_maps/_topic_map.yml
  _topic_maps/_topic_map_osd.yml
  _topic_maps/_topic_map_rosa.yml
  _topic_maps/_topic_map_rosa_hcp.yml
  architecture/control-plane.adoc
  backup_and_restore/application_backup_and_restore/aws-sts/oadp-aws-sts.adoc
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/oadp-rosa/oadp-rosa-backing-up-applications.adoc
  cicd/pipelines/installing-pipelines.adoc
  modules/olm-installing-from-software-catalog-using-cli.adoc
  modules/olm-installing-from-software-catalog-using-web-console.adoc
  modules/olm-installing-operators-from-software-catalog-configure.adoc
  modules/olm-installing-operators-from-software-catalog.adoc
  modules/olm-software-catalog-architecture.adoc
  modules/olm-software-catalog-overview.adoc
  observability/distr_tracing/distr-tracing-tempo-installing.adoc
  observability/otel/otel-installing.adoc
  operators/admin/olm-adding-operators-to-cluster.adoc
  operators/admin/olm-cs-podsched.adoc
  operators/index.adoc
  operators/operator_sdk/token_auth/osdk-cco-aws-sts.adoc
  operators/operator_sdk/token_auth/osdk-cco-azure.adoc
  operators/operator_sdk/token_auth/osdk-cco-gcp.adoc
  operators/understanding/olm-understanding-software-catalog.adoc
  operators/understanding/olm/olm-understanding-olm.adoc
  operators/user/olm-installing-operators-in-namespace.adoc
  osd_cluster_admin/dedicated-admin-role.adoc
  post_installation_configuration/configuring-multi-arch-compute-machines/multiarch-tuning-operator.adoc
  post_installation_configuration/preparing-for-users.adoc
  rosa_architecture/index.adoc
  serverless/install/preparing-serverless-install.adoc
  web_console/capabilities_products-web-console.adoc
  welcome/learn_more_about_openshift.adoc
  whats_new/new-features.adoc
Labels: size/L, branch/enterprise-4.20

#100192 OSDOCS-16338-419RN: manual CP release notes
  microshift_release_notes/microshift-4-19-release-notes.adoc
Labels: size/S

#100177 OSDOCS#16434: Open the firewall port 53 on TCP for HCP
  hosted_control_planes/hcp-prepare/hcp-requirements.adoc
  modules/hcp-proxy-cp-workloads.adoc
Labels: lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19, branch/enterprise-4.20
