Repository openshift/openshift-docs, pull requests merged in 2025-04, with the labels that each got.

#88418 RHDEVDOCS-6339: Content creation for CMP
  argocd_instance/argo-cd-cr-component-properties.adoc
  modules/con-enabling-config-management-plugins-argo-cd-cr.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference

#89980 CNV#45693- Fix kubevirt_vmi_vcpu_wait_seconds_total docs to be IO specific
  modules/virt-querying-metrics.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#90047 RHDEVDOCS-6337: Content creation for GitOps 1.16 RN
  _topic_maps/_topic_map.yml
  accesscontrol_usermanagement/configuring-sso-for-argo-cd-using-keycloak.adoc
  modules/gitops-release-notes-1-16-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
  release_notes/gitops-release-notes-1-16.adoc
Labels: peer-review-done, size/L, ok-to-merge, merge-review-in-progress, jira/valid-reference

#90684 OCPBUGS-52488: Removed note from configuring-egress-ips-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91383 OCPBUGS-52488: Removed note from configuring-egress-ips-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: size/XS, jira/severity-important, jira/valid-reference, branch/enterprise-4.16

#91384 OCPBUGS-52488: Removed note from configuring-egress-ips-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#91385 OCPBUGS-52488: Removed note from configuring-egress-ips-ovn.adoc
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14

#91382 [gitops-docs-1.16] RHDEVDOCS-6337: Content creation for GitOps 1.16 RN
  _topic_maps/_topic_map.yml
  accesscontrol_usermanagement/configuring-sso-for-argo-cd-using-keycloak.adoc
  modules/gitops-release-notes-1-16-0.adoc
  modules/go-compatibility-and-support-matrix.adoc
  release_notes/gitops-release-notes-1-16.adoc
Labels: size/L, jira/valid-reference

#91118 OBSDOCS#1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91368 [enterprise-4.16] OCPBUGS:48509 Configuring Linux cgroup docs are referencing to enabled psi which has been disabled with 4.16.7
  modules/nodes-clusters-cgroups-2.adoc
Labels: size/XS

#91367 [enterprise-4.19] OCPBUGS:48509 Configuring Linux cgroup docs are referencing to enabled psi which has been disabled with 4.16.7
  modules/nodes-clusters-cgroups-2.adoc
Labels: size/XS

#91366 [enterprise-4.18] OCPBUGS:48509 Configuring Linux cgroup docs are referencing to enabled psi which has been disabled with 4.16.7
  modules/nodes-clusters-cgroups-2.adoc
Labels: size/XS

#91365 [enterprise-4.17] OCPBUGS:48509 Configuring Linux cgroup docs are referencing to enabled psi which has been disabled with 4.16.7
  modules/nodes-clusters-cgroups-2.adoc
Labels: size/XS

#91391 [enterprise-4.12] OBSDOCS#1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: size/M

#91392 [enterprise-4.13] OBSDOCS#1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: size/M

#91393 [enterprise-4.14] OBSDOCS-1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: size/M, jira/valid-reference

#91394 [enterprise-4.15] OBSDOCS-1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: size/M, jira/valid-reference

#91395 [enterprise-4.16] OBSDOCS-1324: Improve 'troubleshooting monitoring issues: Investigati…
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: size/M, jira/valid-reference

#88687 OCPBUGS#43475: Drop Ethernet adaptor hardware address requirements
  modules/installation-network-user-infra.adoc
Labels: peer-review-done, lgtm, size/S, needs-ok-to-test, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91403 [rhacs] update version number
  modules/common-attributes.adoc
Labels: size/XS

#91404 [rhacs] update version number
  modules/common-attributes.adoc
Labels: size/XS, rhacs-docs-4.5

#91336 OBSDOCS-1739: Add new dashboard screenshots
  images/monitoring-dashboard-administrator.png
  images/observe-dashboard-developer.png
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91415 [enterprise-4.14] OBSDOCS-1739: Add new dashboard screenshots
  images/monitoring-dashboard-administrator.png
  images/observe-dashboard-developer.png
Labels: size/XS, jira/valid-reference

#91416 [enterprise-4.15] OBSDOCS-1739: Add new dashboard screenshots
  images/monitoring-dashboard-administrator.png
  images/observe-dashboard-developer.png
Labels: size/XS, jira/valid-reference

#91417 [enterprise-4.16]OBSDOCS-1739: Add new dashboard screenshots
  images/monitoring-dashboard-administrator.png
  images/observe-dashboard-developer.png
Labels: size/XS, jira/valid-reference

#90393 Adds a consideration when migrating
  modules/nw-ovn-kubernetes-live-migration-about.adoc
  modules/nw-ovn-kubernetes-migration-about.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.15, branch/enterprise-4.16

#90436 TELCODOCS-2127: RN for kernelpagesize API
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#91422 Remove aireilly from edge_computing OWNERS
  edge_computing/OWNERS
Labels: size/XS

#89042 OADP-3215: Implement suggestions related to MCG
  backup_and_restore/application_backup_and_restore/aws-sts/oadp-aws-sts.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
  backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc
  modules/migration-configuring-mcg.adoc
  modules/oadp-about-backup-snapshot-locations-secrets.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, OADP, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#91361 [OSDOCS-13914]Update certifications in OSD docs
  modules/policy-security-regulation-compliance.adoc
Labels: peer-review-done, lgtm, size/XS, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#90860 OSSM-8955 [DOC] Add text about using "latest" in the "version" field of the Istio CRD
  modules/ossm-about-concepts-resources.adoc
Labels: peer-review-done, size/XS, service-mesh, merge-review-in-progress, merge-review-needed

#91436 [enterprise-4.19] OADP-4561: Update parent ToC for Troubleshooting modules
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/issues-with-velero-and-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/velero-cli-tool.adoc
  backup_and_restore/index.adoc
  modules/oadp-monitoring.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
Labels: size/XL, jira/valid-reference, branch/enterprise-4.19

#91090 ROX-26909: Update scanner v4 db parameter
  modules/central-configuration-options-operator.adoc
  modules/central-services-public-config.adoc
  modules/secured-cluster-configuration-options-operator.adoc
Labels: peer-review-done, size/S, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8

#91435 DIAGRAMS-504: Layer 2 UDN diagram
  images/504_OpenShift_UDN_L2_0325.png
  modules/nw-udn-best-practices.adoc
  modules/nw-udn-l2-l3.adoc
  modules/nw-udn-limitations.adoc
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
Labels: size/S, branch/enterprise-4.17

#90902 [OCPBUGS-49679]: Improvements to restoring the cluster state procedure
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17

#85892 ROX-27142: clarify automatic upgrades for secured clusters
  _topic_maps/_topic_map.yml
  configuration/configure-automatic-upgrades.adoc
  modules/automatic-upgrade-failure.adoc
  modules/automatic-upgrade-status.adoc
  modules/disable-automatic-upgrades.adoc
  modules/enable-automatic-upgrades.adoc
  modules/manual-upgrade-secured-clusters.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8

#91358 Adds important note to OMR ensuring that it's not intended to be used…
  disconnected/mirroring/installing-mirroring-creating-registry.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#90231 OSDOCS#13517: Note 4-, 5-node HA clusters in etcd quorum restore docs
  modules/dr-restoring-cluster-state.adoc
  modules/dr-restoring-etcd-quorum-ha.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.18, branch/enterprise-4.19

#91453 [enterprise 4.16] CP-89097
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/issues-with-velero-and-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/velero-cli-tool.adoc
  backup_and_restore/index.adoc
  modules/oadp-monitoring.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
Labels: size/XL

#91447 [enterprise 4.14] CP-89097
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/issues-with-velero-and-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/velero-cli-tool.adoc
  backup_and_restore/index.adoc
  modules/oadp-monitoring.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
Labels: size/XL

#91448 [enterprise 4.15] CP-89097
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/issues-with-velero-and-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/velero-cli-tool.adoc
  backup_and_restore/index.adoc
  modules/oadp-monitoring.adoc
  modules/oadp-restic-timeouts.adoc
  modules/oadp-timeouts.adoc
Labels: size/XL

#91421 HCIDOCS-689-final: Fix OCP landing page final
  installing/installing_on_prem_assisted/installing-on-prem-assisted.adoc
  modules/assisted-installer-using-the-assisted-installer.adoc
Labels: peer-review-done, size/M, merge-review-in-progress

#91470 ROX-21316: Add info for compliance operator
  operating/compliance-operator-rhacs.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8

#90200 OSSM-8856 [DOC] Add warning to installation instructions about conflicts with existing OSSM 3 installations
  install/ossm-installing-openshift-service-mesh.adoc
  modules/ossm-installing-operator.adoc
Labels: peer-review-done, size/S, service-mesh, merge-review-in-progress, merge-review-needed

#91490 Updating the note for windows must-gather prerequisites [OCPBUGS-53231]
  modules/about-must-gather.adoc
Labels: peer-review-done, size/XS, ok-to-test, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91437 OBSDOCS-1753 Add known issue with upgrade oom error
  observability/cluster_observability_operator/cluster-observability-operator-release-notes.adoc
Labels: size/S

#90598 Revised steps for installing and creating an AWS worker
  modules/installation-creating-aws-worker.adoc
Labels: peer-review-done, size/XS, ok-to-test, merge-review-in-progress, branch/enterprise-4.18, branch/enterprise-4.19

#91091 OSDOCS13031: Document the floor for CPU limits
  modules/nodes-pods-understanding-requests-limits.adoc
  nodes/pods/nodes-pods-using.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91465 [OSDOCS-13946]: Update risk profile info in HCP docs
  modules/hcp-shared-infra.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91469 ROX-21229: Remove incorrect network graph info
  modules/simulate-network-policies-ng20.adoc
Labels: peer-review-done, size/XS, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8

#91160 OCPBUGS-54302: Add Key Rings list permission for gcp
  modules/minimum-required-permissions-ipi-gcp.adoc
  modules/minimum-required-permissions-upi-gcp.adoc
Labels: peer-review-done, size/S, qe-approved, jira/severity-moderate, jira/valid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#91521 [enterprise-4.12] OSDOCS13031: Document the floor for CPU limits
  modules/nodes-pods-understanding-requests-limits.adoc
  nodes/pods/nodes-pods-using.adoc
Labels: size/M

#91522 [enterprise-4.13] OSDOCS13031: Document the floor for CPU limits
  modules/nodes-pods-understanding-requests-limits.adoc
  nodes/pods/nodes-pods-using.adoc
Labels: size/M

#91523 [enterprise-4.14] OSDOCS13031: Document the floor for CPU limits
  modules/nodes-pods-understanding-requests-limits.adoc
  nodes/pods/nodes-pods-using.adoc
Labels: size/M

#91525 [enterprise-4.16] OSDOCS13031: Document the floor for CPU limits
  modules/nodes-pods-understanding-requests-limits.adoc
  nodes/pods/nodes-pods-using.adoc
Labels: size/M

#85095 CMA 2.15.1 release notes
  nodes/cma/nodes-cma-rn/nodes-cma-autoscaling-custom-rn-past.adoc
  nodes/cma/nodes-cma-rn/nodes-cma-autoscaling-custom-rn.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91536 CNV#54770: 4.17.7 HCO bump
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.17

#91372 OBSDOCS-1793: Logging Z-Stream Release Notes - 5.8.19
  modules/logging-release-notes-5-8-19.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#91369 OSDOCS-11940: specify Arm nodes not yet available for Virtualization
  modules/virt-supported-cluster-version.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#90975 OSDOCS-10661-4.16:adds local gateway mode to migration procedure
  modules/checking-cluster-resources-before-initiating-limited-live-migration.adoc
  modules/nw-ovn-kubernetes-live-migration-about.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.15, branch/enterprise-4.16

#91562 [enterprise-4.15] OSDOCS-10661-4.15:gateway mode added to migration procedure
  modules/checking-cluster-resources-before-initiating-limited-live-migration.adoc
  modules/nw-ovn-kubernetes-live-migration-about.adoc
Labels: size/M

#91256 OSDOCS-13815: Documented the 4.17.23 z-stream RNs
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#91314 TELCODOCS-2160#Update validated RHACM version in OCP 4.17
  modules/ztp-telco-ran-software-versions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17

#89198 TELCODOCS-2216: Enabling SR-IOV metrics backport
  modules/nw-sriov-configuring-operator.adoc
  modules/sriov-network-metrics-exporter.adoc
  modules/sriov-operator-metrics.adoc
  networking/networking_operators/sr-iov-operator/configuring-sriov-operator.adoc
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/L, telco, jira/valid-reference, branch/enterprise-4.16

#91566 Update oc-mirror-imageset-config-parameters-v2.adoc
  modules/oc-mirror-imageset-config-parameters-v2.adoc
Labels: lgtm, size/XS, qe-approved

#91401 OBSDOCS#1326: Improve 'troubleshooting monitoring issues, - post OCPBUGS#39126
  modules/monitoring-investigating-why-user-defined-metrics-are-unavailable.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91559 OCPBUGS54500: The example of nodeDisruptionPolicy is incorrect
  modules/machine-config-node-disruption-example.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91582 [enterprise-4.16] OCPBUGS54500: The example of nodeDisruptionPolicy is incorrect
  modules/machine-config-node-disruption-example.adoc
Labels: size/XS

#90215 OSDOCS:13467: Creating new tutorial book and updating CLI tutorial
  _topic_maps/_topic_map.yml
  getting_started/accessing-your-services.adoc
  getting_started/dedicated-networking.adoc
  getting_started/deleting-your-cluster.adoc
  getting_started/openshift-cli.adoc
  getting_started/scaling-your-cluster.adoc
  modules/getting-started-cli-connecting-a-database.adoc
  modules/getting-started-cli-creating-new-project.adoc
  modules/getting-started-cli-creating-route-backend.adoc
  modules/getting-started-cli-creating-route.adoc
  modules/getting-started-cli-creating-secret.adoc
  modules/getting-started-cli-deploying-first-image.adoc
  modules/getting-started-cli-deploying-python-app.adoc
  modules/getting-started-cli-examining-pod.adoc
  modules/getting-started-cli-granting-permissions.adoc
  modules/getting-started-cli-load-data-output.adoc
  modules/getting-started-cli-scaling-app.adoc
  modules/getting-started-cli-view.adoc
  tutorials/_attributes
  tutorials/dev-app-cli.adoc
  tutorials/dev-app-web-console.adoc
  tutorials/images
  tutorials/index.adoc
  tutorials/modules
  tutorials/snippets
  web_console/web-console-overview.adoc
Labels: peer-review-done, lgtm, size/XL, branch/enterprise-4.19

#91371 OSDOCS#3814: Update the z-stream RN for 4.18.7
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#91552 [OSDOCS-13962] Remove reference to C3 and N4 instance types from OSD docs
  storage/container_storage_interface/persistent-storage-csi-gcp-pd.adoc
Labels: peer-review-done, size/XS, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#91355 [OSDOCS-13848]: Add must-gather docs for day 2 HCP
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-must-gather-cli.adoc
  modules/hcp-must-gather-console.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91288 Update violations page info
  modules/analyzing-all-violations.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.7, rhacs-docs-4.8

#91476 OSDOCS:13913 Add reason for no Node Disrupt Policy for /etc/containers/registries.conf.d
  modules/machine-config-node-disruption-example.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#90760 OSDOCS-13539-removed: Removed the OCPBUGS-43323 in configuring-ipsec-…
  networking/network_security/configuring-ipsec-ovn.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18

#91590 [enterprise-4.17][OSDOCS-13848]: Add must gather docs for day 2 HCP
  hosted_control_planes/hcp-troubleshooting.adoc
  modules/hcp-must-gather-cli.adoc
  modules/hcp-must-gather-console.adoc
Labels: size/M

#91561 [OCPBUGS-49935]: Adding prerequisite to HCP CLI procedures
  modules/hcp-cli-console.adoc
  modules/hcp-cli-gateway.adoc
  modules/hcp-cli-terminal.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#88156 MIG-1691: PSA labels should be called out explicitly in the docs
  migration_toolkit_for_containers/mtc-direct-migration-requirements.adoc
  modules/ocp-running-rsync-root-or-non-root.adoc
  modules/security-context-constraints-psa-about.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, MTC, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#87773 OSSM-8192: product documentation for external control plane topology
  _topic_maps/_topic_map.yml
  install/ossm-external-control-plane-topology.adoc
  modules/ossm-about-external-control-plane-topology.adoc
  modules/ossm-installing-external-control-plane.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference

#87859 OCPBUGS-31917 added a note that states latency profiles do not suppor…
  modules/nodes-cluster-worker-latency-profiles-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91625 [enterprise-4.12] OCPBUGS-31917 added a note that states latency profiles do not suppor...
  modules/nodes-cluster-worker-latency-profiles-about.adoc
Labels: size/XS

#91099 TELCODOCS-2162#Fix capitalization in FIPS config for Agent-based Installer
  modules/agent-installer-configuring-fips-compliance.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91626 MCO updated several 'Module included in' metadata
  installing/installing_openstack/installing-openstack-user-sr-iov.adoc
  modules/checking-mco-node-status-configuring.adoc
  modules/checking-mco-node-status.adoc
  modules/checking-mco-status-certs.adoc
  modules/machine-config-node-disruption-config.adoc
  modules/machine-config-node-disruption-example.adoc
  modules/machineconfig-garbage-collect-removing.adoc
  modules/machineconfig-garbage-collect-viewing.adoc
  modules/mco-update-boot-images-disable.adoc
  modules/mco-update-boot-images.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91583 TELCODOCS-2167#Update link to PolicyGenerator docs in RHACM
  edge_computing/policygenerator_for_ztp/ztp-configuring-managed-clusters-policygenerator.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91603 CNV-38746: Added known issue to 4.15 release notes
  virt/release_notes/virt-4-15-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.15

#91652 CNV-38746: Added known issue to 4.16 release notes
  virt/release_notes/virt-4-16-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.16

#91653 CNV-38746: Added known issue to 4.17 release notes
  virt/release_notes/virt-4-17-release-notes.adoc
Labels: size/S, CNV, jira/valid-reference, branch/enterprise-4.17

#91654 CNV-38746: Added known issue to 4.18 release notes
  virt/release_notes/virt-4-18-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.18

#91655 CNV-38746: Added known issue to 4.19 release notes
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: size/XS, CNV, jira/valid-reference, branch/enterprise-4.19

#91631 [enterprise-4.17] Ocpbugs 51308-417-1
  modules/nw-route-override-cni.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/secondary_networks/creating-secondary-nwt-other-cni.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: lgtm, size/M, merge-review-in-progress, branch/enterprise-4.17

#91600 [enterprise-4.14] OCPBUGS-51308-414 manual addition missing route-override CNI information
  modules/nw-route-override-cni.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: lgtm, size/M, merge-review-in-progress, branch/enterprise-4.14

#79341 OBSDOCS-1147: Bugfix - update storage secret table
  modules/distr-tracing-tempo-config-default.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, observability, branch/enterprise-4.18, branch/enterprise-4.19

#91530 [OSDOCS-13743]: Fixing command in steps to create a hosted cluster on BM and non-BM
  modules/hcp-bm-hc.adoc
  modules/hcp-non-bm-hc.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91002 [OSDOCS-13755] ROSA docs for editing billing account
  _topic_maps/_topic_map_rosa_hcp.yml
  cli_reference/rosa_cli/rosa-updating-billing-account-cli.adoc
  modules/rosa-edit-objects.adoc
  modules/rosa-update-billing-cli.adoc
  ocm/ocm-overview.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, size/M, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#91683 [enterprise-4.13] Update oc-mirror-imageset-config-params.adoc
  modules/oc-mirror-imageset-config-params.adoc
Labels: size/XS

#91685 [enterprise-4.15] Update oc-mirror-imageset-config-params.adoc
  modules/oc-mirror-imageset-config-params.adoc
Labels: size/XS

#91684 [enterprise-4.14] Update oc-mirror-imageset-config-params.adoc
  modules/oc-mirror-imageset-config-params.adoc
Labels: size/XS, branch/enterprise-4.14

#91680 Update logging-loki-storage-aws.adoc
  modules/logging-loki-storage-aws.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91581 OCPBUGS-46596-feat: Moved ec2:DescribeInstanceTypeOffering as a requi…
  modules/installation-aws-permissions.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#91236 OBSDOCS-1778: Remove COO pre-GA support notice in OCP 4.17
  _topic_maps/_topic_map.yml
  observability/logging/logging-6.0/log6x-visual.adoc
  observability/logging/logging-6.1/log6x-visual-6.1.adoc
  observability/logging/logging-6.2/log6x-visual-6.2.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#91231 OBSDOCS-1778: Remove COO pre-GA support notice
  observability/logging/logging-6.0/log60-cluster-logging-support.adoc
  observability/logging/logging-6.0/log6x-visual.adoc
  observability/logging/logging-6.1/log61-cluster-logging-support.adoc
  observability/logging/logging-6.1/log6x-visual-6.1.adoc
  observability/logging/logging-6.2/log62-cluster-logging-support.adoc
  observability/logging/logging-6.2/log6x-visual-6.2.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#91320 OBSDOCS#1796: Improve troubleshooting monitoring issues: create new section about the AlertmanagerReceiversNotConfigured alert
  modules/monitoring-resolving-the-alertmanagerreceiversnotconfigured-alert.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91238 OBSDOCS-1778: Remove COO pre-GA support notice for OCP 4.16
  _topic_maps/_topic_map.yml
  observability/logging/logging-6.0/log6x-visual.adoc
  observability/logging/logging-6.1/log6x-visual-6.1.adoc
  observability/logging/logging-6.2/log6x-visual-6.2.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#91413 OCPBUGS-46596: Documented the bug fix for the default instance type
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.19

#91686 OBSDOCS#1800: Small fixes for 'Enabling a separate Alertmanager instance for user-defined alert routing'
  modules/monitoring-enabling-a-separate-alertmanager-instance-for-user-defined-alert-routing.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91720 [enterprise-4.12] OBSDOCS-1800: Small fixes for 'Enabling a separate Alertmanager insta…
  modules/monitoring-enabling-a-separate-alertmanager-instance-for-user-defined-alert-routing.adoc
Labels: size/XS, branch/enterprise-4.12, jira/valid-reference

#91719 [enterprise-4.13] OBSDOCS-1796: Improve troubleshooting monitoring issues: create new s…
  modules/monitoring-resolving-the-alertmanagerreceiversnotconfigured-alert.adoc
  observability/monitoring/troubleshooting-monitoring-issues.adoc
Labels: size/S, jira/valid-reference

#90059 OCPBUGS-35712#planning tips
  architecture/architecture-installation.adoc
  installing/overview/index.adoc
  modules/installation-process.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89623 OSDOCS-10316#adding DHCP details
  modules/installation-special-config-chrony.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89860 OCPBUGS-37778#correcting yaml file
  modules/installation-installer-provisioned-vsphere-config-yaml.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91681 OBSDOCS-1723: Port the "Installing Logging" sections to 5.8 and 6.y
  _topic_maps/_topic_map.yml
  modules/log6x-logging-clo-cli-install.adoc
  modules/log6x-logging-clo-gui-install.adoc
  modules/log6x-logging-loki-cli-install.adoc
  modules/log6x-logging-loki-gui-install.adoc
  observability/logging/logging-6.0/6x-cluster-logging-deploying-6.0.adoc
  observability/logging/logging-6.1/6x-cluster-logging-deploying-6.1.adoc
  observability/logging/logging-6.2/6x-cluster-logging-deploying-6.2.adoc
  observability/logging/logging_release_notes/cluster-logging-deploying.adoc
Labels: size/XL, jira/valid-reference, branch/enterprise-4.18

#90608 Additional steps to modify the parameter overprovisionRatio after the LVM cluster is created
  modules/lvms-about-lvmcluster-cr.adoc
Labels: peer-review-done, lgtm, size/S, ok-to-test, branch/enterprise-4.18, branch/enterprise-4.19

#86498 TELCODOCS-1786: AMD GPU Operator
  _topic_maps/_topic_map.yml
  hardware_accelerators/about-hardware-accelerators.adoc
  hardware_accelerators/amd-about-amd-gpu-operator.adoc
  hardware_accelerators/amd-gpu-operator.adoc
  modules/amd-about-amd-gpu-operator.adoc
  modules/amd-installing-gpu-operator.adoc
  modules/amd-testing-the-amd-gpu-operator.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91043 [OSDOCS-13765]: Update RN about custom taints and tolerations for HCP
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: peer-review-done, size/XS, px-approved, branch/enterprise-4.17

#91042 [OSDOCS-13765]: Clarify that custom taints and tolerations apply to all HCP platforms
  modules/hcp-support-matrix.adoc
  modules/hcp-virt-taints-tolerations.adoc
Labels: peer-review-done, lgtm, size/XS, px-approved, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91343 TELCODOCS-1843#Update GNSS sync status value in PTP HW Fast events
  modules/cnf-fast-event-notifications-api-reference-v2.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91617 OLS-1644: api_token should be base64 encoded when used with data in s…
  modules/ols-creating-the-credentials-secret-using-cli.adoc
  modules/ols-creating-the-credentials-secret-using-web-console.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#91124 TELCODOCS-2008 - 4.18/4.19 update coreos-install commands with --offl…
  modules/installation-user-infra-machines-advanced-enabling-serial-console.adoc
  modules/installation-user-infra-machines-advanced.adoc
  modules/installation-user-infra-machines-iso.adoc
  modules/rhcos-enabling-multipath.adoc
  modules/rhcos-install-iscsi-ibft.adoc
  modules/rhcos-install-iscsi-manual.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.18, branch/enterprise-4.19

#91641 [enterprise-4.16] MCO updated several 'Module included in' metadata
  installing/installing_openstack/installing-openstack-user-sr-iov.adoc
  modules/checking-mco-node-status.adoc
  modules/checking-mco-status-certs.adoc
  modules/machine-config-node-disruption-config.adoc
  modules/machine-config-node-disruption-example.adoc
  modules/machineconfig-garbage-collect-removing.adoc
  modules/machineconfig-garbage-collect-viewing.adoc
  modules/mco-update-boot-images-disable.adoc
  modules/mco-update-boot-images.adoc
Labels: size/S

#91779 [enterprise-4.14] CNV#50962_417: Documentation Issue in Regards to SSP Operator
  modules/virt-connecting-vm-virtctl.adoc
  modules/virt-temporary-token-VNC.adoc
  virt/virtual_machines/virt-accessing-vm-consoles.adoc
Labels: size/S

#91149 [enterprise-4.15] CNV#50962_417: Documentation Issue in Regards to SSP Operator
  modules/virt-connecting-vm-virtctl.adoc
  modules/virt-temporary-token-VNC.adoc
  virt/virtual_machines/virt-accessing-vm-consoles.adoc
Labels: size/S

#91345 OSDOCS-13650-1: RPM typo update
  modules/microshift-updating-rpms-y.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89189 OSDOCS-11245 OSD minimum bandwidth
  modules/mos-network-prereqs-min-bandwidth.adoc
  osd_planning/aws-ccs.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91632 [OCPBUGS-53046] IBMZ changes related to pxe
  modules/adding-ibm-z-lpar-agent.adoc
  modules/installing-ocp-agent-ibm-z-kvm.adoc
Labels: peer-review-done, size/XS, ok-to-test, merge-review-in-progress, branch/enterprise-4.18, branch/enterprise-4.19

#90698 OCPBUGS-28512: Added node reboot node to customize-certificates-repla…
  modules/customize-certificates-replace-default-router.adoc
  modules/nw-proxy-configure-object.adoc
Labels: peer-review-done, size/M, qe-approved, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91767 TELCODOCS-2241#Fix link to RHACM PolicyGenerator docs
  snippets/pgt-deprecation-notice.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#91812 OCPBUGS-53444: Changed default parameter values in nw-sriov-configuri…
  modules/nw-sriov-configuring-operator.adoc
Labels: size/XS, jira/invalid-bug, branch/enterprise-4.14

#91815 OCPBUGS-53444: Changed default parameter values in nw-sriov-configuri…
  modules/nw-sriov-configuring-operator.adoc
Labels: size/XS, branch/enterprise-4.13

#91816 [enterprise-4.12] OCPBUGS-53444: Changed default parameter values in nw-sriov-configuri…
  modules/nw-sriov-configuring-operator.adoc
Labels: size/XS, branch/enterprise-4.12

#91811 [enterprise-4.15] OCPBUGS-53444: Changed default parameter values in nw-sriov-configuri…
  modules/nw-sriov-configuring-operator.adoc
Labels: size/XS, jira/severity-important, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.15

#91797 OSDOCS#13367:Replace/Insight Operator/Insights Operator
  modules/obfuscating-dvo-data.adoc
  support/index.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91824 [enterprise-4.12] OSDOCS#13367:Replace/Insight Operator/Insights
  support/index.adoc
Labels: size/XS

#91825 [enterprise-4.13] OSDOCS#13367:Replace/Insight Operator/Insights
  support/index.adoc
Labels: size/XS

#91338 TELCODOCS-1843#Update GNSS sync status value in PTP HW Fast events
  modules/cnf-fast-event-notifications-api-refererence.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#91340 [enterprise-4.14] TELCODOCS-1843#Update GNSS sync status value in PTP HW Fast events
  modules/cnf-fast-event-notifications-api-refererence.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#91769 OCPBUGS-53398:updates policy group label
  modules/nw-networkpolicy-about.adoc
  modules/nw-networkpolicy-multitenant-isolation.adoc
  modules/nw-networkpolicy-project-defaults.adoc
Labels: peer-review-done, lgtm, size/XS, jira/severity-low, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91359 OCPBUGS-43596:updates compute machine to include all platforms
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
Labels: peer-review-done, size/XS, jira/severity-moderate, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91791 OSDOCS#13693: attempting table format fix
  modules/agent-configuration-parameters.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91493 CNV-58930: Correct the links to MTV docs
  _attributes/common-attributes.adoc
  modules/migrating-to-virt.adoc
Labels: peer-review-done, lgtm, size/S, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#90806 OSDOCS#12900: Increasing rec visibility
  modules/cert-manager-operator-update-channels.adoc
  modules/customize-certificates-add-service-serving.adoc
  modules/network-observability-lokistack-ingestion-query.adoc
  modules/security-container-content-universal.adoc
  modules/security-hosts-vms-rhcos.adoc
  modules/tls-profiles-understanding.adoc
  observability/network_observability/installing-operators.adoc
  security/network_bound_disk_encryption/nbde-managing-encryption-keys.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91849 Explain headlined options
  nodes/clusters/nodes-cluster-overcommit.adoc
  post_installation_configuration/node-tasks.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91668 OSDOCS-5815: OSD/ROSA BYO-VPC document DHCP option requirements
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-quickly.adoc
  rosa_install_access_delete_clusters/rosa-shared-vpc-config.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.adoc
  rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-with-customizations.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#91845 CNV#54764: HCO version 4.15.10
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.15

#91878 [enterprise-4.12] Explain headlined options
  nodes/clusters/nodes-cluster-overcommit.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/S

#90978 OSDOCS-12955: 4.18 RN tech preview tables for recommend and status
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#91420 TELCODOCS-2150: Removing redundant flag
  modules/ptp-configuring-dynamic-leap-seconds-handling-for-tgm.adoc
  snippets/ptp_PtpConfigDualCardGmWpc.yaml
  snippets/ptp_PtpConfigGmWpc.yaml
Labels: peer-review-done, lgtm, size/XS, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91882 [enterprise-4.17] OCPBUGS-43596-4.17
  machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
Labels: size/XS

#91491 RHDEVDOCS-6317: Post GA changes for GitOps 1.16
  modules/gitops-creating-aggregated-cluster-roles.adoc
  modules/gitops-release-notes-1-16-0.adoc
  understanding_openshift_gitops/about-redhat-openshift-gitops.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, gitops

#91879 [enterprise-4.13] Explain headlined options
  nodes/clusters/nodes-cluster-overcommit.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/S

#91880 [enterprise-4.14] Explain headlined options
  nodes/clusters/nodes-cluster-overcommit.adoc
  post_installation_configuration/node-tasks.adoc
Labels: size/S
