Repository openshift/openshift-docs, pull requests merged in 2025-05, with the labels that each got.

#92783 OCPBUGS-54518: Fixed codeblock to enhance clipboard experience on cus…
  modules/customize-certificates-api-add-named.adoc
Labels: peer-review-done, size/XS, jira/severity-important, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92761 [enterprise-4.17] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly …
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92762 [enterprise-4.16] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly as it confuses the DRK single-page view
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92763 [enterprise-4.15] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly as it confuses the DRK single-page view
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92764 [enterprise-4.14] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly as it confuses the DRK single-page view
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92765 [enterprise-4.13] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly as it confuses the DRK single-page view
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92766 [enterprise-4.12] TELCODOCS-2291: Removing index anchor for index.adoc in S&P assembly as it confuses the DRK single-page view
  scalability_and_performance/index.adoc
Labels: size/XS, jira/valid-reference

#92847 [OSDOCS-14530]Enable C3 and N4 Instance types
  modules/sdpolicy-am-gcp-compute-types.adoc
Labels: peer-review-done, size/M, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#92754 OCPBUGS-55471:fixes OVN-K external IP docs
  modules/nw-networkpolicy-optimize-ovn.adoc
  networking/understanding-networking.adoc
Labels: peer-review-done, lgtm, size/S, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92259 OCPBUGS#55065: Updated the JSON examples in compatibility-with-multi-…
  modules/configuring-localnet-switched-topology.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91781 OCPBUGS-48479: Adding MHC exception to Pausing MHC cluster update …
  modules/machine-health-checks-pausing.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, jira/valid-reference

#92880 quick-fix:fixes typo
  modules/nw-networkpolicy-optimize-ovn.adoc
Labels: peer-review-done, size/XS

#92667 OSDOCS-13088: adds 4.17.27 relnote MicroShift
  microshift_release_notes/microshift-4-17-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, jira/valid-reference

#92879 build all the versions of standalone logging for testing purposes
  _distro_map.yml
  scripts/package.sh
Labels: size/M

#92643 OSDOCS-13966: remove RHEL worker node docs
  _topic_maps/_topic_map.yml
  disconnected/updating/disconnected-update-osus.adoc
  installing/overview/installing-fips.adoc
  machine_management/index.adoc
  migrating_from_ocp_3_to_4/planning-migration-3-4.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/node-tasks.adoc
  updating/understanding_updates/understanding-openshift-update-duration.adoc
  updating/updating_a_cluster/control-plane-only-update.adoc
Labels: peer-review-done, size/M, jira/valid-reference, branch/enterprise-4.19

#92866 [enteprise-4.17] OCPBUGS-55471:fixes OVN-K external IP docs
  modules/nw-networkpolicy-optimize-ovn.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference

#92832 Adds nodeport limitation to UDN docs
  modules/nw-udn-limitations.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#92895 parameterize package script and update devcontainer to use it
  .devcontainer/devcontainer.json
  scripts/package.sh
Labels: size/M

#92897 OSDOCS-14437_v1 updated release notes from branch OSDOCS-14437
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed

#92756 OCPBUGS55471-4.16:adds external IP to migration docs
  modules/nw-external-ip-ovn-k.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16

#92910 add main branch so that cached erb file for package command will be main
  _distro_map.yml
  _templates/_page_openshift.html.erb
Labels: size/XS

#92534 OCPBUGS-55288: Added note about bonded interface and node IP address …
  installing/installing_bare_metal/ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: peer-review-done, lgtm, size/M, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92757 RHDEVDOCS 6446 add missing RN for 1.14.6
  modules/op-release-notes-1-14.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress

#92888 [OSDOCS-14538]Release Note for c3 and n4 instance types for GCP on OSD
  osd_whats_new/osd-whats-new.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#91565 OBSDOCS-1795: Improve the contents of 'Configuring alert routing for default platform alerts'
  modules/monitoring-configuring-alert-routing-default-platform-alerts.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#92312 OCPBUGS-33247: Improving QoS pod based on docfooding feedback
  modules/cnf-node-tuning-operator-creating-pod-with-guaranteed-qos-class.adoc
Labels: peer-review-done, size/M, jira/severity-low, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92915 [enterprise-4.15] OCPBUGS#55288: Added note about bonded interface and node IP address …
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: size/M, branch/enterprise-4.15

#92929 [enterprise-4.12] OCPBUGS-55288: Added note about bonded interface and node IP address …
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: size/M, jira/invalid-bug, branch/enterprise-4.12, jira/valid-reference

#92923 [enterprise-4.14] OCPBUGS#55288: Added note about bonded interface and node IP address …
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: size/M, branch/enterprise-4.14

#92925 [enterprise-4.13] OCPBUGS-55288: Added note about bonded interface and node IP address …
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: size/M, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.13

#92924 OSDOCS#13706: Adding docs for KDO 5.1.2
  nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc
Labels: size/S

#92936 [enterprise-4.16] OCPBUGS-55288: Added note about bonded interface and node IP address …
  modules/ipi-install-configuring-host-network-interfaces-in-the-install-config.yaml-file.adoc
  modules/ipi-install-establishing-communication-between-subnets.adoc
Labels: size/M, jira/invalid-bug, branch/enterprise-4.16

#92540 OLS-1642: Create release notes for OLS 0.3.4
  modules/ols-0-3-4-fixed-issues.adoc
  modules/ols-0-3-4-release-notes.adoc
  release_notes/ols-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#92144 OSDOCS#14025: Removing note saying that modern profile isn't supporte…
  modules/tls-profiles-ingress-configuring.adoc
  modules/tls-profiles-kubelet-configuring.adoc
  modules/tls-profiles-kubernetes-configuring.adoc
  modules/tls-profiles-understanding.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.19

#89926 RHDEVDOCS 6385 procedure for PAC pipeline runs
  _topic_maps/_topic_map.yml
  modules/op-creating-pipeline-run-pac.adoc
  modules/op-filtering-pipeline-run-using-pipelines-as-code.adoc
  modules/op-matching-pipeline-run-using-pipelines-as-code.adoc
  modules/op-pac-concepts.adoc
  modules/op-parameters-pipeline-run-using-pipelines-as-code.adoc
  modules/op-pipelines-as-code-resolver-annotations.adoc
  modules/op-using-remote-pipeline-annotations-with-pipelines-as-code.adoc
  modules/op-using-remote-task-annotations-with-pipelines-as-code.adoc
  modules/op-verifying-pipeline-run-pac.adoc
  pac/about-pipelines-as-code.adoc
  pac/creating-pipeline-runs-pac.adoc
  pac/managing-pipeline-runs-pac.adoc
  pac/using-pac-resolver.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed

#92543 OCPBUGS-35084: Configuration verification warning for running vsphere virtual hardware template
  modules/update-vsphere-virtual-hardware-on-template.adoc
Labels: peer-review-done, lgtm, size/XS, jira/invalid-bug, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92679 OSDOCS-13102: adds 4.18.11 relnote MicroShift
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/S, qe-approved, jira/valid-reference

#92894 OSDOCS-14483 added zero trust attributes to the common-attributes file
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.19

#92145 OSDOCS#14025: Release note for TLS 1.3 and modern profile for control…
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.19

#92696 OSDOCS-14405: Fix and improve OADP documentation for ROSA
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#92115 OCPBUGS-54909: Add multicast snooping
  modules/configuring-localnet-switched-topology.adoc
  modules/creating-manifest-file-customized-br-ex-bridge.adoc
Labels: peer-review-done, size/S, jira/severity-moderate, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91883 CNV-52859: Configuring VM interface link state
  _topic_maps/_topic_map.yml
  modules/virt-configuring-interface-link-state.adoc
  virt/vm_networking/virt-setting-interface-link-state.adoc
Labels: peer-review-done, size/L, CNV, jira/valid-reference, branch/enterprise-4.19

#92938 ROX-28825: Add ACSCS Central access restriction documentation
  cloud_service/rhacs-cloud-service-service-description.adoc
Labels: peer-review-done, lgtm, size/S, RHACS, jira/valid-reference, rhacs-docs-4.5, rhacs-docs-4.6, rhacs-docs-4.7, rhacs-docs-4.8

#92980 [enterprise-4.12] OBSDOCS-1795: Improve the contents of 'Configuring alert routing for default platform alerts'
  modules/monitoring-configuring-notifications-for-default-platform-alerts.adoc
Labels: size/L, merge-review-in-progress, jira/valid-reference

#92982 [enterprise-4.14] OBSDOCS-1795: Improve the contents of 'Configuring alert routing for default platform alerts'
  modules/monitoring-configuring-alert-routing-default-platform-alerts.adoc
Labels: size/L, merge-review-in-progress, jira/valid-reference

#92983 [enterprise-4.15] OBSDOCS-1795: Improve the contents of 'Configuring alert routing for default platform alerts'
  modules/monitoring-configuring-alert-routing-default-platform-alerts.adoc
Labels: size/L, merge-review-in-progress, jira/valid-reference

#92985 [enterprise-4.17] OBSDOCS-1795: Improve the contents of 'Configuring alert routing for default platform alerts'
  modules/monitoring-configuring-alert-routing-default-platform-alerts.adoc
Labels: size/L, merge-review-in-progress, jira/valid-reference

#92999 OSDOCS-14544: Add Classic for Tel Aviv and Calgary regions Back In Docs
  modules/rosa-sdpolicy-am-regions-az.adoc
  rosa_release_notes/rosa-release-notes.adoc
Labels: lgtm, size/S, jira/valid-reference

#92942 fixed wrong version nr
  modules/ob-release-notes-1-4.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#92993 No Jira: Re-arrange table rows in HCP 4.18 RN
  hosted_control_planes/hosted-control-planes-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.18

#92423 TELCODOCS#1858: Updated the command to download logs
  modules/lvms-download-log-files-and-diagnostics.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92459 OSDOCS-14042: fixing OPENSHIFT_HA_VRRP_ID_OFFSET default value
  modules/nw-ipfailover-configuration.adoc
  modules/nw-ipfailover-environment-variables.adoc
Labels: peer-review-done, size/XS, qe-approved, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.19

#89614 [SRVKE-1693] GA of TLS - remove TP notice
  eventing/serverless-config-tls-encryption-eventing.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-in-progress

#88080 [SRVCLI-403] Option `--to` replaces `--to-url`
  modules/serverless-send-events-kn.adoc
Labels: peer-review-done, size/M, ok-to-merge, serverless

#89602 [SRVCLI-406] GA of kn-event - remove TP notice
  cli_tools/kn-plugins.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-in-progress

#93017 fix base URL so it is not hard-coded
  _javascripts/page-loader.js
Labels: lgtm, size/M

#93015 [enterprise-4.17] OSDOCS-14023: Clarified secondary/additional networks
  modules/cnf-assigning-a-secondary-network-to-a-vrf.adoc
  modules/configuration-ovnk-multi-network-policy.adoc
  modules/configuration-ovnk-network-plugin-json-object.adoc
  modules/configuring-localnet-switched-topology.adoc
  modules/configuring-ovnk-additional-networks.adoc
  modules/configuring-pods-secondary-network.adoc
  modules/configuring-pods-static-ip.adoc
  modules/microshift-multus-intro.adoc
  modules/nw-multi-network-policy-differences.adoc
  modules/nw-multus-add-pod.adoc
  modules/nw-multus-advanced-annotations.adoc
  modules/nw-multus-bridge-object.adoc
  modules/nw-multus-configure-dualstack-ip-address.adoc
  modules/nw-multus-create-master-interface-bridge-cni.adoc
  modules/nw-multus-create-multiple-vlans-sriov.adoc
  modules/nw-multus-create-network-apply.adoc
  modules/nw-multus-create-network.adoc
  modules/nw-multus-creating-whereabouts-reconciler-daemon-set.adoc
  modules/nw-multus-delete-network.adoc
  modules/nw-multus-edit-network.adoc
  modules/nw-multus-host-device-object.adoc
  modules/nw-multus-ipam-object.adoc
  modules/nw-multus-ipvlan-object.adoc
  modules/nw-multus-macvlan-object.adoc
  modules/nw-multus-remove-pod.adoc
  modules/nw-multus-tap-object.adoc
  modules/nw-multus-vlan-object.adoc
  modules/nw-nad-cr.adoc
  modules/nw-route-override-cni.adoc
  networking/multiple_networks/assigning-a-secondary-network-to-a-vrf.adoc
  networking/multiple_networks/configuring-additional-network.adoc
  networking/multiple_networks/primary_networks/about-primary-nwt-nad.adoc
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
  networking/multiple_networks/secondary_networks/attaching-pod.adoc
  networking/multiple_networks/secondary_networks/configuring-multi-network-policy.adoc
  networking/multiple_networks/secondary_networks/creating-secondary-nwt-other-cni.adoc
  networking/multiple_networks/secondary_networks/creating-secondary-nwt-ovnk.adoc
  networking/multiple_networks/secondary_networks/editing-additional-network.adoc
  networking/multiple_networks/secondary_networks/removing-pod.adoc
  networking/multiple_networks/understanding-multiple-networks.adoc
Labels: size/L, jira/valid-reference, branch/enterprise-4.17

#92799 OSDOCS-14395:adds note about legacy behavior for nil selector in netpol
  modules/nw-networkpolicy-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92318 OSSM-9337 Document Istio control plane update strategy: InPlace strategy
  install/ossm-installing-openshift-service-mesh.adoc
  modules/ossm-about-deployment-and-update-strategies.adoc
  modules/ossm-about-inplace-strategy.adoc
  modules/ossm-about-istio-control-plane-update-strategies.adoc
  modules/ossm-about-istio-update-process.adoc
  modules/ossm-about-revisionbased-strategy.adoc
  modules/ossm-attach-workloads-to-control-plane.adoc
  modules/ossm-performing-inplace-update.adoc
  modules/ossm-preparing-to-update-istio-control-plane-with-inplace.adoc
  modules/ossm-selecting-inplace-strategy.adoc
  modules/ossm-updating-istio-control-plane-with-inplace.adoc
  update/ossm-updating-openshift-service-mesh.adoc
Labels: peer-review-done, size/L, service-mesh, merge-review-in-progress

#91285 OSDOCS-13185#Disabling vSphere TP->GA
  storage/container_storage_interface/persistent-storage-csi-vsphere.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#92902 [enterprise-4.14] OCPBUGS-55471:adds external IP to migration docs
  modules/nw-external-ip-ovn-k.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference

#92278 OSDOCS13996: Remove cGroup v1 in OCP 4.19
  _topic_maps/_topic_map.yml
  architecture/index.adoc
  installing/install_config/enabling-cgroup-v1.adoc
  installing/installing_openstack/installing-openstack-nfv-preparing.adoc
  modules/architecture-about-cgroup-v2.adoc
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  modules/nodes-clusters-cgroups-2-install.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/telco-core-application-workloads.adoc
  modules/telco-core-cpu-partitioning-and-performance-tuning.adoc
  modules/telco-ran-cluster-tuning.adoc
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
  nodes/clusters/nodes-cluster-cgroups-2.adoc
  post_installation_configuration/cluster-tasks.adoc
  scalability_and_performance/telco-core-rds.adoc
  snippets/cgroupv2-vs-cgroupv1.adoc
  snippets/nodes-cgroup-vi-removed.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19

#92994 [enterprise-4.15]OCPBUGS-55471:adds external IP to migration docs
  modules/nw-external-ip-ovn-k.adoc
  networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc
Labels: size/S, jira/invalid-bug, jira/valid-reference

#93031 [enterprise-4.19] OSDOCS13996: Remove cGroup v1 in OCP 4.19
  _topic_maps/_topic_map.yml
  architecture/index.adoc
  installing/install_config/enabling-cgroup-v1.adoc
  installing/installing_openstack/installing-openstack-nfv-preparing.adoc
  modules/architecture-about-cgroup-v2.adoc
  modules/cnf-tuning-nodes-for-low-latency-via-performanceprofile.adoc
  modules/nodes-clusters-cgroups-2-install.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/telco-core-application-workloads.adoc
  modules/telco-core-cpu-partitioning-and-performance-tuning.adoc
  modules/telco-ran-cluster-tuning.adoc
  networking/multiple_networks/primary_networks/about-user-defined-networks.adoc
  nodes/clusters/nodes-cluster-cgroups-2.adoc
  post_installation_configuration/cluster-tasks.adoc
  scalability_and_performance/telco-core-rds.adoc
  snippets/cgroupv2-vs-cgroupv1.adoc
  snippets/nodes-cgroup-vi-removed.adoc
Labels: size/L, branch/enterprise-4.19

#89395 OSDOCS#12768: Adding docs for OSSO 1.4.0
  nodes/scheduling/secondary_scheduler/index.adoc
  nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-configuring.adoc
  nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-release-notes.adoc
  nodes/scheduling/secondary_scheduler/nodes-secondary-scheduler-uninstalling.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.18, branch/enterprise-4.19

#86242 OSDOCS-12755 adding admonition to only use marketplace images for compute nodes
  modules/installation-aws-marketplace-subscribe.adoc
  modules/installation-azure-marketplace-subscribe.adoc
  modules/installation-configuration-parameters.adoc
  modules/installation-gcp-marketplace.adoc
  snippets/installation-marketplace-note.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92899 [enterprise-4.19] OSDOCS-14520: add RN entry
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.19

#93050 [enterprise-4.12] OSDOCS-12755 adding admonition to only use marketplace images for compute nodes
  modules/installation-aws-marketplace-subscribe.adoc
  modules/installation-azure-marketplace-subscribe.adoc
  modules/installation-gcp-marketplace.adoc
  snippets/installation-marketplace-note.adoc
Labels: size/M, branch/enterprise-4.12, branch/enterprise-4.13

#92992 OSDOCS#13548: Generating the CLI docs for OCP 4.19
  modules/oc-adm-by-example-content.adoc
  modules/oc-by-example-content.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.19

#92844 OSDOCS:14528 Docs for On Cluster Layering and a seamless SNO experience/Disconnected Support
  modules/coreos-layering-configuring-on.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.19

#92990 OSDOCS#13189: Bumping kube versions to 1.32 in example output
  metering/configuring_metering/metering-common-config-options.adoc
  modules/ai-adding-worker-nodes-to-cluster.adoc
  modules/aws-outposts-load-balancer-clb.adoc
  modules/cleaning-crio-storage.adoc
  modules/compliance-apply-remediation-for-customized-mcp.adoc
  modules/connected-to-disconnected-verify.adoc
  modules/coreos-layering-configuring-on-revert.adoc
  modules/coreos-layering-configuring.adoc
  modules/coreos-layering-removing.adoc
  modules/graceful-restart.adoc
  modules/hibernating-cluster-hibernate.adoc
  modules/hibernating-cluster-resume.adoc
  modules/ibi-create-standalone-config-iso.adoc
  modules/images-configuration-file.adoc
  modules/images-configuration-image-registry-settings-hcp.adoc
  modules/images-configuration-registry-mirror-configuring.adoc
  modules/infrastructure-moving-router.adoc
  modules/install-sno-monitoring-the-installation-manually.adoc
  modules/installation-approve-csrs.adoc
  modules/installation-aws-user-infra-bootstrap.adoc
  modules/installation-installing-bare-metal.adoc
  modules/installation-osp-creating-control-plane.adoc
  modules/installation-special-config-rtkernel.adoc
  modules/ipi-install-provisioning-the-bare-metal-node.adoc
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
  modules/ipi-install-troubleshooting-ntp-out-of-sync.adoc
  modules/ipi-install-troubleshooting-reviewing-the-installation.adoc
  modules/machine-node-custom-partition.adoc
  modules/microshift-custom-ca-proc.adoc
  modules/nodes-cluster-resource-override-move-infra.adoc
  modules/nodes-clusters-cgroups-2.adoc
  modules/nodes-nodes-kernel-arguments.adoc
  modules/nodes-nodes-rtkernel-arguments.adoc
  modules/nodes-nodes-viewing-listing.adoc
  modules/nodes-nodes-working-evacuating.adoc
  modules/nodes-scheduler-node-selectors-cluster.adoc
  modules/nodes-scheduler-node-selectors-pod.adoc
  modules/nodes-scheduler-node-selectors-project.adoc
  modules/nvidia-gpu-aws-adding-a-gpu-node.adoc
  modules/nvidia-gpu-azure-adding-a-gpu-node.adoc
  modules/nvidia-gpu-gcp-adding-a-gpu-node.adoc
  modules/nw-sriov-hwol-configuring-machine-config-pool.adoc
  modules/olm-catalogsource-image-template.adoc
  modules/querying-the-status-of-cluster-nodes-using-the-cli.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/rhcos-add-extensions.adoc
  modules/rhcos-enabling-multipath-day-2.adoc
  modules/rhel-compute-updating.adoc
  modules/sno-adding-worker-nodes-to-sno-clusters-manually.adoc
  modules/update-upgrading-cli.adoc
  modules/update-vsphere-virtual-hardware-on-compute-nodes.adoc
  modules/update-vsphere-virtual-hardware-on-control-plane-nodes.adoc
  updating/preparing_for_updates/updating-cluster-prepare-past-4-18.adoc
Labels: peer-review-done, lgtm, size/XL, branch/enterprise-4.19

#92840 OSDOCS:14527 Docs for automatic OCL image pruning
  machine_configuration/mco-coreos-layering.adoc
  modules/coreos-layering-configuring-on-remove.adoc
  modules/coreos-layering-configuring-on.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.19

#92775 OSDOCS-14377: updates greenboot wait time MicroShift
  modules/microshift-greenboot-health-check-command.adoc
  modules/microshift-greenboot-health-check-log.adoc
  modules/microshift-greenboot-microshift-health-script.adoc
Labels: peer-review-done, lgtm, size/XS, qe-approved, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#93066 handle subfolder for github pages
  _javascripts/page-loader.js
Labels: size/XS

#93069 CP-OSDOCS-14377-418: manual CP
  modules/microshift-greenboot-health-check-log.adoc
  modules/microshift-greenboot-microshift-health-script.adoc
Labels: size/XS, jira/valid-reference

#92419 OSDOCS#14382: adding nutanix platform to Agent docs
  modules/installation-configuration-parameters.adoc
  modules/understanding-agent-install.adoc
  nodes/nodes/nodes-nodes-adding-node-iso.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#92716 OSDOCS-14436:Release Note for 4.17.27
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.17

#93072 fix current version to allow for subdirectory in github actions
  _javascripts/page-loader.js
Labels: size/S

#92047 Update logging-loki-storage-azure.adoc
  modules/logging-loki-storage-azure.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.16

#92372 ocpbugs-45748: fixing outdated instruction
  modules/dr-restoring-cluster-state.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92839 Update distr-tracing-rn.adoc
  observability/distr_tracing/distr-tracing-rn.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92838 Update distr-tracing-tempo-object-storage-setup-ibm-storage.adoc
  modules/distr-tracing-tempo-object-storage-setup-ibm-storage.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92906 [enterprise-4.17] OBSDOCS-1634: missed prom-label-proxy version in 4.17 release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference

#92905 [enterprise-4.16] OBSDOCS-1634: missed prom-label-proxy version in 4.16 release notes
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference

#92988 logging-z-6.2.2 release notes
  modules/log6x-6-2-2-rn.adoc
  observability/logging/logging-6.2/log6x-release-notes-6.2.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#92851 RHDEVDOCS 6429 taskRunTemplate not supported in Trigger and EventListener
  modules/op-adding-triggers.adoc
Labels: peer-review-done, size/XS

#90790 PR for SRVLOGIC-524: Add the section to upgrade Serverless Logic Operator from 1.34.0 to 1.35.0
  _topic_maps/_topic_map.yml
  modules/serverless-logic-upgrade-backing-up-data-index-database.adoc
  modules/serverless-logic-upgrade-backing-up-job-service-database.adoc
  modules/serverless-logic-upgrade-deleting-migrating-workflows-with-preview-profile.adoc
  modules/serverless-logic-upgrade-deleting-workflows-with-dev-profile.adoc
  modules/serverless-logic-upgrade-finalizing-data-index.adoc
  modules/serverless-logic-upgrade-finalizing-job-service.adoc
  modules/serverless-logic-upgrade-redeploying-workflows-with-dev-profile.adoc
  modules/serverless-logic-upgrade-restoring-workflows-with-preview-profile.adoc
  modules/serverless-logic-upgrade-scaling-down-workflows-with-gitops-profile.adoc
  modules/serverless-logic-upgrade-scaling-up-workflows-with-gitops-profile.adoc
  modules/serverless-logic-upgrading-osl-operator.adoc
  modules/serverless-logic-verifying-the-1.35.0-upgrade.adoc
  serverless-logic/serverless-logic-managing-upgrades/_attributes
  serverless-logic/serverless-logic-managing-upgrades/images
  serverless-logic/serverless-logic-managing-upgrades/modules
  serverless-logic/serverless-logic-managing-upgrades/serverless-logic-upgrading-operator-from-1.34-to-1.35.adoc
  serverless-logic/serverless-logic-managing-upgrades/snippets
Labels: peer-review-done, size/L, serverless, merge-review-in-progress, jira/valid-reference

#89354 4.16 MIG-1690: Release Notes for MTC 1.7.19
  migration_toolkit_for_containers/release_notes/mtc-release-notes-1-7.adoc
  modules/migration-mtc-release-notes-1-7-19.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, MTC, jira/valid-reference

#93003 OBSDOCS-z-6.0.8
  modules/log6x-rn-6.0.8.adoc
  observability/logging/logging-6.0/log6x-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17

#92779 PR for SRVLOGIC-467: Enhance the "Configuring OpenAPI services" section with the correct references.
  modules/serverless-logic-openAPI-function-definition.adoc
  serverless-logic/serverless-logic-managing-services/serverless-logic-configuring-openAPI-services-endpoints.adoc
Labels: peer-review-done, size/XS, serverless, merge-review-in-progress, jira/valid-reference

#88371 TELCODOCS-2202 Provide guidance on installing and configuring the DPU OPERATOR
  _topic_maps/_topic_map.yml
  modules/nw-about-dpu.adoc
  modules/nw-dpu-configuring-operator.adoc
  modules/nw-dpu-creating-a-sfc.adoc
  modules/nw-dpu-installing-operator-cli.adoc
  modules/nw-dpu-installing-operator-ui.adoc
  modules/nw-dpu-operator-uninstall.adoc
  modules/nw-dpu-running-workloads.adoc
  networking/networking_operators/dpu-operator/_attributes
  networking/networking_operators/dpu-operator/about-dpu.adoc
  networking/networking_operators/dpu-operator/configuring-dpu-operator.adoc
  networking/networking_operators/dpu-operator/images
  networking/networking_operators/dpu-operator/installing-dpu-operator.adoc
  networking/networking_operators/dpu-operator/modules
  networking/networking_operators/dpu-operator/running-workload-on-dpu.adoc
  networking/networking_operators/dpu-operator/snippets
  networking/networking_operators/dpu-operator/uninstalling-dpu-operator.adoc
Labels: peer-review-done, size/XL, branch/enterprise-4.19

#92609 OSDOCS-13662: Adding ROSA & OSD Life Cycle entry for version 4.18
  modules/life-cycle-dates.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#93074 OCPBUGS-55738 numaresources-operator docs have a mistake in the mustg…
  modules/cnf-about-collecting-nro-data.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92424 TELCODOCS#2285: Updated docs for hardwareTuning field to be more accurate
  modules/ztp-recommended-cluster-kernel-config.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93145 4.13 MIG-1690: Release Notes for MTC 1.7.19
  migration_toolkit_for_containers/release_notes/mtc-release-notes-1-7.adoc
  modules/migration-mtc-release-notes-1-7-18.adoc
  modules/migration-mtc-release-notes-1-7-19.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, MTC, jira/valid-reference

#93121 Moving attribute includes earlier so they are actually used
  backup_and_restore/application_backup_and_restore/oadp-intro.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#92182 CNV#47262
  modules/virt-optimizing-clone-performance-at-scale-in-openshift-data-foundation.adoc
  virt/creating_vms_advanced/creating_vms_cli/virt-creating-vms-by-cloning-pvcs.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93148 OSDOCS-13801 remove Egress IP admonition for HCP
  networking/ovn_kubernetes_network_provider/configuring-egress-ips-ovn.adoc
Labels: peer-review-done, size/XS, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#91316 CNV-20188: Mass machine type change procedure
  modules/virt-updating-multiple-vms.adoc
  virt/managing_vms/virt-edit-vms.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#93087 OSDOCS-14549: ESO documentation structure
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  security/external_secrets_operator/_attributes
  security/external_secrets_operator/images
  security/external_secrets_operator/index.adoc
  security/external_secrets_operator/modules
  security/external_secrets_operator/snippets
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.19

#88931 CNV#52365: a few minor bugfixes from IBM Z team
  modules/virt-attaching-vm-secondary-network-cli.adoc
  modules/virt-enabling-disabling-downward-metrics-feature-gate-cli.adoc
Labels: peer-review-done, lgtm, size/XS, CNV, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#91830 OSDOCS#14009: Adding Openshift editions info
  _topic_maps/_topic_map.yml
  welcome/kubernetes-overview.adoc
  welcome/oke_about.adoc
  welcome/openshift-editions.adoc
Labels: peer-review-done, size/M

#92893 CNV#52870: Multi IOthread with fast storage
  modules/virt-configure-multiple-iothreads.adoc
  virt/managing_vms/virt-edit-vms.adoc
Labels: peer-review-done, size/M, merge-review-in-progress

#92940 OSDOCS-14545: Documented the 4.17.28 z-stream RNs
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#93182 OCPBUGS-51316-19: Added release version to RHCOS reference in 4.19 RN
  release_notes/ocp-4-19-release-notes.adoc
Labels: size/XS, jira/invalid-bug, jira/valid-reference, branch/enterprise-4.19

#92991 OSDOCS-14548_v1 created z-stream release notes
  release_notes/ocp-4-12-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, merge-review-in-progress

#90971 OSDOCS-12099#Add CLI cmd for PVC usage
  modules/storage-persistent-storage-pvc.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.19

#91810 OSDOCS-13791#adding RN text
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, qe-approved, merge-review-needed

#93063 OSDOCS#14546: Update the z-stream RNs for 4.18.12
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-needed

#92728 [RHACS] [Docs] ROX-28809: Updates to the Dev Hub integration documentation
  configuration/configuring-and-integrating-the-rhacs-plugin-with-red-hat-developer-hub.adoc
  modules/common-attributes.adoc
  modules/rebuilding-the-oci-artifact.adoc
  modules/viewing-security-information-in-red-hat-developer-hub.adoc
Labels: peer-review-done, size/M, RHACS, jira/valid-reference, rhacs-docs-4.7, rhacs-docs-4.8

#93070 OSDOCS-14547-1:Release Note for 4.15.50
  release_notes/ocp-4-15-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.15

#93166 [OSDOCS- 14613]Add warning to users about resources being consumed even if a cluster fails
  modules/create-wif-cluster-cli.adoc
  modules/create-wif-cluster-ocm.adoc
  modules/osd-create-cluster-ccs.adoc
  modules/osd-create-cluster-red-hat-account.adoc
Labels: peer-review-done, size/S, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#91362 OSDOCS-10269: Updating dev/fuse instructions
  modules/nodes-containers-dev-fuse-configuring.adoc
  nodes/containers/nodes-containers-dev-fuse.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93161 OLS-1742: Update doc for UI change
  images/fa-minus-circle.svg
  images/fa-plus-circle.png
  modules/ols-creating-lightspeed-custom-resource-file-using-web-console.adoc
  modules/ols-creating-the-credentials-secret-using-web-console.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference

#93012 HCIDOCS-249: Metal3 Support for Network Controller Sideband Interface (NC-SI)
  installing/installing_bare_metal/ipi/ipi-install-post-installation-configuration.adoc
  installing/installing_bare_metal/ipi/ipi-install-prerequisites.adoc
  modules/bmo-configuring-ncsi-disable-poweroff.adoc
  modules/ipi-install-nc-si-hardware-requirements-for-bare-metal.adoc
Labels: peer-review-done, size/L, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#93000 Fixing typo
  modules/graceful-restart.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#89935 [SRVKS-1306] Configuring long running requests
  knative-serving/config-applications/configuring-revision-timeouts.adoc
  modules/configuring-default-route-timeouts-globally.adoc
  modules/configuring-default-route-timeouts.adoc
  modules/serverless-long-running-requests.adoc
Labels: peer-review-done, size/L, serverless, merge-review-in-progress, merge-review-needed

#91195 OSDOCS#12040: RNs for 4.19 removed kube APIs and admin-ack
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.19

#93198 OSDOCS-14623: updates RHDE intro for localization
  _attributes/common-attributes.adoc
  modules/about-rhde.adoc
  overview/rhde-overview.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#93217 [enterprise-4.18] Fixing typo
  modules/graceful-restart.adoc
Labels: size/XS

#93218 [enterprise-4.17] Fixing typo
  modules/graceful-restart.adoc
Labels: size/XS

#93219 [enterprise-4.16] Fixing typo
  modules/graceful-restart.adoc
Labels: size/XS

#91221 PR for SRVLOGIC-438: Document "Configuring workflow services" section in the OSL docs.
  _topic_maps/_topic_map.yml
  modules/serverless-logic-defining-global-managed-properties.adoc
  modules/serverless-logic-modifying-managed-properties-workflow-services.adoc
  modules/serverless-logic-modifying-workflow-configuration.adoc
  serverless-logic/serverless-logic-configuring-workflow-services.adoc
Labels: peer-review-done, size/L, serverless, merge-review-in-progress, jira/valid-reference

#93109 OSDOCS-12030 adding missing view task permission to Nutanix doc
  modules/installation-nutanix-installer-infra-reqs.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93202 Updated RN GA: Externally managed certificate support for OpenShift routes
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, branch/enterprise-4.19

#93088 #CNV-57872-Change_boot_source_to_bootable_volume_in_windows_pipline
  modules/virt-creating-vm-instancetype.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.19

#93062 OLS-1621: Document cluster interaction feature
  configure/ols-configuring-openshift-lightspeed.adoc
  modules/ols-cluster-interaction-overview.adoc
  modules/ols-enabling-cluster-interaction.adoc
  modules/snippets
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, jira/valid-reference

#92860 TELCODOCS-2286 - Add Dynamic ASN to 4.17
  modules/nw-metallb-bgppeer-cr.adoc
  modules/nw-metallb-frr-k8s-configuration-crd.adoc
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.17

#92861 TELCODOCS-2286 - Add Dynamic ASN to 4.16
  modules/nw-metallb-bgppeer-cr.adoc
  modules/nw-metallb-frr-k8s-configuration-crd.adoc
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, size/S, telco, branch/enterprise-4.16

#93167 DOC: Explain how to opt-out of boot image update in 4.18
  modules/mco-update-boot-images-disable.adoc
Labels: peer-review-in-progress, peer-review-needed, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93143 TELCODOCS-2300: Clarifying network config limitations for IBI
  modules/ibi-create-standalone-config-iso.adoc
  modules/ibi-image-based-install-cluster-guide.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93168 OSDOCS-13197 add anchor tag to the resource responsibilities table
  modules/rosa-policy-change-management.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#93233 Updates UDN documentation to add limitations for web console creation
  modules/nw-cudn-cr-ui.adoc
  modules/nw-udn-cr-ui.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.18, branch/enterprise-4.19

#92553 CNV-60438: Correct misleading information about vTPM devices
  modules/virt-about-vtpm-devices.adoc
Labels: peer-review-done, size/S, CNV, merge-review-in-progress, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#93251 Jira:RHELDOCS-20134 NBDE Tang Server Operator 1.1.1 update
  security/nbde_tang_server_operator/nbde-tang-server-operator-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#92134 OSDOCS#14285: Removing unsupported KDO versions
  nodes/scheduling/descheduler/index.adoc
  nodes/scheduling/descheduler/nodes-descheduler-configuring.adoc
  nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc
  nodes/scheduling/descheduler/nodes-descheduler-uninstalling.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#93247 OBSDOCS-1393: Add links to Prometheus write_relabel_configs reference
  observability/monitoring/configuring-core-platform-monitoring/configuring-metrics.adoc
  observability/monitoring/configuring-user-workload-monitoring/configuring-metrics-uwm.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93241 Fix: DOC: Explain how to opt-out of boot image update in 4.18
  modules/mco-update-boot-images-disable.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93292 [RHACS] Set up RNs for 4.8
  _topic_maps/_topic_map.yml
  modules/common-attributes.adoc
  release_notes/47-release-notes.adoc
  release_notes/48-release-notes.adoc
Labels: size/XL

#93284 Remove TP note from Nodes Updated boot images module
  modules/mco-update-boot-images.adoc
  nodes/nodes/nodes-nodes-managing.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18, branch/enterprise-4.19

#90952 OSDOCS#12040: Adding admin-ack for updating from 4.18 to 4.19
  modules/update-preparing-ack.adoc
  modules/update-preparing-evaluate-apirequestcount-workloads.adoc
  modules/update-preparing-evaluate-apirequestcount.adoc
  modules/update-preparing-list.adoc
  modules/update-preparing-migrate.adoc
  updating/preparing_for_updates/updating-cluster-prepare.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.19

#93305 [rhacs-docs-4.8] Set up RNs for 4.8
  _topic_maps/_topic_map.yml
  modules/common-attributes.adoc
  release_notes/47-release-notes.adoc
  release_notes/48-release-notes.adoc
Labels: size/XL

#93244 OLS-1753: In cluster interaction task create verification section
  modules/ols-enabling-cluster-interaction.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#92780 OSDOCS#14516: Removed tech preview for support router load secrets
  modules/nw-ingress-route-secret-load-external-cert.adoc
  security/cert_manager_operator/cert-manager-securing-routes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed

#93313 Revert "[enterprise-4.16] Remove TP note from Nodes Updated boot images module"
  modules/mco-update-boot-images.adoc
  nodes/nodes/nodes-nodes-managing.adoc
Labels: size/S

#93238 OSDOCS-14655: use localqueue instead of queue to be more correct
  authentication/rbac-permissions.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#92567 HCIDOCS-699: Missing documentation for BMO configuration
  _topic_maps/_topic_map.yml
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/quorum-restoration.adoc
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  edge_computing/image_base_install/ibi_deploying_sno_clusters/ibi-edge-image-based-install.adoc
  installing/installing_bare_metal/bare-metal-expanding-the-cluster.adoc
  installing/installing_bare_metal/bare-metal-postinstallation-configuration.adoc
  installing/installing_bare_metal/ipi/ipi-install-expanding-the-cluster.adoc
  installing/installing_bare_metal/ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal/upi/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  installing/overview/cluster-capabilities.adoc
  installing/overview/index.adoc
  modules/ipi-install-replacing-a-bare-metal-control-plane-node.adoc
  modules/nw-enabling-a-provisioning-network-after-installation.adoc
  networking/networking_operators/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  post_installation_configuration/cluster-tasks.adoc
  scalability_and_performance/managing-bare-metal-hosts.adoc
Labels: peer-review-done, size/L, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#93059 [OSDOCS-12351]: Migrating etcd backup/restore docs to new etcd book
  _topic_maps/_topic_map.yml
  etcd/etcd-backup.adoc
  hosted_control_planes/hcp_high_availability/hcp-recovering-etcd-cluster.adoc
  modules/backup-etcd.adoc
  modules/creating-recurring-etcd-backups.adoc
  modules/creating-single-etcd-backup.adoc
  modules/dr-recover-expired-control-plane-certs.adoc
  modules/dr-restoring-cluster-state-about.adoc
  modules/dr-restoring-cluster-state-sno.adoc
  modules/dr-restoring-cluster-state.adoc
  modules/dr-restoring-etcd-quorum-ha.adoc
  modules/dr-scenario-cluster-state-issues.adoc
  modules/dr-testing-restore-procedures.adoc
  modules/manually-restoring-cluster-etcd-backup.adoc
  modules/restore-determine-state-etcd-member.adoc
  modules/restore-identify-unhealthy-etcd-member.adoc
  modules/restore-replace-crashlooping-etcd-member.adoc
  modules/restore-replace-stopped-baremetal-etcd-member.adoc
  modules/restore-replace-stopped-etcd-member.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19

#93330 No Jira: Fixing error caused by etcd-backup.adoc
  etcd/etcd-backup.adoc
Labels: size/XS, branch/enterprise-4.19

#93306 Fix typo in SPO section
  security/security_profiles_operator/spo-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.12, merge-review-in-progress, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19
