Repository openshift/openshift-docs, pull requests merged in 2025-06, with the labels that each got.

#94031 [enterprise-4.12] OBSDOCS-1629: Missing attribute fix for cherrry-pick
  _attributes/common-attributes.adoc
Labels: size/XS, branch/enterprise-4.12, jira/valid-reference

#94022 OBSDOCS-1629: Fix tick
  snippets/distr-tracing-tempo-tempostack-custom-resource.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#93663 OLS-1787: publish OLS 0.3.5 release notes
  release_notes/ols-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, jira/valid-reference

#94107 Manual cp2 94055 to 6.1
  _topic_maps/_topic_map.yml
  log_collection_forwarding/_attributes
  log_collection_forwarding/cluster-logging-collector.adoc
  log_collection_forwarding/cluster-logging-enabling-json-logging.adoc
  log_collection_forwarding/cluster-logging-eventrouter.adoc
  log_collection_forwarding/configuring-log-forwarding.adoc
  log_collection_forwarding/images
  log_collection_forwarding/log-forwarding.adoc
  log_collection_forwarding/logging-output-types.adoc
  log_collection_forwarding/modules
  log_collection_forwarding/snippets
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/logging-http-forward.adoc
Labels: size/L

#94108 Manual cp 94055 to 6.0
  _topic_maps/_topic_map.yml
  log_collection_forwarding/_attributes
  log_collection_forwarding/cluster-logging-collector.adoc
  log_collection_forwarding/cluster-logging-enabling-json-logging.adoc
  log_collection_forwarding/cluster-logging-eventrouter.adoc
  log_collection_forwarding/configuring-log-forwarding.adoc
  log_collection_forwarding/images
  log_collection_forwarding/log-forwarding.adoc
  log_collection_forwarding/logging-output-types.adoc
  log_collection_forwarding/modules
  log_collection_forwarding/snippets
  modules/cluster-logging-collector-log-forward-syslog.adoc
  modules/logging-http-forward.adoc
Labels: size/L

#94132 OBSDOCS-1972 Comment out all migrated content for now
  _topic_maps/_topic_map.yml
Labels: size/L

#93162 CNV#57866 4.19: autoResourceLimits documentation needs update
  modules/virt-about-cpu-and-memory-quota-namespace.adoc
  modules/virt-setting-resource-quota-limits-for-vms.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.19

#94037 WMCO remove snippet from ifdef
  modules/images-configuration-registry-mirror-configuring.adoc
  windows_containers/enabling-windows-container-workloads.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94160 OBSDOCS-1595: Fix
  observability/otel/otel-rn.adoc
Labels: peer-review-done, size/XS, merge-review-needed, jira/valid-reference

#93291 OSDOCS-14654:Added cluster installation errors to ROSA Classic Troubleshooting guide
  modules/rosa-troubleshooting-awsapiratelimitexceeded-failure-deployment.adoc
  modules/rosa-troubleshooting-awsec2quotaexceeded-failure-deployment.adoc
  modules/rosa-troubleshooting-awsinsufficientcapacity-failure-deployment.adoc
  modules/rosa-troubleshooting-awsinsufficientpermission-failure-deployment.adoc
  modules/rosa-troubleshooting-awsnatgatewaylimitexceeded-failure-deployment.adoc
  modules/rosa-troubleshooting-awssubnetnotexist-failure-deployment.adoc
  modules/rosa-troubleshooting-awsvpclimit-failure-deployment.adoc
  modules/rosa-troubleshooting-deleteiamrole-deployment.adoc
  modules/rosa-troubleshooting-general-deployment.adoc
  modules/rosa-troubleshooting-invalidinstallconfigsubnet-failure-deployment.adoc
  modules/rosa-troubleshooting-invalidkmskey-failure-deployment.adoc
  modules/rosa-troubleshooting-lblimitexceeded-failure-deployment.adoc
  modules/rosa-troubleshooting-multipleroute53zonesfound-failure-deployment.adoc
  modules/rosa-troubleshooting-osdccsadmin-deployment.adoc
  modules/rosa-troubleshooting-pendingverification-failure-deployment.adoc
  modules/rosa-troubleshooting-s3bucketslimitexceeded-failure-deployment.adoc
  modules/rosa-troubleshooting-toomanyroute53zones-failure-deployment.adoc
  support/troubleshooting/rosa-troubleshooting-deployments.adoc
Labels: peer-review-done, size/XL, merge-review-in-progress, jira/valid-reference

#93432 OSDOCS-13794#adding RN for VM Azure change
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94087 [OSDOCS-14631]: Add tag policy section to ROSA cluster installation requirements
  rosa_planning/rosa-cloud-expert-prereq-checklist.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#92024 OCPBUGS#54799: fixing parameter values for ABI disk encryption
  modules/installing-ocp-agent-encrypt.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93854 [OCPBUGS#56815] Install param description fix for ShiftStack
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#93501 [SRVKS-1303] haproxy.router.openshift.io/timeout config for auto-created routes
  knative-serving/external-ingress-routing/configuring-service-routes.adoc
  modules/configuring-default-route-timeouts-globally.adoc
  modules/serverless-openshift-routes.adoc
Labels: peer-review-done, size/M, serverless, merge-review-in-progress, merge-review-needed

#94217 [OCPBUGS#56815] Install param description fix for ShiftStack - manual CP
  modules/installation-configuration-parameters.adoc
Labels: size/S

#94213 [OCPBUGS#56815] Install param description fix for ShiftStack - manual CP
  modules/installation-configuration-parameters.adoc
Labels: size/S

#94215 [OCPBUGS#56815] Install param description fix for ShiftStack - manual CP
  modules/installation-configuration-parameters.adoc
Labels: size/S

#94065 OBSDOCS-1706: Monitoring 4.19 Update support version matrix
  modules/monitoring-support-version-matrix-for-monitoring-components.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.19

#94081 RHDEVDOCS-6468: Adding a missing module in GitOps 1.16
  argo_rollouts/using-argo-rollouts-for-progressive-deployment-delivery.adoc
  modules/gitops-enabling-argo-rollouts-ui-on-an-argo-cd-instance.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#93822 TELCODOCS-1874-missing-modules: Adding QE approved missing modules from upstream
  modules/telco-deviations-from-the-ref-design.adoc
  modules/telco-hub-software-stack.adoc
  modules/telco-ran-core-ref-design-spec.adoc
  scalability_and_performance/telco-hub-rds.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.18, branch/enterprise-4.19

#93076 MIG-1727: Attributes Updates for MTC 1.8.7
  _attributes/common-attributes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#94260 [enterprise-4.12]OCPBUGS-50926#Clarify SNO min requirements
  modules/install-sno-requirements-for-installing-on-a-single-node.adoc
Labels: size/S

#93111 OLS-1347: Document using TLSConfig in CRD
  configure/ols-configuring-openshift-lightspeed.adoc
  modules/ols-configuring-custom-tls-certificates.adoc
Labels: peer-review-done, size/M, jira/valid-reference

#94150 RHDEVDOCS-6469: Change management request for 1.18.1
  modules/op-release-notes-1-18.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#94014 OSDOCS-14790 created z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.17

#94193 [enterprise-4.19] add RHCOS RNs
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#93562 OSDOCS#14595: 4.19 TP [OLMv1] Specifying a deployment namespace
  extensions/ce/managing-ce.adoc
  modules/olmv1-installing-an-operator-in-a-specific-namespace.adoc
  modules/olmv1-installing-an-operator.adoc
  snippets/olmv1-tp-extension-support.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#93142 OCP 4.19 Release Notes for P/Z
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.19

#93637 #CNV-43159_how_to_detect
  modules/virt-deprecated-tasks-web.adoc
  virt/managing_vms/virt-managing-vms-openshift-pipelines.adoc
Labels: peer-review-done, lgtm, size/S, CNV, branch/enterprise-4.19

#94280 [OSDOCS-14539]: Release note for custom DNS on HCP
  _unused_topics/hosted-control-planes-release-notes.adoc
Labels: size/XS, branch/enterprise-4.19

#93714 OSDOCS#12096: Add the release note for the Observability service
  microshift_release_notes/microshift-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94282 [enterprise-4.18] Remove extra ID segment from one module
  modules/virt-configuring-downward-metrics.adoc
  virt/install/preparing-cluster-for-virt.adoc
Labels: size/XS

#94283 [enterprise-4.17] Remove extra ID segment from one module
  modules/virt-configuring-downward-metrics.adoc
Labels: size/XS

#94284 [enterprise-4.16] Remove extra ID segment from one module
  modules/virt-configuring-downward-metrics.adoc
Labels: size/XS

#93964 OCPBUGS#56008 known issue - Azure identity 'none' causes ACR pull failure
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS

#93586 OSDOCS-14551: Add Kueue user docs for running jobs
  _topic_maps/_topic_map.yml
  develop/_attributes
  develop/images
  develop/modules
  develop/running-kueue-jobs.adoc
  develop/snippets
  modules/defining-running-jobs.adoc
  modules/identifying-local-queues.adoc
  modules/running-jobs.adoc
  snippets/prereqs-snippet-yaml-user.adoc
Labels: peer-review-done, lgtm, size/L, jira/valid-reference

#93849 CNV-53423: RN - tech preview descheduler profile
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#94134 OSDOCS#14791:Update the z-stream RN for 4.18.16
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#94287 OSDOCS-14169-exclude:updates value
  modules/nw-udn-additional-config-details.adoc
  modules/support-matrix-for-udn-nad.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94300 Revert "OSDOCS-14603: assembly and module creation for ESO docs"
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  modules/external-secrets-about.adoc
  modules/external-secrets-enable-metrics.adoc
  modules/external-secrets-fips-support.adoc
  modules/external-secrets-operator-install-cli.adoc
  modules/external-secrets-operator-install-console.adoc
  modules/external-secrets-operator-uninstall-console.adoc
  modules/external-secrets-provider-types.adoc
  modules/external-secrets-query-metrics.adoc
  modules/external-secrets-remove-resources-cli.adoc
  modules/external-secrets-remove-resources.adoc
  security/external_secrets_operator/external-secrets-operator-install.adoc
  security/external_secrets_operator/external-secrets-operator-monitoring.adoc
  security/external_secrets_operator/external-secrets-operator-release-notes.adoc
  security/external_secrets_operator/external-secrets-operator-uninstall.adoc
  security/external_secrets_operator/index.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.19

#94303 Revert "OSDOCS-14549: ESO documentation structure"
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  security/external_secrets_operator/_attributes
  security/external_secrets_operator/images
  security/external_secrets_operator/index.adoc
  security/external_secrets_operator/modules
  security/external_secrets_operator/snippets
Labels: peer-review-done, size/S, jira/valid-reference

#93898 Move OADP configuring sections one level up
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/_attributes
  backup_and_restore/application_backup_and_restore/troubleshooting/backup-and-restore-cr-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/images
  backup_and_restore/application_backup_and_restore/troubleshooting/issues-with-velero-and-admission-webhooks.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/modules
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-installation-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-monitoring.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-operator-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/oadp-timeouts.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/pods-crash-or-restart-due-to-lack-of-memory-or-cpu.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/restic-issues.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/snippets
  backup_and_restore/application_backup_and_restore/troubleshooting/troubleshooting.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/using-the-must-gather-tool.adoc
  backup_and_restore/application_backup_and_restore/troubleshooting/velero-cli-tool.adoc
  backup_and_restore/index.adoc
Labels: peer-review-done, lgtm, size/L, merge-review-in-progress, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94263 OSDOCS-14170-rn: Documented the release note for OSDOCS-14170
  modules/virt-linux-bridge-nad-port-isolation.adoc
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94267 OSDOCS-14794: Documented the release note for OSDOCS-13333
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, jira/valid-reference, branch/enterprise-4.19

#94235 OCPBUGS-13539-18-remove-libreswan
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.18

#94237 OCPBUGS-13539-16-remove-libreswan
  release_notes/ocp-4-16-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.16

#94086 CNV-62830: Updated note about IPv6 single-stack support
  virt/install/preparing-cluster-for-virt.adoc
  virt/vm_networking/virt-networking-overview.adoc
Labels: peer-review-done, lgtm, size/S, CNV, jira/valid-reference, branch/enterprise-4.19

#94316 OADP-6202-4.13-CP
  _topic_maps/_topic_map.yml
Labels: size/M, merge-review-in-progress

#92606 Updated the docs to cover KeyCloak as an OIDC provider
  modules/rosa-hcp-sts-creating-a-cluster-external-auth-provider-cli.adoc
  modules/rosa-hcp-sts-example-external-auth-provider.adoc
  rosa_hcp/rosa-hcp-sts-creating-a-cluster-ext-auth.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.18, branch/enterprise-4.19

#94208 CNV#52389: Document spec.EnableApplicationAwareQuota
  modules/virt-enabling-aaq-operator.adoc
Labels: peer-review-done, lgtm, size/S, CNV, merge-review-in-progress, merge-review-needed, branch/enterprise-4.19

#93240 OSDOCS-14588: Updates to egress lockdown documentation
  _attributes/attributes-openshift-dedicated.adoc
  modules/rosa-hcp-create-network.adoc
  modules/rosa-hcp-set-environment-variables.adoc
  modules/rosa-hcp-sts-creating-a-cluster-egress-lockdown-cli.adoc
  modules/rosa-hcp-vpc-manual.adoc
  modules/rosa-hcp-vpc-terraform.adoc
  modules/rosa-operator-config.adoc
  rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
  rosa_planning/rosa-cloud-expert-prereq-checklist.adoc
Labels: peer-review-done, size/XL, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#94333 OLS-1785: cmd to set up TLS cert is missing namespace argument
  modules/ols-configuring-lightspeed-with-a-trust-provider-certificate-for-the-llm.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference

#93912 TELCODOCS-2308 O-RAN Compliant Events API: update spec to v04.00
  modules/cnf-about-ptp-events-using-ptp-event-producer-with-o-ran-api.adoc
  modules/cnf-about-ptp-fast-event-notifications-framework.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.19

#94035 TELCODOCS-2333 Event API v1: update examples for GET CurrentState
  modules/cnf-fast-event-notifications-api-reference.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.18

#93680 Removed Technology Preview in Insights Operator Runtime Extractor for 4.19 docs
  modules/insights-operator-what-information-is-collected.adoc
  modules/nodes-cluster-enabling-features-about.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, branch/enterprise-4.19

#91901 OCPBUGS#52836: sysType needs to be a property of controlPlane.platform.powervs and ompute.platform.powervs
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.19

#94361 OSDOCS-14533 Release note for vsphere multi data disk
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#93007 OSDOCS-14533 adding tech preview params for vsphere multi disk
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94309 Update 4.14 RAN RDS with Cluster Logging Operator 5.8
  modules/ztp-telco-ran-software-versions.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14

#93710 OSDOCS-13370-1:MicroShift 4.19 Release Note Ingress Controller Params
  microshift_release_notes/microshift-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#94395 OSDOCS-14866-416: manual CP
  modules/microshift-multus-intro.adoc
  modules/microshift-nw-multus-add-pod.adoc
Labels: size/M, jira/valid-reference

#94149 4.19 RN - TELCODOCS-2123 - PolicyGenerator GA
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed

#94407 adding bug fix text
  _unused_topics/hosted-control-planes-release-notes.adoc
Labels: size/M

#91567 TELCODOCS-2063#Add Removing old Cluster Logging Operator artifacts with PolicyGen/PGT
  edge_computing/policygenerator_for_ztp/ztp-talm-updating-managed-policies-pg.adoc
  edge_computing/policygentemplate_for_ztp/ztp-talm-updating-managed-policies.adoc
  modules/cnf-topology-aware-lifecycle-manager-cluster-logging-6x-update-policygenerator.adoc
  modules/cnf-topology-aware-lifecycle-manager-cluster-logging-6x-update-policygentemplate.adoc
  modules/telco-core-logging.adoc
  modules/telco-ran-logging.adoc
  scalability_and_performance/telco_ref_design_specs/core/telco-core-ref-design-components.adoc
  scalability_and_performance/telco_ref_design_specs/ran/telco-ran-ref-du-components.adoc
Labels: peer-review-done, size/L, merge-review-needed, branch/enterprise-4.17

#93632 CNV#58546: DOC: UI - Bulk Storage Class Migration within a single cluster
  _topic_maps/_topic_map.yml
  modules/virt-migrating-bulk-vms-different-storage-class-web.adoc
  virt/managing_vms/virt-migrating-vms-in-single-cluster-to-different-storage-class.adoc
Labels: peer-review-done, size/M, CNV, merge-review-needed, branch/enterprise-4.19

#94360 OSDOCS-14867 4.19 release note for extended loopback certificate
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-needed, branch/enterprise-4.19

#91003 TELCODOCS-2226: AI Distributed workloads with RDMA 1
  _topic_maps/_topic_map.yml
  hardware_accelerators/rdma-remote-direct-memory-access.adoc
  modules/rdma-configuring-the-gpu-operator.adoc
  modules/rdma-configuring-the-nfd-operator.adoc
  modules/rdma-configuring-the-nmstate-operator.adoc
  modules/rdma-configuring-the-nvidia-network-operator.adoc
  modules/rdma-configuring-the-sriov-operator.adoc
  modules/rdma-creating-a-service-user.adoc
  modules/rdma-creating-persistent-naming-rules.adoc
  modules/rdma-disabling-irdma-kernel-module.adoc
  modules/rdma-prerequisites.adoc
Labels: peer-review-done, size/XXL, telco, merge-review-needed, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#94133 MCO change on-cluster layering to image mode for OpenShift
  _attributes/common-attributes.adoc
  _topic_maps/_topic_map.yml
  machine_configuration/mco-coreos-layering.adoc
  modules/coreos-layering-configuring-on-extensions.adoc
  modules/coreos-layering-configuring-on-modifying.adoc
  modules/coreos-layering-configuring-on-proc.adoc
  modules/coreos-layering-configuring-on-rebuild.adoc
  modules/coreos-layering-configuring-on-revert.adoc
  modules/coreos-layering-configuring-on.adoc
  modules/coreos-layering-configuring.adoc
  modules/coreos-layering-updating.adoc
  rosa_architecture/index.adoc
  welcome/learn_more_about_openshift.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94321 OBSDOCS-1716: monitoring - sync with eng reference file
  modules/monitoring-resources-reference-for-the-cluster-monitoring-operator.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.19

#94406 updates link to resolve 404
  networking/ovn_kubernetes_network_provider/ovn-kubernetes-tracing-using-ovntrace.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#85302 OSDOCS-12422#VolumeAttributesClass TP
  modules/storage-persistent-storage-pvc-volumeattributesclass.adoc
  storage/understanding-persistent-storage.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19

#94398 Removes erroneous consideration from limited live migration
  modules/nw-ovn-kubernetes-live-migration-about.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.15, branch/enterprise-4.16

#94447 [enterprise-4.17] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-host-vrf.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M, branch/enterprise-4.17

#94448 [enterprise-4.16] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-host-vrf.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M, branch/enterprise-4.16

#94449 [enterprise-4.15] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-host-vrf.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M, branch/enterprise-4.15

#94454 [enterprise-4.13] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M, branch/enterprise-4.13

#93116 OSDOCS-13187:Manually setting the MTU value
  modules/microshift-nw-topology.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#92669 Configuring backupPVC and restorePVC
  _topic_maps/_topic_map.yml
  backup_and_restore/application_backup_and_restore/installing/configuring-backup-restore-pvc-datamover.adoc
  modules/oadp-configuring-backup-pvc-datamover-backup.adoc
  modules/oadp-configuring-restore-pvc-datamover-restore.adoc
Labels: peer-review-done, size/L, merge-review-needed, OADP, branch/enterprise-4.19

#94347 OCPBUGS#56526 updating install encryption proc to use XTS only
  modules/installation-special-config-storage.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.18, branch/enterprise-4.19

#94286 OLS-1757: mention tool calling for cluster interaction
  modules/ols-cluster-interaction-overview.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference

#94400 Removes bare metal consideration that should not be under public clou…
  modules/nw-egress-ips-about.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94278 OSDOCS-14620 adding confidential compute GCP parameters
  modules/installation-configuration-parameters.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94456 [enterprise-4.12] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/S

#94452 [enterprise-4.14] OSDOCS-8677-OVNK: Applied revised changes to the K8S NMstate docs
  modules/node-network-configuration-policy-file.adoc
  modules/virt-creating-interface-on-nodes.adoc
  modules/virt-example-host-vrf.adoc
  modules/virt-example-nmstate-IP-management.adoc
  modules/virt-nmstate-example-policy-configurations.adoc
  networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.adoc
Labels: size/M, branch/enterprise-4.14

#94269 OSDOCS-14837: Documented the release note for OSDOCS-12848
  modules/k8s-nmstate-troubleshooting-dns-disconnected-env-resolv.adoc
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.19

#94094 OSDOCS-14814: GA Azure confidential computing via MAPI
  modules/machineset-azure-confidential-vms.adoc
  modules/machineset-azure-trusted-launch.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.19

#94291 OSDOCS-14522: Cluster API base YAML updates
  _attributes/common-attributes.adoc
  modules/capi-creating-machine-template.adoc
  modules/capi-modifying-machine-template.adoc
  modules/cluster-capi-operator.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference, branch/enterprise-4.19

#92358 MCO & Node 4.19 Release Notes
  _attributes/common-attributes.adoc
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94165 4.19 RN - TELCODOCS-2107 - replacement of events REST API v1 with v2
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, merge-review-in-progress, branch/enterprise-4.19

#94167 OSDOCS#12643: Release notes for direct auth
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.19

#93738 Add secret file format for object storage
  modules/oadp-creating-default-secret.adoc
Labels: peer-review-done, size/M, OADP, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94294 OLS-1664: Mention FIPS support in OLS product docs
  about/ols-about-openshift-lightspeed.adoc
  modules/ols-openshift-lightspeed-fips-support.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference

#94005 #CNV-59097- Additional multi-VM operations
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#93679 Added Insights Runtime Extractor feature GA to 4.19 release notes
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94446 TELCODOCS-2342: Fixes for hub cluster 4.18 and later
  modules/telco-hub-architecture-overview.adoc
  modules/telco-hub-hub-cluster-openshift-deployment.adoc
  modules/telco-hub-managed-cluster-updates-and-upgrades.adoc
  modules/telco-hub-resource-utilization.adoc
  scalability_and_performance/telco-hub-rds.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.18, branch/enterprise-4.19

#94492 OSDOCS#14859: Update the z-stream RN for 4.18.17
  release_notes/ocp-4-18-release-notes.adoc
Labels: peer-review-done, lgtm, size/S

#93884 [OSDOCS-14778]: Adding RN to announce new etcd book
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#94523 [OSDOCS-12313]: Editing etcd topic map
  _topic_maps/_topic_map.yml
Labels: peer-review-done, lgtm, size/XS, branch/enterprise-4.19

#94525 [OSDOCS-14912]: Adding etcd encryption content to the new etcd book
  _topic_maps/_topic_map.yml
  etcd/etcd-encrypt.adoc
  hosted_control_planes/index.adoc
  installing/overview/installing-fips.adoc
  modules/about-etcd-encryption.adoc
  modules/disabling-etcd-encryption.adoc
  modules/enabling-etcd-encryption.adoc
  modules/etcd-encryption-types.adoc
  security/encrypting-etcd.adoc
  security/index.adoc
Labels: peer-review-done, lgtm, size/M, branch/enterprise-4.19

#94207 MCO add info on upgrade ack for updated boot images
  modules/mco-update-boot-images-disable.adoc
Labels: peer-review-done, size/S, do-not-merge, branch/enterprise-4.18

#94399 OSDOCS-13532: Add small explainer about the need for ECR
  rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
Labels: lgtm, size/XS, jira/valid-reference

#94340 OSDOCS-14855: adds microshift-bootc image access to async relnotes
  microshift_release_notes/microshift-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#94352 OSDOCS-14865 4.19 ServiceAccountTokenNodeBinding release note
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS

#94366 OLS-1628: Remove TP language from OLS docs
  about/ols-about-openshift-lightspeed.adoc
  modules/ols-about-data-use.adoc
  modules/ols-large-language-model-requirements.adoc
  modules/ols-openshift-requirements.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#94493 TELCODOCS-2184: Known issue RNs 4.19 - Telco Core
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#94468 TELCODOCS-2284: Updates for 4.19 hub cluster with GA support
  modules/telco-hub-gitops-operator-and-ztp-plugins.adoc
  modules/telco-hub-scaling-targets.adoc
  modules/telco-hub-software-stack.adoc
  scalability_and_performance/telco-hub-rds.adoc
Labels: peer-review-done, size/S, jira/valid-reference

#93638 CNV-56003: Add a release note for draggable VMs in the tree view
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#93518 [enterpise-4.17] MULTIARCH#5446: Release notes for MTO 1.1.z
  post_installation_configuration/configuring-multi-arch-compute-machines/multi-arch-tuning-operator-release-notes.adoc
Labels: size/S, merge-review-in-progress, branch/enterprise-4.17

#93519 [enterprsie-4.18] MULTIARCH#5446: Release notes for MTO 1.1.z
  post_installation_configuration/configuring-multi-arch-compute-machines/multi-arch-tuning-operator-release-notes.adoc
Labels: size/S, merge-review-in-progress, merge-review-needed, branch/enterprise-4.18

#94576 OSDOCS-13727.1:Corrected link to point directly to ROSA specific OCM doc
  rosa_release_notes/rosa-release-notes.adoc
Labels: peer-review-done, lgtm, size/XS, SD-docs, branch/enterprise-4.18, branch/enterprise-4.19

#94422 OBSDOCS-1715: Sync of the monitoring config map API reference file
  observability/monitoring/config-map-reference-for-the-cluster-monitoring-operator.adoc
Labels: peer-review-done, lgtm, size/XS, jira/valid-reference, branch/enterprise-4.19

#94505 OSDOCS-14604: Add RN for OCPSTRAT-1577
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.19

#94369 OSDOCS-14857: Documented the 4.17.33 z-stream release notes
  release_notes/ocp-4-17-release-notes.adoc
Labels: peer-review-done, size/S, jira/valid-reference, branch/enterprise-4.17

#94206 OSDOCS-13556 4.19 update to TechPreviewNoUpgrade
  modules/nodes-cluster-enabling-features-about.adoc
Labels: peer-review-done, lgtm, size/L, branch/enterprise-4.19

#94602 [94566] Added patch release notes for 4.7.4
  modules/common-attributes.adoc
  release_notes/47-release-notes.adoc
Labels: size/S, rhacs-docs-4.7

#94612 [enterprise-4.18] Updating a bunch of typos
  disconnected/mirroring/about-installing-oc-mirror-v2.adoc
  edge_computing/day_2_core_cnf_clusters/telco-day-2-welcome.adoc
  migration_toolkit_for_containers/mtc-migrating-vms.adoc
  modules/backing-up-the-backend-redis-database.adoc
  modules/compliance-priorityclass.adoc
  modules/dr-restoring-etcd-quorum-ha.adoc
  modules/microshift-auto-recovery-example-bootc-systems.adoc
  modules/migration-mtc-release-notes-1-8-6.adoc
  modules/nodes-pods-vertical-autoscaler-tuning.adoc
  modules/nw-cudn-best-practices.adoc
  modules/nw-understanding-networking-features.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/oc-mirror-command-reference-v2-delete.adoc
  modules/persistent-storage-csi-gcp-hyperdisk-storage-pools-procedure.adoc
  modules/restoring-the-backend-redis-database.adoc
  modules/restoring-the-mysql-database.adoc
  modules/scaling-up-the-3scale-api-management-operator-and-deployment.adoc
  modules/virt-restoring-vm-from-snapshot-web.adoc
  modules/ztp-configuring-the-hub-cluster-for-backup-and-restore.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
  post_installation_configuration/configuring-multi-arch-compute-machines/multiarch-tuning-operator.adoc
Labels: size/L

#94615 [enterprise-4.15] Updating a bunch of typos
  migration_toolkit_for_containers/mtc-migrating-vms.adoc
  modules/backing-up-the-backend-redis-database.adoc
  modules/compliance-priorityclass.adoc
  modules/migration-mtc-release-notes-1-8-6.adoc
  modules/nodes-pods-vertical-autoscaler-tuning.adoc
  modules/oadp-usecase-backup-odf.adoc
  modules/restoring-the-backend-redis-database.adoc
  modules/restoring-the-mysql-database.adoc
  modules/scaling-up-the-3scale-api-management-operator-and-deployment.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: size/L

#94617 [enterprise-4.12] Updating a bunch of typos
  modules/compliance-priorityclass.adoc
  observability/network_observability/network-observability-operator-release-notes.adoc
Labels: size/XS

#94298 OSDOCS#13470:Update the About-this-release page for 4.19
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, merge-review-in-progress, branch/enterprise-4.19

#89952 OCPBUGS-37089#adding Important text
  installing/installing_aws/upi/installing-aws-user-infra.adoc
  installing/installing_aws/upi/installing-restricted-networks-aws.adoc
  modules/installation-aws-creating-cloudformation-stack-compute.adoc
  modules/installation-cloudformation-worker.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94349 OSDOCS-12697+13803# RNs for AWS Malaysia and Thailand support
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94479 CNV-58547_2: Release Notes: UI - Bulk Storage Class Migration within a single cluster
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, CNV

#94504 release notes for 4.6.7 patch
  modules/common-attributes.adoc
  release_notes/46-release-notes.adoc
Labels: peer-review-done, size/S, RHACS, rhacs-docs-4.6

#94126 OSDOCS#14821: Updates to dynamic plugin sdk docs
  modules/dynamic-plugin-api.adoc
  modules/dynamic-plugin-sdk-extensions.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19

#94271 OSDOCS-14822 UDN NetObserv Content
  modules/network-observability-con_user-defined-networks.adoc
  modules/network-observability-proc_working-with-udn.adoc
  observability/network_observability/observing-network-traffic.adoc
Labels: peer-review-done, size/M, qe-approved, merge-review-in-progress

#94595 Zero Egress: Clarifies the which channel is mirrored.
  rosa_hcp/rosa-hcp-egress-lockdown-install.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.18, branch/enterprise-4.19

#94607 Batches 4.19 Cloud Compute bugs
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/L, branch/enterprise-4.19

#94408 OSDOCS#14594: OLMv1 RBAC preflight check (TP)
  extensions/ce/managing-ce.adoc
  modules/olmv1-troubleshooting-rbac-errors-with-preflight-check.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94510 OBSDOCS-1916: Logging Z-Stream Release Notes - 5.9.15
  modules/logging-release-notes-5-9-15.adoc
  observability/logging/logging_release_notes/logging-5-9-release-notes.adoc
Labels: peer-review-done, size/S, merge-review-in-progress, jira/valid-reference

#93733 OBSDOCS-1919: Logging Z-Stream Release Notes - 6.2.3
  modules/log6x-6-2-3-rn.adoc
  observability/logging/logging-6.2/log6x-release-notes-6.2.adoc
Labels: peer-review-done, size/M, merge-review-in-progress, jira/valid-reference

#94605 OSDOCS-13634-im-16: Enhancements to creating-manifest-file-customize …
  backup_and_restore/control_plane_backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc
  installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
  installing/installing_bare_metal/installing-bare-metal.adoc
  installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
  installing/installing_bare_metal/scaling-a-user-provisioned-cluster-with-the-bare-metal-operator.adoc
  installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
  installing/installing_bare_metal_ipi/ipi-install-post-installation-configuration.adoc
  modules/creating-manifest-file-customized-br-ex-bridge.adoc
  networking/networking_operators/k8s-nmstate-about-the-k8s-nmstate-operator.adoc
  post_installation_configuration/cluster-tasks.adoc
  post_installation_configuration/post-install-bare-metal-configuration.adoc
Labels: size/M, jira/valid-reference, branch/enterprise-4.16

#94495 OBSDOCS-1979 known issues with logging UI plugin
  modules/coo-logging-ui-plugin-install.adoc
  observability/cluster_observability_operator/ui_plugins/logging-ui-plugin.adoc
Labels: size/S

#94556 OSDOCS-14920-RN Updating confidential VMs GCP RN to include day 2
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.19

#94312 [CNV-56434] Watchdog add support for IBM Z
  modules/virt-defining-watchdog-device-vm.adoc
  modules/virt-installing-watchdog-agent.adoc
Labels: peer-review-done, lgtm, size/S, branch/enterprise-4.19

#94163 Monitoring 4.19 Release Notes
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#94508 OBSDOCS-1920: Logging Z-Stream Release Notes - 5.8.21
  modules/logging-release-notes-5-8-21.adoc
  observability/logging/logging_release_notes/logging-5-8-release-notes.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.12, jira/valid-reference, branch/enterprise-4.13, branch/enterprise-4.14, branch/enterprise-4.15

#94596 MULTIARCH#5446: Release notes for MTO 1.1.1
  post_installation_configuration/configuring-multi-arch-compute-machines/multi-arch-tuning-operator-release-notes.adoc
Labels: size/S, branch/enterprise-4.19

#94592 [enterprise-4.16] OCPBUGS-46045 Symmetric routing with MetalLB improvements + missing rule
  modules/nw-egress-service-cr.adoc
  modules/nw-egress-service-ovn.adoc
  modules/nw-metallb-configure-return-traffic-proc.adoc
Labels: lgtm, size/S, merge-review-in-progress, branch/enterprise-4.16

#94597 TELCODOCS-2248 4.19 RAN RDS - cleanup
  modules/telco-ran-crs-day-2-operators.adoc
  modules/telco-ran-ptp-operator.adoc
  scalability_and_performance/telco-ran-du-rds.adoc
Labels: peer-review-done, size/S, branch/enterprise-4.19

#94451 OSDOCS#13488: OLMv1 4.19 release notes
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/M, branch/enterprise-4.19

#91500 OLS-1622: Document token quota feature
  configure/ols-configuring-openshift-lightspeed.adoc
  modules/ols-activating-token-quota-limits.adoc
  modules/ols-tokens-and-token-quota-limits.adoc
Labels: peer-review-done, lgtm, size/M, jira/valid-reference

#93110 Agent 4.19 release notes
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94420 CNV#61769: fixing identical RN in 4.18
  virt/release_notes/virt-4-18-release-notes.adoc
Labels: peer-review-done, size/XS, CNV, branch/enterprise-4.18

#94688 OLS-1845: Remove BYOK content from OLS docs
  configure/ols-configuring-openshift-lightspeed.adoc
Labels: peer-review-done, size/XS, jira/valid-reference

#94156 CNV-58007: RHEL 10 guest OS for 4.19 RN
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#94063 CNV-54610: Updating multiple VMs for 4.19 RN
  virt/release_notes/virt-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, merge-review-in-progress, merge-review-needed, jira/valid-reference, branch/enterprise-4.19

#94693 OCPBUGS-37089_2#style change
  modules/installation-aws-creating-cloudformation-stack-compute.adoc
Labels: peer-review-done, lgtm, branch/enterprise-4.16, branch/enterprise-4.17, branch/enterprise-4.18, branch/enterprise-4.19

#94631 OSDOCS-14788 known issue with AWS credentials
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, branch/enterprise-4.19

#94606 OSDOCS-14925: Documented the slb mode release note
  release_notes/ocp-4-19-release-notes.adoc
Labels: peer-review-done, size/XS, jira/valid-reference, branch/enterprise-4.19
